### ISSUE TITLE
VMware fetches DHCP address, even when DHCP is disabled

### ISSUE THREAD

**Issue by normelton** [coreos/bugs#1000]
I'm configuring a vmware node, following https://coreos.com/os/docs/latest/booting-on-vmware.html. I've got the following parameters set:

```
guestinfo.interface.0.dhcp  no
guestinfo.interface.0.role  public
guestinfo.interface.0.ip.0.address  10.1.25.10/16
guestinfo.interface.0.route.0.gateway 10.1.0.1
guestinfo.interface.0.route.0.destination 0.0.0.0/0
guestinfo.dns.server.0  128.239.20.9
guestinfo.dns.server.1  128.239.29.9
guestinfo.coreos.config.data.encoding base64
guestinfo.coreos.config.data <my config file>
```

The static IP is applied, but my node still fetches a DHCP address:

```
$ ip addr show dev ens192
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:be:16:4c brd ff:ff:ff:ff:ff:ff
    inet 10.1.253.234/16 brd 10.1.255.255 scope global dynamic ens192
       valid_lft 3352sec preferred_lft 3352sec
    inet 10.1.25.10/16 brd 10.1.255.255 scope global secondary ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:febe:164c/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by kayrus** [comment]
It is default behavior. Please refer to this doc for details: https://coreos.com/os/docs/latest/network-config-with-networkd.html#networkd-and-dhcp-behavior

**Comment by crawford** [comment]
First of all, congrats on filing the 1000th issue.

The DHCP address is still present because coreos-cloudinit runs too late in the boot process to configure networking. Once Ignition is supported in our VMware images, this problem will go away. Until then, you can use `ip addr del` to remove dynamic addresses.

**Comment by normelton** [comment]
Okay. I guess I just figured that by specifically configuring "dhcp = no", cloudinit would take care of it for me :). No problem, thanks.

**Comment by normelton** [comment]
If anyone stumbles on this down the road, CoreOS behaves as expected if you specify your interface name. That is, I had to add:

```
guestinfo.interface.0.name  ens192
```

Now, there's no more DHCP address. Also, the specified static gets applied only to ens192, not to both ens192 and the loopback interface. This causes all sorts of problems. Don't do that.

Norman
