### ISSUE TITLE
coreos 835.7.0 machinectl login  <container> closes connection to the coreos host

### ISSUE THREAD

**Issue by f0** [coreos/bugs#1002]
hw1907 ~ # machinectl login graylog
Connected to machine graylog Press ^] three times within 1s to exit session.
Connection to hw1907 closed.
fk@linux-3zvu:~> 

```
hw1907 ~ # cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=835.7.0
VERSION_ID=835.7.0
BUILD_ID=
PRETTY_NAME="CoreOS 835.7.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by crawford** [comment]
Thanks for the report. `machinectl login` is a fairly new mechanism that we really haven't had time to look at. Your best bet right now is to use a different mechanism, like `nsenter.

**Comment by f0** [comment]
@crawford  i think you mix up machinectl login and machinectl **shell**
machinectl ligin works well in previous versions

**Comment by crawford** [comment]
@f0 yeah, you're right. Can you tell me how you are starting the graylog container?

**Comment by f0** [comment]
hw1907 ~ # systemctl status -ll  systemd-nspawn@graylog.example.net                                                                                            
● systemd-nspawn@graylog.mgmt.dvag.net.service - Container graylog.example.net
   Loaded: loaded (/etc/systemd/system/systemd-nspawn@.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/systemd-nspawn@graylog.example.net.service.d
           └─50-CPUQuota.conf, 50-MemoryLimit.conf
   Active: active (running) since Sat 2015-11-28 13:29:14 CET; 3 days ago                                                                                                      $
     Docs: man:systemd-nspawn(1)
 Main PID: 1326 (systemd-nspawn)
   Status: "Container running."
   CGroup: /machine.slice/systemd-nspawn@graylog.example.net.service
           ├─1326 /usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-macvlan=vlan1112 --machine=graylog.example.net
           ├─1338 /usr/lib/systemd/systemd
           └─system.slice
             ├─dbus.service
             │ └─1376 /bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation

**Comment by jonboulle** [comment]
Is this distinct from #863?

**Comment by f0** [comment]
@crawford  hm at the moment if i try this again i am not able to reproduce the problem, in the meantime the ost was restarted.

**Comment by crawford** [comment]
I was able to reproduce this by:

 1. open two SSH connections to a machine
 2. in the first, run `sudo systemd-nspawn --image coreos_developer_container.bin`
 3. in the second, run `sudo machinectl login coreos_developer_container.bin`.

The first connection is terminated and the `machinectl login` says that it is connected. I have to `^]` three times to exit the session.

**Comment by crawford** [comment]
If I use `sudo systemd-run systemd-nspawn --image ~core/coreos_developer_container.bin --boot` instead in step 2, the behavior is the same.

If I close the SSH connection after running the modified step 2, `machinectl login` fails with:

```
Failed to get login PTY: No such file or directory
```

**Comment by crawford** [comment]
After backporting https://github.com/systemd/systemd/commit/5f430ff76e8e5f7ca5b7ef67dd3b205487a0f41b, I am no longer able to reproduce this failure. I'm still not able to `machinectl login` to the container though (I have not actually seen this work yet).

**Comment by crawford** [comment]
I was able to make this work in 766.5.0 with the toolbox container. It looks like https://github.com/systemd/systemd/commit/5f430ff76e8e5f7ca5b7ef67dd3b205487a0f41b alone is not sufficient.

**Comment by f0** [comment]
@crawford  with your described steps, i can reproduce this.

on a 766.4.0 system it does work

**Comment by f0** [comment]
@crawford @jonboulle   hm why you guys release a "stable" version with a borken machinectl login? 
It works before , now i can not update because of the broken machinectl login...

**Comment by crawford** [comment]
@f0 `machinectl login` is a seldom used feature of systemd, so it slipped under the radar. This has been broken for almost three months now and this is the first we are hearing of it. It would be helpful to us if you ran some Beta (and even Alpha) machines in your cluster to alert us to these problems earlier.

**Comment by f0** [comment]
@crawford  hm seldom used? we run systemd-nspawn containers, and its part from the normal workflow to use machinectl login, its not a third party tool..... its a main systemd tool.
I run a beta system in the cluster, thats the reason why i reported the problem
i only wonder why a "stable" release was done with a known regression

**Comment by crawford** [comment]
We chose to continue with the Stable release because if we waited for there to be absolutely no bugs, we would never ship anything. I determined this issue to be a fairly risky fix, fairly involved, and a low impact; the combination of which made it acceptable, in my eyes, to move forward with the release.

**Comment by f0** [comment]
@crawford  hm in my definition a "bug" and a "regression" are 2 different things.... zero bugs releases are not possible, i know that, but things that worked before should work also after anew release, especially if the problem was known. 

But i understand that there are different views at this, so lets move on and let us fix the problem

**Comment by crawford** [comment]
Bisecting reveals that this was broken by https://github.com/coreos/systemd/commit/154429127cb400bf010d41d7dd3ba4ec41b9ffb3.

**Comment by f0** [comment]
@crawford  thx
