### ISSUE TITLE
Coreos boot-kernel does not work on Intel nuc

### ISSUE THREAD

**Issue by sudsy** [coreos/bugs#1007]
This issue is very similar to Coreos boot-kernel issue #179 but I can see that there was a patch that resolved that issue.

I can boot to Core A or Core B fine but when trying to boot from boot-kernel, the machine crashes.

Taking the lead from the previous issue, the output from udevadm info --export-db is 
https://gist.github.com/sudsy/65e1480fd76e399ef8dc

Output from lspci -vv
 https://gist.github.com/sudsy/4d09f6f09c64c72ab8de

Not sure how else to debug this. Nothing I could see from dmesg

**Comment by crawford** [comment]
Which version of CoreOS is this?

**Comment by sudsy** [comment]
This machine has been offline for a while and so it is back at 766.5.0. 

Discovered the issue while trying to update.

**Comment by crawford** [comment]
It sounds like this machine is using Syslinux as its bootloader (which means this machine is very old). The best bet is going to be to reprovision the machine (if possible) so it picks up our newer boot process (which uses GRUB instead of Syslinux + kexec).

**Comment by sudsy** [comment]
OK, Will do. It will have to wait till the new year though. It's running something important for the XMAS Season. I have shut down the update client to avoid accidental boot failures for the time being.
