### ISSUE TITLE
failed to start a new CoreOS cluster with 5 nodes

### ISSUE THREAD

**Issue by bchanan03** [coreos/bugs#1008]
Hi,
I tried to start using vagrant a new CoreOS cluster with minimum of 5 nodes 
using the Alpha image - it failed to start the cluster.
It did create a cluster using minimum of 3 nodes.

NAME=CoreOS
ID=coreos
VERSION=877.1.0
VERSION_ID=877.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 877.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**Comment by robszumski** [comment]
Need a lot more info. Can you share what steps you took to create the cluster?

 - what provider?
 - share your cloud-config
 - how did you bootstrap etcd?
 - are you using fleet? or kubernetes?

What is different for the 5 node vs the 3?

**Comment by bchanan03** [comment]
reference: https://github.com/coreos/bugs/issues/936
My colleague Ofer Kessler (ofekes01) has added the logs for me under github

**Comment by robszumski** [comment]
Closing in favor of #936
