### ISSUE TITLE
Shutdown issues in CoreOS 835.8.0

### ISSUE THREAD

**Issue by huguesb** [coreos/bugs#1009]
Shutdown issues in systemd-225, fixed upstream and patched in some distros. Especially problematic for remote shutdown from scripts.

See:
https://github.com/systemd/systemd/issues/1120
https://bbs.archlinux.org/viewtopic.php?id=202018

**Comment by crawford** [comment]
As a workaround, you can use `systemd-run` to schedule a shutdown in the future.

**Comment by huguesb** [comment]
Our use case is an immediate shutdown. Adding an arbitrary delay would be pretty annoying but I'll give it a shot if it's the only workaround.

**Comment by crawford** [comment]
The upstream bug to which you linked results in an immediate shutdown. Is `shutdown` not working at all?

**Comment by huguesb** [comment]
@crawford If you look at the archlinux forum post, you'll see the exact issue we're facing: immediate shutdown over ssh result in improper termination of the connection with the following message:

```Failed to set wall message, ignoring: Message did not receive a reply (timeout by message bus)
Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown: Message did not receive a reply (timeout by message bus)```

Crucially, the ssh exit code is 255 so our script aborts. The VM shuts down but we don't have a good way of distinguishing between legitimate problem and this bug.

**Comment by crawford** [comment]
Gotcha. `systemd-run shutdown` should do the trick for now.

```
$ ssh core@ec2-52-11-47-66.us-west-2.compute.amazonaws.com sudo systemd-run shutdown
Running as unit run-679.service.
$ echo $?
0
```

**Comment by pbx0** [comment]
Should be fixed in our v225 branch but, I don't think it will make its way into our current alpha being released. https://github.com/coreos/coreos-overlay/pull/1676
