### ISSUE TITLE
locksmithd failed with result exit-code

### ISSUE THREAD

**Issue by reiz** [coreos/bugs#1011]
On one of my clusters on 1 node the locksmithd failed to start. Journalctl shows this: 

```
journalctl -u locksmithd
-- Logs begin at Thu 2015-12-03 14:04:21 UTC, end at Thu 2015-12-03 15:01:38 UTC. --
Dec 03 14:04:29 localhost systemd[1]: Started Cluster reboot manager.
Dec 03 14:04:29 localhost locksmithd[729]: Cannot get update engine status: The name com.coreos.update1 was not provided by any .service files
Dec 03 14:04:29 localhost systemd[1]: locksmithd.service: Main process exited, code=exited, status=1/FAILURE
Dec 03 14:04:29 localhost systemd[1]: locksmithd.service: Unit entered failed state.
Dec 03 14:04:29 localhost systemd[1]: locksmithd.service: Failed with result 'exit-code'.
Dec 03 14:04:37 node1.veye.com systemd[1]: locksmithd.service: Service hold-off time over, scheduling restart.
Dec 03 14:04:37 node1.veye.com systemd[1]: locksmithd.service: Failed to schedule restart job: Unit locksmithd.service is masked.
Dec 03 14:04:37 node1.veye.com systemd[1]: locksmithd.service: Unit entered failed state.
Dec 03 14:04:37 node1.veye.com systemd[1]: locksmithd.service: Failed with result 'resources'.
Dec 03 14:05:09 node1.veye.com systemd[1]: Stopped locksmithd.service.
```

I googled for it but couldn't find anything useful. Please advice how to fix this.

**Comment by crawford** [comment]
"Unit locksmithd.service is masked"

Something appears to have masked locksmith mid-boot. Have you set the reboot strategy to "off"? Are one of your programs making it? You'll need to unmask the service before you can start it.

**Comment by reiz** [comment]
@crawford Yes. reboot-strategy is set to off. 
Sorry for the stupid question but I'm new to systemd. But what exactly means "masked"?

**Comment by reiz** [comment]
@crawford Now I know what masking of the context of systemd means. I tried to unmask the service with: 

```
sudo systemctl unmask locksmithd
```

Also performed a `reload` and `restart`, but without any effect. Still getting the same error message. 

I turned the reboot-strategy to off because I want to manually trigger the reboots in a time frame at weekends.

**Comment by reiz** [comment]
I don't understand why locksmith is masked, just because the reboot-strategy is off. I would expect that the locksmith daemon still runs and can be manually triggered with locksmithctl.

**Comment by reiz** [comment]
I guess I have the same problem as described [here](838).

**Comment by crawford** [comment]
When you set the reboot strategy to "off", coreos-cloudinit masks the locksmith service to prevent it from running. If you are trying to achieve reboot windows, this is already [supported by locksmith](https://github.com/coreos/locksmith#reboot-windows). You can use something like this:

```yaml
#cloud-config

coreos:
  locksmith:
    window_start: "Sat 10:00"
    window_length: "30h"
```

**Comment by crawford** [comment]
Here's my theory as to what is going on: locksmith starts before update-engine and fails because `com.coreos.update1` isn't provided. Some time later, the service automatically restarts, which normally would succeed, but fails because coreos-cloudinit has masked the service. This error can be safely ignored.

We could fix this by forcing locksmith to run after user-config.target is realized.

**Comment by reiz** [comment]
Perfect. The update window is exactly what I need. Many Thanks :+1:

**Comment by bjaglin** [comment]
The actual problem is still present for users for who the update window is not an option, like me. The error can of course be ignored, but it's pretty verbose. @crawford your proposal sounds a lot like https://github.com/coreos/locksmith/pull/94, is it worth considering it?

**Comment by crawford** [comment]
@bjaglin yeah, I'll follow up and get that merged.

**Comment by pbx0** [comment]
Just to add that I've seen this happen in kola tests in which machines are set not to reboot via cloud-config. This then causes the entire test to fail because of https://github.com/coreos/mantle/blob/master/platform/platform.go#L233

So the test infra won't ignore the failure.
