### ISSUE TITLE
ssh-authorized-keys entries merged with existing entries

### ISSUE THREAD

**Issue by loopsysdev** [coreos/bugs#1012]
It seems that `ssh-authorized-keys` entries are added to rather than replace the entries already in `$HOME/.ssh/authorized_keys`. I would expect only the entries which are in `ssh-authorized-keys` to be in the resulting image.

**Comment by crawford** [comment]
`ssh-authorized-keys` entries are written to `~core/.ssh/authorized_keys.d/coreos-cloudinit` which are then appended to the other keys in `~core/.ssh/authorized_keys.d/*` by `update-ssh-keys`.

**Comment by loopsysdev** [comment]
OK, so it's a feature ;)
