### ISSUE TITLE
Update strategy status printed at interactive login time is racy

### ISSUE THREAD

**Issue by vcaputo** [coreos/bugs#1013]
Rather than determining the update strategy via `systemctl is-active locksmithd`, we should probably derive it from /etc/coreos/update.conf and the masked state of locksmithd.service.

The current implementation can result in misleading output if the login occurs before locksmithd has started (easy to experience via coreos.autologin).

**Comment by bgilbert** [comment]
This is still potentially a problem, but since we now support pluggable update coordinators, it's not so easy to know what we should be checking instead.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
