### ISSUE TITLE
Scheduled Update and HDD Expansion causes Crash

### ISSUE THREAD

**Issue by jbkc85** [coreos/bugs#1014]
Hello all,

Recently my team went through to update our CoreOS boxes and ran into an interesting issue: the partition was damaged and unable to boot with the message "no GPT signature".  The box would not allow us to do anything further..so we could not think of any troubleshooting to fix the issue.  In fact, after an hour or so trying to fix whatever the issue was we elected to delete the VM and start from scratch.  I know that there are some other causes of the "no GPT signature", but in this case we were able to reproduce the issue and were wondering WHY the issue would crop up at this point.  Here is a bit of information about our environment and the issue replication.
### Environment

VMWare
CoreOS OVA (originally 723.3.0, updating to 766.5.0)
Reboot Strategy: off
### Reproducing the Issue

In our case we did not check to see if an upgrade was downloaded to the disk and awaiting Reboot.  There in fact **WAS** an update scheduled, but we decided to adjust the disk size of the CoreOS machine running anyway hoping that on the reboot both the update and the disk size adjustment would take place.  This is in fact the cause of our issues.  Whenever we have an update scheduled via CoreOS and we _also_ adjust the disk space (which is an irreversible operation in VMware) somehow it erases the partition and gives us the "no GPT signature".
### Resolution

We could not find a resolution for this bug.  We simply deleted the VM and started from scratch (thank god for templating the cloud-config.yml)

Just wanted to share to see if anyone could enlighten us to the issue.

Thanks,
Jason Cameron

PS: We are updating the last two boxes of our cluster this weekend and will inevitably fall into this same issue.  I am more than happy to try further efforts to debug if anyone asks, otherwise I will just be replacing the nodes in the cluster as mentioned before.

**Comment by crawford** [comment]
That's interesting. Increasing the size of the disk will destroy the secondary GPT header and table (since it is no longer at the end of the disk), but the primary header and table (at the front) should still be valid and subsequently copied to the secondary. We will definitely be interested in grabbing some debug info from you when you resize the remaining machines.

/cc @marineam

**Comment by jbkc85** [comment]
How could I get more debugging information for you?  At this time all I know (as I was not looking directly at the console) is that the machine was stuck in constant reboot due to the "no GPT header".  Therefore any help would help me pass on information needed to get you better debugging info :-).

**Comment by pschmitt** [comment]
Hi, I had the exact same problem using the OVA (857 -> 1010.5.0, reboot_strategy: reboot)
Luckily I had a backup, once I restored and booted it up the disk was resized correctly. The update then went through without any problem.
So: reboot after expanding a disk - don't wait for an upgrade.

I still have the borked VM, let me know if and how I can provide additional info.

**Comment by crawford** [comment]
Sorry we let this slip through the cracks. Is this issue still present with newer versions of GRUB? We've made a number of improvements to the header handling logic?

**Comment by jbkc85** [comment]
I can confirm that in a recent upgrade from 1235.9.0 to 1353.7.0, it did not crash when the hard drive was in fact expanded, and an update was applied.

So with that being said, I think whatever improvements were implemented helped between the sub 900 versions :-)

**Comment by crawford** [comment]
Excellent. I'm going to go ahead and close this. Thanks again for your patience.
