### ISSUE TITLE
regression in coreos alpha 877.1.0

### ISSUE THREAD

**Issue by jumanjiman** [coreos/bugs#1016]
## primary symptom: host fails to get on network

similar past issue: https://github.com/coreos/bugs/issues/450

host info:

* bare metal host
* bnx2x NICs
* coreos alpha 877.1.0

os-release:

```
NAME=CoreOS
ID=coreos
VERSION=877.1.0
VERSION_ID=877.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 877.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

## other symptoms

* bnx2x firmware fails to load

```
[   25.399183] bnx2x 0000:02:00.1: Direct firmware load for bnx2x/bnx2x-e1h-7.12.30.0.fw failed with error -2
[   25.401217] bnx2x: [bnx2x_init_firmware:13406(enp2s0f1)]Can't load firmware file bnx2x/bnx2x-e1h-7.12.30.0.fw
[   25.403424] bnx2x: [bnx2x_func_hw_init:5785(enp2s0f1)]Error loading firmware
[   25.405292] bnx2x: [bnx2x_nic_load:2745(enp2s0f1)]HW init failed, aborting
[   26.965376] bnx2x 0000:02:00.0: Direct firmware load for bnx2x/bnx2x-e1h-7.12.30.0.fw failed with error -2
[   26.967917] bnx2x: [bnx2x_init_firmware:13406(enp2s0f0)]Can't load firmware file bnx2x/bnx2x-e1h-7.12.30.0.fw
[   26.970428] bnx2x: [bnx2x_func_hw_init:5785(enp2s0f0)]Error loading firmware
[   26.972302] bnx2x: [bnx2x_nic_load:2745(enp2s0f0)]HW init failed, aborting
```

**Comment by crawford** [comment]
```
CoreOS alpha (835.1.0)
core@ip-172-31-43-87 ~ $ find /usr/ -name bnx2x-e1h-7.10.51.0.fw 2>/dev/null
/usr/lib64/firmware/bnx2x/bnx2x-e1h-7.10.51.0.fw
```

**Comment by brenix** [comment]
+1, same issue

**Comment by mischief** [comment]
@jumanjiman the firmware files should be present in the next alpha. apologies for missing this when the kernel was updated.

**Comment by jumanjiman** [comment]
no worries. thanks @mischief !

**Comment by jumanjiman** [comment]
update: the fix appeared in https://coreos.com/releases/#891.0.0

i used ilo vsp to boot into the alternate (good) version with `coreos.autologin`,
ran `sudo update_engine_client -update`, then
rebooted into alpha 891.0.0 normally.

bnx2x is up and good on 891.0.0

**Comment by jumanjiman** [comment]
> I also see this same issue when PXE booting stable (835.8.0) in conjunction with ignition (even though the firmware file exists). Once I take out the coreos.config.url parameter, it is able to load the firmware properly. Could this be related, or possibly a separate issue?

@brenix stable 835.x.x uses a different/older version of firmware than i reported here, so yours is a different issue.

**Comment by spkane** [comment]
I am seeing this issue on stable 1010.5.0, and only when trying to utilize ignition instead of cloud-init. This might be a regression. I am going to test with one of the beta releases next.
