### ISSUE TITLE
Limit journal size

### ISSUE THREAD

**Issue by ibuildthecloud** [coreos/bugs#102]
The default journal size is 10% of the file system on which it resides.  For a 20GB root, that means you end up with a +2GB journal.  When the journal gets that big its pretty unusable.   Things like globbing with -u or --since=yesterday can takes minutes to find any result.

**Comment by porjo** [comment]
:+1: 

 My journal had grown to +700MB and operations using `journalctl` were becoming quite sluggish at that size

I've manually set `SystemMaxUse=50M` in `/etc/systemd/journald.conf` to bring it back to a more manageable size.

**Comment by crawford** [comment]
`/etc/systemd/journald.conf` can be used to limit these parameters. Using Ignition to write the configs is your best bet; it will write the config before systemd starts.
