### ISSUE TITLE
rss feed for releases?

### ISSUE THREAD

**Issue by worr** [coreos/bugs#1020]
Could we get an RSS feed for releases? I saw what looked like an RSS feed button on the [release notes page](https://coreos.com/releases/), but it turned out to just yield json.

**Comment by reiz** [comment]
@worr I will integrate that json feed into [VersionEye](https://www.versioneye.com/). That way you can get updates via an Atom/RSS feed or via email notifications. 

But it would be nice to have an API endpoint for the channels as well. I would like to know what is the newest version in each channel. Can somebody provide that from the CoreOS team?

**Comment by crawford** [comment]
I'm not sure that RSS is the most appropriate format for release updates. If we are interested in showing the various versions of CoreOS in each of the public groups (Alpha, Beta, and Stable) in addition to the latest versions of our components (e.g. etcd, fleet, flannel), I think a JSON API would be easier to consume. Granted, I am not very familiar with RSS, but it doesn't look like there is a good way to represent hierarchy. I think the immediate solution would be to remove the RSS logo from the JSON feed. The long-term solution would be a better design of the feed structure and a more accurate source of truth (it uses docs right now, instead of watching CoreUpdate).

**Comment by reiz** [comment]
@crawford @worr I just integrated that JSON feed into VersionEye. Now  you can follow the updates here: https://www.versioneye.com/go/coreos. Every time there is a new release you will receive an email. Alternatively you can have a RSS feed as well for all the packages you are following. 

I would like to mark which versions are alpha, beta, stable. Currently that information is only available from this HTML page: https://coreos.com/releases/. Would be nice if that information would be available as JSON as well.

**Comment by crawford** [comment]
We are going to go with a well-structured JSON API.

**Comment by reiz** [comment]
@crawford Is this  well-structured JSON API already online? I would like to use it for VersionEye.

**Comment by crawford** [comment]
@reiz not yet. We are hoping to have something ready by the end of the summer.

**Comment by reiz** [comment]
@crawford OK. Looking forward to it. How can I get notified about that? Is there a newsletter I can sign up for?

**Comment by crawford** [comment]
@reiz we'll announce something on https://groups.google.com/forum/#!forum/coreos-dev.

**Comment by so0k** [comment]
I've created the [following python script](https://github.com/honestbee/coreos-updatenotice) to keep track of the current release by CoreOS release channel. 

The script is designed to run as a [k8s CronJob](http://kubernetes.io/docs/user-guide/cron-jobs/) - it relies on a redis server to keep track of the version it last saw and can call a webhook when a key field changes (in my use cast this is an [operable/cog trigger](http://cog-book.operable.io/#_triggers)) - this notifies me on slack when the current CoreOS release for my channel of choice changes

**Comment by everett-toews** [comment]
@crawford Did the well-structured JSON API for releases happen?

I searched https://groups.google.com/forum/#!forum/coreos-dev but couldn't find anything relevant. Like everyone else, I'd love to see an Atom/RSS feed for each release channel. If one of us has to build a service (much like @so0k did) on that JSON API to provide the Atom/RSS feed, that's fine.

**Comment by so0k** [comment]
Another option to get current version for a channel is this... https://github.com/coreos/bugs/issues/461#issuecomment-140907302

Also just saw this CoreOS reboot operator for Kubernetes https://github.com/jamiehannaford/coreos-reboot-operator

My service was just to have slack notifications the day before the cluster would have its maintenance window for updates

**Comment by crawford** [comment]
@everett-toews no, we have not yet had a chance to rethink all of that.

**Comment by everett-toews** [comment]
FWIW, here's a feed for beta channel releases https://feed43.com/coreos-beta-channel-releases.xml

It only shows one release at a time but it works well enough. You can subscribe to it with the Slack RSS integration, Feedly, or whatever RSS tool you prefer and get notified when a release happens.

**Comment by dm0-** [comment]
We've recently added channel-specific release feeds.  There are now:

- https://coreos.com/releases/releases-alpha.json
- https://coreos.com/releases/releases-beta.json
- https://coreos.com/releases/releases-stable.json
- https://coreos.com/releases/releases.json (all releases)

**Comment by JoelESvensson** [comment]
Any chance that there could be a `release-[channel].rss` too? RSS might not be optimal but you can subscribe to RSS feeds directly in Slack with the `/feed subscribe [rss-link]` command. I currently use this to track software updates in a devops channel.

**Comment by everett-toews** [comment]
That's exactly why we need release channel RSS feeds too. I think it's a worthwhile use case for CoreOS to support.

**Comment by RyPeck** [comment]
RSS or Atom would be much appreciated so clients like Slack, Outlook and other RSS readers can ingest.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.

**Comment by captn3m0** [comment]
I wrote a rss-bridge plugin that converts the JSON feed to RSS.

You can try it in [atom](https://rss-bridge.bb8.fun/?action=display&bridge=ContainerLinuxReleases&channel=stable&format=Atom), [HTML](https://rss-bridge.bb8.fun/?action=display&bridge=ContainerLinuxReleases&channel=stable&format=Html) formats.

It supports all three channels (stable/alpha/beta) and you can generate the feed that you want at https://rss-bridge.bb8.fun/ (can't guarantee uptime)
