### ISSUE TITLE
write_files cannot write to /usr/share/oem

### ISSUE THREAD

**Issue by jeberle** [coreos/bugs#1023]
`write_files` gives a read-only file system error when writing to `/usr/share/oem`.

My guess is that since `/usr` is mounted `ro`, a dir check isn't descending to the actual dirname of the target file.

**error**

    cf05 coreos-install # coreos-cloudinit --from-file cloud-config-cf05.yml
    2015/12/08 23:37:31 Checking availability of "local-file"
    2015/12/08 23:37:31 Fetching user-data from datasource of type "local-file"
    2015/12/08 23:37:31 line 62: error: file cannot be written to a read-only filesystem

**offending lines**

    cf05 coreos-install # sed -n '62,$p' cloud-config-cf05.yml
    - path: /usr/share/oem/grub.cfg
      owner: root:root
      permissions: '0644'
      content: |
        set linux_append="console=tty1 coreos.autologin=tty1"

**work-around**

    - name: oem-grub-cfg.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStart=/bin/bash -c 'printf "set linux_append=\\x22console=tty1 coreos.autologin=tty1\\x22\\n" >/usr/share/oem/grub.cfg'

**version**

    cf05 coreos-install # grep PRETTY /etc/os-release
    PRETTY_NAME="CoreOS 835.8.0"

**Comment by mischief** [comment]
looks like it just checks for a prefix of /usr.

https://github.com/coreos/coreos-cloudinit/blob/master/config/validate/rules.go#L158

**Comment by crawford** [comment]
@jeberle can you attach the full logs? The error you are seeing is a result of [this check](https://github.com/coreos/coreos-cloudinit/blob/08eb9bae3c4deb470b63c24c659f7c8659eadb27/coreos-cloudinit.go#L197) which is non-fatal unless the `-validate` flag is provided.

**Comment by jeberle** [comment]
I had a chance to try this again. As you say, the error is indeed non-fatal. `coreos-cloudinit` does write the file.
