### ISSUE TITLE
etcd2 becomes unresponsive on Azure Government Cloud

### ISSUE THREAD

**Issue by stmpy** [coreos/bugs#1024]
Since the update to 835 etcd will become unresponsive after a short amount of time, typically within 24 hours. 

There are only 3 services running on my current cluster, this ends up being a consistent issue where I have to rebuild the cluster to get it working again.

All over the journal log I see this message:
```
etcd2[5224]: got unexpected response error (etcdserver: request timed out)
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint http://10.1.0.6:4001 exceeded header timeout
error #1: client: endpoint http://10.1.0.5:4001 exceeded header timeout
error #2: client: endpoint http://10.1.0.4:4001 exceeded header timeout
```

I can still ping all of the different coreos nodes so I know the network connection is available. etcd2 is not running on any of them at this point in time, they all look similar, etcd2 just stops working and crashes.

I can provide more information if needed

**Comment by stmpy** [comment]
I was on 835.8 and am updating to 835.9 to try again.

We had increased our heartbeat interval and election timeout to the following with Azure and we were stable previous to 835.

```
heartbeat-interval: 600
election-timeout: 3000
```

**Comment by xiang90** [comment]
@stmpy 

> etcd2 just stops working and crashes.

What do you mean by not working and crash? It panics? Deadlock? Unresponsive with timeout logging?

**Comment by stmpy** [comment]
Unresponsive with timeout logging

**Comment by xiang90** [comment]
@stmpy Can you please provide logs from all etcd members in the cluster for at least 5 mins when the issue happened?

**Comment by stmpy** [comment]
I'm rebuilding the cluster on 835.9 and I'll provide the logs

**Comment by stmpy** [comment]
The cluster has been up for 18hours on 835.9 with no issues so far, I'm going to more fully deploy our software stack and get the server running more of a load and will report back. Just wanted to provide a heads up

**Comment by xiang90** [comment]
@stmpy OK. At this point, even if there is an issue, it is probably an etcd issue not CoreOS itself. Can you please report to etcd repo if there is a future issue?

**Comment by stmpy** [comment]
Will do
