### ISSUE TITLE
Coreos PXE image doesn't support RAID device passed to kernel 'root' param

### ISSUE THREAD

**Issue by shredder12** [coreos/bugs#1025]
While booting CoreOS PXE image, when a pre-formatted raid device is passed to the kernel as root param, boot fails with the attached error message.

![screen shot 2015-12-04 at 5 21 08 pm](https://cloud.githubusercontent.com/assets/490551/11674742/8f573e00-9dd8-11e5-909c-da8e57b648ba.png)

These are the parameters I used
```
kernel ${base-url}/coreos_production_pxe.vmlinuz console=tty1 coreos.autologin=tty1 root=/dev/md0
```

It seems initramfs isn't able to detect/assemble the RAID device. I am not sure if this is a limitation of coreos PXE image or something I missed.

Please let me know if more information is needed.

Thanks.

**Comment by vcaputo** [comment]
@shredder12 I haven't tested this, but does including `rd.auto` in the parameters help?

**Comment by shredder12** [comment]
that did the trick. Thanks @vcaputo

**Comment by vcaputo** [comment]
Nice! no problemo.
