### ISSUE TITLE
etcdctl doesn't work with etcd 0.4.9 on 835.9.0

### ISSUE THREAD

**Issue by kmccormack** [coreos/bugs#1027]
After upgrading to 835.9.0 a machine that runs etcd 0.4.9, I attempt to run etcdctl and get: 

```
$ etcdctl ls /
Error:  unexpected status code 404
```

This appears to be because etcdctl relies on querying the /members API which doesn't exist (I believe) in etcd 0.4.9. If I use the `--no-sync` option, it works OK: 

```
$ etcdctl --no-sync ls /
/coreos.com
/resources
/services
/skydns
/test
```

**Comment by edgurgel** [comment]
Yeah I just noticed this is happening on 2 machines as well.

**Comment by kmccormack** [comment]
I should have been clearer in my original filing that this has caused all our fleet unit files that call etcdctl (quite a few of them) to fail to run when the OS was updated automatically. I've had to revert a bunch of machines to 766.5.0 in order for those unit files to run.

**Comment by edgurgel** [comment]
Same thing here.

**Comment by philips** [comment]
We should fix this as we must have broken a userspace API here. cc @xiang90 @gyuho

**Comment by philips** [comment]
Is there anyway that you can upgrade to etcd v2+? The version of etcd that you are using has known issues that are fixed in later versions of etcd, unfortunately it is a manual update process. We would be happy to help you through the process on the mailing list or IRC: https://coreos.com/community/

**Comment by xiang90** [comment]
@philips 

For etcd components, we keep backward compatibility between two versions. So etcd 0.4.9 cannot be upgraded to etcd 2.2 automatically and etcdctl 2.2 cannot talk to etcd 0.4.9. (etcd 2.0/2.1 can).

I am not sure what is the best way to solve it.

**Comment by edgurgel** [comment]
Well 766.5 has etcd2 and etcdctl  2.1.2 right? An upgrade could happen at this stage and then move to the newest stable (835.9) which has etcd 2.2. Would it work?

```
CoreOS stable (766.5.0)
$ etcdctl --version
etcdctl version 2.1.2
 $ etcd2 --version
etcd Version: 2.1.2
Git SHA: ff8d1ec
Go Version: go1.4.2
Go OS/Arch: linux/amd64
```

**Comment by kmccormack** [comment]
@philips we are looking at upgrading to etcd 2.2. We would just destroy and rebuild the cluster to do it so upgrading is not so much the issue. It's more that we are still trialling etcd 2.2 and need to be more confident with it before widely deploying it. I don't really want to have to roll it out just because of an etcdctl bug. I do appreciate that etcd 0.4.9 is deprecated and that 2.x is much better in many ways…it's just that we're not there yet. 

For now I've stopped our machines from auto-updating and reverted any that had migrated.

**Comment by svett** [comment]
This is really frustrating. A soon as my CoreOS deployment was upgraded automatically everything went down due to this issue. Do you even test any new feature or change?

**Comment by mischief** [comment]
waiting on this fix to appear in etcd. it will be backported to the next stable.

**Comment by iolloyd** [comment]
@svett tests do happen and bad things sometimes happen. For that reason, in general, it's good to do your own tests too.

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/coreos-overlay/pull/1723. This should be available in 899.2.0.

**Comment by gclayburg** [comment]
I ran into this same issue with the latest stable version 835.12.0.  So I guess my options are to insert the "--no-sync" option everywhere etcdctl is used or upgrade the cluster to use the latest etcd2.2.    I like the idea of automatic coreos updates and I was hoping that incompatible updates would not be introduced into the stable channel.   I realize that the etcd upgrade from 0.4 to 2.2 is a major change.  Going forward, should we expect breaking changes like this one to slip into the stable channel?  Or is this one just an artifact of maturing etcd to version 1.0?

**Comment by crawford** [comment]
@gclayburg This is definitely a rare case. While we cannot guarantee that we will never introduce incompatible changes, we do our best to provide ample warning for planned  incompatible changes and testing to catch unintended incompatible changes.
