### ISSUE TITLE
Using $public_ipv4 did not discover multi-region ec2 instances

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#103]
>Hi All,
>
>I've used a cloud-config like [1] to discover multi-region ec2 instances with CoreOS latest stable build (367). But it failed to discover nodes in other regions. Is this a known issue or is it a config issue?
>
>Also, I'm not sure what this addr and peer-addr properties mean. Can someone please explain?
>
>Thanks.
>
>[1]
>
>```
>#cloud-config
>
>coreos:
>etcd:
># generate a new token for each unique cluster from https://discovery.etcd.io/new
>discovery: https://discovery.etcd.io/xxxxxxxxxxxxxx
># multi-region and multi-cloud deployments need to use $public_ipv4
>addr: $public_ipv4:4001
>peer-addr: $public_ipv4:7001
>units:
>- name: etcd.service
>command: start
>- name: fleet.service
>command: start
>```
@nirmal070125

**Comment by yichengq** [comment]
@bcwaldon has answered your question. Close this due to low activity.

PS, we strongly recommend to upgrade to etcd 2.x, which is more stable.
