### ISSUE TITLE
Ignition 0.2.4 (PXE boot): journalctl shows no ignition content unless run with sudo

### ISSUE THREAD

**Issue by SpencerBrown** [coreos/bugs#1030]
PXE boot CoreOS with `coreos.first_boot` and `coreos.config.url` kernel parameters.

If you run `journalctl --identifier=ignition` as the `core` user, you will see nothing.

If you run under sudo you will see ignition entries in the log.

Not sure if this is a fixable issue, or maybe just update the documentation to point this out.

**Comment by crawford** [comment]
I believe this is due to the fact that the PXE images use a tmpfs for the root. This also makes it difficult to write files to the root filesystem.

**Comment by crawford** [comment]
I had a chance to reproduce this and as I suspected, there are two machine IDs in `/run/log/journal`. The initramfs' is owned by root and the pivoted journal is in the `systemd-journal` group.
