### ISSUE TITLE
HTTPS support for *.release.core-os.net

### ISSUE THREAD

**Issue by Manouchehri** [coreos/bugs#1032]
I don't think there's an easy fix for this with Google Cloud Storage, but the following hosts have an invalid certificate.

https://stable.release.core-os.net
https://beta.release.core-os.net
https://alpha.release.core-os.net

Does Google Cloud Storage allow downloading with a URL from `*.storage.googleapis.com`? If so, a 303 or 307 redirect could be given to avoid the certificate mismatch.

**Comment by marineam** [comment]
Yeah, unfortunatly Google doesn't really support custom SSL certificates for most of there products, including GCS. They are ever so slowly rolling out such support but I have no idea if/when GCS will be fixed. Also `*.storage.googleapis.com` style URLs won't work either because that star cert won't match bucket names with `.` in them like ours. So if you want to use HTTPS the only option right now is https://storage.googleapis.com/stable.release.core-os.net and similar.

I do want to fix this but it will require transitioning to a different frond-end. Additionally moving away from Google may improve our availability in China.

**Comment by Manouchehri** [comment]
@marineam Thank you! Never knew it was easy as appending `https://storage.googleapis.com/`.

**Comment by marineam** [comment]
Looks like the website features don't work when using URLs of that form so if you want to browse you'll need to add index.html: https://storage.googleapis.com/stable.release.core-os.net/index.html

**Comment by jimmycuadra** [comment]
Although you can use https://storage.googleapis.com/stable.release.core-os.net form to access this content over HTTPS, the content served from them may still reference HTTP URLs. For example:

```
$ curl https://storage.googleapis.com/alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
{
  "name": "coreos-alpha",
  "description": "CoreOS alpha",
  "versions": [{
    "version": "949.0.0",
    "providers": [{
      "name": "virtualbox",
      "url": "http://alpha.release.core-os.net/amd64-usr/949.0.0/coreos_production_vagrant.box",
      "checksum_type": "sha256",
      "checksum": "c0e67eb190db11887e02b4c7971f650cd0daee31352a1a947916444078f07a1e"
    }]
  }]
}
```

I think the "url" field in the JSON response should use an HTTPS URL in the same form as how I accessed it. As it is now, in the case of Vagrant, if I use the HTTPS URL as the box URL, Vagrant will access this metadata file over HTTPS, but will still download the box file itself over HTTP.

**Comment by Smana** [comment]
@paulczar did you face that issue ?

**Comment by marineam** [comment]
Greetings! HTTPS for *.release.core-os.net now works correctly *finally* and the URL listed in this week's alpha will use HTTPS as well.

**Comment by marineam** [comment]
https://alpha.release.core-os.net/amd64-usr/1045.0.0/coreos_production_vagrant.json

```json
{
  "name": "coreos-alpha",
  "description": "CoreOS alpha",
  "versions": [{
    "version": "1045.0.0",
    "providers": [{
      "name": "virtualbox",
      "url": "https://alpha.release.core-os.net/amd64-usr/1045.0.0/coreos_production_vagrant.box",
      "checksum_type": "sha256",
      "checksum": "ae34e58f216661abf149a6cc28463bf6b6a42bbbec2043da6931ce5b046cf426"
    }]
  }]
}
```
