### ISSUE TITLE
iPXE Code Signing

### ISSUE THREAD

**Issue by Manouchehri** [coreos/bugs#1034]
One of the great features of iPXE is that it supports code signing. CoreOS seems like a good candidate for verified network booting, there's not much extra work left.

To-do list:

- Enforce signature checking with [`imgtrust --permanent` and use `imgverify`](http://ipxe.org/crypto#code_signing).
- Embed CoreOS's certificate with iPXE, `make bin/ipxe.efi CERT=production.crt`.
- [Sign `ipxe.efi` with an approved EV certificate.](http://ipxe.org/appnote/etoken#ev_code_signing_certificate)
- Add EFI to iPXE's ISO. [(Likely will be done upstream in iPXE.)](http://lists.ipxe.org/pipermail/ipxe-devel/2015-December/004522.html)

**Comment by marineam** [comment]
Note: no need for a cert from a public CA or approval from Microsoft, our secure boot plan is to require systems to trust our own certificate(s) instead.

**Comment by Manouchehri** [comment]
@marineam It's only $500 for a three year certificate from DigiCert. Obviously not my call, but I think it's worth it to reduce the hassle; hardly anyone is interested in secure boot at the moment because it's "too difficult". @mjg59 [already did this](https://mjg59.dreamwidth.org/20303.html) back during his time with Red Hat, might want to ask him for help.

**Comment by marineam** [comment]
@Manouchehri the price isn't the question, it's that being signed by a public CA or Microsoft is a pretty uninteresting level of security to me. My ideal model would be to improve the tooling such that it is strait-forward for users to provision machines with their own keys which they can then use to sign our version of shim (so CoreOS can boot) and all configuration and rkt containers the system is allowed to run. This way a system a machine can be locked down to run only code the user trusts. Obviously users can do a more limited deployment by provisioning systems with CoreOS keys directly and not restricting rkt and such, or if a customer needs it we could release a Microsoft signed shim at a later point. My priority is targeting a higher level of security first though. @mjg59 and I have been working towards this for a while, the last major step is on me to finish the required changes to update_engine to support upgrading systems locked down via secure boot.

Regardless of the keys, once we start signing kernels we can sort out how to sign them in a way to make iPXE happy to. Making sure the chain of trust works correctly through iPXE, the kernel, and the PXE squashfs image takes a bit more thought than just adding a signature to iPXE itself. on the TODO now though! :)

**Comment by Manouchehri** [comment]
Is it even possible to remove factory keys from Microsoft on most
motherboards? They're still going to be there regardless if you use them,
no?

**Comment by marineam** [comment]
Yes, you can clear the full trust database on a properly implemented system.

**Comment by Manouchehri** [comment]
Neat, I always thought Microsoft's key was stuck in there (I usually use
OVMF which has no keys by default). Glad to hear that's not the case.

Any ideas on how you're going to handle dedicated servers without a KVM
console?

**Comment by marineam** [comment]
Specifically for setting up secure boot? In some cases where folks are provisioning new systems it may be possible to work with the OEM to set up the firmware appropriately, in other cases as long as systems start off in setup mode it is possible to boot to a UEFI tool that will initialize the trust database and enable secure mode.

**Comment by Manouchehri** [comment]
Now that I think about it, why not use self-signed keys *and* DigiCert? You'd have the best of both world.

My concern is that if we only use self-signed keys, the first result on Google for "secure boot CoreOS" is going to be how to turn it off.

**Comment by mjg59** [comment]
@Manouchehri It's not practical to sign the same binary with multiple keys - the spec permits it, most firmware breaks. We'd need to ship two separate images. I'm going to close this issue for now because we're going to be using grub for netboooting on UEFI systems. It's much easier to reduce the number of boot stacks we have to support, ipxe hasn't been audited for behaviour on secure boot systems and the imgtrust/imgverify support doesn't use the UEFI signing spec so we'd need to add more complexity to our build process.

**Comment by Manouchehri** [comment]
@mjg59 Couldn't there be two binaries, `bootx64.efi` with a self-signed certificate and `fallback.efi` signed with DigiCert/another CA?

**Comment by mjg59** [comment]
Yes, but the system will only attempt to execute bootx64.efi so it would involve manual modification in order to make it possible to boot

**Comment by Manouchehri** [comment]
Shouldn't it fallback to `fallback.efi` if there's no valid signature on `bootx64.efi`, or does it just halt?

**Comment by mjg59** [comment]
fallback.efi isn't part of the UEFI spec - Shim launches it if there are no existing boot entries. So if you can't launch bootx64.efi, fallback won't be launched.
