### ISSUE TITLE
Include cachefiles module

### ISSUE THREAD

**Issue by wienczny** [coreos/bugs#1039]
Please include the cachefiles module with CoreOS. It's required to use cachefilesd which is useful to improve performance of remote filesystems like afs,ceph and nfs. Some of these filesystems are already supported by CoreOS.

**Comment by mtanski** [comment]
For @wienczny to get everything he needs to make this work there's additional kconf options needed for the kernel.

```bash
mtanski@bnode-dc16d823:/lib/udev/rules.d$ cat /boot/config-4.2.0-19-generic  | grep 'FSCACHE'
CONFIG_FSCACHE=m
CONFIG_FSCACHE_STATS=y
# CONFIG_FSCACHE_HISTOGRAM is not set
# CONFIG_FSCACHE_DEBUG is not set
# CONFIG_FSCACHE_OBJECT_LIST is not set
CONFIG_NFS_FSCACHE=y
CONFIG_CEPH_FSCACHE=y
CONFIG_CIFS_FSCACHE=y
CONFIG_AFS_FSCACHE=y
CONFIG_9P_FSCACHE=y
```

**Comment by mischief** [comment]
we do not have support for AFS, so i am not enabling caching support. the others have been enabled in my PR.

**Comment by wienczny** [comment]
I already created a docker container to use it when deployed.
You can find the Dockerfile at https://bitbucket.org/styleauteam/coreos_cachefilesd and an image at quay.io/wienczny/coreos_cachefilesd

**Comment by mtanski** [comment]
@mischief sounds good, just wanted to point out all filesystems that support fscache need to have to have it explicitly enabled
