### ISSUE TITLE
cloud-init: write_files.permissions: parse error

### ISSUE THREAD

**Issue by maticmeznar** [coreos/bugs#1040]
I forgot to put permission value into quotes and my user-data was only partially applied when setting up CoreOS with Vagrant. When I run "coreos-cloudinit -validate" on my workstation, my user-data seems valid. https://coreos.com/validate/ also says my cloud-config is valid. However, if I run "coreos-cloudinit -from-file=/var/lib/coreos-vagrant/vagrantfile-user-data -validate" on a CoreOS node that failed to set up correctly, it reports an error: "line 80: error: invalid value 384". File /var/lib/coreos-vagrant/vagrantfile-user-data is different from the one on my workstation, e.g., blank lines are missing and 0600 got changed into 384.

`write_files:`
`- path: /some.file`
`  permissions: '0600' <- GOOD`
`...`
`- path: /bootstrap.sh`
`  permissions: 0600 <- BAD, interpreted as "384"`

**Comment by crawford** [comment]
`0600` (or `0o600`) equals `384`. I believe the default Vagrantfile does transformation on the cloud-config. One of the side effects is that all numeric values are converted to decimal. You will need to quote the values to prevent the transform from screwing up the file or skip the transform altogether.

This is one of the uncountable number of reasons why we switched to JSON with Ignition.
