### ISSUE TITLE
Stock IPXE does not support HTTPS 

### ISSUE THREAD

**Issue by joshix** [coreos/bugs#1044]
Stock iPXE is not built with the `DOWNLOAD_PROTO_HTTPS` option needed to dial TLS connections for retrieving boot scripts &c.

The [ipxe doc](https://github.com/Manouchehri/docs/blob/ipxe-https/os/booting-with-ipxe.md) complains of this fact, and the build option was noted/suggested in https://github.com/coreos/docs/pull/697

**Comment by Manouchehri** [comment]
Related: #1034.

**Comment by marineam** [comment]
Regarding "The iPXE shipped in CoreOS" you mean the upstream iPXE builds right? I don't think we are distributing iPXE at all except with QEMU inside the development SDK.

But yes, we could ship iPXE builds but what form would that take?

**Comment by joshix** [comment]
@marineam Sloppy writing on my part. "Stock iPXE" is all that was intended. Corrected the description above to match what the title already said.

I created this issue to track the idea from the docs PR and relate it to the #1034 stuff. I don't know that we should talk about shipping a iPXE so much (even tho I'm who accidentally kicked that off), as just maybe documenting a certain iPXE build recommended for CoreOS booting, which incorporates some of the features discussed.

**Comment by Manouchehri** [comment]
@joshix Well, anything done in #1034 would require shipping a custom CoreOS iPXE build.

**Comment by Manouchehri** [comment]
I should mention that HTTPS is mostly useful for `cloud-config-url` (e.g., using Gist) and not obtaining the actual CoreOS image.

**Comment by joshix** [comment]
closed - resolved with doc (long ago)
