### ISSUE TITLE
curl error 77 on running update_engine_stub.service unit

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1046]
_From @streamnsight on December 16, 2015 1:3_

not sure if this relates to this project but couldn't find any better place...

I get 
```
/usr/sbin/update_engine_stub
Request: <?xml version="1.0" encoding="UTF-8"?>
<request protocol="3.0" version="CoreOSUpdateEngine-0.1.0.0" updaterversion="CoreOSUpdateEngine-0.1.0.0" installsource="scheduler" ismachine="1">
<os version="Chateau" platform="CoreOS" sp="835.9.0"></os>
<app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" oem="diskless" version="835.9.0" track="stable" bootid="{b3f01128-3773-479b-ab04-4550b2dd9ffc}" machineid="3eed9016e3d94e51aaf1a268d8db7e19" lang="en-US" hardware_class="" delta_okay="false"  >
<event eventtype="3" eventresult="2" previousversion=""></event>
</app>
</request>
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
```

on start of my node
This is related to curl not being able to find the ca certs... but the path is right and the certs are there.
so what's wrong here? and how do i fix it?

I ran update-ca-certificates to no avail.
i checked the curl config and it's correct as far as i can tell

```
curl-config --configure
 '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-cros-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--disable-dependency-tracking' '--disable-silent-rules' '--libdir=/usr/lib64' '--enable-dict' '--enable-file' '--enable-ftp' '--enable-gopher' '--enable-http' '--enable-imap' '--disable-ldap' '--disable-ldaps' '--enable-pop3' '--enable-rtsp' '--disable-smb' '--without-libssh2' '--enable-smtp' '--enable-telnet' '--enable-tftp' '--disable-ares' '--enable-cookies' '--enable-hidden-symbols' '--enable-ipv6' '--enable-largefile' '--enable-manual' '--enable-proxy' '--disable-soname-bump' '--disable-sspi' '--disable-static' '--disable-threaded-resolver' '--disable-versioned-symbols' '--without-cyassl' '--without-darwinssl' '--without-libidn' '--without-gssapi' '--without-krb4' '--without-libmetalink' '--without-nghttp2' '--without-librtmp' '--without-spnego' '--without-winidn' '--with-zlib' '--without-axtls' '--without-gnutls' '--without-nss' '--without-polarssl' '--without-ssl' '--without-winssl' '--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt' '--with-ssl' '--with-ca-path=/etc/ssl/certs' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-cros-linux-gnu' 'CFLAGS=-O2 -pipe -mtune=generic -g' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed'
```

```
ls -l /etc/ssl/certs/ca-certificates.crt
-rw-r--r-- 1 root root 281403 Dec 16 00:53 /etc/ssl/certs/ca-certificates.crt
```

any ideas?

_Copied from original issue: coreos/updateservicectl#116_

**Comment by crawford** [comment]
_From @sym3tri on December 18, 2015 1:0_

Hi @streamnsight 
Have you tried the mailing list or IRC? Those are usually a better place to ask questions like this (faster response time).

https://coreos.com/community/

**Comment by crawford** [comment]
_From @sym3tri on December 18, 2015 1:5_

or https://github.com/coreos/bugs/issues

**Comment by streamnsight** [comment]
seems like this is due to an issue when i add a CA cert to the /etc/ssl/certs directory and run update-ca-certificates.

when i removed my CA cert and re-run update-ca-certificates, it seems to work.
Not sure what is wrong with my  CA cert.

**Comment by crawford** [comment]
Are the permissions correct?

**Comment by streamnsight** [comment]
same permission as the other certs. Somehow after I run update-ca-certificates with my CA cert included, it doesn't work, when I remove it and re-run update-ca-certificates, it works again. So my cert is inserted in the ca-certificates.crt and causing problems.

**Comment by vcaputo** [comment]
@streamnsight Maybe performing a manual `openssl verify -verbose` with your misbehaving ca-certificates.crt in place will shed more light on the situation.

**Comment by crawford** [comment]
@streamnsight were you able to figure out what was going on?

**Comment by streamnsight** [comment]
still not sure what is wrong with my certs but when they are in /etc/ssl/certs and i update-ca-certificate

**Comment by streamnsight** [comment]
it fails

**Comment by crawford** [comment]
Did @vcaputo's suggestion shed any light on the failure?

**Comment by euforic** [comment]
@streamnsight I had the same issue due to a bad cert in `/etc/ssl/certs`. To fix it I did the following

- Remove bad cert(s) from `/etc/ssl/certs`
- Run `sudo update-ca-certificates`
- Run `update_engine_client -update` to force the coreos update

Hope that helps
