### ISSUE TITLE
toolbox: "sh: can't access tty; job control turned off"

### ISSUE THREAD

**Issue by jumanjiman** [coreos/bugs#1052]
`$subject` is an ongoing issue on coreos+toolbox.

I looked through this repo but could not find an existing issue for it.

Related issues in other projects:

* https://github.com/systemd/systemd/issues/1431
* https://github.com/gliderlabs/docker-alpine/issues/85

There are lots of details in the above two issues thanks to @ianbytchek
but I thought it would help to raise visibility here, as well.

example:

```
core@ip-192-168-254-21 ~ $ grep -i version /etc/os-release 
VERSION=899.1.0
VERSION_ID=899.1.0

core@ip-192-168-254-21 ~ $ cat .toolboxrc 
TOOLBOX_DOCKER_IMAGE=alpine
TOOLBOX_DOCKER_TAG=3.3

core@ip-192-168-254-21 ~ $ toolbox sh
Spawning container core-alpine-3.3 on /var/lib/toolbox/core-alpine-3.3.
Press ^] three times within 1s to kill container.
Timezone UTC does not exist in container, not updating container timezone.
sh: can't access tty; job control turned off
/ # exit
Container core-alpine-3.3 exited successfully.
```

**Comment by ianbytchek** [comment]
:+1: Thanks Paul, this is a big pain indeed.

**Comment by crawford** [comment]
I'm not sure this is our bug to fix. The default (Fedora) works fine:

```
$ cat .toolboxrc
cat: .toolboxrc: No such file or directory
$ toolbox sh
Spawning container core-fedora-latest on /var/lib/toolbox/core-fedora-latest.
Press ^] three times within 1s to kill container.
sh-4.3# exit
Container core-fedora-latest exited successfully.
```

[This FAQ](https://busybox.net/FAQ.html#job_control) is a nice overview of the problem.

**Comment by zsoltm** [comment]
Use `toolbox getty -nl /bin/sh 0 /dev/console` like I posted for [systemd/#1052](//github.com/systemd/systemd/issues/1431). It has nothing to do with coreos, most major distros works fine as toolbox (I'm using debian), I'm wondering what are they doing differently than Alpine.

**Comment by jumanjiman** [comment]
@zsoltm tyvm for the workaround.

**Comment by rowanj** [comment]
👍 for the workaround, @zsoltm 

@jumanjiman FWIW `apk add tzdata` to fix the time zone warning, too
