### ISSUE TITLE
rkt was accidentally bumped to revision 13.0 instead of 0.13.0

### ISSUE THREAD

**Issue by mischief** [coreos/bugs#1053]
rkt outputs 0.13.0, but the ebuild and coreos package list show version 13.0. this should be fixed before it goes on too long.

**Comment by jonboulle** [comment]
Seems this actually started with 0.11.0: https://github.com/coreos/coreos-overlay/commit/bf402aa0dc1fda4bb9d9816d52f87ff9baae4625

is it as simple as just moving to 0.13.0 or are there some other side effects?

/cc @steveeJ
