### ISSUE TITLE
Are kernel modules really signed?

### ISSUE THREAD

**Issue by maticmeznar** [coreos/bugs#1054]
I was unable to find any relevant CoreOS documentation on a canonical way of enabling signature verification of kernel modules. Also, modinfo doesn't show modules as being signed:

CoreOS 877.1.0:
```
$ modinfo ip_tables
filename:       /lib/modules/4.3.0-coreos/kernel/net/ipv4/netfilter/ip_tables.ko
description:    IPv4 packet filter
author:         Netfilter Core Team <coreteam@netfilter.org>
license:        GPL
depends:        
intree:         Y
vermagic:       4.3.0-coreos SMP mod_unload 
```
Ubuntu 15.10:
```
$ modinfo ip_tables
filename:       /lib/modules/4.2.0-22-generic/kernel/net/ipv4/netfilter/ip_tables.ko
description:    IPv4 packet filter
author:         Netfilter Core Team <coreteam@netfilter.org>
license:        GPL
srcversion:     D6340E11A5121FD07067C61
depends:        x_tables
intree:         Y
vermagic:       4.2.0-22-generic SMP mod_unload modversions 
signer:         Build time autogenerated kernel key
sig_key:        5B:A1:35:31:09:D2:78:49:DD:D6:FB:D5:54:A5:53:44:38:BE:AF:AB
sig_hashalgo:   sha512
```
^^ Notice the last 3 lines.

I'd like to know whether the kernel modules are really signed and how to properly enable signature verification.

**Comment by vcaputo** [comment]
Signing is enabled, and the modules do have `~Module signature appended~` at the end, but modinfo is not reporting the signature information in the recent builds I explored.  I *suspect* I may have broken this somehow in the course of https://github.com/coreos/coreos-overlay/pull/1663, but it's unclear to me what exactly did it.

**Comment by crawford** [comment]
@vcaputo Bump

**Comment by vcaputo** [comment]
The modules are signed, if you try loading an unsigned module (or one signed with an unknown key) via insmod you'll get an error on the console:
`module verification failed: signature and/or required key missing - tainting kernel`

We're not getting any such errors, and any booted CoreOS instance will have myriad kernel modules already loaded.

The modinfo utility however is no longer showing these signatures, and after some investigation it appears in kernel 4.3 the utility `scripts/sign-file` was converted from a perl script to a C program by this commit:
```
commit bc1c373dd2a5113800360f7152be729c9da996cc
Author: David Howells <dhowells@redhat.com>
Date:   Mon Jul 20 21:16:27 2015 +0100

    MODSIGN: Provide a utility to append a PKCS#7 signature to a module
    
    Provide a utility that:

     (1) Digests a module using the specified hash algorithm (typically sha256).
    
         [The digest can be dumped into a file by passing the '-d' flag]
    
     (2) Generates a PKCS#7 message that:
    
         (a) Has detached data (ie. the module content).
    
         (b) Is signed with the specified private key.
    
         (c) Refers to the specified X.509 certificate.
    
         (d) Has an empty X.509 certificate list.
    
         [The PKCS#7 message can be dumped into a file by passing the '-p' flag]
    
     (3) Generates a signed module by concatenating the old module, the PKCS#7
         message, a descriptor and a magic string.  The descriptor contains the
         size of the PKCS#7 message and indicates the id_type as PKEY_ID_PKCS7.
    
     (4) Either writes the signed module to the specified destination or renames
         it over the source module.
    
    This allows module signing to reuse the PKCS#7 handling code that was added
    for PE file parsing for signed kexec.
    
    Note that the utility is written in C and must be linked against the OpenSSL
    crypto library.
    
    Note further that I have temporarily dropped support for handling externally
    created signatures until we can work out the best way to do those.  Hopefully,
    whoever creates the signature can give me a PKCS#7 certificate.
    
    Signed-off-by: David Howells <dhowells@redhat.com>
    Tested-by: Vivek Goyal <vgoyal@redhat.com>
```

If I go back to the old sign-file perl script and sign a kernel module in the CoreOS sdk using it, modinfo outputs the signature as it used to.  So it appears the new sign-file.c replacement is producing slightly different output that modinfo isn't grokking, but that the kernel is grokking.

**Comment by maticmeznar** [comment]
@vcaputo Thank you for the explanation. I hope modinfo maintainers implement that functionality soon :)

**Comment by vcaputo** [comment]
I dug a little deeper and it appears the kernel is now using a `PKCS#7` message to sign modules, which has been given an `id_type=2`, and the current master of upstream kmod doesn't have any knowledge of types > 1.

Kernel v4.4 sign-file.c utility:
https://github.com/torvalds/linux/blob/v4.4/scripts/sign-file.c#L131

kmod (master) modinfo utility:
http://git.kernel.org/cgit/utils/kernel/kmod/kmod.git/tree/libkmod/libkmod-signature.c#n72

So kmod needs to learn about PKCS#7 before modinfo is going to report anything for these signatures.

/cc @lucasdemarchi

**Comment by lucasdemarchi** [comment]
PKCS#7 is currently not supported in kmod yet. There was a patch from Wouter van Kesteren to add it, but he stopped when realized most of the necessary information was not available. Quoting here:

```
> I attempted to make a patch to support this new method of signing. But
> whilst doing so i came to the conclusion that a lot of things that are
> in the appended struct are now set to zero.
> Infact, everything except id_type (which is 2) and sig_len is set to
> zero. Instead this information seems to be embedded in the signature
> blob instead.

That struct should be filled by the tool signing the module:

/*
 * Module signature information block.
 */
struct module_signature {
        uint8_t algo;        /* Public-key crypto algorithm [enum pkey_algo] */
        uint8_t hash;        /* Digest algorithm [enum pkey_hash_algo] */
        uint8_t id_type;     /* Key identifier type [enum pkey_id_type] */
        uint8_t signer_len;  /* Length of signer's name */
        uint8_t key_id_len;  /* Length of key identifier */
        uint8_t __pad[3];
        uint32_t sig_len;    /* Length of signature data (big endian) */
};


I'm not sure why it was decided to omit this information in the commit
you mentioned and embed it inside the signature blob. I'm CC'ing
Michael who worked on the support for signature in kmod and David who
did that commit.  Ideally kmod would not link to any crypto library.
```

In order to avoid linking with a myriad of crypto libraries to decode the blob just to show the information, I think the signing tool should fill that structure which is the way for the kernel to communicate the high level signature details to kmod. The info would be duplicated since it's available in the blob, but I don't think it really matters.

As suggested by Michael Marek later, I think in kmod we should at least output that the module is signed with PKCS#7 while the signing tool doesn't gain support to fill the useful struct.
