### ISSUE TITLE
Systemd: ExecStartPost docker exec use

### ISSUE THREAD

**Issue by vmatekole** [coreos/bugs#1056]
Hi! 

This is probably not the ideal place to post this but it is my last resort:
I have been struggling for mths now with the following unit:
The ExecStartPost step isn't working - SideKiq refuses to start. I have to manually
launch this command when I restart each app node. Hoping someone might be able to point me in the 
right direction.
```
[Unit]
Description=Spree-Vendservice

# Requirements
Requires=docker.service

# Dependency ordering
After=docker.service
After=docker-registrator.service
After=docker-postgres.service
After=docker-redis.service

[Service]
# Let processes take awhile to start up (for first run Docker containers)
User=core
TimeoutStartSec=60s

# Change killmode from "control-group" to "none" to let Docker remove
# work correctly.
KillMode=none

# Get CoreOS environmental variables
EnvironmentFile=/etc/environment

# Pre-start and Start
## Directives with "=-" are allowed to fail without consequence
ExecStartPre=-/usr/bin/docker kill spree-vend
ExecStartPre=-/usr/bin/docker rm -v spree-vend
ExecStartPre=-/usr/bin/docker pull quay.io/XXXXX/spree-vend:production
ExecStart=/bin/bash -c  "/usr/bin/docker run --name spree-vend \
                             -p $COREOS_PRIVATE_IPV4:8080:3000 \
                             -v /var/log/spree-vend:/apps/spree-vend/log \                             
                             -e SERVICE_NAME=spree-vend \
                             -e \"RAILS_ENV=production\" \                             
                             -e \"SECRET_SPREE_API=\" \
                             -e \"VEND_CLIENT_ID=\" \
                             -e \"SECRET_VEND_API=\" \
                             -e \"SECRET_VEND_ACCESS_TOKEN=\" \
                             -e \"SPREE_API_URL=\" \
                             -e \"SECRET_SPREE_API=\" \
                             quay.io/XXXX/spree-vend:production passenger start -b $COREOS_PRIVATE_IPV4"
ExecStartPost=-/bin/bash -c "/usr/bin/docker exec -it spree-vend sidekiq -C config/sidekiq.yml"
# Stop
ExecStop=/usr/bin/docker stop spree-vend
Restart=always
RestartSec=10

[X-Fleet]
# Don't schedule on the same machine as other nginx instances
Global=true
MachineMetadata="role=app"

**Comment by crawford** [comment]
I just double checked that this works for `simple` service types. My guess is that the `docker exec` is happening long before the `docker run` completes. If you take a look at the service status and logs, I would expect to see a failure. You can use `systemctl status <service name>` and `journalctl -b -u <service name>` to verify this. You will need to either:

 - set the service type to `notify` and use the [sdnotify-proxy](https://github.com/coreos/sdnotify-proxy) to get the signal out of the container
 - poll for a running container in the ExecStartPost

**Comment by vmatekole** [comment]
@crawford Thank you very much for your response, appreciated! That explains a lot - I presumed that each step denoted in a unit happens consecutively and only if the previous step has completed - it appears  asynchonous in behaviour. sdnotify-proxy looks tricky and I am not sure how the 2nd option will work.... That being said... I think I will shamelessly duck the above options and opt to kickstart Sidekiq in a separate unit and set the dependent service accordingly. I have similar issue (not mentioned above) with using *docker cp* on start, such commands - where a running container is dependent will have to be placed in a separate unit.

**Comment by crawford** [comment]
That's the better approach (I forgot that in my first list). DigitalOcean has a pretty good [overview](https://www.digitalocean.com/community/tutorials/how-to-create-flexible-services-for-a-coreos-cluster-with-fleet-unit-files) of the solution.
