### ISSUE TITLE
"id -Z" does not produce expected output

### ISSUE THREAD

**Issue by ae6rt** [coreos/bugs#1059]
On CoreOS 835.9.0, the command _id -Z_ does not produce SELinux context informational output. Instead it produces this

```
# id -Z
id: --context (-Z) works only on an SELinux-enabled kernel
```

On IRC, @mischief says

```
4:49:24 PM	mischief  we don't build coreutils with selinux
4:49:28 PM	mischief  can you file an issue for this?
```

**Comment by ae6rt** [comment]
I should also mention that the _semanage_(8) command is missing.  It would be nice to have it.

**Comment by ae6rt** [comment]
While I'm at it, I might as well ask for setroubleshoot, which I think brings in sealert.  Many thanks.

**Comment by askb** [comment]
Hi, I would like to help fixing this issue, if no one else is working on this. Thanks
