### ISSUE TITLE
SSH host key: is a

### ISSUE THREAD

**Issue by hackzilla** [coreos/bugs#106]
I've followed coreos vmware guide, and chosen stable release.

https://coreos.com/docs/running-coreos/platforms/vmware/

However once the system boots up, the login screen says: SSH host key: is a
and I can't ssh into the VM.

![screen shot 2014-08-11 at 16 46 51](https://cloud.githubusercontent.com/assets/1474182/3878383/c0423ff2-216e-11e4-9a84-63104ab7223c.png)

**Comment by jfoy** [comment]
I just encountered this issue on CoreOS v618.0.0, VMware Fusion Pro v7.1.1, OS X v10.10.2. Thanks for the workaround: enabling autologin, then `sudo rm /etc/ssh/ssh_host_* && sudo systemctl restart sshd-keygen.service` resolved the problem for this host.

**Comment by mischief** [comment]
@sunadm is the ssh keys ever printed on the console? is it simply delayed, or does it never work?

**Comment by lmcdasm** [comment]
Hey there.

Hit the same issue today.
ISO installation from OVF of coreOS stable.
3 machines, all with the same cloud-config and .vmx setup (guestinfo.xyz).. 

2 of the 3 machines came up with no ssh_host_xyz data populated in the files, 1 of the 3 hosts worked without issue.

I used the procedure of wiping out the files and regenerating them listed above 

again 
1 - sudo rm -rf /etc/ssh/ssh_host_*
2 - sudo systemctl restart sshd-keygen.service

doing an ls -l  /etc/ssh/ shows that teh files are not populated with values (before they were all zero byte).

Thanks
Daniel

**Comment by mischief** [comment]
hm, does issuegen need Requires=sshd-keygen.service too?

**Comment by crawford** [comment]
This has nothing to do with issuegen. The keys themselves aren't being generated properly.

**Comment by f0** [comment]
@crawford 
hi, we are hitting this issue with 1010.5.0, reproduced 3 times with fresh installs is it possible to merge the fix?

**Comment by crawford** [comment]
@f0 we are going to try to figure out a root cause before the next Alpha. If we cannot figure out why it's failing, we'll pull in the workaround for now.

**Comment by crawford** [comment]
I'm having trouble reproducing this locally in qemu. If you've seen this failure, can you provide the output of `journalctl -u sshd-keygen --no-pager`?

**Comment by mischief** [comment]
@f0 how can we reproduce this?

**Comment by f0** [comment]
@mischief 
i installed a Bare Metal Server (DELL)
- booted the coreos live iso
- grab the coreos image
- dd the image to disk
- mount the partitions and copy the cloud config 
- adjust grub config to  autologin
- restart the system twice (to got the networking working)

**Comment by crawford** [comment]
@f0 we ran out of time this week (the kernel vuln ate up a good chunk), so I'm going to merge https://github.com/coreos/init/pull/206 for now. This should make it a bit easier to see when there is a failure and its cause. Once this is in Alpha, would you mind keeping an eye out for any failures? Your environment seems to be particularly good at reproducing the failure.

**Comment by f0** [comment]
@crawford  yes i test this if the alpha is released

**Comment by mischief** [comment]
@f0 can you try CoreOS 1109.1.0?

**Comment by f0** [comment]
@mischief  sure, maybe i can do this tomorrow

**Comment by f0** [comment]
@mischief  testet 1109.1.0 the problem is gone

**Comment by f0** [comment]
@mischief  hm wired, i also build a new system with the stable version 1068.8.0, works also without problems
And in found a difference between the systems with the problem, and them without...
The systems with the problem where installed with coreos before (the Disks where not "clean") , the systems without are clean systems without any installation before

**Comment by crawford** [comment]
@f0 I don't think you are going to see any failures with the workaround, but you might see warnings in the logs. Can you check `journalctl -u sshd-keygen.service --no-pager`?

**Comment by f0** [comment]
@crawford  installed stable from scratch, no warnings and the keys are correct

**Comment by crawford** [comment]
@f0 have you noticed any failures? Can you try reproducing in the problematic environment for me?

**Comment by f0** [comment]
@crawford  sure, i am on vacation atm and back in the office in 2 weeks

**Comment by crawford** [comment]
@f0 have you had a chance to test this? I'd like to revert [the workaround](https://github.com/coreos/init/pull/206/commits/90f574ea62be354bd18ec2d6bd87fa22b11b9449) and understand what is actually failing.

**Comment by f0** [comment]
@crawford   tested 
```cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=1164.1.0
VERSION_ID=1164.1.0
BUILD_ID=2016-09-10-0834
PRETTY_NAME="CoreOS 1164.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues```

problem is gone

regards f0

**Comment by crawford** [comment]
@f0 thank you for confirming. I'm going to revert that workaround.

**Comment by crawford** [comment]
Actually, no. The workaround is still needed if the filesystem is uncleanly shutdown. I'm going to leave it in place.
