### ISSUE TITLE
locksmith: Unlocking old locks fail when using remote etcd endpoint

### ISSUE THREAD

**Issue by miguelangel-nubla** [coreos/bugs#1062]
When I configure locksmithd v0.3.4 to use a remote etcd server:

```
Jan 05 19:55:01 worker.example.com systemd[1]: Started Cluster reboot manager.
Jan 05 19:55:01 worker.example.com locksmithd[4046]: locksmithd starting currentOperation="UPDATE_STATUS_IDLE" strategy="best-effort"
Jan 05 19:55:06 worker.example.com locksmithd[4046]: [etcd.service etcd2.service] are inactive
Jan 05 19:55:06 worker.example.com locksmithd[4046]: Unlocking old locks failed: [etcd.service etcd2.service] are inactive. Retrying in 10s.
Jan 05 19:55:16 worker.example.com locksmithd[4046]: [etcd.service etcd2.service] are inactive
Jan 05 19:55:16 worker.example.com locksmithd[4046]: Unlocking old locks failed: [etcd.service etcd2.service] are inactive. Retrying in 20s.
Jan 05 19:55:36 worker.example.com locksmithd[4046]: [etcd.service etcd2.service] are inactive
Jan 05 19:55:36 worker.example.com locksmithd[4046]: Unlocking old locks failed: [etcd.service etcd2.service] are inactive. Retrying in 40s.
```

locksmith should not care about etcd.service and etcd2.service when LOCKSMITHD_ENDPOINT is provided.

**Comment by mischief** [comment]
@miguelangel-nubla why don't you set the strategy to `etcd-lock`? see https://coreos.com/os/docs/latest/update-strategies.html for some details.

**Comment by miguelangel-nubla** [comment]
That eliminates the messages, but still, shouldn't `best-effort` try to connect to the specified endpoints, and reboot only if the connection failed (or after getting the lock)?

In my opinion, it should not complain about local services anyway.

**Comment by crawford** [comment]
`best-effort` should not be used. If you intend to use etcd to manage the locks, use `etcd-lock`.
