### ISSUE TITLE
Ignition: support multi line JSON instead of "\n" using

### ISSUE THREAD

**Issue by kayrus** [coreos/bugs#1064]
Just an example: https://gun.io/blog/multi-line-strings-in-json/

And this config:

```json
{
    "ignitionVersion": 1,
    "systemd": {
        "units": [
            {
                "name": "example.service",
                "enable": true,
                "contents": "[Service]\nType=oneshot\nExecStart=/usr/bin/echo Hello World\n\n[Install]\nWantedBy=multi-user.target"
            }
        ]
    }
}
```

will look like:

```json
{
    "ignitionVersion": 1,
    "systemd": {
        "units": [
            {
                "name": "example.service",
                "enable": true,
                "contents": [
                    "[Service]",
                    "Type=oneshot",
                    "ExecStart=/usr/bin/echo Hello World",
                    "",
                    "[Install]",
                    "WantedBy=multi-user.target"
                ]
            }
        ]
    }
}
```

/cc @philips @crawford

**Comment by crawford** [comment]
Ignition configs are not meant to be handled by humans, so I'm hesitant to abuse the language like this (it's similar `"_comment": "foobar"`) for such a minor gain. This change would also require a spec version bump, so at the very least we'd for a few more changes to bundle together. I'm heavily leaning toward "no" on this one.

**Comment by kayrus** [comment]
Rejections, rejections. Anyway, I've just made some change. And will add some backwards compatibility soon. It will allow to use both arrays and regular strings. https://github.com/endocode/ignition/commit/a6d1e2390d4ea60d710c818bcc763f2fdd48d439

`Ignition configs are not meant to be handled by humans` - we will try to solve that because we still don't have appropriate tool which will simplify this behavior ;)

**Comment by crawford** [comment]
> It will allow to use both arrays and regular strings.

Don't spend too much time on this, because I won't accept it. It is very confusing for a key to accept multiple types and it will very quickly put us right back in the same nightmare that is cloud-config.

> we still don't have appropriate tool which will simplify this behavior

Changing a fairly permanent aspect of the project just to work around a temporary issue doesn't make much sense. We should build the tool rather than hacking up the spec.

**Comment by kayrus** [comment]
@crawford it is already a nightmare. I predict lots of questions regarding improper json formatting and unavailability to easily debug it because it is inside initramfs.
@robszumski, @joshix do you have something to add/comment?

**Comment by crawford** [comment]
> it is already a nightmare

Harsh.

> improper json formatting

Tools will very rarely output improper JSON. I don't anticipate this ever being a problem.

> unavailability to easily debug it because it is inside initramfs

That is why the logs are cranked way up.
