### ISSUE TITLE
Ship "sys-apps/acl" with CoreOS distribution

### ISSUE THREAD

**Issue by kayrus** [coreos/bugs#1073]
I suppose these utils (`setfacl`, `getfacl`) are ones of must-have.

/cc @crawford @marineam objections?

**Comment by mischief** [comment]
fixed in coreos/coreos-overlay@020c5081c37617461461061f2cf7e89d8c53897a

**Comment by crawford** [comment]
@mischief we should explicitly call out this dependency in coreos-base.
