### ISSUE TITLE
Lots of images missing on http://beta.release.core-os.net/amd64-usr/899.1.0/

### ISSUE THREAD

**Issue by schneidexe** [coreos/bugs#1075]
Usually there are 311 files for each (recent) version of the core image. On http://beta.release.core-os.net/amd64-usr/899.1.0/ there are only 226. So it seems a lot of image files do not appear there. I stumbled upon this when looking for the vmware image which is one of the missing ones.

In http://beta.release.core-os.net/amd64-usr/current all are present again. Was there maybe some issue copying/linking those build also the version folder?

**Comment by marineam** [comment]
Looks like the build of 899.1.0 actually failed part way through creating the beta images but no one noticed and promoted 899.1.0 to alpha and then beta anyway.

**Comment by marineam** [comment]
The images that are in current but not in 899.1.0 are left over from the previous beta

**Comment by schneidexe** [comment]
Uh oh, that does not sound good. Thanks for the info and for taking care of it.

**Comment by crawford** [comment]
http://beta.release.core-os.net/amd64-usr/current has been trimmed to only include the correct images. We'll follow up with a 899.2.0.

**Comment by crawford** [comment]
New images were published. Sorry, I forget to report back.

**Comment by schneidexe** [comment]
Recognized that, got 899.3.0 running already... :)
