### ISSUE TITLE
Generating .ssh/authorized_keys is not necessary

### ISSUE THREAD

**Issue by KellerFuchs** [coreos/bugs#1078]
Rather than performing complex locking in `update-ssh-keys`, it would be much simpler to use OpenSSH's `AuthorizedKeysCommand` to collect all the keys.
This is a simple script that can act as a `AuthorizedKeysCommand`; it is however missing a usage line and does not properly handles `authorized_keys.d` files that are not terminated with a newline -- the current `update-ssh-keys` tool doesn't either, but this is extremely undesirable behaviour.

``` sh
#!/bin/sh -e
USER="$1"
HOMEDIR=$(getent passwd "${USER}" | cut -d: -f6)

# Check the globbing doesn't match dotfiles in any POSIX-compliant sh
cat "${HOMEDIR}"/.ssh/authorized_keys.d/* 2>/dev/null
```

That would enable significant simplification of `update-ssh-keys`, in particular its locking.
The process involved in modifying a `authorized_keys.d` file (let's call it `foo`) would be as follows:
1. Create `authorized_keys.d/.foo` then get a lock on it
2. Read the content from `authorized_keys.d/foo` (it is safe to do once we have the lock).
3. Write new content to `authorized_keys.d/.foo` (and flush)
4. Rename it to `authorized_keys.d/foo` (renaming/replacing files is guaranteed to be atomic)
5. Release the lock

Notice there is no need anymore to have a per-user lock anymore, as seems to be currently the case.

**Comment by KellerFuchs** [comment]
I'm surprised by the `area/performance` tag: I reported this because the correctness of the locking performed in `update-ssh-keys` is non-obvious.

But thanks @crawford  for tagging this and taking it under consideration anyway.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
