### ISSUE TITLE
flannel unit should be more flexible

### ISSUE THREAD

**Issue by sigma** [coreos/bugs#1079]
Right now, the flanneld.service reads like this:

```
...
Environment="FLANNEL_VER=0.4.0"
...
ExecStart=... \
  /usr/bin/docker run ... quay.io/coreos/flannel:${FLANNEL_VER} ...
...
```

There are at least 2 issues with this:
- it makes mirroring the flannel image locally more difficult than it should be (since a non-trivial part of the service definition needs to be overloaded by a drop-in)
- when the network is super-slow, starting flannel can easily timeout in the "docker pull" part, which can mess the surrounding automation (convoluted ansible stuff has to be written to work around this)

If instead we had something like an environment file containing

```
FLANNEL_VER=0.4.0
FLANNEL_IMG=quay.io/coreos/flannel
```

then it would be trivial to overload the image to point to a local mirror, and we could force a synchronization point in automation by building a "docker pull" invocation based on that same file *before* trying to start the service (so that the systemd part would be just fine). Although if the image was indeed local, that probably wouldn't even be needed.

**Comment by crawford** [comment]
+1
