### ISSUE TITLE
unexpected reboot on VM Xen 

### ISSUE THREAD

**Issue by Energy1190** [coreos/bugs#1080]
Hi.

installed CoreOS 835.9.0
Unexpected reboot occur about once a week.
I can not understand what is the reason?
[20-01-2016.txt](https://github.com/coreos/bugs/files/99298/20-01-2016.txt)

**Comment by mischief** [comment]
CoreOS automatically updates. you can read more about it [here](https://coreos.com/os/docs/latest/update-strategies.html). you can configure the system to not automatically reboot, but you will not have the update applied automatically.

**Comment by mischief** [comment]
sorry, i didn't realize initially this was a kernel panic. can you reproduce this on beta (899.4.0) or alpha (933.0.0)? is this on aws? if so, what is the ami id?

**Comment by Energy1190** [comment]
Yes, it aws. AMI - CoreOS-stable-717.3.0-hvm (ami-6b1cd400). I went to the beta (899.4.0), but I can not reproduce restart, because I can not find a reason.

**Comment by Energy1190** [comment]
In the beta channel, the problem is not repeated.
