### ISSUE TITLE
locksmithd service fails with 'resources' result code, update docs?

### ISSUE THREAD

**Issue by icheko** [coreos/bugs#1085]
When following the steps in https://coreos.com/os/docs/latest/update-strategies.html#auto-updates-with-a-maintenance-window

I receive this on startup - but I'm guessing once https://github.com/coreos/locksmith/pull/94 is fixed this will go away.
```bash
core@CoreOS_7 ~ $ systemctl status locksmithd.service
● locksmithd.service
   Loaded: masked (/dev/null)
   Active: failed (Result: resources) since Fri 2016-01-22 00:54:24 UTC; 3min 7s left
 Main PID: 655 (code=exited, status=0/SUCCESS)

Jan 22 00:54:24 CoreOS_7 systemd[1]: locksmithd.service: Service hold-off time over, scheduling restart.
Jan 22 00:54:24 CoreOS_7 systemd[1]: locksmithd.service: Failed to schedule restart job: Unit locksmithd.service is masked.
Jan 22 00:54:24 CoreOS_7 systemd[1]: locksmithd.service: Unit entered failed state.
Jan 22 00:54:24 CoreOS_7 systemd[1]: locksmithd.service: Failed with result 'resources'.
Jan 22 00:54:25 CoreOS_7 systemd[1]: Stopped locksmithd.service.
```
```bash
NAME=CoreOS
ID=coreos
VERSION=835.10.0
VERSION_ID=835.10.0
BUILD_ID=
PRETTY_NAME="CoreOS 835.10.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
--
https://github.com/coreos/bugs/issues/1011#issuecomment-162612427 pointed out that reboot windows is already supported by locksmithd.
```yml
#cloud-config

coreos:
  locksmith:
    window_start: "Sat 10:00"
    window_length: "30h"
```
Maybe worth updating docs? Definitely cleaner.

**Comment by crawford** [comment]
The docs have been updated (https://coreos.com/os/docs/latest/update-strategies.html#auto-updates-with-a-maintenance-window). Unfortunately, that race condition remains and cannot be fixed. We are encouraging users to switch to [Ignition](https://coreos.com/ignition) if possible.
