### ISSUE TITLE
Orphaned docker containers

### ISSUE THREAD

**Issue by Zapadlo** [coreos/bugs#1086]
We are seeing several instances where docker containers remain running after fleet has stopped controlling them, resulting in orphaned containers running for days while fleet is now controlling a different container of the same service on a different machine.

One such container I found had uptime of 6 days and looking at the service logs from 6 days prior:

```
Jan 15 08:45:35 ip-172-24-179-97.eu-west-1.compute.internal systemd[1]: methode-article-transformer@1.service: State 'stop-sigterm' timed out. Killing.
Jan 15 08:45:35 ip-172-24-179-97.eu-west-1.compute.internal systemd[1]: methode-article-transformer@1.service: Main process exited, code=killed, status=9/KILL
Jan 15 08:45:35 ip-172-24-179-97.eu-west-1.compute.internal systemd[1]: Stopped methode-article-transformer@1.service.
Jan 15 08:45:35 ip-172-24-179-97.eu-west-1.compute.internal systemd[1]: methode-article-transformer@1.service: Unit entered failed state.
Jan 15 08:45:35 ip-172-24-179-97.eu-west-1.compute.internal systemd[1]: methode-article-transformer@1.service: Failed with result 'signal'.
```

Part of the service file:

```
ExecStart=/bin/sh -c '\
  /usr/bin/docker run --rm --name %p-%i -p 8080 -p 8081 [redacted]'
ExecStop=/usr/bin/docker stop -t 3 %p-%i
```

CMD of the Dockerfile:

```
CMD java -Ddw.server.applicationConnectors[0].port=8080 \
     -Ddw.server.adminConnectors[0].port=8081 \
     ....
     -jar app.jar server config.yaml
```

Running ps inside the container:

```
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c java -Ddw.server.applicationConnectors[0].port
    9 root      12:15 java -Ddw.server.applicationConnectors[0].port=8080 -Ddw.
 6628 root       0:00 ps
```

I wanted to try changing the CMD to exec form (`CMD ["executable","param1","param2"]`) but we are passing command line arguments to the application so those need to be interpolated.

We are running stable version, currently (835.10.0) in most of our clusters.

Please advise if anyone else seen this issue to potential steps to debug.

Thanks!

**Comment by crawford** [comment]
Is this still an issue?

**Comment by Zapadlo** [comment]
@tamas-molnar @catalin-ilea ^^

**Comment by catalin-ilea** [comment]
@crawford The problem was in our Dockerfiles. Wrapping the main process in a shell was causing SIGINT/SIGTERM not to reach the main process. So you can close the issue from our point of view.

**Comment by crawford** [comment]
Oh, excellent. Glad you got it sorted out.
