### ISSUE TITLE
Beta release kernel regressed support for Xen PV guests

### ISSUE THREAD

**Issue by tanuck** [coreos/bugs#1087]
Hi,

I'm not 100% which beta release has caused this, but all our beta nodes have been running the CPU at 100%. With the cpu cycles taken up by the kernel and irq's. After a lot of digging around, I managed to uncover a regression in the 4.3 linux kernel affecting Xen PV guests. For me, this causes all of the nodes running on older PV EC2 images to become very unresponsive.

Recompiling the kernel with [this](https://github.com/coreos/linux/commit/d8c98a1d1488747625ad6044d423406e17e99b7a) patch, or updating to the alpha release fixes this problem.

Here's a more involved explanation of the cause: [http://lkml.iu.edu/hypermail/linux/kernel/1512.1/03504.html](http://lkml.iu.edu/hypermail/linux/kernel/1512.1/03504.html)

I hope this can get fixed before the 4.3 kernel is introduced to stable!

Kind regards

**Comment by crawford** [comment]
This was fixed upstream in https://github.com/coreos/linux/commit/d8c98a1d1488747625ad6044d423406e17e99b7a. We either need to backport this to 4.3 or jump straight to 4.4.

**Comment by tanuck** [comment]
Either would work, I just really don't want to see this problem land in to the stable branch!

**Comment by marineam** [comment]
FYI, that patch landed in 4.3.5 but I think beta has remained on 4.3.3. We'll need to bump the kernel.

**Comment by marineam** [comment]
4.3.6 is also available

**Comment by mischief** [comment]
fixed by https://github.com/coreos/coreos-overlay/pull/1785

**Comment by tanuck** [comment]
:+1:
