### ISSUE TITLE
docker starts before var-lib-docker.mount with ext4 at reboot

### ISSUE THREAD

**Issue by arthur-c** [coreos/bugs#1088]
Hi,

I'm using /var/lib/docker on a volume in ext4 for few nodes and after their reboot with the 835.10.0 stable update my units did not restart. Docker started before the mount unit then the mount unit overwrite /var/lib/docker (despite Before=docker.service).
I can reproduce the problem easily. It never fails while bootsraping a node, only at reboot, each time:

```
var-lib-docker.mount: Directory /var/lib/docker to mount over is not empty, mounting anyway.
docker[874]: open /var/lib/docker/repositories-overlay: no such file or directory
```

I can't reproduce with btfrs, docker always wait the mount.

RequiresMountsFor=/var/lib/docker in a drop-in for docker.service doesn't solve the problem.

More details (cloud-config, log with ext4 at reboot, log with btrfs): 
https://gist.github.com/arthur-c/9aec3cb157014169299b

Nodes are on aws with ebs storage.

**Comment by crawford** [comment]
FYI, `Before=docker.service` has no effect unless you also `Require` or `Wants` `docker.service` as well.

In your logs for ext4, it looks like Docker starts running before cloud-init actually has a chance to write the mount unit. On CoreOS, Docker doesn't run by default, so you must be triggering its start earlier in your config (nrsysmond?). Make sure the mount unit and format service are the first two things in your config.

**Comment by arthur-c** [comment]
Thanks for the hint, I found a solution.
I reproduced the problem, the cloud-init is wrote but fleet triggers docker.service despite docker.service requirements.

I fixed the problem with this drop-in:

```
    - name: fleet.service
      drop-ins:
        - name: 10-wait-docker.conf
          content: |   
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount
      command: start 
```
but also with 'Before=fleet.service' in my var-lib-docker.mount unit in my cloud-init (without the above drop-in)

My guess is that systemd doesn't handle cascading dependencies. Fleet triggers docker and docker ignores its requirements... seems weird to me, but I'll search the systemd doc later. It might not happening with btrfs because it might be faster to format than ext4.

**Comment by arthur-c** [comment]
Anyhow, https://coreos.com/os/docs/latest/mounting-storage.html#use-attached-storage-for-docker is buggy at the moment.

**Comment by crawford** [comment]
Ah yes, we need to update that document. I think the more correct fix would be to add the drop-in to docker.service.

```yaml
    - name: docker.service
      drop-ins:
        - name: 10-wait-docker.conf
          content: |   
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount 
```

Just make sure this unit appears before everything else to ensure that it's in place before docker is activated.
