### ISSUE TITLE
Not possible to copy CoreOS AWS AMI storage snapshot

### ISSUE THREAD

**Issue by tobiemh** [coreos/bugs#1090]
When using AWS it is possible to launch the official CoreOS AMIs, but is not possible to copy them - instead getting this error message: "You do not have permission to access the storage of this ami".

Although the AMI itself is public, the underlying snapshot is not public, therefore preventing copying, and preventing the ability to copy the snapshot to an encrypted snapshot in order to enable root volume encryption.

Is there a reason that the underlying storage is not publicly accessible, or could this be enabled?

**Comment by osterman** [comment]
+1 we need this to increase cluster stability. if snapshots are deleted it messes up our autoscaling groups.

**Comment by githubuseracct** [comment]
+1. My company cannot always move at the same pace of external forces due to the sheer size of our infrastructure and it would add a LOT of peace of mind to know that an AMI we rely on won't accidentally or intentionally disappear. Thanks!

**Comment by opsline-radek** [comment]
+1. Is there a plan to make the image snapshots public so that images can be copied and encrypted?

**Comment by seanknox** [comment]
Hey @crawford, could you help with removing the copy-restriction on the CoreOS AMI? As @tobiemh described, because underlying snapshop used by the AMI isn't public, it's not possible to copy the AMI, and thus not possible to setup encrypted root volumes. This makes Kubernetes+CoreOS is a no go without for many folks.

**Comment by crawford** [comment]
We are going to go ahead and make this change. I'll report back once the snapshots have been updated.

**Comment by seanknox** [comment]
Thanks @crawford!

**Comment by seanknox** [comment]
Hey @crawford, do you know when these CoreOS AWS snapshots are slated to get in? Our team is putting together a "howto" for building for HITECH/HIPAA on AWS with Kubernetes that we'd like to open source, but this is a blocker.

**Comment by crawford** [comment]
@seanknox it's on our 1221.0.0 milestone, which should be completed in a week.

**Comment by meonkeys** [comment]
@seanknox will you keep me in the loop about that howto? I'd like to read it and possibly even contribute.

Cc: @iameli, @skifaster, @tylerhartley, @harleyholt

(we run HITECH/HIPAA-compliant k8s clusters on AWS for https://github.com/csats )

**Comment by crawford** [comment]
I've gone ahead and marked the latest snapshot in each channel public. I'm going to close this out now.

**Comment by seanknox** [comment]
Thanks very much @crawford!

```
$ aws ec2 describe-images --image-ids ami-4d795c5a
{
    "Images": [
        {
            "VirtualizationType": "hvm",
            "Name": "CoreOS-stable-1185.3.0-hvm",
            "Hypervisor": "xen",
            "SriovNetSupport": "simple",
            "ImageId": "ami-4d795c5a",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/xvda",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-8c39603a",
                        "VolumeSize": 8,
                        "VolumeType": "standard",
                        "Encrypted": false
                    }
                },
                {
                    "DeviceName": "/dev/xvdb",
                    "VirtualName": "ephemeral0"
                }
            ],
            "Architecture": "x86_64",
            "ImageLocation": "595879546273/CoreOS-stable-1185.3.0-hvm",
            "RootDeviceType": "ebs",
            "OwnerId": "595879546273",
            "RootDeviceName": "/dev/xvda",
            "CreationDate": "2016-11-01T08:03:49.000Z",
            "Public": true,
            "ImageType": "machine",
            "Description": "CoreOS stable 1185.3.0 (HVM)"
        }
    ]
}

$ aws ec2  describe-snapshots --snapshot-ids snap-8c39603a
{
    "Snapshots": [
        {
            "Description": "Copied for DestinationAmi ami-4d795c5a from SourceAmi ami-6f1eb80f for SourceSnapshot snap-2cd4cf01. Task created on 1,477,987,429,501.",
            "Encrypted": false,
            "VolumeId": "vol-ffffffff",
            "State": "completed",
            "VolumeSize": 8,
            "Progress": "100%",
            "StartTime": "2016-11-01T08:03:58.000Z",
            "SnapshotId": "snap-8c39603a",
            "OwnerId": "595879546273"
        }
    ]
}
```
