### ISSUE TITLE
running rkt install on first boot

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1094]
In order to do permissions correctly inside of rkt we have the tool `rkt install` which sets up the /var/lib/rkt directory with permissions for the `rkt` group to fetch. Without this the first run experience on CoreOS is lame:

Before:
```
core@core-01 ~ $ rkt fetch coreos.com/etcd,version=v2.3.1
fetch: cannot open store: mkdir /var/lib/rkt/cas: permission denied
```

After:

```
core@core-01 ~ $ rkt fetch coreos.com/etcd,version=v2.3.1
rkt: searching for app image coreos.com/etcd
```

I think we should run `rkt install` on first boot as it is something like a systemd generator that does /etc/machine-id setup, etc. 

cc @alban @jonboulle

**Comment by philips** [comment]
add @crawford too.

**Comment by crawford** [comment]
Is there anyway we could get a tmpfiles equivalent of `rkt install`?
Does it hurt to run `rkt install` multiple times?

**Comment by jonboulle** [comment]
It should be idempotent; if not we can make it that way.

**Comment by philips** [comment]
@crawford running rkt install multiple times _should_ be safe. @alban ?

**Comment by crawford** [comment]
What about the first option? I don't feel great about blocking system boot with an enormous Go binary.

**Comment by alban** [comment]
Sorry I didn't notice this issue before.

See the fix in https://github.com/coreos/rkt/pull/2088/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR38

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/1757/files#diff-534c632c395d27e1063bdd6c4a9b7679R135 instead.
