### ISSUE TITLE
installing coreos over ubuntu 14.04

### ISSUE THREAD

**Issue by mvdhoning** [coreos/bugs#1101]
On a virtualbox machine i installed a minimal ubuntu 14.04 from the mini.iso. All i added was openssh to be able to connect to it via ssh.

Next i retrieved the coreos installer script from:
wget https://raw.github.com/coreos/init/master/bin/coreos-install 

and gave it the proper rights and made a cloud-config file. For the cloud-config file i followed instructions at: https://www.binarysludge.com/2014/10/02/installing-coreos-on-bare-metal-at-ovh/

when running the installer it goes do a segfault (i am running it as root):

```
root@ubuntu:/home/user# ./coreos-install -d /dev/sda -C stable -c ./cloud-config./coreos-install: coreos-cloudinit not found. Could not validate config. Continuing...
Downloading the signature for http://stable.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2...
2016-01-29 20:10:18 URL:http://stable.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2.sig [543/543] -> "/tmp/coreos-install.fNNHVVO8vq/coreos_production_image.bin.bz2.sig" [1]
Downloading, writing and verifying coreos_production_image.bin.bz2...
2016-01-29 20:12:05 URL:http://stable.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2 [214915999/214915999] -> "-" [1]
./coreos-install: line 309:   954 Done                    wget --inet4-only --no-verbose -O - "${IMAGE_URL}"
       955                       | tee >(bunzip2 --stdout >"${DEVICE}")
       956 Segmentation fault      | gpg --batch --trusted-key "${GPG_LONG_ID}" --verify "${WORKDIR}/${SIG_NAME}" -
139: GPG signature verification failed for coreos_production_image.bin.bz2
./coreos-install: line 309:   963 Segmentation fault      wipefs --all --backup "${DEVICE}"
./coreos-install: line 1:   964 Segmentation fault      wipefs --all --backup "${DEVICE}"
root@ubuntu:/home/user# ls
Segmentation fault
root@ubuntu:/home/user#
```

also on:
http://pastebin.com/ZNE7TXFR

**Comment by crawford** [comment]
It looks like ubuntu's `wget` segfaulted. Just use CoreOS [from the start](https://coreos.com/os/docs/latest/booting-with-iso.html).

**Comment by mvdhoning** [comment]
in the end i want to install in a vps and there i cannot use an .iso there
it also fails on centos7 and debian 8 is wget broken on all those platforms?
also when it fails it should not continue with installing as that gives me an broken system.
pre download and check and then install it?

**Comment by mvdhoning** [comment]
on debian gpg is complaining about an invalid packet on keydbsearch next it states that the public key cannot be found

**Comment by FirefighterBlu3** [comment]
@mvdhoning delete and re-add your ed25519 key(s) from your keyring. it is a bug in gnupg agent, they added a prefix character in the agent protocol for those keys.
