### ISSUE TITLE
Overlay: Add an [Install] section to flanneld.service

### ISSUE THREAD

**Issue by danderson** [coreos/bugs#1102]
I have automation set up to configure flanneld on machine installation via Ignition. However, Ignition is unable to enable flanneld, because the systemd unit file provided in the coreos image doesn't have an [Install] section. Per the semantics of systemd units, this section cannot be provided in a drop-in unit, which leaves Ignition no way of setting flannel to start automatically on system boot.

Please consider adding an [Install] section to coreos-overlay/app-admin/flannel/files/flanneld.service that targets multi-user.target (like e.g. locksmithd does). Happy to provide a PR for this as well, if there's no objection.

**Comment by mischief** [comment]
systemctl add-wants and systemctl add-requires commands can accomplish a
similar goal regardless of the [Install] section of a unit. The [Install]
section usually just determines what symlinks will be created as part of
systemctl enable.

**Comment by danderson** [comment]
Unlike cloud-config, Ignition doesn't let you run arbitrary commands, so I can't make it run systemctl add-wants/add-requires without setting up a rube goldberg device of one-time units. The only operation it supports is enabling a systemd unit by making use of its [Install] section. Given the choice between adding an [Install] section to flannel, and adding a non-orthogonal config mechanism to Ignition to work around missing install sections, adding [Install] seems much cleaner.

**Comment by marineam** [comment]
Yup, this needs to happen. The missing install section is an artifact from cloudinit days where enabling etcd dependent services instead of starting them directly would generally cause problems.
