### ISSUE TITLE
Ignition: support user/group names for file ownership

### ISSUE THREAD

**Issue by danderson** [coreos/bugs#1104]
Ignition's spec currently specifies file ownership as numeric uid+gid. In practice, this means that you can only set ownership to root or users/groups that you have created with a specific ID.

Specifically, this means that you can't set files to be owned by well-known CoreOS role accounts like "etcd", because there's no guarantee (that I know of?) that the baselayout will never change the ID associated with those accounts.

This gets in the way of installing credentials for etcd2 and kubernetes via Ignition, because I can't easily change the ownership of the private keys to "etcd", so that the daemon can read them. I can work around it by adding a systemd drop-in that chowns files as an ExecuteStartPre step, but that's quite clunky, and further sends the signal that the uid/gid fields in ignition file specs are useless, because in practice you should just write out everything as root and chown them at runtime.

Please consider having "owner" and "group" fields in the ignition file spec, and have Ignition resolve those to uid/gid at execution time by examining the union of /etc and baselayout account files.

**Comment by felixsanz** [comment]
+1

It's hard to assign permissions to "core" user when you don't know what ID the user has.
