### ISSUE TITLE
Support for osx 10.11.x

### ISSUE THREAD

**Issue by motisaroka** [coreos/bugs#1109]
Does this code should getting complied for OSX 10.11.x ?

**Comment by xied75** [comment]
CoreOS is an Operating System, not an app, do you mean CoreOS should be able to run on a Mac hardware or you want cross-compile CoreOS on a Mac or you really mean that you want run CoreOS within OSX without a hypervisor?

**Comment by motisaroka** [comment]
I am talking about the updateEngine project which is part of CoreOS.
https://github.com/coreos/update_engine
I want to create a demo on OSX using updateEngine code to demonstrate an update process of a specific component - Generally it should be the same as Omaha does.

**Comment by crawford** [comment]
Update Engine is designed and maintained to run exclusively on CoreOS. Supporting other operating systems, especially proprietary ones, is outside the scope of the project.
