### ISSUE TITLE
Locksmith: document whether the semaphore format is stable

### ISSUE THREAD

**Issue by danderson** [coreos/bugs#1111]
I'd like to write software that interacts with the locksmithd semaphore in Etcd directly, to implement smarter "disruption scheduling" in my cluster (e.g. prevent reboots while Ceph is repairing from a drive failure). The format is documented at https://github.com/coreos/locksmith , but it'd be nice to know whether I should expect this format to change in incompatible ways, or if I can rely on it.

**Comment by mischief** [comment]
@danderson can you simply use a systemd inhibitor for this? https://www.freedesktop.org/software/systemd/man/systemd-inhibit.html

although, i don't think a whole lot of thought has been given to the interaction of locksmith and inhibitors.

**Comment by danderson** [comment]
Neat, I didn't know about inhibitors. Yeah, that's a much nicer way of doing what I want than messing with locksmith internals. I'll go play with that and open bugs if locksmith behaves poorly under those conditions, thanks!

**Comment by mischief** [comment]
the only problem i can think of is that locksmith would get the etcd lock and then attempt to shutdown, but the shutdown is blocked by an inhibitor, so the etcd lock is held until the inhibitor is gone. i don't think this situation has been explored, so reporting back with your findings would be great if we don't get to it first.

**Comment by danderson** [comment]
Yeah, that would be fine for my particular use case, because I would simultaneously inhibit reboots on the entire locksmith group, so I'm not losing out on any concurrency. I think as long as the inhibit is a superset of a locksmith group, the semantics remain correct.

It'd be nice to also integrate locksmith with the local inhibitor API, so that it can play nicely there, but I'm not sure that's easy to get right.
