### ISSUE TITLE
locksmith: integrate with kubelet

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1112]
We need to think through how locksmith will integrate with kubernetes and the kubelet. For example perhaps the locksmithd daemon needs to present a filesystem based API that the kubelet can consume to know when an update is applied and the node is ready for reboot. This would be something like the node out of disk or node ready state: https://github.com/kubernetes/kubernetes/blob/c4b66f66f3fb1d1f284b3b67a8df276d246cf8bf/pkg/kubelet/kubelet.go#L2865

![screen shot 2016-02-09 at 3 46 17 pm](https://cloud.githubusercontent.com/assets/33544/12934648/f84799da-cf44-11e5-8b3a-31d17d3bd8ed.png)

**Comment by mischief** [comment]
@philips what exactly is a `filesystem based API`?

i'd be more in favor of a http/rest/json or gRPC api than anything involving on-disk files, but then we need to maintain some kind of client library for locksmithd.

**Comment by philips** [comment]
Potential upstream topics:

https://github.com/kubernetes/kubernetes/issues/1535
https://github.com/kubernetes/kubernetes/issues/7351

**Comment by philips** [comment]
@mischief Yea, it just depends on what upstream k8s will find acceptable

**Comment by philips** [comment]
Closing in favor of https://github.com/coreos/bugs/issues/1274 which has a design doc.
