### ISSUE TITLE
CoreOS 955.0 /dev/sda3 has unsupported feature(s) - e2fsck: Get a newer version of e2fsck!

### ISSUE THREAD

**Issue by andrewwebber** [coreos/bugs#1125]
Machines, after an update, can only partially boot successfully.

The new partition is not able to be mounted due to the following error:

/dev/sda3 has unsupported feature(s): FEATURE_R24 FEATURE_R25 FEATURE_R26 FEATURE_R27 FEATURE_R28 FEATURE_R29 FEATURE_R30 FEATURE_R31

This results in, amoungst other issues, cloud init not being executed - etcd/fleet not running, big problems.

cloud config file (/var/lib/coreos-install/user_data) is still accessible

After a manual roll back everything is fine.

```bash
Feb 18 11:07:23 localhost systemd[1]: Starting dracut pre-mount hook...
Feb 18 11:07:23 localhost systemd[1]: Reached target Remote File Systems (Pre).
Feb 18 11:07:23 localhost systemd[1]: Reached target Remote File Systems.
Feb 18 11:07:23 localhost systemd-fsck[1068]: ROOT: clean, 3432883/144800320 files, 25218371/145632763 blocks
Feb 18 11:07:23 localhost systemd[1]: Started File System Check on /dev/disk/by-label/ROOT.
Feb 18 11:07:23 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-fsck-root comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? r
Feb 18 11:07:23 localhost systemd[1]: Started dracut pre-mount hook.
Feb 18 11:07:23 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-pre-mount comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? re
Feb 18 11:07:23 localhost kernel: audit: type=1130 audit(1455793643.199:12): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-fsck-root comm="systemd" exe="/usr/lib64/systemd/systemd" hos
Feb 18 11:07:23 localhost kernel: audit: type=1130 audit(1455793643.220:13): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=dracut-pre-mount comm="systemd" exe="/usr/lib64/systemd/systemd" host
Feb 18 11:07:23 localhost systemd[1]: Mounting /sysroot...
Feb 18 11:07:23 localhost systemd[1]: Starting File System Check on /dev/disk/by-partuuid/7130c94a-213a-4e5a-8e26-6cce9662f132...
Feb 18 11:07:23 localhost systemd-fsck[1085]: /dev/sda3 has unsupported feature(s): FEATURE_R24 FEATURE_R25 FEATURE_R26 FEATURE_R27 FEATURE_R28 FEATURE_R29 FEATURE_R30 FEATURE_R31
Feb 18 11:07:23 localhost systemd-fsck[1085]: e2fsck: Get a newer version of e2fsck!
Feb 18 11:07:23 localhost systemd-fsck[1085]: fsck failed with error code 8.
Feb 18 11:07:23 localhost systemd-fsck[1085]: Ignoring error.
Feb 18 11:07:23 localhost systemd[1]: Started File System Check on /dev/disk/by-partuuid/7130c94a-213a-4e5a-8e26-6cce9662f132.
Feb 18 11:07:23 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-fsck@dev-disk-by\x2dpartuuid-7130c94a\x2d213a\x2d4e5a\x2d8e26\x2d6cce9662f132 comm="syst
Feb 18 11:07:23 localhost systemd[1]: Mounted /sysroot.

```

**Comment by kayrus** [comment]
I have the same log on my coreos node:

```
Feb 18 14:45:26 localhost systemd-fsck[272]: /dev/vda4 has unsupported feature(s): FEATURE_R24 FEATURE_R25 FEATURE_R26 FEATURE_R27 FEATURE_R28 FEATURE_R29 FEATURE_R30 FEATURE_R31
Feb 18 14:45:26 localhost systemd-fsck[272]: e2fsck: Get a newer version of e2fsck!
Feb 18 14:45:26 localhost systemd-fsck[272]: fsck failed with error code 8.
Feb 18 14:45:26 localhost systemd-fsck[272]: Ignoring error.
```

But it doesn't harm `coreos-cloudinit`. Can you provide `coreos-cloudinit` logs?

```sh
journalctl _EXE=/usr/bin/coreos-cloudinit -b --no-pager
```

**Comment by andrewwebber** [comment]
I just found another azure machine with this issue

My test has always been to view etcd2

```bash
sudo systemctl cat etcd2
```

expected

```bash
# /usr/lib64/systemd/system/etcd2.service
[Unit]
Description=etcd2
Conflicts=etcd.service
...

# /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
...
```

However the following is the case post upgrade
```bash
# /usr/lib64/systemd/system/etcd2.service
[Unit]
Description=etcd2
Conflicts=etcd.service

[Service]
...
```

here is the output from your command on one machine with this problem:

```bash
-- No entries --
```

attached is the boot log

[boot.txt](https://github.com/coreos/bugs/files/136377/boot.txt)

**Comment by crawford** [comment]
This is probably a dup of https://github.com/coreos/bugs/issues/1120.

**Comment by andrewwebber** [comment]
@crawford was also my hunch however i was not sure as I am not using iPXE

**Comment by crawford** [comment]
That change, unfortunately, affected all platforms.

**Comment by andrewwebber** [comment]
I also have an old azure tracking the alpha channel has similar issues however additional log information.

However then catting etcd2 I still dont see the expected:
# /run/systemd/system/etcd2.service.d/20-cloudinit.conf

[azure.txt](https://github.com/coreos/bugs/files/136392/azure.txt)

**Comment by andrewwebber** [comment]
[Azure] Looks like only some units maybe affected as etcd does not have a 20-cloudinit.conf however fleet does. Unfortunately etcd2 is too critical to not have working

```bash
systemctl cat fleet
# /usr/lib64/systemd/system/fleet.service
[Unit]
Description=fleet daemon

After=etcd.service
After=etcd2.service

Wants=fleet.socket
After=fleet.socket

[Service]
Environment=GOMAXPROCS=1
ExecStart=/usr/bin/fleetd
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target

# /run/systemd/system/fleet.service.d/20-cloudinit.conf
[Service]
Environment="FLEET_METADATA=role=webserver"

**Comment by crawford** [comment]
Can you provide a copy of your config so I can try to reproduce this?

**Comment by kayrus** [comment]
@crawford it is reproducible in fleet functional tests, when you run them on alpha. these tests spawn coreos instances as a container and sometimes cloud-config is not applied.

https://github.com/endocode/fleet/tree/kayrus/docker_test

how did I debug that (not perfect instructions, sorry, didn't have lot time):

* checkout fleet from this repo inside latest alpha coreos instance and run `sudo ./functional/test`
* when you'll see lots `Dialing` logs (it will try to ssh into nspawned container), just press ctrl+c to stop tests. you'll get running containers. then list them using `machinectl list`
* change dir to /tmp/smoke/*nspawn_id* and set password for core user into `./fs/etc/shadow` (i.e. run `sudo passwd core`, then cat /etc/shadow > ./fs/etc/shadow)
* enter nspawned container: `machinectl login *nspawn_id*` and login as core. now you can get logs and debug instance.

**Comment by andrewwebber** [comment]
@crawford let me know if you need more information from me however I am assuming based upon @kayrus comments that you have everything you need to re-produce the bug

**Comment by crawford** [comment]
Should be fixed by https://github.com/coreos/coreos-cloudinit/pull/416.

**Comment by andrewwebber** [comment]
is this fixed in 970.1.0?

**Comment by devurandom** [comment]
1. The fix was included in coreos-cloudinit-1.9.1: https://github.com/coreos/coreos-cloudinit/releases/tag/v1.9.1
2. coreos-cloudinit-1.9.1 was included in coreos-969.0.0: https://github.com/coreos/manifest/releases/tag/v969.0.0

Assuming that 970.1.0 is based off of 969.0.0, this should be fixed in the former.

**Comment by crawford** [comment]
970.1.0 included coreos-cloudinit 1.9.1: http://alpha.release.core-os.net/amd64-usr/970.1.0/coreos_production_image_packages.txt

**Comment by andrewwebber** [comment]
@crawford thats, i must have missed it in the coreos release notes https://coreos.com/releases/

**Comment by devurandom** [comment]
@andrewwebber You did not. It is missing in there.

**Comment by celevra** [comment]
got this error on 
Container Linux by CoreOS stable (1235.9.0)

what do you need to dig deeper into this?
