### ISSUE TITLE
enable vimdiff in coreos distribution

### ISSUE THREAD

**Issue by kayrus** [coreos/bugs#1126]
vimdiff is supported within `normal` feature. right now vim portage uses `tiny` feature - https://github.com/coreos/portage-stable/blob/master/app-editors/vim/vim-9999.ebuild#L170

https://github.com/vim/vim/blob/master/src/auto/configure#L4781

disk size difference between `tiny` vim and `normal` vim is 1M.

/cc @mattthias @marineam @mischief

**Comment by kayrus** [comment]
relates to #1073 #1105

**Comment by mischief** [comment]
any particular reason to have this in base? presumably vimdiff can be used from the toolbox or other container if needed.

**Comment by kayrus** [comment]
@mischief have you ever tried to run tollbox on clear coreos? it takes ~5 minutes depending on quay load (75 Mb). Then, you have to install "vim" package. which also consumes (43+20 mb of package cache with the unbelievably speed). then you have to down vim itself (another 8M). So in total you will download 146 Mb to run vimdiff. and in total 5 minutes depending on internet speed / registry load.

**Comment by crawford** [comment]
Well first off, we don't pull the toolbox from quay, so its load would have no effect on your download speed. Second, if bandwidth is an issue, you can build a custom toolbox image with vimdiff already installed and then use `.toolboxrc` to override the default image. If that's still not enough, you could build a container image containing only vimdiff.

**Comment by kayrus** [comment]
Don't want to argue more. Just want to notice `setfacl` and `bind-tools` which were not available in CoreOS at some point. And I understand when everyone will ask for some tool CoreOS image will consume >1G of disk space.

**Comment by crawford** [comment]
We won't be adding this due to the size and complexity.
