### ISSUE TITLE
update all documentation to refer to etcd2

### ISSUE THREAD

**Issue by mischief** [coreos/bugs#1128]
documentation such as https://coreos.com/etcd/docs/latest/clustering.html invokes a 'etcd' binary, which will run etcd 0.4.9 on coreos. the documentation should be changed to invoke the etcd2 binary, otherwise the documentation is confusing for users.

**Comment by aknuds1** [comment]
See https://github.com/coreos/etcd/pull/4575.

**Comment by mischief** [comment]
wrt @xiang90's comment in https://github.com/coreos/etcd/pull/4575 it might be better to just update the etcd documentation have a note about the naming in CoreOS, and update references in CoreOS documentation in https://github.com/coreos/docs to use 'etcd2'.

cc @robszumski

**Comment by xiang90** [comment]
@mischief I think CoreOS doc should reflect this, not etcd doc. Most people using CoreOS will read the doc in CoreOS. Moreover OS controls the binary naming, not etcd community. For example, some OS ships etcd as coreos-etcd, some as coreosetcd, some as etcd, some as etcd2. It would be hard for us to track all the names and doc inside etcd repo.

**Comment by aknuds1** [comment]
I think the thing to do is for CoreOS docs to not link directly to etcd docs, but have its own etcd documentation that uses `etcd2` in its reference commands so that they actually work.

**Comment by aknuds1** [comment]
@xiang90 Agreed.

**Comment by robszumski** [comment]
The problem here is that there are two audiences for viewing etcd documentation on coreos.com:

1. regular non-CoreOS etcd users: this group is used to using `etcd`
2. CoreOS users: this group is used to using `etcd2`

Which one do we choose? Having a completely separate set of docs isn't feasible.

**Comment by aknuds1** [comment]
@robszumski I would expect at least that documentation pertaining to CoreOS works in the context of CoreOS, which is currently not the case. If pure etcd documentation also exists on coreos.com (I don't know enough about the CoreOS project to say), I'd say that this documentation should be factored out. Maybe you'd want to generate two sets of docs from the same sources, to cater to the different cases.

**Comment by euank** [comment]
We now have a specific `Working with container linux` subsection on the etcd page here: https://coreos.com/etcd/docs/latest/

This section refers to the correct binaries, units, etc, which should solve this problem.
