### ISSUE TITLE
crash, possibily due to btrfs

### ISSUE THREAD

**Issue by ibuildthecloud** [coreos/bugs#113]
I have a three node cluster running 410.0.0 and all nodes will randomly crash with below kernel panic.  This is running on Digital Ocean.
![crash](https://cloud.githubusercontent.com/assets/1754002/4014812/7e2427ac-2a24-11e4-8ce2-7e8c9e4f3e01.png)

**Comment by crawford** [comment]
Please reopen if this is still an issue.
