### ISSUE TITLE
docker 1.10 doesn't properly use systemd docker integration

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1132]
Docker 1.9 used systemd integration by default for cgroups. Docker 1.10 changes this default via this libcontainer PR: https://github.com/docker/docker/pull/17704

We need to add this new exec-opt flag to our docker daemon systemd unit:

```
docker daemon --exec-opt native.cgroupdriver=systemd
```

cc @aaronlevy @mischief

**Comment by marineam** [comment]
Should be fixed in this week's alpha.
