### ISSUE TITLE
Problem in MAC address

### ISSUE THREAD

**Issue by arkkanoid** [coreos/bugs#1134]
I get the following error in one node with Coreos:

    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth6c9ed7f: Gained carrier
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Synchronized to time server 54.229.222.210:123 (0.coreos.pool.ntp.org).
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth6c9ed7f: Configured
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Network configuration changed, trying to establish connection.
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Synchronized to time server 54.229.222.210:123 (0.coreos.pool.ntp.org).
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-udevd[14316]: Could not generate persistent MAC address for veth7726b88: No such file or directory
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth7726b 88: Configured
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Network configuration changed, trying to establish connection.
    Feb 23 10:25:24 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Synchronized to time server 54.229.222.210:123 (0.coreos.pool.ntp.org).
    Feb 23 10:25:25 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth6c9ed7f: Lost carrier
    Feb 23 10:25:25 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Network configuration changed, trying to establish connection.
    Feb 23 10:25:25 ip-10-21-1-161.eu-west-1.compute.internal systemd-timesyncd[533]: Synchronized to time server 54.229.222.210:123 (0.coreos.pool.ntp.org).
    Feb 23 10:25:25 ip-10-21-1-161.eu-west-1.compute.internal systemd-networkd[599]: veth6c9ed7f: Removing non-existent address: fe80::42:aff:fef4:425b/64 (valid for ever)

Moreover, I can't run any command of systemctl neither run docker containers. I'm not sure if both errors are related.

How can I solve this problem?

**Comment by crawford** [comment]
What are the specific errors you are seeing when you attempt to run systemctl or docker?

**Comment by arkkanoid** [comment]
I can't get logs of systemctl or docker due to they give a timeout.
I've rebooted the node and now it works fine.
Thanks

**Comment by gesellix** [comment]
we also stumbled on that messages and ask ourselves whether this is "only" a message or a real error. There have been similar issues at #122 and #362. Is there some way of actually finding out whether this is a real issue?
We have problems with instable networking combined when using linked Docker containers and would like to find the root cause.

**Comment by marcbachmann** [comment]
I get simillar errors on ubuntu with docker:
```
Sep  5 07:51:22 branches2 kernel: [402040.837950] device vethe2aa9a0 entered promiscuous mode
Sep  5 07:51:22 branches2 kernel: [402040.843815] IPv6: ADDRCONF(NETDEV_UP): vethe2aa9a0: link is not ready
Sep  5 07:51:22 branches2 systemd-udevd[7251]: Could not generate persistent MAC address for veth3a87ed9: No such file or directory
Sep  5 07:51:22 branches2 systemd-udevd[7259]: Could not generate persistent MAC address for vethe2aa9a0: No such file or directory
Sep  5 07:51:22 branches2 kernel: [402040.907754] IPVS: Creating netns size=1680 id=206
Sep  5 07:51:22 branches2 kernel: [402041.084948] eth0: renamed from veth3a87ed9
Sep  5 07:51:22 branches2 kernel: [402041.124671] IPv6: ADDRCONF(NETDEV_CHANGE): vethe2aa9a0: link becomes ready
```

So I guess It's not really coreos-specific. More like a systemd one: https://github.com/systemd/systemd/issues/3374
