### ISSUE TITLE
Feature Request: track cloud-init with coreos extensions

### ISSUE THREAD

**Issue by lgreenlee** [coreos/bugs#1135]
Cloud-Init works pretty well - it would be nice if CoreOS supported the full standard.

**Comment by crawford** [comment]
coreos-cloudinit has never been conformant to the spec. We've always only supported a very limited subset of Canonical's CloudInit and it's not really feasible for us to keep feature parity. Furthermore, coreos-cloudinit has many practical issues that can't really be solved given its design. Moving forward, we are investing in Ignition with the intent to eventually migrate to it.

**Comment by lgreenlee** [comment]
I switched to Fedora 23 which does support the cloudinit and it is much easier to manage.
