### ISSUE TITLE
coreos isntall: Image URL unavailable

### ISSUE THREAD

**Issue by pierreozoux** [coreos/bugs#1138]
with `coreos-install`:

```
bash coreos-install -d /dev/sda -c cloud-config.tmp  -C stable
coreos-install: coreos-cloudinit not found. Could not validate config. Continuing...
coreos-install: Image URL unavailable: http://stable.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2
```

with `wget`:

```
wget http://stable.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2
--2016-02-25 20:43:17--  http://stable.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2
Resolving stable.release.core-os.net (stable.release.core-os.net)... 2607:f8b0:400d:c06::80, 74.125.22.128
Connecting to stable.release.core-os.net (stable.release.core-os.net)|2607:f8b0:400d:c06::80|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 215084367 (205M) [application/octet-stream]
Saving to: `coreos_production_image.bin.bz2'

20% [=============================================>                                                                                                                                                                                         ] 43,633,467  18.5M/s    
```

with `wget --inet4-only`:
```
wget --inet4-only http://stable.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2
--2016-02-25 20:43:38--  http://stable.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2
Resolving stable.release.core-os.net (stable.release.core-os.net)... 74.125.22.128
Connecting to stable.release.core-os.net (stable.release.core-os.net)|74.125.22.128|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-02-25 20:43:38 ERROR 403: Forbidden.

```

Do you have any idea what is happening?

**Comment by marineam** [comment]
Hm, not sure why. Currently the downloads are hosted on Google storage and every once and a while one datacenter or backend has a problem while others are ok. Should clear up in time but being in Google's hands there isn't much we can do to understand it. Fortunately for the future I'm going to be redoing our download setup so hopefully this kind of thing is less likely to happen.

**Comment by pierreozoux** [comment]
It is what I thought, will try again tomorrow and let you know!

On 25-02-2016 19:59, Michael Marineau wrote:
> Hm, not sure why. Currently the downloads are hosted on Google storage and every once and a while one datacenter or backend has a problem while others are ok. Should clear up in time but being in Google's hands there isn't much we can do to understand it. Fortunately for the future I'm going to be redoing our download setup so hopefully this kind of thing is less likely to happen.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/coreos/bugs/issues/1138#issuecomment-188953005
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by pierreozoux** [comment]
Still not solved for me :/

**Comment by pierreozoux** [comment]
As a workaround, I removed `--inet4-only` from the script, and it is working.

**Comment by pierreozoux** [comment]
There was other problems with this server, I trashed it, and with the new one, it is working well, from the same DC. I assume it was the server config. I'll then close.
