### ISSUE TITLE
Updates fail in libvirt instances

### ISSUE THREAD

**Issue by omkensey** [coreos/bugs#1143]
On libvirt instances, updates fail in the following way: after (or at the end of?) finalizing the update, the VM immediately reboots (no warning is issued and there is no five-minute delay).  On reboot the OS has not been updated.  Sometimes coreos.autologin stops working after the failed update.

Observed with attempted updates using update_engine_client -check_for_update, updating from 835.11.0 to 835.13.0 on Fedora 22 and 23, and Ubuntu 14.04.4.

Using qemu directly, normal behavior was observed on Fedora 23 (have not tested this on F22 or Ubuntu 14.04.4 yet).
### From the VM log in /var/lib/libvirt/qemu/:

`2016-02-29 22:14:47.644+0000: starting up
LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin QEMU_AUDIO_DRV=none /usr/bin/qemu-system-x86_64 -name coreos-update-test -S -machine pc-i440fx-trusty,accel=kvm,usb=off -m 1024 -realtime mlock=off -smp 1,sockets=1,cores=1,threads=1 -uuid dae6c5b1-6193-6311-07a0-ce62dbbab549 -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/coreos-update-test.monitor,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -drive file=/home/kensey/coreos/coreos-update-test.qcow2,if=none,id=drive-virtio-disk0,format=qcow2 -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x5,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -fsdev local,security_model=none,id=fsdev-fs0,path=/home/kensey/coreos/cloud-config -device virtio-9p-pci,id=fs0,fsdev=fsdev-fs0,mount_tag=config-2,bus=pci.0,addr=0x3 -netdev tap,fd=25,id=hostnet0,vhost=on,vhostfd=26 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:54:3b:42,bus=pci.0,addr=0x4 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -vnc 127.0.0.1:0 -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x6
char device redirected to /dev/pts/6 (label charserial0)`
### `virsh version` output:

`Compiled against library: libvirt 1.2.2
Using library: libvirt 1.2.2
Using API: QEMU 1.2.2
Running hypervisor: QEMU 2.0.0`
### `uname -r` output:

`4.2.8-200.fc22.x86_64`
### From the VM log in /var/lib/libvirt/qemu/:

`2016-02-29 23:09:59.613+0000: starting up libvirt version: 1.2.13.2, package: 1.fc22 (Fedora Project, 2015-12-24-00:13:33, buildvm-22-nfs.phx2.fedoraproject.org), qemu version: 2.3.1 (qemu-2.3.1-9.fc22)
LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin QEMU_AUDIO_DRV=spice /usr/bin/qemu-kvm -name coreos-stable -S -machine pc-i440fx-2.3,accel=kvm,usb=off -cpu Broadwell-noTSX -m 2048 -realtime mlock=off -smp 1,sockets=1,cores=1,threads=1 -uuid 37f4f7bf-3802-45cc-b932-eeaaedd5453f -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/coreos-stable.monitor,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -no-shutdown -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x5.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x5 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x5.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x5.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x4 -drive file=/home/kensey/Documents/VirtualMachines/coreos-stable.qcow2,if=none,id=drive-virtio-disk0,format=qcow2 -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x6,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=2 -drive if=none,id=drive-ide0-0-0,readonly=on,format=raw -device ide-cd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=1 -netdev tap,fd=23,id=hostnet0,vhost=on,vhostfd=24 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:75:ff:e8,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev socket,id=charchannel0,path=/var/lib/libvirt/qemu/channel/target/coreos-stable.org.qemu.guest_agent.0,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0 -chardev spicevmc,id=charchannel1,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charchannel1,id=channel1,name=com.redhat.spice.0 -device usb-tablet,id=input0 -spice port=5900,addr=127.0.0.1,disable-ticketing,image-compression=off,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vgamem_mb=16,bus=pci.0,addr=0x2 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x7 -msg timestamp=on
char device redirected to /dev/pts/2 (label charserial0)`
### `virsh version` output:

`Compiled against library: libvirt 1.2.13
Using library: libvirt 1.2.13
Using API: QEMU 1.2.13
Running hypervisor: QEMU 2.3.1`
### `uname -r` output:

`4.2.0-27-generic`

**Comment by marineam** [comment]
One quick thought on the reboot delay which is unrelated to the main issue here: were you logged in on the console? Maybe only ssh sessions are checked. If no one is logged in then the only delay is acquiring the lock in etcd if things are setup to do so.

**Comment by crawford** [comment]
@omkensey do you have console logs or the journals from the instances?

**Comment by omkensey** [comment]
I'll try to reproduce and submit logs -- in the meantime, another data point: doing it over an ssh connection updated successfullyin the normal way.  So possibly this is an interaction between the way coreos.autologin behaves and the way the update engine behaves.

**Comment by omkensey** [comment]
Here's a journal from an instance showing the failure to update (from 835.11.0).  This was logged in on console, using coreos.autologin, and the update engine kicked off the update a little before this log started.  Log runs through the host rebooting.

[coreos-update-test-journal.txt](https://github.com/coreos/bugs/files/162464/coreos-update-test-journal.txt)

**Comment by crawford** [comment]
Have you been able to reproduce this failure with later versions of Container Linux?

**Comment by omkensey** [comment]
I did reproduce it just now in the following circumstance:

* Used a VM with an old version (1120-something, booting a 4.7.0 kermel from USR-A)
* Kicked off update from a coreos.autologin session
* Instance rebooted immediately at end of update (into a 4.7.3 kernel from USR-B)
* I then soft-rebooted it immediately so I could coreos.autologin again.  I missed hitting Esc soon enough to add coreos.autologin but it booted into the 4.7.0 kernel again anyway, from USR-A.

I think it's that immediate soft-reboot in the last step causing it by making it think the update failed -- but it shouldn't be doing that on a single failure.  I captured `dmesg`, `lsblk`, `cgpt show`, and the journal from the current boot (`journalctl -b 0 -o json` and the same for `-b -1`) -- anything specific I should look for?

**Comment by crawford** [comment]
> I think it's that immediate soft-reboot in the last step causing it by making it think the update failed -- but it shouldn't be doing that on a single failure.

Yes, this is what is causing the failure. We only make one attempt on the new version, so it rolls back after this immediate reboot.
