### ISSUE TITLE
coreos-cloudinit doesn't overwrite /var/lib/coreos-install/user_data

### ISSUE THREAD

**Issue by auguster** [coreos/bugs#1148]
I'm running CoreOS Stable (version 835.13.0 at the time) on a bare metal install.

During install I forgot to start etcd2 and fleet, so I wrote a new cloud-config.yaml file based on the one I provided during installation.

The new config was located in ```/home/core/cloud-config.yaml``` so I ran ```sudo coreos-cloudinit --from-file=/home/core/cloud-config.yaml```
It did launch etcd2 and fleet but at boot time, the old config file (located at ```/var/lib/coreos-install/user_data```) gets used. I checked all the Cloud-Config Locations and couldn't find my new configuration anywhere.

Isn't coreos-cloudinit supposed to update ```/var/lib/coreos-install/user_data``` ?

The workaround I found was ```sudo cp /home/core/cloud-config.yaml /var/lib/coreos-install/user_data```. I rather have cloudinit do that for me.

**Comment by crawford** [comment]
> It did launch etcd2 and fleet but at boot time, the old config file (located at /var/lib/coreos-install/user_data) gets used. I checked all the Cloud-Config Locations and couldn't find my new configuration anywhere.

This is expected behavior. coreos-cloudinit does not managed the configuration - it only executes it.

> Isn't coreos-cloudinit supposed to update /var/lib/coreos-install/user_data ?

No. coreos-cloudinit really isn't meant to be run directly by users.

> The workaround I found was sudo cp /home/core/cloud-config.yaml /var/lib/coreos-install/user_data.

This is the correct approach.

**Comment by auguster** [comment]
Then the name cloudinit is rather misleading, shouldn't it be called something like runconfig.

From what I could find from the documentation: "This command will apply your custom cloud-config."
It would be better to use the sentence you posted in your reply: "coreos-cloudinit does not managed the configuration - it only executes it." that's very clear. Thank you.

**Comment by crawford** [comment]
Patches would be very much appreciated. The docs are in https://github.com/coreos/docs and https://github.com/coreos/coreos-cloudinit.
