### ISSUE TITLE
docker build or run hangs

### ISSUE THREAD

**Issue by jmatsushita** [coreos/bugs#115]
Hi there,

I'm running into a critical issue and would really appreciate any pointers to troubleshoot this. I have installed CoreOS on baremetal and everything was woking fine until this morning. I suspect an automatic update has created the following problems but I'm not sure.

The main symptom is that I cannot build docker containers or run ones. When troubleshooting, I have cleaned up the whole btrfs folder hoping that it was linked to old containers built with AUFS, but even with pre-built and pushed containers (from another machine) I can't run any docker container.

When trying to build a container locally the docker build process hangs on the first step (step 0, downloading dependent layers works):

```
$ docker build -t iilab/static .
Sending build context to Docker daemon 48.13 kB
Sending build context to Docker daemon 
Step 0 : FROM    ubuntu
Pulling repository ubuntu
463ff6be4238: Download complete 
[...]
cc58e55aa5a5: Download complete 
 ---> c4ff7513909d
Step 1 : RUN     apt-get update
 ---> Running in 9ae068bb1d71
### JUST HANGS THERE
```

Similarly when using a pre-built image (with docker pull), the download of the image works but then the docker run process hangs after returning the docker id:

```
$ /usr/bin/docker run -d -p 80:80 -p 443:443 -v /opt/nginx/logs:/var/log/nginx -v /opt/nginx:/data -v /var/run/docker.sock:/tmp/docker.sock --name proxy -t iilab/proxy
8a756f79a4af0e80e6c9bbf87f71dd7e12d650d7e619eaf717d07c17cd1a863a
### JUST HANGS THERE
```

ps shows

```
root       743  2.0  0.2 785580 88264 ?        Ssl  12:09   0:48 /usr/bin/docker -d -s=btrfs -r=false -H fd://
root       958  0.0  0.0 175972  7956 ?        Sl   12:36   0:00  \_ /var/lib/docker/btrfs/subvolumes/9ae068bb1d711f687afb649025ee3f296afdcf688a67d5b0059c63c1e3d612e7/.dockerinit -driver native -console  -pipe 3 -root /var/lib/docker/execdriver/native/9ae068bb1d71
root      1050  0.0  0.0 175972  4964 ?        Sl   12:47   0:00  \_ /var/lib/docker/btrfs/subvolumes/8a756f79a4af0e80e6c9bbf87f71dd7e12d650d7e619eaf717d07c17cd1a863a/.dockerinit -driver native -console /dev/pts/2 -pipe 3 -root /var/lib/docker/execdriver/native/8a
```

docker logs also hangs.

I'm running CoreOS on the beta channel (build 410.0.0)

```
$ uname -a
Linux localhost 3.15.8+ #2 SMP Fri Aug 15 22:29:31 UTC 2014 x86_64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz GenuineIntel GNU/Linux
```

```
$ docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2
Git commit (server): d84a070
```

**Comment by vishalkmr304** [comment]
Dockerfile RUN hangs. Not able to solve the problem.
In Dockerfile,
RUN ["/bin/bash","-c","mkdir -p /opt/common/jdk"]

while running the docker build it says,
Step 2 : RUN /bin/bash -c mkdir -p /opt/common/jdk
 ---> Running in 29fbcf63279d

and it just hangs here.
Not able to figure out what is the problem. Here is my $docker info command
Containers: 3
Images: 66
Storage Driver: devicemapper
 Pool Name: docker-253:2-132062-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.642 GB
 Data Space Total: 107.4 GB
 Data Space Available: 1.113 GB
 Metadata Space Used: 3.953 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.113 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.20.3.el6.x86_64
CPUs: 4
Total Memory: 7.783 GiB

**Comment by wontonst** [comment]
+1 I get same behavior
```
Step 7 : RUN echo "start" && echo $(useradd -m -u $uid -g $gid rdsdb) && echo "done"
 ---> Running in d1d07c9f2316
start

done
```
Hangs after printing done.

Docker info:
```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 12
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 86
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu precise (12.04.5 LTS)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58 GiB
Name: xxx
ID: xxx
WARNING: No swap limit support
```

**Comment by zorosun** [comment]
@wontonst  Did you fix this issue? I have this problem at the moment and couldn't find a way to fix it yet.
