### ISSUE TITLE
systemd-networkd in systemd v225 flushes interfaces after PXE boot

### ISSUE THREAD

**Issue by urzds** [coreos/bugs#1154]
It appears that systemd-networkd in version v225 of systemd flushes interfaces after PXE boot.

After the boot systemd-networkd-wait-online.service (and thus network-online.target) becomes active (as there is a configuration left from PXE), but later the interface gets flushed and setup anew, which briefly causes the connection to drop. This in turn can cause services that depend on network-online.target to be started, but fail to get a working network connection.

To my knowledge systemd v229 fixes that by introducing a `CriticalConnection` parameter for systemd.network that prevents the interface from being flushed in such cases.

**Comment by urzds** [comment]
It turns out I actually had a typo in my `coreos-install.service` (`Require=network-online.target`) and systemd silently ignored that. Afterwards the detection of the online status works.

**Comment by mischief** [comment]
`systemd-analyze verify` might help here.
