### ISSUE TITLE
update_engine_client: NEW_VERSION is always 0.0.0.0

### ISSUE THREAD

**Issue by urzds** [coreos/bugs#1155]
Since as long as I can think `NEW_VERSION` as reported by `update_engine_client` was always 0.0.0.0. This is a minor nuisance, since it prevents me from easily checking whether the version that will be booted next will be the one I desire.

```
LAST_CHECKED_TIME=1457200669
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATED_NEED_REBOOT
NEW_VERSION=0.0.0.0
NEW_SIZE=193158430
```

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/update_engine/pull/137.

**Comment by urzds** [comment]
Thanks!
