### ISSUE TITLE
How to change the bashrc file after the coreos has been configure?

### ISSUE THREAD

**Issue by ghy200692162** [coreos/bugs#1157]
I have to add some env variable to the System after my coreos has been started.
But I found that $HOME/.bashrc has been linked to a readonly file.
So my question is how to add some env variable under this condition.

I got an Idea,but I am not sure whether is ok for the system
1.Delete the $HOME/.bashrc link;
2.Create a  new $HOME/.bashrc file and add some env variable to it.

I think it will work for me but I not sure the method is a right way.
Can I get some suggestions about this problem?
And why this kind of init files have been linked to a readonly File System?

**Comment by robszumski** [comment]
Yes, you're on the right path. The default .bashrc file is actually a symlink into /usr. You can safely clobber it and add your own file in its place.

This strategy is common for things that we want to update by default (everything in /usr) but allow a user to override it.
