### ISSUE TITLE
High journald CPU usage

### ISSUE THREAD

**Issue by ragnard** [coreos/bugs#1162]
# Summary

We're seeing the `systemd-journald` process consistently occupying ~100% of one CPU when running a docker container that uses the `journald` log driver, running an application that logs roughly ~50 messages/s at peak.

# Setup

- CoreOS-beta-899.5.0-hvm on eu-west-1 (ami-f961d48a)
- Tried on t2.medium, c4.large, c4.xlarge and c4.x2large

# Findings

We've straced the `systemd-journald` process and one thing that stood out was comparatively slow `writev` calls to `/dev/console`.

```
11:22:29.363557 open("/dev/console", O_WRONLY|O_NOCTTY|O_CLOEXEC) = 30 <0.000029>
11:22:29.363613 ioctl(30, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig -icanon -echo ...}) = 0 <0.000021>
11:22:29.363664 writev(30, [{"[71658.329457] ", 15}, {"docker", 6}, {"[804]: ", 7}, {"{\"@timestamp\":\"2016-03-08T11:22:29.361+00:00\",\"@version\":1,\"logger_name\":\"nocrm-bigquery-transform.core\",\"thread_name\":\"main\",\"level_name\":\"INFO\",\"message\":\"inserted batch with 1000 rows\"}", 188}, {"\n", 1}], 5) = 217 <0.003830>
11:22:29.367539 close(30)               = 0 <0.000021>
```

As you can see, that particular `writev` call took `0.003830` seconds. but we're seeing numbers between `0.002328` and `0.055282` for that particular trace.

We tried turning off [`ForwardToConsole`](https://www.freedesktop.org/software/systemd/man/journald.conf.html#ForwardToSyslog=) using a drop-in, but were unsuccesful in doing so. We see that CoreOS sets this option to "yes" using the boot options https://github.com/coreos/coreos-overlay/blob/master/coreos-base/oem-ec2-compat/files/grub-ec2.cfg#L7, not sure if that means it can't actually be overriden.

We resorted to setting the [`TTYPath`](https://www.freedesktop.org/software/systemd/man/journald.conf.html#TTYPath=) to `/dev/null` in which case the CPU usage dropped to low ~1% levels again.

**Comment by kayrus** [comment]
Have reproduced the issue.

Let's use this unit file:

```ini
[Service]
TimeoutStartSec=10s
Type=notify
ExecStart=/bin/bash -c "i=0; while true; do ((i++)); echo Hello World $i; done"
```

And run it inside qemu VM with the following `/usr/share/oem/grub.cfg`:

```
set linux_append="systemd.journald.forward_to_console=yes"
```

And without it. The result without grub hack is:

```
$ journalctl -n1 -u hello
Mar 08 14:25:26 coreos1 bash[757]: Hello World 384795
```

And with it:

```
$ journalctl -n1 -u hello
Mar 08 14:27:41 coreos1 bash[762]: Hello World 22080
```

I ran these tests several time, so the results are approximations.

Relates to [this](https://github.com/coreos/coreos-overlay/commit/f2a97e7b8341e1d076cd1c18086be4b2df89c978) commit.

**Comment by kayrus** [comment]
probably it worth an investigation at systemd journald side why it takes so much time to print logs.

**Comment by vcaputo** [comment]
Yes, we turned on forwarding to the console on these providers to aid in troubleshooting situations when the machine is inaccessible, since there's no interactive console provided.

But the writev() calls should not be so costly, this suggests a console or serial driver issue on aws.

We may have to shut it off if there's no obvious fix to make the console output less costly to perform.

**Comment by kayrus** [comment]
@vcaputo it is reproducible even inside the qemu VM. So I don't thinks it is related to serial driver issue on aws.

**Comment by vcaputo** [comment]
@kayrus What you reproduced in the qemu VM is that logging from a service goes slower when forwarding to console.  But you haven't necessarily reproduced the high CPU usage @ragnard is reportedly correcting by wiring the console forwarding to /dev/null.

In your qemu vm there's a serial port being emulated and the data is getting output to the emulated console, this can block those writev() calls down in journald when it's forwarding to the console.

Additionally, your qemu vm has to draw the console, so you're generating additional load on the system in general, which may also contend with the log-producing test to affect the results.  Did you use SDL output?  -nographic?  did you redirect the qemu console to a file or /dev/null?

What is strange in this issue (to me anyways) is the supposed high CPU usage.  The writev() taking a relatively long time could simply be blocking on the emulated serial port, but I'm not clear on why that would also entail high CPU usage unless the driver is polling.

**Comment by vcaputo** [comment]
In any case, since journald implements the console forwarding synchronously we'll have to turn it off.

For what we intended, an asynchronous journal follower piping to the console would be more appropriate, something like how rsyslog consumes journals.

**Comment by kayrus** [comment]
@vcaputo thanks. in my case I used `-chardev socket,id=charmonitor,path=/home/user/coreos1.monitor,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -vnc 127.0.0.1:0`. Since service was stopped qemu instance still printed logs from the queue for ~5 seconds. And CPU load graph was longer rather than without forwarding.

**Comment by ragnard** [comment]
@kayrus @vcaputo We just ran the following experiment on a node that experiences the reported issue:

1. Create a service unit similar to what @kayrus did above, but with a (admittedly crude) limit on logs/s:

  ```
  [Service]
  TimeoutStartSec=10s
  Type=notify
  ExecStart=/bin/bash -c "i=0; while true; do ((i++)); sleep 0.005; echo Hello World $i; done"
  ``` 

2. `systemctl start logtest`
3. Observe CPU usage using `top`, reaches ~60% during multiple test runs.
4. Change `/etc/systemd/journald.conf` to have:

  ```
  [Journal]
  TTYPath=/dev/null
  ```
5. `systemctl restart systemd-journald`
6. Observe CPU usage using `top`, reaches ~4% during multiple test runs.

On a side note, we were unable to set `TTYPath=/dev/null` through a drop-in.

**Comment by kayrus** [comment]
Quick workaround:

```yaml
#cloud-config
write_files:
  - path: "/etc/systemd/journald.conf.d/10-override-tty.conf"
    permissions: "0644"
    owner: "root"
    content: |
      [Journal]
      TTYPath=/dev/null
```

**Comment by vcaputo** [comment]
You may also set MaxLevelConsole to something like "crit" or "emerg" to reduce its utilization without completely losing this troubleshooting facility, if it's something you value.

**Comment by kayrus** [comment]
@vcaputo thanks. updated.

**Comment by vcaputo** [comment]
@kayrus no, thank you sir. :+1:

**Comment by joe1chen** [comment]
Thanks to both @kayrus and @vcaputo for helping us work around this issue.  This problem combined with https://github.com/kubernetes/kubernetes/issues/8620 created 50%+ cpu load, which immediately dropped to almost nothing once I set ```MaxLevelConsole=notice```.

**Comment by brycechesternewman** [comment]
Is there a way to change this permanently when oem-cloudinit.service runs?
For example...
```
         write_files:
             - path: /etc/systemd/journald.conf
              permissions: 0644
              owner: root
              content: |
             [Journal]
             MaxLevelConsole=crit
```
This seems to have no effect and /etc/systemd/journald.conf still has the default value of #MaxLevelConsole=info

**Comment by crawford** [comment]
@brycechesternewman cloudinit runs way too late to configure this. You can use [Ignition](https://coreos.com/ignition) instead.

**Comment by tilgovi** [comment]
Does this mean that SSH host keys fingerprints won't show in the console output? That could make verifying host keys difficult.

**Comment by tilgovi** [comment]
I think I am mistaken and the host keys are printed directly to the console, not through the journal. Apologies for the noise.

**Comment by egoldschmidt** [comment]
We are running CoreOS 1010.4.0 on EC2 and just ran into this issue, symptom for symptom. We too found that @kayrus's workaround resolves the problem immediately.

I see that https://github.com/coreos/coreos-overlay/pull/1823 ought to help, and I can confirm that `systemd.journald.forward_to_console=yes` is absent from my grub.cfg, but shouldn't the journald config change be added to the stock distro to guarantee that other folks won't run into this ticking time bomb? At least until journald changes go in (though the linked issue doesn't look particularly active).

**Comment by crawford** [comment]
@egoldschmidt it looks like this change was mistakenly left out of the non-Alpha builds. We'll be sure to include it in the next Stable.
