### ISSUE TITLE
Failed to parse Cloud Config using VMware Guestinfo interface

### ISSUE THREAD

**Issue by marcusportmann** [coreos/bugs#1170]
Hello,

I am attempting to pass the Cloud Config to a VM based on the http://alpha.release.core-os.net/amd64-usr/983.0.0/coreos_production_vmware_image.vmdk.bz2 VMDK.

I have attempted to pass the Cloud Config in both base64 and gzip+base64 format.

My cloud-config.yaml file is as follows:

```
#cloud-config
hostname: coreos
users:
  - name: root
    passwd: $1$LEfVXsiG$lhcyOrkJq02jWnEhF93IR/
```
The entries in my coreos.vmx file are as follows:

```
guestinfo.coreos.config.data = "I2Nsb3VkLWNvbmZpZwpob3N0bmFtZTogY29yZW9zCnVzZXJzOgogIC0gbmFtZTogcm9vdAogICAgcGFzc3dkOiAkMSRMRWZWWHNpRyRsaGN5T3JrSnEwMmpXbkVoRjkzSVIv"
guestinfo.coreos.config.data.encoding = "base64"
```

The VM always fails on first boot and drops to a root prompt.

When I execute the command "systemctl -l status ignition-disks", I see a "failed to fetch config: error at line 1, column 1" error along with "invalid character 'I' looking for beginning of value".

I have played around with changing the first character of the base64 encoded data and have seen a corresponding matching character in the error message.

It appears that the base64 and base64+gzip configuration is not being decoded before it is parsed.

If I force the VM to reboot then it boots successfully and the Cloud Config is applied correctly the second time.

Regards,

Marcus

**Comment by crawford** [comment]
The fix will be available in tomorrow's Alpha.
