### ISSUE TITLE
ignition-0.3.2 build fails for arm64

### ISSUE THREAD

**Issue by glevand** [coreos/bugs#1175]
ignition-0.3.1 build OK.
ignition-0.3.2 fails.

I didn't look into the problem.

    # github.com/coreos/ignition/src/providers/vmware
    ../gopath/src/github.com/coreos/ignition/src/providers/vmware/vmware_unsupported.go:28: undefined: config.Config
    ../gopath/src/github.com/coreos/ignition/src/providers/vmware/vmware_unsupported.go:29: undefined: config.Config

**Comment by crawford** [comment]
Dogonit. That's my fault.
