### ISSUE TITLE
GlusterFS

### ISSUE THREAD

**Issue by stevesloka** [coreos/bugs#1176]
I have a Kubernetes cluster running on CoreOS right now. I'm looking to setup a GlusterFS cluster to use for persistent volumes for my pods running in the k8s cluster. 

Does CoreOS support this? I have seen ways where people bake the Gluster Client into the container, but I'd rather abstract that away from the container.

**Comment by robszumski** [comment]
The way to accomplish this would be to have a container running on each host that will provide Gluster, and then configure Kubernetes to use that as its persistent volume store, so you can use native Kubernetes tools for PDs. I don't know of any instructions for this but another community member has been working on some PoCs of this for Ceph and he was successful doing that with Kubernetes.

**Comment by stevesloka** [comment]
Thanks @robszumski I just found this which is in line with what you are talking about from @rootfs https://huaminchen.wordpress.com/2016/03/22/yet-another-containerized-mounter-for-kubernetes/

**Comment by robszumski** [comment]
It would be great to get a guide for doing this upstream in the CoreOS docs. If you get this working, would you mind contributing your knowledge?

**Comment by stevesloka** [comment]
@robszumski Absolutely!

**Comment by nballotta** [comment]
hi, anyone got this working and documented?

**Comment by pcm32** [comment]
interested as well to use this. It would be great if it has been documented. Thanks!

**Comment by munnerz** [comment]
Very interested in this - glusterfs would be great to use as a storage solution on my bare metal cluster!

**Comment by TerraTech** [comment]
Can this issue be re-opened as I am also having problems trying to use GlusterFS for rktnetes cluster `Persistent Volume` (PV).

Of reference:
https://github.com/kubernetes/kubernetes/issues/34127
and
https://github.com/kubernetes/kubernetes/issues/32550

In particular:
```It is not supported in GCE & **CoreOS** environments where access to master node or root filesystem is restricted. Access to master node is required to install the plugin for controller-manager to provision, delete, attach & detach calls.```

Best I can tell, trying to use GlusterFS storage for Kubernetes/rktnetes PVs is an uphill battle.

**Comment by crawford** [comment]
@TerraTech please open a new issue detailing the specific errors you are hitting.

**Comment by TerraTech** [comment]
@crawford actually, I will retract.  It appears my issue will be fixed when this hyperkube commit https://github.com/kubernetes/kubernetes/commit/d1256498ff8ad269d78db76aaaeb84f03165b5dc, that includes glusterfs-client, finds its way into https://quay.io/repository/coreos/hyperkube:  

My apologies, because I searched for this prior, but did not find the commit until now - searching for `glusterfs-client` did the trick.

**Comment by pcm32** [comment]
@TerraTech how do you take advantage of the gluster-client inside hyperkube? do you need to make use of the new StorageClasses or just having the PersistentVolume set to a GlusterFS cluster will work out of the box? This previously required for the host node to be able to mount GlusterFS, which is our current issue with CoreOS.

**Comment by TerraTech** [comment]
@pcm32, the latter.  The main sticking point is that CoreOS doesn't provide the glusterfs client utils necessary to mount an explicit remote volume.  I'm also not a big fan of exporting them via NFS and would rather use native mounts.  At this point, using a sidecar/util pod to do the mounting is just not worth the hassle when an upcoming release of hyperkube will have it baked in.  I will look at the new StorageClasses when it exits the experimental phase.

**Comment by pcm32** [comment]
Thanks @TerraTech! I think that someone tried that on this other [issue](https://github.com/coreos/coreos-kubernetes/issues/696#issuecomment-252936700) on CoreOS Kubernetes repo without success (using hyperkube 1.4). I haven't had the chance of trying it myself though.

@robszumski @crawford it would be nice if someone from CoreOS posts an example on how you are supposed to use GlusterFS with CoreOS within Kubernetes, given that CoreOS doesn't intend to provide built-in support for GlusterFS, yet many people would like to use it :-).

**Comment by crawford** [comment]
> @robszumski @crawford it would be nice if someone from CoreOS posts an example on how you are supposed to use GlusterFS with CoreOS within Kubernetes, given that CoreOS doesn't intend to provide built-in support for GlusterFS, yet many people would like to use it :-).

@aaronlevy @sym3tri ^^

**Comment by aaronlevy** [comment]
It looks like the client package was added to upstream hyperkube builds pretty recently:

https://github.com/kubernetes/kubernetes/pull/32686

However, it doesn't look like that change has been proposed a cherry-pick into the v1.4 release. We could optionally carry the change as a patch in our own hyperkube builds - but I won't be able to test the actual GlusterFS functionality / if merely adding the client libs to the hyperkube image is sufficient.

If I build a hyperkube image which contains the client libs - would someone volunteer to validate that it works for them?

**Comment by pcm32** [comment]
@aaronlevy I could give it a try with a new deployment, I need to get a bit more of space on my tenancy, but should be doable. Let me know of the repo and image name to use. I only need to change the hyperkube image used, right?

**Comment by aaronlevy** [comment]
A starting point would be to use the new hyperkube image, but I'm not familiar enough with glusterfs to know if other locations on host need to be mounted into kubelet container.

The image is: `quay.io/coreos/hyperkube-dev:v1.4.1_glusterfs.0` (note the `hyperkube-dev` repo)
This was built from: https://github.com/aaronlevy/kubernetes/tree/v1.4.1%2Bglusterfs

**Comment by TerraTech** [comment]
@aaronlevy I'm happy to report that my glusterfs mounts seem to be working.  So far, edits made to a test file on worker1's mounted glusterfs volume, are showing up properly on other nodes.  However I will need to do some more testing and ensure they are stable to use for Persistent Volumes.
```json
$ cat glusterfs-pod.json
{
	"apiVersion": "v1",
	"kind": "Pod",
	"metadata": {
		"name": "glusterfs"
	},
	"spec": {
		"containers":[
			{
				"name": "glusterfs",
				"image": "kubernetes/pause",
				"volumeMounts": [
					{
						"mountPath": "/mnt/glusterfs",
						"name": "glusterfsvol"
					}
				]
			}
		],
		"volumes": [
			{
				"name": "glusterfsvol",
				"glusterfs": {
					"endpoints": "glusterfs-cluster",
					"path": "kube",
					"readOnly": false
				}
			}
		]
	}
}
```

```sh
$ mount | grep glusterfs
10.x.x.x:kube on /var/lib/rkt/pods/run/585ff411-e3ee-413f-9815-b547006bbaf4/stage1/rootfs/opt/stage2/hyperkube-dev/rootfs/var/lib/kubelet/pods/7082fc84-8dbe-11e6-adf2-0018f3531b4f/volumes/kubernetes.io~glusterfs/glusterfsvol type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
10.x.x.x:kube on /var/lib/kubelet/pods/7082fc84-8dbe-11e6-adf2-0018f3531b4f/volumes/kubernetes.io~glusterfs/glusterfsvol type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
overlay on /var/lib/rkt/pods/run/e59b5ebb-0706-4576-b55d-f8bf0b8d7432/stage1/rootfs/opt/stage2/glusterfs/rootfs type overlay (rw,relatime,lowerdir=/var/lib/rkt/cas/tree/deps-sha512-8cb44306f9d0b8333d78688105122e68fa84858c5d24b79e193f8db418b70288/rootfs,upperdir=/var/lib/rkt/pods/run/e59b5ebb-0706-4576-b55d-f8bf0b8d7432/overlay/deps-sha512-8cb44306f9d0b8333d78688105122e68fa84858c5d24b79e193f8db418b70288/upper/glusterfs,workdir=/var/lib/rkt/pods/run/e59b5ebb-0706-4576-b55d-f8bf0b8d7432/overlay/deps-sha512-8cb44306f9d0b8333d78688105122e68fa84858c5d24b79e193f8db418b70288/work/glusterfs)
overlay on /var/lib/rkt/pods/run/585ff411-e3ee-413f-9815-b547006bbaf4/stage1/rootfs/opt/stage2/hyperkube-dev/rootfs/var/lib/rkt/pods/run/e59b5ebb-0706-4576-b55d-f8bf0b8d7432/stage1/rootfs/opt/stage2/glusterfs/rootfs type overlay (rw,relatime,lowerdir=/var/lib/rkt/cas/tree/deps-sha512-8cb44306f9d0b8333d78688105122e68fa84858c5d24b79e193f8db418b70288/rootfs,upperdir=/var/lib/rkt/pods/run/e59b5ebb-0706-4576-b55d-f8bf0b8d7432/overlay/deps-sha512-8cb44306f9d0b8333d78688105122e68fa84858c5d24b79e193f8db418b70288/upper/glusterfs,workdir=/var/lib/rkt/pods/run/e59b5ebb-0706-4576-b55d-f8bf0b8d7432/overlay/deps-sha512-8cb44306f9d0b8333d78688105122e68fa84858c5d24b79e193f8db418b70288/work/glusterfs)
```

**Comment by TerraTech** [comment]
@aaronlevy After further testing, I was able to properly create a PV, create a bound Claim on it, and use that claim as a volume (/mnt/gtfs) within a test busybox pod with full read/write ability.

**Comment by aaronlevy** [comment]
Awesome. I'll get this lined up for the next release. Given v1.4.2 should be out soon - we'll likely carry the change in that release (rather than cutting another v1.4.1)

**Comment by Rastusik** [comment]
@aaronlevy @TerraTech is the glusterfs update in the stable version already? I see the 1.4.1 and 1.4.3 tags in the quay.io registry, will I be able to use glusterfs with them?

**Comment by TerraTech** [comment]
@Rastusik yes, hyperkube:v1.4.3_coreos.0 includes the glusterfs-client
https://quay.io/repository/coreos/hyperkube/image/e1486465c0aa42323b2404ac318474d23326b83d552f6fef463e0ce9ce31b07e

**Comment by aaronlevy** [comment]
Yeah, sorry I meant to update this issue yesterday. This was added to the v1.4.3 release: https://github.com/coreos/kubernetes/releases/tag/v1.4.3%2Bcoreos.0

Image: `quay.io/coreos/hyperkube:v1.4.3_coreos.0`

**Comment by pcm32** [comment]
@TerraTech can you post the PV and Endpoint that you used? I tried the json that you posted, but I still get (making the correct modifications to my endpoint):

```
Mounting arguments: 192.168.0.162:gluster /var/lib/kubelet/pods/88141c44-b6e8-11e6-a5f9-fa163e848ee4/volumes/kubernetes.io~glusterfs/glusterfsvol glusterfs [log-level=ERROR log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/glusterfsvol/glusterfs-glusterfs.log]
Output: mount: unknown filesystem type 'glusterfs'
```

How are you provisioning Kubernetes? I'm using https://github.com/kubernetes-incubator/kargo, which doesn't lift kubelet through the CoreOS kubelet-wrapper. @aaronlevy Is this a requirement for this to work? As I see it it only mounts files from the host to hyperkube, but I don't see how that allows the gluster mounting.

kargo mounts the following directories from hyperkube (they use CoreOS hyperkube image 1.4.6... which contains glusterfs-client binaries):

```
-v /etc/cni:/etc/cni:ro \
-v /opt/cni:/opt/cni:ro \
-v /etc/kubernetes:/etc/kubernetes \
-v /sys:/sys \
-v /dev:/dev \
-v /var/lib/docker:/var/lib/docker \
-v /var/run:/var/run \
-v /var/lib/kubelet:/var/lib/kubelet \
```

whereas CoreOS kubelet-wrapper mounts:

```
  --volume etc-kubernetes,kind=host,source=/etc/kubernetes \
  --volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates \
  --volume var-lib-docker,kind=host,source=/var/lib/docker \
  --volume var-lib-kubelet,kind=host,source=/var/lib/kubelet \
  --volume os-release,kind=host,source=/usr/lib/os-release \
  --volume run,kind=host,source=/run \
  --mount volume=etc-kubernetes,target=/etc/kubernetes \
  --mount volume=etc-ssl-certs,target=/etc/ssl/certs \
  --mount volume=var-lib-docker,target=/var/lib/docker \
  --mount volume=var-lib-kubelet,target=/var/lib/kubelet \
  --mount volume=os-release,target=/etc/os-release \
  --mount volume=run,target=/run \
```

or is rkt doing some hidden tricks?
Thanks!

**Comment by TerraTech** [comment]
@pcm32 From your mount error message, 'glusterfs' isn't a real filesystem per se, what you are looking for is 'fuse.glusterfs'.  I have only run all this via CoreOS (baremetal) via the kubelet wrapper, so there may be some underlying magic going on.  If you are trying to do (manual) mounts from within a (non-priv'd) container, make sure you mount in the host's /dev/fuse otherwise it won't work.
