### ISSUE TITLE
Support for `*.network` units in ignition

### ISSUE THREAD

**Issue by urzds** [coreos/bugs#1179]
cloud-init supported `*.network` units, which it placed in `.../systemd/network`. Ignition seems to be lacking an easy way to do this.

See-Also: #981

**Comment by mischief** [comment]
i think you are mistaken. there is a networkd section in the ignition config for this.

**Comment by urzds** [comment]
You're right. In cloud-config I could apparently just list those under `units`, but in ignition it's under `networkd`. Thanks for the help and sorry for not looking that up properly.
