### ISSUE TITLE
Docker got stuck on Coreos

### ISSUE THREAD

**Issue by rkononov** [coreos/bugs#118]
Docker became completely unresponsive after 4 hours of running/stopping containers

Linux ip-10-95-165-210.ec2.internal 3.15.8+ #2 SMP Thu Aug 28 08:03:21 UTC 2014 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux

Callstack from logs 

Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel: INFO: task kworker/u30:4:31318 blocked for more than 120 seconds.
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:       Not tainted 3.15.8+ #2
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel: kworker/u30:4   D ffff8803e0433ec0     0 31318      2 0x00000000
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel: Workqueue: netns cleanup_net
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  ffff88008d8cfc48 0000000000000046 ffff88029e428000 0000000000013ec0
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  ffff88008d8cffd8 0000000000013ec0 ffff8803cb341920 ffff88029e428000
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  ffff88029e7c8000 ffffffff81aac820 ffff88029e7c8000 ffff88029e428000
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel: Call Trace:
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff814cbad9>] schedule+0x29/0x70
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff814cbe2e>] schedule_preempt_disabled+0xe/0x10
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff814cdcbc>] __mutex_lock_slowpath+0x1bc/0x1d0
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff814cdcf3>] mutex_lock+0x23/0x37
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff813deb75>] rtnl_lock+0x15/0x20
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff813cdc92>] default_device_exit_batch+0x72/0x160
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff810a8980>] ? finish_wait+0x80/0x80
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff813c82f3>] ops_exit_list.isra.1+0x53/0x60
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff813c8c60>] cleanup_net+0x110/0x230
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff8107db17>] process_one_work+0x187/0x440
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff8107f171>] worker_thread+0x121/0x3e0
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff8107f050>] ? manage_workers.isra.21+0x300/0x300
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff81085909>] kthread+0xc9/0xe0
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff81085840>] ? flush_kthread_worker+0x80/0x80
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff814d043c>] ret_from_fork+0x7c/0xb0
Aug 29 14:36:57 ip-10-95-165-210.ec2.internal kernel:  [<ffffffff81085840>] ? flush_kthread_worker+0x80/0x80

Script to reproduce(launch 40 concurrent processes):

#!/bin/bash
touch kill.me
for i in {0..10000}
do
container_name=$RANDOM-$i
echo $container_name
if [ ! -f kill.me ]; then
    echo "Exiting..."
    exit 0
fi
sudo docker run  --name=$container_name  -m='300M' -c 51 -i -a=stdout -a=stderr ruby ruby -e 'File.open("big.file","w") {|f| f.write("0" * 99999) }'
sudo docker stop -t=5 $container_name
sudo docker rm -f $container_name
echo item: $i
done

**Comment by mischief** [comment]
@rkononov ping, can you still reproduce this?

**Comment by rkononov** [comment]
@mischief didn't have a chance to try this, we're going to give it another try in next few weeks.
I think you could close this for now.
