### ISSUE TITLE
sbsign disk full problem

### ISSUE THREAD

**Issue by glevand** [coreos/bugs#1180]
I added some debugging files to the EFI-SYSTEM partition that took up much of the space.  sbsign seemed to run and generate a signed vmlinuz-a, but that image could not run.  It seemed that sbsign ran out of disk space, but did not fail.  Without the debug files in the partition the signed vmlinuz-a booted OK.  I didn't look into any further.  Build for arm64-usr.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
