### ISSUE TITLE
CoreOS alpha 991 on EC2 with no user data fails to start

### ISSUE THREAD

**Issue by SpencerBrown** [coreos/bugs#1184]
if I have EC2 instance user data as `#cloud-config` with nothing else, the instance comes up and I can SSH into it.

if I provide no user data at all, apparently CoreOS never comes up. At least, I cannot SSH into it (get "connection refused"), so I'm *assuming* it got stuck somewhere in initialization.

Using latest HVM CoreOS AMI.

**Comment by crawford** [comment]
```
$ curl http://169.254.169.254/2009-04-04/user-data
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```

Ignition is attempting to interpret the response body as a valid config. This was introduced in https://github.com/coreos/ignition/pull/181/commits/86d02a0c904fb12b7bf457b3c36a957f49575009.

**Comment by crawford** [comment]
This was fixed by https://github.com/coreos/ignition/pull/208. It should make it into the Alpha today.
