### ISSUE TITLE
use fleetctl to reboot cluster

### ISSUE THREAD

**Issue by hackzilla** [coreos/bugs#119]
Is there anyway, using fleet or systemd, to reboot the cluster on machines?

Ideally, taking advantage of the etcd reboot strategy.

The way I see it working was a systemd/fleet service, that you could exclude/include machines and wait for fleet to be happy the services are backup.

I've been implementing the examples from "[Launching Containers with fleet](https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/)" but the only way to grab the latest docker image is on service restart.  Which currently means either a reboot of all nodes, or stop/start services.

**Comment by mischief** [comment]
you could use fleetctl to start a systemd oneshot which runs `locksmithctl reboot`.
