### ISSUE TITLE
Binary /sbin/ip missing with CoreOS 991.1.0 on GCE

### ISSUE THREAD

**Issue by aknuds1** [coreos/bugs#1190]
In the system journal of my CoreOS 991.1.0 instance on Google Compute Engine, I keep seeing this error message:

>  Mar 29 21:58:21 staging-master1.c.experimentalberlin.internal google-address-manager[1191]: ERROR SyncAddresses exception: Could not run ['/sbin/ip', 'route', 'ls', 'table', 'local', 'type', 'local', 'dev', 'eth0', 'scope', 'host', 'proto', '66'] due to [Errno 2] No such file or directory

**Comment by euank** [comment]
The binary is located at `/bin/ip`. The upstream google-address-manager changed their behaviour to also respect that path, but CoreOS doesn't seem to have pulled in that version (https://github.com/GoogleCloudPlatform/compute-image-packages/pull/160).

cc @crawford, I think updating `oem-gce` should solve this issue.

**Comment by marineam** [comment]
Should be fixed by https://github.com/coreos/coreos-overlay/pull/1919 but need to double check
