### ISSUE TITLE
proposal -- use systemd timers to handle reboot delays

### ISSUE THREAD

**Issue by omkensey** [coreos/bugs#1191]
Currently locksmith handles a reboot delay by simply calling time.Sleep for the specified number of seconds and then after that finishes, calling lgn.Reboot.  This works, but makes it harder for a user to look at the system and determine if it will reboot within a certain threshold.

Another option would be to use systemd timers: locksmith could write a transient unit file for a timer that calls the reboot.  This would let users easily see the reboot status (`systemctl list-timers [name].timer`) or stop the reboot in an emergency by stopping the timer unit.  This could be useful for easily detecting that a system is about to reboot to clean up a running app ahead of time.

**Comment by crawford** [comment]
If the user wants to abort a reboot, they can just stop locksmith. That is much easier than tracking down the transient service. Additionally, if they need to delay the reboot, they can use systemd's reboot-inhibitor mechanism. I'm going to go ahead and close this since we aren't going to change this.

**Comment by omkensey** [comment]
How can the user determine a system is about to reboot and when?  That was the original end-user question that prompted this.  Can (or does) locksmith expose that somehow?

**Comment by crawford** [comment]
It really depends on what you are trying to do here. Yes, it is possible to find out via dbus when the system is about to reboot, but what I suspect you are actually trying to do is either execute a program before reboot or stall the reboot altogether. You can use standard systemd mechanisms to run programs on shutdown and you can also use systemd-inhibit to stall the shutdown until you're ready.
