### ISSUE TITLE
Insufficient disk space caused node to fail and it couldn't recover then

### ISSUE THREAD

**Issue by cyrillk** [coreos/bugs#1193]
I experienced a strange issue with my coreos cluster. One of the nodes used all available disk space which caused services stop working and machine even disappeared from `fleetctl list-machines`. So I had to `ssh` to that machine and free some disk space.  Then it appeared in the list of running machines and tried to run some services. Though journald didn't work properly and 'journalctl -f' didn't show any new log messages at all.

Last message in journald

```
-- Logs begin at Tue 2016-03-29 09:05:19 UTC. --
Mar 29 17:56:52 172.24.24.73 sh[14814]: ... 3 more
Mar 29 17:56:52 172.24.24.73 sh[14814]: Caused by: java.io.IOException: No space left on device
Mar 29 17:56:52 172.24.24.73 sh[14814]: at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
```

So, I had to restart journald manually with 

```
core@172 ~ $ sudo systemctl restart systemd-journald
```

Then it recovered and started to work fine.

```
core@172 ~ $ journalctl -f
-- Logs begin at Tue 2016-03-29 09:05:19 UTC. --
Mar 30 10:36:34 172.24.24.73 kernel: docker0: port 3(vethc3317f3) entered disabled state
Mar 30 10:36:34 172.24.24.73 kernel: device veth76957f0 left promiscuous mode
Mar 30 10:36:34 172.24.24.73 kernel: docker0: port 1(veth76957f0) entered disabled state
```

So, I wonder if it is something expected when disk space is limited?

P.S. CoreOS version is `CoreOS stable (899.13.0)`

**Comment by crawford** [comment]
Yes, it's generally expected that services will start to fail when resources are exhausted. journald has since become more robust to the failure you described.
