### ISSUE TITLE
CoreOS alpha 1000.0 ISO image shows "CoreOS Stable"

### ISSUE THREAD

**Issue by pwaller** [coreos/bugs#1199]
I downloaded the image at [this page](https://coreos.com/os/docs/latest/booting-with-iso.html) just now (Note: alpha channel):

http://alpha.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso

SHA256: `32261582dc23a35d71a57f6caf99c450052e66ba24e118318215df4ce47fedb9`

And when I booted this machine I saw (CoreOS stable 1000.0):

![coreos 1000](https://cloud.githubusercontent.com/assets/438648/14202568/9eb11836-f7f0-11e5-86f6-a00c9025ff6e.png)

I guess this shouldn't say "stable" since https://coreos.com/releases/ currently shows stable as 899.13.0?

**Comment by pwaller** [comment]
Also note, as a (possibly-related) consequence, coreos-install fails:

![coreos 1000](https://cloud.githubusercontent.com/assets/438648/14202729/9762a364-f7f1-11e5-8a1b-0f9364df15d5.png)

**Comment by crawford** [comment]
This is a dup of https://github.com/coreos/bugs/issues/276#issuecomment-76341320.
