### ISSUE TITLE
[Question] CoreOS version that support Ignition

### ISSUE THREAD

**Issue by hectorj2f** [coreos/bugs#1203]
Hello,

Is there any place in the documentation of ignition where I could find which versions of CoreOS support ignition? I tested my ignition config files on recent versions and they worked then I used on older ones like CoreOS stable 681.2.0 and it failed (there was not ignition in there).

 Could you specify it in the docs if ignition was included from one specific version ?

Thanks in advace.

**Comment by crawford** [comment]
The [release notes](https://coreos.com/releases/) will show you which versions of CoreOS shipped with which version of Ignition (depending on the platform and functionality needed, you'll probably need at least a specific version of Ignition).

Why are you using such an old image? The current Stable is 899.13.0.

**Comment by hectorj2f** [comment]
Thanks @crawford. A link in the ignition documentation could be helpful. 

> Why are you using such an old image? 

I was just testing different versions that we used in the past.
