### ISSUE TITLE
Docker container falsely seen as running

### ISSUE THREAD

**Issue by tosan88** [coreos/bugs#1207]
A docker container cannot be started due to a false alarm from docker.
Docker alarms that the container name is conflicting because it is used by another container, but that another container does not really exist (checked with `docker ps -a`). 

Here are the relevant system logs:
```
Apr 04 10:58:54 ip-172-24-121-215.eu-west-1.compute.internal dockerd[894]: time="2016-04-04T10:58:54.419601965Z" level=error msg="Clean up Error! Cannot destroy container fc5f940d5149b6668a23d13c4718a64ee36b7c5a38a6fa14fa7288b4110e4860: nosuchcontainer: No such container: fc5f940d5149b6668a23d13c4718a64ee36b7c5a38a6fa14fa7288b4110e4860"
...
Apr 04 10:59:54 ip-172-24-121-215.eu-west-1.compute.internal sh[11496]: docker: Error response from daemon: Conflict. The name "/locations-transformer-1" is already in use by container fc5f940d5149b6668a23d13c4718a64ee36b7c5a38a6fa14fa7288b4110e4860. You have to remove (or rename) that container to be able to reuse that name..
```

We start and stop the docker container via fleet service unit with the following command:
```
ExecStart=/bin/sh -c '\
  export [redacted] \
  /usr/bin/docker run --rm --name %p-%i -p $PORT --env [redacted] coco/locations-transformer:$DOCKER_APP_VERSION;'
ExecStop=/usr/bin/docker stop -t 3 %p-%i
```

Here is the output from docker info:
```
core@ip-172-24-121-215 ~ $ docker info
Containers: 43
 Running: 43
 Paused: 0
 Stopped: 0
Images: 35
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: none
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.6-coreos
Operating System: CoreOS 1000.0.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: ip-172-24-121-215.eu-west-1.compute.internal
ID: S5TQ:B4NI:W7DL:57KS:TUZM:ZLKE:Y4HE:CR5E:RDQR:7AYA:IGMB:ZJH4
```

This is happening on CoreOS alpha version 1000.0.0.
This is not reproducible on CoreOS stable version 899.13.0.

Can you please help?
Thanks!

**Comment by crawford** [comment]
I'm not really sure how to help you. This sounds like a Docker issue between 1.9.1 and 1.10.3. Are you able to come up with a simple repro case? Does this happen regularly or is it periodic?

**Comment by crawford** [comment]
This looks to be a direct result of the failure described in https://github.com/coreos/bugs/issues/1204. Do you ever see this in absence of the other?

**Comment by lleszczu** [comment]
Looks like https://github.com/docker/docker/issues/23371

**Comment by crawford** [comment]
Let's consolidate the discussion in https://github.com/coreos/bugs/issues/1204.
