### ISSUE TITLE
update engine service stuck on 835.13.0

### ISSUE THREAD

**Issue by tanuck** [coreos/bugs#1208]
Hi,

I have a 5 machine cluster running the stable release - its currently on 835.13.0. The periodic check from update-engine always come back with "No update". However, if I run `update_engine_client -check_for_update` the engine then detects a new version and will perform an upgrade. In my latest attempt it upgraded to 899.15.0.

The automatic updates have always worked in the past, so I'm not sure what has caused the issue now.

Thanks

**Comment by crawford** [comment]
Updates are rate-limited. Your machines will update over the coming days. You can bypass the rate-limit using the command you mentioned.
