### ISSUE TITLE
grub loading hangs on CoreOs beta 991.2.0

### ISSUE THREAD

**Issue by twanc** [coreos/bugs#1221]
Hi

After promotion Alpha to Beta, currently booting of Cisco UCS hangs on "Grub loading"
CoreOs installed on hard-drive (/dev/sda) using coreos-install with latest beta version: 991.2.0
Stable version 899 is working fine.
![screenshot from 2016-04-13 11 08 50](https://cloud.githubusercontent.com/assets/16103806/14488472/c44a7fde-0168-11e6-96ce-696ad619cde0.png)

**Comment by mjg59** [comment]
@twanc Are you able to test this with the 1010 alpha? I believe that this issue has been fixed.

**Comment by twanc** [comment]
Tested on 1010.1.0 (Beta) and OS is booting properly on UCS platform.

**Comment by mjg59** [comment]
Thanks!
