### ISSUE TITLE
arm64 images should have lib symlinked into lib64

### ISSUE THREAD

**Issue by mischief** [coreos/bugs#1226]
right now lib and lib64 are independant directories which can cause confusion of some scripts and tools, like coreos/scripts#519.

cc @marineam @glevand

**Comment by marineam** [comment]
Apparently Gentoo has deprecated `SYMLINK_LIB=yes` for the most part. amd64 is likely stuck with it as the default because migration is hard but other arches don't have/need it: https://bugs.gentoo.org/show_bug.cgi?id=506276
