### ISSUE TITLE
kubelet-wrapper DNS resolution fails

### ISSUE THREAD

**Issue by bcwaldon** [coreos/bugs#1228]
I'm running the kubelet on CoreOS v1010.1.0 using /usr/lib/coreos/kubelet-wrapper w/ KUBELET_VERSION=v1.2.2_coreos.0. If I start the kubelet with --api-servers set to a DNS name, the kubelet is unable to communicate with that API server due to name resolution problems. If I bind-mount in /etc/resolv.conf, however, name resolution succeeds and my kubelet can successfully communicate with my apiserver:

```
RKT_OPTS= \
--volume=etc-resolv-conf,kind=host,source=/etc/resolv.conf \
--mount=volume=etc-resolv-conf,target=/etc/resolv.conf \
```

I propose bind-mounting /etc/resolv.conf in by default in /usr/lib/coreos/kubelet-wrapper.

/cc @luciferous

**Comment by aaronlevy** [comment]
related: https://github.com/coreos/rkt/issues/2141

**Comment by squeeby** [comment]
May be related, we are having a similar issue bringing up a kubelet on CoreOS beta (991.2.0). 
We were initially seeing:
```
kubelet-wrapper[1061]: W0422 13:53:57.588336    1061 manager.go:408] Failed to update status for pod "_()": Get http://kube-master1.lab:8080/api/v1/namespaces/kube-system/pods/kube-proxy-172.23.6.40: dial tcp: lookup kube-master1.lab: no such host
```
Even though `kube-master1.lab` resolves fine. 

strace reveals that it's using a default resolver (8.8.8.8) instead of the one in `/etc/resolv.conf` on the host system.

**Comment by hlamer** [comment]
Workaround:
* Copy `/usr/lib/coreos/kubelet-wrapper` to some writable directory
* Add next lines

```
  --volume resolv-conf,kind=host,source=/etc/resolv.conf \
  --mount volume=resolv-conf,target=/etc/resolv.conf \
```

Use your modified script instead of shipped with CoreOS
