### ISSUE TITLE
Failed to set memory.limit_in_bytes on : Invalid argument

### ISSUE THREAD

**Issue by jfromaniello** [coreos/bugs#123]
I see this message in the logs, not sure what it means:

```
Sep 09 22:15:09 ip-172-31-31-59.us-west-1.compute.internal systemd[1]: Failed to set memory.limit_in_bytes on : Invalid argument
Sep 09 22:15:09 ip-172-31-31-59.us-west-1.compute.internal systemd[1]: Failed to reset devices.list on /system.slice: Invalid argument
```

**Comment by andreas-venturini** [comment]
Not sure what the implications are
```bash
coreos0 ~ $ sudo journalctl -b
[...]
Jan 01 15:48:23 coreos0 systemd[1]: Starting system-addon\x2drun.slice.
Jan 01 15:48:23 coreos0 systemd[1]: Failed to set memory.limit_in_bytes on : Invalid argument
Jan 01 15:48:23 coreos0 systemd[1]: Created slice system-addon\x2drun.slice.
[...]
```

Shortly before in the logs (possibly unrelated to above message)
```bash
coreos0 ~ $ sudo journalctl -b
[...]
Jan 01 15:48:23 coreos0 systemd-journald[88]: Received SIGTERM from PID 1 (systemd).
Jan 01 15:48:23 coreos0 systemd[1]: Breaking ordering cycle by deleting job sockets.target/start
Jan 01 15:48:23 coreos0 systemd[1]: Job sockets.target/start deleted to break ordering cycle starting with basic.target/start
[...]
```

```bash
coreos0 ~ $ cat /etc/lsb-release
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=547.0.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 547.0.0"
```

**Comment by carmstrong** [comment]
Thanks for filing this - I just saw this in our logs and was going to following that path to debug another issue. Good to know it's a red herring.

**Comment by jfoy** [comment]
It looks like this may have been a systemd bug which was just fixed upstream: https://github.com/docker/docker/issues/10280

**Comment by mischief** [comment]
this should be fixed now that systemd 219 has landed.

**Comment by Vish0007** [comment]
I am seeing this issue with CoreOS stable 633.1.0.
failed to set memory.limit_in_bytes on invalid argument.
Any help, how this can be resolved?

**Comment by carmstrong** [comment]
@Vish0007 systemd 219 is in CoreOS >= [647.0.0](https://coreos.com/releases/#647.0.0), so you'll either need to test the beta or alpha channels or wait for it to hit stable.
