### ISSUE TITLE
Replacing the mpt2sas kernel module on 899.15

### ISSUE THREAD

**Issue by laurentzoz** [coreos/bugs#1230]
Hi,  
i get these errors during any sequential write io load:

```
Apr 15 16:28:15 wiz-dock-b02 kernel: mpt2sas0: fault_state(0x0501)!
Apr 15 16:28:15 wiz-dock-b02 kernel: mpt2sas0: sending diag reset !!
Apr 15 16:28:16 wiz-dock-b02 kernel: mpt2sas0: diag reset: SUCCESS
Apr 15 16:28:16 wiz-dock-b02 kernel: mpt2sas0: LSISAS2308: FWVersion(20.00.04.00), ChipRevision(0x05), BiosVersion(07.39.00.00)
Apr 15 16:28:16 wiz-dock-b02 kernel: mpt2sas0: Protocol=(Initiator), Capabilities=(Raid,TLR,EEDP,Snapshot Buffer,Diag Trace Buffer,Task Set Full,NCQ)
Apr 15 16:28:16 wiz-dock-b02 kernel: mpt2sas0: sending port enable !!
Apr 15 16:28:26 wiz-dock-b02 kernel: mpt2sas0: port enable: SUCCESS
Apr 15 16:28:26 wiz-dock-b02 kernel: mpt2sas0: search for end-devices: start
```

i have this raid controller:
`02:00.0 Serial Attached SCSI controller [0107]: LSI Logic / Symbios Logic SAS2308 PCI-Express Fusion-MPT SAS-2 [1000:0086] (rev 05)`

Switching to the beta branch (which use mpt3sas instead of mpt2sas) solves the issue. But the servers will be production systems and i would really like to run the stable branch. I noticed there is a mpt3sas module on stable but i cant find a way to unload mpt2sas in order to replace it.

```
modinfo mpt3sas
filename:       /lib/modules/4.3.6-coreos/kernel/drivers/scsi/mpt3sas/mpt3sas.ko
version:        09.100.00.00
license:        GPL
description:    LSI MPT Fusion SAS 3.0 Device Driver
```

How can i make it happen?

**Comment by mischief** [comment]
have you tried `rmmod mpt2sas; modprobe mpt3sas`?

**Comment by mischief** [comment]
alternately, you could try `modprobe.blacklist=mpt2sas` on the kernel commandline.

**Comment by laurentzoz** [comment]
rmmod is telling me that the module is in use. Can't force remove it either.
I did add 
`set linux_append="modprobe.blacklist=mpt2sas"`
in /usr/share/oem/grub.cfg but the system did not boot with that.

**Comment by s19n** [comment]
On the older LSI SAS2008 I've seen happening the opposite: https://bugs.launchpad.net/ubuntu/+source/linux-lts-xenial/+bug/1625718 . Maybe there is something which prevents both controllers from working correctly with the unified mptsas driver?

**Comment by crawford** [comment]
The newer version of this driver has since made its way into the Stable channel.
