### ISSUE TITLE
ignition: Highlight Ignition v2.0.0 features

### ISSUE THREAD

**Issue by dghubble** [coreos/bugs#1234]
Can we add a docs page, CHANGES.md, or release note that highlights the features and reasons to use Ignition config v2.0.0? A new Ignition user asked "what are the cool new features in v2?" and the docs and NEWS.md don't showcase the work @crawford did.

**Comment by crawford** [comment]
Given Ignition's maturity, I didn't think we should spend much effort calling out the differences between different configuration versions. This is why it didn't make it into NEWS. Going forward, I'll be calling out changes in more detail in the NEWS.
