### ISSUE TITLE
multipath-tools blacklist problem

### ISSUE THREAD

**Issue by f0** [coreos/bugs#1236]
Hi,

recently, multipath-tools are included into coreos , is it possible to patch the version with some upstream bug fixes? 
To be exact this one:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782488

regards f0

**Comment by f0** [comment]
@mjg59  any news here?

**Comment by mjg59** [comment]
PR is up for this.

**Comment by f0** [comment]
@mjg59  Thanky you
