### ISSUE TITLE
Cannot boot production_pxe images with uefi enabled

### ISSUE THREAD

**Issue by rothgar** [coreos/bugs#1239]
I have a few systems I'm trying to boot with uefi enabled. I wanted to use uefi because it enables network booting via ipxe. In legacy boot (uefi disabled) I am able to get the system to boot by chainloading ipxe to my bootcfg server but if uefi is enabled I get the following errors during boot.

The system initially grabs the vmlinuz and initram but during the boot the initrd-switch-root.service fails because it can't find /sysroot/etc/os-release. It appears that in uefi mode the root file system isn't under /sysroot. After it fails I don't see anything under /sysroot when I ls the directory so I can't verify where the files are. The actual command that is running in the service is `systemd --no-block --force switch-root /sysroot`

I found [another post](http://zurlinux.com/?p=1887) about efi booting with systemd with a kernel option to set a different path for sysroot (`rootflags=subvol=root`) which will look in /sysroot/root/ for the system volume to switch to. I tried setting that in bootcfg and verified it after boot in /proc/cmdline but the system still fails to boot.

One option I have been able to make work is disable uefi, install coreos, enable uefi, boot system. This appears to work but is a lot more manual work. I'd like to figure out a way to get coreos to work natively with efi enabled.

**Comment by dghubble** [comment]
Have you seen the `bootcfg` example GRUB netboot of a UEFI client? I'd say it is somewhat experimental until we ship an official `grub.efi` if the OS team wants. I bundled the a `grub.efi` in `coreos/dnsmasq` for now.
 https://github.com/coreos/coreos-baremetal/blob/master/Documentation/dev/grub.md

**Comment by mischief** [comment]
@rothgar i can reproduce this bug with ipxe, but not with grub, under @dghubble's coreos-baremetal.  i can try to look into the iPXE/UEFI use case more.

**Comment by dghubble** [comment]
Booting with CoreOS grub.efi completes (via coreos-baremetal examples), but adding a root kernel argument like root=/dev/sda crashes to the emergency shell. Running from RAM will limit the clusters we can locally validate via qemu/PXE.

**Comment by muthu81** [comment]
@rothgar , where you able to find a solution for this issue? I have facing a similar issue with custom built CentOS-7 kernel. "legacy" booting of kernel image is fine, but when EFI enabled booting is done, it fails in initird-switch-root.service. One difference with yours is that under /sysroot/ I'm able to see the filesystem.

**Comment by rothgar** [comment]
@muthu81 No I never found a solution but only because I stopped trying. I left my systems in legacy mode. The only benefit I had for EFI was iPXE was built into the EFI whereas with legacy I had to chainload PXE via tftp -> iPXE.

**Comment by muthu81** [comment]
@rothgar , Thanks.
@dghubble @mischief , did you guys manage to find why direct EFI booting of kernel failed at "initrd-switch-root.service" ? I've tried tried numerous things, nothing helped.
Following are the logs...

---------------------------------------------------------------------------------------------------------------
Aug 17 14:54:55 dev03_gt systemd[1]: Starting Switch Root.
Aug 17 14:54:55 dev03_gt systemd[1]: Starting Switch Root...
Aug 17 14:54:55 dev03_gt systemctl[421]: Failed to switch root: Specified siwtch root path /sysroot does not seem to be an OS tree. os-release file is missing.
Aug 17 14:54:55 dev03_gt systemd[1]:  Failed to start Switch Root
 ---------------------------------------------------------------------------------------------------------------

This is a custom built kernel, and it works fine when I boot it through shim.efi and Grub loader.

But when I invoke the same kernel after changing its extension to .efi and invoking directly without the Grub, it goes this far and fails.

I'm missing something big, missing "os-release" file doesn't seem to be the real big issue. I created that file in /sysroot path. That file was available in "/etc/os-release", it was a symlink to "/etc/initrd-release". 
Also I'm able to see the filesystem mapping in /sysroot path. All that was there in "/boot/efi" is seen in /sysroot at this stage now.

I can recompile the kernel with whatever necessary changes that would be needed. 
Appreciate your help, Thanks.

**Comment by stuart-warren** [comment]
Believe we had the same problem, we found that you needed to specify an initrd parameter on the kernel line.
As an example:
```
#!ipxe
kernel /assets/coreos/1185.1.0/coreos_production_pxe.vmlinuz coreos.config.url=http://bootcfg.foo:8080/ignition?uuid=${uuid}&mac=${net0/mac:hexhyp} coreos.first_boot=1 coreos.autologin=tty1 initrd=coreos_production_pxe_image.cpio.gz
initrd /assets/coreos/1185.1.0/coreos_production_pxe_image.cpio.gz
boot
```

If using [coreos-baremetal](https://github.com/coreos/coreos-baremetal) then you can do so with the following profile:
```
{
  "id": "install-reboot",
  "cloud_id": "",
  "ignition_id": "install-reboot.yaml",
  "name": "Install CoreOS and Reboot",
  "boot": {
    "kernel": "/assets/coreos/1185.1.0/coreos_production_pxe.vmlinuz",
    "initrd": ["/assets/coreos/1185.1.0/coreos_production_pxe_image.cpio.gz"],
    "cmdline": {
      "coreos.autologin": "tty1",
      "coreos.config.url": "http://bootcfg.foo:8080/ignition?uuid=${uuid}&mac=${net0/mac:hexhyp}",
      "coreos.first_boot": "1",
      "initrd": "coreos_production_pxe_image.cpio.gz"
    }
  }
}
```

**Comment by crawford** [comment]
> Believe we had the same problem, we found that you needed to specify an initrd parameter on the kernel line.

That's odd. I don't know why that parameter would be needed. We include the initramfs in the kernel itself and set `CONFIG_INITRAMFS_SOURCE="bootengine.cpio"`. When you specify the initrd parameter to PXE (pointing to coreos_production_pxe_image.cpio.gz), the bootloader hands that image to the kernel which appends it to the `bootengine.cpio` that it has internally. If you are seeing a failure to switch-root, that would seem to indicate that your bootloader isn't handing off the initrd to the kernel properly.

**Comment by stuart-warren** [comment]
ping @mikebryant. Have I explained this wrong?

**Comment by mikebryant** [comment]
We found this note: http://ipxe.org/appnote/debian_preseed
```This is just a little more complicated than the previous example in that efi linux requires the initrd(s) to be passed on the command line```

My read is that under EFI when you specify `initrd /assets/coreos/1185.1.0/coreos_production_pxe_image.cpio.gz` instead of this being the root filesystem, this is placed as a file in the root filesystem - hence us then telling the kernel to load and decompress that file.

It looks like in PXE mode it just ignores the parameter, so the same config works for both EFI and PXE (using ipxe)

**Comment by mcuadros** [comment]
@stuart-warren THANKS! I just spent the full day try to fix this issue, and thanks to the `initrd` now is solve! 

We are booting using a iPXE in UEFI mode, instead of the grub.efi, because we are running in a VLAN network and we need to set the tag. (and I couldn't find a way to do this with grub).

Will be great if a UEFI boot section can be included in the documentation, because I must to say that was a real paint to setup this.

**Comment by crawford** [comment]
Yeah, we can go ahead and write up some docs. This is definitely a sharp corner.

**Comment by bgilbert** [comment]
Docs updated in coreos/docs@3c4bcacd0081e534c5b4943afde5cf1c0a7753a6 to add the `initrd=` argument to the kernel command line.  Thanks all!

**Comment by redbaron** [comment]
@ stuart-warren, enormous thanks for the tip, this UEFI problem took day of my life, but could be much worse if it wasn't for you.
