### ISSUE TITLE
Ignition: Remove camlistore errorutil dependency

### ISSUE THREAD

**Issue by dghubble** [coreos/bugs#1249]
The `github.com/camlistore/camlistore/pkg/errorutil` package does not exist in camlistore and hasn't for a while. Dependents of Ignition must copy Ignition's vendored copy into their own vendor directory, which does not play well with vendoring tools. The package was only used to provide the `HighlightBytePosition` function so this could be pulled into source or maybe another package carries it.

**Comment by jonboulle** [comment]
It's moved to `go4.org/errorutil` btw

**Comment by crawford** [comment]
> Dependents of Ignition must copy Ignition's vendored copy into their own vendor directory

Why is that? Neither [mantle](https://github.com/coreos/mantle/tree/master/Godeps/_workspace/src/github.com/coreos/ignition/config/vendor/github.com/camlistore/camlistore/pkg/errorutil) nor [fuze](https://github.com/coreos/mantle/tree/master/Godeps/_workspace/src/github.com/coreos/ignition/config/vendor/github.com/camlistore/camlistore/pkg/errorutil) do this.

**Comment by dghubble** [comment]
@crawford on a clean run, godep pulls it in so you're right the manual copy isn't needed.

Keeping this issue open to remove the outdated dep. You wanna just switch to `go4.org/errorutil`?

**Comment by crawford** [comment]
I'm unclear why this dep needs to be updated. Yes, it doesn't exist anymore. This is precisely the reason we vendor everything.

**Comment by dghubble** [comment]
Yes, the vendoring ensures there is no rush to update this dependency. But there is a valid new packaging of the source we can switch to, instead of depending on the outdated vendor copy.

**Comment by crawford** [comment]
What I'm trying to get at is the fact that I don't want to set a precedent that we are going to actively do house cleaning on dependencies (because, to be honest, I won't). Unless there is a particular reason to update that dependency, I am in favor of just leaving it. I'll take a PR though.

**Comment by dghubble** [comment]
Sure, up to you if you'd like to accept https://github.com/coreos/ignition/pull/232. Its not the end of the world if I vendor the copy as well. I usually prefer to maintain updated deps which are available at their given imports - using vendoring just to buy time.
