### ISSUE TITLE
Replace early-docker with rkt

### ISSUE THREAD

**Issue by UserTaken** [coreos/bugs#1252]
The sole purpose of [early-docker](https://coreos.com/flannel/docs/latest/flannel-config.html#under-the-hood) is to start flanneld before main Docker. Now it's possible to accomplish the same task using rkt that is already on the system using stage1-fly in conjunction with mount and exec overrides, without any additional modification to the manifest for a more straightforward implementation than running 2 copies of Docker. For security purpose an officially signed Flanneld ACI with predefined mounts would be a good idea. 

https://github.com/coreos/rkt/issues/13
https://github.com/coreos/rkt/issues/389

**Comment by crawford** [comment]
This was shipped in v1097.0.0.
