### ISSUE TITLE
typo in /etc/os-release

### ISSUE THREAD

**Issue by f0** [coreos/bugs#1253]
typo in PRETTY_NAME -> MoreOS -> CoreOS

```
cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=1010.1.0
VERSION_ID=1010.1.0
BUILD_ID=2016-04-07-0355
PRETTY_NAME="CoreOS 1010.1.0 **(MoreOS)**"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

```

**Comment by jonboulle** [comment]
Coming soon: MostOS

f0 <notifications@github.com> schrieb am Do., 28. Apr. 2016, 18:05:

**Comment by f0** [comment]
@jonboulle  or  better LessOS

**Comment by crawford** [comment]
Not a bug https://github.com/coreos/scripts/commit/d4103b08a6311a4191b6ccf786403b5a928113db. That is the release codename.

**Comment by f0** [comment]
@crawford  o_O cool don't know CoreOS releases has codenames....

**Comment by robszumski** [comment]
codename, bad joke, whatever :)

**Comment by marineam** [comment]
@crawford I told you Coregi was a better name!

**Comment by crawford** [comment]
@marineam dammit, haha. I thought the roman numeral joke would go over a bit better. I'm a thousand years too late.
