### ISSUE TITLE
ignition/semvar: Unmarshal YAML into Ignition 2.0.0 Config

### ISSUE THREAD

**Issue by dghubble** [coreos/bugs#1259]
With Ignition 2.0.0, YAML documents can no longer be marshaled into an Ignition 2.0.0 format [Config](https://github.com/coreos/ignition/blob/master/config/types/config.go#L28).

    document := `
    ignition:
      version: 2.0.0
    systemd:
      units:
        - name: etcd2.service
          enable: true`
    cfg := types.Config{}
    yaml.Unmarshal(document, &cfg)

Error

    cannot unmarshal !!str `2.0.0` into semver.Version

This unmarshal approach was used by fuze and coreos-baremetal to accept YAML documents and convert them to JSON, but no longer works for upgrading to Ignition v0.4.0.

* https://github.com/coreos/fuze/blob/master/src/main.go#L99
* https://github.com/coreos/coreos-baremetal/blob/master/bootcfg/http/ignition.go#L65

**Comment by crawford** [comment]
I'm wondering if the version should even be required by the tool doing the processing. If a particular version of the tool only accepts one version of the config, then it _could_ be elided.

**Comment by dghubble** [comment]
One way would just to make semvar.Version capable of unmarshaling a YAML document string, but I'm happy to do it some other way if you prefer.

**Comment by dghubble** [comment]
I'm needing to support both for a while. (1) I don't want to break existing users (2) Some of the coreos-baremetal examples can't be trivially upgraded yet (need to work around the data URL issue and revalidate cluster deploys)

**Comment by crawford** [comment]
I'm not familiar with the interface that your tool exposes. Can you provide some color?

**Comment by dghubble** [comment]
For coreos-baremetal? [Users provide templates](https://github.com/coreos/coreos-baremetal/blob/master/Documentation/ignition.md#configs) which are rendered and converted (if needed) to serve Ignition JSON to machines.

Validated CoreOS "profiles" use Ignition to install and provision certain sorts of cluster nodes. Once YAML unmarshaling is supported again, I can start to migrate the [Ignition config templates](https://github.com/coreos/coreos-baremetal/tree/master/examples/ignition) and validate the clusters produced.

* [Adding Ignition 2.0.0 Support](https://github.com/coreos/coreos-baremetal/issues/141)
