### ISSUE TITLE
Ignition /metadata endpoint should include {{.query}} variables

### ISSUE THREAD

**Issue by rothgar** [coreos/bugs#1262]
When writing ignition groups and files I have situations where I need to use values that were passed to bootcfg in the query but are not in the metadata for the matched system.

An example is a default group (no requirements) which does a CoreOS install. During the install I need to make other calls to internal inventory apis with the system $hostname as a unique key. The original query has the value I need (e.g. http://bootcfg/ignition?hostname=foo&metadata=bar)

My current solution is to write an ENV file with {{.query}} as the contents and then run

`sed -i -e 's/^.*?\(.*$\)/\1/' -e $'s/&/\\\n/g' /ENV`

This will change the file to look like

```
hostname=foo
metadata=bar
```

It works but would be nice to have that information available via /metadata. This way I could use `curl -o /ENV {{.metadata_endpoint}}?{{.query}}`

cc: @dghubble

**Comment by rothgar** [comment]
After testing this solution it looks like it already works this way. Good job taking care of these edge cases before I could even ask for it. :tada: 

If I make a request `curl http://bootcfg/metadata?foo=bar` I am returned the default ENV along with FOO=bar

```
BASE_URL=http://bootcfg:8080/assets/coreos/
COREOS_CHANNEL=alpha
COREOS_VERSION=1032.0.0
IGNITION_ENDPOINT=http://bootcfg:8080/ignition
HOSTNAME=host
FOO=bar
```

**Comment by dghubble** [comment]
Nice. Also, in future, feel free to file issues about `bootcfg` itself on [coreos-baremetal](https://github.com/coreos/coreos-baremetal)

**Comment by dghubble** [comment]
@rothgar I took another look at this. The `/metadata` endpoint should provide metadata from the machine group definition and the key/value pairs from the selector. Was "foo" a selector or metadata key/value in the matched group? What version of bootcfg are you using? I don't think arbitrary query params are added to the metadata response.

**Comment by dghubble** [comment]
Actually, what you're describing was done in coreos-baremetal bootcfg v0.2.0, but was removed in v0.3.0. I've opened https://github.com/coreos/coreos-baremetal/issues/182 to consider adding the feature back.
