### ISSUE TITLE
Add support for IPVS in the kernel

### ISSUE THREAD

**Issue by betawaffle** [coreos/bugs#1264]
It would be nice to be able to use [IPVS](https://en.wikipedia.org/wiki/IP_Virtual_Server) on CoreOS.

**Comment by aledbf** [comment]
@betawaffle it's already included
```
 $ sudo modprobe ip_vs
 $ more /proc/net/ip_vs
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port Forward Weight ActiveConn InActConn
```

You just need a container with `ipvsadm`

**Comment by betawaffle** [comment]
Badass!

**Comment by mimmus** [comment]
Any help about clearing the IPVS table?
'ipvsadm' from an Alpine-based container seems unable to manipulate the system table, even running it with '--privileged' option.

**Comment by bgilbert** [comment]
@mimmus We're planning to add `ipvsadm` to Container Linux; see https://github.com/coreos/portage-stable/pull/575.

**Comment by mimmus** [comment]
Wonderful!
In any case, I was able to manipulate IPVS kernel table using ipvsadm in the Container Linux "toolbox"
