### ISSUE TITLE
Cannot add user to group 'rkt'

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1267]
This is due to the fact that the 'rkt' group doesn't exist when Ignition is run - it shows up later (created by `systemd-sysusers`). Ignition should probably use sysuser configs instead of using `usermod`.

**Comment by marineam** [comment]
iirc using sysusers was the initial idea but that was dropped because sysusers doesn't support setting some fields like shell. Seems reasonable to extend sysusers though :)

**Comment by crawford** [comment]
Refer to https://github.com/coreos/bugs/issues/1920 instead.
