### ISSUE TITLE
CoreOS stable (899.15.0) flannel_docker_opts.env cannot be written using selinux

### ISSUE THREAD

**Issue by TheTechNick** [coreos/bugs#1270]
After setting selinux mode to "enforcing" flanneld is no longer able to write the file `/run/flannel_docker_opts.env` this prevents the configuration of the docker daemon to use the overlay network.

This configuration file is written in the ExecStartPost directive of the `flanneld.service` unit. Using selinux the container is not able to write or read files in the /run directory.
```
# Update docker options
ExecStartPost=/usr/bin/docker run --net=host --rm -v /run:/run \
quay.io/coreos/flannel:${FLANNEL_VER} \
/opt/bin/mk-docker-opts.sh -d /run/flannel_docker_opts.env -i
```

How to reproduce:
```
# enable selinux
sudo setenforce 1

# mount the /run directory into a docker container
docker run --rm -it -v /run:/run debian bash

# try to open the mounted /run folder
ls /run
> ls: cannot open directory /run: Permission denied
```

I also tried mounting the /run folder using the docker flag z or Z, this should normally configure the needed permissions. Unfortunately the docker daemon can not set the permissions:
```
docker run --rm -it -v /run:/run:Z debian bash
> Error response from daemon: operation not permitted

docker run --rm -it -v /run:/run:z debian bash
> Error response from daemon: operation not permitted
```

**Comment by mjg59** [comment]
I can't reproduce this in alpha. Are you able to test the current beta release? The docker integration with selinux was suboptimal in previous versions (it was primarily implemented around rkt) but should be working now.

**Comment by TheTechNick** [comment]
Hi, thanks for your quick response. I will try the beta channel on Monday.

But can you provide a workaround for the stable channel?
I think its hard to convince the people in my company to run the Beta channel in production :P

**Comment by mjg59** [comment]
I'm afraid that fixing this involved updates to both docker and our selinux policy, so there's no straightforward workaround. Using rkt rather than docker should work, but I appreciate that this may not be a terribly easy option…

**Comment by TheTechNick** [comment]
Migrating early docker to rkt is way out of my scope...
Can you point out a time frame when the beta-channel changes arrive in the stable channel?
Or is the beta channel considered "stable-enough" for production use?

**Comment by mjg59** [comment]
The new stable release should occur within around a week

**Comment by pizzarabe** [comment]
I had the same problem with stable 1068.9.0 and SELinux.

`docker[1612]: /opt/bin/mk-docker-opts.sh: line 83: /run/flannel_docker_opts.env: Permission denied`

but upgrading to the latest stable 1122.2.0 fixed that issue for me.
