### ISSUE TITLE
Introducing cloud-config-server

### ISSUE THREAD

**Issue by auguster** [coreos/bugs#1276]
Greating CoreOS community,

I made a little open-source project to serve templated cloud-config files from a dockerized server. I thought it might interest you. It's quite useful and it makes deploying cloud instances a lot more "fun" through code factoring and reutilization. You can compose your cloud-config files using different parts written in EJS (javascript templating). You can easily give custom arguments to your templates. I used it with PXE and classic static config, it works pretty well.

I'm of course opened to suggestion, remarks, PR ...

**Comment by robszumski** [comment]
This is cool and sounds very similar to [bootcfg](https://github.com/coreos/coreos-baremetal#bootcfg) which has similar functionality for serving customized cloud-config and ignition files.

**Comment by auguster** [comment]
Damn... I didn't know about bootcfg. Well, at least I had fun writing the project :)
