### ISSUE TITLE
audit/auditctl: Rules ordering

### ISSUE THREAD

**Issue by joshix** [coreos/bugs#1279]
There is a bug with ordering/making audit rules permanent in /etc/audit/rules.d:

``` sh
$ cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=1032.1.0
VERSION_ID=1032.1.0
BUILD_ID=2016-05-05-1941
...
$ cd /etc/audit/rules.d
$ ls -1v
00-clear.rules
80-selinux.rules
98-test.rules
99-default.rules
$ cat 98-test.rules 
-w /tmp/a.txt -p wa -k a_change
$ sudo auditctl -l
-w /tmp/a.txt -p wa -k a_change <<<<<<<<<<<<<< #98 is first
-a never,exclude -F msgtype>=AVC -F msgtype<=1499
-a never,exclude -F msgtype=CONFIG_CHANGE
-a always,exclude -F msgtype>0
```

**Comment by joshix** [comment]
related #140

**Comment by glevand** [comment]
@joshix I think your expected result is the problem, and that audit support is working correctly.

The file name ordering only dictates the order that the rule files are processed (`augenrules --load` uses `ls -1v /etc/audit/rules.d`).  This is working correctly, and viewing `/etc/audit/audit.rules` will confirm it.

The rule ordering is only relevant to rules that are order dependent like 'list append'.  Your watch rule has no ordering, so when listed with `auditctl -l`, it shows up on top.

Here's a test with an append rule:

    # auditctl -D
    # echo '-a never,exclude -F msgtype=555' > /etc/audit/rules.d/98-test.rules
    # augenrules --load
    # auditctl -l
    -a never,exclude -F msgtype>=AVC -F msgtype<=1499
    -a never,exclude -F msgtype=555
    -a never,exclude -F msgtype=CONFIG_CHANGE
    -a always,exclude -F msgtype>0

My `555` rule is between the `80-selinux.rules` and the `99-default.rules` as it should be.

@dm0- I think this issue can be closed.

**Comment by dm0-** [comment]
Thanks for looking into this.
