### ISSUE TITLE
kubelet-wrapper can't execute in CoreOS 1045.0.0/rkt 1.5.1

### ISSUE THREAD

**Issue by mischief** [coreos/bugs#1282]
sometime between rkt 1.2.1 and 1.5.1, it now checks if the path to the stage1 given to --stage1-path is 'trusted', and if not, tries to verify the signature. kubelet-wrapper uses the 'old' path, `/usr/share/rkt/stage1-fly.aci`, which is symlinked into the new rkt stage1 dir, but not 'trusted' by rkt, resulting in the error:

```
image: using image from file /usr/share/rkt/stage1-fly.aci
run: open /usr/share/rkt/stage1-fly.aci.asc: no such file or directory
```

**Comment by philips** [comment]
@mischief what is the fix? Are we pausing updates?!

**Comment by crawford** [comment]
@philips we are going to continue rolling out 1032.1.0 while we figure this one out.

**Comment by mischief** [comment]
@philips: see https://github.com/coreos/coreos-overlay/pull/1959

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/1959.
