### ISSUE TITLE
Gziping and base64 not working together.

### ISSUE THREAD

**Issue by alexandrst88** [coreos/bugs#1286]
Hi there, 

I have a big cloud-config file which much bigger than 16KB, and i need to spin up a AWS Spot instance.

According to this doc http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html it must be **base64**. 

But when i launch the instance with gzip and base64, CoreOS can read this cloud-config

Example:
aws ec2 request-spot-instances --spot-price "0.26" --launch-specification "{ \"ImageId\" : \"ami-05783d60\", \"KeyName\":\"keypair\", \"SecurityGroupIds\": [\"sg-xxxxxxx\"], \"UserData\":\"$(gzip -c -n file | base64 -w 0))\",  \"InstanceType\":\"m3.xlarge\", \"BlockDeviceMappings\": [{\"DeviceName\":\"/dev/xvda\",\"Ebs\": {\"VolumeSize\": 50}}], \"SubnetId\":\"subnet-xxxxx\" }"

Cloud config is not applied to the instance, even can't ssh to it(It's says connection refused, it's happens when cloud-config has some errors, but the text file is vaild on 100%. Validated by https://coreos.com/validate/).

**Comment by crawford** [comment]
Sounds like https://github.com/coreos/bugs/issues/1047. What version of CoreOS is this?

**Comment by alexandrst88** [comment]
CoreOS stable (766.4.0): As I see AWS decode data, but leave it in the gzip format here 
```
2016/05/17 09:32:47 Fetching data from http://169.254.169.254/2009-04-04/user-data. Attempt #1
line 1: error: must be "#cloud-config" or begin with "#!"
Fetching meta-data from datasource of type "ec2-metadata-service"
2016/05/17 09:32:47 Fetching data from http://169.254.169.254/2009-04-04/meta-data/public-keys. Attempt #1
2016/05/17 09:32:47 Fetching data from http://169.254.169.254/2009-04-04/meta-data/public-keys/0/openssh-key. Attempt #1
Found SSH key for "gsg-keypair"
2016/05/17 09:32:47 Fetching data from http://169.254.169.254/2009-04-04/meta-data/hostname. Attempt #1
2016/05/17 09:32:47 Fetching data from http://169.254.169.254/2009-04-04/meta-data/local-ipv4. Attempt #1
2016/05/17 09:32:47 Fetching data from http://169.254.169.254/2009-04-04/meta-data/public-ipv4. Attempt #1
Failed to parse user-data: Unrecognized user-data format
Continuing...
```

**Comment by crawford** [comment]
Oh my, 766.4.0 is very old. You should definitely update that. Support for gzipped userdata wasn't added until 870.2.0.

**Comment by alexandrst88** [comment]
I'm so sorry, could you please re-open an issue, I copied CoreOS version from another machine.
Issue happens on the CoreOS stable (899.17.0). 
So when i gzip and then base64 user-data, Cloud config is not applied to the instance, even can't ssh to it(It's says connection refused, it's happens when cloud-config has some errors, but the text file is vaild on 100%. Validated by https://coreos.com/validate/).

**Comment by crawford** [comment]
Can you run two tests from that instance?

`curl http://169.254.169.254/2009-04-04/user-data | gzip --decompress --stdout | coreos-cloudinit --validate --from-file /dev/stdin`

`coreos-cloudinit --validate --from-url http://169.254.169.254/2009-04-04/user-data`

**Comment by alexandrst88** [comment]
Basically, I can't even ssh to the instance. It says connection refused. Usually this happens due to bad user-data (cloud-config). You could reproduce this issue with the launching **spot-instance**:

aws ec2 request-spot-instances --spot-price "0.26" --launch-specification "{ \"ImageId\" : \"ami-05783d60\", \"KeyName\":\"keypair\", \"SecurityGroupIds\": [\"sg-xxxxxxx\"], \"UserData\":\"$(gzip -c -n file | base64 -w 0))\", \"InstanceType\":\"m3.xlarge\", \"BlockDeviceMappings\": [{\"DeviceName\":\"/dev/xvda\",\"Ebs\": {\"VolumeSize\": 50}}], \"SubnetId\":\"subnet-xxxxx\" }"

With you instance type and etc.

**Comment by crawford** [comment]
If you've specified a keypair via the AWS API, the key will be inserted into the machine, regardless of the validity of your userdata. Something else is going wrong. Try this sequence:

 1. Boot instance with keypair but no userdata
 2. Verify you can SSH in
 3. Power off the instance
 4. Add your userdata
 5. Power on the instance
 6. SSH in and grab the logs (`journalctl -b -t coreos-cloudinit --no-pager`) and run my two tests

**Comment by alexandrst88** [comment]
1. I can't shutdown spot instance, because it will gone.
2. I've made two tests, 
1) I ran instance, ssh connection is ok. Then shutdown instance, add gzip + base64 user-data, and power on instance. Everything was working fine.
2) But when I've added user-data with first instance launching i cant event ssh to it.
```
port 22: Connection refused
```

**Comment by crawford** [comment]
> I ran on-demand instance, ssh connection is ok. Then shutdown instance, add gzip + base64 user-data, and power on instance. Everything was working fine.

So this confirms my original theory. You need at least Ignition [v0.2.5](https://github.com/coreos/ignition/blob/v0.2.5/NEWS#L5) (CoreOS [921.0.0](https://coreos.com/releases/#921.0.0)) to use gzipped user-data.

> I will be appreciate you if you give me a link to the Developer Guide or something, in other words how can setup like Dev env for CoreOS.

https://coreos.com/os/docs/latest/sdk-modifying-coreos.html

**Comment by alexandrst88** [comment]
I've tested with CoreOS beta (1010.3.0), and everything works as expected, thank you @crawford.
