### ISSUE TITLE
Support disabling services

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1287]
Somehow I overlooked this feature... There is no way to disable a service which is enabled by default.

**Comment by dgonyeo** [comment]
Should I add a `disable` field, or just explicitly disable any units that have `enable` set to false?

**Comment by crawford** [comment]
The code already exists in [my branch](https://github.com/crawford/ignition/commits/disable). The problem is more around we enable services in our build system. We don't use presets and instead create symlinks in `/usr/lib/systemd`. Because of this, Ignition cannot disable those services. The user instead has to mask them.
