### ISSUE TITLE
Update open-vm-tools

### ISSUE THREAD

**Issue by tux21b** [coreos/bugs#1288]
Please consider updating open-vm-tools to version 10 and adding libfuse to the base install of the vmware image. This allows users to mount shared folders via the new "vmhgfs-fuse" tool:
`vmhgfs-fuse -o allow_other -o auto_unmount .host:/shared_folder /mnt/shared_folder`.
(the legacy kernel module vmhgfs still doesn't work but I think that is acceptable)

We would like to use CoreOS in production for on-premise instances as well as during development for local developer instances and the shared folder feature would be great for the later use case. I have already copied the required files manually and everything works great.

**Comment by crawford** [comment]
Related https://github.com/coreos/bugs/issues/630.

**Comment by crawford** [comment]
We can certainly update to version 10, but we won't be adding the fuse support. Container Linux is targeted toward production environments; not so much development.
