### ISSUE TITLE
kubernetes 1.2 and docker 1.10 errors

### ISSUE THREAD

**Issue by davidewatson** [coreos/bugs#1289]
I have a 10-node kubernetes cluster running on AWS m3.medium instances with CoreOS. When I run the kubernetes density e2e tests, containers fail to start with the error "System error: The minimum allowed cpu-shares is 1024". The requested CPU shares is 10 for each container. I have not seen this error when using AWS m3.large instances.

I opened a ticket against docker and they believe the problem has been fixed in docker 1.11 (https://github.com/docker/docker/issues/22818)

This is a blocking issue for us because it prevents us from running kubernetes density tests. Do we know when to expect a CoreOS release with docker 1.11?

**Comment by davidewatson** [comment]
From the ticket linked above, I believe this [PR](https://github.com/opencontainers/runc/pull/491) fixes our problem. Note that Samsung would like to pay to have this back ported to docker 1.10, or see a release of CoreOS with docker 1.11.

**Comment by philips** [comment]
@davidewatson this is set for the milestone for next week. Meaning we will look into it this week and it will release into Alpha next week.

**Comment by philips** [comment]
@davidewatson We have also been playing with running the docker engine under rkt. Here is an example service file: https://gist.github.com/philips/4ba6f9888499266b0ab09d95991e6784

**Comment by davidewatson** [comment]
The latest released version is currently 1053.2.0. I do not see anything in the change logs to suggest that this fix has been back ported to that version. Is there a plan for when 1080.0.0 or 1066.0.0 will be available?

**Comment by crawford** [comment]
@davidewatson this ended up getting pushed back to the 1080.0.0 release since it is not a trivial change. 1080.0.0 will be released on the 16th of the month. Sorry for the delay.
