### ISSUE TITLE
ignition: enable systemd unit does not work?

### ISSUE THREAD

**Issue by j-vizcaino** [coreos/bugs#1291]
Hi,

I've been giving ignition a try recently and I can't get the `enable` feature for systemd unit to work.

**How to reproduce**

* Spin up a Vagrant box with CoreOS 1010.3.0 or 1032.1.0 (tested both)
* Edit `/usr/share/oem/grub.cfg`, comment out the `set oem_id` line and add `set linux_append="coreos.first_boot=1 coreos.config.url=http://<url>"`
* Reboot the VM, Ignition should now run (checked with `journalctl --identifier=ignition`)

The Ignition file I used for the test is the one from the examples in the doc:

```json
{
  "ignition": { "version": "2.0.0" },
  "systemd": {
    "units": [{
      "name": "example.service",
      "enable": true,
      "contents": "[Service]\nType=oneshot\nExecStart=/usr/bin/echo Hello World\n\n[Install]\nWantedBy=multi-user.target"
    }]
  }
}
```

**What happens**

* The `example.service` is properly created and its contents match
* The service **does not start on boot**!

Reading the code, I see that enabling unit is done adding a line to the system-preset file `/etc/systemd/system-preset/20-ignition.preset`. This works as well because:

```
$ systemctl status example
* example.service
  Loaded: loaded (/etc/systemd/system/example.service); disabled; vendor preset: enabled)
  Active: inactive (dead)
```

Where/when does the unit get enabled during the boot process? It is because I am running Vagrant/Virtualbox and the vagrant box image does not have the "enable-services" hook on startup?

**Comment by crawford** [comment]
systemd presets are only evaluated on first boot. Since you are running Ignition on the second boot, you'll need to remove `/etc/machine-id` (that will trigger systemd's first-boot actions) before you do that first reboot or run `systemctl  preset-all` to evaluate the presets.

**Comment by j-vizcaino** [comment]
Thank you! I suspected something like that but could not find the trick anywhere. I will give it a try on Monday. You can close the issue.

**Comment by j-vizcaino** [comment]
That worked perfectly.
In order to quickly test my Ignition configuration using Vagrant, all I have to do is follow the steps I mentioned above plus removing `/etc/machine-id` before rebooting.
I hope this will be helpful to other people where testing on bare-metal is usually painful (servers BIOS or EFI is so sloooowwww)
