### ISSUE TITLE
version.txt updated yet vmlinuz was not updated

### ISSUE THREAD

**Issue by stelund** [coreos/bugs#1293]
Our alpha machine booted but had problems to get into our test cluster.

The docker hosts yells at us with:
'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded
Error starting daemon: error initializing graphdriver: driver not supported

We also notice that our cifs mounting also fails with cifs filesystem is not supported.

Looking at lsmod compared 1053.2.0 and 1010.3.0 there is a big change.

Is this intentional that they have changed to modules?

**Comment by mischief** [comment]
i can't seem to reproduce a problem with docker and overlay. how are you running it?

**Comment by stelund** [comment]
I think we have an drop-in to docker.service to add --storage-driver=overlay. But I can confirm a bit later. The host is in vmware, perhaps it is a problem with vmware tools.

**Comment by stelund** [comment]
ExecStartPre=/bin/mount --make-rprivate /
ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H tcp://0.0.0.0:4243 -H unix:///run/docker.sock --dns 10.22.0.15 --dns 10.22.0.16
and
LimitNOFILE=10240

If you can't repoduce this I suppose it's vmware tools that's causing it. I will continue to investigate it on monday.

Thanks

**Comment by stelund** [comment]
Seems we got the linux 4.5 kernel when updated our pxe boot images.

@mischief Is it so that the your release script can update version.txt before coreos_production_pxe.vmlinuz? If so it's a race condition which caused the issue.

**Comment by crawford** [comment]
@stelund if you are looking at the "current" directory, then yes, they are subject to eventual consistency (nothing we can do about that). I would recommend reading version.txt out of "current" and then referring to the exact version directory when pulling the rest of the assets. For example:

```
$ curl https://alpha.release.core-os.net/amd64-usr/current/version.txt
COREOS_BUILD=1053
COREOS_BRANCH=2
COREOS_PATCH=0
COREOS_VERSION=1053.2.0
COREOS_VERSION_ID=1053.2.0
COREOS_BUILD_ID="2016-05-20-0151"
COREOS_SDK_VERSION=1032.0.0
```

```
$ curl https://alpha.release.core-os.net/amd64-usr/1053.2.0/coreos_production_vmware_ova.ova ...
```

**Comment by stelund** [comment]
Great! Thank you!
