### ISSUE TITLE
CoreOS 1010.* networking breaks Rancher orchestration

### ISSUE THREAD

**Issue by sshipway** [coreos/bugs#1294]
When using Rancher 'Cattle' orchestration, inter-host communication is broken under CoreOS 1010 and later (though it works fine in CoreOS 899.*, and when using Docker 1.10.x under Debian).

This seems to be an issue with the way CoreOS Docker is compiled.

See these reports
https://github.com/rancher/rancher/issues/4874
https://github.com/rancher/rancher/issues/4745
https://github.com/rancher/rancher/issues/4238

**Comment by crawford** [comment]
Sounds like this has been fixed.
