### ISSUE TITLE
ignition: filesystems.mount.create.force option is misleading

### ISSUE THREAD

**Issue by j-vizcaino** [coreos/bugs#1295]
Stating the documentation, the option is meant to toggle 
> whether or not the create operation shall overwrite an existing filesystem

Reading the code, this is not true (at least for `mkfs.ext4`): using this option adds the `-F` option to mkfs, which is meant to force `mkfs` when using whole disk (instead of partitions), or ignoring unknown command line options.

Therefore, **no matter what force option is specified**, the target device is **always formatted**!

**Comment by crawford** [comment]
Ugh, it [looks like](http://git.kernel.org/cgit/fs/ext2/e2fsprogs.git/tree/misc/mke2fs.c?h=v1.42.13#n1793) e2fsprogs will silently destroy existing filesystems unless it is being run from a terminal.

**Comment by j-vizcaino** [comment]
The mkfs  behavior is strange because according to `man mkfs.ext4`, the `-F` flag is:

> Force mke2fs to create a filesystem, even if the specified device is not a partition on a block special device, or if other parameters do not make sense.  In order to force mke2fs to create a filesystem even if the filesystem appears to be in use or is mounted (a truly dangerous thing to do), this option must be specified twice.

Nothing states that the filesystem should be preserved.

By the way, there's almost the same problem with XFS, because without `-f` mkfs will not overwrite existing FS (which is good) but not ensure that the underlying FS is actually XFS. This will lead to Ignition running successfully but systemd failing to mount the volume afterwards.

Kubernetes has some sort of trick to "format volume when needed" and I think it uses `fsck` to check whether the volume has a valid and expected FS on it.

**Comment by crawford** [comment]
> but not ensure that the underlying FS is actually XFS

But the command _will_ fail, causing Ignition and the boot to fail.

```
May 23 21:02:22 localhost ignition[234]: disks: failed to create filesystems: failed to run "/sbin/mkfs.xfs": exit status 1: Stderr: "mkfs.xfs: /dev/disk/by-label/ROOT appears to contain an existing filesystem (xfs).\nmkfs.xfs: Use the -f option to force overwrite.\n" [-L ROOT /dev/disk/by-label/ROOT]
```

**Comment by j-vizcaino** [comment]
You're right.

Still, there's something awkward about the "force" behavior implemented right now: if a user wants to reinstall his machine without formatting an extra partition, he has to modify the existing Ignition config file because there is no way for Ignition to "just check" that the FS format is the expected one.

What would you think of this instead?
* `force: false` → format if FS does not conform, preserve otherwise
* `force: true` → always format, no matter what's on the partition

**Comment by crawford** [comment]
https://github.com/coreos/bugs/issues/1070#issuecomment-181497578

We are going to add another flag to explicitly allow reusing a file system.

**Comment by j-vizcaino** [comment]
Don't you think adding another flag will lead to more confusion?
What would happen when `force: true` and `reuseExisting: true`? (if combination is valid)
Also, adding a new flag and not changing the force behavior would still mean modifying the Ignition config file on the second install when preserving the extra volume that got formatted on the first install. That would be far from ideal.

**Comment by crawford** [comment]
> What would happen when `force: true` and `reuseExisting: true`? (if combination is valid)

At first glance, I would say this is invalid. `force` should blow away any data (regardless of filesystem) and `reuseExisting` should ensure that the filesystem is of the correct format (created if necessary).

> Also, adding a new flag and not changing the force behavior would still mean modifying the Ignition config file on the second install when preserving the extra volume that got formatted on the first install.

The intent is to provide `reuseExisting: true` always (if this is acceptable). Of course, this will only work once Ignition supports the flag.

**Comment by j-vizcaino** [comment]
It seems using `force: false` and `reuseExisting: false` would be a useless combination also. Do you really think adding another option is necessary?

**Comment by crawford** [comment]
`force: false` and `reuseExisting: false` might be useful for ensuring that a fresh filesystem is created and yet no data is lost, though this does feel a bit contrived. My bigger concern is changing the semantics of `force`.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/ignition/pull/243. We will revisit the `force` and `reuseExisting` in another issue.
