### ISSUE TITLE
ignition: systemd or networkd unit files without contents

### ISSUE THREAD

**Issue by j-vizcaino** [coreos/bugs#1298]
It seems the Ignition code has support for early-return when unit files have no content.
Is this intentional? because when there's nothing to write, Ignition still logs "Writing unit foo." but does not actually write anything!

I wasted 2 hours today because I forgot the "s" in "contents":

* Ignition was happy loading the JSON
* log entries showed "Start writing unit foo" and "Finished writing unit foo"

Please consider either, setting the "contents" field as mandatory or at least logging a warning when unit file is not written because it has no content.

**Comment by crawford** [comment]
Yes, this is intentional. When enabling an existing unit, we wouldn't want to write a blank unit to `/etc`. The logging could probably be a bit better around that operation.

Ignition will show the parsed config in the log. This is your best bet (right now) to determine whether or not Ignition is parsing your config correctly.

**Comment by j-vizcaino** [comment]
Actually, the problem I encountered was with `networkd` units. Can these too have no contents?

Dumping the content of the config file would help (unless the JSON is really big), but the most disturbing problem I find is that the log shows *misleading* information.

To be clear, I'm talking about the log produced by `s.Logger.LogOp` of `writeSystemdUnit` and `writeNetworkdUnit` functions, located in `internal/exec/stages/files/files.go`. This logs `Writing unit...` whereas there's a chance for the function not to write anything.

**Comment by crawford** [comment]
`networkd` units can also have no comments, but they won't have any effect (other than masking another identically named unit).

We'll have to improve the logging a bit around this.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/ignition/pull/301.
