### ISSUE TITLE
kubelet-wrapper: launching kubelet with hyperkube

### ISSUE THREAD

**Issue by j-vizcaino** [coreos/bugs#1299]
`kubelet-wrapper` starts `kubelet` using `/kubelet` which is a symlink to `/hyperkube`.
It seems this is specific to the CoreOS Hyperkube ACI image: looking at Google's Hyperkube images, there's no `/kubelet` symlink.

How about starting `kubelet` using `hyperkube kubelet $@` instead of `kubelet $@`?
This way, both CoreOS images and Kubernetes pristine images would be compatible with `kubelet-wrapper`

**Comment by euank** [comment]
As of Kubernetes v1.4.0, those symlinks exist in the upstream image too: https://github.com/kubernetes/kubernetes/pull/29591
