### ISSUE TITLE
cloud-config in EC2 UserData causes instance to fail to boot

### ISSUE THREAD

**Issue by nathankunicki** [coreos/bugs#1300]
Hi,

I'm encountering an issue with using cloud-config as UserData when booting an EC2 CoreOS instance. I'm attempting to enable the Docker remote API port as per the [documentation here](https://coreos.com/os/docs/latest/customizing-docker.html#cloud-config). My cloud-config is essentially copypasta:

```
#cloud-config

coreos:
  units:
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        BindIPv6Only=both
        Service=docker.service

        [Install]
        WantedBy=sockets.target
```

When I add this as UserData the instance fails to boot, and after a while begins to fail its EC2 status checks. Thanks to the new "Get Instance Screenshot" feature on EC2 ([Literally launched yesterday](https://aws.amazon.com/about-aws/whats-new/2016/05/ec2-now-supports-the-ability-to-capture-screenshots-of-an-instance-console/)) I'm able to see what the hypervisors view of the startup process is:

![screen shot 2016-05-25 at 15 28 01](https://cloud.githubusercontent.com/assets/2862695/15543613/72fe1b9a-228d-11e6-9d82-8115055a6c8e.png)

Unfortunately as the instance fails to boot and I can't ssh to the machine, I do not have any further logs to show you.

An additional note is that when I spin up an instance without this UserData, then manually add the docker-tcp.socket service to /etc/systemd/system, enable and start it, it all works fine.

I'm using AMI "ami-feaa228d" in the eu-west-1 region.

Cheers,
Nathan

**Comment by nathankunicki** [comment]
An additional note, I've also tried the following as UserData, with the same result:

```
#!/bin/bash
set -ex

cat<<-EOF > /etc/systemd/system/docker-tcp.socket
[Unit]
Description=Docker Socket for the API

[Socket]
ListenStream=2375
BindIPv6Only=both
Service=docker.service

[Install]
WantedBy=sockets.target
EOF

systemctl enable /etc/systemd/system/docker-tcp.socket
systemctl start docker-tcp.socket
```

**Comment by crawford** [comment]
Which version of CoreOS is this? Can you provide the instance/system logs (you can get those from the EC2 web UI)?

**Comment by nathankunicki** [comment]
AMI is ami-feaa228d, listed [here](https://coreos.com/os/docs/latest/booting-on-ec2.html) on the CoreOS site, which I believe is the latest. Version 899.17.0.

Unfortunately the system logs are blank:

![screen shot 2016-05-25 at 18 46 28](https://cloud.githubusercontent.com/assets/2862695/15550374/040a0142-22a9-11e6-9b6e-872865df70de.png)

**Comment by crawford** [comment]
There is a known issue with HVM logging (EC2 folks are looking into it) that prevents the full boot logs from showing up. If you use a PV instance, the logs will be present and it should be clear what failed. My guess is that Ignition doesn't recognize the config and is failing. Is there any leading whitespace in your config? Is the config compressed?

**Comment by nathankunicki** [comment]
Well I'll be damned, that was it! I'm using ES6 multi-line strings and putting the #cloud-config instruction on the first line meant there was a line break at the beginning.

Will close the issue.

Thanks!
