### ISSUE TITLE
"Error relabeling merged directory: operation not supported" when building docker inside docker

### ISSUE THREAD

**Issue by Hartimer** [coreos/bugs#1301]
I came across this error and I'm not sure how to fix it.

For the record, the faulty commit seems to be https://github.com/coreos/docker/commit/8acee1bc06813191ba5ea396137e1c17a7120bdf and I was pointed there by https://github.com/docker/docker/issues/22548.

I'm trying to build a docker image from within a docker container to which I mounted the host's docker binay and socket.

We're using:
```
NAME=CoreOS
ID=coreos
VERSION=1010.3.0
VERSION_ID=1010.3.0
BUILD_ID=2016-05-05-0730
PRETTY_NAME="CoreOS 1010.3.0 (MoreOS)"
```
and `Docker version 1.10.3, build 8acee1b`

Similar to what the user described on the linked issue, this is what I'm getting:

```
> docker build --rm -t myimage:mytag .
Sending build context to Docker daemon 24.58 kB
Step 1 : FROM baseimage
 ---> 63e9b759074e
Step 2 : MAINTAINER <me>
 ---> Using cache
 ---> 13fcbeec8eab
Step 3 : RUN mkdir -p /home/jenkins-slave
 ---> Running in 1acfaece4e8a
Error relabeling merged directory: operation not supported
```

The parameter -p is irrelevant, I get the same error with or without it. Any advice?

**Comment by mischief** [comment]
cc @mjg59

**Comment by mjg59** [comment]
Hm. I'm going to need to look at the behaviour of upstream Docker in this case - when running inside a confined selinux context, we don't want Docker to attempt to change to a new context.

**Comment by DerekTBrown** [comment]
I was receiving the same error trying to build a modified Alpine docker image in CoreOS v1010.5.0 running inside Vagrant/Virtualbox. which seems to indicate it is not a Docker-inside-Docker container problem.  I was able to solve the error by running the docker build command using sudo.

**Comment by derDieDasJojo** [comment]
I got this error when i mixed up pulling from docker hub automated build and self build images.
removing old images solved the problem for me: `docker rmi $(docker images -q)`

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/2006.
