### ISSUE TITLE
CoreOS stuck at 899.17 update, won't update itself or manually

### ISSUE THREAD

**Issue by gutigen** [coreos/bugs#1304]
I'm using single CoreOS instance and I've just noticed that it had not updated since 899.17, whats up with that? I restored it from snapshot which had same cloud config.

My cloud config:
https://gist.github.com/gutigen/43f45ce0bb85c11270201e14084a5dcc

```
sudo update_engine_client -update
[0527/195901:INFO:update_engine_client.cc(243)] Initiating update check and install.
[0527/195901:INFO:update_engine_client.cc(248)] Waiting for update to complete.
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0.0
NEW_SIZE=0
[0527/195906:ERROR:update_engine_client.cc(189)] Update failed.
```

**Comment by crawford** [comment]
Automatic updates from the public CoreOS update service are inherently more conservative than fresh images. They are subject to rate-limiting and other slow-downs out of an abundance of caution. If you would like to bypass this behavior, [Premium Managed Linux](https://coreos.com/products/premium-managed-linux/) is available which gives you access to your own deployment of CoreUpdate, giving you absolute control over updates.

**Comment by gutigen** [comment]
To clarify, I cannot update manually and I have to wait for some specific time to actually get an update, is that correct?

**Comment by crawford** [comment]
The Stable channel is currently held at 899.17.0 for the long weekend in the US. We are planning on rolling it on Tuesday morning (PDT).

**Comment by gutigen** [comment]
oh I see... I've seen higher version being available at Digital Ocean so I thought it was what I was suppose to have, thanks!
