### ISSUE TITLE
filesystems.mount.create.force: true leads to unusable system when running dev images

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/bugs#1307]
When using dev images (i.e. built with ./build_image dev) setting the filesystems.mount.create.force flag to true in ignition causes an unbootable system next boot. The system will boot, but the update engine, cloud config, and authorization manager will fail to start, preventing being able to log in, even with coreos.autologin set in grub.

Tested with btrfs, ext4, and xfs

Does not effect prod images.

ignition config used (xfs can be substituted for brtfs/ext4):

``` json
{
  "ignition": { "version": "2.0.0" },
  "storage": {
    "filesystems": [{
      "mount": {
        "device": "/dev/disk/by-label/ROOT",
        "format": "xfs",
        "create": {
          "force": true,
          "options": [ "-L=ROOT" ]
        }
      }
    }]
  }
}
```

Furthermore, the journal (under /var/log/journal) is empty.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
