### ISSUE TITLE
Support Brendan Gregg's perf-tools

### ISSUE THREAD

**Issue by ryao** [coreos/bugs#131]
I tried using opensnoop from Brendan Gregg's perf-tools when developing the ZFS on CoreOS prototype. Unfortunately, the image did not support it:

https://github.com/brendangregg/perf-tools
https://github.com/ClusterHQ/flocker/blob/zfs-on-coreos-tutorial-667/docs/experimental/zfs-on-coreos.rst

I used strace to do what I had wanted, but it would be nice to have support for ftrace-based tools inside the kernel. I am filing this because @marineam requested the issue be filed after I mentioned it to him.

**Comment by mwitkow** [comment]
Hi, is there any movement on this?

We'd love to use `perf` to profile our staging environments. The current CoreOS image is missing a couple of kernel modules and some userspace stuff to make it happen. @ashmere

**Comment by crawford** [comment]
There hasn't been any movement. It's just not a high enough priority. Pull requests would be greatly appreciated.

**Comment by bossjones** [comment]
Curious if anyone else was ever able to give this a shot. Would be nice to run perf tools against lab environments or even production to evaluate issues. Also thanks for such an awesome OS.

**Comment by dannyk81** [comment]
>4 years and this is still an issue 😞 

CoreOS is awesome, until you need to troubleshooting some complex issue, the toolbox is relatively limited as none of the kernel-interfacing tools can be used... took me couple of days just to get Systemtap [working](https://medium.com/makingtuenti/systemtap-for-coreos-container-linux-b2c0a0b5dce3), no luck with perf - seems like a capabilities masking/restriction in systemd-nspawn.

We have an issue in our production servers with high system cpu utilization, however we cannot determine what is causing it, we suspect delays in RX packet processing but we can't find a way to profile the kernel cpu usage...

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.

**Comment by cyrus-mc** [comment]
I was able to get perf to work in toolbox by simply adding the --system-call-filter option to the systemd-nspawn call in toolbox. 

> sudo systemd-nspawn \
        --directory="${machinepath}" \
        --capability=all \
        --share-system \
        --system-call-filter=perf_event_open \
        ${TOOLBOX_BIND} \
        ${TOOLBOX_ENV} \
        --user="${TOOLBOX_USER}" "$@"

**Comment by DeviaVir** [comment]
@cyrus-mc I'm seeing a segmentation fault when I add that:
```
[root@b1423 ~]# perf record -p "18783"
perf: Segmentation fault
Obtained 9 stack frames.
perf(+0x2d0908) [0x56185a65e908]
/lib64/libc.so.6(+0x3c6b0) [0x7f2e35d686b0]
perf(+0x290cfd) [0x56185a61ecfd]
perf(+0x20f226) [0x56185a59d226]
perf(+0x21035d) [0x56185a59e35d]
perf(+0x27e833) [0x56185a60c833]
perf(+0x1f9964) [0x56185a587964]
/lib64/libc.so.6(__libc_start_main+0xf3) [0x7f2e35d531a3]
perf(+0x1f9bbe) [0x56185a587bbe]
Segmentation fault (core dumped)
```
Did you make any other changes?
