### ISSUE TITLE
1010.5.0 - docker 1.10.x pushed, causing lstat issues

### ISSUE THREAD

**Issue by chr0n1x** [coreos/bugs#1311]
Same issue as https://github.com/coreos/bugs/issues/1245, logging here with our own logs since this is now in stable.

Our machines recently updated to 1010.5.0. With the latest docker 1.10 updates a random assortment of our docker images failed to download when new nodes spin up in AWS (it's different on each node). All fail, eventually, with an error of this form:

```
342a5ee7819c: Extracting [==================================================>] 39.76 MB/39.76 MB
8c8440083872: Download complete
371a799007df: Download complete
dacfdb8c32ca: Download complete
4afdb48db02e: Download complete
b3a71ac633ec: Download complete
4155f8fcaa44: Download complete
c3119bd099ea: Download complete
6348821dfd93: Download complete
3554eb0d49c9: Download complete
d1b20131d358: Download complete
e358afc9da43: Download complete
cc237c9eb9ba: Download complete
failed to register layer: lstat /var/lib/docker/overlay/d634beec75db64004deb5878e6234311d42edc0a4a19199b300ae4c4c9e2e989: no such file or directory
```

We've tried performing the [1.10 migration](https://docs.docker.com/engine/migration/) but that doesn't really work since the images simply don't exist locally due to this error. We've also tried rebuilding our images using a docker 1.10 daemon/client, pushed, and that doesn't work either.
This occurs for both instances that have self-updated to 1010.5.0 and new nodes that spin up with the latest AMI.

Overall, this is causing all of our automations to fail. Even some of our deployments.

We're currently turning off updates for our clusters, locking them to an AMI that's known to have docker 1.9.1 (I believe that's version ~899).

@philips was kind enough to provide me with a glimpse into what you guys are trying to do with the docker daemon itself ([gist here](https://gist.github.com/philips/4ba6f9888499266b0ab09d95991e6784)). However this does not provide us any anything in terms of a solution that would allow us to use auto-updates again. We might as well just revert to CentOS & baking AMIs again (obviously, I don't want to do that but still...).

What would be nice is a list of steps to fix, or to revert...something. Anything in terms of a temporary solution and a migration strategy for future breaking releases of docker.

**Comment by crawford** [comment]
@chr0n1x I have not been able to reproduce this one yet. Out of curiosity, can you try using the btrfs graph driver for Docker? We have some docs detailing how to [create a btrfs volume file](https://coreos.com/os/docs/latest/mounting-storage.html#creating-and-mounting-a-btrfs-volume-file).

**Comment by chr0n1x** [comment]
@crawford will give that a shot and let you know EOD or early tomorrow. Thanks for the reply.

**Comment by crawford** [comment]
I'm able to reliably trigger a related failure when pushing an image.

```
b42617c7cd55: Pushing [==================================================>] 524.3 kB/524.3 kB
f97188336049: Waiting 
78ffa471a4bb: Waiting 
7774b52ef817: Waiting 
stat /var/lib/docker/overlay/3e2add716a5a316a98a3b0ace814e66af37d8b81c4e08d7d4c7b05f57d3a7f51: no such file or directory
```

I created [this Dockerfile](https://gist.githubusercontent.com/crawford/94831d70b7b6251cbc0adfdbb6476616/raw/f3acfe0af14a3cfe6391ec4130d0dcd5bc784f85/Dockerfile) to stress the engine (turns out, 125 layers is the maximum allowed). The junk file added to the image comes from `dd if=/dev/urandom of=junk count=1024`. Once it's built, a push (`docker push quay.io/crawford/layers`) triggers the failure.

As I wrote this up, I started seeing another failure:

```
docker build .
Sending build context to Docker daemon 527.9 kB
Step 1 : FROM scratch
 ---> 
Step 2 : ADD junk 1
 ---> e6cead252f93
Removing intermediate container e59d239643b2
Step 3 : ADD junk 2
lstat /var/lib/docker/overlay/9df9b1507a90ab9ff9c99d74c1ee53f365a1a55a1590eaf1d79f5aa163d5786c: no such file or directory
```

I should also note that on this test machine, I removed all of the directories under `/var/lib/docker/overlay` while an image was downloading. Of course, this upset Docker but I removed all of the containers and images after that and before these latest tests.

**Comment by crawford** [comment]
Hmm, it looks like my destructive rampage through `/var/lib/docker/overlay` triggered these failures. I cleaned everything up again and am no longer able to repro. Back to the drawing board.

**Comment by crawford** [comment]
@chr0n1x can you provide us some more detail about your setup? AMI, region, instance type, container url, registry, etc.

**Comment by chr0n1x** [comment]
@crawford I believe that we used `	ami-32a85152` (us-west-2), `c4.2xlarge` and private docker hub images.

A bunch of our docker images are based off of [our rails image](https://hub.docker.com/r/behance/rails/), not sure if that helps at all. A few others are based on our [golang image](https://hub.docker.com/r/behance/docker-golang/)

**Comment by kbrwn** [comment]
reported as no longer a problem.
