### ISSUE TITLE
failure to start docker after upgrade to 1010.5.0

### ISSUE THREAD

**Issue by martingartonft** [coreos/bugs#1313]
After upgrade to 1010.5.0 docker fails to start with a message:

level=fatal msg="Error starting daemon: layer does not exist"

It looks like it's probably this:
https://github.com/docker/docker/issues/22591

**Comment by martingartonft** [comment]
workaround: sudo rm -rf /var/lib/docker

Perhaps something changed about the expected on disk format between docker versions?

**Comment by crawford** [comment]
This might be due to a failed migration (Docker changed its on-disk format between 1.9 and 1.10). I've heard of failures in the wild, but was never able to track down any concrete examples. Given that this migration is a one-time deal, I think you are all set. Sorry for the trouble.

**Comment by xhallix** [comment]
@martingartonft thanks a lot , this fixed it finally

**Comment by crawford** [comment]
Since this is a one-time upstream issue, I'm going to close this. @martingartonft's suggestion seems to be the best solution. I'm not particularly happy with this, but I don't have any better ideas.

**Comment by g13013** [comment]
`sudo rm -rf /var/lib/docker` warning: destructive operation that will remove all your images and containers
