### ISSUE TITLE
Vagrant os_variant

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1317]
<a href="https://api.github.com/users/benhosmer"><img src="https://avatars.githubusercontent.com/u/625195?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [benhosmer](https://api.github.com/users/benhosmer)**

---

After the first `vagrant up`:

```
Vagrant attempted to execute the capability 'os_variant'
on the detect guest OS 'coreos', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

Then after `vagrant reload --provision` the the box completes without any errors.

Vagrant Version: Vagrant 1.8.1
Using the Virtualbox provider.

**Comment by benhosmer** [comment]
Just to add to this, it likely is an issue with a plugin I am using. (vagrant-service-manager) so this may not be an issue related to coreos.

**Comment by AlexNPavel** [comment]
We don't use or support any guest capabilities called 'os_variant'. It is likely an issue with your plugin, so I will be closing this issue.
