### ISSUE TITLE
558: Terminal entry not found in terminfo "cygwin"

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1322]
<a href="https://api.github.com/users/marcofranssen"><img src="https://avatars.githubusercontent.com/u/694733?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [marcofranssen](https://api.github.com/users/marcofranssen)**

---

When using `vim` on the VM I get following message. Vim also behaves in a very weird way. Is there a possibility to add cygwin in the VM.

```
558: Terminal entry not found in terminfo 
cygwin' not known. Available builtin terminals are:
 builtin_ansi 
 builtin_xterm 
 builtin_iris-ansi 
 builtin_dumb 
```

**Comment by fpahl** [comment]
I have the same problem when I make a ssh connection from a windows machine. It is almost not possible to use `vim` to edit a file.

**Comment by PieterScheffers** [comment]
I have the same problem. I am currently experimenting with [this solution](https://alankent.me/2014/08/18/cygwin-term-type-and-ssh-ing-to-linux-quick-note/).

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
