### ISSUE TITLE
Start container with -v /var/nginx:/etc/nginx failed 

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1326]
<a href="https://api.github.com/users/luk911"><img src="https://avatars.githubusercontent.com/u/1578035?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [luk911](https://api.github.com/users/luk911)**

---

I use 
CoreOs stable and official nginx image and try start container with this option:

docker run --name nginx_1 -v /var/nginx/conf:/etc/nginx:ro -p 80:80 -d nginx

I found this https://github.com/docker/docker/issues/5489
and this https://github.com/docker/docker/pull/5910

but don't understand how to.

**Comment by llarsson** [comment]
This happens to me too on CoreOS 899.15.0. 

Simply running: `docker run -it -v /home/core/test:/test ubuntu:latest` followed by `echo "strange" > /test/result` inside the container should give me a file in `/home/core/test`, but it doesn't. The directory is empty.

**Comment by llarsson** [comment]
Upgrading to latest stable version, 1010.5.0, helped me work around the issue.

**Comment by euank** [comment]
This issue doesn't have enough information to be actionable. Optimistically I'll hope that this is fixed. If not, open a new issue.
