### ISSUE TITLE
No flannel daemon with the corers-vagrant

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1333]
<a href="https://api.github.com/users/huikang"><img src="https://avatars.githubusercontent.com/u/463631?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [huikang](https://api.github.com/users/huikang)**

---

Hi,
I am using this coreos-vagrant file to boot up 3 coreos nodes. I tried following the instructions at this link

https://coreos.com/docs/cluster-management/setup/flannel-config/

to run flannel daemon in the coreos host. However, it seems there is not flannel service available. Is there anything wrong? Thanks.
- Hui

**Comment by AlexNPavel** [comment]
Flanneld currently works if using the provided Ignition file for the VirtualBox provider or the user-data file for the VMWare provider.
