### ISSUE TITLE
etcd failed to start

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1335]
<a href="https://api.github.com/users/shayts7"><img src="https://avatars.githubusercontent.com/u/3765399?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [shayts7](https://api.github.com/users/shayts7)**

---

Hi All,

I'm working on Windows machine. I've installed Vagrant, used the default user-data and config.rb and run vagrant up.
I've logged into the machine and noticed that etcd failed to start.
Here is the error message from "journalctl -f":

Jun 10 11:12:40 core-01 systemd[1]: etcd2.service holdoff time over, scheduling restart.
Jun 10 11:12:40 core-01 systemd[1]: Started etcd2.
Jun 10 11:12:40 core-01 systemd[1]: Starting etcd2...
Jun 10 11:12:40 core-01 systemd[1]: Starting Network fabric for containers...
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: listening for peers on http://172.17.8.101:2380
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: listening for peers on http://172.17.8.101:7001
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: listening for client requests on http://0.0.0.0:2379
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: listening for client requests on http://0.0.0.0:4001
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcdserver: datadir is valid for the 2.0.1 format
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: stopping listening for client requests on http://0.0.0.0:4001
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: stopping listening for client requests on http://0.0.0.0:2379
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: stopping listening for peers on http://172.17.8.101:7001
Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: stopping listening for peers on http://172.17.8.101:2380
**Jun 10 11:12:40 core-01 etcd2[3150]: 2015/06/10 11:12:40 etcd: 13c808a7c74c4d71a83b299a72c04386 has different advertised URLs in the cluster and advertised peer URLs list**
Jun 10 11:12:40 core-01 systemd[1]: etcd2.service: main process exited, code=exited, status=1/FAILURE
Jun 10 11:12:40 core-01 systemd[1]: Unit etcd2.service entered failed state.
Jun 10 11:12:40 core-01 systemd[1]: etcd2.service failed.
Jun 10 11:12:40 core-01 etcdctl[3164]: Error: cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379

Any advise will be appreciated.

Thanks!
Shay

**Comment by AlexNPavel** [comment]
We now use Ignition with the VirtualBox provider and etcd-member for etcd3 support. As this is quite old and inactive, and the setup has changed a lot, I will close this for now. Feel free to repoen this issue or create a new one if this is still an issue.
