### ISSUE TITLE
fleetctl list-machines shows node at 127.0.0.1

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1338]
<a href="https://api.github.com/users/starkovv"><img src="https://avatars.githubusercontent.com/u/654646?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [starkovv](https://api.github.com/users/starkovv)**

---

```
$ fleetctl list-machines
MACHINE     IP      METADATA
384fe667... 172.17.8.102    secure_registry_docker_image_available=true
976365a1... 127.0.0.1   secure_registry_docker_image_available=true
```

Is it normal?

**Comment by AlexNPavel** [comment]
Fleet is deprecated and will soon be unsupported. Please migrate to kubernetes or tectonic for clustering
