### ISSUE TITLE
client and server don't have same version

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1340]
<a href="https://api.github.com/users/JoyceBabu"><img src="https://avatars.githubusercontent.com/u/502942?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [JoyceBabu](https://api.github.com/users/JoyceBabu)**

---

I have installed launched a Virtualbox VM using vagrant running coreos. But when I try to connect to docker, I am getting the following error

FATA[0000] Error response from daemon: client and server don't have same version (client : 1.18, server: 1.17) 

Host is having Docker client 1.6 and CoreOS is running 1.5. I have tried alpha and stable channels and both installed 1.5. How can I upgrade docker to 1.6 in CoreOS?

**Comment by bgilbert** [comment]
If I'm understanding the issue correctly, there doesn't appear to be anything here that we can fix.  Closing.
