### ISSUE TITLE
Is it possible to edit .bashrc or otherwise add an alias?

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1342]
<a href="https://api.github.com/users/alberto56"><img src="https://avatars.githubusercontent.com/u/808265?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [alberto56](https://api.github.com/users/alberto56)**

----

Hi,

in the vagrant box, we have ~/.bashrc as a symlink to /usr/share/skel/.bashrc, which contains

 ...
 # Put your fun stuff here.
 ...

I'd like to add an alias there, but I can't modify it:

 core@core-01 ~ $ echo "alias a=b" >> ~/.bashrc
 -bash: /home/core/.bashrc: Read-only file system
 core@core-01 ~ $ sudo echo "alias a=b" >> ~/.bashrc
 -bash: /home/core/.bashrc: Read-only file system
 core@core-01 ~ $ sudo su
 core-01 core # sudo echo "alias a=b" >> /home/core/.bashrc
 bash: /home/core/.bashrc: Read-only file system
 core-01 core # ls -lah /home/core | grep .bashrc
 lrwxrwxrwx 1 core core 28 Feb 14 05:27 .bashrc -> ../../usr/share/skel/.bashrc
 core-01 core # sudo echo "alias a=b" >> /usr/share/skel/.bashrc
 bash: /usr/share/skel/.bashrc: Read-only file system

Is there a prescribed way to modify .bashrc or otherwise add, say, a $PATH or alias? If so, how? Sub-question: what is "skel"?

Thanks!

**Comment by scls19fr** [comment]
Not being able to seamlessly add aliases to CoreOS is a real pain!
I followed this solution http://stackoverflow.com/questions/30596866/how-can-i-customize-bashrc-bash-profile-or-profile-on-a-coreos-installation but I'm not sure if removing symlink is a great idea.

**Comment by crawford** [comment]
Replacing the symlink with a copy of the file is the correct approach. CoreOS won't touch that file on updates and it will let you make arbitrary modifications.
