### ISSUE TITLE
Slow private network

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1343]
<a href="https://api.github.com/users/mlazarov"><img src="https://avatars.githubusercontent.com/u/976139?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [mlazarov](https://api.github.com/users/mlazarov)**

---

Currently I'm trying latest version of coreos-vagrant with almost default settings. The only non default values:
config.rb file:

```
$num_instances=3
```

Vagrant file:

```
ip = "10.0.69.#{i+30}"
```

And after `vagrant up` here is what I'm getting when trying to ping the private network

ping from core-01 to core-02

```
core@core-01 ~ $ ping 10.0.69.32
PING 172.17.8.102 (172.17.8.102) 56(84) bytes of data.
64 bytes from 10.0.69.32: icmp_seq=1 ttl=64 time=8.47 ms
64 bytes from 10.0.69.32: icmp_seq=2 ttl=64 time=6.73 ms
64 bytes from 10.0.69.32 icmp_seq=3 ttl=64 time=2.27 ms
64 bytes from 10.0.69.32: icmp_seq=4 ttl=64 time=10.6 ms
64 bytes from 10.0.69.32: icmp_seq=5 ttl=64 time=11.5 ms
64 bytes from 10.0.69.32: icmp_seq=6 ttl=64 time=11.4 ms
64 bytes from 10.0.69.32: icmp_seq=7 ttl=64 time=8.15 ms
64 bytes from 10.0.69.32: icmp_seq=8 ttl=64 time=6.52 ms
```

I'm experiencing slow private network only under coreos instances. For example the same default private network between two vagrant centos 7 instances:

```
[root@lb-1 vagrant]# ping 10.0.69.3
PING 10.0.69.3 (10.0.69.3) 56(84) bytes of data.
64 bytes from 10.0.69.3: icmp_seq=1 ttl=64 time=0.389 ms
64 bytes from 10.0.69.3: icmp_seq=2 ttl=64 time=0.587 ms
64 bytes from 10.0.69.3: icmp_seq=3 ttl=64 time=0.678 ms
64 bytes from 10.0.69.3: icmp_seq=4 ttl=64 time=0.505 ms
64 bytes from 10.0.69.3: icmp_seq=5 ttl=64 time=0.563 ms
```

End here is the output from ping between one of the centos vagrant instances to core-01:

```
[root@lb-1 vagrant]# ping 10.0.69.31
PING 10.0.69.31 (10.0.69.31) 56(84) bytes of data.
64 bytes from 10.0.69.31: icmp_seq=1 ttl=64 time=5.99 ms
64 bytes from 10.0.69.31: icmp_seq=2 ttl=64 time=4.82 ms
64 bytes from 10.0.69.31: icmp_seq=3 ttl=64 time=162 ms
64 bytes from 10.0.69.31: icmp_seq=4 ttl=64 time=2.08 ms
64 bytes from 10.0.69.31: icmp_seq=5 ttl=64 time=9.50 ms
64 bytes from 10.0.69.31: icmp_seq=6 ttl=64 time=7.16 ms
64 bytes from 10.0.69.31: icmp_seq=7 ttl=64 time=156 ms
64 bytes from 10.0.69.31: icmp_seq=8 ttl=64 time=5.90 ms
64 bytes from 10.0.69.31: icmp_seq=9 ttl=64 time=3.39 ms
64 bytes from 10.0.69.31: icmp_seq=10 ttl=64 time=2.63 ms
64 bytes from 10.0.69.31: icmp_seq=11 ttl=64 time=96.9 ms
64 bytes from 10.0.69.31: icmp_seq=12 ttl=64 time=150 ms
64 bytes from 10.0.69.31: icmp_seq=13 ttl=64 time=8.86 ms
64 bytes from 10.0.69.31: icmp_seq=14 ttl=64 time=148 ms
64 bytes from 10.0.69.31: icmp_seq=15 ttl=64 time=7.07 ms
```

All the servers are empty (i.e. no docker instances under coreos or running process under centos).

The above experience i'm getting on the separate servers both with:
CentOS release 6.6 (Final)
Vagrant version: 1.7.2
CoreOS 633.1.0 (but also same issue with previews alfa version)

How I can speed up the private network?

**Comment by AlexNPavel** [comment]
I have done some benchmarking and found ping times of <1ms and speedtest-cli run from a docker container maxes out my internet connection (around 90Mbit/s in both directions). I will assume this has been fixed by newer versions of VirtualBox that have been released since this issue was originally created. If you are still having this issue, please feel free to reopen this issue or open a new issue.
