### ISSUE TITLE
SSL_CONNECT error during vagrant up

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1344]
<a href="https://api.github.com/users/sivaramsk"><img src="https://avatars.githubusercontent.com/u/310397?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [sivaramsk](https://api.github.com/users/sivaramsk)**

---

I tried to bring up the latest coreos-vagrant and have this error. How do I make it work?

$ vagrant up
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: C:/Users/v673525/Documents/Code/TestCode/coreos-vagrant/Vagrantfile
Message: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

**Comment by AlexNPavel** [comment]
I believe older versions of vagrant and older versions of our images needed some ssl libraries to do anything, but that isn't the case anymore. This means that this issue also shouldn't occur anymore. If you are still experiencing this issue, please reopen this issue or create a new one.
