### ISSUE TITLE
DNS resolution is not working on 607.0.0 in vagrant

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1345]
<a href="https://api.github.com/users/msumme"><img src="https://avatars.githubusercontent.com/u/462931?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [msumme](https://api.github.com/users/msumme)**

---

I had a box running 557.2.0, and ping works.

```
core@core-01 ~ $ ping google.com
PING google.com (216.58.216.206) 56(84) bytes of data.
64 bytes from 216.58.216.206: icmp_seq=1 ttl=55 time=19.4 ms
64 bytes from 216.58.216.206: icmp_seq=2 ttl=55 time=31.2 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 19.495/25.397/31.299/5.902 ms
```

When I upgrade to 607, I get "bad address: google.com" (or something to that effect).

I'm wondering if this is related to a glibc bug that affected busybox-static ping in gentoo? 

https://sourceware.org/bugzilla/show_bug.cgi?id=17250 

I have a feeling that may be relevant, since glibc 2.19 is in use in 607.0.0. 

One other thing I've noticed is that when I ping 10.0.2.3 in 607.0.0, I get timeouts, whereas in 557.2.0 it works consistently.

Any ideas how I can resolve this? It's in the stable branch now.

**Comment by AlexNPavel** [comment]
I cannot reproduce this with the 1478.0.0 alpha and Vagrant 1.9.1. If you are still experiencing this issue, please open a new issue.
