### ISSUE TITLE
Issue - starting a coreos vagrant cluster inside a VM.

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1349]
<a href="https://api.github.com/users/alok87"><img src="https://avatars.githubusercontent.com/u/9006763?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [alok87](https://api.github.com/users/alok87)**

---

Hi,

I have a windows 7 laptop. I have installed a centos machine inside virtual box in my latop.
Inside Centos Virtual machine, i installed Vagrant, git and virtual box and tried to bring the coreos vagrant up. It is not coming up and throwing the below error. I have increasing the timeout but to no success.

==> core-01: Waiting for machine to boot. This may take a few minutes...
core-01: SSH address: 127.0.0.1:2222
core-01: SSH username: core
core-01: SSH auth method: private key
core-01: Warning: Connection timeout. Retrying...

Please suggest. What could be the issue in starting coreos vagrant cluster inside a VM?

**Comment by AlexNPavel** [comment]
You cannot run a VM within a VM with proper acceleration support. If running a vagrant image or cluster, please run it on bare-metal. Vagrant and VirtualBox are fully support on Windows, Mac, and Linux, and so is our Vagrantfile and plugin.
