### ISSUE TITLE
Failed connect to stable.release.core-os.net:443; No error

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1353]
<a href="https://api.github.com/users/gindasoo"><img src="https://avatars.githubusercontent.com/u/6828681?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [gindasoo](https://api.github.com/users/gindasoo)**

---

D:\coreos-vagrant>vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Box 'coreos-stable' could not be found. Attempting to find and inst
all...
core-01: Box Provider: virtualbox
core-01: Box Version: >= 0
==> core-01: Adding box 'coreos-stable' (v0) for provider: virtualbox
core-01: Downloading: https://stable.release.core-os.net/amd64-usr/current/c
oreos_production_vagrant.json
core-01: Progress: 0% (Rate: 0curl:/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Failed connect to stable.release.core-os.net:443; No error

**Comment by euank** [comment]
At a guess, this was probably a network error.

Closing as stale.
