### ISSUE TITLE
Vmware provider is not using static ip with coreos guest.

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1354]
<a href="https://api.github.com/users/johnraz"><img src="https://avatars.githubusercontent.com/u/304164?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [johnraz](https://api.github.com/users/johnraz)**

---

Just cross linking here as I don't know which side is responsible of the issue:
mitchellh/vagrant#5006

**Comment by bgilbert** [comment]
This appears to be an issue with the provider which has since been fixed (https://github.com/mitchellh/vagrant/issues/5461).  Please reopen if not.
