### ISSUE TITLE
Shared Folder doesn't work on Windows 7

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1358]
<a href="https://api.github.com/users/flyisland"><img src="https://avatars.githubusercontent.com/u/547085?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [flyisland](https://api.github.com/users/flyisland)**

----

vagrant: 1.6.5, Windows 7 sp1

after added `config.vm.synced_folder "D:/DevProjects/docker", "/dockerfiles"`, the `vagrant up` shows

```
No synced folder implementation is available for your synced folders!
Please consult the documentation to learn why this may be the case.
You may force a synced folder implementation by specifying a "type:"
option for the synced folders. Available synced folder implementations
are listed below.
```

At the same time, my other vagrant boxes(like `centos-6.5-x86_64`) work fine with the same shared folder.

**Comment by omniscient** [comment]
I landed here and only thing that worked for me on windows 10 and Vagrant 1.8.6 is this plug-in: https://github.com/winnfsd/vagrant-winnfsd. I think this ticket can/should be closed...
