### ISSUE TITLE
vagrant up causes `no space left on device`

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1359]
<a href="https://api.github.com/users/sjackman"><img src="https://avatars.githubusercontent.com/u/291551?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [sjackman](https://api.github.com/users/sjackman)**

---

See also docker/docker#8804. I'm not sure whether this is primarily a Docker issue, a Vagrant issue, or a Vagrant CoreOS issue. Please reassign this issue as necessary.

Running `vagrant up` on coreos-vagrant causes the error `scp: /var/tmp/hostname.yml: No space left on device (RuntimeError)`. See below for details. The volumes do not appear full.

```
sh-4.2# df
Filesystem 1K-blocks Used Available Use% Mounted on
rootfs 16793600 12362164 3910668 76% /
devtmpfs 2014476 0 2014476 0% /dev
tmpfs 2026352 0 2026352 0% /dev/shm
tmpfs 2026352 236 2026116 1% /run
tmpfs 2026352 0 2026352 0% /sys/fs/cgroup
/dev/sda9 16793600 12362164 3910668 76% /
/dev/sda3 1032088 294556 685104 31% /usr
tmpfs 2026352 0 2026352 0% /media
tmpfs 2026352 0 2026352 0% /tmp
/dev/sda6 110576 88 101316 1% /usr/share/oem
/dev/sda9 16793600 12362164 3910668 76% /var/lib/docker/btrfs
```

**Comment by AlexNPavel** [comment]
This issue was most likely the btrfs 'no space' bug, and some of the other people mentioned that other various apps (like mongo) were eating up a lot of space. Closing the issue for now. If you are still experiencing this problem, please open a new issue
