### ISSUE TITLE
Create Parallels Vagrant Box

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1361]
<a href="https://api.github.com/users/KellyLSB"><img src="https://avatars.githubusercontent.com/u/610328?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [KellyLSB](https://api.github.com/users/KellyLSB)**

---

If you would; please create a Parallels Vagrant Box.

**Comment by AlexNPavel** [comment]
This was added some time back
