### ISSUE TITLE
error: You specified a box version constraint with a direct box file path

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1365]
<a href="https://api.github.com/users/hustcat"><img src="https://avatars.githubusercontent.com/u/1716915?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [hustcat](https://api.github.com/users/hustcat)**

---

$ vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
Bringing machine 'core-02' up with 'virtualbox' provider...
Bringing machine 'core-03' up with 'virtualbox' provider...
==> core-01: Box 'coreos-beta' could not be found. Attempting to find and install...
 core-01: Box Provider: virtualbox
 core-01: Box Version: >= 308.0.1
You specified a box version constraint with a direct box file
path. Box version constraints only work with boxes from Vagrant
Cloud or a custom box host. Please remove the version constraint
and try again.

what's wrong?

**Comment by AlexNPavel** [comment]
This isn't an issue with modern versions of coreos-vagrant as version handling done differently now
