### ISSUE TITLE
CoreOS constantly prints kernel mesaage of docker container.

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1367]
<a href="https://api.github.com/users/liangsuilong"><img src="https://avatars.githubusercontent.com/u/152888?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [liangsuilong](https://api.github.com/users/liangsuilong)**

---

![coreos_print](https://cloud.githubusercontent.com/assets/152888/4042637/35e2d9cc-2d06-11e4-8211-94170b231436.png)

Some docker containers are set to boot automatically by me via systemd. When I boot CoreOS, tty console is constantly printing kernel message of docker containers. It is quite annoyed at me. I cannot get login dialog, and cannot get ethernet IP address and MAC address. If there is something wrong for docker container so that container automatically reboots via systemd, the kernel message on the screen will never stop. 

Could I disable kernel output on the tty0 screen? It is quite import for me. Is there any settings in CoreOS?

**Comment by UserTaken** [comment]
I've experience this problem with other distributions as well as the Raspberry Pi when using a serial cable. The solution was to append `loglevel=3` to the kernel parameter in order to suppress anything not an error or critical.

**Comment by AlexNPavel** [comment]
This does not seem to happen anymore, so I will close this. Please file a new issue if this is still a problem

**Comment by AlexNPavel** [comment]
Reopening because, while this doesn't seem to happen with vagrant-virtualbox, there are still some platforms that this occurs on.

**Comment by euank** [comment]
Those specific log messages are harmless and expected.

If you wish to not receive kernel logs on your serial console, you can reduce their level (via either the kernel cmdline `loglevel=` option, or via writing the value to `/proc/sys/kernel/printk` using a early systemd unit).

I don't think we should change this by default, but if it's important to you, either of those options should work. If they don't, please do reopen.
