### ISSUE TITLE
vmxnet3 instead of e1000

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1369]
<a href="https://api.github.com/users/c4milo"><img src="https://avatars.githubusercontent.com/u/41681?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [c4milo](https://api.github.com/users/c4milo)**

---

vmxnet3 seems to be a much faster driver, is there a reason to not use it? 

hardware version seems to be very low too, 4, current version is 10. A fair hw version could be 8.

**Comment by AlexNPavel** [comment]
We are currently using the defaults from vagrant and will stick with that for now.
