### ISSUE TITLE
Reboot causes docker.service to die

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1381]
<a href="https://api.github.com/users/emilbayes"><img src="https://avatars.githubusercontent.com/u/416524?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [emilbayes](https://api.github.com/users/emilbayes)**

---

Everytime I issue `vagrant reload` or `vagrant suspend` followed by `vagrant up` the `docker.service` fails.

I don't know the cause of this. I always manually restart the service: `sudo systemctl restart docker.service`

**Comment by AlexNPavel** [comment]
Cannot reproduce and this issue is more than 2 years old without any updates. Closing
