### ISSUE TITLE
smb/cifs tools?

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1384]
<a href="https://api.github.com/users/hurrycaner"><img src="https://avatars.githubusercontent.com/u/2671143?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [hurrycaner](https://api.github.com/users/hurrycaner)**

---

As a windows user, i'm being forced to use another box because coreos don't support mount.cifs as windows don't support nfs...
I would build it by my own, but i don't even know how to start :(
I don't even know where to start... (i'm probably posting this on the wrong repo, right?)

**Comment by bgilbert** [comment]
Duplicate of #571.
