### ISSUE TITLE
docker build reboots machine on vagrant with btrfs backend

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1385]
<a href="https://api.github.com/users/philips"><img src="https://avatars.githubusercontent.com/u/33544?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [philips](https://api.github.com/users/philips)**

---

Unable to reproduce this issue on ec2 or kvm.

```
git clone https://github.com/dotcloud/docker.git
cd docker && git checkout v0.9.1
docker build -t docker .
```

At some point the machine simply reboots. The first step is to get a serial console that I can use from vagrant.

/cc @gabrtv

**Comment by AlexNPavel** [comment]
This does not seem to be an issue anymore. Closing
