### ISSUE TITLE
serial-getty@ttyS0 constantly failing

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1386]
<a href="https://api.github.com/users/shawnjgoff"><img src="https://avatars.githubusercontent.com/u/582656?v=3" align="left" width="96" height="96" hspace="10"></img></a>
**Issue by [shawnjgoff](https://api.github.com/users/shawnjgoff)**

---

The serial-getty@ttyS0 (wanted by the getty.target) is constantly spawning and failing, filling up the journal with the following:

```
Feb 27 19:25:26 localhost systemd[1]: serial-getty@ttyS0.service holdoff time over, scheduling restart.
Feb 27 19:25:26 localhost systemd[1]: Stopping Serial Getty on ttyS0...
Feb 27 19:25:26 localhost systemd[1]: Starting Serial Getty on ttyS0...
Feb 27 19:25:26 localhost systemd[1]: Started Serial Getty on ttyS0.
Feb 27 19:25:26 localhost agetty[3130]: /dev/ttyS0: not a character device
```

**Comment by AlexNPavel** [comment]
This is not valid anymore
