### ISSUE TITLE
Ignition timeout of fetching http files

### ISSUE THREAD

**Issue by SchwarzM** [coreos/bugs#1390]
Hi,

the default timeout for fetching http resources is quite ambitious when downloading medium to large go binaries.
https://github.com/coreos/ignition/blob/d5e21763171a55a0c687016ef3062197c9349cc0/internal/util/http.go#L38
I run into the timeout fetching kubernetes binaries. Is there a way around it?

Kind regards
M. Schwarz

**Comment by crawford** [comment]
There is no workaround for this issue, but it is something I am aware of. I've been thinking about increasing the default and then allowing the user to specify a timeout in the Ignition config.

**Comment by ajeddeloh** [comment]
This is being worked on here: https://github.com/coreos/ignition/pull/248.

**Comment by ajeddeloh** [comment]
closed via https://github.com/coreos/ignition/pull/248.
