### ISSUE TITLE
Hardware Interrupts on KVM when CPU is being capped (steal)

### ISSUE THREAD

**Issue by mberner-ch** [coreos/bugs#1391]
## Problem Description

We observe the following problem: 
Whenever the CPU time of the virualized server gets capped (top shows %steal, expected), we observe the same amount of CPU time being spent in hardware interrupts (%hi, not expected) in addition to the steal time.
This results in the bad situation that the servers have less CPU available when they become more loaded.
There are no hardware interrupts when the CPU is idle or not capped (not running into %steal).
## Context

We are running CoreOS (alpha) at a cloud hosting provider (CloudSigma), which uses KVM on Intel hardware for virtualization. 
CloudSigma uses the model that you do not subscribe to a CPU, but instead to a number of GHz. So you can subscribe to 1 GHz which will result on a corresponding CPU share on a 2.6 GHz CPU with 3.3 GHz Turbo Boost.

Examples:
- 2.5 GHz CPU(s) on full load: 25% steal, 25% hardware interrupts => 50% user+system
- 2 GHz CPU(s) on full load: 40% steal, 40% hardware interrupts => 20% user+system
- 1 GHz CPU(s) on full load: 60% steal, 40% hardware interrupts => 0% user + system => system locks up

Example Test: 2 x 2.6GHz:

```
core@GgTest ~ $ top | grep Cpu
%Cpu(s):  7.8 us,  3.5 sy,  0.0 ni, 86.1 id,  0.3 wa,  1.3 hi,  0.7 si,  0.3 st
%Cpu(s): 10.9 us,  3.4 sy,  0.0 ni, 83.5 id,  0.0 wa,  1.2 hi,  0.7 si,  0.3 st
%Cpu(s):  6.3 us,  2.5 sy,  0.0 ni, 89.3 id,  0.0 wa,  1.2 hi,  0.7 si,  0.0 st
%Cpu(s):  8.5 us,  7.3 sy,  0.0 ni, 81.3 id,  0.2 wa,  1.2 hi,  0.7 si,  0.8 st
%Cpu(s):  7.7 us,  2.8 sy,  0.0 ni, 87.4 id,  0.0 wa,  1.2 hi,  0.8 si,  0.0 st
%Cpu(s):  6.6 us,  2.7 sy,  0.0 ni, 89.0 id,  0.2 wa,  1.0 hi,  0.3 si,  0.2 st
%Cpu(s):  6.7 us,  2.7 sy,  0.0 ni, 88.9 id,  0.0 wa,  1.0 hi,  0.7 si,  0.0 st
core@GgTest ~ $ for i in 1 2; do cat /dev/zero | sha512sum > /dev/null & done
core@GgTest ~ $ top | grep Cpu
%Cpu(s):  7.7 us,  3.5 sy,  0.0 ni, 86.2 id,  0.3 wa,  1.3 hi,  0.7 si,  0.3 st
%Cpu(s): 50.6 us,  6.2 sy,  0.0 ni,  0.0 id,  0.0 wa, 21.5 hi,  0.5 si, 21.3 st
%Cpu(s): 49.8 us,  6.5 sy,  0.0 ni,  0.0 id,  0.0 wa, 22.0 hi,  0.7 si, 21.1 st
%Cpu(s): 50.1 us,  6.3 sy,  0.0 ni,  0.0 id,  0.0 wa, 21.8 hi,  0.5 si, 21.3 st
%Cpu(s): 50.6 us,  6.0 sy,  0.0 ni,  0.0 id,  0.0 wa, 21.7 hi,  0.5 si, 21.2 st
%Cpu(s): 49.1 us,  7.0 sy,  0.0 ni,  0.0 id,  0.0 wa, 22.1 hi,  0.7 si, 21.2 st
%Cpu(s): 50.3 us,  6.0 sy,  0.0 ni,  0.0 id,  0.0 wa, 22.0 hi,  0.5 si, 21.2 st
%Cpu(s): 50.1 us,  6.2 sy,  0.0 ni,  0.0 id,  0.0 wa, 22.0 hi,  0.5 si, 21.3 st
%Cpu(s): 50.3 us,  6.1 sy,  0.0 ni,  0.0 id,  0.0 wa, 21.8 hi,  0.7 si, 21.1 st
%Cpu(s): 47.1 us,  9.4 sy,  0.0 ni,  0.0 id,  0.0 wa, 21.8 hi,  0.5 si, 21.1 st
%Cpu(s): 49.8 us,  6.7 sy,  0.0 ni,  0.0 id,  0.0 wa, 22.0 hi,  0.5 si, 21.1 st
```

=> No hardware interrupts when the system is idle
=> Hardware interrupts proportional to steal time when the CPU is loaded

The 21% steal (and additional 21% hardware interrupts) come from the fact that the CPUs go into Turbo Boost mode (2.6GHz / 3.3GHz = 79%)
## Preliminary conclusions from experiments
- The problem is independent of Kernel (occurs with 3.18.6 as well as 4.6.0) and CoreOS version (alpha, stable)
- The problem is independent of KVM virtio drivers (occurs also with Intel NIC & IDE exposed directly)
- The problem is independent of exposing Host CPU (Intel) or virtualized CPU (KVM). We also tried switching between Multi-Core and Multi-CPU settings as well as NUMA.
- The problem seems to be triggered by some property of CoreOS as other distributions do not exhibit the same behavior (Debian 8.4, Ubuntu Server, CentOS, RancherOS)

CloudSigma says that it is a fundamental incompatibility between their Intel hosts and CoreOS, as it does not occur on their AMD hosts in other data centers.
## Additional information

```
core@GgTest ~ $ cat /proc/interrupts 
           CPU0       CPU1       
  0:         44          0   IO-APIC   2-edge      timer
  1:          9          0   IO-APIC   1-edge      i8042
  3:         16          0   IO-APIC   3-edge    
  4:     309478          0   IO-APIC   4-edge      serial
  8:          1          0   IO-APIC   8-edge      rtc0
  9:          0          0   IO-APIC   9-fasteoi   acpi
 10:          0          0   IO-APIC  10-fasteoi   virtio4
 11:         34          0   IO-APIC  11-fasteoi   uhci_hcd:usb1
 12:         96          0   IO-APIC  12-edge      i8042
 14:          0          0   IO-APIC  14-edge      ata_piix
 15:          0          0   IO-APIC  15-edge      ata_piix
 24:          0          0   PCI-MSI 49152-edge      virtio0-config
 25:  178832572          0   PCI-MSI 49153-edge      virtio0-input.0
 26:       1469          0   PCI-MSI 49154-edge      virtio0-output.0
 27:          0          0   PCI-MSI 81920-edge      virtio2-config
 28:     676571          0   PCI-MSI 81921-edge      virtio2-req.0
 29:          0          0   PCI-MSI 65536-edge      virtio1-config
 30:     131419          0   PCI-MSI 65537-edge      virtio1-input.0
 31:          2          0   PCI-MSI 65538-edge      virtio1-output.0
 32:          0          0   PCI-MSI 98304-edge      virtio3-config
 33:    5240600          0   PCI-MSI 98305-edge      virtio3-req.0
NMI:          0          0   Non-maskable interrupts
LOC: 1068117346  989729124   Local timer interrupts
SPU:          0          0   Spurious interrupts
PMI:          0          0   Performance monitoring interrupts
IWI:         72         68   IRQ work interrupts
RTR:          0          0   APIC ICR read retries
RES:  276209755  314337783   Rescheduling interrupts
CAL:      11822      11451   Function call interrupts
TLB:   11367169   11643696   TLB shootdowns
TRM:          0          0   Thermal event interrupts
THR:          0          0   Threshold APIC interrupts
DFR:          0          0   Deferred Error APIC interrupts
MCE:          0          0   Machine check exceptions
MCP:       1949       1949   Machine check polls
ERR:          0
MIS:          0
PIN:          0          0   Posted-interrupt notification event
PIW:          0          0   Posted-interrupt wakeup event
```

Kernel:

```
core@GgTest ~ $ uname -a
Linux GgTest 4.6.0-coreos #2 SMP Fri May 20 01:46:43 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz GenuineIntel GNU/Linux
```

CPU:

```
core@GgTest ~ $ cat /proc/cpuinfo 
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
stepping    : 7
microcode   : 0x1
cpu MHz     : 2593.748
cache size  : 20480 KB
physical id : 0
siblings    : 2
core id     : 0
cpu cores   : 2
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm vnmi ept tsc_adjust xsaveopt
bugs        :
bogomips    : 5187.49
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

Boot output:
[dmesg.txt](https://github.com/coreos/bugs/files/302890/dmesg.txt)
## Request for Help

We are thankful for any hint which would allow us to get to the bottom of this:
- Does anyone know what could be the striking difference between CoreOS and other OSes which do not exhibit that behavior? The only idea I have is that it seems to use CONFIG_HZ=1000 tick rate.
- Is anyone aware about any incompatibilities of CoreOS with KVM on Intel hardware?
- What else can we try? What additional information do you need?

The only other alternatives I see at the moment is to either switch OS (Rancher?) or cloud provider.

**Comment by mjg59** [comment]
I can't immediately reproduce this locally. Are you able to try this:

echo l >/proc/sysrq-trigger

while the system is in this state? Try doing this a few times and attach all the kernel output.

**Comment by mberner-ch** [comment]
Thank you a lot for your reply! This is much appreciated!

Started up a 10-core VM with 16 GHz total => 1.6 GHz per core. Then made all cores busy with calculating (see below):
```
core@hwirq-test ~ $ for i in 1 2 3 4 5 6 7 8 9 10; do cat /dev/zero | sha512sum > /dev/null & done
core@hwirq-test ~ $ top

top - 05:27:41 up 4 min,  1 user,  load average: 0.80, 0.22, 0.07
Tasks: 160 total,  13 running, 147 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.9 us,  0.4 sy,  0.0 ni, 10.2 id,  0.0 wa, 44.8 hi,  0.0 si, 43.6 st
KiB Mem:   1020968 total,   138928 used,   882040 free,     4296 buffers
KiB Swap:        0 total,        0 used,        0 free.    54024 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                  
  709 core      20   0    4356    752    672 R   2.7  0.1   0:00.31 sha512sum                                                                                                                                
  692 core      20   0    4320    784    708 S   2.3  0.1   0:00.17 cat                                                                                                                                      
  704 core      20   0    4320    772    696 S   2.3  0.1   0:00.40 cat                                                                                                                                      
  705 core      20   0    4356    676    600 R   2.0  0.1   0:00.44 sha512sum                                                                                                                                
  701 core      20   0    4356    752    672 R   1.7  0.1   0:00.27 sha512sum                                                                                                                                
  695 core      20   0    4356    788    708 R   1.3  0.1   0:00.21 sha512sum                                                                                                                                
  699 core      20   0    4356    748    668 R   1.3  0.1   0:00.14 sha512sum                                                                                                                                
  676 core      20   0    4356    680    604 R   1.0  0.1   0:05.19 sha512sum                                                                                                                                
  694 core      20   0    4320    680    600 S   0.7  0.1   0:00.09 cat                                                                                                                                      
  702 core      20   0    4320    696    616 S   0.7  0.1   0:00.13 cat                                                                                                                                      
  703 core      20   0    4356    752    672 R   0.7  0.1   0:00.09 sha512sum                                                                                                                                
  707 core      20   0    4356    800    720 R   0.7  0.1   0:00.12 sha512sum                                                                                                                                
  708 core      20   0    4320    796    716 S   0.7  0.1   0:00.15 cat                                                                                                                                      
  675 core      20   0    4320    768    692 S   0.3  0.1   0:09.08 cat                                                                                                                                      
  690 core      20   0    4320    744    668 S   0.3  0.1   0:00.10 cat                                                                                                                                      
  696 core      20   0    4320    744    664 S   0.3  0.1   0:00.11 cat                                                                                                                                      
  698 core      20   0    4320    692    616 S   0.3  0.1   0:00.10 cat                                                                                                                                      
  700 core      20   0    4320    688    608 S   0.3  0.1   0:00.15 cat                                                                                                                                      
  706 core      20   0    4320    772    696 S   0.3  0.1   0:00.08 cat                                                                                                                                      
    1 root      20   0  175624   5072   3616 S   0.0  0.5   0:00.65 systemd                                                                                                                                  
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd           
```

The machine is noticeably slow at that moment as ~90% of the CPU is either stolen or in hwirq - top takes like 10 seconds to come up.
Then I did a few sysrq-trigger stack backtraces, as you asked:
`core@hwirq-test ~ $ sudo sh -c 'echo l > /dev/sysrq-trigger'`
Output of dmesg is attached. What might be an useful observation is that it did not always take the same time to execute the sysrq-trigger - sometimes 1-2 seconds, sometimes more like 8-10 seconds. I believe that the system is very slow at that point is also evident from the 'NMI handler took too long to run' warnings in the stacktraces.
Otherwise the system just seems to think it's doing sha512sums and shuffling around data to feed it.

As a bonus, I also dumped the hrtimer and task stats over sysrq - just in case it helps. 
```
core@hwirq-test ~ $ sudo sh -c 'echo q > /proc/sysrq-trigger'
core@hwirq-test ~ $ sudo sh -c 'echo t > /proc/sysrq-trigger'
```
The latter unfortunately did not fit fully in the print buffer.

Please tell me if I can supply you with more information in this matter.
[dmesg_sysrq-trigger_cpu-backtrace.txt](https://github.com/coreos/bugs/files/324880/dmesg_sysrq-trigger_cpu-backtrace.txt)
[dmesg_sysrq-trigger_hrtimers.txt](https://github.com/coreos/bugs/files/324881/dmesg_sysrq-trigger_hrtimers.txt)
[dmesg_sysrq-trigger_tasks.txt](https://github.com/coreos/bugs/files/324882/dmesg_sysrq-trigger_tasks.txt)

**Comment by mjg59** [comment]
Unfortunately that didn't give any good indications :( If you run

watch cat /proc/interrupts

while in this state, is one interrupt increasing more rapidly than any others?

**Comment by mberner-ch** [comment]
Yes, I was afraid so. Thank you anyway for having a look.

When watching /proc/interrupts it's the 2 interrupts with the highest counts which move very fast (~1000/s):
* Local timer interrupts
* Rescheduling interrupts
with TLB shootdowns coming in in 3rd place.

So pretty much corresponding to the numbers you see in the /proc/interrupts dump of my original post. I believe, at least rescheduling interrupts run faster under load (which makes sense to me) than idle.
I also did some experiments by changing the scheduling parameters to reduce re-scheduling and increase slice times and check times, but to no avail.

Is it normal to have such high Local timer interrupts? I thought that one of the differences of CoreOS to other distributions, which run fine, might be the tick/HZ configuration. But I don't really see through the kernel compile parameters: Is CoreOS tickless, idle-tickless and/or running at 1000 HZ tick rate? Is its setting there different from most major distributions?

**Comment by mjg59** [comment]
High timer interrupts usually imply that the scheduler is scheduling a lot of things in the near future. CONFIG_NO_HZ is set, as is CONFIG_HZ_1000. Let me figure out what the other NO_HZ settings are.

**Comment by mjg59** [comment]
We're using CONFIG_NO_HZ_IDLE rather than CONFIG_NO_HZ_FULL. I can't think of an immediate reason why this would cause a difference, but I'll try switching this.

**Comment by mjg59** [comment]
Although CONFIG_NO_HZ_FULL should be doing nothing unless there's a boot parameter passed - can you provide /proc/cmdline for an affected system?

**Comment by mberner-ch** [comment]
There doesn't seem to be anything out of the ordinary:
```
core@GgTest ~ $ cat /proc/cmdline 
rootflags=rw mount.usrflags=ro BOOT_IMAGE=/boot/vmlinuz console=ttyS0,115200n8 console=tty0 root=LABEL=ROOT mount.usr=PARTUUID=e03dd35c-7c2d-4a47-b3fe-27f15780a57c
```

**Comment by mjg59** [comment]
I've looked at this some more, but I'm afraid that I haven't made any progress. I can't see any way that CONFIG_NO_HZ_FULL can be relevant here, since it's only enabled if the kernel parameter is passed. In its absence, the kernel behaves identically to CONFIG_NO_HZ_IDLE. So as far as I can tell, the problem must be somewhere else.

**Comment by mberner-ch** [comment]
Thank you, Matthew! I appreciate your effort!
This whole thing is still quite a mystery for me. The only additional information I found in the mean time is that the same setup with another Intel CPU, Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz, and a newer QEMU/KVM version (CloudSigma location Frankfurt) has the same issue. We are still in contact with them over this problem.

If someone wants to reproduce the issue - CloudSigma provides 7 day free trial accounts. Just set up CoreOS on one of the affected locations (ZRH, FRA, ...) and create some load, e.g. with:
`cat /dev/zero | sha512sum > /dev/null &` for every CPU core.

**Comment by mberner-ch** [comment]
Update: This strange phenomenon seems to have completely disappeared with newer CoreOS releases.

I cannot reproduce it anymore on CoreOS 1185.3.0 with the 4.7.3 kernel. 
(Instead I see random spontaneous reboots of the OS, but that is a different topic.)

Closing the issue.
