### ISSUE TITLE
update_engine_client -update does not update to *latest* version if another is already downloaded

### ISSUE THREAD

**Issue by llarsson** [coreos/bugs#1392]
I run several servers in several clusters with `update-strategy off` to manually trigger updates and restarts when it suits us and our clients best (in case something goes wrong). I have noticed that the `update_engine_client -update` command behaves in a, to me, suboptimal way: if there is an update, any update, already downloaded, it will not try to check if there is actually a _newer_ update available.

That behavior leads to situations like this:
- A machine is running CoreOS stable version 899.11.0 and the `update-strategy` is `off`.
- In the background, it has at some point determined that 899.13.0 is out. Because it is not set to reboot, it just downloads the update, but does not reboot the server.
- Time goes on, and eventually, version 1010.5.0 is the latest stable version. However, because there is a previously downloaded update, the update engine does not download the newest stable version. Even triggering a manual forced check via `update_engine_client -update` only says that there is an update available (it refers to 899.13.0, not 1010.5.0) and that it will be installed upon next reboot. 
- Rebooting the machine will update to the downloaded version (899.13.0 in this example). A subsequent update check will correctly download the latest version immediately, jumping to version 1010.5.0.

I realize that the only mismatch here is between my expectations and the actual behavior, the latter of which being an implementation of a design decision. However, if you agree with me that explicitly triggering the "download updates" command should actually download the very latest version, then perhaps the design and implementation should also change.

**Comment by crawford** [comment]
Yeah, that is an interesting side-effect. I bet @marineam has a way to trick update-engine into downloading the latest version.

**Comment by marineam** [comment]
There is a reset status option you can use to forget about the already
installed update. This is a behavior I want to fix eventually.

**Comment by marineam** [comment]
So until we change update_engine's behavior this is what you need to do:

```
update_engine_client -reset_status
update_engine_client -check_for_update
```

**Comment by jonaz** [comment]
Just ran into this. I expected the OS to contiune to upgrade to the latest and when i reboot i get the latest installed. Now i had to reboot, install new update again and then reboot. Perhaps make it configurable.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
