### ISSUE TITLE
File auditing

### ISSUE THREAD

**Issue by thedrow** [coreos/bugs#140]
CoreOS should audit the server's configuration possibly using auditd in order to report about any configuration drifts that may have occurred in a server/cluster. Generally you shouldn't be touching CoreOS itself but I see devs use vim on configuration files on production server all the time :).

**Comment by thedrow** [comment]
Now that you guys support SELinux, I think that auditd will fit here perfectly.
Can it be preinstalled in CoreOS?

**Comment by marineam** [comment]
We do include `auditctl` and load `/etc/audit/rules.d/*` on boot. Additionally journald receives audit event data and parses out all the special fields so you can search the journal using them. However given the complexity of auditd and the fact that it and its tools are only designed for a traditional general purpose distro it felt like an odd fit in CoreOS. So if all you want is an audit log you can do that as-is. If you need the special log format from auditd or the guarantee that it won't miss an event or the kernel will panic you'll need to provide auditd as a static binary or in a chroot or similar.

Is auditctl and journalctl enough or do you really need the full auditd suite of tools?

**Comment by thedrow** [comment]
I'd like to have the full auditd suite in order to track the mutable parts of the system, to integrate seamlessly with Splunk, to be notified when an SELinux rule is being violated and other the features that auditd provides.
If security is something that CoreOS is concerned about then the OS should ship with auditd by default. Mainly to allow greater flexibility in the process of hardening and monitoring the system's security but also to reflect that security comes built in with CoreOS which can be demonstrated by the auditd logs (i.e. no rules violated, mutable files are being monitored, splunk integration out of the box etc.).

**Comment by thedrow** [comment]
With that being said, I'm not going to insist on auditd if you have another way to provide the kind of features I described above.
If that's the case, we need to provide documentation about security auditing, SIEM integration and rules that are built into the system that ensure no unauthorized modification is done.

**Comment by philips** [comment]
@joshix Could you look into writing a quick guide to auditctl usage on CoreOS? We have auditctl and systemd audit support enabled now.

Although, audit doesn't seem to work at the moment: https://groups.google.com/forum/#!topic/coreos-user/8A03C7yySxU @marineam can you take a quick look, I can confirm that audit doesn't seem to work.

**Comment by joshix** [comment]
There is a bug with ordering/making audit rules permanent in /etc/audit/rules.d; @marineam investigating

**Comment by crawford** [comment]
@joshix any updates?

**Comment by glevand** [comment]
I think the behavior the OP was requesting can be covered with what is currently provided in Container Linux via SELinux rules, audit rules, and possibly some kind of systemd journal scanner.  If the user wants to restrict access to config files, then run SELinux in enforcing mode and if needed supplement the provided SELinux policy with some additional rules.  If only monitoring is needed, then run SELinux in permissive mode, with additional rules if needed, and/or setup audit rules to get access messages to the systemd journal, then run some kind of systemd journal monitor that will take some action on entries of interests.  

@bgilbert There is nothing specific to Container Linux in setting something like this up, so I think this issue can be closed.
