### ISSUE TITLE
Systemd commands timeout inside docker container

### ISSUE THREAD

**Issue by victorserbu2709** [coreos/bugs#1401]
# Issue Report #
Systemd commands timeout inside container
## Bug ##
I have created a centos image following instruction found here: https://github.com/docker-library/docs/tree/master/centos#systemd-integration
Inside docker container, systemd start units as expected but after boot has finished I cannot run systemd commands inside container, for example:
```
[root@69mz8bpijc ~]# systemctl restart sshd
Error getting authority: Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Activation of org.freedesktop.PolicyKit1 timed out (g-dbus-error-quark, 20)
Failed to restart sshd.service: Connection timed out
```

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1010.5.0
VERSION_ID=1010.5.0
BUILD_ID=2016-05-26-2225
PRETTY_NAME="CoreOS 1010.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

CoreOS was installed in a VMware virtual machine.

Docker container:
```
root@69mz8bpijc ~]# rpm -qa | grep polkit
polkit-0.112-6.el7_2.x86_64
polkit-pkla-compat-0.1-4.el7.x86_64
[root@69mz8bpijc ~]# rpm -qa systemd
systemd-219-19.el7_2.9.x86_64
```

### Expected Behavior ###
Systemd commands works in docker container
### Actual Behavior ###
Systemd commands timeout in docker container
### Reproduction Steps ###

  1. Create an image based on centos 7 with systemd enabled
  2. Start container using a fleet unit similar to
```
Docker container was started using a fleet template:

[Unit]
Description=http-node
After=docker.service
Requires=docker.service
After=generate_http_env_2@%i.service
Requires=generate_http_env_2@%i.service
[Service]
TimeoutStartSec=0
EnvironmentFile=/etc/env_container_2_%i
ExecStartPre=-/usr/bin/docker kill http-node-%i
ExecStartPre=-/usr/bin/docker rm http-node-%i
ExecStart=/usr/bin/docker run --ulimit nofile=248576:248576 --shm-size 4G -v ${PERSISTENT_STORAGE}/var/log:/var/log -v ${PERSISTENT_STORAGE}/usr/local/voinow/admin/logs:/usr/local/voinow/admin/logs -v ${RUN_DIR}:/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /etc/env_container_2_%i:/etc/environment --name http-node-%i --hostname ${VOIPNOW_HOSTNAME} --ip ${PRIVATE_IP} --net=bridge10 --cap-add NET_ADMIN http:20160613002
ExecStop=/usr/bin/docker stop http-node-%i
ExecStopPost=/usr/bin/docker rm http-node-%i
[X-Fleet]
MachineOf=generate_http_env_2@%i.service
```

**Comment by victorserbu2709** [comment]
The problem replicated also on Centos with latest docker, I think it is not specific to CoreOS.
I opened a ticket at: https://bugs.centos.org/view.php?id=11022
Please tell me if you know an workaround for this problem.

**Comment by sweber83** [comment]
AFAIK it isn't that simple running systemd in an unprivileged docker container.
Here is an interesting article, that in part deals with this problem: https://lwn.net/Articles/676831/

**Comment by crawford** [comment]
I'm going to close this out since it isn't specific to CoreOS. If you are interested in running systemd inside of a container, I encourage you to look at `systemd-nspawn --boot` or `rkt`. Both of these tools natively run systemd as PID 1 within that container's CPU namespace.
