### ISSUE TITLE
Unhelpful error message at login

### ISSUE THREAD

**Issue by foxx** [coreos/bugs#1402]
If one of the units fails to start, you get the following messages;

```
Failed Units: 1
  user-cloudinit@var-lib-coreos\x2dinstall-user_data.service
```

This message is somewhat unhelpful, it merely tells you that user data has failed somewhere, and that's pretty much it, the output from `journalctl _EXE=/usr/bin/coreos-cloudinit` doesn't explain anything either, which makes debugging the actual issue a stab in the dark.

Furthermore, why does the string contain `\x2d`?

Can we make this a bit more user friendly?

**Comment by crawford** [comment]
If `journalctl _EXE=/usr/bin/coreos-cloudinit` doesn't yield any useful information, then that is a problem. Let's focus on that for now. Can you show the output of the following: `journalctl -b -t coreos-cloudinit --no-pager`? It should roughly be the same as the command you used.

The `\x2d` is the escape code for a hyphen. The hyphens in the service name represent directory separators which is why the hyphen in the directory name needs to be escaped.

**Comment by foxx** [comment]
Ahh okay, so here's the last 10 lines of each;

```
$ 
Here's the output from _EXE;

```
$ journalctl _EXE=/usr/bin/coreos-cloudinit
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Ensuring runtime unit file "etcd2.service" is unmasked
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Ensuring runtime unit file "fleet.service" is unmasked
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Ensuring runtime unit file "locksmithd.service" is unmasked
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Restarting systemd-networkd
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Restarted systemd-networkd (done)
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Calling unit command "start" on "opt-homermysql.mount"'
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Result of "start" on "opt-homermysql.mount": done
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Calling unit command "start" on "homer-api.service"'
Jun 14 19:32:15 localhost coreos-cloudinit[681]: 2016/06/14 19:32:15 Result of "start" on "homer-api.service": done
Jun 14 19:32:15 localhost coreos-cloudinit[681]: 2016/06/14 19:32:15 Calling unit command "start" on "homer-ui.service"'
Jun 14 19:32:15 localhost coreos-cloudinit[681]: 2016/06/14 19:32:15 Result of "start" on "homer-ui.service": done
Jun 14 19:32:15 localhost coreos-cloudinit[681]: 2016/06/14 19:32:15 Calling unit command "start" on "homer-mysql.service"'

$ journalctl -b -t coreos-cloudinit --no-pager
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Ensuring runtime unit file "etcd.service" is unmasked
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Ensuring runtime unit file "etcd2.service" is unmasked
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Ensuring runtime unit file "fleet.service" is unmasked
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Ensuring runtime unit file "locksmithd.service" is unmasked
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Restarting systemd-networkd
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Restarted systemd-networkd (done)
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Calling unit command "start" on "opt-homermysql.mount"'
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Result of "start" on "opt-homermysql.mount": done
Jun 14 19:32:10 localhost coreos-cloudinit[681]: 2016/06/14 19:32:10 Calling unit command "start" on "homer-api.service"'
Jun 14 19:32:15 localhost coreos-cloudinit[681]: 2016/06/14 19:32:15 Result of "start" on "homer-api.service": done
Jun 14 19:32:15 localhost coreos-cloudinit[681]: 2016/06/14 19:32:15 Calling unit command "start" on "homer-ui.service"'
Jun 14 19:32:15 localhost coreos-cloudinit[681]: 2016/06/14 19:32:15 Result of "start" on "homer-ui.service": done
Jun 14 19:32:15 localhost coreos-cloudinit[681]: 2016/06/14 19:32:15 Calling unit command "start" on "homer-mysql.service"'
Jun 14 19:32:15 localhost coreos-cloudinit[681]: 2016/06/14 19:32:15 Failed to apply cloud-config: Unit opt-homer-mysql.mount failed to load: Invalid argument. See system logs and 'systemctl status opt-homer-mysql.mount' for details.
```

As you can see, the additional command you provided seems to give a much better debug output.

wrt `\x2d`, that makes sense and all but it's not very human friendly. I'm not sure what can be done about it though.

**Comment by crawford** [comment]
That discrepancy in logging output is due to https://github.com/coreos/bugs/issues/373. You'll want to use `-t`/`--identifier` instead.

**Comment by foxx** [comment]
Sorry I'm confused, if I add `-t` this happens;

```
journalctl -t _EXE=/usr/bin/coreos-cloudinit
```

Although I can make it work if I use;

```
journalctl -t coreos-cloudinit
```

If the `_EXE` method isn't recommended, can we get a docs update for [here](https://coreos.com/os/docs/latest/cloud-config.html), as that's where I got the command from

**Comment by crawford** [comment]
`-t` matches the syslog identifier, so that second form is correct. I've submitted PRs for the doc fixes [here](https://github.com/coreos/docs/pull/837) and [here](https://github.com/coreos/coreos-cloudinit/pull/430). Thanks for the report.

**Comment by foxx** [comment]
Awesome, thanks for the quick replies and resolution, much appreciated :)

**Comment by foxx** [comment]
PS) Apologies I didn't realise docs were in Github, otherwise I'd have submitted a PR myself. Will remember for future.

**Comment by crawford** [comment]
The docs are scattered all over the place, don't sweat it.
