### ISSUE TITLE
Support for fully read-only rootfs (or overlay)

### ISSUE THREAD

**Issue by foxx** [coreos/bugs#1404]
Previously `/etc` was read-only on CoreOS, but it's since been made writable after improvements. Is there an out-of-the-box way to make it so CoreOS resides entirely as a read-only image, or would I need to hack away at the internals? My use case for this would be using it as an embedded system image. Thoughts?

**Comment by foxx** [comment]
Also there is some surprising behaviour from `user-data` being executed on each boot. If I make a change to `cloud-config` on an existing host, then any changes to `/etc` made before will persist, but it would be nice if there was a way to make it revert back to a clean state on each reboot.

**Comment by crawford** [comment]
Check out `rootflags` in the [kernel documentation](https://www.kernel.org/doc/Documentation/kernel-parameters.txt).

> If I make a change to cloud-config on an existing host, then any changes to /etc made previously will persist, for example if I remove a unit it will still be there.

This is why coreos-cloudinit is not recommended for configuration management. It's quite poor at it.

> It would be nice if there was a way to make it revert back to a clean state on each reboot.

There are two ways to do this:

  - `rm -rf /`
  - Force [Ignition](https://coreos.com/ignition) to run on every boot and ask it to format the root partition.

**Comment by foxx** [comment]
Thanks for the advice, will check it out and re-open if any problems 👍
