### ISSUE TITLE
Cloud config not mounted on bare metal hosts provisioned with Ironic.

### ISSUE THREAD

**Issue by lleszczu** [coreos/bugs#1405]
# Issue Report
### CoreOS Version

```
$  cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1010.5.0
VERSION_ID=1010.5.0
BUILD_ID=2016-05-26-2225
PRETTY_NAME="CoreOS 1010.5.0 (MoreOS)"

```
### Environment

What hardware/cloud provider/hypervisor is being used to run CoreOS?
### Expected Behavior

Partition with `config-2` label is mounted under /media/configdrive and cloud config is applied
### Actual Behavior

Nothing is mounted and config drive is not executed
### Reproduction Steps
1. Load latest CoreOS image to Openstack
2. Provision bare metal host with Ironic
### Environment

Openstack + Ironic
### Other Information

Ironic is using standard cloud images for provisioning bare metal hosts. 
Script used to create config can be found here: https://github.com/openstack/ironic-python-agent/blob/master/ironic_python_agent/shell/copy_configdrive_to_disk.sh
My tests indicates that issue is caused by this line: https://github.com/coreos/coreos-cloudinit/blob/9a715eff2e45c94dfdc947c13760260e691a1708/units/media-configdrive.mount#L6

**Comment by crawford** [comment]
You need to provide the following kernel parameter during boot: `coreos.configdrive=1`.

Alternatively, we are in the process of adding OpenStack support to [Ignition](https://coreos.com/ignition) (shooting for the next Alpha release). Unless there is a compelling reason to use coreos-cloudinit, I would highly recommend you make the jump to Ignition.

**Comment by lleszczu** [comment]
@crawford Unfortunatelly the way Ironic installer works it's hard to add kernel parameters, it just copies cloud image to disk (https://github.com/openstack/ironic-python-agent/blob/master/ironic_python_agent/shell/write_image.sh#L42).

It's not P1 for me right now, we just prepared custom image with cloud config enabled for all nodes, not just VMs, so I'll take a look at Ignition once it's released.

**Comment by crawford** [comment]
You might be able to get away with using the Rackspace OnMetal CoreOS image. It does an extra [ping operation](https://github.com/coreos/coreos-overlay/blob/master/coreos-base/oem-rackspace-onmetal/files/cloud-config.yml), but that might be okay for your setup.

**Comment by lleszczu** [comment]
Unfortunately it doesn't seem to work for me. Additionally OnMetal image broke my serial console access to node, no video output whatsoever after grub loads (even after adding console=ttyS0 console=tty0 to kernel params).

**Comment by crawford** [comment]
Ignition is the correct solution here. We aren't going to be able to change the way coreos-cloudinit works at this point (as mentioned before, you'll need that kernel parameter or a different Container Linux flavor).
