### ISSUE TITLE
Ignition filesystem section does not support creating a swap partition

### ISSUE THREAD

**Issue by spkane** [coreos/bugs#1407]
# Issue Report

It seems like setting up a swap partition via ignition should be trivial, yet according to the docs it is not possible.

Is there a reason for this, or is it a planned future feature?

What is the recommended method today for using a swap partition versus a swap file?

``` json
  "storage": {
    "disks": [{
      "device": "/dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0",
      "wipeTable": true,
      "partitions": [{
        "label": "SWAP",
        "typeGuid": "0657fd6d-a4ab-43c4-84e5-0933c84b4f4f",
        "number": 1,
        "start": 0,
        "size": 23068672,
      }]
    }],
    "filesystems": [    {
      "name": "swap",
      "mount": {
        "device": "/dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0-part1",
        "format": "swap",
        "create": {
          "force": true,
          "options": [ "--label=SWAP" ]
        }
      }
    }
```
### CoreOS Version

1010.5.0
### Environment

PXE - Dell R420
### Expected Behavior

Ignition would create a swap partition, as expected and be able to enable it.
### Actual Behavior

Swap is not supported.
## Feature Request

Support swap partitions via Ignition
### Environment

PXE - Dell R420

**Comment by mischief** [comment]
this might be because there's no `mkfs.swap`, but instead `mkswap`, so this might have to be special-cased to be supported :disappointed:

**Comment by crawford** [comment]
@spkane there is no technical reason Ignition can't do this - just haven't gotten around to it. As a workaround, you can create two services: one which only runs once (ConditionFirstBoot) and runs mkswap and the other which runs every boot and runs swapon.

**Comment by spkane** [comment]
Thank you. I'll look into doing that as a workaround for now, but this feels like a good use case to add into ignition natively when time allows.
