### ISSUE TITLE
bnx2x firmware regression in coreos stable 1010.5.0

### ISSUE THREAD

**Issue by spkane** [coreos/bugs#1408]
similar past issues: #450 & #1016 

host info:

bare metal host (Dell R420)
bnx2x NICs
coreos stable 1010.5.0

# Issue Report #

## Bug ##

On a bare metal host with bnx2x NICs, when you enable ignition the boot fails, because it can not load the NIC firmware.

The exact same image boots fine, when using cloud-init.

### CoreOS Version ###

1010.5.0

### Environment ###

Dell r420

### Expected Behavior ###

It loads the firmware and can then successfully pull down the Ignition config.

### Actual Behavior ###

Can't load the firmware, and therefore can't download the Ignition file and all else fails.

**Comment by spkane** [comment]
Is there an "easy"-ish way for me to re-build the initrd and the correct drivers?

**Comment by mischief** [comment]
related to https://github.com/coreos/bugs/issues/1263

try https://coreos.com/os/docs/latest/booting-with-pxe.html#adding-a-custom-oem

**Comment by spkane** [comment]
I was able to work around this using the information in the referenced ticket. It would be very useful, if coreos simply provided an alternative initrd with each release that included the firmware, so those of use that need it, can still simply download that initrd and use it directly, without jumping through these hoops each time.

**Comment by crawford** [comment]
@spkane The plan is to include the firmware and modules in the initrd (as detailed by https://github.com/coreos/bugs/issues/1263). Once that's done, the vanilla images should work.

**Comment by crawford** [comment]
I'm going to close this in favor of the aforementioned bug.
