### ISSUE TITLE
Ignition support for OpenStack

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1413]
Ignition and coreos-metadata should support OpenStack - both config drive and the network metadata service.

**Comment by SchwarzM** [comment]
I would love to see that, it would greatly ease things on my side.
Is it possible in the meantime to somehow force it to use an ec2 oem_id ?

Kind regards
SchwarzM

**Comment by crawford** [comment]
@SchwarzM  You can edit `/usr/share/oem/grub.cfg` and add `set oem_id="ec2"`. That will tell CoreOS that it's running on EC2. You'll then need to reset the disk UUID (`sgdisk --disk-guid 00000000-0000-0000-0000-000000000001`) so that Ignition runs on the next boot.

**Comment by crawford** [comment]
Should be fixed by https://github.com/coreos/ignition/pull/287.

@SchwarzM would you mind testing out this release of Ignition (should be in CoreOS 1164.0.0)?

**Comment by crawford** [comment]
I'm going to close this for now. But I'll keep an eye out for any trouble. We can reopen this if there are any issues.

**Comment by SchwarzM** [comment]
will test it when i get my hands on it ...
