### ISSUE TITLE
Can't start iscsiadm inside rkt container on CoreOS

### ISSUE THREAD

**Issue by SerCeMan** [coreos/bugs#1415]
# Issue Report
### Bug

I'm trying to start kubernetes with an iscsi plugin inside rkt on CoreOS using instruction here. The problem is the iscsi daemon can't start, so I'm getting an error and can't mount a volume to pod.
### CoreOS Version

NAME=CoreOS
ID=coreos
VERSION=1081.1.0
VERSION_ID=1081.1.0
BUILD_ID=2016-06-16-2251
PRETTY_NAME="CoreOS 1081.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
### Environment

VMware vSphere
### Expected Behavior

Volume mounts fine.
### Actual Behavior

I getting an error

```
iscsi_util.go:112] iscsi: failed to sendtargets to portal 156.64.48.59:3260 
    error: iscsiadm: Failed to load module tcp: No such file
iscsiadm: Could not load transport tcp.Dropping interface default.
[disk_manager.go:50] failed to attach disk 
iscsi: failed to setup
kubelet.go:1780] Unable to mount volumes for pod ...
```
### Reproduction Steps

Follow the [instruction here](https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html#customizing-rkt-options)
### Other Information

I described workaround that works for me here:
http://stackoverflow.com/questions/37921980/cant-start-iscsiadm-inside-krt-container-on-coreos

**Comment by xchenum** [comment]
SerCeMan, I tried to follow your instructions, but it doesn't work for me under CoreOS 1068.3.0.

Interestingly, the iscsi volume of my pod is actually attached at /dev/sda, but kubelet is reporting "Could not attach disk: Timeout after 10s; skipping pod". Any ideas?

**Comment by SerCeMan** [comment]
@xchenum, You can start with digging to logs on your worker machine by using `journalctl`

**Comment by bgilbert** [comment]
The documentation you were following has since been removed, since it was unmaintained and had become out of date.  Thus I'll close this.  Thanks for reporting.
