### ISSUE TITLE
Ignition fails when asked to create empty files

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1420]
# Issue Report #

### Ignition Version ###

v0.7.0

### Environment ###

All

### Expected Behavior ###

Files can be created without contents, since they are optional in the spec.

### Actual Behavior ###

Ignition fails with:

```
files: createFilesystemsFiles: createFiles: op(1): [started]  fetching file "/etc/empty"
files: createFilesystemsFiles: createFiles: op(1): [failed]   fetching file "/etc/empty": unsupported source scheme
```

### Reproduction Steps ###

  1. Boot a machine with the following config:

```json
{
  "ignition": { "version":"2.0.0" },
  "storage": {
    "files": [{
      "filesystem": "root",
      "path": "/etc/empty"
    }]
  }
}
```

**Comment by ajeddeloh** [comment]
closed via https://github.com/coreos/ignition/pull/248
