### ISSUE TITLE
Docker journald driver on coreos beta channel 1068.2.0

### ISSUE THREAD

**Issue by yanndegat** [coreos/bugs#1422]
# Issue Report #
When using Docker engine journald driver, docker logs breaks starting version 1068.2.0
It seems that it's a docker bug, fixed in 1.11. https://github.com/docker/docker/issues/20497

### CoreOS Version ###
1068.2.0

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1068.2.0
VERSION_ID=1068.2.0
BUILD_ID=2016-06-17-1616
PRETTY_NAME="CoreOS 1068.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

### Expected Behavior ###
docker logs [container_id] 
[blah blah logs]
[...]

### Actual Behavior ###
docker logs [container_id] 
Error running logs job: configured logging reader does not support reading

### Reproduction Steps ###

  1. docker run -d --name tomcat tomcat
  2. docker logs tomcat

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

**Comment by crawford** [comment]
Could you give 1081.1.0 a try? In that release, we added support for the journald logging driver.

**Comment by eazynow** [comment]
For what it's worth we had the same error and switching to 1081.1.0 fixed it 😃

**Comment by mimmus** [comment]
Problem still present in 1068.8.0 (latest stable)

**Comment by brosner** [comment]
I have this issue with 1068.9.0 which we are testing in staging. It is a regression from our production environment running 1010.5.0. It would be really helpful to get a fix for this on the stable channel as I also don't have the option to use beta/alpha for production.
