### ISSUE TITLE
coreos-install script appears to have multiple issues in CoreOS stable (1010.5.0)

### ISSUE THREAD

**Issue by spkane** [coreos/bugs#1425]
# Issue Report #

## Bug ##

coreos-install doesn't work without editing.

### CoreOS Version ###

CoreOS stable (1010.5.0)

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

Dell r420

### Expected Behavior ###

```
# sudo coreos-install -d /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0 -i ignition.json
Downloading the signature for https://stable.release.core-os.net/amd64-usr/1010.5.0/coreos_production_image.bin.bz2...
2016-06-24 03:57:20 URL:https://stable.release.core-os.net/amd64-usr/1010.5.0/coreos_production_image.bin.bz2.sig [543/543] -> "/tmp/coreos-install.TiIffhG3ct/coreos_production_image.bin.bz2.sig" [1]
Downloading, writing and verifying coreos_production_image.bin.bz2...
2016-06-24 03:57:56 URL:https://stable.release.core-os.net/amd64-usr/1010.5.0/coreos_production_image.bin.bz2 [250884614/250884614] -> "-" [1]
gpg: Signature made Thu May 26 22:37:59 2016 UTC using RSA key ID 2E16137F
gpg: key 93D2DCB4 marked as ultimately trusted
gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" [ultimate]
Installing Ignition config ignition.json...
tune2fs 1.42.13 (17-May-2015)
Success! CoreOS stable 1010.5.0 is installed on /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0
```

### Actual Behavior ###

If you run it with ```bash -xv``` it exits becuase OEM_DEV is blank. The blkid command seems to work when tested at the shell prompt, but does not seem to work inside the script.

```
+ [[ -n ignition.json ]]
blkid -t "LABEL=OEM" -o device "${DEVICE}"*)
blkid -t "LABEL=OEM" -o device "${DEVICE}"*
++ blkid -t LABEL=OEM -o device /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0 /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0-part1 /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0-part2 /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0-part3 /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0-part4 /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0-part6 /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0-part7 /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0-part9
+ OEM_DEV=
rm -rf '/tmp/coreos-install.Kke7Rngz42'
+ rm -rf /tmp/coreos-install.Kke7Rngz42
```

### Reproduction Steps ###

  1. PXE boot CoreOS stable (1010.5.0) on a Dell r420 with 2 HW RAID volumes
  2. run ```sudo coreos-install -d /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0 -i ignition.json```

### Other Information ###

This is a diff of the changes I used to get the script to work, and properly start the ignition step after reboot.

The large grub HERE doc at the bottom of the script, is due to the fact that the default grub file has an error in it that prevents the first boot ignition step from being triggered by the magic UUID. In the defgault grub file is uses the argument ```--disk-uuid```, but this should be ```--fs-uuid```.

```
--- /usr/bin/coreos-install	2016-05-26 22:23:11.000000000 +0000
+++ ./coreos-install	2016-06-24 05:35:17.000000000 +0000
@@ -403,12 +407,15 @@
 fi

 # inform the OS of partition table changes
-blockdev --rereadpt "${DEVICE}"
+#blockdev --rereadpt "${DEVICE}"
+udevadm trigger
+sleep 10

 if [[ -n "${CLOUDINIT}" ]] || [[ -n "${COPY_NET}" ]]; then
     # The ROOT partition should be #9 but make no assumptions here!
     # Also don't mount by label directly in case other devices conflict.
-    ROOT_DEV=$(blkid -t "LABEL=ROOT" -o device "${DEVICE}"*)
+    #ROOT_DEV=$(blkid -t "LABEL=ROOT" -o device "${DEVICE}"*)
+    ROOT_DEV=${DEVICE}-part9

     if [[ -z "${ROOT_DEV}" ]]; then
         echo "Unable to find new ROOT partition on ${DEVICE}" >&2
@@ -441,7 +448,8 @@
 if [[ -n "${IGNITION}" ]]; then
     # The OEM partition should be #3 but make no assumptions here!
     # Also don't mount by label directly in case other devices conflict.
-    OEM_DEV=$(blkid -t "LABEL=OEM" -o device "${DEVICE}"*)
+    #OEM_DEV=$(blkid -t "LABEL=OEM" -o device "${DEVICE}"*)
+    OEM_DEV=${DEVICE}-part6

     if [[ -z "${OEM_DEV}" ]]; then
       echo "Unable to find new OEM partition on ${DEVICE}" >&2
@@ -454,12 +462,24 @@

     echo "Installing Ignition config ${IGNITION}..."
     cp "${IGNITION}" "${WORKDIR}/oemfs/coreos-install.json"
-    echo  "set linux_append=\"coreos.config.url=oem:///coreos-install.json"\" > "${WORKDIR}/oemfs/grub.cfg"
+
+    cat << 'EOF' > "${WORKDIR}/oemfs/grub.cfg"
+set linux_append="coreos.config.url=oem:///coreos-install.json"
+set timeout=10
+# Determine if this is a first boot.
+search --no-floppy --set first_boot --fs-uuid 00000000-0000-0000-0000-000000000001
+if [ -n "$first_boot" ]; then
+  # Note we explicitly request the disk-guid randomization, first_boot only triggers ignition.
+  set first_boot="coreos.first_boot=1 coreos.randomize_disk_guid=00000000-0000-0000-0000-000000000001"
+fi
+EOF

     umount "${WORKDIR}/oemfs"
     trap "rm -rf '${WORKDIR}'" EXIT
 fi

+tune2fs "${DEVICE}-part9" -U 00000000-0000-0000-0000-000000000001
+
 rm -rf "${WORKDIR}"
 trap - EXIT
```

**Comment by spkane** [comment]
I filed another ticket specifically for the Grub issue here: https://github.com/coreos/bugs/issues/1426

**Comment by spkane** [comment]
This won't be fully fixed for me, until this bug is also fixed, so that the proper NIC firmware files are included for the initrd and ignition: https://github.com/coreos/coreos-overlay/pull/2005

**Comment by crawford** [comment]
I'm reasonably sure the underlying issue here is the fact that we aren't waiting for udev to settle after kicking the partition tables. `blkid` works when you run it because the system has had enough time to catch up with the changes to the disk.

**Comment by spkane** [comment]
In addition to the partitions, often not being identified, this script needs to be able to apply the magic GUID to the boot device, so that ignition will trigger when the system is rebooted. Initial, I filed this as a separate ticket, but it appears that it is simply functionality that is absent from this script. Is this intentional? It would seem that making this an additional switch would be both safe and convenient. I can try and get a PR in later this week, if no one gets to it before me.

**Comment by crawford** [comment]
The script does not need this functionality. The disk image it downloads (coreos_production_image.bin.bz2) already has the correct GPT table GUID applied. `coreos-install` just `dd`s this to the disk - GPT headers and all.

**Comment by spkane** [comment]
It Isn't working in our setup at all though, hence the problem. I'll play around with it a bit more, but the dd is not doing the the job, maybe because of previous information on the disk.

**Comment by spkane** [comment]
@crawford Based on your input, I took the original file, and simply applied this diff:

```
$ diff -u /usr/bin/coreos-install ./coreos-install
--- /usr/bin/coreos-install	2016-05-26 22:23:11.000000000 +0000
+++ ./coreos-install	2016-07-05 17:08:01.805012706 +0000
@@ -404,6 +404,7 @@

 # inform the OS of partition table changes
 blockdev --rereadpt "${DEVICE}"
+sleep 10

 if [[ -n "${CLOUDINIT}" ]] || [[ -n "${COPY_NET}" ]]; then
     # The ROOT partition should be #9 but make no assumptions here!
```

which worked (at least once)...

There is likely a better way to test that things are as expected, versus just using a stupid ```sleep``` command (like making sure one of the partitions is present), but I'm not sure what you'd all prefer.

**Comment by crawford** [comment]
@spkane okay, thanks for the data-point. @dm0- is working on fixing this up. I believe he is using `udevadm settle` to do the wait.

**Comment by dm0-** [comment]
Oops, I just realized this issue isn't referenced in the actual commits or pull requests that were related.  The attempted fix is coreos/init#fd60a8dbf816a43f8ad10582591dd0a98f8555f5, and it was included in the overlay with coreos/coreos-overlay#a6f6f4d46dd8f4d799b7e62d49b5544002b5a25f.

**Comment by crawford** [comment]
@dm0- was this fixed in 1109.1.0?

**Comment by dm0-** [comment]
No, it doesn't look like this commit was in the overlay at that point.

**Comment by crawford** [comment]
@dm0- have they made it into a release yet? (apparently vacation wiped my memory)

**Comment by dm0-** [comment]
They're not in the latest alpha, so no release yet.  All the `coreos-install` patches are included in the current overlay, though, so they should be in the next one.

**Comment by crawford** [comment]
I'm going to go ahead and close this one since everything has been merged. If we see any more issues after 1122.0.0, let's re-open it.
