### ISSUE TITLE
grub.cfg in CoreOS stable (1010.5.0) does not properly trigger first_boot from UUID

### ISSUE THREAD

**Issue by spkane** [coreos/bugs#1426]
# Issue Report #

## Bug ##

The grub.cfg file in grub.cfg.tar has an error which prevents first_boot from being set when a partition has the magic UUID

### CoreOS Version ###

CoreOS stable (1010.5.0)

### Environment ###

Dell r420

### Expected Behavior ###

If a filesystem has the UUID 00000000-0000-0000-0000-000000000001, then first_boot should be set and things like ignition should run in the initrd.

### Actual Behavior ###

first_boot is not set when the UUID exists, and the system does not run ignition.

### Reproduction Steps ###

  1. Install coreos onto the boot drive of a Dell r420, with an ignition config
  2. Set the ROOT parition's UUID to 00000000-0000-0000-0000-000000000001
  3. Reboot, and notice that ignition is never run.

### Other Information ###

The default grub.cfg looks like this:

```
search --no-floppy --set first_boot --disk-uuid 00000000-0000-0000-0000-000000000001
if [ -n "$first_boot" ]; then
  # Note we explicitly request the disk-guid randomization, first_boot only triggers ignition.
  set first_boot="coreos.first_boot=1 coreos.randomize_disk_guid=00000000-0000-0000-0000-000000000001"
fi
```

when, in fact, it should read like this:

```
search --no-floppy --set first_boot --fs-uuid 00000000-0000-0000-0000-000000000001
if [ -n "$first_boot" ]; then
  # Note we explicitly request the disk-guid randomization, first_boot only triggers ignition.
  set first_boot="coreos.first_boot=1 coreos.randomize_disk_guid=00000000-0000-0000-0000-000000000001"
fi
```

**Comment by crawford** [comment]
GRUB and the rest of the boot process are looking at the disk's GUID, not the filesystem's. If the disk is determined to have a GUID of `00000000-0000-0000-0000-000000000001`, `coreos.first_boot` is set to `1` and the disk's GUID is randomized. This is all working as expected.

**Comment by spkane** [comment]
Ok. That makes sense. I had to try to get this working myself, because the coreos-install script does not set this GUID anywhere, even when you inject an ignition script, so ignition is not triggered on reboot. We can close this in favor of #1425, but there should be a way to set this GUID on the install device, via that script.

**Comment by crawford** [comment]
That GUID should already be in the image that's written to disk. This should work out of the box. Does Ignition not run on first boot in your environment?

**Comment by spkane** [comment]
Ingition does not run on the first boot. I have to jump through some hoops to get it working. Now that I have a better understanding of how it should be working, I can at least try and determine what is missing or interfering and provide some more details.

**Comment by crawford** [comment]
Let's re-open this for now then.

**Comment by crawford** [comment]
Can you provide more information about your setup? After `coreos-install`, what is the output of `sudo cgpt show -v <device>`?

**Comment by spkane** [comment]
```
$ sudo cgpt show -v /dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0
       start        size    part  contents
           0           1          Hybrid MBR
           1           1          Pri GPT header
                                  Sig: [EFI PART]
                                  Rev: 0x00010000
                                  Size: 92
                                  Header CRC: 0xfd9aa505
                                  My LBA: 1
                                  Alternate LBA: 9289727
                                  First LBA: 34
                                  Last LBA: 9289694
                                  Disk UUID: 00000000-0000-0000-0000-000000000001
                                  Entries LBA: 2
                                  Number of entries: 128
                                  Size of entry: 128
                                  Entries CRC: 0xa8418411
           2          32          Pri GPT table
        4096      262144       1  Label: "EFI-SYSTEM"
                                  Type: EFI System Partition
                                  UUID: 4E7D6490-C4F9-4DCD-890F-BFE6C904D6CC
                                  Attr: Legacy BIOS Bootable
      266240        4096       2  Label: "BIOS-BOOT"
                                  Type: BIOS Boot Partition
                                  UUID: 470CE939-E8E5-4069-B578-CA0FCF303189
      270336     2097152       3  Label: "USR-A"
                                  Type: Alias for coreos-rootfs
                                  UUID: 7130C94A-213A-4E5A-8E26-6CCE9662F132
                                  Attr: priority=1 tries=0 successful=1
     2367488     2097152       4  Label: "USR-B"
                                  Type: Alias for coreos-rootfs
                                  UUID: E03DD35C-7C2D-4A47-B3FE-27F15780A57C
                                  Attr: priority=0 tries=0 successful=0
     4464640      262144       6  Label: "OEM"
                                  Type: Alias for linux-data
                                  UUID: E91AD774-868D-43F4-8B22-34BC2D7640BE
     4726784      131072       7  Label: "OEM-CONFIG"
                                  Type: CoreOS reserved
                                  UUID: 94F76F06-867F-4C05-9717-6B9A655528FD
     4857856     4427776       9  Label: "ROOT"
                                  Type: CoreOS auto-resize
                                  UUID: 3C4D7E02-8E27-4D97-850B-DDDC2D3228C7
   285474783          32 INVALID  Sec GPT table
           1           1 INVALID  Sec GPT header

WARNING: one of the GPT header/entries is invalid, please run 'cgpt repair'
```

While trying to reproduce this, I am actually running into what looks like this bug:

https://github.com/coreos/bugs/issues/1398

I'm going to follow some of the advice there and see if I can reproduce the root of this bug or not, and report here.

**Comment by spkane** [comment]
So, Ignition seems to actually be running curently, however the initrd is missing the firmware files we need for our network cards. We fix this when PXE booting, by modifying the initrd, but there is no easy way to do this with the coreos-install image that is currently distributed with stable (1010.5.0).

I'm going to close this for now, but will re-open if the original issue continues is reproduced again. It might be transient based on some pre-existing state on the disk.

**Comment by crawford** [comment]
@spkane CoreOS 1097.0.0 has the firmware and modules in the initrd if you want to give that a shot.
