### ISSUE TITLE
update_engine dbus API blocked while writing update to disk

### ISSUE THREAD

**Issue by danielschonfeld** [coreos/bugs#143]
This happened twice now on two different machines trying to update 8 hours apart:

```
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=103093532
LAST_CHECKED_TIME=1411575812
PROGRESS=0.971182
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=103093532
[0924/162546:INFO:update_engine_client.cc(123)] Error getting status: GError(4): Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=(null)
NEW_VERSION=(null)
NEW_SIZE=0
LAST_CHECKED_TIME=1411575812
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_FINALIZING
NEW_VERSION=0.0.0.0
NEW_SIZE=103093532
LAST_CHECKED_TIME=1411575812
PROGRESS=0.000000
```

**Comment by kdomanski** [comment]
@crawford I'm suffering from a similar issue when running CoreOS from a slow-write media, i.e. a USB stick. `strace` tells me the timeouts happen on a `close` call over an FD attached to one of the media partitions - thus I figure the whole update engine stalls when flushing data from buffers to physical media.

Interestingly, setting the `dst_fd` in `FilesystemCopierAction::PerformAction()` to be non-blocking removes one of the timeouts I'm experiencing.

/cc @hinnerk @tiff

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
