### ISSUE TITLE
Ability to set hostname via ignition

### ISSUE THREAD

**Issue by spkane** [coreos/bugs#1434]
## Feature Request ##

It would be useful to be able force the hostname via ignition, so that the system immediately comes up with the correct hostname, even in cloud environments like AWS. This would provide some feature parity for people moving from cloud config to ignition.

### Environment ###

AWS EC2

### Desired Feature ###

```json
{
  "ignition": { "version": "2.0.0" },
  "system": [{
    "hostname": "my-short-hostname"
    }]
}
```

**Comment by crawford** [comment]
```json
{
  "ignition": { "version": "2.0.0" },
  "storage": {
    "files": [{
      "filesystem": "root",
      "path": "/etc/hostname",
      "mode": 420,
      "contents": { "source": "data:,core1" }
    }]
  }
}
```

We should probably document this though. I'll add an example on https://coreos.com/ignition.
