### ISSUE TITLE
docker cgroup driver discussion - cgroupfs or systemd

### ISSUE THREAD

**Issue by euank** [coreos/bugs#1435]
## Background

CoreOS currently ships docker with a non-default configuration of `--exec-opt native.cgroupdriver=systemd`. This option manages Docker's container's cgroups with systemd instead of the `cgroupfs` driver.

I don't know the full history for why this configuration was chosen, but I believe it was related to interacting well with Kubernetes.

## Problem

I believe that this change might no longer make sense for CoreOS to ship. Below, I've enumerated reasons why we might want to use each driver:

### Reasons to use cgroupfs

* Better tested with docker (and related projects like k8s, cadvisor) due to being the default upstream driver :star::star: 
* Doesn't mess up handling of `init.scope` in systemd 226+ (current issue in CoreOS alpha/beta) ([runc issue](https://github.com/opencontainers/runc/issues/931), [cadvisor issue](https://github.com/google/cadvisor/issues/1344))
* First-supported for some Kubernetes features (e.g. [pod-level cgroups](https://github.com/kubernetes/kubernetes/issues/27204))
* Jessie Frazelle's [endorsement](https://twitter.com/jessfraz/status/641628951408832512) :star2: 

(important reasons starred)

### Reasons to use systemd

* Backwards compatibility with the cgroup layout
* Better integration with some tools (are there any worth noting? I'm specifically thinking of `systemctl status` but I'm not sure that actually does integrate better)
* Belief that having systemd manage cgroups is fundamentally better than having dockerd/runc do so

## Conclusion

I can't claim that any of the reasons for either choice make one inarguably better, but I think there are enough issues here that it's worth having the discussion. This will also help guide some related issues (how effort is directed on some K8s + CoreOS issues etc).

cc @philips @mischief @vishh @timstclair @crawford @marineam @aaronlevy

**Comment by crawford** [comment]
The original reason for the change was due to the poor interaction between Docker and cAdvisor. If I remember correctly, the "docker" cgroup driver was creating a hierarchy that cAdvisor didn't recognize. If that is in fact the issue, then I think we can reverse that configuration change.

**Comment by pbx0** [comment]
I've spent a little time testing the docker cgroup driver on docker on the latest coreos alpha with the v1.3 coreos-kubernetes repo. So far I havn't been able to reproduce some of the possibly related issues:
https://github.com/coreos/coreos-kubernetes/issues/293
https://github.com/kubernetes/kubernetes/issues/12533

So I don't have enough to make the call on this but next step is just running e2e tests against a cluster setup with coreos-kubernetes on coreos and with the docker cgroup driver. I'll be out of office for a few days starting now.

possibly related: https://github.com/kubernetes/kubernetes/issues/27383#issuecomment-226345299

**Comment by pbx0** [comment]
Spent some more time with this and talked to some people. I think the consensus from our team is to ship it. No tests I've been able to run have brought issues nor have I seen anything in the logs that worry me or at least differ from the systemd driver. I've done this testing on a recent alpha and kubernetes v1.3.4.

**Comment by manojlds** [comment]
Hi, how can I know if this has made its way into CoreOS stable?

**Comment by zihaoyu** [comment]
@manojlds Last time I tried latest stable it's not there.

**Comment by crawford** [comment]
@manojlds it can be a bit of a rat's nest to follow, but I'll show you how I figured it out in this case. If you look at my [pull request](https://github.com/coreos/coreos-overlay/pull/2113/files) which fixed the issue, you'll notice that Docker was renamed from `docker-1.11.2` to `docker-1.11.2-r1`. So `docker-1.11.2-r1` is the first version with this fix. If you look at the [package list for Stable](https://stable.release.core-os.net/amd64-usr/current/coreos_production_image_packages.txt), you'll see that the current Stable (as of this writing) ships `docker-1.10.3-r5`. So it's not there yet. The [package list for Beta](https://beta.release.core-os.net/amd64-usr/current/coreos_production_image_packages.txt), however, shows `docker-1.11.2-r3`. So Beta would have the fix.

**Comment by stensonb** [comment]
the current beta channel build (1185.1.0) includes `docker-1.11.2-r5`, fyi...

**Comment by redbaron** [comment]
what is the current status of this? for docker 1.12.6 and systemd 231, which cgroup driver should be used by docker and kubelet?

**Comment by crawford** [comment]
docker's default, cgroupfs, is now used.

**Comment by redbaron** [comment]
I found that  without switching both docker and kubelet to systemd, kubelet checks and complains about non-existing containers, or maybe containers it can't reach.

**Comment by mattshma** [comment]
Could somebody tell us which cgroup driver should be used by docker and kubelet please? 😄

**Comment by ChaitanyaVSH** [comment]
how to change the Cgroup in docker from Systemd to cgroupfs

**Comment by psegaro** [comment]
# Setup daemon.
cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF

# Restart docker.
systemctl daemon-reload
systemctl restart docker

From https://kubernetes.io/docs/setup/cri/

**Comment by psegaro** [comment]
"exec-opts": ["native.cgroupdriver=cgroupfs"],

**Comment by mars64** [comment]
Sorry to resurrect the dead here but this thread seems to disagree with what appears to be a more recent consensus and I'd love to know more about what the recommended go-forward configurations are. As mentioned in https://github.com/kubernetes/kubeadm/issues/1394 - we are indeed seeing situations `where nodes that are configured to use cgroupfs for kubelet and docker and systemd for the rest can become unstable under resource pressure`, currently on `2079.5.1`, but will update shortly and test again. Is there a different place to find more information on cgroup driver configuration recommendations for CoreOS?

**Comment by mars64** [comment]
I received some answers from the CoreOS mailing thread. An important consideration here is the fact that CoreOS is now in maintenance mode, and some otherwise critical changes like Docker upgrades simply won't happen (https://github.com/coreos/bugs/issues/2624#issuecomment-550111416). EoL hasn't been announced, but it sure feels like that what this is (watch the mailing list if you're interested in this).

Regarding my above questions: cgroupfs was chosen as cgroup driver for docker for backward compatibility. Changing it _should_ be possible but doesn't seem like there is much information out there on how to do this. At this point, it seems that if you require deeper customization of your nodes then it's prudent to consider an alternative operating system.
