### ISSUE TITLE
Link to generate-self-signed-certificates.html is invalid in coreos etcd TLS docs

### ISSUE THREAD

**Issue by spkane** [coreos/bugs#1438]
# Issue Report
## Bug

This link is invalid:

https://coreos.com/etcd/docs/os/generate-self-signed-certificates.html

It is listed on this web page:

https://coreos.com/etcd/docs/latest/tls-etcd-clients.html

**Comment by robszumski** [comment]
Thanks for reporting, this is a known bug that has to do with relative links in the source not being rewritten correctly when you traverse projects. Working on a fix!

**Comment by crawford** [comment]
This was fixed some time ago.
