### ISSUE TITLE
wget is not functional for root user via login shell (undefined symbol: SSLv2_client_method) (Stable 1010.5.0)

### ISSUE THREAD

**Issue by spkane** [coreos/bugs#1440]
# Issue Report #

## Bug ##

root's default environment is not sufficient to run wget. It looks like it is unable to find the proper SSL libraries.

```
$ sudo su -

# wget
wget: symbol lookup error: wget: undefined symbol: SSLv2_client_method

# exit
logout

$ sudo wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

### CoreOS Version ###
```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1010.5.0
VERSION_ID=1010.5.0
BUILD_ID=2016-05-26-2225
PRETTY_NAME="CoreOS 1010.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Environment ###

Dell R420

### Expected Behavior ###

```
$ sudo su -

# wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

# exit
logout

$ sudo wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

### Actual Behavior ###

```
$ sudo su -

# wget
wget: symbol lookup error: wget: undefined symbol: SSLv2_client_method

# exit
logout

$ sudo wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

### Reproduction Steps ###

1. Login as core
1. ```sudo su -```
1. ```wget```

**Comment by spkane** [comment]
Amoung other things this breaks the coreos-install script if you ```sudo su -``` before running the script, instead of simply running ```sudo coreos-install ...```

**Comment by luhkevin** [comment]
`wget` is failing for me even as a non-root user. I've tried it on:
```
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=766.5.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 766.5.0"
ID=ami
VERSION_ID=0.0.5
NAME="Amazon EC2"
HOME_URL="http://aws.amazon.com/ec2/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
NAME=CoreOS
ID=coreos
VERSION=766.5.0
VERSION_ID=766.5.0
BUILD_ID=
PRETTY_NAME="CoreOS 766.5.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

and 

```
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=1068.6.0
DISTRIB_CODENAME="MoreOS"
DISTRIB_DESCRIPTION="CoreOS 1068.6.0 (MoreOS)"
ID=ami
VERSION_ID=0.0.6
NAME="Amazon EC2"
HOME_URL="http://aws.amazon.com/ec2/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
NAME=CoreOS
ID=coreos
VERSION=1068.6.0
VERSION_ID=1068.6.0
BUILD_ID=2016-07-12-1826
PRETTY_NAME="CoreOS 1068.6.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

What's the deal? Why is `wget` broken?

**Comment by spkane** [comment]
@luhkevin Are you also using ```sudo su -``` ? I'm assuming that the core issue here is environmental. And only the core user's environment variables are not setup properly for wget to find it's dynamic libraries.

**Comment by luhkevin** [comment]
Yeah, I was using coreos with mesosphere installed, which fiddles with the env, so please disregard my comment up there.

**Comment by vcaputo** [comment]
I am not seeing this in my attempts to reproduce it.  There's nothing special about the environment variables in coreos for any of these users.

@spkane Can you post the output of the `env` command run from the shell you can't run wget from? Maybe you have something unexpectedly setting LD_LIBRARY_PATH?

**Comment by spkane** [comment]
@vcaputo Yes, I''l try and reproduce it and give you the ENV. It is interesting that @luhkevin mentioned mesosphere, as we are also using CoreOS for mesosphere (DC/OS), however, as I recall this was happening before I'd done anything beyond PXE booting CoreOS.

**Comment by spkane** [comment]
@vcaputo This seems to be fixed in the current stable release.
