### ISSUE TITLE
Ignition does not use field present it go 1.6

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/bugs#1442]
In internal/util/http.go the httpClient uses nearly all the DefaultTransport options, except Proxy (not used) and ExpectContinueTimeout which is not available in go 1.5.

ExpectContinueTimeout should be re-added once the build toolchain supports go 1.6

**Comment by crawford** [comment]
This timeout would be unused by Ignition since we never send requests which expect a `100-continue`.
