### ISSUE TITLE
OEM open-vm-tools links against system libraries (e.g. libprocps)

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1447]
```
INFO    build_packages: Checking build root
INFO    build_packages: Checking /build/amd64-usr
app-emulation/open-vm-tools-9.10.0-r1 is missing libraries:
        x86_64: libprocps.so.3
WARNING build_packages: test_image_content: Failed dependency check
WARNING build_packages: This may be the result of having a long-lived SDK with binary
WARNING build_packages: packages that predate portage 2.2.18. If this is the case try:
```

This SDK is a couple of days old. I'm not sure if this missing library will prevent open-vm-tools from running properly, but it doesn't seem good that it is missing.

**Comment by mischief** [comment]
Afaik a @preserved-rebuild will fix it.

**Comment by marineam** [comment]
I fixed this a long while ago by rolling back procps, masking newer versions. First stage of fixing this properly is some new upgradable or containerized OEM scheme. Second we either need a way to migrate existing systems or wait until old systems are phased out. Watching the oemversion data in the update service should help provide this info.
