### ISSUE TITLE
Trailing whitespaces in hostname -a and -i output

### ISSUE THREAD

**Issue by efeller** [coreos/bugs#1452]
# Issue Report #

## Bug ##

The hostname command adds trailing whitespaces to the output of "-a" and "-i" flags. This makes it annoying to use in bash scripts which call $(hostname -a) and/or $(hostname -i).

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=835.13.0
VERSION_ID=835.13.0
BUILD_ID=
PRETTY_NAME="CoreOS 835.13.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Expected Behavior ###

No trailing whitespaces.

### Actual Behavior ###

Trailing whitespaces.

### Reproduction Steps ###

$ hostname -a > out1
$ hostname -i > out2

Check content of out1 and out2 for trailing whitespaces.

**Comment by crawford** [comment]
This is because `hostname -i` and `hostname -a` print lists of addresses and names, space-delimited. Interestingly, on my machine `hostname -i` only gives me the IPv6 address, but within toolbox I get both IPv6 and IPv4.

If you just want the first address in the list, you'll want to use `hostname -i | cut -d' ' -f1`.

**Comment by efeller** [comment]
@crawford It looks like different hostname implementations exist. On my Ubuntu 14.04.4 LTS machine, everything is also printed space-delimited. However, no trailing whitespace exist. The original hostname implementation (https://github.com/ecki/net-tools/blob/master/hostname.c) is not handling the special case to use printf("%s", addr) for the last array element and not printf("%s ", addr); (Line 189).

Was wondering if we could have the CoreOS version patched to take care of this.

**Comment by efeller** [comment]
@crawford I have recently got a patch merged into net-tools that fixes the trailing whitespace bug. The latest code can be found at https://sourceforge.net/p/net-tools/code/ci/master/tree/. I guess this issue can be closed now as you guys are using the net-tools from SourceForge.

**Comment by crawford** [comment]
@efeller cool, we'll bump to that version once it is released. I'm going to close this one out.

**Comment by Frosty939** [comment]
this still happens, so im guessing it was never fixed?

`net-tools is already the newest version (1.60+git20161116.90da8a0-1ubuntu1).

root@scr18:/home/norm# uname -a
Linux scr18 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by bgilbert** [comment]
@frosty939 This issue tracker is for CoreOS Container Linux.  You appear to be running Ubuntu.

**Comment by frosty939** [comment]
@bgilbert oh crap. you are right

my apologies
