### ISSUE TITLE
Ignition: Support retry on HTTP status code 202 when fetching remote configs

### ISSUE THREAD

**Issue by colhom** [coreos/bugs#1458]
If HTTP status `202 - Accepted` is received when fetching a remote config URL, Ignition should retry with a sane back-off strategy. 

How long ignition will tolerate receiving 202's before failing to boot should be configurable, and not default to infinity. My suggestion is 15 minutes.

\cc @crawford

**Comment by crawford** [comment]
Did we decide against doing this?

**Comment by colhom** [comment]
Yeah, @dghubble talked me out of this.
