### ISSUE TITLE
PS1 prompt in 1109.1.0 has no colors.

### ISSUE THREAD

**Issue by monder** [coreos/bugs#1464]
# Issue Report #

## Bug ##

PS1 prompt is not colored :(

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1109.1.0
VERSION_ID=1109.1.0
BUILD_ID=2016-07-14-2047
PRETTY_NAME="CoreOS 1109.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

AWS `(ami-84b6d7f7)`

### Expected Behavior ###
![screen shot 2016-07-16 at 16 33 02](https://cloud.githubusercontent.com/assets/232147/16895100/07a34b40-4b73-11e6-9aca-a86aeb98c337.png)
`PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\]'`
### Actual Behavior ###

![screen shot 2016-07-16 at 16 24 20](https://cloud.githubusercontent.com/assets/232147/16895039/d92341f4-4b71-11e6-8e2e-4e595c8d80c9.png)
`PS1='\u@\h \w \$ '`

### Other Information ###

[It seems](http://git.savannah.gnu.org/cgit/coreutils.git/tree/NEWS?id=68f73f23866d6137e9c8d88d86073b33588d7b56#n91) that `dircolors --print-database` now outputs `TERM`s as:
```
...
TERM st
TERM st-256color
TERM terminator
TERM tmux*
TERM vt100
TERM xterm*
# Below are the color init strings for the basic file types. A color init
...
```
whereas on previous versions it was:
```
...
TERM screen.rxvt
TERM screen.linux
TERM st
TERM st-256color
TERM terminator
TERM vt100
TERM xterm
TERM xterm-16color
TERM xterm-256color
TERM xterm-88color
TERM xterm-color
TERM xterm-debian
# Below are the color init strings for the basic file types. A color init
...
```

And https://github.com/coreos/coreos-overlay/blob/9fe28e3aef7cc51044cdd333f314d7908c651376/app-shells/bash/files/bashrc#L55 doesn't match.

**Comment by betawaffle** [comment]
I've got the same problem!
