### ISSUE TITLE
sssd account restrictions are not enforced

### ISSUE THREAD

**Issue by ailin-nemui** [coreos/bugs#1469]
# Issue Report #

## Bug ##

sssd account restrictions are not enforces

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1109.1.0
VERSION_ID=1109.1.0
BUILD_ID=2016-07-14-2047
PRETTY_NAME="CoreOS 1109.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Expected Behavior ###

sssd.conf
```
access_provider = simple
simple_allow_user = Nei
```
out of the sssd domain, only Nei can log in

### Actual Behavior ###

anyone can log in

### Other Information ###

must be fixed in pam.d/system-auth

**Comment by ailin-nemui** [comment]
the following config seems to have the desired effect, but since I'm not familiar with gentoo/coreos' pam stack I'd rather you double check before opening some undesired holes :-)

```
account		requisite	pam_unix.so
account		required	pam_sss.so ignore_unknown_user
account		optional	pam_permit.so
```
especially that pam_permit there irks me but was present in the original version. for reference here are some other popular distro solutions:

```
account	[success=1 new_authtok_reqd=done default=ignore]	pam_unix.so 
account	requisite			pam_deny.so
account	required			pam_permit.so
account	[default=bad success=ok user_unknown=ignore]	pam_sss.so
```

```
account	requisite	pam_unix.so
account	sufficient	pam_localuser.so 
account	required	pam_sss.so
```

**Comment by mjg59** [comment]
@ailin-nemui Can I just check why you went with a requisite for pam_unix? Is this just to ensure that local users can always log in, even if their account name is blacklisted in sssd?

**Comment by mjg59** [comment]
@ailin-nemui Sorry, I'm misremembering what requisite means. What are the desired semantics here?

**Comment by ailin-nemui** [comment]
As outlined in the initial report, the desired semantics is that the account restrictions in sssd are respected.

here is the current (non-enforcing) CoreOS config:
```
account		required	pam_unix.so
account		sufficient	pam_sss.so
account		optional	pam_permit.so
```
you are still using the optional permit scheme here (see e.g. https://coreos.com/blog/security-brief-coreos-linux-alpha-remote-ssh-issue.html) In fact the line optional pam_permit is never required as long as there are other modules on the stack.

that `sufficient` means that it is optional in this case whether pam_sss succeeds or not. In case it succeeds, then it will return immediately from the stack. The stack ends anyway after that, so if it fails, the success value of pam_unix is returned.

I have copied requisite pam_unix from another system config. If pam_unix fails, sss will not be asked and the stack will be failed immediately. Using required here instead would not likely make a difference

**Comment by mjg59** [comment]
Ok cool just wanted to make sure. Thanks!
