### ISSUE TITLE
Move NFS/RPC configs out of /etc

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#147]
There is a variety of things in /etc installed by NFS related packages and iirc they are needed in order for it to work properly. Currently I can see:

```
/etc/exports
/etc/idmapd.conf
/etc/netconfig
/etc/request-key.conf
/etc/request-key.d/id_resolver.conf
```

We need to clean this up and add a note to our documentation about all the random services that need to be enabled to make NFS work, this has tripped up users in the past.

**Comment by strangemonad** [comment]
+1 I was just going to file a bug about removing /etc/exports. is there a reason I would ever want to expose an NFS mount from my CoreOS machine directly (rather than from inside a container)?

**Comment by mischief** [comment]
/etc/netconfig has been moved into /usr/share/tirpc. that one is easy because there is not much use in changing it.

what is the use in moving /etc/exports, /etc/idmapd.conf, /etc/request-key.conf, and /etc/request-key.d/id_resolver.conf out of etc? if it was in /usr, it would be ro.

**Comment by marineam** [comment]
/etc/exports wouldn't be "moved", an empty /etc/exports is the same as it not existing. Similar deal with /etc/fstab which we don't bother including but people can create it if needed.

Other files are more of a mixed bag. iirc things break if they are not there but often don't need to be modified. Either the tools using them need to look in both /usr and /etc like systemd and others do these days or we need to place defaults in /usr and create symlinks at boot-time if they are missing. Then if a user does need to make modifications they can replace the symlink with a regular file.

For reference `equery-amd64-usr belongs /etc/request-key.conf` and similar will report what package placed the file there.

**Comment by ForbiddenEra** [comment]
Would be very nice for clear documentation on enabling nfs

**Comment by mischief** [comment]
with coreos/bugs#1130 coreos/bugs#1132 coreos/bugs#1138 coreos/bugs#1141 this is done. nfs still needs testing to ensure it works, though.

**Comment by mischief** [comment]
https://github.com/coreos/mantle/blob/master/cmd/kola/nfs.go has a basic test. closing this.

**Comment by malcolmm83** [comment]
I'd like to use idmapd on CoreOS.  What do I have to do to set the domain?  (normally I would just edit /etc/idmapd.conf).  Also, nfs-idmapd had a dependency on nfs-server (why, I don't know) which won't start because /etc/exports is missing.  Sorry to post here, but it's the only reference to this I could find anywhere.
