### ISSUE TITLE
sss_ssh_authorizedkeys helper missing

### ISSUE THREAD

**Issue by ailin-nemui** [coreos/bugs#1470]
# Issue Report #

## Feature Request ##

consider shipping sss_ssh_authorizedkeys

### Other Information ###

this is a simple identity provider helper that can use ssh public keys stored in IPA/LDAP to log in people. it is configured in sshd_config to replace/supplement the .ssh/authorized_keys file with the keys in ldap

(just to aid confusion, this is not compatible with Kerberos as ssh key based log-in cannot issue tickets. it can be used instead of Kerberos on some environments where ssh key based login is used)

**Comment by mjg59** [comment]
https://github.com/coreos/coreos-overlay/pull/2120
