### ISSUE TITLE
Exit with error 139 when running dotnet core (latest) container and MVC web app

### ISSUE THREAD

**Issue by kennyrulez** [coreos/bugs#1476]
# Issue Report #
Running v1068.8.0 mainly for nginx and dotnet core apps. 
randomly, or under simple load, my dotnet core app container crashes with error 139. Dotnet core app stress tested locally, no sign of failures. 
Tried to run the container interactively, no panic from the dotnet core app itself prior to crash. So, it's related to container and coreos.
Reverted to coreos 1010.6.0, no more problems. 

## Bug ##
Container randomly (or under light stress) crashes with error 139.

### CoreOS Version ###
v1068.8.0
```
$ cat /etc/os-release
NAME=CoreOS
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?
Coreos virtualized on vmware esxi-6.0.0-2015092001-standard
HW: 4x E31245 @ 3.30GHz, 16Gb Ram

### Expected Behavior ###
Run

### Actual Behavior ###
Random Crashes

### Reproduction Steps ###

  1. Have coreos v1068.8.0
  2. Run a dotnet core MVC app using "FROM microsoft/dotnet:latest"

**Comment by dm0-** [comment]
Do you have any error messages or logs to go on?  A return code of 139 could be a segfault anywhere.

I was able to get dotnet to segfault myself, but I have no way of knowing if it's the problem you're seeing.  I believe what I saw was related to dotnet/dotnet-docker#61, which apparently has a fix that has not yet made it into the docker image.  Until they update the docker image, you could try building the fix (dotnet/coreclr#6027) locally.

**Comment by kennyrulez** [comment]
Hello Daniel and thanks for the answer.
The app is published as compiled, so the dotnet bits just run the app, no extra work (like dotnet restore).
Just to be sure, I stress tested the app with thousand of concurrent connections locally, in order to verify if somehow fails. No crashes at all.

So I published the app with full log (debug level) enabled and interactive mode. No sign of error during execution, just random error 139 from docker, and not the app itself.

Fun part: the same bits are actually running on coreos 1010.6.0 and even a stress test of 1 thousand connection cannot strike the app down. (And I'm actually impressed how good coreos handles these numbers...)

So, I still think it's related to some changes made between 1010.6.0 and 1068.8.0, probably as dotnet/coreclr#6027 states, because of the kernel (docker is the same on both coreos releases).
Unfortunately, the latest build is 25 days old so I need to wait for some work by Microsoft to definitively address this issues to them.

Is there any coreos log I can post to you to aknowledge problems related to docker/coreos and not the container itself?

Thanks,
Valerio

**Comment by dm0-** [comment]
You are correct that the bug fix says it was occurring after the kernel's 4.6 release.  Since 1010.6.0 is on 4.5.7, and 1068.8.0 is on 4.6.3, that would match up with the behavior you are seeing.

There could be some logging from this particular error in `dmesg`, to further suggest it is the same error.  Can you check it for messages around the time of the crash?  Maybe lines containing "general protection".

**Comment by kennyrulez** [comment]
Hello David (and I'm really sorry to have called you Daniel before),

I tried on a test environment and I can reproduce the error. DMESG return a protection failure, and it is related to registry entries referenced in the bug 6027 you pointed to me.

I'll wait for a .net fix prior to update to the latest versione.

Thank you for your precious support.

Valerio
