### ISSUE TITLE
IPv6 does not work after update to 1068.8.0: "Could not set NDisc route or address: Invalid argument"

### ISSUE THREAD

**Issue by SEAPUNK** [coreos/bugs#1478]
IPv6 no longer works (or maybe the update caused it to start using it, which in turn makes it fail?), causing the system's network to be up for a little bit, to then be turned completely off on every boot. Disabling it manually by writing `net.ipv6.conf.all.disable_ipv6 = 1` to `/etc/sysctl.d/10-disable-ipv6.conf` fixes the issue.
### CoreOS Version

```
NAME=CoreOS
ID=coreos
VERSION=1068.8.0
VERSION_ID=1068.8.0
BUILD_ID=2016-07-18-0616
PRETTY_NAME="CoreOS 1068.8.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Environment

A SoYouStart server, E5-SAT-1-32. http://www.soyoustart.com/us/offers/e5-sat-1-32.xml
### Expected Behavior

Before the update (last known working configuration):

```
$ journalctl --boot -8 -u systemd-networkd
Jun 30 22:15:54 localhost systemd[1]: Starting Network Service...
Jun 30 22:15:55 localhost systemd-networkd[746]: Enumeration completed
Jun 30 22:15:55 localhost systemd-networkd[746]: lo: Configured
Jun 30 22:15:59 localhost systemd-networkd[746]: eno1: Gained carrier
Jun 30 22:16:02 localhost systemd-networkd[746]: eno1: DHCPv4 address xxx.xxx.xxx.xxx/xx via xxx.xxx.xxx.xxx
Jun 30 22:16:02 localhost systemd-networkd[746]: eno1: Configured
```

After disabling IPv6 (first working configuration):

```
$ journalctl --boot -u systemd-networkd
Jul 21 13:16:43 localhost systemd[1]: Starting Network Service...
Jul 21 13:16:43 localhost systemd-networkd[815]: Enumeration completed
Jul 21 13:16:43 localhost systemd[1]: Started Network Service.
Jul 21 13:16:43 localhost systemd-networkd[815]: lo: Removing non-existent address: ::1/128 (valid forever)
Jul 21 13:16:44 localhost systemd-networkd[815]: lo: Configured
Jul 21 13:16:47 localhost systemd-networkd[815]: eno1: Gained carrier
Jul 21 13:16:49 localhost systemd-networkd[815]: eno1: DHCPv4 address xxx.xxx.xxx.xxx/xx via xxx.xxx.xxx.xxx
```
### Actual Behavior

The boots between (I could not SSH into the server, I eventually found these logs while having the server booted into a recovery environment):

```
$ journalctl --boot -1 -u systemd-networkd
Jul 21 13:03:25 localhost systemd[1]: Starting Network Service...
Jul 21 13:03:25 localhost systemd-networkd[822]: Enumeration completed
Jul 21 13:03:25 localhost systemd[1]: Started Network Service.
Jul 21 13:03:26 localhost systemd-networkd[822]: lo: Configured
Jul 21 13:03:29 localhost systemd-networkd[822]: eno1: Gained carrier
Jul 21 13:03:31 localhost systemd-networkd[822]: eno1: Gained IPv6LL
Jul 21 13:03:31 localhost systemd-networkd[822]: eno1: Could not set NDisc route or address: Invalid argument
Jul 21 13:03:31 localhost systemd-networkd[822]: eno1: Failed
```
### Reproduction Steps
1. Be on the stable channel
2. Update to 1068.8.0
3. ???

**Comment by ferdinandhuebner** [comment]
Same problem here on an OVH server. Could be related to systemd/systemd#2228

Networkd acquires a DHCPv4 lease but fails to handle IPv6 RA. As a consequence, the DHCPv4 lease is never renewed. Once the DHCPv4 lease expires, the IPv4 is lost and the host unreachable. 

On soyoustart and OVH, the lease is valid for 10 minutes. 
I set `IPv6AcceptRouterAdvertisements=false` for now. 

Debug logging from systemd-networkd:
```
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Link 2 added
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: udev initialized link
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Saved original MTU: 1500
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Adding address: xxxx::xxxx:xxxx:xxxx:xxxx/64 (valid forever)
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Gained IPv6LL
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Adding address: xxx.xxx.xxx.xxx/24 (valid for 2min 4s)
Jul 23 22:39:40 localhost systemd-networkd[5144]: NDisc CLIENT: Sent Router Solicitation
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Link state is up-to-date
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: found matching network '/usr/lib64/systemd/network/yy-pxe.network'
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Acquiring DHCPv4 lease
Jul 23 22:39:40 localhost systemd-networkd[5144]: DHCP CLIENT (0x4e0e0acc): STARTED on ifindex 2
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Acquiring DHCPv6 lease
Jul 23 22:39:40 localhost systemd-networkd[5144]: DHCPv6 CLIENT: Started in Information request mode
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Discovering IPv6 routers
Jul 23 22:39:40 localhost systemd-networkd[5144]: NDisc CLIENT: Start Router Solicitation
Jul 23 22:39:40 localhost systemd-networkd[5144]: DHCPv6 CLIENT: Sent INFORMATION-REQUEST
Jul 23 22:39:40 localhost systemd-networkd[5144]: DHCPv6 CLIENT: Next retransmission in 1s
Jul 23 22:39:40 localhost systemd-networkd[5144]: DHCP CLIENT (0x4e0e0acc): DISCOVER
Jul 23 22:39:40 localhost systemd-networkd[5144]: NDisc CLIENT: Sent Router Solicitation
Jul 23 22:39:40 localhost systemd-networkd[5144]: NDisc CLIENT: Received Router Advertisement: flags none preference medium lifetime 1800 sec
Jul 23 22:39:40 localhost systemd-networkd[5144]: NDisc CLIENT: Router Advertisement link MTU 1500 using 1500
Jul 23 22:39:40 localhost systemd-networkd[5144]: NDisc CLIENT: New prefix xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/56 lifetime 2592000 expires in 4w 2d
Jul 23 22:39:40 localhost systemd-networkd[5144]: NDisc CLIENT: Received Router Advertisement: flags none preference medium lifetime 1800 sec
Jul 23 22:39:40 localhost systemd-networkd[5144]: NDisc CLIENT: Router Advertisement link MTU 1500 using 1500
Jul 23 22:39:40 localhost systemd-networkd[5144]: NDisc CLIENT: New prefix xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/56 lifetime 2592000 expires in 4w 2d
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Could not set NDisc route or address: Invalid argument
Jul 23 22:39:40 localhost systemd-networkd[5144]: eno1: Failed
```

**Comment by vcaputo** [comment]
Also potentially related:
https://github.com/systemd/systemd/issues/3879
https://github.com/systemd/systemd/issues/2365

**Comment by dm0-** [comment]
Does this issue appear on any platforms other than on soyoustart.com ?  I don't see it in my testing.  Can someone with a soyoustart.com CoreOS system run the following commands and upload the resulting dump file somewhere, or e-mail it to me directly?  (Feel free to apply more filtering if you think sensitive information will be captured.)

    sudo toolbox
    dnf -y install tcpdump  # inside the toolbox
    tcpdump -i any -w /media/root/home/core/dump.pcap  # inside the toolbox
    # switch to another console
    sudo systemctl restart systemd-networkd  # outside the toolbox, on the host

Then you can `Ctrl+C` the `tcpdump` command, and save the `dump.pcap` file in the `core` user's home directory.  Also, please verify that the error appears at the end of `journalctl -u systemd-networkd` to ensure the problem was captured.

**Comment by SEAPUNK** [comment]
@dm0- I can try, but note that I connect to the system via SSH: If the network goes down, I will need to reboot the server into a recovery console.

Is there a way I can undo the `net.ipv6.conf.all.disable_ipv6 = 1` workaround I have without rebooting? I cannot access the server when it reboots under the faulty network configuration.

**Comment by dm0-** [comment]
You should be able to echo `0` into `/proc/sys/net/ipv6/conf/all/disable_ipv6` to toggle the setting at runtime.  I am not certain if setting the kernel module parameter affects that.

I am not familiar with this hosting provider, but if they provide an option to configure multiple network interfaces, perhaps you could set `IPv6AcceptRA=no` on one and use that interface for your SSH sessions, while running `tcpdump` on the other.

**Comment by SEAPUNK** [comment]
Alright. I'll try to test it out later tonight. Is there any email in specific you want me to mail you the results to, or...?

**Comment by dm0-** [comment]
You can send it to my [CoreOS address](mailto:david.michael@coreos.com).  (In case GitHub eats e-mail addresses, you can get it from any git commits I've made lately.)

**Comment by SEAPUNK** [comment]
Thank you! I'll definitely do that.

**Comment by crawford** [comment]
We have been unable to reproduce this failure. @SEAPUNK or @ferdinandhuebner, can you provide a tcpdump of the event?

**Comment by SEAPUNK** [comment]
Ack, yeah, I forgot to get that tcpdump. I'll try to remember to do it tonight.

**Comment by SEAPUNK** [comment]
Emailed tcpdump pcap file to @dm0-

**Comment by SEAPUNK** [comment]
I got bit by this again today, apparently meaning that the workaround I implemented is no longer working. Any ideas?

**Comment by SEAPUNK** [comment]
I added additional workarounds that seemed to work:

- I modified /etc/dhcpcd.conf adding "noipv6rs" and "noipv6" to the end of the file
- I wrote a new file to /etc/systemd/networkd/: 
```
[Match]
Name=eno*

[Network]
DHCP=ipv4
IPv6AcceptRA=false
```

My server just now went down, but I think it's because someone is physically intervening with my server.

**Comment by SEAPUNK** [comment]
Workarounds didn't work. IPv6 is still failing. Hoping someone knows how to completely disable IPv6.

**Comment by dm0-** [comment]
Sorry, I didn't get through trying to reproduce the issue with the tcpdump output yet, and our priorities are shifted around a bit right now so I might not be able to work on it for a while.  The received router advertisement packets didn't have any obvious errors, from what I saw so far.

I've heard from another OVH user that their IPv6 setup is odd, such as the gateway address being outside the range defined by the assigned IP address and netmask.  If this is true on your system, could you try defining a /128 route to the gateway address to see if that helps?

Also, if none of the other methods of disabling IPv6 are working, you can turn off support at the kernel level with `ipv6.disable=1` on the kernel command-line.  (Write `set linux_append="ipv6.disable=1"` to `/usr/share/oem/grub.cfg` and reboot if you don't have access to the boot loader menu.)

**Comment by SEAPUNK** [comment]
Okay, I think I got it.

I noticed that I've been getting strange errors that I haven't seen before, with the (no longer working) sysctl workaround:

```
Nov 10 16:08:00 localhost systemd-networkd[902]: br-6bb250a2a1a4: IPv6 enabled for interface: Success
Nov 10 16:08:00 localhost systemd-networkd[902]: br-6bb250a2a1a4: Could not append VLANs: Operation not permitted
Nov 10 16:08:00 localhost systemd-networkd[902]: br-6bb250a2a1a4: Failed to assign VLANs to bridge port: Operation not permitted
Nov 10 16:08:00 localhost systemd-networkd[902]: br-6bb250a2a1a4: Could not set bridge vlan: Operation not permitted

[snip]

Nov 10 16:08:28 localhost systemd-udevd[2157]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:28 localhost systemd-udevd[2157]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:28 localhost systemd-udevd[2163]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:28 localhost systemd-udevd[2164]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:28 localhost systemd-udevd[2166]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2162]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2161]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2165]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2157]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2157]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2166]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2165]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2161]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2164]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2163]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.
Nov 10 16:08:29 localhost systemd-udevd[2162]: Process '/usr/lib/udev/scripts/iscsidev.sh' failed with exit code 1.

```

**Comment by crawford** [comment]
Is this issue still preset with the latest versions of Container Linux? We are now shipping systemd 233.

**Comment by SEAPUNK** [comment]
I don't know, I'll have to check. Might be a while before I post my results.

And I contacted OVH about this network issue a while back once, and they confirmed that their DHCP setup is non-standard in some weird way. I don't remember the specifics, however.

**Comment by SEAPUNK** [comment]
I think it's fixed for me. I can't use IPv6 externally (which might be my own blunder), but at least it doesn't take the whole network config down with it. That NDisc error doesn't show up anymore, either.

journalctl logs when failing:

```
Nov 10 05:01:10 localhost systemd-networkd[1330]: eno1: IPv6 enabled for interface: Success
Nov 10 05:01:14 localhost systemd-networkd[1330]: eno1: Gained carrier
Nov 10 05:01:15 localhost systemd-networkd[1330]: eno1: DHCPv4 address xxx.xxx.xxx.xxx/24 via xxx.xxx.xxx.xxx
Nov 10 05:01:15 localhost systemd-networkd[1330]: eno1: Gained IPv6LL
Nov 10 05:01:17 localhost systemd-networkd[1330]: eno1: Could not set NDisc route or address: Invalid argument
Nov 10 05:01:17 localhost systemd-networkd[1330]: eno1: Failed
```

journalctl logs with ipv6 disabled:

```
Apr 06 03:01:28 localhost systemd-networkd[923]: eno1: Cannot disable IPv6 for interface eno1: No such file or directory
Apr 06 03:01:32 localhost systemd-networkd[923]: eno1: Gained carrier
Apr 06 03:01:34 localhost systemd-networkd[923]: eno1: DHCPv4 address xxx.xxx.xxx.xxx/24 via xxx.xxx.xxx.xxx
Apr 06 03:01:34 localhost systemd-networkd[923]: eno1: Configured
```

journalctl logs now (ipv6 disable removed):

```
May 20 23:24:28 localhost systemd-networkd[747]: eno1: IPv6 successfully enabled
May 20 23:24:32 localhost systemd-networkd[747]: eno1: Gained carrier
May 20 23:24:32 localhost systemd-networkd[747]: eno1: DHCPv4 address xxx.xxx.xxx.xxx/24 via xxx.xxx.xxx.xxx
May 20 23:24:33 localhost systemd-networkd[747]: eno1: Gained IPv6LL
May 20 23:24:46 localhost systemd-networkd[747]: eno1: Configured
```
