### ISSUE TITLE
Upgrade google-compute-daemon

### ISSUE THREAD

**Issue by lucmult** [coreos/bugs#1481]
# Issue Report #

GCE instances running with outdated google-compute-daemon.

SSH and sudo on the machine still work, though. But the tools are outdated. 
Related issue: https://github.com/coreos/bugs/issues/1468

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1109.1.0
VERSION_ID=1109.1.0
BUILD_ID=2016-07-14-2047
PRETTY_NAME="CoreOS 1109.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

### Reproduction Steps ###

```
$ gcloud   compute instances create  instance-coreos-stable --image-family coreos-stable --image-project coreos-cloud 
$ gcloud   compute instances create  instance-coreos-alpha --image-family coreos-alpha --image-project coreos-cloud 

$ gcloud compute ssh instance-coreos-alpha

$ sudo journalctl -xe
...
Jul 25 06:15:24 instance-coreos4.c.luck-cases.internal accounts-from-metadata[1605]: INFO Did not grant admin access to lucmult. /etc/sudoers not found.
...

## This "accounts.py" doesn't exist any longer on latest: 
## https://github.com/GoogleCloudPlatform/compute-image-packages/tree/master/google_compute_engine
$ ls -lah /usr/share/oem/google-compute-daemon/accounts.py 
-rw-r--r--. 1 root root 15K Jul 14 20:24 /usr/share/oem/google-compute-daemon/accounts.py
``` 

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?
GCE

**Comment by crawford** [comment]
Unfortunately, this isn't something we can fix yet. CoreOS ships these tools in the OEM partition which does not update. We are working to move all of these tools into rkt images so that we can automatically update them. Once this work is done, machines will need to be reprovisioned to pick up the changes. After that, they should remain up-to-date automatically.

**Comment by cmoad** [comment]
@crawford I reported #1468. Based on your explanation, I understand that we cannot update our existing machines. However, can google-compute-daemon be updated in the next stable CoreOS release so we can reprovision our machines?

**Comment by bsphere** [comment]
@crawford is it possible to do this update manually? I don't like the idea of re-provisioning etcd servers...
