### ISSUE TITLE
cloud-config doesn't accept ssh keys with size 4096 bits

### ISSUE THREAD

**Issue by gbialas** [coreos/bugs#1487]
# Issue Report #
When I have booted coreos with cloud-config containig ssh key with size 4096 bits, user-configvirtfs (and underlaying coreos-cloudinit also, when run manually) couldn't parse it. Changing ssh-key to one with size 2096 fixed problem (actually it is a workaround). Only host name and user from cloud config was added to running configuration. Network configuration, and key wasn't applied. 
### CoreOS Version ###

```
coreos1 ~ # cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=1068.8.0
VERSION_ID=1068.8.0
BUILD_ID=2016-07-18-0616
PRETTY_NAME="CoreOS 1068.8.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###
Coreos on KVM. 
KVM host:

root@compute6:~# uname -a 
Linux compute6 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

root@compute6:~# libvirtd -V
libvirtd (libvirt) 1.3.1
root@compute6:~# kvm -version 
QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.2), Copyright (c) 2003-2008 Fabrice Bellard

### Expected Behavior ###
ssh key added to user core 
### Actual Behavior ###
Part of cloud-config ignored, key wasn't added. 
### Reproduction Steps ###

  1. Install coreos on KVM host in virtual machine according to manual form coreos site. 
  2. Run this vm with cloud-config containing 4096 bit ssh-key  size

**Comment by crawford** [comment]
Can you provide the output of `journalctl -t coreos-cloudinit --no-pager`? Maybe we'll see something interesting in the logs.

**Comment by gbialas** [comment]
Hi, there is not much: 
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Checking availability of "cloud-drive"
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Fetching user-data from datasource of type "cloud-drive"
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Attempting to read from "/media/configvirtfs/openstack/latest/user_data"
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Fetching meta-data from datasource of type "cloud-drive"
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Attempting to read from "/media/configvirtfs/openstack/latest/meta_data.json"
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Parsing user-data as cloud-config
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Merging cloud-config from meta-data and user-data
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Set hostname to coreos-test
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 User 'aqq' exists, ignoring creation-time fields
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Setting 'aqq' user's password
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]: 2016/07/29 08:23:39 Failed to apply cloud-config: Call to update-ssh-keys failed with exit status 255: Adding/updating coreos-cloudinit:
Jul 29 08:23:39 coreos-test coreos-cloudinit[602]:  /home/core/.ssh/authorized_keys.d/coreos-cloudinit.kDsorzXzoT is not a public key file.

Please notice in last line, string "kDsorzXzoT" is random, and it is changing upon each reboot or execution of coreos-cloudinit --from-file /path/to/user_data

**Comment by crawford** [comment]
I was unable to reproduce this with a simplified test case.

```
cat .ssh/id_rsa.pub.4096 | update-ssh-keys -a foo
Adding/updating foo:
4096 SHA256:qmitIxPScWufkNJewHE4lMGe2p+lXzi0CAQSeXoCkwA localhost (RSA)
Updated /home/core/.ssh/authorized_keys
```

Can you verify that your key is valid? There may have been some truncation when the cloud-config was created.

> Please notice in last line, string "kDsorzXzoT" is random, and it is changing upon each reboot or execution of coreos-cloudinit --from-file /path/to/user_data

That's expected. `update-ssh-keys` uses `mktemp` to create an intermediate file which contains the keys.

**Comment by gbialas** [comment]
Hi. 
Key is valid, I am using it connect to bunch of other servers :) 
I found the reason, why key isn't added. It is lack of "==" in the end of 4096 key. 
ssh-key-gen adds "==" to key when it's length is 4096 bits, in case of generating 2048 length key "==" isn't added. In theory "==" isn't mandatory (details can be found on [wiki](https://en.wikipedia.org/wiki/Base64#Padding) ).
For me this closes this case. Hope that some one will find this in case of the same problem. 
Thanks for help!

**Comment by crawford** [comment]
Great! Glad you got it figured out.
