### ISSUE TITLE
arm64-usr coreos_developer_container.bin is unbootable

### ISSUE THREAD

**Issue by mischief** [coreos/bugs#1496]
# Issue Report #
## Bug

coreos_developer_container.bin is unbootable on arm64 because it has the wrong partition UUID.
### CoreOS Version

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.0.0
VERSION_ID=1122.0.0
BUILD_ID=2016-07-27-0735
PRETTY_NAME="CoreOS 1122.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Environment

arm64
### Expected Behavior

nspawn runs coreos container
### Reproduction Steps

```
core@localhost ~ $ sudo systemd-nspawn -q -i coreos_developer_container.bin --share-system                                                                                                                                                     
Failed to identify root partition in disk image
    /home/core/coreos_developer_container.bin
Note that the disk image needs to either contain only a single MBR partition of
type 0x83 that is marked bootable, or a single GPT partition of type 0FC63DAF-8483-4772-8E79-3D69D8477DE4 or follow
    http://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/
to be bootable with systemd-nspawn.
```
### Other Information

disk_layout.json in github.com/coreos/scripts needs to be fixed to handle different UUIDs for the partitions, or a seperate entry for arm64 container needs to be made, or the root partition needs to be set to `0fc63daf-8483-4772-8e79-3d69d8477de4`, the non-architecture specific partition type.

setting the partition type by hand, e.g. with:

```
sgdisk -t 9:0FC63DAF-8483-4772-8E79-3D69D8477DE4 coreos_developer_container.bin
```

makes it bootable.

https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/

**Comment by bgilbert** [comment]
Closing because we're [dropping ARM64 support from Container Linux](https://groups.google.com/d/topic/coreos-user/3Z2S6bKNF5E/discussion).
