### ISSUE TITLE
[toolbox] systemd-nspawn --share-system is deprecated by upstream

### ISSUE THREAD

**Issue by f0** [coreos/bugs#1497]
Hi,

systemd-nspawn --share-system is deprecated upstream 
https://github.com/systemd/systemd/pull/3820#issuecomment-237229765

maybe toolbox can be migrated to rkt fly?

regards f0

**Comment by vcaputo** [comment]
Looks like they're keeping the flag around, just removing it from the documentation.

**Comment by f0** [comment]
@vcaputo  yes, for now if i understand correct...

**Comment by crawford** [comment]
Closing in favor of https://github.com/coreos/bugs/issues/1610.
