### ISSUE TITLE
Docker 1.12

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1501]

**Comment by mischief** [comment]
for this we need go 1.6, and runc bump.

afaict, we also need some changes to our script wrapper and to the docker units. still investigating.

**Comment by mischief** [comment]
it looks like the major blocker for this is runc.

currently, docker 1.12.0 depends on opencontainers/runc@cc29e3dded8e27ba8f65738f40d251c885030a28, but no tag exists for this.

so either we wait for a tag (which seems unlikely to happen soon given the current trend), or we make an ebuild for the untagged opencontainers/runc@cc29e3dded8e27ba8f65738f40d251c885030a28
