### ISSUE TITLE
enable ext4 native encryption

### ISSUE THREAD

**Issue by f0** [coreos/bugs#1502]
with linux 4.1  ext4 supports native encryption, with 4.4 it gains more stable

Please update e2fsprogs to 1.43.1 and enable this Kernel options
CONFIG_EXT4_ENCRYPTION
CONFIG_KEYS

**Comment by f0** [comment]
@crawford  is this merged?

**Comment by crawford** [comment]
This was fixed in https://github.com/coreos/coreos-overlay/pull/2134. Thanks for bugging us. This one slipped through the cracks.
