### ISSUE TITLE
Feature request: Fuze should print the whole path to "unrecognized keys"

### ISSUE THREAD

**Issue by urzds** [coreos/bugs#1504]
### Environment

bare-metal with bootcfg 0.4.0 and CoreOS 1068.8.0
### Desired Feature

It would be nice if Fuze would print the whole path to "unrecognized keys" instead of just the names of the keys.
### Other Information

bootcfg logged "error parsing Ignition config: unrecognized keys: [enable enable command content]". The "enable" key is valid in several places and I cannot spot any place where I am using it in an invalid place. It would be great, if bootcfg could print the whole path (e.g. `systemd/units[1]/dropins[1]/content`) to the invalid key.

See-Also: coreos/coreos-baremetal#308

**Comment by crawford** [comment]
The config transpiler now supports more detailed output. Given this config:

```yaml
storage:
  foobar: hi
```

The transpiler will output the following:

```
warning at line 1, column 2
Config has unrecognized key: foobar

{"ignition":{"version":"2.0.0","config":{}},"storage":{},"systemd":{},"networkd":{},"passwd":{}}
```
