### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by stereoshoots** [coreos/bugs#1506]
# Issue Report #

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

### Reproduction Steps ###

  1. ...
  2. ...

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

**Comment by mischief** [comment]
this looks empty, so i'm closing this. please file another issue if you have a problem.
