### ISSUE TITLE
Setting global env vars that take affect by systemd units?

### ISSUE THREAD

**Issue by asaf** [coreos/bugs#1507]
Hey,

I probably miss something about Systemd here,

I have a systemd file such:

```bash
sudo cat /etc/systemd/system/flanneld.service.d/50-network-config.conf
[Service]
ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
```

Which fails to start due to:
```bash
Aug 09 20:42:30 core-01 etcdctl[1184]: Error:  malformed HTTP response "\x15\x03\x01\x00\x02\x02"
Aug 09 20:42:30 core-01 systemd[1]: flanneld.service: Control process exited, code=exited status=4
```

This fails because `ETCDCTL_***` env vars are missing,

I put the relevant etcdctl config params in `/etc/profile.d/01-etcd.sh`, also tried in `/etc/environment`,

```bash
cat /etc/environment
export ETCDCTL_CA_FILE=/etc/certs/ca.pem
export ETCDCTL_CERT_FILE=/etc/certs/coreos.pem
export ETCDCTL_KEY_FILE=/etc/certs/coreos-key.pem
export ETCDCTL_ENDPOINT=https://127.0.0.1:2379
```

These exported fine in interactive session and works just fine:

```bash
core@core-01 ~ $ etcdctl ls
/coreos.com
```

But seems like these env vars have no effect in systemd units, I also tried to put these vars in `/etc/systemd/system.conf` as a value of the `DefaultEnvironment` field.

Is this a bug ? alternatively, what is the official approach for setting up env vars that should take affect on systemd units globally?

Thanks. 

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1122.0.0
VERSION_ID=1122.0.0
BUILD_ID=2016-07-27-0739
PRETTY_NAME="CoreOS 1122.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Using official vagrant file to raise the VMs

**Comment by omkensey** [comment]
I think you have to explicitly call files with environment variable definitions you want systemd units to use, e.g.:

...
[Service]
EnvironmentFile=-/etc/environment
...

(The dash before the path signifies "go ahead and start if this file is missing" -- otherwise if the file doesn't exist, the unit file would fail to start.)

For an example, check out the unit file for user-cloudinit@.service.

**Comment by crawford** [comment]
There is nothing special about `/etc/environment`. If you service depends on those variables, it will need to source them as @omkensey mentioned. I also tested `DefaultEnvironment` and it worked fine.

Please reopen if you are still having trouble.

**Comment by asaf** [comment]
Yea I know, but this  is crazy, I use some automations (such [CoreOS scripts](https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/generic) to build Kubernetes), these scripts dump systemd files with `etcdctl` calls, all fails just because these env vars are missing,

So really? solution would be to reference a file on every Systemd service?

Thanks for answering @omkensey

**Comment by omkensey** [comment]
That's the way systemd works.  There are three possibilities:

1) Reference environment variables directly in individual unit files (Environment=)
2) Put the variable assignments in a file (like /etc/environment) and reference that file per-unit (EnvironmentFile=)
3) Put the variable assignments in the DefaultEnvironment variable in /etc/systemd/system.conf or a snippet in /etc/systemd/system.conf.d/[some file].

It sounds like #3 is what you want.

For example I create the following files:

/etc/systemd/system.conf.d/test1.conf:

[Manager]
DefaultEnvironment=TEST1=test1 TEST2=test2

/etc/systemd/system.conf.d/test2.conf:

DefaultEnvironment="TEST3=test3"

When I had a test unit output its environment variables, I saw this in the output:

TEST1=test1
TEST2=test2
TEST3=test3

Note that when you write a new snippet to a file in /etc/systemd/system.conf.d, you need to do a daemon-reload for it to take effect.

**Comment by crawford** [comment]
> You tested DefaultEnvironment and it worked without sourcing env vars per systemd unit?

Yes.

**Comment by asaf** [comment]
@omkensey Thanks for the detailed answer,

@crawford Probably I've done some mistake, I'll re-try, will re-open if something goes wrong,

Thanks folks.
