### ISSUE TITLE
9p mount not supported - Could not find request transport: virtio

### ISSUE THREAD

**Issue by BenHall** [coreos/bugs#1508]
When attempting to mount a fileshare via 9p, I get an error saying virtio is not found. Is this supported?

```
/bin/mount -t 9p -o trans=virtio,version=9p2000.L hostshare /tmp/vm-files
mount: wrong fs type, bad option, bad superblock on hostshare,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

When I attempt to navigate to the directory I get the error:
```
# cd /tmp/vm-files
9pnet: Could not find request transport: virtio
```

However the module appears to have been loaded.
```
# lsmod |grep virtio
virtio_blk             20480  5
virtio_pci             24576  0
virtio_ring            20480  2 virtio_blk,virtio_pci
virtio                 16384  2 virtio_blk,virtio_pci
```

Mount includes it in the list:
```
# mount
systemd-1 on /tmp/vm-files type autofs (rw,relatime,fd=23,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=10619)
```

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.0.0
VERSION_ID=1122.0.0
BUILD_ID=2016-07-27-0739
PRETTY_NAME="CoreOS 1122.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by BenHall** [comment]
It looks like `9pnet_virtio` is missing.

```
# lsmod | grep 9p
9p                     49152  0
9pnet                  69632  1 9p
fscache                57344  1 9p
```

**Comment by ailin-nemui** [comment]
I wouldn't advise to using 9p its performance is horrible

**Comment by BenHall** [comment]
In this scenario the performance isn't critical. Are there alternatives to 9p? The aim is to mount a volume provided as a QEMU share...

**Comment by ailin-nemui** [comment]
why not use nfs

**Comment by BenHall** [comment]
According too https://nixos.org/wiki/QEMU_guest_with_networking_and_virtfs

"VirtFS (Plan 9 folder sharing over Virtio - I/O virtualization framework) allows you to mount folders from the host system on the guest system, this is significantly faster than folder sharing over the network e.g. NFS."

**Comment by ailin-nemui** [comment]
I suggest you run your own benchmarks. maybe the situation has improved since I last checked although that would surprise me
