### ISSUE TITLE
CoreOS Stable AMI's listed on the latest page seem to be deregistered/unavailable

### ISSUE THREAD

**Issue by DeviaVir** [coreos/bugs#1509]
# Issue Report #

## Bug ##
Try a few https://coreos.com/os/docs/latest/booting-on-ec2.html _stable_ AMI's listed on this page, and notice that most of them are not working when trying them out on AWS. (at least **us-west-1 and us-west-2** as by my tests)

<img width="756" alt="screen shot 2016-08-10 at 10 53 45" src="https://cloud.githubusercontent.com/assets/777823/17547678/bdca2668-5ee8-11e6-8725-f695ac05b977.png">
#
<img width="713" alt="screen shot 2016-08-10 at 10 45 37" src="https://cloud.githubusercontent.com/assets/777823/17547556/246e1d62-5ee8-11e6-9652-9de72a0ba1e0.png">

### Expected Behavior ###
All Stable AMIs to be available.

### Actual Behavior ###
Some or all Stable AMIs do not work, blocking deploys on automated systems relying on the correctness of this data.

### Reproduction Steps ###

  1. select AMI on https://coreos.com/os/docs/latest/booting-on-ec2.html (stable channel)
  2. click on the AMI
  3. optionally log in to AWS
  4. observe the AMI error

### Other Information ###

Seemed like a disruptive issue, so also tweeted here https://twitter.com/DeviaVir/status/763295372815065088

**Comment by wellsie** [comment]
eu-central-1 stable is affected too

![screen shot 2016-08-10 at 6 56 11 am](https://cloud.githubusercontent.com/assets/5160593/17556303/c1eab134-5ec7-11e6-90e1-d526d27dee13.png)

**Comment by philips** [comment]
One of our release scripts broke and we ended up merging bad metadata to coreos.com. I am rolling back to 1068.8.0 on the site and then we will roll-forward with 1068.9.0 again once we fix the issue. I expect this to be resolved on coreos.com in the next 10 minutes once the site clears caches.

**Comment by crawford** [comment]
It appears as though the metadata was correct, but the images were not marked public. They are now public and we'll update the site again. Sorry for the mix-up.

**Comment by DeviaVir** [comment]
@crawford thanks for your quick action on this one! :+1:
