### ISSUE TITLE
release.core-os.net is really slow ( from Germany )

### ISSUE THREAD

**Issue by sweber83** [coreos/bugs#1510]
Sometimes release.core-os.net is really slow, like 2kb/s.
At the moment I'm downloading the Vagrant Box for 1068.9.0 and my eta ~ 6h.
Would be nice to know if others suffer from the same problem.
The same happened some weeks ago, but then on other days it was really fast.

**Comment by crawford** [comment]
`release.core-os.net` is backed by CloudFlare. Are you able to verify if you are downloading from a datacenter near your current location?

**Comment by sweber83** [comment]
I just did a nslookup + geo location lookup and the ip ( 104.16.20.26 ) is in the US.
But at the moment the download speed is totally fine.
I'll do a lookup again if I have trouble with the download speed.

**Comment by crawford** [comment]
Closing for now.

**Comment by davidsanusi** [comment]
I am experiencing this issue currently. Download from https://stable.release.core-os.net is really slow. This is the exact url I'm trying to download https://stable.release.core-os.net/amd64-usr/1185.3.0/coreos_production_vagrant.box. I can barely hit 50KB/s

**Comment by wmark** [comment]
@davidsanusi Do you experience this from Germany?

**Comment by davidsanusi** [comment]
@wmark No. Experiencing this from Lagos, Nigeria

**Comment by crawford** [comment]
@davidsanusi we have a CDN in front of the actual buckets which host the files. Can you try downloading directly from the bucket?

https://storage.googleapis.com/coreos-stable/amd64-usr/1185.3.0/coreos_production_vagrant.box
vs
https://stable.release.core-os.net/amd64-usr/1185.3.0/coreos_production_vagrant.box

**Comment by davidsanusi** [comment]
@crawford Downloading from the bucket directly is way much better. Thanks a lot

**Comment by nahmad-vf-ic-pk** [comment]
I was experiencing the same issue today from Pakistan. Downloading directly from the bucket helped me. Thanks @crawford
