### ISSUE TITLE
CoreOS stable 1068.8.0 Systemd 229 - Systemd timers broken

### ISSUE THREAD

**Issue by sweber83** [coreos/bugs#1516]
# Issue Report #

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1068.8.0
VERSION_ID=1068.8.0
BUILD_ID=2016-07-18-0616
PRETTY_NAME="CoreOS 1068.8.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###
Digitalocean VPS

### Expected Behavior ###
The following timer unit should run backup.service everyday @ 10 past 9pm.
```
[Unit]
Description=Run backup.service once every night

[Timer]
OnCalendar=*-*-* 21:10:00

[Install]
WantedBy=multi-user.target
```

### Actual Behavior ###
The timer ran the backup.service for the last time on 31st of July 2016.
```
$ date
```
```
Fri Aug 12 10:25:35 UTC 2016
```
```
$ systemctl list-timers
```
```
NEXT                         LEFT           LAST                         PASSED  UNIT                         ACTIVATES
Sat 2016-08-13 21:10:00 UTC  1 day 10h left n/a                          n/a     backup.timer                 backup.service
```
As you can see the unit should run today at 21:10 but systemd says the next run would be tomorrow, not today.

### Other Information ###
I suspect this issue could be at fault here: https://github.com/systemd/systemd/issues/2682

**Comment by vcaputo** [comment]
@sweber83 thanks for the report, we're backporting the upstream fix to stable.

**Comment by crawford** [comment]
Fixed via Fixed via https://github.com/coreos/systemd/pull/56.
