### ISSUE TITLE
systemd-journald permanently fails from ENOSPC

### ISSUE THREAD

**Issue by vcaputo** [coreos/bugs#1522]
systemd-journald should resume operation once space is made available, this is not the case.

Upstream reported issue https://github.com/systemd/systemd/issues/3968

**Comment by vcaputo** [comment]
Proposed tested fix upstream https://github.com/systemd/systemd/pull/3973

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/systemd/pull/56..

**Comment by vcaputo** [comment]
Follow-up commit was needed to fully fix this, already landed upstream and backport is waiting in https://github.com/coreos/systemd/pull/59

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/systemd/pull/59.
