### ISSUE TITLE
Error getting authority: Error initializing authority

### ISSUE THREAD

**Issue by shenshouer** [coreos/bugs#1524]
# Issue Report #
Error getting authority: Error initializing authority
## Bug ##
# systemctl daemon-reload
Error getting authority: Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Activation of org.freedesktop.PolicyKit1 timed out (g-dbus-error-quark, 20)
Failed to execute operation: Connection timed out
### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1010.6.0
VERSION_ID=1010.6.0
BUILD_ID=2016-06-28-0910
PRETTY_NAME="CoreOS 1010.6.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Run CoreOS direct on bare machine 

### Reproduction Steps ###

  1. ...
  2. ...

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

**Comment by mischief** [comment]
Can you reproduce this with the latest stable 1068.9.0?

**Comment by shenshouer** [comment]
@mischief  sorry! this issue appear in my produce environment. There are many service run on this host. So cann`t upgrade the version of the OS. My temporary solution is `nohup /usr/lib/polkit-1/polkitd &`

**Comment by crawford** [comment]
This looks like an issue with systemd (you are using 225). Stable currently ships 229 and 231 is working it's way down the pipe. If you are still having trouble on a newer version, please re-open.
