### ISSUE TITLE
rkt is being built with a TEXTREL section

### ISSUE THREAD

**Issue by mjg59** [coreos/bugs#1525]
1097 is fine, 1109 is broken.

**Comment by mjg59** [comment]
@glevand This is a result of eb9c5a4b6769d3808bb92b86f212868bbfde9ddf - -nopie is no longer being passed to the build, and we're ending up with this breakage as a result

**Comment by mjg59** [comment]
I'm going to revert that commit for now to unbreak the build

**Comment by mjg59** [comment]
https://github.com/coreos/coreos-overlay/pull/2139

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/2163.
