### ISSUE TITLE
Docker 1.10 and 1.11 break Stats API for Kubernetes

### ISSUE THREAD

**Issue by treed** [coreos/bugs#1526]
# Issue Report #

### CoreOS Version ###

`$ for host in $(imvuasset.pl -f adb-class-kubernetes); do ssh core@$host cat /etc/os-release | grep VERSION=; done | sort | uniq -c | sort -n`

      1 VERSION=1010.3.0
      1 VERSION=1010.4.0
      1 VERSION=1010.6.0
      1 VERSION=1068.6.0
      2 VERSION=1068.8.0
      2 VERSION=1068.9.0
     29 VERSION=899.17.0

(The problem only applies to versions >= 1010.3.0 in this case though, those still on 899.17.0 don't experience this problem.)

### Environment ###

All bare metal:

20x Dell 1950
11x Dell R420
4x SuperMicro 1028R

### Expected Behavior ###

That 'docker stats' and the related stats API return useful information about containers running in our Kubernetes cluster.

### Actual Behavior ###

Those nodes running on more recent versions of CoreOS Stable which have been upgraded to 1.10 or higher fail to provide stats for containers running in Kubernetes pods.

The Docker bug: https://github.com/docker/docker/issues/21848
The Docker fix: https://github.com/docker/docker/commit/86002decd0936fa5d466ba7dcbb3fd1524fd86dd

Unfortunately the fix didn't make it out until 1.12, which seems to still be in the process of being added to CoreOS alpha, and even when it is, it'll be a while before the fix makes its way to stable.

You can see here the output of docker stats across all containers running on a CoreOS machine running version 1068.6.0: 

```
collectd-host                                                                                                          0.00%               5.005 MB / 67.51 GB   0.01%               0 B / 0 B             905.2 kB / 0 B
istatd-agent                                                                                                           0.00%               0 B / 67.51 GB        0.00%               0 B / 0 B             4.907 MB / 0 B
k8s_POD.a0630492_mcrouter-web-1263107726-4e1r8_imvu_d2f45f3e-6405-11e6-b79a-0015c5edce7e_333be248                      0.00%               90.11 kB / 67.51 GB   0.00%               3.111 GB / 3.122 GB   0 B / 0 B
k8s_POD.a0630492_mcrouter-web-1263107726-pi8md_imvu_107f7a21-6405-11e6-b79a-0015c5edce7e_0fe13e7c                      0.00%               2.355 MB / 67.51 GB   0.00%               3.286 GB / 3.3 GB     0 B / 0 B
k8s_POD.a0630492_mcrouter-web-1263107726-r5ond_imvu_d2f3f9a5-6405-11e6-b79a-0015c5edce7e_2a3f612a                      0.00%               0 B / 67.51 GB        0.00%               3.269 GB / 3.268 GB   0 B / 0 B
k8s_POD.a0630492_mcrouter-web-1263107726-tcb30_imvu_d2f51a84-6405-11e6-b79a-0015c5edce7e_afa01375                      0.00%               2.036 MB / 67.51 GB   0.00%               3.456 GB / 3.471 GB   0 B / 0 B
k8s_collectd.cbfdd970_mcrouter-web-1263107726-4e1r8_imvu_d2f45f3e-6405-11e6-b79a-0015c5edce7e_bc10343d                 0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_collectd.cbfdd970_mcrouter-web-1263107726-pi8md_imvu_107f7a21-6405-11e6-b79a-0015c5edce7e_b387f2df                 0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_collectd.cbfdd970_mcrouter-web-1263107726-r5ond_imvu_d2f3f9a5-6405-11e6-b79a-0015c5edce7e_d2e541a3                 0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_collectd.cbfdd970_mcrouter-web-1263107726-tcb30_imvu_d2f51a84-6405-11e6-b79a-0015c5edce7e_d12eb4fb                 0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_docker-to-istatd.8b39fccb_mcrouter-web-1263107726-4e1r8_imvu_d2f45f3e-6405-11e6-b79a-0015c5edce7e_4511a8a7         0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_docker-to-istatd.8b39fccb_mcrouter-web-1263107726-pi8md_imvu_107f7a21-6405-11e6-b79a-0015c5edce7e_15cc01fe         0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_docker-to-istatd.8b39fccb_mcrouter-web-1263107726-r5ond_imvu_d2f3f9a5-6405-11e6-b79a-0015c5edce7e_698157fc         0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_docker-to-istatd.8b39fccb_mcrouter-web-1263107726-tcb30_imvu_d2f51a84-6405-11e6-b79a-0015c5edce7e_fbdef4dd         0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_istatd-container-relay.7c0c07fb_mcrouter-web-1263107726-4e1r8_imvu_d2f45f3e-6405-11e6-b79a-0015c5edce7e_23087d9c   0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_istatd-container-relay.7c0c07fb_mcrouter-web-1263107726-pi8md_imvu_107f7a21-6405-11e6-b79a-0015c5edce7e_150cbc71   0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_istatd-container-relay.7c0c07fb_mcrouter-web-1263107726-r5ond_imvu_d2f3f9a5-6405-11e6-b79a-0015c5edce7e_3a1d5fe9   0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_istatd-container-relay.7c0c07fb_mcrouter-web-1263107726-tcb30_imvu_d2f51a84-6405-11e6-b79a-0015c5edce7e_237a8b52   0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_mcrouter-configurator.6a1418b5_mcrouter-web-1263107726-4e1r8_imvu_d2f45f3e-6405-11e6-b79a-0015c5edce7e_2176bf94    0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_mcrouter-configurator.6a1418b5_mcrouter-web-1263107726-pi8md_imvu_107f7a21-6405-11e6-b79a-0015c5edce7e_3f1ee866    0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_mcrouter-configurator.6a1418b5_mcrouter-web-1263107726-r5ond_imvu_d2f3f9a5-6405-11e6-b79a-0015c5edce7e_e70906bf    0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_mcrouter-configurator.6a1418b5_mcrouter-web-1263107726-tcb30_imvu_d2f51a84-6405-11e6-b79a-0015c5edce7e_4255164c    0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_mcrouter.6dd31aa3_mcrouter-web-1263107726-4e1r8_imvu_d2f45f3e-6405-11e6-b79a-0015c5edce7e_0da9bc0a                 0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_mcrouter.6dd31aa3_mcrouter-web-1263107726-pi8md_imvu_107f7a21-6405-11e6-b79a-0015c5edce7e_df03dc8b                 0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_mcrouter.6dd31aa3_mcrouter-web-1263107726-r5ond_imvu_d2f3f9a5-6405-11e6-b79a-0015c5edce7e_0e54e515                 0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
k8s_mcrouter.6dd31aa3_mcrouter-web-1263107726-tcb30_imvu_d2f51a84-6405-11e6-b79a-0015c5edce7e_6ca5749e                 0.00%               0 B / 0 B             0.00%               0 B / 0 B             0 B / 0 B
kube-proxy                                                                                                             8.59%               219 MB / 67.51 GB     0.32%               0 B / 0 B             45.41 MB / 0 B
kubelet                                                                                                                141.76%             19.81 GB / 67.51 GB   29.34%              0 B / 0 B             29.43 MB / 254 kB
ladvd                                                                                                                  0.00%               16.7 MB / 67.51 GB    0.02%               0 B / 0 B             4.735 MB / 0 B
romantic_wozniak9                                                                                                      0.00%               0 B / 67.51 GB        0.00%               3.088 MB / 3.406 MB   45.06 kB / 208.9 kB
```

Note that for all of the Kubernetes-run pods, only the POD containers show anything but zeroes. (Which is fine and expected for network, but not for CPU/memory)

### Reproduction Steps ###

  1. Run Kubernetes on CoreOS Stable
  2. Run "docker stats" with the id of a container running in a Kubernetes pod

### Other Information ###

I'm honestly a little surprised that this bugfix hasn't already been backported, given CoreOS' focus on Kubernetes, but I suppose it's possible most people don't use the stats API? I just spent some time looking at the CoreOS docker fork and the ebuilds and don't see any fix for this.

Would it be possible to cherrypick that commit for the CoreOS releases containing Docker 1.10 or 1.11 to hold us over until 1.12 makes it through the chain?

**Comment by jsoriano** [comment]
@treed how do you monitor the pods in your cluster?

We are using heapster, that retrieves the stats through the cAdvisor port in the kubelets and we have seen that it doesn't work well with `--exec-opt native.cgroupdriver=systemd`, but it does it with `--exec-opt native.cgroupdriver=cgroupfs`.
For example, with systemd driver, for some dockers `/sys/fs/cgroup/memory/system.slice/docker-<id>/memory.usage_in_bytes` is 0.

I'm also a little surprised of finding these kind of issues between CoreOS stable and kubernetes.

**Comment by treed** [comment]
Using the Docker stats API. We have a lot of custom monitoring here (see https://github.com/imvu-open/istatd in particular), and I already had some code from something else to access stats, so it was pretty trivial to write up something using the API and send it to istatd.

**Comment by stevezau** [comment]
This is also having issues for me as I'm trying to collect the stats and send via graphite to another tool. (Heapstar does not support graphite/statsd/collectd yet which is why i have to use the stats api).

Is there anyway to force an upgrade to 1.12?

**Comment by crawford** [comment]
The Alpha channel currently has 1.12. You can just switch channels and let it upgrade.

**Comment by stevezau** [comment]
@crawford doing that seems to of broken kubernetes.. Haven't really digged into why but i did try from a fresh install..

**Comment by crawford** [comment]
We are going to backport this to 1.11.2 (done in https://github.com/coreos/coreos-overlay/pull/2167).

**Comment by crawford** [comment]
@stevezau uh oh. That's not good. This new version should roll out tomorrow. You should be able to stick with 1.11.2.

**Comment by treed** [comment]
Can we expect that 1.11.2 will hit stable soon, then?

**Comment by crawford** [comment]
@treed 1.10.3 is currently in Stable. I imagine the next Stable release (in about two months) will have 1.11.2 with the mentioned fixes.

**Comment by stensonb** [comment]
any chance we can get a stable release quick than that?  this bug wiped out container monitoring for us...and being on the "stable" channel, that's something we expect to have.

**Comment by crawford** [comment]
@stensonb No, but in the mean time you can move your machines to the Beta channel and test out Docker 1.11.2.
