### ISSUE TITLE
resizing / breaks /dev/disk/by-partlabel/ROOT

### ISSUE THREAD

**Issue by mischief** [coreos/bugs#1527]
using extend-filesystems.service results in /dev/disk/by-partlabel/ROOT going missing. the partition information is also missing from blkid -o -p /dev/vda9.

running partx -u after e.g. cgpt resize/resize2fs seems to fix the partition information and partlabel symlink.

**Comment by vcaputo** [comment]
I'll poke a bit at this...

**Comment by crawford** [comment]
@mischief I heard you uncovered some interesting behavior from `cgpt`.

**Comment by mischief** [comment]
@crawford yes, running `cgpt resize /dev/vda9` (or whatever ROOT is) is what causes the bug. extend-filesystems.service is basically doing that.

**Comment by crawford** [comment]
@dm0- was telling me that `cgpt` wrote a new partlabel to the kernel but didn't persist it to disk, which is why `partx` (which reads the label from the disk) fixes the information.

**Comment by vcaputo** [comment]
ah, I didn't poke at this yet, sounds like dm0 has identified the probable root cause though.  So we've got a cgpt bug to fix here?

**Comment by vcaputo** [comment]
for posterity: this turned out to simply be an off by one error in the cgpt resize code.
