### ISSUE TITLE
cannot find sdnotify-proxy in /usr/libexec

### ISSUE THREAD

**Issue by voith** [coreos/bugs#1528]
# Issue Report #

## Bug ##
cannot find sdnotify-proxy in /usr/libexec. Has coreos stopped shipping sdnotify-proxy?

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.1.0
VERSION_ID=1122.1.0
BUILD_ID=2016-08-11-0252
PRETTY_NAME="CoreOS 1122.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?
cloud provider: Digital Ocean

### Expected Behavior ###
expected to find sdnotify-proxy in /usr/libexec
### Actual Behavior ###
```-bash: /usr/libexec/sdnotify-proxy: No such file or directory ```
### Reproduction Steps ###
```
$ /usr/libexec/sdnotify-proxy
-bash: /usr/libexec/sdnotify-proxy: No such file or directory
$ whereis sdnotify-proxy
sdnotify-proxy:
```

**Comment by styxlab** [comment]
Experience the same issue on bare-metal installations. Due to this bug flanneld cannot start, thus subsequent processes such as docker and kubernetes will fail too.
This is a really sever bug which I expect in alpha but not in beta releases. This issue led me to switch off automatic reboots.

**Comment by vcaputo** [comment]
@voith @styxlab as you can see from the related merges this has been corrected, and was an unintended consequence of flannel-related development moving flannel from docker to rkt.

**Comment by voith** [comment]
@vcaputo When can I expect this fix to be released?

**Comment by voith** [comment]
@vcaputo Also, does `docker 1.11.0+` need `sdnotify-proxy`?  Since `docker 1.11.0+` uses `runC`, I think it should support `sdnotify` out of the box. Please correct me if I'm wrong.

**Comment by vcaputo** [comment]
I don't think docker's using runc makes any difference WRT sdnotify-proxy, the client-server architecture of docker is unchanged AFAIU.

**Comment by vcaputo** [comment]
@voith The change is slated for the next beta, in two weeks.

**Comment by voith** [comment]
@vcaputo Thanks for the reply, I read `The future of systemd and containers` in this [article]  (https://lwn.net/Articles/676831/) and assumed that `sdnotify` would work out of the box. Anyways thanks for clearing my doubt :)
