### ISSUE TITLE
coreos-install -o vmware failes. File does not exist

### ISSUE THREAD

**Issue by pizzarabe** [coreos/bugs#1533]
If i try to install coreos with the coreos-install script and the -o switch to use a specific OEM it failes to download the vmware file
```

 - name: coreos-bootstrap.service
      runtime: no
      command: start
      content: |
        [Unit]
        Description=Install coreos to disk
        [Service]
        ExecStart=/bin/bash -c "/usr/bin/coreos-install -C  stable -d /dev/sda -c /home/core/cloud-config.yml  -o vmware && reboot"
        [X-Fleet]
        X-Conflicts=coreos-bootstrap.service
```

`Error: Image URL unavailable: https://stable.release.core-os.net/amd64-usr/1068.9.0/coreos_production_vmware_image.bin.bz2 `

And this is absolutly correct, bc there is no file with that name (but for example there is a "coreos_production_vmware_image.vmdk.bz2")

### Environment ###

Installing CoreOS 1068.9.0 with a 1069.9.0 image.
There is a newer stable image but the changelogs does not refere to a bug like that.

a quick check of the installation script shows:

```
if [[ -n "${OEM_ID}" ]]; then
    IMAGE_NAME="coreos_production_${OEM_ID}_image.bin.bz2"
else
    IMAGE_NAME="coreos_production_image.bin.bz2"
fi
```

Is there a problem with my interpretation of the OEM switch or should we rename the files?

**Comment by vcaputo** [comment]
This isn't really supported by `coreos-install` at the moment, vmware users can just fetch the appropriate disk image from `https://stable.release.core-os.net/amd64-usr/1068.9.0` and boot it.

The UX around this could be better, feeding vmware as the oem to coreos-install and having it 404 is inappropriate, coreos-install should probably detect the vmware oem and print something more useful.

I'm not the author of `coreos-install` but I imagine it's the way it is so additional oems may be supported later by simply publishing their appropriately named image.bin files, and coreos-install would be able to install them without modification.

Closing this for now, feel free to reopen if needed.

**Comment by robszumski** [comment]
@vcaputo is there a reason that the appropriately named files aren't being generated?

**Comment by vcaputo** [comment]
@robszumski Well, I'm not the author but if more natively formatted images are being provided perhaps the rationale was why go through the install when you can just get something natively supported?  /cc @marineam may have more input there.
