### ISSUE TITLE
ignition: add docs on how to disable/configure update-engine and locksmith

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1537]
update-engine and locksmith are common and we should just provide the snippets. Based on this user discussion: https://groups.google.com/d/msg/coreos-user/7As40BM7Rkw/BAut9puACgAJ

**Comment by cemo** [comment]
@philips I know this is not correct place since the issue is related to ignition. However I can not move to ignition easily because of the user-data limit of AWS and could not find the way to bypass limit. What is the proper way to disable `update-engine` with cloud-init?
