### ISSUE TITLE
Add Container Linux Config snippets throughout os docs

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1538]
Everything in https://github.com/coreos/docs/tree/master/os.

Supersedes: https://github.com/coreos/bugs/issues/1537.

**Comment by urzds** [comment]
Related to #1537 I would like to ask: Is there a guide how to translate a cloud-config to Ignition? An explanation how to express the old `coreos.{update,locksmith,etcd,fleet,flannel}` cloud-config keys using Ignition.

**Comment by crawford** [comment]
@urzds The [config transpiler](https://github.com/coreos/container-linux-config-transpiler) will gain support for those high level configurations. It doesn't exist today, but it is on our roadmap.

**Comment by ElijahCaine** [comment]
@crawford Are we sure we want to move to ignition configs? Won't we eventually just replace *those* with Container Linux configs?

**Comment by crawford** [comment]
@urzds CT now supports syntactic sugar for most of these features (https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/examples.md#etcd). Let us know if you run into trouble.

@ElijahCaine We should move to Container Linux Configs. This bug predated a lot of that work.

**Comment by crawford** [comment]
I think this is adequately addressed at this point.
