### ISSUE TITLE
Get oem:///coreos-install.json: unsupported protocol scheme "oem"

### ISSUE THREAD

**Issue by dghubble** [coreos/bugs#1541]
# Issue Report #

Unsupported oem protocol on first boot from disk. Seems like a possible regression since using 1122.0.0 or earlier works as expected.

### CoreOS Version ###

1151.0.0 (not ok)
1122.0.0 (working ok)

### Environment ###

Both qemu/kvm and hardware. Occurs on every machine, reliably.

### Expected Behavior ###

Run coreos-install with an ignition config (via flag). Reboot machine. First boot should run Ignition.

### Actual Behavior ###

After coreos-install with an Ignition file (via flag), the first boot from disk will crash to an emergency shell. 

```
Reached target Initrd File Systems
Requested transaction contradicts existing jobs: Transaction is destructive.
Failed to start initrd-switch-root.target: Transaction is destructive.
```

Ignition logs

```
Get error: Get oem:///coreos-install.json: unsupported protocol scheme "oem"
```

I've tested the very same machine profiles except using CoreOS Alpha 1109.1.0 and 1122.0.0 (both to PXE into, and install) and this doesn't occur.

This should only affect freshly provisioned nodes since Ignition won't run after initial boot. I haven't seen any problems with my machines which auto-update.

### Reproduction Steps ###

 Checkout https://github.com/coreos/coreos-baremetal/pull/330 and try any of the qemu/kvm install to disk examples (etcd-install, k8s-install, [tutorial](https://github.com/coreos/coreos-baremetal/blob/master/Documentation/getting-started-rkt.md), etc.) or install manually.

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/coreos-overlay/pull/2151.
