### ISSUE TITLE
CoreOS on GCE does not have shutdown scripts features

### ISSUE THREAD

**Issue by tsing** [coreos/bugs#1543]
# Issue Report #

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1068.10.0
VERSION_ID=1068.10.0
BUILD_ID=2016-08-23-0220
PRETTY_NAME="CoreOS 1068.10.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Google Compute Engine

### Expected Behavior ###

- Add a shutdown script to metadata of a CoreOS VM, as described in this article:
  https://cloud.google.com/compute/docs/shutdownscript
- It should run shutdown scripts when shutting down or rebooting the VM

### Actual Behavior ###

- shutting down or rebooting the VM never run the script
- There is no `/var/run/google.shutdown.script` file inside the CoreOS VMs. The other operating systems have this script.

### Reproduction Steps ###

 * Add a shutdown script to metadata of a CoreOS VM, as described in this article:
   https://cloud.google.com/compute/docs/shutdownscript
  * shutting down or rebooting the VM

### Other Information ###

https://code.google.com/p/google-compute-engine/issues/detail?id=299

**Comment by robszumski** [comment]
I'm interested in what you're using this feature for. Can you explain your use-case?

I totally agree that this should be supported, in an effort to have CoreOS function similarly to other OSes on GCE.

**Comment by tsing** [comment]
We use the feature to send some important log files to google storage
before instance preempted, it works well with Ubuntu on GCE

**Comment by crawford** [comment]
@tsing can you try running `journalctl -u google-shutdown-scripts.service`? I'm curious if that service is running properly.

**Comment by tsing** [comment]
@crawford `-- No entries --` when run the command. 

There is a `/etc/systemd/system/google-startup-scripts.service` in the os, but the ``/etc/systemd/system/google-shutdown-scripts.service` is not exists.

The `google-shutdown-scripts.service` also not exists in https://github.com/coreos/coreos-overlay/tree/master/coreos-base/oem-gce/files/units

**Comment by crawford** [comment]
Okay, so it looks like we just need to add that service. We can do that.

> We use the feature to send some important log files to google storage

Just an FYI, the shutdown-script mechanism is best-effort - it isn't guaranteed to run.

**Comment by dm0-** [comment]
The shutdown script is run as of coreos/coreos-overlay#2224 and coreos/scripts#593.
