### ISSUE TITLE
SkyDNS can't listen on 0.0.0.0:53 in CoreOS 1151.0.0

### ISSUE THREAD

**Issue by steveeJ** [coreos/bugs#1545]
### CoreOS Version ###
1151.0.0

```
$ cat /etc/os-release
NAME=CoreOS
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###
I have a SkyDNS container that uses `--net=host` and attempts to listen on `0.0.0.0:53`.

### Expected Behavior ###
SkyDNS works.

### Actual Behavior ###
SkyDNS doesn't work, because systemd-resolved is listening on `127.0.0.53:53`, causing SkyDNS to fail.

### Reproduction Steps ###

  1. Boot CoreOS 1151.0.0
  1. `etcdctl set /skydns/config {"dns_addr":"0.0.0.0:53"}`
  1. `sudo /usr/bin/rkt run --debug --net=host docker://skynetservices/skydns --insecure-options=image`

### Other Information ###
This has worked in the past without any configuration change.

## Feature Request ##
Disable systemd-resolved by default, or revert whatever caused it to claim that socket.

**Comment by dm0-** [comment]
We discussed this, and I will send a PR upstream shortly to make enabling the stub resolver configurable.  I'll leave it enabled by default for upstream consistency, but we will disable it on CoreOS.

**Comment by philips** [comment]
And as a workaround doing `systemctl mask systemd-resolved` works if you are running your own full resolver. However, if you rely on /etc/resolv.conf entries from DHCP it will break. 

Also, this issue will be fixed before Beta and we will default this behavior to off.

**Comment by dm0-** [comment]
We are unconditionally disabling the DNS stub resolver's listening ports on the next alpha and beta, until upstream agrees on a configurable option.
