### ISSUE TITLE
Using CoreOS as minikube ISO image

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/bugs#1546]
Currently we have [minikube-iso](https://github.com/coreos/minikube-iso) to create a minimal bootable ISO image to be used as a boot2docker replacement for [minikube](https://github.com/kubernetes/minikube).

To use CoreOS as a minikube-iso replacement, we have the following issues to consider:
- minimal final ISO size: [minikube-iso](https://github.com/coreos/minikube-iso/releases/download/v0.0.1/minikube-v0.0.1.iso) is ~68MB, the current [minikube-0.6.iso](https://storage.googleapis.com/minikube/minikube-0.6.iso) boot2docker is ~36MB
- must include both `rkt`, as well as `docker`
- disabled [predictable network interface names](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/#idontlikethishowdoidisablethis): (unfortunately) libmachine relies on `eth0` to be used for `minikube ip`. 
- A possibility to include a custom script/systemd unit file: Currently I migrated the boot2docker automount script which implements the "transfer" from ssh-keys being generated on the host to the VM, and the reformatting of the attached image drive for persistent storage. The original is https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/etc/rc.d/automount, the migrated one including the systemd-unit is https://github.com/coreos/minikube-iso/tree/master/package/automount.
- Binaries from the following packages must be present in `$PATH`: 
1. attr
2. bridge-utils
3. e2fsprogs
4. parted
5. socat
6. sudo
7. util-linux
8. iptables

I listed all installed packages in the minikube-iso v0.0.1 release page: https://github.com/coreos/minikube-iso/releases/tag/v0.0.1

xref https://github.com/kubernetes/minikube/issues/168

**Comment by philips** [comment]
@s-urbaniak the binaries should be in the hyperkube image, right?

As for the ssh-keys you can just use an OEM, right? Documented here: https://coreos.com/os/docs/latest/notes-for-distributors.html

**Comment by s-urbaniak** [comment]
@philips minikube doesn't use the hyperkube image at all. They build a custom version of the `kubelet` binary (called `localcube` [1]), copy it via ssh the VM during `minikube start` [2], and then start [3] that directly via ssh.

As for the pre-generated ssh keys ... hmm I'd need to recheck if that is possible in minikube. They delegate this to libmachine, which implements a ssh generator [5] per driver (virtualbox, kvm, xhyve, etc). Then they "transfer" those generated SSH keys inside a fake disk image, unpacking them during boot time [6] to `/userdata.tar`.

[1] [cmd/localkube/cmd/start.go](https://github.com/kubernetes/minikube/blob/33063656fc2b0086e262376096fc468bbed64d4d/cmd/localkube/cmd/start.go)
[2] [pkg/minikube/cluster/localkube_caching.go#L134](https://github.com/kubernetes/minikube/blob/33063656fc2b0086e262376096fc468bbed64d4d/pkg/minikube/cluster/localkube_caching.go#L134)
[3] [pkg/minikube/cluster/commands.go#L32](https://github.com/kubernetes/minikube/blob/33063656fc2b0086e262376096fc468bbed64d4d/pkg/minikube/cluster/commands.go#L32)
[4] [pkg/minikube/cluster/cluster.go#L174](https://github.com/kubernetes/minikube/blob/33063656fc2b0086e262376096fc468bbed64d4d/pkg/minikube/cluster/cluster.go#L174)
[5] [vendor/github.com/docker/machine/drivers/virtualbox/misc.go#L35](https://github.com/kubernetes/minikube/blob/33063656fc2b0086e262376096fc468bbed64d4d/vendor/github.com/docker/machine/drivers/virtualbox/misc.go#L35)
[6] https://github.com/coreos/minikube-iso/blob/master/package/automount/minikube-automount#L26

**Comment by crawford** [comment]
I'm not sure if it makes sense to use CoreOS for this if you are concerned about the size. It's possible to use our SDK to define a much smaller image though. That is the route I would take.

**Comment by crawford** [comment]
Were you able to investigate the use of our SDK for generating images?

**Comment by s-urbaniak** [comment]
Unfortunately no, since minikube-iso was adopted upstream I concentrated on rkt issues only.

**Comment by crawford** [comment]
Okay, I'm going to close this out then. Container Linux is focused more on stability and hardware-support than size.
