### ISSUE TITLE
Producing a custom CoreOS image for rkt stage1-coreos

### ISSUE THREAD

**Issue by lucab** [coreos/bugs#1547]
Currently rkt has a stage1-coreos ACI which is created by downloading the PXE image and extracting some files. On top of that, some binaries for stage1 entrypoints are produced during the build process, together forming the final rootfs.

This usecase may or may not fit in the reworking for #1546. In particular, rkt currently has to start from an existing CoreOS release (for consistency) but it has to strip most of the rootfs content due to size concerns.

The current stage1-coreos ACI is ~90MB uncompressed (including all stage1 entrypoint binaries).
These (plus runtime libraries) are the pristine binaries included from the PXE image:
- systemd (with helpers: systemctl, etc.)
- journald (with helpers: journalctl, etc.)
- bash
- mount

stage1-coreos build machinery is at https://github.com/coreos/rkt/tree/master/stage1/usr_from_coreos. It contains some manifest defining the full list of files to be copied from a downloaded PXE image.

**Comment by crawford** [comment]
As mentioned in #1546, it's possible to define a much smaller image to build via the existing CoreOS Linux SDK.
