### ISSUE TITLE
Tracking: Stable 1122.2.0

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1552]
Here are the proposed set of packages that will go into the release.

[app-admin/etcd-wrapper-0.0.2-r0](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-admin/etcd-wrapper/etcd-wrapper-0.0.2-r0.ebuild)
[app-admin/flannel-0.5.5-r3](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-admin/flannel/flannel-0.5.5-r3.ebuild)
[app-admin/fleet-0.11.7](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-admin/fleet/fleet-0.11.7.ebuild)
[app-admin/kubelet-wrapper-0.0.1-r5](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-admin/kubelet-wrapper/kubelet-wrapper-0.0.1-r5.ebuild)
[app-admin/locksmith-0.3.4-r1](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-admin/locksmith/locksmith-0.3.4-r1.ebuild)
[app-admin/mayday-0.1.0-r1](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-admin/mayday/mayday-0.1.0-r1.ebuild)
[app-admin/toolbox-0.0.0-r5](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-admin/toolbox/toolbox-0.0.0-r5.ebuild)
[app-crypt/tpmpolicy-20160404](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-crypt/tpmpolicy/tpmpolicy-20160404.ebuild)
[app-emulation/actool-0.5.1-r1](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-emulation/actool/actool-0.5.1-r1.ebuild)
[app-emulation/containerd-0.2.2-r1](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-emulation/containerd/containerd-0.2.2-r1.ebuild)
[app-emulation/docker-1.11.2](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-emulation/docker/docker-1.11.2.ebuild)
[app-emulation/rkt-1.7.0](https://github.com/coreos/coreos-overlay/tree/95e1b044002b47def111376d7e58fc11f1dfec6b/app-emulation/rkt/rkt-1.7.0.ebuild)
[app-emulation/runc-0.1.0](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/app-emulation/runc/runc-0.1.0.ebuild)
[dev-db/etcd-0.4.9-r2](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/dev-db/etcd/etcd-0.4.9-r2.ebuild)
[dev-db/etcd-2.3.2](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/dev-db/etcd/etcd-2.3.2.ebuild)
[sys-apps/seismograph-2.1.0](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/sys-apps/seismograph/seismograph-2.1.0.ebuild)
[sys-apps/systemd-229-r108](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/sys-apps/systemd/systemd-229-r108.ebuild)
[sys-kernel/coreos-kernel-4.7.0-r1](https://github.com/coreos/coreos-overlay/tree/b8dacee7d61ff5fde5cf29f9eef3928660fc8490/sys-kernel/coreos-kernel/coreos-kernel-4.7.0-r1.ebuild)

/cc @mike-saparov @steveeJ @aaronlevy @brianredbeard @lucab @xiang90 

I think we should hold off on the etcd-wrapper until we've sorted out the design.

Aiming to release this on Sept. 6.

**Comment by xiang90** [comment]
dev-db/etcd-0.4.9-r2 -> lgtm
dev-db/etcd-2.3.2 -> probably we should upgrade this to 2.3.7 soon. See https://github.com/coreos/etcd/releases/tag/v2.3.3. Also see https://github.com/coreos/bugs/issues/1550

**Comment by lucab** [comment]
The following P0 bugs have been found in rkt 1.7.0 and fixed in the next release cycle:
https://github.com/coreos/rkt/issues?q=milestone%3Av1.8.0+is%3Aclosed+label%3Apriority%2FP0

In short, log retrieving via api-service is buggy. This affects kubernetes mostly.

**Comment by crawford** [comment]
We are going to hold Docker back at 1.10.3 due to https://github.com/coreos/bugs/issues/1554.

**Comment by crawford** [comment]
@lucab we can only ship 1.7 (currently in stable), 1.8, or 1.11 (currently in beta). Other versions have not been tested enough. Which should we go with?

**Comment by lucab** [comment]
@crawford 1.8 is the best pick in that set.

**Comment by crawford** [comment]
https://github.com/coreos/manifest/releases/tag/v1122.2.0
