### ISSUE TITLE
Tracking: Beta 1153.0.0

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1553]
Here are the proposed set of packages that will go into the release.

[app-admin/etcd-wrapper-0.0.2-r0](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-admin/etcd-wrapper/etcd-wrapper-0.0.2-r0.ebuild)
[app-admin/flannel-0.5.5-r3](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-admin/flannel/flannel-0.5.5-r3.ebuild)
[app-admin/fleet-0.11.8](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-admin/fleet/fleet-0.11.8.ebuild)
[app-admin/kubelet-wrapper-0.0.1-r5](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-admin/kubelet-wrapper/kubelet-wrapper-0.0.1-r5.ebuild)
[app-admin/locksmith-0.4.0](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-admin/locksmith/locksmith-0.4.0.ebuild)
[app-admin/mayday-0.1.0-r1](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-admin/mayday/mayday-0.1.0-r1.ebuild)
[app-admin/toolbox-0.0.0-r7](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-admin/toolbox/toolbox-0.0.0-r7.ebuild)
[app-crypt/tpmpolicy-20160404](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-crypt/tpmpolicy/tpmpolicy-20160404.ebuild)
[app-emulation/actool-0.5.1-r1](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-emulation/actool/actool-0.5.1-r1.ebuild)
[app-emulation/containerd-0.2.3](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-emulation/containerd/containerd-0.2.3.ebuild)
[app-emulation/docker-1.12.1-r2](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-emulation/docker/docker-1.12.1-r2.ebuild)
[app-emulation/rkt-1.13.0](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-emulation/rkt/rkt-1.13.0.ebuild)
[app-emulation/runc-1.0.0_rc1_p20160615-r1](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/app-emulation/runc/runc-1.0.0_rc1_p20160615-r1.ebuild)
[dev-db/etcd-0.4.9-r2](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/dev-db/etcd/etcd-0.4.9-r2.ebuild)
[dev-db/etcd-2.3.2](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/dev-db/etcd/etcd-2.3.2.ebuild)
[sys-apps/seismograph-2.1.1](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/sys-apps/seismograph/seismograph-2.1.1.ebuild)
[sys-apps/systemd-231-r2](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/sys-apps/systemd/systemd-231-r2.ebuild)
[sys-kernel/coreos-kernel-4.7.1](https://github.com/coreos/coreos-overlay/tree/0d7f1e8b257fde4aeaf5aeae509af9931be30a60/sys-kernel/coreos-kernel/coreos-kernel-4.7.1.ebuild)

/cc @mike-saparov @steveeJ @aaronlevy @brianredbeard @lucab @xiang90

Aiming to release this on Sept. 7.

**Comment by xiang90** [comment]
dev-db/etcd-0.4.9-r2 -> lgtm
dev-db/etcd-2.3.2 -> probably we should upgrade this to 2.3.7 soon. See https://github.com/coreos/etcd/releases/tag/v2.3.3. Also see https://github.com/coreos/bugs/issues/1550

**Comment by dm0-** [comment]
Noting that `systemd-231-r2` is the version that results in #1545.

Also, it may be worth incrementing the seismograph version to `-r1`, which is just this fix: coreos/seismograph@fd6ede5

**Comment by vcaputo** [comment]
it's kind of surprising that cgpt issue hasn't caused (noticed) problems for users yet

**Comment by lucab** [comment]
I'm not aware of any big issues in rkt 1.13.0.

rkt 1.12.0 introduced a default seccomp filter based on the docker one, which was found to be too strict and adjusted in 1.14.0: https://github.com/coreos/rkt/pull/3126

If you get any reports of containers suddenly getting killed, seccomp may be the first thing to check.

**Comment by crawford** [comment]
We are going to hold Docker back at 1.11.2 due to a large number of issues.

**Comment by euank** [comment]
:+1:

**Comment by aaronlevy** [comment]
👍

**Comment by brianredbeard** [comment]
FYI, I don't see anything in the mayday ebuild to copy the config files
into place.

**Comment by mischief** [comment]
@redbeard see https://github.com/coreos/coreos-overlay/pull/2150/files
