### ISSUE TITLE
"XYZ is unreachable." - HTTP doesn't quite seem to work anymore (Alpha)

### ISSUE THREAD

**Issue by amcsi** [coreos/bugs#1555]
# Issue Report #

## Bug ##
Can't seem to access HTTP

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1153.0.0
VERSION_ID=1153.0.0
BUILD_ID=2016-08-27-0408
PRETTY_NAME="CoreOS 1153.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?
DigitalOcean

### Expected Behavior ###
Being able to reach the webserver's default page in Chrome at http://<domain>:999/

### Actual Behavior ###
Getting domain is unreachable.

### Reproduction Steps ###

  1. Type `docker run --rm -p 999:80 nginx`
  2. Go to http://<domain>:999/ in Google Chrome

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

**Comment by dm0-** [comment]
Directly pasting your Docker command and accessing the port `999` URL worked for me using the latest CoreOS alpha (1153.0.0) available on DigitalOcean.

Can you access the IP address directly without the DNS name?  Do you have any firewall rules configured that would block port `999`?

**Comment by amcsi** [comment]
Ok, it does seem to work now for some reason
