### ISSUE TITLE
Stable 1122.2.0 missing on coreos update server

### ISSUE THREAD

**Issue by styxlab** [coreos/bugs#1558]
# Issue Report
Stable CoreOS Release **1122.2.0** is out since September 6, 2016, but cannot be downloaded from the update servers.

## Bug ##
When querying **https://update.release.core-os.net/amd64-usr/1122.2.0/update.gz** an error message is shown. Other CoreOS versions are available on update.release.core-os.net.

### Expected Behavior ###
If a new CoreOS relase is published, it should be available on the update servers within a couple of hours.

### Actual Behavior ###
Update image for stable version **1122.2.0** is missing on https://update.release.core-os.net/amd64-usr/ for more than 2 days.

### Philosophy  ###
This behavior is at odds with the CoreOS update philosophy. See https://coreos.com/why/#updates for further details.

**Comment by crawford** [comment]
We rate limit updates to ensure that potential issues don't affect too many users. In this case, we decided to hold off for a period before actively rolling out the update. That being said, the update payload should have been made available on the update server in the mean time. That is my mistake. I just uploaded the payload and we'll begin rolling out today.

**Comment by styxlab** [comment]
That was quick. Thank you!
