### ISSUE TITLE
Ignition speed up raid creation

### ISSUE THREAD

**Issue by deimosfr** [coreos/bugs#1560]
# Issue Report

Raid creation could take a very long time depending on the size of the disks and their speeds
### CoreOS Version

1122.2.0
### Environment

Virtualbox 5.0.26
### Expected Behavior

When creating a raid, we can speed up mdadm with "--assume-clean" option which avoid waiting a full sync of the disks by assuming they're clean.

Here is an example:
`mdadm --create --assume-clean --verbose /dev/md0 --level=1 --raid-devices=2 /dev/sdb1 /dev/sdc1`
## Feature Request

Can you please add by default or with an option the --assume-clean parameter?

**Comment by vcaputo** [comment]
Well, we could either add a boolean to the raid config for --assume-clean, or for custom flags passed verbatim to mdadm similar to what we already support for mkfs.  There are quite a few possible flags for mdadm so maybe the latter makes more sense, but it would be very easy to produce broken mdadm invocations.  /cc @crawford thoughts?

**Comment by deimosfr** [comment]
As you suggested, I think additional custom parameter is the best solution to let users choose which options they want to add.

**Comment by bgilbert** [comment]
Ignition config spec version &ge; 2.2.0 now has a `storage.raid[].options` attribute which allows passing `--assume-clean` to mdadm.  Thanks for reporting.
