### ISSUE TITLE
SSH login failed for CoreOS 1153.3.0

### ISSUE THREAD

**Issue by sachincab** [coreos/bugs#1562]
Hi Team,

I could not able to login to server via ssh with below message:
**"System is booting up. See pam_nologin(8)"**

Using beta channel with latest version (CoreOS 1153.3.0):
AMI: ami-89ec90fa

All the services running on server has been started and working.
Please find system log from one of instance.
[system-log.txt](https://github.com/coreos/bugs/files/463768/system-log.txt)

Please let me know your inputs on this.

**Comment by basvdlei** [comment]
We have the same issue (beta 1153.3.0)

Can be reproduced by specifying a reboot strategy (reboot or etcd-lock) in the cloud-config:
```
#cloud-config
coreos:
  update:
    reboot-strategy: reboot
```

Bypassing the nologin shows that cloudinit is haning:
```
ssh root@192.168.121.224
"System is booting up. See pam_nologin(8)"
Password: 
"System is booting up. See pam_nologin(8)"
Last login: Fri Sep  9 11:13:17 2016 from 192.168.121.1
Update Strategy: No Reboots
localhost ~ # systemctl list-jobs
 JOB UNIT                                                                         TYPE  STATE  
 246 motdgen.service                                                              start waiting
 237 serial-getty@ttyS0.service                                                   start waiting
 236 getty.target                                                                 start waiting
1040 user-0.slice                                                                 start waiting
 592 user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service start running
 271 user-config.target                                                           start waiting
1044 user@0.service                                                               start waiting
 267 systemd-user-sessions.service                                                start waiting
 155 multi-user.target                                                            start waiting
 268 locksmithd.service                                                           start waiting
 240 getty@tty1.service                                                           start waiting
1119 session-1.scope                                                              start waiting

12 jobs listed.
```

Unit status:
```
● user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service - Load cloud-config from /var/lib/coreos-vagrant/vagrantfile-user-data
   Loaded: loaded (/usr/lib/systemd/system/user-cloudinit@.service; static; vendor preset: disabled)
   Active: activating (start) since Fri 2016-09-09 11:11:54 UTC; 2min 34s ago
 Main PID: 791 (coreos-cloudini)
    Tasks: 4
   CGroup: /system.slice/system-user\x2dcloudinit.slice/user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service
           └─791 /usr/bin/coreos-cloudinit --from-file=/var/lib/coreos-vagrant/vagrantfile-user-data

Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Writing file to "/etc/coreos/update.conf"
Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Wrote file to "/etc/coreos/update.conf"
Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Wrote file /etc/coreos/update.conf to filesystem
Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Updated /etc/environment
Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Ensuring runtime unit file "etcd.service" is unmasked
Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Ensuring runtime unit file "etcd2.service" is unmasked
Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Ensuring runtime unit file "fleet.service" is unmasked
Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Ensuring runtime unit file "locksmithd.service" is unmasked
Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Ensuring runtime unit file "locksmithd.service" is unmasked
Sep 09 11:11:54 localhost coreos-cloudinit[791]: 2016/09/09 11:11:54 Calling unit command "restart" on "locksmithd.service"'
```

Golang trace:
[cloudinit.txt](https://github.com/coreos/bugs/files/463819/cloudinit.txt)

Screenshot of the console:
![hanging-boot](https://cloud.githubusercontent.com/assets/11786068/18385263/d382958a-768f-11e6-83f7-2a797ee5879c.png)

**Comment by sachincab** [comment]
In our case, we do have reboot-strategy  with etcd-lock.
However services are running on server which has been started via user_data.

**Comment by basvdlei** [comment]
Looks like this fix for a race condition, introduced a deadlock: https://github.com/coreos/locksmith/commit/ebbef92a6de4cb477d783612517171e1d63be4ed

**Comment by basvdlei** [comment]
@sachincab can you change the title back? This issue is not EC2 related. We have it on VMWare ESXi and I reproduced it with a Vagrant box (KVM)

**Comment by jumanjiman** [comment]
fwiw i had the same problem on bare metal.
worked around it on bare metal by adding `coreos.autologin rd.break` to the kernel cmdline in bootloader, then `rm /var/lib/coreos-install/user_data`, then reboot.

**Comment by crawford** [comment]
We paused the Beta updates around 06:18 UTC. We'll get a fix together today.

**Comment by crawford** [comment]
Here is the fix for locksmith: https://github.com/coreos/locksmith/pull/110.

**Comment by crawford** [comment]
For reference, this deadlock prevents logins because `motdgen.service` has `After=locksmith.service` and `Before=permit-user-sessions.service`. Since, `locksmith.service` never starts, it prevents `motdgen.service` from starting, which prevents `permit-user-sessions.service` from starting.

**Comment by TaiSHiNet** [comment]
Thanks for the speed @crawford

**Comment by Ulexus** [comment]
IMO, the user-cloudinit service should have an explicit timeout anyway.  I use the follwing drop-in, but it really should have _some_ timeout defined in the system service unit.  Otherwise we get this problem, where it will wait _forever_ with no ability to log in.

```yaml
coreos:
  units:
    - name: user-cloudinit@.service
      drop-ins:
        - name: 10-timeout.conf
          content: |
            [Service]
            TimeoutSec=60s
```

**Comment by crawford** [comment]
1153.4.0 is currently rolling out with the fix. If you machine was caught by this issue, you may need to manually reboot the machine to pick up the fix.

**Comment by crawford** [comment]
1164.1.0 starting rolling out about nine hours ago (forgot to leave a comment). I'm going to monitor this over the next couple of days. The updates are currently rate limited, but if I don't see any trouble come Monday, I'll lift the limit so every machine gets the update. If you are still unable to log in to the machine after this, you'll need to reboot it.

**Comment by crawford** [comment]
At this point, all machines should have the update. If you are still having trouble logging in, you'll need to manually reboot the machine. Apologies for the trouble.

**Comment by TaiSHiNet** [comment]
@maintainers this issue seems to be present again on 1180.0.
Working instances now deadlock and disallow login. Some services (kubelet) _do_ start.

**Comment by TaiSHiNet** [comment]
After 13 minutes I finally could log on
```Failed Units: 1
  system-cloudinit@usr-share-oem-cloud\x2dconfig.yml.service```
Should I open a new issue for this?
