### ISSUE TITLE
Intermittent container network outgoing connection issue (CoreOS 1153.4)

### ISSUE THREAD

**Issue by xueshanf** [coreos/bugs#1564]
# Issue Report #

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1153.4.0
VERSION_ID=1153.4.0
BUILD_ID=2016-09-10-0107
PRETTY_NAME="CoreOS 1153.4.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

On AWS EC2 hvm

### Expected Behavior ###
```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1068.3.0
VERSION_ID=1068.3.0
BUILD_ID=2016-06-25-0103
PRETTY_NAME="CoreOS 1068.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

$  docker run --rm -it alpine:3.4 wget 169.254.169.254/latest/
Connecting to 169.254.169.254 (169.254.169.254:80)
index.html           100% |*******************************|    27   0:00:00 ETA
$ docker run --rm -it alpine:3.4 wget 169.254.169.254/latest/
Connecting to 169.254.169.254 (169.254.169.254:80)
index.html  100% |************************************************************** 27   0:00:00 ETA

```
### Actual Behavior ###

Alpine:3.4 container cannot make outgoing connections

ip-10-10-x-x core # docker run --rm -it alpine:3.4 wget 169.254.169.254/latest/
Connecting to 169.254.169.254 (169.254.169.254:80)
wget: can't connect to remote host (169.254.169.254): Host is unreachable
ip-10-10-x-x core # docker run --rm -it alpine:3.4 wget 169.254.169.254/latest/
Connecting to 169.254.169.254 (169.254.169.254:80)
wget: can't connect to remote host (169.254.169.254): Host is unreachable
ip-10-10-x-x core # docker run --rm -it alpine:3.4 wget 169.254.169.254/latest/
Connecting to 169.254.169.254 (169.254.169.254:80)
wget: can't connect to remote host (169.254.169.254): Host is unreachable
ip-10-10-x-x core # docker run --rm -it alpine:3.4 wget 169.254.169.254/latest/
Connecting to 169.254.169.254 (169.254.169.254:80)
wget: can't connect to remote host (169.254.169.254): Host is unreachable
ip-10-10-x-x core # docker run --rm -it alpine:3.4 wget 169.254.169.254/latest/
Connecting to 169.254.169.254 (169.254.169.254:80)
wget: can't connect to remote host (169.254.169.254): Host is unreachable

### Reproduction Steps ###

  1. On CoreOS 1153.4.0
  2. docker run --rm -it alpine:3.4 wget 169.254.169.254/latest/

### Other Information ###

The problem seems intermittent - occasionally the connection was successful. 
It doesn't seem to limit alphine:3.4 image. I got same issue with Fedra image. 

Running wget on the host has no issues.

**Comment by crawford** [comment]
Dup of https://github.com/coreos/bugs/issues/1554.
