### ISSUE TITLE
flanneld: Add option through environment variable

### ISSUE THREAD

**Issue by styxlab** [coreos/bugs#1566]
# Issue Report #
Please add an environment variable to the falnneld.service exec start command for passing in existing and additional options to flannel.

## Motivation ##
If you need to modify existing parameter to flannel, such as --ip-masq=true, you currently need to overwrite the complete ExecStart parameter with a cloud_init drop-in. However, that technique is prone to error: Whenever the coreos team changes the command, the existing drop-in may not work anymore.

## Background ##
As I need to pass in --ip-masq=true due to flanneld bug [#433](https://github.com/coreos/flannel/issues/433) I had defined a custom ExecStart drop-in for flannel. When the coreos team switched from docker to rkt for starting up flannel the previous command crashed. With automatic updates turned on, my coreos cluster could not start flannel and the cluster became stale.

### CoreOS Version ###
All versions.

### Expected Behavior ###
A new environment variable such as FLANNEL_OPTS which contain the current options to the flannel deamon and which can be overwritten in the cloud_config with custom options to flannel.

### Similar Issues ###
While you are adding FLANNEL_OPTS you can also make RKT_OPTS available as requested here: [#1565](https://github.com/coreos/bugs/issues/1565).

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/coreos-overlay/issues/2205.
