### ISSUE TITLE
Pre-golang 1.6 docker cannot talk to docker daemon

### ISSUE THREAD

**Issue by jakolehm** [coreos/bugs#1569]
# Issue Report #

## Bug ##

Pre-golang 1.6 docker should be able to talk with docker daemon. 

It seems that the latest beta (1153.4.0) docker is built with the go 1.6. Previous betas were built with 1.5 and they seems to work just fine.

https://github.com/docker/docker/issues/20865

### CoreOS Version ###

1153.4.0

### Expected Behavior ###

Pre-golang 1.6 docker should be able to talk with docker daemon

### Actual Behavior ###

Docker daemon responds:

```
Error response from daemon: 400 Bad Request: malformed Host header
```

**Comment by crawford** [comment]
As mentioned in https://github.com/docker/docker/issues/20865, upstream isn't supporting this scenario. I don't think we should either. You'll need to update the Docker client in your containers.

**Comment by jakolehm** [comment]
I think that upstream is actually supporting this scenario because CoreOS Alpha with Docker 1.12 works fine. See: https://github.com/docker/docker/pull/22888

Updating docker client is not always so easy when those container images are out of your hands. In this case we noticed problems with [Weave Net](https://github.com/weaveworks/weave) that embeds older docker client for backwards compatibility.

**Comment by crawford** [comment]
Okay, so maybe we pull in https://github.com/docker/docker/commit/3d6f5984f52802fe2f4af0dd2296c9e2e4a1e003 and https://github.com/docker/docker/commit/989f6f852f639404f8e86e179ce5389e2d29c5d2. 

@marineam what do you think?

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/docker/pull/31.
