### ISSUE TITLE
SDK: build_image script fails sometimes running grub_install.sh

### ISSUE THREAD

**Issue by c4milo** [coreos/bugs#157]
It sometimes works but sometimes it doesn't. 

Command: `./build_image --noenable_rootfs_verification --replace dev`

Here is a screenshot: 

![](https://i.cloudup.com/Q2AG7beu9l.png)

**Comment by crawford** [comment]
A while ago, a retry was added to help with this issue. I still see the warning so the underlying issue is still present, but the command should work now.
