### ISSUE TITLE
Docker crash: "fatal error: bad map state"

### ISSUE THREAD

**Issue by basvdlei** [coreos/bugs#1570]
# Issue Report
## Bug

Docker crashed when starting containers (in our case on boot) with a fatal error:

```
fatal error: bad map state
```

The stack traces [trace.txt](https://github.com/coreos/bugs/files/470389/trace.txt) show that runc is accessing a map unsynchronized:

```
runtime.throw(0x16a6690, 0xd)
    /usr/lib/go/src/runtime/panic.go:527 +0x90 fp=0xc820916a90 sp=0xc820916a78
runtime.evacuate(0x11c4720, 0xc820316090, 0x0)
    /usr/lib/go/src/runtime/hashmap.go:825 +0x3b1 fp=0xc820916b50 sp=0xc820916a90
runtime.growWork(0x11c4720, 0xc820316090, 0x1)
    /usr/lib/go/src/runtime/hashmap.go:791 +0x57 fp=0xc820916b70 sp=0xc820916b50
runtime.mapassign1(0x11c4720, 0xc820316090, 0xc820916c58, 0xc820916c57)
    /usr/lib/go/src/runtime/hashmap.go:433 +0x176 fp=0xc820916c18 sp=0xc820916b70
github.com/opencontainers/runc/libcontainer/selinux.mcsAdd(0xc820a83b20, 0xa, 0x0, 0x0)
    /build/amd64-usr/var/tmp/portage/app-emulation/docker-1.10.3-r5/work/docker-1.10.3/vendor/src/github.com/opencontainers/runc/libcontainer/selinux/selinux.go:263 +0xfd fp=0xc820916c80 sp=0xc820916c18
```

This race condition is fixed in a later version of runc by this commit: https://github.com/opencontainers/runc/commit/c6cfce304b10513abd71252fddb57367f3c91673
### CoreOS Version

```
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Environment

VMWare ESXi OVA
### Reproduction Steps

I've not yet been able to reproduce it. But creating/starting multiple containers at the same time should do the trick, if you're (un)lucky.
### Other Information

Incidentally after the `docker.service` was restarted by systemd, some of docker's iptable dnat rules were incorrect. This caused traffic to the host mapped port of container A to be forwarded to container B and vice versa. I need to track this down further...

**Comment by jtower525** [comment]
i've seen this on 3 of my 19 kubernetes nodes w/ coreos 1122.2.0 in the past 24 hours.

**Comment by basvdlei** [comment]
I think this issue can be closed. Since all the channels now contain a version of Docker that use a fixed runc.
