### ISSUE TITLE
Slow DNS resolution inside containers when using --net flag

### ISSUE THREAD

**Issue by rwky** [coreos/bugs#1575]
# Issue Report

This appears to be similar or the same issue as here https://github.com/docker/docker/issues/11407 however I'm only experiencing this with Docker 1.11.2 in beta, 1.10.3 from the stable channel seems fine.
## Bug

When using the --net flag DNS resolution slows down after some time (or times out) when querying the internal docker DNS server 127.0.0.11 querying external services is fine.
### CoreOS Version

```
NAME=CoreOS
ID=coreos
VERSION=1153.4.0
VERSION_ID=1153.4.0
BUILD_ID=2016-09-10-0107
PRETTY_NAME="CoreOS 1153.4.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Environment

Dedicated hardware
### Expected Behavior

DNS resolution is fine
### Actual Behavior

DNS resolution slows
### Reproduction Steps

Run a container with a user defined network that queries DNS at regular intervals.
### Other Information

It appears to be resolved in Docker 1.12.1 I've no idea how practical it is to port whatever fixed it back to 1.11/1.10 however I would consider this a good reason not to put 1.11 into stable.

**Comment by crawford** [comment]
Is this still present in Docker 1.12?

**Comment by rwky** [comment]
I've recently updated a server to the beta channel containing 1.12.3 and it seems resolved. I'll close it for now and re-open if it crops up again.
