### ISSUE TITLE
systemd & nspawn mount propagation fix for rkt

### ISSUE THREAD

**Issue by alban** [coreos/bugs#1578]
In rkt, we will need to attach new volumes into an already-running pod for [CRI](https://github.com/coreos/rkt/blob/master/Documentation/proposals/app-level-api.md). That feature is possible to implement with the same algorithm as in the "machinectl bind" command. However, there is a bug in current systemd versions that blocks the implementation:

- rkt issue: https://github.com/coreos/rkt/issues/3195
- systemd upstream issue: https://github.com/systemd/systemd/issues/3860
- systemd upstream PR with the fix: https://github.com/systemd/systemd/pull/4152

Hopefully, that will be fixed in future systemd-v232. Meanwhile, could we backport the fix above into CoreOS Linux once the systemd PR is merged? Then, we could build rkt's stage1-coreos.aci with the new CoreOS Linux PXE image.

The fix is not yet reviewed upstream, but I'm hoping it will be soon.

/cc @coreos/rkt-maintainers

**Comment by alban** [comment]
Patch https://github.com/systemd/systemd/commit/19caffac75a2590a0c5ebc2a0214960f8188aec7 merged via https://github.com/systemd/systemd/pull/4252

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/systemd/pull/65.
