### ISSUE TITLE
Unable to mount Ceph RBD volume inside pods create by kubernetes

### ISSUE THREAD

**Issue by JrCs** [coreos/bugs#1579]
# Issue Report #

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1153.4.0
VERSION_ID=1153.4.0
BUILD_ID=2016-09-10-0107
PRETTY_NAME="CoreOS 1153.4.0 (MoreOS)"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

- Running on VMWare vSphere virtual machines

### Expected Behavior ###
Allow kubelet to create the ceph RBD device

### Actual Behavior ###
Failed to modprobe rbd error:executable file not found in $PATH

I'm using the `kubelet-wrapper` script with the image quay.io/coreos/hyperkube:v1.3.7_coreos.0. The problem is that the kubelet cannot create the rbd device. See [here](http://stackoverflow.com/questions/39619078/mount-rdb-volumes-in-kubernetes-coreos)

It seems that the kubelet container don't have the `/sbin/modprobe` and `rbd` commands. Also some mount binds are need: /dev, /lib/modules, /etc/ceph, etc..

An issue has been open: [#23924](https://github.com/kubernetes/kubernetes/issues/23924)

Can use update the ACI image and the  `kubelet-wrapper` script to allow kubelet to create the RBD device ?

**Comment by aaronlevy** [comment]
@JrCs We have some relatively new docs about this here: [kubelet-wrapper rbd docs ](https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubelet-wrapper.md#allow-pods-to-use-rbd-volumes). These haven't been synced with the website yet - but we should soon

**Comment by JrCs** [comment]
Thanks a lot @aaronlevy.
Great Job like always.

**Comment by kokhang** [comment]
Hi guys, I am also having this issue, which i work around by adding args to kubelet to mount /sbin/modprobe and /lib/modules. Is there any plan to fix this so that we dont have to manually feed this workaround to kubelet?
