### ISSUE TITLE
coreos-metadata race condition on Microsoft Azure

### ISSUE THREAD

**Issue by omkensey** [coreos/bugs#1582]
# Issue Report
### CoreOS Version

1122.2.0
### Environment

What hardware/cloud provider/hypervisor is being used to run CoreOS?

Microsoft Azure
### Expected Behavior

coreos-metadata.service runs normally and generates the IP metadata (COREOS_AZURE_IPV4_DYNAMIC) for the instance.
### Actual Behavior

About 1/3 to 1/2 of the time, coreos-metadata runs before DHCP has completed so it can't capture the private IP.
### Reproduction Steps
1. Boot a number of CoreOS VMs on Azure and check for which ones don't get metadata properly.
### Other Information

Creating a dropin for coreos-metadata.service to make it require and run after network-online.target works around the issue.

**Comment by crawford** [comment]
For reference, something like this should work:

```json
{
  "ignition": { "version": "2.0.0" },
  "systemd": {
    "units": [{
      "name": "coreos-metadata.service",
      "dropins": [{
        "name": "network-online.conf",
        "contents": "[Service]\nRequires=network-online.target\nAfter=network-online.target"
      }]
    }]
  }
}
```

**Comment by crawford** [comment]
Fixed in https://github.com/coreos/coreos-overlay/pull/2262.
