### ISSUE TITLE
docker commands hang

### ISSUE THREAD

**Issue by jay-ouellette** [coreos/bugs#1584]
# Issue Report #

I installed Kubernetes on AWS with the instructions here https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-render.html

I can login to the master and workers, but docker doesn't appear to work.

## Bug ##

Docker commands:

docker ps
docker info
docker stats

all hang

I don't even see a docker daemon running:

ps aux | grep docker
core      1789  0.0  0.0   6756   984 pts/0    S+   22:24   0:00 grep --colour=auto docker

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

AWS m3.medium instances

uname -a
Linux ip-172-18-5-5.ec2.internal 4.7.0-coreos #1 SMP Tue Sep 6 14:39:20 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux

### Expected Behavior ###

When I create a Kubernetes cluster with "kube-aws up" docker works on all hosts.

### Actual Behavior ###

Docker hangs on all hosts

### Reproduction Steps ###

  1. Install Kubernetes on AWS with these instructions https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws-render.html
  2. ssh into one of the created EC2 instances
  3. run "docker info"

### Other Information ###

kube-aws version v0.8.2

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

**Comment by jay-ouellette** [comment]
```bash
sudo systemctl enable docker
sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib64/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─40-flannel.conf
   Active: inactive (dead)
     Docs: http://docs.docker.com

Sep 25 23:37:11 ip-172-18-5-5.ec2.internal systemd[1]: Dependency failed for Docker Application Container Engine.
Sep 25 23:37:11 ip-172-18-5-5.ec2.internal systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Sep 25 23:37:32 ip-172-18-5-5.ec2.internal systemd[1]: Dependency failed for Docker Application Container Engine.
Sep 25 23:37:32 ip-172-18-5-5.ec2.internal systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Sep 25 23:37:54 ip-172-18-5-5.ec2.internal systemd[1]: Dependency failed for Docker Application Container Engine.
Sep 25 23:37:54 ip-172-18-5-5.ec2.internal systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Sep 25 23:38:14 ip-172-18-5-5.ec2.internal systemd[1]: Dependency failed for Docker Application Container Engine.
Sep 25 23:38:14 ip-172-18-5-5.ec2.internal systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Sep 25 23:38:35 ip-172-18-5-5.ec2.internal systemd[1]: Dependency failed for Docker Application Container Engine.
Sep 25 23:38:35 ip-172-18-5-5.ec2.internal systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
```

**Comment by jay-ouellette** [comment]
So when I gave the machine an Internet connection, docker started to work suddenly.

CoreOS doesn't work without an Internet connection?

**Comment by mischief** [comment]
if you are using flanneld.service, it is expecting to pull a flannel rkt image you can override the image used if you want.. see `systemctl cat flanneld.service`.

i believe kube-aws also pulls containers from the internet by default.
