### ISSUE TITLE
cannot boot CoreOS from local disk

### ISSUE THREAD

**Issue by sandaar** [coreos/bugs#1592]
# Issue Report
### CoreOS Version

```
$ cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Environment

Hardware being used to run CoreOS - IBM System x3850 X5 / x3950 X5 servers
### Expected Behavior

Successfull boot from local disk.
### Actual Behavior

Stuck at "Welcome to GRUB" message
![grub](https://cloud.githubusercontent.com/assets/3398162/19010382/f9d1d6d8-8733-11e6-809a-372dd1c3c15d.png)
### Reproduction Steps
1. PXE boot server with CoreOS 1122.2.0
2. coreos-install -d /dev/sda -C stable -V current -c cloud-config.yml
3. reboot from local disk
### Other Information

Issue first reported GPT errors during the coreos installation. After reboot, stuck at Welcome to GRUB screen.
Sequential reboots still same.
Many reinstallation including recommended doing parted, dd MBR still results the same https://github.com/coreos/bugs/issues/1031, https://github.com/coreos/bugs/issues/1091 
Wiped out RAID 1 and recreate still same.
Change to new clean drives still same.
Installed another OS like SLES12SP1; it installed and booted up with no problem.
Installed CoreOS after one more time and it's the same issue.

Using stable or beta, still the same issue
coreos-install -d /dev/sda -C stable -V current -c cloud-config.yml
coreos-install -d /dev/sda -C beta –V current  -c cloud-config.yml

More data below… after pxe booted, log into the node; export proxy, scp yml file and do coreos-install…

```
server ~ # coreos-install -d /dev/sda -C beta -V current -c cloud-config.yml
2016/09/29 23:25:31 Checking availability of "local-file"
2016/09/29 23:25:31 Fetching user-data from datasource of type "local-file"
Current version of CoreOS beta is 1153.4.0
Downloading the signature for https://beta.release.core-os.net/amd64-usr/1153.4.0/coreos_production_image.bin.bz2...
2016-09-29 23:25:31 URL:https://beta.release.core-os.net/amd64-usr/1153.4.0/coreos_production_image.bin.bz2.sig [543/543] -> "/tmp/coreos-install.vblnIN4L3f/coreos_production_image.bin.bz2.sig" [1]
Downloading, writing and verifying coreos_production_image.bin.bz2...
2016-09-29 23:26:27 URL:https://beta.release.core-os.net/amd64-usr/1153.4.0/coreos_production_image.bin.bz2 [268026319/268026319] -> "-" [1]
gpg: Signature made Sat Sep 10 01:34:39 2016 UTC using RSA key ID 2E16137F
gpg: key 93D2DCB4 marked as ultimately trusted
gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" [ultimate]
Installing cloud-config...
Success! CoreOS beta 1153.4.0 is installed on /dev/sda
```

**Comment by alxzndr** [comment]
I have more or less the same problem on a hp proliant bladeserver.
I found out grub is spawning TPM errors, see #1529
Maybe you should check your bios for TPM related settings? worth the try i guess...

**Comment by crawford** [comment]
> Issue first reported GPT errors during the coreos installation.

Do you have those error messages, or is it just that GRUB is hanging?

**Comment by sandaar** [comment]
@crawford the same error message as here https://github.com/coreos/bugs/issues/1031 followed by "succesfully installed" message. I read in the comments that it's normal so I ignored it. 

Another scenario that I tried: I pxe booted with CoreOS 835.9.0, installed 835.9.0 to disk, booted from local disk, then after some time I started getting "SysRq: reboot crash, kill all tasks, memory-full-oom, ..." messages in console and I couldn't do anything, can't ssh, run commands. 
After that I pxe booted with CoreOS 1122.2.0, installed it to disk, didn't get any GPT errors (probably because of previously installed 835.9?), booted from local disk, got the same hanging GRUB.

@alxzndr thanks for suggesting, I'll try it

**Comment by sandaar** [comment]
@alxzndr in BIOS TPM Physical Presence is shown as not asserted. I'm guessing I don't have TPM?
![image](https://cloud.githubusercontent.com/assets/3398162/19058866/d51058d4-898f-11e6-82a9-1822c6f54763.png)

I did try to install coreos to disk, then run tpmown as @avongluck-r1soft suggested in https://github.com/coreos/bugs/issues/1529 Got hanging GRUB again

**Comment by dghubble** [comment]
I successfully installed 1122.2.0 to disk on an IBM System x3250 M5 two days ago. TPM screen looks a bit different. Another difference was that I was using Ignition rather than cloud-config.

![img_20160816_004234](https://cloud.githubusercontent.com/assets/2253428/19133762/d8bad4ca-8b0e-11e6-80ff-65bb1b019181.jpg)

**Comment by sandaar** [comment]
@dghubble sorry for the delayed response. I tried to pxe boot using ignition config, the config doesn't get applied.
ignition.json:
```
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "systemd": {
    "units": [{
      "name": "systemd-journald.service",
      "dropins": [{
        "name": "10-debug.conf",
        "contents": "[Service]\nEnvironment=SYSTEMD_LOG_LEVEL=debug"
      }]
    }]
  },
  "networkd": {
    "units": [
      {
        "name": "00-eno1.network",
        "contents": "[Match]\nName=eno1\n\n[Network]\nAddress=x.x.x.x/24"
      },
      {
        "name": "10-eno2.network",
        "contents": "[Match]\nName=eno2\n\n[Network]\nAddress=x.x.x.x/24\nGateway=x.x.x.x\nDNS=x.x.x.x\nDomains=some.domain"
      }
    ]
  },
  "storage": {
    "disks": [
      {
        "device": "/dev/sda",
        "wipeTable": true,
        "partitions": [
          {
            "label": "ROOT",
            "number": 0,
            "size": 0,
            "start": 0
          }
        ]
      }
    ],
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/hostname",
        "mode": 420,
        "contents": { "source": "data:,some_hostname" }
      },
      {
        "filesystem": "root",
        "path": "/etc/ssh/sshd_config",
        "mode": 600,
        "contents": { "source": "data:,%23%20Use%20most%20defaults%20for%20sshd%20configuration.%0D%0AUsePrivilegeSeparation%20sandbox%0D%0ASubsystem%20sftp%20internal-sftp%0D%0AClientAliveInterval%20180%0D%0AUseDNS%20no%0D%0APermitRootLogin%20yes" }
      }
    ]
  },
  "passwd": {
    "users": [
      {
        "name": "root",
        "passwordHash": "some_hash",
        "sshAuthorizedKeys": ["key1", "key2"],
        "create": {
          "groups": ["sudo", "docker"]
        }
      },
      {
        "name": "guest",
        "passwordHash": "some_hash",
        "sshAuthorizedKeys": ["key1", "key2"],
        "create": {
          "groups": ["sudo", "docker"]
        }
      },
      {
        "name": "core",
        "passwordHash": "some_hash",
        "sshAuthorizedKeys": ["key1", "key2"],
        "create": {
          "groups": ["sudo", "docker"]
        }
      }
    ]
  }
}
```
pxe config:
```
default menu.c32
display message
prompt 0
timeout 0
menu title MAIN MENU

label local
menu label Boot from ^Local Drive
COM32 chain.c32
APPEND hd0 0

label coreos
menu label ^CoreOS
kernel coreos_production_pxe.vmlinuz
append initrd=coreos_production_pxe_image.cpio.gz console=tty0 console=ttyS0 coreos.autologin=tty1 coreos.autologin=ttyS0 cloud.config.url=http://x.x.x.x/ignition.json coreos.first_boot=1

label linux
menu label ^Install SLES 11 SP3 from Network Repository
kernel /sles11sp3/linux
append initrd=sles11sp3/initrd ramdisk_size=65536 netdev=eth0 vga=0 textmode=1 install=http://x.x.x.x/sles11sp3/dvd1 autoyast=http://x.x.x.x/autoinst.xml 

label linux
menu label ^Install SLES 12 from Network Repository
kernel /sles12/linux
append initrd=sles12/initrd ramdisk_size=65536 netdev=eth0 vga=0 textmode=1 install=http://x.x.x.x/sles12/dvd1 autoyast=http://x.x.x.x/autoinst_sles12.xml
```
Then I pxe booted with cloud-config, ran:
```
coreos-install -d /dev/sda -C stable -V current -i ignition.json
```
it says successfully installed, but reboot from local disk still gives hanging grub.

**Comment by ErnestG4** [comment]
Sandaar is "able to pxe boot current alpha 1221.0.0 using cloud config, it gets installed to disk but during reboot still gets stuck at GRUB."

NOTE: Sandaar tried older versions at random, and 835.9.0 works for them. What is exceptional about this release?

**Comment by crawford** [comment]
@sandaar please provide boot logs when you run into failures. Just my looking at your config, my guess is that Ignition is failing to write files because you haven't formatted a filesystem on the ROOT partition.

**Comment by sandaar** [comment]
@crawford sorry don't know how to retrieve logs from remote servers, I am using java video viewer to access remote console and emergency shell that i get prompted to after fail doesn't have tools. I read /run/initramfs/rdsosreposrt.txt and found that ignition failed at creating root and core users cause they were already existing. After removing them from config I am able to pxe boot 1221.0.0 using ignition config. Then coreos-install with the same ignition config says it succesfully installed the os. Then after reboot again stuck at 'Welcome to GRUB' 

[Ignition config](https://gist.github.com/sandaar/1419bb256efe53debb554c0aa6734823). Also added formatting of root partition. Is it okay that I am formatting /dev/sda1? I followed examples [here](https://github.com/coreos/coreos-baremetal/blob/master/examples/ignition/k8s-worker.yaml) Disk layout in [docs](https://coreos.com/os/docs/latest/sdk-disk-partitions.html) labels /dev/sda9 as root. Also even though i was able to pxe boot with the given ignition config, files didn't get written.

**Comment by crawford** [comment]
> Then coreos-install with the same ignition config says it succesfully installed the os. Then after reboot again stuck at 'Welcome to GRUB'

That config blows away the partition table on `/dev/sda`, which is where the OS is stored. If you are running from a disk-based installation, just drop the "filesystems" and "disks" sections from your config. The disk is already partitioned and the filesystems are already formatted.

**Comment by sandaar** [comment]
@crawford thanks for clarifying! I deleted filesystems and disks section from the initial ignition config; successfully installed to disk with the changed ignition config; rebooted; got hanging grub.

**Comment by sandaar** [comment]
@crawford we found workaround: pxe boot and install to disk old version that used to work (681.0.0 for us) and then `update_engine_client -update`.

**Comment by crawford** [comment]
@sandaar CoreOS 681.0.0 doesn't have Ignition, so I'm not sure how this works. I've tested your config in a QEMU VM and as I suspected it works fine. Something else must be going on in your environment.

**Comment by sandaar** [comment]
@crawford thanks a lot for checking! Agreed, I think it's something on our side. I'm on it, will update here if I find anything. I guess this issue can be closed.

**Comment by sandaar** [comment]
@crawford  My colleague had the same hanging grub issue when deploying CoreOS on 2S Lenovo servers, he found that boot mode was reset to legacy after coreos deployment so changing boot mode back to uefi using asu tool solved it.

For our case we haven't figured it out yet fully but temporarily workaround is: after install to disk, reboot, go to settings (F1 for us) – Boot Manager – Add boot option – EFI-SYSTEM – coreos – grub – x86_64-efi – core.efi – input the description (e.g. testcoreos), commit changes – back to boot manager – change boot order to have testcoreos first, commit changes. After that reboots from local disk work fine.

**Comment by go4875** [comment]
Hello @sandaar i am having the same issue as you noted here. Sorry to revive the topic, some questions
1. are you booting with regular ipxe from matchbox? meaning, your not using grub for the booting of the servers?
2. can you let me know what settings are configured for your Lenovo servers? for both the PXE and system? Thanks @sandaar . been working on this for past 3 days with no luck.
