### ISSUE TITLE
polkit.service fails on development image

### ISSUE THREAD

**Issue by hasso** [coreos/bugs#1593]
# Issue Report
### CoreOS Version

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.2.0+2016-10-03-1633
VERSION_ID=1122.2.0
BUILD_ID=2016-10-03-1633
PRETTY_NAME="CoreOS 1122.2.0+2016-10-03-1633 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Environment

Development image (iso) booted in qemu. Starting polkitd fails because libstdc++.so.6 isn't found. Sude etc don't work as a result making image pretty unusable.

```
core@localhost ~ $ systemctl status --no-pager -l polkit
* polkit.service - Authorization Manager
  Loaded: loaded (/usr/lib64/systemd/system/polkit.service; static; vendor preset: disabled)
  Active: failed (Result: exit-code) since Tue 2016-10-04 09:43:20 UTC; 4min 38s ago
  Docs: man:polkit(8)
  Process: 1238 ExecStart=/usr/lib/polkit-1/polkitd --no-debug (code=exited, status=127)
 Main PID: 1238 (code=exited, status=127)

Oct 04 09:43:20 localhost systemd[1]: Starting Authorization Manager...
Oct 04 09:43:20 localhost polkitd[1238]: /usr/lib/polkit-1/polkitd: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Oct 04 09:43:20 localhost systemd[1]: polkit.service: Main process exited, code=exited, status=127/n/a
Oct 04 09:43:20 localhost systemd[1]: Failed to start Authorization Manager.
Oct 04 09:43:20 localhost systemd[1]: polkit.service: Unit entered failed state.
Oct 04 09:43:20 localhost systemd[1]: polkit.service: Failed with result 'exit-code'.
core@localhost ~ $
```

**Comment by urzds** [comment]
I ran into the same issue with 1339.0.0+2017-03-10-1956.

**Comment by urzds** [comment]
Both sys-devel/gcc-4.9.3 and sys-devel/gcc-4.9.4 were installed in `/build` (CoreOS' scripts did not bother to uninstall the older one). After unmerging 4.9.3 from `/build` (and the SDK), the image was built without the libstdc++.so.6 issue. Something seems to be broken when multiple versions of GCC are installed.

**Comment by viohex** [comment]
how to resolve this problem?

**Comment by viohex** [comment]
/usr/lib/polkit-1/polkitd: error while loading shared libraries: libstdc++.so.6: cannot open shared object file

**Comment by glevand** [comment]
Seems to be working OK for me with amd64 1520.8.0 and arm64 1590.0.0.

    $ sudo systemctl start polkit
    $ sudo systemctl status --no-pager -l polkit
    ...
    Nov 20 17:48:50 crb2 polkitd[9846]: Finished loading, compiling and executing 3 rules

**Comment by bgilbert** [comment]
Closing because we're [dropping the development image](https://groups.google.com/d/topic/coreos-dev/JNU-UDYprMo/discussion).  Thanks for the report.
