### ISSUE TITLE
1G memory isn't enough for development images

### ISSUE THREAD

**Issue by hasso** [coreos/bugs#1594]
# Issue Report
### CoreOS Version

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.2.0+2016-10-03-1633
VERSION_ID=1122.2.0
BUILD_ID=2016-10-03-1633
PRETTY_NAME="CoreOS 1122.2.0+2016-10-03-1633 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

For most of images the qemu script is generated with VM_MEMORY set to 1024. It's not enough for development images and booting it fails with cryptic messages and dropping into rescue shell. Increasing VM_MEMORY to 2048 fixes the problem.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
