### ISSUE TITLE
locksmithd doesn't work with etcd tls certificates

### ISSUE THREAD

**Issue by kfirufk** [coreos/bugs#1595]
# Issue Report #
locksmithctl doesn't work properly with etcd tls

## Bug ##

'locksmithctl status' returns 'Error initializing etcd client: client: etcd cluster is unavailable or misconfigured'

### CoreOS Version ###

NAME=CoreOS
ID=coreos
VERSION=1153.4.0
VERSION_ID=1153.4.0
BUILD_ID=2016-09-10-0107
PRETTY_NAME="CoreOS 1153.4.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

### Environment ###

it's a coreos installed on a pc machine at my home with core i7 cpu.

### Expected Behavior ###
that the Update Strategy would change to etcd-lock. 

### Actual Behavior ###

Update Strategy: No Reboots

### Other Information ###

some useful stuff from //var/lib/coreos-install/user_data

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/6dd43cef65845322a436f0a433c09b1b
    advertise-client-urls: https://coreos-2.tux-in.com:2379
    initial-advertise-peer-urls: https://coreos-2.tux-in.com:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: https://0.0.0.0:2379
    listen-peer-urls: https://coreos-2.tux-in.com:2380
  locksmith:
    endpoint: "https://coreos-2.tux-in.com:2379,https://coreos-3.tux-in.com:2379"
    etcd_cafile: /etc/ssl/etcd/ca.pem
    etcd_certfile: /etc/ssl/etcd/etcd1.pem
    etcd_keyfile: /etc/ssl/etcd/etcd1-key.pem
  update:
    reboot-strategy: etcd-lock

just to show that my etcd2 tls configuration works properly..
i ran from my macbook pro the command tcdctl --endpoint=https://coreos-2.tux-in.com:2379 --ca-file=/<PATH>/ca.pem --cert-file=/<PATH>/etcd1.pem --key-file=/<PATH>/etcd1-key.pem  --timeout=10s member list

and I got in response:

6e810b1ce009da9e: name=a8fe2f4a993442da8a4569c3ba5e6dc8 peerURLs=https://coreos-3.tux-in.com:2380 clientURLs=https://coreos-3.tux-in.com:2379 isLeader=true
ba43217a75b6ee38: name=2a2f7b63a8104d75904bcb4b57f87965 peerURLs=https://coreos-2.tux-in.com:2380 clientURLs=https://coreos-2.tux-in.com:2379 isLeader=false

more information at http://stackoverflow.com/questions/39853109/locksmithd-doesnt-work-properly-with-etcd-tls

**Comment by mischief** [comment]
what arguments are you passing to locksmithctl?

**Comment by kfirufk** [comment]
Hi! :) for some reason I thought that locksmithctl fetches the configuration provided in the could config file.

when I run 'locksmithctl --endpoint="https://coreos-2.tux-in.com:2379,https://coreos-3.tux-in.com:2379" --etcd-cafile=/etc/ssl/etcd/ca.pem --etcd-certfile=/etc/ssl/etcd/etcd1.pem --etcd-keyfile=/etc/ssl/etcd/etcd1-key.pem  status' it returns:

Available: 1
Max: 1

I currently have two coreos machines at my home to play with. should is state two machines available ?

I do notice that the locksmithd systemd script always restarts and fails with the following information:

Oct 03 15:56:45 coreos-2.tux-in.com systemd[1]: Started Cluster reboot manager.
Oct 03 15:56:45 coreos-2.tux-in.com locksmithd[1792]: No configured reboot window
Oct 03 15:56:45 coreos-2.tux-in.com locksmithd[1792]: locksmithd starting currentOperation="UPDATE_STATUS_IDLE" strategy="etcd-lock"
Oct 03 15:56:50 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 15:57:00 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 15:57:20 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 15:58:00 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 15:59:20 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 16:01:26 coreos-2.tux-in.com locksmithd[1792]: LastCheckedTime=0 Progress=0 CurrentOperation="UPDATE_STATUS_CHECKING_FOR_UPDATE" NewVersion=0.0.0.0 NewSize=0
Oct 03 16:01:27 coreos-2.tux-in.com locksmithd[1792]: LastCheckedTime=0 Progress=0 CurrentOperation="UPDATE_STATUS_IDLE" NewVersion=0.0.0.0 NewSize=0
Oct 03 16:02:00 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 16:07:00 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 16:12:00 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 16:17:00 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 16:22:00 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 16:27:00 coreos-2.tux-in.com locksmithd[1792]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unava
Oct 03 16:27:29 coreos-2.tux-in.com systemd[1]: Stopping Cluster reboot manager...
Oct 03 16:27:29 coreos-2.tux-in.com systemd[1]: Stopped Cluster reboot manager.

so.. what's wrong with my configuration?

thanks a lot! :)

**Comment by mischief** [comment]
no, locksmithctl does not share a config with locksmithd, but both are configurable via environment variables, such as LOCKSMITHCTL_* for locksmithctl and LOCKSMITHD_* for locksmithd.

are there any logs in the target etcd about the client trying to connect?

**Comment by kfirufk** [comment]
I have two coreos machines, configured with a discovery url of two servers.
when you're saying the 'target etcd' i'm guessing you mean that etcd2 server configured in each machine. 

so this is the information on the first machine i'm trying to fix: (coreos-2.tux-in.com)

journalctl -b -u etcd2 output at http://pastebin.com/pvjURYMx

I apologize for not properly understanding what information you required, if you need anything else, please let me know :)

**Comment by mischief** [comment]
it doesn't look like there are any logs here about the client connecting.

i can try to test locksmithctl/locksmithd + ssl later today.

**Comment by kfirufk** [comment]
awesome. thanks a lot.

**Comment by kfirufk** [comment]
needed to run "systemctl unmask update-engine.service" on both servers and now locksmithd runs. but running 'locksmithctl status' on both servers still shows "Available: 1 Max: 1". shouldn't I see both servers there ?

**Comment by kfirufk** [comment]
ahmm.. when I use locksmithctl to lock one of the servers, and i use 'locksmithctl status' on the other server, I do see the machine id that is locked, but when I browse the discovery url I don't see any new data. am I missing something ? am i not supposed to be locksmith related data there?
