### ISSUE TITLE
Tracking: Beta 1185.1.0

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1596]
Here are the proposed set of packages that will go into the release.

[app-admin/etcd-wrapper-0.0.2-r0](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-admin/etcd-wrapper/etcd-wrapper-0.0.2-r0.ebuild)
[app-admin/flannel-0.6.2](https://github.com/coreos/coreos-overlay/blob/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-admin/flannel/flannel-0.6.2.ebuild)
[app-admin/fleet-0.11.8](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-admin/fleet/fleet-0.11.8.ebuild)
[app-admin/kubelet-wrapper-0.0.1-r5](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-admin/kubelet-wrapper/kubelet-wrapper-0.0.1-r5.ebuild)
[app-admin/locksmith-0.4.1](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-admin/locksmith/locksmith-0.4.1.ebuild)
[app-admin/mayday-1.0.0](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-admin/mayday/mayday-1.0.0.ebuild)
[app-admin/toolbox-0.0.0-r7](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-admin/toolbox/toolbox-0.0.0-r7.ebuild)
[app-crypt/tpmpolicy-20160404](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-crypt/tpmpolicy/tpmpolicy-20160404.ebuild)
[app-emulation/actool-0.5.1-r1](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-emulation/actool/actool-0.5.1-r1.ebuild)
[app-emulation/containerd-0.2.3](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-emulation/containerd/containerd-0.2.3.ebuild)
[app-emulation/docker-1.11.2-r4](https://github.com/coreos/coreos-overlay/blob/78736b05c50d53b968b7d425f4c7ef2b5a0e67c5/app-emulation/docker/docker-1.11.2-r4.ebuild)
[app-emulation/rkt-1.14.0](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-emulation/rkt/rkt-1.14.0.ebuild)
[app-emulation/runc-1.0.0_rc1_p20160615-r1](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/app-emulation/runc/runc-1.0.0_rc1_p20160615-r1.ebuild)
[dev-db/etcd-0.4.9-r2](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/dev-db/etcd/etcd-0.4.9-r2.ebuild)
[dev-db/etcd-2.3.7](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/dev-db/etcd/etcd-2.3.7.ebuild)
[sys-apps/seismograph-2.1.1-r1](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/sys-apps/seismograph/seismograph-2.1.1-r1.ebuild)
[sys-apps/systemd-231-r4](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/sys-apps/systemd/systemd-231-r4.ebuild)
[sys-kernel/coreos-kernel-4.7.3-r1](https://github.com/coreos/coreos-overlay/tree/97f0469aa4d2be456b2728dfd49a18b80c3971fb/sys-kernel/coreos-kernel/coreos-kernel-4.7.3-r1.ebuild)

/cc @mike-saparov @steveeJ @aaronlevy @brianredbeard @lucab @xiang90

Aiming to release this on Oct. 5.

**Comment by xiang90** [comment]
LGTM on etcd.

**Comment by lucab** [comment]
LGTM on rkt.

**Comment by aaronlevy** [comment]
LGTM on kubernetes (via tests by @pb)

**Comment by crawford** [comment]
https://github.com/coreos/manifest/releases/tag/v1185.1.0.
