### ISSUE TITLE
1192.0.0 does not boot on AWS in paravirtual mode

### ISSUE THREAD

**Issue by monder** [coreos/bugs#1600]
# Issue Report #

## Bug ##

1192.0.0 fails to start on AWS

### CoreOS Version ###

CoreOS-alpha-1192.0.0 (ami-f7b6f684)

### Environment ###

PV m1.xlarge

### Expected Behavior ###

Instance boots.

### Actual Behavior ###

Instance does not boot and throws emergency shell
```
[K[[0;1;31m TIME [0m] Timed out waiting for device dev-mapper-usr.device.
[   92.212015] [systemd[1]: dev-mapper-usr.device: Job dev-mapper-usr.device/start timed out.[0;1;33mDEPEND[0m
] Dependency failed for /sysroot/usr.
```
Full log: https://gist.github.com/monder/c501245755f7c3271e3b03489ba495bb

**Comment by monder** [comment]
HVM (ami-82b5f5f1) works just fine.

**Comment by marineam** [comment]
By mistake we never added a piece of code to the Xen loader in GRUB that amends the kernel cmdline with the correct verity hash. And due to an oversight in our testing the Xen PV images weren't being tested.
