### ISSUE TITLE
Feature Request: Enable kernel options for eBPF

### ISSUE THREAD

**Issue by iaguis** [coreos/bugs#1602]
# Issue Report #

### Desired Feature ###

Enable `CONFIG_KPROBES`, `CONFIG_KPROBE_EVENT`. `CONFIG_BPF_SYSCALL` and `CONFIG_BPF_EVENTS` so we can use the [`bpf()`](http://man7.org/linux/man-pages/man2/bpf.2.html) syscall and attach eBPF programs to kprobe events.

We need this for some [Weave Scope](https://github.com/weaveworks/scope) plugins and for an upcoming new implementation of the probe component.

Reference: https://github.com/iovisor/bcc/blob/master/INSTALL.md#kernel-configuration

### Other Information ###

We're also struggling with compiling eBPF programs due to header problems but it seems we have everything we need from CoreOS' side, it's just a BCC problem (see https://github.com/iovisor/bcc/issues/743).

I'll comment here if we need anything on that regard.

cc @alban @asymmetric

**Comment by philips** [comment]
+1 to enabling this

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/2231.
