### ISSUE TITLE
Set partition UUID

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1603]
There is no way to set the partition UUID via Ignition. As a result, users cannot modify the GPT on the primary disk. Doing so would result in unexpected partuuids for the USR partitions.

**Comment by dgonyeo** [comment]
Does the this config not work for this? Or do you want more specific syntactic sugar for this?
https://gist.github.com/dgonyeo/428fa7c207505e4edd67543e6e412046

**Comment by crawford** [comment]
That sets the filesystem UUID, not the partition UUID.

**Comment by dgonyeo** [comment]
Ah yep. I'll go implement this.
