### ISSUE TITLE
Unable to find user core / System error: json: cannot unmarshal object into Go value of type libcontainer.syncType.

### ISSUE THREAD

**Issue by vielmetti** [coreos/bugs#1607]
# Issue Report #

When docker is run with the ``--user core`` option, it spits back a system error and does not start a container. However the ``--user root`` option works just fine.

Motivation: I'm running into this issue: https://github.com/node-red/node-red-docker/issues/9 and the ``-user`` flag is the recommended approach to give a container a stable UID when you persist data into the file system on the server.

## Bug ##

```
$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
Digest: sha256:ca7b185775966003d38ccbd9bba822fb570766e4bb69292ac23490f36f8a742e
Status: Image is up to date for alpine:latest
$ docker run -it --user core alpine /bin/sh
Unable to find user core
docker: Error response from daemon: Cannot start container 473a4fe8cfe50b76cbd76e43a7c373733db0a749ac239c4ee9fb8af7ee60481b: [9] System error: json: cannot unmarshal object into Go value of type libcontainer.syncType.
$ docker run -it --user root alpine /bin/sh
/ # 
```

### CoreOS Version ###

```
$ cat /etc/os-release
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

AWS

**Comment by vielmetti** [comment]
There's a similar error message in #1215 for a different component.

**Comment by mischief** [comment]
Does the container image have a user called core? If not, you shouldn't
expect user core to work in the container.

**Comment by vielmetti** [comment]
Thanks @mischief - I was able to resolve this by creating a user called core in the container and setting its uid to the uid of the core user on the host, and all is well. Closing.
