### ISSUE TITLE
kubelet wrapper doesn't have a bind mount path to /var/log/containers

### ISSUE THREAD

**Issue by kayrus** [coreos/bugs#1614]
Which results in inaccessible docker logs for fluentd log shipper.

by default kubelet creates `/var/log/containers/` directory with the symlinks to `/var/lib/docker/containers`. and when you run fluentd in kubernetes it can not find these logs, because symlinks are created only inside rkt container (kubelet wrapper)

**Comment by crawford** [comment]
The kubelet wrapper already mounts in `/var/lib/docker`. Do you mean that it should also mount in `/var/log/containers/`?

**Comment by kayrus** [comment]
@crawford exactly

**Comment by crawford** [comment]
I'll pull that into https://github.com/coreos/coreos-overlay/pull/2205.

**Comment by crawford** [comment]
We decided not to make this change (https://github.com/coreos/coreos-overlay/pull/2238). If the user wants this behavior, they can pass an extra flag to the wrapper.
