### ISSUE TITLE
/hyperkube image is outdated (and has high security issues)

### ISSUE THREAD

**Issue by kayrus** [coreos/bugs#1615]
* There is already Kubernetes 1.4.3 release (https://github.com/kubernetes/kubernetes/releases/tag/v1.4.3)
* 1.4.1 has 5 high security issues: https://quay.io/repository/coreos/hyperkube/image/dfa647550ef7100e3441d041a8ca8df599daf2bf8fe966dae7c2c7595cb0f64b?tab=vulnerabilities

**Comment by aaronlevy** [comment]
The issues in the security scan are unfortunately do not have a package with a fix (see the "Fixed in Version" column.

Also, the hyperkube image should be updated in a few hours. /cc @pbx0

**Comment by kayrus** [comment]
looks like image was updated.
