### ISSUE TITLE
visudo isn't useful

### ISSUE THREAD

**Issue by kbrwn** [coreos/bugs#1617]
# Issue Report
## Bug

Attempting to add a sudo user is done using the `visudo` command but this isn't useful on CoreOS as the default sudoers file is on the read-only partition. 

```
$ visudo
visudo: /usr/share/baselayout/sudoers: Read-only file system
```

This may cause users to attempt to add a sudo user by creating a `/etc/sudoers.d/user1` but if the formatting of this file is incorrect the user will lose sudo access for the `core` user: 

```
$ sudo vi /etc/sudoers.d/user1
>>> /etc/sudoers.d/user1: syntax error near line 1 <<<
sudo: parse error in /etc/sudoers.d/user1 near line 1
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```
### CoreOS Version

```
$ cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=1192.0.0
VERSION_ID=1192.0.0
BUILD_ID=2016-10-06-0240
PRETTY_NAME="CoreOS 1192.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
### Expected Behavior

visudo edits the sudoers file in a safe fashion

**Comment by kbrwn** [comment]
@crawford This actually may be fine. You can still use `visudo` with files in the `/etc/sudoers.conf/` dir.

```
visudo -f /etc/sudoers.d/test
```

**Comment by crawford** [comment]
Oh yeah, I forgot about that flag... We should get some docs together for this.

**Comment by kbrwn** [comment]
I'll add something to this doc: https://coreos.com/os/docs/latest/adding-users.html

**Comment by mischief** [comment]
looks like coreos/docs#898 documented `visudo -f` behavior. can this be closed now?

**Comment by crawford** [comment]
I think so.
