### ISSUE TITLE
remove ip6 network

### ISSUE THREAD

**Issue by vasilyt** [coreos/bugs#1619]
# Issue Report #

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

### Reproduction Steps ###

  1. ...
  2. ...

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

**Comment by crawford** [comment]
Assuming this was accidentally submitted.

**Comment by vasilyt** [comment]
Hm, sorry, this was submitted by mistake.
