### ISSUE TITLE
No AMI for EC2 in us-east-2

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1623]
_From @paultyng on October 19, 2016 21:0_

I realize this is probably the wrong repo for this issue, but I wasn't sure where exactly to log it.  There is no AMI in the new us-east-2 region (and subsequently no AMI listed in the docs for that region as well).

Is there a way to get the new region added to the lists of where AMI's are built?

_Copied from original issue: coreos/docs#900_

**Comment by crawford** [comment]
I wish Amazon would keep their [docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UserProvidedKernels.html) up-to-date.

**Comment by paultyng** [comment]
@crawford  Do you know approximately when this new AMI will be available? I didn't see it this morning in the AWS public list.

**Comment by crawford** [comment]
It will be available for new images. The next Alpha should be published in a couple of hours. I'll reply here once it's ready. Do you need the other channels as well?

**Comment by paultyng** [comment]
I need stable and beta unfortunately.

**Comment by paultyng** [comment]
I could make do with stable and alpha.

**Comment by paultyng** [comment]
@crawford I checked today, and still not seeing any coreos images in us-east-2, specifically didn't see **1192.2.0** which I think was what you said would be there.  Something not hooked up somewhere?

**Comment by crawford** [comment]
1192.2.0 was a high-priority security release (addressing DirtyCOW). We didn't actually release the new Alpha last week. I can manually publish the images today, now that I have a free moment.

**Comment by crawford** [comment]
@paultyng okay, you should be all set. These AMIs won't show up on our site, but if you search for CoreOS in that region, they should show up. Future AMIs will be listed on the site.

**Comment by paultyng** [comment]
Yep, see them now! Thanks!

**Comment by paultyng** [comment]
Will the site be updated automatically at some point I imagine? https://coreos.com/os/docs/latest/booting-on-ec2.html

**Comment by robszumski** [comment]
@paultyng Yes, our release automation will add a new row to that table and list the AMIs. This will happen with the next alpha release.
