### ISSUE TITLE
coreOS not updating to 1122.3.0 

### ISSUE THREAD

**Issue by anuiq** [coreos/bugs#1632]
**# Issue Report #**

I am trying to update coreos to the Latest stable version but have been unable to do so. I am on a private network but it does have access to public network. I wanted to know if its some network setting within AWS or some other problem that I have? 

**What hardware/cloud provider/hypervisor is being used to run CoreOS?**
I am running Coreos on EC2 instance. 

**### CoreOS Version ###**
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**$ update_engine_client -check_for_update**

[1025/170708:INFO:update_engine_client.cc(243)] Initiating update check and install.
[1025/170733:FATAL:update_engine_client.cc(181)] Check failed: rc == 1 (0 vs. 1)Error checking for update: GError(4): Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
/lib64/libbase-core-180609.so(base::debug::StackTrace::StackTrace()+0x34) [0x7fb514e5a2f4]
/lib64/libbase-core-180609.so(logging::LogMessage::~LogMessage()+0x313) [0x7fb514e6ed83]
update_engine_client(+0x3f75) [0x556e8f2c4f75]
/lib64/libc.so.6(__libc_start_main+0x114) [0x7fb51410bac4]
update_engine_client(+0x4689) [0x556e8f2c5689]

Trace/breakpoint trap (core dumped)

**$ update_engine_client -update**

[1025/171505:INFO:update_engine_client.cc(243)] Initiating update check and install.
[1025/171505:INFO:update_engine_client.cc(248)] Waiting for update to complete.

LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_CHECKING_FOR_UPDATE
NEW_VERSION=0.0.0.0
NEW_SIZE=0
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_CHECKING_FOR_UPDATE
NEW_VERSION=0.0.0.0
NEW_SIZE=0
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_CHECKING_FOR_UPDATE
NEW_VERSION=0.0.0.0
NEW_SIZE=0
[1025/171610:INFO:update_engine_client.cc(122)] Error getting status: GError(4): Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=(null)
NEW_VERSION=(null)
NEW_SIZE=0
[1025/171635:INFO:update_engine_client.cc(122)] Error getting status: GError(4): Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=(null)
NEW_VERSION=(null)
NEW_SIZE=0
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0.0
NEW_SIZE=0
[1025/171645:ERROR:update_engine_client.cc(189)] Update failed.

**$journalctl -u update-engine.service** 

[1022/033752:INFO:prefs.cc(51)] certificate-report-to-send-update not present in /var/lib/update_engine/prefs
update_engine[778]: [1022/033752:INFO:prefs.cc(51)] certificate-report-to-send-download not present in /var/lib/update_engine/prefs
update_engine[778]: [1022/033752:INFO:omaha_request_params.cc(60)] Current group set to stable
update_engine[778]: [1022/033752:INFO:update_attempter.cc(475)] Already updated boot flags. Skipping.
update_engine[778]: [1022/033752:INFO:update_attempter.cc(658)] Scheduling an action processor start.
update_engine[778]: [1022/033752:INFO:action_processor.cc(36)] ActionProcessor::StartProcessing: OmahaRequestAction
update_engine[778]: [1022/033752:INFO:omaha_request_action.cc(257)] Posting an Omaha request to https://public.update.core-os.net/v1/update/
update_engine[778]: [1022/033752:INFO:omaha_request_action.cc(258)] Request: <?xml version="1.0" encoding="UTF-8"?>
update_engine[778]: <request protocol="3.0" version="CoreOSUpdateEngine-0.1.0.0" updaterversion="CoreOSUpdateEngine-0.1.0.0" installsource="scheduler" ismachine="1">
update_engine[778]:     <os version="Chateau" platform="CoreOS" sp="1122.2.0_x86_64"></os>
update_engine[778]:     <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="1122.2.0" track="stable" bootid="{fd5b47ca-25d3-4d4d-b359-a35bae774093}" oem="ami" oemversio
update_engine[778]:         <ping active="1"></ping>
update_engine[778]:         <updatecheck></updatecheck>
update_engine[778]:         <event eventtype="3" eventresult="2" previousversion=""></event>
update_engine[778]:     </app>
update_engine[778]: </request>
update_engine[778]: [1022/033752:INFO:libcurl_http_fetcher.cc(48)] Starting/Resuming transfer
update_engine[778]: [1022/033752:INFO:libcurl_http_fetcher.cc(164)] Setting up curl options for HTTPS
  update_engine[778]: [1022/033822:ERROR:libcurl_http_fetcher.cc(243)] Unable to get http response code: name lookup timed out
  update_engine[778]: [1022/033822:INFO:libcurl_http_fetcher.cc(260)] No HTTP response, retry 1
  update_engine[778]: [1022/033832:INFO:libcurl_http_fetcher.cc(48)] Starting/Resuming transfer
  update_engine[778]: [1022/033832:INFO:libcurl_http_fetcher.cc(164)] Setting up curl options for HTTPS
  update_engine[778]: [1022/033902:ERROR:libcurl_http_fetcher.cc(243)] Unable to get http response code: name lookup timed out
  update_engine[778]: [1022/033902:INFO:libcurl_http_fetcher.cc(260)] No HTTP response, retry 2
  update_engine[778]: [1022/033912:INFO:libcurl_http_fetcher.cc(48)] Starting/Resuming transfer
  update_engine[778]: [1022/033912:INFO:libcurl_http_fetcher.cc(164)] Setting up curl options for HTTPS
  update_engine[778]: [1022/033942:ERROR:libcurl_http_fetcher.cc(243)] Unable to get http response code: name lookup timed out
  update_engine[778]: [1022/033942:INFO:libcurl_http_fetcher.cc(260)] No HTTP response, retry 3
  update_engine[778]: [1022/033952:INFO:libcurl_http_fetcher.cc(48)] Starting/Resuming transfer
  update_engine[778]: [1022/033952:INFO:libcurl_http_fetcher.cc(164)] Setting up curl options for HTTPS
  update_engine[778]: [1022/034022:ERROR:libcurl_http_fetcher.cc(243)] Unable to get http response code: name lookup timed out
  update_engine[778]: [1022/034022:INFO:libcurl_http_fetcher.cc(274)] Transfer resulted in an error (0), 0 bytes downloaded
  update_engine[778]: [1022/034022:INFO:omaha_request_action.cc(574)] Omaha request response:
  update_engine[778]: [1022/034022:ERROR:omaha_request_action.cc(588)] Omaha request network transfer failed.
  update_engine[778]: [1022/034022:INFO:subprocess.cc(229)] GError(8): Failed to execute child process "/usr/bin/crossystem" (No such file or directory)
  update_engine[778]: [1022/034022:INFO:action_processor.cc(68)] ActionProcessor::ActionComplete: OmahaRequestAction action failed. Aborting processing.
  update_engine[778]: [1022/034022:INFO:action_processor.cc(73)] ActionProcessor::ActionComplete: finished last action of type OmahaRequestAction
  update_engine[778]: [1022/034022:INFO:update_attempter.cc(283)] Processing Done.
  update_engine[778]: [1022/034022:ERROR:update_attempter.cc(598)] Update failed.

**Comment by crawford** [comment]
The logs are riddled with network errors. Double check that your network settings allow network traffic outside your VPC.

**Comment by anuiq** [comment]
Turns out that the DNS wasn't working. Thank you
