### ISSUE TITLE
Remove legacy etcd wrapper

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1636]
We don't want to ship the legacy etcd-wrapper to Stable.

**Comment by mischief** [comment]
i believe this was already completed with https://github.com/coreos/coreos-overlay/pull/2165

**Comment by crawford** [comment]
Huh, apparently I pulled it before it went to Beta. Neat.

**Comment by mischief** [comment]
needs to be pulled into 1185 branch still.

**Comment by mischief** [comment]
fixed by https://github.com/coreos/coreos-overlay/pull/2261
