### ISSUE TITLE
Need a way for cloud-init to expire user's password

### ISSUE THREAD

**Issue by aneverov4vmw** [coreos/bugs#164]
This functionality should be similar to Canonical's cloudinit chpasswd/expire (https://github.com/number5/cloud-init/blob/master/cloudinit/config/cc_set_passwords.py)

Tried doing the same thing using "chage -d 0 username". However, it seems to completely break login. The user gets kicked out right after login without any prompt to change password.

**Comment by crawford** [comment]
Related to https://github.com/coreos/bugs/issues/439.

**Comment by crawford** [comment]
This works now that we've included PAM in Container Linux. coreos-cloudinit itself doesn't know about this option, but we won't be adding it at this point since we are working on Ignition instead.
