### ISSUE TITLE
Stable CoreOS needs Newer RKT Runtime for Kubernetes 1.4.3

### ISSUE THREAD

**Issue by gmcquillan** [coreos/bugs#1640]
# Issue Report #

## Bug ##

Cannot run kubelet with hyperkube 1.4.3+ on latest stable channel CoreOS.

### CoreOS Version ###
Latest Stable. 1122.3.0, and 1122.2.0 were tried. 1185.2.0 is unaffected.

### Environment ###
What hardware/cloud provider/hypervisor is being used to run CoreOS?
Baremetal.

Kubelet Unit file:
```
        [Service]
        Environment=KUBELET_VERSION={{ k8s_version }}
        Environment=KUBELET_ACI={{ hyper_kube_repo }}
        Environment="RKT_OPTS=--volume dns,kind=host,source=/etc/resolv.conf \
        --mount volume=dns,target=/etc/resolv.conf \
        --volume rkt,kind=host,source=/opt/bin/host-rkt \
        --mount volume=rkt,target=/usr/bin/rkt \
        --volume var-lib-rkt,kind=host,source=/var/lib/rkt \
        --mount volume=var-lib-rkt,target=/var/lib/rkt \
        --volume stage,kind=host,source=/tmp \
        --mount volume=stage,target=/tmp \
        --volume var-log,kind=host,source=/var/log \
        --mount volume=var-log,target=/var/log"
        ExecStartPre=/usr/bin/mkdir -p /var/log/containers
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
        --api-servers=http://localhost:8080 \
        --network-plugin-dir=/etc/kubernetes/cni/net.d \
        --network-plugin=cni \
        --container-runtime=rkt \
        --rkt-path=/usr/bin/rkt \
        --rkt-stage1-image=coreos.com/rkt/stage1-coreos \
        --register-schedulable=false \
        --allow-privileged=true \
        --config=/etc/kubernetes/manifests \
        --cluster_dns={{ dns_service_ip }} \
        --cluster_domain=cluster.local \
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
```

Part of this could be using rkt as the container-runtime...

### Expected Behavior ###

rkt would be able to run kubelet of 1.4.3

### Actual Behavior ###

```
Oct 28 18:27:59 s0506 kubelet-wrapper[2352]: E1028 18:27:59.401879    2352 kubelet.go:2627] Container runtime sanity check failed: rkt: binary version is too old(1.8.0), requires at least 1.13.0
```
### Reproduction Steps ###

  1. ... PXE Coreos machine.
  2. ... Use a Kubernetes 1.4.3 Hyperkube Kubelet image.

### Other Information ###
Workaround: Just update to the beta channel.

**Comment by philips** [comment]
@yifan-gu Does kubelet unconditionally check the version of the rkt binary if found? It seems like it should only version check rkt if the container runtime is set to rkt.

**Comment by philips** [comment]
Oops, just change container-runtime to docker as you want the containers to execute under docker for now, right? (as discussed on slack)
