### ISSUE TITLE
rkt: bind-mounted /etc/hosts is out of sync with host

### ISSUE THREAD

**Issue by h0tbird** [coreos/bugs#1643]
# Issue Report #

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1214.0.0
VERSION_ID=1214.0.0
BUILD_ID=2016-10-27-2126
PRETTY_NAME="CoreOS 1214.0.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

VirtualBox

### Expected Behavior ###

If`/etc/hosts` is bind-mounted then host and container view must be in sync.

### Actual Behavior ###

Host and container view are out of sync.

### Reproduction Steps ###

```
sudo rkt run \
 --interactive \
 --net=host \
 --volume hosts,kind=host,source=/etc/hosts,readOnly=true \
 --mount=volume=hosts,target=/etc/hosts \
 quay.io/coreos/alpine-sh
```

Edit `/etc/hosts`in the host. The container version is out of sync.

### Other Information ###

Same thing happens with `/etc/resolv.conf`

**Comment by lucab** [comment]
Thanks for the report @h0tbird, may I ask how are you editing those files?

I just checked and this seems to work as expected when just modifying the file (eg. appending something via `echo foo >> /etc/resolv.conf`), but I see that this may break if you are using some editor which does unlinking and renaming, thus changing the file inode (some [vim configurations](http://vimdoc.sourceforge.net/htmldoc/editing.html#backup-table) may do this).

/cc @squeed for the dns topic, but I think this is just a side-effect of file bind-mounting behavior

**Comment by squeed** [comment]
This works for me:
```
[root@localhost ~]# rkt run --interactive --volume hosts,kind=host,source=/etc/hosts,readOnly=true  --mount=volume=hosts,target=/etc/hosts quay.io/coreos/alpine-sh
/ # cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

## In another terminal
[root@localhost ~]# echo "#foo" >> /etc/hosts

## Back in the pod:

/ # cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
#foo
/ # 
```

**Comment by h0tbird** [comment]
You're totally right! I was using `vim`. The `echo` trick works as expected.
Sorry for the noise today I'll think twice next time.
