### ISSUE TITLE
rkt: new --host-dns shortcut flag

### ISSUE THREAD

**Issue by h0tbird** [coreos/bugs#1644]
# Issue Report #

### Environment ###

Any

### Desired Feature ###

Shortcut flag for:

```
--volume resolv,kind=host,source=/etc/resolv.conf,readOnly=true \
--mount volume=resolv,target=/etc/resolv.conf \
--volume hosts,kind=host,source=/etc/hosts,readOnly=true \
--mount volume=hosts,target=/etc/hosts \
```

Perhaps `--host-dns=true`?

**Comment by lucab** [comment]
Which rkt version are your using? rkt recently gained some more options related to `resolv.conf` and `hosts` handling, have you seen https://github.com/coreos/rkt/blob/master/Documentation/networking/dns.md?

/cc @squeed

**Comment by squeed** [comment]
Indeed, you can do `--dns host --hosts-entry host` and it will do exactly what you've specified :-).

**Comment by h0tbird** [comment]
OMG that was fast. You rock ;-)
