### ISSUE TITLE
systemd: please backport streaming-fd patch (systemd PR 4179)

### ISSUE THREAD

**Issue by lucab** [coreos/bugs#1645]
In order to implement streams/tty attach in rkt, stage1 images need a systemd recent enough to support `Standard{Input,Output,Error}=fd`. Implementation for this landed in systemd master some time ago (post v231).

Unfortunately systemd-v232 release is taking longer than expected, so we would like to have that single commit from PR 4179 backported for next coreos alpha release. As such, please cherry-pick 
https://github.com/systemd/systemd/pull/4179/commits on top of current systemd-v231.

- Original rkt ticket: https://github.com/coreos/rkt/issues/1799

/cc @crawford @dm0- @mischief

**Comment by dm0-** [comment]
Since systemd v232 was released earlier today, we can look into upgrading for the next alpha.

**Comment by lucab** [comment]
@dm0- thanks a lot, this was filed just before the release actually happened :)

Feel free to directly look into upgrading to v232 (there are other interesting bits we contributed into there) and let us know once this land in an alpha image.

**Comment by lucab** [comment]
Just for a status update: are still shooting for v232 in the next alpha?

**Comment by crawford** [comment]
@lucab no, we have no plans to upgrade to v232.
