### ISSUE TITLE
How to properly disable automatic updates?

### ISSUE THREAD

**Issue by mlafeldt** [coreos/bugs#1646]
## Question ##

We're following the guide at https://coreos.com/os/docs/latest/update-strategies.html to disable automatic updates of CoreOS. (We update CoreOS by rolling out new AMIs.)

As documented, we stop these two units via cloud-init:

```
coreos:
  units:
    - name: update-engine.service
      command: stop
    - name: locksmithd.service
      command: stop
...
```

However, when doing this, `update-engine.service` will be marked as "failed":

```
$ ssh 10.8.3.234
Warning: Permanently added '10.8.3.234' (ECDSA) to the list of known hosts.
CoreOS stable (1068.9.0)
Last login: Thu Nov  3 13:23:08 2016 from 10.8.4.244
Update Strategy: No Reboots
Failed Units: 1
  update-engine.service
```

```
core@ip-10-8-3-234 ~ $ systemctl status update-engine
● update-engine.service - Update Engine
   Loaded: loaded (/usr/lib64/systemd/system/update-engine.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-11-02 20:58:35 UTC; 16h ago
 Main PID: 845 (code=exited, status=1/FAILURE)

Nov 02 20:58:32 localhost systemd[1]: Starting Update Engine...
Nov 02 20:58:34 localhost update_engine[845]: [1102/205834:INFO:main.cc(155)] CoreOS Update Engine starting
Nov 02 20:58:34 localhost systemd[1]: Started Update Engine.
Nov 02 20:58:34 localhost update_engine[845]: [1102/205834:INFO:update_check_scheduler.cc(82)] Next update check in 10m36s
Nov 02 20:58:35 ip-10-8-3-234.eu-west-1.compute.internal systemd[1]: Stopping Update Engine...
Nov 02 20:58:35 ip-10-8-3-234.eu-west-1.compute.internal systemd[1]: update-engine.service: Main process exited, code=exited, status=1/FAILURE
Nov 02 20:58:35 ip-10-8-3-234.eu-west-1.compute.internal systemd[1]: Stopped Update Engine.
Nov 02 20:58:35 ip-10-8-3-234.eu-west-1.compute.internal systemd[1]: update-engine.service: Unit entered failed state.
Nov 02 20:58:35 ip-10-8-3-234.eu-west-1.compute.internal systemd[1]: update-engine.service: Failed with result 'exit-code'.
```

Please tell us how to disable CoreOS updates properly, so that we can get rid of this error, which has been a constant distraction in our monitoring and when logging into machines. Thanks!

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1068.9.0
VERSION_ID=1068.9.0
BUILD_ID=2016-08-05-0455
PRETTY_NAME="CoreOS 1068.9.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

AWS EC2

**Comment by crawford** [comment]
My recommendation is to use [Ignition](https://coreos.com/ignition) for this (apologies for not updating the documentation yet). You can mask `update-engine.service` and `locksmithd.service` to prevent them from ever running (this is just not possible with coreos-cloudinit).

Your config would look something like the following (untested):

```json
{
  "ignition": { "version": "2.0.0" },
  "systemd": {
    "units": [
      {
        "name": "update-engine.service",
        "mask": true
      },
      {
        "name": "locksmithd.service",
        "mask": true
      }
    ]
  }
}
```

**Comment by mlafeldt** [comment]
Thanks. Good to know that it's not possible with coreos-cloudinit. I guess we will take a look at Ignition at some point.

Feel free to close this issue or leave it open for documentation purposes.

**Comment by geekpete** [comment]
Has the documentation been updated yet? It seems not to mention Ignition as an alternative in the docs yet.

**Comment by euank** [comment]
cc @dgonyeo, related to #1024

**Comment by dgonyeo** [comment]
Yup, this has been updated in the PR that @euank linked. It'll go live once the PR gets merged, which should hopefully happen in the next couple days.
