### ISSUE TITLE
DHCP=v6/both inside networking config doesn't enable DHCPv6

### ISSUE THREAD

**Issue by aneverov4vmw** [coreos/bugs#165]
Should work based on http://www.freedesktop.org/software/systemd/man/systemd.network.html.

Example config:

[Match]
Name=ens33

[Network]
...
DHCP=v6

**Comment by crawford** [comment]
Are you still running into this issue?

**Comment by aneverov4vmw** [comment]
I'm sorry I'm not working on this project at the moment and don't have anybody to assign to look at it. Feel free to close if it doesn't repro.

**Comment by crawford** [comment]
OK. Go ahead and reopen this if you are able to repro it in the future.
