### ISSUE TITLE
The OEM partition is supposed to be read-only

### ISSUE THREAD

**Issue by dm0-** [coreos/bugs#1651]
The OEM partition is mounted writable at `/usr/share/oem`.  It should be read-only.

```
mount | grep oem
/dev/sda6 on /usr/share/oem type ext4 (rw,nodev,relatime,seclabel,commit=600,data=ordered)
```

/cc @crawford

**Comment by marineam** [comment]
Sadly no, it has never been mounted ro and some things (rackspace) assume it is rw. At this point users also assume it is rw which may cause problems.

**Comment by crawford** [comment]
Huh, I guess I mis-remembered. I've been telling people for the longest time to remount it rw.

Do you remember how Rackspace uses that partition? Are there others that do something similar?

**Comment by marineam** [comment]
Rackspace includes a container under OEM that is executed in place. No other OEM did that because we could execute agents without a container.

**Comment by crawford** [comment]
Would we ever want control over OEM? For example, being able to push update payloads to that partition as well.

**Comment by marineam** [comment]
That would require a disk format change to add a second OEM so not really a consideration for existing systems.

**Comment by crawford** [comment]
Why would it require a second OEM?

**Comment by marineam** [comment]
If you are going to update at the block level you can't overwrite the partition while it is in use.

If the update mechanism is at the file level then OEM needs to be rw as it is already.

**Comment by marineam** [comment]
But I presume the real answer is neither and eventually use rkt some day?

**Comment by crawford** [comment]
Okay. Just exploring options.
