### ISSUE TITLE
"Domains" property inside networking config doesn't get reflected in /etc/resolv.conf

### ISSUE THREAD

**Issue by aneverov4vmw** [coreos/bugs#166]
Should work based on http://www.freedesktop.org/software/systemd/man/systemd.network.html.

Example config:

[Match]
Name=ens33

[Network]
...
Domains=foo.com

**Comment by hvolpers** [comment]
Hi,

fixed on alpha channel (see #226)

**Comment by marineam** [comment]
I can confirm that Domains= works now in the alpha channel. The feature was added in systemd 216 but we remained on 215 for quite a while.

**Comment by aneverov4vmw** [comment]
Yep, works for me too. Thanks!

The only thing is that the ordering of the Domains doesn't seem to be respected. With two entries I've got them in reverse order inside /etc/resolv.conf.
