### ISSUE TITLE
/usr/bin/coreos-install: line 402: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by yanpeipan** [coreos/bugs#1660]
# Issue Report #

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1185.3.0
VERSION_ID=1185.3.0
BUILD_ID=2016-11-01-0605
PRETTY_NAME="CoreOS 1185.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
402 line
```
    | tee >(bunzip2 --stdout >"${DEVICE}") \
```

**Comment by dm0-** [comment]
How are you executing that script?  That line is syntactically correct, and I can't reproduce the error on a fresh 1185.3.0 system.

**Comment by yanpeipan** [comment]
`sh -x /usr/bin/coreos-install -d /dev/sda -c ./cloud-config.yaml`

**Comment by dm0-** [comment]
The `coreos-install` program is a bash script, so you can't run it with `sh`.  (See the first line `#!/bin/bash`.)  You can use the following if you want to set shell flags.

    bash -x /usr/bin/coreos-install -d /dev/sda -c ./cloud-config.yaml
