### ISSUE TITLE
overcommit_memory settings with zero swap space

### ISSUE THREAD

**Issue by jeberle** [coreos/bugs#1663]
# Issue Report #

## Bug ##

The default values of `vm.overcommit_memory=0` and `vm.overcommit_ratio=50` are problematic on machines with zero swap space.

Details best explained here: [The problem with Overcommit](http://engineering.pivotal.io/post/Virtual_memory_settings_in_Linux_-_The_problem_with_Overcommit/)  
and here: [www.kernel.org/doc](<https://www.kernel.org/doc/Documentation/sysctl/vm.txt>)

### CoreOS Version ###

`VERSION=1185.3.0`

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

Bare metal

### Expected Behavior ###

`vm.overcommit_memory=2`  
`vm.overcommit_ratio=98`

### Actual Behavior ###

`vm.overcommit_memory=0`  
`vm.overcommit_ratio=50`

### Reproduction Steps ###

My workaround is to add `.conf` files to `/etc/sysctl.d/` to set these values.

**Comment by mjg59** [comment]
overcommit is still desirable, even on systems without swap. What's the problematic behaviour you're seeing?

**Comment by jeberle** [comment]
The OOM killer is being invoked in cases with very little memory pressure: cache memory might be high, but actual user memory is quite low.

If you want to close this out as NAB, that's fine. I originally thought setting `0` used the value set in `overcommit_ratio`, e.g. `50`, but after reading more, it apparently is only used w/ setting `2`.

**Comment by mjg59** [comment]
Yeah, the right config here is workload dependent. I suspect some of the other vm tunables might help you, but if you're happy with never overcommitting then 2 is a reasonable choice (cost is that you'll have a bunch of RAM allocated that will probably never get used)

**Comment by jeberle** [comment]
Thank you.
