### ISSUE TITLE
wrong selinux context for container processes

### ISSUE THREAD

**Issue by lian** [coreos/bugs#1664]
# Issue Report #

## Bug ##
container processes don't get their own selinux context anymore.

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1185.3.0
VERSION_ID=1185.3.0
BUILD_ID=2016-11-01-0605
PRETTY_NAME="CoreOS 1185.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

tested on latest alpha too. same issue

### Environment ###

```
EC2 AMI and coreos_production_iso_image.iso
```

### Expected Behavior ###
running at least one container `ps -eZ` shows `system_u:system_r:svirt_lxc_net_t:...` for container processes.

### Actual Behavior ###
running at least one container `ps -eZ` is all `system_u:system_r:kernel_t:s0`

### Other Information ###
`/var/lib/docker/containers/*/configv2.json` field `ProcessLabel` shows the expected `system_u:system_r:svirt_lxc_net_t:...`. seems container processes don't have that context assigned properly

**Comment by lian** [comment]
more debugging/understanding..

docker:
`cat /var/lib/docker/containers/*/config.v2.json` contains the right `ProcessLabel = system_u:system_r:svirt_lxc_net_t:s0:...`

runc:
`cat /run/docker/libcontainerd/*/config.json` contains the right `selinuxLabel = system_u:system_r:svirt_lxc_net_t:s0:...`

docker run:
`docker run -it --rm=true alpine:3.3 sh -c "top"` fails with `ps -eZ |grep top` = `system_u:system_r:kernel_t:s0`

runc exec: (forcing process label)
`runc exec --process-label system_u:system_r:svirt_lxc_net_t:s0:c689 <docker-run-id> sh -c "top"` fails with `ps -eZ |grep top` = `system_u:system_r:kernel_t:s0`

**Comment by lian** [comment]
`cat /etc/selinux/mcs/contexts/lxc_contexts` contains `process = "system_u:system_r:svirt_lxc_net_t:s0"`

**Comment by mjg59** [comment]
Does this work with rkt? Are you seeing any avc denials in the logs?

**Comment by lian** [comment]
@mjg59 haven't tried rkt. no avc in auditd logs. are you able to reproduce it?

**Comment by mjg59** [comment]
Currently working on something else, so it'll take me a little while to bring up a test environment

**Comment by lian** [comment]
glad for any help or pointers. security wise, aren't able roll all our production machines to this potentially broken selinux runc containers.

**Comment by lian** [comment]
@mjg59 were you able to confirm the issue by now? and have any thoughts on fixing or workaround?

**Comment by mjg59** [comment]
Should be fixed in https://github.com/coreos/coreos-overlay/commit/6ecf3a40296d37e059533dbcae936f39e42ff586

**Comment by lian** [comment]
@mjg59 awesome, thanks!

**Comment by einyx** [comment]
This is happening *still* on latest stable and alpha releases
