### ISSUE TITLE
update_engine_client -update reports "Update failed" if there's no new version

### ISSUE THREAD

**Issue by dontub** [coreos/bugs#1665]
# Issue Report #

$ update_engine_client -update
reports "Update failed" if there's no new version available. This indicates that something went wrong, though it doesn't. Instead there should be printed something like "No update available". A special exit code (not 0 or 1) for this case would be nice.

### CoreOS Version ###

$ cat /etc/os-releaseNAME=CoreOS
ID=coreos
VERSION=1185.3.0
VERSION_ID=1185.3.0
BUILD_ID=2016-11-01-0605
PRETTY_NAME="CoreOS 1185.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
