### ISSUE TITLE
update_engine_client: LAST_CHECKED_TIME not updated if there's no new version

### ISSUE THREAD

**Issue by dontub** [coreos/bugs#1666]
# Issue Report #

$ update_engine_client -check_for_update
doesn't update `LAST_CHECKED_TIME` if there's no new version.

### CoreOS Version ###

$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1185.3.0
VERSION_ID=1185.3.0
BUILD_ID=2016-11-01-0605
PRETTY_NAME="CoreOS 1185.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**Comment by crawford** [comment]
As far as I know, this has never worked. What issues are you running into as a result?

**Comment by dontub** [comment]
Reboot strategy is `off`.
$ update_engine_client -check_for_update
... some time in between
$ update_engine_client -status
The status output is the same as before check_for_update. How can I know if something failed or just no new version is available without looking in the journal?

**Comment by crawford** [comment]
Big picture: what are you trying to do? Update engine will periodically check for updates and let you know via dbus once it has installed a newer version.
