### ISSUE TITLE
fleet: create a fleet wrapper and replace docs upstream

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1669]
## Feature Request ##

Currently CoreOS ships /usr/bin/fleet on the host system. This has made it difficult to ship breaking changes or allow users to pin to a particular release. Lets run fleet under rkt instead to make it easier for users to move forward.

@dongsupark is working on the making the Docker image available https://github.com/coreos/fleet/pull/1707.

Then it is as simple as creating the script and bind-mounting in the systemd control unix socket.

**Comment by philips** [comment]
@dongsupark could you take this on as well? 

You can see the kubelet-wrapper here: https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper

**Comment by dongsupark** [comment]
@philips Yes, I will do. Thanks for the pointer to kubelet-wrapper.

**Comment by crawford** [comment]
Just to be clear on the game-plan here, we are going to write up documentation showing the wrapper script and service unit that are required to make this work. We aren't going to actually ship those in the OS. The user will need to write those files to their system (via Ignition) before they can use the rkt-powered fleet.
