### ISSUE TITLE
kexec'd kernel fails to locate RSDP on an EFI system

### ISSUE THREAD

**Issue by vcaputo** [coreos/bugs#167]
Others have experienced similar issues surrounding kdump on efi systems:
http://lists.infradead.org/pipermail/kexec/2012-October/006924.html
http://lists.infradead.org/pipermail/kexec/2010-March/003889.html

A simple solution seems to be adding the following to the kernel cmdline supplied via kexec in bootengine on efi systems:

acpi_rsdp=$(grep -m1 ^ACPI /sys/firmware/efi/systab | cut -f2- -d=)

**Comment by nh2** [comment]
Note that this also helps when you're running a kernel started via `kexec` and `poweroff` does not work, and dmesg prints and hangs at:

```
reboot: System halted
```

Passing the mentioned kernel parameter during the `kexec` invocation allows the kexec'ed kernel to `poweroff` in that case.

**Comment by nh2** [comment]
While the above is a workaround, I have now identified two bugs in kexec that made it necessary in my case, and proposed patches to fix them at http://lists.infradead.org/pipermail/kexec/2019-April/022964.html
