### ISSUE TITLE
Bump to rkt 1.19.0

### ISSUE THREAD

**Issue by stuart-warren** [coreos/bugs#1670]
# Issue Report #

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

Openstack

### Desired Feature ###

Can we get the latest release of rkt in the next alpha?
https://github.com/coreos/rkt/releases/tag/v1.19.0
I was disappointed to not see it in v1235.0.0

Mainly for this fix which allows us to use private docker images
coreos/rkt#3356

**Comment by mischief** [comment]
the next alpha is due for dec 1, at which point rkt 1.20 should be out, so let's just wait for that.
