### ISSUE TITLE
systemd-tmpfiles-setup.service: Duplicate line for path "/var/lib" and "/var/lib/tpm"

### ISSUE THREAD

**Issue by f0** [coreos/bugs#1672]
# Issue Report #
journalctl -u systemd-tmpfiles-setup.service

Nov 21 13:16:58 xxx.example.net systemd-tmpfiles[34968]: [/usr/lib64/tmpfiles.d/trousers.conf:1] Duplicate line for path "/var/lib/tpm", ignoring.
Nov 21 13:16:58 xxx.example.net systemd-tmpfiles[34968]: [/usr/lib64/tmpfiles.d/var.conf:20] Duplicate line for path "/var/lib", ignoring.

### CoreOS Version ###
```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1122.3.0
VERSION_ID=1122.3.0
BUILD_ID=2016-10-20-2045
PRETTY_NAME="CoreOS 1122.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by bgilbert** [comment]
This appears to be fixed in current alpha (1298).  Thanks for the report.
