### ISSUE TITLE
Failing to get IPV4 address from Openstack consistently

### ISSUE THREAD

**Issue by stensonb** [coreos/bugs#1673]
# Issue Report #

booting CoreOS alpha in Openstack (via ISO in glance) fails to acquire ipv4 address consistently.

## Bug ##
<img width="734" alt="failed to get ipv4" src="https://cloud.githubusercontent.com/assets/933389/20504452/593a2896-affc-11e6-80c4-f0fdf1a0bbef.png">
<img width="733" alt="got ipv4 address" src="https://cloud.githubusercontent.com/assets/933389/20504453/594082e0-affc-11e6-80c4-090f3b75e36a.png">

### CoreOS Version ###

CoreOS alpha (currently 1235.0.0)

### Environment ###

Openstack Juno

### Expected Behavior ###

booting the ISO, CoreOS should assign eth0 the IP address given by the openstack metadata service every time.

### Actual Behavior ###

~50% of the time, the expected IP address assigned via Openstack is NOT assigned to the CoreOS box.

### Reproduction Steps ###

  1. load the CoreOS alpha ISO as a glance image in Openstack
  2. provision a new VM using the image
  3. navigate through Openstack to the VM console
  4. post-boot, observe the login prompt has eth0 listed:
     a. sometimes with the correct/expect ipv4 IP
     b. sometimes with just an ipv6 address

### Known workaround ###
- a reboot (or several, until the ipv4 address shows on the console login screen) seems to solve this...

### Other Information ###

- VMs built with other linux guest OSes get the correct IP address every time on this Openstack cluster (ubuntu 14.04)

(see attached screenshots of the VM console when the instance gets an IP address successfully vs. when it does not)

**Comment by stensonb** [comment]
I should note this is a stock image, with NO additional user-data (cloud-init) being supplied.

**Comment by crawford** [comment]
The network configuration on OpenStack is managed by DHCP. Can you check to see if networkd is successfully getting a lease?

**Comment by stensonb** [comment]
here are logs from a "failed" boot (didn't get a ipv4 address): https://gist.github.com/stensonb/4aa9baac522d4d639de912b45062a16e

here are logs from a "successful" boot (got a ipv4 address): https://gist.github.com/stensonb/0a273c0cff58d52be1f85b6410134b9d

i'm looking into increasing verbosity of the systemd-networkd logs to find out more...

**Comment by crawford** [comment]
You can create a drop-in for `systemd-networkd.service` with the following:

```INI
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by stensonb** [comment]
I saw that, thanks.  I've added comments (with more verbose logs) to both of those gists...

The logs indicate it might be an openstack DHCP server causing trouble here...perhaps related to this: https://review.openstack.org/gitweb?p=openstack/neutron.git;a=commitdiff;h=0241176d0a81577b13a7139c9b55af0e2f31f2ce

(working with our openstack team now...i'll be sure to update this ticket if/when i learn more)

**Comment by stensonb** [comment]
Looks like this is a known Openstack bug (apparently a dhcp database issue)...apparently CoreOS is more strict (which is good), compared to debian/ubuntu about where it's DHCP leases come from (which is why is "works" on debian/ubuntu, and doesn't on CoreOS).

Closing for now.  I'll update this thread with a link to the Openstack bug when I track it down.
