### ISSUE TITLE
AWS images for 1235.0.0 are not available.

### ISSUE THREAD

**Issue by monder** [coreos/bugs#1674]
# Issue Report #

## Bug ##

AWS images are not available.

### Expected Behavior ###

I'm able to run latest version of CoreOS specified in https://alpha.release.core-os.net/amd64-usr/current/
(https://alpha.release.core-os.net/amd64-usr/current/coreos_production_ami_all.json to be exact)

### Actual Behavior ###

AMIs specified in JSON are not available.

### Reproduction Steps ###

1. Open https://coreos.com/os/docs/latest/booting-on-ec2.html#alpha
2. Click any region/link
3. <img width="671" alt="screen shot 2016-11-22 at 15 01 52" src="https://cloud.githubusercontent.com/assets/232147/20524893/7165f476-b0c5-11e6-9565-17a0adcb8c8c.png">

### Other Information ###
I'm relying on that information to launch up-to-date spot instance fleet.
CoreOS update model is not compatible with spot instances that are created and destroyed frequently,  I can "follow" some initial ami, but then the boot process of the instance will take ~hour for it to boot from some old template, download all docker/rkt images, find out that is not the latest version, wait for reboot, reboot and update, try to launch whole rkt/docker again. And with the clustering and all volume mounting/unmounting balancing, instance spends most of the time doing that instead of processing the data it was launched for.
My solution is to disable autoupdate and always create the up-to-date versions. For that I need the reliable source of ami ids.

**Comment by jdnurmi** [comment]
One way to automate this is to hook the JSON feed for alpha (or your channel of choice) up to a lambda function and feed your CFN template that way;  For a nominal cost, coreos could provide such a function publicly, but it doesn't fix the issue that right now -- that both the page and the feed point to an AMI that's unavailable (I got here because of the same issue wth the 1235 AMI being unavailable globally).

**Comment by crawford** [comment]
Sorry about that. This is entirely my fault. The AMIs should be available now.

**Comment by jdnurmi** [comment]
Can confirm both as visible in us-east-1 and a few other spot checked regions - thanks!
