### ISSUE TITLE
Make kernel debug doable

### ISSUE THREAD

**Issue by uzytkownik** [coreos/bugs#1679]
Currently it is next-to-impossible to debug kernel in CoreOS. The /usr partition is hard read-only and I had no success in removing the flag using tune2fs. It would be nice if there was a version provided for kernel debug.

**Comment by crawford** [comment]
Our [SDK guide](https://coreos.com/os/docs/latest/sdk-modifying-coreos.html) can be used to build a development version of CoreOS. Why do you need write access to `/usr`? We tend to use bind mounts or overlayfs to "add" things into that filesystem.

**Comment by uzytkownik** [comment]
I need to update `/lib/modules` presumably very early in the boot process (as it is where overlayfs module is located). Recreating whole `/usr` seems to be an overkill.

**Comment by dm0-** [comment]
Can you use the documentation at https://coreos.com/os/docs/latest/kernel-modules.html to make changes to `/lib/modules`?  You can adjust the dependencies of `lib-modules.mount` to use your changes as early as needed.

Or maybe you can just append `modprobe.blacklist=...` to the kernel command-line to prevent loading whatever modules you're modifying, then manually load your versions later.

**Comment by uzytkownik** [comment]
Not directly though it gave me an idea. The problem is that I'm trying to build a new kernel (vmlinux) with kgdb enabled so I need to somehow load `overlayfs`. However I guess I could inject insmod very early into boot process and use overlayfs from there on.

**Comment by dm0-** [comment]
Okay, I think I see what you're doing now.  When I run similar setups (replacing the entire kernel + modules), I just bind mount over `/lib/modules` instead.  I don't think it is necessary to load any modules to do that, so maybe that would work for you.

The following is the mount unit I use.  Adjust the `/opt`-related paths/mounts as needed.

    [Unit]
    Description=Custom Kernel Modules
    ConditionPathExists=/opt/coreos/modules/%v
    After=opt.mount
    Wants=opt.mount
    
    [Mount]
    What=/opt/coreos/modules
    Where=/lib/modules
    Options=ro,bind

Here are some (possibly outdated) notes on how I built a modified CoreOS kernel, if that helps make sense of the above: https://gist.github.com/dm0-/1f656b68491cd22e65ae0f33d4f1dd25

**Comment by uzytkownik** [comment]
Hmm. When I try to boot qemu it refuses to boot. Is the qcow2 image EFI-only>
![screenshot](https://cloud.githubusercontent.com/assets/5706/21079003/953bc976-bf38-11e6-98f9-4e94e7c370d9.png)

**Comment by dm0-** [comment]
It shouldn't be UEFI-only, except maybe for arm64.  You could also try a raw disk image, e.g. https://alpha.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2 .

**Comment by uzytkownik** [comment]
I managed to boot using qemu disk (I misconfigured libvirt) but it looks like dracut is unable to mount / using new kernel. It looks like `update-bootengine` passes to not include kernel modules. I rest my case that CoreOS should have easier kernel debug.

**Comment by dm0-** [comment]
You need to specify the kernel version with `update-bootengine -k`.

**Comment by uzytkownik** [comment]
Ok. I managed to boot though I need to modify grub commandline as /dev/mapper/usr does not exists and vmlinuz with debug information was too large to fit onto /boot. Where is grub.cfg located?

**Comment by dm0-** [comment]
The kernel command-line can be modified by writing `set linux_append="..."` in `/usr/share/oem/grub.cfg`.

https://coreos.com/os/docs/latest/other-settings.html#adding-custom-kernel-boot-options

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
