### ISSUE TITLE
CoreOS Linux: consider using ntp.google.com as default

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1686]
## Feature Request ##

Google's new NTP servers provide smeared time which is a useful way of avoiding bugs. Consider using these servers instead of the default ntp.org servers today.

https://developers.google.com/time/

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
