### ISSUE TITLE
Improve RAID docs

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1688]
# Issue Report #

### Environment ###

All

### Desired Feature ###

Right now the RAID docs mention how to create and assemble a RAID array, which works fine on the first boot. On subsequent boots, the array is not automatically mounted. `rd.auto` is needed to tell the initramfs to automatically assemble the arrays. This also requires the partitions to have the correct typecode.

**Comment by ajeddeloh** [comment]
This was only an issue with root-on-raid, right? Data volumes should not need `rd.auto` or the correct type GUID.

**Comment by dgonyeo** [comment]
I believe so, although I don't think I had realized that when I first wrote this.

**Comment by ajeddeloh** [comment]
Ok. I'm closing this since we added documentation for root-on-raid and the existing documentation for data raid works on subsequent boots.
