### ISSUE TITLE
Enable XFS quota config in the coreos builds by default.

### ISSUE THREAD

**Issue by imkin** [coreos/bugs#1691]
# Issue Report #
While trying to mount an xfs device with quota enabled it does not understand the `prjquota` option. 

When I digged further found that the xfs quota was not enabled.

```
bash-4.3# mount -o prjquota /dev/sdc1 /data/
mount: wrong fs type, bad option, bad superblock on /dev/sdc1,
missing codepage or helper program, or other error

In some cases useful info is found in syslog - try
dmesg | tail or so.
```

### CoreOS Version ###
```
bash-4.3# cat /etc/lsb-release
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=1122.3.0
DISTRIB_CODENAME="MoreOS"
DISTRIB_DESCRIPTION="CoreOS 1122.3.0 (MoreOS)"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?
```
vmware/vsphere
```
### Expected Behavior ###
the xfs quota should be enabled.

### Reproduction Steps ###

 ```
bash-4.3# mkfs.xfs -L media <device>
bash-4.3# mount -o prjquota <device> <dir>
mount: wrong fs type, bad option, bad superblock on <dev>,
missing codepage or helper program, or other error

In some cases useful info is found in syslog - try
dmesg | tail or so.
  2. cat /usr/boot/config | grep XFS
CONFIG_XFS_FS=m
# CONFIG_XFS_QUOTA is not set
CONFIG_XFS_POSIX_ACL=y
# CONFIG_XFS_RT is not set
# CONFIG_XFS_WARN is not set
# CONFIG_XFS_DEBUG is not set
# CONFIG_VXFS_FS is not set
```
## Feature Request ##
enable xfs quota by default

**Comment by imkin** [comment]
Does any one have any comments?

**Comment by crawford** [comment]
Fixed in https://github.com/coreos/coreos-overlay/pull/2312.

**Comment by imkin** [comment]
Can we get this up on beta and stable channels soon?
@mischief @crawford

**Comment by dm0-** [comment]
It is in both beta and stable.

**Comment by lucab** [comment]
note to self: ext4 gained support for prjquota in [4.5](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=689c958cbe6be4f211b40747951a3ba2c73b6715), toggled via `CONFIG_QUOTA` (`y` in current CL [config](https://github.com/coreos/coreos-overlay/blob/32f13c016518cbea5bdac6d87495f2415a9f0671/sys-kernel/coreos-modules/files/commonconfig-4.10#L741)).

**Comment by imkin** [comment]
@lucab is it available in stable/beta right now. :-)

**Comment by lucab** [comment]
@imkin yes. However, the ext4 tools are not recent enough to support the "project" option (so mkfs.ext4 can't create one locally).
