### ISSUE TITLE
Ignition QEMU firmware config fails to load via libvirt pass-through

### ISSUE THREAD

**Issue by dghubble** [coreos/bugs#1693]
# Issue Report #

## Bug ##

I've been able to modify coreos_production_qemu.sh to allow Ignition with the new `-fw_cfg` option added in Ignition v0.12.0 and CoreOS 1235.1.0.

Using libvirt's QEMU command pass-through for `-fw_cfg name=opt/com.coreos/config,file=/absolute/path/coreloko/hello.ign`, the file is mounted and contains the expected contents, but Ignition doesn't pick it up.

I'd expect these two approaches to work nearly identically since the arguments are "passed through".  I suspect we've never tried to use the `fg_cfg` feature this way before.

### CoreOS Version ###

1235.1.0

Ignition v0.12.0

### Environment ###

libvirt

### Actual Behavior ###

```
    Dec 05 10:24:20 localhost ignition[405]: Ignition v0.12.0
    Dec 05 10:24:20 localhost ignition[405]: parsed url from cmdline: ""
    Dec 05 10:24:20 localhost ignition[405]: no config URL provided
    Dec 05 10:24:20 localhost ignition[405]: op(1): [started]  loading QEMU firmware config module
    Dec 05 10:24:20 localhost ignition[405]: op(1): executing: "modprobe" "qemu_fw_cfg"
    Dec 05 10:24:20 localhost ignition[405]: op(1): [finished] loading QEMU firmware config module
    Dec 05 10:24:20 localhost ignition[405]: QEMU firmware config was not found. Ignoring...
    Dec 05 10:24:20 localhost ignition[405]: parsing config:
    Dec 05 10:24:20 localhost ignition[405]: failed to fetch config: not a config (empty)
    Dec 05 10:24:20 localhost ignition[405]: not a config (empty): ignoring user-provided config
```

```
ls -al /sys/firmware/qemu_fw_cfg/by_name/opt/com.coreos/config/
    -r--------.  1 root root 4096 Dec  5 10:43 key
    -r--------.  1 root root 4096 Dec  5 10:43 name
    -r--------.  1 root root    0 Dec  5 10:43 raw
    -r--------.  1 root root 4096 Dec  5 10:43 size
```

Is the file permission / size wrong perhaps?

Ignition contents are added to firmware as I'd expect.

```
# cat /sys/firmware/qemu_fw_cfg/by_name/opt/com.coreos/config/raw
{
  "ignition": { "version": "2.0.0" },
  "systemd": {
    "units": [{
      "name": "example.service",
      "enable": true,
      "contents": "[Service]\nType=oneshot\nExecStart=/usr/bin/echo Hello World\n\n[Install]\nWantedBy=multi-user.target"
    }]
  },
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa pubkey"
        ]
      }
    ]
  }
}
```

cc @dm0- @crawford

**Comment by dghubble** [comment]
To reproduce: https://github.com/dghubble/coreloko

**Comment by dghubble** [comment]
Stopping in initramfs and invoking Ignition directly, it seems to pick up the Ignition config. Probably fails because I'm not invoking Ignition at the usual step.

```
switch_root:/# ignition --oem=qemu --stage=files
[  484.439286] ignition[506]: Ignition v0.12.0
[  484.446250] ignition[506]: files: createUsers: op(1): [started]  adding ssh keys to user "core"
[  484.456204] ignition[506]: files: createUsers: op(1): [failed]   adding ssh keys to user "core": no such file or directoryswitch_root:/# 
[  484.461705] ignition[506]: files: failed to create users/groups: failed to create users: failed to add keys to user "core": no such file or directory
```

```
switch_root:/# cat /run/ignition.json 
{"ignition":{"version":"2.0.0","config":{}},"storage":{},"systemd":{"units":[{"name":"example.service","enable":true,"contents":"[Service]\nType=oneshot\nExecStart=/usr/bin/echo Hello World\n\n[Install]\nWantedBy=multi-user.target"}]},"networkd":{},"passwd":{"users":[{"name":"core","sshAuthorizedKeys":["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt3BebCHqnSsgpLjo4kVvyfY/z2BS8t27r/7du+O2pb4xYkr7n+KFpbOz523vMTpQ+o1jY4u4TgexglyT9nqasWgLOvo1qjD1agHme8LlTPQSk07rXqOB85Uq5p7ig2zoOejF6qXhcc3n1c7+HkxHrgpBENjLVHOBpzPBIAHkAGaZcl07OCqbsG5yxqEmSGiAlh/IiUVOZgdDMaGjCRFy0wk0mQaGD66DmnFc1H5CzcPjsxr0qO65e7lTGsE930KkO1Vc+RHCVwvhdXs+c2NhJ2/3740Kpes9n1/YullaWZUzlCPDXtRuy6JRbFbvy39JUgHWGWzB3d+3f8oJ/N4qZ cardno:000603633110"]}]}}
```

**Comment by euank** [comment]
Reading the ignition section of that readme, it sounds like the process is "boot, shut down, add ignition config file, boot again".

Since ignition will only run on the first boot (excluding cases when coreos.first_boot is overridden), it seems like it's working as intended.

By applying the following diff:

```
diff --git a/coreloko b/coreloko
index a472f99..0bc5f1f 100755
--- a/coreloko
+++ b/coreloko
@@ -105,7 +105,7 @@ function create {
 function create_vm {
   NODE=$1
   create_disk $NODE
-  virt-install --connect qemu:///system \
+  xml=$(virt-install --connect qemu:///system \
       --name $NODE \
       --vcpus=1 \
       --memory=1024 \
@@ -115,7 +115,9 @@ function create_vm {
       --boot hd \
       --os-type=linux \
       --os-variant=generic \
-      --noautoconsole
+      --noautoconsole \
+      --print-xml)
+  virsh define <(echo $xml)
 }
 
 function create_disk {
```

and then running through the ignition instructions on that repo (`virsh edit`, etc) I was able to observe example.service print hello world.

Perhaps coreloko shouldn't use virt-install, but should rather use something capable of generating the full xml domain, including needed ignition config stuff.

**Comment by dghubble** [comment]
Revisiting this, @euank is right. If we can define the right XML domain (and inject the `fw_cfg` pass-through) upfront then Ignition does run the config on first boot. The boot, shutdown, add pass-through, reboot was a hack to get the `fw_cfg` but `--print-xml` works to avoid creation.

I'm still thrown off that in the initial report, the Ignition logs are from *after* reboot. If the disk uuid is already marked to indicate "not first disk boot", I'm surprised it tries to run at all.

> Perhaps coreloko shouldn't use virt-install, but should rather use something capable of generating the full xml domain, including needed ignition config stuff.

Absolutely. Unfortunately, none of these libvirt tools are aware of QEMU's `-fw_cfg` feature. For now, I've updated the example to use the virsh define and added some sed lines to inject in the right XML until libvirt has direct support for QEUM firmware config. Its gross, but it works and saves the user some trouble.

Thanks!
