### ISSUE TITLE
Install to Disk feature does not correctly partition large disks

### ISSUE THREAD

**Issue by z3net** [coreos/bugs#1696]
# Issue Report #
Install to Disk feature does not correctly partition large disks 
### CoreOS Version ###
Stable 1185.3.0

### Environment ###

Bare Metal / Dell 730xd 12 drive Perc raid 6 12x8tb seagate
### Expected Behavior ###
Root partition sda9 should be entire size of dev/sda9 which in my case is 72.8TB

### Actual Behavior ###
Instead it partitions it as 2GB partition:
/dev/sda9       2.0G  230M  1.7G  13% /

### Reproduction Steps ###

  1. ...Install coreos to a large raid 6 array
  2. ...

### Other Information ###
mkfs.ext4 may also need to be upgraded to support large disks over 16tb. 
### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

**Comment by crawford** [comment]
`coreos-install` is effectively a nice wrapper around `curl`, `gpg`, and `dd`. It just writes the image, bit for bit, to the disk. On boot, the OS will recognize that it can expand its root partition to fill the disk, so it should grow larger after that first boot. How large is the root partition after the first boot?

**Comment by z3net** [comment]
root partition after the first boot is 2GB

**Comment by crawford** [comment]
Okay, that might be because `mkfs.ext4` doesn't know what do do with 72 TB. Are there any failed services after the boot completes? It'll take me some time to get a hold of that much storage, so I can test and fix this.

**Comment by marineam** [comment]
Probably best to use ignition to reformat with XFS though, even if ext4 can handle volumes that big these days I suspect it is a bit of a stretch.

**Comment by z3net** [comment]
From what I hear XFS Recovery tools are not up to par.  I may end up
booting these boxes bare metal via pxe or usb since I don't have any drive
bays left for a boot ssd and I also cannot boot off my intel pcie nvme
device.  I understand I will then need to manage updates on my own which
sorta takes away a core feature of coreos. pxe option sounds easier than a
usb key for managing updates.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
