### ISSUE TITLE
document or change journald rate limit defaults

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1697]
### Desired Feature ###

Lots of people complain about journald locking up on them. As a solution perhaps we set an even lower limit on number of logs per second per service in journald.conf.

Docs: https://www.freedesktop.org/software/systemd/man/journald.conf.html#RateLimitIntervalSec=

I believe this is what other distros do.

**Comment by vcaputo** [comment]
@philips I did a casual search of the issues and didn't see evidence of this, where would one look to understand and characterize those complaints?

Is it actual lockups or just more of the watchdog timer killing journald?  If it's the latter, just disable the watchdog for journald in coreos.

**Comment by crawford** [comment]
@vcaputo we have a few users on old versions of CoreOS (before all of your journald fixes) that are hitting this. I'm confident that they'll see huge improvements just by updating.

As far as I can tell, it's just the watchdog timer killing journald. I don't remember the internals, so I'm not sure how long one pass of the event loop needs to take in order for the watchdog to starve.

**Comment by crawford** [comment]
> I don't remember the internals, so I'm not sure how long one pass of the event loop needs to take in order for the watchdog to starve.

```c
sd_event_add_time(s->event, &s->watchdog_event_source, CLOCK_MONOTONIC, now(CLOCK_MONOTONIC) + s->watchdog_usec/2, s->watchdog_usec/4, dispatch_watchdog, s);
```

Given a three-minute watchdog, it looks like a 45-second operation could starve the watchdog.

**Comment by vcaputo** [comment]
@crawford I see, well, they could always disable the watchdog or just increase the timeout in the interim.

**Comment by crawford** [comment]
I'd rather us fix performance issues than document workarounds that will hide the issue. If users are hitting this on the **latest** version of Container Linux, please file a new issue.
