### ISSUE TITLE
Unit with After=network-online.target starts up before an IP is on the interface

### ISSUE THREAD

**Issue by jayofdoom** [coreos/bugs#170]
Details are here: https://gist.github.com/jayofdoom/f4bb69b3d35e4646e2a7

**Comment by crawford** [comment]
@jayofdoom is this still an issue in the later versions of CoreOS?

**Comment by mischief** [comment]
in current coreos, network-online.target by default depends on systemd-networkd-wait-online.service, which waits for all configured links to get a carrier, so this should not be a problem any more. leave a message if this is still a problem and we can take another look.

**Comment by Moolica23** [comment]
I'm still having a similar problem while running coreos using matchbox

**Comment by crawford** [comment]
@Moolica23 can you file a new issue, detailing what you are seeing?

**Comment by Moolica23** [comment]
Sure, here's the link: [https://github.com/coreos/bugs/issues/1966](url)
