### ISSUE TITLE
Empty cgroups left behind by docker

### ISSUE THREAD

**Issue by guoshimin** [coreos/bugs#1700]
# Issue Report #

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=899.1.0
VERSION_ID=899.1.0
BUILD_ID=2015-12-18-0004
PRETTY_NAME="CoreOS 899.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

AWS

### Expected Behavior ###
Cgroups created by docker cleaned up after the container exits

### Actual Behavior ###
Some empty cgroups are left behind. They have names like ` /sys/fs/cgroup/devices/system.slice/docker-122fb452a2062d6305e6c18fe9e2996ca96082f25fbd24304d4c5387ed1e1611.scope`

### Reproduction Steps ###

I don't have specific steps to reproduce, but we have a kubernetes cluster of around 20 nodes, and the nodes have been running for 1-3 months. Most of the nodes are exhibiting the problem.

### Other Information ###
We are running Kubernetes 1.3.8 on CoreOS v899 nodes. We are also hitting the problem described in https://github.com/docker/docker/issues/5618.

**Comment by crawford** [comment]
Starting in [1151.0.0](https://coreos.com/releases/#1151.0.0), we started using the default Docker cgroup driver. Can you give that version a shot and see if the problem still occurs?

**Comment by guoshimin** [comment]
We are somewhat stuck with docker 1.9 at the moment. Just wanted to check if there was an easy fix or if this was an known issue.  We will try upgrading.

**Comment by crawford** [comment]
Since this is such an old version and so many bugs have been fixed since then, I'm going to close this out. Feel free to re-open it if the upgrade doesn't help.
