### ISSUE TITLE
toolbox depends on running Docker daemon

### ISSUE THREAD

**Issue by GreatSUN** [coreos/bugs#1704]
# Issue Report #
When trying to use toolbox on our Kubernetes clusters running on rkt, we see that we would either have to run the Docker daemon or to setup the Containers our self.

As discussed with @euank 

## Bug ##
Toolbox should not be depending on a running Docker daemon, instead it would be nicer if Toolbox would make use of rkt which basically doesn't require anything.

### CoreOS Version ###
ALL

BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

### Environment ###
Kubernetes 1,4.6
rkt 1.21.0

What hardware/cloud provider/hypervisor is being used to run CoreOS?
Bare metal

### Expected Behavior ###
Toolbox is not depending on running Docker daemon

### Actual Behavior ###
Toolbox is only working when Docker is enabled

### Reproduction Steps ###
Run toolbox after disabling Docker

## Feature Request ##
Make Toolbox independent from Docker

### Desired Feature ###
Toolbox is independent from Docker

**Comment by glevand** [comment]
For this change to work on arm64 we need https://github.com/coreos/rkt/issues/3526 (fetch: arch messed up) fixed.
