### ISSUE TITLE
Could not generate persistent MAC address for veth94c4d7b

### ISSUE THREAD

**Issue by kbingham** [coreos/bugs#1705]
# Issue Report #

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1248.1.0
VERSION_ID=1248.1.0
BUILD_ID=2016-12-07-0251
PRETTY_NAME="CoreOS 1248.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

Digital Ocean
https://cloud.digitalocean.com/

### Expected Behavior ###

Systemd unit file  (http://paste.ubuntu.com/23620619/) expected to start nginx-proxy container

### Actual Behavior ###

The container is continually relaunched, and fails to start.
Journalctl -ex logs (http://paste.ubuntu.com/23620664/) seem to show issues 
such as "systemd-udevd[18203]: Could not generate persistent MAC address for veth94c4d7b: No such file or directory"
This looks like it is / related to https://github.com/systemd/systemd/issues/3374

### Reproduction Steps ###

  1.  Paste unit file from http://paste.ubuntu.com/23620619 into /etc/systemd/system/nginx-proxy.service

  2. sudo systemctl daemon-reload
  3. systemctl start nginx-proxy

### Other Information ###

This looks like it is / related to https://github.com/systemd/systemd/issues/3374

**Comment by crawford** [comment]
Your service type is notify, which doesn't seem correct.
