### ISSUE TITLE
Systemd oneshot service called by timer periodically gets stuck

### ISSUE THREAD

**Issue by marclennox** [coreos/bugs#1708]
# Issue Report #

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1185.5.0
VERSION_ID=1185.5.0
BUILD_ID=2016-12-07-0937
PRETTY_NAME="CoreOS 1185.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"```
```

### Environment ###

AWS EC2 T2.Small

### Expected Behavior ###

Systemd one shot service gets executed by timer every 15 seconds.

### Actual Behavior ###

Systemd one shot service seems to periodically (once every couple of days) get "stuck" and prevents further timers from triggering.

In order to unblock it, we have to manually stop the systemd service (which takes about 30 seconds to complete).

### Other Information ###

This started happening in the past month, prior to this things were working for the previous 2 years with no issues using the same systemd trigger and service.  Here are the relevant files, please advise how to debug this further.

```
$ systemctl | grep trigger
trigger-background-job@equipment_visit_session_timeout.service loaded activating start     start Background job trigger service

```

```
$ systemctl list-timers | grep trigger
NEXT                         LEFT                LAST                         PASSED       UNIT                                                         ACTIVATES
Fri 2016-12-09 18:24:05 UTC  4 days ago          Fri 2016-12-09 18:24:20 UTC  4 days ago   trigger-background-job@equipment_visit_session_timeout.timer trigger-background-job@equipment_visit_
```

```
$ cat /var/run/systemd/system/trigger-background-job@equipment_visit_session_timeout.timer
[Unit]
Description=Background equipment visit session timeout job trigger timer

[Timer]
OnCalendar=*-*-* *:*:5,20,35,50
```

```
$ cat /var/run/systemd/system/trigger-background-job@.service
[Unit]
Description=Background job trigger service
Wants=ambassador.service

[Service]
User=root
Type=oneshot
ExecStart=/opt/bin/trigger-background-job %i
```

**Comment by dm0-** [comment]
From that service file and the behavior you describe, it sounds like your `trigger-background-job` program is hanging.  I don't know what that program does, so you would have to consult its documentation for how to debug it.  A `Type=oneshot` service has no timeout by default, so I'd suggest appending `TimeoutStartSec=15` (or however long you want to give it) to avoid it locking up your timer.

**Comment by marclennox** [comment]
OK thanks, the timeout will work well for this use-case.  I initially misunderstood the systemd documentation, thinking that you could not specify a timeout for oneshot, but I see now that you indeed can.

**Comment by dm0-** [comment]
Closing this, as it sounds like a problem with a third-party program.
