### ISSUE TITLE
DownloadAction fails because of  "payload verification error"

### ISSUE THREAD

**Issue by je-al** [coreos/bugs#1711]
# Issue Report #

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1068.10.0+2016-08-31-1023
VERSION_ID=1068.10.0
BUILD_ID=2016-08-31-1023
PRETTY_NAME="CoreOS 1068.10.0+2016-08-31-1023 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

A VS on SoftLayer's cloud

### Expected Behavior ###

Update to the latest stable release

### Actual Behavior ###

Update fails

### Other Information ###
Attached you'll find the logs from update-engine (I've manually shortened the download progess)
[update.txt](https://github.com/coreos/bugs/files/652798/update.txt)
The (I believe) relevant bit:
```Dec 14 20:23:57 test.blink.internal update_engine[731]: I1214 20:23:57.346885   731 update_attempter.cc:381] Download status: inactive
Dec 14 20:23:57 test.blink.internal update_engine[731]: I1214 20:23:57.347455   731 payload_processor.cc:272] Verifying delta payload using public key: /usr/share/update_engine/update-payload-key.pub.pem
Dec 14 20:23:57 test.blink.internal update_engine[731]: I1214 20:23:57.347776   731 payload_signer.cc:254] signature size = 528
Dec 14 20:23:57 test.blink.internal update_engine[731]: E1214 20:23:57.413537   731 payload_processor.cc:309] Public key verification failed, thus update failed. Attached Signature:
Dec 14 20:23:57 test.blink.internal update_engine[731]: I1214 20:23:57.413560   731 utils.cc:235] Logging array of length: 256
Dec 14 20:23:57 test.blink.internal update_engine[731]: I1214 20:23:57.413578   731 utils.cc:252] 0x00000000 : b0 55 41 72 f3 68 4a 09 9b bc dc 55 39 f5 3a 3a
Dec 14 20:23:57 test.blink.internal update_engine[731]: I1214 20:23:57.413589   731 utils.cc:252] 0x00000010 : ca 2e 01 e3 3d 99 b4 cb ae 4c 31 c0 be f0 f9 c3
Dec 14 20:23:57 test.blink.internal update_engine[731]: I1214 20:23:57.413599   731 utils.cc:252] 0x00000020 : 6c f6 77 89 fb f2 7c d2 67 c8 c7 b6 06 4d 1d 5a
```

**Comment by marineam** [comment]
This is expected as `VERSION=1068.10.0+2016-08-31-1023` is not an official build so `/usr/share/update_engine/update-payload-key.pub.pem` is most likely our insecure development key, not the official update key. Only official builds can receive automatic updates.

I'm not familiar with SoftLayer's cloud, how was this instance installed?

**Comment by je-al** [comment]
Oh...
That's the newest (and not "deprecated") public image they provide as a base for VMs (the others being 835.10.0+2016-01-21-1403 and 899.15.0+2016-05-02-1212)

**Comment by marineam** [comment]
Shoot, they must be customizing the system and building their own images instead of using ours.

**Comment by marineam** [comment]
@je-al It's been a while since we've talked to anyone from Softlayer but I'll try to reach out to see what the situation is. I cannot remember if there is a reason for the images being like this.

As for migrating to an official image, without knowing what changes they made I don't know if that will result in a working system or not. Since you have a running system that can hit the update service just swapping the update signing key might do the trick:

```sh
sudo su -
wget https://raw.githubusercontent.com/coreos/coreos-overlay/master/coreos-base/coreos-au-key/files/official-v2.pub.pem
mount --bind ./official-v2.pub.pem /usr/share/update_engine/update-payload-key.pub.pem
systemctl restart update-engine.service
update_engine_client -update
```

Don't attempt that unless you are ok with potentially breaking the system though. :)

**Comment by je-al** [comment]
@marineam Well, that seems to have worked just fine. There's a couple of errors on the logs (they were also there before the upgrade), but nothing outright failed...
