### ISSUE TITLE
Kernel: enable CONFIG_ENA_ETHERNET

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1714]
### Desired Feature ###

This is a device that is only available in Amazon http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html

Driver is upstream.

**Comment by euank** [comment]
Pull request to enable the driver: https://github.com/coreos/coreos-overlay/pull/2331.

Proper ENA support requires some additional AMI registration script changes as well.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/2331.
