### ISSUE TITLE
Unable to SSH into a Digital Ocean CoreOS droplet with ED25519 SSH Key

### ISSUE THREAD

**Issue by cwgem** [coreos/bugs#1715]
I was asked on Twitter to report this bug so here I am.

### CoreOS Version ###

Both the CoreOS stable 1185.5.0 and alpha offered by Digital Ocean have this issue

### Environment ###

I'm attempting to run CoreOS on a Digital Ocean droplet

### Expected Behavior ###

I can SSH into the machine

### Actual Behavior ###

debug1: Offering ED25519 public key: [masked]
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Trying private key: [masked]
debug1: Trying private key: [masked]
debug1: Trying private key: [masked]
debug2: we did not send a packet, disable method
debug1: Next authentication method: keyboard-interactive
debug2: userauth_kbdint
debug2: we sent a keyboard-interactive packet, wait for reply
debug2: input_userauth_info_req
debug2: input_userauth_info_req: num_prompts 1

I'm then given a password prompt instead

### Reproduction Steps ###

  1. Attempt to SSH into a Digital Ocean CoreOS droplet with an ED25519 SSH Key
  2. Get a password prompt

### Other Information ###

The same key given to an Ubuntu 16.10 image allows me to login just fine.

**Comment by philips** [comment]
Just tested myself on CoreOS stable (1185.3.0) and it works fine. 
<img width="648" alt="screen shot 2016-12-15 at 6 13 36 pm" src="https://cloud.githubusercontent.com/assets/33544/21245751/7df471b0-c2f2-11e6-984f-9c4c4619b293.png">

**Comment by philips** [comment]
Since I can't repro I am going to close this.
