### ISSUE TITLE
Manual Rollback instructions do not work with dm-verity

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1718]
# Issue Report #

### CoreOS Version ###

Started with 1214.0.0.

### Environment ###

All

### Expected Behavior ###

`cgpt prioritize "$(cgpt find -t coreos-usr | grep --invert-match "$(findmnt --noheadings --raw --output=source --target=/usr)")"` works properly.

### Actual Behavior ###

```
$ cgpt prioritize "$(cgpt find -t coreos-usr | grep --invert-match "$(findmnt --noheadings --raw --output=source --target=/usr)")"
ERROR: cgpt prioritize: unable to access device /dev/sda3
/dev/sda4: No such file or directory
```

This is because `findmnt --noheadings --raw --output=source --target=/usr` prints `/dev/mapper/usr`, but `cgpt find -t coreos-usr` prints `/dev/sda3` and `/dev/sda4`.

**Comment by joshix** [comment]
fixed in https://github.com/coreos/docs/pull/957
