### ISSUE TITLE
Jenkins job hang on 1262.0.0

### ISSUE THREAD

**Issue by aaronlevy** [coreos/bugs#1720]
# Issue Report #

A jenkins job was repeatedly hanging at the same spot in execution. Rolling OS back to 1248.1.0 resolved the issue. I would say this may have also been the reboot which fixed this, but @crawford was reporting the same issue (and suggested the fix).

Specifically the job was running: https://github.com/kubernetes-incubator/bootkube/blob/master/build/build-image.sh#L13-L14

It was on the last step of build-releash.sh (tar-ing the built assets: https://github.com/kubernetes-incubator/bootkube/blob/master/Makefile#L16)

This step would never "complete" (from jenkins perspective) - not sure if it was tar not exiting, or the next step not starting.

I can try and roll forward again later today and see if the issue re-surfaces (to rule out the restart)

### CoreOS Version ###

1262.0.0

### Environment ###

GCE

**Comment by crawford** [comment]
This seems to be working again with 1284.2.0. We need to narrow down and figure out when it was fixed so we don't roll that configuration to Beta.
