### ISSUE TITLE
Enable {CONFIG_FB_BACKLIGHT, CONFIG_BACKLIGHT_CLASS_DEVICE} in default kernel

### ISSUE THREAD

**Issue by jpap** [coreos/bugs#1722]
# Issue Report #

I'm trying to add the Nvidia frame buffer driver as a module `CONFIG_FB_NVIDIA=m`, and control of the backlight with `CONFIG_FB_NVIDIA_BACKLIGHT=y`.  I can build the driver OK, but can't load the module:

1. The driver module fails to find a symbol:
```
[81992.090730] nvidiafb: Unknown symbol fb_bl_default_curve (err 0)
```

2. That symbol is included as part of the frame buffer driver, when `CONFIG_FB_BACKLIGHT` is set in the kernel config.  The relevant driver source is `drivers/video/fbdev/core/fbsysfs.c`:
```
#ifdef CONFIG_FB_BACKLIGHT
/* This function generates a linear backlight curve
 *
 *     0: off
 *   1-7: min
 * 8-127: linear from min to max
 */
void fb_bl_default_curve(struct fb_info *fb_info, u8 off, u8 min, u8 max)
{
   ...
}
EXPORT_SYMBOL_GPL(fb_bl_default_curve);
#endif
```

3. As the frame buffer driver is built-into the kernel with `CONFIG_FB`, I cannot enable `CONFIG_FB_BACKLIGHT` by separately compiling the frame buffer as a module: doing so conflicts with what's already built-into the kernel.

The only possible solution would be to enable `CONFIG_FB_BACKLIGHT` in the default CoreOS kernel configuration, or compile a custom kernel from scratch.  

It would be great the `CONFIG_FB_BACKLIGHT` kernel configuration was included by default.

Separately, it would be nice to have `CONFIG_BACKLIGHT_CLASS_DEVICE` included by default as well.  The alternative is to compile as the `backlight.ko` module which is also required to host the Nvidia driver.  There appears to be a bug in the fbdev Kconfig where if `CONFIG_FB_BACKLIGHT=y` and `CONFIG_BACKLIGHT_CLASS_DEVICE=m` were to be set, Kconfig would incorrectly disable building of that backlight module.  This issue is avoided by having `CONFIG_BACKLIGHT_CLASS_DEVICE=y` included in the kernel configuration and baked directly into the kernel.

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1185.5.0
VERSION_ID=1185.5.0
BUILD_ID=2016-12-07-0937
PRETTY_NAME="CoreOS 1185.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Bare-metal install.

**Comment by crawford** [comment]
Since Container Linux is geared toward head-less environments, I don't think we are going to enable this option. An alternative solution would be to compile your own module which provides `fb_bl_default_curve` and load that in addition to the NVIDIA module.

**Comment by bgilbert** [comment]
Since we're not pursuing this for now, I'll close.
