### ISSUE TITLE
Enable CONFIG_MPLS_IPTUNNEL

### ISSUE THREAD

**Issue by bluecmd** [coreos/bugs#1730]
# Issue Report #

### Environment ###

Bare metal

### Desired Feature ###

Please ship kernel with `mpls_iptunnel` (CONFIG_MPLS_IPTUNNEL) as module.

### Other Information ###

This is useful for using CoreOS in advanced routing scenarios.

**Comment by bluecmd** [comment]
Ping @crawford on this one as well. I feel like a meanie pinging you on all these bugs, but if this one could be in the next Alpha I would be very happy.

**Comment by crawford** [comment]
@bluecmd ha, no worries at all. I've fallen a bit behind triaging these. I could use the kick in the pants.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/2353.
