### ISSUE TITLE
Support eu-west-2 & ca-central-1 EC2 regions.

### ISSUE THREAD

**Issue by ggreer** [coreos/bugs#1733]
# Issue Report #

### Desired Feature ###

The eu-west-2 & ca-central-1 EC2 regions were added in the past couple of months. It'd be nice to have AMIs for both of them.

### Other Information ###

The Tectonic installer needs these AMIs before it can support these regions.

**Comment by ggreer** [comment]
Just curious, but when will these regions show up in https://stable.release.core-os.net/amd64-usr/current/coreos_production_ami_all.json ?

**Comment by crawford** [comment]
@ggreer Crap. I'll re-run that generation to include the new regions. They'll show up once Google Storage replicates again (maybe 30 minutes or so).
