### ISSUE TITLE
ensure cloud-init writes flannel env vars to correct path in newer Container Linux versions

### ISSUE THREAD

**Issue by sym3tri** [coreos/bugs#1735]
As I understand it cloud-init translates flannel config options into values written to `/run/flannel/options.env`. With newer versions of Container Linux, this path has changed. So cloud-init needs to be updated to write to the new location.

/cc @crawford

**Comment by crawford** [comment]
Sorry @sym3tri, I lied to you. `/run/flannel/flannel_docker_opts.env` is the path that changed.
