### ISSUE TITLE
Docker: image not pulled in systemd ExecStartPre=

### ISSUE THREAD

**Issue by jeusdi** [coreos/bugs#1737]
# Issue Report #

I'm getting this message from `systemd/dockerd`:

    Dec 29 14:41:32 core-01 systemd[1]: Starting ElasticSearch...
    Dec 29 14:41:32 core-01 docker[1335]: Error response from daemon: No such container: es
    Dec 29 14:41:32 core-01 docker[1346]: Error response from daemon: No such container: es
    Dec 29 14:41:33 core-01 docker[1367]: Pulling repository prv.private.registry/elasticsearch-qa
    Dec 29 14:41:33 core-01 docker[1367]: Error: image elasticsearch-qa not found
    Dec 29 14:41:33 core-01 systemd[1]: living-es.service: Control process exited, code=exited status=1

So it's telling me that `image elasticsearch-qa not found`.

The systemd service definition is:

      - name: living-es.service
        command: start
        enable: true
        content: |-
          [Unit]
          Description=ElasticSearch
          Author=Living
          After=docker.service
    
          [Service]
          Restart=always
          RestartSec=10s
          ExecStartPre=-/usr/bin/docker stop es
          ExecStartPre=-/usr/bin/docker rm es
          ExecStartPre=/usr/bin/docker pull prv.private.registry/elasticsearch-qa:v1
          ExecStart=/usr/bin/docker run --name es -p 9200:9200 -p 9300:9300 --hostname es -v /home/core/data/es:/usr/share/elasticsearch/data prv.private.registry.com/elasticsearch-qa:v1 -Des.node.name="esn1" -Des.cluster.name="cluster"
          ExecStop=/usr/bin/docker stop es

The message it's clear, nevertheless, when I pull the image on shell, it's pulled correctly. Any ideas?

    docker pull prv.private.registry/elasticsearch-qa:v1
    v1: Pulling from elasticsearch-qa
    8ad8b3f87b37: Pull complete
    751fe39c4d34: Pull complete
    b165e84cccc1: Pull complete
    acfcc7cbc59b: Pull complete
    04b7a9efc4af: Pull complete
    b16e55fe5285: Pull complete
    8c5cbb866b55: Pull complete
    53c3dd7fc70d: Pull complete
    3de13756a8c8: Pull complete
    64be422416b7: Pull complete
    b808918635ce: Pull complete
    5b3ceec8c156: Pull complete
    561269d0b7cc: Pull complete
    0c6cf9533753: Pull complete
    5234b57e3d12: Pull complete
    4a86b042378a: Pull complete
    c6f98581a18c: Pull complete
    b6ee1115f29d: Pull complete
    Digest: sha256:1f3c29d4f10ae897f67067ff72b8e25d8380531f04637941e67747bec96228f9code=exited status=1
    Status: Downloaded newer image for prv.private.registry/elasticsearch-qa:v1

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1185.5.0
VERSION_ID=1185.5.0
BUILD_ID=2016-12-07-0937
PRETTY_NAME="CoreOS 1185.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by euank** [comment]
Does the registry require authentication?

If it does, then it's possible the docker config file is only present for the 'core' user.

The CoreOS [docs](https://coreos.com/os/docs/latest/registry-authentication.html#the-docker-config-file) on using a private registry provide an example of adding `User=core` to a given service so that docker commands can run.

**Comment by euank** [comment]
Closing as stale.
