### ISSUE TITLE
unit contents as array of string

### ISSUE THREAD

**Issue by jhmartin** [coreos/bugs#1738]
### Environment ###

AWS

### Desired Feature ###
In unit file 'contents' blocks, allow the result to be a array that is inherently newline delimited. 

So where I currently have:
```
            {
                "contents": "[Unit]\nDescription=Var Lib Expansion Mount\n[Mount]\nWhat=/dev/disk/by-label/DOCKER\nWhere=/var/lib/docker\n[Install]\nRequiredBy = local-fs.target\n",
                "enable": true,
                "name": "var-lib-docker.mount"
            }
```

I would instead have a much more readable / git-history'able:
```
            {
                "contents": [
                 "[Unit]",
                 "Description=Var Lib Expansion Mount",
                 "[Mount]",
                 "What=/dev/disk/by-label/DOCKER"
                 "Where=/var/lib/docker"
                 "[Install]",
                 "RequiredBy = local-fs.target"
                ],
                "enable": true,
                "name": "var-lib-docker.mount"
            }
```

This plays well with version control, and is more readable.  This way contents could either be a bare string or an array of strings.

**Comment by crawford** [comment]
As I mentioned in https://github.com/coreos/bugs/issues/1729, human readability is not a major goal of Ignition. We instead recommend that [ct](https://github.com/coreos/container-linux-config-transpiler) be used to write the configs. Your above example would look like the following:

```yaml
systemd:
  units:
    - name: var-lib-docker.mount
      enable: true
      contents: |
        [Unit]
        Description=Var Lib Expansion Mount
        [Mount]
        What=/dev/disk/by-label/DOCKER
        Where=/var/lib/docker

        [Install]
        RequiredBy = local-fs.target
```

It is this form of the config that humans should interact with and check in to revision control. `ct` can then be used to transpile the config for the specific combination of target environment and Container Linux version.

I'm still in the process of writing documentation for this, so you'll have to bear with me for a few more days.

**Comment by crawford** [comment]
Here are those docs https://github.com/coreos/container-linux-config-transpiler/pull/23.
