### ISSUE TITLE
SELinux systemd-udevd deny

### ISSUE THREAD

**Issue by jhmartin** [coreos/bugs#1739]
# Issue Report #

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1235.2.0
VERSION_ID=1235.2.0
BUILD_ID=2016-12-07-0039
PRETTY_NAME="CoreOS 1235.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###
AWS

### Expected Behavior ###
No SELinux denials

### Reproduction Steps ###
System repeatedly logs: 
```audit[760]: AVC avc:  denied  { wake_alarm } for  pid=760 comm="systemd-udevd" capability=35  scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=capability2 permissive=0```

**Comment by mjg59** [comment]
Should be fixed in the next release. Thanks for the report!

**Comment by crawford** [comment]
We can probably backport this issue as well. @mjg59 do you have a link to the fix?

**Comment by mjg59** [comment]
https://github.com/coreos/coreos-overlay/pull/2375

**Comment by crawford** [comment]
Backported in https://github.com/coreos/coreos-overlay/pull/2393.
