### ISSUE TITLE
networkd-ndisc problems with local IPv6 addressing

### ISSUE THREAD

**Issue by mikebryant** [coreos/bugs#1745]
# Issue Report #

## Bug ##

ipv6 router advertisements cause networkd to mark the link as failed

```
Jan 04 18:58:16 c307f480-7277-11e3-8720-f44d306238d7 systemd-networkd[23411]: NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
Jan 04 18:58:16 c307f480-7277-11e3-8720-f44d306238d7 systemd-networkd[23411]: NDISC: Invoking callback for 'r'.
Jan 04 18:58:16 c307f480-7277-11e3-8720-f44d306238d7 systemd-networkd[23411]: cluster0: Acquiring DHCPv6 lease on NDisc request
Jan 04 18:58:16 c307f480-7277-11e3-8720-f44d306238d7 systemd-networkd[23411]: cluster0: Could not set NDisc route or address: Invalid argument
Jan 04 18:58:16 c307f480-7277-11e3-8720-f44d306238d7 systemd-networkd[23411]: cluster0: Failed
```

### CoreOS Version ###
1262.0.0

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1262.0.0
VERSION_ID=1262.0.0
BUILD_ID=2016-12-14-2334
PRETTY_NAME="CoreOS 1262.0.0 (Ladybug)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Bare metal - Intel NUC

### Expected Behavior ###

Router advertisements originating from the host should not be acted upon

### Actual Behavior ###

networkd attemps to set up a route to the local host, and fails

### Reproduction Steps ###

  1. run dnsmasq giving out route advertisements on an interface

### Other Information ###

This appears to be the same issue as systemd/systemd#4467 - this was merged in systemd v232
Can we get a backport of the fix, or an update to this version of systemd?

**Comment by dm0-** [comment]
The shipped version of systemd now includes the linked fix.
