### ISSUE TITLE
Shutdown scripts do not run on GCE

### ISSUE THREAD

**Issue by zmarano** [coreos/bugs#1746]
# Issue Report #

### CoreOS Version ###
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.4.0
VERSION_ID=1235.4.0
BUILD_ID=2017-01-04-0450
PRETTY_NAME="Container Linux by CoreOS 1235.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

### Environment ###
GCE

### Expected Behavior ###
Setting a metadata script for "shutdown-script" on GCE should run that script on shutdown/reboot. Normally this is done [via a systemd script](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google_compute_engine_init/systemd/google-shutdown-scripts.service). The CoreOS google_metadata_script_runner runs in a rkt container now. It is unclear how to make this work correctly on system reboot or shutdown.

### Actual Behavior ###
Shutdown scripts never run.

### Reproduction Steps ###
1) Start a CoreOS stable instance on GCE.
2) Set a metadata key "shutdown-script" to any generic script.

### Other Information ###
GCE CoreOS users have requested this feature.

**Comment by dm0-** [comment]
What do you see when you run `journalctl -u oem-gce`?

I saw it running shutdown scripts when the service stops (i.e. it contains `/usr/bin/google_metadata_script_runner --script-type shutdown`), just as the native service used to do.  An exception is when one of the agent daemons encounters an error and aborts; then the container is stopped without executing shutdown scripts.  You'll see an `exit 1` in the output in that case.

**Comment by zmarano** [comment]
Oh you're right- it is running and working now. I am not 100% sure what case this particular user was running into but I'll follow up and see if they have more info. My generic test case is actually working correctly. For now, I'll close this issue out.

**Comment by ok-devalias** [comment]
To keep all threads updated, the original issue was resolved via issue 1543: https://github.com/coreos/bugs/issues/1543

**Comment by crawford** [comment]
It's worth noting that this was fixed in https://coreos.com/releases/#1214.0.0. If the user provisioned a machine older than this release, the shutdown scripts won't work.

**Comment by zmarano** [comment]
Yes- this user report was from before that time so I suspect they ran into issues then. In any case, we are circling back with them. Thanks for the pointers!
