### ISSUE TITLE
Can't downgrade to a lower version on the same channel

### ISSUE THREAD

**Issue by ahmetalpbalkan** [coreos/bugs#1747]
# Issue Report #

I am using https://coreos.com/os/docs/latest/manual-rollbacks.html#performing-a-manual-rollback article to lower my version on the same channel, i.e. `stable` however I keep booting to the same version.

### CoreOS Version ###

1185.5.0

### Environment ###

DigitalOcean

### Expected Behavior ###

I follow the docs and set `COREOS_RELEASE_VERSION=1122.3.0` after copying the release file to /tmp/release and run `sudo systemctl restart update-engine; update_engine_client -update` then I expect to be in lower version. I also run the one-liner command to revert to the other partition.

### Actual Behavior ###

It doesn't get me to a lower version, whatever I did I am still in the same partition.

### Reproduction Steps ###

```
# cgpt show /dev/vda*
       start        size    part  contents
           0           1          Hybrid MBR
           1           1          Pri GPT header
           2          32          Pri GPT table
        4096      262144       1  Label: "EFI-SYSTEM"
                                  Type: EFI System Partition
                                  UUID: 340A53DF-DE0F-4B1B-9F3D-86028CE53D13
                                  Attr: Legacy BIOS Bootable
      266240        4096       2  Label: "BIOS-BOOT"
                                  Type: BIOS Boot Partition
                                  UUID: 25F85B89-95C9-42B5-BB88-374B44B8F712
      270336     2097152       3  Label: "USR-A"
                                  Type: Alias for coreos-rootfs
                                  UUID: 7130C94A-213A-4E5A-8E26-6CCE9662F132
                                  Attr: priority=1 tries=0 successful=0
     2367488     2097152       4  Label: "USR-B"
                                  Type: Alias for coreos-rootfs
                                  UUID: E03DD35C-7C2D-4A47-B3FE-27F15780A57C
                                  Attr: priority=2 tries=0 successful=1
     4464640      262144       6  Label: "OEM"
                                  Type: Alias for linux-data
                                  UUID: 7FFB25F1-A3AB-406B-8C74-F5D9FE3FB5A8
     4726784      131072       7  Label: "OEM-CONFIG"
                                  Type: CoreOS reserved
                                  UUID: 95A635FE-2C8A-4245-A29C-9E743A2E2A7D
     4857856    37085151       9  Label: "ROOT"
                                  Type: CoreOS auto-resize
                                  UUID: B2F7CC0E-C179-476B-80CA-82EBCB295334
    41943007          32          Sec GPT table
    41943039           1          Sec GPT header
```

active partition:
```
# findmnt --noheadings --raw --output=source --target=/usr
/dev/vda4
```

Then I do the following steps:

1. `cp /usr/share/coreos/release /tmp`
2. edit /tmp/release with  `COREOS_RELEASE_VERSION=1122.3.0` because I want that
3. `sudo mount -o bind /tmp/release /usr/share/coreos/release`
4. `sudo systemctl restart update-engine`
5. wait a few secs
6. `update_engine_client -update`
7. `reboot`
8. ssh again
9. I'm on the existing version (1185.5.0) again.

<details>
<summary>"update_engine_client -update" output</summary>
<pre>
core core # update_engine_client -update
I0105 01:24:17.417250  1725 update_engine_client.cc:247] Initiating update check and install.
I0105 01:24:17.426007  1725 update_engine_client.cc:252] Waiting for update to complete.
LAST_CHECKED_TIME=1483579457
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATE_AVAILABLE
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATE_AVAILABLE
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.040074
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.100192
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.160311
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.230449
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.400786
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.450884
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.490963
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.551082
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.741458
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.801576
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.911794
CURRENT_OP=UPDATE_STATUS_DOWNLOADING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
LAST_CHECKED_TIME=1483579457
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_FINALIZING
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038

Broadcast message from locksmithd at 2017-01-05 01:25:31.215990388 +0000 UTC:
System reboot in 5 minutes!

LAST_CHECKED_TIME=1483579457
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATED_NEED_REBOOT
NEW_VERSION=0.0.0.0
NEW_SIZE=264897038
I0105 01:25:32.699391  1725 update_engine_client.cc:194] Update succeeded -- reboot needed.
</pre>
</details>

<details>
<summary>"cgpt show" output after "-update"</summary>
<pre>
$ cgpt show /dev/vda*
       start        size    part  contents
           0           1          Hybrid MBR
           1           1          Pri GPT header
           2          32          Pri GPT table
        4096      262144       1  Label: "EFI-SYSTEM"
                                  Type: EFI System Partition
                                  UUID: 340A53DF-DE0F-4B1B-9F3D-86028CE53D13
                                  Attr: Legacy BIOS Bootable
      266240        4096       2  Label: "BIOS-BOOT"
                                  Type: BIOS Boot Partition
                                  UUID: 25F85B89-95C9-42B5-BB88-374B44B8F712
      270336     2097152       3  Label: "USR-A"
                                  Type: Alias for coreos-rootfs
                                  UUID: 7130C94A-213A-4E5A-8E26-6CCE9662F132
                                  Attr: priority=2 tries=1 successful=0
     2367488     2097152       4  Label: "USR-B"
                                  Type: Alias for coreos-rootfs
                                  UUID: E03DD35C-7C2D-4A47-B3FE-27F15780A57C
                                  Attr: priority=1 tries=0 successful=1
     4464640      262144       6  Label: "OEM"
                                  Type: Alias for linux-data
                                  UUID: 7FFB25F1-A3AB-406B-8C74-F5D9FE3FB5A8
     4726784      131072       7  Label: "OEM-CONFIG"
                                  Type: CoreOS reserved
                                  UUID: 95A635FE-2C8A-4245-A29C-9E743A2E2A7D
     4857856    37085151       9  Label: "ROOT"
                                  Type: CoreOS auto-resize
                                  UUID: B2F7CC0E-C179-476B-80CA-82EBCB295334
    41943007          32          Sec GPT table
    41943039           1          Sec GPT header
</pre>
</details>

----

From reading the doc what's not clear to me is

1. Does `-update` prioritize the passive partition so that after `reboot` it is picked up?
2. Do I have to swap the boot partition myself manually in this case?
3. Why does `-update` output show NEW_VERSION=0.0.0? That's confusing

Either I'm missing something or it's not straightforward to downgrade a coreos version on the same channel?

**Comment by crawford** [comment]
This isn't quite how update-engine works. The version number that you are modifying only changes the version that is reported to the public update servers. The update server actually makes the decision as to which version you'll get, and you'll always get the latest.

There is no way to downgrade to an arbitrary version without using [CoreUpdate](https://coreos.com/products/coreupdate) (a commercial product).

**Comment by ahmetalpbalkan** [comment]
Understood. Is this documented somewhere? Perhaps the doc I linked is a good place to add this info that it can't be downgraded to an arbitrary lower version number.

I have seen someone posting the same question in coreos-user mailing list, but the response was this doc and it did not explain what you described here.

**Comment by crawford** [comment]
> Is this documented somewhere?

I'm sure it's documented in a couple of places, but I cannot remember. Maybe @robszumski remembers where.

> Perhaps the doc I linked is a good place to add this info that it can't be downgraded to an arbitrary lower version number.

It's there in the first sentence "...so that it boots an older image (assuming it's still intact on the passive partition)."

**Comment by ahmetalpbalkan** [comment]
@crawford it still doesn't clearly state that I can't arbitrarily lower version number that I never installed. I'll move this to coreos/docs.
