### ISSUE TITLE
CoreOS stable switched to Container Linux by CoreOS beta

### ISSUE THREAD

**Issue by amir** [coreos/bugs#1748]
# Issue Report #

### CoreOS Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.4.0
VERSION_ID=1235.4.0
BUILD_ID=2017-01-04-0450
PRETTY_NAME="Container Linux by CoreOS 1235.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Microsoft Azure.

### Expected Behavior ###
A CoreOS stable to remain on the stable channel.

### Actual Behavior ###
A `CoreOS stable (1185.5.0)` machine switched to `Container Linux by CoreOS stable (1235.4.0)`. Note the *stable* in the upgraded one even though there exists no such stable version at https://coreos.com/releases/.

**Comment by johngilden** [comment]
Same here, same versions (1185.5.0 -> 1235.4.0)

**Comment by amir** [comment]
@mischief then there's a problem in Docker's systemd unit file.

```
ExecStart=/usr/lib/coreos/dockerd daemon
```

Fails to start Docker with an error saying: “dockerd: "dockerd" requires 0 arguments.”. Removing `daemon` fixes the problem but at current state any host upgraded to `1235.4.0` fails to start Docker on reboot.

**Comment by johngilden** [comment]
Hey @mischief,

strange, my other two CoreOS boxes are still getting "No update" from update-engine.service. Version is 1185.5.0:
```
I0105 13:17:49.401803 24953 omaha_request_action.cc:563] Omaha request response: <?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="update.core-os.net">
 <daystart elapsed_seconds="0"></daystart>
 <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
  <updatecheck status="noupdate"></updatecheck>
 </app>
</response>
I0105 13:17:49.401912 24953 omaha_request_action.cc:383] No update.
```

**Comment by crawford** [comment]
An error occurred while deploying the latest version to coreos.com and I hadn't noticed. Sorry about that. It should be fixed in a couple of minutes.

@johngilden this is expected. We rate-limit updates, so your other machines will gradually pick up the update as well.

**Comment by crawford** [comment]
Okay, the [release page](https://coreos.com/releases/) has been updated. Thanks for the report and thanks again for your patience.
