### ISSUE TITLE
Reconsider enabling the x32 ABI

### ISSUE THREAD

**Issue by martynd** [coreos/bugs#1749]
Happy new year everyone!

This subject was previously discussed in https://github.com/coreos/coreos-overlay/pull/914

I think there is still a strong case for at least enabling the kernel option (CONFIG_X86_32), and perhaps even a case to fully embrace and encourage its useage. Several distros do in fact have the flag enabled by default and some the libraries as well.

Back in 2012 CERN released a paper on their usage of the x32 ABI and its benefits to them and did a re-evaluation of it last year.
[These](https://indico.cern.ch/event/468210/contributions/1143887/attachments/1218724/1780705/slides.pdf) are the slides discussing the re-evaluation
The original 2012 evaluation can be found [here](http://linuxplumbersconf.net/2011/ocw//system/presentations/531/original/x32-LPC-2011-0906.pptx)

A [similar presentation](https://indico.fnal.gov/getFile.py/access?contribId=2&sessionId=7&resId=0&materialId=slides&confId=6138) from Fermilab mentions their use of the X32 ABI to work with a 1 core to 2gb ram ratio

With most container processes being distributed and not each over 4GB, it seems like rewards with little cost, especially with how pricing for virtual servers is done. 

As a couple of other examples:
Recent discussions of its use has even occured at the most unlikely of places, such as the Windows "bash" repo: https://github.com/Microsoft/BashOnWindows/issues/711/
Intels original presentation on the subject also goes into more details:
http://linuxplumbersconf.net/2011/ocw//system/presentations/531/original/x32-LPC-2011-0906.pptx

Thank you

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
