### ISSUE TITLE
Illegal opcode

### ISSUE THREAD

**Issue by nithinsnv** [coreos/bugs#1750]
# Issue Report #
I am having problem in loading OS and showing Illegal OPCODE 
EFLAGS-0000A96
### CoreOS Version ###
Centos 6
```
$ cat /etc/os-release
NAME=CoreOS
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

### Reproduction Steps ###

  1. ...
  2. ...

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

**Comment by crawford** [comment]
This is the CoreOS bug tracker. You'll need to file your bug with CentOS.

**Comment by nithinsnv** [comment]
Thank u Alex where shall I find the centos bug clear option
