### ISSUE TITLE
Need guide for cloning container linux instances

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1753]
# Issue Report #

### Environment ###

All

### Desired Feature ###

We need a guide detailing how to clone images or make a base image. This needs to include removing `/etc/machine-id` and resetting the disk GUID.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
