### ISSUE TITLE
Flannel environment path in docker unit.

### ISSUE THREAD

**Issue by arthur-c** [coreos/bugs#1756]
# Issue Report #

## Bug ##

The flannel environment file path has changed in the docker unit with the update to 1235.5.0, it prevents docker to use flannel.

From https://coreos.com/flannel/docs/latest/flannel-config.html:

> docker.service sources in /run/flannel_docker_opts.env which contains env variables with command line options and starts the Docker with them

but systemctl cat docker.service

```
[Service]
Type=notify
EnvironmentFile=-/run/flannel/flannel_docker_opts.env
```

I updated my flannel configuration in my cloud-config to write `/run/flannel/flannel_docker_opts.env` and it's now fine. But the environment file path should be consistent between doc and units. 
I think the change docker unit is buggy as it breaks the old behaviour and breaks node after the upgrade.

### CoreOS Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.5.0
VERSION_ID=1235.5.0
BUILD_ID=2017-01-08-0037
PRETTY_NAME="Container Linux by CoreOS 1235.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

```

### Environment ###

AWS

**Comment by crawford** [comment]
I've gone ahead and updated the docs, but I'm curious why you are writing directly to `/run/flannel/flannel_docker_opts.env`. This is an implementation detail of flannel and shouldn't be modified by the end user.

**Comment by arthur-c** [comment]
Thanks. I have these lines in my cloud-config to configure the flanneld unit,

```
          # Update docker options
          ExecStartPost=/usr/bin/docker run --net=host --rm -v /run:/run \
            quay.io/coreos/flannel:${FLANNEL_VER} \
            /opt/bin/mk-docker-opts.sh -d /run/flannel_docker_opts.env -i

```

I can't rembember where I found the source of that, I might have imported the flanneld service from CoreOS to the cloud config to fix the flannel version, I remember having issues with some flannel updates and needed to have more control on the versioning.

**Comment by crawford** [comment]
Ah. You can use a drop-in instead which just sets the `FLANNEL_VER` environment variable. That will ensure that we can keep the flannel-related units up to date and still respect your version specification.
