### ISSUE TITLE
SELinux avc denies after updating to 1235.x.0

### ISSUE THREAD

**Issue by pizzarabe** [coreos/bugs#1757]
# Issue Report #

I run ~ 1000 containers in a multi-node kubernetes system. The infrastructure updated itself (locksmithd; auto-update) to 1235.x.0 (some 1235.4.0, others 1235.5.0).

All updated nodes are unable to spawn the containers (nginx:alpine) and the pods are in a crash-loop.

The output of a nginx container 

```
docker logs 142dc41cd711
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2017/01/10 14:56:52 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
```

I disabled the Dontaudit rules (https://coreos.com/os/docs/latest/selinux.html) and I got the following avc denials:

```
Jan 10 15:51:17 alien3 audit[20404]: AVC avc:  denied  { read } for  pid=20404 comm="nslookup" name="etc-hosts" dev="sda9" ino=1062417 scontext=system_u:system_r:svirt_lxc_net_t:s0:c15,c665 tcontext=system_u:object_r:svirt_lxc_file_t:s0:c354,c771 tclass=file permissive=0
Jan 10 15:51:17 alien3 audit[20404]: AVC avc:  denied  { read } for  pid=20404 comm="nslookup" name="etc-hosts" dev="sda9" ino=1062417 scontext=system_u:system_r:svirt_lxc_net_t:s0:c15,c665 tcontext=system_u:object_r:svirt_lxc_file_t:s0:c354,c771 tclass=file permissive=0
Jan 10 15:51:17 alien3 audit[20406]: AVC avc:  denied  { read } for  pid=20406 comm="nslookup" name="etc-hosts" dev="sda9" ino=1062417 scontext=system_u:system_r:svirt_lxc_net_t:s0:c15,c665 tcontext=system_u:object_r:svirt_lxc_file_t:s0:c354,c771 tclass=file permissive=0
Jan 10 15:51:17 alien3 audit[20406]: AVC avc:  denied  { read } for  pid=20406 comm="nslookup" name="etc-hosts" dev="sda9" ino=1062417 scontext=system_u:system_r:svirt_lxc_net_t:s0:c15,c665 tcontext=system_u:object_r:svirt_lxc_file_t:s0:c354,c771 tclass=file permissive=0
Jan 10 15:51:18 alien3 audit[20436]: AVC avc:  denied  { append } for  pid=20436 comm="nginx" dev="pipefs" ino=13613572 scontext=system_u:system_r:svirt_lxc_net_t:s0:c636,c992 tcontext=system_u:system_r:kernel_t:s0 tclass=fifo_file permissive=0
Jan 10 15:51:18 alien3 audit[20436]: AVC avc:  denied  { append } for  pid=20436 comm="nginx" dev="pipefs" ino=13613572 scontext=system_u:system_r:svirt_lxc_net_t:s0:c636,c992 tcontext=system_u:system_r:kernel_t:s0 tclass=fifo_file permissive=0
Jan 10 15:51:19 alien3 audit[20492]: AVC avc:  denied  { read } for  pid=20492 comm="nslookup" name="etc-hosts" dev="sda9" ino=1062417 scontext=system_u:system_r:svirt_lxc_net_t:s0:c15,c665 tcontext=system_u:object_r:svirt_lxc_file_t:s0:c354,c771 tclass=file permissive=0
[...]

```

### CoreOS Version ###

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.5.0
VERSION_ID=1235.5.0
BUILD_ID=2017-01-08-0037
PRETTY_NAME="Container Linux by CoreOS 1235.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.4.0
VERSION_ID=1235.4.0
BUILD_ID=2017-01-04-0450
PRETTY_NAME="Container Linux by CoreOS 1235.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

### Environment ###

VMware

**Comment by pizzarabe** [comment]
My systems updated to 1235.6.0 with the same problem.

The current policy does not allow to append to fifo_fles:

`allow svirt_lxc_net_t kernel_t : fifo_file { ioctl read write getattr open } ;`

But the containers seems to need that in order to write to stderr:

```
2017/01/12 09:34:17 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)

lrwxrwxrwx. 1 root root system_u:object_r:var_lib_t:s0   11 Dec 27 20:18 error.log -> /dev/stderr

lrwxrwxrwx. 1 root root system_u:object_r:device_t:s0 15 Jan 11 20:05 /dev/stderr -> /proc/self/fd/2

lrwx------. 1 root root system_u:system_r:kernel_t:s0 64 Jan 12 10:33 /proc/self/fd/2 -> /dev/pts/0
```

simply allowing to append to fifo_files from that type helped and allowed me to spawn my containers again.

```
module testing_module 1.0;

require {
type svirt_lxc_net_t;
type kernel_t;
class fifo_file { append };
}
allow svirt_lxc_net_t kernel_t:fifo_file append;
```

I do not know if it is necessary to allow that kind of operation, maybe the underlying problem is sth. else.

**Comment by mjg59** [comment]
There are two problems here. The first (the denied reads from nslookup) is because the label on /etc/hosts is from a different container. Are you binding that in from somewhere else? The second looks like a policy bug. I'll fix that up.

**Comment by mjg59** [comment]
@pizzarabe Are you using rkt or docker?

**Comment by mjg59** [comment]
@pizzarabe Oh never mind - I see docker in the log output now. Sorry!

**Comment by pizzarabe** [comment]
> The first (the denied reads from nslookup) is because the label on /etc/hosts is from a different container. Are you binding that in from somewhere else?

@mjg59 just checked my k8s-cluster again and this problem seems to be related to the kube-dns pod  

```
Jan 13 09:53:53 alien3 audit[11947]: AVC avc:  denied  { ioctl } for  pid=11947 comm="nslookup" path="/etc/hosts" dev="sda9" ino=1062417 ioctlcmd=5401 scontext=system_u:system_r:svirt_lxc_net_t:s0:c278,c1001 tcontext=system_u:object_r:svirt_lxc_file_t:s0:c93,c135 tclass=file permissive=1
Jan 13 09:53:53 alien3 kernel: audit: type=1400 audit(1484297633.456:2928): avc:  denied  { read } for  pid=11945 comm="nslookup" name="etc-hosts" dev="sda9" ino=1062417 scontext=system_u:system_r:svirt_lxc_net_t:s0:c278,c1001 tcontext=system_u:object_r:svirt_lxc_file_t:s0:c93,c135 tclass=file permissive=1
```
My kube-dns is from the upstream 1.4 release (https://github.com/kubernetes/kubernetes/blob/release-1.4/cluster/addons/dns/skydns-rc.yaml.base) but I don't know what the kube-dns tries to do here :/


there is also a problem with the open of nfs_t (this was not before 1235.x)

`Jan 13 09:48:40 alien3 audit[575]: AVC avc:  denied  { open } for  pid=575 comm="kube-dns" path="/etc/kubeconfig" dev="0:44" ino=5463952129 scontext=system_u:system_r:svirt_lxc_net_t:s0:c489,c530 tcontext=system_u:object_r:nfs_t:s0 tclass=file permissive=1`

**Comment by mjg59** [comment]
Any mounts into containers need to be flagged to ensure that they're appropriately labeled - http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/ has some more information on this. You want Z if it's container-specific, z if it's something that will be shared between multiple containers.

**Comment by mjg59** [comment]
BTW, the reason you're seeing this with 1235 and not earlier is that after Docker transitioned to runc we shipped several releases without SELinux support in Docker - 1235 is the first stable release with it fully reenabled. There's been no change in SELinux policy, merely the fact that Docker is actually being contained by it again.

**Comment by mjg59** [comment]
Fix committed, should be in the next release. Thanks for the report!

**Comment by crawford** [comment]
@mjg59 do you have a link to the PR that fixes this? Should we backport this to Stable?

**Comment by mjg59** [comment]
https://github.com/coreos/coreos-overlay/pull/2375, and that sounds like a good plan

**Comment by crawford** [comment]
Backported in https://github.com/coreos/coreos-overlay/pull/2393.
