### ISSUE TITLE
systemd: require networkd drop-ins from v232

### ISSUE THREAD

**Issue by stuart-warren** [coreos/bugs#1758]
# Issue Report #

### Environment ###

We are running on VMs/baremetal on the current alpha v1284.2.0 (systemd v231)

### Desired Feature ###

The networkd unit drop-in features from systemd v232

https://github.com/systemd/systemd/blob/v232/NEWS#L156

### Other Information ###

We are attempting some interesting networking of coreos instances and as Kubernetes is currently ipv4 only we are creating tunnels all over the place and this requires adding: 
```
[Network]
Tunnel=sometunnelname
IPForward=ipv4
``` 
to the interfaces .network files, it's nicer to not have to edit existing system files when these tunnels are generated by a different process.

**Comment by crawford** [comment]
This is going to be a pretty low priority for us. My guess is that we'll upgrade to 232+ before we get around to backporting this.

**Comment by stuart-warren** [comment]
That's cool, I was curious why you had been backporting features rather than upgrading though?
Is there an issue in 232?

**Comment by crawford** [comment]
There were a number of issues with 232 (I don't recall the specifics). I was expecting a 233 shortly after with a bunch of fixes, but it looks like 233 is going to be another full-featured release.
