### ISSUE TITLE
/var/log/journal is not present

### ISSUE THREAD

**Issue by errm** [coreos/bugs#1761]
# Issue Report #

## Bug ##

`/var/log/journal` is not present

### CoreOS Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.6.0
VERSION_ID=1235.6.0
BUILD_ID=2017-01-10-0545
PRETTY_NAME="Container Linux by CoreOS 1235.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

AWS

### Expected Behavior ###

We have been using fluentd to read the journal from files in `/var/log/journal` and expect this directory to be present...

### Actual Behavior ###

`/var/log/journal` is not present

```
ip-10-50-1-208 / # ls -la /var/log
total 28
drwxr-xr-x. 1 root root     64 Jan 12 13:07 .
drwxr-xr-x. 1 root root     82 Jan 11 10:57 ..
-rw-------. 1 root utmp   3456 Jan 11 10:59 btmp
drwxr-xr-x. 1 root root   6352 Jan 14 15:35 containers
-rw-r--r--. 1 root root  32096 Jan 12 13:07 faillog
-rw-r--r--. 1 root root 292876 Jan 14 15:29 lastlog
-rw-rw-r--. 1 root utmp  11520 Jan 14 15:29 wtmp
```

`journalctl -f` seems to work as expected ...

### Other Information ###

motd includes info about failed units (not sure if related)

```
Container Linux by CoreOS stable (1235.6.0)
Failed Units: 45
  systemd-coredump@1-23513-0.service
  systemd-coredump@12-4439-0.service
  systemd-coredump@13-8196-0.service
  systemd-coredump@14-9088-0.service
  systemd-coredump@15-10492-0.service
  systemd-coredump@16-12652-0.service
  systemd-coredump@17-13884-0.service
  systemd-coredump@18-15705-0.service
  systemd-coredump@19-17831-0.service
  systemd-coredump@20-19355-0.service
  systemd-coredump@21-539-0.service
  systemd-coredump@22-10374-0.service
  systemd-coredump@23-14141-0.service
  systemd-coredump@24-24149-0.service
  systemd-coredump@25-646-0.service
  systemd-coredump@26-1774-0.service
  systemd-coredump@27-4291-0.service
  systemd-coredump@28-5870-0.service
  systemd-coredump@29-18901-0.service
  systemd-coredump@30-19275-0.service
  systemd-coredump@31-20066-0.service
  systemd-coredump@32-21045-0.service
  systemd-coredump@33-24833-0.service
  systemd-coredump@34-26627-0.service
  systemd-coredump@35-30492-0.service
  systemd-coredump@36-5692-0.service
  systemd-coredump@37-20166-0.service
  systemd-coredump@38-20631-0.service
  systemd-coredump@39-22745-0.service
  systemd-coredump@40-24193-0.service
  systemd-coredump@41-25017-0.service
  systemd-coredump@42-27189-0.service
  systemd-coredump@43-28673-0.service
  systemd-coredump@44-31988-0.service
  systemd-coredump@45-675-0.service
  systemd-coredump@46-1497-0.service
  systemd-coredump@47-7535-0.service
  systemd-coredump@48-8557-0.service
  systemd-coredump@49-9730-0.service
  systemd-coredump@50-10967-0.service
  systemd-coredump@51-12533-0.service
  systemd-coredump@52-15058-0.service
  systemd-coredump@53-18962-0.service
  systemd-coredump@6-28395-0.service
  systemd-coredump@7-29159-0.service
```

**Comment by errm** [comment]
It works as expected if I manually create `/var/log/journal`

```
sudo mkdir /var/log/journal
```

Is this expected behaviour?  If so could you add some documentation to this effect?

**Comment by euank** [comment]
When I boot a fresh machine, that directory exists and I don't see such an error.
Do you have more information for how to reproduce that issue, @errm?
Is there some program that might be deleting `/var/log/journal`?

**Comment by marineam** [comment]
One thought worth checking on: in times past the only systems that started
with an empty root were PXE which usually use tmpfs. So there probably is
not a tmpfiles rule to create /var/log/journal on the idea that journald
shouldn't think it can flush to persistent disk when that is not the case.
However these days it is easy to recreate root via ignition. On such
systems I don't know that there is anything that will automatically create
/var/log/journal

**Comment by errm** [comment]
So I am just creating machines from the official AMI on AWS, the root volume is an EBS volume...

**Comment by crawford** [comment]
I tried reproducing this with CoreOS-stable-1235.6.0-hvm (ami-12942672), but everything seems in order:

```
$ ls -la /var/log
total 56
drwxr-xr-x. 4 root root              4096 Feb 21 18:54 .
drwxr-xr-x. 9 root root              4096 Feb 21 18:54 ..
-rw-------. 1 root utmp                 0 Feb 21 18:54 btmp
-rw-r--r--. 1 root root                 0 Feb 21 18:54 faillog
drwxr-sr-x. 4 root systemd-journal   4096 Feb 21 18:54 journal
-rw-r--r--. 1 root root            146292 Feb 21 18:54 lastlog
drwx------. 2 root root              4096 Jan 10 05:47 sssd
-rw-rw-r--. 1 root utmp              2688 Feb 21 18:54 wtmp
```

It looks like there is something on your system removing that directory. Can you try starting with an empty machine and adding configuration one-by-one in order to figure out the offender?

**Comment by errm** [comment]
I just took another look (version: `1353.7.0`) and was unable to reproduce, I guess this is one of those things ...
