### ISSUE TITLE
Developer container image can't fetch binhost package info for 1235.6.0 and 1248.4.0

### ISSUE THREAD

**Issue by therc** [coreos/bugs#1762]
dm0 on IRC suggested that this might be due to them being special security releases.
Anyway, I can't build NVIDIA modules for the new versions.

# Issue Report #

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

Doesn't matter. Technically speaking, I'm not even running the container on a CoreOS machine.

### Expected Behavior ###

No error getting coreos-sources

### Actual Behavior ###

!!! Error fetching binhost package info from 'http://builds.developer.core-os.net/boards/amd64-usr/1235.6.0/pkgs/'
!!! HTTP Error 404: Not Found

### Reproduction Steps ###

  1. Get a developer container image
  2. Run `emerge -gKq coreos-sources` inside it

**Comment by dm0-** [comment]
To temporarily work around this, drop the `-g` and `-K` arguments to `emerge` to build packages from source.

**Comment by therc** [comment]
I tried the workaround and it makes the developer container blow up earlier and reliably:

``
>>> Installing (1 of 19) sys-devel/autoconf-wrapper-13::portage-stable
>>> Emerging (2 of 19) sys-devel/automake-wrapper-10::portage-stable
>>> Installing (2 of 19) sys-devel/automake-wrapper-10::portage-stable
>>> Emerging (3 of 19) sys-devel/m4-1.4.16::portage-stable
>>> Installing (3 of 19) sys-devel/m4-1.4.16::portage-stable
>>> Emerging (4 of 19) dev-libs/libltdl-2.4.6::portage-stable
>>> Installing (4 of 19) dev-libs/libltdl-2.4.6::portage-stable
>>> Emerging (5 of 19) sys-devel/flex-2.6.3::portage-stable

Container coreos_developer_container.bin.1235.6.0 terminated by signal KILL.
```

With -gK, it tried emerging only 10 packages and it would only occasionally get killed.

**Comment by dm0-** [comment]
Yes, more packages are going to be installed as build dependencies when building from source.  I am not seeing any `SIGKILL`s, though.  Is your system running out of memory?

**Comment by therc** [comment]
systemd-nspawn is a total mystery when it comes to memory. I'm running it on a laptop with 8GB of RAM and 16GB of SSD swap, very little of which is used. Does it perhaps avoid swap? There are 0.5GB of RAM free and 2GB used for buffers/cache. For the record, I'm running version 231 on an Ubuntu 16.10 system

**Comment by therc** [comment]
Alright, it looks like the use of --share-system triggers or is a lightning bolt for the KILL signals. And it's going to be gone in systemd 232 anyway.

Without the flag, it's currently going futher than it ever did, but this is probably going to break the nvidia build part of the script. I'll have to find another workaround...

**Comment by therc** [comment]
Much to my surprise, things worked. It just took an eternity.

I think the examples in the docs, in this day and age, should just run emerge with at least `--jobs=2 --load-average=2`. They could mention running `grep -c ^processor /proc/cpuinfo`, but that's icing on the cake.

Anyway, closing this issue. Hopefully it will be of aid to others for future reference. Thanks for your help!

**Comment by therc** [comment]
Still broken... while building drivers for beta 1248.4.0, which runs kernel 4.8.11:

```

**Comment by therc** [comment]
Still broken... while building drivers for beta 1248.4.0, which runs kernel 4.8.11:

```
 * Messages for package sys-kernel/coreos-sources-4.8.17:
[...]
+ cp /lib/modules/4.8.11-coreos-r2/build/.config .config
```

You end up with a module built against the latest alpha kernel, 4.8.17. The obvious hacky fix

``` emerge -q coreos-sources-`ls /lib/modules`

or similar variations doesn't seem to work. :-(

**Comment by dm0-** [comment]
What documentation are you following?  I am only aware of the page at https://coreos.com/os/docs/latest/kernel-modules.html .  It includes checking out the appropriate version branch (and does not include `--share-system`).  I just verified that it does install the correct `=sys-kernel/coreos-sources-4.8.11-r2` for current beta.

**Comment by therc** [comment]
Nevermind, I just realised I had not done the git magic to pin the correct branch. Sorry for the noise.
