### ISSUE TITLE
coreos-cloudinit --from-url should support s3 bucket downloads

### ISSUE THREAD

**Issue by redbaron** [coreos/bugs#1765]
To make it easier to bypass userdata limit, `coreos-cloudinit --from-url` should be able to download credentials from s3 bucket using IAM instance profile to authenticate.

Currently workarounds involving `awscli` tools are needed: https://github.com/coreos/kube-aws/issues/252#issuecomment-272850696

**Comment by crawford** [comment]
Sorry, but coreos-cloudinit is no longer under active development. We are instead focusing our effort on [Ignition](https://github.com/coreos/ignition) and [CT](https://github.com/coreos/container-linux-config-transpiler).
