### ISSUE TITLE
Locksmithd: Unlocking old locks failed 

### ISSUE THREAD

**Issue by xueshanf** [coreos/bugs#1766]
# Issue Report #

Locksmithd failed to unlock existing lock after reboot when TLS is used to communicated with etcd cluster, and it doesn't re-try either.

## Bug ##

Not sure if it is a bug or configuration issue. 

No problems with etcd cluster that doesn't use TLS, which means locksmithd works fine with default http:// endpoint. When TLS is used,  the LOCKSMITHD_ETCD_* and https:// endpoint related values seems not being used. 

### CoreOS Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1248.4.0
VERSION_ID=1248.4.0
BUILD_ID=2017-01-10-0545
PRETTY_NAME="Container Linux by CoreOS 1248.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

On AWS platform.

### Expected Behavior ###

Locksmithd should unlock existing reboot lock.

### Actual Behavior ###

Locksmithd unable to unlock and doesn't re-try.

### Reproduction Steps ###

Here is the locksmithd systemd unit produced by cloud-config.

```
core@ip-10-x-x-x ~ $ systemctl cat locksmithd
# /usr/lib/systemd/system/locksmithd.service
[Unit]
Description=Cluster reboot manager
ConditionVirtualization=!container
ConditionPathExists=!/usr/.noupdate

[Service]
CPUShares=16
MemoryLimit=32M
PrivateDevices=true
Environment=GOMAXPROCS=1
EnvironmentFile=-/usr/share/coreos/update.conf
EnvironmentFile=-/etc/coreos/update.conf
ExecStart=/usr/lib/locksmith/locksmithd
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target

# /run/systemd/system/locksmithd.service.d/20-cloudinit.conf
[Service]
Environment="LOCKSMITHD_GROUP=etcd"
# /etc/systemd/system/locksmithd.service.d/30-cloudinit.conf
[Unit]
Requires=etcd2.service
After=etcd2.service
[Service]
Environment="LOCKSMITHD_ETCD_CERTFILE=/etc/etcd/certs/kubernetes.pem"
Environment="LOCKSMITHD_ETCD_KEYFILE=/etc/etcd/certs/kubernetes-key.pem"
Environment="LOCKSMITHD_ETCD_CAFILE=/etc/etcd/certs/ca.pem"
Environment="LOCKSMITHD_ENDPOINT=https://127.0.0.1:2379"
Environment="LOCKSMITHD_REBOOT_WINDOW_START=05:30"
Environment="LOCKSMITHD_REBOOT_WINDOW_LENGTH=3h"

```
All files exist and valid,  and I can manually release the lock with these environments variables with locksmithctl client. 

```
core@ip-10-240-1-57 ~ $ printenv |grep LOCK
LOCKSMITHCTL_ENDPOINT=https://127.0.0.1:2379
LOCKSMITHCTL_ETCD_KEYFILE=/etc/etcd/certs/kubernetes-key.pem
LOCKSMITHCTL_ETCD_CERTFILE=/etc/etcd/certs/kubernetes.pem
LOCKSMITHCTL_ETCD_CAFILE=/etc/etcd/certs/ca.pem

core@ip-10-x-x-x ~ $ locksmithctl status
Available: 0
Max: 1

MACHINE ID
d4a4242f2a0c43f68ba129fd2203c763
core@ip-10-x-x-x ~ $ locksmithctl unlock
core@ip-10-x-x-x ~ $ locksmithctl status
Available: 1
Max: 1
```
### Other Information ###

Systemctl shows the locksmithd running happily.
```
core@ip-10-x-x-x ~ $ systemctl status locksmithd
● locksmithd.service - Cluster reboot manager
   Loaded: loaded (/usr/lib/systemd/system/locksmithd.service; disabled; vendor preset: disabled)
  Drop-In: /run/systemd/system/locksmithd.service.d
           └─20-cloudinit.conf
        /etc/systemd/system/locksmithd.service.d
           └─30-cloudinit.conf
   Active: active (running) since Mon 2017-01-16 08:05:02 UTC; 12h ago
 Main PID: 1741 (locksmithd)
    Tasks: 6
   Memory: 3.6M (limit: 32.0M)
      CPU: 57ms
   CGroup: /system.slice/locksmithd.service
           └─1741 /usr/lib/locksmith/locksmithd

Jan 16 17:04:58 ip-10-x-x-x.us-west-2.compute.internal locksmithd[1741]: LastCheckedTime=1484583716 Progress=0 CurrentOperation="UPDATE_STATUS_C
Jan 16 17:04:59 ip-10-x-x-x.us-west-2.compute.internal locksmithd[1741]: LastCheckedTime=1484586299 Progress=0 CurrentOperation="UPDATE_STATUS_I
Jan 16 17:52:54 ip-10-x-x-x.us-west-2.compute.internal locksmithd[1741]: LastCheckedTime=1484586299 Progress=0 CurrentOperation="UPDATE_STATUS_C
Jan 16 17:52:55 ip-10-x-x-x.us-west-2.compute.internal locksmithd[1741]: LastCheckedTime=1484589175 Progress=0 CurrentOperation="UPDATE_STATUS_I
```
Journalctl error message about locksmithd unable to unlock:

```
-- Reboot --
Jan 16 08:04:48 ip-10-240-1-57.us-west-2.compute.internal systemd[1]: Started Cluster reboot manager.
-- Subject: Unit locksmithd.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit locksmithd.service has finished starting up.
--
-- The start-up result is done.
Jan 16 08:04:49 ip-10-x-x-x.us-west-2.compute.internal locksmithd[717]: Reboot window start is "05:30" and length is "3h"
Jan 16 08:04:49 ip-10-x-x-x.us-west-2.compute.internal locksmithd[717]: Next window begins at 2017-01-17 05:30:00 +0000 UTC and ends at 2017-01-17 08:30:00 +0000 UTC
Jan 16 08:04:49 ip-10-x-x-x.us-west-2.compute.internal locksmithd[717]: locksmithd starting currentOperation="UPDATE_STATUS_IDLE" strategy="etcd-lock"
Jan 16 08:04:55 ip-10-x-x-x.us-west-2.compute.internal locksmithd[717]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: client: etcd cluster is unavailable or misconfigured. Retrying in 10s.

```
### Other Information ###

Our bootstrapping process is like this:

* user-data is a shell script that use instance's profile IAM policy to download cloud-config for the instances
* after cloud-config is downloaded, the shell script executes cloud-config like so `coreos-cloudinit --from-file=${workDir}/cloud-config.yaml`.

The cloud-config.yaml contains coreos cloud-config that defines locksmithd's LOCKSMITHD_* environments, among other services. 

Could that be a problem, meaning the second stage locksmithd service ignored LOCKSMITHD_*?

**Comment by crawford** [comment]
It looks like Locksmith doesn't support providing this information via environment variables. To work around the issue for now, you can override the `ExecStart` directive in locksmithd.service and pass the flags (`etcd-keyfile`, `etcd-certfile`, `etcd-cafile`).

**Comment by dm0-** [comment]
I have not been able to reproduce this behavior on current alpha; i.e. locksmithd can unlock when using etcd with TLS configured through the environment.

Does overriding the `ExecStart=` in `locksmithd.service` with the respective options result in the same behavior?

**Comment by dm0-** [comment]
Oh, sorry, I missed your `cloud-init` setup.  I provisioned the system with Ignition when it worked for me.

To check if your system is starting locksmith before the environment files are written, you can run the following to check what environment variables are used by the process.

    cat /proc/$(systemctl show -p MainPID locksmithd | sed s/.*=//)/environ

**Comment by dm0-** [comment]
I am taking this off the alpha milestone, since it sounds like a provisioning process issue.  The services appear to work as intended.

**Comment by xueshanf** [comment]
@dm0- thanks for the  trouble-shooting command. The cat command doesn't show the ETCD ENV's I needed. Restart locksmithd made it work. I will fix my provisioning.

**Comment by bgilbert** [comment]
Looks like this is resolved, so I'll close.
