### ISSUE TITLE
dd-ing CoreOS ISO image to USB pen drive results in unbootable device

### ISSUE THREAD

**Issue by urzds** [coreos/bugs#1769]
# Issue Report #

### CoreOS Version ###

1235.6.0

### Environment ###

N/A

### Expected Behavior ###

Plugging a USB pen drive into your desktop computer (I'll assume it gets assigned the `/dev/sdb` node) and running `sudo dd bs=4M if=$HOME/Downloads/coreos_production_iso_image.iso of=/dev/sdb` should result in a device that appears in the desktop's file manager or that can be booted by the server's firmware.

### Actual Behavior ###

The target server's firmware detects the USB pen, but does not offer to boot it. The desktop computer's Linux kernel detects the device, but the file manager (Dolphin running on Debian "Stretch" 9) does not show it. GNU parted shows `Error: Invalid partition table - recursive partition on /dev/sdb.`

### Reproduction Steps ###

  1. Download the CoreOS Linux 1235.6.0 image from https://coreos.com/os/docs/latest/booting-with-iso.html
  2. Plug a USB pen drive into your computer, assuming it gets detected as `/dev/sdb`
  3. Run `sudo dd bs=4M if=$HOME/Downloads/coreos_production_iso_image.iso of=/dev/sdb`
  4. Run `sudo sync`
  5. Run `sudo dmesg` and see that the device and is still being detected
  6. Run `parted /dev/sdb` and see that it shows `Error: Invalid partition table - recursive partition on /dev/sdb.`
  7. Open Dolphin (or probably any other file manager) and see that the device is missing there

**Comment by crawford** [comment]
I wasn't able to reproduce this issue. It sounds like there may have been an issue writing to the beginning of the disk.

```
$ parted /dev/sdb print 
Modell:  (file)
Festplatte  /home/alex/Downloads/coreos_production_image.bin:  4756MB
Sektorgröße (logisch/physisch): 512B/512B
Partitionstabelle: gpt
Disk-Flags: pmbr_boot

Nummer  Anfang  Ende    Größe   Dateisystem  Name        Flags
 1      2097kB  136MB   134MB   fat16        EFI-SYSTEM  boot, legacy_boot, esp
 2      136MB   138MB   2097kB               BIOS-BOOT   bios_grub
 3      138MB   1212MB  1074MB  ext2         USR-A
 4      1212MB  2286MB  1074MB               USR-B
 6      2286MB  2420MB  134MB   ext4         OEM
 7      2420MB  2487MB  67,1MB               OEM-CONFIG
 9      2487MB  4754MB  2267MB  ext4         ROOT
```

**Comment by urzds** [comment]
@crawford You downloaded `coreos_production_image.bin.bz2` (where did you get that link from?), while I used `coreos_production_iso_image.iso`. I assumed that it is a regular hybrid USB/ISO image, as is common for many other distributions.

**Comment by urzds** [comment]
Additionally, `coreos_production_image.bin` is 4.5GiB large - too much for a cheap pen drive. Thus neither ISO nor bin image is immediately usable for us. I would hope that the ISO image would be turned into a hybrid image, which can also be dd-ed onto an USB pen drive, such that installation of CoreOS Linux becomes even easier.

**Comment by crawford** [comment]
> You downloaded coreos_production_image.bin.bz2 (where did you get that link from?), while I used `coreos_production_iso_image.iso`.

Shoot, you're right. Let me test that again. I got that link from https://stable.release.core-os.net/amd64-usr/current/ ("stable" can be swapped for "alpha" or "beta" and "current" can be omitted for a list of all of the versions available).

**Comment by marineam** [comment]
Unless something broke the ISO should be a hybrid image, though it doesn't support UEFI, only legacy BIOS booting.

**Comment by urzds** [comment]
I compared the data on the disk after dd-ing the CoreOS image onto it with the data after dd-ing some Debian image onto it. The latter did not show the `parted` error. From what I understand, a boot device needs a valid (MSDOS) MBR when booting from a legacy BIOS, but parted claims this ISO does not contain one.

**Comment by urzds** [comment]
I just confirmed that this is not a problem resulting from copying the data or broken USB pen drives and checked the ISO image in parted directly:
```
# sudo parted ~/Downloads/coreos_production_iso_image.iso
GNU Parted 3.2
Using /home/AD/tf128/Downloads/coreos_production_iso_image.iso
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) p
Error: Invalid partition table - recursive partition on .../Downloads/coreos_production_iso_image.iso.
```

Is there anything I can do to help you reproduce and fix this issue?

**Comment by crawford** [comment]
I just burned the image to a flash drive and booted it on my laptop. Make sure you are booting with BIOS (legacy) mode.

**Comment by vomlehn-coreos** [comment]
A bit more info: I used the a slightly newer version, 1235.8.0, and reproduced the issue. Then I set up the .iso on a loopback device and parted again had the same problem. The interesting thing is that I used lopsetup -P, which has the kernel read the partition table and it only thought there was one partition, of type NTFS. This suggests that the kernel and parted may be looking at the partition table differently than the bootloader.

**Comment by crawford** [comment]
Try with `gdisk` instead. That utility understands hybrid partition schemes like the one we are using. You might also want to try dropping the `bs` argument to `dd` and/or using different hardware to test.

**Comment by vomlehn-coreos** [comment]
I haven't tracked down all details, but there appears to be an issue with the partition table. The image is using the [GPT format](https://en.wikipedia.org/wiki/GUID_Partition_Table) to describe the disk layout. For backwards compatibility, the first sector in this format looks like a partition table in the old-fashioned [MBR format](https://en.wikipedia.org/wiki/Master_boot_record). The second sector has information identifying it as a GPT, along with the information for finding all of the partitions on the disk. The GPT information seems to be working fine and new BIOSes look only at that, ignoring anything in the first sector.

Older BIOSes don't know about GPT, so they ignore the second sector and try to boot with the MBR information. Parted finds what appears to be a problem with that information. It fails in the code that reads the MBR and tries to follow the extended partition chain. It encounters an extended partition that points to itself as the next in the chain. Thus, the "recursive partition" message.

The quick fix: Update to a BIOS that can handle the GPT format. It's been around for a while, so this will probably help a lot of people. But, older machines will probably never get a BIOS that smart. :-(

The painful fix: Dig into the code that writes the partition table and look for a problem where it writes extended partitions. That seems the most likely place for the image creation process to have failed.

The non-technical question is whether it is worth the effort to track this down and fix it. As old systems that can't read GPT are retired, it becomes gradually less of an issue.

**Comment by crawford** [comment]
Unfortunately, hybrid partitioning schemes are largely dependent on the firmware behaving properly. It sounds like your machine doesn't understand what is happening and refuses to boot. I've been able to boot the image on older hardware (without UEFI support) and newer hardware. I'd say it's probably not worth digging to much into the issue. It's going to be an endless battle against different firmware implementations.

**Comment by urzds** [comment]
Could you compare what you are doing to create the ISOs with what Debian does? Their images work fine.

**Comment by crawford** [comment]
We can, but this issue is a very low priority for us. The majority of our large installations are using the PXE images today. Given that I am unable to reproduce this issue with any of my hardware, I'm unable to proceed at this point. Out of curiosity, why kind of machine do you have? Is the BIOS firmware up-to-date?

**Comment by glevand** [comment]
@urzds See the ```_write_iso_disk()``` routine here: https://github.com/coreos/scripts/blob/dcc33671641fe76b17de7c30efadaf79dc4db5ea/build_library/vm_image_util.sh#L630.  What does Debian do?

**Comment by urzds** [comment]
@crawford We use these machines: Supermicro X8DTT-IBXF, Rev. 1.02, with this BIOS: Version 1.1, AMI Core Version: 08.00.15

@glevand I am certainly no expert, but I think they first create an ISO image using `xorriso` and then call their own [geniso_hybrid_plus_firmware_partition](https://anonscm.debian.org/cgit/d-i/debian-installer.git/tree/build/util/geniso_hybrid_plus_firmware_partition) script on the result. This is done in their [build/config/x86.cfg Makefile](https://anonscm.debian.org/cgit/d-i/debian-installer.git/tree/build/config/x86.cfg#n244).

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
