### ISSUE TITLE
Instance-store Backed AMIs

### ISSUE THREAD

**Issue by phemmer** [coreos/bugs#177]
This is a dup of coreos/coreos-ami-builder#1. I'm opening here as the [coreos-ami-builder](https://github.com/coreos/coreos-ami-builder) project has a description of "RETIRED", and this bug has seen no official activity after several months of inquiry from users.

The issue is a request for CoreOS to provide instance-store backed EC2 AMIs.
Instance-store volumes have several advantages in that you get a large amount of fast, reliable (compared to EBS), & free storage.

**Comment by wmark** [comment]
I've distilled 571.0.0 into such an AMI for testing purposes: ```ami-c2f68daa```

```xvdb``` will be used by Docker without any modification of your *cloud-config*.

**Comment by pwaller** [comment]
Hi @wmark, I went to try it out but I don't see it, I guess because it belongs to a specific region. Where is it, and can you make on on eu-west-1 and then I will happily test it.

**Comment by wmark** [comment]
@pwaller, sorry, it should've been replicated, but I am not cleared by Amazon for their marketplace yet, either. Here they are:

eu-west-1: ami-0522a072
ap-southeast-1: ami-cc042f9e
sa-east-1: ami-67dc607a
us-east-1: ami-c2f68daa

Good till February.

**Comment by pwaller** [comment]
@wmark I don't see `ami-0522a072` in eu-west-1. Are you sure it's public?

**Comment by wmark** [comment]
@pwaller Yes, I am. Searching with another account I can currently only find the one in us-east-1, despite them having been copied and me making them and their S3 files public.

Please send me your AWS account number **by email** and I will share them and the next iteration with you if this doesn't change within the next hour.

**Comment by pwaller** [comment]
@wmark Hm. I can see the one in us-east-1 but not the others, too. I would rather not have you pin anything on an account number, since this is a sort of detail that I would quickly forget.

**Comment by pwaller** [comment]
I checked again and now I can see them.

**Comment by derrley** [comment]
+1

**Comment by willglynn** [comment]
+1

I want this. What's next to do here? How can I help make it happen?

**Comment by willglynn** [comment]
I have a script that produces bootable AMIs and I opened a PR (coreos/scripts#576). Two AMIs produced through that process are listed in that thread if you'd like to kick the tires.

**Comment by wt** [comment]
I don't know if you know this, but you can launch EBS root images with the instance storage volumes attached on instances where that is available. If you aren't using your root volume for too much, it may work out just fine. This way you can use the EBS images and get the benefits of instance storage.

**Comment by willglynn** [comment]
@wt: True, but I want EC2 instances with _no_ dependence on EBS. As @phemmer points out, there are cost, performance, and availability advantages. Running pure instance-store has saved my bacon more than once in the past.

This is also apparently not hard to accomplish; the CoreOS build process already produces a `coreos_production_ami_image.bin` which can be bundled and registered as an instance store AMI without modification. It could therefore be added to the existing AMI build process without requiring major alterations.

**Comment by wt** [comment]
I don't disagree with your technical arguments. However, I do not see EBS root as a very big risk, especially considering that most instance new instance types are being launched without instance-root support. At this point, I am not sure it's even worth the time of the CoreOS developers to support the use case.

**Comment by willglynn** [comment]
EBS remains _a_ risk, and it's an avoidable risk. I would rather my CoreOS machines have fewer failure modes, especially ones with a history of [correlated](http://www.networkworld.com/article/2160902/cloud-computing/amazon-ebs-failure-brings-down-reddit--imgur--others.html) [failures](http://www.theregister.co.uk/2013/08/26/amazon_ebs_cloud_problems/).

Two commands. That's it. I've even written them down. Right now, CoreOS takes an image and passes it to `ec2-import-volume` + `ec2-create-snapshot`; all I'm asking is for them to run `ec2-bundle-image` + `ec2-upload-bundle` on it too.

**Comment by wt** [comment]
There is definitely a risk. I'm just not sure that the risk is as high these days. Amazon seems to have really improved since 2011, 2012, or 2013 when the linked issues happened.

With regard to the change needed by CoreOS, I would welcome such a thing as I'd love to have the option. However, they haven't chosen to do that up to this point. I figured they probably had reasons for that decision, so I'm not expecting any major changes. I would love to be surprised, but that is a decision for the CoreOS folks.

With regard to building images outside of CoreOS. I think it's great that that's possible with so little effort.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
