### ISSUE TITLE
Maximum number of CPUs setting is too low

### ISSUE THREAD

**Issue by jakub-d** [coreos/bugs#1771]
# Issue Report #

I am trying to use CoreOS on a platform with Intel 2nd Generation Xeon Phi processor.
The system boots properly, but it limits number of CPUs to 128.
In the boot log I get: 

```
Jan 21 20:44:07 localhost kernel: APIC: NR_CPUS/possible_cpus limit of 128 reached.  Processor 128/0x2 ignored.
Jan 21 20:44:07 localhost kernel: APIC: NR_CPUS/possible_cpus limit of 128 reached.  Processor 129/0x6 ignored.
Jan 21 20:44:07 localhost kernel: APIC: NR_CPUS/possible_cpus limit of 128 reached.  Processor 130/0xa ignored.
```

When I run the nproc command, I get 128.
The number should be 255 for this processor.

Please increase the `CONFIG_NR_CPUS` Kernel setting to at least 512 (RedHat uses 8192).

### CoreOS Version ###
1284.2.0

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?
Bare metal.

### Expected Behavior ###
`nproc` returns 128 

### Actual Behavior ###
`nproc` should return 255

### Reproduction Steps ###

Install CoreOS on the server with the Intel Xeon Phi 2nd Generation processor.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/2410.
