### ISSUE TITLE
motdgen depends on locksmithd, blocking user logins

### ISSUE THREAD

**Issue by llamahunter** [coreos/bugs#1774]
# Issue Report #

### CoreOS Version ###

NAME=CoreOS
ID=coreos
VERSION=1185.5.0
VERSION_ID=1185.5.0
BUILD_ID=2016-12-07-0937
PRETTY_NAME="CoreOS 1185.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

### Environment ###

AWS and Openstack

### Expected Behavior ###

User is able to log in to node even if locksmithd has not run (i.e. it is being held off so that it doesn't release its cluster reboot lock until the current node comes back up in a known good state).

### Actual Behavior ###

User is unable to log in because locksmithd is before motdgen which is before a whole bunch of stuff necessary for users to be able to log in.

### Reproduction Steps ###

  1. Configure a systemd unit to hold off the start of locksmithd for an indefinite period
  2. Boot up the node
  3. Try to log in via ssh

### Environment ###

See above

### Desired Feature ###

motdgen.service is not listed as depending on locksmithd.service

### Other Information ###

Alternatively, some way to let locksmithd come up normally, but provide a hook to *not* release its software update reboot lock until given some all clear signal.

**Comment by crawford** [comment]
Now that Ignition exists, we have a deterministic way of deciding the reboot strategy _before_ the message of the day is generated. It's probably time we strip all of that timer logic from motdgen.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/2494.
