### ISSUE TITLE
leak of document to ETCD_SSL_DIR for flannel-wrapper

### ISSUE THREAD

**Issue by kkpoon** [coreos/bugs#1775]
# Issue Report #

## Bug ##

There is an error which make my flannel cannot start. I look at the log by `journalctl` and found that the flannel could not load the TLS cert.

After walk around the `logs`, I found that cloud-init use flannel-wrapper to kick start the flannel in an `rtk` container. and the `/usr/lib/coreos/flannel-wrapper` is looking for `ETCD_SSL_DIR` environment variable.

```
#/usr/lib/coreos/flannel-wrapper
...
ETCD_SSL_DIR="${ETCD_SSL_DIR:-/etc/ssl/etcd}"
if [[ -d "${ETCD_SSL_DIR}" ]]; then
        RKT_RUN_ARGS="${RKT_RUN_ARGS} \
                --volume ssl,kind=host,source=${ETCD_SSL_DIR},readOnly=true \
                --mount volume=ssl,target=${ETCD_SSL_DIR} \
        "
fi
...
```

I could not find any document talking about this option.

### CoreOS Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.6.0
VERSION_ID=1235.6.0
BUILD_ID=2017-01-10-0545
PRETTY_NAME="Container Linux by CoreOS 1235.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Bare Metal

### Expected Behavior ###

I do not know that I should set `ETCD_SSL_DIR` while my SSL not in `/etc/ssl/etcd`,
while I expect I set the `etcd_cafile` `etcd_certfile` and `etcd_keyfile`
, and it should work

```
etcd_cafile: /etc/ssl/myssl/ca.pem
etcd_certfile: /etc/ssl/myssl/client.pem
etcd_keyfile: /etc/ssl/myssl/client-key.pem
```
The flannel-wrapper may directly mount these files into the rtk container, instead of mounting `ETCD_SSL_DIR`

### Actual Behavior ###

cannot find TLS files because of missing config of `ETCD_SSL_DIR` plus SSL cert not placing in `/etc/ssl/etcd`

**Comment by jdrowell** [comment]
I experienced the same problem. Setting ETCD_SSL_DIR=/etc/ssl in /etc/flannel/options.env seems to fix the problem if all your certs are inside that folder (or subfolders).

**Comment by crawford** [comment]
As @jdrowell mentioned, this can be fixed by overriding `ETCD_SSL_DIR` (which defaults to `/etc/ssl/etcd`). The coreos-cloudinit options you mentioned would be a great addition to CT (the successor to coreos-cloudinit). We will be revamping the configuration story over the coming months. Does that address your issue?

**Comment by kkpoon** [comment]
Sure. I was confused the guides or documents didn't mention about this magic. Thanks

**Comment by crawford** [comment]
Okay. I filed a documentation bug. I'm going to go ahead and close this one out.
