### ISSUE TITLE
container-linux-config-transpiler: add developer docs

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1777]
## Feature Request ##

I have no idea how to build container-linux-config-transpiler but poking around I ended up doing 

```
go get github.com/coreos/container-linux-config-transpiler/internal
mv ~/bin/internal ~/bin/ct
```

Perhaps we also rename `internal` to `cmd/ct`

**Comment by crawford** [comment]
In the meantime, `git clone`, `./build`.

**Comment by philips** [comment]
Can you document it?

**Comment by crawford** [comment]
Yep. The labels indicate that we recognize it as an issue and will address it.
