### ISSUE TITLE
Adding NTFS and HFS+ support

### ISSUE THREAD

**Issue by astromahi** [coreos/bugs#1781]
# Issue Report #

## Feature Request ##
We are facing a case where we need to add support for handling NTFS & HFS+ filesystem on CoreOS.
By default, CoreOS does not support these file-system.

We are running tons of server that needs these above mentioned file-system support as we plug the `NTFS` and `HFS+` drives directly into it. Compiling custom CoreOS would break our development chain. 

### Environment ###

Bare Metal and VMWare

### Desired Feature ###
We would like to have kernel modules supporting `NTFS` and `HFS+` inculded in the
CoreOS release by default.

@philips  @imagineammon

**Comment by marineam** [comment]
What do you need to do with those filesystems? The in-kernel NTFS driver has severely limited write support so effectively it is only useful for read-only access. These days the user space ntfs3g FUSE implementation is typically used instead. The kernel's HFS+ driver cannot write to journaled filesystems, though the journal feature can be turned off from macOS.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
