### ISSUE TITLE
Locksmithd releases lock before nodes are fully up, after a controlled shutdown + upgrade

### ISSUE THREAD

**Issue by pgburt** [coreos/bugs#1782]
# Issue Report #

## Feature Request ##

We would prefer to finish bringing newly upgraded nodes fully back in to service before releasing a lock (re: locksmithd).

### Desired Feature ###

Would like to be able to use a systemd unit dropin.

### Other Information ###

Taken from https://groups.google.com/forum/#!topic/coreos-user/5l-dxlYRzgU

<details>
   <summary>text from GG</summary>
  Hi there-

Generally speaking, we like the 'auto update' feature of CoreOS.  However, we would like to do controlled shutdown and bring up of our nodes whenever possible (they can handle uncontrolled shutdown, too, but recovery time may be longer, and user experience is marginally better if they are cleanly removed from service).

To that end, we've added a systemd unit with a blocking ExecStop (and a long TimeoutStopSec) until things are cleanly shut down before allowing controlled reboots.  This works fine on the way down.

However, on the way back up after upgrade, it appears that locksmithd releases its lock as soon as it runs.  This allows the next node in the cluster to reboot immediately.  We would prefer to finish bringing the newly upgraded node fully back in to service before releasing this lock.

It seemed like simply delaying the execution of locksmithd via a systemd unit dropin would be straightforward.  However, for reasons I can't ascertain, motdgen.service depends on locksmithd, with halts the bringup of the whole system into multi user mode if locksmithd.  Thus, if something goes awry when bringing back the node online, you can't even ssh into the node to debug what's going on.

So, is there a better way to use locksmithd to do coordinated reboots, but hold it off from releasing the lock until we're ready, without blocking us from being able to ssh into the node in the meantime?

Richard
</details>

**Comment by llamahunter** [comment]
This includes baremetal, openstack, and aws node deployments, running the current coreos stable, beta, and alpha channels (currently 1235.6.0, 1248.4.0, and 1298.1.0, respectively).

**Comment by dm0-** [comment]
Since `locksmithd` no longer runs after `motdgen`, are you now able to use a drop-in to run it after whatever services you want to be started first?

**Comment by bgilbert** [comment]
Closing due to lack of response.
