### ISSUE TITLE
Ignition `-fw_cfg` flag not recognized by qemu-kvm

### ISSUE THREAD

**Issue by pgburt** [coreos/bugs#1783]
# Issue Report #

Original post on the Google Group [here](https://groups.google.com/forum/#!topic/coreos-user/g4ujTncIW8M).

### Environment ###

Ubuntu 16.04

### Expected Behavior ###

The `-fw_cfg` Ignition option is recognized when passed to qemu-kvm.

### Actual Behavior ###

The `-fw_cfg` option to qemu-kvm is not recognised (I think that the version of qemu-kvm installed might not support -fw_cfg, it is running 1.5.3).

### Reproduction Steps ###

  1. ...
  2. ...

### Other Information ###

Original post on the Google Group [here](https://groups.google.com/forum/#!topic/coreos-user/g4ujTncIW8M).

**Comment by dm0-** [comment]
It looks like the option first appeared in [2.4.0](https://github.com/qemu/qemu/compare/v2.3.0...v2.4.0#diff-829d87af1b357a252f641782d14111f1R2697).

You can still use the `coreos.config.url=` boot parameter for Ignition.  Since this is for QEMU, if hosting the Ignition file somewhere isn't feasible, you could either inject an Ignition file into the OEM partition on the disk image:

    sudo mount -o x-mount.mkdir,offset=2285895680 coreos_production_image.bin oem
    sudo cp ignition.json oem/
    echo 'set linux_append="coreos.config.url=oem:///ignition.json"' | sudo tee oem/grub.cfg
    sudo umount -d oem && sudo rmdir oem

Or serve it locally over HTTP (with `coreos.config.url=http://10.0.2.2:8080/` for this):

    file=ignition.json nc -klp 8080 -c 'echo -e "HTTP/1.1 200 OK\r\nContent-Length: $(stat -c %s $file)\r\nContent-Type: text/plain\r\n\r" ; cat $file'

**Comment by euank** [comment]
Indeed, it was added in qemu version 2.4: http://wiki.qemu.org/ChangeLog/2.4#Command-line_options

It's possible that the config-drive option from the [openstack provider](https://github.com/coreos/ignition/pull/287) could be used on older versions of qemu, but really the best course of action is updating qemu to a recent version

**Comment by dm0-** [comment]
I've heard previously that forcing the OpenStack provider on QEMU for config-drive support will have other adverse affects.  It seems that method is only [usable for cloud-config](https://coreos.com/os/docs/latest/config-drive.html), not Ignition.

**Comment by crawford** [comment]
@dm0- is right. Use `coreos.config.url` to point Ignition at the config. HTTP and HTTPS URLs are supported so you could even through it in a gist.

**Comment by craigtracey** [comment]
This issue was resolved for me by upgrading QEMU to 2.6 on my Xenial host OS.  This did *not* work with qemu @ 2.5+dfsg-5ubuntu10.9.  2.6 is easily obtained via Launchpad PPA: https://launchpad.net/~jacob/+archive/ubuntu/virtualisation
