### ISSUE TITLE
Ingition: enabled systemd unit does not start

### ISSUE THREAD

**Issue by styxlab** [coreos/bugs#1786]
# Issue Report #
I have the following ignition config:

```
systemd:
  units:
    - name: rpc-mountd.service
      enable: true
```
but the rpc-mountd.service is not started:
```
core@localhost ~ $ systemctl status rpc-mountd.service
● nfs-mountd.service - NFS Mount Daemon
   Loaded: loaded (/usr/lib/systemd/system/nfs-mountd.service; static; vendor preset: disabled)
   Active: inactive (dead)
```
### Question ###
How can I activate this service with ignition?

### CoreOS Version ###
Container Linux by CoreOS stable (1235.6.0)

### Expected Behavior ###
rpc-mountd.service reaches active state on first boot

### Actual Behavior ###
rpc-mountd.service reaches inactive state on first boot

### Other Information ###

I'm trying to migrate from cloud_config to ignition. The same works fine with cloud_config, but here I have the `command: start` that is not available in ignition.

```
    - name: rpc-mountd.service
      command: start
      enable: true
```

**Comment by crawford** [comment]
Does [this documentation](https://coreos.com/ignition/docs/latest/getting-started.html#enabling-systemd-services) address your issue?

**Comment by styxlab** [comment]
I'm on first boot, so I do not understand how this documentation addresses the issue.

**Comment by crawford** [comment]
Okay, it wasn't clear from the original report that it was first boot.

Looking at that service, there is no `[Install]` section, so it cannot be enabled. This makes sense given that this service generally shouldn't be used on its own. Both `nfsd.service` and `nfs-server.service` start it up for their use. What are you trying to accomplish?

**Comment by styxlab** [comment]
Thanks for your help, that really points into the right direction. After adding both `nfsd.service` and `nfs-server.service` to my ignition config, the `rpc-mountd.service` came finally active on first boot. So, that solves it for me although I'm a bit puzzled that I did not have to enable those services in my cloud_config.

I'm trying to make NFS storage available through an appropriate NFS service. That worked fine with the `rpc-mountd.service` when created with cloud_config.

**Comment by crawford** [comment]
`nfsd.service` is actually a symlink to `nfs-server.service`. If your intent is to run an NFS server on Container Linux, `nfs-server.service` is the service you'll want to start.

**Comment by styxlab** [comment]
Great. That's exactly what I needed.

**Comment by seh** [comment]
I asked a related question about forcing Ignition to run again [here](https://github.com/coreos/bugs/issues/2090#issuecomment-388195088).
