### ISSUE TITLE
Follow-up backport for R/W support of /proc and /sys is missing in systemd-nspawn

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/bugs#1789]
# Issue Report #

### Container Linux Version ###

1284.2.0

### Other Information ###

https://github.com/coreos/systemd/pull/71 backported R/W support for `/proc` and `/sys` in `systemd-nspawn`. The upstream maintainer @evverx gave us a hint that another backport commit is missing, namely https://github.com/systemd/systemd/pull/4824.

https://github.com/coreos/systemd/pull/77 fixes it.

**Comment by dm0-** [comment]
This was merged for alpha, but is has missed the window for the currently building stable and beta branches.
