### ISSUE TITLE
Container Linux support in AWS China

### ISSUE THREAD

**Issue by eddieesquivel** [coreos/bugs#1792]
# Issue Report #

### Environment ###

AWS China

### Desired Feature ###

Would like to have Container Linux support in China so that I can install Tectonic in that region.

**Comment by bgilbert** [comment]
Starting with this week's releases, we're now creating Container Linux AMIs in AWS China.

**Comment by mazzy89** [comment]
@bgilbert could you share some insights about the creation/pushing of AMIs to China? Did you go with the recommended way that is creating an image with Linux `dd` command and push this image to an instance in China?

**Comment by bgilbert** [comment]
We use the [same flow](https://github.com/coreos/mantle/blob/2dfef80dd89998b7ed8a7533261747e2ef828770/cmd/plume/prerelease.go#L512-L553) with AWS China that we use with other AWS partitions: upload a disk image as an S3 object, [create a snapshot from it](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ImportSnapshot.html), then [create an AMI from that](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RegisterImage.html).

**Comment by mazzy89** [comment]
Hi @bgilbert thanks a lot for ther quick reaction and to point out to those resources. This is just gold. I'm helping here Kinvolk guys to push Flatcar AMI to AWS China. We at GiantSwarm have an entity to AWS China so we'll push Flatcar and make it available in China.
