### ISSUE TITLE
Docker 1.13.0 logging warning about runc version.

### ISSUE THREAD

**Issue by ktwalrus** [coreos/bugs#1794]
Using the latest alpha (v1313.0.0), the docker daemon is logging lots of warnings:
```
Feb 05 15:07:02 vps02 dockerd[890]: time="2017-02-05T15:07:02.232137275Z" level=warning msg="failed to retrieve docker-runc version: unknown output format: runc version 1.0.0-rc2\nspec: 1.0.0-rc2-dev\n"
Feb 05 15:07:02 vps02 dockerd[890]: time="2017-02-05T15:07:02.232293956Z" level=warning msg="failed to retrieve docker-init version"
```

**Comment by bzub** [comment]
There is a bug in Docker 1.13, see: [docker/docker#30083](https://github.com/docker/docker/issues/30083)

Either have to downgrade or get 1.13.1-rc1.

**Comment by euank** [comment]
The first warning log should be fixed by https://github.com/coreos/coreos-overlay/pull/2428 and was fairly harmless.

The second one's a bug which probably results in `docker run --init=true` also not working.

**Comment by dm0-** [comment]
Linking to coreos/coreos-overlay#2517.

**Comment by euank** [comment]
Neither of these warnings are printed on the current releases, and we added a regression test which should catch this (the `docker info` test).
