### ISSUE TITLE
Support for docker run --security-opt=no-new-privileges

### ISSUE THREAD

**Issue by hmalphettes** [coreos/bugs#1796]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1313.0.0
VERSION_ID=1313.0.0
BUILD_ID=2017-02-03-0826
PRETTY_NAME="Container Linux by CoreOS 1313.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###
AWS-EC2 / Vagrant-Virtualbox

### Expected Behavior ###
Prevent privilege escalation inside containers with `docker run --security-opt=no-new-privileges`.

### Actual Behavior ###

```
docker run --rm -ti --security-opt=no-new-privileges alpine sh
panic: standard_init_linux.go:175: exec user process caused "operation not permitted" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "operation not permitted"

goroutine 1 [running, locked to thread]:
panic(0x7eb6e0, 0xc82014d500)
	/usr/lib/go1.6/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc820123300)
```

**Comment by euank** [comment]
This is related to SELinux. Running `docker run --security-opt=no-new-privileges --security-opt label=disable` or dockerd without `--selinux-enabled` works around it.

The relevant audit log:

```
audit: type=1401 audit(1488497948.120:145): op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:kernel_t:s0 newcontext=system_u:system_r:svirt_lxc_net_t:s0:c616,c673
audit: type=1300 audit(1488497948.120:145): arch=c000003e syscall=59 success=no exit=-1 a0=c820158a98 a1=c820158ab0 a2=c820136e40 a3=0 items=0 ppid=4470 pid=4487 auid=500 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts2 ses=6 comm="runc:[2:INIT]" exe="/usr/bin/runc" subj=system_u:system_r:kernel_t:s0 key=(null)
```

**Comment by hmalphettes** [comment]
@euank Thanks for the workaround.

**Comment by euank** [comment]
This was fixed somewhere between docker `1.13.0` and `17.06.1-ce`.
On the current alpha `docker run --rm -ti --security-opt=no-new-privileges alpine sh` works as expected.

**Comment by trevex** [comment]
I am on the current Container Linux stable release `1576.5.0` and am trying to get the `nvidia-container-runtime` to work (specifically to use nvidias k8s device plugin).

Interestingly enough I get the exact same error:
```
standard_init_linux.go:185: exec user process caused "operation not permitted"
```

I am wondering how this was resolved? Are there specific patches for runc for Container Linux? (nvidia-container-runtime is just a set of patches for runc)

**Comment by euank** [comment]
@trevex that error is fairly generic.
The best way to identify the actual error is to follow [these instructions](https://coreos.com/os/docs/latest/selinux.html#check-a-containers-compatibility-with-selinux-policy) to have selinux log audit results.

The audit output will then hopefully make it clear what's breaking. I don't know exactly what changed on the docker/runc side to fix this issue before, sorry!

I did verify the issue originally reported here hasn't regressed, so what you're observing would probably best be reported as a new issue.

**Comment by trevex** [comment]
Thank you, @euank. The gpu node is currently in use, but I'll schedule another downtime and will try to inspect the selinux log and hopefully with more conclusive findings I'll open a new issue.
