### ISSUE TITLE
Container Linux support in AWS .GOV cloud

### ISSUE THREAD

**Issue by eddieesquivel** [coreos/bugs#1800]
### Environment ###

Hi, Would like to have Container Linux available in .GOV cloud. I'd like to be able to install Tectonic there.

**Comment by robszumski** [comment]
Check out https://coreos.com/os/docs/latest/booting-on-ec2.html#ec2-images and `us-gov-west-1`.

Here are the current Container Linux 1235.9.0 AMIs:

`ami-5ec77d3f`
`ami-12c67c73`

**Comment by ketzacoatl** [comment]
@robszumski, does CoreOS have an Account ID published, for locating the images on GovCloud with tools like Terraform?

**Comment by robszumski** [comment]
@crawford any idea about that ^^?

**Comment by bgilbert** [comment]
@ketzacoatl It's not currently published on our website, but you can get the account ID by doing a DescribeImages on one of our AMIs.  On GovCloud our account ID is 190570271432.

**Comment by ketzacoatl** [comment]
TY!
