### ISSUE TITLE
coreos document misunderstand??

### ISSUE THREAD

**Issue by sunvooker** [coreos/bugs#1803]
# Issue Report #
in the guide document: https://coreos.com/os/docs/latest/booting-on-azure.html

say: "This will additionally create an endpoint allowing SSH traffic to reach the newly created instance. If you bring up more machines, you'll need to choose a different port for each instance."

why need different port??  same port have problem??

i don't know why,  can someone explain it, thks.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Reproduction Steps ###

  1. ...
  2. ...

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

**Comment by coresolve** [comment]
This is a limitation of the azure endpoint that you create. You can create multiple endpoints as well. Basically the endpoint sits between the internet and your internal services like ssh.
