### ISSUE TITLE
CoreOS 1235.9.0 Bare Metal /dev/sda3 has unsupported feature(s) - e2fsck: Get a newer version of e2fsck!

### ISSUE THREAD

**Issue by celevra** [coreos/bugs#1810]
got this error on 
Container Linux by CoreOS stable (1235.9.0)

the whole system isn't booting, it boots to failsave.
It is bare metal.
what do you need to dig deeper into this?

![image](https://cloud.githubusercontent.com/assets/232437/22969983/b9d1109a-f370-11e6-8b57-f282ea18a6b6.png)
![image](https://cloud.githubusercontent.com/assets/232437/22969507/08a7910a-f36f-11e6-8371-2c36ed3a1ffa.png)

**Comment by bgilbert** [comment]
The third partition is /usr, and intentionally has unsupported features; that's how we enforce /usr being read-only.  The boot already failed before the top of your first screenshot.  Could you grab screenshots from a couple earlier pages' worth of messages?

**Comment by celevra** [comment]
here they come:

![image](https://cloud.githubusercontent.com/assets/232437/23078771/5dad33a8-f54a-11e6-8544-890748cb2c19.png)

![image](https://cloud.githubusercontent.com/assets/232437/23078742/3f7a3f98-f54a-11e6-8be8-f04dec4cbb0e.png)

![image](https://cloud.githubusercontent.com/assets/232437/23078731/2d700a4e-f54a-11e6-9b84-20e8358bb2b8.png)

![image](https://cloud.githubusercontent.com/assets/232437/23078727/234cd0e2-f54a-11e6-873a-3e32029ea5f5.png)

**Comment by celevra** [comment]
fsck -y /dev/disk/by-label/ROOT helped...
what a pity, i'm closing, sorry for wasting your thime
