### ISSUE TITLE
Handle coreos-metadata.service on QEMU

### ISSUE THREAD

**Issue by dm0-** [coreos/bugs#1815]
### Environment ###

QEMU

### Desired Feature ###

The `coreos-metadata.service` unit fails with an `invalid provider` error if it is run on QEMU.  This complicates sharing system configurations between platforms.

Maybe add a unit condition, a QEMU provider, or just exit successfully when there is nothing to do.

### Other Information ###

coreos/mantle#466

**Comment by crawford** [comment]
Why is that service running? Did Ignition erroneously start it?

**Comment by dm0-** [comment]
It is started intentionally because other platforms require it, but it causes system startup to fail on QEMU.  The context is in the linked mantle PR.  It breaks most Ignition-based kola tests.

**Comment by crawford** [comment]
QEMU isn't supported, so don't start it when running on that platform. Your solution in the linked PR seems fine if you are limited to reusing the same config everywhere
