### ISSUE TITLE
AWS Enhanced Networking Intel 82599 VF Interface Not Working

### ISSUE THREAD

**Issue by holybit** [coreos/bugs#1816]
# Issue Report #

## Bug ##

AWS [Enhanced Networking with the Intel 82599 VF Interface](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sriov-networking.html) not working at 10GB throughput

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.9.0
VERSION_ID=1235.9.0
BUILD_ID=2017-02-02-0235
PRETTY_NAME="Container Linux by CoreOS 1235.9.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

AWS - CoreOS-stable-1235.9.0-hvm (ami-fd6c94eb)

### Expected Behavior ###

Two EC2 Container Linux instances `m4.large` w/ Enhanced Networking enabled should be seeing network through put of ~10Gbps per #273 

### Actual Behavior ###

Actual through put ~.5Gbps

### Reproduction Steps ###

  1. Login to AWS Console
  2. Spin up two Container Linux EC2 instances (i.e., ami-fd6c94eb) in us-east-1 as m4.large. Both instances should be in the same subnet of the same VPC. Setup security groups on each so you can SSH to them and they both allow ingress on port 5001.
  3. SSH to both instances
  4. Launch toolbox
  5. Install iperf3 to [benchmark network throughput](https://aws.amazon.com/premiumsupport/knowledge-center/network-throughput-benchmark-linux-ec2/)
  6. Choose one machine as the iperf3 client and the other as the server. Doesn't matter which is which.
  7. server - `iperf3 -s -p 5001`
  8. client - `iperf3 -c SERVER_IP -i 10 -t 60 -V -f g -p 5001`
  9. Run this client for a few minutes and then CTRL-C both client and server.

Client results
```
$ iperf3 -c 10.248.25.51 -i 10 -t 60 -V -f g -p 5001
iperf 3.1.3
Linux ip-10-248-16-248.lan.returnpath.net 4.7.3-coreos-r2 #1 SMP Thu Feb 2 02:26:10 UTC 2017 x86_64
Time: Sat, 18 Feb 2017 04:47:43 GMT
Connecting to host 10.248.25.51, port 5001
      Cookie: ip-10-248-16-248.lan.returnpath.net.
      TCP MSS: 8949 (default)
[  4] local 10.248.16.248 port 38398 connected to 10.248.25.51 port 5001
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 60 second test
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-10.00  sec   677 MBytes  0.57 Gbits/sec  307    367 KBytes
[  4]  10.00-20.00  sec   533 MBytes  0.45 Gbits/sec  100    306 KBytes
[  4]  20.00-30.00  sec   533 MBytes  0.45 Gbits/sec  106    341 KBytes
[  4]  30.00-40.00  sec   533 MBytes  0.45 Gbits/sec  106    376 KBytes
[  4]  40.00-50.00  sec   533 MBytes  0.45 Gbits/sec  108    271 KBytes
[  4]  50.00-60.00  sec   533 MBytes  0.45 Gbits/sec  101    306 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-60.00  sec  3.26 GBytes  0.47 Gbits/sec  828             sender
[  4]   0.00-60.00  sec  3.26 GBytes  0.47 Gbits/sec                  receiver
CPU Utilization: local/sender 1.1% (0.0%u/1.1%s), remote/receiver 2.9% (0.3%u/2.7%s)

iperf Done.
```

### Other Information ###

I checked a few basic setting for both instances to ensure they are correctly configured for EN Intel 82599 VF Interface support. I'll list the results for only one instance, but both had identical results for each command.

SriovNetSupport for both instances is "simple" as required for EN.
```
$ aws ec2 describe-instance-attribute --instance-id "i-094f3b57f1ef3d3f0" --attribute sriovNetSupport
{
    "InstanceId": "i-094f3b57f1ef3d3f0",
    "SriovNetSupport": {
        "Value": "simple"
    }
}
```

Modinfo
```
$ modinfo ixgbevf
filename:       /lib/modules/4.7.3-coreos-r2/kernel/drivers/net/ethernet/intel/ixgbevf/ixgbevf.ko
version:        2.12.1-k
license:        GPL
description:    Intel(R) 10 Gigabit Virtual Function Network Driver
author:         Intel Corporation, <linux.nics@intel.com>
srcversion:     21AEE2E548FCFE26FC2FB9F
alias:          pci:v00008086d000015A9sv*sd*bc*sc*i*
alias:          pci:v00008086d000015A8sv*sd*bc*sc*i*
alias:          pci:v00008086d00001564sv*sd*bc*sc*i*
alias:          pci:v00008086d00001565sv*sd*bc*sc*i*
alias:          pci:v00008086d00001530sv*sd*bc*sc*i*
alias:          pci:v00008086d00001515sv*sd*bc*sc*i*
alias:          pci:v00008086d0000152Esv*sd*bc*sc*i*
alias:          pci:v00008086d000010EDsv*sd*bc*sc*i*
depends:
intree:         Y
vermagic:       4.7.3-coreos-r2 SMP mod_unload
parm:           debug:Debug level (0=none,...,16=all) (int)
```

ethtool
```
$ ethtool -i eth0
driver: ixgbevf
version: 2.12.1-k
firmware-version:
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

journalctl
```
$ journalctl | grep ixgbevf
Feb 18 02:36:56 localhost kernel: ixgbevf: Intel(R) 10 Gigabit PCI Express Virtual Function Network Driver - version 2.12.1-k
Feb 18 02:36:56 localhost kernel: ixgbevf: Copyright (c) 2009 - 2015 Intel Corporation.
Feb 18 02:36:56 localhost kernel: ixgbevf 0000:00:03.0: 0e:c2:c4:3a:d2:c4
Feb 18 02:36:56 localhost kernel: ixgbevf 0000:00:03.0: MAC: 1
Feb 18 02:36:56 localhost kernel: ixgbevf 0000:00:03.0: Intel(R) 82599 Virtual Function
Feb 18 02:36:56 localhost kernel: ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
Feb 18 02:37:14 localhost kernel: ixgbevf 0000:00:03.0: NIC Link is Up 10 Gbps
```

**Comment by euank** [comment]
I don't think this is a Container Linux bug.
If you run iperf3 on, say, the Amazon Linux AMI instead you still get roughly the same numbers.

m4.larges, even though they have ENA support, still have limited network bandwidth.

The [instance detail](https://aws.amazon.com/ec2/instance-types/) page calls this out in the "network performance" column by only claiming "moderate" performance.

The somewhat well hidden [instance type network limits](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-ec2-config.html) table claims m4.large instances have a max bandwidth of 450Mb/s.

From the same table, only the m4.16xlarge instances in the m4 series should get a full 10Gb/s.

Hopefully that helps,
Euan

**Comment by holybit** [comment]
@euank Thanks for response and clarity on how AWS ENA behaves in the real world. Agree 100% not a Container Linux bug.

**Comment by kylegato** [comment]
I think this should be re-opened. This could probably be avoided by using placement groups. 

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html

**Comment by euank** [comment]
@kylegato Mind clarifying what you mean?
I think my response, that this isn't a bug in Container Linux, still stands. Using placement groups does sound like it would help, but I don't think there's anything we need to do on the OS-side of things to enable that.

**Comment by kylegato** [comment]
@euank Sorry I got this repo confused w/ the kube-aws project. The kube-aws project needs a placement group method.
