### ISSUE TITLE
Ignition not working on OpenStack

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/bugs#1817]
### Container Linux Version ###

```
core@localhost ~ $ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.9.0
VERSION_ID=1235.9.0
BUILD_ID=2017-02-02-0235
PRETTY_NAME="Container Linux by CoreOS 1235.9.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Openstack - https://vexxhost.com/

### Expected Behavior ###

Ignition configs should work.

### Actual Behavior ###

Ignition configs don't work.

### Reproduction Steps ###

https://gist.github.com/s-urbaniak/8108dfa3269da858c489f8cdf38d6461

  1. Create a vexxhost account
  2. Create an instance like this:

```
$ openstack flavor list | grep v1-standard-4
| 5cf64088-893b-46b5-9bb1-ee020277635d | v1-standard-4   |   4096 |  100 |         0 |     4 | True      |
$ openstack image list | grep -i container
| 90f57210-9354-4a2f-852e-d844237fbbad | Container Linux 1235.9.0                  | active |
$ jq . user_data.ign
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "storage": {},
  "systemd": {
    "units": [
      {
        "name": "docker.service",
        "enable": true,
        "dropins": [
          {
            "name": "10-overlay.conf",
            "contents": "[Service]\nEnvironmentFile=/etc/node.env\nEnvironment=\"DOCKER_OPTS=--storage-driver=overlay2\"\n"
          }
        ]
      }
    ]
  },
  "networkd": {},
  "passwd": {}
}
$ nova boot \
  --image 90f57210-9354-4a2f-852e-d844237fbbad \
  --flavor 5cf64088-893b-46b5-9bb1-ee020277635d \
  --user-data user_data.ign \
  sur-test
```

### Other Information ###

The kernel boot log is available here: https://gist.github.com/s-urbaniak/8108dfa3269da858c489f8cdf38d6461#file-gistfile1-txt

/cc @alexsomesan

**Comment by philips** [comment]
cc @dgonyeo

**Comment by s-urbaniak** [comment]
I modified locally the contents of `grub.cfg` on a local `coreos_production_openstack_image.img` qcow image to have the following parameters:

```
 systemd.journald.forward_to_console=true coreos.autologin=tty1 coreos.autologin=ttyS0
```

I updated the kernel output here: https://gist.github.com/s-urbaniak/8108dfa3269da858c489f8cdf38d6461#file-gistfile1-txt

Bonus point: since we have `coreos.autologin` set, one can have a working VNC terminal:
```
(openstack) console url show test
+-------+------------------------------------------------------------------------------------------------+
| Field | Value                                                                                          |
+-------+------------------------------------------------------------------------------------------------+
| type  | novnc                                                                                          |
| url   | https://vnc-ca-ymq-1.vexxhost.net:443/vnc_auto.html?token=ffffffff-fff8-49ed-a1ac-9cd123defabc |
+-------+------------------------------------------------------------------------------------------------+
```

Open the above URL in the browser.

**Comment by s-urbaniak** [comment]
fwiw here is something I catched, while the machine was booting:

![2017-02-21-143918_1525x196_scrot](https://cloud.githubusercontent.com/assets/375856/23167178/a5fe75ee-f843-11e6-8f64-622be38437df.png)

**Comment by dm0-** [comment]
Closing this, since it sounds like the above PRs fixed it.

**Comment by s-urbaniak** [comment]
@dm0- yes, indeed, the bug is fixed, thanks.
