### ISSUE TITLE
[UI] [Quay] "Add team member" does not show profile picture

### ISSUE THREAD

**Issue by billforward-alex** [coreos/bugs#1819]
Tried to add team member to one of my organization's teams:

![image](https://cloud.githubusercontent.com/assets/9741519/23170452/177836d0-f847-11e6-8b27-27c70aab7ba8.png)

I wasn't sure if this was the right person (it did not show the profile picture).

The fastest way for me to view the user's profile was to send the invite (without yet knowing their identity):

![image](https://cloud.githubusercontent.com/assets/9741519/23170509/4a6a0f32-f847-11e6-88c3-db0bf035d4f3.png)

It would be nice if it were possible to see profile details _before_ sending the invite. :)

**Comment by jzelinskie** [comment]
This should be in production now. Sorry about the closed issue without any context; our private PR linked to this issue.

Nice luluco avatar, btw.
