### ISSUE TITLE
Support for "Container Linux"-specific configuration

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1820]
# Issue Report #

### Desired Feature ###

CT should support configuring tools like etcd and flannel directly in the configuration. Instead of the user needing to understand which services to modify and how exactly to modify them, some high-level options should be available in the config.

**Comment by dgonyeo** [comment]
With the recent merging of support for configuring etcd and flannel (https://github.com/coreos/container-linux-config-transpiler/pull/18), and support for setting an update group (https://github.com/coreos/container-linux-config-transpiler/pull/40), mind if I close this?
