### ISSUE TITLE
systemd-networkd does not set up IPv6 addresses in EC2 (via DHCPv6)

### ISSUE THREAD

**Issue by ilianaw** [coreos/bugs#1828]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.12.0
VERSION_ID=1235.12.0
BUILD_ID=2017-02-23-0222
PRETTY_NAME="Container Linux by CoreOS 1235.12.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

AWS (ami-444dcd24) in an [IPv6-enabled VPC](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/get-started-ipv6.html)

### Expected Behavior ###

The instance should have a global-scope IPv6 address, e.g.:

```
$ ip -6 addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 state UP qlen 1000
    inet6 2600:1f14:46d:a700:fc55:9d1c:8968:2517/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::8bc:2cff:fe4c:ba2b/64 scope link 
       valid_lft forever preferred_lft forever
```

### Actual Behavior ###

```
$ aws ec2 describe-instances --instance-ids i-0addb095b6ec65bdc --output json \
> | jq '.Reservations[].Instances[].NetworkInterfaces[].Ipv6Addresses[].Ipv6Address'
"2600:1f14:46d:a700:fc55:9d1c:8968:2517"
$ ip -6 addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 state UP qlen 1000
    inet6 fe80::8bc:2cff:fe4c:ba2b/64 scope link 
       valid_lft forever preferred_lft forever
```

### Reproduction Steps ###

  1. Use the [VPC Wizard](https://us-west-2.console.aws.amazon.com/vpc/home?region=us-west-2#wizardSelector:) to create a `VPC with a Single Public Subnet`, selecting `Amazon provided IPv6 CIDR block` under `IPv6 CIDR Block` (or [follow these instructions](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/get-started-ipv6.html#get-started-ipv6-vpc))
  2. Configure the subnet to auto-assign an IPv6 address
  3. Run `CoreOS-stable-1235.12.0-hvm` (ami-444dcd24 in us-west-2) in the newly created subnet
  4. `ip -6 addr show dev eth0`

### Other Information ###

I work for Amazon EC2 (specifically on Amazon Linux, and I implemented the changes required for IPv6 support there). I can either answer questions you have about IPv6 support in EC2 or find the people who can answer them.

Amazon's solution for providing IPv6 to EC2 instances is *technically* RFC-compliant: in order to reliably know what IPv6 address the instance has, we have to assign it one (or several), instead of letting it pick one. This requires DHCPv6, which many cloud-like images of Linux distributions are unable to support (*shakes fists at network setup shell scripts*), as the RFC specifies listening for an ICMPv6 router advertisement packet with the `M` flag set to 1 ([RFC 4861](https://tools.ietf.org/html/rfc4861#section-4.2)), then starting your DHCPv6 client daemon process.

systemd-networkd *should* support this out of the box per relevant documentation, but I'm not sure why it's not reacting to the RA messages. I've verified that the host is receiving router advertisements with the `M` flag:

```
[root@ip-10-0-0-225 /]# tcpdump -i eth0 icmp6 -vvv
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
02:37:28.177406 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 56) fe80::824:50ff:fec2:d469 > ff02::1: [icmp6 sum ok] ICMP6, router advertisement, length 56
        hop limit 64, Flags [managed], pref medium, router lifetime 1800s, reachable time 0ms, retrans time 0ms
          source link-address option (1), length 8 (1): 0a:24:50:c2:d4:69
            0x0000:  0a24 50c2 d469
          prefix info option (3), length 32 (4): 2600:1f14:46d:a700::/64, Flags [none], valid time infinity, pref. time infinity
            0x0000:  4000 ffff ffff ffff ffff 0000 0000 2600
            0x0010:  1f14 046d a700 0000 0000 0000 0000
```

I set up a CentOS 7 instance to use systemd-networkd (v219ish) and it's also failing to set up an IPv6 address (with the only configuration being `DHCP=yes`). I should also test both on a basic DHCPv6-enabled home network.

**Comment by crawford** [comment]
Have you tried enabling [`IPv6AcceptRA`](https://www.freedesktop.org/software/systemd/man/systemd.network.html#IPv6AcceptRA=)? I can't tell from the documentation if that is enabled by default.

**Comment by ilianaw** [comment]
I set it to `yes` on my CentOS host and that had no effect; the sysctls didn't seem to change either. And if the sysctls were set to not accept RAs, there wouldn't be a default route:

```
core@ip-10-0-0-225 ~ $ ip -6 route show
fe80::/64 dev eth0  proto kernel  metric 256  mtu 9001
default via fe80::824:50ff:fec2:d469 dev eth0  proto ra  metric 1024 
```

I haven't tried it on Container Linux yet because I haven't quite figured out if simply copying ``/usr/lib/systemd/network/zz-default.network`` to ``/etc/systemd/network`` actually does an override of that file correctly.

**Comment by euank** [comment]
@ilianaw 

> The first (in lexical order) of the network files that matches a given device is applied, all later files are ignored, even if they match as well. - [systemd.network](https://www.freedesktop.org/software/systemd/man/systemd.network.html)

Anything that matches and is named before `zz` (e.g "00-eth0.network") should cause it to ignore the `zz` match entirely.

To make sure it's early enough, you should use ignition https://coreos.com/os/docs/latest/network-config-with-networkd.html#ignition-config

**Comment by takaomag** [comment]
See these my posts.

- [How to disable rapid-commit option on DHCPv6 client (systemd-networkd and dhcpcd)](https://serverfault.com/questions/838327/how-to-disable-rapid-commit-option-on-dhcpv6-client-systemd-networkd-and-dhcpcd)

- [DHCPv6 server does not respond to SOLICT messages](https://forums.aws.amazon.com/thread.jspa?messageID=772808&tstart=0)

According to https://tools.ietf.org/html/rfc3315#section-17.2.1, I guess DHCPv6 server in VPC is not RFC compliant.
One workarounds,
- Use dhclient container with `--net host` and `--privileged`

And ask Amazon to make their DHCPv6 server be RFC compliant.

**Comment by benpiper** [comment]
Its DHCPv6 server does seem to be compliant. From section 17.2.1:
> The server ... checks its administrative policy about responding to the client.  **If the server is not permitted to respond to the client, the server discards the Solicit message.**

**Comment by couling** [comment]
I stumbled on this looking for why EC2 wouldn't setup an IPv6 address on Ubuntu server.
I noted the comment in the question that this also affects CentOS and it made me wonder if it's a more general wider linux config issue.

I've stumbled on a fix for Ubuntu server which was less than obvious:

In `/etc/network/interfaces.d/50-cloud-init.cfg` (aka `/etc/network/interfaces`) add a line to specifically DHCP on IPv6:

```
auto eth0
iface eth0 inet dhcp
## Add the below line
iface eth0 inet6 dhcp
```
On an Ubuntu EC2 instance it WILL NOT assign a V6 address without this.  With this line it will detect the IP allocted in the AWS console.  As it's not mentioned in the "steps to reproduce", you might want to check if the same issue affects CoreOS.

**Comment by lucab** [comment]
@couling thanks for checking in. ContainerLinux doesn't ship/use ifupdown, so it is likely not related. Such configuration and network function is handled directly by systemd-networkd instead.

**Comment by euank** [comment]
xref https://github.com/systemd/systemd/issues/5845; it looks like there is some movement related to this upstream.

**Comment by bgilbert** [comment]
It looks as though this is working now (tested alpha 1786.0.1), so I'll close.  Thanks for the report!
