### ISSUE TITLE
Add support for PCI virtual nics

### ISSUE THREAD

**Issue by polvi** [coreos/bugs#183]
SR-IOV enables a Single Root Function (for example, a single Ethernet port), to appear as multiple, separate, physical devices. A physical device with SR-IOV capabilities can be configured to appear in the PCI configuration space as multiple functions. Each device has its own configuration space complete with Base Address Registers (BARs).

Should just be a kernel module addition /cc @philips

**Comment by crawford** [comment]
@marineam has this been resolved?
