### ISSUE TITLE
CoreOS: unable to transfer zero-length packets using datagram sockets

### ISSUE THREAD

**Issue by dimitryc** [coreos/bugs#1834]
# Issue Report #

### Container Linux Version ###

$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.12.0
VERSION_ID=1235.12.0
BUILD_ID=2017-02-23-0222
PRETTY_NAME="Container Linux by CoreOS 1235.12.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

### Environment ###

Amazon, HVM, m3.large instance

### Expected Behavior ###

It should be possible to transfer zero-length packets using datagram sockets.

### Actual Behavior ###

It’s impossible to transfer zero-length packets using datagram sockets.

### Reproduction Steps ###

See the test case in attachments. To reproduce it:

1) start server with the following command (where 9999 is the port and 10 sec is timeout for socket server)

udpserver 9999 10000

2) start client with the following command (where 9999 is the port and 0 is packet length)
Note that after entering this command, it will ask for a message to transfer, just press enter as it’s a test for zero-length packet.

udpclient localhost 9999 0

3) If server doesn’t receive the packet (nothing printed to console), then the problem is reproducible.

### Other Information ###

The scenario works on other Linux distributions.

[test.zip](https://github.com/coreos/bugs/files/804255/test.zip)

**Comment by crawford** [comment]
I'm not able to reproduce this on 1325.0.0.

```
$ ./udpserver 9999 10000
server enables timeout
server received datagram from localhost (127.0.0.1)
server received 0/0 bytes: 
ERROR: received timeout
: Success
```

Can you try on the latest Stable (uses the 4.9.9 kernel instead of 4.7.3)?

**Comment by dimitryc** [comment]
Tested it on latest Stable (4.9.9 kernel) and it works to me as well now. Thanks.
