### ISSUE TITLE
Unable to mount nfs with option context=<SELinux context> 

### ISSUE THREAD

**Issue by pizzarabe** [coreos/bugs#1840]
## Bug ##

I am unable to mount my nfs-share with context=<selinux context> option to lable the nfs share to sth. like svirt_sandbox_file_t.

> The  context=  option is useful when mounting filesystems that do not support extended attributes
http://man7.org/linux/man-pages/man8/mount.8.html

With the help from #atomic I am now pretty sure it is the mount binary

CoreOS:

> mount from util-linux 2.27.1 (libmount 2.27.0: assert, debug)

Fedora 25 Atomic (with working -o context=...): 

> mount from util-linux 2.28.2 (libmount 2.28.2: **selinux**, btrfs, force-mountinfo, assert, debug

I guess we have to recompile(?) that binary with selinux support.

### Container Linux Version ###
Container Linux by CoreOS 1325.1.0 (Ladybug)
and 
Container Linux by CoreOS 1235.12.0 (Ladybug)

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
