### ISSUE TITLE
Upgrade from 1325.1.0 to Alpha 1339.0.0 non-responsive on reboot under xenserver7

### ISSUE THREAD

**Issue by timechanter** [coreos/bugs#1849]
# Issue Report #

### Container Linux Version ###
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1325.1.0
VERSION_ID=1325.1.0
BUILD_ID=2017-02-23-0035
PRETTY_NAME="Container Linux by CoreOS 1325.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Xenserver7 Alpha Guest originally deployed via Baremetal. Fault occurring on 6 (all) nodes.

### Expected Behavior ###
The 1339.0.0 version updates, the node reboots, and you can interact with the console or via network.

### Actual Behavior ###
Upgrade occurs and node restarts and console never shows and network is no responsive. Console output always stops at the below lines.

![coreos-upgrade-1325 1 0-to-1339 0 0-hang](https://cloud.githubusercontent.com/assets/1670817/23635787/d619f338-0325-11e7-8bb2-bf236f60b12d.png)

### Reproduction Steps ###

  1. Start with a 1325.1.0 Baremetal server
  2. Force update (or just wait)
  3. Node hangs on restart

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

**Comment by crawford** [comment]
The screenshot you attached is from the virtual console (VGA). Do you have the raw console logs (serial)?

**Comment by timechanter** [comment]
Good question. I've never tried to get a console log from a guest. I'll try in the morning my time.

**Comment by timechanter** [comment]
I'm having difficulty in getting debug kernel messages out. And the serial connection to the Guest fails to connect to 1339. I can get what I want from 1325.1  , but thats not much help. 

The weird thing is, if I manually start CoreOS and switch to "B" from grub menu (which I suspect is the installed and waiting 1339), then it hangs bringing the second CPU online in SMP. The only difference in 1325.1 and 1339 at this stage of the boot is 1325.1 will have two messages about NMI watchdog , and 1339 doesn't.

```
1325.1.0
---------
[    0.102008] installing Xen timer for CPU 0^M
[    0.104045] smpboot: CPU0: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (family: 0
x6, model: 0x5e, stepping: 0x3)^M
[    0.107020] cpu 0 spinlock event irq 53^M
[    0.108003] Performance Events: unsupported p6 CPU model 94 no PMU driver, so
ftware events only.^M
[    0.110325] NMI watchdog: disabled (cpu0): hardware events not enabled^M
[    0.111003] NMI watchdog: Shutting down hard lockup detector on all cpus^M
[    0.112050] installing Xen timer for CPU 1^M
[    0.113031] x86: Booting SMP configuration:^
```

```
1339.0.0
---------
[    0.106000] installing Xen timer for CPU 0^M
[    0.108000] smpboot: CPU0: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (family: 0
x6, model: 0x5e, stepping: 0x3)^M
[    0.108000] cpu 0 spinlock event irq 53^M
[    0.108000] Performance Events: unsupported p6 CPU model 94 no PMU driver, so
ftware events only.^M
[    0.108000] smp: Bringing up secondary CPUs ...^M
[    0.108000] installing Xen timer for CPU 1^M
[    0.108000] x86: Booting SMP configuration:^M
```

Any suggestions on how to get more information?

**Comment by timechanter** [comment]
So I reduced the CPU count to 1 and 1339 boots and hangs exactly like it does on a update reboot, so I'll ignore the prior error for now. The kernel on 1325.1 after the common line 
```
[    1.633261]  xvda: xvda1 xvda2 xvda3 xvda4 xvda6 xvda7 xvda9^M
```

is starting up the other storage devices and goes onto (1325.1.0 does this, 1339.0 never progresses past the prior line) say
```
    1.688523] ata2.01: ATAPI: QEMU DVD-ROM, 0.10.2, max UDMA/100^M
[    1.691809] ata2.01: configured for MWDMA2^M
[    1.694902] scsi 1:0:1:0: CD-ROMQEMU     QEMU DVD-ROM     0.10 PQ
: 0 ANSI: 5^M
[    1.715132] sr 1:0:1:0: [sr0] scsi3-mmc drive: 4x/4x xa/form2 tray^M
[    1.718442] cdrom: Uniform CD-ROM driver Revision: 3.20^M
[    1.823032] tsc: Refined TSC clocksource calibration: 3408.000 MHz^M
```

**Comment by crawford** [comment]
Ah, this is helpful. What kind of hardware is this? And what is the output of `lspci -nnk` on the working version.

**Comment by timechanter** [comment]
It is a HVM guest running under XenServer 7.0 (all patches). Host is ASRock with an Intel 6700 chip, Storage is iSCSI from a FreeNAS9 machine.

First couple of entries from Host:
```
00:00.0 Host bridge [0600]: Intel Corporation Skylake Host Bridge/DRAM Registers [8086:191f] (rev 07)
Subsystem: ASRock Incorporation Device [1849:191f]
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 530 [8086:1912] (rev 06)
````

The Guest lspci -nnk is

```
00:00.0 Host bridge [0600]: Intel Corporation 440FX - 82441FX PMC [Natoma] [8086:1237] (rev 02)
	Subsystem: Red Hat, Inc Qemu virtual machine [1af4:1100]
00:01.0 ISA bridge [0601]: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II] [8086:7000]
	Subsystem: Red Hat, Inc Qemu virtual machine [1af4:1100]
00:01.1 IDE interface [0101]: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II] [8086:7010]
	Subsystem: XenSource, Inc. 82371SB PIIX3 IDE [Natoma/Triton II] [5853:0001]
	Kernel driver in use: ata_piix
	Kernel modules: ata_piix
00:01.2 USB controller [0c03]: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] [8086:7020] (rev 01)
	Subsystem: XenSource, Inc. 82371SB PIIX3 USB [Natoma/Triton II] [5853:0001]
	Kernel driver in use: uhci_hcd
	Kernel modules: uhci_hcd
00:01.3 Bridge [0680]: Intel Corporation 82371AB/EB/MB PIIX4 ACPI [8086:7113] (rev 01)
	Subsystem: Red Hat, Inc Qemu virtual machine [1af4:1100]
	Kernel modules: i2c_piix4
00:02.0 VGA compatible controller [0300]: Cirrus Logic GD 5446 [1013:00b8]
	Subsystem: XenSource, Inc. GD 5446 [5853:0001]
00:03.0 SCSI storage controller [0100]: XenSource, Inc. Xen Platform Device [5853:0001] (rev 01)
	Subsystem: XenSource, Inc. Xen Platform Device [5853:0001]
	Kernel driver in use: xen-platform-pci
```

**Comment by timechanter** [comment]
We have two different Host configurations (different ChipSets/CPUs) and the issue occurs for all, so I don't think its Host specific at this stage.

**Comment by timechanter** [comment]
I have "removed" the DVD Rom and USB controllers for the Guests via Xen's command line. Hasn't altered the "hang". I'm still unsure if it actually hung, or its just the console/network are not responding. Not that it really matters.

**Comment by timechanter** [comment]
Since I don't have a gentoo build environment, I have updated one of my Ubuntu servers to kernel 4.10.1  . Which behaves exactly the same as latest alpha. So pretty sure this is unrelated to CoreOS overlays. I'll move over to the kernel folks and see if I can get some joy (beyond them suggesting I bi-sect the patches).

**Comment by lucab** [comment]
@timechanter thanks for trying and tracking this down to vanilla upstream. The only important regression I've seen so far in 4.10 is https://bugzilla.kernel.org/show_bug.cgi?id=194723, but it seems completely unrelated to your case. Please link back here the upstream thread after your report.

**Comment by timechanter** [comment]
Just as a heads up, I'm currently bisecting 4.9 -> 4.10 to find the issue. I'm 3 bisects into approx 13.

**Comment by timechanter** [comment]
I narrowed the SMP hang down to 
# first bad commit: [3be134e5152f08e8bd3c2afdaac723f64d93c2bb] Merge tag 'libnvdimm-for-4.10' of git://git.kernel.org/pub/scm/linux/kernel/git/nvdimm/nvdimm

I've reported it to Xenserver. I am still bisecting the subsequent hang which will take me 3 days to narrow it down (life is busy).

**Comment by timechanter** [comment]
SMP fault is logged as https://bugs.xenserver.org/browse/XSO-701  .
Still bisecting the final hang.

**Comment by timechanter** [comment]
Xenserver team have suggested it as a fault that was patched upstream in Xen 4.6.5 (4.7.2) release on the 10th March (Friday). I don't see the same boot messages on hang, so I'm still bisecting. Unsure how to patch Xen in the host at this stage to verify that fix.

**Comment by timechanter** [comment]
Since upstream Xenserver have accepted this as a fault for 7.0 and 7.1 Dom0 (host), closing this out for CoreOS since there is nothing the guest can do.

**Comment by crawford** [comment]
Ah, bummer. Thank you for digging into this.
