### ISSUE TITLE
Docker daemon not starting when using -g flag

### ISSUE THREAD

**Issue by sepiroth887** [coreos/bugs#1852]
# Issue Report #

## Bug ##
Docker daemon not starting with error: 
Error starting daemon: error initializing graphdriver: invalid argument

We are using the -g option with a drop in to force docker to use /mnt/resource/docker 
This is an ext4 formatted drive (/dev/sdb1) in Azure using the VM exposed SSDs. 
Until docker 1.12 this worked fine (ish) and now leads to the above error. 

When using -g /mnt/resource the daemon will start fine. Same when using any other folder name not containing docker.

### Container Linux Version ###

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.5.0
VERSION_ID=1298.5.0
BUILD_ID=2017-02-28-0013
PRETTY_NAME="Container Linux by CoreOS 1298.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

### Environment ###

Azure

### Reproduction Steps ###

  1. run /usr/lib/coreos/dockerd -g /mnt/resource/docker

### Other Information ###

systemctl status docker seems to show different binary in use sometimes /usr/bin/dockerd and sometimes /usr/lib/coreos/dockerd

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
Azure CoreOS official image

**Comment by crawford** [comment]
On Container Linux, we use [a script](https://github.com/coreos/coreos-overlay/blob/master/app-emulation/docker/files/dockerd) to detect which graph driver should be used (for a long time, docker couldn't figure this out on its own). `docker.service` calls to this script instead of docker directly. Can you share the result of `systemctl cat docker`?

**Comment by sepiroth887** [comment]
```
# /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=containerd.service docker.socket network.target
Requires=containerd.service docker.socket

[Service]
Type=notify
EnvironmentFile=-/run/flannel/flannel_docker_opts.env

# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/lib/coreos/dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock $DOCKER_OPTS $DOCKER_CGROUPS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/docker.service.d/10-storage.conf
[Unit]
After=dev-sdb.device
[Service]
Environment="DOCKER_OPTS=-g /mnt/resource/docker-storage --default-ulimit nofile=1048576:1048576 --log-opt max-size=15m --log-opt max-file=1"
```

**Comment by crawford** [comment]
Hrmm, that looks fine. We'll have to dig into what is failing. Do you happen to have an ARM template for this deployment or reproduction steps?

**Comment by sepiroth887** [comment]
Hmm let me check, I need to do some mods on the template in order to safely post it here.... 

I have yet to try installing this cleanly from a deployment (this was updated from an older version via the update-engine) 

Funny thing is it started fine and only happened after a reboot. 

There is one more thing that's a bit custom: 

In order to allow us to update the cloud-config on Azure we have a basic cloud-config that pulls another one and that actually removes docker data on every reboot (thanks to it's awesome stability -.-) 

I wonder if this has race condition somewhere where docker starts very shortly, stops, gets wiped, then starts somewhat broken again.

**Comment by sepiroth887** [comment]
Ugh. sorry I think I found the root cause. 

We were trying to run systemctl stop docker; rm -rf /mnt/resource/docker in our base cloud-init followed by /usr/bin/coreos-cloudinit --from-file=/var/lib/cloud-init/CUSTOM.yml 

the CUSTOM.yml cloud-init has the docker drop-in unit which set the -g option to /mnt/resource/docker but I assume that we were racing against /mnt/resource being not yet mounted. 

I just modified our CUSTOM.yml to format /dev/sdb1 (/mnt/resource/docker) before the drop-in and ensure it's dependent on mnt-resource.mount before it starts and that seems to work :) 

I think this is a bit too exotic a config to ask you to support xD 

So feel free to close.

**Comment by crawford** [comment]
That is a gnarly setup! I would recommend you use Ignition for the first stage of that. Ignition can partition and format the resource volume before first boot so you can always assume it is there. Then you can just add a dependency between this second-stage and the mount unit that mounts the resource volume.

I'm going to go ahead and close this, but feel free to bug me with any questions you have.
