### ISSUE TITLE
Increase container start timeout

### ISSUE THREAD

**Issue by rojer** [coreos/bugs#1854]
# Issue Report #

### Container Linux Version ###

```
# cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.5.0
VERSION_ID=1298.5.0
BUILD_ID=2017-02-28-0013
PRETTY_NAME="Container Linux by CoreOS 1298.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Amazon EC2

### Expected Behavior ###

Containers start every time

### Actual Behavior ###

Sometimes containers fail to start with the following error:

```
docker: Error response from daemon: containerd: container did not start before the specified timeout.
```

### Reproduction Steps ###

Intermittent, no good repro. I suspect this happens when a lot of containers are started at once, with increased load on the system.

### Other Information ###

The timeout in question is controlled by the `--start-timeout` flag to `containerd`. Default for this flag is 30 seconds, and it was raised to 2 minutes several months ago (in [this commit](https://github.com/docker/docker/commit/64a91ee74e73c956e92801447ae73ba82d168ed5)).
However, since CoreOS uses its own service to launch `containerd`, this was not picked up.
`--start-timeout=2m` should be added to `containerd.service`.

**Comment by dm0-** [comment]
This will be in Thusday's alpha.

**Comment by rojer** [comment]
thank you!
