### ISSUE TITLE
Enable sssd_sudo support

### ISSUE THREAD

**Issue by guilhem** [coreos/bugs#1856]
# Issue Report #

Today it's not possible to add `sudo` rights based on ldap with `sssd`

```
(Wed Mar  8 15:06:56 2017) [sssd] [service_startup_handler] (0x0010): Could not exec /usr/libexec/sssd/sssd_sudo --uid 0 --gid 0 -d 0xf7f0 --debug-to-stderr, reason: No such file or directory
```

### Environment ###

Container Linux run on baremetal

### Desired Feature ###

Install `sssd_sudo` component.

**Comment by dm0-** [comment]
Merged, thanks.

**Comment by glevand** [comment]
@dm0- It seems we still don't have all the pieces for this to work.  See: https://groups.google.com/forum/#!topic/coreos-user/YAtP4z7Eo6g

> Can you add "--with-sssd" flag to build sudo in new versions?

I did a test build of sudo with '--with-sssd', and it built OK.  I guess we would need to move `app-admin/sudo` to coreos-overlay and add our own `with-sssd` use flag.

**Comment by dm0-** [comment]
This is something that makes sense to send to Gentoo.  I'll send a PR and see what they say, but yes, we can add it in the overlay to get it in the next release.

**Comment by dm0-** [comment]
I've opened gentoo/gentoo#8230.  If that is merged this week, we can just sync portage-stable instead of moving to the overlay.
