### ISSUE TITLE
ignition: load config by tftp

### ISSUE THREAD

**Issue by glevand** [coreos/bugs#1857]
## Feature Request ##

It would be nice if ignition could load config files via tftp.  PXE boot uses tftp, and if ignition could load with tftp a separate http server would not be needed.  So something like:

`coreos.config.url=tftp://example.com/ignition.cfg`

**Comment by racurrie** [comment]
+1

**Comment by bgilbert** [comment]
Workaround for PXE-booted systems: [put the Ignition config into a custom OEM](https://coreos.com/os/docs/latest/booting-with-pxe.html#adding-a-custom-oem). The resulting cpio archive will be retrieved over TFTP.
