### ISSUE TITLE
Failed setting 'core' user's password: exit status 1

### ISSUE THREAD

**Issue by urzds** [coreos/bugs#1860]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1339.0.0+2017-03-10-2016
VERSION_ID=1339.0.0
BUILD_ID=2017-03-10-2016
PRETTY_NAME="Container Linux by CoreOS 1339.0.0+2017-03-10-2016 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

* Supermicro X8DTT via PXE
* QEMU
* CoreOS CL images for QEMU and PXE both generated from the same `developer-1339.0.0+2017-03-10-2015-a1` raw image
* The same `ignition.json` was used for both QEMU and PXE boot

### Expected Behavior ###

CoreOS CL should boot via PXE, just as it boots in QEMU
### Actual Behavior ###

The machine booting via PXE has this in the logs:
```
coreos-cloudinit[942]: 2017/03/10 20:10:55 Checking availability of "local-file"
coreos-cloudinit[942]: 2017/03/10 20:10:55 Fetching user-data from datasource of type "local-file"
coreos-cloudinit[942]: 2017/03/10 20:10:55 Fetching meta-data from datasource of type "local-file"
coreos-cloudinit[942]: 2017/03/10 20:10:55 Parsing user-data as cloud-config
coreos-cloudinit[942]: 2017/03/10 20:10:55 Merging cloud-config from meta-data and user-data
coreos-cloudinit[942]: 2017/03/10 20:10:55 User 'core' exists, ignoring creation-time fields
coreos-cloudinit[942]: 2017/03/10 20:10:55 Setting 'core' user's password
chpasswd[1002]: Authentication failure
coreos-cloudinit[942]: 2017/03/10 20:10:55 Failed setting 'core' user's password: exit status 1
coreos-cloudinit[942]: 2017/03/10 20:10:55 Failed to apply cloud-config: exit status 1
systemd[1]: system-cloudinit@usr-share-coreos-developer_data.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: Failed to start Load cloud-config from /usr/share/coreos/developer_data.
systemd[1]: system-cloudinit@usr-share-coreos-developer_data.service: Unit entered failed state.
systemd[1]: system-cloudinit@usr-share-coreos-developer_data.service: Failed with result 'exit-code'.
systemd[1]: Reached target Load system-provided cloud configs.
systemd[1]: Reached target Load user-provided cloud configs.
```
The machine does not allow me to login via SSH, but `coreos.autologin` works.

I cannot use `sudo`, either. The message is `sudo: policy plugin failed session initialization`. There is no related message (apart from the `sudo` attempt) in the logs / dmesg.

Both systems, QEMU and PXE, also log this: `kernel: PKCS#7 signature not signed with a trusted key`. Since both are logging it, I assume it is unrelated.

### Reproduction Steps ###

* `./coreos_developer_qemu.sh -i /ignition.json -- -curses` to create the QEMU VM.
* A more complex setup involving matchbox, but using the same `ignition.json`, was used to boot the PXE booting bare-metal machines.
*  `./coreos_developer_pxe.sh` was completely broken and cannot be used to reproduce this. The boot stops with an error when trying to switch root.

### Other Information ###

[log-and-ignition.zip](https://github.com/coreos/bugs/files/835055/log-and-ignition.zip)

**Comment by crawford** [comment]
You are using a developer image, so it's tough to tell what customizations have been made. Are you able to use a production image instead?

**Comment by urzds** [comment]
The only changes are these: urzds/coreos-overlay@2bad2c9587626470d854e3bafa71792ef083fce6

**Comment by crawford** [comment]
```
Failed to start Load cloud-config from /usr/share/coreos/developer_data
```

This is probably due to you running `./set_shared_password` in the SDK. I'm guessing the authentication failure coreos-cloudinit is running into is for the same reason that sudo is failing. When did you clone the SDK and what manifest version are you using? If you haven't already, you'll want to run `repo init --manifest-branch=build-1339 && repo sync --detach` before applying your patches. That'll make sure that you actually only have your changes on top of our branch (if you just ran `repo init`, you'll pick up top-of-tree which might have breaking changes).

**Comment by urzds** [comment]
> This is probably due to you running ./set_shared_password in the SDK. I'm guessing the authentication failure coreos-cloudinit is running into is for the same reason that sudo is failing.

I assumed something of the sort, but I was unable to figure out which mistake I made.

> When did you clone the SDK and what manifest version are you using? If you haven't already, you'll want to run repo init --manifest-branch=build-1339 && repo sync --detach before applying your patches. That'll make sure that you actually only have your changes on top of our branch (if you just ran repo init, you'll pick up top-of-tree which might have breaking changes).

I was using the `cork` variant described here: https://coreos.com/os/docs/latest/sdk-modifying-coreos.html
Followed by `repo branch` described here ("Add new upstream package"): https://coreos.com/os/docs/latest/sdk-tips-and-tricks.html

I cloned it last week, but I don't know how to figure out the manifest version. `repo info` and `repo status` are not really helpful: They just tell me, that I am on the master branch, but not which revision is checked out. `cork` does not seem to provide a command to show the version, either - it can only `update`?

Is `repo init --manifest-branch=...` the recommended way to update / select a release, in case one does not want the bleeding-edge version? I.e. `cork update` was the wrong command? Is all this documented somewhere?

**Comment by urzds** [comment]
The issue also exists with an image built from the `build-1339` branch.

**Comment by urzds** [comment]
I tried an image generated with:
```
./build_image prod
./image_to_vm.sh --from=../build/images/amd64-usr/developer-1353.0.0+... --board=amd64-usr --prod_image --format=pxe
```

This image boots without issues.

**Comment by crawford** [comment]
Okay, is this safe to close out then?

**Comment by urzds** [comment]
I don't think so. The developer image is still broken.

**Comment by crawford** [comment]
Interesting. I'm not sure why the dev and prod images would behave differently in this case. The dev images are a much lower priority for us though. Can I ask why you are using dev instead of prod?

**Comment by urzds** [comment]
Because I am planning to make some additions to Kubernetes and thought the developer image, with debuggers, etc., would be more suitable for this task in the long run.

**Comment by bgilbert** [comment]
There may be multiple problems here, but one of them is that `/usr/lib64/pam.d` in the dev image is missing a bunch of config files that are included in the prod image:

```
chage
chfn
chgpasswd
chpasswd
chsh
groupadd
groupdel
groupmems
groupmod
newrole
newusers
polkit-1
run_init
saslauthd
shadow
sshd
sudo
useradd
userdel
usermod
```

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.

**Comment by jlsalvador** [comment]
@bgilbert and you think that this issue don't deserve a maintenance?
I found one of the problem. CoreOS doesn't removes the locks files generated by shadow-utils. More info here https://github.com/shadow-maint/shadow/issues/111

**Comment by bgilbert** [comment]
@jlsalvador The developer OS image has long been unmaintained and is known to be broken in various ways.  If you're seeing this problem with a production image, please open a new bug.
