### ISSUE TITLE
Core + AWS ECS Docker logdriver

### ISSUE THREAD

**Issue by optimisticanshul** [coreos/bugs#1863]
# Issue Report #

## Bug ##
If i use amazon ami i am able to send logs to cloudwatch group but with coreos latest ami i am unable to send logs.
### Container Linux Version ###
lastest stable

**Comment by euank** [comment]
Please provide more information about what you've done to configure the logdriver and what errors you're seeing (e.g. in the docker daemon's logs).

**Comment by euank** [comment]
Reopen if you're able to provide more information about what steps you're using, how you're configuring the logdriver, etc.
