### ISSUE TITLE
Cloud-init variables are not processed correctly when launching coreos-cloudinit from a script in user-data in AWS

### ISSUE THREAD

**Issue by Sodki** [coreos/bugs#1865]
# Issue Report #

Bug

## Bug ##

In order to bypass the 16 KB limit of AWS' user data, we've created a small wrapper script that is used as a wrapper:

```
#!/bin/bash

toolbox dnf install -y awscli
toolbox aws s3 cp "s3://<bucket>/<path>" /media/root/tmp/user-data
coreos-cloudinit -from-file /tmp/user-data
```

This way we can have a user data that is as big as we want, while still having all the benefits of using CoreOS. Unfortunately, this doesn't work quite as expected because cloud-init variables such as `$private_ipv4` turn out blank, empty strings, which breaks our workflow. Running the command manually works as expected. I've also tried duplicating the last line, so that cloud-init runs twice, but it has the same effect - empty variables.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.5.0
VERSION_ID=1298.5.0
BUILD_ID=2017-02-28-0013
PRETTY_NAME="Container Linux by CoreOS 1298.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

AWS

### Expected Behavior ###

Variables such as `$private_ipv4` should be rendered correctly when launching coreos-cloudinit from a user-data shell script.

### Actual Behavior ###

Variables such as `$private_ipv4` are rendered as empty strings.

### Reproduction Steps ###

  1. Launch an AWS instance with the following user data:

```
#!/bin/bash

echo "#cloud-config

write_files:
  - path: /tmp/ip
    content: \\$private_ipv4" > /tmp/data

coreos-cloudinit -from-file /tmp/data
```

  2. `/tmp/ip` is an empty file, and it shouldn't be
  3. Running `coreos-cloudinit -from-file /tmp/data` works as expected, the file `/tmp/ip` becomes non empty
  4. If you create a new AWS instance with the content of `/tmp/data`, it works as expected

**Comment by crawford** [comment]
You need to tell coreos-cloudinit which provider it should use to fetch the metadata. Without this, the variable expansion won't work. It works when you manually run it because the first invocation of coreos-cloudinit populates `/etc/environment`, which is then implicitly used by later invocations. You could also source `/etc/environment` before running coreos-cloudinit in your script.

I should also let you know that coreos-cloudinit has been deprecated in favor of Ignition. Ignition has the ability to chain configs together, allowing you to bypass the size restrictions imposed by AWS.

**Comment by Sodki** [comment]
I get it now. And because it's a regular file it will not use the regular metadata provider. To bypass this I did exactly what you mentioned, sourcing `/etc/environment`, it's a simple approach.

I now about coreos-cloudinit deprecation, but we can't realistically fully move to Ignition until it supports fetching from S3 using EC2 IAM roles (#1631).

I'm closing this ticket.
