### ISSUE TITLE
arm64 (ARMv8) stable version release schedule

### ISSUE THREAD

**Issue by vielmetti** [coreos/bugs#1867]
## Bug ##

The arm64 stable version is not on a formal release schedule, resulting in known issues that are fixed in other stable versions. 

Copying in the relevant bits from #1763 ; this is not about bug fixing in the code (that's OK), just getting in sync with releases and identifying any blocking issues that would prevent stable support.

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.9.0
VERSION_ID=1235.9.0
BUILD_ID=2017-02-02-0337
PRETTY_NAME="Container Linux by CoreOS 1235.9.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Packet ARMv8 "2A" Cavium 96-core server

### Expected Behavior ###

Stable release on ARMv8 platform is in sync with stable release on other platforms, and is stable, and "officially exists".

### Actual Behavior ###

Reference #1763 - from @dm0- 

"Oh, I don't think the arm64 stable channel is supported or officially exists (i.e. there is no auto-update group for it), but some releases accidentally got published for it there."

A version which addresses the bug in #1763 arrived at 1298.1.0, and is available in the beta channel for ARMv8 and the stable channel for other platforms, but the stable version for ARMv8 is 1235.9.0 which is behind the stable channel for amd64 at 1298.5.0.

### Reproduction Steps ###

  1. Launch "stable" CoreOS at Packet, provision for 2A server.
  2. System boots with 1235.9.0 (instead of 1298.5.0 or something similar).

### Other Information ###

We are directing people to the beta channel for now, but would prefer of course to have the stable channel available. Happy to help provide resources to make this happen on ARMv8.

**Comment by Knight1** [comment]
I don't know if this is related to this specifig bug but if I try to run docker run the system crashes with the following message.

```localhost login: core (automatic login)

[   31.513628] audit: type=1006 audit(1489441081.190:4): pid=2032 uid=0 subj=kernel old-auid=4294967295 auid=500 tty=ttyAMA0 old-ses=4294967295 ses=2 res=1
Last login: Mon Mar 13 21:38:01 UTC 2017 on tty1
[   31.535718] audit: type=1006 audit(1489441081.212:5): pid=2061 uid=0 subj=kernel old-auid=4294967295 auid=500 tty=(none) old-ses=4294967295 ses=3 res=1
CoreOS stable (1185.5.0)
core@localhost ~ $ docker run -it --rm aarch64/hello-world
[ 1127.149775] containerd[2250]: syscall 1069
[ 1127.153923] Code: f94023e4 f94027e5 f9400fe8 d4000001 (b13ffc1f)
[ 1127.160032] CPU: 95 PID: 2250 Comm: containerd Not tainted 4.7.3-coreos-r3 #1
[ 1127.167207] Hardware name: FOXCONN R2-1221R-A4/C2U4N_MB, BIOS G31FB12A 10/26/2016
[ 1127.174702] task: ffff800fda880000 ti: ffff800fda900000 task.ti: ffff800fda900000
[ 1127.182213] PC is at 0x4ed350
[ 1127.185189] LR is at 0x4ed330
[ 1127.188197] pc : [<00000000004ed350>] lr : [<00000000004ed330>] pstate: 60000000
[ 1127.195602] sp : 00000048200af7c0
[ 1127.198942] x29: 0000ffff877fe940 x28: 00000048200ce480
[ 1127.204276] x27: 0000000000df0eb8 x26: 0000000000000000
[ 1127.209628] x25: 0000000000800000 x24: 0000000000000000
[ 1127.214996] x23: 0000ffff8e0c5000 x22: 0000ffff87ffe60f
[ 1127.220355] x21: 0000000000000000 x20: 000000000046d998
[ 1127.225707] x19: 000000000043bf28 x18: 0000000000000000
[ 1127.231061] x17: 0000ffff8dfa4a44 x16: 00000048200afeb0
[ 1127.236421] x15: 0000000000000040 x14: 0000000000000000
[ 1127.241775] x13: 0000000000000000 x12: 0000000000000008
[ 1127.247128] x11: 0000000000000000 x10: 0000000000000001
[ 1127.252511] x9 : 00000048200affd0 x8 : 000000000000042d
[ 1127.257869] x7 : 00000000004ed330 x6 : 00000048200af7c0
[ 1127.263222] x5 : 0000000000000000 x4 : 0000000000000000
[ 1127.268577] x3 : ffffffffffffffff x2 : 0000000000000080
[ 1127.273930] x1 : 00000048200af8b8 x0 : 0000000000000003
[ 1127.279297]
[ 1133.115683] containerd[2258]: syscall 1069
[ 1133.119785] Code: f94023e4 f94027e5 f9400fe8 d4000001 (b13ffc1f)
[ 1133.125899] CPU: 59 PID: 2258 Comm: containerd Not tainted 4.7.3-coreos-r3 #1
[ 1133.133039] Hardware name: FOXCONN R2-1221R-A4/C2U4N_MB, BIOS G31FB12A 10/26/2016
[ 1133.140539] task: ffff800fdab01d00 ti: ffff800fdab84000 task.ti: ffff800fdab84000
[ 1133.148039] PC is at 0x4ed350
[ 1133.151011] LR is at 0x4ed330
[ 1133.153979] pc : [<00000000004ed350>] lr : [<00000000004ed330>] pstate: 60000000
[ 1133.161373] sp : 00000048203207c0
[ 1133.164687] x29: 0000ffffb593e940 x28: 00000048200d4780
[ 1133.170016] x27: 0000000000df0eb8 x26: 0000000000000000
[ 1133.175346] x25: 0000000000800000 x24: 0000000000000000
[ 1133.180670] x23: 0000ffffb6365000 x22: 0000ffffc1aef60f
[ 1133.185994] x21: 0000000000000000 x20: 000000000046d998
[ 1133.191325] x19: 000000000043bf28 x18: 0000000000000000
[ 1133.196648] x17: 0000ffffb634de24 x16: 0000004820320eb0
[ 1133.201973] x15: 0000000000000180 x14: 0000000000000000
[ 1133.207297] x13: 0000ffffb593e790 x12: 0000ffffaee9f1e0
[ 1133.212622] x11: 00000000003d0f00 x10: 0000ffffb634710c
[ 1133.217946] x9 : 0000004820320fa0 x8 : 000000000000042d
[ 1133.223270] x7 : 00000000004ed330 x6 : 00000048203207c0
[ 1133.228594] x5 : 0000000000000000 x4 : 0000000000000000
[ 1133.233918] x3 : ffffffffffffffff x2 : 0000000000000080
[ 1133.239242] x1 : 00000048203208b8 x0 : 0000000000000003
[ 1133.244566]
```

Hope that helps you

**Comment by crawford** [comment]
There is no plan right now for a Stable ARM64 channel. Reason being, we aren't fully testing that architecture and are not investing enough effort in it for me to feel comfortable calling it stable. We will continue publishing images and providing a Beta and Alpha channel. Once the day comes that we can support ARM64, we will create the Stable channel. Until then, it feels disingenuous.

In the meantime, I'll ask Packet to remove the Stable option for ARM64 and we'll clean up the stable bucket.

**Comment by vielmetti** [comment]
Thanks @crawford this is an accurate assessment of the current situation, good call.

Do you have a CI test infrastructure that you use for the rest of the architectures you build for? If so, adapting that for ARM64 would be something I'd be interested in collaborating with you on at Packet. That in the interest of getting the beta release as solid as possible, and of shaking out alpha release issues and bugs and regressions as they happen.

**Comment by crawford** [comment]
@vielmetti We have some basic tests in place. They run on emulated hardware but we have plans to put some mustang and thunderx boards to work. All of the jobs can be found in https://github.com/coreos/jenkins-os/, specifically https://github.com/coreos/jenkins-os/blob/master/os/kola/qemu.groovy.

**Comment by glevand** [comment]
Right now only a few of the kola tests complete successfully on arm64.  More work is needed for arm64.
