### ISSUE TITLE
[ignition] Being able to copy file

### ISSUE THREAD

**Issue by guilhem** [coreos/bugs#1873]
# Issue Report #

### Environment ###

On baremetal

### Desired Feature ###

We would like to set file content from local file.

### Other Information ###

This is useful to set hostname from machine serial

**Comment by dgonyeo** [comment]
Support for creating both hard and symbolic links was just merged into ignition: https://github.com/coreos/ignition/pull/352

Would you still like to see this feature, or can I close this issue?

**Comment by ajeddeloh** [comment]
Closing this since it looks like links should be able to handle this. Please reopen if this is still an issue.
