### ISSUE TITLE
container-linux-config-transpiler doesn't work when compiled for windows

### ISSUE THREAD

**Issue by ericchiang** [coreos/bugs#1876]
# Issue Report #

### Container Linux Version ###

NA

### Environment ###

NA

### Expected Behavior ###

Since container-linux-config-transpiler is only parsing and converting configs, I wouldn't expect that it would be dependent on the platform it was compiled for. 

### Actual Behavior ###

Running a program such as the following:

```go
// convertToIgnition parses a container linux config and converts it into
// a machine readable Ignition config JSON bytes.
func convertToIgnition(config []byte) ([]byte, error) {
	// parse bytes into a fuze / config-transpiler Config
	tc, report := fuze.Parse(config)
	if report.IsFatal() {
		return nil, fmt.Errorf("error parsing config: %s", report.String())
	}
	// convert into an Ignition config
	ign, report := fuze.ConvertAs2_0_0(tc)
	if report.IsFatal() {
		return nil, fmt.Errorf("error converting into Ignition: %s", report.String())
	}
	return json.Marshal(ign)
}
```

Produces the following error:

```
error converting into Ignition: error: path not absolute error: path not absolute error: path not absolute error: path not absolute error: path not absolute error: path not absolute error: path not absolute error: path not absolute error: path not absolute
```

These are originating from the following ignition methods: https://github.com/coreos/ignition/blob/v0.14.0/config/v2_0/types/path.go

### Reproduction Steps ###

Compiling and running the following program on windows fails:

```go
package main

import (
	"fmt"
	"os"

	"github.com/coreos/ignition/config/types"
)

func main() {
	report := types.Path("/hello/world").Validate()

	if report.IsFatal() {
		fmt.Fprintf(os.Stderr, "%s\n", report.String())
		os.Exit(2)
	}
}
```

output:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\angry>cd Downloads

C:\Users\angry\Downloads>blah.exe
error: path not absolute

C:\Users\angry\Downloads>
```

### Other Information ###

This is an issue because ignition uses the `path/filepath` package (machine dependent) instead of `path` (machine independent).

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/ignition/pull/348.
