### ISSUE TITLE
Ability to select encrypted EBS volume as storage type when defining nodes

### ISSUE THREAD

**Issue by cricci82** [coreos/bugs#1879]
## Feature Request ##
Ability to store their Docker logs on workers in an encrypted EBS volume as they may contain PII data.  

### Environment ###
AWS

### Desired Feature ###
During installation have the option to select an encrypted EBS volume when defining nodes

### Other Information ###

**Comment by euank** [comment]
Same answer as #1878, please reopen if there's more information which #1878 doesn't cover.
