### ISSUE TITLE
etcd version shouldn't be required

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1894]
# Issue Report #

## Bug ##

`ct` requires that etcd version be specified. Since this information isn't required (and hardcoding a version number is discouraged), the CLC shouldn't require it either.

**Comment by dgonyeo** [comment]
`ct` needs to know what version of etcd is being used so that it can correctly validate the options passed to it. 

It looks like the OS currently defaults to `v3.0.10`, so I'll have ct assume it's using etcd 3.0 when the version is unspecified.
