### ISSUE TITLE
systemd-journald

### ISSUE THREAD

**Issue by guru2018** [coreos/bugs#1896]
Using syslog API i am logging around 1500 log messages per second, and once a while(once in 200 times) the call takes more time around 0.1 sec, in normal case it takes around 50 to 100 micro second. During this time (0.1 second) my application will be blocked. 

After further analysis I found the issue is because the sendto call done by the syslog is taking more time, which in turn due to buffer is full and the its waiting for buffer to get free.  
The buffer is getting full because the systemd-jorunald is not reading the messages fast enough from the remote end unix domain socket. 

I tried modifying below values from journald.conf, its not of much help. 
RateLimitIntervalSec=1s
RateLimitBurst=2000

Could you please suggest how can I make systemd-journald read the remote socket fast enough that the buffer will not get full. 
syslog socket type: unix domain socket. DGRAM. 
systemd version: 232
kernel version: 4.4.36

**Comment by euank** [comment]
We've never shipped systemd v232; this is not a CoreOS nor Container Linux bug.

Depending on your distro, their upstream bugtracker or support might be a better bet.
