### ISSUE TITLE
CoreOS Boot / Network Issues on OpenStack

### ISSUE THREAD

**Issue by magreiner** [coreos/bugs#1897]
Hey there,

I'd like to run CoreOS on OpenStack, but after starting the CoreOS Container Linux instance, I'm not able to login.
To deploy it, I closely followed the documentation at: https://coreos.com/os/docs/latest/booting-on-openstack.html)

I tried the following steps to solve the issue:
 1. If the (OpenStack) config-drive is attached to the instance on boot:
     -> The Hostname is set correctly, but the machine not accessible via SSH
 2. If the (OpenStack) config-drive is not attached to the instance on boot:
     -> The Hostname is set to localhost, and the machine is not accessible via SSH
 3. I tried multiple versions of CoreOS Container Linux (Stable 1010.5.0, Stable 1122.1.0, Stable 1298.6.0, Alpha 1353.1.0)
     -> but with none of them login via SSH is possible.
 4. Adding the default cloud-config from the documentation mentioned above did not help.
 5. Booting the instance without adding a cloud-config did also not help.
 6. Starting an Ubuntu 16.04 image with the same parameters works perfectly.

However after restarting the instances from the OpenStack Dashboard they all become accessible:
The (basic) network functionality is available ('ping www.google.de' succeeds, docker can download images), but
docker containers have only limited internet access ('ping www.google.de' succeeds but apt-get update fails with network-timeout).

I've attached the boot log of the first boot (network doesn't seem to work), and the boot-log of the instance after the first reboot (instance accessible).

Do you have tips how to solve these issues or might this be a bug in some component of CoreOS CL?

Do you have any suggestions how to further debug the issue?

Thank you very much in advance.

### Container Linux Version ###
```
Stable 1010.5.0, Stable 1122.1.0, Stable 1298.6.0, Alpha 1353.1.0
```

# Boot-log of first boot #
**(instance is not accessible via ssh)**

[CoreOS-FirstBoot-NoNetwork.txt](https://github.com/coreos/bugs/files/885583/CoreOS-FirstBoot-NoNetwork.txt)

# Boot-log after rebooting the instance #
**(instance is accessible via ssh but containers have only limited internet access).**

[CoreOS-Restarted-NetworkLimited.txt](https://github.com/coreos/bugs/files/885595/CoreOS-Restarted-NetworkLimited.txt)

**Comment by euank** [comment]
One thing that might help is using ignition rather than cloud-config. Networking is one of the things harder to get right with cloud-config.

The documentation you reference above has been updated to reference ignition already.

Also, cc @dgonyeo, the docs example there mentions in text the need for an ssh key, but doesn't include one in the example.

If, after using ignition, the machine still doesn't accept ssh connections, I'd try to login to the console of the machine and check the network configuration from that (assuming it's possible to do so easily with your openstack configuration/provider).

**Comment by dgonyeo** [comment]
made a PR to include setting an ssh key in the example: https://github.com/coreos/docs/pull/1071

A better solution is to finish the config-drive support in coreos-metadata so users don't need to explicitly add these. I'll make sure to get to that after my current stuff is done.

**Comment by magreiner** [comment]
Due to an error with our network infrastructure the MTU was set to 206 and rejected by systemd-networkd.

```
[    2.464657] localhost systemd-networkd[228]: eth0: Gained carrier
[    2.733202] localhost kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    2.475135] localhost systemd-networkd[228]: eth0: DHCPv4 address 192.168.0.98/24 via 192.168.0.1
[    2.477249] localhost systemd-networkd[228]: eth0: Could not update MTU in DHCP client: Numerical result out of range 
```

After restarting the instance the MTU was set to 206 and basic network access possible.
As temporary solution we set the MTU manually and patched systemd to allow bad values with a warning:
https://github.com/systemd/systemd/pull/5954

**Comment by crawford** [comment]
@magreiner Is this safe to close out? Sounds like resolving the MTU issue will fix the behavior you are seeing.
