### ISSUE TITLE
CoreOS Docs need update for latest Azure CLI

### ISSUE THREAD

**Issue by pgburt** [coreos/bugs#1905]
### Environment ###

CoreOS on Azure

### Desired Feature ###

Update the docs to work with the latest Azure client.

### Other Information ###

[This came in over IRC](https://botbot.me/freenode/coreos/2017-04-10/?msg=83699492&page=1). User said they ran into issues when using a custom cloud-config. Also wanted to know if we could update the docs to use the latest Azure client.

cc @joshix @radhikapc and whatever Beth's username is 📟

**Comment by crawford** [comment]
Dup of https://github.com/coreos/docs/issues/910.
