### ISSUE TITLE
kernel: enable NVMe over fabrics

### ISSUE THREAD

**Issue by philips** [coreos/bugs#1907]
We have had some customer requests to enable NVMe over fabric.

```
CONFIG_NVME_FABRICS=m
CONFIG_NVME_RDMA=m
CONFIG_NVME_TARGET=m
CONFIG_NVME_TARGET_LOOP=m
CONFIG_NVME_TARGET_RDMA=m
```

**Comment by philips** [comment]
More information: https://community.mellanox.com/docs/DOC-2508

**Comment by philips** [comment]
More information: https://community.mellanox.com/docs/DOC-2508

**Comment by bgilbert** [comment]
Fixed in https://github.com/coreos/coreos-overlay/pull/2518.
