### ISSUE TITLE
Make it easier to use kubectl w/ multiple kubernetes clusters

### ISSUE THREAD

**Issue by emaildanwilson** [coreos/bugs#1915]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Reproduction Steps ###

  1. ...
  2. ...

## Feature Request ##
When using tectonic w/ multiple clusters it should be easy to configure the kubectl client for all clusters. Also, it would be nice if the config played nice with any non-tectonic clusters that folks are using.

Currently in tectonic console it provides the following steps when downloading kubectl configuration:
1. Download the kubectl binary for Mac or Linux or Windows

2. Place the configuration file at ~/.kube/config

3. Done! Interact with the cluster, i.e. kubectl get namespaces

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
aws

### Desired Feature ###
Preferably this would have the option to work how our other internal tools do, by generating the "kubectl config" commands that can be piped to a shell. That way any new cluster configuration is appended to the existing k8s client config.

### Other Information ###
I know that I could manage multiple kubernetes client config files using the provided environment variables but this is cumbersome.

**Comment by robszumski** [comment]
@emaildanwilson Can you share a sample of your commands? Always interested in how to better accomplish this.

A related aside, I wish that kubectl would read from a directory of configs in `~/.kube/configs/` so that you could easily drop in new ones without having to concatenate the single file.

**Comment by euank** [comment]
The way I handle this issue for my clusters is by using a combination of  [direnv](https://direnv.net/) and associating directories with clusters.

For example, my cluster named 'foo' is in `~/k8s/foo`. I have an envrc file that looks like:

```sh
$ cat ~/k8s/foo/.envrc
export KUBECONFIG=$HOME/k8s/foo/auth/kubeconfig
```

I then use that cluster by changing directory to `~/k8s/foo` and then running `kubectl` commands per normal.

**Comment by emaildanwilson** [comment]
We curl an internal api like this
```
curl -H "Content-Type: application/json" -X GET -d '{"namespace": "NAMESPACE", "token": "REDACTED"}' https://internalsite/api/setup | /bin/bash
```

Which prints out the statement similar to this (with real values obviously)
```
#!/bin/bash

kubectl config set-credentials USER --token=REDACTED
base64 -D <<< dGVzdAo=
if [ "$?" == "0" ]; then
 export basecmd="base64 -D"
else
 export basecmd="base64 -d"
fi

($basecmd) <<< "base64'd CERTIFICATE" > /tmp/cert.txt
kubectl config set-cluster cluster1 --certificate-authority="/tmp/cert.txt" --server="https://clusterdnsname.com" --embed-certs=true
kubectl config set-context cluster1 --user=USER --namespace=NAMESPACE --cluster=cluster1
kubectl config use-context cluster1
kubectl version

($basecmd) <<< "base64'd CERTIFICATE" > /tmp/cert.txt
kubectl config set-cluster cluster2 --certificate-authority="/tmp/cert.txt" --server="https://cluster2dnsname.com" --embed-certs=true
kubectl config set-context cluster2 --user=USER --namespace=NAMESPACE --cluster=cluster2
kubectl config use-context cluster2
kubectl version
```

We can then always switch between clusters using "kubectl config use-context" and it still works with minikube or any other personal clusters that folks have configured.

You may not need to do the base64 portions if you're storing the certificates in a different way.

**Comment by euank** [comment]
Since this is a tectonic and/or kubernetes issue, I've opened it in the tectonic repo (https://github.com/coreos/tectonic-forum/issues/110). On this issue tracker, it'll just be lost.
