### ISSUE TITLE
In EC2, resolv.conf doesn't populate with DHCP VPC Settings

### ISSUE THREAD

**Issue by JoeOrtiz** [coreos/bugs#1916]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.4.0
VERSION_ID=1353.4.0
BUILD_ID=2017-03-31-0211
PRETTY_NAME="Container Linux by CoreOS 1353.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

AWS EC2 - us-east-1

### Expected Behavior ###

Populate /etc/resolv.conf

### Actual Behavior ###

Empty /etc/resolv.conf, non-existent file.

### Reproduction Steps ###
1. Boot up an EC2 instance with DHCP VPC Settings.

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
m1.xlarge - PV
AWS EC2

**Comment by euank** [comment]
I wasn't able to reproduce this.

```shell
$ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1381.0.0
VERSION_ID=1381.0.0
BUILD_ID=2017-04-12-2311
PRETTY_NAME="Container Linux by CoreOS 1381.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
COREOS_BOARD="amd64-usr"



core@ip-172-31-24-251 ~ $ cat /etc/resolv.conf 
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known DNS servers.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 172.31.0.2
search us-west-2.compute.internal
core@ip-172-31-24-251 ~ $ 
```

resolv.conf was populated correctly for me on both the PV and HVM AMIs.

Does `/run/systemd/resolve/resolv.conf` exist? Does `systemctl status coreos-tmpfiles.service` show that tmpfiles ran? Is `systemd-resolved` running?

**Comment by JoeOrtiz** [comment]
Seems to be happening in all beta/alpha CoreOS.

The systemd-resolved doesn't show as a unit, but coreos-tmpfiles did run:

```i-07e87d028c4165ec6 ~ # systemctl status coreos-tmpfiles.service
● coreos-tmpfiles.service - Create missing system files
   Loaded: loaded (/usr/lib/systemd/system/coreos-tmpfiles.service; static; vendor preset: disabled)
   Active: inactive (dead) since Mon 2017-04-17 21:48:08 UTC; 3min 29s ago
 Main PID: 537 (code=exited, status=0/SUCCESS)
      CPU: 4ms

Apr 17 21:48:08 i-07e87d028c4165ec6.node.us-west-1-shmoop-tools systemd[1]: Started Create missing system files.
i-07e87d028c4165ec6 ~ # systemctl|grep -i resolv
i-07e87d028c4165ec6 ~ #
```

**Comment by euank** [comment]
I'm still unable to reproduce when launching a PV ami in the default VPC (which should have dhcp settings I think). Does this happen on every instance you launch?
Do you have any user-data that could be interfering with networking?
Are you launching your instances with any other unusual configuration (e.g. many ENIs, etc)?

**Comment by lucab** [comment]
I also did some recent investigation (https://github.com/coreos/bugs/issues/1934#issuecomment-346345773) requiring custom DHCP options and I'm also unable to reproduce the issue described here. I'm thus closing this stale bug. If anybody is hitting this, please open a new ticket and attach the output of:
 * journalctl --no-pager -u systemd-resolved
 * journalctl --no-pager -u systemd-networkd
 * cat /run/systemd/netif/leases/*
