### ISSUE TITLE
multipath -f <map> does not flush maps

### ISSUE THREAD

**Issue by patrick-east** [coreos/bugs#1929]
# Issue Report #

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.7.0
VERSION_ID=1298.7.0
BUILD_ID=2017-03-31-0215
PRETTY_NAME="Container Linux by CoreOS 1298.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

Baremetal and VM's on KVM (all x86_64)

### Expected Behavior ###

When detaching multipath volume devices we should be able to flush the mapper device to remove it safetly.

### Actual Behavior ###

The flush command does not work on individual maps.

### Reproduction Steps ###

  1. Attach multipath device and locate the map id
```
coreos-dev-1 ~ # multipath -l
3624a93702f6eb7add2464f9b0002a375 dm-0 PURE,FlashArray
size=32G features='1 retain_attached_hw_handler' hwhandler='0' wp=rw
`-+- policy='queue-length 0' prio=0 status=active
  |- 5:0:0:1 sdd 8:48 active undef running
  |- 2:0:0:1 sdb 8:16 active undef running
  |- 3:0:0:1 sda 8:0  active undef running
  `- 4:0:0:1 sdc 8:32 active undef running
```
  2. Flush the multipath map id
```
coreos-dev-1 ~ # multipath -f 3624a93702f6eb7add2464f9b0002a375
```
  3. See error in the journal, and map is still there
```
coreos-dev-1 ~ # multipath -l
3624a93702f6eb7add2464f9b0002a375 dm-0 PURE,FlashArray
size=32G features='1 retain_attached_hw_handler' hwhandler='0' wp=rw
`-+- policy='queue-length 0' prio=0 status=active
  |- 5:0:0:1 sdd 8:48 active undef running
  |- 2:0:0:1 sdb 8:16 active undef running
  |- 3:0:0:1 sda 8:0  active undef running
  `- 4:0:0:1 sdc 8:32 active undef running
coreos-dev-1 ~ # journalctl -n 1
-- Logs begin at Mon 2017-01-23 23:03:20 UTC, end at Mon 2017-04-24 20:40:26 UTC. --
Apr 24 20:40:26 coreos-dev-1.novalocal multipath[24913]: must provide a map name to remove
```

### Other Information ###

Upstream in Gentoo they've updated to 0.6.4, https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=464cae287dd74763239b33d48b871224a888cb50

It should be pretty easy then to just bump the version from 0.6.2 to 0.6.4. That may help with this issue (and probably others like http://git.opensvc.com/gitweb.cgi?p=multipath-tools/.git;a=commit;h=69a9b6e90f647635e01c19eee2928d4280d9b7c5 )

**Comment by redbaron** [comment]
Been hit by this, any chance multipath can be bumped to >=0.6.4?

**Comment by redbaron** [comment]
This was released and it seems to work now, at least to a point where multipath device is created just fine

**Comment by lucab** [comment]
@redbaron thanks for reporting back, I'm closing this based on that.
