### ISSUE TITLE
docker > 1.12.x not supported by Kubernetes/Tectonic

### ISSUE THREAD

**Issue by euank** [coreos/bugs#1930]
Container Linux is frequently used as a distro for Kubernetes clusters. However, Container Linux is also used to run other workloads on docker... which can often benefit from newer docker versions.

Currently, Kubernetes 1.5 and 1.6.x [don't support docker > 1.12](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#external-dependency-version-information).

We intend to keep the stable and beta channels on docker versions supported by Kubernetes/Tectonic until we have a better solution.

We've already updated alpha beyond what Kubernetes supports, so until we have a better solution, we'll continue supporting Kubernetes on beta/stable, while keeping alpha on more recent versions of docker.

See [torcx](https://github.com/coreos/torcx) for one possibility of what might be a "better solution" (runtime choice of docker).

**Comment by eskaaren** [comment]
Related to this might be that Flannel 0.7.0 seems to not work in latest stable coreos 1353.7.0.
My kubernetes cluster stopped working after the coreos update and flanneld would not start. By creating systemd units for flanneld.service and flannel-docker-opts.service with FLANNEL_IMAGE_TAG=v0.6.2 the flanneld is starting again but there are other problems in journalctl -xe.

**Comment by euank** [comment]
@eskaaren since 1353.7.0 still has docker 1.12.6, that's a different image. Can you open a new issue with more details about the issues you're hitting?

**Comment by philips** [comment]
@eskaaren For Kubernetes we have moved to flannel being hostable on-top of Kubernetes as a daemonset, so you can now remove Docker customizations:  https://github.com/coreos/flannel#getting-started

**Comment by dteeter** [comment]
Is there an ETA for 17.0X on the beta or stable channels?

This page gives the EOL for docker 1.12 as "Approximately 2017-Q2"
https://success.docker.com/Policies/Maintenance_Lifecycle

This page shows the last update for 1.12 was in early June:
https://docs.docker.com/cs-engine/1.12/release-notes/release-notes/#prior-versions

**Comment by euank** [comment]
cc @sym3tri / @aaronlevy 

At this point I'd also like to move towards 17.0x for stable if at all possible. If you're comfortable enough in Tectonic's testing / validation related to the Kubelet+runtime, we'll happily update the default version.

Either way though, torcx is making its way towards stable and within the next couple stable releases should allow selecting 17.x as a non-default option even if the default isn't updated.

**Comment by aaronlevy** [comment]
I do not believe > 1.12 is supported for kubernetes yet (upstream)

**Comment by squeed** [comment]
Latest news from the front: "Both 1.13.x and 17.03.x will be supported in k8s 1.8", says https://github.com/kubernetes/kubernetes/issues/42926#issuecomment-324724110

**Comment by sandeepone** [comment]
Any Update??

**Comment by crawford** [comment]
We are currently working to enable Tectonic to choose a specific version of docker. We are *hoping* to be able to move back to the latest version of docker in the next Stable release in October.

**Comment by dteeter** [comment]
FYI: Docker 1.12.x will be EOL on 2017-11-14 (reference: https://success.docker.com/Policies/Maintenance_Lifecycle)
![screen shot 2017-10-09 at 11 12 41 am](https://user-images.githubusercontent.com/1538533/31352242-e3c21abc-ace2-11e7-9799-56a9a47fc92b.png)

**Comment by euank** [comment]
@dteeter That chart actually refers to Docker CSE (Commercially Supported Engine).

We do not ship docker CSE (which is a closed-source product I'm not very familiar with).

The open source 1.12 release we ship is not maintained by upstream per this comment here: https://github.com/docker/for-linux/issues/122#issuecomment-334866011

Since we ship it in the distro, we do provide a level of support (backport critical fixes, etc), but it's not the same as upstream support.

**Comment by dteeter** [comment]
@euank: CoreOS stable has been shipping with the same docker version (1.12.6) since January 31st of this year. 

This is concerning, as it is not clear from the release notes if any patches, security fixes, etc. have been applied during that time.

During that same interval, I see a number of security fixes and bug fixes in the docker 17.X release notes.

Can you give any details on what has been done to maintain 1.12.6 within CoreOS?

Is there

**Comment by euank** [comment]
@dteeter We are prepared to backport CVE fixes to 1.12.6 if needed. To my knowledge, there are no public CVEs affecting 1.12.6 currently. If you're aware of anything we've missed, please let us know!
Our source code tree is [here](https://github.com/coreos/docker/commits/coreos-1.12.6) (and built [here](https://github.com/coreos/coreos-overlay/tree/master/app-emulation/docker)) if you're curious about the minor changes we have made.

As @crawford mentioned above, we're working on getting ourselves out of the situation of shipping such an old version. We should have more information on that soon!

**Comment by bgilbert** [comment]
For the broader issue of coupling between Docker versions and Kubernetes versions, see https://github.com/kubernetes/kubernetes/issues/53221.

**Comment by jebe2009** [comment]
@euank Will there be support for newer docker versions during November or what does soon mean? Running alpha to run the latest docker is not really something which we do in production.

**Comment by bgilbert** [comment]
We've just released a [blog post](https://coreos.com/blog/toward-docker-17-in-container-linux) explaining how to select between Docker 1.12 and Docker CE 17.09 in all three Container Linux channels, as well as the timeline for beta and stable moving to Docker CE 17.09 by default.

For the longer-term, more general solution to selecting Docker versions, see #2215.

**Comment by euank** [comment]
This bug had two components to it.

1. The upstream Kubernetes project lags behind on validating/recommending Docker CE versions.
2. Container Linux is impacted by this reality

Issue 1. is being discussed upstream (e.g. in https://github.com/kubernetes/kubernetes/issues/53221) and isn't really our bug in the first place.
Issue 2. should be resolved by this intermediate mechanism combined with ongoing torcx work.

I'm closing this in favor of discussion in Kubernetes and in https://github.com/coreos/bugs/issues/2215
