### ISSUE TITLE
systemd-journald.service high CPU consumption

### ISSUE THREAD

**Issue by nicorevin** [coreos/bugs#1932]
# Issue Report #

## Bug ##

Having a source of a large amount of messages makes systemd-journald process consume up to 100% CPU

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.7.0
VERSION_ID=1298.7.0
BUILD_ID=2017-03-31-0215
PRETTY_NAME="Container Linux by CoreOS 1298.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Expected Behavior ###

`systemd-journal`'s CPU usage at reasonable levels.

### Actual Behavior ###

```
top - 11:32:43 up 3 min,  1 user,  load average: 1.57, 0.60, 0.22
Tasks: 459 total,   5 running, 454 sleeping,   0 stopped,   0 zombie
%Cpu(s): 49.7 us, 30.1 sy,  0.0 ni, 18.5 id,  0.0 wa,  1.0 hi,  0.5 si,  0.2 st
KiB Mem:   8180096 total,  1655624 used,  6524472 free,    19000 buffers
KiB Swap:        0 total,        0 used,        0 free.   864056 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                  
 5622 root      20   0  238712  90856  90352 R  94.8  1.1   0:23.89 systemd-journal  
```

### Reproduction Steps ###

  1. `$ sudo systemd-run sh -c "while :; do echo ok; done"`
  2. ...

### Other Information ###
Systemd-journald config drop-in:
```
$ cat /etc/systemd/journald.conf.d/50-set-rate-limit.conf 
[Journal]
RateLimitInterval=30s
RateLimitBurst=120000
SystemMaxUse=10G
SystemKeepFree=5G
```
Setting up `CPUQuota` for systemd-journald.service is a workaround for now.

**Comment by vcaputo** [comment]
systemd-journald is known to have substantial deficiencies in its current implementation resulting in excessive superfluous system calls and /proc filesystem accesses.  This is really an upstream systemd issue, and it would make sense to create an issue there so they get more feedback on how this problem is affecting users.

https://github.com/systemd/systemd/issues

**Comment by nicorevin** [comment]
here's the upstream issue https://github.com/systemd/systemd/issues/5102
