### ISSUE TITLE
Add support for Ignition on CloudStack

### ISSUE THREAD

**Issue by larstobi** [coreos/bugs#1939]
# Issue Report #

## Feature Request ##

We would like Ignition support on CloudStack.

### Environment ###

CloudStack on Xen.

### Desired Feature ###

To have Igition read config from CloudStack userdata when I boot a CoreOS Container Linux in CloudStack.

**Comment by crawford** [comment]
CloudStack appears to have a very similar setup to Exoscale, which I'm currently [working on](https://github.com/crawford/ignition/commit/db02457918a930d1a822d6eb30022df0351f5405). This looks straightforward enough, but I'll need some help testing images.

**Comment by larstobi** [comment]
@crawford I'll help testing.

**Comment by larstobi** [comment]
I think Exoscale is based on CloudStack. Exoscale has created their own Web UI.

**Comment by larstobi** [comment]
Actually, I think the provider should be called cloudstack, since it is the software that presents the guest vm with the virtual router from which to fetch the userdata.

**Comment by crawford** [comment]
Ah, you are correct. Exoscale and Interoute appear to be based on CloudStack. I'll go ahead and update that code and then just take care of all three in one shot.

**Comment by larstobi** [comment]
@crawford Have you had any success with your code?

I wonder, how can I test your code on my rig? What is the best way to get your Ignition binary in a CoreOS image?

**Comment by crawford** [comment]
https://github.com/coreos/ignition/pull/367 adds support for CloudStack's config-drive. Once that's merged, I can follow on with my code for the network service. The easiest way to test this is to compile Ignition and then copy it over to the machine and manually run it. It's fairly involved to build the full image.

**Comment by larstobi** [comment]
Yay!

**Comment by crawford** [comment]
@larstobi If I build you a development image of Container Linux, will you be able to do some smoke tests to make sure that Ignition and coreos-metadata run correctly?

**Comment by larstobi** [comment]
@crawford I will

**Comment by crawford** [comment]
@larstobi Okay, in case you are able to test, I've uploaded a [test image](https://users.developer.core-os.net/alex/boards/amd64-usr/1520.0.0+2017-09-06-1836/coreos_production_cloudstack_image.bin.bz2). **This is a development image and should not be used in production.** There is a hardcoded password ("password") in case something goes wrong.

**Comment by larstobi** [comment]
I just tested the image, but it didn't pick up the network config. See https://gist.github.com/larstobi/02751c8516012fd5637c8e0179eadbef

**Comment by crawford** [comment]
@larstobi Does this mean Ignition also needs to check the network endpoint from your gist? The existing implementation only reads from the config-drive. The [OpenStack provider](https://github.com/coreos/ignition/blob/master/internal/providers/openstack/openstack.go) also has support for the network metadata.

**Comment by larstobi** [comment]
I can't use the config-drive, it doesn't work on CloudStack with Xen hypervisor. I can only use the network endpoint.

**Comment by larstobi** [comment]
This should work, @crawford: https://github.com/crawford/ignition/blob/cloudstack/internal/providers/cloudstack/cloudstack.go

**Comment by crawford** [comment]
@larstobi It sounds like we need to add support for the CloudStack network metadata as well. It should be pretty straightforward.

**Comment by larstobi** [comment]
@crawford Yes, I agree. Do you have time to do it, or would you like me to give it a shot?

**Comment by crawford** [comment]
I can do it if you're willing to test another image.

**Comment by crawford** [comment]
@larstobi I submitted a [patch](https://github.com/coreos/ignition/pull/445) and built a new [image](http://users.developer.core-os.net/alex/boards/amd64-usr/1520.0.0+2017-09-12-0942/coreos_production_cloudstack_image.bin.bz2). Again, **this is a development image and should not be used in production.** There is a hardcoded password ("password") in case something goes wrong.

**Comment by larstobi** [comment]
@crawford Unfortunately, it didn't work. See https://gist.github.com/larstobi/a7b719265856bd67ae09921bbc3f414c

**Comment by crawford** [comment]
@larstobi Is `http://10.30.5.1/latest/user_data` the correct URL?

**Comment by arithx** [comment]
It looks like it attempted to pull from `10.30.5.1`

```
Sep 12 20:32:43 localhost ignition[458]: GET http://10.30.5.1/latest/user_data: attempt #1
Sep 12 20:32:43 localhost ignition[458]: config drive ("config-2") not found. Waiting...
Sep 12 20:32:43 localhost ignition[458]: config drive ("CONFIG-2") not found. Waiting...
Sep 12 20:32:43 localhost ignition[458]: GET result: Not Found
Sep 12 20:32:43 localhost ignition[458]: failed to fetch config from metadata service: resource not found
```

**Comment by larstobi** [comment]
No, it's "user-data" with a dash, not underscore.

**Comment by larstobi** [comment]
@crawford :-)

**Comment by crawford** [comment]
Crap

**Comment by crawford** [comment]
@larstobi okay, let's try this again. [Image](gs://users.developer.core-os.net/alex/boards/amd64-usr/1520.0.0+2017-09-13-0954/coreos_production_cloudstack_image.bin.bz2).

**Comment by larstobi** [comment]
@crawford Uhm, are you sure that's a new image?

It looks like the same image as last time:

**Comment by larstobi** [comment]
@crawford There's quite a bit of time difference between us, so this can take some days to finish. Anyway, I'm going to bed pretty soon now, but I'll check here again in the morning, when you're asleep. :-)

**Comment by crawford** [comment]
Ah, I didn't rebuild the kernel properly. [This one](http://users.developer.core-os.net/alex/boards/amd64-usr/1520.0.0+2017-09-13-1344/coreos_production_cloudstack_image.bin.bz2) should work.

```
Sep 13 21:12:45 localhost ignition[409]: Ignition v0.18.0-3-gd8afe88-dirty
```

**Comment by larstobi** [comment]
@crawford Good morning! I just tested the new image and I can confirm that it works! :-)

**Comment by crawford** [comment]
@larstobi Great! Thanks for testing. We'll go ahead and get that into the next Alpha release (due in two weeks).

**Comment by larstobi** [comment]
Thanks, @crawford! :-) When do you think it might reach stable?
