### ISSUE TITLE
etcd unable to connect after PXE booting

### ISSUE THREAD

**Issue by pgburt** [coreos/bugs#1941]
# Issue Report #

### Container Linux Version ###

Unsure, many logs are in the Google Groups thread this spawned from, here:
[https://groups.google.com/forum/#!topic/coreos-user/S5XK6onsqAE](https://groups.google.com/forum/#!topic/coreos-user/S5XK6onsqAE)

### Environment ###

ESXi VMs

### Expected Behavior ###

User tried to install CoreOS using PXE, on some ESXi VMs. They would expect the etcd service to connect.

### Actual Behavior ###

The etcd cluster is having issues connecting. 

They include a log of them pinging between machines, some netstats, and the ignition file they used to turn-up the machines. 

### Other Information ###

I looked through the etcd variables, and couldn't spot anything wrong (but I'm fallible). Sharing here to give the issue more visibility.

To respond, the [original thread is here](https://groups.google.com/forum/#!topic/coreos-user/S5XK6onsqAE).

**Comment by dannymk** [comment]
Same state here, I was trying to setup a 3 node etcd V3 cluster following the docs and ran into this issue.

**Comment by bgilbert** [comment]
It appears that the problem has been resolved, so I'll close.
