### ISSUE TITLE
Unable to migrate from ETCD2 to ETCD3 using documentation

### ISSUE THREAD

**Issue by troyfontaine** [coreos/bugs#1942]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

AWS EC2: ami-12942672

### Expected Behavior ###
Documentation on how to migrate from etcd2 to etcd3 via etcd-member.  In etcd2 where data is stored in /var/lib/etcd2/ and not in /var/lib/etcd/ using the systemd service it is unable to find the existing cluster.

### Actual Behavior ###
No documentation is available on how to perform this migrations from what I can find?  Following the instructions, the etcd service cannot find the cluster.

### Reproduction Steps ###

  1. Stop etcd2
  2. Start etcd-member
  3. Query etcdctl cluster-health and find the instance is not a member of the cluster.

**Comment by euank** [comment]
As you point out, those two units use different data directories.

I filed an [issue](https://github.com/coreos/docs/issues/1062) on the docs repo for the same thing a few days ago since I hit this pain point too. Thanks for reporting!

**Comment by radhikapc** [comment]
has been fixed https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_0.md
