### ISSUE TITLE
Fleet fails to list all services and to restart them correctly

### ISSUE THREAD

**Issue by e-massa** [coreos/bugs#195]
I'm running a CoreOS cluster of 4 machines and I'm experiencing issues with fleet.
First of all, latency between nodes is low, as show by pinging each machine.

>2553 packets transmitted, 2552 received, 0% packet loss, time 1128ms
rtt min/avg/max/mdev = 0.142/0.389/11.069/0.582 ms, ipg/ewma 0.442/0.245 ms

Still the command:
>fleetctl list-machines

very often shows just a subset of the cluster (2 or 3 machines) and the command:

>fleetctl list-units

might not show any unit or just a small subset. 

When this happens the scheduled units are terminated and some fail to restart. Moreover when it happens that a unit is successfully restarted, the corresponding values in etcd which are set by the systemd service using:

>ExecStartPre=/usr/bin/etcdctl set ....

and which are normally removed using 

>ExecStop=/usr/bin/etcdctl rm
or
>ExecStop=/usr/bin/etcdctl rmdir

are not removed in this case (i.e. not all the ExecStop commands are executed correctly).

The output from journalctl is the following:

>journalctl -r -u fleet
-- Logs begin at Mon 2014-11-24 11:29:27 UTC, end at Fri 2014-11-28 12:41:38 UTC. --
Nov 28 12:41:28 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:41:27 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:54 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:53 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:36 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:34 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:25 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:24 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:19 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:18 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:15 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:14 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:12 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:11 node-1 fleetd[577]: INFO client.go:278: Failed getting response from http://localhost:4001/: cancelled
Nov 28 12:40:10 node-1 fleetd[577]: ERROR event.go:91: etcd watcher {Watch /_coreos.com/fleet/job} returned error: cancelled

The heartbeat interval and the election timeout have been increased respectively to 500ms and 2000ms with not improvement.

I'm running CoreOS alpha with the following versions:
>fleetctl version 0.8.3
>etcdctl version 0.4.6

**Comment by crawford** [comment]
Sorry we let this report slide through the cracks. Newer versions of both fleet and etcd have been released. Can you file a new issue if you still have trouble?
