### ISSUE TITLE
Config transpiler: Public and private IPs swapped on GCE

### ISSUE THREAD

**Issue by maikzumstrull** [coreos/bugs#1950]
### Environment ###

ct v0.3.0 on macOS, generating configs for `-platform gce`

### Expected Behavior ###

`PRIVATE_IPV4` resolves to private IP

### Actual Behavior ###

`PRIVATE_IPV4` resolves to public IP

### Other Information ###

https://github.com/coreos/container-linux-config-transpiler/blob/master/config/templating/templating.go#L74-L75

Those are swapped. E.g. on a test box:
```
COREOS_GCE_IP_LOCAL_0=172.16.219.5
COREOS_GCE_IP_EXTERNAL_0=104.155.179.42
```

**Comment by dgonyeo** [comment]
Fixed in https://github.com/coreos/container-linux-config-transpiler/pull/68

A patch release is being made that will include this.
