### ISSUE TITLE
container linux config on openstack

### ISSUE THREAD

**Issue by gregster85** [coreos/bugs#1952]
# Issue Report #

I have converted a container linux config yml to a ignition json using ct tool v0.3.1.
To be sure I validated the json on coreos.com/validate.
I provisioned a CoreOS machine using Terraform and the ignition config as user_data.
The ssh_authorized_keys were set correctly, but the etcd part did not work.

It seems the COREOS_OPENSTACK_IPV4_LOCAL is not working, is that possible?
The ignition config I used: https://gist.github.com/gregster85/0f121e68fbc18dca7ed5eb5df8b37ea2

"systemctl status coreos-metadata.service" shows it's trying to fetch from http://169.254.169.254/latest/meta-data?

```
coreos-metadata.service - CoreOS Metadata Agent
   Loaded: loaded (/usr/lib/systemd/system/coreos-metadata.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/coreos-metadata.service.d
           └─20-clct-provider-override.conf
   Active: inactive (dead) since Fri 2017-05-05 11:22:32 UTC; 9s ago
  Process: 7444 ExecStart=/usr/bin/coreos-metadata ${COREOS_METADATA_OPT_PROVIDER} --attributes=/run/metadata/coreos (code=exited, status=0/SUCCESS)
 Main PID: 7444 (code=exited, status=0/SUCCESS)
      CPU: 4ms

May 05 11:22:31 host-192-168-0-128 systemd[1]: Starting CoreOS Metadata Agent...
May 05 11:22:31 host-192-168-0-128 coreos-metadata[7444]: Fetching "http://169.254.169.254/latest/meta-data/instance-id": Attempt #1
May 05 11:22:32 host-192-168-0-128 coreos-metadata[7444]: Fetching "http://169.254.169.254/latest/meta-data/local-ipv4": Attempt #1
May 05 11:22:32 host-192-168-0-128 coreos-metadata[7444]: Fetching "http://169.254.169.254/latest/meta-data/public-ipv4": Attempt #1
May 05 11:22:32 host-192-168-0-128 coreos-metadata[7444]: Fetching "http://169.254.169.254/latest/meta-data/hostname": Attempt #1
May 05 11:22:32 host-192-168-0-128 coreos-metadata[7444]: Fetching "http://169.254.169.254/latest/meta-data/public-keys": Attempt #1
May 05 11:22:32 host-192-168-0-128 coreos-metadata[7444]: Fetching "http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key": Attempt #1
May 05 11:22:32 host-192-168-0-128 systemd[1]: Started CoreOS Metadata Agent.
```

### Container Linux Version ###

Container Linux by CoreOS stable (1353.7.0)

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

Openstack mitaka

### Expected Behavior ###

Provide an ignition configuration that configures etcd.

### Actual Behavior ###

etcd is not configured

### Reproduction Steps ###

  1. Use my provided ignition json to launch a CoreOS vm on openstack
  2. It will set authorized_keys & locksmith update config, but no etcd

**Comment by gregster85** [comment]
I found it uses /run/metadata/coreos as environment file, and the COREOS_OPENSTACK_IPV4_LOCAL is correct there.
The real cause was because "advertise_client_urls" & "initial_advertise_peer_urls" were not set correct, and there is an error in the documentation on some places. For example https://coreos.com/os/docs/latest/dynamic-data.html

May 05 12:13:27 host-192-168-0-129 etcd-wrapper[3551]: ++ id -u etcd
May 05 12:13:27 host-192-168-0-129 etcd-wrapper[3551]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid --trust-keys-from-https --mount volume=systemd-dir,target=/run/systemd/system --volume systemd-dir,kind=host,source=/run/systemd/system,readOnly=true --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --volume data-dir,kind=host,source=/var/lib/etcd,readOnly=false --volume etc-ssl-certs,kind=host,source=/etc/ssl/certs,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=data-dir,target=/var/lib/etcd --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci quay.io/coreos/etcd:v3.0.15 --user=232 -- --name=coreos-test.novalocal --listen-peer-urls=http://192.168.0.129:2380 --listen-client-urls=http://0.0.0.0:2379 --initial-advertise-peer-urls=192.168.0.129:2380 --initial-cluster=2a48a7ead82942a288f52d9a97c74a7e=http://192.168.0.129:2380 --advertise-client-urls=192.168.0.129:2379
May 05 12:13:28 host-192-168-0-129 etcd-wrapper[3551]: invalid value "192.168.0.129:2380" for flag -initial-advertise-peer-urls: URL scheme must be http, https, unix, or unixs: 192.168.0.129:2380

The advertise_client_urls & initial_advertise_peer_urls should start with http.
After fixing this, I get another error now:

etcdmain: couldn't find local name "coreos-test.novalocal" in the initial cluster configuration

But the ignition configuration is passed like it should... so case closed.

**Comment by gregster85** [comment]
To be clear, these docs should be updated:

https://coreos.com/os/docs/latest/dynamic-data.html
https://coreos.com/os/docs/latest/clc-examples.html

`advertise_client_urls:       "{PRIVATE_IPV4}:2379"
initial_advertise_peer_urls: "{PRIVATE_IPV4}:2380"`

Should be:

`advertise_client_urls:       "http://{PRIVATE_IPV4}:2379"
initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"`

**Comment by gregster85** [comment]
Also Openstack could be added to https://coreos.com/ignition/docs/0.14.0/supported-platforms.html

**Comment by crawford** [comment]
Thank you for identifying the documentation issue. @dgonyeo, can you fix this up and get the site updated? We should also update `ct` to catch this sort of mistake.

**Comment by dgonyeo** [comment]
Made two PRs to fix the docs, working on extra validation in `ct` to catch this, but got tripped up on reflection. That PR will land Monday.
