### ISSUE TITLE
network interface has static (intended) and dynamic IP addresses

### ISSUE THREAD

**Issue by davenport** [coreos/bugs#1953]
# Issue Report #

### Container Linux Version ###

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.6.0
VERSION_ID=1353.6.0
BUILD_ID=2017-04-25-0215
PRETTY_NAME="Container Linux by CoreOS 1353.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"

### Environment ###

VMWare/vSphere 6U2

### Expected Behavior ###

Assign static IP address and interface has only 1 static IP address
Works as expected on 1235.12.0 and 1298.7.0

ip addr show ens192                                                                                                     
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8d:87:92 brd ff:ff:ff:ff:ff:ff
    inet 140.141.101.14/24 brd 140.141.101.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8d:8792/64 scope link 
       valid_lft forever preferred_lft forever

### Actual Behavior ###

On versions 1353.6.0 and 1353.7.0 the "scope global secondary dynamic ens192" IP address is a bug

ip addr show ens192                                                                                         
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8d:21:02 brd ff:ff:ff:ff:ff:ff
    inet 140.141.101.50/24 brd 140.141.101.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet 140.141.101.226/24 brd 140.141.101.255 scope global secondary dynamic ens192
       valid_lft 164sec preferred_lft 164sec
    inet6 fe80::250:56ff:fe8d:2102/64 scope link 
       valid_lft forever preferred_lft forever

### Reproduction Steps ###

the relevant ignition YAML...

```
networkd:
  units:
    - name: 10-static.network
      contents: |
        [Match]
        Name=e*

        [Network]
        Address=${IP_ADDRESS}/24
        Gateway=${GATEWAY}
        DNS=${DNS1}
        DNS=${DNS2}
```

### Other Information ###

Is this the expected behavior for 1353.6.0 and 1353.7.0 ?
Is there a work around?

Thank you,

Doug

**Comment by davenport** [comment]
Here is some more info. I'm seeing the following via journalctl

coreos-cloudinit[1246]: 2017/05/07 07:50:31 Writing unit "00-.network" to filesystem
coreos-cloudinit[1246]: 2017/05/07 07:50:31 Writing file to "/run/systemd/network/00-.network"
coreos-cloudinit[1246]: 2017/05/07 07:50:31 Wrote file to "/run/systemd/network/00-.network"
coreos-cloudinit[1246]: 2017/05/07 07:50:31 Wrote unit "00-.network"
coreos-cloudinit[1246]: 2017/05/07 07:50:31 Ensuring runtime unit file "00-.network" is unmaskeMay 07 07:50:31
coreos-cloudinit[1246]: 2017/05/07 07:50:31 /run/systemd/network/00-.network is not null or empty, refusing to unmask

cat /run/systemd/network/00-.network
[Match]

[Network]
DHCP=true

I do not see this in versions 1235.12.0 and 1298.7.0

I can fix the problem by:
rm /run/systemd/network/00-.network
systemctl restart systemd-networkd

After a few minutes the dynamic IP is removed and /etc/resolv.conf is updated as expected.

After a reboot the problem returns.

Any ideas or suggestions?

Thank you,

Doug

**Comment by davenport** [comment]
Decided to try the beta channel (1381.1.0)

The problem does not exist in (1381.1.0)

Seems like there is something wrong with 1353.6.0 and 1353.7.0

**Comment by bgilbert** [comment]
This looks like the same issue as #1802.  You should able to work around it by setting the `guestinfo.interface.0.dhcp` OVF property to `no`.

**Comment by bgilbert** [comment]
I'll go ahead and close.  Please reopen if you're still seeing this issue.
