### ISSUE TITLE
Container Linux should ship a cpio binary

### ISSUE THREAD

**Issue by maikzumstrull** [coreos/bugs#1956]
### Desired Feature ###

Container Linux currently doesn't ship a cpio binary. This seems like a weird omission, since it's otherwise shipping a quite extensive collection of archivers. cpio is a required format for Linux work, since it's the only thing the kernel will unpack to fill initramfs. CoreOS docs suggest using cpio files to emulate the OEM partition feature when network booting. There also doesn't seem to be a workaround that I could find. GNU cpio can unpack tar files, but GNU tar does not understand cpio. busybox or toybox don't seem to be available either.

Suggested fix: Ship a cpio binary, either GNU or libarchive.

**Comment by bgilbert** [comment]
We're already shipping the libarchive cpio as `/usr/bin/bsdcpio`, though admittedly that isn't very obvious.

**Comment by maikzumstrull** [comment]
Interesting. There's probably limited value in _also_ shipping GNU cpio, so maybe add a symlink in the build process for discoverability?

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
