### ISSUE TITLE
cloud-config docs: Should mention using ignition/deprecation

### ISSUE THREAD

**Issue by euank** [coreos/bugs#1959]
# Issue Report #

The [cloud-config](https://coreos.com/os/docs/latest/cloud-config.html) docs make no mention of ignition. They should have a warning at the top that ignition should be used.

**Comment by ElijahCaine** [comment]
I can cover this. Thank's for the heads up.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-cloudinit/pull/446.

**Comment by ismay** [comment]
One thing that doesn't seem to be mentioned anywhere is whether using a cloud-config will eventually be removed completely from coreos. Is there any info on that?

**Comment by crawford** [comment]
@ismay Maybe someday we'll be able to remove it, but we are at least two or three years away given the amount of development and the time needed to migrate.
