### ISSUE TITLE
config-transpiler outputs booleans values in invalid format

### ISSUE THREAD

**Issue by raeesbhatti** [coreos/bugs#1960]
### Expected Behavior ###
That `ct` tool outputs `boolean` values as `true` or `false`.
### Actual Behavior ###
It turns boolean values to `%!q(bool=true)` and `%!q(bool=false)`. Which does not work when deployed.
### Reproduction Steps ###
Provide the following as input to `ct` tool.
```
etcd:
  version:                     "3.1.5"
  auto_tls:                    true
  peer_auto_tls:               true
```

**Comment by crawford** [comment]
This has already been fixed by https://github.com/coreos/container-linux-config-transpiler/pull/66. Please upgrade to [v0.3.1](https://github.com/coreos/container-linux-config-transpiler/releases/tag/v0.3.1).
