### ISSUE TITLE
Recent kubernetes can't talk to ectd2 by default

### ISSUE THREAD

**Issue by jpap** [coreos/bugs#1963]
# Issue Report #

## Bug ##

In recent Kubernetes, e.g. `v1.6.2_coreos.0`, the api server will try and talk to etcd using version 3 of the protocol.  By default, CoreOS ships with version 2 of etcd.  As a result, the api server will fail to start.

It took some time to [find the issue](https://github.com/kubernetes/kubernetes/issues/39710), where the simple solution is to add the `--storage-backend=etcd2` option to `/etc/kubernetes/manifests/kube-apiserver.yaml`.

The [CoreOS documentation](https://coreos.com/kubernetes/docs/latest/deploy-master.html) should be updated to suit, until CoreOS starts shipping etcd3 by default.

I encountered this error after upgrading the Kubernetes image in my configuration and it failed to restart.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

Bare metal server.

### Expected Behavior ###

K8s api server should start based on the CoreOS documented configuration.

### Actual Behavior ###

Api server fails to start because it needs to be configured with the etcd2 backend.

**Comment by ElijahCaine** [comment]
@jpap, Container Linux does ship with etcd3 via the etcd-member systemd service. This runs etcd3 out of a container. We're working on improving the docs around this. The [Getting started with etcd on Container Linux](https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html) doc might be worth checking out.

We're not planning on shipping an etcd3 binary any time soon and will eventually remove the etcd2 binary from the OS. This means that down the road the easiest way to [manually] run etcd will be via the `etcd-member` service.

Thank's for the heads up, this will help us improve the documentation around the *Container Linux* way to run etcd.

**Comment by jpap** [comment]
Thanks for the link to the new etcd docs.

Separately I'd recommend an immediate update to the CoreOS kubernetes setup documentation to address the `storage-backend` option as outlined above.  It might also be pertinent to amend the "Step 1" part of the documentation to introduce the etc-member systemd service, link to the etcd docs you've highlighted, and mention the built-in etcd2 phaseout in addition to the v{2,3} considerations with the api-server.

That is, updates to:
* https://coreos.com/kubernetes/docs/latest/getting-started.html
* https://coreos.com/kubernetes/docs/latest/deploy-master.html

**Comment by bgilbert** [comment]
We no longer ship etcd2 in Container Linux and our Kubernetes docs have been rewritten.  I'll close.
