### ISSUE TITLE
coreos-metadata: additional ec2 attributes

### ISSUE THREAD

**Issue by s-urbaniak** [coreos/bugs#1972]
# Issue Report #

### Container Linux Version ###

Any version running https://github.com/coreos/coreos-metadata/releases/tag/v0.9.0

### Environment ###

AWS / ec2

### Desired Feature ###

Currently the following attributes are exposed:

- COREOS_EC2_HOSTNAME
- COREOS_EC2_IPV4_LOCAL
- COREOS_EC2_IPV4_PUBLIC
- COREOS_EC2_AVAILABILITY_ZONE

Additionally the following new attributes would be helpful:

- COREOS_EC2_INSTANCE_ID
- COREOS_EC2_REGION
- COREOS_EC2_ASG_NAME (if available)

Reference:
https://github.com/coreos/tectonic-installer/pull/707/files#diff-be7dd467e2012e0169fac3f83b6ac7f7R3

/cc @lucab as discussed OOB
/cc @alexsomesan Any additional metadata that could/should be exposed?

**Comment by lucab** [comment]
@s-urbaniak thanks for capturing this. If there are any similarly wishlist entries for Azure / GCP / OpenStack, feel free to open dedicated tickets.

**Comment by dgonyeo** [comment]
`COREOS_EC2_INSTANCE_ID` is currently supported by coreos-metadata, but for some reason isn't mentioned in the README.

I just made a PR to add support for `COREOS_EC2_REGION`, and to add the instance id to the README: https://github.com/coreos/coreos-metadata/pull/43

I don't yet see how to find the asg name via the metadata service, I'll keep looking around, and make a separate PR to add that if I find it.

**Comment by lucab** [comment]
@dgonyeo I don't think it is available as instance metadata, see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-categories.

**Comment by sdemos** [comment]
`COREOS_EC2_INSTANCE_ID` and `COREOS_EC2_REGION` are now both exposed by `coreos-metadata`, and It doesn't seem like the asg name is available from the aws metadata service, so it seems like we've hit all the points of this issue. closing.
