### ISSUE TITLE
Long DHCP setup time causes ignition to fail

### ISSUE THREAD

**Issue by FarzanRNobakht** [coreos/bugs#1973]
# Issue Report #
We are trying to setup coreos with matchbox, when the coreos is booted to ram for the first time
ignition unit tries to fetch its configuration from matchbox but after multiple try it fails because the network is not setup yet. The network gets configured via DHCPv4 about 2-3 seconds after the ignition unit gives up. 

## Bug ##

Ignition unit doesn't wait for network to get up properly.

### Container Linux Version ###
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.7.0
VERSION_ID=1298.7.0
BUILD_ID=2017-03-31-0215
PRETTY_NAME="Container Linux by CoreOS 1298.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###
Bare Metal: HP ProLiant DL160 Gen9

### Expected Behavior ###
Ignition unit must wait for the network to setup.

### Actual Behavior ###
Ignition unit starts running before the network setups.

### Reproduction Steps ###

  1. Setup a fairly slow DHCP server (we are using dnsmasq)
  2. Boot CoreOS with matchbox v0.6 and wait till it fails.

### Other Information ###
We are using Matchbox v0.6 and the ignition file we're trying to boot with is reboot-install.json from the examples.

**Comment by crawford** [comment]
I believe the default timeout is 90 seconds. Can you attach the Ignition logs (`journalctl -t ignition --no-pager`) so we can investigate further?

**Comment by mdhheydari** [comment]
@crawford Is there any way so I could increase it?
I'm trying to collect the logs you wanted.

**Comment by mdhheydari** [comment]
Here they are. [The ignition log](https://pastebin.com/DjFanL0K) and [The whole journal log](https://pastebin.com/FYv097y9)

**Comment by crawford** [comment]
@mdhheydari There is an experimental option in the config to allow the timeout to be increased. _Unfortunately_, that appears to have been broken at some point. We'll fix that up so you can use that.

**Comment by bgilbert** [comment]
Those log links have expired.

The Ignition 2.1.0 spec includes an option to increase the fetch timeout, and the next major Container Linux stable release will support it.  However, that doesn't help with the initial config fetch, unless you [pass a stub config in a second initramfs](https://coreos.com/os/docs/latest/booting-with-pxe.html#adding-a-custom-oem) which sets the timeout and fetches the real config.

We do need to have *some* default timeout, and 90 seconds seems like a pretty long time to wait for network activation, so I don't think we're likely to increase the default.
