### ISSUE TITLE
Update btrfs-progs to latest release

### ISSUE THREAD

**Issue by nri-pl** [coreos/bugs#1974]
Hi,
Please update btrfs-progs to the latest release, there are some nice fixes/features which I need.
https://github.com/kdave/btrfs-progs/releases
Current version is v4.11

The latest CoreOS has v4.4.1

```
# btrfs --version
btrfs-progs v4.4.1

# cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.0.0
VERSION_ID=1409.0.0
BUILD_ID=2017-05-10-2301
PRETTY_NAME="Container Linux by CoreOS 1409.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

```

**Comment by bgilbert** [comment]
Do you need 4.11 specifically, or will 4.10.2 do?

**Comment by nri-pl** [comment]
4.10.2 will do.

**Comment by bgilbert** [comment]
Done in https://github.com/coreos/portage-stable/pull/553.
