### ISSUE TITLE
Kubernetes Pods crash/unrecoverable stream copy error: reading from a closed fifo

### ISSUE THREAD

**Issue by battlecow** [coreos/bugs#1978]
# Issue Report #

### Container Linux Version ###

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"

### Environment ###

VMware ESX hosts on prem, followed https://coreos.com/kubernetes/docs/latest/getting-started.html for setup.

### Expected Behavior ###

Pods don't randomly stop working on a node and are never able to come back online.

### Actual Behavior ### 
Nodes intermittently fail and pods (at least with readiness checks) are never able to come back online.  Most pods have been running on the node for an extended amount of time (from hours to days).

Docker log errors include:
`level=error msg="Error running exec in container: rpc error: code = 2 desc = shim error: context deadline exceeded"`
`level=error msg="Handler for GET /v1.24/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"`
A larger snapshot of docker journal can be found in the Gist: https://gist.github.com/battlecow/4f255c1594297218cbf2c3f1992597b2 

### Reproduction Steps ###

  1. Run Kubernetes
  2. Run deployment with a readiness check on a pod
  3. Wait?

### Other Information ###
Found a related issue: https://github.com/moby/moby/issues/29369
I am not using checkpoint restore nor was the host under serious load when these issues crop up.
Restarting Docker and the Kubelet resolve the issues until the next time they happen.

**Comment by fiksn** [comment]
I've seen it also on our cluster running

VERSION_ID=1409.5.0
BUILD_ID=2017-06-22-2222
PRETTY_NAME="Container Linux by CoreOS 1409.5.0 (Ladybug)"

It seems to happen (more often?) on nodes which have storage on Ceph filesystem. Usually it occurs after a lot of pods get restarted (redeploy) and restarting docker daemon on the affected machine helps. But obviously this is quite annoying. I was thinking about tweaking kube-controller-manager --concurrent settings. And limit everything to 1.

**Comment by euank** [comment]
This typically means either dockerd or containerd is wedged. Containerd's status and logs would be helpful to further debug this.

I'm hopeful that containerd automatically restarting on failure, which happens starting with Container Linux 1506, will be sufficient to workaround this.

**Comment by battlecow** [comment]
So this is still occurring on 1465.6.0, here are the docker and containerd logs when the issue begins, https://gist.github.com/battlecow/ea9fb0b10b7efcfe328ad75d585e7079

**Comment by zq-david-wang** [comment]
Caught similar issue with 1465.8.0:  "docker ps" would hang after one pod OOM-killed.
According to this, https://github.com/moby/moby/issues/34293, this docker issue could be fixed in docker-ce 17.06.1.

**Comment by euank** [comment]
I'm closing this issue as stale. Every channel now ships a recent docker-ce version by default.
