### ISSUE TITLE
coreos-cloudinit doesn't support drop-ins

### ISSUE THREAD

**Issue by chengweiv5** [coreos/bugs#198]
CoreOS release: alpha 509.1.0

I followed the [document](https://coreos.com/docs/cluster-management/setup/cloudinit-cloud-config/) at coreos.com and used 'drop-ins' to configure docker.service to access insecure internal registry, just copy and paste the exactly lines in the guide like below.

```
    - name: docker.service
      drop-ins:
        - name: 50-insecure-registry.conf
          content: |
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="10.0.1.0/24"'
```

However, when I started a single coreos, from journalctl, I see coreos-cloudinit complained an error like below:

```
Dec 04 14:02:58 core-01 coreos-cloudinit[886]: line 34: warning: unrecognized key "drop_ins"
```

Could anyone to fix coreos-cloudinit or the document?

**Comment by marineam** [comment]
cloudinit >= 1.0.0 has been in alpha and beta for a while now.
