### ISSUE TITLE
SystemD timer randomly skips execution

### ISSUE THREAD

**Issue by SDedik** [coreos/bugs#1985]
# Issue Report #

## Bug ##
SystemD timer randomly skips execution

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

Hyper-V on Windows Server 2012 R2 Datacenter

### Expected Behavior ###
Once every day timer should fire up and trigger the service that initiates VM reboot.

### Actual Behavior ###
On random occurrences timer skips execution and does not trigger the service.

### Reproduction Steps ###
This is how timer and associated service is defined:
```
coreos:
  units:
    - name: reboot.service
      content: |
        [Unit]
        Description=Service to reboot this server.
        [Service]
        Type=oneshot
        ExecStart=/usr/sbin/reboot -f
    - name: reboot.timer
      command: start
      content: |
        [Unit]
        Description=Runs reboot.service according to timer.
        [Timer]
        OnCalendar=*-*-* 05:24:00
        AccuracySec=1s
```
As can be seen from following output, next expected start is on 2017-06-01:
```
sudo systemctl list-timers reboot.timer
NEXT                         LEFT     LAST PASSED UNIT         ACTIVATES
Thu 2017-06-01 05:24:00 UTC  20h left n/a  n/a    reboot.timer reboot.service
```
However, timer has been started 2 days ago and should have been triggered on 2017-05-31:
```
sudo journalctl -u reboot.timer
-- Logs begin at Tue 2017-05-30 11:44:13 UTC, end at Wed 2017-05-31 08:43:50 UTC. --
May 30 11:44:30 host01 systemd[1]: Started Runs reboot.service according to timer..
```
### Other Information ###
I tried to set timer to trigger every 3 minutes and according to my observations it can successfully trigger for days and then skip couple of executions in a row.

**Comment by lucab** [comment]
I'm surprised that `list-timers` doesn't show any LAST occurence, even though there is a journal entry on the 30th.

Can you please check and post the content of:
 * `sudo ls -la --time-style=long-iso /var/lib/systemd/timers/`
 * `sudo journalctl --list-boots`
 * `sudo journalctl -m` around 05:24 on May 31st

**Comment by SDedik** [comment]
The way I understand it: timer gets created on every machine boot, therefore if everything would work as expected, than on every boot LAST occurrence would be empty and it would be normal behavior. In this case, however, absence of LAST occurrence indicates that timer never fired up.

```
sudo ls -la --time-style=long-iso /var/lib/systemd/timers/
total 0
drwxr-xr-x. 2 root root  60 2017-05-30 11:44 .
drwxr-xr-x. 6 root root 160 2017-05-30 11:44 ..
-rw-r--r--. 1 root root   0 2017-05-30 11:44 stamp-logrotate.timer
```
```
sudo journalctl --list-boots
 0 9bdacd117d624500b882bf0ae036b26b Tue 2017-05-30 12:18:53 UTC—Wed 2017-05-31 10:23:47 UTC

```
sudo journalctl -m from tonight when reboot was supposed to happen:
```
sudo journalctl -m
May 31 03:44:31 host01 sshd[1877]: WARNING: could not open /etc/ssh/moduli (No such file or directory), using fixed modulus
May 31 04:44:32 host01 sshd[1877]: WARNING: could not open /etc/ssh/moduli (No such file or directory), using fixed modulus
May 31 05:44:33 host01 sshd[1877]: WARNING: could not open /etc/ssh/moduli (No such file or directory), using fixed modulus
May 31 06:27:06 host01 dockerd[3528]: time="2017-05-31T06:27:06.903446837Z" level=error msg="Handler for POST /v1.24/containers/create returned error: No such image: postgres:latest"
```

**Comment by crawford** [comment]
@SDedik Have you seen this issue in the Alpha or Beta channel? Those are now shipping systemd 234.

**Comment by SDedik** [comment]
Haven't tried them yet.
I'll give it a shot and test for some time.

**Comment by euank** [comment]
I think we should report this issue upstream (https://github.com/systemd/systemd/issues).

I doubt this issue is specific to Container Linux, and the systemd issue tracker could have people more familiar with possible problems here.

Are you willing to file it upstream if it still reproduces in 234, @SDedik?

**Comment by SDedik** [comment]
I've been keeping an eye on one server with "Container Linux by CoreOS beta (1520.4.0)". This very same server experienced the issue before with CoreOS Stable branch.
Since switching it to beta, I haven't seen a single time for this issue to occur. Of course, two days is not much, and I'll keep watching, but it looks promising.
If the issue occurs again, you are right, it is probably much better to report it to Systemd tracker and I will do just that.
I believe this issue here can be closed for now.

**Comment by crawford** [comment]
@SDedik thanks for double checking.
