### ISSUE TITLE
Upgrade etcd-member to >= 3.0.12 to prevent kubernetes bugs

### ISSUE THREAD

**Issue by pizzarabe** [coreos/bugs#1986]
## Feature Request ##

There is a bug tracking various problems with (the current 1.6?) Kubernetes and etcd < 3.0.12 (https://github.com/kubernetes/kubernetes/issues/45506)

This problem results in not correct deleted k8s objects (https://github.com/projectcalico/calico/issues/753) and dying schedulers (https://github.com/kubernetes/kubernetes/issues/46347)

The current etcd-member.service in CoreOS Container Linux stable (1353.8.0) seems to deploy etcd 3.0.10, to prevent errors with kubernetes we should consider using >= 3.0.12

**Comment by lucab** [comment]
Thanks for the report. For reference, etcd has already been bumped in the other non-stable channels and 1409 (current beta, next stable) ships with 3.1.6.
In the meanwhile, to override current etcd-member version, you can specify a custom `ETCD_IMAGE_TAG` environment flag to the service.

**Comment by lucab** [comment]
@dm0- @bgilbert FYI there is a newer patch release you may want to bump to https://github.com/coreos/etcd/releases/tag/v3.1.8.

**Comment by euank** [comment]
Stable v1409.2.0, which was just released, has etcd-wrapper at 3.1.6.
