### ISSUE TITLE
ct: unrecognized key: docker  while following latest doc example for docker TLS

### ISSUE THREAD

**Issue by WesleyThurner** [coreos/bugs#1991]
# Issue Report #

### ct Version ###

compiled from source on Jun 5th

### Environment ###

MacOS 10.12.5

### Expected Behavior ###

I expected to transpile my config into ignition without errors.  I followed this example: https://coreos.com/os/docs/latest/customizing-docker.html
Under the container linux config section I used the following in my config per the example:
docker:
  flags:
    - --tlsverify
    - --tlscacert=/etc/docker/ca.pem
    - --tlscert=/etc/docker/server.pem
    - --tlskey=/etc/docker/server-key.pem

This will error during ct.  I reviewed the ignition example tab and it appears that the transpiled version I should be creating a service with a conf file and the contents with the flag options. 

### Actual Behavior ###

ct output:
warning at line 150, column 0
Config has unrecognized key: docker

### Reproduction Steps ###

  1. create a file for consumption by ct with docker flag options as in the example
  2. ct the config file
  3. review error output and final file.

**Comment by euank** [comment]
```sh
$ git rev-parse HEAD         
4adc141165a323433df8efa389a74fcdee8a5044
$ ./build
Building Config Transpiler...

$ cat docker-debug.yaml
docker:
  flags:
  - "--debug"
$ ./bin/ct < docker-debug.yaml
{"ignition":{"version":"2.0.0","config":{}},"storage":{},"systemd":{"units":[{"name":"docker.service","enable":true,"dropins":[{"name":"20-clct-docker.conf","contents":"[Service]\nEnvironment=\"DOCKER_OPTS=--debug\""}]}]},"networkd":{},"passwd":{}}
```

Using the example on that page worked on my machine. Can you double check you're on a recent commit?

**Comment by WesleyThurner** [comment]
Thanks for the information.  I reviewed the README.md and realized that the instructions specify branch v0.1.0 instead of v0.3.1.  Once I compiled from source from the latest branch, it worked perfectly.

I created a pull request to fix this:
https://github.com/coreos/container-linux-config-transpiler/pull/80

**Comment by WesleyThurner** [comment]
Closing Issue - PR was approved

https://github.com/coreos/container-linux-config-transpiler/pull/80
