### ISSUE TITLE
Inaccessible 443 port

### ISSUE THREAD

**Issue by ganlub** [coreos/bugs#1994]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.8.0
VERSION_ID=1353.8.0
BUILD_ID=2017-05-30-2322
PRETTY_NAME="Container Linux by CoreOS 1353.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

DigitalOcean

### Expected Behavior ###

To be able to access via 443 port

### Actual Behavior ###

It's just not working with https, just via port 80.

### Reproduction Steps ###

  1. Create a fresh Droplet
  2. Run `docker run -d -p 80:80 -p 443:443 --name nginx nginx`
  3. Access https://{YOUR_DRROPLET_IP}

### Other Information ###
I also tried checking the open ports with Nmap and nc, but both report it as closed.
I checked the Docs but there's no mention of having to do something special to open certain ports or whatsoever.

**Comment by lucab** [comment]
This is probably due to some network filtering between you and the droplet.
Please check with `sudo docker ps` and `sudo netstat -lptn`, you should see both port in a listening state and reachable via curl (altought the TLS config would be missing). In that case, please double check your network config.

**Comment by ganlub** [comment]
@lucab thanks for your fast response:

Here the outputs:
```
$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                      NAMES
3100da4754ab        nginx               "nginx -g 'daemon off"   35 minutes ago      Up 35 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx
```
```
$ sudo netstat -lptn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0      0 :::80                   :::*                    LISTEN      2276/docker-proxy   
tcp6       0      0 :::22                   :::*                    LISTEN      1/systemd           
tcp6       0      0 :::443                  :::*                    LISTEN      2269/docker-proxy
```
```
$ curl -v https://0.0.0.0
* Rebuilt URL to: https://0.0.0.0/
*   Trying 0.0.0.0...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 0.0.0.0:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 0.0.0.0:443
```
From an external machine:
```
$ curl -v https://46.101.75.127
* Rebuilt URL to: https://46.101.75.127/
*   Trying 46.101.75.127...
* TCP_NODELAY set
* connect to 46.101.75.127 port 443 failed: Connection refused
* Failed to connect to 46.101.75.127 port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 46.101.75.127 port 443: Connection refused
```
Same thing is happening on my local server that's why I tried to reproduce it on a fresh DO Droplet...

**Comment by lucab** [comment]
I was actually wrong, and as @squeed pointed out the explanation of this is much simpler.
Without a proper configuration, the nginx container is only listening on port 80. Port 443 is only being kept open by docker, but inside the container it forward to a closed port. See `nsenter -n -t $(pgrep -o nginx) /usr/bin/netstat -lptn`.

**Comment by squeed** [comment]
Indeed, this isn't a bug, AFAICT - I think it can be closed.
