### ISSUE TITLE
Document HTTP retry strategy

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1995]
# Issue Report #

## Bug ##

Ignition's documentation doesn't describe the retry strategy or how to modify it. We'll need this before we release the 2.1 spec.

**Comment by dgonyeo** [comment]
This doesn't appear to be currently modifiable, since the [parameters are constants in the code](https://github.com/coreos/ignition/blob/master/internal/resource/http.go#L33). Is this something that users should be able to modify?

**Comment by crawford** [comment]
They can modify it with the [parameters right below](https://github.com/coreos/ignition/blob/c3cb45d464d656d51753fc2b80b2ba3f89aedde5/internal/resource/http.go#L37). These are exposed as timeouts in the config.

P.S. Please use immutable URLs (press "y" in GitHub), otherwise they will be broken in the future.
