### ISSUE TITLE
/sysroot is hardcoded in Ignition

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#2000]
# Issue Report #

## Bug ##

Ignition hardcodes `/sysroot` in several locations despite exposing a `--root` flag. This isn't a big deal since almost every Linux distro uses `/sysroot`, but for correctness and testing, the `--root` flag should be respected.

**Comment by arithx** [comment]
Fixed in https://github.com/coreos/ignition/commit/4cc23ba628f7e2adfd2ac5ac923614c916d6a15e
