### ISSUE TITLE
How can I re-import the changed configuration file?

### ISSUE THREAD

**Issue by kongreddgrass** [coreos/bugs#2002]
Since the release of Ignition, i don't know how to re-read the configuration-file as json-file (Ignition format).

In older CoreOS-Versions it was pretty simply to re-read the configuration file as a cloud-init file. I only changed the /var/lib/core-os/user-data. After the reboot, my entered changes have been accepted.

And now? 
If i run coreos-install -i /path/to/ignition/file, he breaks and say he doesnt found the installation-medium.
If i run coreos-cloudinit, he doesn't like the file-format, because it's not a cloud-init format. But we should use now the Ignition format. The documentation is good, but nothing is documented with regard to the import of the configuration file.

Why do you have to change something that went well before?

And how do I get my goal now?

Greetings from Bavaria

**Comment by lucab** [comment]
Ignition only run from initrd on first-boot, and in that case the JSON configuration is cached at `/run/ignition.json`. It doesn't run on subsequent boots, so it won't apply any further change (and the cached config file won't be there). Its purpose is to first-provision a new instance, which can then rely on an immutable configuration/state. If you want to further tweak it at runtime, you should instead look for a configuration management tool.

Please check https://coreos.com/ignition/docs/latest/what-is-ignition.html#ignition-vs-coreos-cloudinit if you want to read more on the design goals of ignition and the differences with cloudinit.
