### ISSUE TITLE
Container Linux Man pages (on the ~web~)

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2006]
### Desired Feature ###

Container Linux doesn't ship man pages! I'm totally okay with that, but it would be nice to be able to access man pages for the specific versions of software present on a given Container Linux version.

Most importantly, projects like `systemd` add flags over time, and viewing the upstream man pages sometime mean I'm viewing features I'm not able to use yet.

This could be implemented by, during the build of Container Linux, generating html man pages and hosting them as part of the Container Linux docs. This would version the man pages correctly for free.

The final bit could be including a stub `man` implementation in container linux which spits out the link to that version's man pages.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
