### ISSUE TITLE
mount points that are configured in systemd -> units don't get auto-mounted

### ISSUE THREAD

**Issue by kfirufk** [coreos/bugs#2007]
# Issue Report #
I think it's a bug

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1437.0.0
VERSION_ID=1437.0.0
BUILD_ID=2017-06-07-2316
PRETTY_NAME="Container Linux by CoreOS 1437.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

it's a PC at home with Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz

### Expected Behavior ###

mount points will be mounted after reboot

### Actual Behavior ###

they don't

### Reproduction Steps ###

```
  "systemd": {
    "units": [
            {
                    "name": "var-lib-rkt.mount",
                    "enable": true,
                    "contents": "[Mount]\nWhat=/dev/sdd1\nWhere=/var/lib/rkt\nType=ext4"
            },
        {
                "name":"mnt-btrfs_storage.mount",
                "enable": true,
                "contents":"[Mount]\nWhat=/dev/disk/by-uuid/12045f15-7283-47ed-b221-7e6fc43a2a2b\nWhere=/mnt/btrfs_storage\nType=btrfs\nOptions=loop,discard"
        },
        {
                "name":"mnt-ssd_storage.mount",
                "enable":true,
                "contents":"[Mount]\nWhat=/dev/sda1\nWhere=/mnt/ssd_storage\nType=ext4"
        },
        .....
```

this is the ignition part where I create the unit files and enable mounting.

specifically the mount points don't start at boot, the rest work. for example I have etcd-member set up and it runs at boot properly.

**Comment by crawford** [comment]
The `"enable": true` configuration has no effect in your config because there is no `[Install]` section in your mount units. I believe you can use something like the following in you units:

```ini
[Install]
WantedBy=local-fs.target
```

**Comment by kfirufk** [comment]
welp.. that didn't do the trick.
I have a file at /etc/systemd/system/mnt-btrfs_storage.mount with the content
```
[Mount]
What=/dev/disk/by-uuid/12045f15-7283-47ed-b221-7e6fc43a2a2b
Where=/mnt/btrfs_storage
Type=btrfs
Options=loop,discard

[Install]
WantedBy=local-fs.target

```
but still it doesn't auto mount the volume.

**Comment by crawford** [comment]
Is that mount unit enabled? You should be able to use `systemctl is-enabled` to verify.

**Comment by kfirufk** [comment]
the result is: static

**Comment by crawford** [comment]
According to [the documentation](https://www.freedesktop.org/software/systemd/man/systemctl.html#is-enabled%20NAME%E2%80%A6), that means that the service has not been enabled. If you've manually made that change to your filesystem after the fact, you'll need to run `systemctl enable mnt-btrfs_storage.mount`.

**Comment by kfirufk** [comment]
ahh.. ok.. setting enable does fixes that. any ideas why ignition didn't enable that by default? i had 'enable' set to 'true' in the ignition configuration file

**Comment by kfirufk** [comment]
thank you! :)
