### ISSUE TITLE
CT does not recognize "source" key

### ISSUE THREAD

**Issue by narunask** [coreos/bugs#2008]
# Issue Report #

```
$ ./ct -version
ct v0.3.1

$ ./ct < storage.yml 
warning at line 6, column 8
Config has unrecognized key: source
{"ignition":{"version":"2.0.0","config":{}},"storage":{"files":[{"filesystem":"root","path":"/etc/hostname","contents":{"source":"data:,","verification":{}},"mode":420,"user":{},"group":{}}]},"systemd":{},"networkd":{},"passwd":{}}

$ cat storage.yml 
storage:
  files:
    - filesystem: root
      path: /etc/hostname
      mode: 420
      contents:
        source: "data:,core1"
```

It seems `CT` is having troubles to reproduce a very basic example from the docs:
https://coreos.com/ignition/docs/latest/examples.html#setting-the-hostname

**Comment by crawford** [comment]
The example to which you are referring is an Ignition Config, which has a different structure than Container Linux Configs. You can refer to the [Container Linux Config examples](https://coreos.com/os/docs/latest/clc-examples.html#storage-and-files) to help.

In your case, you'll want something like the following:

```yaml
storage:
  files:
    - filesystem: root
      path: /etc/hostname
      mode: 420
      contents:
        inline: core1
```

**Comment by narunask** [comment]
Indeed, I got lost in the docs and was looking to the wrong spec (Ignition spec), thanks for the prompt response.
