### ISSUE TITLE
[CoreOS 1409.2.0] SELinux: mount: invalid. Same superblock. Different security settings for (dev mqueue, type mqueue)

### ISSUE THREAD

**Issue by JoelESvensson** [coreos/bugs#2012]
This happened immediately after upgrade to latest stable and I can't start containers anymore

**Comment by lucab** [comment]
This is a benign log entry which typically doesn't impact workloads in such extreme way, see https://github.com/coreos/bugs/issues/1580#issuecomment-292279994 for the full discussion.

I suggest to look into docker logs to see if there any hints about what you are experiencing.

**Comment by JoelESvensson** [comment]
Yes sorry you are probably right. "error creating overlay mount to /var/lib/docker/overlay/2e85d89f62ebf6a13d0c0822ed3bb46704a70b5349a9392e2e27409bdd3d8075/merged: invalid argument" is the error message i'm getting

**Comment by lucab** [comment]
This report would benefit from some more details, for example a `docker info` output, which containers are failing to run, whether this appeared after an update, whether there is custom partitioning/mounting involved in this system.

If you are using a non-ext4 lower filesystem, please be aware of [limitations](https://github.com/moby/moby/blob/v1.13.0-rc4/docs/deprecated.md#backing-filesystem-without-d_type-support-for-overlayoverlay2).

**Comment by JoelESvensson** [comment]
All containers that need host mounts fail to run. I'm not using any custom partitioning. 
This is the `docker info` output:

```
Containers: 22
 Running: 5
 Paused: 0
 Stopped: 17
Images: 46
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.24-coreos
Operating System: Container Linux by CoreOS 1353.8.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.958 GiB
Name: skiftet-new-one.novalocal
ID: 7POO:PTE7:OLLA:Z7UN:KBGN:DAM6:MN4K:QJ7I:EUJK:RHJH:KRLM:ORG3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by lucab** [comment]
Thanks for the feedback. Can you please try reproducing this on a pristine stable machine matching your initial report (1409.2.0), without any further customizations or other containers running? Also can you please provide the docker-client command line to reproduce this (possibly with a public minimal container image)? Also, are there any other relevant logs from docker/containerd/kernel around the error entry?

**Comment by JoelESvensson** [comment]
After further troubleshooting I finally found out that the problem was only indirectly related to the CoreOS upgrade. The real issue was in the container management platform (Rancher) that injects a startup program to all containers with certain attributes, and the server upgrade made the OS restart, which triggered the error. Apologies for taking up for your time!
