### ISSUE TITLE
Need perl in the base system

### ISSUE THREAD

**Issue by val0x00ff** [coreos/bugs#2013]
# Issue Report #

Hello everyone,

I did read that perl is not going to be included in the base system. For guests running on vmware esxi hosts perl is required. If perl is not present guest customization will fail. The following error appears:

ERROR: Guest Customization is not supported on systems not having Perl installed.

Is it possible to include perl in the base OS?

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.8.0
VERSION_ID=1353.8.0
BUILD_ID=2017-05-30-2322
PRETTY_NAME="Container Linux by CoreOS 1353.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"

...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###
vmware ESXi hypervisors

### Expected Behavior ###
Guest customization to be successful

### Actual Behavior ###

localhost ~ # grep -i perl /var/log/vmware-imc/toolsDeployPkg.log 
`ERROR: Guest Customization is not supported on systems not having Perl installed`

## Feature Request ##
Including perl in base OS.

**Comment by lucab** [comment]
> If perl is not present guest customization will fail

According to [VMWare knowledge base](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2109161), they don't support Guest Customization on Container Linux.

We do ship open-vm-tools, which depending on your requirements may fit the case.

**Comment by val0x00ff** [comment]
Well how would I manage to e.g extend the hard drive or hot-add cpu/memory to the guest ?  Having DHCP to assign IP addresses to the guestOS is not always desirable. What if I want to choose between 2 IP addresses?

**Comment by lucab** [comment]
Those look like questions better directed at VMWare support or open-vm-tools upstream ticket system, to see whether they can be supported via `vmtoolsd` (I didn't check if that's already the case) or if there are plans to provide containerized guest tools.

Though, some of those (hotplugging) looks more related to kernel-side support, while others (networking settings) may be done via usual configuration units/files. However, I'm not a VMWare expert so feel free to contact your support endpoint to see what their reccomendations are.

To directly answer your initial question: there are no plans at the moment to ship perl (+ bulk ecosystem) as part of the base OS.

**Comment by val0x00ff** [comment]
Thank you for the insights. I think coreos (guest customization) will be supported by vmware once the perl package is on the base system. I've had the same issue wiith other *nix OS'es which didn't have perl included in the base. Once I installed perl the customization worked flawlessly. I am aware I could install stuff within /opt/ directory but perl wants its shared object files in /lib64 which is type of crypt and read-only mounted. If you guys aren't planning to include perl then I'll have to figure out something else.  

Thanks again for your time.

**Comment by lucab** [comment]
Thanks for the feedback, closing this issue accordingly.
