### ISSUE TITLE
Network goes offline when /run FS fills up

### ISSUE THREAD

**Issue by pctj101** [coreos/bugs#2019]
# Issue Report #
Bug

### Container Linux Version ###

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.2.0
VERSION_ID=1409.2.0
BUILD_ID=2017-06-19-2321
PRETTY_NAME="Container Linux by CoreOS 1409.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

### Environment ###

AWS ap-southeast-1
ami-0365e860

### Expected Behavior ###
I didn't really expect tmpfs /run to fill up

### Actual Behavior ###
Manual reboots necessary.  Disk space "looks" clear after reboot (of course)
Filesystem      1K-blocks    Used Available Use% Mounted on
devtmpfs          3813700       0   3813700   0% /dev
tmpfs             3830904       0   3830904   0% /dev/shm
tmpfs             3830904     376   3830528   1% /run
tmpfs             3830904       0   3830904   0% /sys/fs/cgroup
/dev/xvda9       28056904 5260824  21597028  20% /
/dev/mapper/usr   1007760  653140    302604  69% /usr
tmpfs             3830904       0   3830904   0% /media
/dev/xvda1         130798   41456     89342  32% /boot
tmpfs             3830904       0   3830904   0% /tmp
/dev/xvda6         110576      64    101340   1% /usr/share/oem
tmpfs              766180       0    766180   0% /run/user/500

Jun 22 01:53:41 ip-172-16-193-96 systemd-networkd[731]: Failed to save network state to /run/systemd/netif/state: No space left on device
Jun 22 02:00:40 ip-172-16-193-96 systemd-networkd[731]: Failed to save lease data /run/systemd/netif/leases/2: No space left on device
-- Reboot --
Jun 22 19:31:46 ip-172-16-193-96 systemd-networkd[644]: Failed to save network state to /run/systemd/netif/state: No space left on device
Jun 22 19:36:50 ip-172-16-193-96 systemd-networkd[644]: Failed to save lease data /run/systemd/netif/leases/2: No space left on device
-- Reboot --

### Reproduction Steps ###
Run a container
Run cadvisor

### Other Information ###
EC2 Server suddenly goes off line

**Comment by lucab** [comment]
I seem to understand you are in a DCHP-based network setup. I think that then the problem is that your DHCP lease is expired and can't be renewed due to `/run` being out of space.

Can you try to determine what is filling it up in your case? Also, which kind of EC2 instance is this? If you really need that amount of tmpfs usage, it's worth considering a bigger memory-sized one.

**Comment by pctj101** [comment]
Hi,

Thanks for asking about the memory issue.  I filed these issues separately since they are different servers on different AMI images.

On a totally unrelated server, the same docker image has run into memory usage issues.  However on that 3rd server, there is in fact a log stating such an out of memory condition.

On this server and #2020 I could not locate such an OOM log message.

Does tmpfs reserve "0" space and allow containers to entirely "fill up" ram?

**Comment by lucab** [comment]
> Does tmpfs reserve "0" space and allow containers to entirely "fill up" ram?

I'm not sure about the internals, but indeed I think tmpfs memory is allocated on demand. There is a `size` option for the fs, but that only sets the upper limit.

**Comment by pctj101** [comment]
I'm going to close this issue for now.  I've noticed another machine with memory pressure that has similar problems.  Let's see if a simple tuning of memory usage/capacity solves the issue.
