### ISSUE TITLE
1409.5.0, xencenter, unable to boot, 

### ISSUE THREAD

**Issue by hawliczek** [coreos/bugs#2023]
# Issue Report #
How can I get some Information about the failed boot of the passive partition?

there are some 1353.8.0 machines on xenserver.
Update to 1409.x hangs: update is downloaded and reboots, but the machine hangs. reboot again brings up the 1353.8 again.
i disabled the automatic download and disabled locksmithd, so the machines don´t reboot and hang any more.

I read about the disk layout (https://coreos.com/os/docs/latest/sdk-disk-partitions.html).

How can I get some Information of the boot that fails?

I downloaded the isof the current alpha, beta and production and even booting from cd-rom on a new virtual machine in xen-center causes the error.
There are four xen-server with this issue.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.8.0
VERSION_ID=1353.8.0
BUILD_ID=2017-05-30-2322
PRETTY_NAME="Container Linux by CoreOS 1353.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

xenserver 7.0 (corrected)

### Expected Behavior ###
coreos system reboots, update should be take place, prompting for login.

### Actual Behavior ###
systems hangs in startup porcess, seems to be an error with networkd.
even booting from cd/iso brings system into the same error

### Reproduction Steps ###
booting the virtual-machine from cd-rom/coreos-iso

**Comment by euank** [comment]
The guest console output would be helpful.

The version of Xen might also be relevant since it's possible this is a bug on their end.

**Comment by hawliczek** [comment]
![grafik](https://user-images.githubusercontent.com/13299180/27641456-20268c6c-5c1c-11e7-80f5-e05f897c77b7.png)

its xenserver 7.0 

XenServer build date: 2016-12-19
XenServer build number: 125380c
XenServer version 7.0

2016-12-19

**Comment by euank** [comment]
@hawliczek I suspect this issue is a duplicate of #1849, which turned out to be a bug in XenServer. Updating your XenServer to include [this hotfix](https://support.citrix.com/article/CTX222423) should fix it.

**Comment by hawliczek** [comment]
thanks, i will try this
