### ISSUE TITLE
Support etcdctl v3

### ISSUE THREAD

**Issue by shamalco** [coreos/bugs#2024]
Hi,

I just was told CoreOS currently doesn't ship with etcdctl v3, only 2.3.7. I tried to to pass `export ETCDCTL_API=3` but it didn't work. Is there a workaround?

It important to support etcdctl v3 especially etcd2 will be removed by June next year, and most customers and documentation today are etcd3 clusters.

**Comment by bgilbert** [comment]
Duplicate of https://github.com/coreos/bugs/issues/1717.  We're currently hoping to support this through torcx.

**Comment by lucab** [comment]
(Closing as a duplicate of #1717)
