### ISSUE TITLE
Output full system logs to non-interactive consoles

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#203]
Cloud providers like EC2 and GCE provide output from system's console but no interactive use. Since the console on these systems is logging-only we might as well enable full logging from the journal to the console on these platforms.

Question: do we need to be concerned about what gets logged to these consoles? It is possible sensitive information may get logged so we need to be confident that access to the log reasonably protected by the provider.

**Comment by crawford** [comment]
This has already been enabled on EC2 and Azure.
