### ISSUE TITLE
coreos-metadata support for Oracle Cloud

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2034]
# Issue Report #

### Environment ###

Oracle Cloud

### Desired Feature ###

- [ ] Environment variables
- [ ] Hostname
- [x] SSH keys
- [ ] Network unit generation for VNICs

**Comment by bgilbert** [comment]
Initial support done in 0.13.0.

**Comment by dgonyeo** [comment]
On the list of desired features:
- **Environment variables**: we have some supported attributes now
- **Hostname**: not something we can get at this point from OCI
- **SSH Keys**: done
- **Network unit generation for VNICs**: not something we can sanely do for the user (do they want another interface on the host or in a container?)

I think this is as done as it can get.
