### ISSUE TITLE
New image type for Oracle Cloud

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2035]
# Issue Report #

### Environment ###

Oracle Cloud

### Desired Feature ###

- [x] New OEM
- [x] New image format in `vm_image_util.sh`
- [x] Add format to Jenkins
- [ ] Upload image to Oracle cloud as release artifact
- [ ] Add documentation page to website (https://github.com/coreos/bugs/issues/2199)

**Comment by euank** [comment]
This is being added to the 1548.0.0 tracker specifically for the following two bullet points.

- [ ] Add format to Jenkins
- [ ] Upload image as a release artifact

Without mantle support (https://github.com/coreos/mantle/issues/649) or documentation this won't be "officially supported", but having it in the release bucket anyways is helpful for Oracle to validate it.
