### ISSUE TITLE
rpc-statd.service not started on boot while enabled

### ISSUE THREAD

**Issue by gstorme** [coreos/bugs#2038]
# Issue Report #
### Container Linux Version ###
```
Container Linux by CoreOS 1409.5.0 (Ladybug)
```

### Environment ###
VMWare ESXi

### Expected Behavior ###
The rpc-statd service is enabled, and started upon boot

### Actual Behavior ###
The rpc-statd is not started automatically, while it is enabled.

### Reproduction Steps ###

Provide a transpiled CLC as guestinfo in the vmx, with a systemd part to enable the rpc-statd service
```
  "systemd": {
    "units": [
      {
        "name": "rpc-statd.service",
        "enable": true
      }
    ]
```

The service is enabled correctly upon provisioning the VM:
```
Jul 01 11:05:30 localhost ignition[464]: files: op(9): [started]  processing unit "rpc-statd.service"
Jul 01 11:05:30 localhost ignition[464]: files: op(9): [finished] processing unit "rpc-statd.service"
Jul 01 11:05:30 localhost ignition[464]: files: op(a): [started]  enabling unit "rpc-statd.service"
Jul 01 11:05:30 localhost ignition[464]: files: op(a): [finished] enabling unit "rpc-statd.service"
```

And systemctl status shows the service is enabled:
```
● rpc-statd.service - NFS status monitor for NFSv2/3 locking.
   Loaded: loaded (/usr/lib/systemd/system/rpc-statd.service; static; vendor preset: enabled)
   Active: inactive (dead)
```

However, the service does not start unless started manually.

### Other Information ###

When not using the systemd unit part in the CLC, but enabling the rpc-statd service manually with systemd, the following error is returned:

```
master01 core # systemctl enable rpc-statd
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.
```

This is also the case when you have already used a CLC with systemd unit to enable the service anyway.
I followed the docs from https://coreos.com/os/docs/latest/mounting-storage.html for this.

When using a cloud-config file the service is started upon boot, because cloud-config executes on each boot.
```
coreos:
  units:
    - name: rpc-statd.service
      command: start
      enable: true
```

**Comment by gstorme** [comment]
When actually having a systemd unit for the NFS mount, the rpc-statd service does start correctly on boot.

```
systemd:
  units:
    - name: rpc-statd.service
      enable: true

    - name: mnt-data.mount
      enable: true
      contents: |
        [Mount]
        What=x.x.x.x:/k8s_poc
        Where=/mnt/data
        Type=nfs
        [Install]
        WantedBy=multi-user.target
```

**Comment by gstorme** [comment]
When the goal is to use NFS for persistent volumes in kubernetes, the rpc-statd service should be able to start without having to mount a nfs on coreos. Right?

**Comment by bgilbert** [comment]
The `systemctl enable` error is correct and the Mounting Storage page is wrong.  `rpc-statd.service` is not designed to be enabled separately (also indicated by `static` in the `systemctl status` output), but will be started automatically by the NFS mount unit.  You can delete the `rpc-statd.service` lines from your CLC.

Re https://github.com/coreos/bugs/issues/2038#issuecomment-312733156, do you need rpc.statd to be running without NFS volumes mounted?

**Comment by gstorme** [comment]
Ok.
What if there is no NFS mount unit but you want to use kubernetes persistent volumes on NFS? Kubernetes will mount the volume, not CoreOS.

**Comment by bgilbert** [comment]
It should still work.  What actually happens is that the `mount` command runs `mount.nfs`, which runs `/usr/sbin/start-statd` if rpc.statd is needed, and `start-statd` runs `systemctl start rpc-statd.service`.

**Comment by gstorme** [comment]
When the rpc-statd service is not started, this error occurs when using a nfs pv:

```
MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: x.x.x.x:/k8s_poc /var/lib/kubelet/pods/92d1717c-6042-11e7-af75-005056981d91/volumes/kubernetes.io~nfs/nfs nfs [] 
Output: mount.nfs: rpc.statd is not running but is required for remote locking. mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: an incorrect mount option was specified
Error syncing pod
```

When I start the rpc-statd service manually, it works.
Kubernetes version: v1.7.0+coreos.0

**Comment by euank** [comment]
So, my suspicion is that the problem comes from kubelet-wrapper's `/usr/sbin/start-statd` being used since that's where the `mount` call is being made.

The hyperkube copy of `/usr/sbin/start-statd` looks like (on tag `v1.7.0_coreos.0`):

```sh
#!/bin/bash -p
# ...
PATH=/sbin:/usr/sbin
exec rpc.statd --no-notify
```

So the `start-statd` in hyperkube doesn't currently end up triggering the systemd service... but that's a gotcha to watch out for in hyperkube updates; once it updates to a newer debian base image, it's possible that'll call systemctl as the host one does

Attempting to run `rpc.statd` from within the chroot (via `rkt enter $hyperkube-id`) on one of my nodes gives me the following (note: hyperkube 1.5.7 since that's what I had lying around):

```
# rpc.statd --no-notify -F -d 
rpc.statd: Version 1.2.8 starting
rpc.statd: Flags: No-Daemon Log-STDERR TI-RPC 
rpc.statd: Failed to read /var/lib/nfs/state: Success
rpc.statd: Initializing NSM state
rpc.statd: Local NSM state number: 3
rpc.statd: Failed to unregister program 100024, version 1
rpc.statd: Effective UID, GID: 106, 65534
rpc.statd: Failed to register (statd, 1, udp)
rpc.statd: Failed to register (statd, 1, tcp)
rpc.statd: Failed to register (statd, 1, udp6)
rpc.statd: Failed to register (statd, 1, tcp6)
rpc.statd: failed to create RPC listeners, exiting
```

I suspect this is the issue. It seems to me that ultimately hyperkube's nfs mounting logic should use the rpc.statd on the host, not the one shipped in the debian image..

The easiest workaround for this issue is probably to add a wants/requires dependency on `rpc-statd.service` for `kubelet.service` while we figure out a more appropriate fix for the underlying issue.

cc @aaronlevy wrt hyperkube stuff and because we chatted about this.

**Comment by gstorme** [comment]
I can confirm that adding a Wants=rpc-statd.service to the kubelet.service is a working workaround.
Thanks

**Comment by euank** [comment]
I've created a followup for the hyperkube-specific issue: https://github.com/coreos/bugs/issues/2074

This bug, not being able to enable `rpc-statd`, is working as intended.
it's kubelet-wrapper/hyperkube not starting rpc-statd correctly that's broken.

Thanks for reporting this!
