### ISSUE TITLE
Please bring "hybla" congestion control algorithm into coreos kernel

### ISSUE THREAD

**Issue by HouzuoGuo** [coreos/bugs#2045]
# Issue Report #

### Environment ###

CoreOS stable on GCE

### Desired Feature ###

Hybla is a specialised congestion control algorithm optimised for long RTT.

Amazon Linux has it compiled into the kernel but CoreOS does not yet have it. So consider bringing it into kernel to make CoreOS even more versatile.

**Comment by bgilbert** [comment]
This is done (https://github.com/coreos/coreos-overlay/issues/2662) and should be included in 1492.0.0.

**Comment by HouzuoGuo** [comment]
many thanks!
