### ISSUE TITLE
dracut uses broken mechnism of parsing "ip=" parameter

### ISSUE THREAD

**Issue by rozcietrzewiacz** [coreos/bugs#2046]
# Issue Report #

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.1.0
VERSION_ID=1409.1.0
BUILD_ID=2017-05-23-2225
PRETTY_NAME="Container Linux by CoreOS 1409.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="arm64-usr"
```

### Environment ###

Booting via iPXE under Qemu. Trying to set MAC address for an interface using kernel cmdline (dracut). According to [dtacut.cmdline(7)](http://man7.org/linux/man-pages/man7/dracut.cmdline.7.html), there are two formats that should allow this:

```
ip=<interface>:{dhcp|on|any|dhcp6|auto6}[:[<mtu>][:<macaddr>]]
```
and
```
ip=<client-IP>:[<peer>]:<gateway-IP>:<netmask>:<client_hostname>:<interface>:{none|off|dhcp|on|any|dhcp6|auto6|ibft}[:[<mtu>][:<macaddr>]]
```

### Expected Behavior ###

Be able to set the MAC address using either of the syntax options, including variations resulting from optional parameters.

### Actual Behavior ###

Neither format works properly. It seems the dracut version used by ContainerOS is one that 
was [reported to have this functionality broken back in 2015](https://bugzilla.redhat.com/show_bug.cgi?id=1271656). My tests match what was reported there (the only usable syntax is a variation that involves static IP setting).

### Other Information ###
- Red Hat bug report from 2015: https://bugzilla.redhat.com/show_bug.cgi?id=1271656 - apparently fixed in 2016 in RH version `dracut-033-450.el7`

**Comment by dm0-** [comment]
Dracut does not configure the network of a fully booted system.  You need to use Ignition to write `.network` files appropriately.

https://coreos.com/ignition/docs/latest/
https://www.freedesktop.org/software/systemd/man/systemd.network.html

The `ip=` argument is used to configure the network in the initramfs (mostly just for non-DHCP systems), only for setting up the connection for Ignition to download remote configuration files.  In that case, MAC address should be defined correctly.

https://github.com/coreos/bootengine/blob/master/dracut/03coreos-network/parse-ip-for-networkd.sh#L77

**Comment by rozcietrzewiacz** [comment]
@dm0- : I understand how the booting process works, but I don't understand why you closed this issue. The way I see it is that dracut has this bug, which doesn't allow to use set MAC address, when your setup requires that you
 1. use DHCP and
 2. have a proper MAC address set
in order to download the ignition files.

That, it seems, is not possible with the broken dracut.

**Comment by dm0-** [comment]
I just booted with `ip=eth0:dhcp::12-34-56-78-90-AB rd.break`, and it seems to work fine for me.

    switch_root:/# cat /etc/systemd/network/10-dracut-cmdline-99.network
    [Match]
    Name=eth0
    [Link]
    MACAddress=12-34-56-78-90-AB
    [Network]
    DHCP=yes
    [Address]
    [DHCP]
    switch_root:/# ip addr show dev eth0
    2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP gr
    oup default qlen 1000
        link/ether 12:34:56:78:90:ab brd ff:ff:ff:ff:ff:ff
