### ISSUE TITLE
Add platform option to terraform-provider-ct

### ISSUE THREAD

**Issue by dghubble** [coreos/bugs#2049]
## Feature Request

The container-linux-config-transpiler added a new platform-specific templating feature as part of a change some time ago that removed `ConvertAs2_0_0(cfg)` and added `ConvertAs2_0(cfg, platform)` (please add to changelog). I believe the intent is that the valid variables a user can write in the Container Linux Config vary by platform and only get substituted if the correct platform name is provided. As a default, "" is used to specify no templating.

If that all checks out, we'd like make that feature usable in `terraform-provider-ct` via a platform option? cc @crawford @dgonyeo 

## Related

* https://github.com/coreos/terraform-provider-ct/pull/9
* https://groups.google.com/forum/#!topic/coreos-user/7BC7Th4X1pY

**Comment by dghubble** [comment]
Hm, Derek is OOO

**Comment by crawford** [comment]
That all sounds good. Does terraform provide that info for us at runtime?

**Comment by dghubble** [comment]
Since the terraform-provider-ct tool just converts Container Linux config files to Ignition config files, I think we'd ask users to pass along that information:

```
data "ct_config" "controller" {
  pretty_print = false
  provider = "ec2"    <- new
  content      = "${file("controller.yaml")}"
}
```

**Comment by crawford** [comment]
Wouldn't Terraform already know that though? It knows where it's deploying the plan. It seems silly and error-prone to ask the user to specify that twice.

**Comment by dghubble** [comment]
It doesn't. Terraform modules have a set of inputs and outputs. Our module simply takes container linux configs (from a string, read from a file by the file module, or output from another module) and converts it to an Ignition config as an output (for consumption by other modules, output to disk, whatever people want). The same output Ignition config could be used in EC2 user-data or in GCE user-data. It'd be up to the user to prepare, there is no state that keeps track of the intended use.

Modules are more akin to individual programs piped together.

**Comment by dghubble** [comment]
Requires https://github.com/coreos/terraform-provider-ct/pull/9
