### ISSUE TITLE
JSON Release Feed Enhancement Request

### ISSUE THREAD

**Issue by arg0nik** [coreos/bugs#2050]
Hello,

We are currently using CoreOS in our environment and need to integrate CVE/security fixes as part of our compliance program. CVE fix information is found on the releases page, which also has a link to a JSON feed (requested here https://github.com/coreos/bugs/issues/1020):
https://coreos.com/releases/releases.json

My request is to please format the release notes piece of the JSON in such a way that the CVE ID can be programmatically read without needing to parse through the "release_notes" string. Thank you!

**Comment by greenage** [comment]
(The regex to do this in a program is pretty simple, just thought it would be useful for quickly ingesting -- closing).

**Comment by euank** [comment]
@greenage sorry for not responding, this slipped off my radar.

You're right that we should have something better.
We've wanted to have a proper advisories page for listing CVEs for a while, which would presumably have a programmatically usable interface and would hopefully better solve this issue.

For now, just regexing out CVEs yourself is probably the best option.

**Comment by greenage** [comment]
@euank not a problem. An advisories source would be fantastic. I imagine once security vendors (specifically vulnerability scanning tools) catch up, you will get similar asks. Thanks!

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
