### ISSUE TITLE
Omitting `version:` in Container Linux configuration `flannel:` section breaks flannel

### ISSUE THREAD

**Issue by zultron** [coreos/bugs#2051]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.6.0
VERSION_ID=1409.6.0
BUILD_ID=2017-07-06-0128
PRETTY_NAME="Container Linux by CoreOS 1409.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

DigitalOcean

### Expected Behavior ###

The `version:` key may be omitted from the Container Linux configuration `flannel:` section.

### Actual Behavior ###

Omitting `version:` in Container Linux configuration `flannel:` section breaks flannel, producing a dropin with the line `Environment="FLANNEL_IMAGE_TAG=v<nil>"`.

### Reproduction Steps ###

  1. Create a Container Linux configuration with a filled-out `flannel:` section, but omitting the `version:` key
  2. Convert to ignition config and bootstrap machine
  3. Observe that the `flanneld.service` unit failed with `systemctl status flanneld.service`
  4. Observe the bogus `FLANNEL_IMAGE_TAG` line with `systemctl cat flanneld.service`

**Comment by crawford** [comment]
Which version of CT are you using? I believe this is fixed in the latest version.

**Comment by zultron** [comment]
CT v0.3.1 from this page, dated May 4th:
https://github.com/coreos/container-linux-config-transpiler/releases/

**Comment by crawford** [comment]
Nope, not fixed.

```
$ echo 'flannel: ~' | ct --pretty
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "storage": {},
  "systemd": {
    "units": [
      {
        "name": "flanneld.service",
        "enable": true,
        "dropins": [
          {
            "name": "20-clct-flannel.conf",
            "contents": "[Service]\nEnvironment=\"FLANNEL_IMAGE_TAG=v\u003cnil\u003e\"\nExecStart=\nExecStart=/usr/lib/coreos/flannel-wrapper $FLANNEL_OPTS"
          }
        ]
      }
    ]
  },
  "networkd": {},
  "passwd": {}
}
```

**Comment by AlexNPavel** [comment]
I fixed it in this pull request from a week ago. Forgot to merge: https://github.com/coreos/container-linux-config-transpiler/pull/88

**Comment by crawford** [comment]
@zultron we've released [v0.4.0](https://github.com/coreos/container-linux-config-transpiler/releases/tag/v0.4.0) with the fix.

**Comment by zultron** [comment]
It works!  Thanks @AlexNPavel and @crawford.

One nit with at least `ct-v0.4.0-x86_64-unknown-linux-gnu`:
```
$ ct -version
ct was not built properly
```

**Comment by crawford** [comment]
Uh oh. We'll have to do another release to fix that. Thanks for the heads-up!
