### ISSUE TITLE
ct repo has a lot of unused code

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#2052]
## Bug ##

CT's codebase has, for example, go-systemd which is unused.

**Comment by ajeddeloh** [comment]
`go-systemd` is used as part of ignition for systemd unit validation. `glide-vc` should be cleaning up any unused transient dependencies. I'm generally unaware of any large swaths of dead code; was there something else you were thinking of.

**Comment by crawford** [comment]
This may have been before glide was in use. Probably can be closed now.
