### ISSUE TITLE
wipeFilesystem == false doesn't work with VFAT

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2055]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.0.0
VERSION_ID=1465.0.0
BUILD_ID=2017-07-06-0206
PRETTY_NAME="Container Linux by CoreOS 1465.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

AWS

### Expected Behavior ###

Ignition never wipes an existing filesystem when `wipeFilesystem` is false.

### Actual Behavior ###

When creating a VFAT filesystem, Ignition ignores `wipeFilesystem`.

### Reproduction Steps ###

1.
```json
{
  "ignition": {
    "version": "2.1.0"
  },
  "storage": {
    "filesystems": [
      {
        "mount": {
          "device": "/dev/disk/by-partlabel/OEM",
          "format": "vfat",
          "wipeFilesystem": false,
          "label": "OEM"
        }
      }
    ]
  }
}
```
2. Wonder where your OEM partition went.

### Other Information ###

We probably shouldn't trust mkfs implementations to correctly test for existing filesystems.  Instead, we should do those checks ourselves with the existing blkid functions, then unconditionally pass the force flag to all mkfs tools if we do decide to run them.  That would also address https://github.com/coreos/bugs/issues/1977.

**Comment by crawford** [comment]
https://github.com/coreos/ignition/commit/fa650ba72cb4127910e1664ab85205c4d0df244b#diff-55db92a37bfccfb3bdf4141c68889e7fR358
