### ISSUE TITLE
VM crashes after doing reboot now

### ISSUE THREAD

**Issue by vmStiwa** [coreos/bugs#2057]
We are using ESX 6.0 with CoreOs (1409.6.0).
After (nearly) every "reboot now" the VM crashes with following error:
![bugscreenshot](https://user-images.githubusercontent.com/30287784/28362817-440431d0-6c7e-11e7-92b1-598da82c59e2.PNG)

We also tried to repair the filesystem with fsck-commands.

**Comment by crawford** [comment]
Can you hit enter and look for failures in the logs? The screenshot you provided doesn't actually show the root of the failure (the fsck failure is being ignored).

**Comment by bgilbert** [comment]
Closing due to lack of response.  If you can provide the requested information, please feel free to reopen.
