### ISSUE TITLE
Ignition doesn't write to the correct filesystem 

### ISSUE THREAD

**Issue by arithx** [coreos/bugs#2059]
# Issue Report #

### Version ###

Master

### Expected Behavior ###

File is written to the correct filesystem

### Actual Behavior ###

File is written to the root filesystem

### Reproduction Steps ###

Config:
```
{
        "ignition": {"version": "2.0.0"},
        "storage": {
                "filesystems": [{
                        "mount": {
                                "device": "/dev/mapper/loop0p1",
                                "format": "ext4",
                                "create": {
                                        "force": true
                                }},
                         "name": "test"}],
                "files": [{
                        "filesystem": "test",
                        "path": "/ignition/test",
                        "contents": {"source": "data:,asdf"}
                }]}
}
```

### Other Information ###

It looks like when we refactor'd the files stage to include the new Fetcher we removed the instantiation of a new utility that pointed the DestDir at the newly created mount point. See link below.

https://github.com/coreos/ignition/commit/8f6e802753404e5bac805cb46054243fe72005ab#diff-14bf0cdab0fa5f8140f06f308e1bca14L308

I've tested a fix locally against filesystems to add back the following lines:
```
        u := util.Util{
                Logger:  s.Logger,
                DestDir: mnt,
                Fetcher: s.Util.Fetcher,
        }
```

**Comment by crawford** [comment]
@arithx That was exactly the issue. Nice find.
