### ISSUE TITLE
Ignition ignores force flag when recreating filesystem of the same type

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2061]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1478.0.0+2017-07-18-1921
VERSION_ID=1478.0.0
BUILD_ID=2017-07-18-1921
PRETTY_NAME="Container Linux by CoreOS 1478.0.0+2017-07-18-1921 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

QEMU

### Expected Behavior ###

Ignition always creates a filesystem when `force` is true.

### Actual Behavior ###

Ignition does not create a filesystem if the partition already has a filesystem of the same type.

### Reproduction Steps ###

  1.
```
{
  "ignition": {
    "version": "2.0.0"
  },
  "storage": {
    "filesystems": [
      {
        "mount": {
          "device": "/dev/disk/by-partlabel/OEM",
          "format": "ext4",
          "create": {
            "force": true,
            "options": [
              "-L", "OEM"
            ]
          }
        }
      }
    ]
  }
}
```
  2. `ls /usr/share/oem`

### Other Information ###

Ignition says:

```
Jul 19 20:19:16 localhost ignition[365]: disks: createFilesystems: filesystem at
 "/dev/disk/by-partlabel/OEM" is already formatted. Skipping mkfs...
```

I have a kola patch that catches this, but will hold off on PRing it until the bug is fixed.

**Comment by arithx** [comment]
I've added a test for both force options as well as wipeFilesystems on disks of the same type to the ignition blackbox tests as well.

**Comment by arithx** [comment]
Fix worked for my blackbox tests. Will manually test in the morning.
