### ISSUE TITLE
Custom docker bridge network issue

### ISSUE THREAD

**Issue by vadimi** [coreos/bugs#2068]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.7.0
VERSION_ID=1409.7.0
BUILD_ID=2017-07-19-0005
PRETTY_NAME="Container Linux by CoreOS 1409.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
- Amazon EC2.

### Expected Behavior ###
It should be possible to run docker containers on a custom bridge network.

### Reproduction Steps ###

1. Run the following commands to create new docker network:

```
docker network create \
  --driver=bridge \
  --subnet=9.0.15.128/25 \
  --gateway=9.0.15.129 \
  -o "com.docker.network.bridge.name"="d-dcos" \
  -o "com.docker.network.bridge.enable_icc"="true" \
  -o "com.docker.network.bridge.enable_ip_masquerade"="true" \
  -o "com.docker.network.bridge.host_binding_ipv4"="0.0.0.0" \
  dcos2
```
2. Check `ip addr` of newly created network interface:
```
190: d-dcos: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default                                   
link/ether 02:42:16:77:78:75 brd ff:ff:ff:ff:ff:ff                                                                            
 inet 9.0.15.129/25 scope global d-dcos                                                                                            
 valid_lft forever preferred_lft forever 
```
3. Run a container:
`docker run --rm --network=dcos2 busybox nslookup google.com`

4. Check `ip addr` of `d-dcos` network interface:
```
190: d-dcos: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default                                  
 link/ether 02:42:16:77:78:75 brd ff:ff:ff:ff:ff:ff                                                                            
 inet6 fe80::42:16ff:fe77:7875/64 scope link                                                                                       
  valid_lft forever preferred_lft forever 
```
**inet** address is missing. After that all containers I run do not receive any traffic and cannot do outbound connections.

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

**Comment by dm0-** [comment]
If you're making new interfaces, you need to tell networkd to not configure them.  Copy `/run/systemd/network/50-docker.network` or `/usr/lib/systemd/network/50-docker.network` into `/etc/systemd/network`, add your bridge name, and run `systemctl restart systemd-network`.  This fixed it in a quick test.

**Comment by vadimi** [comment]
it worked, thanks
