### ISSUE TITLE
Increased TCP errors on libvirt/virtio-net + Container Linux alpha (kernel 4.12.2)

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2076]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1478.0.0
VERSION_ID=1478.0.0
BUILD_ID=2017-07-19-0038
PRETTY_NAME="Container Linux by CoreOS 1478.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

libvirt using the default network libvirt provides + the qemu image.

### Expected Behavior ###

Downloading files from the us-east-1 s3 buckets doesn't have any significant number of tcp errors

### Actual Behavior ###

I reliably get tcp errors and slow download speeds when compared to stable.

### Other Information ###

I'm in the process of doing a git bisect of the kernel, we'll see what I find.

**Comment by mer-at** [comment]
made the same observation, when moving one of my kvm guests to 4.12.4 (4.13-rc2 affected too)
absolutely sluggish nfs performance, hat to revert back to 4.11

**Comment by euank** [comment]
I've bisected it to https://github.com/torvalds/linux/commit/680557cf79f8

There's an ongoing thread on netdev which matches what I'm seeing as well: https://www.spinics.net/lists/netdev/msg446206.html

**Comment by euank** [comment]
Per above we've applied a patch to our kernel which resolves this issue. It should be fixed in the upcoming alpha release.
