### ISSUE TITLE
criu in coroes

### ISSUE THREAD

**Issue by giper45** [coreos/bugs#2086]
## Feature Request ##
criu in coreos
### Environment ###
Virtualbox

### Desired Feature ###
Add criu to default coreos packages (stable or alpha channel)

### Other Information ###
Criu is a live-migration tool that allows to checkpoint/restore containers. It works with docker if experimental mode is enabled. Coreos is a perfect OS to use Docker, so I'm trying to use criu in coreos, but unfortunately I've discovered that criu is not integrated in coreos default binary packages, but it can be installed only inside /bin/toolbox.

To use it I've to follow a little complex steps: 

```
# enter in toolbox
/bin/toolbox

 # install criu in toolbox
 dnf -y install criu

#copy criu from toolbox a home/core/bin inside coreos
cp /usr/sbin/criu /media/root/home/core/bin/
# copy shared objects used by criu
 cp /usr/lib64/libprotobuf-c.so.1 /media/root/home/core/lib64/  
 cp /usr/lib64/libnl-3.so.200 /media/root/home/core/lib64/
 cp /usr/lib64/libnet.so.1 /media/root/home/core/lib64/

# load config directory for linker
sudo ldconfig /home/core/lib64/

# Set /home/core/bin in PATH variable and update system environment variables
export PATH=$PATH:/home/core/bin/
sudo systemctl set-environment PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/core/bin/
# Set docker experimental 
sudo mkdir /etc/docker
echo "{\"experimental\": true}" >> daemon.json
sudo mv daemon.json /etc/docker
# restart docker 
sudo systemctl restart docker
```

It would be nice if criu was installed by default.
Thanks in advance!

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
