### ISSUE TITLE
VMware has released open-vm-tools version 10.1.10

### ISSUE THREAD

**Issue by oliverkurth** [coreos/bugs#2087]
VMware has released open-vm-tools version 10.1.10. Pleae update in CoreOS.

https://github.com/vmware/open-vm-tools/releases/tag/stable-10.1.10

Thanks!

**Comment by dm0-** [comment]
It is in the current alpha.  https://coreos.com/releases/#1492.0.0

**Comment by oliverkurth** [comment]
Awesome, thank you!
