### ISSUE TITLE
Multiple runs of igniton

### ISSUE THREAD

**Issue by gappan** [coreos/bugs#2090]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.8.0
VERSION_ID=1353.8.0
BUILD_ID=2017-05-30-2322
PRETTY_NAME="Container Linux by CoreOS 1353.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
AWS - Xen

We tried to have a sane default image of coreos(with certain settings like ntp configured using ignition)  and use that as our base image for our applications. 
Came across this issue https://github.com/coreos/bugs/issues/1291 which mentions that deleting `/etc/machine-id` will trigger systemd first boot action. Hence we deleted the `/etc/machine-id` and saved the image.
We planed to use the above saved base core os image and on top of that  we wanted to execute its own specific ignition configs but the `coreos-cloudinit` never ran the ignition files and it was throwing `Detected an Ignition config. Exiting...`. 
Is it not possible to run ignition twice?

**Comment by crawford** [comment]
Ignition is designed to only [run once](https://coreos.com/ignition/docs/latest/what-is-ignition.html#ignition-only-runs-once). We wanted to make it very clear that this is a provisioning tool and not a general configuration management tool.

Your use case however, seems pretty reasonable. In order to trick Ignition into running a second time, you'll want to `touch /boot/coreos/first_boot` in addition to removing `/etc/machine-id`. Ignition will run if that file is present. Once Ignition successfully completes, it will remove the flag.

**Comment by euank** [comment]
Can you detail what you mean by "sane default image of coreos"?

Perhaps we should apply those changes to the distro so you won't have to do whatever modifications these are.

**Comment by gappan** [comment]
@crawford tried touching the file `/boot/coreos/first_boot`with `-rwxr-xr-x. 1 root root ` . Ignition did not trigger and also this file still existed after the boot. Also as earlier removed the `/etc/machine-id` as well. Anything I am missing here? 

@euank: It is more specific to our org. Eg: configuring the ntp server in `timesyncd`. Reason being, AWS user-data file has a size limit. Hence we wanted to have a base image which could have all the general configurations required for our apps. And create our apps on top of that base image and use ignition for provisioning our apps.

**Comment by bgilbert** [comment]
The `/boot/coreos/first_boot` trick only works with images initially provisioned with Container Linux 1367.5.0 or above.  On older systems you can get the same result by running `sgdisk -U 00000000-0000-0000-0000-000000000001 /dev/xvda` (and also removing `/etc/machine-id`), but please consider updating to a current Container Linux release instead.

Ignition's config append and replace facilities are [intended to address](https://coreos.com/ignition/docs/latest/examples.html#replace-the-config-with-a-remote-config) exactly this kind of size limit.  There are a couple possibilities:

1. Upload your entire Ignition config to S3, and pass a stub Ignition config in userdata that uses `ignition.config.replace`.  
2. Continue to pass your application configs in userdata, and use `ignition.config.append` to include your base Ignition config from a well-known URL.

**Comment by gappan** [comment]
Updated my Container Linux release and it worked ! Thanks a bunch for the replies.

**Comment by seh** [comment]
After removing the _first_boot_ file and rebooting, Ignition runs again, but it seems that systemd units enabled on this second boot don’t get started.

The documentation [here](https://coreos.com/ignition/docs/latest/getting-started.html#enabling-systemd-services) mentions the special enabling behavior on first boot. Is deleting that aforementioned file and tricking Ignition into running again not enough to summon this “first boot” behavior again?

**Comment by seh** [comment]
I asked a related question about forcing Ignition to run again [here](https://github.com/coreos/bugs/issues/2090#issuecomment-388195088).

**Comment by seh** [comment]
I noticed something odd: If you run the following before the second boot,
```
sudo touch /boot/coreos/first_boot
sudo rm /etc/machine-id
```
systemd **units** defined via Ignition before that second boot do get enabled, but systemd **drop-ins** for existing units that had been disabled do not get enabled. Ignition reports that it's enabling the latter unit for which it's adding a drop-in, but subsequent inspection via _systemctl status_ shows the unit still disabled, and its "vendor preset" status is also still disabled.

Do you know why that behavior is inconsistent?
