### ISSUE TITLE
containerd should be restarted when it crashes

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2096]
The current `containerd.service` we ship does not have a `Restart` directive. We've observed numerous containerd crashes where that directive would have allowed it to recover correctly.

**Comment by ajeddeloh** [comment]
Is there specific case that causes containerd to crash where the restart lets it recover? It would be nice for testing if there was a easy to repro case.

**Comment by bgilbert** [comment]
Fixed in https://github.com/coreos/coreos-overlay/pull/2703.
