### ISSUE TITLE
Docker ps hangs when DOCKER_HOST is not defined with 1.12.5, ubuntu 16.04

### ISSUE THREAD

**Issue by avidane1** [coreos/bugs#2097]
Running docker 1.12.5 on Ubuntu 16.04, I observe the following behaviour. Normally when DOCKER_HOST is not defined I just get a message asking if docker daemon is running but not in this case where **docker ps** just hangs forever, but works ok after I define DOCKER_HOST.

```
avidan@ua08cfdd0533f5967f734:~$ docker --version
Docker version 1.12.5, build 7392c3b
avidan@ua08cfdd0533f5967f734:~$ env | grep DOCKER
avidan@ua08cfdd0533f5967f734:~$ docker ps -n 1
^C
avidan@ua08cfdd0533f5967f734:~$ export DOCKER_HOST=tcp://localhost:4243
avidan@ua08cfdd0533f5967f734:~$ docker ps -n 1
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by euank** [comment]
This issue tracker is for Container Linux and some other CoreOS projects.
Since you're not running Container Linux, you'd probably find better support on either one of Ubuntu's issue trackers / forums, or with the moby project itself (though docker 1.12.5 isn't supported by them anymore).

**Comment by avidane1** [comment]
ah yes, I got the wrong number here :-(...thanks.
