### ISSUE TITLE
Azure: disks are not populated in `/dev/disk/azure`

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2098]
# Issue Report #

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.8.0
VERSION_ID=1353.8.0
BUILD_ID=2017-05-30-2322
PRETTY_NAME="Container Linux by CoreOS 1353.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

Azure

### Expected Behavior ###

Per azure's documentation [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/troubleshoot-device-names-problems) and the WA Agent's behaviour [here](https://github.com/Azure/WALinuxAgent/blob/v2.2.14/config/66-azure-storage.rules), I expect `/dev/disk/azure` to contains symlinks.

### Actual Behavior ###

Doesn't exist.

### Other Information ###

See also https://github.com/kubernetes/kubernetes/issues/50150 and https://github.com/coreos/tectonic-installer/pull/1618

**Comment by edevil** [comment]
I also ran into this "problem", but is this a CoreOS bug?

**Comment by szarkos** [comment]
CC @crawford 

Yes, we need this for Azure, can it be added to the Azure images?  There is some precedent, for example CoreOS also carries udev rule "99-azure-product-uuid.rules".

The official upstream source for the Azure storage udev rule is in the WALinuxAgent directory: https://raw.githubusercontent.com/Azure/WALinuxAgent/master/config/66-azure-storage.rules

**Comment by crawford** [comment]
This should be fixed in the next Alpha.
