### ISSUE TITLE
Disable DHCP by default for igbvf interfaces

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#210]
Reported via email. From what I gather igbvf devices are hardware virtualized interfaces intended for use with virtual machines. There shouldn't be a need to ever apply our default dhcp rule to them because they are essentially duplicates of the primary interface the host already has.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
