### ISSUE TITLE
Ignition-created RAIDs don't have stable device names

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2104]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1478.0.0+2017-07-28-2222
VERSION_ID=1478.0.0
BUILD_ID=2017-07-28-2222
PRETTY_NAME="Container Linux by CoreOS 1478.0.0+2017-07-28-2222 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Expected Behavior ###

Ignition creates RAID arrays with a stable name in `/dev/md`.

### Actual Behavior ###

Ignition-created RAID arrays have a different `/dev/md` symlink depending whether they're started before or after the hostname is set.

### Reproduction Steps ###

  1. Create a RAID with Ignition, named e.g. `home`
  2. Reboot, notice `/dev/md/home`
  3. `mdadm --stop` the array and then `mdadm --assemble` it
  4. Notice `/dev/md/localhost:home` instead of `/dev/md/home`

### Other Information ###

Without an `mdadm.conf`, `mdadm` sets the homehost to the system hostname, which is `localhost` in the initramfs.  On subsequent boots, if the array is auto-assembled while the hostname is still `localhost`, the homehost is omitted from the device name in `/dev/md`.  This is potentially racy for data volumes.

Possible fixes:

- Create a default `mdadm.conf` with `HOMEHOST localhost` (or `core` etc).

- Omit the homehost from the array name (`--homehost ""`).  The array will always be treated as foreign, ending up with a path like `/dev/md/home_0`.

- Allow the user to specify the homehost in the Ignition config.  Given the unreliability of the system hostname at boot, this would likely only make sense if they also add a `HOMEHOST` directive to `/etc/mdadm.conf` in the rootfs.

- Create arrays with `--homehost any`.  That will ensure the device name is never prefixed, at the cost of potentially creating confusion by also not prefixing it if the array is attached to a different machine.

**Comment by ajeddeloh** [comment]
I'm not a fan of the default `mdadm.conf` idea or the specifying it as part of the ignition config. If a user tries to change it via ignition, they'll overwrite it without knowing they need that line. We could document it, but I don't know how much we want to have special keywords that must be in config files.

Is it possible to move the ensure the hostname gets set correctly in the initramfs before ignition runs and creates the arrays?

**Comment by bgilbert** [comment]
The Ignition files stage has an opportunity to set the hostname, and can't run until the disks stage is complete.

**Comment by dgonyeo** [comment]
I just discovered that the kola test `coreos.disk.raid.data` is failing due to this. When a machine first boots `/dev/md/DATA` exists and after a reboot the device is then named `/dev/md/localhost:DATA`, causing the mount unit to fail.

```
core@kola-08e679cf-1fb39f50f0 ~ $ lsblk
NAME      MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda         8:0    1 74.5G  0 disk  
|-sda4      8:4    1    1G  0 part  
| `-md127   9:127  0 63.9M  0 raid1 
|-sda2      8:2    1    2M  0 part  
|-sda9      8:9    1 72.2G  0 part  /
|-sda7      8:7    1   64M  0 part  
| `-md127   9:127  0 63.9M  0 raid1 
|-sda3      8:3    1    1G  0 part  
| `-usr   254:0    0 1016M  1 crypt /usr
|-sda1      8:1    1  128M  0 part  /boot
`-sda6      8:6    1  128M  0 part  /usr/share/oem
core@kola-08e679cf-1fb39f50f0 ~ $ systemctl status var-lib-data.mount
● var-lib-data.mount - /var/lib/data
   Loaded: loaded (/etc/systemd/system/var-lib-data.mount; enabled; vendor preset: enabled)
   Active: inactive (dead)
    Where: /var/lib/data
     What: /dev/md/DATA

Aug 17 22:44:34 kola-08e679cf-1fb39f50f0 systemd[1]: Dependency failed for /var/lib/data.
Aug 17 22:44:34 kola-08e679cf-1fb39f50f0 systemd[1]: var-lib-data.mount: Job var-lib-data.mount/start failed with result 'dependency'.
Aug 17 22:46:07 kola-08e679cf-1fb39f50f0 systemd[1]: Dependency failed for /var/lib/data.
Aug 17 22:46:07 kola-08e679cf-1fb39f50f0 systemd[1]: var-lib-data.mount: Job var-lib-data.mount/start failed with result 'dependency'.
core@kola-08e679cf-1fb39f50f0 ~ $ ls /dev/md
localhost:DATA
```

**Comment by bgilbert** [comment]
That's happening specifically on Packet, which makes sense: on that platform coreos-metadata runs in the initramfs on first boot and creates `/sysroot/etc/hostname`, so the hostname can be set in the real root before the network is up.
