### ISSUE TITLE
cloud-config & etcd

### ISSUE THREAD

**Issue by yichengq** [coreos/bugs#211]
coreos may start without etcd-related environment var set.
it is reproducible with Vagrant in coreos 509.1.0
original issue: https://github.com/coreos/etcd/issues/1794
and config: https://gist.github.com/digital-wonderland/eaad2c2e76e0b898b606
more details are in original issue.
/cc @digital-wonderland

**Comment by yichengq** [comment]
@crawford 
`Nov 26 18:52:26 core-01 etcd[462]: [etcd] Nov 26 18:52:26.238 INFO      | Rejoin with http://127.0.0.1:7001 instead of http://172.17.8.103:7001 from 49646c2cea5644adb656cd62df1ab5f4`

**Comment by robszumski** [comment]
I talked to a user today on IRC with this issue, but he reported that all drop-ins looked correct.

**Comment by yichengq** [comment]
I suppose this has been fixed because I don't know users have this problem these several months.
