### ISSUE TITLE
Unable to set a UTF-8 locale for MOSH

### ISSUE THREAD

**Issue by deed02392** [coreos/bugs#2113]
# Issue Report #

### Environment ###

VMWare ESXi 6.5

### Desired Feature ###

Enable support for at least one UTF-8 locale so that MOSH can be supported by CoreOS. I have installed a statically compiled version of mosh-server but can't use it because there are no UTF-8 locales installed (or at least I can't figure out how to enable one).

`localectl list-locales` shows that C.utf8 is available, but when I try to: `localectl set-locale LANG=C.utf8`, subsequent calls to `locale` show that POSIX is still being used.

### Other Information ###

```
appar core # locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
appar core # localectl list-locales
C.utf8
appar core # localectl set-locale "LANG=C.utf8"
appar core # locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
