### ISSUE TITLE
Reboot after  coreos-install -d /dev/sda -i ignition.json fails with Failed to start Ignition (disks)

### ISSUE THREAD

**Issue by jaggedjagged** [coreos/bugs#2118]
I installed coreos via the ISO image
(s. http://dietrichschroff.blogspot.de/2017/08/first-step-to-micorservices-coreos-on.html)

Then i created a ignition.json with
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "storage": {},
  "systemd": {},
  "networkd": {},
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa AAAAB3NzaC....
        ]
      }
    ]
  }
}

Inside the coreos vm i added a 8GB disk at /dev/sda and then i ran:

./coreos-install -d /dev/sda -i ignition.json 
Downloading the signature for https://stable.release.core-os.net/amd64-usr/1409.6.0/coreos_production_image.bin.bz2...
wget --no-verbose -O /tmp/coreos-install.JROwzOsi1W/coreos_production_image.bin.bz2.sig https://stable.release.core-os.net/amd64-usr/1409.6.0/coreos_production_image.bin.bz2.sig
2017-08-22 19:01:28 URL:https://stable.release.core-os.net/amd64-usr/1409.6.0/coreos_production_image.bin.bz2.sig [543/543] -> "/tmp/coreos-install.JROwzOsi1W/coreos_production_image.bin.bz2.sig" [1]
Downloading, writing and verifying coreos_production_image.bin.bz2...
2017-08-22 19:02:31 URL:https://stable.release.core-os.net/amd64-usr/1409.6.0/coreos_production_image.bin.bz2 [288249718/288249718] -> "-" [1]
gpg: Signature made Thu Jul  6 01:34:01 2017 UTC
gpg:                using RSA key 07FA9ED31CB5FA26
gpg: key 50E0885593D2DCB4 marked as ultimately trusted
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" [ultimate]
Installing Ignition config ignition.json...
Success! CoreOS Container Linux stable 1409.6.0 is installed on /dev/sda

I umounted the ISO image and rebootet.

There i got:

![bildschirmfoto_2017-08-22_20-35-55](https://user-images.githubusercontent.com/31256241/29583349-1ec012b4-8780-11e7-884e-80cef8665276.png)

![bildschirmfoto_2017-08-22_20-48-26](https://user-images.githubusercontent.com/31256241/29583358-26ce9552-8780-11e7-8835-b01850f3b393.png)

What am i doing wrong?

**Comment by ajeddeloh** [comment]
Are you missing a closing quote on line 14? It looks like your config is invalid; you can check [here](https://coreos.com/validate).

**Comment by jaggedjagged** [comment]
Thanks a lot.
This fixed my problem....

![bildschirmfoto_2017-08-22_21-43-44](https://user-images.githubusercontent.com/31256241/29584142-111faebe-8783-11e7-8836-a29005b40166.png)
