### ISSUE TITLE
DHCP lease losts intermittently, ens* gets new IP

### ISSUE THREAD

**Issue by supershal** [coreos/bugs#2119]
# Issue Report #

## Bug ##
We are deploying coroes 1409.9.0 on vSphere environment on ESXI host. We are noticing that coreos is randomly lost DHCP lease and assigns new IP address to the VM.
The DHCP lease should be renewed periodically by coreos and retain same IP address.

We have noticed that DHCP lease gets lost anywhere from 30 minutes to 5 days after the VM is up and running.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.9.0
VERSION_ID=1409.9.0
BUILD_ID=2017-08-11-2208
PRETTY_NAME="Container Linux by CoreOS 1409.9.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
VSphere environment
ESXI host

### Expected Behavior ###
IP address of the VM should not change and DHCP lease of the IP address should be renewed periodically.
### Actual Behavior ###
DHCP lease lost intermittently and new IP is assigned at random interval whenever the DHCP lease is lost.

### Reproduction Steps ###

  1. Provision new vmware OVA using vsphere iso image: https://stable.release.core-os.net/amd64-usr/1409.9.0/coreos_production_iso_image.iso

### Other Information ###
```
sudo journalctl -b -u systemd-networkd
-- Logs begin at Fri 2017-08-18 00:41:13 UTC, end at Tue 2017-08-22 21:49:25 UTC. --
Aug 18 21:17:34 localhost systemd[1]: Starting Network Service...
Aug 18 21:17:34 localhost systemd-networkd[239]: Enumeration completed
Aug 18 21:17:34 localhost systemd[1]: Started Network Service.
Aug 18 21:17:34 localhost systemd-networkd[239]: lo: Configured
Aug 18 21:17:34 localhost systemd-networkd[239]: eth0: IPv6 successfully enabled
Aug 18 21:17:34 localhost systemd-networkd[239]: eth0: Gained carrier
Aug 18 21:17:35 localhost systemd-networkd[239]: eth0: DHCPv4 address 10.25.206.34/22 via 10.25.207.254
Aug 18 21:17:36 localhost systemd[1]: Stopping Network Service...
Aug 18 21:17:36 localhost systemd-networkd[239]: lo: Lost carrier
Aug 18 21:17:36 localhost systemd-networkd[239]: eth0: Lost carrier
Aug 18 21:17:36 localhost systemd-networkd[239]: eth0: DHCP lease lost
Aug 18 21:17:36 localhost systemd[1]: Stopped Network Service.
Aug 18 21:17:39 localhost systemd[1]: Starting Network Service...
Aug 18 21:17:39 localhost systemd-networkd[657]: Enumeration completed
Aug 18 21:17:39 localhost systemd-networkd[657]: ens160: IPv6 successfully enabled
Aug 18 21:17:39 localhost systemd-networkd[657]: lo: Configured
Aug 18 21:17:39 localhost systemd-networkd[657]: ens160: Gained carrier
Aug 18 21:17:39 localhost systemd[1]: Started Network Service.
Aug 18 21:17:40 localhost systemd-networkd[657]: ens160: DHCPv4 address 10.25.206.20/22 via 10.25.207.254
Aug 18 21:17:41 localhost systemd-networkd[657]: ens160: Gained IPv6LL
Aug 18 21:17:54 localhost systemd-networkd[657]: ens160: Configured
Aug 22 09:32:35 localhost systemd-networkd[657]: ens160: DHCP lease lost
Aug 22 09:32:38 localhost systemd-networkd[657]: ens160: DHCPv4 address 10.25.206.67/22 via 10.25.207.254
```

```
 sudo networkctl status ens160
2: ens160
       Link File: /usr/lib64/systemd/network/99-default.link
    Network File: /usr/lib64/systemd/network/yy-vmware.network
            Type: ether
           State: routable (configured)
            Path: pci-0000:03:00.0
          Driver: vmxnet3
          Vendor: VMware
           Model: VMXNET3 Ethernet Controller
      HW Address: 00:50:56:b9:67:47 (VMware, Inc.)
         Address: 10.25.206.67
                  fe80::250:56ff:feb9:6747
         Gateway: 10.25.207.254 (CISCO SYSTEMS, INC.)
             DNS: <DNS1>
                  <DNS2>
  Search Domains: <DNS_NAME>```

**Comment by euank** [comment]
Increasing the networkd loglevel to debug (as described here: https://coreos.com/os/docs/latest/network-config-with-networkd.html#enable-debugging-manually) might include some more useful messages.

**Comment by supershal** [comment]
@euank Here is debug log for networkd service running on separate vm with the same issue.
https://gist.githubusercontent.com/supershal/ac5de0410ab94bd245042911fd0cd37e/raw/9474bd3a606df17cfc0dcf2888e472b8e15d0fa4/networkd-debug.log

Following are the highlights.
```
Aug 13 11:16:18 localhost systemd-networkd[802]: ens33: DHCP lease lost
Aug 13 11:16:21 localhost systemd-networkd[802]: ens33: DHCPv4 address 10.25.206.2/22 via 10.25.207.254
```
and
```
Aug 15 00:07:34 localhost systemd-networkd[943]: ens33: Gained IPv6LL
Aug 15 00:07:36 localhost systemd-networkd[943]: ens33: DHCPv4 address 10.25.206.66/22 via 10.25.207.254
Aug 15 00:07:47 localhost systemd-networkd[943]: ens33: Configured
```

**Comment by bgilbert** [comment]
@supershal Unfortunately, the default log level doesn't provide enough information to investigate this issue.  Please post a log with the [networkd log level set to `debug`](https://coreos.com/os/docs/latest/network-config-with-networkd.html#enable-debugging-manually).

**Comment by supershal** [comment]
@bgilbert 
I started new VM and set log level to debug and restarted networkd service as per instructions.
I noticed that from log that the VM got another IP after I restarted networkd.
Now network interface shows two ips. The vm had 10.25.235.1 before networkd restarted. After I restarted it acquired another IP 10.25.235.2.
```
> ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b9:7f:e9 brd ff:ff:ff:ff:ff:ff
    inet 10.25.235.1/23 brd 10.25.235.255 scope global dynamic ens160
       valid_lft 77837sec preferred_lft 77837sec
    inet 10.25.235.2/23 brd 10.25.235.255 scope global secondary dynamic ens160
       valid_lft 78986sec preferred_lft 78986sec
    inet6 fe80::250:56ff:feb9:7fe9/64 scope link
       valid_lft forever preferred_lft forever
```
Here is full debug log of the VM. https://gist.githubusercontent.com/supershal/27535b770cb6fc58c59bea3d726d29e2/raw/b219889ce13254fe151444e61736caa5f76d3f12/debug-networkd.log

I can ssh to my vm using both ip addresses.
Also, My DHCP server frees up earlier address and make it available as free while the VM is still holding on the IP 10.25.235.1 . here is my DHCP log.
```
dhcpd log: [root@localhost dhcpd]# tail -f dhcpd.leases
lease 10.25.235.1 {
  starts 3 2017/08/23 18:34:00;
  ends 4 2017/08/24 18:34:00;
  cltt 3 2017/08/23 18:34:00;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet 00:50:56:b9:7f:e9;
  uid "\377\237n\205$\000\002\000\000\253\021\341\377]\330\354\200v\227";
}
lease 10.25.235.1 {
  starts 3 2017/08/23 18:53:06;
  ends 3 2017/08/23 18:53:06;
  tstp 3 2017/08/23 18:53:06;
  cltt 3 2017/08/23 18:53:06;
  binding state abandoned;
  next binding state free;
  rewind binding state free;
}
lease 10.25.235.2 {
  starts 3 2017/08/23 18:53:09;
  ends 4 2017/08/24 18:53:09;
  cltt 3 2017/08/23 18:53:09;
  binding state active;
  next binding state free;
  rewind binding state free;
  hardware ethernet 00:50:56:b9:7f:e9;
  uid "\377\237n\205$\000\002\000\000\253\021\341\377]\330\354\200v\227";
}
lease 10.25.235.1 {
  starts 3 2017/08/23 18:53:06;
  ends 3 2017/08/23 18:53:06;
  tstp 3 2017/08/23 18:53:06;
  cltt 3 2017/08/23 18:53:06;
  binding state free;
}```

**Comment by bgilbert** [comment]
Thanks for the logs.  It's possible that networkd isn't properly renewing the lease before the previous one expires.  From your logs it looks as though it intends to do so, at least.  If you see the lease lost + new address behavior again:

```
Aug 13 11:16:18 localhost systemd-networkd[802]: ens33: DHCP lease lost
Aug 13 11:16:21 localhost systemd-networkd[802]: ens33: DHCPv4 address 10.25.206.2/22 via 10.25.207.254
```

please post the debug logs of that event as well.

Either way, it seems your DHCP server is misconfigured.  Your leases file shows two active leases for the same MAC address and client ID.  When networkd restarted and requested a new lease, your server should have offered the same address already issued to the client.  I'd suggest checking your DHCP server settings.

**Comment by bgilbert** [comment]
@supershal Any updates?

**Comment by bgilbert** [comment]
This appears to be a server misconfiguration, so I'll close.

**Comment by tyronefrance** [comment]
Hi bgilbert,

I am having the same issue.. Could you tell me what was the miscuguration you had in the server?
