### ISSUE TITLE
MAC addresses change on bonding interfaces on 1465.6.0

### ISSUE THREAD

**Issue by jsoriano** [coreos/bugs#2120]
# Issue Report #

I'm not sure this is really a regression, but it is a behavioural change between stable 1465.6.0 and previous versions that can break automatic upgrades when using DHCP on bonding interfaces.

## Bug ##

On 1465.6.0, MAC address of bonding interfaces is generated randomly (or based on machine-id), on previous stable releases it took one of the slave interfaces.
This is problematic when using DHCP based on MAC addresses. As a workaround a known MAC address of bonding interface has to be set in the netdev file.
According to [documentation of netdev unit](https://www.freedesktop.org/software/systemd/man/systemd.netdev.html#MACAddress=), the current behaviour seems to be the expected one, so maybe this is more a fix than a regression, but it breaks automatic updates when using bonding and DHCP if `MACAddress=` is not being set.

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.6.0
VERSION_ID=1465.6.0
BUILD_ID=2017-08-16-0012
PRETTY_NAME="Container Linux by CoreOS 1465.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Reproduced on bare-metal and on VirtualBox with vagrant.

### Expected Behavior ###

Bonding interfaces have the same MAC address as one of the slave interfaces.

### Actual Behavior ###

Bonding interfaces have a generated MAC address, different from the ones of the slave interfaces.

### Reproduction Steps ###

  1. Start a machine with two network interfaces
  2. Create a bonding interface with these two network interfaces
  3. Check the MAC address

### Other Information ###

Used network configuration to reproduce this issue (link files are only used in VirtualBox to mimic interface names of bare-metal tests):

10-eth1.link:
```
[Match]
OriginalName=eth1
[Link]
Name=eno1
```

10-eth2.link:
```
[Match]
OriginalName=eth2
[Link]
Name=eno2
```

25-bond0.netdev:
```
[NetDev]
Name=bond0
Kind=bond
```

25-bond0.network
```
[Bond]
Mode=balance-rr
MIIMonitorSec=1s
LACPTransmitRate=fast
[Match]
Name=bond0
[Network]
DHCP=yes
[DHCP]
UseDomains=yes
```

25-bond0-phys-all.network
```
[Match]
Name=en*

[Network]
Bond=bond0
```

**Comment by jsoriano** [comment]
Can be related with https://github.com/systemd/systemd/issues/3375

**Comment by bgilbert** [comment]
Thanks for the report.

Starting in 1465.0.0, Container Linux configures the bonding driver not to create a `bond0` device by default (https://github.com/coreos/baselayout/pull/66).  Before the change, `bond0` was special: because it was pre-created, networkd would not configure it, even if a netdev unit matched it.  Now networkd will configure `bond0` as with any other bond device.  To restore the previous behavior, you can create an empty file at `/etc/modprobe.d/bond.conf`.

The effect on MAC address assignment was overlooked at the time, but now that it's happened, I'm not sure we should revert the change:
- The inability to set parameters on `bond0` using networkd was fairly surprising.
- With the previous configuration, as I understand it, `bond0` could end up with the MAC address of any of the member interfaces, depending on which one happened to come up first.

Thoughts?

**Comment by jsoriano** [comment]
Thanks for the explanation. Then this was working for us by chance before :)

I have tried now in previous versions to create a bonding called bond1 and it has indeed a generated MAC address, I can also see that a bond0 interface is created too.

So I think that new behaviour is more consistent. It is consistent with systemd.netdev documentation and it doesn't handle bond0 as an special case. And if needed it's easy to restore previous behaviour by creating this empty file or by setting a fixed `MACAddress=`.
Maybe a note in documentation or in the release notes could be added in case it affects someone else.

**Comment by bgilbert** [comment]
There was a note of sorts in the [release notes](https://coreos.com/releases/#1465.0.0), though it didn't mention MAC addresses specifically.  If anyone wants more information, this bug will be here. 😀  

Thanks again for reporting!

**Comment by jsoriano** [comment]
@bgilbert I have a suggestion about this, it'd be nice, if possible, to have the accumulated release notes in stable and beta channel tabs of the releases site. If not very few things appear to change in the sable releases, for example this change only appears in alpha channel tab.

**Comment by bgilbert** [comment]
@jsoriano The release notes page is indeed very difficult to read.  I've now filed https://github.com/coreos/bugs/issues/2134 to track the problem, and we're going to see what we can do to improve it.  Thanks for the nudge.

**Comment by jsoriano** [comment]
Great, thanks a lot!

**Comment by bgilbert** [comment]
For the record, systemd upstream made the same change in https://github.com/systemd/systemd/pull/6448.

**Comment by kbrwn** [comment]
Another customer reported needed to create /etc/modprobe.d/systemd.conf  to override the default systemd configuration.

**Comment by luxifer** [comment]
According to the documentation here https://www.kernel.org/doc/Documentation/networking/bonding.txt if the `fail_over_mac` policy is set to `none` which is the default in the kernel, the bonding interface should take the MAC address of the first enslaved interface and apply it to all slave. Actually with this patch, which lets systemd fully manage the bonding configuration, the MAC address change at each reboot and is completely random.
