### ISSUE TITLE
lddtree -> strings: command not found

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2122]
Container Linux ships the `lddtree` binary.

However, that binary has a dependency on executing `strings`, which we don't ship.

### Reproduction

```shell
$ lddtree /bin/bash
bash => /bin/bash (interpreter => /lib64/ld-linux-x86-64.so.2)/usr/bin/lddtree: line 163: strings: command not found

    libreadline.so.6 => /lib64/libreadline.so.6
    libncurses.so.5 => /lib64/libncurses.so.5
    libc.so.6 => /lib64/libc.so.6
        ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
```

### Expected behavior

Either `lddtree` shouldn't be shipped, or `lddtree` should run without an error.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
