### ISSUE TITLE
docker-17.06.1-ce: error creating overlay mount to /var/lib/docker/overlay2/ID/merged: device or resource busy"

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2127]
### Container Linux Version ###

Current nightly test runs, e.g.:

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1506.0.0+2017-08-25-1813
VERSION_ID=1506.0.0
BUILD_ID=2017-08-25-1813
PRETTY_NAME="Container Linux by CoreOS 1506.0.0+2017-08-25-1813 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Happens on qemu and AWS, probably all of them.

### Expected Behavior ###

`docker run` works reliably

### Actual Behavior ###

Every once in a while, the first run has the below error:

```
$ journalctl -u docker -o cat | head -n 12
Starting Docker Application Container Engine...
time="2017-08-29T01:38:38.034391242Z" level=warning msg="failed to rename /var/lib/docker/tmp for background deletion: rename /var/lib/docker/tmp /var/lib/docker/tmp-old: no such file or directory. Deleting synchronously"
time="2017-08-29T01:38:38.047270072Z" level=error msg="Failed to built-in GetDriver graph aufs /var/lib/docker"
time="2017-08-29T01:38:38.244953954Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2017-08-29T01:38:38.248685288Z" level=info msg="Loading containers: start."
time="2017-08-29T01:38:38.416311592Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2017-08-29T01:38:38.539319520Z" level=info msg="Loading containers: done."
time="2017-08-29T01:38:38.562007032Z" level=info msg="Daemon has completed initialization"
time="2017-08-29T01:38:38.562264173Z" level=info msg="Docker daemon" commit=874a737 graphdriver=overlay2 version=17.06.1-ce
Started Docker Application Container Engine.
time="2017-08-29T01:38:38.571944666Z" level=info msg="API listen on /var/run/docker.sock"
time="2017-08-29T01:38:39.756677347Z" level=error msg="Handler for POST /v1.30/containers/5b2752feaa6cff592771206bb4d5fe27a14bf5936bfdd167abc470648df25165/start returned error: error creating overlay mount to /var/lib/docker/overlay2/ef86febd7609b1508ef12b147c5aaf07ed750d09ca90b4d362b7e81543f33a3e/merged: device or resource busy"
```

### Reproduction Steps ###

1. `kola run "docker.base"` and get really (un)lucky

### Other info

We, unfortunately, bumped the kernel to 4.13 at around the same time we bumped docker to 17.06.
I expect it'll be one of those two changes.

This happens very infrequently. When it does happen, the impact is minimal; the first container run fails, but subsequent ones are fine. I think it can only happen as the first container run, so anything that's retrying appropriately should be fine.

**Comment by euank** [comment]
There's also an overlayfs related message in `dmesg` at the time:

```
$ dmesg -T | grep -C 5 upper
[Tue Aug 29 01:38:38 2017] docker0: port 1(vetha03b986) entered blocking state
[Tue Aug 29 01:38:38 2017] docker0: port 1(vetha03b986) entered forwarding state
[Tue Aug 29 01:38:38 2017] docker0: port 1(vetha03b986) entered disabled state
[Tue Aug 29 01:38:39 2017] docker0: port 2(vethfdee011) entered blocking state
[Tue Aug 29 01:38:39 2017] docker0: port 2(vethfdee011) entered disabled state
[Tue Aug 29 01:38:39 2017] overlayfs: upperdir is in-use by another mount
[Tue Aug 29 01:38:39 2017] device vethfdee011 entered promiscuous mode
[Tue Aug 29 01:38:39 2017] IPv6: ADDRCONF(NETDEV_UP): vethfdee011: link is not ready
[Tue Aug 29 01:38:39 2017] docker0: port 2(vethfdee011) entered blocking state
[Tue Aug 29 01:38:39 2017] docker0: port 2(vethfdee011) entered forwarding state
[Tue Aug 29 01:38:39 2017] docker0: port 2(vethfdee011) entered disabled state
```

**Comment by euank** [comment]
That message, and resulting mount error, are introduced in https://patchwork.kernel.org/patch/9760547/

That's new to the 4.13 kernel.

It seems very likely to me docker internally has a race or logic bug resulting in it mounting twice in some cases, and until now it silently succeeded.

**Comment by amir73il** [comment]
@euank there has been a failure in the process handling this regression.
As @rhvgoyal correctly pointed on #34948 (https://github.com/moby/moby/pull/34948#issuecomment-332955028), kernel changes that break userspace are not tolerable.
In this case, you spotted the regression very early at rc6 time. Had the regression been reported
to the kernel mailing list or to the author of the patch (myself) it could have been fixed in time for v4.13 release and probably could save you guys a lot of fuss.
Anyway, I will be posting a patch to fix the regression in the kernel and I expect the patch to land in some future stable v4.13.y update.
I am writing this for you to know for next time and quite frankly, must say I am surprised that CoreOs guys didn't follow up on your report and handle this regression as expected.
Sorry for the pain..

**Comment by euank** [comment]
@amir73il 
Apologies for not reporting it upstream early on.

As I read the patch, it seemed like it was intentionally preventing this behavior for the sake of correctness, which isn't so much breaking userspace as "userspace was already broken, let's make it more obvious".
Since the patch made it clear that erroring on re-using an inuse upper/workdir was intentional, I wasn't certain that emailing to tell you that your patch did that was really new information.

Regardless, I'm glad you've found your way to this info even though we neglected to email you. Thanks for the help!

**Comment by amir73il** [comment]
@euank you should read https://felipec.wordpress.com/2013/10/07/the-linux-way/
The fact that my patch was "correct" and changed behavior intentionally is no excuse to breaking docker, a program used by a few users out there..
The rational behind doing the behavior change unconditionally was that we were wrong to think that "who is the world would have this bizar setup of using same workdir/upperdir intentionally?".
We simply missed the obvious unintentional mount leak scenario.
The way I proposed to fix the regression is to make the "correct" behavior depend on an opt-in feature
https://marc.info/?l=linux-unionfs&m=150667387131734&w=2 

Your work to fix docker is important none the less.
Containers should not leak mounts (even for administrative chroot operations).  
First of all, leaking mounts is bad for other reasons, for example -
when leaking blockdev mounts like devicemapper, umount in one namespace does not clean umount the filesystem.

Secondly, at some point, it is hoped, docker will want to catch up with new overlayfs features
and allow users to enable the redirect_dir and index features, both solve real user issues
(directory rename and breaking hardlinks). When that happens, overlayfs may not be as forgiving
about leaked mounts, unless we end up implementing Vivek's suggestion to mount the same super block.

Thanks for testing early versions and reporting the issue!

**Comment by euank** [comment]
The overlay partial-revert which avoids this issue is queued up for stable and has been cherry-picked into the most recent set of Container Linux releases. This should be fixed.
