### ISSUE TITLE
Finalize root-on-RAID support

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2128]
Finish coreos/docs#1141, then release-note as done.

**Comment by steigr** [comment]
Are there any plans to support USR-partitions on MD-RAID?
The use-case will be to support cheap servers with 2 drives but without HWRAID.

**Comment by bgilbert** [comment]
@steigr Not in the short term.  I've filed https://github.com/coreos/bugs/issues/2143 for USR-on-RAID support.
