### ISSUE TITLE
nfs mounts stalled under alpha 522.x but work under beta 494.4.0

### ISSUE THREAD

**Issue by lordelph** [coreos/bugs#213]
Running coreos 522.1.0 with Virtual Box 4.3.20 and Vagrant 1.7.1 on Mac OS X Mavericks.

VMs had an NFS share declared in the Vagrantfile as follows

    config.vm.synced_folder "/Users/paul/Documents/workspace", "/home/core/share", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']

Within the CoreOS 522.1.0 VM I had a script which performed a git clone operation into the shared folder. This operation would stall, with the git process hanging indefinitely during the final phases of the checkout. If the git operation was carried out on the VMs own filesystem, it succeeded

Dropping back to CoreOS 494.4.0, the operation succeeded.

I believe there's *something* about the kernel in 522.x which has caused this, but I'm not savvy enough with NFS to know how to diagnose it further.

**Comment by crawford** [comment]
NFS issues should be resolved at this point. Please reopen if you are still having trouble.
