### ISSUE TITLE
Container Linux release notes are not usable

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2134]
# Issue Report #

### Container Linux Version ###

Any beta or stable

### Environment ###

Any

### Expected Behavior ###

The release notes page clearly states what has changed between releases.

### Actual Behavior ###

The release notes page assumes a working understanding of the Container Linux branching model.

### Reproduction Steps ###

  1. Visit the [release notes page](https://coreos.com/releases/).
  2. Try to determine what has changed between 1409.9.0 and 1465.6.0.

### Other Information ###

To answer that question, one must currently:

1. Read the alpha release notes for the *first* release of each major version between 1409 exclusive and 1465 inclusive.  This is usually x.0.0 but not always (e.g. 1451.2.0).
2. Read the release notes for all other 1465 alpha releases, if any.
3. Read the release notes for all 1465 beta releases.
4. Read the release notes for all 1465 stable releases up to 1465.6.0 inclusive.
5. Remain unconcerned about version numbers missing from all three channels, e.g. 1465.1.0.

This is highly non-obvious.  Looking solely at the Stable tab, one might plausibly conclude that the only change between 1409.9.0 and 1465.6.0 was an update to Linux 4.12.7.

**Comment by FreekingDean** [comment]
How are the release notes currently generated? Is it manual or automated in some fashion?

**Comment by bgilbert** [comment]
They're manually generated based on the diffs between the current and previous tags, i.e. two successive releases on the same branch or two successive branch points (if branching a new alpha from master).  The release notes are attached to the [manifest release on GitHub](https://github.com/coreos/manifest/releases), collected from there by tooling, and added to the metadata read by the website code.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
