### ISSUE TITLE
Consolidate kernel options into commonconfig where possible

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2137]
There are config options in the amd64 and arm64 defconfigs that don't need to be arch-specific, and probably some redundancy between arch configs and commonconfig.  Clean up duplicates, and move options to commonconfig where possible to improve cross-arch consistency.

**Comment by ajeddeloh** [comment]
Just did a quick check for redundancy:
`cat sys-kernel/coreos-modules/files/* | sort | uniq -d`
and there doesn't appear to be any duplicates.

**Comment by glevand** [comment]
Maybe something like this is more useful:
`cat sys-kernel/coreos-modules/files/* | egrep --only-matching '^CONFIG_[^=]*' | sort | uniq -d | xargs -i egrep -rH {}= sys-kernel/coreos-modules/files`

**Comment by ezequielgarcia** [comment]
@bgilbert @glevand I believe we can consider closing this issue for now -- unless you wanna make this a sticky issue.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
