### ISSUE TITLE
unsupported public key algorithm: ecdsa-sha2-nistp384-cert-v01@openssh.com [

### ISSUE THREAD

**Issue by f0** [coreos/bugs#214]
is there a reason to not support this?

'''userauth_pubkey: unsupported public key algorithm: ecdsa-sha2-nistp384-cert-v01@openssh.com [preauth]'''

**Comment by wmark** [comment]
If you feel that ECC [implementations] should be removed from OpenSSL you should remove it from your Go-based products as well:
https://github.com/golang/go/tree/master/src/crypto/elliptic

----
See also:
* coreos/etcd-ca#22 — RHEL, CentOS, doesn't ship with *ellptic*
* http://www.secg.org/certicom_patent_letter_SECG.pdf

**Comment by marineam** [comment]
For reference, the upstream Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=531540

**Comment by darconeous** [comment]
This should totally be enabled. No brainer.

**Comment by lleszczu** [comment]
I just tried bootstrapping python with https://github.com/defunctzombie/ansible-coreos-bootstrap but with pypy version upgraded to latest 4.0.1 and without EC extensions it doesn't work. After manual ssl upgrade it works just fine. It seems to be the only lacking functionality to run latest pypy on CoreOS.

**Comment by paulszego** [comment]
Is there any plan to address this issue? It's been over a year.

**Comment by lgreenlee** [comment]
I would like to see this supported as well.

**Comment by marineam** [comment]
EC will finally be available in this weeks alpha :)
