### ISSUE TITLE
Startup or shutdown scripts on GCE

### ISSUE THREAD

**Issue by hamann** [coreos/bugs#2140]
Since GCE agent is running in an rkt container, how could we manage docker containers or processes running on host? For example we'd like to stop or send a signal to consul when deleting an instance so that it could gracefully leave the cluster.

**Comment by crawford** [comment]
The GCE agent is run via rkt in the "fly" stage-2. This differs from the default stage-2, but the main difference is that the "container" exists within the host's namespaces. This means you'll be able to send signals to processes. Note that the "container" is still chrooted. You'll need to bind mount in any paths that you'll need access to.

That being said, I would highly recommend avoiding the use of the startup and shutdown scripts. Leveraging systemd is going to be far faster, easier, and more robust. The startup and shutdown scripts have had [problems in the past](https://github.com/coreos/bugs/issues/1999) and I should note that I'm considering recommending the GCE agents removal (nothing to worry about yet, there will always be a deprecation window).

**Comment by hamann** [comment]
Thanks for your answer!
Unfortunately I don't have any experience yet with rkt, I just tried to enter that container with `rkt enter` to see what's going on (e.g. `ps` is missing, so no idea how to identify a process and sending a signal).

Maybe I missed a thing, but what I've read so far is that shutdown scripts are the only way to have a chance to execute something before GCE kills the instance [due to an instances.delete request or an instances.stop request to the API](https://cloud.google.com/compute/docs/shutdownscript). I'd be more than happy if the instance would just do a clean shutdown like in `shutdown -h now`. Not sure how systemd could be involved.

**Comment by crawford** [comment]
> Maybe I missed a thing, but what I've read so far is that shutdown scripts are the only way to have a chance to execute something before GCE kills the instance

When GCE kills the instance, it attempts to shutdown first. This is no different than a regular, user-initiated shutdown (actually, GCE will only allow the machine two minutes to shutdown, so move quickly).

**Comment by hamann** [comment]
Yes, you're right. I added a `ExecStop` to the according systemd services and now everything works as expected. No need anymore for a shutdown script. Thanks a lot!
