### ISSUE TITLE
CT doesn't support same protocol for include as ignition

### ISSUE THREAD

**Issue by Elettronik** [coreos/bugs#2141]
## Feature Request ##
The config transpiler supports only local data and http protocol for including files in configuration section like ignition.config.append.source, ignition.config.replace.source and storage.files.contents.url while the ignition config generated supports more protocols like http, https, tftp, s3, and data.

Is possible to have same protcols support in config transpiler and ignition?

By looking at sources (I'm not a go programmer but, it seems to generate ignition 2.0 files, while wider url type support is included in version 2.1)

**Comment by dgonyeo** [comment]
The reason for the limited protocols is that CT generates Ignition 2.0 files, as you noticed. The configuration spec for this version only supports http, https, and data urls.

The spec is here: https://github.com/coreos/ignition/blob/master/doc/configuration-v2_0.md

Version 2.1 was recently marked as stable, and once it makes it into a stable version of Container Linux we'll be adding support for generating 2.1 configs into CT, which will include support for the extra protocols (tftp and s3) you're asking about.

**Comment by dgonyeo** [comment]
Oh I was just informed that 2.1 has already made it into a stable. I'll be doing the work of adding support for this soon, I just need to wrap up a couple other things before I can get to it.

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/container-linux-config-transpiler/pull/106
