### ISSUE TITLE
Coreos-Vagrant issue - Etcd, Flannel & fleet service are not started on boot (Ignition)

### ISSUE THREAD

**Issue by rishi-nair-js** [coreos/bugs#2148]
I recently tried to setup a development cluster using the step as provided here - https://github.com/coreos/coreos-vagrant

Looks like the cluster was setup with no issues. But on examining the nodes i found that none of the coreos services have been started on boot.

Container Linux by CoreOS alpha (1520.1.0)
core@core-01 ~ $ fleetctl list-machines
Error retrieving list of active machines: Get http://domain-sock/fleet/v1/machines?alt=json: dial unix /var/run/fleet.sock
: connect: no such file or directory

**Etcd2**
core@core-01 ~ $ systemctl status etcd2
● etcd2.service - etcd2
   Loaded: loaded (/usr/lib/systemd/system/etcd2.service; disabled; ven
   Active: inactive (dead)
core@core-01 ~ $

**flannel**

core@core-01 ~ $ systemctl status flanneld
WARNING: terminal is not fully functional
● flanneld.service - flannel - Network fabric for containers (System Application Container)
   Loaded: loaded (/usr/lib/systemd/system/flanneld.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/flanneld.service.d
           └─20-clct-flannel.conf, 50-network-config.conf
   Active: inactive (dead)
     Docs: https://github.com/coreos/flannel
core@core-01 ~ $
[coreos-vagrant.zip](https://github.com/coreos/bugs/files/1296620/coreos-vagrant.zip)

**The files used to build the cluster have been attached.**

**Comment by Constantin07** [comment]
@rishi-nair-js  It looks like this happens because the default ignition file `config.ign` contains some variables which are not substituted:
* ${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}
* ${COREOS_VAGRANT_VIRTUALBOX_HOSTNAME}
* token

https://github.com/coreos/coreos-vagrant/blob/master/config.ign.sample#L15

**Comment by rishi-nair-js** [comment]
@Constantin07 - Thanks for your reply.

I figured out, what the issue is,... the token variable is not fetched by default when we run the 'vagrant up' command (which it used to do prior to the ignition update).

So here are the step that need to followed, before every 'vagrant up'

1) curl https://discovery.etcd.io/new\?size\=X  --- X being the size of your cluster.
2) Replace the <token> variable with the generated token.
3) Run ct --platform=vagrant-virtualbox < cl.conf > config.ign ---  which will generate the confign.ign file
4) Vagrant up.

 Note: Fleet services are not running by default, either modify the cl.conf file or start it via the systemctl command.

**Comment by Constantin07** [comment]
@rishi-nair-js Thanks - but how do you get an individual config.ign file for each CoreOS node in a cluster of 3 nodes ?

Each config.ign needs to have individual private IP address for etcd2 to bind to ...

**Comment by rishi-nair-js** [comment]
@Constantin07 - I think the ignition extension takes care of assigning the IP to the nodes in the cluster, I went through a video by alex crawford (developer of ignition ).... he explain the ignition system runs before systemd is loaded... so there is no chance of having the ip's assigned to the system yet...

so the variable you have pointed out.

${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}
${COREOS_VAGRANT_VIRTUALBOX_HOSTNAME}

get there ip's assigned dynamically.

Take a look at the below code in the Vagrantfile

  ip = "172.17.8.#{i+100}"
      config.vm.network :private_network, ip: ip
      # This tells Ignition what the IP for eth1 (the host-only adapter) should be
      config.ignition.ip = ip

**Comment by Constantin07** [comment]
@rishi-nair-js You are right but on CoreOS node after successful boot up in VirtualBox, the etcd2 systemd drop-in file still contains ${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4} and ${COREOS_VAGRANT_VIRTUALBOX_HOSTNAME} instead of ip's mentioned in Vagrant file.

My assumption was that Vagrant will substitute these variables before pushing ingition config to VirtualBox.
