### ISSUE TITLE
Support booting ISO image on UEFI

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2150]
# Issue Report #

### Environment ###

UEFI on bare metal

### Desired Feature ###

Allow booting the ISO image without switching the system to BIOS compatibility mode.

### Other Information ###

See also https://github.com/coreos/scripts/pull/551.

**Comment by berkantipek** [comment]
+1

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
