### ISSUE TITLE
CoreOS-Vagrant - substitute hostname, private_ip and token in Ignition

### ISSUE THREAD

**Issue by Constantin07** [coreos/bugs#2153]
# Issue Report #

Some variables defined in default ignition files are not interpolated on target CoreOS and etcd2 cannot start properly.
https://github.com/coreos/coreos-vagrant/blob/master/config.ign.sample#L15

Variables:
`${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}`
`${COREOS_VAGRANT_VIRTUALBOX_HOSTNAME}`
`<token>`

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.7.0
VERSION_ID=1465.7.0
BUILD_ID=2017-09-05-2043
PRETTY_NAME="Container Linux by CoreOS 1465.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

VirtualBox 5.1.26 r117224 (Qt5.6.2)
Windows 10 Home

### Expected Behavior ###

The etcd2 service is configured with correct parameters.

### Actual Behavior ###

```
# cat  /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}:2379"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/<token>"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}:2380"
Environment="ETCD_NAME=${COREOS_VAGRANT_VIRTUALBOX_HOSTNAME}"
```

`user-data` script has `$private_ipv4` and `$public_ipv4` which are interpolated with per VM values on each CoreOS startup. 

Do we have something similar for ignition ?

**Comment by crawford** [comment]
Ignition doesn't do any [variable substitution](https://coreos.com/ignition/docs/latest/what-is-ignition.html#no-variable-substitution). The variable substitution is actually done by systemd when using Ignition. In the config you referenced, you'll notice that the service is using `EnvironmentFile` and requires `coreos-metadata.service`. This service writes the info into a file which is then pulled in by systemd. If those variables aren't being substituted properly, it means they aren't defined.

I can see in your snippet that coreos-cloudinit is writing the config, not Ignition. Have you pulled the latest version of coreos-vagrant and used its Vagrantfile? We recently changed how this works.

**Comment by Constantin07** [comment]
@crawford thanks for getting back. I'm using the latest version of coreos-vagrant 0.0.3.

I'm using the ignition file  `config.ign` (manually crafted which was verified via [config validator](https://coreos.com/validate/)).
I can see that `coreos-metadata` unit works fine:
```
core-1 ~ # cat /run/metadata/coreos
COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4=172.17.8.101
COREOS_VAGRANT_VIRTUALBOX_HOSTNAME=core-1
```

also the `etcd2` unit file seems to be OK as well:
```
core-1 ~ # systemctl cat etcd2
# /usr/lib/systemd/system/etcd2.service
[Unit]
Description=etcd2
Conflicts=etcd.service

[Service]
User=etcd
Type=notify
Environment=ETCD_DATA_DIR=/var/lib/etcd2
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd2
Restart=always
RestartSec=10s
LimitNOFILE=40000
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/etcd2.service.d/20-clct-etcd.conf
[Unit]
Requires=coreos-metadata.service
After=coreos-metadata.service
Wants=network-online.target
After=network-online.target
Before=flanneld.service
Before=docker.service

[Service]
EnvironmentFile=/run/metadata/coreos
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/3b913e76bcebc3f01fd05bdf8a6c4ce1"
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}:2379"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}:2380"
Environment="ETCD_LISTEN_PEER_URLS=http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}:2380"
Environment="ETCD_NAME=${COREOS_VAGRANT_VIRTUALBOX_HOSTNAME}"
```

but the service fails to start with some strange error:
```
-- Unit etcd2.service has begun starting up.
Sep 20 19:31:13 core-1 etcd2[937]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}:2379
Sep 20 19:31:13 core-1 etcd2[937]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Sep 20 19:31:13 core-1 etcd2[937]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/3b913e76bcebc3f01fd05bdf8a6c4ce1
Sep 20 19:31:13 core-1 etcd2[937]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4
}:2380
Sep 20 19:31:13 core-1 etcd2[937]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Sep 20 19:31:13 core-1 etcd2[937]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}:2380
Sep 20 19:31:13 core-1 etcd2[937]: recognized and used environment variable ETCD_NAME=${COREOS_VAGRANT_VIRTUALBOX_HOSTNAME}
Sep 20 19:31:13 core-1 etcd2[937]: invalid value "http://${COREOS_VAGRANT_VIRTUALBOX_PRIVATE_IPV4}:2380" for ETCD_LISTEN_PEER_URLS: parse http://${COREOS_VA
GRANT_VIRTUALBOX_PRIVATE_IPV4}:2380: invalid character "{" in host name
Sep 20 19:31:13 core-1 systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Sep 20 19:31:13 core-1 systemd[1]: Failed to start etcd2.
```

**Comment by crawford** [comment]
Your drop-in is missing `EnvironmentFile=/run/metadata/coreos`. This file is written by `coreos-metadata.service` and the values are substituted by systemd. How did you generate your Ignition config? CT is a good tool to automate this and has [docs](https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/examples.md#etcd) on configuring etcd. It will automatically insert my recommendation.

**Comment by Constantin07** [comment]
@crawford Thanks, I managed to make it working.
