### ISSUE TITLE
torcx: spurious garbage in vendor-store image names on latest beta/alpha

### ISSUE THREAD

**Issue by lucab** [coreos/bugs#2154]
### Container Linux Version ###

```
VERSION=1535.0.0
VERSION_ID=1535.0.0
BUILD_ID=2017-09-13-2107
PRETTY_NAME="Container Linux by CoreOS 1535.0.0 (Ladybug)"
COREOS_BOARD="amd64-usr"
```

This also applies to latest beta (1520.2.0) but not to previous releases (1520.1.0 was fine).

### Actual Behavior ###

```
$ ls -la /usr/share/torcx/store/
total 25888
drwxr-xr-x. 2 root root     4096 Sep 13 21:10 .
drwxr-xr-x. 4 root root     4096 Sep 13 21:08 ..
-rw-r--r--. 1 root root 26448011 Sep 13 21:10 'docker:17.06.torcx.tgz'$'\n''null'
lrwxrwxrwx. 1 root root       27 Sep 13 21:10 docker:com.coreos.cl.torcx.tgz -> 'docker:17.06.torcx.tgz'$'\n''null'
```

This doesn't break torcx/docker on its own, as the `com.coreos.cl` symlink is correctly pointing to the mangled filename. However it breaks other consumers and introduces a skew with the remote-manifest `path` field.

**Comment by lucab** [comment]
@squeed also mentioned that this should have been caught by this https://github.com/coreos/mantle/blob/master/kola/tests/docker/torcx_manifest_pkgs.go#L123

**Comment by euank** [comment]
We released alpha and beta versions which address this (see https://github.com/coreos/scripts/pull/749 for what caused this if you're curious).

I'm leaving this open because we also should implement a test that validates torcx manifest-mentioned paths are valid.

**Comment by euank** [comment]
The above-referenced test was [added](https://github.com/coreos/mantle/pull/701), so this shouldn't be able to happen again.
