### ISSUE TITLE
XenServer Tools is unable to report CoreOS' VM IP address to parent XenServer

### ISSUE THREAD

**Issue by TheGammelgalopper** [coreos/bugs#2158]
## Bug ##
Cannot see CoreOS's IP in XenCenter under Networking. I have seen this issue: [https://github.com/coreos/bugs/issues/1563](https://github.com/coreos/bugs/issues/1563), which is just the same here.

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.7.0
VERSION_ID=1409.7.0
BUILD_ID=2017-07-19-0005
PRETTY_NAME="Container Linux by CoreOS 1409.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
XenServer 7.2 build date 2017-05-11

**Comment by nitso** [comment]
Same problem with latest version:

    NAME="Container Linux by CoreOS"
    ID=coreos
    VERSION=1465.8.0
    VERSION_ID=1465.8.0
    BUILD_ID=2017-09-20-2237
    PRETTY_NAME="Container Linux by CoreOS 1465.8.0 (Ladybug)"
    ANSI_COLOR="38;5;75"
    HOME_URL="https://coreos.com/"
    BUG_REPORT_URL="https://issues.coreos.com"
    COREOS_BOARD="amd64-usr"

**Comment by TheGammelgalopper** [comment]
Yes, I can second this!

I have tried to comment out the following lines in the cloud config in Xen Orchestra:
```
# - name: etcd.service
# command: start

# etcd:
# name: %VMNAMETOHOSTNAME%
```
This kind of worked. But I see it as a workaround and not a solution...


What is the correct place to file this issue for XenServer/XenOrchestra?

**Comment by nitso** [comment]
There is a merged patch (https://github.com/xenserver/xscontainer/pull/45) to xscontainer already. Hope it ever arrives to supplemental pack iso :)

**Comment by TheGammelgalopper** [comment]
@nitso What does that mean? Is there something I can do to get it running smoothly?

**Comment by nitso** [comment]
@TheGammelgalopper just replace `etcd` with `etcd2` in cloud config. Like here: https://github.com/xenserver/xscontainer/pull/45/files

**Comment by bgilbert** [comment]
Since the xscontainer fix was merged, I'll close.
