### ISSUE TITLE
Include Hyper-V Integration Services

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#2161]
# Issue Report #

### Environment ###

Hyper-V

### Desired Feature ###

Because the integration services aren't shipped in the image, Hyper-V management functionality doesn't work properly. All of the drivers should be shipped already, so I think it's just a matter of adding the userspace tools.

### Other Information ###

https://technet.microsoft.com/en-us/library/dn798297(v=ws.11).aspx

**Comment by strawgate** [comment]
Would like to see this -- without it we cannot easily automate our packer builds for hyperv

**Comment by matthew-hickok** [comment]
I agree -- this would be great. Almost everything is already there too (hv_vmbus, hv_utils, etc). We pretty much just need the hv_kvp_daemon and userspace tooling.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
