### ISSUE TITLE
Consider using the NOOP IO scheduler in virtualized environments

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#2162]
# Issue Report #

### Environment ###

All virtualized environments.

### Desired Feature ###

Use `elevator=noop` to use the NOOP IO scheduler. This allows the hypervisor to make scheduling decisions instead. This may not be applicable to all environments, but it's at least [recommended on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/Best-Practices-for-running-Linux-on-Hyper-V).

**Comment by drcrallen** [comment]
It's what we do for ec2

https://github.com/metamx/coreos-overlay/pull/8

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
