### ISSUE TITLE
bare metal install from ISO on disk containing coreOS fails

### ISSUE THREAD

**Issue by alexbenisch** [coreos/bugs#2163]
# Issue Report #

### Container Linux Version ###
1465.8.0

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

bare metal 

### Expected Behavior ###

Shouldn't reinstalling be possible?

### Actual Behavior ###

... block device is not writable 

### Reproduction Steps ###

  1. ... install coreOS on physical disk 
  2. ... try reinstalling coreOS on this disk

## Feature Request ##

Do you think it would be possible to change the coreos-install script in away that gives the user 
the option to wipe the disk and make it writable so that coreos can be reinstalled?

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

Intel D525mw mainboard
8gb RAM
Adata 128gb SSD
Sandisk Cruzer Blade 8gb USB stick

**Comment by bgilbert** [comment]
I wasn't able to reproduce this.  What were the exact commands you used, and what error did you receive?

**Comment by alexbenisch** [comment]
First install
coreos-install -d /dev/sda

Reinstall
coreos-install -d /dev/sda -i ignition.json

Error
Target block device not writable are you root?
via sudo
sudo coreos-install d /dev/sda -i ignition.json

Some weird gpg error some files are locked or something

**Comment by dghubble** [comment]
We're using coreos-install for fresh installs and reinstalls in several projects successfully. This reminds me of https://github.com/coreos/matchbox/issues/250 where there were a few LVM mappings that had to be removed by hand. Is that similar to what you're seeing?

> Some weird gpg error some files are locked or something

Mind capturing that? Otherwise there is not much to go on.

**Comment by bgilbert** [comment]
Closing due to lack of response.
