### ISSUE TITLE
Ignition - Can i use it for generic linux other than coreos

### ISSUE THREAD

**Issue by harshapic** [coreos/bugs#2165]
Feature Request:
I came across Ignition which is used as part of Matchbox. But i see it supports only coreos boot process. Is it possible if i tweak it or directly whether Ignition supports generic linux as well? just like cloud-init for ubuntu does.

**Comment by lucab** [comment]
[Ignition](https://github.com/coreos/ignition/) is part of ContainerLinux early-boot utilities. It is a free-software project, so you can build your own initramfs with it or ask your preferred distribution to include it in their early-boot process. 

However I think that most distributions already have similar yet different tools for automated PXE setups (e.g. kickstart and FAI). Ignition is also biased towards immutable OS based on systemd.

**Comment by dghubble** [comment]
Random note, Matchbox has a `/generic` endpoint to allow matching machines to arbitrary files to allow you to experiment with using kickstart or cloud-init (rather than our cloud-config fork) to network boot distros other than Container Linux.
