### ISSUE TITLE
Consistent machine-id when using PXE boot 

### ISSUE THREAD

**Issue by travisgroth** [coreos/bugs#2166]
### Environment ###

Any bare metal or VM based PXE booted configuration

### Desired Feature ###

/etc/machine-id should be (optionally?) consistent across boots on the same physical system.  Parsing the actual host uuid and regexing it early in bootup should be sufficient.  An option to turn this behavior on/off is probably reasonable.

### Other Information ###

Reasoning:

/etc/machine-id is used for, amongst other things, MAC addresses of bonded interfaces and DHCP client identifiers by default.  This means that simply rebooting a pxe booted system will make it appear to be a new host even if it is just to re-provision it for some ignition changes.  This leads to DHCP lease churn, arp table updates and ddns conflicts if your DHCP server is handling DNS mappings from DHCP.  I have been able to work through this with a custom early systemd unit file but it seems logical to me that this behavior would be included and possibly even the default.

Here's my unit file for reference:
````
$ cat /etc/systemd/system/uuid.service
[Unit]
Description=Set system uuid as machine-id
Before=network-pre.target
Wants=network-pre.target

[Service]
Type=oneshot
ExecStart=/usr/bin/cp /sys/class/dmi/id/product_uuid /etc/machine-id
ExecStart=/usr/bin/sed -i -e 's/\\(.*\\)/\\L\\1/;s/-//g' /etc/machine-id

[Install]
WantedBy=network.target
````

**Comment by crawford** [comment]
This can be done already with [systemd](https://www.freedesktop.org/software/systemd/man/machine-id.html). You can use `systemd.machine_id=` to specify the ID you want to assign. It does require you to maintain that mapping yourself, but it might solve your problem.

**Comment by travisgroth** [comment]
Ah I forgot to mention that.  Yes it is an option, but prohibitively manual.

Matchbox also doesn’t - to my knowledge - support templating in the kernel command line so you’re stuck creating a lot of scaffolding to customize just that option per machine and tell it what the kernel already knows.

A rational approach might be passing in a special value to systemd.machine_id (or a new option) to tell it to actually use the system’s product_uuid as the machine-id without having to inform it of what that is.  I’m not sure how upstream would feel about that; we’re in a special case here when netbooting.  

I think CoreOS can handle this well on its own without much work.  In fact, my unit file could probably be put into the base image with a ConditionKernelCommandLine flag to activate/deactivate it and it would be solved.  I’m not quite familiar enough with the code base to put together a PR but I wouldn’t mind doing so if I was pointed in the right direction.

**Comment by dghubble** [comment]
Matchbox does template the iPXE config [here](https://github.com/coreos/matchbox/blob/master/matchbox/http/ipxe.go#L17), but only with the kernel, initrd, and kernel args defined in a [profile](https://github.com/coreos/matchbox/blob/master/Documentation/matchbox.md#profiles). You'd need to define a profile per machine, which is not unheard of. Its becoming more common in setups where an external tool (like terraform) generates profiles and [writes them to the Matchbox API](https://github.com/coreos/matchbox/blob/master/examples/terraform/modules/profiles/profiles.tf#L11), but I realize that isn't an option for everyone.

There have been requests to allow custom iPXE templates as well https://github.com/coreos/matchbox/issues/92

**Comment by crawford** [comment]
@travisgroth Generally speaking, a machine ID should be unique to the machine lifetime. If you reprovision a machine, you would expect the machine ID to change. In order to address your concerns around DHCP, you might be able to specify the [DUID Type](https://www.freedesktop.org/software/systemd/man/networkd.conf.html#DUIDType=) to create reproducible addresses.

**Comment by travisgroth** [comment]
Ah - I’m wrong on how manual it would be then.  I didn’t realize those got rendered with metadata.  

That said, having to specify a uuid manually is still something that can be easily avoided and would be prone to error.

**Comment by travisgroth** [comment]
@crawford Well, any change to an ignition configuration means "reprovisioning", right?  We're not doing any sideband CM, so systems are exactly as provisioned via ignition and any change is means running ignition again (thus a reboot).  That seems to be the way to manage base configuration on CoreOS at the moment, or am I mistaken?  

So, our re-provisioning is really just a reboot that may change a single config file.  A new UUID every time a node boots (whether it is reconfigured or not) doesn't really make much sense; especially since things that are expected to be more or less static over a logical machine's lifetime are derived from it.  

re: DUIDRawData...The DHCP and MAC churn issues are _symptoms_ of the machine-id changing needlessly so I don't think that's the right way to fix it.  Thus, my thought is to make machine-id more stable than "changes at every boot".  The idea of using hardware uuid is perhaps more persistent than a typical machine-id generated upon OS install; however, I think it is a reasonable approach with a system that has no local state across boots, and probably isn't changing drastically enough to be considered a new and unique system every time.

Manually specifying machine-id (or DUIDRaw or whatever) for every system in matchbox seems like a poor choice as it requires yet another per-system value to be maintained and there is a ready made per-system value already in place (eg, product_uuid).    

Even if using the product_uuid directly isn't a good idea, some way to make the machine-id relatively consistent across minor changes without more configuration overhead seems like a reasonable ask.  I'm open to how that might be accomplished.

**Comment by crawford** [comment]
> Well, any change to an ignition configuration means "reprovisioning", right? We're not doing any sideband CM, so systems are exactly as provisioned via ignition and any change means running ignition again (thus a reboot). That seems to be the way to manage base configuration on CoreOS at the moment, or am I mistaken?

Correct. I generally approach the problem with the understanding that the machine ID maps to a personality rather than a physical machine. Your use-case isn't unreasonable though. It sounds like systemd needs additional functionality to allow users to specify how the machine ID should be derived. That would allow you to create machine IDs in a deterministic manner. It might be helpful if you file an issue upstream. They might have some good tricks to solve your issue.

**Comment by travisgroth** [comment]
>I generally approach the problem with the understanding that the machine ID maps to a personality rather than a physical machine

I agree.  But, without a way to have a consistent machine-id, any change to a CoreOS system is inherently a "new" personality.  That's where I think the issue is.

I'm happy to see if systemd is open to solving.  I'll reference the issue here.

**Comment by bgilbert** [comment]
For the record, #1432 is similar. We fixed it by generating the DHCP client identifier from the MAC address when booted via PXE, but of course that doesn't help when the MAC address is also generated.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
