### ISSUE TITLE
Add Mosh to Container Linux

### ISSUE THREAD

**Issue by eatnumber1** [coreos/bugs#2168]
# Issue Report #

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

Irrelevant

### Desired Feature ###

It would be great if you could add [Mosh](https://mosh.org/) to the Container Linux base image. This is for two reasons:
1. Mosh is useful
2. Mosh cannot be (cleanly) put into a Docker container. The writeup for why is somewhat lengthy, but eventually amounts to the fact that Mosh needs to detach from its controlling terminal _after_ it has performed a key exchange. I'll do a more detailed writeup if requested.

**Comment by squeed** [comment]
You may wish to consider executing mosh as a [rkt fly](https://coreos.com/rkt/docs/latest/running-fly-stage1.html) container, which is basically a chroot. This lets you package mosh as a Docker container but without relying on the docker execution model.

**Comment by deed02392** [comment]
Voting with a comment

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
