### ISSUE TITLE
/usr/share/oem/coreos-install.json doesn't seem to be read

### ISSUE THREAD

**Issue by nealey** [coreos/bugs#2169]
# Issue Report #

## Bug ##

On a new install of CoreOS stable from CD, with Ignition v0.17.2, using the cmdline provider and an `oem://` URL, changes to `usr/share/oem/coreos-install.json` are ignored. I even tried removing the file to see if I could trigger [the code's "Failed to read" error message](https://github.com/coreos/ignition/blob/v0.17.2/internal/resource/url.go#L299) and couldn't.

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.8.0
VERSION_ID=1465.8.0
BUILD_ID=2017-09-20-2237
PRETTY_NAME="Container Linux by CoreOS 1465.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Bare metal, using install CD downloaded today (2017-09-25).

### Expected Behavior ###

Changes to `/usr/share/oem/coreos-install.json` should be reflected in ignition logs (and, by extension, should be used by ignition).

### Actual Behavior ###

Changes to `/usr/share/oem/coreos-install.json` do not appear in ignition logs, only the configuration provided at install shows up. As a result, changes to the file are never seen by ignition.

### Reproduction Steps ###

  1. Boot from CD
  2. Create file `pinto.json` from ignition config below, substituting your SSH public key
  3. `sudo coreos-install -d /dev/sda -i pinto.json`
  4. `sudo reboot`
  5. Log in as `core`
  5. `journalctl _COMM=ignition | grep -q pinto && echo Setup verified`
  6. `sudo sed -i 's/pinto/lima/' /usr/share/oem/coreos-install.json`
  7. `sudo reboot`
  8. Log in as `core`
  9. Observe that the hostname is still `pinto`
  10. `journalctl _COMM=ignition | grep -q pinto && echo You have reproduced the bug`

### Other Information ###

`pinto.json`:

````json
{"ignition":{"version":"2.0.0","config":{}},"storage":{"files":[{"filesystem":"root","path":"/etc/systemd/system.conf.d/10-default-env.conf","contents":{"source":"data:,%5BManager%5D%0ADefaultEnvironment%3D%22http_proxy%3Dhttp%3A%2F%2Fproxyout.lanl.gov%3A8080%22%20%22https_proxy%3Dhttp%3A%2F%2Fproxyout.lanl.gov%3A8080%22%0A","verification":{}},"mode":420,"user":{},"group":{}},{"filesystem":"root","path":"/etc/profile.env","contents":{"source":"data:,export%20http_proxy%3Dhttp%3A%2F%2Fproxyout.lanl.gov%3A8080%0Aexport%20https_proxy%3Dhttp%3A%2F%2Fproxyout.lanl.gov%3A8080%0Aexport%20no_proxy%3D.lanl.gov%0A","verification":{}},"mode":420,"user":{},"group":{}},{"filesystem":"root","path":"/etc/hostname","contents":{"source":"data:,pinto","verification":{}},"mode":420,"user":{},"group":{}}]},"systemd":{"units":[{"name":"update-engine.service","dropins":[{"name":"50-proxy.conf","contents":"[Service]\nEnvironment=ALL_PROXY=http://proxyout.lanl.gov:8080\n"}]}]},"networkd":{},"passwd":{"users":[{"name":"core","sshAuthorizedKeys":["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQT2eyuee5pHmDV91w7fLRk5Hz4hu9OjAZVT+h+4gAW/7l/91qTz79xocQA696Jk4mUJqMi9F3Jz1b+qsN99ukOxyISI861Gd+lg9g27r3GeVpssV2b+vOzZ5kLsojtu5UeTN/g3TvSj3xqVJIcN44RIF5565rEm0Dgntket81+Ke1IhGYxU41T58P66L3k8sMS9I7kSVFpblCKqikjUsVFxrTZBDFJLRsJygXzE8Fnot4LHqO1TDUs+DtlbGrsoth06xa1uslT+9Ah4PQNVmjE+N1ebK5yM9KOLpfAh+EOkihnmH0FG30JblNOFQ/K7Hkg84ogwOV5je9QlUESdnT arcs-sre"]},{"name":"neale","sshAuthorizedKeys":["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwc6FkQ0QKx0Mk/7/feRsx29N4pKfbkkVwq8LR03/vlcZlinxNY5PWmJnDUsMzi/YjzU0HphLl4HxF3vuGMC7xr2z0OhumjQXi7GSvaX8vgYG10eVus7cvu9jScMD77Usx06JZj5FU43Vg2Y8sfrlk7Bk4L0NkQM+mlPn9iGhFIchhJL2EcdNU62rPuGvzfn3npudYNt06sXA8Tl2ur5sk9QNtev2qB0rvv6NtV8T2/ujdPlyYpZUP+eHCghCak9qeYYfhxr8g+NIuDZ8oMVsi8m2i2n5dd/PWRuOTaQvordioQJ/bIss0opr/z1o71Z+jtnlpFlaaTRsl+gbLZKzP neale@cfl"],"create":{"groups":["sudo","docker"]}}]}}
````

**Comment by bgilbert** [comment]
By design, [Ignition runs only on the first boot](https://coreos.com/ignition/docs/latest/what-is-ignition.html#ignition-only-runs-once) to perform initial provisioning of a machine.

What is your goal in modifying the existing configuration?  We might be able to point you to a better way to achieve the same result.

**Comment by nealey** [comment]
Oh!

I was just trying to set the hostname on an incorrectly provisioned machine. No big deal.

Before reading your reply, it was not clear to me from the document you linked that ignition only runs on the first boot. As written I thought it was telling me in only runs once *per session*, like how /sbin/init only runs once. Modifying that document to say "ignition runs only on the first boot" would have helped me a lot.

Thank you very much for your courteous response!

**Comment by bgilbert** [comment]
@nealey Thanks for the feedback!  I've tweaked the wording in https://github.com/coreos/docs/pull/1155.
