### ISSUE TITLE
Backport Docker EBUSY fix to 1.12.6

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2173]
The fix for https://github.com/coreos/bugs/issues/2127 should also be backported to 1.12.6.

**Comment by euank** [comment]
We ultimately settled on backporting the kernel patch. I've tracked the work for that using this issue since it fixes the bug similarly.

**Comment by euank** [comment]
Done for next-beta/next-stable branches. I think we can consider this resolved since the backported kernel patch means 1.12.6 doesn't need the patch.
