### ISSUE TITLE
Ignition line 202 has a typo

### ISSUE THREAD

**Issue by sfchrisgleason** [coreos/bugs#2174]
# Issue Report #

The folder mapping on the gcloud alias has a type on[ line 202](https://github.com/coreos/ignition/blob/v0.17.2/internal/oem/oem.go#L202)

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

Google Cloud

### Expected Behavior ###

The issue is when running docker [people are seeing Torcx errors](https://github.com/coreos/bugs/issues/2112?imz_s=skqcdi0dd3036brb3e1p7p5v40). I just noticed a typo in the alias though.

The container side of the -v folder mapping says 'doker.sock' instead of 'docker.sock'

**Comment by lucab** [comment]
This has been fixed in Ignition by https://github.com/coreos/ignition/pull/427. If I'm properly reading git history, that should be part of release 0.18.0 which is available on ContainerLinux >= 1535.0.0 (i.e. not yet in beta/stable at this time).
