### ISSUE TITLE
CoreOS Install To Disk - login prompt

### ISSUE THREAD

**Issue by naisanza** [coreos/bugs#2175]
# Issue Report #

When booting from a CoreOS ISO, I end up getting a login prompt, with no way of logging in 

### Container Linux Version ###

```
coreos: 1465.7.0
```

### Environment ###

Proxmox 5.0-31

### Expected Behavior ###

1. Boot from CoreOS ISO
2. Get command prompt

### Actual Behavior ###

1. Boot from CoreOS ISO
2. Get login prompt

### Reproduction Steps ###

  1. Boot from CoreOS ISO

**Comment by dm0-** [comment]
How are you booting the ISO?  I downloaded https://stable.release.core-os.net/amd64-usr/1465.7.0/coreos_production_iso_image.iso , and it booted to a shell with no issue.  The ISO bootloader specifies `coreos.autologin`, which means it will not prompt for a password on the console: https://github.com/coreos/scripts/blob/build-1465/build_library/vm_image_util.sh#L652

**Comment by naisanza** [comment]
@dm0- I'm using:

```
553063bebfa3fc594547fc4bb25a98ff  coreos_1465.7.0.iso
```
Downloaded from https://coreos.com/os/docs/latest/booting-with-iso.html 

I'm just booting a new KVM with the ISO attached, how I would boot any other ISO, and letting it pick which ever default grub boot options

**Comment by dm0-** [comment]
The ISO does not use GRUB, so your VM is most likely configured to boot an existing installation from its hard drive.  If you're using QEMU, try adding `-boot once=d` to the command-line.

**Comment by naisanza** [comment]
@dm0- I just discovered, it must have been installed without my knowing
