### ISSUE TITLE
Document iptables systemd units on Container Linux

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2184]
We ship `iptables-store` and `iptables-restore` service files, but we don't document how to use them anywhere.

We should document how to use these servces and how to write a firewall with a Container Linux config (including an example).

There is work to add CT sugar for this https://github.com/coreos/container-linux-config-transpiler/pull/42, but we don't have to block on that; having any docs at all would be an improvement.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
