### ISSUE TITLE
Automatically clean up any leaked kola instances

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2186]
## Bug ##

Our nightly kola tests can leak machines in a number of edge cases.
There's also no 100% reliable way for the tool itself to cleanup since it's perfectly possible the jenkins job running it crashes.

We should run a job outside of kola which handles tracking and cleanup of these resources.

One tool that might come in handy for this is [grafiti](https://github.com/coreos/grafiti) (though that only covers AWS, not other platforms like GCE).
It's possible `grafiti` isn't the right tool though given we have fewer resources we need to cleanup (and tbh parsing cloudtrail logs isn't as nice as using the regular api).
`kola gc` could also be a valid thing to create and run on a timer if it turns out to be simpler.

Note also, `kola spawn` instances should not necessarily be subject to the same cleanup requirements.

**Comment by bgilbert** [comment]
There are now `ore <platform> gc` commands that clean up instances, but not generally images or SSH keys, for all of the above except ESX.

**Comment by euank** [comment]
With ore gc being there, this issue's probably fine to close. Closing...
