### ISSUE TITLE
Ignition blackbox tests fail on non-Container Linux instances

### ISSUE THREAD

**Issue by arithx** [coreos/bugs#2188]
We'd like all tests to run on non-Container Linux instances. Currently several tests fail on other distros.

Tests currently failing on Fedora:

- [ ] CreateFileFromRemoteContentsTFTP
- [ ] ReplaceConfigWithRemoteConfigTFTP
- [ ] AppendConfigWithRemoteConfigTFTP
- [ ] AddingUsers

Tests currently failing on Arch:

- [ ] AddingUsers
- [ ] ReuseExistingFilesystem

**Comment by dgonyeo** [comment]
@arithx with the recent improvements to running the blackbox tests locally, want to give running them on Fedora another shot?

**Comment by arithx** [comment]
Re-ran on Fedora and still seeing the same tests failing along with `AddingUsers`. @dgonyeo @ajeddeloh are all tests passing on Arch/Gentoo?

**Comment by dgonyeo** [comment]
I'm seeing `Adding_users` and `Reuse_Existing_Filesystem` fail on Arch.

```
Jan 11 14:01:36 proton ignition[353]: files: createUsers: op(4): [failed]   adding ssh keys to user "test": unable to lookup user "test"
Jan 11 14:01:36 proton ignition[353]: files: failed to create users/groups: failed to create users: failed to add keys to user "test": unable to lookup user "test"
```

```
--- FAIL: TestIgnitionBlackBox (4.37s)
    --- FAIL: TestIgnitionBlackBox/Reuse_Existing_Filesystem (4.36s)
    	blackbox_test.go:130: Reuse Existing Filesystem
    	filesystem.go:34: mount exit status 32 mount: /var/tmp/ignition-blackbox-489379491/hd1p0: /dev/loop16p1 already mounted or mount point busy.
```

**Comment by arithx** [comment]
Updated original ticket to add `AddingUsers` to Fedora failures & add Arch failure tracking.

**Comment by ajeddeloh** [comment]
They all pass for me on gentoo now (except that reuse filesystems flake). Can anyone with fedora verify they pass there?

**Comment by dgonyeo** [comment]
They also all pass for me on Fedora (except that flake).

**Comment by ajeddeloh** [comment]
Cool, closing this in that case.
