### ISSUE TITLE
Add Google Cloud OS Login components to Container Linux

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2189]
# Issue Report #

### Environment ###

GCE

### Desired Feature ###

Support GCE OS Login in Container Linux.

### Other Information ###

https://github.com/GoogleCloudPlatform/compute-image-packages/tree/master/google_compute_engine_oslogin

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/coreos-overlay/pull/3319
