### ISSUE TITLE
Question: "Temporarily support a flag file to switch Docker versions"

### ISSUE THREAD

**Issue by jrave9000** [coreos/bugs#2191]
Does it mean that one could use docker v17 in the stable release? And if 'yes', where could one read about it?

Thank you.
I'm sorry if I'm asking at the wrong place or asking something evident, but I just can't find literally anything.

**Comment by bgilbert** [comment]
Hi @jrave9000, thanks for checking.  More information on this will be available soon; we're still working on writing up the details.  I'll update this issue once the docs are ready.

**Comment by klausenbusk** [comment]
I just stumbled on this Gist: https://gist.github.com/dm0-/66f8375418a8f2369070a2f5902ec5f0 , for what it worth..

**Comment by bgilbert** [comment]
We've just released a [blog post](https://coreos.com/blog/toward-docker-17-in-container-linux) documenting the flag file and announcing a timeline for switching Container Linux to Docker CE 17.xx by default. Thanks for your patience.
