### ISSUE TITLE
Add pam_oath.so/OATH Toolkit for SSH 2Fa

### ISSUE THREAD

**Issue by klausenbusk** [coreos/bugs#2194]
# Issue Report #

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
DigitalOcean

### Desired Feature ###
For SSH 2Fa it could be very useful if the [`pam_oath.so`](http://www.nongnu.org/oath-toolkit/pam_oath.html) module could get added to the image.

### Other Information ###
It is very easy to configure, when the right pam modules is in place: https://wiki.archlinux.org/index.php/Pam_oath

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
