### ISSUE TITLE
Oracle iSCSI device is not necessarily firewalled from containers using host networking

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2197]
In https://github.com/coreos/coreos-overlay/pull/2753 we implemented some firewalling for traffic to the iscsi address for security reasons.

However, these rules don't catch containers with `--net=host` (unless they use `--user` or are using user namespaces).

I think we can do better. We should be able to identify the iscsid process by its cgroup, and therefore distinguish it from other, potentially containerized, processes.
Furthermore, eBPF programs to do network filtering can be attached to cgroups.
One example of this is the features added to systemd in v235 with [ip access lists](http://0pointer.net/blog/ip-accounting-and-access-lists-with-systemd.html).
It's possible we can use that relatively unmodified (block the iscsi ip on the root slice, allow it for iscsid specifically), but even if we can't it's possible it can provide inspiration for a better solution.

**Comment by bgilbert** [comment]
iscsiadm commands run by the root user may also need access.  iscsiadm does almost everything via iscsid, but I don't think everything.
