### ISSUE TITLE
Document channel upgrade/downgrade support & semantics

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2198]
Our documentation [here](https://coreos.com/os/docs/latest/switching-channels.html) does not make it clear what combination of channel upgrades downgrades is supported.
This is probably because we haven't given this much thought, and historically it hasn't caused any major problems.

I will assert here that we should not support "downgrading" channels (from alpha towards stable), but should be comfortable with "upgrading" channels (from stable towards alpha).

The primary reason we should not support such "downgrades" is that it can incidentally lead to downgrading software we've intentionally "held back" in the beta or stable channel. One example of an issue this causes is #2195.

**Comment by xueshanf** [comment]
@euank I was able to rebuild to solve the problem. My downgrade was not intentional. BTW, I looked up the doc  https://coreos.com/os/docs/latest/switching-channels.html, which might need a bit of clarification. Thanks for fast response!

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
