### ISSUE TITLE
Coreos doesn't include bash completion for docker

### ISSUE THREAD

**Issue by jmmills** [coreos/bugs#22]
Via vagrant coreos image doesn't include bash completion via docker

**Comment by port22** [comment]
this isn't working (anymore), and I am not able to find the bash-completion file in the moby repo. any hints where I can find it ?
Anyway, adding bash-completion for docker wouldn't increase the size of the coreos image noticeably, but using docker is almost the only reason to use coreos , in my opinion that would make a lot of sense to add it, since the "real" coreos iso includes it too.

**Comment by port22** [comment]
finally found it:

https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker

and take bash-completion from toolbox, then copy /usr/share/bash-completion to /media/root/...

**Comment by gcstang** [comment]
@port22 do you have any other instructions, this doesn't seem to work anymore.
Container Linux by CoreOS stable (1576.5.0)

**Comment by port22** [comment]
I still use it. Make sure that your bashrc is actually sourced when you log in. 
You got the bash-completion file from fedora toolbox and the linked docker-completion file and sourced them in your bashrc?
where are you stuck?

**Comment by gcstang** [comment]
I got it to work, found another script someone wrote.

[bash_completion_script](https://gist.githubusercontent.com/franciscocpg/a7c87d86696293b4e6d74ef5ee0a2c8e/raw/ec644d1342ca751d5bc792a542abbe0f1e08339c/install.sh)

**Comment by vladkras** [comment]
> I got it to work, found another script someone wrote.
>
> bash_completion_script
this script is not working and fails with
```
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-03 13:44:23 ERROR 404: Not Found.
```
cause https://raw.githubusercontent.com/docker/docker/master/contrib/completion/bash/docker is really 404

**Comment by vladkras** [comment]
So i fixed it with
```
$ toolbox 
# dnf -y install bash-completion
# wget https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker -O /usr/share/bash-completion/completions/docker
# exit
$ toolbox cp /usr/share/bash-completion /media/root/var/ -R 
$ echo "source /var/bash-completion/bash_completion" >> ~/.bashrc
```
 **don't forget to backup your ~/.bashrc!**!!

**Comment by port22** [comment]
> don't forget to backup your ~/.bashrc!!!

you can also put a file in `/etc/bash/bashrc.d/` defined via ignition
