### ISSUE TITLE
Ignition doesn't report fetch timeouts/retries to console

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2206]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1562.1.0
VERSION_ID=1562.1.0
BUILD_ID=2017-10-12-0536
PRETTY_NAME="Container Linux by CoreOS 1562.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

DigitalOcean

### Expected Behavior ###

Ignition reports failed fetch attempts and retries to the console when fetching a remote resource (e.g. using the `files` object).

### Actual Behavior ###

Ignition logs failures and retries to the journal but not to the console.

### Reproduction Steps ###

  1. Boot an Ignition config with a `files` object referencing a remote resource which times out when accessed.
  2. Wait for status messages on the console.

### Other Information ###

Now that the default timeout is infinite, a fetch timeout results in Ignition hanging forever without much evidence of what went wrong.  This used to be more verbose.

**Comment by crawford** [comment]
Hmmm, is [00-forward-to-console.conf](https://github.com/coreos/bootengine/blob/master/dracut/99journald-conf/00-forward-to-console.conf) not taking effect?

**Comment by bgilbert** [comment]
Those messages are logged at priority `debug` now, and `MaxLevelConsole` defaults to `info`.

**Comment by crawford** [comment]
:(

**Comment by ajeddeloh** [comment]
Do we want bump log levels in general? It would be helpful while debugging in general. In terms of noise on things like journald, you can filter that with `journalctl --priority` if you don't want it.

**Comment by bgilbert** [comment]
Defaulting to noisy logs isn't great for users.  I think it'd be better to limit the fix to this particular case for now.
