### ISSUE TITLE
Document collecting kernel crash dumps on VMs without pstore

### ISSUE THREAD

**Issue by schneidexe** [coreos/bugs#2210]
# Issue Report #

pstore not working on Vmware 5.5 and Vagrant 1.9.4/VirtualBox5.1.22/MacOS10.12.6

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1548.2.0
VERSION_ID=1548.2.0
BUILD_ID=2017-10-12-0514
PRETTY_NAME="Container Linux by CoreOS 1548.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Vmware vSphere ESXi 5.5 or Vagrant 1.9.4/VirtualBox5.1.22 on MacOS 10.12.6 . Neither works.

### Expected Behavior ###

When following https://coreos.com/os/docs/latest/collecting-crash-logs.html after running ```echo c > /proc/sysrq-trigger``` and rebooting the machine should have a kernal crash log in ```/sys/fs/pstore```

### Actual Behavior ###

```/sys/fs/pstore``` is empty

### Reproduction Steps ###

  1. run ```echo c > /proc/sysrq-trigger```
  2. wait for reboot
  3. ssh in
  4. ```ls /sys/fs/pstore```

### Environment ###

see above

### Desired Feature ###

The FAQ article states that if _the hardware support is absent, the pstore will remain empty_.
Are there any known setup where pstore on CoreOS works out of the box? Are vSphere and Vagrant/VirtualBox known to not support pstore?

**Comment by bgilbert** [comment]
pstore is primarily helpful for bare-metal systems, where it's otherwise difficult to extract logs after kernel crashes.  I don't know for sure, but I wouldn't expect ESXi or VirtualBox to support pstore and couldn't immediately find evidence that they do.

Container Linux generally reports kernel crashes both to the VGA console and to the first serial port.  On most virtualization platforms, the serial port is probably the easiest way to collect crash logs.  Both ESXi and VirtualBox should allow you to attach the VM serial port to a file on the host.

**Comment by schneidexe** [comment]
Hi. Thanks for the fast reply. Yeah, was already expecting that there is a lack of support. VGA in vSphere UI was not very helpful as c&p pretty much sucks there and default 80x25 lines default is usually too small. I'll give serial port a try. 

Maybe also the docs at https://coreos.com/os/docs/latest/collecting-crash-logs.html should be extended with some practices for virtual environments like Vmware, Vbox or AWS as those are very common. Most scenarios I know (incl. my own) people run containers on VMs rather then BMs and it's awesome to have those as phoenix VMs with CoreOs.

**Comment by luis-silva** [comment]
This works on VMWare if you enable `efi` boot for the guest VM. It's been supported since ESXi 5.0 according to [this](https://communities.vmware.com/docs/DOC-28494) document.

You can confirm pstore is using the efi backend by running:
```
# cat /sys/module/pstore/parameters/backend
efi
```

test the kernel panic with 
```
echo c > /proc/sysrq-trigger
```

And then after reboot you'll find:
```
# ls -l /sys/fs/pstore/
-r--r--r--. 1 root root 1790 Apr 23 20:03 dmesg-efi-152451379201001
-r--r--r--. 1 root root 1800 Apr 23 20:03 dmesg-efi-152451379201002
-r--r--r--. 1 root root 1815 Apr 23 20:03 dmesg-efi-152451379202001
-r--r--r--. 1 root root 1803 Apr 23 20:03 dmesg-efi-152451379202002
-r--r--r--. 1 root root 1787 Apr 23 20:03 dmesg-efi-152451379203001
-r--r--r--. 1 root root 1776 Apr 23 20:03 dmesg-efi-152451379203002
-r--r--r--. 1 root root 1779 Apr 23 20:03 dmesg-efi-152451379204001
-r--r--r--. 1 root root 1826 Apr 23 20:03 dmesg-efi-152451379204002
-r--r--r--. 1 root root 1806 Apr 23 20:03 dmesg-efi-152451379205001
-r--r--r--. 1 root root 1776 Apr 23 20:03 dmesg-efi-152451379205002
-r--r--r--. 1 root root 1724 Apr 23 20:03 dmesg-efi-152451379206001
-r--r--r--. 1 root root 1765 Apr 23 20:03 dmesg-efi-152451379206002
-r--r--r--. 1 root root 1760 Apr 23 20:03 dmesg-efi-152451379207001
-r--r--r--. 1 root root 1645 Apr 23 20:03 dmesg-efi-152451379207002
-r--r--r--. 1 root root 1646 Apr 23 20:03 dmesg-efi-152451379208001
-r--r--r--. 1 root root 1777 Apr 23 20:03 dmesg-efi-152451379208002
-r--r--r--. 1 root root 1806 Apr 23 20:03 dmesg-efi-152451379209001
-r--r--r--. 1 root root 1776 Apr 23 20:03 dmesg-efi-152451379209002
-r--r--r--. 1 root root 1806 Apr 23 20:03 dmesg-efi-152451379210001
-r--r--r--. 1 root root 1757 Apr 23 20:03 dmesg-efi-152451379210002
-r--r--r--. 1 root root 1771 Apr 23 20:03 dmesg-efi-152451379211001
-r--r--r--. 1 root root 1754 Apr 23 20:03 dmesg-efi-152451379211002
-r--r--r--. 1 root root 1806 Apr 23 20:03 dmesg-efi-152451379212001
-r--r--r--. 1 root root 1826 Apr 23 20:03 dmesg-efi-152451379212002
-r--r--r--. 1 root root 1795 Apr 23 20:03 dmesg-efi-152451379213001
-r--r--r--. 1 root root 1795 Apr 23 20:03 dmesg-efi-152451379213002
-r--r--r--. 1 root root 1792 Apr 23 20:03 dmesg-efi-152451379214001
-r--r--r--. 1 root root 1798 Apr 23 20:03 dmesg-efi-152451379214002
-r--r--r--. 1 root root 1792 Apr 23 20:03 dmesg-efi-152451379215001
-r--r--r--. 1 root root 1824 Apr 23 20:03 dmesg-efi-152451379215002
-r--r--r--. 1 root root 1819 Apr 23 20:03 dmesg-efi-152451379216001
-r--r--r--. 1 root root 1768 Apr 23 20:03 dmesg-efi-152451379216002
-r--r--r--. 1 root root 1814 Apr 23 20:03 dmesg-efi-152451379217001
-r--r--r--. 1 root root 1024 Apr 23 20:03 dmesg-efi-152451379217002
```

Hope this helps the next person trying to get this to work with VMWare.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
