### ISSUE TITLE
consider supporting pre and post hooks to update_engine

### ISSUE THREAD

**Issue by coresolve** [coreos/bugs#2214]
## Feature Request ##
Consider supporting pre and post hooks for the update engine.
There may be times when users need to pull in libraries or other dependencies to the base os. If update_engine supported a pre hook we could notify that the kernel and libs may need to change. On post hook we could wait until the post hook was completed before hitting the multi-user target. 

This would enable the ability to compile new kernel modules if needed as well as pull a new version of a lib after reboot and ensure that the new version of lib is available before the system comes up. 

### Environment ###
What hardware/cloud provider/hypervisor is being used to run Container Linux?
All
### Desired Feature ###
Please consider supporting pre and post hooks to update_engine.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
