### ISSUE TITLE
Consider adding bash completions

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2217]
# Issue Report #

### Environment ###

All

### Desired Feature ###

Include bash completions in the OS image.

### Other Information ###

Bash completions make the shell experience more pleasant, e.g. with `systemctl` and friends. Their absence adds friction for admins coming from other distros. https://github.com/coreos/bugs/issues/22#issuecomment-48755431 says we don't ship them for space reasons, but it might be useful to quantify that a bit.

**Comment by port22** [comment]
finally found it:

https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker

and take bash-completion from toolbox, then copy /usr/share/bash-completion to /media/root/...

summing up to 172kb what you saved. just saying .

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
