### ISSUE TITLE
Add notrap to default options for restricted hosts in ntpd.conf

### ISSUE THREAD

**Issue by brianredbeard** [coreos/bugs#2220]
# Issue Report #

## Feature Request ##

Add `notrap` to default options for restricted hosts in `ntpd.conf` 

> The notrap option prevents ntpdc control message protocol traps. 

As per section 2.2.1.2 of the CIS security benchmark for generic Linux hosts.

**Comment by bgilbert** [comment]
`ntpd` is not enabled by default, but we should still do this.

**Comment by bgilbert** [comment]
This should be fixed in alpha 1786.0.1, due shortly.  Thanks for reporting.
