### ISSUE TITLE
Ignition failures aren't obviously Ignition failures

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2227]
# Issue Report #

### Environment ###

Any

### Desired Feature ###

When Ignition fails and drops to an emergency shell, clearly announce what has happened and how to get more information.

### Other Information ###

Users often don't correlate an emergency shell prompt with a bad Ignition config. Often users send a screenshot of the prompt itself, several screens after the actual Ignition error.

**Comment by dgonyeo** [comment]
random potentially messy and bad idea for this: replace the emergency shell with something that'll give you the failed Ignition logs in less, and upon quitting less drop you into the shell

**Comment by bgilbert** [comment]
It's also possible to reach the emergency shell for reasons unrelated to Ignition, so we'd need to take that into account.

**Comment by dgonyeo** [comment]
Ignition could do the work to do the replacement once it encounters an error

**Comment by ajeddeloh** [comment]
In general I think we want to keep CL specific things out of Ignition (unless we want to revisit that decision). It might be possible to have the emergency shell detect if Ignition has failed, and if so either reguritate Ignition's logs or spit out instructions on how to get them.

**Comment by bgilbert** [comment]
Dumping the logs is better for platforms that don't have interactive console access.

**Comment by bgilbert** [comment]
Fixed in https://github.com/coreos/bootengine/pull/142 in 1758.0.0.
