### ISSUE TITLE
Ignition creation of filesystem timeout failure.

### ISSUE THREAD

**Issue by Denikin80** [coreos/bugs#2228]
# Issue Report #

'Bug'

### Container Linux Version ###
1520.8.0
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

VmWare 5.5 vm (2GB RAM, 100Gb HDD) booted and configured via ipxe and Matchbox

### Expected Behavior ###
configured via ignition config file
### Actual Behavior ###
creation of filesystem failed with timeout
### Reproduction Steps ###

  1. preboot env (DHCP, tFTP, DNS, iPXE, Matchbox)
  2. booting vm via PXE chain > core.ipxe

### Other Information ###
pxe-config-core1.ign:

```
{
  "ignition": {
    "version": "2.1.0",
    "config": {}
  },
    "storage": {
    "disks": [{
        "device": "/dev/sda",
        "wipeTable": true,
        "partitions": [{
            "label": "ROOT",
            "number": 0,
            "size": 0,
            "start": 0
          }]
     }],
   "filesystems": [{
       "mount": {            
                "device": "/dev/disk/by-label/ROOT",
                "format": "ext4",
                "wipeFilesystem": true,
                "options": [ "--label=ROOT" ]
                }
           }] ,
    "files": [{
      "filesystem": "root",
      "path": "/etc/hostname",
      "mode": 420,
      "contents": { "source": "data:,core1" }
    },
     { "filesystem": "root",
      "path": "/etc/resolv.conf",
      "mode": 420,
      "contents": { "source": "http://192.168.120.222:8080/assets/resolv.conf" }
    }]
  },
  "systemd": {
    "units": [
      {
        "name": "etcd-member.service",
        "enable": true,
        "dropins": [
          {
            "name": "20-clct-etcd-member.conf",
            "contents": "[Service]\nExecStart=\nExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS \\\n  --name=\"my-etcd-1\" \\\n  --listen-peer-urls=\"https://192.168.120.170:2380\" \\\n  --listen-client-urls=\"https://192.168.120.170:2379,https://127.0.0.1:2379\" \\\n  --initial-advertise-peer-urls=\"https://192.168.120.170:2380\" \\\n  --initial-cluster=\"my-etcd-1=https://192.168.120.170:2380,my-etcd-2=https://192.168.120.171:2380,my-etcd-3=https://192.168.120.172:2380\" \\\n  --initial-cluster-state=\"new\" \\\n  --initial-cluster-token=\"my-etcd-token\" \\\n  --advertise-client-urls=\"https://192.168.120.170:2379\" \\\n --auto-tls \\\n --peer-auto-tls"
          }
        ]
      }
    ]
  },
  "networkd": {
    "units": [{
      "name": "00-ens32.network",
      "contents": "[Match]\nName=ens32\n\n[Network]\nAddress=192.168.120.170/24\nGateway=192.168.120.203\nDNS=192.168.120.200\nDNS=8.8.8.8"
    }]
  },
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa blablalbaKXnvtVJCi/IApssa8F979lCbgDjC8t/4IHtO5G1ESh3VusQGoI9+Ms4kK6/GoQPPOesq+2rucbglpxyfBjO8Td9RaOsUD root@faiserver"
        ]
      }
    ]
  }
}
```

and the screenshots of "journalctl" command:
https://ibb.co/nu6QFw
https://ibb.co/mQ6goG

**Comment by bgilbert** [comment]
You've given the `/dev/sda1` _partition_ the label `ROOT`, but that partition doesn't have a filesystem in it yet, so there is no _filesystem_ labeled `ROOT`. As a result, `/dev/disk/by-label/ROOT` won't exist. You can fix your Ignition config by changing the `mount` object to refer to `/dev/disk/by-partlabel/ROOT` instead.

By the way, in the Ignition 2.1 spec you can specify `"label": "ROOT"` instead of `"options": ["--label=ROOT"]`.

**Comment by Denikin80** [comment]
fixed ignition config with your reccomendation:
{
  "ignition": {
    "version": "2.1.0",
    "config": {}
  },
    "storage": {
    "disks": [{
        "device": "/dev/sda",
        "wipeTable": true,
        "partitions": [{
            "label": "ROOT",
            "number": 0,
            "size": 0,
            "start": 0
          }]
     }],
   "filesystems": [{
       "mount": {            
                "device": "/dev/disk/by-partlabel/ROOT",
                "format": "ext4",
                "wipeFilesystem": true,
                "label": "ROOT"
                }
           }] ,
    "files": [{
.....

but failed:
https://ibb.co/eit2TG

**Comment by ajeddeloh** [comment]
It sounds like it could be this: https://github.com/coreos/ignition/blob/master/NEWS#L23, which is fixed in Ignition 0.19.0. Can you try on beta and see if the problem persists?

**Comment by Denikin80** [comment]
> It sounds like it could be this: https://github.com/coreos/ignition/blob/master/NEWS#L23, which is fixed in Ignition 0.19.0. Can you try on beta and see if the problem persists?

Thanks! It works!

**Comment by Denikin80** [comment]
Can you give me quick solution to avoid this problem ( - Fix partition number validation where multiple partitions on a disk were
unable to specify 0 for the next available partition number) ?
cause i don't want use beta version

**Comment by bgilbert** [comment]
The workaround to that partition number validation problem is to specify non-zero partition numbers. On the other hand, the race condition @ajeddeloh mentioned has no effective workaround; it should be fixed in the stable release due on December 6.
