### ISSUE TITLE
Make "needs reboot" update_engine status more accessible

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2233]
### Background

On Container Linux, [`update_engine`](https://github.com/coreos/update_engine) sends a dbus signal when an update has been applied and the machine should be rebooted.
Locksmith, [CLUO](https://github.com/coreos-inc/container-linux-update-operator), or some third-party tool may listen for that signal and coordinates reboots.

### Feature request

`update_engine` should also write a `/var/run/reboot-required` file when an update is ready to be rebooted into. Checking for the existence of a file is far simpler than interacting with a dbus api.

The primary goal of this change is to make implementing `locksmithd` like tools simpler.

Note, that filename is already used by `dpkg` based distros (such as Debian and Ubuntu) to indicate a reboot is needed for e.g. a kernel update.
This is semantically similar to what `update_engine`'s "needs reboot" status means, so I think that re-using the same file is reasonable.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
