### ISSUE TITLE
Virtualbox + Ignition documentation

### ISSUE THREAD

**Issue by euank** [coreos/bugs#2238]
## Bug ##

Per the discussion in https://github.com/coreos/bugs/issues/1573, there's now a mechanism to use Ignition in virtualbox. However, we don't provide any tooling nor guides for doing so.

We have a [Virtualbox guide](https://coreos.com/os/docs/latest/booting-on-virtualbox.html), but it only provides cloud-config instructions.

The existing documentation should be updated, as well as any tooling needed to make this easier.

One possible approach is for `ct` to be augmented to optionally output a virtualbox-compatible gpt raw disk for this use-case, though a separate `.ign -> .ign.gpt` tool would also be useful in some cases.

**Comment by bgilbert** [comment]
Note that there's some OEM rearranging that needs to be done beforehand.

**Comment by euank** [comment]
The `ct` thing would also have to be run by more people. i'm not really sure if that would be considered in-scope or not. cc @crawford if you'd like to have an opinion.

**Comment by crawford** [comment]
I'm leaning toward a separate tool to enclose the Ignition config in a GPT image, but I do worry about the added complexity of having to use so many different tools.

**Comment by bgilbert** [comment]
In principle the tool could also add the disk to a VM via the VBox API, but that may be more work than we want to take on.  Similar tooling would be useful for VMware Workstation and libvirt as well (#1976).

**Comment by euank** [comment]
Container Linux is deprecated. Closing this PR as stale.
