### ISSUE TITLE
Automatically move pstore logs to permanent storage

### ISSUE THREAD

**Issue by arithx** [coreos/bugs#2249]
## Feature Request ##

Automatically move logs from pstore to permanent storage. Currently users must manually move the logs out of pstore to prevent them from filling up, [documentation](https://coreos.com/os/docs/latest/collecting-crash-logs.html) recommends doing this at boot time. This will prevent situations where long-running machines do not have newer logs.

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

All

**Comment by euank** [comment]
xref https://github.com/systemd/systemd/blob/v235/TODO#L568; ideally I'd say this should be implemented in journald

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
