### ISSUE TITLE
consider moving ssh logging to VERBOSE by default (or allow option)

### ISSUE THREAD

**Issue by wt** [coreos/bugs#225]
The openssh VERBOSE level of logging only adds a little additional information about users that are logging in, like the key fingerprint of the successfully authenticated key. It would be great it if I could turn on that level of logging without writing out a completely custom /etc/ssh/sshd_config file, like mentioned at [[1](https://coreos.com/docs/cluster-management/setup/customizing-sshd/)].

I believe that the level of extra logging at VERBOSE is actually quite minimal and should be considered for a default instead of an option. However, it would be great to have even an option.

**Comment by marineam** [comment]
Well, the way to do this is either replace sshd_config or update the service unit with something like:

`/etc/systemd/system/sshd@.service.d/logging.conf`:
```
[Service]
ExecStart=-/usr/sbin/sshd -i -e -o LogLevel=VERBOSE
```

You can add that via cloud-config with the drop-ins option: https://coreos.com/docs/cluster-management/setup/cloudinit-cloud-config/#units

I would rather leave the default config at the default log level.
