### ISSUE TITLE
Ingition should support .network dropins

### ISSUE THREAD

**Issue by redbaron** [coreos/bugs#2250]
## Feature Request ##

Ignition should support `.network`  dropins. Trying to solve https://github.com/coreos/bugs/issues/1432 in a least intrusive way possible, and found that it is not supported:
  * systemd.units complains about unexpected target unit type
  * networkd.unitd doesn't have dropins section at all.

**Comment by bgilbert** [comment]
Thanks for pointing this out.  As a workaround, you should be able to use the `files` section.

**Comment by crawford** [comment]
> systemd.units complains about unexpected .target unit type

That's odd. Judging by [the code](https://github.com/coreos/ignition/blob/458e5668f5359b08b4c6f8574fdac157be252820/config/types/unit.go#L47) I would have assumed target units worked.

> networkd.unitd doesn't have dropins section at all.

Network units don't support drop-ins (do they?).

**Comment by dm0-** [comment]
Network drop-ins were added in v232: https://github.com/systemd/systemd/blob/master/NEWS#L997-L998

**Comment by crawford** [comment]
Oops, I must have missed that. Ignition should pick up support for the drop-ins then.

**Comment by redbaron** [comment]
> That's odd. Judging by the code I would have assumed target units worked.

sorry, there was a typo in my report. systemd.units complains about `.network` unit type with error saying that systemd unit type is invalid

**Comment by crawford** [comment]
Ah, yeah that makes sense. The `systemd` section cannot be used for networkd units. As @bgilbert pointed out, you'll need to use the `storage.files` section as a workaround for now.
