### ISSUE TITLE
Ignition should support data: protocol for append/replace config urls

### ISSUE THREAD

**Issue by colhom** [coreos/bugs#2251]
Feature request. Currently append/replace block source fields support `http, https, s3, and tftp`, but not the data URL.

File sources support `http, https, tftp, s3, and data` protocols. 

Ideally ignition would support the same protocol set across append/replace config sources and ignition files.

\cc @crawford

**Comment by bgilbert** [comment]
@colhom What's the use case?

**Comment by colhom** [comment]
Modular/heirachical ignition config construction, but without remote
storage requirement (no managing of remote s3/http/https config blobs
necessary to implement nested config structure if you're using data urls.)

**Comment by crawford** [comment]
Hmm, it's a bit surprising that this doesn't work. I agree that this should be possible.

**Comment by arithx** [comment]
Append & Replace both do actually support data urls. We need to update the documentation and add additional blackbox tests.
