### ISSUE TITLE
CL obtains different IP adresses from DHCP when PXE booting and running from disk

### ISSUE THREAD

**Issue by redbaron** [coreos/bugs#2252]
## Bug ##

After https://github.com/coreos/bugs/issues/1432, Container Linux receives different IP addresses during PXE stage and after OS is installed. 

yy-pxe.network:

```...
[DHCP]
ClientIdentifier=mac
UseMTU=true
UseDomains=true
```

zz-default.network:

```
...
[DHCP]
UseMTU=true
UseDomains=true
```

What happens in my case, PXE starts, downloads Ignition config from matchbox and calls coreos-install. If Igntion config is templated with values of the {net0/ip:ipv4}, then it become invalid on a subsequent boot :( If Container Linux continues to use DUID, then this quirk at least should be documented in a PXE booting docs.

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

```

### Environment ###

bare-metal, DHCP

### Expected Behavior ###

 PXE booted and os-installed servers should receive same IP address from DHCP.

### Actual Behavior ###

PXE booted server uses MAC as client ID and os-installed use DUID which causes DHCP server to issue a different IP address.

**Comment by nexusofdoom** [comment]
I have same issue with pxe booting live lubuntu desktop over network it gets two IP address 
it started doing this after upgrading to 18.04.1 version 18.04 worked a ok.

**Comment by bgilbert** [comment]
@nexusofdoom This issue tracker is for CoreOS Container Linux, not Lubuntu.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
