### ISSUE TITLE
Multipathd fails

### ISSUE THREAD

**Issue by tailtwo** [coreos/bugs#2254]
# Issue Report #

## Bug ##

Creating multipaths fails. When using the default multipathd.service, some kernel modules aren't found and it may hinder the process.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Bare-metal with amd64 architecture. 1814 IBM System Storage. Two FC HBA.

`/etc/multipath.conf` custom configuration :

```bash
defaults {
        user_friendly_names     yes
        polling_interval        10
        path_selector           "round-robin 0"
        path_grouping_policy    multibus
        path_checker            readsector0
        rr_min_io               100
        max_fds                 8192
        rr_weight               priorities
        failback                immediate
        no_path_retry           fail
}

blacklist {
        devnode                 "^sd[a-z]"
}

blacklist_exceptions {
        devnode                 "^sd[a-d]"
}

multipaths {
        multipath {
                wwid           "3600a0b80005670740000225b52f899a9"
                alias           mpatha
        }
        multipath {
                wwid           "3600a0b80005671660000216a52e23446"
                alias           mpathb
        }
}
```

### Expected Behavior ###

multipathd.service should be able to create two multipath devices : mpatha and mpathb.

### Actual Behavior ###

After launching the multipath daemon, the multipath creation fail.

The error thrown from multipathd.conf :

```bash
Nov 15 17:36:07 systemd[1]: Starting Device-Mapper Multipath Device Controller...
Nov 15 17:36:07 modprobe[18530]: modprobe: WARNING: Module scsi_dh_alua not found.
Nov 15 17:36:07 modprobe[18530]: modprobe: WARNING: Module scsi_dh_emc not found.
Nov 15 17:36:07 modprobe[18530]: modprobe: WARNING: Module scsi_dh_rdac not found.
Nov 15 17:36:07 systemd[1]: Started Device-Mapper Multipath Device Controller.
Nov 15 17:36:07 multipathd[18534]: path checkers start up
Nov 15 17:36:07 multipathd[18534]: mpatha: ignoring map
Nov 15 17:36:07 multipathd[18534]: mpathb: ignoring map
Nov 15 17:36:07 multipathd[18534]: mpatha: ignoring map
Nov 15 17:36:07 multipathd[18534]: mpathb: ignoring map
Nov 15 17:36:07 multipathd[18534]: dm-1: remove map (uevent)
Nov 15 17:36:07 multipathd[18534]: dm-1: remove map (uevent)
```

Kernel logs :

```bash
Nov 15 17:01:01 kernel: device-mapper: table: 254:1: multipath: error attaching hardware handler
Nov 15 17:01:01 kernel: device-mapper: ioctl: error adding target to table
Nov 15 17:01:02 kernel: device-mapper: table: 254:1: multipath: error attaching hardware handler
Nov 15 17:01:02 kernel: device-mapper: ioctl: error adding target to table
```

### Reproduction Steps ###

  1. Have coreos installed on bare-metal and connected to a SAN by two separate HBA.
  2. Configure /etc/multipathd.conf
  3. Launch multipathd.service or the `multipathd -d -s` command

### Other Information ###

I'm a beginner in the network storage field, so it may be possible I missed something in the configuration. Thank you for noticing me if necessary. :smiley:

**Comment by redbaron** [comment]
New CoreOS version have scsi_dh_* modules, try again :) Also worth trying to run it with no `mulitpath.conf` at all, builtin defaults are reasonable enough

**Comment by lucab** [comment]
Devices handler modules were fixed after https://github.com/coreos/bugs/issues/2254. The rest of this report might sound like a misconfiguration on `multipath.conf`, but I don't know much about multipathd.

@tailtwo can you please re-check with latest release, and try to minimize configuration to see what is wrong? I fear your multipath mappings may be off.

**Comment by lucab** [comment]
Lacking any further feedback and reproducer, I'm going to close this ticket. This has likely been fixed by newer CL releases, or by adjusting the configuration.
If anybody is hitting this, please try to reproduce with a minimal configuration on latest alpha and let us know.

**Comment by redbaron** [comment]
Multipath handling is completely broken in Kubernetes and is not fit for purpose:  https://github.com/kubernetes/kubernetes/issues/59946#issuecomment-380401916
