### ISSUE TITLE
coreos-metadata running before network is up

### ISSUE THREAD

**Issue by dgonyeo** [coreos/bugs#2259]
It might make sense for the coreos-metadata unit to wait to run until after `systemd-networkd` has started.

Here's logs from support:

```
Nov 01 21:03:11 localhost update_engine[1227]: I1101 21:03:11.402587  1227 main.cc:89] CoreOS Update Engine starting
Nov 01 21:03:11 localhost dbus[1295]: [system] Successfully activated service 'org.freedesktop.systemd1'
Nov 01 21:03:11 localhost systemd[1]: Reached target Load system-provided cloud configs.
Nov 01 21:03:11 localhost systemd[1]: Reached target Load user-provided cloud configs.
Nov 01 21:03:11 localhost coreos-metadata[1267]: Fetching "http://169.254.169.254/2009-04-04/meta-data/instance-id": Attempt #1
Nov 01 21:03:11 localhost ethos-diagnostics-components[1254]: inactive
Nov 01 21:03:11 localhost systemd[1]: Started Login Service.
Nov 01 21:03:11 localhost systemd-logind[1234]: Watching system buttons on /dev/input/event1 (Power Button)
Nov 01 21:03:11 localhost systemd-logind[1234]: Watching system buttons on /dev/input/event2 (Sleep Button)
Nov 01 21:03:11 localhost systemd-logind[1234]: New seat seat0.
Nov 01 21:03:11 localhost coreos-metadata[1267]: Failed to fetch: Get http://169.254.169.254/2009-04-04/meta-data/instance-id: dial tcp 169.254.169.254:80: connect: network is unreachable
Nov 01 21:03:11 localhost kernel: EXT4-fs (xvda9): resized filesystem to 51821563
Nov 01 21:03:11 localhost systemd[1]: Started Update Engine.
Nov 01 21:03:11 localhost update_engine[1227]: I1101 21:03:11.444154  1227 update_check_scheduler.cc:74] Next update check in 5m54s
Nov 01 21:03:11 localhost systemd-networkd[1223]: Enumeration completed
Nov 01 21:03:11 localhost systemd[1]: Started Network Service.
Nov 01 21:03:11 localhost systemd-networkd[1223]: eth0: IPv6 successfully enabled
Nov 01 21:03:11 localhost systemd[1]: Starting Wait for Network to be Configured...
Nov 01 21:03:11 localhost systemd[1]: Reached target Network.
```

And the file we would change:
https://github.com/coreos/coreos-overlay/blob/master/coreos-base/coreos-metadata/files/coreos-metadata.service

**Comment by crawford** [comment]
The target you specifically want is `network.target` (`network-online.target` is for garbage programs that don't know how to retry network operations). There will be no practical improvement from this change other than documentation purposes.

**Comment by bgilbert** [comment]
@dgonyeo What problem is this trying to solve?

**Comment by dgonyeo** [comment]
I'm not actually aware of any problem this is causing, support just commented on how the ordering doesn't seem right.

If we can prevent this error message from appearing in logs it could have a small positive impact on user experience.

**Comment by bgilbert** [comment]
As @crawford said, the situation reported by those messages is not avoidable. At the same time, the messages are useful for debugging real connectivity problems, so I'm in favor of keeping the messages at their current loglevel of `info`. The message could perhaps be clarified, e.g.:

```
Failed to fetch, retrying in 2s: Get http://169.254.169.254/2009-04-04/meta-data/instance-id: ...
[...]
Fetched: http://169.254.169.254/2009-04-04/meta-data/instance-id
```

**Comment by dgonyeo** [comment]
Closing since those messages are not avoidable.

**Comment by lucab** [comment]
While the above is true, I think it still makes sense to order coreos-metadata after network.target to possibly spare a couple of retries and backoff pauses. I put up # for this, but feel to decline it if I'm wrong of if it feels useless.
