### ISSUE TITLE
Ignore domain name adertised by DHCP (2 NIC + DHCP setup)

### ISSUE THREAD

**Issue by hvolpers** [coreos/bugs#226]
Hi,

I'm running CoreOS 494.5.0 with 2 NICs using DHCP. No matter which parameter I set (UseHostname=false, UseDNS=false, ...) it looks like networkd is always accepting the advertised domain (resolv.conf "domain" directive) from both DHCP server. Even worse, after running coreos-cloudinit I see the domain from the internal interface and after some seconds it switches to the external one (looks like the slowest dhcp responds wins).

Here the cloud-init config:

```
[...]
    - name: 01-external.network
      runtime: true
      content: |
        [Match]
        Name=ens34

        [Network]
        DHCP=yes

        [DHCP]
        UseDNS=false
        UseHostname=false
        SendHostname=false

        # workaround as layer 2 communication between the hosts is blocked
        # shouldn't make a difference, but to make sure you see the entire setup
        # (three hosts)
        [Route]
        Gateway=<public_gw>
        Destination=<host_2>/32

        [Route]
        Gateway=<public_gw>
        Destination=<host_3>/32
    - name: 02-internal.network
      runtime: true
      content: |
        [Match]
        Name=ens32

        [Network]
        DHCP=yes
        Domains=my.domain.local

        [DHCP]
        UseRoutes=false
[...]
```

**Comment by marineam** [comment]
I believe the option you want is `UseDomains=false` but I do not know if this option works correctly in the version of systemd 215 shipped in 494.5.0, I had to write a patch to get that functionality to work at all and the code that landed upstream is dramatically different from my patch.

It *should* work in systemd 218 which is in our current alpha release, in fact UseDomains=false is the default but we added UseDomains=true to the default network unit to maintain the existing functionality. https://github.com/coreos/init/blob/master/systemd/network/zz-default.network

I would recommend trying alpha (currently 550.0.0) and see if networkd behaves properly for you.

**Comment by hvolpers** [comment]
Hi,

UseDomains=false doesn't make any difference. Behaviour is the same on beta channel, with alpha channel the domain directive isn't set at all, but the result is the one I want :)
Any chance to get the update to the beta/stable channel? This will be my first productive CoreOS setup and I don't want to start with an alpha version tbh :)

**Comment by marineam** [comment]
beta has the same version of systemd as stable right now so that's why those behave the same way. I don't think this is critical enough to squeeze into the current beta series (522) but if it is any re-assurance I expect 550 to be the base for the next beta/stable series once 522 is promoted to stable.

If 550 works for you and you don't want to upgrade to whatever the next alpha will be you can change the channel to beta or stable. The system won't downgrade, it will stay at 550 until a version higher than that is available to upgrade to. https://coreos.com/docs/cluster-management/setup/switching-channels/
