### ISSUE TITLE
SELinux denies `setfcap`

### ISSUE THREAD

**Issue by dhild** [coreos/bugs#2260]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

AWS

### Expected Behavior ###

SELinux would not block the  `SETFCAP` operations.

### Actual Behavior ###

```
$ docker run -d --cap-add=IPC_LOCK vault:0.8.3
$ journalctl | grep avc
Nov 21 01:59:57 ip-10-19-168-170 audit[30210]: AVC avc:  denied  { setfcap } for  pid=30210 comm="setcap" capability=31  scontext=system_u:system_r:svirt_lxc_net_t:s0:c635,c793 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c635,c793 tclass=capability permissive=1
Nov 21 01:59:57 ip-10-19-168-170 kernel: audit: type=1400 audit(1511229597.273:173): avc:  denied  { setfcap } for  pid=30210 comm="setcap" capability=31  scontext=system_u:system_r:svirt_lxc_net_t:s0:c635,c793 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c635,c793 tclass=capability permissive=1
```

### Reproduction Steps ###

  1. Launch an instance of Container Linux.
  2. Follow instructions to check compatibility at https://coreos.com/os/docs/latest/selinux.html.
  3. Run `docker run -d --cap-add=IPC_LOCK vault:0.8.3`
  4. Check for SELinux denials with `journalctl | grep avc`

### Other Information ###

I thought I had a temporary workaround where I would build a docker image that already has the capability set on the binary, and set the environment variable `SKIP_SETCAP=true` so that the entrypoint would skip running the `setcap` command. However, this version also fails to start; after turning on the same SELinux logging, the error is now logged as a denial of the `ipc_lock` capability.
```
Nov 21 17:56:05 ip-10-19-133-6 audit[6510]: AVC avc:  denied  { ipc_lock } for  pid=6510 comm="vault" capability=14  scontext=system_u:system_r:svirt_lxc_net_t:s0:c532,c909 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c532,c909 tclass=capability permissive=0
```

**Comment by euank** [comment]
The first error (setfcap) happens under docker 1.12, but under version 17.09 (via writing 'no' to /etc/coreos/docker-1.12 per [this post](https://coreos.com/blog/toward-docker-17-in-container-linux)) this no longer occurs.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
