### ISSUE TITLE
nova boot --file option doesn't work on Container Linux.

### ISSUE THREAD

**Issue by hiyosi** [coreos/bugs#2261]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.8.0
VERSION_ID=1465.8.0
BUILD_ID=2017-09-20-2237
PRETTY_NAME="Container Linux by CoreOS 1465.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

OpenStack

### Expected Behavior ###

When `--file <dst_path>:<src_path>` option for nova CLI is spcified, it will be create the file to <dst_path>

### Actual Behavior ###

The file is not created to <dst_path>.

### Reproduction Steps ###

  1. boot CoreOS like `$ nova boot --image coreos --flavor 1 --file /tmp/test=test ...`
  2. login host
  3. ls -l /tmp

### Other Information ###

It works correctly with the Ubuntu 16.04 image.

**Comment by ajeddeloh** [comment]
Container Linux uses [Container Linux Configs](https://coreos.com/os/docs/latest/provisioning.html) to add files, setup systemd units, etc. Your CLC can specify that a file should be created at a specific path. Take a look at the [booting on openstack docs](https://coreos.com/os/docs/latest/booting-on-openstack.html) for how to use CLCs with openstack specifically.

**Comment by hiyosi** [comment]
Thank you for your help.
I see. I'll useContainer Linux Config to add files instead of OpenStack's function.
