### ISSUE TITLE
tectonic website: IAM policy missing required action 

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#2266]
Hi friends, the example AWS IAM policy for Tectonic (hosted at https://coreos.com/tectonic/docs/latest/files/aws-policy.json, linked from https://coreos.com/tectonic/docs/latest/install/aws/requirements.html#privileges) is missing the `iam:ListRoles` action, which now appears to be required by the installer.

(if this is the wrong place to report this, kindly redirect complaints to Ed).

**Comment by sym3tri** [comment]
Fixed in https://github.com/coreos/tectonic-docs/pull/105
