### ISSUE TITLE
Ignition file not being applied on Hyper-V 

### ISSUE THREAD

**Issue by matthew-hickok** [coreos/bugs#2268]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
### Environment ###

Hyper-V running on Windows Server 2016. Using Generation 1 VMs. Using 2 disks. Providing the Ignition file via HTTP. 

### Expected Behavior ###

Ignition configuration is applied. 

### Actual Behavior ###

None of the settings in the Ignition file are applied, but there is no error either.

### Reproduction Steps ###

  1. Boot Generation 1 VM with appropriate resources. 
  2. Once booted, wget the Ignition file
  3. cat the ignition file to verify contents
  4. Run command "coreos-install -d /dev/sda -C stable -i ignition.json"
  5. Wait for installation to finish
  6. Once complete, get message: "Installing Ignition config ignition.json..." 
  7. Then "Success! CoreOS Container Linux stable 1520.8.0 is installed on /dev/sda" 
  8.  Then I run "sudo journalctl --identifier=ignition --all" and it states " -- No entries --"
  9. Verify that none of the changes in the ignition file were made

### Other Information ###

- The same exact Ignition file works without issue on VMware Workstation.
- The Ignition file was validated with the validate configuration utility
- I'm very new to this, but I am happy to get whatever other information is needed

**Comment by arithx** [comment]
Did you reboot after `coreos-install` finished?

Also, does `/usr/share/oem/coreos-install.json` exist & match the `ignition.json` you provided to `coreos-install`?

**Comment by matthew-hickok** [comment]
@arithx 

Yes, I did reboot.

/usr/share/oem/ exists but coreos-install.json is not there. Does that mean it's getting lost on reboot or something?

**Comment by bgilbert** [comment]
[coreos-user thread](https://groups.google.com/d/topic/coreos-user/0tP1bLRc5j0/discussion).

**Comment by matthew-hickok** [comment]
This can be closed. 

Resolution: User error. Stopped being an idiot and it worked. Thanks for your help @arithx
