### ISSUE TITLE
Cron-ish solution?

### ISSUE THREAD

**Issue by hvolpers** [coreos/bugs#227]
Is there something like cron available?

**Comment by marineam** [comment]
Yes, systemd timer units. They are a bit more complicated that a crontab but can also express a lot more. I think they work with fleet too. Arch has a pretty good document covering them: https://wiki.archlinux.org/index.php/Systemd/Timers
man page: http://www.freedesktop.org/software/systemd/man/systemd.timer.html

**Comment by hvolpers** [comment]
But that would mean that I'd have to do the micro management on my own - what if a host goes down etc. Is there something working like fleetd/services? If not, is there something on the roadmap?

**Comment by marineam** [comment]
I haven't personally used timer units in fleet but fleet does claim to support them: https://coreos.com/docs/launching-containers/launching/fleet-unit-files/

You may need to adjust the parameters in the [X-Fleet] section such as adding `MachineOf=foo.service` in the timer unit to ensure the timer and the service unit it controls are claimed by the same machine.

**Comment by jonboulle** [comment]
Right, timer units should work fine with fleet as Mike described - if they do not please file a bug against the fleet repository.
