### ISSUE TITLE
"Long" GCE instance and project names cause hostname setting failure.

### ISSUE THREAD

**Issue by drcrallen** [coreos/bugs#2273]
# Issue Report #

The hostname detected by the Container Linux startup process grabs the almost-FQDN of the instance, which is in general of the form `${INSTANCE_NAME}.${INSTANCE_ZONE}.${PROJECT}.internal`

If the entire resulting string is ~64 characters or longer, the step of setting the hostname during startup fails claiming an invalid hostname. This failure will actually cause problems for JMX connections to java containers which use host networking, causing the RMI connection to fail with confusing 127.0.0.1 errors.

GKE nodes, on the other hand, seem to correctly set the hostname of the instance, even though the instance names are quite long.

## Bug ##

CoreOS startup process does not detect / set hostname correctly if the total domain name is long.

### Container Linux Version ###

1520.8.0

### Environment ###

GCE

### Expected Behavior ###

The hostname is properly set as long as the instance name is below 64 bytes.

### Actual Behavior ###

Startup fails to set the hostname and defaults to `localhost`

### Reproduction Steps ###

  1. Launch container linux instance in GCE with a "long" instance name.
  2. Look at the `journalctl -b` logs for a hostname setting error
  3. Notice that the hostname is set to `localhost` and not the instance name.

### Other Information ###

We are running our own build of Container Linux, but all changes are in user land post-boot. I have not tried this on vanilla Container Linux yet.

**Comment by lucab** [comment]
> CoreOS startup process does not detect / set hostname correctly if the total domain name is long.
> The hostname is properly set as long as the instance name is below 64 bytes.

This is an hardcoded and document limit of the Linux kernel itself, see `man 2 sethostname`. I don't think you are hitting any ContainerLinux-specific bug here.

**Comment by bgilbert** [comment]
The GCE DHCP server sends the FQDN as the hostname.  This is allowed by RFC 2132, and sd-networkd _could_ parse out the name part and set the hostname from that.  In fact, retrieving the rejected hostname from the sd-networkd log and passing it to `sudo hostnamectl set-hostname` will set the "static hostname" (kernel hostname) to a truncated name (which may or may not be the desired behavior) and the "pretty hostname" to the FQDN.  @drcrallen, any interest in filing a bug with upstream systemd?

Ironically, if you configure the machine with a cloud-config (or, equivalently, don't specify an Ignition config), coreos-cloudinit will correctly set the hostname from instance metadata.

**Comment by drcrallen** [comment]
@bgilbert do you know which one Google's COS is doing?

**Comment by bgilbert** [comment]
It appears that COS uses only the hostname part.

**Comment by lucab** [comment]
https://github.com/systemd/systemd/pull/7616 should take care of this once systemd v236 is released.

**Comment by euank** [comment]
Every channel's on at least systemd 236 now, so that change should be in all of them.

Per @lucab's comment / work, this should be fixed (thanks!), closing.
