### ISSUE TITLE
Use Amazon Time Sync Service on AWS as default

### ISSUE THREAD

**Issue by johanneswuerbach** [coreos/bugs#2275]
In line with the advice in https://coreos.com/os/docs/latest/configuring-date-and-timezone.html#recommended-ntp-sources 

> use your cloud provider's NTP source

I would be great if CoreOS on AWS would use the Amazon Time Sync Service https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-the-amazon-time-sync-service by default as it requires no outgoing connections to the public internet and smooths leap seconds.

When using Amazon Linux, this is already done by default http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service, but currently requires additional steps on CoreOS.

**Comment by crawford** [comment]
@johanneswuerbach Do you know if AWS advertises these time servers via DHCP? If so, Container Linux should pick them up by default. If not, we'd have to document how the VPC's DHCP options can be modified.

**Comment by johanneswuerbach** [comment]
Not yet as far as I can tell, nodes started after the announcement still point to `ntp.org`

```
Nov 30 14:29:25 localhost systemd-timesyncd[701]: Network configuration changed, trying to establish connection.
Nov 30 14:29:39 ip-xxx.ec2.internal systemd-timesyncd[701]: Network configuration changed, trying to establish connection.
Nov 30 14:29:40 ip-xxx.ec2.internal systemd-timesyncd[701]: Synchronized to time server 162.210.111.4:123 (2.coreos.pool.ntp.org).
```

So I guess you would need to override `ntp-servers` http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html manually for now or via https://coreos.com/os/docs/latest/configuring-date-and-timezone.html#changing-ntp-time-sources

**Comment by Sodki** [comment]
Also please note the following:

`Support for the Amazon Time Sync Service on C5 and M5 instances is coming soon.`

Source: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service

I would wait until all instances are supported before any attempts of making it the default choice.

**Comment by mindw** [comment]
@Sodki the above comment is no longer present in the above link.

**Comment by Sodki** [comment]
@mindw Correct, I've tested with an M5 instance and it's working.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
