### ISSUE TITLE
Disk attached to a PCI Sata card does not work (Silicon Image, Inc. SiI 3114 Serial ATA Controller)

### ISSUE THREAD

**Issue by X-5Zc7** [coreos/bugs#2278]
# Issue Report #

### Container Linux Version ###

```
 localhost core # cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.3.0
VERSION_ID=1576.3.0
BUILD_ID=2017-11-30-1716
PRETTY_NAME="Container Linux by CoreOS 1576.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Regular consumer desktop HW.

Motherboard: ASUS M5A78L/USB3
CPU: AMD FX-6100
NVIDIA Geforce GTX 970
RAM: 4 x some random sticks
PCI sata controller (Silicon Image Sil3114)

### Expected Behavior ###

Disks connected to the PCI sata controlelr to show up as /dev/sd*

### Actual Behavior ###

Disks connected to the PCI sata cotroller do not show up in /dev/

### Reproduction Steps ###

  1. Attach disk to a Silicon Image Sil3114 sata controller (PCI card)
  2. Notice that it does not work in CoreOS

### Other Information ###

The disk is reported correctly at boot/bios. The controller worked on debian

```
localhost core # lspci | grep Silicon
04:07.0 RAID bus controller: Silicon Image, Inc. SiI 3114 [SATALink/SATARaid] Serial ATA Controller (rev 02)
```

Might be relevant: https://cateee.net/lkddb/web-lkddb/SATA_SIL.html

**Comment by bgilbert** [comment]
Thanks for reporting.  This should be fixed in the alpha after 1618.
