### ISSUE TITLE
flanneld.service startparameter

### ISSUE THREAD

**Issue by hvolpers** [coreos/bugs#228]
Hi,

is it possible to run flanned on a different Interface? The default route is pointing to the public Interface (public IP in my case) and I want to bind it to the internal interface.
Would be great to have an optional opts file like for docker (EnvironmentFile=-/run/docker_opts.env).

What would be the standard / best practice way to inject this change on alpha channel? Clone the existing service or modify it?

**Comment by AntonioMeireles** [comment]
+1

**Comment by eyakubovich** [comment]
An interface can be specified via "interface" field in cloud-config. e.g:

```
#cloud-config
coreos:
    flannel:
        interface: eth1
```

See https://coreos.com/docs/cluster-management/setup/cloudinit-cloud-config/#coreos for more info.

**Comment by pires** [comment]
When is this being released?

**Comment by eyakubovich** [comment]
@pires It has been released and in all the latest versions across all channels.

**Comment by pires** [comment]
thanks @eyakubovich
