### ISSUE TITLE
update-ssh-keys should warn on invalid keys

### ISSUE THREAD

**Issue by sdemos** [coreos/bugs#2283]
# Issue Report #

### Desired Feature ###

`update-ssh-keys` currently throws an error when it reads an invalid key. This behavior should be modified to instead display a warning for each invalid key, and omit them from `authorized_keys`, while still successfully including any valid keys it finds.

### Other Information ###

motivation - https://github.com/golang/go/issues/23034

**Comment by bgilbert** [comment]
Reopening until merged to master.

**Comment by sdemos** [comment]
should this be backported, and if so, what versions

**Comment by bgilbert** [comment]
https://github.com/coreos/coreos-overlay/pull/2954
https://github.com/coreos/coreos-overlay/pull/2955
https://github.com/coreos/coreos-overlay/pull/2956

This should be fixed in the next alpha, and is queued for the next beta and stable point releases.

**Comment by bgilbert** [comment]
This will be fixed in beta 1632.1.0 and stable 1576.5.0, due shortly.

**Comment by zyclonite** [comment]
@bgilbert if this should have fixed the error with not existing ssh keys as well, then it did not work
service still fails with
```
systemd[1]: Starting CoreOS Metadata Agent (SSH Keys)...
coreos-metadata[656]: Error: writing ssh keys
coreos-metadata[656]: Caused by: failed to update authorized keys
coreos-metadata[656]: Caused by: update-ssh-keys: no keys found in "/home/core/.ssh/authorized_keys.d"
systemd[1]: coreos-metadata-sshkeys@core.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: Failed to start CoreOS Metadata Agent (SSH Keys).
systemd[1]: coreos-metadata-sshkeys@core.service: Unit entered failed state.
systemd[1]: coreos-metadata-sshkeys@core.service: Failed with result 'exit-code'.
```

**Comment by lucab** [comment]
@zyclonite that looks like a different behavior and something that @sdemos was explicitly stopping on: https://github.com/coreos/update-ssh-keys/blob/v0.1.2/src/lib.rs#L258-L262

Can you please open a separate ticket with your ignition config, any relevant cloud metadata, and what are the initial and expected final statuses (it doesn't look like a fresh install)?

**Comment by sdemos** [comment]
Yeah, that's correct. As the comment above that error condition says, `update-ssh-keys` refuses to help a user delete all of their ssh keys, and instead expects them to do it manually if it is actually the desired behavior.

**Comment by zyclonite** [comment]
@lucab opened #2312
