### ISSUE TITLE
Rename coreos-metadata oracle provider to oracle-oci

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2289]
# Issue Report #

### Environment ###

OCI

### Desired Feature ###

coreos-metadata code and log messages should refer to `oracle-oci`, `oracle_oci`, or `oracleoci` instead of `oracle`.  Oracle has two clouds and we should clearly specify which one we support.

**Comment by lucab** [comment]
It looks like platform label and documentation already refers to `oracle-oci`, so I think this is mostly cosmetics on the log messages side. Just for reference, what does `oci` stands for in this context? Is this cloud.oracle.com? How is the non-oci one called and is there any public URL to it that we can refer to?

**Comment by bgilbert** [comment]
OCI is [Oracle Cloud Infrastructure](https://cloud.oracle.com/cloud-infrastructure), formerly Bare Metal Cloud Service.  The old one is Oracle Public Cloud, which I guess is [here](https://cloud.oracle.com/classic) now.

Fixed in https://github.com/coreos/coreos-metadata/pull/76; closing.
