### ISSUE TITLE
coreos-metadata logging doesn't work under systemd

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2290]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1618.0.0+2017-12-06-0025
VERSION_ID=1618.0.0
BUILD_ID=2017-12-06-0025
PRETTY_NAME="Container Linux by CoreOS 1618.0.0+2017-12-06-0025 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Any

### Expected Behavior ###

coreos-metadata log messages are written to the journal.

### Actual Behavior ###

coreos-metadata log messages are not recorded anywhere.

### Reproduction Steps ###

  1. `journalctl -u coreos-metadata-sshkeys@core.service`

### Other Information ###

When run directly from the command line, coreos-metadata writes logs to stderr.  However, systemd sends stderr to the journal by default, and no log messages show up there.  Adding `StandardError=kmsg` to the unit doesn't send log messages to dmesg.  Adding `strace -f` to the `ExecStart=` line shows no log messages being written to stderr.

**Comment by sdemos** [comment]
I believe that regular, info level log messages are printing to stdout, not stderr. I'll do some investigation on the logging library I'm using to make sure that's the case, and make sure it's logging in all situations.

**Comment by bgilbert** [comment]
In my tests on the command line, info messages go to stderr as well.

**Comment by sdemos** [comment]
well that's not what I expected. I've been meaning to update the logging library to print synchronously anyway, and it looks like that will give us some more control over exactly where that gets printed. 

I'm still not sure why it isn't logging to the journal though. Perhaps that also has to do with the async logging interacting with systemd running it and redirecting the output? I'm going to explore that possibility.

**Comment by lucab** [comment]
A `cargo update` seems to be fixing the issue for me on my local (Debian) machine. However I didn't spot any relevant commit in our dependencies.

This is the list of outdated deps that could be related:
```
$ cargo outdated -R
Name          Project  Compat   Latest   Kind    Platform
----          -------  ------   ------   ----    --------
base64        0.6.0    ---      0.8.0    Normal  ---
byteorder     1.1.0    1.2.1    1.2.1    Normal  ---
clap          2.27.1   2.29.0   2.29.0   Normal  ---
clippy        0.0.169  0.0.175  0.0.175  Normal  ---
hyper         0.11.6   0.11.9   0.11.9   Normal  ---
openssh-keys  0.2.0    0.2.1    0.2.1    Normal  ---
openssl       0.9.20   0.9.23   0.9.23   Normal  ---
reqwest       0.7.3    ---      0.8.1    Normal  ---
serde         1.0.19   1.0.24   1.0.24   Normal  ---
serde_derive  1.0.19   1.0.24   1.0.24   Normal  ---
serde_json    1.0.5    1.0.8    1.0.8    Normal  ---
slog          2.0.12   2.1.1    2.1.1    Normal  ---
slog-async    2.1.0    2.2.0    2.2.0    Normal  ---
slog-term     2.2.0    2.3.0    2.3.0    Normal  ---
```

**Comment by lucab** [comment]
This may just be a matter of coreos-metadata writing to stdout/stderr and then being too quick at exiting. Journald in that case loses the https://github.com/systemd/systemd/issues/2913 race and some service metadata are missing. Log line are still visible via `sudo journalctl -t coreos-metadata` though.
The logs from https://github.com/coreos/bugs/issues/2361#issue-297591085 also seems to be only missing error lines, not info messages.

**Comment by bgilbert** [comment]
Looks like this is working in alpha 1828.0.0.  Closing.
