### ISSUE TITLE
How to mimic guestinfo options in standard ova in a custom vmware ova

### ISSUE THREAD

**Issue by charandas** [coreos/bugs#2297]
# Issue Report #

### Container Linux Version ###
```
coreos2 oem # cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.4.0
VERSION_ID=1576.4.0
BUILD_ID=2017-12-06-0449
PRETTY_NAME="Container Linux by CoreOS 1576.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

VMWare Fusion (later to be run on ESXi) - but for this issue, generating an OVA using packer/ovftool

### Expected Behavior ###
The generated OVA would have VMware specific `guestinfo` options.

### Actual Behavior ###
It doesn't. I may be having unreasonable expectations here. If that is the case, I would like
to know how the [standard OVA](https://coreos.com/os/docs/latest/booting-on-vmware.html) comes to support those options. 

### Reproduction Steps ###

  1. Like #2090, I want to generate a baseimage with packer/vmware-iso
```
sudo coreos-install -d /dev/sda -C {{ user `release` }} -i /tmp/ignition.json -o vmware_raw
```
  2. Generate an OVA from the VMX using `ovftool`

I would like to additionally do all the boilerplate so ignition can run once more when this OVA actually is cloned in VMware. That is where, I am hoping to have the power afforded by the `guestinfo` options. But for now, those steps above suffice in proving that the OVA generated doesn't have those options.

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Other Information ###

My full packer manifest:

```js
{
  "variables": {
    "name": "coreos-baseimage",
    "release": "stable",
    "iso_checksum": "",
    "iso_checksum_type": "none",
    "disk_size": "40000",
    "memory": "2048",
    "boot_wait": "30s",
    "ignition": "ignition.json"
  },
  "builders": [{
    "type": "vmware-iso",
    "vm_name": "{{user `name`}}",
    "vmdk_name": "{{user `name`}}-disk",
    "iso_url": "coreos_production_iso_image.iso",
    "iso_checksum": "d97ed6c250f2037b6fd92471c2890176",
    "iso_checksum_type": "md5",
    "ssh_username": "core",
    "ssh_password": "packer",
    "shutdown_command": "shutdown -P now",
    "format": "vmx",
    "boot_wait": "{{user `boot_wait`}}",
    "boot_command": [
      "sudo passwd core<enter><wait>",
      "packer<enter>",
      "packer<enter>",
      "sudo systemctl start sshd.service<enter>"
    ],
    "vmx_data": {
      "cpuid.coresPerSocket": "1",
      "memsize": "{{user `memory`}}",
      "numvcpus": "1"
    }
  }],
  "provisioners": [
    {
      "type": "file",
      "source": "{{ user `ignition` }}",
      "destination": "/tmp/ignition.json"
    },
    {
        "type": "shell",
        "inline": [
            "sudo coreos-install -d /dev/sda -C {{ user `release` }} -i /tmp/ignition.json -o vmware_raw"
        ]
    }
  ],
  "post-processors": [
    {
        "inline": [
            "/path/to/ovftool output-vmware-iso/{{user `name`}}.vmx {{user `name`}}.ova"
        ],
        "type": "shell-local"
    },
    {
        "files": [
            "{{user `name`}}.ova"
        ],
        "type": "artifice"
    }
  ]
}
```

**Comment by bgilbert** [comment]
[Here's the OVF template](https://github.com/coreos/scripts/blob/7ab2b63f09686580a8cdef15281d2c4ee535b477/build_library/template_vmware.ovf#L21-L85) used by the Container Linux build system.

**Comment by charandas** [comment]
@bgilbert I followed your suggestion, and made my OVF have those properties in `ProductSection`.

Now, I accordingly see those properties when setting up my VM in vsphere. However, the ignition config does not have any effect.

I am having to boot for once, then:

1. `rm /etc/machine-id`
2. `touch /boot/coreos/first_boot`
3. Replace contents of `/usr/share/oem/coreos-install.json`

I am curious as to what additional steps needs to be added to my OVA generation process, so that it would read the ignition config from `guestinfo.coreos.config.data` vApp property, like it does with the standard OVA provided by coreos.

**Comment by bgilbert** [comment]
Steps 1, 2, and 3 should indeed be unnecessary.  The problem is that you're passing `-i /tmp/ignition.json` to `coreos-install`.  That option modifies `/usr/share/oem/grub.cfg` on the installed system to override the Ignition config source, with the result that Ignition will never look at the guestinfo property.

**Comment by charandas** [comment]
Are you suggesting, that I do not need to pass `-i /tmp/ignition.json`, and all would work like standard OVA?

**Comment by charandas** [comment]
@bgilbert I tried this: `sudo coreos-install -d /dev/sda -C {{ user `release` }} -o vmware_raw`

Below is the output from packer shell provisioner. However, I still do not have success in passing the `guesinfo` through. The only two ways I have to confirm that for now are:

1. to start a VMWare console in the browser, which shows `localhost` instead of my configured name of `coreos9`, and 
2.ssh access does not work

```
==> coreos-baseimage: Provisioning with shell script: /var/folders/js/gmc33xtx61bdnt9_p3bq998w0000gn/T/packer-shell721520550
    coreos-baseimage: Current version of CoreOS Container Linux stable is 1576.4.0
    coreos-baseimage: Downloading the signature for https://stable.release.core-os.net/amd64-usr/1576.4.0/coreos_production_vmware_raw_image.bin.bz2...
    coreos-baseimage: 2017-12-16 23:40:39 URL:https://stable.release.core-os.net/amd64-usr/1576.4.0/coreos_production_vmware_raw_image.bin.bz2.sig [566/566] -> "/tmp/coreos-install.aTSTFSHbKO/coreos_production_vmware_raw_image.bin.bz2.sig" [1]
    coreos-baseimage: Downloading, writing and verifying coreos_production_vmware_raw_image.bin.bz2...
    coreos-baseimage: 2017-12-16 23:41:32 URL:https://stable.release.core-os.net/amd64-usr/1576.4.0/coreos_production_vmware_raw_image.bin.bz2 [340570297/340570297] -> "-" [1]
    coreos-baseimage: gpg: Signature made Wed Dec  6 05:26:28 2017 UTC
    coreos-baseimage: gpg:                using RSA key 8826AD9569F575AD3F5643E7DE2F8F87EF4B4ED9
    coreos-baseimage: gpg: key 50E0885593D2DCB4 marked as ultimately trusted
    coreos-baseimage: gpg: checking the trustdb
    coreos-baseimage: gpg: marginals needed: 3  completes needed: 1  trust model: pgp
    coreos-baseimage: gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
    coreos-baseimage: gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" [ultimate]
    coreos-baseimage: Success! CoreOS Container Linux stable 1576.4.0 (vmware_raw) is installed on /dev/sda
```

### CT Config

```
# This config is meant to be consumed by the config transpiler, which will
# generate the corresponding Ignition config. Do not pass this config directly
# to instances of Container Linux.

storage:
  files:
    - filesystem: "root"
      path:       "/etc/hostname"
      mode:       0644
      contents:
        inline: coreos9
    - filesystem: "root"
      path:       "/etc/hosts"
      mode:       0644
      contents:
        inline:  "127.0.0.1 localhost coreos9\n
                  ::1 localhost"

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - some key
```

**Comment by charandas** [comment]
If before the reboot, I look at my grub.cfg, it is pretty barebones.

<img width="736" alt="screen shot 2017-12-16 at 7 32 52 pm" src="https://user-images.githubusercontent.com/542168/34075546-ffcfed3e-e297-11e7-9bf2-b5210f106cbb.png">

**Comment by charandas** [comment]
Thanks so much @bgilbert for your support in the last few days.

I figured it out just now. Besides copying `ProductSection` from the template, I needed:

```
<VirtualHardwareSection ovf:transport="com.vmware.guestInfo">
```

I also copied:

```
<vmw:Config ovf:required="false" vmw:key="firmware" vmw:value="bios"/>
```

It totally works as intended now. I may capture it all in a repo/blog post somewhere at some point.

**Comment by AshleyByeUK** [comment]
@charandas Trying to do a similar thing. Wondering what version of packer you are using? I don't see the `v_app_properties` option in the docs for the `vsphere-template` post-processor and if I try to use it, packer throws an error.

**Comment by charandas** [comment]
@AshleyByeUK if you look closely at my gist, it’s comments specifically point out the fact that you would need to use my post-processor fork:

https://gist.github.com/charandas/dc99c36bd97c1baa3e23d4ecba6beb4a

**Comment by AshleyByeUK** [comment]
Thanks. I completely missed the comments at the bottom when I first read it.
