### ISSUE TITLE
quay.io/coreos/hyperkube:1.9.0_coreos.0 is missing version numbers

### ISSUE THREAD

**Issue by alkar** [coreos/bugs#2299]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.4.0
VERSION_ID=1576.4.0
BUILD_ID=2017-12-06-0449
PRETTY_NAME="Container Linux by CoreOS 1576.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

AWS

### Expected Behavior ###

I expect to be able to get the kubernetes version from the apiserver.

### Actual Behavior ###

The `Major` and `Minor` fields are empty.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0+coreos.0", GitCommit:"1b69a2a6c01194421b0aa17747a8c1a81738a8dd", GitTreeState:"clean", BuildDate:"2017-12-19T02:52:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

Output is the same when using `curl` to retrieve the version.

### Reproduction Steps ###

N/A

### Other Information ###

N/A

**Comment by dghubble** [comment]
cc @rphillips

**Comment by rphillips** [comment]
Looking into this... the binaries return the correct version with a `--version`.

**Comment by rphillips** [comment]
Thank you for the report.

GitMajor and GitMinor are being deprecated and were formerly defaulted within `pkg/version/base.go`. In 1.9 the default values were removed and our version string `v1.9.0+coreos.0` does not match the regex with the included (+); the code is looking for a (-). We should be able to release a new point release with the necessary fix.

**Comment by rphillips** [comment]
PR for this issue has been submitted. https://github.com/kubernetes/kubernetes/pull/57420

**Comment by alkar** [comment]
Thanks, @rphillips , will be following that PR 👍

**Comment by george-angel** [comment]
1.9.2 works correctly:

```
kubectl --context=exp version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bgilbert** [comment]
Okay, closing.  @alkar, thanks for reporting.
