### ISSUE TITLE
async_page_fault crash during high load

### ISSUE THREAD

**Issue by andruby** [coreos/bugs#230]
I'm getting kernel crashes once a week or sometimes multiple times a day on Digital Ocean. The system is tracking the stable channel and is running CoreOS 494.5.0.

This is a screenshot from the DigitalOcean vnc connection after a crash occurred and the droplet is unresponsive via http and ssh, but does respond to pings:
![digitalocean control panel 2015-01-05 21-38-05](https://cloud.githubusercontent.com/assets/10639/5626352/9c0d1996-958a-11e4-9533-b66ed67bc646.png)
Only a hard power cycle can bring the machine back. Is there a way to get the full crash stack trace after a reboot?

I'm running Nginx, Sentry, Gitlab, GitlabCI and one GitlabCI runner on a 2GB memory droplet. The CI runs docker-in-docker which builds and runs a container on every git push to our main app repo. Those CI runs take ~10 minutes to finish and cause quite some load.

I've added a 4GB swap file at `/4GiB.swap` using this systemd service (taken [from here](https://github.com/coreos/docs/issues/52#issuecomment-45418877)):

```shell
[Unit]
Description=Turn on swap

[Service]
Type=oneshot
Environment="SWAPFILE=/4GiB.swap"
RemainAfterExit=true
ExecStartPre=/usr/sbin/losetup -f ${SWAPFILE}
ExecStart=/usr/bin/sh -c "/sbin/swapon $(/usr/sbin/losetup -j ${SWAPFILE} | /usr/bin/cut -d : -f 1)"
ExecStop=/usr/bin/sh -c "/sbin/swapoff $(/usr/sbin/losetup -j ${SWAPFILE} | /usr/bin/cut -d : -f 1)"
ExecStopPost=/usr/bin/sh -c "/usr/sbin/losetup -d $(/usr/sbin/losetup -j ${SWAPFILE} | /usr/bin/cut -d : -f 1)"

[Install]
WantedBy=multi-user.target
```

The `/4GiB.swap` file was created using [these instructions](https://github.com/coreos/docs/issues/52#issuecomment-51142602):

```shell
sudo fallocate -l 4096m /4GiB.swap
sudo chmod 600 /4GiB.swap
sudo chattr +C /4GiB.swap
sudo mkswap /4GiB.swap
```

The swap file is being used correctly:
```
KiB Mem:   2054164 total,  1984332 used,    69832 free,      624 buffers
KiB Swap:  4194300 total,  1557252 used,  2637048 free.   722400 cached Mem
```

I've logged this at DigitalOcean first, but they were unable to help me further.

What could be causing the crashes? How can I get more helpful information?

**Comment by andruby** [comment]
Just had it again, this time I managed to get some screenshots while it was happening:

![digitalocean control panel 2015-01-06 10-34-24](https://cloud.githubusercontent.com/assets/10639/5626778/4891b6b8-9590-11e4-917b-d95c75490300.png)

![digitalocean control panel 2015-01-06 10-35-29](https://cloud.githubusercontent.com/assets/10639/5626776/3b50b2c4-9590-11e4-94ed-aee5a6bb0dbc.png)

**Comment by zjeraar** [comment]
Have exactly the same issue (completely other stack, running ruby on rails). When the load reaches 1+ (not extremely high, just 1.03 average on a 1 cpu droplet), the system hangs with the async_page_faults of @andruby first post.

**Comment by zjeraar** [comment]
I'm testing this and I have the feeling that this might have to do with swap (something which the btrfs page clearly say you should avoid). I did not disable COW for the swap file and I'm testing with COW disabled and so far it looks good. @andruby are you able to test this too? My unit to turn on swap and with COW disabled (as far as i know chattr +C can only be done on a zero byte file, so I do touch first):

```
 - name: swapon.service
      command: start
      content: |
        [Unit]
        Description=Turn on swap
        [Service]
        Type=oneshot
        Environment="SWAPFILE=/2GiB.swap"
        RemainAfterExit=yes
        ExecStartPre=/usr/bin/touch ${SWAPFILE}
        ExecStartPre=/usr/bin/chattr +C ${SWAPFILE}
        ExecStartPre=/usr/bin/fallocate -l <swap_size>g ${SWAPFILE}
        ExecStartPre=/usr/bin/chmod 600 ${SWAPFILE}
        ExecStartPre=/usr/sbin/mkswap ${SWAPFILE}
        ExecStartPre=/usr/sbin/losetup -f ${SWAPFILE}
        ExecStart=/usr/bin/sh -c "/sbin/swapon $(/usr/sbin/losetup -j ${SWAPFILE} | /usr/bin/cut -d : -f 1)"
        
        [Install]
        WantedBy=multi-user.target
```

**Comment by zjeraar** [comment]
No, NOCOW doesn't work for me either, only took longer for the box to crash. Now trying without swap, to see if that's really the problem.

**Comment by andruby** [comment]
I'm pulling my hair out :unamused: box crashed again today with a different trace though:

![digitalocean control panel 2015-01-07 17-06-00](https://cloud.githubusercontent.com/assets/10639/5648560/b4de1df2-968f-11e4-9e77-f90ea91dadca.png)

I guess the cleanup didn't help all that much..

**Comment by zjeraar** [comment]
Yeah, I saw that one too once. I just tested the last few hours without swap and heavily stressing the droplet, with a positive result. So my conclusion for now is that the swap causes the issue.

**Comment by marineam** [comment]
There have been other reports of issues with swap on btrfs. I think my recommendation at this point is to never do that. If you want swap use a partition on a physical disk (in the VM/cloud world this usually means ephemeral storage). Otherwise you are better off without it. If the only reason you need swap is to get an application that allocates way more memory than it actually needs to work you can turn on overcommit instead.

**Comment by zjeraar** [comment]
Hi @marineam thanks. How do you turn on overcommit on CoreOS, searched for that before.

**Comment by marineam** [comment]
Write something like `/etc/systctl.d/overcommit.conf`:

    vm.overcommit_memory=1

See https://www.kernel.org/doc/Documentation/sysctl/vm.txt and https://www.kernel.org/doc/Documentation/vm/overcommit-accounting

To provision out of the box via cloud-config something like this should do it:
```yaml
#cloud-config

write_files:
    - path: /etc/systctl.d/overcommit.conf
      content: vm.overcommit_memory=1

coreos:
    units:
      - name: systemd-sysctl.service
        command: restart
```

**Comment by marineam** [comment]
We now ship images with ext4, making using a swap file more practical. As for swap on btrfs, that is a configuration that is unlikely to work well any time soon. So if you need swap use a partition on a second disk or use a file on ext4, no point in fighting btrfs.
