### ISSUE TITLE
PXE Boot: Invalid or corrupt kernel image

### ISSUE THREAD

**Issue by davbizz** [coreos/bugs#2300]
I followed the tutorial at: https://coreos.com/os/docs/latest/booting-with-pxe.html 
but when i start the installation I get this error:
```
 Invalid or corrupt kernel image
```

I have download the coreos_production_pxe.vmlinuz image from here: https://stable.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz where the last current version is 1576.4.0

The machine is a VM on VmWare vShpere with BIOS

**Comment by dm0-** [comment]
Your link is to the PGP signature.  Try https://stable.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz; it's working for me.

**Comment by davbizz** [comment]
I have copied the wrong link inside the ticket I used coreos_production_pxe.vmlinuz file and to be sure I test it again but i receive the same error
```
Invalid or corrupt kernel image
```

I have even tried to download the iso, extract the vmlinuz from there but nothing changed.

**Comment by dm0-** [comment]
Okay, then can you verify the signature to make sure your download wasn't corrupted.  The kernel image has no problem booting for me, but I don't have vmware available to try it right now.

**Comment by davbizz** [comment]
```
# gpg --verify coreos_production_pxe.vmlinuz.sig
gpg: Signature made mer 06 dic 2017 06:07:06 CET using RSA key ID EF4B4ED9
gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0412 7D0B FABE C887 1FFB  2CCE 50E0 8855 93D2 DCB4
     Subkey fingerprint: 8826 AD95 69F5 75AD 3F56  43E7 DE2F 8F87 EF4B 4ED9
```

**Comment by lucab** [comment]
@davbizz if this is still an issue, can you please attach your PXE entry config? Can you also check/attach logs from your PXE/TFTP server to make sure that the VM is using the proper server and hitting the correct endpoint?

**Comment by lucab** [comment]
Lacking any further feedback and any further reproducer, I'm going to close this ticket. If anybody is hitting this, please open a new bug and attach the full PXE configuration and relevant logs from the server.
