### ISSUE TITLE
Boot sequence stuck on ACPI with Proxmox and KVM.

### ISSUE THREAD

**Issue by lchabert** [coreos/bugs#2304]
# Issue Report #

### Environment ###

Matchbox iPXE booting version 1576.4.0.

running on Proxmox 4 with 
```
QEMU emulator version 2.7.0 pve-qemu-kvm_2.7.0-9, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers
```
Virtio network interface and disks.

### Expected Behavior ###

Boot sequence end and ignition config file must be downloaded.

### Actual Behavior ###

CoreOS does not boot. Boot sequence is stuck with this message:
```
ACPI: PCI Interrupt Link [LNKB] enabled at IRQ 11
```

### Reproduction Steps ###

  1.Create an environment for matchbox.
  2. Create a new VM with no iso disk, and set iPXE booting on Proxmox UI.
  3. Start the VM with Proxmox UI

### Other Information ###

If i disable ACPI support on proxmox, boot sequence is stop later.
If i run an old version of CoreOS (1353.7.0), boot sequence is ended

**Comment by lchabert** [comment]
After some research, this appear if vm has only 1G of RAM.

How many RAM is needed to boot a coreOS VM with matchbox ?

Regards.

**Comment by dm0-** [comment]
For PXE booting, the system needs at least 2GiB of RAM: https://coreos.com/os/docs/latest/booting-with-pxe.html

**Comment by bgilbert** [comment]
Also, it sounds as though you're booting with the serial console set as primary, so you're only seeing kernel messages on the graphical console.  Check the kernel command line in your iPXE config: `console=tty0` should be the last `console=` argument on the line.

**Comment by lchabert** [comment]
Indeed, with 2Gb of RAM, it works. I have a successfull coreOS installation on Proxmox.

Thanks.
