### ISSUE TITLE
Please add CONFIG_TCG_VTPM_PROXY=m

### ISSUE THREAD

**Issue by coresolve** [coreos/bugs#2308]
## Feature Request ##
Please add the TCG_VTPM_PROXY as a module to the CL kernel.
### Environment ###

Tectonic

What hardware/cloud provider/hypervisor is being used to run Container Linux?

Bare Metal. 

### Desired Feature ###

Want to work on testing the virtual tpm feature in k8s.

### Other Information ###

Other related work in the runc project.
https://github.com/opencontainers/runc/pull/1591

**Comment by bgilbert** [comment]
Done in https://github.com/coreos/coreos-overlay/pull/3009, which should be included in the next alpha.
