### ISSUE TITLE
CoreOS Enterprise Registry Feature Request: Gravatar Email

### ISSUE THREAD

**Issue by marcellodesales** [coreos/bugs#231]
Hi there,

Problem
----- 

We maintain a list of gravatars emails for each specific GitHub Enterprise Organization, as GitHub Enterprise has that capability. The current version of the CoreOS Enterprise Registry only contains a single contact email address, whose Gravatar email is pulled from. 

Solution
-----

Following the same GitHub Enteprise Organization setup, we would like to Enterprise Registry to have a separate field for the Gravatar email. That way, the organization could render the appropriate image.

Thanks!
Marcello

**Comment by crawford** [comment]
This is being tracked internally.
