### ISSUE TITLE
bootstrapping instance without ssh key fails coreos-metadata-sshkeys unit

### ISSUE THREAD

**Issue by zyclonite** [coreos/bugs#2312]
# Issue Report #

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.5.0
VERSION_ID=1576.5.0
BUILD_ID=2018-01-05-1121
PRETTY_NAME="Container Linux by CoreOS 1576.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

AWS EC2

### Expected Behavior ###

bootstrapping a new instance without a ssh-key
all units run/start without any failure

### Actual Behavior ###

since version 1576.4.0 we get
```
Failed Units: 1
  coreos-metadata-sshkeys@core.service
```
```
systemd[1]: Starting CoreOS Metadata Agent (SSH Keys)...
coreos-metadata[726]: Error: writing ssh keys
coreos-metadata[726]: Caused by: failed to update authorized keys
coreos-metadata[726]: Caused by: update-ssh-keys: no keys found in "/home/core/.ssh/authorized_keys.d"
systemd[1]: coreos-metadata-sshkeys@core.service: Main process exited, code=exited, status=1/FAILURE
```

### Reproduction Steps ###

  1. you need a ldap server setup (enabling you to login)
  2. use https://console.aws.amazon.com/ec2/home?region=eu-west-1#launchAmi=ami-32d1474b to launch your instance
  3. configure with the below ignition config
  4. choose to "Proceed without a key pair" and confirm

#### ignition-config.json
(file contents removed due to size and sensitive data)

```
{
  "ignition": {
    "config": {},
    "timeouts": {},
    "version": "2.1.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "group": {},
        "path": "/etc/sssd/sssd.conf",
        "user": {
          "id": 0
        },
        "contents": {
          "source": "<...>",
          "verification": {}
        },
        "mode": 384
      },
      {
        "filesystem": "root",
        "group": {},
        "path": "/etc/ssh/sshd_config",
        "user": {
          "id": 0
        },
        "contents": {
          "source": "<...>",
          "verification": {}
        },
        "mode": 384
      }
    ]
  },
  "systemd": {
    "units": [
      {
        "enable": true,
        "name": "sssd.service"
      }
    ]
  }
}
```

**Comment by bgilbert** [comment]
kola doesn't test this.  It tries putting the SSH key only in platform metadata, and putting it only in userdata, but there are no tests that use no SSH keys at all.

**Comment by zyclonite** [comment]
masking is a valid option, i can live with the failed service as well... the behavior simple changed in the most recent releases, this was the main reason for reporting it

**Comment by bgilbert** [comment]
@zyclonite Yep, it's a regression, and we'll get it fixed.  Thanks for reporting.

**Comment by bgilbert** [comment]
Fixed upstream in https://github.com/coreos/coreos-metadata/pull/97.  Leaving open until the change merges to overlay.
