### ISSUE TITLE
Install fails on Dell Poweredge R640 with Broadcom BCM57416 network controller

### ISSUE THREAD

**Issue by xenexis** [coreos/bugs#2314]
# Issue Report #

## Bug ##
Install starts with PXE boot properly, fails with network config as the required module (bnxt_en) not loaded and no networking configured from that point ...
Tried releases:
stable 1576.4.0
stable 1576.5.0
alpha 1649.0.0

### Container Linux Version ###

```
Only emergency shell are available :
:/# cat /etc/os-release
NAME="dracut"
VERSION="dracut-045"
ID=dracut
VERSION_ID=045
PRETTY_NAME="dracut-045 (Initramfs)"
ANSI_COLOR="0;34"

...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

Bare Metal install on Dell Poweredge R640

### Expected Behavior ###
Configure network and install CoreOS

### Actual Behavior ###
Fail due to no network device are available

### Reproduction Steps ###

  1. Boot with PXE the server (Dell Poweredge R640) with configured provision box
  2. No network configured ...

**Comment by bgilbert** [comment]
Thanks for the report.  We need to enable `CONFIG_BNXT`.

**Comment by bgilbert** [comment]
Fixed in https://github.com/coreos/coreos-overlay/pull/3009, which should be included in the next alpha.
