### ISSUE TITLE
gpg --recv-key broken in 1576.5.0

### ISSUE THREAD

**Issue by kcwitt** [coreos/bugs#2319]
# Issue Report #

the gnupg receive key command does not work
```
vb-coreos ~ # gpg --recv-key 50E0885593D2DCB4
gpg: keyserver receive failed: No keyserver available
```

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.5.0
VERSION_ID=1576.5.0
BUILD_ID=2018-01-05-1121
PRETTY_NAME="Container Linux by CoreOS 1576.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

CoreOS 1576.5.0 on Digital Ocean San Francisco and Singapore servers.

### Expected Behavior ###
```
vb-coreos:~# gpg --version
gpg (GnuPG) 2.2.3
...
vb-coreos:~# gpg --recv-key 50E0885593D2DCB4
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: key 50E0885593D2DCB4: 1 signature not checked due to a missing key
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 50E0885593D2DCB4: public key "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
```

### Actual Behavior ###
```
vb-coreos ~ # gpg --version
gpg (GnuPG) 2.1.20
...
vb-coreos ~ # gpg --recv-key 50E0885593D2DCB4
gpg: keyserver receive failed: No keyserver available
```

### Reproduction Steps ###

  1. `gpg --recv-key 50E0885593D2DCB4`

### Other Information ###
The example below shows that running gpg 2.2.3 in a toolbox sandbox (using alpine linux) works, so it does not seem to be an internet connectivity or DNS issue. Also, it is an intermittent issue occurring around 60% of the time.
```
vb-coreos ~ # echo "TOOLBOX_DOCKER_IMAGE=alpine" > ~/.toolboxrc
vb-coreos ~ # toolbox
Spawning container root-alpine-latest on /var/lib/toolbox/root-alpine-latest.
...
vb-coreos:~# apk add gnupg
...
OK: 24 MiB in 33 packages
vb-coreos:~# gpg --version
gpg (GnuPG) 2.2.3
vb-coreos:~# gpg --recv-key 50E0885593D2DCB4
gpg: key 50E0885593D2DCB4: 1 signature not checked due to a missing key
gpg: key 50E0885593D2DCB4: "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by dm0-** [comment]
You'll need to add a default server to your `~/.gnupg/dirmngr.conf` file, or use an argument like `--keyserver pool.sks-keyservers.net` with the command.  It seems to be working as expected for me.

**Comment by kcwitt** [comment]
That is what I used to do, but even that didn't work reliably, and I need it to actually be relaible.

You should not be required to specify a keyserver (it even states that in the dirmngr.conf file). Specifying it was an okay hack as long as it worked, but it doesn't work reliably.

Also, it is possible my estimate that it fails 60% of the time is probably very misleading. It probably fails infrequently, but when it does I have to keep retrying for what feels like a long time before it works.

I think there is an actual bug in the upstream gnupg, and CoreOS just needs to update to a 2.2.x version.

**Comment by kcwitt** [comment]
That explains why `--keyserver hkps://hkps.pool.sks-keyservers.net` has never worked for me.

The remaining errors using `--keyserver pgp.mit.edu` probably are network related. I just tried pool.sks-keyservers.net per your suggestion above and it works.

Thanks.

**Comment by lucab** [comment]
@dm0- should we consider building with TLS support or switching the default to match our build configuration?

**Comment by dm0-** [comment]
Last time it was considered, it was left disabled to avoid pulling in yet another TLS implementation that nothing else uses.  With the default configuration, it's adding at least another five packages to prod images.
