### ISSUE TITLE
Remove AllowedValues parameter from EC2 template

### ISSUE THREAD

**Issue by tleyden** [coreos/bugs#232]
From Rob Szumski in https://groups.google.com/d/msg/coreos-user/h2ebmFvkRyc/pZvm5s9RYiYJ

> We should just remove this. We had an issue a while ago with only the m1.small instance type, hence the need to prevent you selecting it. I think this issue has been cleared up though.

 > I’ll remove this allowed values parameter altogether. Thanks for pointing this out.

**Comment by robszumski** [comment]
I just pushed these changes live. I tested it, but let me know if it doesn't work for you. Be sure you don't mix up your PV and HVM values!
