### ISSUE TITLE
Bad signatures for some of the released ct-v0.6.0 binaries

### ISSUE THREAD

**Issue by ggsenger** [coreos/bugs#2321]
# Issue Report #

I am unable to verify the given signatures for the [ct-v0.6.0-x86_64-unknown-linux-gnu](https://github.com/coreos/container-linux-config-transpiler/releases/download/v0.6.0/ct-v0.6.0-x86_64-unknown-linux-gnu), [ct-v0.6.0-x86_64-apple-darwin](https://github.com/coreos/container-linux-config-transpiler/releases/download/v0.6.0/ct-v0.6.0-x86_64-apple-darwin) and [ct-v0.6.0-x86_64-pc-windows-gnu.exe](https://github.com/coreos/container-linux-config-transpiler/releases/download/v0.6.0/ct-v0.6.0-x86_64-pc-windows-gnu.exe) binaries.

GPG states the following: 
```bash
gpg: BAD signature from "CoreOS Application Signing Key <security@coreos.com>"
```

### Expected Behavior ###

All released binaries have a valid signature.

### Actual Behavior ###

The signature verification fails for some of the released ct-v0.6.0 binaries.

### Reproduction Steps ###

```bash
#!/bin/sh

curl -sfSL https://github.com/coreos/container-linux-config-transpiler/releases/download/v0.6.0/ct-v0.6.0-x86_64-unknown-linux-gnu -o ct
curl -sfSL https://github.com/coreos/container-linux-config-transpiler/releases/download/v0.6.0/ct-v0.6.0-x86_64-unknown-linux-gnu.asc -o ct.asc
GNUPGHOME_OLD=$GNUPGHOME && export GNUPGHOME="$(mktemp -d)"
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys CDDE268EBB729EC7 &> /dev/null
gpg --batch --verify ct.asc ct
rm -r "$GNUPGHOME"
export GNUPGHOME="$GNUPGHOME_OLD"
rm ./ct.asc ./ct

```

**Comment by sdemos** [comment]
Yeah, that was my fault. I apologize for any confusion this might have caused. Thanks for reporting this! We would like to generally treat releases as immutable entities even though github allows for modification of binaries, so a patch release has been tagged with corrected signatures - https://github.com/coreos/container-linux-config-transpiler/releases/tag/v0.6.1

I manually verified that all these signatures are correct using the method you provided. If you find that it no longer works, please feel free to open another issue and tag me directly.
