### ISSUE TITLE
Document process for bumping Ignition spec version

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2323]
# Issue Report #

### Desired Feature ###

Various things need to be done when bumping the Ignition spec version.  Document them all in one place.

### Other Information ###

Source material:
- https://github.com/coreos/ignition/pull/400
- https://github.com/coreos/ignition/pull/416 (would now apply to OEM base/default configs in coreos-overlay)
- https://github.com/coreos/ignition/pull/426
- https://github.com/coreos/ignition/pull/501

**Comment by dgonyeo** [comment]
I can make sure to write down the steps as I do them for 2.2.0.

**Comment by bgilbert** [comment]
Fixed in https://github.com/coreos/ignition/pull/519.
