### ISSUE TITLE
Add support for applying microcode from the initramfs

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/bugs#2324]
# Issue Report #

## Feature Request ##

The kernel should be able to apply microcode from an initramfs (not just initrds)

### Environment ###

Any bare metal, including packet

### Desired Feature ###

Currently the only two ways for the kernel to apply microcode early in the boot are to either bake it in via `CONFIG_EXTRA_FIRMWARE` or create a seperate initrd with the microcode. Ideally, we should be able to either include it in our `bootengine.cpio` or prepend a cpio to `bootengine.cpio` and use that instead.

### Other Information ###
See https://www.kernel.org/doc/Documentation/x86/early-microcode.txt

**Comment by bgilbert** [comment]
Note that `CONFIG_EXTRA_FIRMWARE` requires the kernel to keep all microcode blobs in RAM forever (3 MB or so), while putting the microcode in the initramfs allows it to drop microcode for CPUs we don't have.

This _should_ be a fairly straightforward kernel patch, modulo any interactions with `CONFIG_INITRAMFS_COMPRESSION`.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
