### ISSUE TITLE
Can I have a newer GCE OEM?

### ISSUE THREAD

**Issue by negz** [coreos/bugs#2330]
# Issue Report #
At the time of writing CoreOS stable is shipping with [compute-image-packages](https://github.com/GoogleCloudPlatform/compute-image-packages)  20170327. I'd like a more modern version so I can turn off the relatively new `IpForwarding` `ip_aliases` [knob](https://github.com/GoogleCloudPlatform/compute-image-packages#configuration).

Setting `ip_aliases = false` prevents Google's IP Forwarding daemon from enforcing a route sending [Alias IP](https://cloud.google.com/compute/docs/alias-ip/) traffic out eth0. We want the Alias IP range to route through cbr0 and into our Kubernetes Pod network.

We've worked around this issue by running our own fork of the GCE OEM image, so this is not a high priority request. 

## Feature Request ##
Update the GCE OEM's compute-image-packages dependency.

### Environment ###
Google Compute Engine.

**Comment by dm0-** [comment]
This will be updated to the latest release in the next alpha (due Thursday).

**Comment by negz** [comment]
Thanks!
