### ISSUE TITLE
Unable to SSH into Oracle OCI VMs

### ISSUE THREAD

**Issue by arithx** [coreos/bugs#2335]
# Issue Report #

## Bug ##

Starting with Alpha `1662.0.0` when booting on Oracle OCI the machine does not boot properly (from the console logs it looks like the machine comes up but `ssh` times out & `ping` hangs indefinitely. `1649.0.0` works correctly.

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1662.0.0
VERSION_ID=1662.0.0
BUILD_ID=2018-01-18-0546
PRETTY_NAME="Container Linux by CoreOS 1662.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Oracle OCI Virtual Machines

### Expected Behavior ###

Machine boots and it's possible to SSH in

### Actual Behavior ###

Machine boots and it's not possible to connect to it.

### Reproduction Steps ###

  1. Upload a `1662.0.0` image into Oracle OCI
  2. Launch the VM & try to SSH in

### Other Information ###

Console Log: https://gist.github.com/arithx/2ddb6be32d1bf2049bda035de33f2fe9

**Comment by ajeddeloh** [comment]
This is a problem with OCI where the route to 0.0.0.0/0 is not being provided in DHCP option 121 (classless static routes). They're working on deploying a fix. I'll close this bug once we confirm it's fixed.

The reason this only showed up as of 1662 is that systemd 236 is the first systemd release to handle rfc3442 correctly and ignore the dhcp option 3 (router) when option 121 is specified.

**Comment by ajeddeloh** [comment]
Closing because it's fixed in OCI.
