### ISSUE TITLE
Consider compressing kernel modules

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/bugs#2339]
# Issue Report #

## Feature Request ##

Consider compressing kernel modules to reduce image size. The USR partitions are only 1GB in size and we're approaching that (currently 78%). We should start taking steps to ensure we do not run out of space.

### Environment ###

All

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Desired Feature ###

`coreos-modules` is the largest package we ship. It's almost entirely composed of things that support compression and compress well. We should at least evaluate if it's worth doing.

### Other Information ###

`tar -cJf mods.tar.xf /usr/lib/modules` reduced the size from ~200MB to ~20MB.

Compressing the modules will slightly increase build time.

@euank you mentioned userspace support issues. Were you refering things shipped in the image or containers/things added by users?

**Comment by glevand** [comment]
`equery-amd64-usr u sys-apps/kmod` shows `- - lzma`, so we would need to add `sys-apps/kmod lzma` to the USE flags if we set `MODULE_COMPRESS_XZ=y`.

**Comment by euank** [comment]
@ajeddeloh A container could also have a `kmod` which doesn't support compression properly and thus fails to load a kernel module.

Debian only turned on xz/zlib for kmod as of [a month ago](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=772628).

One example I think may fail is a container like Kubernetes' kube-proxy or kubelet which loads kernel modules. For example, [here](https://github.com/kubernetes/kubernetes/blob/v1.9.2/pkg/proxy/ipvs/proxier.go#L695-L703) kube-proxy calls `modprobe`, but it's running in a debian based container with no compression support, per the following:

```
$ docker run --entrypoint=kmod gcr.io/google-containers/kube-proxy-amd64:v1.9.2 --version
kmod version 23
-XZ -ZLIB -EXPERIMENTAL
```

**Comment by glevand** [comment]
@euank, @ajeddeloh  Maybe add a feature request to Kubernetes  to support compresses kernel modules.  I would think kube-proxy, etc. could decompress a file before running modprobe.

**Comment by euank** [comment]
@glevand I don't think that really solves the root problem I'm getting at. It's somewhat rare for containers to modprobe existing os modules, but I don't think it's so rare that only k8s is doing it. Other networking containers/tools exist. We can't easily know the full set of things that may similarly break.

In addition, it looks like the space savings, while nice, weren't massive. I think the risk of breaking unknown modprobing-host-modules containers is enough that it's best to just wait a few years for userspace support for compression to propagate through most distros' userspace.

**Comment by glevand** [comment]
@euank I would guess that there are some loadable modules that are always used, and those could be configured as built-in if more space is needed in the usr partition at the expense of the boot partition.  Generally having them built-in will save some space since the support for loading is not needed.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
