### ISSUE TITLE
Grub TPM Error 2

### ISSUE THREAD

**Issue by PhilippHomann** [coreos/bugs#2341]
## Bug ##
When booting an installed version of Container Linux I shortly recognize this output before GRUB boot menu appears:
```
error: TPM error 2, disabling TPM
```
The system keeps booting (as expected by https://github.com/coreos/grub/commit/bf25cda14eb09116a1d92bfcb291968618caa6cb), but `/sys/class/tpm/tpm0/device/pcrs` shows that only PCR 09-10 are being filled by GRUB.

```
PCR-00: E1 DF 69 6B 51 52 B7 17 A1 F0 FA C0 9B DF 27 04 5B C5 98 9A 
...
PCR-10: AA D8 BB C6 DD E5 FF D7 84 15 48 94 F6 AF 2F 3D 60 F1 81 E3 
PCR-11: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-12: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-13: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-14: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-15: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-16: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-17: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-18: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-19: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-20: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-21: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-22: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-23: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

I wonder if that is the expected behaviour. From my knowledge PCR 09-13 should be set by GRUB?!

I already tried everything mentioned in #1529 with no luck.
I also disabled/enabled TPM from BIOS and reset ownership.

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.5.0
VERSION_ID=1576.5.0
BUILD_ID=2018-01-05-1121
PRETTY_NAME="Container Linux by CoreOS 1576.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
HP Elitebook 6480p

### Expected Behavior ###
PCR 09-13 are being set by GRUB.

### Actual Behavior ###
Only PCR 09-10 are being set by GRUB.
GRUB shows `error: TPM error 2, disabling TPM`.

### Reproduction Steps ###

  1. Boot from Container Linux live iso
  2. run `coreos-install -d /dev/sda` 
      (in my case I had to add -f downloaded-file.bz2, because I have no internet access)

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
