### ISSUE TITLE
os linux

### ISSUE THREAD

**Issue by emmanuelfe** [coreos/bugs#2344]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Reproduction Steps ###

  1. ...
  2. ...

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

**Comment by lucab** [comment]
Closing a stray report. Feel free to open a new one with all details if you are encountering any issues.
