### ISSUE TITLE
Ignition translator/config refactor

### ISSUE THREAD

**Issue by dgonyeo** [coreos/bugs#2346]
Converting an experimental spec into a stable spec in Ignition is a rather scary operation. If there are any omissions in the translator that's written for the new experimental spec, fields can be silently ignored by Ignition. If there are any errors in hacking up the new `config/vX_Y` package, there can be issues in processing the new stable config. These cases can both be covered by meticulous tests, but it would be preferable to not have to worry about them at all.

After yak shaving with @bgilbert, we've agreed that a refactor of the `config` package in Ignition would mitigate a lot of the scariness involved in marking an experimental config spec as stable.

There would be two major changes to the current structure:
- Rewrite the translator so that instead of translating any given config into the latest version of the config, each config package (e.g. `config/v2_2`) would be able to translate the prior version of the config into itself. This means that given an old config, Ignition would run it through a series of translation steps instead of one to get it to the latest config. The effects of this are that when a field type is changed (e.g. becomes a `*int` instead of a `int`) the translator only needs to be updated in one place, instead of the logic being modified separately for every translator.
- Move `config/types` into `internal/config/types`, and keep a copy of it in `config/vX_Y_experimental/types`. The `./generate` script would generate both `config/vX_Y_experimental/types/schema.go` and `internal/config/types/schema.go`. A translator would be written in `internal/config` to convert from the latest `config/vX_Y_experimental/types` into `internal/config/types`. This makes `config` spec version agnostic. This has the effect of forcing the translator typically written at a spec bump to be incrementally written as a new experimental config is developed.

With these changes, marking a new stable version would then be renaming `config/vX_Y_experimental` into `config/vX_Y`, copying `config/vX_Y` into `config/vX_(Y+1)_experimental`, copying the translator from `internal/config` into `config/vX_Y`, and tweaking `config` to use the new/renamed packages.

**Comment by bgilbert** [comment]
To be clear, the purpose of the extra translation step from `config/vX_Y_experimental` to `internal/config` is to maintain a unity translator which correctly copies all fields.  This would be the basis of the translator for the _next_ experimental version.

This scheme also fixes another problem: in the current scheme, `config/types` must be used by any application that wants to support multiple config versions, but `config/types` is permanently unstable.  That's not great now, and will be untenable once Ignition reaches 1.0 and needs to start respecting semver.  Instead, applications will be able to use whatever spec version they'd like, including the current experimental version if desired, and will then be able to translate from any earlier spec version.
