### ISSUE TITLE
Can't delete folder created by a docker container

### ISSUE THREAD

**Issue by exocom** [coreos/bugs#235]
Hey coreos team,

I am unable to delete folders that were created by docker container. This is the output (renamed the folder to 1 to keep the error short) :

```
rm: cannot remove '1': Operation not permitted
```

Seem to have full access to the folders, in other words all of the following commands work with out issue:
chmod
chown
chgrp
mv

but folders can't be deleted. I've tried rm -rf, rmdir, sudo rm -rf, sudo rmdir but same error on each command.

The folders come from a Docker-In-Docker container (jpetazzo/dind), that was running as privileged.

```
docker run \
  --env PORT=2375 \
  --privileged=true \
  -v /home/core/data/docker/:/var/lib/docker/ \
  --rm \
  -i jpetazzo/dind
```

After creating the container, I opened a bash on the container and did a docker pull, stoped the container, restatred it to verify the images persisted, they did :). Went to clean up the /home/core/data/docker/ folder and ran into this.

Let me know if you need any other info.

**Comment by marineam** [comment]
Is it a btrfs subvolume? It will appear in `btrfs subvolume list` and can be removed by `btrfs subvolume delete`

**Comment by exocom** [comment]
@marineam That was is!  Thank you so much, I was stumped.

For future reference I was able to remove them using

```
$ sudo btrfs subvolume delete 22093c35d77bb609b9257ffb2640845ec05018e3d96cb939f68d0e19127f1723/
Transaction commit: none (default)
Delete subvolume '/cleanup/22093c35d77bb609b9257ffb2640845ec05018e3d96cb939f68d0e19127f1723'

```
