### ISSUE TITLE
ssh keyfiles in authorized_keys.d are truncated on hard system reset in the first minute

### ISSUE THREAD

**Issue by sdemos** [coreos/bugs#2350]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.2.1
VERSION_ID=1632.2.1
BUILD_ID=2018-02-01-2053
PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

virtualbox, though it would likely happen on any platform during a crash that halts the cpu. 

### Expected Behavior ###
ssh keys exist and are populated after a system reset

### Actual Behavior ###
ssh keys exist but are empty

### Reproduction Steps ###

  1. have a virtualbox vm that is running cloudinit or (probably) coreos-metadata to get it's ssh-keys
  2. boot up the vm
  3. hard reset within the first minute
  4. on reboot, you can't ssh in

### Other Information ###

The current vastly most probable reason for this is that `update-ssh-keys` doesn't fsync the files it writes to disk, and so if the write buffer doesn't get flushed to disk before there is a hard reset, then they show up as empty files (since the filesystem stays intact). The reason it would show up on virtualbox more consistently than other platforms could be a combination of whatever filesystem drivers they have and the hard reset they perform (they trigger a triple fault from my understanding).

I haven't gotten to test out this particular fix yet, because I've been busy and haven't gotten a test image or finished a patch. However, on linux the rust function [`sync_all`](https://doc.rust-lang.org/beta/std/fs/struct.File.html#method.sync_all) on files runs fsync under the hood (see the [fs implementation](https://doc.rust-lang.org/beta/src/std/fs.rs.html#394-396) and the [underlying unix implementation](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fs.rs#L464)), so calling that should fix this issue.

**Comment by bgilbert** [comment]
To be thorough, we should also be calling `fsync` on the file's containing directory.  Because we're renaming the files into place, this should happen after the rename.

**Comment by sdemos** [comment]
with a few minutes of searching, I couldn't find a way to call `fsync` on a dirctory in rust. rust provides `std::fs::read_dir` which returns an iterator over the directory contents, but there doesn't seem to be a way to get a reference to a directory directly, at least not one that has a file handle that we can run `fsync` on. I can dig more into it though, maybe I'm missing something obvious. 

Also fwiw we are only renaming the directory itself; the files are written into the staging directory and then they aren't modified after that. I suppose I'm not well versed enough in the details of filesystems to know if changing the directory changes the contained files at all.

**Comment by sdemos** [comment]
okay so I was missing something obvious. you can just open a directory using the standard `std::fs::File` interface and then run `sync_all` on that just like a normal file.

**Comment by bgilbert** [comment]
Okay, then we'd need to fsync the staging directory, rename it, then fsync its parent.  The goal is to make sure that the directory entry for any given file or directory is written to disk.
