### ISSUE TITLE
portage-stable: net-libs/libpcap build failure

### ISSUE THREAD

**Issue by glevand** [coreos/bugs#2355]
I got a jenkins build failure in net-libs/libpcap:
```
net-libs/libpcap-1.8.1/work/libpcap-libpcap-1.8.1/grammar.y:78:21: fatal error: scanner.h: No such file or directory
```
On re-run it built OK.  It seemed like a make dependency bug and I found this:

  https://patchwork.openembedded.org/patch/140984/

I haven't looked into it, but maybe syncing net-libs/libpcap to gentoo upstream will include a fix.

**Comment by dm0-** [comment]
It doesn't look like the-tcpdump-group/libpcap@0dd90a6bdbce4dca14106859eee63ef643a106e2 is included in https://github.com/gentoo/gentoo/tree/master/net-libs/libpcap/files yet.  If it's an issue for you, we could move the package to the overlay to pick up the patch.  If it's not urgent we might as well submit a PR directly to Gentoo and sync portage-stable when it's ready.

**Comment by glevand** [comment]
I submitted a gentoo bug:
  https://bugs.gentoo.org/647538 (net-libs/libpcap: scanner.h: No such file or directory).
I think it is enough to wait and then sync the package in portage-stable.

**Comment by glevand** [comment]
Just to update, a fix was merged to upstream Gentoo and my bug report closed: https://bugs.gentoo.org/647538.

**Comment by dm0-** [comment]
Thanks for getting that upstream, we've applied the update in portage-stable.
