### ISSUE TITLE
Docker unregister_netdevice hang, reopen #254

### ISSUE THREAD

**Issue by cehoffman** [coreos/bugs#2359]
# Issue Report #

https://github.com/coreos/bugs/issues/254

## Bug ##

Docker become unable to launch new containers.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.2.1
VERSION_ID=1632.2.1
BUILD_ID=2018-02-01-2053
PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Running in Azure East US 2 on a Standard_L8s instance. This running Tectonic 1.8.4-tectonic.3 with docker 17.03.2-ce.

### Expected Behavior ###

New pods can launch on machine.

### Actual Behavior ###

Docker becomes stuck with:

```
[Tue Feb 13 22:26:54 2018] EXT4-fs (pxd!pxd475270347521599972): mounted filesystem with ordered data mode. Opts: discard
[Tue Feb 13 22:26:56 2018] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[Tue Feb 13 22:26:56 2018] IPv6: ADDRCONF(NETDEV_UP): cali760305f6bec: link is not ready
[Tue Feb 13 22:26:56 2018] IPv6: ADDRCONF(NETDEV_CHANGE): cali760305f6bec: link becomes ready
[Tue Feb 13 22:26:56 2018] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[Tue Feb 13 22:47:14 2018] unregister_netdevice: waiting for eth0 to become free. Usage count = 1
[Tue Feb 13 22:47:24 2018] unregister_netdevice: waiting for eth0 to become free. Usage count = 1
[Tue Feb 13 22:47:34 2018] unregister_netdevice: waiting for eth0 to become free. Usage count = 1
[Tue Feb 13 22:47:44 2018] unregister_netdevice: waiting for eth0 to become free. Usage count = 1
```

### Reproduction Steps ###

  1. Running Tectonic and farming jobs to cluster
 
### Other Information ###

This same cluster has been running since May 2016 with kubernetes 1.6.2. This is the first time I have experienced this problem without any significant changes to cluster makeup in a 3 weeks (node type change).

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

**Comment by euank** [comment]
I can't quite tell from your description; does this happen with any level of frequency, or is this more of a "lighting strikes" event?

Anyways, xref https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1711407 where ongoing investigation for this issue is occurring.

The last patch to result from that investigation ([this one](https://github.com/torvalds/linux/commit/4ee806d51176ba7b8ff1efd81f271d7252e03a1d)) is included in the 4.14.16 kernel, which you're running, so this quite possibly is the as-of-yet unfixed variant being investigated in that bug now.

**Comment by cehoffman** [comment]
More of a lightning strikes, but given the history of the symptom and the suggestion to open a new issue if it appeared on Container Linux I thought I'd drop an issue here.

Looking through the system logs of the node, it appears it was draining pods when this occurred. I don't know why it was doing that though. There is a bug https://github.com/Azure/acs-engine/issues/863 where nodes erroneously become NotReady that may have been the cause there.

We run Portworx on these nodes an recently upgrade (just over ~30 hours earlier) to 1.2.18 from 1.2.14, but it doesn't interact with the network stack of containers to provide persistent volume support as far as I'm aware.

**Comment by cehoffman** [comment]
Had this happen again on 1632.3.0. A drain of the pods on the node had been issued because of a problem with the physical disk. The drain stalled because infinite wait for unregister on eth0.

**Comment by cehoffman** [comment]
We've had this a few more times and I think an event that seems to make it more likely is a mass pod eviction. Taking an instance with 30 or more pods that can stop quickly and triggering a drain has a chance of triggering this.

**Comment by redbaron** [comment]
It feels like SIGKILL has higher chance of triggering it, so making sure that pod processes are exiting within terminationGracePeriodSeconds helps a lot with this issue

**Comment by bgilbert** [comment]
Are you still seeing this on current versions of Container Linux?

**Comment by cehoffman** [comment]
I haven’t seen this in several months.

**Comment by bgilbert** [comment]
Okay, I'll close.  Please reopen if the issue recurs.
