### ISSUE TITLE
docker process is not reading /root/.dockercfg

### ISSUE THREAD

**Issue by aledbf** [coreos/bugs#236]
The information in the docs (https://coreos.com/docs/launching-containers/building/registry-authentication/) only works for the coreos user. If I need authentication "by default" this is not possible because the docker process doesn't read the `.dockerfile` located in `/root/.dockercfg`.
To test this I follow the docs and that works fine if I execute docker as core. After that I just copied the `.dockercfg` to the root folder and run the same pull as root but that fails.

As a workaround if I add a service like:
```
  - name: docker-login.service
    command: start
    content: |
      [Unit]
      Description=use docker credentials
      After=docker.service

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/sh -c 'docker login -u <username> -p <password> -e <email> <url>'
```
this works
Any idea?
Thanks.

**Comment by aledbf** [comment]
I found the problem. The `docker.service` it doesn't declare the `HOME` variable and the docker cli https://github.com/docker/docker/blob/60027853aa1d233b0bbd95250125605ba5bf2c5f/api/client/cli.go#L108 uses that variable as base path to where `.dockercfg` must exists to use authentication.

Just adding `Environment=HOME=/root` in the Service section of `docker.service` solves the problem but I don't know if this is the correct way.

**Comment by marineam** [comment]
Alternatively when `$HOME` is blank it just winds up looking in the current directory so you can set `WorkingDirectory=` to the directory containing `.dockercfg`. Either scheme should work just fine.

**Comment by aledbf** [comment]
@marineam it is required the `docker login` when running as root? 
As user `core` I don't need to run `docker login` to pull/push

**Comment by marineam** [comment]
I assume because the core user had previously run docker login? Or maybe there is some other behavior tweak I'm not thinking of. You can always have the unit run as core by using the `User=` option.
