### ISSUE TITLE
coreos-metadata should only make necessary requests to metadata services

### ISSUE THREAD

**Issue by sdemos** [coreos/bugs#2362]
### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

all, particularly ones with more segmented metadata service apis.

### Desired Feature ###

`coreos-metadata` should take into account the requested metadata when making calls to the metadata service.

### Other Information ###

Right now, `coreos-metadata` collects all available metadata for the specified provider into a common metadata struct. However, not all of that metadata necessarily gets used. In fact, it's almost always one or two of them that get used. 

Some metadata services provide all the required metadata in one giant slug, like [Digital Ocean](https://github.com/coreos/coreos-metadata/blob/master/src/providers/digitalocean/mod.rs#L70). For those, we wouldn't really do anything differently.

Some services provide separate endpoints for all concievable metadata, like [AWS](https://github.com/coreos/coreos-metadata/blob/master/src/providers/ec2/mod.rs#L44). For those, we would be able to reduce the number of network calls to the metadata service, and reduce possible failures that aren't caused by us, but make `coreos-metadata` fail to retrieve otherwise unrelated metadata (see #2361).

"Some" services (looking at you, [Azure](https://github.com/coreos/coreos-metadata/blob/master/src/providers/azure/mod.rs#L225)) require us to do a significant amount of computational work to get metadata that we might not use. With Azure in particular, we have to call do a significant amount of cryptographic work to extract the ssh keys from the metadata service, and that happens even when `coreos-metadata` isn't asked to retrieve the ssh keys.

For example: if the regular [coreos-metadata systemd unit](https://github.com/coreos/coreos-overlay/blob/master/coreos-base/coreos-metadata/files/coreos-metadata.service) is enabled it runs `coreos-metadata --cmdline --attributes=/run/metadata/coreos`, which is only asking for the attributes file to be populated. However, `coreos-metadata` still fetches all the ssh public keys and network configuration information and then chucks it straight into the garbage. If possible, we should avoid getting that information at all if it isn't going to be useful for this run.

**Comment by ajeddeloh** [comment]
Right now `coreos-metadata` doesn't know what metadata it needs, and even so there's nothing to stop people from writing units that depend on the contents of the environment file. I don't think `coreos-metadata` should attempt any introspection as to what is needed at runtime, since users might have use cases it doesn't know about. 

It could work to have some command line flags or environment variables or something that tells it what to fetch (which I'm guessing is what you're suggesting). Then `ct` could use what it knows from the sections with dynamic data. We would still need to provide an override for users with configurations that do use the metadata in other places and possibly make it opt-in instead of opt-out to avoid breakage.

**Comment by sdemos** [comment]
I think you are misunderstanding what I'm saying. I'm not talking about breaking up the attributes file that `coreos-metadata` generates. At a higher level than that, `coreos-metadata` knows exactly what metadata it needs to get. 

`coreos-metadata` currently has the concept of four different "types" of metadata - attributes, ssh keys, the hostname, and network units (see [the flag definitions](https://github.com/coreos/coreos-metadata/blob/master/src/bin/coreos-metadata.rs#L120) and [the metadata writing logic](https://github.com/coreos/coreos-metadata/blob/master/src/bin/coreos-metadata.rs#L74). It doesn't actually output any of those four things that weren't explicitly asked for. However, right now, no matter which one of those four things are asked for, we get all the available metadata information. I'm saying we should only get what is asked for, and nothing more, whenever possible.

**Comment by ajeddeloh** [comment]
Reopening until changes make it in to coreos-overlay

**Comment by csssuf** [comment]
Reopening until a new release is cut and updated in coreos-overlay.
