### ISSUE TITLE
Caching cluster node discovery

### ISSUE THREAD

**Issue by HarmenM** [coreos/bugs#237]
Yesterday I experienced downtime of the https://discovery.etcd.io/ cluster discovery service. After some search on twitter I found out I was not the only one having troubles getting my cluster up and running (https://twitter.com/eik3/status/554665505009958912).

I first experienced problems after a node automatically went down to do an upgrade of the coreos system. After reboot, the system could not discover the other nodes in my cluster, due to the lack of response of the discovery.etcd.io cluster discovery webservice.

Maybe it is an idea to cache the available service discovery data before going down for a reboot, so that the node has a fallback strategy in case cluster discovery is down?

**Comment by yichengq** [comment]
For etcd 2.x, we recommend users to use static bootstrap(https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static), and discovery service only helps on initial bootstrapping stage of etcd cluster now(https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#etcd-discovery). So it is no longer a problem now.
