### ISSUE TITLE
Misleading information in Stateful root about "factory reset"

### ISSUE THREAD

**Issue by Constantin07** [coreos/bugs#2370]
# Issue Report #

https://coreos.com/os/docs/latest/sdk-disk-partitions.html
Under `Stateful root` in my opinion is a misleading info which should be corrected:

```
Due to the unique disk layout of Container Linux, an rm -rf / is an un-supported but valid operation to do a "factory reset". The machine should boot and operate normally afterwards.
```

`rm -rf` / deletes as well /boot after which kernel cannot be found so machine cannot boot.

### Container Linux Version ###
Stable 1632.3.0

### Environment ###

Any.

### Expected Behavior ###

Provide correct documentation on how to actually do a `factory reset`.

### Actual Behavior ###

Wrong guidance given.

**Comment by dm0-** [comment]
Thanks for reporting this, we'll update the documentation.  You could try adding `--one-file-system` to the `rm` command.

A cleaner way may be to reformat the partition, which can be done on the same system by booting with `rd.break` on the kernel command-line to get a prompt in the initramfs so you can run `mke2fs` before changing to the file system.

**Comment by Constantin07** [comment]
@dm0- thanks for advice `rm -rf --one-file-system --no-preserve-root /` restored to factory without executing ignition after reboot.

I believe getting a prompt at boot in AWS is not possible.

**Comment by lucab** [comment]
@Constantin07 thanks for checking and reporting back! I've amended the docs with your suggestion at https://github.com/coreos/docs/pull/1213.

**Comment by lucab** [comment]
Closes via https://github.com/coreos/docs/pull/1213
