### ISSUE TITLE
Updating CoreOS will not update open-vm-tools 

### ISSUE THREAD

**Issue by Winnie81** [coreos/bugs#2372]
# Issue Report #

Updating CoreOS will not update open-vm-tools 

### Container Linux Version ###

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.6.0
VERSION_ID=1409.6.0
BUILD_ID=2017-07-06-0128
PRETTY_NAME="Container Linux by CoreOS 1409.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

### Environment ###

ESXi 6.0GA

### Expected Behavior ###
Updating CoreOS will also update open-vm-tools.

### Actual Behavior ###
Updating CoreOS will not update open-vm-tools.

### Reproduction Steps ###

  1. Install CoreOS 1409.6.0 from VMWare ESX, then configure user name and password.
  2. Edit /etc/coreos/update.conf by modifying "Group=stable" as "Group=alpha"
  3.From terminal, input "sudo systemctl restart update-engine" 
 4. Check its status by "journalctl -f -u update-engine". 

It will give some tips to leave X minutes for next update.
After X minutes, we can find this VM reboot automatically
Check its current version by "cat /etc/os-release" and it has been updated as latest 1688.0.0 build.

**Comment by Winnie81** [comment]
@john Savanyo jsavanyo@vmware.com
@Oliver Kurth <okurth@vmware.com>

**Comment by glevand** [comment]
open-vm-tools is now at v10.1.10. @Winnie81 What version do you get? 
See: https://github.com/coreos/coreos-overlay/commit/3b95fcdbde1c1e2c051d335c6

**Comment by Winnie81** [comment]
@glevand It is still 10.1.5.59732, and which is ovt of 1409.6.0.

**Comment by lucab** [comment]
Just to confirm @Winnie81 report: indeed, ContainerLinux update mechanism (via `update_engine`) does not currently update the OEM partition, which is were `open-vm-tools` is located. Thus the version which was initially installed will persist across updates.

This is an unfortunate limitation of the update mechanism, and it is related to the fact that there are no [allocated](https://coreos.com/os/docs/latest/sdk-disk-partitions.html) A/B partitions for the OEM image. I think this limitation is documented somewhere in the OS docs, but I don't have a reference at hand.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
