### ISSUE TITLE
1688.1.1 Beta - Deadlock in kernel 4.14.22 (Already fixed upstream in 4.14.23)

### ISSUE THREAD

**Issue by martynd** [coreos/bugs#2375]
# Issue Report #

## Bug ##

Beta release has a kernel issue resulting in socket deadlocks requiring a hard reboot of machines

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.1.1
VERSION_ID=1688.1.1
BUILD_ID=2018-02-28-0132
PRETTY_NAME="Container Linux by CoreOS 1688.1.1 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
Bare metal setup, nothing out of the ordinary

### Expected Behavior ###
Socket usage not causing deadlocks after certain netfilter actions take place

### Actual Behavior ###
Socket usage causes deadlocks due to netfilter activity. Machines need to be force rebooted

### Reproduction Steps ###
Issue present in kernel 4.15.6 and 4.14.22

### Other Information ###
Upstream fix
https://github.com/torvalds/linux/commit/d7ef969797fdeeb12a3afe069d86d1eaf037ac71

Similar reports:
https://bugs.archlinux.org/task/57651?project=1
https://bugs.archlinux.org/task/57684?project=1

**Comment by bgilbert** [comment]
Fixed in alpha 1702.1.0 and beta 1688.2.0.  Thanks for the report.
