### ISSUE TITLE
ignition: systemd service remains disabled

### ISSUE THREAD

**Issue by schu** [coreos/bugs#2376]
I want to enable the `iptables-restore.service` (included in Container Linux by default, but disabled) from ignition, the relevant part of my config looks like

```
systemd:
  units:
    - name: "iptables-restore.service"
      enabled: true
...
```

But the services remains in state disabled. Is something wrong or missing here?

Container Linux 1632.3.0

**Comment by lucab** [comment]
Before starting to investigate this, can you please check and attach anything relevant from [ignition logs](https://coreos.com/ignition/docs/latest/getting-started.html#gathering-logs)? Moreover, what do `sudo systemctl status iptables-restore` and `sudo ls -la /etc/systemd/system/*` say?

**Comment by bgilbert** [comment]
That CLC fragment worked for me in a quick test.

**Comment by schu** [comment]
Ah, I didn't know the logs are available in journald. There I see

```
Feb 28 09:03:57 localhost ignition[408]: warning at line 13, column 18
                                            12:       {
                                            13:         "enabled"
                                                                ^
                                         Config has unrecognized key: enabled
```

The rendered config looks like

```
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "systemd": {
    "units": [
      {
        "enabled": true,
        "name": "iptables-restore.service"
      },
      {
        "enabled": true,
        "name": "ip6tables-restore.service"
      }
    ]
  },
...
```

I used ct v0.7.0

>  what do `sudo systemctl status iptables-restore` and `sudo ls -la /etc/systemd/system/*` say?

I manually enabled the service on the system meanwhile but before it was disabled.

Thanks.

**Comment by bgilbert** [comment]
It should be impossible to get the rendered config you provided: ct < 0.5.0 doesn't recognize `enabled`, and ct &ge; 0.5.0 won't emit a version 2.0.0 config.  Ignition is rejecting the `enabled` key because that is only supported in configs &ge; 2.1.0.  Are you passing the Ignition config through any other tooling?

**Comment by arithx** [comment]
The `enabled` field for systemd units is not valid in an Ignition `2.0.0` config. ct v0.7.0 produces Ignition version `2.1.0` configs (where `enabled` is a valid field), when ran on my local system with the config:

```
systemd:
  units:
    - name: "iptables-restore.service"
      enabled: true
```

produces

```
{
  "ignition": {
    "config": {},
    "timeouts": {},
    "version": "2.1.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {
    "units": [
      {
        "enabled": true,
        "name": "iptables-restore.service"
      }
    ]
  }
}
```

**Comment by schu** [comment]
Found the issue: I had used ct v0.7.0 but actually manually merged the systemd part of the new config with an older file in the project, hence the discrepancy (2.0.0 vs 2.1.0). Sorry for the noise and thank you for the quick help!
