### ISSUE TITLE
docker failed to start  os version 1632.3.0 ( help needed)

### ISSUE THREAD

**Issue by darktall** [coreos/bugs#2380]
i updated coreos machine from 15.x to DISTRIB_RELEASE=1632.3.0  facing issue with docker daemon.
using default  docker start up script which come from coreos.  its not  able to start docker service. i deleted   /var/lib/docker  and restarted  the box still its not getting started. All i am seeing logs as below.

journal logs for docker in docker mode 

nstalled deserialized job docker.service/start as 235
Mar 09 07:50:36  systemd[1]: docker.service: Trying  to enqueue job docker.service/start/replace
Mar 09 07:50:36 systemd[1]: docker.service: Merged into installed job docker.service/start as 235
Mar 09 07:50:36 systemd[1]: docker.service: Enqueued job docker.service/start as 235

**Comment by euank** [comment]
@darktall Can you fill out the other information listed in the [issue template](https://github.com/coreos/bugs/blob/master/ISSUE_TEMPLATE.md), such as the environment?

> using default docker start up script which come from coreos

Mind clarifying what you mean by that?

**Comment by darktall** [comment]
@euank  Thank you. I added useful report.

Issue Report
Bug
Container Linux Version
$ cat /etc/os-release

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.3.0
VERSION_ID=1632.3.0
BUILD_ID=2018-02-14-0338
PRETTY_NAME="Container Linux by CoreOS 1632.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

Environment
What hardware/cloud provider/hypervisor is being used to run Container Linux?

Product Name: VMware Virtual Platform
Product Name: 440BX Desktop Reference Platform

hypervisor : vmware 

Expected Behavior
docker should start using systemd commmands ( systemctl start docker )

Actual Behavior
when tying to start using systemd commands docker hung forever but when trying to start using dockerd from /usr/bin/dockerd  it's starting successfully. 


start up script

$systemctl cat docker
# /run/systemd/system/docker.service
[Unit]
Requires=torcx.target
After=torcx.target
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=containerd.service docker.socket network-online.target
Wants=network-online.target
Requires=containerd.service docker.socket

[Service]
EnvironmentFile=/run/metadata/torcx
Environment=TORCX_IMAGEDIR=/docker
Type=notify
EnvironmentFile=-/run/flannel/flannel_docker_opts.env
Environment=DOCKER_SELINUX=--selinux-enabled=true

# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/env PATH=${TORCX_BINDIR}:${PATH} ${TORCX_BINDIR}/dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock $DOCKER_SELINUX $DOCKER_OPTS $DOCKER_CGROUPS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCK
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/docker.service.d/10-debug.conf
[Service]
Environment=DOCKER_OPTS=--debug
# /etc/systemd/system/docker.service.d/50-insecure-registry.conf
[Service]
Environment=DOCKER_OPTS='--insecure-registry="10.98.8.100:5000"'

journalctl logs:

-- Reboot --
Mar 09 09:24:56 docker-dev1 systemd[1]: docker.service: Installed new job docker.service/start as 271
Mar 09 09:28:02 docker-dev1 systemd[1]: docker.service: Trying to enqueue job docker.service/start/replace
Mar 09 09:28:02 docker-dev1 systemd[1]: docker.service: Merged into installed job docker.service/start as 271
Mar 09 09:28:02 docker-dev1 systemd[1]: docker.service: Enqueued job docker.service/start as 271
Mar 09 09:47:44 docker-dev1 systemd[1]: docker.service: Job docker.service/start finished, result=canceled
Mar 09 09:47:44 docker-dev1 systemd[1]: docker.service: Installed new job docker.service/stop as 1475
Mar 09 09:47:44 docker-dev1 systemd[1]: docker.service: Job docker.service/stop finished, result=done
-- Reboot --
Mar 09 09:47:54 docker-dev1 systemd[1]: docker.service: Installed new job docker.service/start as 253
Mar 09 09:48:42 docker-dev1 systemd[1]: docker.service: Trying to enqueue job docker.service/start/replace
Mar 09 09:48:42 docker-dev1 systemd[1]: docker.service: Merged into installed job docker.service/start as 253
Mar 09 09:48:42 docker-dev1 systemd[1]: docker.service: Enqueued job docker.service/start as 253
Mar 09 09:51:17 docker-dev1 systemd[1]: docker.service: Trying to enqueue job docker.service/start/replace
Mar 09 09:51:17 docker-dev1 systemd[1]: docker.service: Merged into installed job docker.service/start as 253
Mar 09 09:51:17 docker-dev1 systemd[1]: docker.service: Enqueued job docker.service/start as 253
Mar 09 11:46:54 docker-dev1 systemd[1]: docker.service: Trying to enqueue job docker.service/start/replace
Mar 09 11:46:54 docker-dev1 systemd[1]: docker.service: Merged into installed job docker.service/start as 253
Mar 09 11:46:54 docker-dev1 systemd[1]: docker.service: Enqueued job docker.service/start as 253
Mar 09 12:30:36 docker-dev1 systemd[1]: docker.service: Trying to enqueue job docker.service/start/replace
Mar 09 12:30:36 docker-dev1 systemd[1]: docker.service: Merged into installed job docker.service/start as 253
Mar 09 12:30:36 docker-dev1 systemd[1]: docker.service: Enqueued job docker.service/start as 253
Mar 10 03:44:58 docker-dev1 systemd[1]: docker.service: Reinstalled deserialized job docker.service/start as 253
Mar 10 03:44:58 docker-dev1 systemd[1]: docker.service: Reinstalled deserialized job docker.service/start as 253
Mar 10 03:45:10 docker-dev1 systemd[1]: docker.service: Trying to enqueue job docker.service/start/replace
Mar 10 03:45:10 docker-dev1 systemd[1]: docker.service: Merged into installed job docker.service/start as 253
Mar 10 03:45:10 docker-dev1 systemd[1]: docker.service: Enqueued job docker.service/start as 253

**Comment by ajeddeloh** [comment]
Is the systemd unit cut off? It ends in `$DOCK`? Can you edit `/etc/systemd/system.conf` to set the log level to debug, run `systemctl daemon-reload` and then see if the logs have anything more of interest in them?

**Comment by darktall** [comment]
@ajeddeloh  i enabled LogLevel=debug the above are the logs that i gathered after enabling systemd loglevel in debug mode.  

What else i need to provide more. please let me know.

**Comment by ajeddeloh** [comment]
Can you run jouranclt with `UNIT=docker.service + _SYSTEMD_UNIT=docker.service + _PID=1`? Logs from when a unit is just being started sometimes aren't logged with _SYSTEMD_UNIT which `journalctl -u` is specifying.

Can you try with alpha or beta, just to help narrow down the problem?

Is there anything notable in your ignition config or cloud config?

**Comment by darktall** [comment]
i disabled and stopped flannel. docker started successfully after flannel service stopped. 
Please close this ticket.

journactl UNIT=docker.service + _SYSTEMD_UNIT=docker.service + _PID=1 really helped me.

Thank you.
