### ISSUE TITLE
update ignition to look for `/usr/{,s}bin/chroot`

### ISSUE THREAD

**Issue by dustymabe** [coreos/bugs#2392]
## Feature Request ##

Make ignition look use the available chroot binary whether it be in `/usr/bin/chroot/` or `/usr/sbin/chroot`

```
[root@c7 ~]# ignition --log-to-stdout --oem qemu --stage files
INFO     : Ignition 0.23.0                                         
INFO     : reading system config file "/usr/lib/ignition/base.ign" 
INFO     : no config at "/usr/lib/ignition/base.ign"               
INFO     : files: createUsers: op(1): [started]  checking if user "core" exists                                                        
DEBUG    : files: createUsers: op(1): executing: "/usr/bin/chroot" "/" "/usr/bin/id" "core"                                            
CRITICAL : files: createUsers: op(1): [failed]   checking if user "core" exists: fork/exec /usr/bin/chroot: no such file or directory: Cmd: "/usr/bin/chroot" "/" "/usr/bin/id" "core" Stdout: "" Stderr: ""                                                                   
INFO     : files: createUsers: error encountered (*errors.errorString): fork/exec /usr/bin/chroot: no such file or directory: Cmd: "/usr/bin/chroot" "/" "/usr/bin/id" "core" Stdout: "" Stderr: ""                                                                            
CRITICAL : files: failed to create users/groups: failed to create users: failed to create user "core": fork/exec /usr/bin/chroot: no such file or directory: Cmd: "/usr/bin/chroot" "/" "/usr/bin/id" "core" Stdout: "" Stderr: ""
```

### Environment ###

Fedora/CentOS

**Comment by bgilbert** [comment]
The path is a compile-time option.  The specfile should build with:
```
-X github.com/coreos/ignition/internal/distro.chrootCmd=/usr/sbin/chroot
```

**Comment by dustymabe** [comment]
> The path is a compile-time option. The specfile should build with:

+1. I didn't realize that

**Comment by ajeddeloh** [comment]
Closing since Ignition can change this via compile time options.

**Comment by cgwalters** [comment]
That said...`chroot` is a rather "old school" way to run software in an alternate root in 2018 :smile:   There's `systemd-nspawn`, `runc`, and (yeah I'm biased) [bubblewrap](https://github.com/projectatomic/bubblewrap/).  The latter is about the thinnest possible wrapper around the basic kernel container functionality; both runc/nspawn for example try to maintain a global list of containers.

**Comment by bgilbert** [comment]
@cgwalters Ignition is using it to run `/usr/bin/id` inside `/sysroot`.  Is any of those alternatives a sufficient improvement to be worth carrying in the initramfs?

**Comment by cgwalters** [comment]
bwrap is tiny:
```
$ ls -alh /usr/bin/bwrap
-rwxr-xr-x. 4 root root 56K Dec 31  1969 /usr/bin/bwrap
```

I don't see an immediate need to change, but there are real bugs one can hit with "raw chroot" around basics if e.g. `/dev` and `/proc` aren't mounted - running software without an accessible `/dev/null` and `/dev/urandom` is fairly hostile, and a lot of software parses `/proc/self/fd`, etc.
