### ISSUE TITLE
etcd2.service is no present causing oem-cloudinit.service to fail

### ISSUE THREAD

**Issue by benjaminbarbe** [coreos/bugs#2395]
## Bug ##

etcd2.service is no present causing oem-cloudinit.service to fail

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
DigitalOcean

### Expected Behavior ###

etcd2.service to be present and oem-cloudinit.service able to start

### Actual Behavior ###

```
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Enabling unit file "systemd-journal-gatewayd.socket"
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Enabled unit "systemd-journal-gatewayd.socket"
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Ensuring runtime unit file "etcd.service" is unmasked
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Writing drop-in unit "20-cloudinit.conf" to filesystem
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Writing file to "/run/systemd/system/etcd2.service.d/20-cloudinit.conf"
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Wrote file to "/run/systemd/system/etcd2.service.d/20-cloudinit.conf"
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Wrote drop-in unit "20-cloudinit.conf"
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Ensuring runtime unit file "etcd2.service" is unmasked
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Ensuring runtime unit file "fleet.service" is unmasked
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Ensuring runtime unit file "locksmithd.service" is unmasked
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Calling unit command "start" on "etcd2.service"
Apr 06 05:27:38 content-01 coreos-cloudinit[719]: 2018/04/06 05:27:38 Failed to apply cloud-config: Unit etcd2.service not found.
Apr 06 05:27:38 content-01 systemd[1]: oem-cloudinit.service: Main process exited, code=exited, status=1/FAILURE
Apr 06 05:27:38 content-01 systemd[1]: oem-cloudinit.service: Failed with result 'exit-code'.
Apr 06 05:27:38 content-01 systemd[1]: Failed to start Cloudinit from DigitalOcean metadata.
```

### Other Information ###

I haven't changed anything, it's the latest stable version who cause this problem.

Thanks

**Comment by lucab** [comment]
Thanks for the report. Can you please attach the cloudinit configuration you are using to provision this node?

Moreover, please note that both on-host etcd2 and coreos-cloudinit have been on a deprecation notice, and etcd2 was recently removed as planned:
 * https://coreos.com/blog/toward-etcd-v3-in-container-linux.html
 * https://coreos.com/blog/introducing-ignition.html

**Comment by benjaminbarbe** [comment]
Thanks @lucab for your quick response

```
#cloud-config

coreos:
  etcd2:
    discovery: https://discovery.etcd.io/#
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380
  units:
    - name: etcd2.service
      drop-ins:
        - name: "timeout.conf"
          content: |
            [Service]
            TimeoutStartSec=0
      command: start
    - name: fleet.service
      command: start
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target
    - name: systemd-journal-gatewayd.socket
      command: start
      enable: yes
      content: |
        [Unit]
        Description=Journal Gateway Service Socket
        [Socket]
        ListenStream=/var/run/journald.sock
        Service=systemd-journal-gatewayd.service
        [Install]
        WantedBy=sockets.target
write_files:
  - path: /etc/fleet/fleet.conf
    permissions: 0644
    content: |
      metadata="name=core-01"
  - path: /etc/systemd/system/docker.service.d/50-insecure-registry.conf
    content: |
      [Service]
      Environment=DOCKER_OPTS='--insecure-registry="0.0.0.0/0"'
```

**Comment by tonglil** [comment]
Is there a way to configure container linux config without having to run `ct` locally first?

The nice thing about cloud-config was that I didn't need to do any compiling locally (or in my CI/CD).

**Comment by ajeddeloh** [comment]
No. We strongly recommend you use `ct`. You _can_ write Ignition configs by hand, but it's a pretty painful process and we do not recommend it. If your config doesn't change much, you can take the resulant Ignition config, which can be handed to the machine directly and use it where you used the cloud-config. The Ignition spec is backwards compatible so newer releases will accept old configs just fine. If your config does change a lot, I'd recommend you work `ct` into your development workflow and/or CI/CD pipeline. It does validation as well as translation, so you can catch a lot of errors earlier.

**Comment by tonglil** [comment]
I have been trying to convert my cloudconfig to clc yaml but `ct` has problems dealing with multiline strings I need to put as files. Many of these files are yaml and json themselves.

Additionally debugging clc is difficult since `ct` just spits out basic error messages like this without any context (which is hard to find since the clc yaml is generated by terraform):
```
error: yaml: line 28: could not find expected ':'
Failed to parse config
```

**Comment by ajeddeloh** [comment]
I assume you're using a pipe `|` then ensuring the contents of the file is indented properly? If so, please open a new bug (as it's getting off topic for this one) with an example. Given the error message, I'd double check you have:
```
inline: |
    file contents
```
and not 
```
inline |
    file contents
```

Finally, ct does allow you to include files from your filesystem by using `local` instead of `inline` or `remote`. If the yaml in yaml is hard to read, I'd recomment that.

**Comment by ajeddeloh** [comment]
Closing, since etcd2 won't be added back. Please open a new bug if you find any issues with ct or Ignition.
