### ISSUE TITLE
CoreOS fails to shut down on Rackspace Public Cloud

### ISSUE THREAD

**Issue by gintautassulskus** [coreos/bugs#2401]
# Issue Report #

### Container Linux Version ###

1688.5.3

### Environment ###

Rackspace Public Cloud

### Expected Behavior ###

CoreOS should gracefully shut down upon receiving a signal from the hyperviosor. I am not an expert in this, thus I assume the hypervisor is the origin of the poweroff signal.

### Actual Behavior ###

The instance fails to gracefully shut down upon receiving the signal from the hyperviosr.
The log output:

```
Apr 10 18:32:26 test-instance systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Apr 10 18:32:26 test-instance systemd[1]: Started Process Core Dump (PID 1446/UID 0).
Apr 10 18:32:26 test-instance systemd-coredump[1447]: Resource limits disable core dumping for process 1445 (poweroff).
Apr 10 18:32:26 test-instance systemd-coredump[1447]: Process 1445 (poweroff) of user 0 dumped core.
```

coredumpctl info 1445:
```
PID: 1445 (poweroff) 
UID: 0 (root) 
GID: 0 (root) 
Signal: 6 (ABRT) 
Timestamp: Fri 2018-04-06 12:05:12 UTC (19s ago) 
Command Line: /sbin/poweroff 
Executable: /usr/bin/systemctl 
Control Group: / Slice: -.slice 
Boot ID: ce73beca5cc143be8bb7b77cee8840eb 
Machine ID: f2c4f6b3ef2443db91d02b4f7f44cd68 
Hostname: test-instance
Storage: none 
Message: Process 1041 (poweroff) of user 0 dumped core.
```

### Reproduction Steps ###

  1. Spin up an instance from the default CoreOS (1068.10.0) image on Rackspace 
  2. Update to the latest release to date - 1688.5.3
  3. Attempt to delete the instance via the Web Control Panel or using REST API

### Other Information ###

CoreOS 1068.10.0 and 1632.3.0 shuts down just fine.

### Environment ###

I believe Rackspace uses Xen Hypervisor for Public Cloud.

### Other Information ###

This is a cross post from [CoreOS Users mailing list](https://groups.google.com/forum/#!topic/coreos-user/tckiO7-KcfE
). 
Almost identical [post](https://groups.google.com/forum/#!topic/coreos-user/YcGkRHU9SvQ) just popped up there.

**Comment by dm0-** [comment]
Are you able to get a backtrace from that core dump?  If it looks like systemd/systemd#8075, the fix has been backported to stable and beta in coreos/systemd#100 so it will be in the next releases.

**Comment by gintautassulskus** [comment]
I was not able to get the core dump due to the resource limits. Will look into this.

However, the backtrace looks the same as in the [link](https://groups.google.com/forum/#!topic/coreos-user/YcGkRHU9SvQ) at the very bottom of my first post.

**Comment by gintautassulskus** [comment]
I got the same backtrace as in [systemd/systemd#8075](https://github.com/systemd/systemd/issues/8075).
