### ISSUE TITLE
systemd-resolved stopped listening on 127.0.0.53

### ISSUE THREAD

**Issue by michalzxc** [coreos/bugs#2406]
# Issue Report #

## Bug ##

systemd-resolved stopped listening on 127.0.0.53

itaz07controller2 ~ # systemctl status systemd-resolved
● systemd-resolved.service - Network Name Resolution
   Loaded: loaded (/usr/lib/systemd/system/systemd-resolved.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2018-04-14 16:11:21 UTC; 4h 52min ago
     Docs: man:systemd-resolved.service(8)
           https://www.freedesktop.org/wiki/Software/systemd/resolved
           https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
           https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
 Main PID: 728 (systemd-resolve)
   Status: "Processing requests..."
    Tasks: 1 (limit: 32768)
   CGroup: /system.slice/systemd-resolved.service
           └─728 /usr/lib/systemd/systemd-resolved

Apr 14 16:11:20 localhost systemd[1]: Starting Network Name Resolution...
Apr 14 16:11:21 localhost systemd-resolved[728]: Positive Trust Anchors:
Apr 14 16:11:21 localhost systemd-resolved[728]: . IN DS 19036 8 2 49aac11d7b6f6446702e54a1607371607a1a41855200fd2ce1cdde32f24e8fb5
Apr 14 16:11:21 localhost systemd-resolved[728]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Apr 14 16:11:21 localhost systemd-resolved[728]: Negative trust anchors: 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.
Apr 14 16:11:21 localhost systemd-resolved[728]: Defaulting to hostname 'linux'.
Apr 14 16:11:21 localhost systemd[1]: Started Network Name Resolution.
Apr 14 16:11:23 itaz07controller2 systemd-resolved[728]: System hostname changed to 'itaz07controller2'.

itaz07controller2 ~ # netstat -lpn|grep :53

itaz07controller2 ~ # host google.com 127.0.0.53

### Container Linux Version ###

```
$ cat /etc/os-release

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.2.1
VERSION_ID=1632.2.1
BUILD_ID=2018-02-01-2053
PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
Openstack

### Expected Behavior ###
Systemd-resolved is listening on 127.0.0.53 what was making possible to query records from /etc/hosts by "resolve" added to /etc/nsswitch.conf

### Actual Behavior ###

It is not listening on 127.0.0.53:53

### Reproduction Steps ###

Run coreos, and exec cmd:
netstat -lpn|grep 127.0.0.53:53
or ex: 
host google.com  127.0.0.53

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

**Comment by michalzxc** [comment]
I forgot to paste config - I am doing this now to show I didn't accidentally disabled it:

cat /etc/systemd/resolved.conf 
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
#DNS=
#FallbackDNS=
#Domains=
#LLMNR=yes
#MulticastDNS=yes
#DNSSEC=allow-downgrade
#Cache=yes
DNSStubListener=udp

**Comment by lucab** [comment]
Thanks for the report. It looks like your `resolved.conf` entry has no effect because it does not override the OS hardcoded configuration at `/usr/lib/systemd/resolved.conf.d/50-no-dns-listener.conf`.

You should re-order your configuration file with an higher lexicographic priority, or plainly disable the OS config:
```
sudo mkdir -p /etc/systemd/resolved.conf.d && sudo ln -s /dev/null /etc/systemd/resolved.conf.d/50-no-dns-listener.conf
```

@michalzxc where you following any guide of ours which instructed you to specifically edit `/etc/systemd/resolved.conf `? If so, we should amend our docs.

**Comment by michalzxc** [comment]
Thank you, that of course was it :)
I didn't found it in instruction, it was my attempt to fix it guessing that maybe systemd-resolved was compiled with some parameter what was changing default for it
