### ISSUE TITLE
Interactive authentication required while restarting systemd-networkd

### ISSUE THREAD

**Issue by sj2208** [coreos/bugs#2408]
Currently in my organisation we have authentication on connecting ethernet cable. Thus asking for username and password to connect and thus get IPv4.  

How can I provide credentials while starting up systemd-networkd on coreOS. 
Whenever I try to restart using the command: " systemctl restart systemd-networkd.service" 
I get the error: 
Failed to restart systemd-networkd.service: Interactive authentication required.

**Comment by lucab** [comment]
Barring any further feedback on this question, I'm inclined to close this ticket.

**Comment by ZhengxunWu** [comment]
I am also facing similar issue, any idea how to solve it
