### ISSUE TITLE
Huge performance degradation after upgrading from 1632.3.0 to 1688.5.3

### ISSUE THREAD

**Issue by eliskovets** [coreos/bugs#2409]
# Issue Report #

## Bug ##
After upgrading our ami from ami-a61464df to ami-34237c4d we started to experience huge performance degradation for our php application running on php-fpm.
### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

AWS eu-west-1

### Expected Behavior ###
No cpu spikes on every request
### Actual Behavior ###
Cpu spikes on every request
### Reproduction Steps ###

  1. Start ami-34237c4d in eu-west-1
  2. Run docker container with php-fpm and try to load it a bit
  3. Check cpu spikes on every request

**Comment by eliskovets** [comment]
Hi guys, 
The main reason why I've created this issue is that when we upgraded our instances to the latest coreOS(stable) version our cpu utilisation jumped from 10-20% to 40-60%. For sure we expected some performance degradation with Spectre2 fix, but not so huge impact which we actually got.

**Comment by euank** [comment]
Hey @eliskovets, that sounds like a quite large impact.
Unfortunately, without a bit more information it's not very actionable for us. Can you also provide:

* AWS instance type / types in use
* Some sort of fairly self-contained reproduction
* (optionally / more difficult) `perf` recordings to figure out where the extra cpu cycles go

I wouldn't expect anything near that sort of performance hit unless there's something more to it than just the spectre patches, so if you have a reasonable repro this could be well worth digging into.

**Comment by eliskovets** [comment]
Hi guys, sorry for a delay with response. We just checked a latest version of coreos stable - 1800.4.0 and it looks like the problem is fixed. Thank you for your work :)
