### ISSUE TITLE
COREOS_PUBLIC_IPV4 not loading after reboot digital ocean

### ISSUE THREAD

**Issue by exocom** [coreos/bugs#241]
The COREOS_PUBLIC_IPV4 env is not loaded after doing a 'sudo reboot'.

Oddly enough it is in the /etc/enviroment file, but it is not getting loaded. Is there any way to fix this without having to recreate the machine.

Here is what a fresh login looks like:

```
Last login: Thu Jan 15 08:02:49 2015 from 68.231.86.32
CoreOS (stable)

core@core-03 ~ $ env
MANPATH=/usr/local/share/man:/usr/share/man
TERM=xterm-256color
SHELL=/bin/bash
SSH_CLIENT=68.231.86.32 37708 22
SSH_TTY=/dev/pts/0
USER=core
PAGER=/usr/bin/less
MAIL=/var/mail/core
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
PWD=/home/core
EDITOR=/usr/bin/vim
LESSCHARSET=utf-8
SHLVL=1
HOME=/home/core
LESS=-R -M --shift 5
LOGNAME=core
SSH_CONNECTION=68.231.86.32 37708 198.199.92.84 22
LESSOPEN=|lesspipe %s
INFOPATH=/usr/share/info
CONFIG_PROTECT=/usr/share/gnupg/qualified.txt
_=/usr/bin/env


core@core-03 ~ $ cat /etc/environment 
COREOS_PUBLIC_IPV4=198.199.92.84

core@core-03 ~ $ echo $COREOS_PUBLIC_IPV4

core@core-03 ~ $ 
     
```

**Comment by crawford** [comment]
/etc/environment does not get sourced into your interactive session by default. systemd services can source the file by using EnvironmentFile= and you can pull it into your interactive shell by modifying ~/.bashrc.

**Comment by exocom** [comment]
Thanks for clarifying, it seems it is something else. Probably an issue in my unit file.

I am going to close the issue for now, but I will continue to troubleshoot to see why it stopped populating on my unit file for that single node.  I'll reopen this if I find anything.
