### ISSUE TITLE
mantle: cork enter missing mounts

### ISSUE THREAD

**Issue by glevand** [coreos/bugs#2418]
# Issue Report #

## Bug ##

I have some files I want to share between SDK instances.  I have those in a directory that I had been bind mounting into the SDK sources before entering.  That works with the legacy entry, but doesn't work with the new entry:

    mkdir sdk-extra
    sudo mount --bind ${some_path}/sdk-extra sdk-extra
    cork enter

Then inside:

    ls ~/trunk/sdk-extra/

Is this expected behavior?  If so, how can I get those files shared?

**Comment by ajeddeloh** [comment]
Looks like the old method was a recursive bind and the new one is a non-recursive bind. I've opened a PR to fix this: https://github.com/coreos/mantle/pull/850.

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/mantle/pull/850. We will release a new cork binary (v0.9.1) soon.

**Comment by glevand** [comment]
Tested repo tag `v0.9.1`, and my bind mounts seem to work OK.
