### ISSUE TITLE
resource controls?

### ISSUE THREAD

**Issue by porjo** [coreos/bugs#242]
I'd like to limit the maximum memory a particular container can consume. I've tried adding `MemoryLimit=200M` to my service file, however the process has now consumed in excess of 200M and is still happily running!?

$ systemctl cat vulcand
```ini
# /run/fleet/units/vulcand.service
[Unit]
Description=Vulcand Reverse Proxy
After=docker.service

[Service]
MemoryLimit=200M
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill vulcand
ExecStartPre=-/usr/bin/docker rm vulcand
ExecStart=/usr/bin/docker run --rm --name vulcand -p 80:8181 -p 443:8183 vulcand /opt/vulcand 
ExecStop=/usr/bin/docker stop vulcand

[X-Fleet]
Global=true
```

$ systemctl status vulcand
```
● vulcand.service - Vulcan Reverse Proxy
   Loaded: loaded (/run/fleet/units/vulcand.service; linked-runtime)
   Active: active (running) since Thu 2015-01-15 21:41:59 UTC; 8h ago
  Process: 6719 ExecStartPre=/usr/bin/docker rm vulcand (code=exited, status=1/FAILURE)
  Process: 6711 ExecStartPre=/usr/bin/docker kill vulcand (code=exited, status=1/FAILURE)
 Main PID: 6728 (docker)
   CGroup: /system.slice/vulcand.service
           └─6728 /usr/bin/docker run --rm --name vulcand -p 80:8181 -p 443:8183 vulcand /opt/vulcand 
```
Output from top:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                    
 6754 99        20   0  243776 236840   7236 S   0.0 23.2   1:13.58 vulcand          
```
Is limiting of memory (and other resources) possible with CoreOS, and if so, how should that be configured?

**Comment by robszumski** [comment]
Docker doesn’t pay attention to certain systemd parameters since the daemon creates its own cgroups/namespaces. You'll have to use the Docker-specific resource flags on your run command.

This is one thing that we hope to fix with Rocket. Any resource settings and environment variables set in the unit will take affect as you would expect.

**Comment by porjo** [comment]
ok, thankyou
