### ISSUE TITLE
Ignition writes an extra temp file when appending

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2420]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1758.0.0
VERSION_ID=1758.0.0
BUILD_ID=2018-04-24-0443
PRETTY_NAME="Container Linux by CoreOS 1758.0.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

At least AWS

### Expected Behavior ###

No extra temp file written.

### Actual Behavior ###

When appending to a file, Ignition leaves an extra tmpNNNNN file in the same directory as the target.

### Reproduction Steps ###

  1.
```sh
cat > userdata <<EOF
storage:
  filesystems:
    - name: oem
      mount:
        device: /dev/disk/by-label/OEM
        format: ext4
        label: OEM
  files:
    - filesystem: oem
      path: /grub.cfg
      mode: 0644
      append: true
      contents:
        inline: |
          set linux_append="ipv6.disable=1"
EOF
```
  2. `kola spawn -p aws -u userdata`
  3. `ls /usr/share/oem`

**Comment by dgonyeo** [comment]
Found the error:
https://github.com/coreos/ignition/blob/9796484de2dd06b39691c4021b6bbd8f51431d42/internal/exec/util/file.go#L180

This specific block was written before appending was implemented, so the only case where the temp file was removed was when an error value was being returned. This should be `if err != nil || f.Append`. I'll make a PR to fix this.
