### ISSUE TITLE
Add sssd support for sudo

### ISSUE THREAD

**Issue by SergeiDiachenko** [coreos/bugs#2423]
# Issue Report #

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
Amazon EC2

### Desired Feature ###
I joined CoreOS in FreeIPA domain. SSSD on CoreOS configured to get users and sudo rules from FreeIPA. FreeIPA users can authenticate on CoreOS, but FreeIPA sudo rules don't apply. 
I believe the reason is that sudo is built without "--with-sssd" flag. As I see in log files, sssd fetches sudo rules from FreeIPA, but sudo doesn't ask sssd.

### Other Information ###

https://groups.google.com/forum/#!topic/coreos-dev/JbefCb309LI
https://github.com/coreos/bugs/issues/1856

**Comment by ajeddeloh** [comment]
It looks like this is already done and will  be in the next alpha. See https://github.com/coreos/coreos-overlay/pull/3210. Please reopen if 1772.0.0 doesn't fix this for you.
