### ISSUE TITLE
flannel not able to communicate etcd cluster

### ISSUE THREAD

**Issue by Dileep2016** [coreos/bugs#2424]
# Issue Report #

hi i am trying to setup flannel in kubernetes nodes master is working working fine..
master i did the set up fine..
etcdctl \
    --cert-file /etc/etcd/kubernetes.pem \
    --key-file=/etc/etcd/kubernetes-key.pem \
    --ca-file /etc/etcd/ca.pem \
    --endpoints "https://172.17.37.22:2379,https://172.17.37.6:2379" \
    set \
    -- coreos.com/network/config '{"Network":"10.20.0.0/16", "SubnetLen": 24,"Backend":{"Type":"vxlan"}}'

it working fine on master but worker node throwing error. not able to start

etcd.service file
-------------------------------------------------------------

[Unit]
Description=flannel is an etcd backed overlay network for containers
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
EnvironmentFile=-/etc/default/flanneld
ExecStart=/usr/bin/flanneld --etcd-endpoints=${FLANNELD_ETCD_ENDPOINTS} --etcd-prefix=${FLANNELD_ETCD_PREFIX} $FLANNEL_OPTIONS
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service

----------------------------------------------------------------------
/etc/default/flanneld
-----------------------------------------------------------------------
FLANNELD_ETCD_ENDPOINTS=" https://172.17.37.22:2379,https://172.17.37.6:2379"
FLANNELD_ETCD_PREFIX="coreos.com/network/"
FLANNELD_ETCD_CERTFILE="/etc/etcd/kubernetes.pem"
FLANNELD_ETCD_KEYFILE="/etc/etcd/kubernetes-key.pem"
FLANNELD_ETCD_CAFILE="/etc/etcd/ca.pem"
FLANNEL_OPTIONS="-ip-masq"
------------------------------------------------------

Node also i have put the same configuration but not bale to start the flannel service...
------------------------------------------------------------------------------------
Error is :---
-----------------------------------------------------------------
● flanneld.service - flannel is an etcd backed overlay network for containers
   Loaded: loaded (/etc/systemd/system/flanneld.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Mon 2018-05-07 14:01:14 UTC; 21s ago
 Main PID: 26207 (code=exited, status=1/FAILURE)

May 07 14:01:13 ip-172-17-37-60 systemd[1]: Failed to start flannel is an etcd backed overlay network for containers.
May 07 14:01:13 ip-172-17-37-60 systemd[1]: flanneld.service: Unit entered failed state.
May 07 14:01:13 ip-172-17-37-60 systemd[1]: flanneld.service: Failed with result 'exit-code'.
May 07 14:01:14 ip-172-17-37-60 systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
May 07 14:01:14 ip-172-17-37-60 systemd[1]: Stopped flannel is an etcd backed overlay network for containers.
May 07 14:01:14 ip-172-17-37-60 systemd[1]: flanneld.service: Start request repeated too quickly.
May 07 14:01:14 ip-172-17-37-60 systemd[1]: Failed to start flannel is an etcd backed overlay network for containers.

### Container Linux Version ###
ubuntu 
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)

**Comment by lucab** [comment]
It looks like you are having problem with running flannel as a systemd service on ubuntu. As such, the proper tracker to report this is https://github.com/coreos/flannel (or ubuntu tracker, if this is coming from a package).

**Comment by euank** [comment]
Closing per @lucab's comment; the flannel maintainers are unlikely to see issues posted to this repository.

Note that the error `flanneld.service: Start request repeated too quickly` is systemd refusing to try and run it due to its current retry/backoff settings.
Running `systemctl reset-failed` will make it forget about failures and allow it to retry, and `StartLimitIntervalSec=0` may avoid it getting into that state in the first place.

If that's the root problem, not just something masking a real problem, the source of the systemd service file is probably the best project to contact.
