### ISSUE TITLE
config-transpiler: config options that are zero value for their type are discarded

### ISSUE THREAD

**Issue by vboginskey** [coreos/bugs#2428]
# Issue Report #

### Container Linux Version ###

```
ct v0.8.0-2-gac4a2c7
```

### Expected Behavior ###

Given:

```
❯ cat etcd.yml
etcd:
  enable_v2: false
  version: 3.3.1
```

the command `ct -strict -in-file etcd.yml -out-file etcd.json` should generate:

```
❯ jq . < etcd.json
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.2.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {
    "units": [
      {
        "dropins": [
          {
            "contents": "[Service]\nEnvironment=\"ETCD_IMAGE_TAG=v3.3.1\"\nExecStart=\nExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS \\\n  --enable-v2=false",
            "name": "20-clct-etcd-member.conf"
          }
        ],
        "enable": true,
        "name": "etcd-member.service"
      }
    ]
  }
}

```

### Actual Behavior ###

The generated drop-in is missing the `--enable-v2=false` argument:

```
❯ jq . < etcd.json
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.2.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {
    "units": [
      {
        "dropins": [
          {
            "contents": "[Service]\nEnvironment=\"ETCD_IMAGE_TAG=v3.3.1\"\nExecStart=\nExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS",
            "name": "20-clct-etcd-member.conf"
          }
        ],
        "enable": true,
        "name": "etcd-member.service"
      }
    ]
  }
}
```

### Reproduction Steps ###

Detailed above.

### Other Information ###

[Here](https://github.com/coreos/container-linux-config-transpiler/blob/f8bebed489bda139f8cb09c6de285f610c92b156/config/types/common.go#L111) is the offending function. This will discard any `bool` values set to false.

Considering that `--enable-v2` defaults to `true`, it is not possible to configure it as `false` with the `etcd` section of a Container Linux config with the current version of config-transpiler.

**Comment by ajeddeloh** [comment]
Thanks for the report! It looks like we forgot to make the options pointer types since go assumes unspecified is the same as the zero value. Really we should go through and audit all of the options.
