### ISSUE TITLE
Drop old SDK enter methods

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2432]
# Issue Report #

### Environment ###

All

### Desired Feature ###

- [ ] Drop `cork enter --legacy`
- [ ] Drop `cros_sdk`

### Other Information ###

[Deprecation notice](https://groups.google.com/d/topic/coreos-dev/JV3s-j51Tcw/discussion).

**Comment by ajeddeloh** [comment]
https://github.com/coreos/mantle/pull/865
https://github.com/coreos/scripts/pull/820
https://github.com/coreos/manifest/pull/153
Drop the old enter method and chromite entirely

**Comment by ajeddeloh** [comment]
Closed with those PRs merging
