### ISSUE TITLE
journald logs seemingly ceased after reboot for update; clock has gone backwards by a week

### ISSUE THREAD

**Issue by pwaller** [coreos/bugs#2438]
# Issue Report #

## Misbehaving instances on AWS ##

* Missing logs
* Clock going backwards (first by a day, then by a week!)

Hi,

I do not currently believe this to be a Container Linux bug, but hopefully this saves others the trouble, since it seemed at first connected to Container Linux.

Apologies for deviating from the usual format. I'm putting this here in case anyone else finds the same issue. I couldn't easily find anything on the internet about this.

* On m5.large instances on AWS, 5 separate machines had software failures within 24h, all after rebooting for a Container Linux update (`1688.5.3` to `1745.3.1`).
* An m4.large instance running a similar software configuration was unaffected.
* The `journalctl` logs were seemingly empty since the reboot after a Container Linux update, making it hard to determine what the issue was.
* The dmesg log contained the following (`journal corrupted or uncleanly shut down`):

    ```
    [    6.906804] systemd-journald[524]: File /var/log/journal/ec27ee7551664207b78bff78ecbfc65d/system.journal corrupted or uncleanly shut down, renaming and replacing.
    ...
    [   28.041367] systemd-journald[524]: File /var/log/journal/ec27ee7551664207b78bff78ecbfc65d/user-1000.journal corrupted or uncleanly shut down, renaming and replacing.
    ```

* It transpires that the clock on these instances is behaving very strangely:
    
    ```
    pwaller@ip-10-1-166-75 ~ $ sudo journalctl --lines=1
    -- Logs begin at Thu 2018-05-17 12:51:43 UTC, end at Thu 2018-05-24 06:04:39 UTC. --
    May 24 06:04:39 ip-10-1-166-75.eu-west-1.compute.internal systemd-journald[626]: Journal stopped
    
    pwaller@ip-10-1-166-75 ~ $ dmesg | head -n1
    [    0.000000] Linux version 4.14.42-coreos (jenkins@localhost) (gcc version 7.3.0 (Gentoo Hardened 7.3.0 p1.0)) #1 SMP Wed May 23 08:32:56 UTC 2018
    
    pwaller@ip-10-1-166-75 ~ $ date
    Thu May 17 16:42:39 UTC 2018
    
    pwaller@ip-10-1-166-75 ~ $ uptime
     16:42:43 up 14 min,  1 user,  load average: 0.00, 0.02, 0.00
    ```
    
    Interpreting: Pre-reboot the time was 6am on May 24th. The machine has been up for 14 minutes. The first time the machine saw on boot was May 23rd at 8am, i.e, the time went backwards by 22-ish hours. And measuring the time now, I see it's a week further back.

    The fact the clock has gone backwards between the last journal message and the first kernel boot message suggests that something is wrong with the hypervisor, perhaps?
    
* In fact, it turns out that logs are being written, they're just being written with a timestamp prior those before the reboot, making them harder to spot; if you just look at the end of the logs you don't see the most recent messages, because those are being written with an older timetsamp:

    ```
    pwaller@ip-10-1-166-75 /var/log/journal/ec2e9f237a066d886f7847e6c53cf170 $ ls -ltr
    total 73764
    -rw-r-----. 1 root systemd-journal  8388608 May 17 16:28 user-1002.journal
    -rw-r-----. 1 root systemd-journal  8388608 May 17 16:28 user-1000.journal
    -rw-r-----. 1 root systemd-journal  8388608 May 17 16:29 user-1001.journal
    -rw-r-----. 1 root systemd-journal  8388608 May 17 16:30 system.journal
    -rw-r-----. 1 root systemd-journal 16777216 May 24  2018 user-1000@00056c664dc77b1d-ad52a7b8da021d80.journal~
    -rw-r-----. 1 root systemd-journal 25165824 May 24  2018 system@00056c664c6a5fe3-ee29fb2af7861fbc.journal~
    ```

---

I have raised a ticket with AWS support. Perhaps this is only one physical host which is affected, I'm not in a position to tell. Maybe it's a wider issue and someone from CoreOS can shed some light.

I'll report back when we have a resolution.

**Comment by lucab** [comment]
Thanks for the report, it sounds indeed strange. It sounds like the hypervisor RTC is jumping around, but I don't know if something on the OS side is triggering it.
I'd suggest to check:
 * any RTC or time related entries in `dmesg`
 * logs from `journalctl -u systemd-timesyncd.service`
 * whether restarting that service triggers and re-sync the current time

**Comment by pwaller** [comment]
Unfortunately timesyncd is failing, as reported in https://github.com/coreos/bugs/issues/417.

```
May 24 11:02:44 ip-10-1-149-249.eu-west-1.compute.internal systemd-timesyncd[702]: Timed out waiting for reply from 89.234.64.77:123 (0.coreos.pool.ntp.org).
```

However, if I run ntpdate, it works, but it is taking in excess of 6 seconds to get a response:

```
pwaller@ip-10-1-149-249 ~ $ time sudo ntpdate 0.coreos.pool.ntp.org
24 May 12:11:38 ntpdate[1386]: adjust time server 85.91.1.164 offset 0.000075 sec
real	0m6.459s
user	0m0.004s
sys	0m0.003s
```

The machines in question have been rotated out and I've run out of time budget for this at this moment in time. I'll report back with what Amazon says, but the preliminary response from them suggests that there may not be enough information to assign blame. If this crops up again in the same manner I'll definitely report back, if not, I don't mind if the issues is closed with 'needs more information'.

**Comment by lucab** [comment]
AWS is now offering an [internal NTP service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html) over `169.254.169.123`, did you check if that performs a bit better and at least solves the timesyncd timeout?

**Comment by pwaller** [comment]
Great observation, that also takes 6 seconds:

```
pwaller@ip-10-1-41-14 ~ $ time sudo ntpdate 169.254.169.123
24 May 14:00:27 ntpdate[3498]: adjust time server 169.254.169.123 offset -0.082211 sec

real	0m6.108s
user	0m0.003s
sys	0m0.004s
```

**Comment by pwaller** [comment]
Things seem stable for now. Amazon needs more information than I could provide (because of instance rotation) to continue investigating, and it hasn't recurred in the meantime. I'll report back if it happens again.

**Comment by pwaller** [comment]
(not reopening, but will do so if anything actionable within CoreOS arises)

/cc @lucab 

After a few weeks, the problem has reoccurred with two machines on AWS, again causing an outage in our staging environment. At 14th June 0830 UTC, the clock on one machine is 3rd June 0443 and another is 3rd June 1612.

Here are all the messages relating to RTC:

```
[    1.988916] rtc_cmos 00:00: RTC can wake from S4
[    1.990030] rtc_cmos 00:00: rtc core: registered rtc_cmos as rtc0
[    1.991044] rtc_cmos 00:00: alarms up to one day, 114 bytes nvram
[    2.030734] rtc_cmos 00:00: setting system clock to 2018-06-01 11:09:59 UTC (1527851399)
```

The timesyncd logs on both machines are full of timeout messages (see also #417).

```
machine 1$ sudo journalctl -u systemd-timesyncd.service | grep 'Timed out' | wc -l
6181

machine2 $ sudo journalctl -u systemd-timesyncd.service | grep 'Timed out' | wc -l
7054
```

Restarting systemd-timesyncd does not fix the time.

```
$ sudo systemctl status systemd-timesyncd
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; disabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-06-03 04:45:31 UTC; 26s ago
     Docs: man:systemd-timesyncd.service(8)
 Main PID: 21518 (systemd-timesyn)
   Status: "Connecting to time server 34.242.217.31:123 (1.coreos.pool.ntp.org)."
    Tasks: 2 (limit: 32767)
   Memory: 956.0K
   CGroup: /system.slice/systemd-timesyncd.service
           └─21518 /usr/lib/systemd/systemd-timesyncd

Jun 03 04:45:31 ip-10-1-149-249.eu-west-1.compute.internal systemd[1]: Starting Network Time Synchronization...
Jun 03 04:45:31 ip-10-1-149-249.eu-west-1.compute.internal systemd[1]: Started Network Time Synchronization.
Jun 03 04:45:41 ip-10-1-149-249.eu-west-1.compute.internal systemd-timesyncd[21518]: Timed out waiting for reply from 52.17.231.73:123 (0.coreos.pool.ntp.org).
Jun 03 04:45:51 ip-10-1-149-249.eu-west-1.compute.internal systemd-timesyncd[21518]: Timed out waiting for reply from 40.112.75.180:123 (0.coreos.pool.ntp.org).

$ timedatectl
                      Local time: Sun 2018-06-03 04:47:20 UTC
                  Universal time: Sun 2018-06-03 04:47:20 UTC
                        RTC time: Sun 2018-06-03 04:47:20
                       Time zone: UTC (UTC, +0000)
       System clock synchronized: no
systemd-timesyncd.service active: no
                 RTC in local TZ: no
```

**Comment by pwaller** [comment]
After a bit of back and forth, I have just received a positive response from AWS:

> [The internal team] dug deep and informed me that they have identified and root-caused the issue to a software bug, which affected a small portion of our fleet. 
> 
> Further they also informed that they are in the process of deploying the fix for the same and will complete the deployment the next couple of weeks.
