### ISSUE TITLE
1786.0.1 - Docker 18.05.0-ce has a bind mount bug that prevents containers with volumes from starting

### ISSUE THREAD

**Issue by JTarasovic** [coreos/bugs#2440]
# Issue Report #

## Bug ##
Docker 18.05.0-ce has a bind mount bug that prevents containers from starting.
Issue: moby/moby#37032
Fix: moby/moby#37031

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1786.0.1
VERSION_ID=1786.0.1
BUILD_ID=2018-05-23-1022
PRETTY_NAME="Container Linux by CoreOS 1786.0.1 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
AWS

### Expected Behavior ###
kubernetes / kubelet managed containers w/ bind mounted volumes start

### Actual Behavior ###
`"Error": "linux mounts: Could not find source mount of /etc/coreos"`

### Reproduction Steps ###
`docker run -it --rm --mount type=bind,source=/etc/coreos,target=/etc/coreos,bind-propagation=rslave busybox /bin/sh`

### Other Information ###

partial output of `docker inspect` for failing container-linux-update-agent container

```
         "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 128,
            "Error": "linux mounts: Could not find source mount of /etc/coreos",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
```

```
            {
                "Type": "bind",
                "Source": "/etc/coreos",
                "Destination": "/etc/coreos",
                "Mode": "rslave",
                "RW": true,
                "Propagation": "rslave"
            },
```

**Comment by ajeddeloh** [comment]
I can repro this (thanks for the easy repro). Tested the fixed and confirmed it worked. Working on backporting this now.

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/coreos-overlay/pull/3248 which should be in Alpha 1786.1.0, which should be released soon

**Comment by JTarasovic** [comment]
Thank you, all! That was hella quick.
