### ISSUE TITLE
kola userdata option does not work

### ISSUE THREAD

**Issue by Bubblemelon** [coreos/bugs#2453]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1786.2.0
VERSION_ID=1786.2.0
BUILD_ID=2018-05-31-0804
PRETTY_NAME="Container Linux by CoreOS 1786.2.0 (Rhyolite)"
...
COREOS_BOARD="amd64-usr"
```

### Environment ###

Packet.net 

### Expected Behavior ###

Ignition should receive the config file through the `-u` option when running `kola spawn`.

### Actual Behavior ###

Ignition did not receive the config file.  

### Reproduction Steps ###

  1. Within the SDK chroot, run `kola spawn --packet-config-file packet.json -u example.ign`
  2. a) When inside the instance, the response output from `curl https://metadata.packet.net/userdata -v` is empty. 
Additionally, when running `curl -X GET --header 'Accept: application/json' --header 'X-Auth-Token: s2LCc...' 'https://api.packet.net/devices/{Device UUID}'
` outside the instance:
```
...
		"class": "t1.small.x86",
		"pricing": {
			"hour": 0.07
		}
	},
	"userdata": "",
	"switch_uuid": "3bce1f4b",
	"network_ports": [
		{

...
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;returns userdata as empty. 

  2. b) In the **Servers** view on [app.packet.net](https://app.packet.net/), click on the instance; this opens the **Overview** page. Under the **Instance Details** section, click on **Edit Hostname, Description, Userdata PXE**. The side popout will show that Userdata is empty. 

### Other Information ###

The example ignition config, `example.ign`, that I've used is from the [Example Configs](https://coreos.com/ignition/docs/latest/examples.html) page under _Start Services_. 

> The content of the ignition file may be is irrelevant, I believe that `kola` is not passing the config to ignition. I've used more than one validated ignition config to reproduce this bug.

[Packet API for Device Information](https://www.packet.net/developers/api/devices/)

Do not use [api.packet.net/userdata](https://www.packet.net/developers/api/userdata/). The people at Packet noted that this is for their internal consumption only and will be removed from the APIs page. 
Use step 2.a) instead.

The contents of `packet.json` follows the format as specified on the Mantle [README.md](https://github.com/coreos/mantle#packet)

**Comment by arithx** [comment]
I'm not able to replicate this. 

```
[stephenlowrie@localhost mantle]$ cat cnf.ign 
{
    "ignition": {"version": "2.2.0"},
    "storage": {
        "files": [{
            "filesystem": "root",
            "path": "/etc/motd",
            "mode": 420,
            "contents": { "source": "data:,test" }
        }]
    }
}
[stephenlowrie@localhost mantle]$ bin/kola -p packet -u cnf.ign spawn
test
[bound] core@kola-f905384a-64f0b3c278 ~ $ cat /etc/motd
test
```

`kola` doesn't use the metadata URL for passing userdata on Packet, [a file is uploaded to google storage containing the userdata](https://github.com/coreos/mantle/blob/master/platform/api/packet/api.go#L194) which is [referenced in the iPXEScript (also uploaded to google storage)](https://github.com/coreos/mantle/blob/master/platform/api/packet/api.go#L459-L465). Ultimately the userdata is passed to the instance via the `coreos.config.url` parameter on the kernel command-line.

**Comment by ajeddeloh** [comment]
I was looking at this last night with @Bubblemelon. We weren't seeing Ignition logs in general, which seemed wrong.

**Comment by arithx** [comment]
@ajeddeloh: do you want to take over investigation into this?

**Comment by arithx** [comment]
Also we should probably move this over to the mantle issue tracker.

**Comment by Bubblemelon** [comment]
Talked this over with Andrew, and it's good to close.

The link [to the comment on Packet's metadata api was](https://github.com/coreos/mantle/blob/841beeca0aa645e1940729e7bb2f00ee3f2db648/platform/api/packet/api.go#L194) was helpful. **Perhaps putting this the docs related to SDK dev somewhere would be great**. 

In Andrew's earlier comment about not seeing the ignition logs, it was simply because we ran `journalctl -t ignition` without the `--no-pager` option and also because the ignition config was not pretty printed as it would if an ignition config was given over a qemu vm... 

I guess I shouldn't have assumed that deploying an instance through kola would look the same on the Overview page as it would when deploying one through the Packet.net dashboard.

**Comment by Bubblemelon** [comment]
@arithx maybe adding that snippet in [your PR](https://github.com/coreos/mantle/pull/861) would be helpful if not already included.

**Comment by arithx** [comment]
Adding additional documentation about the individual implementations of the different platforms does make sense. I'll see if I can block off some time and write that up and get it added into that PR or a followup.
