### ISSUE TITLE
base64 encoded file content should be decoded by ignition

### ISSUE THREAD

**Issue by figo** [coreos/bugs#2458]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

```

### Environment ###

running on vSphere 6.5

### Expected Behavior ###
passing a ignition config to VM:
```
"source": "data:,U0NIRURVTEVSX09QVFM9Ii0tbGVhZGVyLWVsZWN0PXRydWUgXAotLWt1YmVjb25maWc9L3Zhci9saWIva3ViZS1zY2hlZHVsZXIva3ViZWNvbmZpZyBcCi0tdj0yIgo%3D%0A"
``` 
expecting it can be decoded by ignition

### Actual Behavior ###
it is not, it stay encoded in file.
```
U0NIRURVTEVSX09QVFM9Ii0tbGVhZGVyLWVsZWN0PXRydWUgXAotLWt1YmVjb25maWc9L3Zhci9saWIva3ViZS1zY2hlZHVsZXIva3ViZWNvbmZpZyBcCi0tdj0yIgo
```
### Reproduction Steps ###
we use terraform to drive this, please refer to this repo:
https://github.com/figo/cross-cloud/blob/binary-content/master_templates-v1.10.0/master.yml#L238
 
### Other Information ###
this issue initially been discussed here:
https://github.com/coreos/container-linux-config-transpiler/pull/158#discussion_r193551460

@crawford

**Comment by crawford** [comment]
Can you post more of the Ignition config? Based on what I see, Ignition is behaving as expected. It's decoding the URL-encoded data and writing it to disk. That's exactly what the config has requested.

**Comment by figo** [comment]
maybe both andrew and i misunderstood originally, what we thought is ignition going to eventually decoded it to
```
$ echo U0NIRURVTEVSX09QVFM9Ii0tbGVhZGVyLWVsZWN0PXRydWUgXAotLWt1YmVjb25maWc9L3Zhci9saWIva3ViZS1zY2hlZHVsZXIva3ViZWNvbmZpZyBcCi0tdj0yIgo%3D%0A | urldecode | base64 -D
SCHEDULER_OPTS="--leader-elect=true \
--kubeconfig=/var/lib/kube-scheduler/kubeconfig \
--v=2"
```
when write to file inside VM, now we are in situation that the file has the encoded content.
and how to make ignition decoding happen, thanks

**Comment by crawford** [comment]
Ignition doesn't handle base64 encoding/decoding so there is no way to tell Ignition to decode this. You need to tell CT to decode this instead (using the `!binary` tag).

**Comment by figo** [comment]
thanks again, i already using `inline: !binary |` with CT, and CT translate this:
```
storage:
  files:
    - path: /etc/config
      filesystem: root
      mode: 0644
      contents:
         inline: !binary |
           U0NIRURVTEVSX09QVFM9Ii0tbGVhZGVyLWVsZWN0PXRydWUgXAotLWt1YmVjb25maWc9L3Zhci9saWIva3ViZS1zY2hlZHVsZXIva3ViZWNvbmZpZyBcCi0tdj0yIgo=
```
to
```
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.2.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/config",
        "contents": {
          "source": "data:,U0NIRURVTEVSX09QVFM9Ii0tbGVhZGVyLWVsZWN0PXRydWUgXAotLWt1YmVjb25maWc9L3Zhci9saWIva3ViZS1zY2hlZHVsZXIva3ViZWNvbmZpZyBcCi0tdj0yIgo%3D%0A",
          "verification": {}
        },
        "mode": 420
      }
    ]
  },
  "systemd": {}
}
```

**Comment by crawford** [comment]
Use `!!binary` instead of `!binary`.

**Comment by figo** [comment]
it works, thanks a lot for helping, i will close it now
