### ISSUE TITLE
CLCs are unversioned

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/bugs#2461]
# Issue Report #

Container Linux Configs (CLCs) are not currently versioned. This means there is no clear contract about how deprecations or behavior changes are expected to work. CLCs should be versioned.

Versioning proposal:

- Use semver
- Support translating old config versions to the latest config version (in the same way Ignition handles this). This means a version 1.0.0 CLC will always be usable and be supported indefinitely.
- If we do ever need to drop support for a config version, it should have a clear deprecation window with plenty of notice. This is not expected to happen.
- Release new spec major versions instead of deprecating old fields. This means to update a 1.x.y config to a 2.0.0 config changes to the config other than just the version will be necessary.

**Comment by bgilbert** [comment]
We'll also need to handle existing, unversioned CLCs.  We probably don't want to support them indefinitely, since it'd be easy to to accidentally omit the version declaration and thus select the wrong CLC version.  **Proposal:** retroactively assign version 1.0.0 to the current CLC spec, then accept unversioned CLCs until a well-defined end date (e.g. a year) with a warning advising users to add a version declaration by then.   Afterward, drop support for unversioned CLCs.

**Comment by lucab** [comment]
Related question: do we plan to let `ct` ingest multiple types of configurations for different OSes, or do we plan to have dedicated per-OS tools?

If the former, it may make sense to not use semver and instead adopt a top-level type+version kind (pretty much the same as [this](https://github.com/coreos/container-linux-config-transpiler/pull/158#issuecomment-396527593)), and internally translate to the latest per-OS config and then to ignition.

**Comment by ajeddeloh** [comment]
We haven't decided that yet. I agree adding some kind of type+version kind is probably a good idea. Otherwise people will think configs for different distros are interchangable. We could even swing something where different top level sections (e.g. flannel, etcd, etc) are supported on some distros but not others.

**Comment by lucab** [comment]
[Fleshing some more details from my cryptic comment above]

Ignition [config spec](https://github.com/coreos/ignition/blob/master/doc/configuration-v2_2.md) prescribes a mandatory SemVer-compatible field called `ignition.version` with the following guarantees:
> the semantic version number of the spec. The spec version must be compatible with the latest version (2.2.0). Compatibility requires the major versions to match and the spec version be less than or equal to the latest version. -experimental versions compare less than the final version with the same number, and previous experimental versions are not accepted.

I'm a fan of semver for libraries/APIs, but for this kind of configuration I'd prefer instead an approach with an explicit tag that simply describes what's the format of the configuration object. For an example, [torcx config schemas](https://github.com/coreos/torcx/tree/master/Documentation/schemas) work that way.
The idea is that the internal representation is anyway different from the input, and the parser only needs a simple way to detect the input type.

Changes (breaking or not) are handled by incremental revision numbers and older revisions are accepted for compatibility (until some planned purge-point, if desired). This means there are no special micro-compatible versions and deprecated/moved/renamed fields can be directly changed on the next revision bump. Users can keep their old configs working at old revisions, or jump into new revisions with new features and deprecations.

In practice, for `ct` this would look like:
 * day-0: `kind: cl-config-v0`
 * day-1: `kind: cl-config-v1-exp`
 * day-10: `kind: cl-config-v1`
 * day-20: `kind: fcos-config-v0-exp`
 * ...

**Comment by ajeddeloh** [comment]
Is your "day-20" kind supposed to be `fcos-config-v2-exp`? If not, I don't follow.

Assuming it is: How do you think that should be implemented? I'd prefer to not have to do a massive translation dance like we do with Ignition if we can avoid it.

**Comment by crawford** [comment]
Why bother fixing this when we know that Container Linux has a limited lifetime? Can we just leave it as is and fix the issue in the successor to Container Linux?

**Comment by crawford** [comment]
> Because the CL lifetime is long enough to warrant it and we may want to make changes.

I'm not convinced that the lifetime is long enough. We can also just agree not to make breaking changes to the config going forward. This is the approach we've taken up to this point and it has worked fine.

This seems like a tremendous amount of effort for very little gain.

**Comment by lucab** [comment]
Clarified out-of-band: `fcos-` and `cl-` are separate genealogy which can live and progress in parallel. 

Yes, it would probably entail an external->internal translation dance (on top of the later ignition transpilation), but I don't know how much work this requires on ct internal. I did a similar refactoring on torcx (splitting external input and internal state) and it wasn't a lot of work, but I understand ct is much heavier on config parsing/processing logic.

This came up as a result of the first breaking change proposed in https://github.com/coreos/container-linux-config-transpiler/pull/158#discussion_r193535656. In the best case, this rework can be directly used to support FCOS and CL the same way. In the worst case, this only allows us to snapshot/freeze the current config format.

**Comment by ajeddeloh** [comment]
Currently ct internal translation would be even more painful than Ignition's. We actually parse two trees, one that gets parsed into go structs and another with generic go maps/slices/interface{}s that also contains information about where various structs come from in the source yaml. We transform that tree along with the go structs so we can hand it to Ignition's validation code. We rely heavily on using the vendored Ignition's validation code instead of duplicating valdiation logic in the ct structs.

I'm not married to that approach. It was good at the time for avoiding duplicating a bunch of valdiation code, but it makes the translation trickier and if we are going to do a bunch more translation it's worth revisiting.

**Comment by bgilbert** [comment]
@crawford The Ignition 3.0 spec will have breaking changes and will hopefully occur before CL EOL.  At that point we'll need to either make breaking changes to the CLC spec, implement compatibility glue in CT itself, or ignore 3.0 for CL.  The latter doesn't seem great for encouraging wide adoption.

In addition, we'll want versioning in the FCOSC spec from day 1 to avoid repeating our earlier mistakes, and we'll certainly want a way to distinguish CLCs from FCOSCs.  So we might as well implement versioning just before we start working on FCOS support, rather than just after.

**Comment by dustymabe** [comment]
> @crawford 
> Why bother fixing this when we know that Container Linux has a limited lifetime?

It's my understanding that versioning CLCs would help us in Fedora CoreOS as well. Is that wrong?

> @bgilbert 
> In addition, we'll want versioning in the FCOSC spec from day 1

Agree. The open question is does fixing this issue help us get there? My understanding was it did.

**Comment by crawford** [comment]
> It's my understanding that versioning CLCs would help us in Fedora CoreOS as well. Is that wrong?

Nope. I think they should be versioned out of the gate. I'm just not convinced we need to do all of that work on something that we are ultimately going to leave behind (the container-linux-config-transpiler is, by definition, very specific to container linux).

**Comment by dustymabe** [comment]
> (the container-linux-config-transpiler is, by definition, very specific to container linux).

indeed. I think the thought was (and I don't know anything about the code base so it's mostly from context) that we would fork container-linux-config-transpiler for FCOS, so we would be re-using most of the code, thus this work would still have value. I'll let @bgilbert and @ajeddeloh speak authoritatively on the subject, though.

**Comment by ajeddeloh** [comment]
The plan was to:
 - Version CLCs ASAP for reasons described above
 - Fork ct as a stopgap when we need it for FCOS. Maybe later rewrite it if we want, but users should have something to start with so they don't start writing Ignition configs by hand.

**Comment by ajeddeloh** [comment]
Finally getting around to this, now that some dust has settled. Current plan: Version ct with v0 which will be the same as the current config. Golang's default 0 values mean an unspecified config will be the same as specifying v0. We will reject all other values. Since Ignition spec 3.0.0 will not be supported by CL (and by extension CLCs)  we don't anticipate any breaking changes.

In the event we do need to make a breaking change we will split ct (either via separate binaries or seperate packages for each config version) and do no translation. In that case specifying v1 will select the new config and specifying no version for explicitly v0 will select the old config.

I'm deferring discussion about an fcos ct equivalent for a fcos-tracker issue not yet created.

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/container-linux-config-transpiler/pull/161
