### ISSUE TITLE
Issues with metadata on Openstack

### ISSUE THREAD

**Issue by Unb9rn** [coreos/bugs#2467]
# Issue Report #
Metadata is not created after boot because coreos-metadata.service on OpenStack doesn't load on boot. Maybe because it is required by metadata.target.

`systemctl list-units --type target` does not list metadata.target

Also it looks like there is some problems with provider string from cmdline.
I had to write a dropin with COREOS_METADATA_OPT_PROVIDER=--provider=openstack-metadata or else the service would fail because it could not resolve "openstack" provider instead of "openstack-metadata" Are there any better solutions than adding dropins to coreos-metadata and coreos-metadata-sshkeys@ services?

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.7.0
VERSION_ID=1745.7.0
BUILD_ID=2018-06-14-0909
PRETTY_NAME="Container Linux by CoreOS 1745.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
I am running CoreOS on Openstack.
### Expected Behavior ###
Creating /run/metadata/coreos and populating authorized keys for core user from openstack-metadata.
### Actual Behavior ###
Metadata service is dead and metadata-sshkeys server requires a dropin with openstack-metadata provider name.
### Reproduction Steps ###
Self-explaining. Just run coreos without pre-configuring dropins.

**Comment by lucab** [comment]
`coreos-metadata.service` is typically not enabled by default, units that need cloud metadata can depend on it.

Openstack has multiple and optional ways of providing metadata, right now only the remote metadata endpoint (`openstack-metadata`) is supported by coreos-metadata service. All available platforms are listed in the documentation: https://github.com/coreos/coreos-metadata

In case you are not aware of it, `ct` supports automatic setup and configuration if your node configuration references dynamic cloud metadata: https://github.com/coreos/container-linux-config-transpiler/blob/v0.9.0/doc/dynamic-data.md

**Comment by lucab** [comment]
@Unb9rn in case you were following any of CoreOS official docs and the facts above were not immediately clear, we'll gladly [accept a PR](https://github.com/coreos/docs) to make it more useful for other readers too.
