### ISSUE TITLE
resolv.conf is not preserving nameserver order from dhcp

### ISSUE THREAD

**Issue by marclennox** [coreos/bugs#247]
I'm on 561.0.0 and I've got an issue where the dns server or is put into resolv.conf not in the order provided by my dhcp server.  The result is that I can't lookup private dns entries from my internal dns server, because it tries to find them on the public ones.  This was working properly in previous versions of CoreOS and broke recently it seems.

**Comment by crawford** [comment]
Can you tell if the order is just a reversal or is it shuffled? This is definitely a change of behavior with systemd.

**Comment by marclennox** [comment]
It appears to be in the order 3,1,2 every time

—

**Comment by marclennox** [comment]
Any progress on this one?  I've updated to the latest Alpha CoreOS and I now think it's pretty random.  On some reboots, resolv.conf has the servers in the correct order, on other reboots it does not.

**Comment by crawford** [comment]
I have not had a chance to look into this one. :(

systemd 219 was just released. It might be worth checking if it fixes the issue before digging around in 218 too much.

**Comment by crawford** [comment]
@marclennox This upstream bug also mentions the behavior you are seeing. https://bugs.freedesktop.org/show_bug.cgi?id=85397#c6

**Comment by marclennox** [comment]
OK thanks Alex, this looks like the same issue indeed.



—

**Comment by marclennox** [comment]
@crawford I was able to work around this by modifying the DOCKER_OPTS to include "--dns=" options, since the issue was only present inside of docker containers (they were inheriting dns settings from the host which were incorrect).

The only weird part is that even if I specify multiple --dns flags in DOCKER_OPTS, only the first one is used, but that sounds like a docker issue.

**Comment by crawford** [comment]
This has since been fixed.
