### ISSUE TITLE
Move ignition issues to the ignition repo

### ISSUE THREAD

**Issue by ashcrow** [coreos/bugs#2471]
### Desired Feature ###

- [x] Create an `issues` area under [ignition](https://github.com/coreos/ignition/)
- [x] Add labels
- [x] Move any open `ignition` issues to https://github.com/coreos/ignition/issues
- [x] Add issue templates
- [x] Update documentation to point people to the project issues rather than the organizational bugs repo.

### Other Information ###

`ignition` has been undergoing work so that it has the ability to be used in multiple distributions. Currently all bugs for `ignition` fall under this repository. While that made a lot of sense when `ignition` was specific to Container Linux/original CoreOS I believe it is a bit confusing as we widen out `ignition` usage.

If this move sounds good I'll help make it happen :-)

**Comment by lucab** [comment]
I left a similar comment for coreos-metadata at https://github.com/coreos/bugs/issues/2468#issuecomment-401779817 this morning.

**Comment by crawford** [comment]
:ship: :it:

**Comment by ashcrow** [comment]
@crawford that took me a minute :laughing:

**Comment by ashcrow** [comment]
In repo doc update: https://github.com/coreos/ignition/pull/572

**Comment by ashcrow** [comment]
We had a bit of a false start on this. It sounds we are in agreement to do this, but we have different views on how much needs to happen right away. I'll follow up with an email thread to try to get some of that hammered out before we continue. In the mean time issues have been turned off in the `ignition` repository.

**Comment by ashcrow** [comment]
In the meantime, let's talk labels. I'm keen to keep `area/*` labels as well as the default GitHub labels. Is there any other labels we *need* to bring along besides those?

**Comment by bgilbert** [comment]
@ashcrow Need?  No.  But IMO `kind/*`, `platform/*`, and `needs/*` (or equivalent) would be useful here.  Is there value to keeping the default labels in their unprefixed form?

**Comment by ashcrow** [comment]
@bgilbert I've generally used them myself. However, if we want to specifically move to ``kind/*`` instead of the default, then no we don't need them.

**Comment by bgilbert** [comment]
I think this is all done now, for both Ignition and coreos-metadata.  Closing.
