### ISSUE TITLE
Download from ratelimit.update.core-os.net fails

### ISSUE THREAD

**Issue by dontub** [coreos/bugs#2473]
Currently downloading larger files from ratelimit.update.core-os.net fail at some point. If I use curl to download e.g. https://ratelimit.update.core-os.net/stableupdate.gz I'll get "transfer closed with x bytes remaining to read". I tried it from different machines so it is not a problem of my setup.

**Comment by bgilbert** [comment]
That server intentionally drops connections every 10 minutes as a workaround for https://github.com/coreos/bugs/issues/2457.  update_engine will automatically resume downloading after a failure.  Is this behavior causing a problem for you?

**Comment by dontub** [comment]
Yes, it makes CoreRoller fail downloading the files and thus it tries it again and again with some delay.

**Comment by bgilbert** [comment]
Ah, gotcha.  I've configured `ratelimit.update.core-os.net` to redirect CoreRoller to the usual update bucket instead.  Let me know whether that fixes the problem for you.

**Comment by dontub** [comment]
Yes, the stable update is received. For `betaupdate.gz` CoreRoller reports a hash missmatch. Though this is obviously another issue.

**Comment by bgilbert** [comment]
Hmm, what OS version does it think it's downloading for the beta channel?

**Comment by dontub** [comment]
1800.2.0. From the log:
> {"_t":"2018-07-05T14:02:09+0000", "_p":"1", "_l":"DBG", "_n":"syncer", "_m":"checkForUpdates, got an update", "channel":"beta", "currentVersion":"1772.3.0", "availableVersion":"1800.2.0"}

As to the logged Omaha response these are the expected hashes and size:
`hash="jKib4Oceb7qIlJEQxghxktHuKSs="`
`hash_sha256="7Ap3UuFiVn3tEPxjs2GEqTkqIKR6K76otiACuyQUyso="`
`size="367849181"`

**Comment by bgilbert** [comment]
Ouch.  That's another bug in our workaround; CoreUpdate should be sending a version number of 1772.4.0 and the corresponding hash.  (We want all machines on 1772.3.0 to upgrade to 1772.4.0 via the ratelimit server before upgrading any further.)  We'll get this fixed as soon as we can.

**Comment by bgilbert** [comment]
The incorrect version and hash values should be fixed now.  Does the beta update now download successfully for you?

**Comment by dontub** [comment]
Yes, it's in sync again with the CoreOS releases. Thank you!
