### ISSUE TITLE
Server 198.137.202.56 in CoreOS NTP Pool has 5 minutes of skew

### ISSUE THREAD

**Issue by theospears** [coreos/bugs#2477]
# Issue Report #

### Container Linux Version ###
Not Applicable

### Environment ###
Not Applicable

### Expected Behavior ###
All NTP servers in `0.coreos.pool.ntp.org` have at least approximately correct clocks

### Actual Behavior ###
The server with IP 198.137.202.56 (rDNS owners.kjsl.com) has a skew of ~355 seconds.

### Reproduction Steps ###
Query the DNS of 0.coreos.pool.ntp.org enough times until it resolves to 198.137.202.56 
Do an NTP request against that server (e.g. with https://servertest.online/ntp) and see its time is wrong.

### Other Information ###
Assuming that coreos manages this pool due to the DNS name, but maybe this is just the main ntp.org pool?

**Comment by lucab** [comment]
Thanks for the report, that server indeed has routinely skewed off in the past days: http://www.pool.ntp.org/scores/198.137.202.56

`0.coreos.pool.ntp.org` is a subzone of the main pool.ntp.org. NTP pool has a mechanism to automatically expunge de-synced servers from the DNS rotation. So the normal pool management logic should eventually prevent users to reach that server while it is misbehaving.

I don't know if we have a way to bar specific servers from our vendor zone, I'll need to check that.

**Comment by lucab** [comment]
Confirmed that we don't have direct control over which servers are part of the "coreos" vendor zone. We still rely on the node-scoring algorithm to evict bad nodes from the pool just-in-time.

**Comment by lucab** [comment]
Additionally, I contacted the ntp-pool admins to check if that server can be de-ranked given the daily drift it routinely experiences. I'm going to close this ticket, as there is nothing else we can directly do.
If anybody happens to step on a bad NTP server in the future, please report it directly to https://www.ntppool.org/en/mailinglists.html.
