### ISSUE TITLE
initrd-cleanup failed during first boot/install

### ISSUE THREAD

**Issue by kratan** [coreos/bugs#2487]
# Issue Report #

### Container Linux Version ###

```
1855.0.0 - alpha
```

### Environment ###

different mainboards are affected (asus consumer mainboards), it works well with virtualboxes

### Expected Behavior ###
booting successfully

### Actual Behavior ###
stuck in boot proccess, after some time pc will reboot

### Other Information ###

with latest stable 1576.5.0 the problem does not appear

**Comment by lucab** [comment]
@kratan thanks for the report, but unfortunately this does not contain enough information for us to be actionable. Can you please check your machine console and see what are the errors logged there? Also, if you press enter before the reboot, you will enter an emergency shell (very limited, in initramfs) where you can inspect the journal logs further.

**Comment by kratan** [comment]
@lucab thanks for your reply. I cant reproduce the problem right now with 1855.0.0. Since i installed latest stable 1576.5.0 now it work with 1855.0.0 too. Maybe the problem had something to do with the existing installation on the hard disk (ubuntu 18.04). 1576.5.0 managed to kill it and 1855.0.0 cant kill it? Just a guess. 
So marked it as solved...

**Comment by lucab** [comment]
@kratan (and anybody happening to hit this) we are still interested in console logs if you manage to reproduce it.

**Comment by kratan** [comment]
ok, i managed to reinstall ubuntu 18.04 again and tried to install coreos 1855.0.0
 via matchbox, problem is back. So it has something to do with the existing installation/hdd partitioning. there is no way to press enter before it reboots. it just reboots.....i have make some screenshots, but they are not very informary

**Comment by kratan** [comment]
Hi, does not happening with coreos 
alpha - 1897.0.0
greets
