### ISSUE TITLE
locksmithctl: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by gintautassulskus** [coreos/bugs#2488]
# Issue Report #

## Bug ##
Locksmithctl is unable to connect to etcd cluster.

### Container Linux Version ###

```
1800.6.0
```

### Expected Behavior ###

Conect to etcd cluster and retrieve requested info.

### Actual Behavior ###
The following is the only output of the `status` command:
`Error initializing etcd client: client: etcd cluster is unavailable or misconfigured`

No connection attemps are seen in `etcd-member` logs.

### Reproduction Steps ###

```
locksmithctl --endpoint=http://127.0.0.1:2379 --etcd-cafile=/etc/etcd/certs/ca.pem --etcd-certfile=/etc/etcd/certs/client.pem --etcd-keyfile=/etc/etcd/certs/client-key.pem --group=stable --debug=true status
```

### Other Information ###

Etcdctl with the same certificates and endpoint works as expected.
```
etcdctl --endpoints=https://127.0.0.1:2379 --ca-file=/etc/etcd/certs/ca.pem --cert-file=/etc/etcd/certs/client.pem --key-file=/etc/etcd/certs/client-key.pem  ls
```

**Comment by dm0-** [comment]
Is there different behavior when you use `https` with the `locksmithctl` command?

**Comment by bgilbert** [comment]
Closing due to lack of response.
