### ISSUE TITLE
docker image ls ls / docker images ls

### ISSUE THREAD

**Issue by MikesCodeProjects** [coreos/bugs#2490]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

### Environment ###
Ubuntu 17.10.1

### Expected Behavior ###

Usage:	docker image COMMAND

Manage images

Options:

Commands:
    [...]

Run 'docker image COMMAND --help' for more information on a command.

### Actual Behavior ###
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

### Reproduction Steps ###

  1. docker image ls ls
  2. docker images ls

**Comment by lucab** [comment]
@MikesCodeProjects looking at your os-release, it seems you are running Ubuntu and you may want to report your troubles according to https://help.ubuntu.com/community/ReportingBugs.

**Comment by MikesCodeProjects** [comment]
### Reproduction Steps ###

  1. docker image ls ls
  2. docker images ls

are docker commands. So this is a docker bug. If you dont fix it, I dont mind. Many developers dont care about bugs. They dont even want to fix those.
