### ISSUE TITLE
User metatadata scripts on GCE behaviour changed

### ISSUE THREAD

**Issue by justinsb** [coreos/bugs#2502]
# Issue Report #

The behaviour of metadata scripts has changed now that scripts are run in a rkt container; it seems like it is no longer possible to start systemd unit files.

### Container Linux Version ###

```
$ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1855.4.0
VERSION_ID=1855.4.0
BUILD_ID=2018-09-11-0003
PRETTY_NAME="Container Linux by CoreOS 1855.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

GCE

### Expected Behavior ###

Previous versions of CoreOS were able to run scripts in GCE metadata.

### Actual Behavior ###

Scripts now run inside a container, and it is hard to register a systemd service.  I have figured out how to do most things in this environment, but I can't figure out how to start a systemd service.

### Reproduction Steps ###

  1. Boot with a metadata script, SSH to the node and `sudo rkt enter <id>` into the rkt container
  2. Register a systemd unit file as normal
  3. `systemctl enable <service>` runs OK
  4.  `systemctl start <service>` fails with `Running in chroot, ignoring request: start`

### Other Information ###

Trying to mount the root and chroot execute on it fails with `System has not been booted with systemd as init system (PID 1). Can't operate.`

**Comment by ajeddeloh** [comment]
How the gce agent is run with rkt has not changed (except in the very latest alpha 1897.0.0 where the gce agent version was bumped). Can you confirm that this does in fact work in 1855.3.0 and 1800.7.0?

**Comment by bgilbert** [comment]
@justinsb What version of Container Linux was previously working for you?

**Comment by bgilbert** [comment]
Closing due to lack of response.
