### ISSUE TITLE
Hardware watchdog support

### ISSUE THREAD

**Issue by urzds** [coreos/bugs#2504]
# Issue Report #

### Environment ###

bare-metal: [Supermicro X8DTT-IBXF, Rev. 1.02](http://www.supermicro.com/products/motherboard/QPI/5500/X8DTT-IBXF.cfm)

### Desired Feature ###

Support for hardware watchdogs, incl. all hardware watchdog kernel modules and the [sys-apps/watchdog](https://packages.gentoo.org/packages/sys-apps/watchdog) userspace daemon.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
