### ISSUE TITLE
coreos-install broken (571.0.0)

### ISSUE THREAD

**Issue by zjeraar** [coreos/bugs#251]
Seems that coreos-install is still broken. I tried on Vultr.com through iPXE. Before 561.0.0 there are no problems,but 561.0.0 and 571.0.0 fail. Not sure what goes wrong.

I call this script as cloud-config-url from the iPXE script:

```
#!/bin/bash

curl -O http://[url_to_cloud_config]/cloud_config_alpha.yml
sudo coreos-install -d /dev/vda -c cloud_config_alpha.yml
sudo reboot
```

Server just keeps rebooting after that, because coreos-install fails.

**Comment by marineam** [comment]
What is the output of the coreos-install command?

**Comment by zjeraar** [comment]
Okay, figured it out. I thought that without specifying the channel, it would take the channel of the currently running os. But it tries to install stable 571.0.0. So I had to add -C alpha to the coreos-install command.

Not sure if this is still a bug then, cause I'm not sure this is intended behaviour.

**Comment by crawford** [comment]
coreos-install isn't necessarily being run from CoreOS, so it doesn't assume it can check the channel. As you found out, it uses "stable" by default.
