### ISSUE TITLE
Failed Units

### ISSUE THREAD

**Issue by oded-dd** [coreos/bugs#2510]
# Issue Report #
There are failed unit on CoreOS (1855.4.0)
### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1855.4.0
VERSION_ID=1855.4.0
BUILD_ID=2018-09-11-0003
PRETTY_NAME="Container Linux by CoreOS 1855.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
AWS

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Expected Behavior ###
We are getting logrotate.service failed units on all our CoreOS instances
See attached the logrotate configuration 
```
# create new (empty) log files after rotating old ones.
create

# use date as a suffix of the rotated file.
dateext

# compress rotated log files.
compress

missingok
notifempty
nomail
noolddir

# accept user provided configuration files in /etc.
include /etc/logrotate.d

# must match creation rules in /usr/lib/tmpfiles.d/var.conf
/var/log/wtmp {
    create 0664 root utmp
    size 1M
}
/var/log/btmp {
    create 0600 root utmp
    size 1M
}
```
### Reproduction Steps ###

  1. ...
  2. ...

**Comment by lucab** [comment]
@oded-dd what does `sudo journalctl -b 0 -u logrotate.service` say?

**Comment by bgilbert** [comment]
Closing due to lack of response.
