### ISSUE TITLE
Bonding devices flapping 

### ISSUE THREAD

**Issue by mimmus** [coreos/bugs#2515]
# Issue Report #
On some bare metal servers, we are observing flapping behaviour on bond interfaces: server starts correctly but it starts to flap up/down indefinitely after a few seconds.
Sometime bonding stabilizes and works; also other servers with same config works.

Same with 1635.x.y. while older servers with 1235.12.0 never experienced this problem.

lspci output:
```
03:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
03:00.1 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
07:00.0 Ethernet controller: NetXen Incorporated NX3031 Multifunction 1/10-Gigabit Server Adapter (rev 42)
07:00.1 Ethernet controller: NetXen Incorporated NX3031 Multifunction 1/10-Gigabit Server Adapter (rev 42)

```

dmesg output:
```
[ 1202.718785] bond0: link status definitely down for interface eno50, disabling it
[ 1202.740897] bond0: making interface eno49 the new active one
[ 1202.770080] ixgbe 0000:03:00.0: removed PHC on eno49
[ 1203.422721] bond1: link status definitely down for interface ens3f1, disabling it
[ 1203.445599] bond1: link status definitely down for interface ens3f0, disabling it
[ 1203.467563] bond1: now running without any active interface!
[ 1203.756603] ixgbe 0000:03:00.1: registered PHC device on eno50
[ 1203.900797] bond0: link status definitely down for interface eno49, disabling it
[ 1203.922685] bond0: now running without any active interface!
[ 1203.947335] ixgbe 0000:03:00.1 eno50: detected SFP+: 5
[ 1204.231861] ixgbe 0000:03:00.0: registered PHC device on eno49
[ 1204.418823] ixgbe 0000:03:00.0 eno49: detected SFP+: 6
[ 1204.574185] netxen_nic: ens3f1 NIC Link is up
[ 1204.948977] netxen_nic: ens3f0 NIC Link is up
[ 1205.492671] bond1: link status definitely up for interface ens3f1, 10000 Mbps full duplex
[ 1205.516306] bond1: making interface ens3f1 the new active one
[ 1205.536738] bond1: first active interface up!
[ 1205.556318] bond1: link status definitely up for interface ens3f0, 10000 Mbps full duplex
[ 1207.550137] ixgbe 0000:03:00.1 eno50: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 1208.014192] ixgbe 0000:03:00.0 eno49: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[ 1208.052596] bond0: link status definitely up for interface eno50, 10000 Mbps full duplex
[ 1208.075343] bond0: making interface eno50 the new active one
[ 1208.096626] bond0: first active interface up!
[ 1208.115676] bond0: link status definitely up for interface eno49, 10000 Mbps full duplex

```

### Container Linux Version ###
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1800.7.0
VERSION_ID=1800.7.0
BUILD_ID=2018-08-15-2254
PRETTY_NAME="Container Linux by CoreOS 1800.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

### Environment ###
HP ProLiant DL560 Gen9 server

### Expected Behavior ###
Stable network

### Actual Behavior ###
Flapping bonding interfaces

### Reproduction Steps ###

  1. Boot via PXE, install on disk with coreos-install and Ignition file
  2. Reboot
  3. After a few seconds, both bonding interfaces start to flap

### Other Information ###
Relevant config:

```
**/etc/modprobe.d/bonding.conf**
options bonding max_bonds=0

**/etc/systemd/network/10-eth.network**
[Match]
Name=eno*
[Network]
Bond=bond0

**/etc/systemd/network/15-eth.network**
[Match]
Name=ens*
[Network]
Bond=bond1

**/etc/systemd/network/20-bond.netdev**
[NetDev]
Name=bond0
Kind=bond
[Bond]
Mode=active-backup
MIIMonitorSec=1s

**/etc/systemd/network/25-bond.netdev**
[NetDev]
Name=bond1
Kind=bond
[Bond]
Mode=active-backup
MIIMonitorSec=1s

**/etc/systemd/network/30-bond0.network**
[Match]
Name=bond0
[Network]
Address=10.11.0.12/23
Gateway=10.11.1.254
DNS=10.9.1.11
DNS=10.192.72.77
Domains=mydomain.com
LinkLocalAddressing=no
IPv6AcceptRA=no

**/etc/systemd/network/35-bond1.network**
[Match]
Name=bond1
[Network]
Address=192.168.99.190
LinkLocalAddressing=no
IPv6AcceptRA=no

```

**Comment by bgilbert** [comment]
Would you mind testing on the latest alpha release?

**Comment by mimmus** [comment]
Unfortunately, Mesosphere DC/OS currentky supports at most 1800.7.0.
Are you aware of some bug?

I was thinking alsi to try only with two network cards, leaving out others
two, as I noticed that only LAN switches disable related ports due to
excessive flapping while NFS switches don’t.

Thank you

Il giorno gio 25 ott 2018 alle 19:09 Benjamin Gilbert <
notifications@github.com> ha scritto:

**Comment by bgilbert** [comment]
The latest alpha release includes kernel 4.19.  That kernel may eventually be promoted to the beta and stable channels, and it'd be helpful to see whether it fixes your issue.

I hadn't noticed that you were running an old stable release.  It's worth trying 1855.5.0 as well.  We don't support versions of Container Linux older than the most recent version in each channel.

**Comment by mimmus** [comment]
I was convinced that 1800.7.0 was the latest stable, sorry.
Our platform Mesosphere DC/OS supports various versions:
https://docs.mesosphere.com/version-policy/#dcos-platform-version-compatibility-matrix
but I don' see 1855.5.0! Probably a typo.

I hope to be able to try latest alpha today and eventually give a note
about this to Mesosphere (and you).

Thanks again

Il giorno ven 26 ott 2018 alle ore 00:02 Benjamin Gilbert <
notifications@github.com> ha scritto:

**Comment by mimmus** [comment]
Investigations continued.
It seems that Mesosphere DC/OS agressively restarts systemd-networkd during its bootstrap phase and it fails almost always if bonding (instead of simpler networking) is in use, probably because it is slower or for other causes (I found this https://github.com/systemd/systemd/issues/10118)

I will post updates when I will be sure.

**Comment by mimmus** [comment]
I can confirm that Mesosphere DC/OS restarts systemd-networkd too aggressively.
Now they modified their script to check for network config modification before restarting systemd-networkd and this seems to relieve issue.
In any case, it’s not fully clear why issue is not seen with normal (not bonding) interfaces.

For me, this case can be closed.
