### ISSUE TITLE
Azure Linux Agent Update to 2.2.32

### ISSUE THREAD

**Issue by danielsollondon** [coreos/bugs#2519]
# Issue Report #
The Linux Agent team have released 2.2.32, please can you update your Linux Agent packages and images with this latest release.

## Bug ##
For details on this release please see : https://github.com/Azure/WALinuxAgent/releases/tag/v2.2.32

**Comment by bgilbert** [comment]
This should be fixed in the upcoming alpha 1995.0.0.  Thanks for reporting.
