### ISSUE TITLE
Vagrant is not able to successfully provision a CoreOS virtual machine that is using multiple virtual CPU cores

### ISSUE THREAD

**Issue by iulian-antohe** [coreos/bugs#2520]
# Issue Report #

## Bug ##
`vagrant up` command fails communication check with the VM within the default boot timeout (300 seconds) when `vm_cpus` variable is set to a number greater than 1.

### Container Linux Version ###

```
$ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1939.0.0
VERSION_ID=1939.0.0
BUILD_ID=2018-10-22-2357
PRETTY_NAME="Container Linux by CoreOS 1939.0.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
Hardware: MacBook Pro, i7, 16 GB RAM
Host OS: macOS High Sierra 10.13.6
Hypervisor: VirtualBox 5.2.20
Tool: Vagrant 2.2.0

### Expected Behavior ###
Vagrant is able to successfully provision a CoreOS virtual machine that is using multiple virtual CPU cores.

### Actual Behavior ###
```
$ vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Importing base box 'coreos-alpha'...
==> core-01: Configuring Ignition Config Drive
==> core-01: Matching MAC address for NAT networking...
==> core-01: Checking if box 'coreos-alpha' is up to date...
==> core-01: Setting the name of the VM: coreos-vagrant_core-01_1540911239013_16367
==> core-01: Clearing any previously set network interfaces...
==> core-01: Preparing network interfaces based on configuration...
    core-01: Adapter 1: nat
    core-01: Adapter 2: hostonly
==> core-01: Forwarding ports...
    core-01: 22 (guest) => 2222 (host) (adapter 1)
==> core-01: Running 'pre-boot' VM customizations...
==> core-01: Booting VM...
==> core-01: Waiting for machine to boot. This may take a few minutes...
    core-01: SSH address: 127.0.0.1:2222
    core-01: SSH username: core
    core-01: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

### Reproduction Steps ###

  1. Open `Vagrantfile` in your favourite text editor.
  2. Go to line 33 and change `vm_cpus` variable to a number greater than 1. For example: `$vm_cpus = 2`.
  3. Run `vagrant up`

### Other Information ###
I've attached the VirtualBox debug log file [here](https://github.com/coreos/bugs/files/2530269/coreos-vagrant-virtualbox-debug.log).

**Comment by luishdez** [comment]
Looks that I'm having the same problem. Works with 1 cpu fails when I set multiple cores

It says 

<img width="846" alt="cores" src="https://user-images.githubusercontent.com/38347/50939549-9d0f3d80-147d-11e9-86a0-c5e9f8211df4.png">

**Comment by nurtext** [comment]
Same here. What to do?

**Comment by luishdez** [comment]
Well CoreOS (the SO) won't be maintained anymore just security issues (I think) apparently they are going to release a new SO under fedora so I won't expect any fix for this. Anyways I haven't seen much movement with the project

https://coreos.fedoraproject.org/

**Comment by nurtext** [comment]
@luishdez Oh wow I didn't knew that because I haven't used CoreOS for a long time. Thanks for poiting out.

**Comment by brohan** [comment]
Any update? I am trying to test out CoreOS with Kubernetes, Kubernetes master requires 2 CPUs. I have the same issue with the key login b/c the VM never comes up (potential timing issue). FWIW my host in Manjaro running VirtualBox.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
