### ISSUE TITLE
initrd-cleanup.service fails on SIGTERM, causing boot failure

### ISSUE THREAD

**Issue by bgilbert** [coreos/bugs#2526]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1953.0.0
VERSION_ID=1953.0.0
BUILD_ID=2018-11-06-0042
PRETTY_NAME="Container Linux by CoreOS 1953.0.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

Any?

### Expected Behavior ###

System boots successfully.

### Actual Behavior ###

Some boots drop to an emergency shell in the real root (i.e. not the initramfs shell).

### Reproduction Steps ###

1. `kola run`

### Other Information ###

Journal excerpt:

```
[    7.310801] systemd[1]: initrd-cleanup.service: Main process exited, code=killed, status=15/TERM
[    7.328219] systemd[1]: initrd-cleanup.service: Failed with result 'signal'.
[    7.360409] systemd[1]: initrd-cleanup.service: Triggering OnFailure= dependencies.
```

This looks similar to https://github.com/systemd/systemd/issues/4343, which was supposedly fixed by https://github.com/systemd/systemd/pull/4345.

**Comment by dm0-** [comment]
I've run thousands of test instances with systemd 241, and this issue has not happened again.  I'll optimistically close this as fixed in the next alpha.
