### ISSUE TITLE
iptables is 3 years out of date in Container Linux

### ISSUE THREAD

**Issue by RichardoC** [coreos/bugs#2528]
# Issue Report #

## Bug ##

Could https://github.com/coreos/portage-stable/tree/master/net-firewall/iptables be updated from upstream? This is a 3 year old version of iptables which means container linux is missing the mitigations for issues listed in projectcalico/felix#1901 and https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02

I'm happy to do it myself, but the README for that repo has gone stale.

Thanks!

**Comment by dm0-** [comment]
What part of the README doesn't work?

Is the host iptables being used for those issues, or is it the version in the container?

I've put up PRs for the update regardless.  They would make it to the stable channel in February based on the current schedule.

**Comment by bgilbert** [comment]
> There is no update_ebuilds file in scripts dir

That script is [in the scripts repo](https://github.com/coreos/scripts/blob/master/update_ebuilds) within an [SDK](https://coreos.com/os/docs/latest/sdk-modifying-coreos.html).

**Comment by dm0-** [comment]
@RichardoC The PR uses 1.6.2, since Gentoo only marks 1.6.1 as the latest stable version, and 1.6.2 is listed in the PR as supporting all the needed flags.

**Comment by RichardoC** [comment]
Thanks
