### ISSUE TITLE
Add support for ip_vs_mh module in the kernel

### ISSUE THREAD

**Issue by xnaveira** [coreos/bugs#2542]
## Feature Request ##
As a part of a bare metal kubernetes cluster on CoreOS we run ingress controllers that get their traffic via BGP ECMP and we would like to run Google's Maglev algorithm (https://ai.google/research/pubs/pub44824) on our ipvs instances. There is a module for that since 4.18 Kernel (https://github.com/torvalds/linux/blob/master/net/netfilter/ipvs/ip_vs_mh.c) but it is not currently included in your beta/alpha releases (1995.1.0 and 2016.0.0 respectively) which run on kernel 4.19.13.

### Environment ###
Bare metal servers

### Desired Feature ###
We are custom compiling the ip_vs_mh module using this guide https://coreos.com/os/docs/latest/kernel-modules.html but it would be much more convenient to have it precompiled.

**Comment by dm0-** [comment]
This will be in the alpha release on Tuesday.
