### ISSUE TITLE
Container Linux versions based on kernel 4.14.96 have broken POSIX timers

### ISSUE THREAD

**Issue by urisimchoni** [coreos/bugs#2549]
# Issue Report #

### Container Linux Version ###
Unknown (issue happens at my SaaS CI infrastructure), but the kernel is:
uname -a
Linux 6af282fe-9334-4ae9-8a12-a75fabd6c201 4.14.96-coreos #1 SMP Mon Jan 28 05:16:10 -00 2019 x86_64 x86_64 x86_64 GNU/Linux

### Environment ###

Bitbucket pipelines

### Expected Behavior ###
Posix timers generate periodic signals if configured to do so

### Actual Behavior ###
Posix timers generate a signal just once

### Reproduction Steps ###
I'm skipping this because the problem is well understood and has an upstream fix - see below.

### Other Information ###
Kernel 4.14.96, used by Container Linux 1967.5.0 and 1967.4.0, has a regression with POSIX timers. The fix is in 4.14.97, see kernel release notes https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.14.97 under "posix-cpu-timers: Unbreak timer rearming".

This is the same bug as reported in https://bugzilla.redhat.com/show_bug.cgi?id=1662602

This breaks some tests that we run in Bitbucket pipelines, which seem (according to reported kernel version) to run Container Linux.

**Comment by bgilbert** [comment]
This should be fixed in 1967.6.0, due shortly.  Thanks for reporting!
