### ISSUE TITLE
AWS ENA driver Version 2.0.2 

### ISSUE THREAD

**Issue by sohel2020** [coreos/bugs#2552]
We are using CoreOS 1745.7.0 version with ena 1.2.0. A week ago we faced network driver problem and we reach out to AWS support. They investigate and recommend to use ENA version 2.0.2.  But looks like coreos latest stable version is using the same version (1.2.0). 

Is it possible to customize coreos 1745.7.0 and update the driver?  possible bake AMI with latest version? What is the procedure to customize coreos AMI?

**Comment by dm0-** [comment]
I wrote how to do this here: https://groups.google.com/forum/#!msg/coreos-user/wERApCZ7tr8/n8MDP4HQBAAJ

If that doesn't work for you, maybe try building just the newer module source for the existing kernel with a procedure like https://coreos.com/os/docs/latest/kernel-modules.html which would allow manually loading the module on official AMIs.  (I have not investigated if that is feasible to do with the ENA module.)

**Comment by sohel2020** [comment]
Hi David,
Now we're using 1967.6.0 and want to install ena driver 2.0.2 on top of this version. I'm sharing what I have already done.

1. In my local machine (Ubuntu 14.04), I have installed cork, make it executable send to /usr/bin
2. mkdir coreos-sdk && cd coreos-skd
3. cork create --manifest-branch build-1967 
4. cork enter

What I Don't know:
5. I don't know where to add ena driver with version 2.0.2.
6. and next what command need to run. May be couple of commnad needs to run. (would be really great if I get step by step command)
7. How to make image like AWS support?
8. How to upload that images to my AWS account using AWS cli?

Thanks in Advance.

**Comment by dm0-** [comment]
The two methods I suggested (updating the distro to Linux 4.20 or attempting to backport the module) require more time than I can dedicate to this, and neither will be supported in Container Linux.  If no one from the community decides to do this work for you or has a different suggestion and you truly require a newer ENA driver, then I'd recommend switching to a different distro that supports Linux 4.20 or later.  You can continue to try the mailing list or IRC if you want to pursue community support, but I'm going to close this issue as there is nothing for us to fix in this report.
