### ISSUE TITLE
support vmware_fusion in vagrant-ignition plugin

### ISSUE THREAD

**Issue by nickytd** [coreos/bugs#2557]
## Feature Request ##
Support vmware_fusion in vagrant-ignition plugin
### Environment ###
Vagrant , c, VMware Fusion
What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Desired Feature ###
support vmware_fusion in vagrant_ignition plugin

### Other Information ###
Currently cloud-config is the only supported mechanism for coreos vagrant box configurations on VMware_fusion. But that is outdated now. Are there plans the enhance current vagrant-ignition plugin to support also vmware_fusion provider?

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
