### ISSUE TITLE
ignition fails to install in Debian unstable (2019-03) due to wrong dependencies

### ISSUE THREAD

**Issue by abate** [coreos/bugs#2559]
# Issue Report #

ignition fails to install in Debian unstable (2019-03) due to wrong dependencies

## Bug ##

```
$ vagrant up
Installing plugins: vagrant-ignition
Installing the 'vagrant-ignition' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 2.1.0)
  Activated fog-core-2.1.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 2.1.0), 2.1.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)


Installation of one or more plugins has failed. Aborting.
```

### Environment ###

```
$ vagrant --version
Vagrant 2.2.3
$ vagrant plugin list 
vagrant-libvirt (0.0.45, system)

```

### Expected Behavior ###

It should install correctly

### Actual Behavior ###

Fails to install 

### Reproduction Steps ###

  1. `vagrant plugin install vagrant-ignition` on debian unstable
  2. ...

**Comment by bgilbert** [comment]
That would be the vagrant-ignition plugin, not Ignition.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
