### ISSUE TITLE
Add support for vhost_vsock module in the kernel

### ISSUE THREAD

**Issue by jcrowthe** [coreos/bugs#2563]
## Feature Request ##
As part of an effort to achieve greater workload isolation, we are looking to run containers inside a lightweight [Firecracker VM](https://firecracker-microvm.github.io/). Firecracker has very few dependencies, but does require the `vhost_vsock` [kernel module](https://github.com/torvalds/linux/blob/master/drivers/vhost/vsock.c). This module has been available since kernel 4.8 but is not included in the Container Linux releases.

### Environments ###
Azure, bare metal, and AWS

### Desired Feature ###
Include `vhost_vsock.ko` kernel module in standard releases of Container Linux.

**Comment by bgilbert** [comment]
Thanks for reporting.  This should be enabled in the next alpha release of Container Linux.
