### ISSUE TITLE
vhost_vsock kernel driver broken

### ISSUE THREAD

**Issue by jcrowthe** [coreos/bugs#2570]
# Issue Report #

## Bug ##

In kernel maintainers mitigating a CVE, a new bug was introduced regarding 32bit and 64bit variables in the `vhost_vsock` kernel driver. The fix was rather simple, [found here](https://github.com/torvalds/linux/commit/7fbe078c37aba3088359c9256c1a1d0c3e39ee81). 

Notably, since CoreOS Alpha is currently on 4.19.28 it is affected. The next version that contains this fix is kernel version 4.19.30 https://lwn.net/Articles/783478/

## Solution ## 
Upgrade CoreOS kernel to 4.19.30.

### Container Linux Version ###
2079.0.0 - Alpha

### Environment ###
AWS/Azure/Baremetal

**Comment by dm0-** [comment]
Updates will roll out on Tuesday with 4.19.30 (or 4.19.31 if it's tagged by then).

**Comment by bgilbert** [comment]
Already fixed in Git for master and alpha; closing.
