### ISSUE TITLE
/_coreos.com/fleet/lease/engine-leader Key Not Found

### ISSUE THREAD

**Issue by danielschonfeld** [coreos/bugs#258]
I have a 3 machine dedicated etcd cluster.  I have about 20 worker machines which run fleet.  All of this runs on CoreOS 522.5.0 (stable).

I have recently raise the heartbeat timeout value to 200 while the election timeout value was 1200 for a long while.

Everything seems to be working fine and normal but I am worried about the engine-leader key not found which I have recently discovered while seeing a lot of the following in my fleet logs:

```
Failed getting response from http://etcd1:4001/: cancelled
```

Somehow that prompted me to check for the engine-leader key and there, to my surprise i found out that 2 out of the 3 etcd machines have a Key Not Found while the third machine continues getting the TTL and key updated every 2 seconds.

Nothing out of the ordinary in the etcd logs of any one of my 3 machines.  Just the usual

```
snapshot of 10005 events at index 216251730 completed
```

I have tried creating a bash script that updates a key every 2 seconds with a 10 second t/l and have NOT observed the same problem.  The key was available and set correctly on all three machines.

**NOTE: this is the only key in my etcd cluster exhibiting this behavior.

**Comment by danielschonfeld** [comment]
I've went ahead and effectively paused and then shut down fleet across my cluster by first setting the engine-leader to having a Version of:99 (thanks @bcwaldon) and then shutting down fleet.  

Then I went ahead and tried to mimic what fleet would do, by utilizing the following script:
```
#!/bin/bash

etcdctl set --ttl 10 /_coreos.com/fleet/lease/engine-leader '{"MachineID":"XXX","Version":99}'

while :
do
	echo "Press [CTRL+C] to stop.."
	etcdctl set --ttl 10 /_coreos.com/fleet/lease/engine-leader '{"MachineID":"XXX","Version":99}'
	sleep 2
done
```

The key's value was preserved just fine across the 3 node etcd cluster.

Another interesting thing to note is that between writing this issue and now, my leader has changed from etcd3 to etcd2.  When I go ahead and restart fleet across the cluster and remove my version:99 key, and let fleet acquire a leader again.  The same thing as reported above happens.  However, this time the key stays on the etcd2 machine while etcd1&etcd3 machines show an expires, Key Not Found. 

The difference between my original posting and now is that while the leader of etcd is the machine that keeps on maintaining the key's value, the physical machine it happens on has changes since my original posting.

This leads me to think there is something different in how fleet 0.8.3 sets a key with etcd and giving it a TTL and how 'etcdctl set --ttl' does it, in etcd 0.4.6.

**Comment by bcwaldon** [comment]
To answer the question about your simulation matching what fleet is actually doing: each fleet daemon is doing a create (set w/ PrevExist=false), then a CAS (set w/ PrevIndex). You're just using a bare set, which doesn't take into account the previous state, and won't generate the appropriate "create" event. I'm still not sure why you're seeing this behavior, though.

**Comment by danielschonfeld** [comment]
@bcwaldon how can I recreate that with a simple bash script utilizing etcdctl? or is that not possible?

is there any other diagnostic i could do or provide to help figure out why this problem happens and above all, why does fleet some to be functioning *properly*

**Comment by danielschonfeld** [comment]
Just wondering if anyone has an idea of what to do with the bug mentioned above?  Lately this has been hitting us more with random fleet workers exhibiting those cancelled errors for a while and then restarting the fleet daemon taking with them all the scheduled units on that worker and restarting them.

There were no network issues with etcd at the time or unreachability of the cluster as a whole.  It just the random worker each time that cannot reach it.

**Comment by marineam** [comment]
For reference, some IRC chatter from today on this:
```
20:00 < schone> does anyone have any clue about https://github.com/coreos/bugs/issues/258
20:01 < schone> we are still dealing with this issue and every now and then fleet seems to die on some arbitrary machine
20:02 <@marineam> schone: hm, if bcwaldon is the one guy who will know, not sure if he is online at the moment.
20:03 < schone> marineam: i just wish this could be solved… i mean for the most part things are working but its weird and fleet sometimes decided to die and with i
t the unscheduling that happens is disruptive for us
20:04 < schone> i just upgraded the etcd dedicated cluster to 0.4.7 and that didnt solve anything
20:05 <@marineam> schone: understood, and 0.4.7 was just made to smooth over the eventual transition to 2.0, if the bug is the fault of etcd that version won't make a difference.
20:05 < schone> marineam: got ya
20:10 <@marineam> schone: I'm not sure if fleet's etcd client differes much from etcdctl in behavior, but to get a sense of if something has gone seriously wrong in the cluster I would curl the offending key both with ?consistent=true and without.
20:11 < schone> marineam: on which node?
20:11 <@marineam> schone: try all of them
20:12 <@marineam> if you wind up with different results then the etcd cluster likely lost touch with reality in the middle of a leader election. Or some similar terrible terrible state.
20:12 < schone> marineam: thats been the problem all along i think, differing results
20:13 < schone> marineam: so with consistent=FALSE i get what i expected, a key not found on both follower nodes and the key value correctly displaying on the master/leader node of etcd
20:13 < schone> with consistent=TRUE i get redirects to the master/leader node of etcd from both followers and the leader showing the correct key value
20:15 <@marineam> schone: yeah, so somehow the current master got into a different state of reality from the others, and then from then on things are funky. I can reliably hit that if disk IO is slow enough to trigger leader election thrashing for a while.
20:16 <@marineam> schone: we haven't added 2.0 to images yet but my hope is that it will make that class of problems go away (although may bring entirely new exiting problems)
20:16 < schone>  marineam: but when the master changes, i get the same results only this time pointing to the correct new master
20:16 <@marineam> schone: hm, then perhaps it is a different situation than what I've hit.
20:17 < schone> marineam: if it was indeed the situation you referred to.  what can I do to correct it?
20:18 <@marineam> schone: mostly make sure the etcd nodes do not have problems with high IO latency, if you are on btrfs switching to ext4 may help.
20:19 <@marineam> but I would need to defer to bcwaldon or one of the etcd guys (who I don't see in this channel right now)
20:20 < schone> marineam: high IO u mean disk or network or both?
20:20 < schone> and also how can I switch the CoreOS image to using ext4 instead of btrfs?
20:20 <@marineam> schone: sorry, I meant disk latency
20:21 < schone> marineam: is there a way to fix the current state of affairs?
20:21 <@marineam> schone: install from a recent image or format/mount an extra data volume.
20:22 < schone> marineam: i would be more than happy to give you guys SSH access if u wanted to that etcd cluster… in case you wanna see for yourselves what we’ve got here
20:24 <@marineam> schone: after lunch we'll try to recruit someone to look into this again.
20:24 < schone> marineam: ok thanks :) we’ll be here and ready
20:25 < schone> marineam: I believe this is the behavior we see from our fleet workers https://github.com/coreos/fleet/issues/1044 - but, i am not sure if its related to the etcd bug or not we have
20:25 < schone> also we have raise the timeout on our fleet workers and it didnt change anything
20:29 <@marineam> schone: ok, afk for a bit.
22:58 <@marineam> schone: wasn't able to get anyones time this afternoon, but we should be able to get back to you in the next few days.
```

**Comment by bcwaldon** [comment]
@danielschonfeld Can you share the precise commands you are using that make you conclude that two of the etcd nodes don't have the keys? Perhaps time is not in sync across the cluster?

**Comment by marineam** [comment]
@bcwaldon sorry, forgot to update this bug. It was the etcd cluster causing issues. @danielschonfeld was running on small instances on GCE which have been known to frequently throw etcd into leader election thrashing and various resulting bad states. I walked him through migrating his cluster to n1-standard instances with a better IO quota to hopefully ease the pain of etcd 0.4.x. Initial reports were positive so I think we can consider this resolved.

**Comment by danielschonfeld** [comment]
I can confirm the above and to add to that we also switched along the way from spinning disks to a 50GB SSD boot disk for the instances.

So far everything looks pretty good.
