### ISSUE TITLE
CoreOS kernel config: CONFIG_XDP_SOCKETS is not set

### ISSUE THREAD

**Issue by mkfsn** [coreos/bugs#2580]
I would like to use AF_XDP in CoreOS Linux, but it seems like it's not enabled by default:

```
# grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Container Linux by CoreOS 2079.3.0 (Rhyolite)"

# zcat /proc/config.gz | grep XDP
# CONFIG_XDP_SOCKETS is not set
```

Could this be added in CoreOS Linux? Or could it be installed in some other ways?

**Comment by dm0-** [comment]
This will be in the alpha update released on Tuesday.  It will promote to stable in mid-June.

**Comment by mkfsn** [comment]
@dm0- Thanks!
