### ISSUE TITLE
Transpiler silently fails when keys are missing or there are unknown keys present

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [coreos/bugs#2585]
# Issue Report #

Transpiler when presented with a unit with incorrect keys (i.e. "content") and which is missing a crucial key ("contents") does no type checking and does not report these as errors! The transpiler silently "succeeds" to create an empty unit file, pushes a JSON with empty unit to userdata, then silently fails to install the empty unit on the target, reporting "success".

## Bug ##

There appears to be no type checking or validity checking in the transpiler. This is bizarre for a transpiler; it should throw a hard error on missing keys or on presence of keys it does not know how to process.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2079.3.0
VERSION_ID=2079.3.0
BUILD_ID=2019-04-22-2119
PRETTY_NAME="Container Linux by CoreOS 2079.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
r
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
AWS

Transpiler is the Terraform transpiler https://github.com/poseidon/terraform-provider-ct/blob/master/README.md

### Expected Behavior ###

Throw an error if a key is present that is not understood (i.e. "content") or if a crucial key for a unit (like "contents") is missing.

### Actual Behavior ###

This YAML:
```yaml

  - name: rsconnect.service
    enabled: true
    content: |
      [Unit]
      Description=wat

      [Service]
      Type=oneshot
      ExecStart=echo "foo"

      [Install]
      WantedBy=multi-user.target
```

Results in this JSON in userdata:
```json

// ...
  "systemd": {
    "units": [
      {
        "enabled": true,
        "name": "rsconnect.service"
      },
//...

```
Ignition  shows

```
May 15 18:54:07 localhost ignition[457]: files: op(e): [started]  processing unit "rsconnect.service"
May 15 18:54:07 localhost ignition[457]: files: op(e): [finished] processing unit "rsconnect.service"
May 15 18:54:07 localhost ignition[457]: files: op(f): [started]  enabling unit "rsconnect.service"
May 15 18:54:07 localhost ignition[457]: files: op(f): [finished] enabling unit "rsconnect.service"
```

But there is no file /etc/systemd/system/rsconnect.service

### Reproduction Steps ###

  1. Have a YAML file with a config for a unit with no "contents" but a "content"
  2. Watch it silently fail

### Other Information ###

Probably related to https://github.com/coreos/ignition/issues/587

**Comment by ajeddeloh** [comment]
The transpiler actually does warn on this, but it only warns, it does not error. I think this is actually a bug with the terraform provider, not CLCT.

The Ignition bug you linked is actually different. That bug refers to the fact Ignition doesn't know what units are on the system it runs on (actually it _can't_ know) and thus you can try to enable a nonexistent unit and succeed.

**Comment by krestivo-kdinfotech** [comment]
Thanks. I'd like to have it be an error. 

I'll try to locate the ct terraform plugin source code and see what it is doing.

**Comment by ajeddeloh** [comment]
I'm going to close this as it doesn't look to be a bug in CLCT. Please reopen if that turns out not to be the case.
