### ISSUE TITLE
CoreOS Stable 2135.4.0 build appears unstable for us (veritysetup, dm-verity, and falco_probe issues seen)

### ISSUE THREAD

**Issue by spkane** [coreos/bugs#2599]
# Issue Report #

## Bug ##

The CoreOS Stable 2135.4.0 build appears to have serious reliability issues. We have been unable to install it successfully on bare metal or VMs via iPXE. Reverting back to 2079.6.0 works fine.

### Container Linux Version ###

```
CoreOS Stable 2135.4.0
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

We have tested this on SuperMicro hardware (x86_64) and VMs (Xen HVM) in IBM's classic infrastructure (Softlayer).

### Expected Behavior ###

The netboot installer and OS should both work as expected.

### Actual Behavior ###

We believe that there have been 2 separate symptoms. On the VMs things appeared to always fail at first boot, in the initrd phase (dracut-45), with an error in `veritysetup` from `dm-verity`.

On the hardware the setup usually installs and boots, but then we get a kernel panic that seems to be caused by `falco_probe` very soon after the system is ready for a login.

### Reproduction Steps ###

  1. Install CoreOS Stable 2135.4.0 onto disk from the CoreOS Stable 2135.4.0 netboot image or any earlier netboot image.

### Other Information ###

![image](https://user-images.githubusercontent.com/129629/60297145-72565b80-98dc-11e9-9514-4c0d807b39ef.png)

**Comment by ajeddeloh** [comment]
We didn't see any verity errors in our CI. Can you double check the kernel/userspace images you're using match versions? Can you verify the images pass gpg verification?

**Comment by spkane** [comment]
I am pretty sure that the our codebase verifies all of this after downloading from the +current+ release from the +stable+ channel and I know that the CoreOS installer script checks the gpg signature, but we can definitely double check this.

**Comment by spkane** [comment]
Ok, I think we have determine what is causing the verity issue, although it is interesting since we have never seen this before. I feel somewhat confident that something changed that made what we are doing "bad".

After installing `coreos-installer` we immediately modify the OEM partition to change some linux kernel parameters for grub (this is a snippet of a Go template that generates that script)

```
          echo "Installing CoreOS to disk" > /dev/console
          /opt/coreos-install -d "${DEVICE}" -V {{ getOrDefault .Host.Tags "coreos-version" (getEnvOrDefault "COREOS_VERSION" "current") }} -C {{ getOrDefault .Host.Tags "coreos-channel" "stable" }} -i /opt/ignition.json

          echo "Modifying grub config" > /dev/console
          WORKDIR=$(mktemp --tmpdir -d coreos-install.XXXXXXXXXX)
          OEM_DEV=$(blkid -t "LABEL=OEM" -o device "${DEVICE}"*)
          mkdir -p "${WORKDIR}/oemfs"
          mount "${OEM_DEV}" "${WORKDIR}/oemfs"
          echo "Disabling THP" > /dev/console
          echo 'set linux_append="$linux_append transparent_hugepage=never"' >> "${WORKDIR}/oemfs/grub.cfg"
          {{ if eq (index .Host.Tags "intel_idle") "off" }}
          echo 'set linux_append="$linux_append intel_idle.max_cstate=0"' >> "${WORKDIR}/oemfs/grub.cfg"
          {{ end }}
          {{ if eq (index .Host.Tags "elevator") "cfq" "deadline" "noop"}}
          echo 'set linux_append="$linux_append elevator={{ index .Host.Tags "elevator" }}"' >> "${WORKDIR}/oemfs/grub.cfg"
          {{ end }}
          umount "${WORKDIR}/oemfs"
```

This appears to make verity very unhappy now. Is there something that we need to do to re-sign things, or is there a simple, but better approach to ensuring that these setting are configured before the first boot?

Also, in the initial boot I mentioned that we were seen a kernel panic on some systems related to `falco_probe`, I am reasonably sure that this is related to the fact that we are running sysdig falco in a container, and it is an older release. So, likely some change in the kernel module has caused in to panic. We'll update that container with a more recent release to see if that fixes the kernel panic.

**Comment by spkane** [comment]
Also, as a side note. Is there a stable release candidate channel? Something that would allow testing releases that are about to get promoted to stable, but not test all the beta releases?

**Comment by spkane** [comment]
So, our current thinking is that the `veritysetup` issue was legitimate (and not related to the above code). That being said, we are still at a loss to what caused it, but we have been unable to re-produce it on other nodes.

The `falco_probe` kernel panic, is related to the fact that our `sysdig-falco` container is older and needfs to be updated for this release of CoreOS.

In general, this container can likely be closed, but I would still like to know:

> Is there a better (more proper) way to update the grub config before the first boot, than what we are doing in the script snippet above?

and

> Is there a stable release candidate channel? Something that would allow testing releases that are about to get promoted to stable, but not test all the beta releases?

Thank you!

Sean

**Comment by ajeddeloh** [comment]
> Is there a better (more proper) way to update the grub config before the first boot, than what we are doing in the script snippet above?

Editing the grub.cfg in the OEM partition should be fine. I'm not sure why it's causing verity issues. Verity only looks at /usr so editing OEM shouldn't cause issues there.

> Is there a stable release candidate channel? Something that would allow testing releases that are about to get promoted to stable, but not test all the beta releases?

Beta is the stable release candidate channel. Most of the time the difference between the two is very minor. Several of the last few stable promotions have involved no changes. Do not read into "beta" as "unstable", it simply leads Stable to catch exactly the kinds of things going on here.

**Comment by spkane** [comment]
Ok. Thank you for the information. I'll go ahead and mark this closed for now as I think the core issues are actually on our side.
