### ISSUE TITLE
cloud-config unit is stuck on fresh server boot

### ISSUE THREAD

**Issue by dustinwtf** [coreos/bugs#26]
I have a custom docker unit in my cloud-config along with a unit that builds a docker image (ExecStartPre) and then runs that image (ExecStart).

Though, when the server first starts, it hangs on my unit that builds the docker image.

```
May 21 00:19:56 coreos-27 docker[7820]: Uploading context 5.632 kB
May 21 00:19:56 coreos-27 docker[7820]: Uploading context
```

That is the last thing in my `systemctl status builder`.

Now, if I stop the process and start it manually, it works perfectly.  It only seems to hang on boot.

Here's a gist with a little bit more info.  It has the full status and the unit that is used my cloud-config.  https://gist.github.com/dustinwtf/ffcddb5aa3cf8ffbec63

If I can provide any more info here, let me know.

**Comment by mischief** [comment]
@dustinwtf is this issue still occurring for you?

**Comment by dustinwtf** [comment]
I haven't seen this happen in awhile so maybe it has been fixed or maybe it was something on my end.

Thanks!
