### ISSUE TITLE
backport: systemd-nspawn kernel module capability

### ISSUE THREAD

**Issue by philips** [coreos/bugs#260]
http://cgit.freedesktop.org/systemd/systemd/commit/?id=d0a0ccf3fecdb422d3fb7ab89646fe9042f11acd

Can we get this in an image to fix @jayofdoom 's usecase?

/cc @crawford

**Comment by jayofdoom** [comment]
While this now allows me to merge kernel modules, it looks like still our BIOS flasher is failing inside the container. I think I'll have to patch out all the seccomp stuff if capability=all in order to have this continue to work inside an nspawn container.

**Comment by crawford** [comment]
This patch is now in 584.0.0. I'm going to close out this bug.

@jayofdoom let me know what other patches you need in order to make this work.
