### ISSUE TITLE
Old/re-published AWS AMIs appearing in us-east-1

### ISSUE THREAD

**Issue by dghubble** [coreos/bugs#2604]
# Issue Report #

## Bug ##

Old Container Linux AMIs seem to have been re-published to AWS in `us-east-1` on July 3, 2019. This surfaced because of some tooling that picks the `most_recent` image in a particular channel/region, but I thought its worth asking about. Originally reported in [typhoon#522](https://github.com/poseidon/typhoon/issues/522#issue-475337088)

```
aws ec2 describe-images --output table --owners 595879546273 --filters "Name=name,Values=CoreOS-stable-*" "Name=virtualization-type,Values=hvm" "Name=architecture,Values=x86_64" --query 'sort_by(Images, &CreationDate)[].[ImageId,Name,CreationDate]' --region us-east-1
|  ami-016a8193f03cf4a79|  CoreOS-stable-2079.6.0-hvm   |  2019-06-11T09:23:11.000Z  |                                                                                                        
|  ami-00386353b49e325ba|  CoreOS-stable-2135.4.0-hvm   |  2019-06-25T00:04:57.000Z  |                                                                                                        
|  ami-02b51824b39a1d52a|  CoreOS-stable-2135.5.0-hvm   |  2019-07-01T21:04:41.000Z  |                                                                                                        
|  ami-03c90c77d3f1cbf4a|  CoreOS-stable-367.1.0-hvm    |  2019-07-02T22:24:47.000Z  |                                                                                                        
|  ami-09fbdf0319a23b1b1|  CoreOS-stable-367.1.1-hvm    |  2019-07-02T22:24:57.000Z  |                                                                                                        
|  ami-0683ef793613d2061|  CoreOS-stable-410.0.0-hvm    |  2019-07-02T22:55:00.000Z  |                                                                                                        
|  ami-0fadbb43a62d7c5b5|  CoreOS-stable-410.1.0-hvm    |  2019-07-02T22:55:17.000Z  |  
...
|  ami-075deac7b5ecf3241|  CoreOS-stable-1576.4.0-hvm   |  2019-07-03T10:02:07.000Z  |
```

These AMIs no longer seem to match the published AMI IDs on the CoreOS Releases website (e.g. https://stable.release.core-os.net/amd64-usr/1576.4.0/coreos_production_ami_hvm_us-east-1.txt compared to the last entry above).

Was this an intended re-publish that didn't reflect in site metadata? If so, any chance the latest image might be re-published to ensure it really is chronologically most recent (as in other regions I checked).

### Container Linux Version ###

AMIs from CoreOS-stable-367.1.0-hvm to CoreOS-stable-1576.4.0-hvm in `us-east-1`

### Environment ###

AWS

### Expected Behavior ###

AMI IDs match CoreOS Releases page

### Actual Behavior ###

On July 3, 2019 a re-publish with new images seems to have happened and the releases metadata wasn't updated.

### Reproduction Steps ###

```
aws ec2 describe-images --output table --owners 595879546273 --filters "Name=name,Values=CoreOS-stable-*" "Name=virtualization-type,Values=hvm" "Name=architecture,Values=x86_64" --query 'sort_by(Images, &CreationDate)[].[ImageId,Name,CreationDate]' --region us-east-1
```

**Comment by lucab** [comment]
I think this is a duplicate of https://github.com/coreos/bugs/issues/2600.

**Comment by dghubble** [comment]
Ah! Thanks Luca! Ok, so it was intentional and the mismatch is known out of support. In practice, sounds like alpha and beta in us-east-1 have a new most_recent and I'll just wait for the next release on stable and the ripple effect goes away.

Since that thread mentions the releases metadata won't be updated, I think I have no asks then. I'll close.
