### ISSUE TITLE
corrupt build source?

### ISSUE THREAD

**Issue by phylake** [coreos/bugs#2609]
# Issue Report #
I downloaded and unpacked the following sources from `toolbox` yesterday with no issue:

```
http://builds.developer.core-os.net/boards/amd64-usr/2135.6.0/pkgs/sys-kernel/coreos-kernel-4.19.56-r1.tbz2
http://builds.developer.core-os.net/boards/amd64-usr/2135.6.0/pkgs/sys-kernel/coreos-modules-4.19.56-r1.tbz2
http://builds.developer.core-os.net/boards/amd64-usr/2135.6.0/pkgs/sys-kernel/coreos-sources-4.19.56-r1.tbz2
```

Today I get this bzip error:

```
... lots of files
./usr/lib/debug/usr/lib/modules/4.19.56-coreos-r1/kernel/virt/lib/
./usr/lib/debug/usr/lib/modules/4.19.56-coreos-r1/kernel/virt/lib/irqbypass.ko
./usr/boot/

bzip2: (stdin): trailing garbage after EOF ignored
./usr/boot/config-4.19.56-coreos-r1
./usr/boot/config
```

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2135.6.0
VERSION_ID=2135.6.0
BUILD_ID=2019-07-30-0722
PRETTY_NAME="Container Linux by CoreOS 2135.6.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

AWS

### Expected Behavior ###

No bzip error

### Actual Behavior ###

bzip error

### Reproduction Steps ###

From inside `toolbox` with no `~/.toolboxrc`

```bash
dnf -y install wget bzip2 python2 @development-tools gcc-c++ elfutils-devel findutils
source /media/root/etc/os-release
UNAMER=`uname -r| sed 's/-coreos//'`
wget -N http://builds.developer.core-os.net/boards/amd64-usr/${VERSION}/pkgs/sys-kernel/coreos-{kernel,modules,sources}-${UNAMER}.tbz2
find . -maxdepth 1 -name 'coreos-*.tbz2' -exec tar --directory=/ -xvf '{}' \;
```

**Comment by ajeddeloh** [comment]
That's not a `.tar.bz2`; it's a gentoo binary package. It has the tar contents first then a trailer with metadata at the end. The `bzip2: (stdin): trailing garbage after EOF ignored` is from tar finding that header. It can safely be ignored. I'm not sure why this is just appearing now.

Is it actively failing or just emitting that warning? If it's the latter, I'd just ignore it.

If you want to strip the header, the gentoo `qtbz2` utility can do that.

**Comment by phylake** [comment]
It's actively failing. Do you know what package has `qtbz2`?

**Comment by ajeddeloh** [comment]
`app-portage/portage-utils`

**Comment by phylake** [comment]
Or is there an alternative file with just the tar contents?

**Comment by ajeddeloh** [comment]
I just re-read the bug; did this occur without upgrading (i.e. only thing that changed was time?)

**Comment by phylake** [comment]
Crazy right? Same exact commands as yesterday

**Comment by ajeddeloh** [comment]
If you have an old file still, can you compare them and ensure they are the same?

**Comment by phylake** [comment]
I wish I did so I could use them. Is there a way to see if these files have been modified on the server?

**Comment by ajeddeloh** [comment]
Just checked. They haven't been modified in any way. Are you sure this was working before and that tar is actually failing? I can untar the tbz2 on my current alpha just fine. I get the warning, but `tar xf <file>` works. Same for 2135.6.0. Both on aws.

**Comment by phylake** [comment]
Yeah I'm sure. I went back to the same SHA that I ran yesterday just to be double sure the CoreOS version didn't change or something. All that could have changed out-of-band is my `toolbox` since everything else is version pinned.

`curl http://builds.developer.core-os.net/boards/amd64-usr/2135.6.0/pkgs/sys-kernel/coreos-sources-4.19.56-r1.tbz2 | tar -xvj` works for you?

**Comment by ajeddeloh** [comment]
Works on the host and in toolbox.

**Comment by phylake** [comment]
It consistently fails for me in and out of `toolbox` with the last few lines of

```
./usr/src/linux-4.19.56-coreos-r1/virt/lib/irqbypass.c
./usr/src/linux-4.19.56-coreos-r1/MAINTAINERS
./usr/src/linux-4.19.56-coreos-r1/Makefile

bzip2: (stdin): trailing garbage after EOF ignored
```

```
[root@ip-10-10-13-58 ~]# tar --version
tar (GNU tar) 1.32
```

**Comment by phylake** [comment]
No idea. Thank you for the help though. What I need out of these files is there so I'm closing this
