### ISSUE TITLE
Default Max Open File too high?

### ISSUE THREAD

**Issue by mimmus** [coreos/bugs#2611]
Hi,
I'm having some issues with value of Max Open Files on CoreOS 2079.4.0:
`# sudo cat /proc/sys/fs/nr_open
`
1073741816

It is "too high" compared to Linux usual value (1048576 ) and it causes some troubles ("unable to allocate file descriptor table") to some Java applications, peraphs related to this:
[https://bugs.openjdk.java.net/browse/JDK-8150460](url)

I know that  this is not CoreOS specific nor Fedora specific. It is the new "Linux" default for all distributions using systemd (and not overriding the value). Here's the relevant change:
https://github.com/systemd/systemd/pull/10244

Is it definitely something that needs to be fixed in JDK?
Any simple workaround?

**Comment by lucab** [comment]
Thanks for the report! This was recently discussed on Fedora CoreOS mailing-list and we came to the conclusion that systemd should definitely be free to bump that limit.
OpenJDK behavior here seems to be buggy. To the best of my understanding, JDK9 behavior should already be fixed in this regard.

**Comment by mimmus** [comment]
I fully agree with rationale behind this decision and I will insist with app developers to fix from their side.
I reported it just for knowledge.

**Comment by lucab** [comment]
@mimmus for reference, did you check if JDK9 works for you? On which JDK were originally you experiencing this issue?

**Comment by mimmus** [comment]
I'm not able to test with JDK9: it is a "pre-packaged" app running on
Mesosphere DC/OS.
Surely now it uses JDK 1.8.0_192

Il giorno lun 2 set 2019 alle ore 11:46 Luca Bruno <notifications@github.com>
ha scritto:
