### ISSUE TITLE
Previuos version on reboot

### ISSUE THREAD

**Issue by aledbf** [coreos/bugs#262]
After the upgrade the node starts with the new CoreOS version but after a reboot the node starts with the previous version.
Environment: kvm, CoreOS version: 575.0.0 to 584.0.0
I can reproduce this with any node in the cluster.

There's only one detail: this was a manual update running `update_engine_client -update`

**Comment by crawford** [comment]
Just so I understand correctly:

1. running 575.0.0
2. `update_engine_client -update`
3. `reboot`
4. running 584.0.0
5. `reboot`
6. running 575.0.0

That would mean that the OS hasn't marked the new version as good (handled by /usr/sbin/coreos-setgoodroot) and it's rolling back to the previous version.

**Comment by aledbf** [comment]
> OS hasn't marked the new version as good

@crawford ok. How I can check if the upgrade was correct?

**Comment by marineam** [comment]
After booting a new version CoreOS will wait about 45 seconds to mark that version as successfully booted. So if you reboot again too quickly the bootloader will assume the new version failed and fall back to the previously successful version. Could that be the case here?

**Comment by aledbf** [comment]
@marineam no but I will try a new update without rebooting the node for at least a couple of minutes to check what you mention.

**Comment by aledbf** [comment]
@marineam I tried this:
1. manual update (update_engine_client -update)
2. reboot
3. 598.0.0 running
4. after 5 minutes I rebooted the node
5. 593.0.0 running

**Comment by marineam** [comment]
Could you post the log from update_engine during the time 598.0.0 was running? You can select the previous boot with something like: `journalctl -b -1 -u update-engine.service`

**Comment by aledbf** [comment]
@marineam my fault. The update-engine service is disabled using cloud-init so that's why the update never occurs after the reboot. If I enable the service the update to boot works just fine.

**Comment by marineam** [comment]
Ahh, ok. We recommend only masking locksmith if you want to avoid automatic reboots. It would be reasonable to pull "mark boot as successful" step into a different process but I don't have any plan to implement that right now.
