### ISSUE TITLE
How to use authenticated url to downoad file

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2626]
My ignition includes:
 - path: /etc/imageFactory/remediation.sh
      filesystem: root
      mode: 0644
      contents:
        remote:
          url: https://artifactory-XXXXXXX.com/artifactory/XXXXXXXX/coreos/remediation.sh

This url allows to download file with some token.
How can I pass that?

**Comment by ajeddeloh** [comment]
Ignition currently does not support authentication like that. There's also many variants of authentication, including https basic auth and a whole slew of variants using headers. This would be a feature request for Ignition, maybe file one there with details about what exactly should be implemented. Perhaps a generic way of adding headers?
