### ISSUE TITLE
wrong time for all of Brazil

### ISSUE THREAD

**Issue by thiago-scherrer** [coreos/bugs#2627]
# Issue Report #
Current president canceled daylight saving time for Brazil. Need update the **tzadata-2019b**
http://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/decreto/D9772.htm

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2247.5.0
VERSION_ID=2247.5.0
```

### Environment ###

```
Amazon Web Services (AWS) 
```

### Expected Behavior ###
```
$ zdump -v America/Sao_Paulo  | grep 2019
America/Sao_Paulo  Sun Feb 17 01:59:59 2019 UT = Sat Feb 16 23:59:59 2019 -02 isdst=1 gmtoff=-7200
America/Sao_Paulo  Sun Feb 17 02:00:00 2019 UT = Sat Feb 16 23:00:00 2019 -03 isdst=0 gmtoff=-10800
```

**Comment by bgilbert** [comment]
This should be fixed in alpha 2317.0.1, beta 2303.1.1, and stable 2247.6.0, due shortly.  Thanks for reporting.
