### ISSUE TITLE
How to add noexec flag to /tmp partition

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2629]
From df-Th,
![image](https://user-images.githubusercontent.com/8611615/68280698-11b20900-009c-11ea-9181-5b050c126c02.png)
we know that tmfs is mounted on /tmp

Also, from /proc/mounts  [tmpfs /tmp tmpfs rw,seclabel,nosuid,nodev 0 0], we know it has nosuid and nodev flags
I want to add noexec flag to it.
How can I do it either from Ignition or from any other method?

**Comment by bgilbert** [comment]
Use Ignition to add a drop-in for `tmp.mount` with contents like this:

```
[Mount]
Options=mode=1777,strictatime,nosuid,nodev,noexec
```

**Comment by alpana17** [comment]
oh
Thanks a lot

**Comment by alpana17** [comment]
Can you tell me, how can I add 'noexec' option to 'tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0' in /proc/mounts

**Comment by bgilbert** [comment]
Unlike `/tmp`, `/dev/shm` doesn't have a mount unit.  According to https://github.com/systemd/systemd/issues/8394#issuecomment-374698015, you'll need to add an `/etc/fstab` entry to override the mount options for `/dev/shm`.

**Comment by alpana17** [comment]
How to implement it in fstab?
Please share some document or example

**Comment by alpana17** [comment]
Is this ok?
/dev/shm    /dev/shm    tmpfs   noexec,nosuid,rw,nodev  0 0
