### ISSUE TITLE
Why is initrd-setup-root.service failing

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2631]
What can be the reason of 
![image](https://user-images.githubusercontent.com/8611615/68564628-2238f980-0477-11ea-9e9c-c4380a9636c2.png)

**Comment by ajeddeloh** [comment]
That's odd. If that's failing it shouldn't be possible to reach the real root where you're running those commands. Can you share the information that's in the bug template please, as well as if you're using Ignition or cloudinit and the (sanitized, don't post anything private) config you're using. Also can you post the output of `sudo journalctl -u initrd-setup-root`?
