### ISSUE TITLE
service created by ignition is not started on machine boot up

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2636]
I am passing following ignition file in User-data
{"ignition":{"config":{},"security":{"tls":{}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{"units":[{"contents":"[Unit]\nDescription=Implements Security\n[Service]\nType=oneshot\nExecStart=/bin/bash /etc/sssd_config.sh\nRemainAfterExit=false\n[Install]\nWantedBy=multi-user.target\n","enabled":true,"name":"conf_sssd.service"}]}}

But, when the EC2 instance is in running state and I login to machine, cmd 'systemctl status conf_sssd' returns 'Loaded: loaded (/etc/systemd/system/conf_sssd.service; disabled; vendor preset: enabled)'
snapshot for same is attached:
![image](https://user-images.githubusercontent.com/8611615/68846568-50c30880-06f3-11ea-8900-9290896cd421.png)

Why is it so? Why the service is not enabled when this has been mentioned in ignition?

**Comment by alpana17** [comment]
If I execute 'systemctl start conf_sssd', the service performs intended tasks and output is:
![image](https://user-images.githubusercontent.com/8611615/68846691-810aa700-06f3-11ea-8e27-6d3ddba819ba.png)

**Comment by crawford** [comment]
Have you tried the suggestions in the [documentation](https://coreos.com/ignition/docs/latest/getting-started.html#troubleshooting)?

**Comment by alpana17** [comment]
![image](https://user-images.githubusercontent.com/8611615/68859513-6b09e000-070d-11ea-8a60-c7b340b6b00b.png)
Logs show that the unit has been enabled
But it actually is not enabled "sssd_config"

**Comment by alpana17** [comment]
any update? any clue?
