### ISSUE TITLE
Parse audit logs from journalctl

### ISSUE THREAD

**Issue by Eshakk** [coreos/bugs#2638]
# Issue Report #

I'm able to capture file changes by writing a new rule:
```
new_user@17ed6f18d9dc4f8a94624b296cdc84d1 ~ $ sudo auditctl -l
Password: 
-w /home/new_user/test_change.txt -p rwxa -k test_change
new_user@17ed6f18d9dc4f8a94624b296cdc84d1 ~ $
```

The audit logs are being captured in journalctl but they are not in easily readable format:
```
Nov 18 19:55:36 17ed6f18d9dc4f8a94624b296cdc84d1 audit[31399]: SYSCALL arch=c000003e syscall=90 success=yes exit=0 a0=5566a517e480 a1=81a4 a2=0 a3=5566a518ec96 items=1 ppid=31322 pid=31399 auid=1000 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=pts1 ses=155 comm="vi" exe="/usr/bin/vim" subj=system_u:system_r:kernel_t:s0 key="test_change"
Nov 18 19:55:36 17ed6f18d9dc4f8a94624b296cdc84d1 audit: CWD cwd="/home/new_user"
Nov 18 19:55:36 17ed6f18d9dc4f8a94624b296cdc84d1 audit: PATH item=0 name="test_change.txt" inode=24077 dev=08:09 mode=0100644 ouid=1000 ogid=1000 rdev=00:00 obj=system_u:object_r:unlabeled_t:s0 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
Nov 18 19:55:36 17ed6f18d9dc4f8a94624b296cdc84d1 audit: PROCTITLE proctitle=766900746573745F6368616E67652E747874
```

Can someone please let me know how I can convert these messages into more easily readable format ?

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2191.5.0
VERSION_ID=2191.5.0
BUILD_ID=2019-09-04-0357
PRETTY_NAME="Container Linux by CoreOS 2191.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

**Comment by bgilbert** [comment]
Could you be more specific about the problem you're having?  They're key-value pairs; you should be able to process them with your favorite text processor.

**Comment by Eshakk** [comment]
@bgilbert How can I view audit logs ? In journalctl, the logs seems more cryptic and I'm not sure how to parse them. Could you please explain how key-value pairs can be extracted or how to view them ?

I'm using `journalctl _TRANSPORT=audit -b -r` to view audit event but unable to understand them.

**Comment by bgilbert** [comment]
We don't ship auditd, so those are the logs that are available.

I'm afraid we can't provide general advice on Unix tools here.  `sed` and `awk` may be of some help, or you can process them with the scripting language of your choice.

I'll close this.  If you believe you're seeing a bug in CoreOS Container Linux, please feel free to reopen with more details.

**Comment by Eshakk** [comment]
Thanks for the info. I thought there might be something alternative to `aureport` or `ausearch` to parse the logs. Didn't know we have to manually read the audit message and parse them.
