### ISSUE TITLE
Core user password is last changed in 2013

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2639]
Why is chage command showing that core used password was last changed in july 2013?
![image (2)](https://user-images.githubusercontent.com/8611615/69136150-58622300-0ae0-11ea-8564-7f8929f5e670.png)

**Comment by bgilbert** [comment]
Looks like it's because of the `15887` [here](https://github.com/coreos/baselayout/blob/81d44f654441ac7243ccb4e911176b146a4e0fff/Makefile#L14).  Why does it matter?  The `core` user doesn't have a valid password by default.

**Comment by alpana17** [comment]
True
