### ISSUE TITLE
How can I forward /var/log/journal/* logs using Splunk universal forwarder

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2641]
My inputs.conf at /opt/splunkforwarder/etc/system/local/inputs.conf looks like
[monitor:///var/log/journal/dcf370a7752c4b14b6f7be387fabdf5f/system.journal]
_TCP_ROUTING = IHF-ext_encrypted
ignoreOlderThan = 7d
index = os
disabled = 0
sourcetype = syslog

But I can not see logs in splunk

**Comment by ajeddeloh** [comment]
We don't know about splunk, as it's not part of the OS; this isn't an OS bug. I recommend asking splunk.
