### ISSUE TITLE
Does any other property matters if REBOOT_STRATEGY is set to off

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2650]
In file /etc/coreos/update.conf
 I have set REBOOT_STRATEGY=off

then adding any other key-value pair like 
     GROUP=stable 
     OR 
     SERVER=https://public.update.core-os.net/v1/update/ 
matters????

**Comment by lucab** [comment]
Yes, you can set all those keys separately.

[update-engine](https://github.com/coreos/update_engine) uses `GROUP` and `SERVER` to detect and fetch new updates.
[lockmisth](https://github.com/coreos/locksmith) uses `REBOOT_STRATEGY` to decide when to reboot.

For further details, see https://coreos.com/os/docs/latest/update-strategies.html.
