### ISSUE TITLE
Core OS server Disc is almost full 

### ISSUE THREAD

**Issue by Sarah-Qiao** [coreos/bugs#2651]
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2247.3.0
VERSION_ID=2247.3.0
BUILD_ID=2019-09-24-0005
PRETTY_NAME="Container Linux by CoreOS 2247.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

cloud provider--AWS instance 

### Expected Behavior ###
 resize partition without reboot 
### Reproduction Steps ###

  1. ...core@buildtools ~ $ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0   60G  0 disk
|-xvda1 202:1    0  128M  0 part /boot
|-xvda2 202:2    0    2M  0 part
|-xvda3 202:3    0    1G  0 part /usr
|-xvda4 202:4    0    1G  0 part
|-xvda6 202:6    0  128M  0 part /usr/share/oem
|-xvda7 202:7    0   64M  0 part
`-xvda9 202:9    0 27.7G  0 part /
xvdh    202:112  0  500G  0 disk /opt/data
  2. ...sudo growpart /dev/xvda 2
sudo: growpart: command not found

**Comment by bgilbert** [comment]
What are you trying to accomplish?  It appears that you're trying to extend the BIOS Boot Partition, which is not a filesystem and doesn't need to be larger than 2 MiB.

**Comment by Sarah-Qiao** [comment]
@bgilbert  thanks for your feedback,t I'm trying to extend File system space of partition 
/dev/xvda3 
Based on below information, you will see available disk space for /dev/xvda3 is around 8% ,I'm a little worried about this partition will be occupied someday.
````
core@buildtools ~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.4G     0  7.4G   0% /dev
tmpfs           7.4G     0  7.4G   0% /dev/shm
tmpfs           7.4G  1.2M  7.4G   1% /run
tmpfs           7.4G     0  7.4G   0% /sys/fs/cgroup
/dev/xvda9       27G   24G  2.1G  92% /
/dev/xvda3      985M  854M   80M  92% /usr
none            7.4G  200M  7.2G   3% /run/torcx/unpack
tmpfs           7.4G     0  7.4G   0% /media
tmpfs           7.4G  8.0K  7.4G   1% /tmp
/dev/xvda6      108M   64K   99M   1% /usr/share/oem
/dev/xvda1      128M  100M   29M  78% /boot
/dev/xvdh       493G  215G  253G  46% /opt/data
overlay          27G   24G  2.1G  92% /var/lib/rkt/pods/run/8fa204bb-ce8a-4ea1-ad74-fc2dcb0f7a1f/stage1/rootfs
overlay          27G   24G  2.1G  92% /var/lib/rkt/pods/run/e932ac53-ef59-4296-8dc0-d53f29e3bf9e/stage1/rootfs
tmpfs           1.5G     0  1.5G   0% /run/user/500

**Comment by bgilbert** [comment]
The `/usr` partition is managed by the operating system developers.  We ship the entire filesystem image with every update, so it can't actually fill up.  There's no need to resize the partition.

**Comment by Sarah-Qiao** [comment]
How about the other partitions,for instance the root folder and overlay part ? As you might see the usage is also 92% as well? should we take some actions to resize them or keep is as -is ? Thanks for your suggestions in advance.

**Comment by bgilbert** [comment]
Sure, you can resize the root partition if you'd like.  The overlay mounts are just showing the size of the root partition which is backing them.

**Comment by Sarah-Qiao** [comment]
actually, i'd like to resize the root partition without reboot? is it possible? after a quick verification, we have to reboot coreos servers to make the new disc space take effective. could you please check this point as well ?
