### ISSUE TITLE
How can Ignition be executed?

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2652]
I want to execute Ignition while launching an AWS instance. The Ignition is of 140840 bytes size.
One way to execute Ignition is to pass in userdata.

But userdata has a limit of 2048 bytes.

How can I execute this Ignition?

**Comment by bgilbert** [comment]
Host your large Ignition config on a web server.  In userdata, pass a stub config which uses the [`ignition.config.append`](https://github.com/coreos/ignition/blob/spec2x/doc/configuration-v2_3.md) directive to append the large config.

**Comment by alpana17** [comment]
If I create Ignition.yaml as
ignition:
  version: 2.2.0,
  config:
    replace: "https://xxxxx.s3.amazonaws.com/ignition.json?AWSAccessKeyId=AAAAAA&Signature=ewrewrerwerwerwrwrw&Expires=12345678"

and run ./ct-v0.9.0 < ignition_small_new.yaml
It gives error:-
![image](https://user-images.githubusercontent.com/8611615/72716133-b7531f80-3b97-11ea-95a7-784134ce0237.png)
