### ISSUE TITLE
ct tool gives error

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2653]
If I create Ignition.yaml as
![image](https://user-images.githubusercontent.com/8611615/72716540-61cb4280-3b98-11ea-9b3f-6254720afc79.png)

and run ./ct-v0.9.0 < ignition_small_new.yaml
It gives error:-
![image](https://user-images.githubusercontent.com/8611615/72716551-67c12380-3b98-11ea-8bdd-b283ba49436b.png)

**Comment by bgilbert** [comment]
You want `ignition.config.replace.source`, not `ignition.config.replace`.

**Comment by alpana17** [comment]
oh
yes it worked.
Thanks a lot.
