### ISSUE TITLE
Missing Release Notes for 2512.2.0 ?

### ISSUE THREAD

**Issue by vpnachev** [coreos/bugs#2657]
# Issue Report #

Recently [2513.0.0](https://coreos.com/releases/#2513.0.0) and [2512.1.0](https://coreos.com/releases/#2512.1.0) were released. There are a lot of CVEs fixed with these alpha and beta versions. I am curious whether the stable version [2512.2.0](https://coreos.com/releases/#2512.2.0) resolves the same CVEs?  I see also another stable version is coming https://github.com/coreos/manifest/releases/tag/v2512.3.0, but it again has no release note about any fixed CVE or bug.

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Reproduction Steps ###

  1. ...
  2. ...

**Comment by vpnachev** [comment]
cc @bgilbert

**Comment by bgilbert** [comment]
Stable 2512.2.0 is a promotion of beta 2512.1.0 (they share the same major version) so it includes all of the latter's changes.  In fact, all three channels are now shipping the same code.

For more on deciphering Container Linux release notes, see #2134.

**Comment by vpnachev** [comment]
Thank you for the clarification!
