### ISSUE TITLE
Error 503: fleet server unable to communicate with etcd

### ISSUE THREAD

**Issue by Sarah-Qiao** [coreos/bugs#2658]
# Issue Report #
run command fleetctl list-units got below errors 

core@ip-192-168-192-187 ~ $ fleetctl list-units
Error retrieving list of units from repository: googleapi: Error 503: fleet server unable to communicate with etcd

## Bug ##
N/A
### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1548.2.0
VERSION_ID=1548.2.0
BUILD_ID=2017-10-12-0514
PRETTY_NAME="Container Linux by CoreOS 1548.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Expected Behavior ###
The core OS cluster is healthy 
### Actual Behavior ###
failed to reach the peerURL 

### Reproduction Steps ###

  1.fleetctl list-machines
Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd

**Comment by lucab** [comment]
`fleet` has been deprecated and removed from Container Linux more than two years ago: https://coreos.com/blog/migrating-from-fleet-to-kubernetes.html
Additionally, Container Linux reached End-Of-Life last month: http://coreos.com/os/eol/
At this point, we urge any fleet and CL users to migrate away from those.

While we have no way to investigate and update components that are not anymore maintained, you can try to debug this by passing `--debug=true` to `fleetctl`.
