### ISSUE TITLE
Rocket not in CoreOS

### ISSUE THREAD

**Issue by philips** [coreos/bugs#266]
_From @blakelapierre on February 9, 2015 3:18_

Not sure if this should go here or in another repo ([manifest](https://github.com/coreos/manifest) maybe?)

I can see not wanting to do this if there's no way to withhold it from being automatically promoted up into the beta and stable channels, but...

It would be nice to have this in the images that are available on the cloud platforms. As-is, it looks like you get to write a custom install step (which will eventually need to be removed) to be able to use this anywhere.

Confirmed this on a GCE instance running 584.0.0

_Copied from original issue: coreos/rocket#507_

**Comment by marineam** [comment]
@crawford fyi, I'll take this
