### ISSUE TITLE
CoreOS Boot failure on Dell C6525 server

### ISSUE THREAD

**Issue by AvRajath** [coreos/bugs#2660]
# Issue Report #
Added a Virtual CD/DVD using iDRAC console. And uploaded the RHCOS_4.4.3.iso image file to the virtual media. after editing and adding the required configuration for OpenShift Deployment. I have been observing the below error.
## Bug ##
![image](https://user-images.githubusercontent.com/54664782/94311814-7f5b7200-ff99-11ea-8ba9-db25a30139fd.png)

### Container Linux Version ###
4.4.3
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
Using Dell C6525 Server

### Expected Behavior ###
Expected to boot into RHCOS with its image_url
### Actual Behavior ###
Fails boot
### Reproduction Steps ###

  1. Upload the .iso file to virtual media
  2. Press E to make changes and add the below content
coreos.inst.install_dev=sda coreos.inst.image_url=http://192.168.22.1:8080/ocp4/rhcos coreos.inst.ignition_url=http://192.168.22.1:8080/ocp4/master.ign

**Comment by bgilbert** [comment]
This issue tracker is for CoreOS Container Linux, not Red Hat CoreOS.  For help with Red Hat CoreOS, please contact your OpenShift support channel.
