### ISSUE TITLE
cloud-config does not substitute $private_ipv4 and $public_ipv4 in CloudStack

### ISSUE THREAD

**Issue by mozg31337** [coreos/bugs#272]
The use of $private_ipv4 and $public_ipv4 in cloudstack does not work. The /etc/environment is actually set correctly, but using something like in cloud-config.yml does not work:

      addr: $private_ipv4:4001
      peer-addr: $private_ipv4:7001

**Comment by crawford** [comment]
Are you providing your config via the CloudStack metadata service? Can you show your full, sanitized config? Can you attach the output of `journalctl --boot cloudstack-cloudinit.service`?

**Comment by larstobi** [comment]
I just checked, and $private_ipv4 works fine with CloudStack.
