### ISSUE TITLE
Systemd getting started fails

### ISSUE THREAD

**Issue by robszumski** [coreos/bugs#277]
_Originally posted by [lethjakman](https://github.com/lethjakman) at https://github.com/coreos/docs/issues/439_

Hey,

I've noticed that if you follow the "Getting Started with systemd" tutorial your docker container will fail to start every time. It seems that the "docker pull busybox" is happening too quickly and returning an error like this:

Feb 22 22:48:20 general docker[628]: time="2015-02-22T22:48:20Z" level="fatal" msg="Get https://index.docker.io/v1/repositories/library/busybox/images: dial tcp: lookup index.docker.io: connection refused"

I have no clue what to do to fix this. I've tried things like "After=network-online.target" but nothing seems to allow a pull. Any ideas what this should really look like? Thank you.

**Comment by lethjakman** [comment]
I have an idea that this might be related to digital oceans VM service, but I can't confirm this.
