### ISSUE TITLE
A (secure) cross-origin way to retrieve current Alpha, Beta, Stable release version numbers 

### ISSUE THREAD

**Issue by blakelapierre** [coreos/bugs#278]
I asked in IRC if there was an API to get the current release version for the three CoreOS channels. Rob pointed to:

    http://alpha.release.core-os.net/amd64-usr/current/version.txt
    http://beta.release.core-os.net/amd64-usr/current/version.txt
    http://stable.release.core-os.net/amd64-usr/current/version.txt

This would work, but the `Access-Control-Allow-Origin: *` header is not sent, so the data cannot be used by a website on a different domain. Can the header be sent for those files, or, is there another way to retrieve the current version numbers from a browser context?

An https endpoint would be preferable so that it can be accessed by an https site without an ugly warning or straight up block.

**Comment by AntonioMeireles** [comment]
@blakelapierre see some of the shell functions [here](https://github.com/AntonioMeireles/coreos-packer/blob/master/releaser). you should find there all the machinery you need, i suppose.
