### ISSUE TITLE
networkd wedges down interfaces in 'configuring' state, broken between 215 and 218.

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#279]
_From @tligda on February 25, 2015 22:0_

I'm having an issue where I use NFS mounts handled by systemd and they are not mounting. The issue is present in 557.2.0. The issue is not present in 522.5.0.

I have the following user_data file:

```
#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/*****
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: *****:4001
    peer-addr: *****:7001
  fleet:
    metadata: region=*****
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: rpcbind.service
      enable: true
      command: start
    - name: rpc-statd.service
      enable: true
      command: start
    - name: 00-eno1.network
      runtime: true
      content: |
        [Match]
        Name=eno1

        [Network]
        DNS=*****
        DNS=*****
        Domains=*****.*****
        Address=*****/23
        Gateway=*****
    - name: *****-*****.mount
      command: start
      content: |
        [Unit]
        Description=/*****/*****
        After=network-online.target 
        Requires=network-online.target
        After=rpcbind.service
        Requires=rpcbind.service
        After=rpc-statd.service
        Requires=rpc-statd.service

        [Mount]
        What=*****:/*****
        Where=/*****/*****
        Type=nfs
        Options=defaults,noexec
    - name: settimezone.service
      command: start
      content: |
        [Unit]
        Description=Set the timezone

        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone America/Los_Angeles
        RemainAfterExit=yes
        Type=oneshot
ssh_authorized_keys:
  - *****
  - *****
hostname: *****
```

I spoke to a few people on IRC chat and we couldn't figure out where the failure was.

_Copied from original issue: coreos/coreos-cloudinit#322_

**Comment by crawford** [comment]
552.5.0 is not a release. Did you mean 522.5.0? Both 557.2.0 and 522.5.0 use coreos-cloudinit 1.1.0, so I don't think this is an issue with cloudinit specifically.

Let me know if I was correct about my assumption of the version number.

**Comment by crawford** [comment]
_From @tligda on February 25, 2015 23:13_

@crawford You are entirely correct. I edited the text and the title.

**Comment by crawford** [comment]
_From @tligda on February 25, 2015 23:14_

@crawford I didn't realize the coreos-cloudinit version is the same between the two. Can you point me in the direction of where to try next?

**Comment by crawford** [comment]
I'll move this bug over to our general bug tracker and I can start to dig into it.

**Comment by crawford** [comment]
For reference:
522.5.0: systemd 215
557.2.0: systemd 218

**Comment by crawford** [comment]
@tligda is there anything in the journal for `*****-*****.mount`?

**Comment by tligda** [comment]
All that the journal shows is the following:

```
Feb 25 10:21:13 ***** systemd[1]: Mounting /*****/*****...
```

**Comment by tligda** [comment]
I should add that if I manually mount the NFS export in 557.2.0, it works properly. Also, when I do the manual mount, the *****-*****.mount status goes to "active".

**Comment by crawford** [comment]
What command are you using to manually mount?

**Comment by tligda** [comment]
```sudo mount *****:/*****/***** /*****/*****```

**Comment by tligda** [comment]
Upon further investigation, I am seeing the "systemd-networkd-wait-online.service", uh, service hanging and preventing the .mount from occurring. Without the .mount configured, everything seems to come up properly (and the mount does not, which is expected). With the .mount configured, the "systemd-networkd-wait-online.service" starts and never exits.

I can manually kill the "systemd-networkd-wait-online.service" service and everything proceeds fine. I'm no expert, but I believe this is because the unit file defines the services as a oneshot.

**Comment by tligda** [comment]
When I enter the following command:

```
sudo /usr/lib/systemd/systemd-networkd-wait-online
```

I never get a prompt back. It doesn't exit.

I see this behavior in 557.2.0 and 584.0.0. When you do the same command in 522.5.0, it exits normally and quickly.

**Comment by crawford** [comment]
What is the output of `networkctl list`? Are you using a cloud-provider to run this (and if so, which one) or is this bare metal?

**Comment by tligda** [comment]
I'm running on bare metal.
```
core@localhost ~ $ networkctl
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     configured
  2 eno1             ether              routable    configured
  3 eno2             ether              no-carrier  configuring

3 links listed.
core@localhost ~ $ 
```

**Comment by tligda** [comment]
As seen in my user_data file above, I have a .network file for eno1, but none for eno2.

**Comment by tligda** [comment]
When I configure eno2 with a static IP address (not a real address and no cable connected), then it seems the "systemd-networkd-wait-online.service" service does work properly.

```
core@localhost ~ $ networkctl
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     configured
  2 eno1             ether              routable    configured
  3 eno2             ether              no-carrier  configured

3 links listed.
```

If I setup eno2 with DHCP, it doesn't work.

**Comment by crawford** [comment]
You can tell systemd-networkd-wait-online.service to only watch eno1 with:

```yaml
#cloud-config 
coreos: 
  units: 
    - name: systemd-networkd-wait-online.service 
      drop-ins: 
        - name: 50-interface.conf 
          content: | 
            [Service] 
            ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --interface=enp1s0f0 
```

**Comment by tligda** [comment]
This doesn't seem to do the trick. I tried the following command:

```
/usr/lib/systemd/systemd-networkd-wait-online --interface=eno1
```

I got the following:

```
core@localhost ~ $ /usr/lib/systemd/systemd-networkd-wait-online --interface=eno1
ignore irrelevant link: lo

```

Then the same hang as before.

**Comment by crawford** [comment]
`networkctl` shows eno1 as routable and configured?

**Comment by tligda** [comment]
Sure does.

```
core@localhost ~ $ networkctl
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     configured
  2 eno1             ether              routable    configured
  3 eno2             ether              no-carrier  configuring

3 links listed.
core@localhost ~ $ 
```

**Comment by crawford** [comment]
Can you try one more command? `/usr/lib/systemd/systemd-networkd-wait-online --ignore=eno2`

**Comment by tligda** [comment]
```
core@localhost ~ $ /usr/lib/systemd/systemd-networkd-wait-online --ignore=eno2
/usr/lib/systemd/systemd-networkd-wait-online: unrecognized option '--ignore=eno2'
core@localhost ~ $ cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=584.0.0
VERSION_ID=584.0.0
BUILD_ID=
PRETTY_NAME="CoreOS 584.0.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
core@localhost ~ $ 
```

**Comment by crawford** [comment]
Darn, that was added in systemd 219.

**Comment by marineam** [comment]
Ok, so it is `3 eno2             ether              no-carrier  configuring` that is wedging it. Not sure how networkd got stuck in that state yet though.

**Comment by tligda** [comment]
It looks that way. Bad regression. Any chance of getting this use case added in to regression testing?

**Comment by marineam** [comment]
Not sure how to reproduce it yet though. Reading through the code but given that the link has `no-carrier` it is really odd that something is kicking it into one of the configuring states:

```c
        [LINK_STATE_ENSLAVING] = "configuring",
        [LINK_STATE_SETTING_ADDRESSES] = "configuring",
        [LINK_STATE_SETTING_ROUTES] = "configuring",
```

**Comment by tligda** [comment]
The way I reproduce it is to use a bare metal machine with two NICs. I configure one in the cloud-config and not the other. I also connect the configured NIC to a good network (this may not be necessary to reproduce). Then run the command for systemd-networkd-wait-online.

I'm not sure what platform you use for regression testing, so this may or may not be helpful.

**Comment by marineam** [comment]
Oop, nevermind. I thought I had never seen this before but then poof, spotted it on our office router:

```
  3 enp5s0           ether              no-carrier  configuring
```

So if it is that simple fixing this should be easier than I had assumed.

**Comment by tligda** [comment]
It looks like the pull request has been completed. Can this be integrated into a release based on the latest Stable? Something like 607.1.0?

**Comment by marineam** [comment]
@tligda off the top of my head I don't know for sure, if it looks good in the next alpha it could be backported but whether that is worth the time depends on how the rest of the release schedule lines up. Will add a note here if that happens.

**Comment by eatnumber1** [comment]
Can we either leave this open, or promise to get a ping on this bug when the fix is pushed to stable?

**Comment by crawford** [comment]
@eatnumber1 I'll leave a note here once it's in stable (currently scheduled for Apr-14).

**Comment by crawford** [comment]
The fix for this bug is currently rolling out to the stable channel.

**Comment by rosskukulinski** [comment]
Awesome, thanks @crawford
