### ISSUE TITLE
networkd attempts to configure flannel interfaces

### ISSUE THREAD

**Issue by eyakubovich** [coreos/bugs#280]
flannel handles configuring its interfaces so networkd needs to be told to ignore them.

Reported in https://github.com/coreos/flannel/issues/132

**Comment by marineam** [comment]
Just need to add a network unit similar to the one we provide for docker: https://github.com/coreos/coreos-overlay/blob/master/app-emulation/docker/files/50-docker-veth.network

**Comment by crawford** [comment]
@eyakubovich this isn't still an issue is it?

**Comment by eyakubovich** [comment]
No, it's fixed in https://github.com/coreos/coreos-overlay/commit/6a8476537a101958495bfeda3ceeae10f01fc2c5
