### ISSUE TITLE
bcrypt for /etc/shadow hashes

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#282]
_From @michaelsbradleyjr on June 17, 2014 17:41_

**Feature request:** support bcrypt hashes in `/etc/shadow`.

For conveniently generating random password and bcrypt-hash pairs on the command line (so as to use the latter member to populate, say, a `cloud-config` file), I've put together a little script: [passnhash.bash](https://gist.github.com/michaelsbradleyjr/dec5d69af50832166274).  There may be a better way, but it wasn't apparent to me what that was on my macbook pro.

However, after implementing that helper, I came to realize that CoreOS can't, at present, employ bcrypt hashing with respect to `/etc/shadow`.

_Copied from original issue: coreos/manifest#38_

**Comment by marineam** [comment]
For reference, upstream request from glibc. It seems unlikely they will bother revisiting it and adding bcrypt. https://sourceware.org/bugzilla/show_bug.cgi?id=13286

I doubt there is a strong reason for us to deviate from upstream glibc on this.

**Comment by michaelsbradleyjr** [comment]
For the record, there is a public domain implementation named [crypt_blowfish](http://www.openwall.com/crypt/) which can hook to glibc.

Also, Openwall's [Services](http://www.openwall.com/services/) page indicates they are willing in some cases to contribute effort toward third-party free software projects. Given the nature of CoreOS, they might be more than happy to help integrate it with [crypt_blowfish](http://www.openwall.com/crypt/).
