### ISSUE TITLE
systemd-networkd-wait-online hanging post 522.0.0

### ISSUE THREAD

**Issue by rosskukulinski** [coreos/bugs#283]
We're seeing a similar problem to [this thread](https://groups.google.com/forum/#!searchin/coreos-dev/systemd-networkd-wait-online.service$20/coreos-dev/RKDzKAAQri0/etzHVcelmNsJ).

We just updated our 5.22.0 staging cluster to 557.2.0 and we're seeing that systemd-networkd-wait-online.service is hanging on 'activating'.

**Comment by rosskukulinski** [comment]
cc: @jareddlc

**Comment by marineam** [comment]
Same issue as https://github.com/coreos/bugs/issues/279
