### ISSUE TITLE
Docker w/overlayfs and hard links

### ISSUE THREAD

**Issue by porjo** [coreos/bugs#285]
Not sure if this is a bug or just the way overlayfs works, but I'm getting an error `gzip: staticserve.gz has 4 other links -- unchanged` when attempting to gunzip a file from within my Dockerfile e.g.

```
Step 7 : RUN gunzip staticserve.gz
 ---> Running in af5fe414dfb4
gzip: staticserve.gz has 2 other links -- unchanged
INFO[0014] The command [/bin/sh -c gunzip staticserve.gz] returned a non-zero code: 2 
```

I've recently migrated from btrfs to ext4. The same Dockerfile had no problem on btrfs. I've worked around this just by removing the gunzip step and doing it another way, but thought I'd raise the issue for other people's benefit.

**Comment by porjo** [comment]
I'm also seeing the same issue as report in https://github.com/docker/docker/issues/10180 which may be related

**Comment by krishnasrinivas** [comment]
Looks like gunzip does not like gz files to have hard links. You can just use 'gunzip -f staticserve.gz' as a workaround.

**Comment by scole-scea** [comment]
postfix also complains about too many hard links to {{/etc/mailname}}, when you run it inside a container. (I always thought this was a docker thing, not a CoreOS thing, though.)

**Comment by batmat** [comment]
For the record, just hit the exact same failure with `bunzip2 somefile.bz2`.

**Comment by mischief** [comment]
any chance you can retry this on coreos alpha 991.0.0? there's been a few commits to the overlay driver in the kernel from upstream.

**Comment by emmetog** [comment]
I have the same problem as https://github.com/coreos/bugs/issues/474 (which was closed as dup of this one) on docker 1.12 on ubuntu. Pulling results in this error:
```
$ sudo docker pull <<private-registry>>/<<image-name>>
master: Pulling from <<image-name>>
a3ed95caeb02: Already exists 
66b316858002: Already exists 
8ecbf2c4007d: Pull complete 
b05256b13203: Pull complete 
6de542492b10: Pull complete 
4180c6348d72: Pull complete 
8d2cb72cb40d: Pull complete 
995acc262064: Pull complete 
97bac58a262c: Pull complete 
afbe6282cbe1: Pull complete 
65a6eccc989d: Pull complete 
d9360b87db33: Pull complete 
2a914c24f5c8: Pull complete 
0f3dc4507b38: Pull complete 
c3f8c8fd157b: Pull complete 
bde686c6c960: Pull complete 
678f79a2c4e3: Pull complete 
fd030f4e14b1: Pull complete 
438c4b03a9b8: Pull complete 
10f4c08cef7a: Pull complete 
e825f3c6a33e: Pull complete 
f3281c279591: Pull complete 
6660bc31a391: Pull complete 
e6c9d9af2b19: Extracting [==================================================>] 10.28 kB/10.28 kB
ab9cc5a0e258: Download complete 
failed to register layer: link /var/lib/docker/overlay/8ae625c87d474ebb050d768f139dc8da0d5ed7630c80b9cbcd2e21ccab6b7120/root/var/lib/yum/yumdb/i/1eb801f7335c6973d5921a6f97e7b8c24e3c3c76-info-4.13a-8.el6-x86_64/checksum_type /var/lib/docker/overlay/4e847eb7060976e00126b0ab0992a38fef63fedaec6cf805528805e62bc53e43/tmproot307695192/var/lib/yum/yumdb/i/1eb801f7335c6973d5921a6f97e7b8c24e3c3c76-info-4.13a-8.el6-x86_64/checksum_type: too many links
```
The server is in swarm mode with one node, itself as manager.
```
$ sudo docker info
Containers: 15
 Running: 13
 Paused: 0
 Stopped: 2
Images: 21
Server Version: 1.12.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: active
 NodeID: 0xrh150xndcqwsp6yvwod1gok
 Is Manager: true
 ClusterID: cxqmtq8txbcu24llbwx7l2ncb
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 10.0.0.200
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.675 GiB
Name: <<redacted>>
ID: ZURF:MPZQ:GVJA:KS7G:UZAB:FSYT:X7YT:ESHV:4Y3V:TUKS:OO2B:PYKM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by vcaputo** [comment]
From https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/
```
The overlay driver only works with two layers. This means that multi-layered 
images cannot be implemented as multiple OverlayFS layers. Instead, each image
layer is implemented as its own directory under /var/lib/docker/overlay. Hard
links are then used as a space-efficient way to reference data shared with 
lower layers.
```

Hence this is not an overlayfs problem, but a docker (when run using overlayfs) problem.  I'm not sure what the best approach to working around docker's limitation here would be, you could try using XFS which uses a more capacious type for the inode refcount, or btrfs.

Docker should really be handling `EMLINK` properly by duplicating the file when its hard-link optimization is unavailable, if it must continue using hard-links for this purpose.

**Comment by crawford** [comment]
@vcaputo do you know if Docker's `overlay2` driver behaves properly?

**Comment by vcaputo** [comment]
@crawford If you're referring specifically to the hard-link `EMLINK` error issue, it appears that `overlay2` should improve that situation judging from the documentation, but I have not played with it.

**Comment by pgburt** [comment]
A user on the Google Group ([link](https://groups.google.com/d/topic/coreos-user/TlXCRPkfgPo/discussion)) writes:
> what is the state of overlay2 in CoreOS?
> We are experiencing "Too may links" errors since ancient days and we are hoping that the definitive solution will be overlay2.

**Comment by mimmus** [comment]
The user above is me 👍

In addition to gunzip, another source of problem is Red Hat's yum database that is heavily based on hardlinks.
Actually, we are forced to aggressively clean unused Docker images to alleviate the problem.

**Comment by euank** [comment]
The overlay2 driver is available for the docker version each Container Linux channel ships.

An ignition config of `{"ignition":{"version":"2.0.0","config":{}},"systemd":{"units":[{"name":"docker.service","dropins":[{"name":"10-overlay2.conf","contents":"[Service]\nEnvironment=DOCKER_OPTS=--storage-driver=overlay2"}]}]}}`

can be used to configure docker to use it.

If you're able to see if it helps with the issues reported here, that info would be appreciated!

**Comment by mimmus** [comment]
After more than 1 year :-), we just found the time to try overlay2 on a server where the infamous "too many links" is frequent!

**Comment by svenwltr** [comment]
Did anyone try to use overlay2, yet? Does it solve the problem?

**Comment by mimmus** [comment]
After two months of use, problem not seen anymore!

**Comment by bgilbert** [comment]
overlay2 is the default on new Container Linux installs, and has been for a while now.  I'll go ahead and close.  Please reopen if you're still seeing this problem.

**Comment by svenwltr** [comment]
FTR for future readers: This statement confused me a bit, since we are on the most recent Container Linux version, but overlay was still the default. This is probably, because we downgraded Docker to 1.12, because Kubernetes is not compatible with the default one provided by Container Linux.
