### ISSUE TITLE
Possibility on setting GPT partition as bootable?

### ISSUE THREAD

**Issue by savingschampion** [coreos/bugs#286]
I'm trying to install CoreOS on a Kimsufi machine, however their machines require the GPT partition to be marked as bootable (which i did via cfdisk)

However whenever there is an update and the cluster reboots, the CoreOS update attempts to reboot into the other install, without the bootable GPT partition, and fails to boot.

**Comment by marineam** [comment]
Could you explain what you mean by 'bootable GPT partition'? By default we currently ship a hybrid bootloader that provides both a MBR and GPT partition table. The MBR includes the EFI System partition and a protective partition for the rest of the GPT partitions disk. Are you needing to set the boot flag on the EFI system partition or the protective partition?

It is also possible to switch from a hybrid MBR to a plain protective MBR which can resolve boot issues with some firmware. In coreos run: `cgpt add -B 0 -i 1 /dev/sda`

**Comment by savingschampion** [comment]
If I open cfdisk, there are two partitions listed and one marked as free space, the first one needs to be listed as bootable for the machiens to boot correctly.

**Comment by marineam** [comment]
Ok.. that's a pretty odd expectation for the firmware to have. Could you try the cgpt command I noted above to switch from a hybrid MBR to a protective MBR? Also the version of cfdisk you are using is only reporting the MBR partitions, if you want to see the main GPT partition table you can use cgdisk.

**Comment by savingschampion** [comment]
This works, is there a way to perform this step before installation reboot? As I'm using bare metal this would be really handy

**Comment by crawford** [comment]
@marineam can you document that command?

@savingschampion you can run this once as part of your cloud-config or Ignition config.
