### ISSUE TITLE
systemd-coredump: Failed to get COMM, falling back to the command line.

### ISSUE THREAD

**Issue by IbnSaeed** [coreos/bugs#288]
Hello

I am running Coreos beta VERSION=584.0.0

I get the following error when i use a drush command inside a running docker container.

[ 1893.297925] docker0: port 4(veth9ad9f9f) entered disabled state
[ 1893.299041] device veth9ad9f9f left promiscuous mode
[ 1893.300611] docker0: port 4(veth9ad9f9f) entered disabled state
[ 1897.245112] device veth13e3506 entered promiscuous mode
[ 1897.250081] IPv6: ADDRCONF(NETDEV_UP): veth13e3506: link is not ready
[ 1897.414930] eth0: renamed from veth4ff9c63
[ 1897.432637] IPv6: ADDRCONF(NETDEV_CHANGE): veth13e3506: link becomes ready
[ 1897.433879] docker0: port 4(veth13e3506) entered forwarding state
[ 1897.434856] docker0: port 4(veth13e3506) entered forwarding state
[ 1912.481114] docker0: port 4(veth13e3506) entered forwarding state
[ 2213.992984] systemd-coredump[2517]: Failed to get COMM, falling back to the command line.
[ 2213.994054] systemd-coredump[2517]: Failed to get EXE.
[ 2221.378935] systemd-coredump[2530]: Failed to get COMM, falling back to the command line.
[ 2221.380601] systemd-coredump[2530]: Failed to get EXE.
[ 2280.044996] systemd-coredump[2601]: Failed to get COMM, falling back to the command line.
[ 2280.047807] systemd-coredump[2601]: Failed to get EXE.
[ 2497.068099] systemd-coredump[2691]: Failed to get COMM, falling back to the command line.
[ 2497.099913] systemd-coredump[2691]: Failed to get EXE.
[ 2600.703980] systemd-coredump[2724]: Failed to get COMM, falling back to the command line.
[ 2600.707333] systemd-coredump[2724]: Failed to get EXE.
[ 5169.413761] systemd-coredump[3141]: Failed to get COMM, falling back to the command line.
[ 5169.415308] systemd-coredump[3141]: Failed to get EXE.

**Comment by crawford** [comment]
Can you try this on a newer version of CoreOS and reopen if you are still seeing the issue?
