### ISSUE TITLE
systemd drop in confusion /etc/systemd/* or /run/systemd/*

### ISSUE THREAD

**Issue by ForbiddenEra** [coreos/bugs#292]
According to the docs at https://coreos.com/docs/distributed-configuration/customize-etcd-unit/

```
We need to create our drop-in unit in /run/systemd/system/etcd.service.d/
```

If I create any files in /run/systemd/system/etcd.service.d/ - they're wiped every boot..

But - if I put it in /etc/systemd/system/etcd.service.d - it's picked up by etcd..

Am I missing something or are the docs wrong?

On CoreOS alpha 607.0.0

**Comment by marineam** [comment]
Things that cloudinit creates can often be placed under /run since cloudinit will run on every boot to initalize them. If you are placing files yourself that need to be preserved then you should use the path under /etc.

**Comment by ForbiddenEra** [comment]
That's what I've always though - however the doc I linked clearly states otherwise - which is an issue!

**Comment by marineam** [comment]
Hm, well the doc uses /run because it is ultimately puts it into a cloudconfig. Should probably use /etc for the non-cloudconfig example though.

/cc @robszumski

**Comment by robszumski** [comment]
One of the root problems here is a lack of documentation on how drop-ins work and how we use them: https://github.com/coreos/docs/issues/364

It's _not_ safe to change that path to `/etc` for any example, cloud-config or otherwise, right?

**Comment by ForbiddenEra** [comment]
If you're using the cloud-config, it will drop it in ``/run/`` and do that every boot so it's fine.

Otherwise it needs to be placed in ``/etc/``, as far as I'm aware.

**Comment by marineam** [comment]
Yup.

@robszumski perhaps you are thinking of issues we've had when some auto-generated cloudinit stuff landed in /etc, making it difficult to override and tell the difference between something automatic and something a user placed there intentionally.
