### ISSUE TITLE
Seccomp filters in systemd-nspawn prevent firmware flashes

### ISSUE THREAD

**Issue by jayofdoom** [coreos/bugs#293]
Some seccomp filters in systemd-nspawn are breaking the ability to flash firmware inside a capability=all container. 

I've patched upstream systemd-nspawn: http://lists.freedesktop.org/archives/systemd-devel/2015-February/028671.html to support this; but have gotten no traction on getting it merged.

Could this be carried downstream by CoreOS until systemd merges it?

I'll follow this up with a PR to the overlay to resolve this bug.

**Comment by marineam** [comment]
I would say probably yes, after all we did already include the earlier version of your fix: https://coreos.com/releases/#584.0.0 https://github.com/coreos/coreos-overlay/commit/7fe6b32718a03f276d87a2cdb2fa2bd514d51af7

Sucks that which patches get reviewed when upstream can be so haphazard.

**Comment by jayofdoom** [comment]
http://cgit.freedesktop.org/systemd/systemd/commit/?id=9a71b1122c6e49dd9227f82b2f53837c7ea13019 is now merged upstream, I'm going to wait for the next systemd release. Feel free to include this downstream before then, but given it's upstream I could also wait :).

Thanks!

**Comment by marineam** [comment]
Oops, lost track of this. Given the tricky process of updating major releases we should add the patch.
