### ISSUE TITLE
alpha: 612.0.0 has problems with outbound traffic and veth

### ISSUE THREAD

**Issue by philips** [coreos/bugs#297]
The latest alpha release has issues with outbound traffic from containers.

The rollout of this release to the alpha channel has been paused. We suspect this is a bug in the 3.19 kernel.

**Comment by philips** [comment]
I don't see any patches in the 3.19.y stable queue: https://git.kernel.org/cgit/linux/kernel/git/stable/stable-queue.git/tree/queue-3.19

**Comment by philips** [comment]
It seems to be caused by this: https://github.com/systemd/systemd/commit/5a8bcb674f71a20e95df55319b34c556638378ce

Somehow forwarding is getting disable by systemd in the wrong order compared to docker, I think, maybe.

**Comment by marineam** [comment]
So they broke all systems that already set forwarding via sysctl instead of this new option they just added? Even if we fix our units custom units provided by uses will still be broken. We need to roll back systemd until this is done in a way compatible with existing systems.

**Comment by gregkh** [comment]
I don't have any networking patches queued up at the moment, has this been discussed on the upstream networking mailing list?

**Comment by philips** [comment]
@gregkh we tracked it down to systemd v219 changing the default forwarding policy https://github.com/systemd/systemd/commit/5a8bcb674f71a20e95df55319b34c556638378ce

**Comment by crawford** [comment]
Rolling back to 218 via https://github.com/coreos/coreos-overlay/pull/1133.

**Comment by gregkh** [comment]
Great, not a kernel problem, I'm happy :)

**Comment by ForbiddenEra** [comment]
Thanks, for pausing this. I'd hate to see a broken version pushed.

**Comment by crawford** [comment]
Upstream bug: https://bugs.freedesktop.org/show_bug.cgi?id=89509

**Comment by philips** [comment]
We have rolled out 612.1.0 wit this fix, right? Can this be closed? @crawford

**Comment by crawford** [comment]
Sure.
