### ISSUE TITLE
Services failing to start in 612.1.0

### ISSUE THREAD

**Issue by jmreicha** [coreos/bugs#299]
I'm not sure what is going on but after taking a reboot the locksmith service was reporting that it could not start.  I poked around a little bit and noticed that journalctl did not work so I rebooted again, and the "splash" screen reported the following:

```
CoreOS alpha (612.1.0)
Failed Units: 7
  system-cloudinit@usr-share-oem-cloud\x2dconfig.yml.service
  systemd-hostnamed.service
  systemd-journald.service
  systemd-random-seed.service
  systemd-update-utmp.service
  systemd-journald-dev-log.socket
  systemd-journald.socket
```

Not sure if this is related to any of the other bugs or changes that were made but thought I would report it.

**Comment by crawford** [comment]
Yikes. Sorry, this one slipped through the cracks. Are you still having this issue?

**Comment by jmreicha** [comment]
This was so long ago I can't remember what I was doing.  I'm okay to close this one.
