### ISSUE TITLE
Empty file ending in .conf in /etc/systemd/network breaks all networking

### ISSUE THREAD

**Issue by hookenz** [coreos/bugs#300]
Honestly, it's probably just a rant but systemd is nothing short of "fragile" and working with it remotely is so painful.  I'm trying to set up another interface remotely and just locked myself out of a machine for nothing other than having an empty file named 10-static.network... however I also have a 20-dhcp.network that has match rules on the interface that was working before.

I'm curious as to the rationale behind why systemd it was chosen for CoreOS.  I hate it!
Binary logs...?  odd networking?  What were the systemd developers thinking??  where else can I go write and complain? lol

**Comment by crawford** [comment]
"10-static.network" is lexicographically ordered before "20-dhcp.network" and it matches all interfaces (by omitting a match). While it is an unfortunate effect, I don't know of a more sane behavior without introducing special cases.

**Comment by hookenz** [comment]
I didn't realise that if you ommit a match section it'll match all interfaces.  Thanks for pointing that out.  I thought I was temporarily disabling it.  It turns out not.
