### ISSUE TITLE
Please make the grub boot prompt longer by default

### ISSUE THREAD

**Issue by hookenz** [coreos/bugs#302]
It's really hard, next to impossible to break into the grub prompt to edit the boot and add coreos.autologin so I can fix broken networking remotely via IPMI.

Please make it display the prompt for a couple of seconds by default before just booting up and provide/document a way that this can be edited.

**Comment by crawford** [comment]
We have systems that regularly boot in less than 3 seconds. Adding a few seconds to the bootloader would introduce a significant slowdown.

We've configured grub to read additional configs from `/usr/share/oem/grub.cfg`. You can use this in a pinch to increase the timeout (similar to the config for [OnMetal](https://github.com/coreos/coreos-overlay/blob/master/coreos-base/oem-rackspace-onmetal/files/grub.cfg)). Keep in mind that this is not guaranteed to work forever. We may change this mechanism in the future.

**Comment by hookenz** [comment]
That is useful! I'll try that.

**Comment by jobinar** [comment]
> Keep in mind that this is not guaranteed to work forever. We may change this mechanism in the future.

Has this been removed? I am on CoreOS stable (1010.5.0) and have added  
`set timeout=15` to `/usr/share/oem/grub.cfg` and rebooted my machine but I still don't see my grub.

**Comment by crawford** [comment]
@jobinar It has not been removed. Setting the timeout as you've described should work. Would you mind opening a new bug?
