### ISSUE TITLE
curl fails on coreos-alpha 612.1.0

### ISSUE THREAD

**Issue by tomdee** [coreos/bugs#306]
I'm running coreos-alpha 612.1.0 under Vagrant

When I run curl, I get the following error
`curl: symbol lookup error: /lib64/libcurl.so.4: undefined symbol: SSLv2_client_method`

**Comment by marineam** [comment]
I'm not sure how this could happen, the openssl build in 612.1.0 does still include SSLv2. Have you copied any binaries or libraries to the system from other systems? What is the exact command you are running and the environment (run `env`)?

**Comment by crawford** [comment]
@tomdee are you still seeing an issue or can this be closed?

**Comment by tomdee** [comment]
I haven't seen this again so happy to close.
