### ISSUE TITLE
Make licenses easier to understand

### ISSUE THREAD

**Issue by rothgar** [coreos/bugs#310]
Trying to get license info on CoreOS and individual components is very difficult. The website says it is Apache 2.0 licensed but no where in the repositories was that clear.

It is also difficult to figure out how the individual components are licensed. I was provided [the list of image packages](http://alpha.release.core-os.net/amd64-usr/current/coreos_production_image_packages.txt) but trying to track down licenses for individual packages in the (overlay repo)[https://github.com/coreos/coreos-overlay/] also proved to be difficult.

I know upstream packages have different licenses that are not in the control of the CoreOS team but for packages that are managed by the CoreOS team it would be nice if those components had clear licenses indicated in their repos and the main website was able to link to a license for the project.

This will help for development forks as well as legal approval.

**Comment by crawford** [comment]
This should be addressed by https://github.com/coreos/scripts/pull/385. The results of this will show up in http://alpha.release.core-os.net/amd64-usr/current/coreos_production_image_packages.txt.

**Comment by marineam** [comment]
Re-opening as there isn't any documentation on this yet which was part of the request.

@rothgar Does the list in http://alpha.release.core-os.net/amd64-usr/current/coreos_production_image_packages.txt at least start to meet your needs? The text of the named licenses in that file can be found here: https://github.com/coreos/portage-stable/tree/master/licenses

That covers what lands in the actual image, you mentioned some components not having clear licenses in their repos? Is there any particular example that is missing or misleading?

**Comment by marineam** [comment]
Oops, that is licenses.txt, not packages.txt and the code didn't upload licenses.txt. Sorry for the noise. Next release will upload the correct file. For reference the contents looks like this:

```
app-admin/flannel-0.3.0-r3::coreos Apache-2.0
app-admin/fleet-0.9.1::coreos Apache-2.0
app-admin/locksmith-0.2.3::coreos Apache-2.0
app-admin/sdnotify-proxy-0.1.0::coreos Apache-2.0
app-admin/sudo-1.8.10_p2::portage-stable ISC BSD
app-admin/toolbox-0.0.0-r4::coreos Apache-2.0
app-arch/bzip2-1.0.6-r6::portage-stable BZIP2
app-arch/gzip-1.5::portage-stable GPL-3
app-arch/tar-1.27.1-r2::portage-stable GPL-3+
...
```

**Comment by rothgar** [comment]
License versions available in a list like that should work for me. Having the text available is also good too.
