### ISSUE TITLE
OverlayFS breaks sockets

### ISSUE THREAD

**Issue by 46labs** [coreos/bugs#311]
So since upgrading CoreOS to a build running overlayfs as the standard fs, unix sockets are basically broken. This is evidenced in supervisord (which we run to control nearly all of our apps) simply rejects connections. This, apparently, is a known issue...but has yet to be addressed in any of the 6-series CoreOS releases. Are we the only people running sockets in containers on CoreOS? This is a massive bug that seems to have gone overlooked.

**Comment by brettnem** [comment]
Here's a ubuntu bug report for essentially the same issue. Not sure if this is related; but the information might help in the underlying diagnosis. 

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1214500

Just to be clear, if you update to CoreOS Beta or Stable as of today, containers running supervisord won't work right. Specifically supervisord runs and seems to work fine, but controlling supervisord with supervisorctl using the unix socket (default) *does not work at all*. 

Although it is likely possible that supervisord can be controlled via a non-unix socket method, there are other instances where the use of unix sockets is desirable or required depending on specific application needs. This seems like a huge bug; and I'm not sure how others are not experiencing this on *stable*

Am I looking at this wrong?

**Comment by mischief** [comment]
so far, i can't find a problem with just unix domain sockets. a little ping-pong program i wrote in go works fine. all the bug reports i can find about this specifically describe supervisord.

**Comment by Xarthisius** [comment]
Just hit it today with *ipython nbconvert*. It uses nodejs to convert python to e.g. html. Apperently opens a lot of sockets...

**Comment by Yossibh** [comment]
Not sure if it help, but I'm seeing the same unix socket supervisord issue when deploying clearwater-docker https://github.com/Metaswitch/clearwater-docker

**Comment by euank** [comment]
According to https://github.com/moby/moby/issues/12080#issuecomment-226435505 this has been fixed as of the 4.7 kernel.

All Container Linux channels ship at least that new a kernel.
