### ISSUE TITLE
Add PPP support

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#313]
_From @olalonde on March 21, 2015 7:48_

I'm trying to run pptp on CoreOS inside a Docker container. So far, the file looks like this (it's my first try):

```systemd
[Unit]
Description=PPTP
After=docker.service
Requires=docker.service
[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill pptp
ExecStartPre=-/usr/bin/docker rm pptp
ExecStartPre=/usr/bin/docker pull olalond3/vpn-pptp
ExecStartPre=/usr/bin/mknod /dev/ppp c 108 0
ExecStart=/bin/bash -c "\
  docker run \
    --name pptp \
    --privileged \
    --env PPTP_USERNAME=$(etcdctl get /pptp_username) \
    --env PPTP_PASSWORD=$(etcdctl get /pptp_password) \
    -p 1723:1723 \
    olalond3/vpn-pptp \
"
ExecStop=/usr/bin/docker stop pptp
```

When doing `fleetctl start pptp`, and `fleetctl journal -f pptp`, I'm getting this error message:

```bash
bash[10051]: modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.18.1/modules.dep.bin'
bash[10051]: /usr/sbin/pppd: Please load the ppp_generic kernel module.
```

I assume this means my unit file should probably be loading some kernel module? Is that possible and if so, how?

_Copied from original issue: coreos/fleet#1162_

**Comment by jonboulle** [comment]
_From @olalonde on March 21, 2015 9:3_

```bash
$ modprobe ppp_generic
modprobe: FATAL: Module ppp_generic not found.
```

This doesn't appear to work. Any ideas which step I should take now? Do I have to compile ppp_generic module myself and put it in CoreOS through the cloud init file?

**Comment by olalonde** [comment]
I'm not very familiar with Kernel modules. Maybe this is not really a bug but it would be nice if someone could point me in the right direction.

**Comment by marineam** [comment]
Curently CoreOS doesn't include support for PPP, we will need to add those kernel modules before this works. Even then loading the modules from inside a docker container are unlikely to work correctly. Instead you can write `ppp_generic` and anything else you need to `/etc/modules-load.d/ppp.conf` or similar.

Will update once we enable PPP

**Comment by olalonde** [comment]
I'd like do this by myself if possible and send a PR. But I'm not sure where to start. Is there a guide somewhere on how to contribute to CoreOS?

**Comment by sllawap** [comment]
See https://github.com/coreos/coreos-overlay/tree/master/sys-kernel

According to the README:

To modify the defconfig to .config in the kernel source and run:
  make olddefconfig
  make menuconfig
  make savedefconfig
and copy defconfig back to coreos-kernel/files
