### ISSUE TITLE
Config drive mounted regardless of oem/cloud-config.yml entries

### ISSUE THREAD

**Issue by jayofdoom** [coreos/bugs#314]
Hi all, this is an upstreaming of the bug reported to Ironic here: https://bugs.launchpad.net/ironic/+bug/1433812

Basically, despite masking all relevant units (https://github.com/openstack/ironic-python-agent/blob/master/imagebuild/coreos/oem/cloud-config.yml#L5p) if a configdrive exists on a booted disk it will still be mounted. This is undesirable in several cases for OpenStack Ironic, such as when we boot to erase an existing installation or overwrite an existing one (if cleaning is disabled).

Using the kernel command line config option to disable configdrive is a workaround, but since Ironic has multiple ramdisks, we'd rather not add a CoreOS-specific workaround to the default configuration.

There are two possible workarounds:
1) We could remove the offending units from the PXE image during build time. This would be a break from existing policy where we don't modify anything outside of oem/ from the shipped CoreOS image, and prevent us from ever shipping a 100% stock CoreOS PXE image.

2) We could unmount the configdrive before masking the units. Would this work? Or is the cloud-config.yml processed too late in the boot process to have prevented coreos-cloudinit from running against an existing configdrive?

Any insight would be appreciated, as well as a better overall way to handle this in PXE images.

**Comment by crawford** [comment]
@jayofdoom now that CoreOS ships with Ignition, you can just mask off any units you don't want to run. Ignition runs before systemd, so you won't have to deal with any race conditions.
