### ISSUE TITLE
Ship etcd2 in CoreOS

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#317]
- [x] switch etcd2 to IANA port numbers
  - [x] support etcdctl https://github.com/coreos/etcd/pull/2611
  - [x] support fleet https://github.com/coreos/fleet/issues/1171
    - [x] modify fleetctl to use correct ports https://github.com/coreos/fleet/pull/1173
    - [x] modify fleetd to use correct ports https://github.com/coreos/fleet/pull/1177
  - [x] support flannel https://github.com/coreos/flannel/issues/147
  - [x] support locksmith https://github.com/coreos/locksmith/pull/75
  - [x] documentation
- [x] remove fleet dependency on etcd.service https://github.com/coreos/coreos-overlay/pull/1182
- [x] make etcd.service and etcd2.service conflict https://github.com/coreos/coreos-overlay/pull/1173
- [x] locksmith needs to check etcd[2].service is-active https://github.com/coreos/locksmith/pull/74
- [x] cloud-config support for configuring etcd2 https://github.com/coreos/coreos-cloudinit/pull/330
- [x] OEM support for etcd2 https://github.com/coreos/coreos-overlay/pull/1191
- [x] Update site docs to use etcd2 (do not merge until etcd2 hits stable)
- [x] ~~Move etcd2 to /usr/lib64/etcd2/etcd~~
- [x] Bump utilities
 - [x] locksmith
 - [x] flannel
 - [x] fleet
 - [x] etcd
 - [x] cloud-init

**Comment by philips** [comment]
On locksmith can we have etcd start a fake target or something instead?

**Comment by philips** [comment]
I would prefer that we not make the IANA port stuff a requirement as it is going to cause a large amount of work and complication for negligible gain.

**Comment by brianredbeard** [comment]
I can understand that it is a non-trivial amount of work... then again we've had those numbers in pocket for over eight months now so it's also not a secret that the change has been coming.

**Comment by brianredbeard** [comment]
Additionally, having different port numbers gives users a mechanism for making a distinct choice about which version they're using while still allowing for a migration path forward.

**Comment by marineam** [comment]
I don't see anything wrong with listening on both ports like etcd does by default now. It provides a graceful way to migrate clients. Up until now there wasn't any way to gracefully move to the new ports so the 8 month thing is just a reflection of how long it took us to get here, not that we plan to just ignore the ports forever.

**Comment by jedsmith** [comment]
@philips Isn't migrating to 2 already complication? You migrate to 2, you also migrate to the IANA ports.

Makes sense to me, anyway.

**Comment by philips** [comment]
We listen on both ports by default and users can configure to only listen on the new ones if they want if all of their applications use them. Seems simple and easy to understand. IANA is great but nearly all applications use the 'de facto' ports of 4001 and 7001. Consolidating to one is great but it only introduces more problems for us at this point.

**Comment by kelseyhightower** [comment]
I agree with @philips here, we need to depreciate the use of the default port over time.

**Comment by crawford** [comment]
The original text was unclear. My intent is that we stop defaulting to the legacy port and instead default to the IANA port. In practice, the clients can support reading from both (like `etcdctl`). This is much more of a documentation issue than anything else.

**Comment by marineam** [comment]
And just to follow up from today's meeting, considering the default is to listen on both ports on localhost and doing anything else requires explicit configuration the port question is mostly for documentation. We can make some of our clients like locksmith follow the etcdctl behavior of trying both ports to avoid explicitly configuring those too if the legacy port is disabled by the user but adding that magic behavior is not a blocker so our first pass of documentation should include examples of configuring locksmith and friends. We can add magic and simplify configuration as a second pass.

**Comment by marineam** [comment]
We *do* need to verify that all of our things work with etcd2 though, regardless of port choice.

**Comment by philips** [comment]
One suggestion would be to call it `/usr/lib64/etcd2/etcd` instead. Bit of a bikeshed though.

**Comment by crawford** [comment]
+1

**Comment by crawford** [comment]
Shipped in 653.0.0.
