### ISSUE TITLE
New btrfs documentation

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#319]
We have switched to ext4 by default but there are some cases that btrfs does handle better, such as providing accurate POSIX filesystem semantics in Docker containers. Ways users may want to use btrfs include:

 - Reformat ROOT as btrfs
 - Mount extra btrfs volumes to /var/lib/docker
   - Instructions will vary based on platform
 - Maintain a file on ext4 containing a btrfs filesystem and mount it via loop
   - Document growing the file if needed since docker won't do this automatically.
   - iirc systemd-nspawn has some built-in support for such a setup, it may be insightful to look at that implementation.

**Comment by marineam** [comment]
Related: https://github.com/docker/docker/issues/10180

**Comment by mischief** [comment]
it seems like https://coreos.com/docs/cluster-management/setup/mounting-storage/#use-attached-storage-for-docker already fits the bill, or am i mistaken?

**Comment by marineam** [comment]
Something that applies to persistent volumes would be good to.

**Comment by marineam** [comment]
Haven't worked on this yet but I claimed the task in last week's meeting

**Comment by jumanjiman** [comment]
add myself to this thread.

$dayjob has determined that an important app works great when rootfs is btrfs, but fails miserably on ext4. our current workaround is to build system on coreos 522.x.y (the last release with btrfs as rootfs), then update to latest since it preserves rootfs as btrfs.

**Comment by businessBoris** [comment]
@jumanjiman I wonder, aloud, if this is still a viable strategy (stable being at 717) ? Have you, or anyone else here, had cause to try it of late please?

**Comment by bradfordcp** [comment]
FWIW I am seeing the issue at docker/docker#10180 on stable 717 and has to fall back to using the btrfs workaround.

It's worth noting that the [documentation](https://coreos.com/docs/cluster-management/setup/mounting-storage/) does not mention how to start docker with the btrfs storage engine.

**Comment by marineam** [comment]
@bradfordcp our docker service will select the overlay driver if /var/lib/docker is tmpfs or ext4 or it will select btrfs if /var/lib/docker is btrfs. so no additional configuration should be needed.

Since we added https://coreos.com/docs/cluster-management/setup/mounting-storage/#creating-and-mounting-a-btrfs-volume-file the only bit we are missing is reformatting ROOT but that will come as part of the ignition project, so I think this can be resolved now.

**Comment by bradfordcp** [comment]
@marineam that is not my experience from a few minutes ago. I had to copy the `docker.service` file into `/etc/systemd/system` then add `-s btrfs`. Should I file a bug?

**Comment by jumanjiman** [comment]
we still need btrfs to avoid failure on latest stable channel release

**Comment by marineam** [comment]
@bradfordcp yes, please file a bug with any details of how /var/lib/docker is setup and the error you observed without `-s btrfs`.
