### ISSUE TITLE
Failed to stop docker: Interactive authentication required. 

### ISSUE THREAD

**Issue by philips** [coreos/bugs#321]
Originally reported at https://github.com/docker/docker/issues/7015#issuecomment-90642732

Only if this can help someone, after upgrading my enviroment I can avoid the error on docker restart.
My new environment:

CoreOS stable (607.0.0)

core@core-01 ~ $ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef-dirty

The bad news are that now I get an error on docker stop:

Apr 07 16:38:41 core-01 systemd[1]: xx.service: main process exited, code=exited, status=143/n/a 
Apr 07 16:38:41 core-01 bash[6595]: Failed to stop docker-345029b9c94588f154a9e517e0b480f18c6488f42c72d84fcc04f6f476d51406.scope: Interactive authentication required. 
Apr 07 16:38:41 core-01 systemd[1]: xx.service: control process exited, code=exited status=1

I will continue looking for some light on this topic and keep you posted

Agus

**Comment by philips** [comment]
@agusgr  Can you followup over here with what you were doing to cause this? Any example unit files, what you were doing on the command line, etc would be helpful.

**Comment by agusgr** [comment]
@philips Of course I will do. Now it's no possible to post more info, but tomorrow morning I will send you more info. Thanks for your help on this!

Regards,

Agus

**Comment by agusgr** [comment]
Hi again,

Mystery solved.

- I had applied the "workaround" found on https://github.com/smilart/smilart.os.distribution/commit/e18e28d5b33b7614033984def59d34579eb308e2
- Obviously, I had forgotten to remove it when I upgrade my CoreOs environent (shame on me, :( )
- I have tested this morning without it and the "Interactive authentication required." message dissapeared

Sorry about the noise and lot of thanks for your help.

Regards,

Agus

**Comment by mischief** [comment]
@agusgr thanks for solving the mystery and reporting back :-)

**Comment by marineam** [comment]
@agusgr odd, that ExecPostStop command should have still been OK unless you had User= set to something other than root in the unit. The "Interactive authentication required." message is the confusing error message from systemd+polkit when you try to run systemctl as non-root.

**Comment by idonin** [comment]
Problem doesnt solved at 675.0.0

core2 ~ # systemd-nspawn --ephemeral --bind-ro=/home/ceph:/root --bind-ro=/opt/cloud-configs/etc/ceph:/etc/ceph --machine=ceph --capability=CAP_MKNOD
Spawning container ceph on /var/lib/machines/.#ceph4b2590c28afc5f1c.
Press ^] three times within 1s to kill container.
Failed to register machine: Unit machine-ceph.scope already exists.
