### ISSUE TITLE
systemd fails to pull private repo from quay.io

### ISSUE THREAD

**Issue by groob** [coreos/bugs#323]
Unit file:
```
# /etc/systemd/system/proxy-pac.service
[Unit]
Description=Serve proxy PAC file to redirect Google.com to squid.
Requires=docker.service

[Service]
ExecStartPre=-/usr/bin/bash -c whoami
ExecStartPre=-/usr/bin/docker kill proxy-pac
ExecStartPre=-/usr/bin/docker rm -f proxy-pac
ExecStartPre=/usr/bin/docker pull quay.io/whitby/proxy-pac:latest
ExecStart=/usr/bin/docker run --rm --name proxy-pac \
  -e VIRTUAL_HOST=proxy \
  -p 8082:80 quay.io/whitby/proxy-pac:latest
ExecStop=-/usr/bin/docker stop proxy-pac

[Install]
WantedBy=multi-user.target
```
The service fails with 403 error
journalctl output

```
Apr 09 14:38:15 coreos1 systemd[1]: Starting Serve proxy PAC file to redirect Google.com to squid....
Apr 09 14:38:15 coreos1 bash[1390]: root
Apr 09 14:38:15 coreos1 docker[1392]: Error response from daemon: No such container: proxy-pac
Apr 09 14:38:15 coreos1 docker[1392]: time="2015-04-09T14:38:15Z" level="fatal" msg="Error: failed to kill one or more containers"
Apr 09 14:38:15 coreos1 docker[1400]: Error response from daemon: No such container: proxy-pac
Apr 09 14:38:15 coreos1 docker[1400]: time="2015-04-09T14:38:15Z" level="fatal" msg="Error: failed to remove one or more containers"
Apr 09 14:38:15 coreos1 docker[1408]: Pulling repository quay.io/whitby/proxy-pac
Apr 09 14:38:15 coreos1 systemd[1]: proxy-pac.service: control process exited, code=exited status=1
Apr 09 14:38:15 coreos1 systemd[1]: Failed to start Serve proxy PAC file to redirect Google.com to squid..
Apr 09 14:38:15 coreos1 systemd[1]: Unit proxy-pac.service entered failed state.
Apr 09 14:38:15 coreos1 systemd[1]: proxy-pac.service failed.
Apr 09 14:38:15 coreos1 docker[1408]: time="2015-04-09T14:38:15Z" level="fatal" msg="HTTP code: 403"
```
I've made sure to add the .dockercfg file to both /home/core/.dockercfg and /root/.dockercfg
Pulling the repository myself works fine as both core and root.
```
core@coreos1 ~ $ ls -l /home/core/.dockercfg
-rw------- 1 core core 175 Apr  9 13:52 /home/core/.dockercfg
core@coreos1 ~ $ sudo ls -l /root/.dockercfg
-rw------- 1 root root 175 Apr  9 14:00 /root/.dockercfg
```
By the way, the documentation [here](https://coreos.com/docs/enterprise-registry/configure-machines/) says that the home directory for root is /home/root which is wrong. I added .dockercfg to home/root/.dockercfg for good measure but that did not fix the error. 

```
core@coreos1 ~ $ /usr/bin/docker pull quay.io/whitby/proxy-pac:latest
224873bdcaa1: Download complete
Status: Image is up to date for quay.io/whitby/proxy-pac:latest

core@coreos1 ~ $ sudo /usr/bin/docker pull quay.io/whitby/proxy-pac:latest
224873bdcaa1: Download complete
Status: Image is up to date for quay.io/whitby/proxy-pac:latest

core@coreos1 ~ $ sudo su
coreos1 core # /usr/bin/docker pull quay.io/whitby/proxy-pac:latest
Status: Image is up to date for quay.io/whitby/proxy-pac:latest
```

Rebooting the server does not resolve this issue either. 

I'm zalmoxes on #coreos if I can help with debugging this further.

**Comment by jzelinskie** [comment]
There are two solutions to this issue:

* Pull a squashed image 

```sh
$ curl -L -f https://USER:PASSWORD@quay.io/c1/squash/NAMESPACE/REPOSITORY/TAG | docker load
```

* Execute `docker login` in a step beforehand. 

[Here's](https://github.com/DevTable/container-cloud-config/blob/788dcbc20002dcd016fd06cdffe116f5bccefc85/container_cloud_config/templates/dockersystemd.yaml#L31) an example in a python script, that we use to generate CloudFormations and deploy to AWS.

**Comment by scole-scea** [comment]
Yeah, we always use `docker login` first on our pulls from quay. Never had a problem. (Unlike pulls from docker.io, which occasionally fail.)

**Comment by crawford** [comment]
On 04/09, Victor wrote:
> I've made sure to add the .dockercfg file to both /home/core/.dockercfg and /root/.dockercfg
You'll need to set the WorkingDirectory [1] to one of the aforementioned
paths. By default systemd will run unit's with WorkingDirectory=/.

> By the way, the documentation [here](https://coreos.com/docs/enterprise-registry/configure-machines/) says that the home directory for root is /home/root which is wrong. I added .dockercfg to home/root/.dockercfg for good measure but that did not fix the error. 
We'll fix that. Thanks for the heads up.

[1] http://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=

-Alex

**Comment by groob** [comment]
Thanks for all the responses. I was able to resolve this issue by adding the following line to my SystemD unit. 
``` 
Environment="HOME=/root"
```

**Comment by appleusers25** [comment]
Hi All,
We are having similar issue,When i do docker pull on individual SWARM worker nodes to pull image form a private repo it works.

However when I try to create a service from SWARM Manager it complains of "no image found.." as it fails downloading image from private repo.
Just before service create command I used "docker login".. sucessfully.

Appreciate any direction regarding this.
