### ISSUE TITLE
CoreOS update tries to fetch resources using IPv6 when that is disabled

### ISSUE THREAD

**Issue by stexyz** [coreos/bugs#324]
The coreos cluster fails to perform automated updates (default strategy).

I try to invoke update manually calling:
update_engine_client -check_for_update

When I look at the logs of the update-engine.service I can see the following log. I find the problem in highlighted line.
I have disabled the ipv6 on all net ifaces, proxy is set-up for the service. Our infrastructure doesn't support IPv6 now.

[0410/164626:INFO:omaha_request_action.cc(266)] Request: <?xml version="1.0" encoding="UTF-8"?>
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: <request protocol="3.0" version="CoreOSUpdateEngine-0.1.0.0" updaterversion="CoreOSUpdateEngine-0.1.0.0" installsource="ondemandupdate" ismachine="1">
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: <os version="Chateau" platform="CoreOS" sp="522.6.0_x86_64"></os>
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="522.6.0" track="stable" bootid="{52f3125e-ea01-416d-b0f8-91a868b6b554}" oem="" oemversion="" alephversion="522.6.0" machineid="902a3ef2e15c4b49a81b28c016704be7"
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: <event eventtype="13" eventresult="1"></event>
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: </app>
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: </request>
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: [0410/164626:INFO:libcurl_http_fetcher.cc(62)] Starting/Resuming transfer
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: [0410/164626:INFO:libcurl_http_fetcher.cc(51)] We are connected via Ethernet, Updates allowed: Yes
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: [0410/164626:INFO:libcurl_http_fetcher.cc(185)] Setting up curl options for HTTPS
Apr 10 16:46:26 mpaphsvperf01 update_engine[906]: [0410/164626:INFO:libcurl_http_fetcher.cc(448)] Setting up timeout source: 1 seconds.
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:libcurl_http_fetcher.cc(261)] HTTP response code: 200
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:libcurl_http_fetcher.cc(318)] Transfer completed (200), 798 bytes downloaded
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:omaha_request_action.cc(588)] Omaha request response: <?xml version="1.0" encoding="UTF-8"?>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <response protocol="3.0" server="update.core-os.net">
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <daystart elapsed_seconds="0"></daystart>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <updatecheck status="ok">
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <urls>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <url codebase="https://commondatastorage.googleapis.com/update-storage.core-os.net/amd64-usr/607.0.0/"></url>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: </urls>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <manifest version="607.0.0">
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <packages>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <package hash="mQlb6BgHaIoxe/8u0gIuEwLLG0A=" name="update.gz" size="111550391" required="false"></package>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: </packages>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <actions>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: <action event="postinstall" ChromeOSVersion="" sha256="QsIsGx7Dp97jdJpYYq561bbuvVUVezswrMNvyKCp16o=" needsadmin="false" IsDelta="false" DisablePayloadBackoff="true"></action>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: </actions>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: </manifest>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: </updatecheck>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: </app>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: </response>
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:action_processor.cc(82)] ActionProcessor::ActionComplete: finished OmahaRequestAction, starting DownloadAction
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:install_plan.cc(52)] InstallPlan: , new_update, url: https://commondatastorage.googleapis.com/update-storage.core-os.net/amd64-usr/607.0.0/update.gz, payload size: 111550391, payload hash: QsIsGx7Dp97jdJ
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:update_attempter.cc(597)] Download status: active
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:multi_range_http_fetcher.cc(29)] starting first transfer
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:multi_range_http_fetcher.cc(57)] starting transfer of range 0+?
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:libcurl_http_fetcher.cc(62)] Starting/Resuming transfer
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:libcurl_http_fetcher.cc(51)] We are connected via Ethernet, Updates allowed: Yes
Apr 10 16:46:31 mpaphsvperf01 update_engine[906]: [0410/164631:INFO:libcurl_http_fetcher.cc(185)] Setting up curl options for HTTPS
Apr 10 16:46:32 mpaphsvperf01 update_engine[906]: [0410/164632:INFO:libcurl_http_fetcher.cc(448)] Setting up timeout source: 1 seconds.

-------->>>> problem starts here

Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:ERROR:libcurl_http_fetcher.cc(264)] Unable to get http response code: Failed to connect to 2a00:1450:4009:80c::2001: Network is unreachable

-------->>>> problem ends here

Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:libcurl_http_fetcher.cc(295)] Transfer resulted in an error (0), 0 bytes downloaded
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:multi_range_http_fetcher.cc(150)] Received transfer complete.
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:multi_range_http_fetcher.cc(107)] TransferEnded w/ code 0
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:multi_range_http_fetcher.cc(141)] Done w/ all transfers
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:update_attempter.cc(597)] Download status: inactive
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:action_processor.cc(68)] ActionProcessor::ActionComplete: DownloadAction action failed. Aborting processing.
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:action_processor.cc(73)] ActionProcessor::ActionComplete: finished last action of type DownloadAction
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:update_attempter.cc(460)] Processing Done.
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:ERROR:update_attempter.cc(787)] Update failed.
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:payload_state.cc(97)] Updating payload state for error code: 9 (kActionCodeDownloadTransferError)
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:payload_state.cc(271)] Incrementing the URL failure count
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:payload_state.cc(421)] Current URL (Url0)'s Failure Count = 6
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:action_processor.cc(36)] ActionProcessor::StartProcessing: OmahaRequestAction
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:omaha_request_action.cc(265)] Posting an Omaha request to https://public.update.core-os.net/v1/update/
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:omaha_request_action.cc(266)] Request: <?xml version="1.0" encoding="UTF-8"?>
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: <request protocol="3.0" version="CoreOSUpdateEngine-0.1.0.0" updaterversion="CoreOSUpdateEngine-0.1.0.0" installsource="ondemandupdate" ismachine="1">
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: <os version="Chateau" platform="CoreOS" sp="522.6.0_x86_64"></os>
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="522.6.0" track="stable" bootid="{52f3125e-ea01-416d-b0f8-91a868b6b554}" oem="" oemversion="" alephversion="522.6.0" machineid="902a3ef2e15c4b49a81b28c016704be7"
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: <event eventtype="3" eventresult="0" errorcode="9"></event>
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: </app>
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: </request>
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:libcurl_http_fetcher.cc(62)] Starting/Resuming transfer
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:libcurl_http_fetcher.cc(51)] We are connected via Ethernet, Updates allowed: Yes
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:libcurl_http_fetcher.cc(185)] Setting up curl options for HTTPS
Apr 10 16:46:47 mpaphsvperf01 update_engine[906]: [0410/164647:INFO:libcurl_http_fetcher.cc(448)] Setting up timeout source: 1 seconds.
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: [0410/164648:INFO:libcurl_http_fetcher.cc(261)] HTTP response code: 200
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: [0410/164648:INFO:libcurl_http_fetcher.cc(318)] Transfer completed (200), 798 bytes downloaded
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: [0410/164648:INFO:omaha_request_action.cc(588)] Omaha request response: <?xml version="1.0" encoding="UTF-8"?>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <response protocol="3.0" server="update.core-os.net">
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <daystart elapsed_seconds="0"></daystart>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <updatecheck status="ok">
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <urls>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <url codebase="https://commondatastorage.googleapis.com/update-storage.core-os.net/amd64-usr/607.0.0/"></url>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: </urls>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <manifest version="607.0.0">
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <packages>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <package hash="mQlb6BgHaIoxe/8u0gIuEwLLG0A=" name="update.gz" size="111550391" required="false"></package>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: </packages>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <actions>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: <action event="postinstall" ChromeOSVersion="" sha256="QsIsGx7Dp97jdJpYYq561bbuvVUVezswrMNvyKCp16o=" needsadmin="false" IsDelta="false" DisablePayloadBackoff="true"></action>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: </actions>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: </manifest>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: </updatecheck>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: </app>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: </response>
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: [0410/164648:ERROR:omaha_request_action.cc(595)] HTTP reported success but Omaha reports an error.
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: [0410/164648:INFO:action_processor.cc(65)] ActionProcessor::ActionComplete: finished last action of type OmahaRequestAction
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: [0410/164648:INFO:action_processor.cc(73)] ActionProcessor::ActionComplete: finished last action of type OmahaRequestAction
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: [0410/164648:INFO:update_attempter.cc(460)] Processing Done.
Apr 10 16:46:48 mpaphsvperf01 update_engine[906]: [0410/164648:INFO:update_attempter.cc(467)] Error event sent.

**Comment by marineam** [comment]
[coppied from a previous email conversation]

Found something possibly related:

https://bugzilla.redhat.com/show_bug.cgi?id=1187531
https://github.com/bagder/curl/commit/92835ca5d87850ae0c670d66bd73af391b34cdc3

Will update libccurl in the next alpha to see if that helps.

As a workaround you can put commondatastorage.googleapis.com in
/etc/hosts with the v4 addresses or try pointing at a different DNS
server to see if it sends you the address results in an order that
libcurl doesn't get confused over. (assuming your issue is the above
linked one)

**Comment by mischief** [comment]
should be fixed in the next alpha via coreos/coreos-overlay#1198 and coreos/portage-stable#183
