### ISSUE TITLE
enable kernel mods for sysdig

### ISSUE THREAD

**Issue by PierreKircher** [coreos/bugs#325]
after chatting with @marineam today & @kelseyhightower a few days back  in irc 

here the formal request

CONFIG_TRACEPOINTS
CONFIG_HAVE_SYSCALL_TRACEPOINTS

they do have a workaround with the toolbox, yet its not an elegant solution.

http://www.sysdig.org/wiki/how-to-install-sysdig-from-the-source-code/

thanks alot

**Comment by gianlucaborello** [comment]
Although getting it upstream would be indeed cool, please notice that running sysdig on CoreOS is fully supported via the Docker container we provide and maintain, and there's no need to have kernel headers available on the host (some people seemed to be confused about that looking at the IRC logs):

```
docker run -i -t --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro sysdig/sysdig
```

**Comment by crawford** [comment]
Both of these options have been enabled.

```
$ zgrep 'CONFIG_TRACEPOINTS\|CONFIG_HAVE_SYSCALL_TRACEPOINTS' /proc/config.gz 
CONFIG_TRACEPOINTS=y
CONFIG_HAVE_SYSCALL_TRACEPOINTS=y
```
