### ISSUE TITLE
update_engine doesn't report error when upgrade fails

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#327]
I attempted to upgrade a machine to a bad image. The update was applied, the machine rebooted, it failed to boot properly, and then rolled back to the previous image. After reverting, update_engine didn't report the failure.

To test this, I updated to a later version and then rebooted before update_engine could mark the boot as successful.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
