### ISSUE TITLE
CoreOS AMI's not signed 

### ISSUE THREAD

**Issue by pwaller** [coreos/bugs#328]
I'm looking at this useful directory:

http://stable.release.core-os.net/amd64-usr/current/

I note that there are lots of files there with the word AMI in the name which aren't accompanied by .sig/asc files (unless I'm missing something).

**Comment by marineam** [comment]
That is expected, right now the AMIs are created in AWS independently of the image build process and on a system that doesn't have access to the image signing key. This is something that should be fixed in the future as we gradually improve our build infrastructure.

**Comment by pwaller** [comment]
Ping.

**Comment by marineam** [comment]
Hm, yeah, I should be able to fix this in the next month or so. On the up side we finally have proper HTTPS support for the download sites so that offers a hint of verification.

**Comment by pwaller** [comment]
@bgilbert

This got marked `closed/rejected` but not actually closed - seems like [a lot of other issues are in that state](https://github.com/coreos/bugs/labels/closed%2Frejected). Please close this if it is meant to be closed.

**Comment by bgilbert** [comment]
@pwaller Whoops, thanks for the reminder.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
