### ISSUE TITLE
Not able to detect disks/DMAR errors on Dell R420

### ISSUE THREAD

**Issue by treed** [coreos/bugs#340]
I've been having an issue getting CoreOS running directly on a Dell R420 server via ipxe.

This is the case with version 660.0.0, and has been an issue since at least March 11th, with whatever versions were beta/alpha back then. (Looks like I tried 607.0.0 at least.)

This looks similar to #59 and #75, except that it is still happening. I decided to open a new issue rather than trying to reopen those.

Here's the output of `journalctl -b`: http://sprunge.us/WYGF

Here's the output of `lspci -vv`: http://sprunge.us/XKKT

Here's the output of `lsmod`: http://sprunge.us/MWRT

It is perhaps worth calling out in particular the megaraid controller.

Let me know if you need any additional information or debugging from me.

... I actually just noticed that I'm running 607.0.0 right now, and was when those logs were generated.

I pulled down a fresh copy of 660 (unsure what happened before), and tried booting that, and I can't even log into the box now, whereas with 607 I could at least ssh into it after a bit.

The console output (which I could screenshot if you want) does not seem materially different from the journalctl -b output. If I ping the server as it's trying to boot, I get exactly two ping responses and then it goes silent again, which is... weird.

**Comment by treed** [comment]
Update: Per suggestions I found about these error messages, we upgraded all possible firmwares today. I can now ssh into 668.2.0 again, but it still couldn't find the disks and was spewing the DMAR errors.

Until, at a different suggestion I found when checking a different error message, I disabled VT in the BIOS.

Now it boots and finds the disks.

Which... I don't even know. In the near term, I don't expect us to have any need to run VMs on the same machines I'm running containers on, but it might be worth figuring out what's actually going on here.

**Comment by wmark** [comment]
In a similar case I've created this file:

```
# /usr/share/oem/grub.cfg
set linux_append="intel_iommu=off"
```

**Comment by mischief** [comment]
@treed i found a similar question here that was also never resolved. https://communities.vmware.com/thread/268696?db=5

**Comment by crawford** [comment]
Does this work when UEFI booting?

**Comment by crawford** [comment]
@treed We've done a few quick tests on an R430 booting in UEFI mode with VT-x and VT-d enabled and haven't seen any trouble. Since it looks like you have an adequate work-around, I'm going to close this out. We can re-open it if you run into more trouble.
