### ISSUE TITLE
segfault at reboot

### ISSUE THREAD

**Issue by antoineco** [coreos/bugs#342]
CoreOS 660.0.0 crashes on AWS (hvm) with the following message when I reboot it:

`systemd-coredum[571]: segfault at 0 ip 00007f74142ac157 sp 00007ffc7f329600 error 6 in systemd-coredump[7f741429c000+16000]` ([full boot log](https://gist.github.com/antoineco/b44fd22384cf596cc58a#file-reboot))

I use the [provided ami](https://coreos.com/docs/running-coreos/cloud-providers/ec2/) with etcd2, fleet and flannel configured, on a t2.small instance with a Magnetic EBS. Nothing fancy.

The first boot is always fine, only the reboot fails. It happens every time without exception.

**Comment by antoineco** [comment]
I first assumed the problem was related to the flannel.1 interface, but it occurs also without enabling flannel.

**Comment by crawford** [comment]
systemd is also asserting:

```
[   45.476604] localhost systemd[1]: Assertion 's->type == SERVICE_ONESHOT' failed at /build/amd64-usr/var/tmp/portage/sys-apps/systemd-219-r6/work/systemd-219/src/core/service.c:1524, function service_enter_start(). Aborting.
[   45.599598] localhost systemd[1]: Caught <ABRT>, dumped core as pid 595.
[   45.599770] localhost systemd[1]: Freezing execution.
```

**Comment by crawford** [comment]
Can you provide the coredump file? You can use `coredumpctl` to find the file.

**Comment by antoineco** [comment]
Unfortunately systemd doesn't generate any coredump. I rebooted the instance several times without luck. The problem exists on CoreOS 668.2.0 as well.

**Comment by crawford** [comment]
I just spun up CoreOS 668.2.0 (hvm) and didn't run into the problem. How are you configuring this machine? What does your cloud-config look like?

**Comment by antoineco** [comment]
It happens only when I use a cloud-config, which consists of a couple of units to retrieve and run binaries (I run a Kubernetes cluster) and simple bash scripts.

You can find my configuration here: https://gist.github.com/antoineco/b44fd22384cf596cc58a#file-cloud-init

**Comment by antoineco** [comment]
@crawford I did a bit of [cleanup in my cloud-config](https://gist.github.com/antoineco/b44fd22384cf596cc58a/revisions), and now everything works like a charm. I hope it helps narrowing down the problem, in case there is one.

I believe overriding the whole docker unit caused the issue here. Besides it was completely unnecessary.

**Comment by jhart99** [comment]
I have the same issue one a single instance running CoreOS 668.2.0 (PXE).  All the rest of the nodes are configured identically and not experiencing this issue.  Issue remains in 681.  I took another node to 681 and it booted just fine.

Similar issue.  This is occuring inside of docker container which runs Zookeeper and Mesos slave.  Systemd-coredump catches a coredump and then dumps itself leaving behind no dumps.

```
May 15 17:22:59 vogtsl335a0 dockerd[662]: time="2015-05-15T17:22:59Z" level=info msg="-job start(fa46753c04e18ed4908809ae05a2fb31acf2d6427cd6d41431e4d81a5afc982b) = OK (0)"
May 15 17:22:59 vogtsl335a0 sh[3269]: info: Setting locale to en_US.UTF-8...
May 15 17:23:00 vogtsl335a0 sh[3269]: info: Starting syslog...
May 15 17:23:00 vogtsl335a0 sh[3269]: info: Mesos slave will try to register with a master using ZooKeeper
May 15 17:23:00 vogtsl335a0 sh[3269]: info: Starting slave...
May 15 17:23:01 vogtsl335a0 systemd-coredump[3354]: Failed to get EXE.
May 15 17:23:01 vogtsl335a0 kernel: systemd-coredum[3354]: segfault at 0 ip 00007f00580170e7 sp 00007ffe4436d9e0 error 6 in systemd-coredump[7f0058007000+16000]
May 15 17:23:01 vogtsl335a0 sh[3269]: /usr/local/bin/mesos_bootstrap.sh: line 28:    49 Aborted                 (core dumped) /usr/bin/mesos-init-wrapper slave > /dev/null 2>&1
 segfault at 0 ip 00007f00580170e7 sp 00007ffe4436d9e0 
```

**Comment by jhart99** [comment]
Ok after looking at this a bit more, it looks like this issue pops up when the hostname is more than 10 characters in length.  I don't think this is a problem with CoreOS, but with something else.

**Comment by djmaze** [comment]
I was getting the exact same assertion error that @crawford reported. It happened on two CoreOS stable servers (647.2.0) in my cluster upon starting a particular oneshot service via fleet. Afterwards, systemd seemed to be broken on those machines, with the following appearing in the logs every 25 minutes:

    [system] Failed to activate service 'org.freedesktop.systemd1': timed out

It believe from that point on, the systems became unresponsive to SSH logins and soft reboot attempts. Also fleet wasn't able to fetch unit states, so it broke too. No coredumps either.

This might be linked: On one of the systems, I am seeing a `systemd[1]: Out of memory` log entry a few seconds earlier. (Seems I need to setup swap, too!)

**Comment by crawford** [comment]
Is this still an issue with the systemd 225?

**Comment by mischief** [comment]
reopen this if anyone can still reproduce it.
