### ISSUE TITLE
PXE Booting with current Alpha (660.0.0) and Beta (647.0.0) images seems to result in a stuck process

### ISSUE THREAD

**Issue by geauxvirtual** [coreos/bugs#343]
We are currently in the process of installing CoreOS Alpha 660.0.0 on some physical servers (SuperMicro Fat Twins) and ran into an issue where PXE booting the current alpha or beta image with systemd 219 results in the server basically hanging on boot. It will report that systemd-journald fails with "Failed to set file attributes: inappropriate ioctl for device". At this point, the udev kernel device manager will stop and start again only to fail again with systemd-journald.

We are able to PXE boot the stable image with systemd 218. Once we are booted, we can install the current alpha 660.0.0 to disk and reboot, and the server boots successfully.

**Comment by marineam** [comment]
Oh damn. Sorry for the delay, will see if I can reproduce this.

**Comment by marineam** [comment]
Could you post any kernel args you are using?

**Comment by crawford** [comment]
I haven't been able to reproduce this failure (granted, I don't have any SuperMicro Fat Twins at my disposal). @geauxvirtual, can you provide us with any more information to go on?

**Comment by geauxvirtual** [comment]
Not sure when this gear will be back online. I can try and track down some more physical nodes we have available to see if we see the same issue. I don't recall passing any additional kernel args when booting up the servers.

**Comment by FirefighterBlu3** [comment]
i've seen this message whether coreos will boot or not. if you look a bit further back in your console, i suspect you will find that sysroot.mount failed which is in my situation, the only failure that causes the udev/journal cycle.

**Comment by crawford** [comment]
I believe this has been fixed in 717.0.0. Please reopen if you still have trouble.
