### ISSUE TITLE
Enable Dell RBU and DCDBAS drivers

### ISSUE THREAD

**Issue by zapient** [coreos/bugs#346]
Please enable the Dell Systems Management Base (dcdbas) and Dell Remote BIOS (dell_rbu) Update kernel drivers since they are in the mainline kernel.

> The dcdbas and dell_rbu drivers are Linux kernel drivers that are required to perform certain operations in libsmbios. For example, BIOS updates require the dell_rbu driver. These kernel drivers are included in the standard linux kernel starting with Linux 2.6.14. If you have this kernel and these drivers are not present, please talk to your vendor about enabling these drivers.

https://github.com/coreos/coreos-overlay/blob/f139078c379856ee1f583df8b8242c335fb30784/sys-kernel/coreos-kernel/files/amd64_defconfig-4.0#L3227-L3228

**Comment by marineam** [comment]
I thought we enabled this ages ago, must have been thinking of something else. Thanks for the fix.
