### ISSUE TITLE
remount-ro and journald

### ISSUE THREAD

**Issue by ineu** [coreos/bugs#348]
Default errors behavior for root filesystem is remount-ro:

```
core@production-coreos-2 ~ $ sudo tune2fs -l /dev/sda9 | grep behav
Errors behavior:          Remount read-only
```

When journald cannot write journal files to filesystem, it starts logging errors to the kernel buffer. 
These two facts together lead to following problem:
1. An error happens to underlying device.
2. Root filesystem is remounted readonly.
3. Journald fails to write logs to the now read-only filesystem and starts flooding kernel buffer with its own messages like 'cannot write journal, filesystem is readonly'.
4. These messages fill the buffer, removing original disk error from it.

Thus it is not possible to see what the problem which caused remount-ro was, neither it is possible to serve logs to remote location as journald-gatewayd has no new files to read from filesystem and journald never writes them to RO filesystem.

So, there should be some way to see original disk error. Either journald shouldn't write messages to the kernel buffer endlessly, or root FS shouldn't be remounted read-only in case of error, or journal location (maybe the whole /var) should reside on separate parition which is never remounted RO, or there should be some way to setup proper remote logging.

**Comment by crawford** [comment]
This should have been fixed in newer releases of systemd. Feel free to reopen if it's still an issue.
