### ISSUE TITLE
motd on Alpha shows "CoreOS stable"

### ISSUE THREAD

**Issue by JeanMertz** [coreos/bugs#349]
Minor thing, motd is wrong in 668.2.0 Alpha 

```
CoreOS stable (668.2.0)
```

**Comment by mischief** [comment]
@JeanMertz can you give some more information? where did you get the image? how did you boot it? i checked http://alpha.release.core-os.net/amd64-usr/668.2.0/coreos_production_qemu_image.img.bz2 and see `alpha` in the motd.

**Comment by robszumski** [comment]
Did you change your channel via cloud-config?

For example, if you booted a stable image but [attached it to a different channel](https://coreos.com/docs/cluster-management/setup/switching-channels/) for updates, the motd would show alpha.

**Comment by JeanMertz** [comment]
Ah yes, of course that's the issue :+1: I was under the impression that the whole string was related to the current version, where in fact it's a merge of update channel + version.

Sorry for the confusion.
