### ISSUE TITLE
CoreOS documentation: Cluster Bringup and etcd

### ISSUE THREAD

**Issue by scole-scea** [coreos/bugs#350]
Ok, at CoreOSFest today (and yesterday), I heard time and again: don't run your etcd nodes on the same machines that are doing real work. @kelseyhightower ended the day today remarking that it was confusing how many people thought you could just run etcd on every host.

Well.

That's what the CoreOS docs say to do, actually. https://coreos.com/docs/cluster-management/setup/cluster-discovery/

Can we _please_ get some accurate documentation here about how to get etcd running efficiently when what we have is a cluster with a large number of machines?

**Comment by robszumski** [comment]
Have you seen this doc? https://coreos.com/docs/cluster-management/setup/cluster-architectures/

I agree that this experience could be better, and we should definitely have a link to the cluster architectures and a little bit of background on why you need to properly plan out your cluster.

**Comment by scole-scea** [comment]
No, I hadn't seen that actually. Thanks for the pointer. I've clearly got some changes to make to our cluster... ;)

Really what I was pointing out was that the first-seen CoreOS documentation really does lead people down the wrong path, and a clear, up-front description of what the problems might be for the "easy-to-get-running" model would be *extremely* useful.

**Comment by JeanMertz** [comment]
@scole-scea I also made the wrong assumptions in the beginning, based on the mentioned documentation.

Check out [this conversation I had on the `coreos-user` mailing list](https://groups.google.com/d/msg/coreos-user/iE_qRnQETTc/3pzEJaqaSagJ).
