### ISSUE TITLE
regression in docker 1.6.1: cannot mount /sys in container

### ISSUE THREAD

**Issue by jumanjiman** [coreos/bugs#357]
fyi: there is a regression in docker 1.6.1 that affects current coreos alpha channel.
docker cannot mount `/sys` into a container, such as cadvisor.

error message:

```
FATA[0000] Error response from daemon: 
Cannot start container 6e0d00410e368828b02b412f09ccd63545e2cfa7a0ee09b010c48e46e834ad5a: [8] System error: 
"/var/lib/docker/overlay/6e0d00410e368828b02b412f09ccd63545e2cfa7a0ee09b010c48e46e834ad5a/merged/sys/fs/cgroup" 
cannot be mounted because it is located inside "/sys"
```

upstream docker issue: https://github.com/docker/docker/issues/13097

fix in upstream libcontainer: https://github.com/docker/libcontainer/pull/576

possible workaround described here: https://github.com/docker/docker/issues/13097#issuecomment-100632937

**Comment by crawford** [comment]
Introduced in 675.0.0.

**Comment by jumanjiman** [comment]
1.6.2 is imminent:
https://github.com/docker/docker/pull/13133
