### ISSUE TITLE
Installing Mount Helpers in /sbin

### ISSUE THREAD

**Issue by eatnumber1** [coreos/bugs#358]
It's not possible to install mount helpers in `/sbin` due to it being a symlink to the read-only `/usr/sbin`.

A bit of context. If you create a new filesystem, and want to be able to mount it using `mount -t myfs`, the way mount works is that you have to install a binary named `mount.myfs` in `/sbin`. As far as I'm aware, this cannot be changed; the directory that mount searches in is fixed as `/sbin`.

In CoreOS, since `/sbin` is a symlink to `/usr/sbin`, it's not easily possible to install new filesystem mount helpers. A workaround is to delete the `/sbin` symlink, make it a directory, and symlink everything from `/usr/sbin` into `/sbin` at boot. An example unit file for this workaround follows.

```
[Unit]
Description=Make /sbin not a symlink
Requires=network-online.target
After=network-online.target

[Service]
ExecStart=/bin/mkdir -p /opt/bin
ExecStart=/usr/bin/curl -s -L -o /opt/bin/renameat2 https://gist.github.com/eatnumber1/f97ac7dad7b1f5a9721f/raw/3db4dbf58afd8d0024bef298806eec4f77c3e448/renameat2.x86_64
ExecStart=/bin/chmod +x /opt/bin/renameat2
ExecStart=/bin/mkdir /sbin.new
ExecStart=/bin/sh -c 'for f in /usr/sbin/*; do ln -s $f /sbin.new; done'
ExecStart=/opt/bin/renameat2 -e /sbin.new /sbin
ExecStart=/bin/rm -rf /sbin.new
RemainAfterExit=yes
Type=oneshot
```

**Comment by marineam** [comment]
What filesystem are you trying to mount?

**Comment by eatnumber1** [comment]
A FUSE filesystem, [ObjectiveFS](https://objectivefs.com). AFAIK, this is the standard way of installing fuse filesystems as first-class filesystems on the machine.

**Comment by marineam** [comment]
Hm, looks like umount respects `helper=` and `uhelper=` options to change the default path to the helper but mount does not. I'm not sure if extending the meaning of `helper=` would be acceptable in upstream util-linux or not but perhaps worth investigating.

Certainly you can do this without any problem inside sufficiently privileged containers but I don't have a better suggestion for doing this on the base CoreOS system right now.

**Comment by flipchart** [comment]
+1 I've got the same issue with trying to add cifs mount support. Having to fall back to using the mount.cifs binary directly

**Comment by miguelangel-nubla** [comment]
+1
Trying to load glusterfs

**Comment by owenhaynes** [comment]
+1 
trying to load glusterfs as well.

**Comment by mischief** [comment]
can you simply mount --bind the helper in /sbin?

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
