### ISSUE TITLE
Enhancement: vmware OEM image

### ISSUE THREAD

**Issue by olliewalsh** [coreos/bugs#359]
A vmware OEM image that includes the vmware tools OEM partition would be useful. A vmdk is not necessarily the ideal format for all deployments.

As a workaround I'm using a bare-metal coreos-install from the ISO then afterwards mount /dev/sda6 and drop in the contents of the OEM partition that I've extracted from the vmdk image.

**Comment by marineam** [comment]
We also have an ova: http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vmware_ova.ova

Between vmdk and ova that pretty much covers vmware I think. What sort of image are you looking for?

**Comment by marineam** [comment]
(the OVA should work with ESXi and all the fancier products)

**Comment by olliewalsh** [comment]
Not always :-) In one particular deployment I'm presented with a bare VM to be reconfigured - I have full admin rights on the VM, but not on the ESXi/VCenter hosting it (so I can't deploy new VMs from OVA etc..).
The bare-metal/ISO approach seems like easiest option, if only there was an OEM image for vmware.

**Comment by marineam** [comment]
Well, you can convert the vmdk to a raw disk image and write that to disk. coreos-install is just a wrapper around downloading and verifying images via gpg with a little extra to throw in a cloud config file. Not sure if your situation is common enough for us to provide both raw and vmdk images. You'll just need to do the conversion on some system that has a tool for the job like qemu-img

**Comment by olliewalsh** [comment]
Modifying the vmdk image doesn't help in this case. I have a (virtual) disk to install to. I can't easily replace that disk with a different image (I could, but it would be much more effort).

As I said in the summary - it's relatively straightforward to workaround, just need to get the files from the vmdk and onto the OEM partition...

> Not sure if your situation is common enough
Yea, I was wondering that. I doubt this is a extremely rare though. E.g where bare-metal infrastructure is virtualized everyone still thinks in terms of bare-metal hosts so it's ISOs or PXE for OS installs. Maybe I'm wrong...

**Comment by mkuzmin** [comment]
`vmware_image.bin.bz2` artifact with included VMware customizations would be very helpful for deploying to vSphere.
Right now we have to upload OVF-file, and then customize it. Much more robust solution would be creating a new VM from scratch, customize all hardware settings, boot from ISO, and install CoreOS to disk. HashiCorp [Packer](https://packer.io/) automates this procedure.

Unfortunately, calling
```
# coreos-install -d /dev/sda/ -V current -o vmware
```
fails with 
```
/usr/bin/coreos-install: Image URL unavailable: http://stable.release.core-os.net/amd64-usr/current/coreos_production_vmware_image.bin.bz2
```

**Comment by mimmus** [comment]
I have same problem. Booting diskless could be useful on VMware too.

**Comment by jonaz** [comment]
We have this problem aswell. Installing coreos with coreos-install use foreman for PXE and we would like to have vmware tools in our image.

**Comment by pizzarabe** [comment]
What do we need to do, to get that? "Just" building a new image? The Installer already tries to install the image but of course there is no.

**Comment by crawford** [comment]
@pizzarabe nothing. If we decide the patch is acceptable, those images will be built as part of our release process. The install script would then just work.

**Comment by bgilbert** [comment]
We've added a new VM type, `vmware_raw`, which can installed with `coreos-install -o vmware_raw`.  This should go out in the next alpha release.

**Comment by pizzarabe** [comment]
Nice, the latest alpha already got that (1312.0.0). Is there a way to get that to the next stable release?
