### ISSUE TITLE
coreos 647.0.0 dhcp ip renew 

### ISSUE THREAD

**Issue by fragpit** [coreos/bugs#360]
Hello, 
recently some of our coreos servers updated to 647.0.0.  The problem is, that after upadte, each host received new ip address from DHCP. (despite that the lease time is 8 days)
We use dhcp server on windows 2003. 

In dhcp console I see, that older versions have mac-address as UniqID, and 647.0.0 hosts have strange uniqid, such as 2d4a9abc00020000ab115ef58edfe274700b

I found that it is a hex value, and can be converted to ascii, but i get unreadable string after conversion of the ID above. Also, i see, that new UniqID-s have common part, this part depends on which hypervisor CoreOS host is running (we use esxi).

What changes in new version might affect this behaviour?

**Comment by fragpit** [comment]
Seems that problem in DHCP client request, in Option 61
Default ClientIdentifier in DHCP client is duid. 
Need to investigate how to set up 
    ClientIdentifier = mac 
in coreos

**Comment by fragpit** [comment]
After configuring:
```
hostname ~ # cd /etc/systemd/network/
hostname network # cat 20-dhcp.network
[Match]
Name=en*

[Network]
DHCP=yes

[DHCP]
UseMTU=true
UseDomains=true
ClientIdentifier=mac
```

i see an error 
```
May 14 14:28:05 hostname systemd-networkd[492]: [/etc/systemd/network/20-dhcp.network:10] Unknown lvalue 'ClientIdentifier' in section 'DHCP'
```

Current systemd-networkd doesn't support this parameter?

**Comment by Telvary** [comment]
Facing the same issue. Looks like this option is only supported in systemd 220 : http://lists.freedesktop.org/archives/systemd-devel/2015-May/032147.html
```
        * systemd-networkd gained support for configuring the DHCP
          client identifier to use when requesting leases.
```

So we have to for systemd 220 in CoreOS... anytime soon I hope :)

**Comment by Telvary** [comment]
Ok, this configuration is working _but_ the problem is that the file containing the configuration is written after networkd is started :
```
Jul 28 16:56:34 localhost systemd[1]: Starting Network Service...
(...)
Jul 28 16:56:35 localhost coreos-cloudinit[791]: 2015/07/28 16:56:35 Writing file to "/etc/systemd/network/20-dhcp.network"
Jul 28 16:56:35 localhost coreos-cloudinit[791]: 2015/07/28 16:56:35 Wrote file to "/etc/systemd/network/20-dhcp.network"
Jul 28 16:56:35 localhost coreos-cloudinit[791]: 2015/07/28 16:56:35 Wrote file /etc/systemd/network/20-dhcp.network to filesystem
```

If you do a systemd-networkd restart a few seconds later then you get the expected DHCP reply as the configuration is now correctly used.

**Comment by crawford** [comment]
This is a limitation of coreos-cloudinit. If you write the configuration via Ignition instead, it will work out of the box.
