### ISSUE TITLE
Add DNS troubleshooting utility outside the toolbox

### ISSUE THREAD

**Issue by jedsmith** [coreos/bugs#361]
One of `dig` or `host` would be extremely useful in the CoreOS base environment. As it stands, there is no ability to debug DNS from the perspective of the CoreOS machine. Since the base environment contains `curl`, I feel that the inclusion makes sense.

Both `dig` and `host` come from one package under Fedora, so you'll probably end up with both.

**Comment by jedsmith** [comment]
Relatedly, is there any ability to clear `systemd-resolved`? I could not find one.

**Comment by marineam** [comment]
Fixed in https://github.com/coreos/coreos-overlay/pull/1426

**Comment by jedsmith** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:
