### ISSUE TITLE
docker0 looses link state?  

### ISSUE THREAD

**Issue by hookenz** [coreos/bugs#362]
I have a bare metal node that for some reason keeps loosing it's link or something.

I think it's related to this issue.  https://github.com/coreos/bugs/issues/122

What I'm seeing is the following, over and over again and has led to some instability for some apps like couchbase.

![screen](https://cloud.githubusercontent.com/assets/6227712/7673930/b9d5ad96-fd70-11e4-8d13-a56c0a362586.jpg)

**Comment by pmoust** [comment]
Experiencing the same on EC2,
Screenshot from a session on 3 CoreOS 766.4.0 nodes
![screenshot 2015-10-10 02 12 02](https://cloud.githubusercontent.com/assets/2493339/10407648/9838aec0-6ef6-11e5-8ad4-7c08e5efbd54.png)

**Comment by mischief** [comment]
i don't see here where a problem with docker0 is. i'm pretty sure this is just the docker containers starting and stopping, and their bridge ports follow suit.

**Comment by pmoust** [comment]
@mischief I stand corrected. Of course it's the containers starting/stopping, it's late here at EEST ;)

**Comment by hookenz** [comment]
Turns out it's normal I think.    I was assuming this error was the symptom of another.  It wasn't.
