### ISSUE TITLE
ntpd ignores /etc/ntp.conf

### ISSUE THREAD

**Issue by eaoliver** [coreos/bugs#363]
The instructions at: https://coreos.com/docs/cluster-management/setup/configuring-date-and-timezone/  appear to be incorrect.

I have configured a custom ntp.conf file; however, CoreOS continues to query the default *.coreos.pool.ntp.org NTP servers.

I am running CoreOS alpha (681.0.0)

The cloud-config parameters are below: 

coreos:
   units:
    - name: settimezone.service
      command: start
      content: |
         [Unit]
         Description=Set the timezone

         [Service]
         ExecStart=/usr/bin/timedatectl set-timezone UTC
         RemainAfterExit=yes
         Type=oneshot

write_files:
 - path: /etc/ntp.conf
   content: |
      # Common pool
      server 10.0.0.10

      # - Allow only time queries, at a limited rate.
      # - Allow all local queries (IPv4, IPv6)
      restrict default nomodify nopeer noquery limited kod
      restrict 127.0.0.1
      restrict [::1]
      restrict 10.0.0.10 mask 255.255.255.255 nomodify notrap noquery

**Comment by marineam** [comment]
Ugg, sorry. I forgot to update that documentation page. ntpd is no longer running by default in alpha, instead using systemd-timesyncd. You can configure it like so: http://www.freedesktop.org/software/systemd/man/timesyncd.conf.html

Also you can switch back to ntpd:

```
systemctl stop systemd-timesyncd
systemctl mask systemd-timesyncd
systemctl enable ntpd
systemctl start ntpd
```

**Comment by eaoliver** [comment]
@marineam Thanks

**Comment by robszumski** [comment]
@marineam Please update that doc!

**Comment by marineam** [comment]
@robszumski https://github.com/coreos/docs/pull/499
