### ISSUE TITLE
Control characters rendered as hex in `systemctl status` pager

### ISSUE THREAD

**Issue by pwaller** [coreos/bugs#365]
Steps to reproduce: run `sudo systemctl status` on CoreOS alpha 681.0.0 from an EC2 image. (It seems to happen on all images I've tested). I've searched around a bit but can't see any clear reason this might happen.

My TERM is set to `xterm-color`, but changing this doesn't seem to have any impact on the problem.

The output looks like this:

```
   State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Tue 2015-05-19 10:36:44 ; 1 day 23h ago
   CGroup: /
           <E2><94><9C><E2><94><80>1 /usr/lib/systemd/systemd --switched-root --system --deserialize 12
           <E2><94><94><E2><94><80>system.slice
             <E2><94><9C><E2><94><80>dbus.service
             <E2><94><82> <E2><94><94><E2><94><80>496 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
             <E2><94><9C><E2><94><80>update-engine.service
             <E2><94><82> <E2><94><94><E2><94><80>491 /usr/sbin/update_engine -foreground -logtostderr
```

**Comment by mischief** [comment]
@pwaller have you tried a different terminal emulator? these characters are utf8 encoded line drawing characters (like '├'). maybe your terminal cannot render utf8 or the font does not have support for these characters.

**Comment by mischief** [comment]
it looks like this is caused by sudo not preserving `LESSCHARSET=utf-8`.

**Comment by mischief** [comment]
you can get sudo to preserve it by using `sudo -E systemctl status`, or you could ask systemctl for `--no-pager` mode.

**Comment by pwaller** [comment]
Nice sleuthing @mischief. Any chance of this being a default, or some way of avoiding needing the user to configure this? I don't want to have to teach each sysadmin this, and it's nice to stay as close to the base coreos image as possible. If not, I guess this can be closed? Thanks!
