### ISSUE TITLE
Docker containers with --restart=always not auto-started on reboot (+fix)

### ISSUE THREAD

**Issue by cknitt** [coreos/bugs#369]
I am running several docker containers on a single CoreOS instance on EC2. I am not using systemd services, but rather starting the containers using ansible with the `--restart=always` option set.

However, when I reboot the instance, the containers are not auto-started - until I log in via ssh and issue the "docker ps" command which finally triggers their start.

Via [this blog post](http://daviddaeschler.com/2014/12/14/centos-7rhel-7-and-docker-containers-on-boot/), I found that CentOS 7 exhibits similar behavior and that the reason is that the docker service is started before the network is actually up.

To fix this, I copied the docker.service definition from /usr/lib/systemd/system/docker.service to /etc/systemd/system to override it and added network-online.target in `After` and `Wants` in the `[Unit]` section:

```
[Unit]
...
After=docker.socket early-docker.target network.target network-online.target
...
Wants=network-online.target
...
```

Can you include this change directly in /usr/lib/systemd/system/docker.service in the next CoreOS release? Or are there any adverse effects it might have?

**Comment by crawford** [comment]
On CoreOS, Docker is socket-activated by default. This means that Docker will not start until it's needed. So on reboot, the Docker daemon will not start until you, in your case, run `docker ps`. You just need to start docker.service from your cloud-config to ensure that it always runs.

```yaml
#cloud-config

coreos:
  units:
    - name: docker.service
      command: start
```

**Comment by cknitt** [comment]
Thanks a lot! I just tested your solution and it works fine. :-)

However, if the Docker daemon does not start at all until triggered by `docker ps` or the cloud config, then I don't understand why my solution with the dependency on network-online.target did actually work.
