### ISSUE TITLE
AWS CoreOS AMI borked SSL certificates

### ISSUE THREAD

**Issue by pires** [coreos/bugs#374]
I need to run `sudo update-ca-certificates` in order to be able to use AWS EC2 certificates (at least) from any CoreOS AMI tested so far (latest, 695.0.0).

**Comment by marineam** [comment]
I don't follow. Are you adding a cert to /etc/ssl/certs? We don't ship any AWS specific certs ourselves.

**Comment by marineam** [comment]
NM, I spotted the conversation on IRC. Sounds like `/etc/ssl/certs/ca-certificates.crt` which is normally a symlink to a read-only copy under /usr was missing or broken. Running update-ca-certificates regenerates that as a plain file. Will check on this...

**Comment by pires** [comment]
@marineam thank you for making sense of this and for looking at a fix.

**Comment by marineam** [comment]
@pires looks fine to me:

```
$ ls -l /etc/ssl/certs/ca-certificates.crt 
lrwxrwxrwx 1 root root 54 May 28 00:46 /etc/ssl/certs/ca-certificates.crt -> ../../../usr/share/ca-certificates/ca-certificates.crt
$ openssl x509 -in /etc/ssl/certs/ca-certificates.crt -text
Certificate:
[blah blah blah blah blah]
```

What specific region/ami was broken for you? Can you reproduce it with a fresh instance?

Note: if you are doing something with a container that is bind mounting /etc/ssl/certs/ca-certificates.crt into the container that will not work if it is a symlink. That does trip people up from time to time.

**Comment by pires** [comment]
@marineam I ran my test with CoreOS AMI 965.0.0-hvm.

My app did fail with `docker (...) -v /etc/ssl/certs:/etc/ssl/certs my-image`, but got fixed by running `sudo update-ca-certificates`. Now it works flawlessly.

**Comment by marineam** [comment]
Ah, yes. that would be the problem then. /etc/ssl/certs just contains symlinks to /usr by default so if you bind mount it you just get a pile of broken symlinks. Since you only need ca-certificates.crt for Go apps running update-ca-certificates fixed it because that replaces the ca-certificates.crt symlink with a fresh regular file. Alternatively you could bind mount /usr/share/ca-certificates

**Comment by marineam** [comment]
Filed https://github.com/coreos/bugs/issues/375 to further clean up /usr/share/ca-certificates which I've been meaning to do but haven't gotten to yet.
