### ISSUE TITLE
kernel: stable: reported panic

### ISSUE THREAD

**Issue by philips** [coreos/bugs#378]
tsunanet: @coreoslinux w/ stable: occasionally seeing this kernel panic upon booting without this fix: https://t.co/vqQVBDkpfH http://t.co/W0AAITPUCw

![](https://pbs.twimg.com/media/CHMLP54UYAMW2g-.png:large)

https://twitter.com/tsunanet/status/608842742848823296

Proposed fix: https://github.com/torvalds/linux/commit/820f9f147dcce2602eefd9b575bbbd9ea14f0953

**Comment by marineam** [comment]
Included in v4.0.5. We were already planning to expedite pushing that to all channels, looks like we have yet another reason to do so :(

**Comment by tsuna** [comment]
Thanks for filing the bug report on my behalf.  I feel almost dumb to not have done this myself, duh.

**Comment by crawford** [comment]
This should be fixed in Alpha which is rolling out right now. We will backport the 4.0.5 kernel to Beta and Stable next week.

**Comment by anothermh** [comment]
If this means the 681 stable release was pulled and that the current stable release is 647, it would be great if the page https://coreos.com/releases/ were updated to reflect that. I've spent a lot of time trying to figure out why I can't force the upgrade and communication about the available releases would have saved me a lot of time. Others have the same problem: http://stackoverflow.com/questions/30784178/coreos-partial-cluster-update

**Comment by arbourd** [comment]
The releases page has been updated with `681.1.0` that fixes this issue.

@anothermh makes an excellent point though: I spent sometime trying to figure out why my instance wouldn't update as well. A note for pulled releases would be great in the future.

**Comment by tsuna** [comment]
I must admit I also found it harder-than-necessary to tell both 1. what is the current exact version of each channel (since the releases page seems to often lag behind a bit) and 2. given a freshly downloaded image, what version is it – the only way I found to answer this question was to boot it.

**Comment by crawford** [comment]
https://coreos.com/releases/ shows the latest version available on each channel. In rare cases, like this one, the latest version available may be newer than the latest version our update servers are offering. 

Consider the case that there is an upgrade bug that prevents us from updating from version 1 to version 2. https://coreos.com/releases/ would show version 2, while the update servers would hold at version 1. Once version 3, which fixes the update bug, is released, both https://coreos.com/releases/ and the update servers would show version 3. There is no reason to hold back version 2; it only affects upgrades from version 1, not newly provisioned machines.

**Comment by crawford** [comment]
The 4.0.5 kernel is now in all three channels.
