### ISSUE TITLE
update-engine server should push a more recent release instead of "no update" for latest

### ISSUE THREAD

**Issue by carmstrong** [coreos/bugs#38]
I'm running update engine on a CoreOS 310 machine subscribed to the alpha channel. I'm getting a "no update" response from the update server, even though there are several more recent releases.

I asked @philips on IRC, and he said that the update server won't always push the latest update, as it's being rolled out slowly. I think the update server should:
- Update clients to a more recent release, even if a newer update is available but is being rolled out (presumably, a slightly newer release has been more fully tested)
- A more descriptive error than "no update" should be returned, as this isn't really the existing condition

```
<carmstrong> is there any reason why running update-engine on 310 alpha channel returns "no update"? trying to get to 324
<philips> carmstrong: the update server doesn't hand out the updates to all clients at once in case there are bugs, etc
<carmstrong> philips: all clients in the same etcd cluster? this is the only one on which update-engine is running
<philips> carmstrong: so there is a server that the update_engine talks to to ask for updates
<philips> carmstrong: when it asks the server may not tell it the latest version because it is slowly rolling out the update to everyone.
<carmstrong> philips: I suppose that makes sense. but why not update the client to a slightly more recent release, which has been rolled out to many servers by this point? the latest may not have been tested, but a super-old client could get a more up-to-date release
<philips> carmstrong: yea, we should add that logic, I agree.
```

**Comment by crawford** [comment]
This was fixed a while ago. `update_engine -client` will bypass the rate-limiting.
