### ISSUE TITLE
CoreOS Stable has wrong etcd version, or should document v2?

### ISSUE THREAD

**Issue by technicool** [coreos/bugs#380]
I started up a cluster on AWS, and ran the following:

    # curl http://169.254.169.254/1.0/meta-data/ami-id && echo && etcd --version && fleet --version
    ami-79ad4712
    etcd version 0.4.9

According to https://coreos.com/docs/running-coreos/cloud-providers/ec2/ the `ami-79ad4712` image is HVM of CoreOS 681.0.0. However, the Release Notes show `etcd: 2.0.10`

**Edit:** I see an etcd2 daemon and service, but there is no documentation that states to use that in a cloud-init for starting the latest version. Am I missing something?

**Comment by crawford** [comment]
681.0.0 includes both `etcd` (0.4.9) and `etcd2` (2.0.10). It is a bit confusing from the release notes. I'll see if I can make that more clear.

**Comment by technicool** [comment]
Thanks!

**Comment by crawford** [comment]
The release notes on https://coreos.com/releases now shows both versions.
