### ISSUE TITLE
can't upgrade from 647.2.0 (prior stable) to 681.0.0 (latest stable)

### ISSUE THREAD

**Issue by cstivers78** [coreos/bugs#383]
_Note: About a month or so ago, I upgraded to 647.2.0 with out fail._

I saw 681.0.0 is now stable, so I wanted to be sure I was on it.

First, I checked to see what version I was on (I have bad memory and don't trust myself):
```
core@core3 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=647.2.0
VERSION_ID=647.2.0
BUILD_ID=
PRETTY_NAME="CoreOS 647.2.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

No problem, probably means update was not done automatically. I expect it to not be.

Next, I checked update_engine's status and it says it has update ready... 

```
core@core3 ~ $ update_engine_client -status
[0611/223211:INFO:update_engine_client.cc(235)] Querying Update Engine status...
LAST_CHECKED_TIME=1433484000
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATED_NEED_REBOOT
NEW_VERSION=0.0.0.0
NEW_SIZE=130324060
```

Cool! Maybe it will boot into 681.0.0?! Wasn't sure what would happen, so I rebooted.

After reboot, I checked status:

```
core@core3 ~ $ sudo update_engine_client -status
[0611/230442:INFO:update_engine_client.cc(235)] Querying Update Engine status...
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0.0
NEW_SIZE=0
```

Nothing useful there... so I checked the version:

```
core@core3 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=647.2.0
VERSION_ID=647.2.0
BUILD_ID=
PRETTY_NAME="CoreOS 647.2.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

Doh! It did not upgrade. Ok, maybe I do need to perform a manual upgrade...

```
core@core3 ~ $ sudo update_engine_client -update
[0611/230448:INFO:update_engine_client.cc(245)] Initiating update check and install.
[0611/230448:INFO:update_engine_client.cc(250)] Waiting for update to complete.
LAST_CHECKED_TIME=0
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0.0
NEW_SIZE=0
[0611/230453:ERROR:update_engine_client.cc(189)] Update failed.
```

Just to be sure nothing happened, I checked `status` and `os-release` and they hadn't changed.

**Comment by cstivers78** [comment]
I suspect it things it has the latest stable, which probably means whatever it checks to get the latest stable is mismatched with what is published on the website? Or maybe my machine is just busted.

**Comment by crawford** [comment]
The stable channel is currently paused (we've received a few too many bug reports). update-engine is correctly reporting that there are no upgrades available. If you really want to try the new Stable, you can provision a new instance using the latest image.

**Comment by cstivers78** [comment]
I would rather just go through the "normal" update process.
Is there a pre-existing ticket for this issue that I can follow to be kept up-to-date? 
Or will this ticket be kept open and be updated when this is resolved?

Either way works for me.

**Comment by crawford** [comment]
This is the major issue holding up the release: https://github.com/coreos/bugs/issues/378. I'm going to close this and let you follow the other bug.

**Comment by jsoriano** [comment]
Hi @crawford, is there any way to check if current stable channel is paused?
We are currently having this issue, update_engine_client doesn't update to 1122.2.0.

**Comment by crawford** [comment]
There is no way to check (yet). We are working on exposing an API so it can be queried, but for now you'll have to bug me.

We are not yet rolling the stable release. It should go later today.

**Comment by crawford** [comment]
@jsoriano Stable is now rolling 1122.2.0.

**Comment by jsoriano** [comment]
Thanks!

**Comment by shpin** [comment]
Today i'm have same problems with different versions of CoreOS.
There is no update for stable versions (that i tried) 1068.10.0 and 1068.9.0 and multiple alpha versions.

Response from https://public.update.core-os.net/v1/update/:
<?xml version="1.0" encoding="UTF-8"?>
<response protocol="3.0" server="update.core-os.net">
 <daystart elapsed_seconds="0"></daystart>
 <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
  <updatecheck status="noupdate"></updatecheck>
 </app>
</response>

**Comment by crawford** [comment]
@shpin See https://github.com/coreos/bugs/issues/1544. You'll need to use `update_engine_client -update`.

**Comment by jtower525** [comment]
and when update_engine_client -update fails, as it does for me?

**Comment by crawford** [comment]
This is a different issue. Would you mind opening a new bug? The output of `journalctl -b -u update-engine --no-pager` will be useful.
