### ISSUE TITLE
Might the CoreOS GPG key have expired?

### ISSUE THREAD

**Issue by mkbhanda** [coreos/bugs#388]
When we use the key https://coreos.com/security/image-signing-key/ in OpenStack Ironic, logs indicate it is expired. Alternately,  is OpenStack checking for expiration incorrectly?
Please see Fix https://review.openstack.org/#/c/191313/ for original bug: https://launchpad.net/bugs/1463632

**Comment by marineam** [comment]
The previous signing sub-key expired back in September. The key you link to includes the current signing sub key so as long as you refresh your copy you should be good to go.
