### ISSUE TITLE
Manual management of OS update

### ISSUE THREAD

**Issue by korya** [coreos/bugs#393]
The most recent automatic upgrade to 681.2.0 made my last Sunday really unforgettable, I've spent couple hours debugging my cloud config and trying to figure out what's going on and why it stopped working after the upgrade.

In order to make our life a little bit more predictable we've decided to manage CoreOS updates manually. In order to achieve this I need to be able to make 2 basic operations:
 1. perform update
 2. perform a rollback to the old version

To perform an update, I can use `update_engine_client` and it's good.

My main problem is that I don't know how to perform the rollback operation.

As I understand, update_engine has some logic to automatically rollback bad updates. But my set of bad updates is much larger of the one defined by CoreOS team. In my case, running CoreOS with misconfigured docker daemon is considered a failed update, while CoreOS considers it as a successful update.

Is there a way to rollback an update manually?

PS. I've disabled `update_engine` service.

**Comment by crawford** [comment]
Manual rollbacks can *usually* be done by following [this guide](https://coreos.com/docs/cluster-management/debugging/manual-rollbacks/). Note that this is not guaranteed to be available and is more useful for debugging.

I encourage you to take a look at https://coreos.com/products/. CoreUpdate will make it a lot easier to manage updates for your cluster (this is what we use internally to delivery updates globally).

**Comment by korya** [comment]
Thanks, that's exactly what I need.

I think CoreUpdate is an overkill for us. At least for the near future.
