### ISSUE TITLE
Exit Status : 127 - When tried to Run rkt on emulator

### ISSUE THREAD

**Issue by smileynewbie123** [coreos/bugs#394]
Hi,

I am new to coreos/rkt and yocto. So i am trying to run rkt on yocto generated core image.

I copied "rkt" , "hello.aci" and "stage1.aci" binaries to target Rootfs and generated core minimal image.

I Ran that image in emulator  by "runqemu kvm qemux86-64", and logged into emulator linux system ( which was generated by using yocto, as stated above).

So on target emulator i ran this command.

# cd  /home    - ( i copied , rkt, hello.aci, stage1.aci to this dir)
#cp  stage1.aci /lib/
# /lib/ld-linux-x86-64.so.2 ./rkt --debug=true --insecure-skip-verify run hello.aci

Error Message:
rkt fetching image from file:///lib/stage1.aci
rkt fetching image from file:///home/hello.aci
[DATE TIME] Preparing stage1
run: error setting up stage0: error preparing stage1: error rendering tree image:treestore: cannot render aci:error extracting ACI: extracttar error: exit status 127, Output: /var/lib/rkt/cas/tree/sha512-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:error while loading libraries: /var/lib/rkt/cas/tree/sha512-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: Cannot read file data : Error 21

So, what is this error means, do i need to copy anything else?

Please let me know

**Comment by jonboulle** [comment]
This issue was moved to coreos/rkt#1084
