### ISSUE TITLE
Enable r8152

### ISSUE THREAD

**Issue by hinnerk** [coreos/bugs#398]
For our bare metal installation we'd like support for the Realtek  RTL 8152  USB2.0 to 10/100M Fast Ethernet Controller. So would it be possible to enable `r8152` in the kernel config?

**Comment by marineam** [comment]
We currently don't enable any USB ethernet devices but we could depending on the need. What soft of deployment is this?

**Comment by hinnerk** [comment]
We'd like use CoreOS as OS on our custom build consumer hardware (small servers). We expect the eventual number of devices to reach 100.000.

While this isn't a conventional data center installation it can be described as a massively distributed data center. :)

**Comment by hinnerk** [comment]
Any news on this?

**Comment by marineam** [comment]
Sorry, missed your earlier reply. I'll go ahead and add the USB devices in
next week's alpha.

**Comment by crawford** [comment]
@marineam can this be closed now?

**Comment by marineam** [comment]
No, I forgot about it :( :(

**Comment by hinnerk** [comment]
Actually we can close it as we're building our own CoreOS images now.
