### ISSUE TITLE
Enable rtl8723bs and rtl8723au_bt

### ISSUE THREAD

**Issue by hinnerk** [coreos/bugs#399]
On our bare metal installations we'd like to use a Realtek RTL8723au USB2.0 Wifi ABGN Controller and a Realtek RTL8723bs SDIO Wi-Fi ABGN Controller. Would it be possible to enable the `rtl8723bs` and `rtl8723au_bt` kernel options?

**Comment by marineam** [comment]
We do not currently ship any wifi drivers or tools to configure wifi since servers are what we target. Doubt it is a direction we want to go right now.

**Comment by hinnerk** [comment]
Same hardware as in #398 – custom build consumer hardware (small servers).
