### ISSUE TITLE
/etc/environment values should be configurable via cloud-config

### ISSUE THREAD

**Issue by jsierles** [coreos/bugs#40]
On some platforms, like bare metal or those without private network interfaces, COREOS_PRIVATE_IP and COREOS_PUBLIC_IP are not set correctly for software like etcd. Maybe they should be configurable in cloud-init, since they are overrwitten on every server reboot.

**Comment by hmatinho** [comment]
That works but environment files won't be sourced ... is there a way to source them ? creating a oneshot service with ExecStart=/usr/bin/bash -a -c "source /etc/environment" doesn't seem to work.

**Comment by crawford** [comment]
That command works fine; it just didn't do what you want. When bash sources that file, the variables only persist for that instance.

Follow @robszumski's suggestion and use `EnvironmentFile`.

**Comment by hmatinho** [comment]
Hi Alex, i did use the EnvironmentFile setting but what i'm trying to do is to get the env variables in the environment file available in coreos shell so that i can do echo $PRIVATE_IP_ADDRESS for example in the shell and get the value for usage in a confd template file

**Comment by crawford** [comment]
There is no need to wrap the call to systemctl in a bash shell. On top of that, set-environment doesn't affect your interactive shell (I assume this is where you want the variable). Write the variable to your .bashrc. You can use the `write_files` section in your cloud-config.

**Comment by hmatinho** [comment]
Indeed it is Alex, thanks will do.
________________________________
