### ISSUE TITLE
"tail -f" doesn't follow

### ISSUE THREAD

**Issue by technicool** [coreos/bugs#401]
Using CoreOS 681.0.0 on AWS (m3.medium), and found out that tailing isn't working, whereas it does in docker on an ubuntu machine.

The host step to get started is `docker run -it --rm ubuntu:14.04`

Then, run the following:

    touch /hi
    tail -f /hi &
    echo Hello >> /hi && sleep 3

Expected output should show "Hello" on the console. This does occur when the host machine is an ubuntu box.

Actual output: just the cursor at the end of a shell prompt.

Extra variations:

* `tail -f --follow=name /hi`
* `tail -f --follow=descriptor /hi`

It looks like this may be an issue related to inotify or inode hooks in the kernel that are different for CoreOS vs Ubuntu 14.04. Is this a known issue elsewhere?

Multiple machines of the following types were tested:

*  stock Ubuntu with `Docker version 1.6.2, build 7c8fca2`
*  stock CoreOS with `Docker version 1.6.2, build 7c8fca2-dirty`

**Comment by mischief** [comment]
hi @technicool, this is actually a known issue. see https://github.com/docker/docker/issues/11705

**Comment by technicool** [comment]
Ah... is there another backend that does work, since Ubuntu is doing it correctly?

**Comment by mischief** [comment]
@technicool you can run `docker info` to print the storage driver. this is a known problem with overlay. you can use btrfs on coreos, and there is a guide for doing so at [mounting storage](https://coreos.com/docs/cluster-management/setup/mounting-storage/). btrfs of course has it's own problems.

**Comment by crawford** [comment]
It is now also possible to reformat your root filesystem using [Ignition](https://coreos.com/ignition/docs/latest/examples.html#reformat-the-root-filesystem).
