### ISSUE TITLE
Documentation on timezones is wrong

### ISSUE THREAD

**Issue by devurandom** [coreos/bugs#403]
The [CoreOS date and time documentation] says:
```
To avoid time zone confusion and the complexities of adjusting clocks for daylight saving time it’s recommended that all machines in a CoreOS cluster use Coordinated Universal Time (UTC). This is the default.
```

However, all my CoreOS systems shipped like this:
```
$ timedatectl status
      Local time: Thu 2015-07-02 15:59:25 
  Universal time: Thu 2015-07-02 15:59:25 UTC
        RTC time: Thu 2015-07-02 15:59:25
       Time zone: n/a (, +0000)
     NTP enabled: no
NTP synchronized: yes
 RTC in local TZ: no
      DST active: n/a
```

I am running CoreOS 681.2.0 on bare-metal. This is an upgrade from 647.???, which was the originally installed version.

[CoreOS date and time documentation]: https://coreos.com/docs/cluster-management/setup/configuring-date-and-timezone/

**Comment by marineam** [comment]
+0000 is in fact UTC, perhaps the /etc/localtime symlink is missing instead of pointing to /usr/share/zoneinfo/UTC. I think we shipped a few versions that neglected to explicitly set the symlink but the default time without it is still UTC.

**Comment by marineam** [comment]
I can confirm that this is fixed in current images and the timezone is properly named 'UTC':
```
core@coreos_production_pxe-735-0-0-20 ~ $ timedatectl 
      Local time: Thu 2015-07-09 00:29:11 UTC
  Universal time: Thu 2015-07-09 00:29:11 UTC
        RTC time: Thu 2015-07-09 00:29:11
       Time zone: UTC (UTC, +0000)
 Network time on: no
NTP synchronized: no
 RTC in local TZ: no
core@coreos_production_pxe-735-0-0-20 ~ $ date
Thu Jul  9 00:29:17 UTC 2015
```

**Comment by devurandom** [comment]
Which version are the "current images" you refer to? When will they hit stable?
