### ISSUE TITLE
Broken network support in systemd networkd+nspawn

### ISSUE THREAD

**Issue by LEW21** [coreos/bugs#404]
Nspawn-based containers executed on CoreOS (with systemd-nspawn@.service) currently are unable to access the network. There are 2 reasons:
1. /usr/lib/systemd/network/50-docker-veth.network has a higher priority than systemd's 80-container-ve.network - which means it's used instead of the systemd's one, and networkd does not try to setup the containers network.
   - This can be easily workarounded by symlinking 80-container-ve.network to /etc/systemd/network/40-container-ve.network, so it's not a big problem (but still probably should get fixed).
2. systemd-networkd is built without iptables support ("nat" portage flag), which means it's unable to provide IP masquerading support for containers.
   - This is a deal breaker, as manually setting up masquerading is quite hard.

**Comment by mischief** [comment]
@LEW21 can you give a simple example to reproduce the problem?

**Comment by LEW21** [comment]
```sh
cd /var/lib/machines
mkdir archlinux
cd archlinux
wget http://lew21.net/archlinux.tar.xz
tar -xf archlinux.tar.xz

machinectl start archlinux
machinectl login archlinux
#archlinux login: root
#Password: a
ping 8.8.8.8
```

Without the first part, networkctl reports "degraded" status:
```sh
networkctl status -a # on host
```

Without the second part, networkd cries about IP masquerading:
```sh
journalctl -u systemd-networkd -b
# Output contains: ve-archlinux: Could not enable IP masquerading: Operation not supported
```

**Comment by mischief** [comment]
@LEW21 have you tried to reproduce this since nat flag was enabled?

**Comment by LEW21** [comment]
Flag fixed the 2nd problem, and I'm now constantly using nspawn containers on CoreOS.

However, the 1st problem still exists (and I'm using the symlink workaround).

**Comment by mischief** [comment]
do you know what (if anything) happens to docker containers launched when you make that symlink?

i'm worried that if it is changed, there will be unintended side effects for other folks.

**Comment by LEW21** [comment]
container-ve.network matches devices named "ve-*", and docker calls them "veth*" - so they never get matched, and those settings are not applied to them.

Therefore there should be no side effects.

**Comment by crawford** [comment]
Yeah, let's move Docker to /usr/lib/systemd/network/81-docker-veth.network.
