### ISSUE TITLE
Disable dhcp definitely

### ISSUE THREAD

**Issue by Smana** [coreos/bugs#407]
Hi,
i'm looking for a way to disable the dhcp.
Please find my cloud-config file here : 
https://gist.github.com/Smana/d337d6e987261fd60b0d

each time i start the server i got the following configuration.
A mix of static and dynamic ip configuration
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:a2:99:99 brd ff:ff:ff:ff:ff:ff
    inet 10.115.200.90/16 brd 10.115.255.255 scope global dynamic eth0
       valid_lft 15514sec preferred_lft 15514sec
    inet 10.115.77.86/16 brd 10.115.255.255 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fea2:9999/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether 7a:a8:12:ea:6e:d9 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::78a8:12ff:feea:6ed9/64 scope link 
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 4e:78:4b:34:06:f5 brd ff:ff:ff:ff:ff:ff
    inet 10.244.19.0/16 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::4c78:4bff:fe34:6f5/64 scope link 
       valid_lft forever preferred_lft forever
```
routes
```
default via 10.115.255.253 dev eth0  proto static 
10.0.0.0/8 via 10.115.255.254 dev eth0  proto static 
10.115.0.0/16 dev eth0  proto kernel  scope link  src 10.115.200.90 
10.244.0.0/16 dev flannel.1  proto kernel  scope link  src 10.244.19.0 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1 
192.168.0.0/17 via 10.115.255.254 dev eth0  proto static
```
Thank you for your help
Smana

**Comment by crawford** [comment]
The current implementation of coreos-cloudinit requires network, in most cases, to fetch the cloud-config. As a result, there is no good way of writing a network config on first boot. Your best bet is to either:

- Add a service which takes down all of the interfaces and restart networkd
- Write the network units to /etc and then reboot
- Wait for [Ignition](https://github.com/coreos/ignition/) to land in the image (should just be a couple weeks)

**Comment by Smana** [comment]
Thank you Crawford.

-Add a service which takes down all of the interfaces and restart networkd

- Write the network units to /etc and then reboot

Could you please help me to achieve one of these options? 
Do i have to change my cloud config file?

i guess i'm not the only guy who wants to configure a static address. maybe there's a recommended way?

regards,
Smana

**Comment by crawford** [comment]
> Could you please help me to achieve one of these options? 

You'll want something like this in addition to your existing config.

```yaml
#cloud-config

coreos:
  units:
    - name: systemd-networkd.service
      command: stop
    - name: down-interfaces.service
      command: start
      content: |
        ip link set eth0 down
        ip addr flush dev eth0
    - name: systemd-networkd.service
      command: start
```

**Comment by Smana** [comment]
Excellent! thank you crawford, and my new configuration solve anothe issue : 
https://github.com/coreos/flannel/issues/247

please find my working configuration : 
https://gist.github.com/Smana/6518172dd818fbe79716

**Comment by baracoder** [comment]
the workaround to take down the interface looks hacky

**Comment by crawford** [comment]
@baracoder it is. Use [Ignition](https://coreos.com/ignition) instead.
