### ISSUE TITLE
How to embed /run/systemd/system/etcd2.service.d/20-cloudinit.conf ?

### ISSUE THREAD

**Issue by Dynom** [coreos/bugs#409]
The file `/run/systemd/system/etcd2.service.d/20-cloudinit.conf` contains all the information I need regarding Etcd's connection strings. Most snippets and online examples I see, simply hard-core the ports. This is not something I prefer. How can I make the contents of `20-cloudinit.conf` available in my unit file?
I've tried the obvious:

EnvironmentFile=/run/systemd/system/etcd2.service.d/20-cloudinit.conf

However since `20-cloudinit.conf` contains the following syntax, it's not supported by Systemd (as it expects `key="value"` and not `Environment="key=value"`, if I understand correctly. http://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=)

contents of 20-cloudinit.conf:
```
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://10.29.115.197:2379,http://10.29.115.197:4001"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/a9d42be514b49f04f02479ec1e151b03"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.29.115.197:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://10.29.115.197:2380"
```

In my unit file I'd like something like this:
```
..
EnvironmentFile=/run/systemd/system/etcd2.service.d/20-cloudinit.conf

ExecStartPre=/usr/bin/echo "ETCD_MACHINES=${ETCD_ADVERTISE_CLIENT_URLS}"
..
```

Original question was asked here: https://github.com/coreos/etcd/issues/3110

**Comment by mischief** [comment]
`/run/systemd/system/etcd2.service.d/20-cloudinit.conf` is a systemd drop-in. see `Example 2. Overriding vendor settings` at [systemd.unit](http://www.freedesktop.org/software/systemd/man/systemd.unit.html).

you could make a symlink from `/etc/systemd/system/some-etcd-client.service.d/etcd2.conf` to `/run/systemd/system/etcd2.service.d/20-cloudinit.conf`. i believe you would need to somehow call `systemctl daemon-reload` for this to have effect, though.

**Comment by Dynom** [comment]
I could do that, but it feels like a work around. I think that this should be properly exposed.

Many services depend on Etcd and basically everybody composes the myriad of "ETCD_MACHINES" variables by hand, for the myriad of services that require an Etcd backend.

**Comment by crawford** [comment]
The contents of that file are already available. It is a systemd drop-in which is automatically loaded and prepended to the service of the same name. You can see this via `systemctl cat etcd2`.

**Comment by Dynom** [comment]
So why isn't it available in my units, am I missing something? or do I need to include something?

**Comment by crawford** [comment]
It sounds like systemd is behaving properly. What exactly is the issue?

**Comment by Dynom** [comment]
The issue is that I'd like `${ETCD_ADVERTISE_CLIENT_URLS}` to be populated in my unit files, which it currently isn't.

It all boils down to the following. I want to be able to do this:
```
ExecStartPre=/usr/bin/echo "${ETCD_ADVERTISE_CLIENT_URLS}"
```

And this (`${ETCD_ADVERTISE_CLIENT_URLS}`) should be the contents of whatever is specified in `/run/systemd/system/etcd2.service.d/20-cloudinit.conf`.

I want that, so that I don't have to compile the details myself and that it's consistent throughout the system.

**Comment by crawford** [comment]
This works fine for me.

```
$ systemctl cat etcd2  
# /etc/systemd/system/etcd2.service
[Service]
ExecStart=/usr/bin/echo "${ETCD_ADVERTISE_CLIENT_URLS}"

# /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=hello"
```

```
$ systemctl status etcd2
● etcd2.service
   Loaded: loaded (/etc/systemd/system/etcd2.service; static; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd2.service.d
           └─20-cloudinit.conf
   Active: inactive (dead)

Jul 23 10:01:13 my-machine systemd[1]: Started etcd2.service.
Jul 23 10:01:13 my-machine systemd[1]: Starting etcd2.service...
Jul 23 10:01:13 my-machine echo[27078]: hello
```

What is the output of `systemctl cat etcd2` on your system?

**Comment by crawford** [comment]
@mischief pointed out that maybe I misunderstand your question. Are you trying to use these values in unit files _other_ than etcd2?

**Comment by Dynom** [comment]
@mischief is right. I try to use the values for connecting to Etcd in unit-files other than Etcd. I'm not quite sure why I'd need connection info of Etcd in the unit file of Etcd, but I suppose that it would be an interesting exercises nonetheless.

To illustrate it even further:

```
[Unit]
Description=HAProxy & Confd service
Requires=docker.service
Requires=etcd2.service

[Service]
TimeoutStartSec=0
User=core
Restart=always
RestartSec=30

#-- Variable declaration --------------------------------------------------------------------------
EnvironmentFile=/etc/environment
Environment='IMAGE_NAME=foo/docker-haproxy:latest'
Environment="CONFD_ETCD_ROOT_PATH=/services/haproxy-dmz"


#-- Main process stop -----------------------------------------------------------------------------

# Stopping the container
ExecStop=/usr/bin/docker stop %p%i
ExecStop=/usr/bin/docker rm %p%i

#-- Register before main progress start -----------------------------------------------------------

ExecStartPre=-/usr/bin/docker kill %p%i
ExecStartPre=-/usr/bin/docker rm %p%i

ExecStartPre=/usr/bin/docker pull ${IMAGE_NAME}

# Etcd init - reates a default config when none defined.
ExecStartPre=/usr/bin/etcdctl ls ${CONFD_ETCD_ROOT_PATH}/domains 2>/dev/null || /usr/bin/etcdctl setdir ${CONFD_ETCD_ROOT_PATH}/domains

#-- Main process start ----------------------------------------------------------------------------

ExecStart=/usr/bin/docker run --name %p%i \
  --net=host  \
  -e "ETCD_NODE=http://${COREOS_PRIVATE_IPV4}:2379" \
  ${IMAGE_NAME}

#-- Register after main process start -------------------------------------------------------------

[X-Fleet]
# https://coreos.com/docs/launching-containers/launching/fleet-unit-files/
Conflicts=haproxy@*.service
MachineOf=dmz@%i.service
```

I want the line `ETCD_NODE=http://${COREOS_PRIVATE_IPV4}:2379` to read `ETCD_NODE=${ETCD_ADVERTISE_CLIENT_URLS}`. Which would make for a much more robust implementation.

**Comment by crawford** [comment]
I could have sworn I replied to this...

You'll need to declare all of the connection options in a separate environment file. From there, you can source it into etcd and any other service files you need. You won't be able to use the specific etcd section in your cloud-config when you do this.
