### ISSUE TITLE
Do not clear the VT

### ISSUE THREAD

**Issue by FredFool** [coreos/bugs#41]
When booting, you show all these wonderful startup messages. And then you just puff them away. I see some errors - but then they are gone. And because the buffer gets cleared, no scrollback using shift-pageup. 

This should happen only on a noob system, not in a datacenter :)) Perhaps you might at least consider adding a kernel parameter to turn that off.

**Comment by crawford** [comment]
@marineam do you think we should adopt this change? Otherwise, let's close this.

**Comment by crawford** [comment]
I think it's preferable if we document how to make this change via Ignition.
