### ISSUE TITLE
Created new cluster on azure and got Error retrieving unit: googleapi

### ISSUE THREAD

**Issue by podviaznikov** [coreos/bugs#411]
I was able to create coreos cluster with 3 nodeson Azure using tutorial (https://coreos.com/docs/running-coreos/cloud-providers/azure/#using-coreos).

All 3 nodes were created without errors.
However after sshing into the node and typing `fleetctl status` I've got 
```
Error retrieving unit: googleapi: Error 503: fleet server unable to communicate with etcd
```

My creation commands were:

```
azure service create my-service

azure vm create --custom-data=cloud-config.yaml --vm-size=Small --ssh=22 --ssh-cert="path/to/key.pem" --no-ssh-password --vm-name=node-1 --location="West Europe" --connect=my-service 2b171e93f07c4903bcad35bda10acf22__CoreOS-Stable-717.3.0 core

azure vm create --custom-data=cloud-config.yaml --vm-size=Small --ssh=2022 --ssh-cert="path/to/key.pem" --no-ssh-password --vm-name=node-2 --location="West Europe" --connect=my-service 2b171e93f07c4903bcad35bda10acf22__CoreOS-Stable-717.3.0 core

azure vm create --custom-data=cloud-config.yaml --vm-size=ExtraSmall --ssh=3022 --ssh-cert="path/to/key.pem" --no-ssh-password --vm-name=node-3 --location="West Europe" --connect=my-service 2b171e93f07c4903bcad35bda10acf22__CoreOS-Stable-717.3.0 core
```

It's unclear what is the issue at this point.

**Comment by crawford** [comment]
What is the status of your etcd cluster? Are all of the nodes online and healthy? Can I see the (sanatized) contents of your cloud-config?

**Comment by podviaznikov** [comment]
Interesting. 8 hours later I tried again and everything works. I didn't do anything after experience issue and posting it here.

**Comment by crawford** [comment]
@podviaznikov the ExtraSmall instances have relatively slow disks. Because etcd needs to commit everything to disk you might be seeing this failure as a result. If you are curious, you could test this by booting a cluster with faster disks.

**Comment by podviaznikov** [comment]
Interesting. I have only 2 small instances and 1 extrasmall. That is good to know.

I also tried few hours before cluster with 2 nodes (both small). I think I got the same issue. But definitely not 100% sure at this point.

You think cluster with 3 small nodes is good enough?

**Comment by crawford** [comment]
@podviaznikov that should be good enough for a quick test. I wouldn't run a substantial workload on that though.

**Comment by podviaznikov** [comment]
Thanks, I think that should be good for experimenting too.
