### ISSUE TITLE
Please enable CONFIG_IMA on CoreOS

### ISSUE THREAD

**Issue by Akhna** [coreos/bugs#416]
Hello,

Could we get the [Integrity Management Architecture](http://sourceforge.net/p/linux-ima/wiki/Home/) (IMA) enabled in the CoreOS kernel?

IMA can be used to prevent the execution of unknown binaries or log the hashes of files which are executed for malware detection and incident response investigations.

With a null default configuration, IMA would have no significant performance impact for users unless they configured it with appropriate boot command line options. 

This is what lead Ubuntu to add support for IMA in their kernel: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1244627

Is IMA something you'd be open to supporting in future versions of CoreOS?

**Comment by Akhna** [comment]
This could be as simple as setting the CONFIG_IMA kernel option:

CONFIG_IMA=y

**Comment by razvanm** [comment]
+1 for this feature.

**Comment by Akhna** [comment]
Friendly ping. @mjg59, any comments?

**Comment by mjg59** [comment]
I'm not inherently averse to this, but what kind of use case are you envisaging?

**Comment by emmanuel** [comment]
I'd like to see CoreOS add support for IMA. It's a good compliment to SELinux (and DTC, for that matter).

**Comment by mjg59** [comment]
In what way are you planning to use IMA? Is the aim to measure the state of the host or the contents of the containers? /usr is read-only, so it's already more complicated for an attacker to replace binaries with modified ones.

I don't want to seem overly negative here, but I'd really like to understand the use case that's being envisaged in order to figure out whether there's a better alternative.

**Comment by emmanuel** [comment]
Frankly, I'm new to IMA, so I don't have a fully-formulated plan about how to utilize it. For one thing, we are placing some executable bits in `/opt` (via `cloud-init`), though those are all shell scripts (today), and may not be feasibly handled in the IMA model. 

Basically, I want to be able to detect malicious tampering of other parts of the filesystem besides `/usr` (`/etc` comes to mind). Also detection of tampering of the contents of containers would be awesome, though maybe IMA doesn't provide much or anything beyond what Docker/rkt image signing gives you today. At my current understanding, it seems like IMA could be used to detect file tampering at runtime within a container, whereas image signing can only detect tampering of the image itself. Please correct me if I'm wrong.

**Comment by mjg59** [comment]
That seems reasonable. I'll look into the logistics and overhead of enabling it.
