### ISSUE TITLE
Running rkt and docker on alpha causes cgroup error

### ISSUE THREAD

**Issue by ecnahc515** [coreos/bugs#420]
In alpha, if you're running rkt containers before running docker containers then you encounter this issue:
https://github.com/opencontainers/runc/issues/133

The issue has been fixed in Docker upstream but waiting for 1.8 might be a bit long for this fix. 

@marineam @crawford Perhaps we can backport the fix?

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/coreos-overlay/issues/1419 and https://github.com/coreos/coreos-overlay/pull/1431.
