### ISSUE TITLE
systemd-networkd restarts every ~3 minutes

### ISSUE THREAD

**Issue by morph77** [coreos/bugs#423]
Greetings, 

Disclaimer; I'm new to CoreOS. 
Question; does anybody have ecountered an instable networkd service? The networkd service restarts every 3 minutes. Etcd2 and fleet are affected by this, failing and not seem to be working correctly also. 
We are testing with CoreOS in Hyper-V. Guest type: other linux 64bit. Etcd; static cluster without  discovery. CoreOS version: 717.3.0 (stable). 

Thanks.. 

```
-- Logs begin at Thu 2015-07-30 15:11:35 UTC. --
Jul 31 10:53:41 coret02 systemd[1]: Started Network Service.
Jul 31 10:53:41 coret02 systemd-networkd[3994]: docker0: Configured
Jul 31 10:53:41 coret02 systemd-networkd[3994]: lo: Configured
Jul 31 10:53:41 coret02 systemd-networkd[3994]: eth0: Configured
Jul 31 10:56:50 coret02 systemd[1]: Starting Network Service...
Jul 31 10:56:50 coret02 systemd-networkd[4034]: Enumeration completed
Jul 31 10:56:50 coret02 systemd[1]: Started Network Service.
Jul 31 10:56:50 coret02 systemd-networkd[4034]: docker0: Configured
Jul 31 10:56:50 coret02 systemd-networkd[4034]: lo: Configured
Jul 31 10:56:50 coret02 systemd-networkd[4034]: eth0: Configured
Jul 31 10:59:51 coret02 systemd[1]: Starting Network Service...
Jul 31 10:59:51 coret02 systemd-networkd[4073]: Enumeration completed
Jul 31 10:59:51 coret02 systemd[1]: Started Network Service.
Jul 31 10:59:51 coret02 systemd-networkd[4073]: docker0: Configured
```

Cloud config (omitted specific data); 

```yaml
#cloud-config
hostname: <hostname>
ssh_authorized_keys:
  - ssh-rsa  <omitted>
 
coreos:
  etcd2:
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://<ip>:2379
    initial-advertise-peer-urls: http://<ip>:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://<ip>:2380,http://<ip>:7001
    #for static cluster setup, no discovery
    name: <hostname>
    initial-cluster-token: etcd-cluster-1
    initial-cluster: <hostname>=http://<ip>:2380,<hostname>=http://<ip>:2380,<hostname>=http://<ip>:2380
    initial-cluster-state: new
  fleet:
    public-ip: <ip>
  update:
    reboot-strategy: etcd-lock
  units:
   - name: static.network
     runtime: true
     content: |
       [Match]
       Name=eth0
       [Network]
       Address=<ip>/24
       Gateway=<ip>
       DNS=<ip>
   - name: etcd2.service
     command: start
   - name: fleet.service
     command: start
   - name: docker.service
     command: start
write_files:
 - path: /etc/environment
   permissions: 0644
   content: |
     COREOS_PUBLIC_IPV4=<ip>
     COREOS_PRIVATE_IPV4=<ip>
```

**Comment by ionave** [comment]
Currently looking into this bug :)

**Comment by ionave** [comment]
So, I wasn't able to reproduce this bug... I was running on Azure instead of a pure Hyper-V instance....

However, you can still get more debug information from networkd... Follow the steps at this link to enable debug logging for networkd and post your results.

https://coreos.com/os/docs/latest/network-config-with-networkd.html

**Comment by mkastanja** [comment]
Thanks, here is the verbose logging for 3 minutes;

Aug 21 10:01:52 coret01 systemd[1]: Starting Network Service...
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.454 object=n/a interface=n/a membe
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:01:52 coret01 systemd-networkd[11863]: timestamp of '/etc/systemd/network' changed
Aug 21 10:01:52 coret01 systemd-networkd[11863]: timestamp of '/run/systemd/network' changed
Aug 21 10:01:52 coret01 systemd-networkd[11863]: docker0: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1 interface=org.freedeskt
Aug 21 10:01:52 coret01 systemd-networkd[11863]: docker0: Link 3 added
Aug 21 10:01:52 coret01 systemd-networkd[11863]: docker0: udev initialized link
Aug 21 10:01:52 coret01 systemd-networkd[11863]: docker0: Saved original MTU: 1500
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Link 2 added
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: udev initialized link
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Saved original MTU: 1500
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: Link 1 added
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: udev initialized link
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: Saved original MTU: 0
Aug 21 10:01:52 coret01 systemd-networkd[11863]: docker0: Adding address: fe80::606f:53ff:fecd:1961/64 (valid for ever)
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1 interface=org.freedeskt
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Adding address: fe80::21d:d8ff:feb7:1d34/64 (valid for ever)
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Adding address: 2a02:1d8:0:63:21d:d8ff:feb7:1d34/64 (valid for 4w 1d 23h 58min 13s)
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1 interface=org.freedeskt
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: Adding address: ::1/128 (valid for ever)
Aug 21 10:01:52 coret01 systemd-networkd[11863]: docker0: Adding address: 172.17.42.1/16 (valid for ever)
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Adding address: 172.23.3.50/24 (valid for ever)
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: Adding address: 127.0.0.1/8 (valid for ever)
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Enumeration completed
Aug 21 10:01:52 coret01 systemd-networkd[11863]: docker0: Link state is up-to-date
Aug 21 10:01:52 coret01 systemd[1]: Started Network Service.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: docker0         : found matching network '/usr/lib64/systemd/network/50-docker.network'
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: docker0: Configured
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Link state is up-to-date
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0            : found matching network '/run/systemd/network/static.network'
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Setting addresses
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: Link state is up-to-date
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo              : found matching network '/usr/lib64/systemd/network/zz-default.network'
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: Ignoring link-local autoconfiguration for loopback link
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: Ignoring DHCP clients for loopback link
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: lo: Configured
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Addresses set
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Setting routes
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Routes set
Aug 21 10:01:52 coret01 systemd-networkd[11863]: eth0: Configured
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Got message type=signal sender=org.freedesktop.DBus destination=:1.454 object=/org/freedesktop/DBus interfac
Aug 21 10:01:52 coret01 systemd-networkd[11863]: Got message type=signal sender=org.freedesktop.DBus destination=:1.454 object=/org/freedesktop/DBus interfac
Aug 21 10:02:22 coret01 systemd-networkd[11863]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:02:22 coret01 systemd-networkd[11863]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:02:22 coret01 systemd-networkd[11863]: Got message type=signal sender=org.freedesktop.DBus destination=:1.454 object=/org/freedesktop/DBus interfac
Aug 21 10:02:22 coret01 systemd-networkd[11863]: Got message type=signal sender=org.freedesktop.DBus destination=n/a object=/org/freedesktop/DBus interface=o
Aug 21 10:03:01 coret01 systemd[1]: Starting Network Service...
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.455 object=n/a interface=n/a membe
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:03:01 coret01 systemd-networkd[11876]: timestamp of '/etc/systemd/network' changed
Aug 21 10:03:01 coret01 systemd-networkd[11876]: timestamp of '/run/systemd/network' changed
Aug 21 10:03:01 coret01 systemd-networkd[11876]: docker0: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1 interface=org.freedeskt
Aug 21 10:03:01 coret01 systemd-networkd[11876]: docker0: Link 3 added
Aug 21 10:03:01 coret01 systemd-networkd[11876]: docker0: udev initialized link
Aug 21 10:03:01 coret01 systemd-networkd[11876]: docker0: Saved original MTU: 1500
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Link 2 added
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: udev initialized link
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Saved original MTU: 1500
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: Link 1 added
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: udev initialized link
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: Saved original MTU: 0
Aug 21 10:03:01 coret01 systemd-networkd[11876]: docker0: Adding address: fe80::606f:53ff:fecd:1961/64 (valid for ever)
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1 interface=org.freedeskt
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Adding address: fe80::21d:d8ff:feb7:1d34/64 (valid for ever)
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Adding address: 2a02:1d8:0:63:21d:d8ff:feb7:1d34/64 (valid for 4w 2d)
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1 interface=org.freedeskt
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: Adding address: ::1/128 (valid for ever)
Aug 21 10:03:01 coret01 systemd-networkd[11876]: docker0: Adding address: 172.17.42.1/16 (valid for ever)
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Adding address: 172.23.3.50/24 (valid for ever)
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: Adding address: 127.0.0.1/8 (valid for ever)
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Enumeration completed
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Updating address: 2a02:1d8:0:63:21d:d8ff:feb7:1d34/64 (valid for 4w 2d)
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Updating address: 2a02:1d8:0:63:21d:d8ff:feb7:1d34/64 (valid for 4w 2d)
Aug 21 10:03:01 coret01 systemd-networkd[11876]: docker0: Link state is up-to-date
Aug 21 10:03:01 coret01 systemd-networkd[11876]: docker0         : found matching network '/usr/lib64/systemd/network/50-docker.network'
Aug 21 10:03:01 coret01 systemd[1]: Started Network Service.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: docker0: Configured
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_33 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Link state is up-to-date
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0            : found matching network '/run/systemd/network/static.network'
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Setting addresses
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: Link state is up-to-date
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo              : found matching network '/usr/lib64/systemd/network/zz-default.network'
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: Ignoring link-local autoconfiguration for loopback link
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: Ignoring DHCP clients for loopback link
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: lo: Configured
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_31 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Addresses set
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Setting routes
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Routes set
Aug 21 10:03:01 coret01 systemd-networkd[11876]: eth0: Configured
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/network1/link/_32 interface=org.
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Got message type=signal sender=org.freedesktop.DBus destination=:1.455 object=/org/freedesktop/DBus interfac
Aug 21 10:03:01 coret01 systemd-networkd[11876]: Got message type=signal sender=org.freedesktop.DBus destination=:1.455 object=/org/freedesktop/DBus interfac
Aug 21 10:03:31 coret01 systemd-networkd[11876]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:03:31 coret01 systemd-networkd[11876]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus inter
Aug 21 10:03:31 coret01 systemd-networkd[11876]: Got message type=signal sender=org.freedesktop.DBus destination=:1.455 object=/org/freedesktop/DBus interfac
Aug 21 10:03:31 coret01 systemd-networkd[11876]: Got message type=signal sender=org.freedesktop.DBus destination=n/a object=/org/freedesktop/DBus interface=o

Please let me know if this windows is broad enough to catch a restart cycle.
Regards.

**Comment by crawford** [comment]
Are you still running into this behavior?
