### ISSUE TITLE
Disable FSCK on boot

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#424]
_From @remonlam on July 31, 2015 12:39_

Hi,

Perhaps I'm posting this in the wrong place but because the question is related to GRUB this seems the best place.

I've tried to add the "fastboot" option in the GRUB config to prevent CoreOS from checking the filesystem on boot. However this option does not work.

Why I want to do this? I'm running CoreOS on a Minnowboard Max that does not have a proper working RTC so when the power is disconnected the time is being set back to the year 2000. On boot the root partition of CoreOS will not mount because of the time changes and needs to be checked/repaired.

Is there an option to prevent CoreOS from checking the disk on boot? because there is not /etc/fstab file I came up with the idea to do this in GRUB, but cant get it to work properly.

Thanks!

_Copied from original issue: coreos/grub#12_

**Comment by remonlam** [comment]
Well I find a solution that seems to be working, it will disable fsck on boot.
https://github.com/remonlam/CoreOS/blob/master/mbm-coreos-rtc_grub.cfg

@marineam could you close this issue?

**Comment by marineam** [comment]
@remonlam great, glad you got it sorted out! Another option may be `tune2fs -i 0 /dev/sda9` to disable time-based fsck triggers, but leaving mount-count based triggers enabled. We may want to investigate doing that automatically if we detect that the system clock is wrong, possibly based on if the system time is before the time the image was built or similar. @crawford thoughts? a possible job for ignition...

**Comment by remonlam** [comment]
@marineam thanks for the info! I've tried tune2fs, however when the date/time is incorrect I still get the fsck error on boot, but the grub.cfg fixed it :-)

**Comment by marineam** [comment]
Ok, closing then.
