### ISSUE TITLE
manage_etc_hosts prevents Google load balancer health checks from passing 

### ISSUE THREAD

**Issue by gdcbyers** [coreos/bugs#425]
Setting manage_etc_hosts to "localhost", it seems to overwrite /etc/hosts. An entry for metadata is required for the google manage_addresses script to function properly. Without the balancer's IP address being added routing for the load balancer doesn't seem to work, resulting in the health checks never passing. Setting it without a health check still does not function because the routing from the load balancer IP does not work.

Running /usr/share/oem/bin/gce-add-metadata-host on each node solves the problem (probably only until restart)

**Comment by crawford** [comment]
May I ask why you are setting that option in your cloud-config? I've kept that option around in coreos-cloudinit for backward compatibly, but I never understood the use case.

**Comment by gdcbyers** [comment]
I'm not sure, to be honest. Its part of a Deis cluster and a "graceful shutdown" feature. It appears @iancoffey added that part of the cloud-config. Perhaps they can explain more of the reasons.

**Comment by carmstrong** [comment]
It was added as part of: https://github.com/deis/deis/pull/3561/files

I assume it was because we weren't properly resolving localhost on some environments, but perhaps that can be resolved without the use of `manage_etc_hosts`.

**Comment by crawford** [comment]
Hmm, that option just adds an entry to /etc/hosts, mapping your hostname to 127.0.0.1. "localhost" is specified in /usr/share/baselayout/hosts, which will work if your program links against libc.

**Comment by iancoffey** [comment]
@crawford Yes, it was added so that `hostname -f` could reliably function. Ill open an issue to investigate removing it from the stock Deis cloud config.

**Comment by crawford** [comment]
@iancoffey OK. For what it's worth, `hostname -f` works on my 758.1.0 box without that option in my cloud-config.
