### ISSUE TITLE
sshd with non-standard port doesn't start after reboot

### ISSUE THREAD

**Issue by akashihi** [coreos/bugs#426]
In latest stable (723.3.0) sshd is not started after boot when using non-standard port:

-- Reboot --
```
Aug 04 17:19:45 node1 systemd[1]: Listening on sshd.socket.
Aug 04 17:19:45 node1 systemd[1]: Starting sshd.socket.
Aug 04 17:19:46 node1 systemd[1]: Stopping sshd.socket.
Aug 04 17:19:46 node1 systemd[1]: sshd.socket: Failed to listen on sockets: Address already in use
Aug 04 17:19:46 node1 systemd[1]: Failed to listen on sshd.socket.
Aug 04 17:19:46 node1 systemd[1]: sshd.socket: Unit entered failed state.
core@node1 ~ $ cat /etc/systemd/system/sshd.socket
[Socket]
ListenStream=1984
Accept=yes
FreeBind=true
ReusePort=yes
```

It could be started manually later, but it would be nice, if it'll start automatically on boot.

**Comment by TorsionalMetric** [comment]
I'm also having this problem with 723.3.0. Boots once, but afterwards ssh doesn't come up. It's like I've locked my keys in the car. V frustrating.

I tried using a combo of options from the various threads... I don't think they conflict.

cloud-config.yml on DigitalOcean (obv)
```
#cloud-config

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp

      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no

coreos:
    units:
      - name: sshd.socket
        command: restart
        runtime: true
        content: |
          [Unit]
          Description=OpenSSH ServerSocket
          Conflicts=sshd.service
          
          [Socket]
          ExecStartPre=/usr/bin/sleep 30
          ListenStream=2323
          ReusePort=true
          FreeBind=true
          Accept=yes
      - name: 99-public-interface.network
        runtime: yes
        content: |
          [Match]
          Path=*:03.0

          [Network]
          IPv4LL=true
      - name: systemd-networkd.service
        command: restart
      - name: oem-cloudinit.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          Description=Cloudinit from DigitalOcean metadata

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/coreos-cloudinit --oem=digitalocean
    oem:
      id: digitalocean
      name: DigitalOcean
      version-id: 0.0.2
      home-url: https://www.digitalocean.com/
      bug-report-url: https://github.com/coreos/bugs/issues
```

**Comment by crawford** [comment]
@TorsionalMetric that cloud-config you posted is the system cloud-config. Are you actually using that as your user config or was that a misprint?

**Comment by TorsionalMetric** [comment]
Nope, wasn't a misprint. I now have some things to read and teach myself. Thanks for taking a look!

I'll post again with further results as soon as I've read and tried again. I may have actually using some of this as my user config, so I may still have a problem?

**Comment by TorsionalMetric** [comment]
I originally locked myself out of a pet server in development. Couldn't get in afterwards. My (slightly arbitrary) goal was to take a snapshot on my host (DigitalOcean), fix it, take a new snapshot and load it in to the same place. This would have allowed me to keep the same IP address and avoid passing the same user-data every time I started a new server in my cluster.

I wanted to accomplish this without changing the user-data for that particular server within the DigitalOcean framework (since I couldn't). Given my limited access, I couldn't modify the read-only portion of the filesystem that establishes the SSH port.

Eventually I gave up and decided that I would just have to use the same block of user-data every time to get it running.

This worked for me:
```
#cloud-config

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp

      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no

coreos:
    units:
      - name: sshd.socket
        command: restart
        runtime: true
        content: |
          [Unit]
          Description=OpenSSH ServerSocket
          Conflicts=sshd.service
          
          [Socket]
          ListenStream=14400
          ReusePort=true
          FreeBind=true
          Accept=yes
```

**Comment by chriswayg** [comment]
I had same problem on CoreOS stable (723.3.0): got locked out from ssh after changing the port and getting error ```  sshd.socket failed to listen on sockets: Address already in use```

This unit file appears to work reliably:

```
#cloud-config
...

coreos:
  units:
      - name: sshd.socket
        command: restart
        runtime: true
        content: |
          [Unit]
          Description=OpenSSH ServerSocket
          Conflicts=sshd.service

          [Socket]
          ExecStartPre=/usr/bin/sleep 20
          ListenStream=22222
          ReusePort=true
          FreeBind=true
          Accept=yes
```

**Comment by winton** [comment]
We are encountering a lot of failed sshd units similar to this: https://groups.google.com/forum/#!topic/coreos-user/p5NMyyCmoUY

Eventually, if there were enough failed units, sshd would fail to start and we are locked out.

So now I change the port according to these directions: https://coreos.com/os/docs/latest/customizing-sshd.html

And now locked out again due to the issue on this thread :( How is anyone using CoreOS on AWS at this point in time? My CoreOS setup is pretty vanilla using the AMIs.

**Comment by vcaputo** [comment]
ignore the label noise, don't know how that happened.

**Comment by mischief** [comment]
@akashihi @TorsionalMetric @chriswayg is this still an issue for anyone? i can't seem to reproduce this on CoreOS alpha 845.0.0.

**Comment by akashihi** [comment]
TBH i stopped using CoreOS due to it's instability :) So this bug is no
more relevant for me.

2015-11-19 22:24 GMT+02:00 Nick Owens <notifications@github.com>:

**Comment by chriswayg** [comment]
The unit file I used as a workaround was satisfactory. I didn't try it without the workaround in newer versions of CoreOS, so I cannot tell, if anything has changed.

this was needed previously:
```
...
          [Socket]
          ExecStartPre=/usr/bin/sleep 20
          ListenStream=22222
          ReusePort=true
          FreeBind=true
          Accept=yes
```

**Comment by mischief** [comment]
if anyone continues to have problems on the latest stable, beta, or alpha, leave a message here and we can investigate again.

**Comment by genti-t** [comment]
on version 835.8.0 (stable) is still needed 
the workaround:
```
          [Socket]
          ExecStartPre=/usr/bin/sleep 20
          ListenStream=22222
          ReusePort=true
          FreeBind=true
          Accept=yes

**Comment by iquiw** [comment]
I got the same problem on 899.1.0 (alpha).

Once `/etc/systemd/system/sshd.socket` is created by cloud-config (`/var/lib/coreos-install/user_data`), the file persists after reboot.
So I just removed the sshd port config from cloud-config and sshd is working with changed port.

**Comment by elephantfries** [comment]
@iquiw  I did the other thing: deleted sshd.socket from /etc/systemd/system then rebooted and voila: sshd instantly available. No need for delays. Maybe cloud-config should've placed that file under /run?

**Comment by iquiw** [comment]
@elephantfries Yes, that works too.

It also works when the port setting is written in `/usr/share/oem/cloud-config.yml` even if `/etc/systemd/system/sshd.socket` exists.

**Comment by elephantfries** [comment]
Ahh, good to know. I am not sure if I can put it there, though. We're running a netbooted bare metal cluster. Seems like I need to take action after the boot.  This works for me perfectly:

[in cloud-config]
```
  units:
    - name: sshd.socket
      command: restart
      content: |
        [Socket]
        ListenStream=2222
        Accept=yes
    - name: bug426.path
      command: start
      content: |
        [Unit]
        Description=Workaround for bug 426 (sshd port in use after restart)
        [Path]
        PathExists=/etc/systemd/system/sshd.socket
        [Install]
        WantedBy=multi-user.target
    - name: bug426.service
      content: |
        [Unit]
        Description=Workaround for bug 426 (sshd port in use after restart)
        [Service]
        ExecStart=/usr/bin/bash -c 'mv /etc/systemd/system/sshd.socket /run/systemd/system; systemctl daemon-reload'
```

**Comment by crawford** [comment]
@elephantfries you can set `runtime: true` on the unit to make coreos-cloudinit write the file to /run.

If you are netbooting bare metal, I would recommend [Ignition](https://coreos.com/ignition/docs/latest/what-is-ignition.html) (still in active development). The mental model is much simpler, and it runs before systemd so you don't have to bother with all of these restarts and daemon-reloads.

**Comment by elephantfries** [comment]
Oh nice. Just verified, this works for me as well:
```
  units:
    - name: sshd.socket
      runtime: true
      command: restart
      content: |
        [Socket]
        ListenStream=2222
        Accept=yes
```
I'll take a look at Ignition, too.

**Comment by iquiw** [comment]
@crawford @elephantfries Thank you for the info. It works!

**Comment by Blackglade** [comment]
Don't want to bump an old issue, but I'm currently on 1235.9.0 (Stable) and just became aware of this issue... 

I am now locked out of my production server because it keeps giving me a Connection Refused error...
