### ISSUE TITLE
Clean up onmetal OEM

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#427]
The device renaming used in onmetal was a terrible workaround that we don't need any more and can cause failures due to a race condition:

    Aug 05 18:14:03 coreos-410-production rename-interfaces.sh[903]: Error changing net interface name 'eno1' to 'eth0': Device or resource busy
    Aug 05 18:14:03 coreos-410-production rename-interfaces.sh[903]: could not rename interface '2' from 'eno1' to 'eth0': Device or resource busy

**Comment by crawford** [comment]
Fixed via https://github.com/coreos/coreos-overlay/pull/1433.
