### ISSUE TITLE
System crashes when using swap file

### ISSUE THREAD

**Issue by bobelev** [coreos/bugs#429]
I use CoreOS on DigitalOcean's droplets. I have several instances with 1GB RAM and 4GB swap. When I run heavy-memory task my system crash. I have there screenshots from two different accidents. 
![1](https://cloud.githubusercontent.com/assets/3942342/9147857/f4097958-3d75-11e5-84a8-c89406081fc8.png)
![2](https://cloud.githubusercontent.com/assets/3942342/9147858/f40bfdcc-3d75-11e5-9f18-1fc035efa7a5.png)

Service used to create swap file looks like:
```
[Unit]
Description=Setup Swap Service

[Service]
Type=oneshot
Environment="SWAP_PATH=/swap" "SWAP_FILE=swap.fs"
ExecStartPre=-/usr/bin/rm -rf ${SWAP_PATH}
ExecStartPre=/usr/bin/mkdir ${SWAP_PATH}
ExecStartPre=/usr/bin/touch ${SWAP_PATH}/${SWAP_FILE}
ExecStartPre=/usr/bin/chattr +C ${SWAP_PATH}/${SWAP_FILE}
ExecStartPre=/bin/bash -c "fallocate -l 4096m ${SWAP_PATH}/${SWAP_FILE}"
ExecStartPre=/usr/bin/chmod 600 ${SWAP_PATH}/${SWAP_FILE}
ExecStartPre=/usr/sbin/mkswap ${SWAP_PATH}/${SWAP_FILE}
ExecStartPre=/usr/sbin/losetup -f ${SWAP_PATH}/${SWAP_FILE}
ExecStart=/usr/bin/sh -c "/sbin/swapon $(/usr/sbin/losetup -j ${SWAP_PATH}/${SWAP_FILE} | /usr/bin/cut -d : -f 1)"
ExecStop=/usr/bin/sh -c "/sbin/swapoff $(/usr/sbin/losetup -j ${SWAP_PATH}/${SWAP_FILE} | /usr/bin/cut -d : -f 1)"
ExecStopPost=/usr/bin/sh -c "/usr/sbin/losetup -d $(/usr/sbin/losetup -j ${SWAP_PATH}/${SWAP_FILE} | /usr/bin/cut -d : -f 1)"
ExecStopPost=-/usr/bin/rm -rf ${SWAP_PATH}
RemainAfterExit=true
```

CoreOS version: 717.3.0.

**Comment by mischief** [comment]
@bobelev are you able to test on beta or alpha?

**Comment by bobelev** [comment]
I updated CoreOS 723.3.0. It's a current beta and stable version. I'm still getting this crashes.

Also I tried to make swap with default 'ubuntu' method — without `losetup` and `chattr`. It seems to be working but I need to run more tests.

**Comment by wmark** [comment]
I don't know what the ›Ubuntu method‹ is, but leaving my notes here how to create a swap partition during installation. It will be picked up automatically on the next boot:

```bash
$ ./coreos-install -d /dev/sda -V …

$ cgpt repair /dev/sda
# operation x / y * y on integers is rounding
$ export STARTBLK=$(( $(cgpt show /dev/sda | tail -n 2 | head -n 1 | sed -e 's/^ *\([0-9]*\).*$/\1/') / 4096 * 4096 - 4194304 ))
# inject swap-A as last partition
# — please note that on memory cards you cannot use numbers higher than 9 (not suitable for swap anyway)
$ cgpt add -i 14 -l swap-A -b ${STARTBLK} -s 4194304 -t linux-swap /dev/sda
$ blockdev --rereadpt /dev/sda && sleep 1
$ mkswap -L swap-A /dev/sda14

# do stuff as usual

$ reboot
```

I hope this helps with testing.

**Comment by ntquyen** [comment]
I got the same crash in v773.1.0. Issue posted here:
http://stackoverflow.com/questions/33512998/coreos-vm-crash-swap-trace-printed

**Comment by bobelev** [comment]
@ntquyen try create swap file without `losetup` and `chattr` commands. It helped me.

**Comment by ntquyen** [comment]
@bobelev It would be awesome if you give me the exact unit file, because I have no idea what i'm doing with swap here :D

**Comment by bobelev** [comment]
@ntquyen here it is
```
[Service]
Type=oneshot
Environment="SWAP_PATH=/swap" "SWAP_FILE=swap.fs"
ExecStartPre=-/usr/bin/rm -rf ${SWAP_PATH}
ExecStartPre=/usr/bin/mkdir ${SWAP_PATH}
ExecStartPre=/usr/bin/touch ${SWAP_PATH}/${SWAP_FILE}
ExecStartPre=/bin/bash -c "fallocate -l 4096m ${SWAP_PATH}/${SWAP_FILE}"
ExecStartPre=/usr/bin/chmod 600 ${SWAP_PATH}/${SWAP_FILE}
ExecStartPre=/usr/sbin/mkswap ${SWAP_PATH}/${SWAP_FILE}
ExecStartPre=/usr/sbin/sysctl vm.swappiness=10
ExecStart=/sbin/swapon ${SWAP_PATH}/${SWAP_FILE}
ExecStop=/sbin/swapoff ${SWAP_PATH}/${SWAP_FILE}
ExecStopPost=-/usr/bin/rm -rf ${SWAP_PATH}
RemainAfterExit=true
```

**Comment by ntquyen** [comment]
Thanks @bobelev !!

**Comment by crawford** [comment]
@bobelev It looks like you were able to resolve this issue. Please reopen if you are still having trouble.
