### ISSUE TITLE
ssh into bare metal CoreOS stable (723.3.0) new install failed 

### ISSUE THREAD

**Issue by BradleyA** [coreos/bugs#430]
Question:  Not sure if this is a bug or my user error I made installing that caused the .ssh/authorized_keys not to be created during install?

first install:
Installed CoreOS stable: sudo ./coreos-install -d /dev/sda -C stable -c ./cloud-config.yml
reboot
ssh core@192.168.1.104
core@192.168.1.104's password: 
Permission denied, please try again.

second install: 
Installed CoreOS stable: sudo ./coreos-install -d /dev/sda -C stable -c ./cloud-config.yml
after install complete
before reboot
mounted /dev/sd9 /mnt 
cd /mnt/home/core/.ssh  directory was empty
copied authorized_keys file into ~core/.ssh
chmod 600 ~core/.ssh/authorized_keys
reboot 
ssh core@192.168.1.104
The authenticity of host '192.168.1.104 (192.168.1.104)' can't be established.
ED25519 key fingerprint is 04:2a:43:24:f8:94:51:81:61:d4:15:2f:c6:a9:0e:a9.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.104' (ED25519) to the list of known hosts.
Enter passphrase for key '/home/three/.ssh/id_rsa': 
CoreOS stable (723.3.0)
core@one ~ $ 
ssh worked

copy of yaml file (received no yaml error from validator):
![screenshot from 2015-08-07 19 40 00](https://cloud.githubusercontent.com/assets/12129046/9148280/7f7ae056-3d3c-11e5-917a-08ec41ea6f30.png)

**Comment by crawford** [comment]
Can you get console access to that failed machine and show me the output of `journalctl -b _EXE=/usr/bin/coreos-cloudinit --no-pager`? You can use the `coreos.autologin` kernel parameter to skip the password check.

**Comment by BradleyA** [comment]
This is the output of the second install:

![screenshot from 2015-08-08 12 26 17](https://cloud.githubusercontent.com/assets/12129046/9151467/f26059b6-3dc8-11e5-8c52-6fc74a7f73de.png)

**Comment by crawford** [comment]
That log seems to indicate that the keys were written. At this point, you should see `.ssh/authorized_keys.d` and `.ssh/authorized_keys`. Are they present?

**Comment by BradleyA** [comment]
The ~core/.ssh directory was empty.  I had to copy .ssh/authorized_keys in from another system with my USB.

**Comment by crawford** [comment]
That's odd. "Authorized SSH keys for core user" only shows up if keys have been successfully written.

When you install CoreOS using that script, it only copies your cloud-config into place (/var/lib/coreos-install); it doesn't actually get executed. Only when you boot the machine, does coreos-cloudinit run the config (and add your keys).

**Comment by BradleyA** [comment]
ssh into system
sudo ls -l /var/lib/coreos-install
sudo cat /var/lib/coreos-install/user_data
In the directory, /var/lib/coreos-install, there is a file named user_data which is a copy of my cloud-config file.
removed files from ~core/.ssh
rebooted system
files are back in ~core/.ssh
able to ssh into system

**Comment by crawford** [comment]
Sounds like it's working. Do you know what was done differently this time?

**Comment by BradleyA** [comment]
I do not know, must be a user error some where in my steps.  I will be loading another system later this week and let you know if I have the same issue, thank you for your feed back.
