### ISSUE TITLE
ssh: unable to authenticate, attempted methods [none publickey]

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#431]
_From @YP28 on August 6, 2015 19:16_

CoreOS stable (723.3.0) (on DigitalOcean)
fleetctl version 0.10.2

When I try to run services through fleetctl and a service get scheduled on a different CoreOS host, and I try to journal -f to that particular service I get the following error:
```
Error running remote command: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
Both nodes are installed with a public/private keypair from my MacBook and the exact same cloud-config. Also, when I try to ssh -A core@ip to the other node, it keeps asking me for a password for the user.

The nodes both register at the discovery service successfully, and are listed when I run ```fleetctl list-machines```.

_Copied from original issue: coreos/coreos-vagrant#261_

**Comment by crawford** [comment]
Are you using `-A` when you SSH into the first node?

**Comment by crawford** [comment]
_From @YP28 on August 7, 2015 6:25_

@crawford, I did indeed forward my ssh agent.

Edit: oh wow, I just noticed I'm in the wrong project entirely. I'm not using Vagrant, I'm having trouble with hosted machines on DigitalOcean.

**Comment by crawford** [comment]
Heh, let's move you to the right place.

**Comment by crawford** [comment]
Once you `ssh -A` into the first machine, can you verify that your keys are in the agent (`ssh-add -l`).

**Comment by YP28** [comment]
Is there any chance CoreOS/fleet tries to start services that are required in a unit file? I noticed that I had a dependency of etcd.service in one of my unit files, while I was running etcd2. Gave me a lot of weird errors along the way, machines seeming to drop out of the cluster, units disappearing. I guess all because etcd couldn't be connected to?

**Comment by crawford** [comment]
That is a very different issue. Please file a separate bug or ask on the mailing lists.

**Comment by c9s** [comment]
same here, I've already verified the same public keys, and the server seems don't have any log of the ssh connection.

If I manually use sshuser to connect to the instance it works pretty fine with the same pair of ssh key.

**Comment by bgilbert** [comment]
@c9s This bug is pretty old. Please open a new one.
