### ISSUE TITLE
mdadm raid disks not working as boot drive with PXE

### ISSUE THREAD

**Issue by medlefsen** [coreos/bugs#433]
I've been using PXE for running CoreOS with a software raid root disk for a while now. I recently upgraded and found that the boot image no longer detects raid devices and so can't use them as the root drive.

Previous version (which worked) was 647.2.0, and have tried a few different versions newer, none of which work, including 766.0.0.

Thanks!

**Comment by crawford** [comment]
Can you try 653.0.0 and 660.0.0?

**Comment by marineam** [comment]
Are you using a raid-autodetect partition type? If so is it MBR or GPT?

**Comment by crawford** [comment]
Any update?
