### ISSUE TITLE
socat missing in 766.0.0

### ISSUE THREAD

**Issue by serbaut** [coreos/bugs#434]
Release notes says that socat 1.7.3 should be in 766.0.0 but it's not.

    $ grep VERSION= /etc/os-release
    VERSION=766.0.0
    $ sudo find / -name socat
    $

**Comment by crawford** [comment]
Sorry about that. I got a little ahead of myself. That _should_ be available this week. Let me update our release notes.

**Comment by adarshaj** [comment]
FWIW, `socat` is still missing on core-os version `766.4.0` and this breaks the port forwarding functionality provided by kubernetes (ex. `kubectl port-forward -p $POD 5000:5000`)

**Comment by mischief** [comment]
@crawford can this be removed from the CoreOS 766.5.0 milestone? we do not ship kubelet in 766.

**Comment by crawford** [comment]
@mischief OK, I was mistaken.
