### ISSUE TITLE
static.network not applied with livecd

### ISSUE THREAD

**Issue by xerovis** [coreos/bugs#436]
I downloaded CoreOS Live CD today to install to a baremetal server connected directly to the internet. I Googled on how to set a static IP for CoreOS so that I could change the IP of the box. I was unable to get this to work. I had to use ifconfig settings to change the IP of the network interface. It would be advisable to add this information to your documentation or have CoreOS apply static.network files.

I was using the documentation here to install - https://coreos.com/os/docs/latest/installing-to-disk.html

I was using the documentation here to configure network - https://coreos.com/os/docs/latest/network-config-with-networkd.html

**Comment by crawford** [comment]
Take a look at [Ignition](https://coreos.com/ignition/docs/latest/). It will allow you to easily [configure the network](https://coreos.com/ignition/docs/0.1.6/network-configuration.html)
