### ISSUE TITLE
Disable Aggressive ARP Caching On AWS AMIs

### ISSUE THREAD

**Issue by brockwood** [coreos/bugs#437]
Due to how newer Linux kernels are caching MAC addresses in the neighbor table, a problem occurs on Amazon EC2 where a new instance is started and assigned an IP of a recently destroyed instance.  When that new instance attempts to talk to an established Etcd cluster, the long running machines of the cluster will have cached the MAC address for the previous instance and communication between the new instance and the Etcd cluster will not be possible.  A discussion of of the problem can be found here:  https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1331150.

To solve this problem, AWS' Linux distribution, Amazon Linux, sets gc_thresh1=0 by default in their AMI (see this discussion here:  https://forums.aws.amazon.com/thread.jspa?messageID=572171).  Would it be possible to see the same thing be applied to the CoreOS AMIs?

**Comment by eyakubovich** [comment]
@brockwood Are you running HVM or PV instances? We're suspecting it might be a driver issue.

**Comment by brockwood** [comment]
HVM instances, exclusively.

**Comment by eyakubovich** [comment]
Are you running with Enhanced Networking turned on? http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

**Comment by brockwood** [comment]
I did not set anything specifically for the EC2 instance, but, based on your document, SriovNetSupport return as "simple" and the modprobe returned the following:

```
$ modinfo ixgbevf
filename:       /lib/modules/4.0.5/kernel/drivers/net/ethernet/intel/ixgbevf/ixgbevf.ko
version:        2.12.1-k
license:        GPL
description:    Intel(R) 10 Gigabit Virtual Function Network Driver
author:         Intel Corporation, <linux.nics@intel.com>
srcversion:     E093AFA46D45A92CCB221A9
alias:          pci:v00008086d000015A8sv*sd*bc*sc*i*
alias:          pci:v00008086d00001565sv*sd*bc*sc*i*
alias:          pci:v00008086d00001515sv*sd*bc*sc*i*
alias:          pci:v00008086d000010EDsv*sd*bc*sc*i*
depends:
intree:         Y
vermagic:       4.0.5 SMP mod_unload
signer:         Magrathea: Glacier signing key
sig_key:        20:EF:63:A4:C6:0F:D6:FB:D6:9B:1E:C4:C3:14:5E:2B:E1:40:A1:46
sig_hashalgo:   sha256
parm:           debug:Debug level (0=none,...,16=all) (int)
```

I believe the answer to your question is "yes".

**Comment by robszumski** [comment]
Possible related change in 735.0.0: https://coreos.com/releases/#735.0.0

> Enable ixgbevf network devices for Amazon EC2 HVM instances that support it. Amazon brands this as Enhanced Networking. As part of this change we disabled the Predictable Network Interface Names scheme on EC2 to ensure network interfaces remain named eth0, eth1, etc. regardless of whether the ixgbevf or Xen driver is in use. This may impact users who enabled this feature themselves on previous versions which would have named the device ens3 instead of eth0.

**Comment by brockwood** [comment]
Forgot to mention that this is running on the latest stable:

```
CoreOS stable (723.3.0)
```

**Comment by eyakubovich** [comment]
Actually I think the minimum required ixgbevf.ko version is 2.14.2 (which Intel did not upstream for a long time; not sure if it's upstreamed now). So probably it's not fully enabled on your host but it could still be a driver issue.

**Comment by marineam** [comment]
No, the 2.14.2 is out of tree nonsense, not sure what mainline kernel maps
closest to that version but Intel actively maintains the mainline drivers
so I don't expect it to be an issue.

Regarding the change log, we goofed and accidentally enabled sriov when
registering some amis prior to the anticipated version but it didn't seem
to cause issues so we didn't bother with a new release just to turn it back
off.

Anywhoo, the theory goes that the reason this arp issue seems to be a big
fat bug and yet unfixed is that it only impacts the ixgbevf driver/hardware
and therefore few enough people hit it for it to linger. Need to verify
that theory though, we will need to try to reproduce it with both the pv
xen device and the hw ixgbevf device to see if behavior is the same.

**Comment by brockwood** [comment]
Thanks for looking into this.  At the moment, the gc_thres1=0 setting has solved our auto scaling problem so it isn't a serious issue.  It would be nice to, in the future, not be required to include that in the cloud config.

**Comment by crawford** [comment]
Is this issue still present in newer kernels?
