### ISSUE TITLE
Login via console fails for core user when password is expired 

### ISSUE THREAD

**Issue by shijinabraham** [coreos/bugs#439]
Coreos version  717.3.0 on virtual box. (Also seem os Vmware esxi)

If I set core user's password to expire immediately, then I am not able to login using the core user via the console. Login via ssh works. I have cloud-config attached no password is configured for core user in it.

 1) Set core users password to expire immediately "sudo chage core -d 0"
 2) Login via console as core user. After entering password, the login prompt  is shown again
 3) Login via ssh, the dialog to change password is shown
 4) If I repeat 1 with another user, I am able to login and change password via console.

Related post in coreos-user group https://groups.google.com/forum/#!topic/coreos-user/UZ_xDgufCXY

**Comment by crawford** [comment]
This should work now that we've included PAM in Container Linux.
