### ISSUE TITLE
Support floppy drives

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#440]
_From @felixbuenemann on August 15, 2015 20:10_

The CoreOS [cloud-config docs](https://coreos.com/os/docs/latest/config-drive.html) say that config data can be provided using either an iso9660 or fat filesystem, as long as the volume is named config-2.

I created a floppy image with the appropriate directory structure using fat-12 filesystem and volume label "CONFIG-2" (fat-12/fast-16 volume names are always uppercase), attached it to /dev/fd0 in the VM, but it was not detected.

The same config data put on an iso image was detected just fine.

I think supporting floppy images would be a good idea, especially for physical servers. Because most servers allow attaching floppy images remotely and the cd drive might already be in used to boot coreos.

It's also easier to modify floppy images if the cloud-config needs to be modified, because for example mac os x allows to mount and modify floppy images without any extra tools, while iso images are read only.

I hope this is the right project for the request, if not please tell me were to post is instead.

_Copied from original issue: coreos/coreos-cloudinit#377_

**Comment by marineam** [comment]
Pretty sure we don't even ship the floppy driver. In the case of mixing a cloud config with the ISO, couldn't you just attach two drives to the VM? In fact you could attach you prefer manipulating a floppy disk image you could attach it as a normal hard drive or cdrom and it should work just fine. I think we are better off to avoid adding floppy support.

**Comment by felixbuenemann** [comment]
You're right, the kernel doesn't have floppy support. In that case adding support seems unreasonable.

Creating a small fat image and mounting it should works fine for VMs. I just checked the HP ILO scripting docs and they do support mounting "usb key images" via http, so one could just use a fat image for the virtual floppy and the iso for the virtual cdrom.

Thanks for investigating!

**Comment by marineam** [comment]
Great! Sounds like this is all set then.
