### ISSUE TITLE
ship with mcelog

### ISSUE THREAD

**Issue by wmark** [coreos/bugs#441]
Please include *app-admin/mcelog* in the CoreOS distribution. Preferably version 117 or later due to its support for various current server-deployed Intel SoC.

It enables logging of hardware errors, such as (but not limited to) memory errors with ECC dimms.

I recommend enabling its start by default.

Kernel support is already given:
```bash
$ uname -r
4.1.4-coreos-r1

$ zgrep -F MCE /proc/config.gz
CONFIG_X86_MCE=y
CONFIG_X86_MCE_INTEL=y
CONFIG_X86_MCE_AMD=y
```

**Comment by wmark** [comment]
Any chance to get label `low-hanging fruit` for this? Thanks!

**Comment by mischief** [comment]
is there any reason that mcelog can't be run in a container?

**Comment by wmark** [comment]
It needs privileged access to the host, and needs to write to the hosts logging facility.

**Comment by mischief** [comment]
@wmark i think it's quite possible to pass through /dev/mcelog or create the device node in the container. also seems perfectly doable to have mcelog write to standard output, which would go into the journal when run from a systemd unit.

**Comment by wmark** [comment]
@mischief If so, then `/sys/devices/system/machinecheck/`. I will see if I can find a machine to check your suggestion.

**Comment by wmark** [comment]
It accesses files outside the two paths, for event handling, and should run before any containers are started.

But we're fine with pulling out own binary from `/opt/sbin` or the like. Can be closed.
