### ISSUE TITLE
Vagrant (Windows host) synced folder; possible to add content from CoreOS to Windows host?

### ISSUE THREAD

**Issue by mkastanja** [coreos/bugs#443]
Well hello, 

Question;

Using the 'coreos-vagrant' setup on a Windows 7 host;

Using auto-rsync it IS possible to dynamically synchronize content created on the Windows side to the CoreOS vms via the synced folders; that is good. (reference; http://micahasmith.github.io/2015/01/22/coreos-vagrant-windows-file-share/)
So from the Windows side => CoreOS VMs; it works to share and dynamically sync content!

But.. 

Not the other way around!
I want to create content from within CoreOS on the same mount point. (Usecase to use a private image registry and persistently store the images and make them available on the other cluster nodes).

Issue: The content does not seem to propagate to the Windows host filesystem, and therefor also not to the fellow CoreOS nodes.

Question 1: Is there a known Vagrant configuration to make this work? 
Question 2: The created content only is available on the specific node it is created, can somebody elaborate how this works?

Thanks, really digging CoreOS btw!

**Comment by popsikle** [comment]
This is not possible.  Auto-rsync is a one way process.

I have had some good luck running unison in a container and then using that to sync to the host.  Never tried on windows, but you can check it out.  http://www.cis.upenn.edu/~bcpierce/unison/

**Comment by popsikle** [comment]
@mkastanja so, I think the process for using unison would be the same on windows as I use on OSX.

https://github.com/OpSitters/ragnarok/tree/master/unison is the docker container I bring up on the host.  Then I run two sync's from the OSX host, one that pushes changed files to the containers (for when unison is not running) and then one that looks for changes on both sides.  That gets done in this function:

https://github.com/OpSitters/ragnarok/blob/master/controllers/ragnarok#L79-L91

So far its working really well, YMMV on windows however.
