### ISSUE TITLE
Install from PXE?

### ISSUE THREAD

**Issue by devurandom** [coreos/bugs#444]
Is there already a bugreport for installing CoreOS from PXE? Something that fetches a basic bootloader via PXE, checks with the primary for "new instructions" (such as wipe-and-reinstall) and if there are none, boots through to the kernel / system currently stored on the disk?

**Comment by popsikle** [comment]
https://coreos.com/os/docs/latest/booting-with-pxe.html

**Comment by devurandom** [comment]
Thanks. I saw that page, but it appears to explicitly say that my desired setup (boot via PXE into network or local system, chooseable on the tftp server - I believe OpenStack/Fuel does something similar?) is not supported and only "boot from network into ramdisk, install, disable PXE, boot from local disk" or "boot from network into ramdisk" are possible.

**Comment by popsikle** [comment]
Well, when you install from pxe you can continue to boot from pxe.  IIRC coreOS will load a system volume on disk if there is one as part of the pxeboot phase.  This lets you upgrade by replace the pxeboot images.  But if you want something like wipe on every boot you could use something like https://github.com/kelseyhightower/coreos-ipxe-server and script it yourself as one of the profiles / chainloads.

**Comment by devurandom** [comment]
I don't want to wipe on every boot. But I am interested in the following features:

1. Wipe / "reset-to-factory-settings" on demand
2. Automatic installation
3. Automatic update

(1) and (2) are quite similar, if not the same, and might be possible if the TFTP server could be configured (CLI? Web-UI?) to deliver instructions to specific machines. This could even integrate with machinectl - i.e. machinectl writes the instructions into etcd and the TFTP server fetches the information from there.

(3) could be done by the PXE image loading the kernel from the local disks, if present, and then kexecing it. The local kernel and disk images would be updated using the "regular" install-to-disk method. If there is no local installation present, it would boot regularly from a ramdisk (as described in the [PXE guide](https://coreos.com/os/docs/latest/booting-with-pxe.html)), from where it could continue with (1) or (2), if desired.

Is that what you described in your last comment, when you mentioned the [coreos-ipxe-server](https://github.com/kelseyhightower/coreos-ipxe-server)?

**Comment by popsikle** [comment]
1.) What factory settings? The only thing that really changes on CoreOS is the docker volume right?

2.) Can be done with PXE.  The server I linked needs some work to do a cold install and then forget about the node, but its possible.  I packaged my own pxe boot images that includes some of my setup scripts that pretty much did auto install and then booted of disk the next time around.  I also needed to setup an OEM script to build the environment files as they are not built on PXE, I *think* that https://github.com/popsikle/coreos-configdrive took care of that part (but its been a while)

3.) This is built into to CoreOS.

**Comment by devurandom** [comment]
3. The page about PXE specifically says that I have to manage updates manually.

> Update Process
> Since our upgrade process requires a disk, this image does not have the option to update itself. Instead, the box simply needs to be rebooted and will be running the latest version, assuming that the image served by the PXE server is regularly updated.

**Comment by crawford** [comment]
1. You can just ran `rm -rf / --no-preserve-root`
3. Yes, you'll need to update the image on the PXE server and then reboot your nodes. Update Engine won't run on disk-less images.

**Comment by danderson** [comment]
You could look at https://github.com/danderson/pixiecore . You could implement an API server that makes policy decisions like wipe-and-reinstall, and tells Pixiecore whether to netboot into your installer image, or make the machine boot to local disk.

It's up to you to write the Pixiecore API server that encodes the netboot policies you want, but at least Pixiecore takes care of implementing whatever you decide.

**Comment by crawford** [comment]
In addition to the above answers, the bootcfg tool in https://github.com/coreos/coreos-baremetal should solve this.
