### ISSUE TITLE
OpenSSH 7?

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#451]
_From @jalev on August 26, 2015 10:49_

Hi there,

Would it be possible to bump OpenSSH to 7? It contains a lot of security fixes. 

_Copied from original issue: coreos/coreos-overlay#1483_

**Comment by cnelson** [comment]
+1

**Comment by enzor** [comment]
+1

**Comment by mischief** [comment]
coreos/portage-stable#261

**Comment by marineam** [comment]
@crawford we only updated to openssh-6.9, 7.0 and 7.1 ebuilds were added but not keyworded as stable in coreos-overlay

**Comment by mischief** [comment]
@jalev @cnelson @enzor OpenSSH 7.1 will be available in the next alpha.

**Comment by crawford** [comment]
Rolled back to 6.9 due to OpenSSH disabling DSA keys by default.

**Comment by FirefighterBlu3** [comment]
instead of rolling back to 6.9, why not enable DSA by default in the /etc/ssh/*config files with a simple patch

**Comment by mischief** [comment]
@FirefighterBlu3 we do not control files in /etc except upon installation of coreos. if the user has broken the symlink in /etc to apply customizations, our changes to the read-only files in /usr would have no effect, resulting in the user locked out of their system.

**Comment by FirefighterBlu3** [comment]
are we going to stay at 6.9 forever or come up with a solution that allows an upgrade to 7+? I don't think DSA keys will ever be enabled by default in the future.

**Comment by mischief** [comment]
@FirefighterBlu3 we will likely suggest folks move off dsa keys and give some lead time, and switch a while after the announcement. alternatively we may patch the source to re-enable dsa keys in 7.0+, and disable it at a later time after an announcement.

**Comment by mischief** [comment]
fixed in coreos/coreos-overlay#1672.
