### ISSUE TITLE
git clone --recursive is not working 

### ISSUE THREAD

**Issue by ntrifunovic** [coreos/bugs#452]
The error reported:

```
/usr/libexec/git-core/git-submodule: line 159: /usr/bin/perl: No such file or directory
```

Version: CoreOS stable (723.3.0)

**Comment by kooyeed** [comment]
me too.

**Comment by mischief** [comment]
as expressed elsewhere (coreos/coreos-overlay#891), we ship no interpreters like perl, or python.

**Comment by crawford** [comment]
This seems to work now (related https://github.com/coreos/bugs/issues/585).
