### ISSUE TITLE
[Upstram fixed] systemd 222 machined thinks all machines terminate on "systemctl daemon-reload

### ISSUE THREAD

**Issue by floriankoch** [coreos/bugs#454]
Coreos 766.1.0

Upstream fix
https://github.com/systemd/systemd/issues/376

**Comment by f0** [comment]
@marineam @crawford   you really have relesed a stable version with this error?

**Comment by crawford** [comment]
Fixed in https://github.com/coreos/coreos-overlay/pull/1540. It has been backported and will roll out in the next Beta and Stable.
