### ISSUE TITLE
weird jq version in the build

### ISSUE THREAD

**Issue by xied75** [coreos/bugs#455]
Not a big deal. Running this:
```
jq --version
```
only return this:
```
jq-
```
which it should be something like this:
```
jq-1.5rc1-48-g7d6d406
```

**Comment by mischief** [comment]
@xied75 this appears to happen if jq is compiled outside of it's git repo, which is the case in the gentoo ebuild for jq. i filed a bug at https://bugs.gentoo.org/show_bug.cgi?id=559334.

**Comment by jaroslavl1** [comment]
It's not just the missing version, but date functions are missing too.

Try for example
```
echo "1425599507" | jq 'todateiso8601'
```
you get 
```
error: todateiso8601 is not defined
todateiso86011 compile error
```
if you run it using jq 1.5 downloaded from https://stedolan.github.io/jq/download/ it works fine

**Comment by crawford** [comment]
@jaroslavl1 the date/time functions were added in [1.5](https://github.com/stedolan/jq/releases/tag/jq-1.5) but CoreOS only ships 1.4. Of course, you wouldn't know that because the version string is missing. :sob:
