### ISSUE TITLE
Godep: merge with recent speakeasy to get Solaris support

### ISSUE THREAD

**Issue by akolb1** [coreos/bugs#456]
Currently etcdctl can't be compiled on Solaris because speakeasy didn't have Solaris support which is now added to speakeasy.

**Comment by mischief** [comment]
@yichengq @xiang90 can you guys handle this?

**Comment by akolb1** [comment]
@xiang90 What is the procedure for updating Godep?

**Comment by xiang90** [comment]
@akolb1 See https://github.com/tools/godep#update-a-dependency

**Comment by yichengq** [comment]
@akolb1 Are these Godep missings fixed yet?

**Comment by yichengq** [comment]
i checked etcd commit history and saw you have fixed it. Thanks for contribution!
