### ISSUE TITLE
rkt complains of missing gid

### ISSUE THREAD

**Issue by NeilW** [coreos/bugs#459]
CoreOS 794.0.0

Running 'sudo rkt install' from a fresh installation gives:

core@srv-iok62 ~ $ sudo rkt install
install: error looking up rkt gid: "rkt" group not found

Either the GID requirement is spurious, or the settings on the /var/lib/rkt directory are incorrect.

**Comment by jonboulle** [comment]
Strange, the group should have been added in 779.0.0. What does `getent group rkt` return?

**Comment by mischief** [comment]
crap.

```
core@core1 ~ $ grep VERSION_ID /etc/os-release 
VERSION_ID=801.0.0
core@core1 ~ $ sudo rkt install
install: error looking up rkt gid: "rkt" group not found
core@core1 ~ $ getent group rkt
```

**Comment by NeilW** [comment]
Also

core@srv-2kiup ~ $ sudo ls -la /var/lib/rkt
total 24
drwx------  3 root root 4096 Sep 11 05:54 .
drwxr-xr-x 19 root root 4096 Sep 11 05:54 ..
drwx------  8 root root 4096 Sep 11 05:54 pods


No write permission for group, nor is there setgid on the directory to
ensure the GID of the directory is propagated to files and sub-directories.


On 11 September 2015 at 03:27, Nick Owens <notifications@github.com> wrote:

> crap.
>
> core@core1 ~ $ grep VERSION_ID /etc/os-release
> VERSION_ID=801.0.0
> core@core1 ~ $ sudo rkt install
> install: error looking up rkt gid: "rkt" group not found
> core@core1 ~ $ getent group rkt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coreos/bugs/issues/459#issuecomment-139432061>.
>



-- 
Neil Wilson

**Comment by NeilW** [comment]
And possibly:

  core@srv-2kiup ~ $ sudo ls -la /etc/rkt
  ls: cannot access /etc/rkt: No such file or directory

if the GID on that area is important.
