### ISSUE TITLE
coreos.com: RSS feed for release notifications

### ISSUE THREAD

**Issue by jumanjiman** [coreos/bugs#461]
would it be possible to add an RSS feed for https://coreos.com/releases/

i'm not sure at the moment how people would use it for automated workflows,
but it seems like it could be useful.

**Comment by bcwaldon** [comment]
Additionally, I would like to see a platform-specific API that lets me discover the latest image ID programmatically. I currently have to manually head over to https://coreos.com/os/docs/latest/booting-on-ec2.html and copy the AMI ID I care about into my application. It would be cool I could hit an API like this:

```
GET /aws/<channel>

{
  "<region>": {"hvm": "<ami-id>", "pv": "<ami-id>"},
  ...
}
```

**Comment by crawford** [comment]
http://alpha.release.core-os.net/amd64-usr/current/coreos_production_ami_all.json

**Comment by bcwaldon** [comment]
@crawford that does solve my problem, but it's a little annoying to have to iterate through the list and search for my region. In the format I suggested, the data is indexed such that I can do a direct lookup: `output[<region>]["hvm"]`.

**Comment by robszumski** [comment]
I propose two different sets of feeds:

1. `coreos.com/releases/releases.xml`

```
{
  "700.1.2": {
    "release_date": "2015-09-03T00:01:48Z",
    "major_software": {
      "etcd": "0.4.9"
      ...
    },
    "release_notes": "Bug fixes:\n - Fix possible race condition with Ignition..."
  }
}
```
2\. `coreos.com/releases/<channel>.xml`

```
{
  "release_info": {
    "version": "700.1.2",
    "release_date": "2015-09-03T00:01:48Z",
  },
  "platforms": {
    "aws": {
      "us-east-1": {
        "hvm": "ami-76bbba6b",
        "pv": "ami-2277ff22"
      },
      ...
    }
  }
}
```

**Comment by bcwaldon** [comment]
@robszumski not breaking the responses down by platform will result in ever-growing JSON documents, and consumers will have to do more and more work over time. I would suggest that we at least provide platform-specific URLs.

**Comment by crawford** [comment]
Why would they have to do more work over time?

**Comment by robszumski** [comment]
I'm not sure if it is more work over time, but after thinking about it, only ec2 and rackspace have specific image IDs anyways. Most platforms have a slug like `coreos-stable` that they allow us to update.

**Comment by robszumski** [comment]
https://coreos.com/releases/ now contains a link to https://coreos.com/releases/releases.json

Additionally, there are:

https://coreos.com/dist/aws/aws-alpha.json
https://coreos.com/dist/aws/aws-beta.json
https://coreos.com/dist/aws/aws-stable.json
