### ISSUE TITLE
Docker fails to start after upgrade from Stable 723.3.0 to Stable 766.3.0 - causing outage...

### ISSUE THREAD

**Issue by slabrador09** [coreos/bugs#466]
```
core@ip-10-0-0-124 ~ $ sudo systemctl start docker.socket
core@ip-10-0-0-124 ~ $ sudo systemctl start docker.service
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
```

Results:

```
-- Unit docker.service has begun starting up.
Sep 09 23:02:47 ip-10-0-0-124.ec2.internal docker[11371]: time="2015-09-09T23:02:47.617025837Z" level=fatal msg="Error starting daemon: error initializing graphdriver: \"/var/lib/docker\" contains other graphdrivers: overlay; Please cleanup or explicitly choose storage 
Sep 09 23:02:47 ip-10-0-0-124.ec2.internal systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Sep 09 23:02:47 ip-10-0-0-124.ec2.internal systemd[1]: Failed to start docker.service.
```

**Comment by crawford** [comment]
By default, we should be exporting `DOCKER_DRIVER=btrfs` or `DOCKER_DRIVER=overlay` depending on the filesystem at that mountpoint/directory.

@slabrador09 can you show me the output of `systemctl cat docker`?

**Comment by mischief** [comment]
@slabrador09, have you recently changed/copied fs in /var/lib/docker? can you send the output of the following command:

```
findmnt --target /var/lib/docker
```

**Comment by slabrador09** [comment]
@crawford 
core@ip-10-0-0-124 ~ $ systemctl cat docker
# /etc/systemd/system/docker.service
Documentation=http://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
EnvironmentFile=-/etc/docker/docker
ExecStart=/usr/bin/docker -d -H fd:// $OPTIONS
LimitNOFILE=1048576
LimitNPROC=1048576

[Install]
Also=docker.socket

**Comment by slabrador09** [comment]
findmnt --target /var/lib/docker
TARGET SOURCE     FSTYPE OPTIONS
/      /dev/xvda9 ext4   rw,relatime,data=ordered

**Comment by slabrador09** [comment]
I have a production cluster on AWS EC2 instances and this issue is on every node that has upgraded so far... I'm afraid that the other upgrades will kick in soon and that will cause total unavailability for us.

**Comment by mischief** [comment]
@slabrador09 this looks like a custom systemd unit. can you try to use the original systemd unit for docker shipped with coreos and see if it resolves the problem?

**Comment by slabrador09** [comment]
Its what shipped since 600 versions but I added the $OPTIONS to support insecure registry.

**Comment by slabrador09** [comment]
I'll try that out now

**Comment by slabrador09** [comment]
Man that fixed it on one of the nodes! Going to propagate that change. I've had these running for nearly a year now and I don't think that service file ever changed after each update. Is there a way to tell when major files like this need updating?

**Comment by mischief** [comment]
@slabrador09 CoreOS doesn't maintain any services in /etc/systemd/system. if a service was put there, it was by your system configuration. we maintain the files in /usr, and the unit /usr/lib64/systemd/system/docker.service specifically to hide problems that may arise when upgrading docker.

if you need to change it, please use a systemd drop-in or set appropriate environment variable. for example, you can write a drop-in which sets `$DOCKER_OPTS` to influence the arguments passed to docker daemon.

**Comment by slabrador09** [comment]
Do you happen to have a URL to point me in the direction of creating drop-ins?

**Comment by robszumski** [comment]
Here ya go: https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html

It's a new doc, would love any feedback if you have it!

**Comment by slabrador09** [comment]
Thanks!
