### ISSUE TITLE
iptables-restore.service and docker.service conflict

### ISSUE THREAD

**Issue by polarina** [coreos/bugs#469]
The services `iptables-restore.service` and `docker.service` can cause each other to fail to start when starting concurrently.

The `iptables-restore` utility can fail when `iptables` is being altered while it's running. Docker does such alterations when it's starting.

Here's an excerpt of the relevant logs from `journalctl`:

    Sep 13 02:07:09 localhost systemd[1]: Starting Restore iptables firewall rules...
    Sep 13 02:07:09 localhost coreos-cloudinit[650]: 2015/09/13 02:07:09 Calling unit command "start" on "iptables-restore.service"'
    Sep 13 02:07:09 localhost systemd-networkd[756]: docker0: Configured
    Sep 13 02:07:10 localhost dockerd[697]: time="2015-09-13T02:07:10.039135798Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" networ: Failed to Setup IP tables: Unable to enable NAT rule: iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.42.1/16 ! -o docker0 -j MASQUERADE: iptables: Resource temporarily unavailable.\n (exit status 4)"
    Sep 13 02:07:10 localhost systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
    Sep 13 02:07:10 localhost systemd[1]: docker.service: Unit entered failed state.
    Sep 13 02:07:10 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
    Sep 13 02:07:10 localhost iptables-restore[807]: iptables-restore: line 9 failed
    Sep 13 02:07:10 localhost systemd[1]: iptables-restore.service: Main process exited, code=exited, status=1/FAILURE
    Sep 13 02:07:10 localhost systemd[1]: Failed to start Restore iptables firewall rules.
    Sep 13 02:07:10 localhost systemd[1]: iptables-restore.service: Unit entered failed state.
    Sep 13 02:07:10 localhost systemd[1]: iptables-restore.service: Failed with result 'exit-code'.
    Sep 13 02:07:10 localhost coreos-cloudinit[650]: 2015/09/13 02:07:10 Result of "start" on "iptables-restore.service": failed

Line 9 in `/var/lib/iptables/rules-save` is simply `COMMIT` and is the last line.

Note that `docker.service` does not start by default on boot unless you have an enabled service that requires it.

**Comment by mischief** [comment]
@polarina what docker containers and iptables rules do you have at the time of the failure?

**Comment by polarina** [comment]
I was able to make a minimal reproducible test-case. I made a new virtual machine and booted into the ISO (version 801.0.0).

    $ scp x@y:z config.yaml
    $ sudo coreos-install -d /dev/sda -C alpha -c config.yaml
    $ sudo reboot

Once the reboot's complete, SSH into the machine and reboot it again (this is for systemd to pick up on the enablement of `container.service`). `systemctl status iptables-restore` will indicate that it has failed.

Here's the cloud-config file:

    #cloud-config
    
    coreos:
      units:
        - name: iptables-restore.service
          command: start
        - name: container.service
          enable: true
          content: |
            [Unit]
            Description=Stuff Going on Here
            After=docker.service
    
            [Service]
            TimeoutStartSec=0
            ExecStartPre=-/usr/bin/docker kill %n
            ExecStartPre=-/usr/bin/docker rm %n
            ExecStart=/usr/bin/docker run --name %n debian
    
            [Install]
            WantedBy=multi-user.target
    
    write_files:
      - path: /var/lib/iptables/rules-save
        permissions: 0644
        owner: root:root
        content: |
          *nat
          -A POSTROUTING -o enp7s0 -j MASQUERADE
          COMMIT
          *filter
          :FORWARD DROP [0:0]
          -A FORWARD -i enp7s0 -o enp9s1 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
          -A FORWARD -i enp9s1 -o enp7s0 -j ACCEPT
          COMMIT

You may wish to add your SSH key to the cloud-config.

**Comment by polarina** [comment]
I did some further testing with this, and a sufficient workaround is to add `iptables-restore.service` to the `Requires` and `After` options of `docker.service`.

I do not know why the dependency of `network.target` is insufficient to guarantee sequential startup of these two services.

**Comment by eyakubovich** [comment]
I think the reason this happens is b/c cloud-config gets run early and starts `container.service` before `iptables-restore.service` is scheduled to start. `container.service` has `After=docker.service` but not `Requires=docker.service` so it does not actually activate any of the dependencies.

**Comment by mischief** [comment]
@polarina if using Requires=iptables-restore.service in docker.service is enough to ensure ordering, can this issue be closed?

**Comment by polarina** [comment]
It can be.

**Comment by PieterScheffers** [comment]
What is the best way to add the 'Requires=iptables-restore.service' to the docker.service?

I currently just create a new docker.service file with the contents of the original + the extra Requires.
But this is probably going to give problems when CoreOS is updated.

```
#cloud-config

coreos:
  units:
    # enable and start iptables-restore
    - name: iptables-restore.service
      enable: true
    - name: docker.service
      enable: true
      content: |
        [Unit]
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.com
        After=containerd.service docker.socket network.target
        # added extra Requires for iptables-restore
        # to make docker start after iptables
        Requires=iptables-restore.service containerd.service docker.socket

        [Service]
        Type=notify
        EnvironmentFile=-/run/flannel/flannel_docker_opts.env

        # the default is not to use systemd for cgroups because the delegate issues still
        # exists and systemd currently does not support the cgroup feature set required
        # for containers run by docker
        ExecStart=/usr/lib/coreos/dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock $DOCKER_OPTS $DOCKER_CGROUPS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ
        ExecReload=/bin/kill -s HUP $MAINPID
        LimitNOFILE=1048576
        # Having non-zero Limit*s causes performance problems due to accounting overhead
        # in the kernel. We recommend using cgroups to do container-local accounting.
        LimitNPROC=infinity
        LimitCORE=infinity
        # Uncomment TasksMax if your systemd version supports it.
        # Only systemd 226 and above support this version.
        TasksMax=infinity
        TimeoutStartSec=0
        # set delegate yes so that systemd does not reset the cgroups of docker containers
        Delegate=yes

        [Install]
        WantedBy=multi-user.target

    - name: nginx-entry.service
      enable: true
      content: |
        [Unit]
        Description=Nginx Entry Container
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill nginx-entry
        ExecStartPre=-/usr/bin/docker rm nginx-entry
        ExecStartPre=/usr/bin/docker pull nginx:latest
        ExecStart=/usr/bin/docker run --name nginx-entry -p 80:80 -p 443:443 nginx
        ExecStop=/usr/bin/docker stop nginx-entry
        ExecReload=/usr/bin/docker kill -s HUP nginx-entry

        [Install]
        WantedBy=multi-user.target
write_files:
  - path: /var/lib/iptables/rules-save
    permissions: 0644
    owner: root:root
    content: |
      *filter
      :INPUT DROP [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [0:0]

      # Accept all loopback (local) traffic:
      -A INPUT -i lo -j ACCEPT

      # Accept all CoreOS cluster traffic
      #-A INPUT -i eth1 -j ACCEPT

      # Accept all traffic on the local network from other members of
      # our CoreOS cluster:
      #-A INPUT -i eth1 -p tcp -s coreos-1_private_ip -j ACCEPT
      #-A INPUT -i eth1 -p tcp -s coreos-2_private_ip -j ACCEPT
      #-A INPUT -i eth1 -p tcp -s coreos-3_private_ip -j ACCEPT

      # Keep existing connections (like our SSH session) alive:
      -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

      # Accept all TCP/IP traffic to SSH, HTTP, and HTTPS ports
      -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT

      # Accept pings:
      -A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
      -A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT
      -A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT
      COMMIT

```

**Comment by euank** [comment]
@PieterScheffers The preferred way is via a drop-in, as documented here: https://coreos.com/os/docs/latest/customizing-docker.html#drop-in-configuration

That page of documentation could use some improvements, but the term 'systemd drop-in' is also a good way to search for more general information on customizing systemd units.

**Comment by PieterScheffers** [comment]
OK thanks!

I changed the cloud-config.yml to this:

```
#cloud-config

coreos:
  units:
    # enable and start iptables-restore
    - name: iptables-restore.service
      enable: true

    - name: docker.service
      enable: true
      dropins:
        - name: 10-requires_iptables-restore.conf
          contents: |
            [Unit]
            Requires=iptables-restore.service containerd.service docker.socket

...rest of cloud-config
```

**Comment by euank** [comment]
@PieterScheffers the documentation I linked, I should have mentioned, is using [Ignition](https://coreos.com/ignition/docs/latest/what-is-ignition.html) (via [Container Linux Configs](https://coreos.com/os/docs/latest/configuration.html)).

We've deprecated cloud-config in favor of ignition for a number of reasons and I'd recommend switching if you can.

One, which is relevant here, is that it runs early enough that it can avoid races with networkd (and thus setup firewalls before the network is up, which cloud-init can't do).

**Comment by PieterScheffers** [comment]
That is too bad. I liked the yaml syntax for embedding files. The ignition (json) syntax isn't as user friendly for that. I just started using CoreOS, so I better start using Ignition syntax anyway. Thanks for the heads up!

**Comment by crawford** [comment]
@PieterScheffers you can have your cake and eat it too. Check out this [provisioning doc](https://coreos.com/os/docs/latest/provisioning.html) (@euank, this is the link we should hand out to users) for details on Container Linux Configs (YAML).

**Comment by PieterScheffers** [comment]
Thanks @euank and @crawford. I now use the [Container Linux Config Transpiler](https://github.com/coreos/container-linux-config-transpiler) to transpile a [Configuration Specification](https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/configuration.md) yaml file.

With it I created a yaml file to be compiled with the ct program. The docker.service dropin isn't needed anymore, if I understand correctly.

```
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAA...

update:
  group: stable

systemd:
  units:
    # enable iptables
    - name: iptables-restore.service
      enable: true

    # install docker-compose
    - name: install-docker-compose.service
      enable: true
      contents: |
        [Unit]
        Description=Install docker-compose

        [Service]
        Type=oneshot

        # create /opt/bin directory
        ExecStart=/usr/bin/mkdir -p /opt/bin/

        # sleep 2 seconds
        ExecStart=/usr/bin/sleep 2

        # get docker-compose from github
        # -q quiet
        # -nc don't fetch if file already exists (return 0)
        ExecStart=/bin/wget -q -nc -O /opt/bin/docker-compose "https://github.com/docker/compose/releases/download/1.13.0/docker-compose-linux-x86_64"

        # set execution rights
        ExecStart=/usr/bin/chmod +x /opt/bin/docker-compose

storage:
  files:
    # write iptables rules
    - filesystem: root
      path: /var/lib/iptables/rules-save
      mode: 0644
      user: 
        id: 0
      group:
        id: 0
      contents:
        inline: |
          *filter
          :INPUT DROP [0:0]
          :FORWARD DROP [0:0]
          :OUTPUT ACCEPT [0:0]

          # Accept all loopback (local) traffic:
          -A INPUT -i lo -j ACCEPT

          # Accept all CoreOS cluster traffic
          #-A INPUT -i eth1 -j ACCEPT

          # Accept all traffic on the local network from other members of
          # our CoreOS cluster:
          #-A INPUT -i eth1 -p tcp -s coreos-1_private_ip -j ACCEPT
          #-A INPUT -i eth1 -p tcp -s coreos-2_private_ip -j ACCEPT
          #-A INPUT -i eth1 -p tcp -s coreos-3_private_ip -j ACCEPT

          # Keep existing connections (like our SSH session) alive:
          -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

          # Accept all TCP/IP traffic to SSH, HTTP, and HTTPS ports
          -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT

          # Accept pings:
          -A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT
          -A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT
          COMMIT

...
```
