### ISSUE TITLE
motd is regenerated constantly

### ISSUE THREAD

**Issue by robszumski** [coreos/bugs#47]
User reported this on 343.0.0 and their machine doesn't have any failed units on it.

My 338.0.0 machine also has this behavior and my machine has a failed unit which I see in the motd. Seems like the regeneration doesn't actually have anything to do with failed units or not.
```
core@ip-10-238-211-47 ~ $ journalctl -n 400 | grep motd
Jun 11 21:37:21 ip-10-238-211-47 systemd[1]: Starting Generate /run/coreos/motd...
Jun 11 21:37:21 ip-10-238-211-47 systemd[1]: Started Generate /run/coreos/motd.
Jun 11 21:38:21 ip-10-238-211-47 systemd[1]: Starting Generate /run/coreos/motd...
Jun 11 21:38:21 ip-10-238-211-47 systemd[1]: Started Generate /run/coreos/motd.
Jun 11 21:39:21 ip-10-238-211-47 systemd[1]: Starting Generate /run/coreos/motd...
Jun 11 21:39:21 ip-10-238-211-47 systemd[1]: Started Generate /run/coreos/motd.
Jun 11 21:40:21 ip-10-238-211-47 systemd[1]: Starting Generate /run/coreos/motd...
Jun 11 21:40:21 ip-10-238-211-47 systemd[1]: Started Generate /run/coreos/motd.
Jun 11 21:41:21 ip-10-238-211-47 systemd[1]: Starting Generate /run/coreos/motd...
Jun 11 21:41:21 ip-10-238-211-47 systemd[1]: Started Generate /run/coreos/motd.
Jun 11 21:42:21 ip-10-238-211-47 systemd[1]: Starting Generate /run/coreos/motd...
Jun 11 21:42:21 ip-10-238-211-47 systemd[1]: Started Generate /run/coreos/motd.
```

**Comment by pwaller** [comment]
Bump and :+1:. This logspam is annoying. I've arrived at this issue (#47) a couple of times before deciding it was worth :+1:'ing it.

**Comment by oldgit** [comment]
@pwaller - The motd message is logged at priority *info*. 
journalctl **-p notice** will filter out *info* & *debug* messages, showing from *notice* to *emerg* messages.
Using this filter will alleviate the logspam annoyance ;-)

See: http://www.freedesktop.org/software/systemd/man/journalctl.html for further info.
The log priorities are: "emerg" (0), "alert" (1), "crit" (2), "err" (3), "warning" (4), "notice" (5), "info" (6), "debug" (7).

**Comment by pwaller** [comment]
That filters out too much, all of my application logs go out of the window with it..

**Comment by oldgit** [comment]
@pwaller - sorry I thought it could help... 
Maybe if the motd messages were logged at *debug* priority instead of *info*, journal -p info could work as a filter for you?
However, I can't see how in systemd you can explicitly specify the log priority for the motdgen.service

**Comment by pwaller** [comment]
@oldgit, thanks, I do appreciate it. The problem is that the spammy messages are generated by systemd itself whenever the service restarts. I'm not aware that this is configurable at all, let alone on a per-service basis..

**Comment by oldgit** [comment]
According to http://www.freedesktop.org/software/systemd/man/systemd.exec.html, the directive:
SyslogLevel=debug can be used in the service definition. I've edited the motdgen.service (sudo systemctl edit --full motdgen.service) and added it, rebooted but still get the motd messages with journalctl -p info. I thought I was close but it doesn't seem to work... :-(

**Comment by pwaller** [comment]
From that page:

> This option is only useful when StandardOutput= or StandardError= are set to syslog or kmsg

This is for the log level to use for the programs output, but as I said above, the spam isn't coming from program output, it's coming from systemd, which is saying "Hey, I'm starting motdgen!" "Hey, motdgen was started!", etc :)

**Comment by oldgit** [comment]
Ah yes - systemd for any unit, x logs to info "Starting x", Started x"... and motdgen.timer does this every minute...
It would be great if you could specify the log level for those systemd start messages on a per service/unit basis...
A hack /workaround would be to put the periodic timer in the motd bash and drop the motdgen.timer

**Comment by pwaller** [comment]
Is there a way to turn off the motdgen altogether? I need to do this now to show a different MOTD and I don't want CoreOS's motd at all right now. `sudo systemd disable motdgen.service` or `.timer` don't work.

**Comment by pwaller** [comment]
I would also like to turn off issuegen.

**Comment by crawford** [comment]
@pwaller you can use `systemd mask {motd,issue}gen.service`.

**Comment by pwaller** [comment]
Aha, thanks @crawford!

**Comment by djui** [comment]
For completeness, one should also mask `motdgen.{path,timer}` (in addition to `{motd,issue}gen.service`).

**Comment by kayrus** [comment]
Also was fixed here: https://github.com/coreos/init/pull/187
