### ISSUE TITLE
CoreOS stable (766.3.0) frequent (docker) networking failures

### ISSUE THREAD

**Issue by martingartonft** [coreos/bugs#471]
We are being hit quite hard by what looks like this:

https://github.com/docker/docker/issues/14738#issuecomment-126739687

.. since upgrading to CoreOS stable (766.3.0)

Our cluster is pretty unstable as a result and right now, we are regularly rebooting individual hosts when we see the symptoms as a workaround.

It is claimed fixed in 1.8.x but I don't see plans to backport to 1.7.x.

Is there any indication when docker 1.8.x might make it to stable.  Otherwise any suggestion on what to do in the meantime?

Let me know if I can help or if I need to provide more information.

**Comment by basvdlei** [comment]
We saw the same issue on 1 of our ~30 CoreOS vm's. It seems to me like a upgrade issue, therefore I stopped Docker, removed all Docker related data files and rebooted the machine:

```sh
systemctl stop docker.service
rm -rf /var/lib/docker/*
reboot
```
I've not (yet) seen this issue return.

**Comment by martingartonft** [comment]
We have still seen the same issue after doing workaround suggested by basvdlei.

It's the reboot (most likely the network interface cleanup & docker restart) that solves it I think, but only temporarily.

It seems to be a known bug in the version of docker that CoreOS stable uses, and is claimed fixed in a later version.

Is there a way to "manually" upgrade docker (but only docker) in our CoreOS cluster to see if that fixes it?

**Comment by jeremyd** [comment]
+1 I'm currently seeing this issue on CoreOS stable 766.3.0.  It seems that not every instance launched experiences this.  Some instances will have many failures, others seem not to encounter this.

**Comment by crawford** [comment]
Fixed in https://github.com/coreos/docker/pull/6. This will roll out in the next Beta and Stable.

**Comment by iamruinous** [comment]
We were experiencing a lot of docker0 failures on 766.3.0.

Upgraded to 766.4.0 and now constantly experiencing a different docker0 error.

```
dockerd[730]: time="2015-09-17T18:11:21.685146925Z" level=error msg="HTTP Error" 
err="Cannot start container ed3f53b3a3e863ac4332208aaa6c919653487fc34b9e8f734e3a63185f333484: 
iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 50278 -j DNAT 
--to-destination 172.17.0.59:80 ! -i docker0: iptables: 
No chain/target/match by that name.\n (exit status 1)" statusCode=500 Context
```

We now have many containers that start up without any network access.

**Comment by iamruinous** [comment]
Host machine is also unable to pull images

```
Pulling repository octoblu/vctl
Get https://index.docker.io/v1/repositories/octoblu/vctl/images: 
dial tcp: lookup index.docker.io: Temporary failure in name resolution
```

**Comment by crawford** [comment]
@iamruinous Can you file a separate bug?
