### ISSUE TITLE
record kernel crash dumps after panic

### ISSUE THREAD

**Issue by andrewhsu** [coreos/bugs#477]
Kernel crash dumps would be useful for post-mortem analysis of panics. Would be good to have CoreOS instrumented with all the tools to capture vmcore files automatically with an ability to activate easily.

This would be useful for iPXE installations on different hardware (RAID, NICs, etc.) that would load different kernel drivers. Capturing the crash dump info on panic would help greatly with diagnostics using the `crash` utility.

Since capture of the vmcore requires memory set aside with the kernel option `crashkernel`, perhaps we can use this option to activate much like [sshkey](https://coreos.com/os/docs/latest/booting-with-ipxe.html) kernel option is used to setup ssh access.

The `kexec` tool loads a kernel into the reserved memory space. Seems like different distros have implemented a `kdump` service to manage loading the kernel and/or a corresponding initrd that has the scripts for capturing the vmcore.

There are many ways to skin this cat and it looks like different distros have slightly different implementations of how a kdump service would behave:
* https://fedoraproject.org/wiki/How_to_use_kdump_to_debug_kernel_crashes
* https://wiki.gentoo.org/wiki/Kernel_Crash_Dumps
* https://help.ubuntu.com/lts/serverguide/kernel-crash-dump.html

Perhaps a minimal starting point of just getting the vmcore file into `/var/crash/` and rebooting the box. This doc hints at what the minimal setup would need:
https://rich0gentoo.wordpress.com/2011/11/11/kdump-on-gentoo/

**Comment by jerryhwang72** [comment]
Any update in progress if someone can share or point to on this item?

**Comment by philips** [comment]
@jerryhwang72 There is no update on this, sorry. It is desirable to add this functionality but we haven't prioritized it for work.

**Comment by cneth** [comment]
+1 for this.  We have a 500+ node cluster where we are seeing some 'random' hard lockups and it's been a real challenge to try and capture a serial console log - we have BMC's but the SOL mechanism is sometimes a little flaky; so far we haven't managed to capture anything useful over this channel.    Without it we've got no other reliable way to capture the problem.

**Comment by vtl** [comment]
I agree that is... unusual for Linux distro in year 2016 to not have a kdump support. If the project is not a localhost toy, it does cause kernel-level bugs, for one reason or another. Kdump is a must.

@cneth If your situation is that bad, you still can fire up kdump from docker container. At least I was able to do so using RHEL-6 (CentOS) container and couple of tweaks in mkdumprd script. You also need to preserve vmlinux with debug symbols, which is normally wiped out during CoreOS build in favor of stripped vmlinuz. But it's all doable. Or use more developer-friendly distro where both kdump and docker are supported.

**Comment by cneth** [comment]
We discovered with some help from Alex Crawford at CoreOS that the ptrace mechanism is enabled on CoreOS, and we were able to use that to collect dmesg logs anyways, which have been helpful.

**Comment by cvanlabe** [comment]
+1 for this. Being able to send a crash dump to another server for later inspection is very much wished for.

**Comment by crawford** [comment]
@cvanlabe you can use the pstore (assuming your hardware supports it).

**Comment by cvanlabe** [comment]
Hi @crawford , our VM is running off of VMware 6 VM's and we're trying to understand the random crashes & reboots we're facing. I don't have experience with pstore, but if that's the way to get the reason of these kind of crashes then we should probably close this bug and put it in FAQ?

**Comment by crawford** [comment]
> put it in FAQ?

I agree. I'll see if I can write up some docs today. Would you mind reviewing them to make sure they are helpful?

**Comment by cvanlabe** [comment]
of course!

**Comment by crawford** [comment]
@cvanlabe here is an initial stab https://github.com/coreos/docs/pull/874

**Comment by crawford** [comment]
We've added [docs](https://github.com/coreos/docs/blob/master/os/collecting-crash-logs.md) detailing how to use the pstore to collect crash logs.
