### ISSUE TITLE
Docker logs in 1.8.2

### ISSUE THREAD

**Issue by AntouanK** [coreos/bugs#483]
Just updated my vagrant box today, to CoreOS [808.0.0](https://coreos.com/releases/#808.0.0) which has Docker 1.8.2.
The problem I face is I cannot see the logs of the containers anymore.

So now when I do
`docker logs -f SOME_CONTAINER` 
it returns 
```
"logs" command is supported only for "json-file" logging driver (got: journald)
```

I downgraded my Vagrant box to CoreOS 766.3.0 which has docker 1.7.1 and logging works fine again.
Any idea on what's going wrong in the latest Docker version?

**Comment by basvdlei** [comment]
Docker's default log driver was changed to journald (https://github.com/coreos/coreos-overlay/pull/1539) in response to https://github.com/coreos/bugs/issues/472.

You should be able to tail your container logs using the journal:

```sh
journalctl -f CONTAINER_NAME=SOME_CONTAINER
```

**Comment by AntouanK** [comment]
I see.
So how is the [`logs`](https://docs.docker.com/reference/commandline/logs/) command going to work now?
