### ISSUE TITLE
Add smartctl

### ISSUE THREAD

**Issue by polarina** [coreos/bugs#484]
Is it possible to have the `smartctl` utility added? I'd like to be able to monitor the health and status of my disks.

**Comment by marineam** [comment]
Yeah, I noticed this one myself yesterday. Probably will just add smartctl but not the smart monitoring daemon as it expects to have things like a local MTA which isn't included in CoreOS.

**Comment by arainho** [comment]
+1
smartctl will be great since i have CoreOS running on physical hardware, no hypervisors.

**Comment by jerryhwang72** [comment]
I have a bunch of hard drives on a physical machine. I installed a toolbox and use this for alternative for now.
for i in {a..z};do toolbox --bind=/dev:/dev smartctl --all /dev/sd"$i";done

**Comment by arainho** [comment]
Just great, it works like a charm :-)
Many thanks

**Comment by johscheuer** [comment]
Was smartctl from the toolbox removed?

```Bash
$ toolbox smartctl --help
Spawning container core-fedora-latest on /var/lib/toolbox/core-fedora-latest.
Press ^] three times within 1s to kill container.
execv() failed: No such file or directory
Container core-fedora-latest failed with error code 1.
```

**Comment by crawford** [comment]
`toolbox` is just a vanilla Fedora image. You'll need to install it via `dnf` before you can use it.

**Comment by crawford** [comment]
Smartctl can be used via toolbox. We aren't going to add this to the base image.
