### ISSUE TITLE
failed to load cloud-config on alpha 808.0 after reboot

### ISSUE THREAD

**Issue by bchanan03** [coreos/bugs#486]
I have 4 machines running CoreOS cluster using alpha 808.0 recently updated
Now after update it fails to load the user_data file and shows error:
user-cloudinit@var-lib-coreos\x2dinstall-user_data.service
Checking the user_data file against CoreOS cloud-config validator - no issue found.

Logs:
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Writing file to "/run/flannel/options.env"
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Wrote file to "/run/flannel/options.env"
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Wrote file /run/flannel/options.env to filesystem
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Writing drop-in unit "50-network-config.conf" to filesy
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Writing file to "/etc/systemd/system/flanneld.service.d
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Wrote file to "/etc/systemd/system/flanneld.service.d/5
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Wrote drop-in unit "50-network-config.conf"
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Writing drop-in unit "60-docker-wait-for-flannel-config
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Writing file to "/etc/systemd/system/docker.service.d/6
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Wrote file to "/etc/systemd/system/docker.service.d/60-
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Wrote drop-in unit "60-docker-wait-for-flannel-config.c
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Enabling unit file "rpc-mountd.service"
Sep 20 09:56:07 host01-il-devops.saas.lab coreos-cloudinit[596]: 2015/09/20 09:56:07 Failed to apply cloud-config: No such file or directory
Sep 20 09:56:07 host01-il-devops.saas.lab systemd[1]: user-cloudinit@var-lib-coreos\x2dinstall-user_data.service: Main process exited, code=
Sep 20 09:56:07 host01-il-devops.saas.lab systemd[1]: Failed to start Load cloud-config from /var/lib/coreos-install/user_data.
Sep 20 09:56:07 host01-il-devops.saas.lab systemd[1]: user-cloudinit@var-lib-coreos\x2dinstall-user_data.service: Unit entered failed state.
Sep 20 09:56:07 host01-il-devops.saas.lab systemd[1]: user-cloudinit@var-lib-coreos\x2dinstall-user_data.service: Failed with result 'exit-c

**Comment by crawford** [comment]
Can you capture the logs with the --no-pager flag? The output is cut off.

**Comment by bchanan03** [comment]
Here are the full logs:
http://pastebin.com/KfTZa3L9

I noticed the same issue found on each of the hosts on the cluster.
ASFIK there was no change in the cloud-config file and also I again verified the file against
CoreOS cloud-config validator - no issue there

**Comment by mischief** [comment]
@bchanan03 the problem appears to be that you try to enable rpc-mountd.service. nfs was updated recently, and the new nfs unit for rpc.mountd has no [Install] section, so you can't enable it.

instead of using enable for rpc-mountd and nfsd in cloud-config, can you just use 'start' on 'nfs-server.service'?

**Comment by bchanan03** [comment]
I removed the rpc-mountd.service from the cloud-config (let it start by systemd and not directly explicit by cloud-config) - Now all works. PS: the only reason I had it started was because I used a mounted volume but found rpc service was down after restart.
Thanks a lot for the quick reply
Chanan
