### ISSUE TITLE
Documented process for setting up dockercfg does not work

### ISSUE THREAD

**Issue by zipmark-rops** [coreos/bugs#487]
See https://coreos.com/os/docs/latest/registry-authentication.html

The doc suggests putting a .dockercfg file at /home/core/. This works if you run `docker pull` from a terminal as the core user, but doesn't work in fleet units, because (I assume) systemctl doesn't run as core. 

Related: #236

**Comment by crawford** [comment]
It looks like this has been addressed:

```
The last step is to tell your systemd units to run as the core user in order for Docker to use the credentials we just set up. 
```
