### ISSUE TITLE
cannot allocate memory

### ISSUE THREAD

**Issue by klausenbusk** [coreos/bugs#489]
I get his error on CoreOS alpha (808.0.0), through I have "plenty" of memory available (300mb+).

Like this:
```
Error response from daemon: open /var/lib/docker/overlay/4147d85b3462f5e8db7d445913e63e680ce113c7361f0b3bcd95b3bdbf3d3e11-init/merged/etc/resolv.conf: cannot allocate memory
```

/proc/meminfo
```
MemTotal:         505456 kB
MemFree:            5952 kB
MemAvailable:     372596 kB
Buffers:           97248 kB
Cached:           209948 kB
SwapCached:            0 kB
Active:           265772 kB
Inactive:         134192 kB
Active(anon):      92988 kB
Inactive(anon):      144 kB
Active(file):     172784 kB
Inactive(file):   134048 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                16 kB
Writeback:             0 kB
AnonPages:         92776 kB
Mapped:            65592 kB
Shmem:               356 kB
Slab:              86292 kB
SReclaimable:      70132 kB
SUnreclaim:        16160 kB
KernelStack:        1760 kB
PageTables:         2480 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      252728 kB
Committed_AS:     556088 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        3220 kB
VmallocChunk:   34359732520 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       94200 kB
DirectMap2M:      430080 kB
DirectMap1G:           0 kB
``` 

I haven't found a way to reproduce it. Got it yesterday on one of my web node, and today on the second web node.

**Comment by klausenbusk** [comment]
I found a user with similar problems https://groups.google.com/forum/#!topic/coreos-user/t1RI2K1BdV0

**Comment by klausenbusk** [comment]
Found a way to reproduce it (tested on Digtal Ocean 512mb node):
1. sudo cat /dev/vda > /dev/null
2. docker run --rm=true -t -i debian:jessie ls
`Error response from daemon: open /var/lib/docker/overlay/3aa2541f3c93a58a9dfbfbca6511a18d638c772608f255f38c4c3dc86512c2bb-init/merged/dev/console: cannot allocate memory`
3. Stop the `cat` progress.
4. Try 2 again, it still error.
5. sysctl vm.drop_caches=3
6. Try 2 again, it work.

**Comment by klausenbusk** [comment]
Uploaded meminfo here: http://sprunge.us/GCNa
On a fresh 512MB CoreOS Alpha node, with the above step.

**Comment by klausenbusk** [comment]
Cannot reproduce on CoreOS Stable 766.3.0

**Comment by bfallik** [comment]
This looks very similar to the issue I reported on coreos-user (linked above).

**Comment by leonfs** [comment]
Do you have Swap enabled on the droplet?

**Comment by klausenbusk** [comment]
> Do you have Swap enabled on the droplet? I had similar problems on Ubuntu and by enabling swap all problems went away. But in CoreOS it doesn't seem to work. Swap has more than 900M available and still throws "cannot allocate memory" error.

Nope, I think swap is just a workaround. It seems like docker don't free the memory used by the cache/buffer, it is my theory at least.

**Comment by mischief** [comment]
can you check slabtop when you hit oom condition?

**Comment by leonfs** [comment]
Active / Total Objects (% used)    : 214570 / 236605 (90.7%)
 Active / Total Slabs (% used)      : 8280 / 8280 (100.0%)
 Active / Total Caches (% used)     : 73 / 96 (76.0%)
 Active / Total Size (% used)       : 45571.83K / 48884.55K (93.2%)
 Minimum / Average / Maximum Object : 0.01K / 0.21K / 16.44K

**Comment by klausenbusk** [comment]
Just hit it on CoreOS stable (766.3.0)
When starting docker with from a systemd service file.
```
9d: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 172.17.42.1 --dport 53 -j DNAT --to-destination 172.17.0.239:53 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory)
```
/proc/meminfo
```
MemTotal:         505380 kB
MemFree:          141308 kB
MemAvailable:     304672 kB
Buffers:           69176 kB
Cached:            89980 kB
SwapCached:            0 kB
Active:           284496 kB
Inactive:          31316 kB
Active(anon):     158288 kB
Inactive(anon):      696 kB
Active(file):     126208 kB
Inactive(file):    30620 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:              3028 kB
Writeback:             0 kB
AnonPages:        156684 kB
Mapped:            44560 kB
Shmem:              2328 kB
Slab:              32604 kB
SReclaimable:      16892 kB
SUnreclaim:        15712 kB
KernelStack:        2192 kB
PageTables:         3356 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      252688 kB
Committed_AS:    1029684 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        3304 kB
VmallocChunk:   34359732584 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      528376 kB
DirectMap2M:    18446744073709547520 kB
DirectMap1G:           0 kB
```
Slabtop
```
 Active / Total Objects (% used)    : 151776 / 166505 (91.2%)
 Active / Total Slabs (% used)      : 6014 / 6014 (100.0%)
 Active / Total Caches (% used)     : 72 / 97 (74.2%)
 Active / Total Size (% used)       : 32526.62K / 35323.95K (92.1%)
 Minimum / Average / Maximum Object : 0.01K / 0.21K / 16.00K
```

**Comment by klausenbusk** [comment]
May be related https://github.com/docker/docker/issues/8539

**Comment by bfallik** [comment]
@klausenbusk are you sure the iptables issue is the same? The previous issue you noted and the one I emailed the list about were trigged by launching docker containers, not by running docker itself. Both exhibit the same OOM symptom but they might have different root causes.

**Comment by klausenbusk** [comment]
> @klausenbusk are you sure the iptables issue is the same?

Not sure, they is both a memory allocate problem. The iptables error is also when launching a docker container.

**Comment by klausenbusk** [comment]
@bfallik Could you try to set /sys/kernel/mm/transparent_hugepage/enabled to always, and see if it fix it? I can't reproduce it longer issue on alpha longer.

**Comment by bfallik** [comment]
@klausenbusk yes I can but I'll need to get back to you later today or tomorrow.

**Comment by bfallik** [comment]
@klausenbusk Unless I'm misreading transparent_hugepage/enabled is set to always automatically:
```
core@core-01 ~ $ cat /sys/kernel/mm/transparent_hugepage/enabled
[always] madvise never
```
This is the default setting. I'm still easily able to reproduce the memory allocation errors on CoreOS 815.0.0.

Am I misreading the output or did you mean to suggest I try changing the setting to "madvise" or "never"?

**Comment by klausenbusk** [comment]
> This is the default setting

On Digital Ocean the default is never. What does /proc/buddyinfo? Maybe it some memory fragmentation, through I think the kernel should handle that..

**Comment by bfallik** [comment]
Ah, interesting. I'm running CoreOS from Vagrant on VirtualBox.

> What does /proc/buddyinfo?

```
core@core-01 ~ $ cat /proc/buddyinfo
Node 0, zone      DMA     33    105     87     31     11      2      0      0      0      0      0
Node 0, zone    DMA32   3283   3386   1667    703    395    226    113     44     14      1      0
```

**Comment by klausenbusk** [comment]
@bfallik Could to try setting vm.min_free_kbytes to 50000? I'm really not a expert, just trying to understand how memory work in Linux :) and haven't found a reliable way to reproduce it in the last alpha.

**Comment by bfallik** [comment]
@klausenbusk Sure, no problem. I can reliably reproduce this failure every time on alpha so I'm happy to run trials to help resolve this.

Speaking of which I think we're making progress! I can reliable run the tests by increasing the min_free_kbytes and I can reproduce the failure by reseting it back to the original value.

**Comment by bfallik** [comment]
Ugh, I pressed submit too soon. Please ignore my previous comment. Increasing min_free_kbytes did allow the tests to pass but reseting it back to the original value had no effect. I need to poke around a bit more.

**Comment by klausenbusk** [comment]
> Ugh, I pressed submit too soon. Please ignore my previous comment. Increasing min_free_kbytes did allow the tests to pass but reseting it back to the original value had no effect. I need to poke around a bit more.

Some links, I found when trying to understand memory:
http://engineering.linkedin.com/performance/optimizing-linux-memory-management-low-latency-high-throughput-databases
https://www.kernel.org/doc/Documentation/sysctl/vm.txt (all the config options)
http://stackoverflow.com/questions/21374491/vm-min-free-kbytes-why-keep-minimum-reserved-memory (explanation of when vm.min_free_kbytes is useful)

I do the following steps to trigger it on my node:
1. Fill up buffer/cache until `free -m` says 5 free, with `sudo bash -c "cat /dev/vda > /dev/null"` and `sudo find / -xdev -exec sha1sum {} \;`
2. Run `docker run --rm -t -i debian:jessie ls` and most of the time it says `cannot allocate memory`.
3. `sudo sysctl vm.min_free_kbytes=10000` and `docker run` work.
4. Doing 1 again, it still work.
5. `sudo sysctl vm.min_free_kbytes=2000` do 1 again and I get `cannot allocate memory` again.

**Comment by leonfs** [comment]
@bfallik What is your process to reproduce the error? I would like to help you debug it.

**Comment by bfallik** [comment]
@leonfs Thanks!

It's fairly simple for us to reproduce. We had a set of Docker containers we run as part of our internal integration tests. As of CoreOS 808.0.0 we encounter memory errors every time we invoke the tests on our standard VM size with 1024GB of RAM. In 766.x and earlier versions the tests always pass.

As a workaround for our developers we've increased the default VM size to 1536GB. Obviously this is not a real fix. The increase to 1536GB is why I was confused yesterday. My local VM had been recreated at that the larger size which explained why I saw inconsistent results.

Now that I'm back to 1024GB RAM, here are my results of testing against a fresh 1024GB VM running 815.0.0. Sorry if this is messy but I can clarify if you have any questions.

# trial 1
min_free_kbytes at default (3846);

> Error response from daemon: symlink /proc/mounts 
> /var/lib/docker/overlay/54c6c3840146217ac28fa11af738dc8e8114fd258261e114b6e8c50fb9664c77-
> init/merged/etc/mtab: cannot allocate memory

# trial 2
(same config as trial 1)

similar results:
```
Oct 01 16:19:03 core-01 kernel: postgres: page allocation failure: order:4, mode:
```

# trial 3
```
core@core-01 ~ $ sudo sh -c "echo 50000 >/proc/sys/vm/min_free_kbytes"
core@core-01 ~ $ cat /proc/sys/vm/min_free_kbytes
50000
```
tests pass; tried twice in a row

# trial 4
```
core@core-01 ~ $ sudo sh -c "echo 3846 >/proc/sys/vm/min_free_kbytes"
core@core-01 ~ $ cat /proc/sys/vm/min_free_kbytes
3846
```
tests pass; tried twice in a row

I'm not sure I understand the real effect, if any, min_free_kbytes is having on the results. I'm also not sure if changing this to a lower setting has any effect or if the kernel can only increase the minimum.

It may also be worth mentioning that failures occur very early in the process before the point where the final container, the one actually running the tests, gets started. We encounter memory errors running  containers that wrap test dependencies like postgres and redis.

**Comment by klausenbusk** [comment]
> tests pass; tried twice in a row

Excepted, it take some time before the 461454 kbytes is used again, by cache/buffer. Try wait a little while, or fill the cache/buffer. Kind of explanation of cache/buffer here: http://stackoverflow.com/questions/6345020/linux-memory-buffer-vs-cache
Explanation of why increasing min_free_kbytes help: http://stackoverflow.com/questions/21374491/vm-min-free-kbytes-why-keep-minimum-reserved-memory (first answer)

**Comment by vcaputo** [comment]
I've been able to reproduce this without involving docker at all, so we can eliminate that variable.

Right now it looks like a kernel regression, and overlayfs is effective at triggering it.  Simply read /dev/vda into /dev/null as @klausenbusk did above then try write to a file on overlayfs triggering a copy_up, it will trigger the allocation failure.  There are plenty of reclaimable buffers but for some reason they aren't being reclaimed before kmalloc fails.

**Comment by bfallik** [comment]
@vcaputo nice catch! hopefully the isolated reproduction case will make it easier to track down the regression.

**Comment by vcaputo** [comment]
I've been able to reproduce this now without overlayfs:
1. fresh boot
2. dd if=dev/vda of=/dev/null
3. insmod oomtest.ko

where oomtest.ko is a trivial kernel module which allocates 64KiB like the overlayfs code path which is failing:
```
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/slab.h>

int init_module(void)
{
        int     ret = 0;
        void    *foo;
        printk(KERN_INFO "allocating\n");
        foo = kmalloc(65536, GFP_KERNEL);
        if(!foo) {
                printk(KERN_INFO "allocation failed\n");
                ret = -ENOMEM;
        } else {
                printk(KERN_INFO "allocation succeeded\n");
                kfree(foo);
        }

        return ret;
}

void cleanup_module(void)
{
}
```

So overlayfs is off the hook and this looks firmly to be a kernel mm regression, which might already be fixed upstream, time to test a newer kernel.

**Comment by vcaputo** [comment]
Unable to reproduce on 4.2.2

**Comment by dongsupark** [comment]
@vcaputo thanks! The sample kernel modules looks like a real reproducer for this issue.
I'm also able to trigger the error with kernel 4.2, by running `"cat /dev/vda > /dev/null; find / -xdev -exec sha1sum {} \;"`, followed by `"insmod oomtest.ko"`, as you mentioned.
However, I don't think this issue is gone with 4.2.2. I'm also able to reproduce the error with both 4.2.2 and 4.3-rc4. So this bug persists in newer kernels too.
I'm going to try with older kernel like 4.1, and also try to bisect if possible.

**Comment by pmoust** [comment]
Experiencing the exact same behavior in our prod cluster. Was able to reproduce it as @vcaputo illustrated

**Comment by vcaputo** [comment]
After going down this rabbit hole and coming back up with some revelations and relevant search queries, I found this gem:
http://lkml.iu.edu/hypermail/linux/kernel/1509.2/03675.html

> There are two important side-effects of this. The most important is that
a non-atomic high-order request can fail even though free pages are available
and the order-0 watermarks are ok.

The issue we're stumbling on here seems to be a high-order direct-reclaim allocation when the watermarks haven't been met by the direct-reclaim.  The subsequent getting of free pages fails because it still consults the watermarks for all orders <= the allocation order:
https://github.com/torvalds/linux/blob/master/mm/page_alloc.c#L2547
and
https://github.com/torvalds/linux/blob/master/mm/page_alloc.c#L2260

Direct-reclaim we can see is given a fixed # of pages to reclaim and stops after satisfying this (presumably to minimize latency in the synchronous reclaim path, don't do more work than necessary):
https://github.com/torvalds/linux/blob/master/mm/vmscan.c#L2834

**Comment by pmoust** [comment]
@vcaputo by glancing at LKML, you think this might be solved after 4.3 gets out of RC?

**Comment by vcaputo** [comment]
I've put together a patch for overlayfs to avoid the bug-triggering high-order allocation triggering whenever possible.  Considering 64KiB extended attributes are not likely, this should effectively fix the OOM issue.

There's an outstanding kernel/mm bug in handling these direct-reclaim high-order allocations when watermarks aren't met.  Rather than hacking together an mm fix which can potentially destabilize the entire OS, eliminating the allocation from overlayfs seems appropriately prudent.

Minimizing high-order allocations in the kernel is preferable regardless of bugs since they will always be more costly to fulfill fragmentation can still cause them to fail.

https://github.com/coreos/linux/issues/1

**Comment by bfallik** [comment]
initial testing looks like this resolves our issue; thanks all!

**Comment by mariomarin** [comment]
@vcaputo We are using 766.4.0 (stable) and we got bitten by this bug. Any workarounds while your patch gets backported to stable?

**Comment by crawford** [comment]
Please give 835.2.0 (currently in Beta) a shot. This should be the next version to hit Stable.

**Comment by vcaputo** [comment]
landed upstream:
https://git.kernel.org/cgit/linux/kernel/git/mszeredi/vfs.git/commit/fs/overlayfs/copy_up.c?h=overlayfs-next&id=e4ad29fa0d224d05e08b2858e65f112fd8edd4fe

**Comment by nharward** [comment]
FWIW: I am seeing the memory issue (iptables within docker) on CoreOS Alpha 877.1.0 (on an AWS t2.micro) when launching a container. I can open a shell to the container just fine, but when I fire it up in 'regular' mode running SSHD I see the issue every time. I'm also planning on running Mosh and am therefore exposing UDP ports 60000 through 61000. It occurred to me that if that range is expanded someplace as a single list it might chew up memory in a sensitive place and trigger the failure. I changed to only 10 ports instead of 1000, rebuilt the image and viola it started right up and appears to be working just fine.

This isn't exactly conclusive evidence, but it makes me wonder if using a large number of ports causes iptables to do something funny, or maybe it just tickles a different problem.

**Comment by vcaputo** [comment]
@nharward can you include the relevant information seen in dmesg caused by the oom?  We've removed the high-order allocation from overlayfs, but the mm bug remains, so there may be another code path prone to high-order allocations you're triggering which a backtrace should shed some light on.

**Comment by klausenbusk** [comment]
Just happened on my CoreOS stable 766.5.0 webservers.

**Comment by nharward** [comment]
@vcaputo: let me know if there is more information that can help. `dmesg` didn't product anything other than a few interfaces going into and out of promiscuous mode, the only info I could find was from the `journalctl` output on `docker.service` and the command line which summarized it. Again the only difference from this image and one that works is opening 10 UDP ports instead of 1000.

Error from the command line:

```$ docker run --rm -P dogs
Error response from daemon: Cannot start container 706e19e1ce074e560aa5bb0007001e054c0c0e82e7bd3575fadcbd7ce089c3ab: failed to create endpoint loving_mclean on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32875 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory)```

`journalctl -u docker.service` output, probably a lot easier to read if you copy/paste into your own text editor as the lines are long:

```Dec 04 09:08:20 zeus dockerd[726]: time="2015-12-04T09:08:20.856958097Z" level=info msg="POST /v1.21/containers/706e19e1ce074e560aa5bb0007001e054c0c0e82e7bd3575fadcbd7ce089c3ab/start"
Dec 04 09:08:27 zeus dockerd[726]: time="2015-12-04T09:08:27.364173317Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32866 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 1"
Dec 04 09:08:27 zeus dockerd[726]: time="2015-12-04T09:08:27.365842919Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32867 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 2"
Dec 04 09:08:27 zeus dockerd[726]: time="2015-12-04T09:08:27.365954554Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32868 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 3"
Dec 04 09:08:27 zeus dockerd[726]: time="2015-12-04T09:08:27.366039490Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32869 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 4"
Dec 04 09:08:27 zeus dockerd[726]: time="2015-12-04T09:08:27.366159931Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32870 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 5"
Dec 04 09:08:27 zeus dockerd[726]: time="2015-12-04T09:08:27.366252772Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32871 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 6"
Dec 04 09:08:27 zeus dockerd[726]: time="2015-12-04T09:08:27.366372136Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32872 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 7"
Dec 04 09:08:28 zeus dockerd[726]: time="2015-12-04T09:08:27.366450613Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32873 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 8"
Dec 04 09:08:28 zeus dockerd[726]: time="2015-12-04T09:08:27.366535095Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32874 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 9"
Dec 04 09:08:28 zeus dockerd[726]: time="2015-12-04T09:08:27.366624007Z" level=warning msg="Failed to allocate and map port: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32875 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory), retry: 10"
Dec 04 09:08:29 zeus dockerd[726]: time="2015-12-04T09:08:29.093735007Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/706e19e1ce074e560aa5bb0007001e054c0c0e82e7bd3575fadcbd7ce089c3ab/shm: no such file or directory\nfailed to umount /var/lib/docker/containers/706e19e1ce074e560aa5bb0007001e054c0c0e82e7bd3575fadcbd7ce089c3ab/mqueue: no such file or directory"
Dec 04 09:08:29 zeus dockerd[726]: time="2015-12-04T09:08:29.095249266Z" level=error msg="Handler for POST /v1.21/containers/706e19e1ce074e560aa5bb0007001e054c0c0e82e7bd3575fadcbd7ce089c3ab/start returned error: Cannot start container 706e19e1ce074e560aa5bb0007001e054c0c0e82e7bd3575fadcbd7ce089c3ab: failed to create endpoint loving_mclean on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32875 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory)"
Dec 04 09:08:29 zeus dockerd[726]: time="2015-12-04T09:08:29.095287385Z" level=error msg="HTTP Error" err="Cannot start container 706e19e1ce074e560aa5bb0007001e054c0c0e82e7bd3575fadcbd7ce089c3ab: failed to create endpoint loving_mclean on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 32875 -j DNAT --to-destination 172.17.0.3:60902 ! -i docker0:  (fork/exec /usr/sbin/iptables: cannot allocate memory)" statusCode=500
Dec 04 09:08:29 zeus dockerd[726]: time="2015-12-04T09:08:29.108641560Z" level=info msg="DELETE /v1.21/containers/706e19e1ce074e560aa5bb0007001e054c0c0e82e7bd3575fadcbd7ce089c3ab?v=1"```

**Comment by nharward** [comment]
Perhaps more useful information is what my `Dockerfile` looks like. I've modified it slightly to be smaller, but verified that it exhibits the same issues. If you change the ports from `60000-61000` to `60000-60010` things work OK.

```
FROM pritunl/archlinux:latest
RUN pacman -Syuq --noconfirm man pacman sudo openssh \
    && /usr/bin/ssh-keygen -A
EXPOSE 2222/tcp 60000-61000/udp
ENTRYPOINT ["/usr/sbin/sshd", "-D"]```

**Comment by miekg** [comment]
We are seeing this across the fleet. Running CoreOS 835.7.0, kernel 4.2.2. We are trying the new beta with kernel 4.3 to see if this makes a difference.

**Comment by miekg** [comment]
The new CoreOS Beta image with kernel 4.3.0 seems to improve on this.

**Comment by miekg** [comment]
Seeing an OOM with kernel 4.3.0 in a lightly loaded cluster.

**Comment by vcaputo** [comment]
@miekg could you provide any additional information?  What is OOMing?

**Comment by miekg** [comment]
@vcaputo stuff like this:
```
java: page allocation failure: order:0, mode:0x120
swapper/0: page allocation failure: order:0, mode:0x120
swapper/1: page allocation failure: order:0, mode:0x120
```

**Comment by vcaputo** [comment]
@miekg Hrm, that looks like a different issue at a glance, you may want to create a new issue if it's an ongoing thing and you can reproduce it.
