### ISSUE TITLE
rpc-statd.service requires /etc/conf.d/nfs but conf.d does not exist.

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#492]
<a href="https://github.com/brianredbeard"><img src="https://avatars.githubusercontent.com/u/57542?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brianredbeard](https://github.com/brianredbeard)**
_Tuesday Apr 29, 2014 at 00:37 GMT_
_Originally opened as https://github.com/coreos/baselayout/issues/14_

----

The systemd unit shipped for rpc-statd.service calls `EnvironmentFile=/etc/conf.d/nfs`.  Since the directory conf.d does exist, this file fails to load and any NFS mount units will subsequently fail.  This is resolved by the following two commands:

```
$ sudo mkdir /etc/conf.d
$ sudo touch /etc/conf.d/nfs
```

**Comment by crawford** [comment]
<a href="https://github.com/philips"><img src="https://avatars.githubusercontent.com/u/33544?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philips](https://github.com/philips)**
_Monday Jun 02, 2014 at 19:23 GMT_

----

@brianredbeard This would need to be added here: https://github.com/coreos/baselayout/blob/master/tmpfiles.d/baselayout-etc.conf

**Comment by crawford** [comment]
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Monday Jun 02, 2014 at 19:48 GMT_

----

Actually, we should patch `rpc-statd.service` instead to define the environment variables or command line args that it is trying to pull in from the OpenRC config in conf.d, we've never shipped any OpenRC files and I'd like to not start.

**Comment by jumanjiman** [comment]
should this be closed?

current stable release is not affected (neither is beta or alpha).

```
$ grep -i version /etc/os-release 
VERSION=1010.5.0
VERSION_ID=1010.5.0

$ systemctl cat rpc-statd | grep -i environment || echo not found
not found
```

**Comment by crawford** [comment]
@jumanjiman Yeah, I think this can be closed. Thanks for double checking!
