### ISSUE TITLE
Fleet fails to schedule units

### ISSUE THREAD

**Issue by BrianHicks** [coreos/bugs#53]
With the attached unit file and log, Fleet on EC2 (Beta channel) fails to start the unit file.

https://gist.github.com/BrianHicks/8bd436bbce429d6ee5b7

*Steps to reproduce:*

 1. submit the attached unit file with `fleetctl start sample-1.unit.service`
 2. check the status of the unit with `fleetctl list-units` - it will never start, just hang out as "inactive"
 3. check the fleet logs with `journalctl -u fleet` and see the attached logging information.

**Comment by cbsmith** [comment]
Just an update to mention that I do indeed still see those innocuous messages using the stock coreos images for AWS with a t2.large:

Dec 02 01:57:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...
Dec 02 01:57:55 ip-10-178-129-239.foo systemd[1]: Started Generate /run/coreos/motd.
Dec 02 01:58:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...
Dec 02 01:58:55 ip-10-178-129-239.foo systemd[1]: Started Generate /run/coreos/motd.
Dec 02 01:59:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...
Dec 02 01:59:55 ip-10-178-129-239.foo systemd[1]: Started Generate /run/coreos/motd.
Dec 02 02:00:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...
Dec 02 02:00:55 ip-10-178-129-239.foo systemd[1]: Started Generate /run/coreos/motd.
Dec 02 02:01:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...
Dec 02 02:01:55 ip-10-178-129-239.foo systemd[1]: Started Generate /run/coreos/motd.
Dec 02 02:02:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...
Dec 02 02:02:55 ip-10-178-129-239.foo systemd[1]: Started Generate /run/coreos/motd.
Dec 02 02:03:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...
Dec 02 02:03:55 ip-10-178-129-239.foo systemd[1]: Started Generate /run/coreos/motd.
Dec 02 02:04:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...
Dec 02 02:04:55 ip-10-178-129-239.foo systemd[1]: Started Generate /run/coreos/motd.
Dec 02 02:05:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...
Dec 02 02:05:55 ip-10-178-129-239.foo systemd[1]: Started Generate /run/coreos/motd.
Dec 02 02:06:55 ip-10-178-129-239.foo systemd[1]: Starting Generate /run/coreos/motd...

**Comment by vcaputo** [comment]
@cbsmith motdgen no longer runs from a timer unit as of https://github.com/coreos/coreos-overlay/pull/1636 (https://github.com/coreos/init/pull/187 in particular), but it will be some time before that percolates into the aws image.

**Comment by cbsmith** [comment]
Got it. Sounds like I should roll my own image, yeah?

**Comment by crawford** [comment]
@cbsmith it was fixed in [870.2.0](https://github.com/coreos/manifest/releases/tag/v870.2.0). You should be all set with the latest Alpha (and _very_ soon) the latest Beta.

**Comment by BrianHicks** [comment]
Welp, looks like I never "reported back" here... this was at a former job and the coreos spike got cancelled (though I don't remember in favor of what.) I'd consider this issue closed if nobody else has seen it in a year. ;)

**Comment by vcaputo** [comment]
Thanks for checking back in.

Closing due to lack of repro and originator having since moved on...
