### ISSUE TITLE
Add DRBD?

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#551]
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marineam](https://github.com/marineam)**
_Friday Mar 21, 2014 at 19:23 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/470_

----

Look into adding DRBD kernel module and user space tools for block level storage replication.

**Comment by crawford** [comment]
<a href="https://github.com/f0"><img src="https://avatars.githubusercontent.com/u/1117435?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [f0](https://github.com/f0)**
_Saturday Mar 22, 2014 at 18:01 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/Vaultman"><img src="https://avatars.githubusercontent.com/u/145859?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Vaultman](https://github.com/Vaultman)**
_Saturday Jun 21, 2014 at 15:09 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/irongaze"><img src="https://avatars.githubusercontent.com/u/1086959?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [irongaze](https://github.com/irongaze)**
_Friday Sep 12, 2014 at 17:25 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/nicholasvmoore"><img src="https://avatars.githubusercontent.com/u/5482842?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nicholasvmoore](https://github.com/nicholasvmoore)**
_Saturday Sep 27, 2014 at 14:44 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/pocketmax"><img src="https://avatars.githubusercontent.com/u/206058?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pocketmax](https://github.com/pocketmax)**
_Thursday Oct 16, 2014 at 07:20 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/t0mmyt"><img src="https://avatars.githubusercontent.com/u/4605747?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [t0mmyt](https://github.com/t0mmyt)**
_Sunday Dec 21, 2014 at 17:55 GMT_

----

+10

**Comment by crawford** [comment]
<a href="https://github.com/masm"><img src="https://avatars.githubusercontent.com/u/20297?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [masm](https://github.com/masm)**
_Saturday Jan 31, 2015 at 23:51 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/philipphug"><img src="https://avatars.githubusercontent.com/u/883881?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philipphug](https://github.com/philipphug)**
_Monday Apr 27, 2015 at 08:17 GMT_

----

+1, but user space tools should probably be put into a container instead of coreos. so adding the kernel modules should be enough.

**Comment by crawford** [comment]
<a href="https://github.com/jesselang"><img src="https://avatars.githubusercontent.com/u/42566?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jesselang](https://github.com/jesselang)**
_Tuesday Sep 01, 2015 at 21:54 GMT_

----

+1

**Comment by themicster** [comment]
+1

**Comment by mischief** [comment]
drdb kernel module is enabled now and should be available in the next alpha release.
