### ISSUE TITLE
change ssh port?

### ISSUE THREAD

**Issue by porjo** [coreos/bugs#57]
Trying to change the SSH port on CoreOS host to be `2222`. I've added the following to my `user_data` file:

```
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
        # Use most defaults for sshd configuration.
        UsePrivilegeSeparation sandbox
        Subsystem sftp internal-sftp

        PermitRootLogin no
        AllowUsers core
        PasswordAuthentication no
        ChallengeResponseAuthentication no
        Port 2222
```

After reboot, sshd is still listening on port 22. Journactl shows the following:

```
Jun 26 06:31:27 coreos-01 systemd[1]: Stopping system-sshd.slice.
Jun 26 06:31:27 coreos-01 systemd[1]: Removed slice system-sshd.slice.
Jun 26 06:31:27 coreos-01 systemd[1]: Stopping Generate sshd host keys...
Jun 26 06:31:27 coreos-01 systemd[1]: Stopped Generate sshd host keys.
Jun 26 06:31:38 coreos-01 systemd-tmpfiles[393]: readlink(/etc/ssh/sshd_config) failed: Invalid argument
Jun 26 06:31:39 coreos-01 coreos-cloudinit[459]: 2014/06/26 06:31:39 Wrote file /etc/ssh/sshd_config to filesystem
Jun 26 06:32:04 coreos-01 systemd[1]: Starting system-sshd.slice.
Jun 26 06:32:04 coreos-01 systemd[1]: Created slice system-sshd.slice.
```

`/etc/ssh/sshd_config` contains the new config and I can start a second sshd instance with it e.g. `/usr/sbin/sshd -f /etc/ssh/sshd_config` without error, and listening on port `2222`

I'm running CoreOS 353

**Comment by akashihi** [comment]
In latest stable (717.3.0) sshd still not started after boot when using non-standard port:

-- Reboot --
Aug 04 17:19:45 node1 systemd[1]: Listening on sshd.socket.
Aug 04 17:19:45 node1 systemd[1]: Starting sshd.socket.
Aug 04 17:19:46 node1 systemd[1]: Stopping sshd.socket.
Aug 04 17:19:46 node1 systemd[1]: sshd.socket: Failed to listen on sockets: Address already in use
Aug 04 17:19:46 node1 systemd[1]: Failed to listen on sshd.socket.
Aug 04 17:19:46 node1 systemd[1]: sshd.socket: Unit entered failed state.
core@node1 ~ $ cat /etc/systemd/system/sshd.socket
[Socket]
ListenStream=1984
Accept=yes
FreeBind=true
ReusePort=yes

It could be started manually later, but it would be nice, if it'll start automatically on boot.

**Comment by crawford** [comment]
Your socket unit is missing the [Install] section.

**Comment by akashihi** [comment]
Well, first of all, that [Install] section is not documented here: https://coreos.com/os/docs/latest/customizing-sshd.html

And, secondly, it doesn't helps:
core@node2 ~ $ cat /etc/systemd/system/sshd.socket
[Socket]
ListenStream=1984
Accept=yes
FreeBind=true
ReusePort=yes
[Install]
WantedBy=sockets.target

-- Reboot --
Aug 05 10:49:21 node2 systemd[1]: Listening on sshd.socket.
Aug 05 10:49:21 node2 systemd[1]: Starting sshd.socket.
Aug 05 10:49:23 node2 systemd[1]: Stopping sshd.socket.
Aug 05 10:49:23 node2 systemd[1]: sshd.socket: Failed to listen on sockets: Address already in use
Aug 05 10:49:23 node2 systemd[1]: Failed to listen on sshd.socket.
Aug 05 10:49:23 node2 systemd[1]: sshd.socket: Unit entered failed state.

btw, it doesn't works on a 723.3.0 too

**Comment by crawford** [comment]
Ah, if you are triggering it from coreos-cloudinit, you don't need the [Install] (coreos-cloudinit runs on every boot). After looking more closely at the output, it looks like you are running into a different issue (the same issue that https://github.com/coreos/docs/pull/422 is trying to solve). Can you open a new bug about this so we can fix this issue once and for all?

**Comment by akashihi** [comment]
Done :) https://github.com/coreos/bugs/issues/426
