### ISSUE TITLE
VMotion blocks traffic to VM after move

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#579]
<a href="https://github.com/damacus"><img src="https://avatars.githubusercontent.com/u/40786?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [damacus](https://github.com/damacus)**
_Thursday Aug 28, 2014 at 09:01 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/826_

----

Linked to #499 

We're seeing an issue when we vMotion between hosts that have vShield on them. In the process of moving, VMWare seems to lose the IP of the CoreOS machine and then proceed to block *all* traffic to the VM. This is a hyper-visor related issue but the ability to have VMWareTools (open or not) working  on the host would help.

**Comment by crawford** [comment]
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Thursday Aug 28, 2014 at 19:09 GMT_

----

Sorting out features like this is in progress but I don't have an ETA right now.

/cc @crawford

**Comment by crawford** [comment]
<a href="https://github.com/damacus"><img src="https://avatars.githubusercontent.com/u/40786?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [damacus](https://github.com/damacus)**
_Thursday Aug 28, 2014 at 19:17 GMT_

----

If you can point me in the right direction I should be able to whip something up. And I *might* be able to get some VMware support on this issue too, as we've opened a ticket with their vShield team.

**Comment by crawford** [comment]
<a href="https://github.com/jsavanyo4vmw"><img src="https://avatars.githubusercontent.com/u/9042975?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jsavanyo4vmw](https://github.com/jsavanyo4vmw)**
_Tuesday Oct 07, 2014 at 22:10 GMT_

----

@damacus do you have a ticket ID for above problem report handy? 
/cc @sujatha4vmw

**Comment by crawford** [comment]
<a href="https://github.com/damacus"><img src="https://avatars.githubusercontent.com/u/40786?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [damacus](https://github.com/damacus)**
_Tuesday Oct 07, 2014 at 22:42 GMT_

----

I don't but have asked one of the other engineers at work for it. I should hear something back soon. 

However I believe the case is closed so it might be a case of getting you in contact with the right people.

**Comment by crawford** [comment]
<a href="https://github.com/damacus"><img src="https://avatars.githubusercontent.com/u/40786?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [damacus](https://github.com/damacus)**
_Wednesday Oct 08, 2014 at 16:17 GMT_

----

Support ID: 14521701108
 
Also it’s not the vmotion that blocks it, it’s the combination of vShield and no tools.

**Comment by crawford** [comment]
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Thursday Oct 09, 2014 at 04:35 GMT_

----

open-vm-tools has landed via https://github.com/coreos/coreos-overlay/pull/907 and will appear in the next alpha but I am unsure if it is sufficient to resolve this issue, testing so far has been minimal.

**Comment by crawford** [comment]
<a href="https://github.com/damacus"><img src="https://avatars.githubusercontent.com/u/40786?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [damacus](https://github.com/damacus)**
_Thursday Oct 09, 2014 at 07:43 GMT_

----

I'll rebuild the cluster when I'm back at work in just over a week if I get
the time. I should be able to test this issue pretty quickly then

**Comment by damacus** [comment]
Hi @crawford I'm no longer working with Vmware and have moved companies, so I can no longer replicate this problem. Sorry!

Probably worth closing this for now unless someone else has had the issue since? To be honest I expect Vmware have closed the ticket by now.
