### ISSUE TITLE
ssl module of OEM python is missing   

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#587]
<a href="https://github.com/qingfuwang"><img src="https://avatars.githubusercontent.com/u/7636878?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [qingfuwang](https://github.com/qingfuwang)**
_Friday Oct 10, 2014 at 09:06 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/912_

---

SSL module is missing, is this by design because of some consideration ?
 Because ssl is missing, HTTPSConnection is not supported on CoreOS. 
   from httplib import ( HTTPSConnection)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name HTTPSConnection

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Friday Oct 10, 2014 at 17:37 GMT_

----

We do not ship Python in the CoreOS base image. I presume you are using GCE, which comes with a version of Python in order to run the GCE utilities. Its best to bundle your preferred version of Python in a container.

**Comment by crawford** [comment]
<a href="https://github.com/qingfuwang"><img src="https://avatars.githubusercontent.com/u/7636878?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [qingfuwang](https://github.com/qingfuwang)**
_Saturday Oct 11, 2014 at 01:36 GMT_

----

hi Alex,
I think you should know that WALinuxAgent  would also use python. The python i mentioned could be "https://github.com/coreos/coreos-overlay/blob/master/app-emulation/wa-linux-agent/wa-linux-agent-2.0.8.ebuild" 
Why need https ? because the agent would  communicate with azure (eg. do vm snapshot by using Azure Storage service RestAPI ).

**Comment by crawford** [comment]
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Saturday Oct 11, 2014 at 01:55 GMT_

----

For the future it is helpful to note when requests are in the context of the OEM python and supporting a new OEM tool like the wa-linux-agent since we don't always recognize usernames and we do get a lot of requests for general support of python which we do not intend to do right now. That'll avoid the extra back and forth. :)

So we will need to figure something out but for context the reason why the OEM python doesn't support SSL is because we want to minimize linking to libraries in the base system, the OEM partition is not upgraded along with the /usr partition and OpenSSL does not provide a stable ABI. On the other hand bundling OpenSSL with python in the OEM seems problematic since we don't have a mechanism to upgrade it and unfortunately as you already know, OpenSSL...

So in the long term we need to figure out how to upgrade OEM partitions or we need to deal with shipping python. In the short term we could just link against the system ssl which will be stable-enough for now. Any thoughts?

**Comment by crawford** [comment]
<a href="https://github.com/qingfuwang"><img src="https://avatars.githubusercontent.com/u/7636878?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [qingfuwang](https://github.com/qingfuwang)**
_Saturday Oct 11, 2014 at 02:18 GMT_

----

Now I can understand it's not easy to support HTTPS. And I can't understand your solution yet, i will forward this thread to Stephen Zarkos, he knows both CoreOS and wa-linux-agent and python.  
By the way, does your solution make "from httplib import ( HTTPSConnection)" work ? for wa-linux-agent everything else looks good. 

Thanks

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Saturday Oct 11, 2014 at 02:23 GMT_

----

@qingfuwang the version of waagent we are using doesn't import HTTPSConnection. We are using the 2.0 branch https://github.com/Azure/WALinuxAgent/commit/639581c3e61ce7365020de88999325a36b8cb1d7.

**Comment by crawford** [comment]
<a href="https://github.com/qingfuwang"><img src="https://avatars.githubusercontent.com/u/7636878?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [qingfuwang](https://github.com/qingfuwang)**
_Saturday Oct 11, 2014 at 02:29 GMT_

----

@crawford  yes, waagent not import Https, this https issue won't break features of waagent. Currently the problem is, one of our extension "CustomScript" need it. My example "do snapshot" is not very accurate.

**Comment by crawford** [comment]
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Saturday Oct 11, 2014 at 02:55 GMT_

----

What is this "CustomScript" extension? Does it provide standard functionality of Azure or is this some user provided customization scheme? It won't be practical for us to support running arbitrary python code on coreos outside of a container.

**Comment by crawford** [comment]
<a href="https://github.com/qingfuwang"><img src="https://avatars.githubusercontent.com/u/7636878?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [qingfuwang](https://github.com/qingfuwang)**
_Saturday Oct 11, 2014 at 03:06 GMT_

----

I don't know who should decide coreOS will not support extension. but if Https is supported this extension can work, and user can decide by themselves.   I agree coreOS should keep simple, do anything in container ,and i think python support https is something better to have for coreOS running on azure.

**Comment by drbolsen** [comment]
Bump, that's been a year since the initial request, any estimate on when it might eventuate?

I guess nowadays having working SSL functionality in is not a caprice, but an essential need, especially for business users.

**Comment by crawford** [comment]
We cannot ship SSL in the OEM position until we have the ability to update it (otherwise, security vulnerabilities would go unpatched). We are working on getting the various OEMs into container images so that we can use rkt to distribute updates, but there are still a number of unanswered questions.

We haven't forgotten about this. We just have to be very deliberate.

**Comment by crawford** [comment]
The Azure Linux Agent is being moved into its own container. Once that is done, we will remove python from the system entirely. You'll need to bring along your own python (with SSL) in a container.
