### ISSUE TITLE
Add support for OpenNebula

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#590]
<a href="https://github.com/roedie"><img src="https://avatars.githubusercontent.com/u/1014038?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roedie](https://github.com/roedie)**
_Tuesday Oct 21, 2014 at 12:22 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/932_

---

I would like to see support for OpenNebula. http://opennebula.org/

Is this anywhere on a roadmap?

**Comment by crawford** [comment]
<a href="https://github.com/roedie"><img src="https://avatars.githubusercontent.com/u/1014038?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [roedie](https://github.com/roedie)**
_Wednesday Oct 22, 2014 at 09:21 GMT_

----

A little more info

OpenNebula provides a virtual cd to the virtual machine with the file context.sh. This file contains the following info:

`----`
`# Context variables generated by OpenNebula`
`DISK_ID='1'`
`ETH0_DNS='x.x.x.x'`
`ETH0_GATEWAY='x.x.x.x'`
`ETH0_GATEWAY6='2001:67c:abcd::1'`
`ETH0_IP='x.x.x.x'`
`ETH0_IP6='2001:67c:abcd::e023'`
`ETH0_MAC='02:00:c3:5d:e0:23'`
`ETH0_MASK='255.255.255.0'`
`ETH0_NETWORK='x.x.x.x'`
`NETWORK='YES'`
`SSH_PUBLIC_KEY='ssh-rsa AAAAB3NzaC1[....]'`
`TARGET='hda'`
`---`

More variables can be added to configure CoreOS. It is also possible to include extra files like cloud-config.yaml in the iso.

If I'm at the wrong place with this ticket, please let me know then I will try somewhere else.

**Comment by crawford** [comment]
<a href="https://github.com/hivearts"><img src="https://avatars.githubusercontent.com/u/4526811?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hivearts](https://github.com/hivearts)**
_Thursday Mar 19, 2015 at 15:13 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/telmich"><img src="https://avatars.githubusercontent.com/u/9397?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [telmich](https://github.com/telmich)**
_Tuesday Aug 25, 2015 at 21:35 GMT_

----

+1 - support for openennebula would be much appreciated

**Comment by carletes** [comment]
I've just uploaded a CoreOS alpha channel KVM image to the OpenNebula Marketplace: <http://marketplace.opennebula.systems/appliance/570151808fb81d0d6f000002>.

I've built it with Packer, and tt supports networking --- see https://github.com/carletes/coreos-opennebula-image

**Comment by crawford** [comment]
We are no longer working on coreos-cloudinit. If this functionality is still desired, it can be added to Ignition and coreos-metadata.
