### ISSUE TITLE
ARMHF support

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#593]
<a href="https://github.com/aallouche"><img src="https://avatars.githubusercontent.com/u/7766403?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aallouche](https://github.com/aallouche)**
_Friday Oct 31, 2014 at 18:36 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/941_

---

Hello gents,
I might be lost here but is it the place to talk about a CoreOS build running on bleeding-edge-bare-metal-armhf-based servers?

French hosting online.net provides such platforms (test it yourself it is in free public preview!)
You may want to check their current status on CoreOS support here 
https://community.cloud.online.net/t/development-docker-and-coreos-support/337

Thanks for your feedback

**Comment by crawford** [comment]
<a href="https://github.com/aimxhaisse"><img src="https://avatars.githubusercontent.com/u/149659?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [aimxhaisse](https://github.com/aimxhaisse)**
_Monday Dec 22, 2014 at 08:27 GMT_

----

:+1:

**Comment by crawford** [comment]
There is ongoing work to support ARM64.

**Comment by Serkan-devel** [comment]
+1 I want to run core os on my raspberry pi 2 model b

**Comment by crawford** [comment]
ARM64 images have been available for a little while now (https://alpha.release.core-os.net/arm64-usr/). Please note that ARM64 is a superset specification of 64-bit ARM. Container Linux is not going to work on the Raspberry Pi (e.g. the Pi is missing UEFI support).
