### ISSUE TITLE
remove /bin and /sbin from PATH

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#603]
<a href="https://github.com/ibukanov"><img src="https://avatars.githubusercontent.com/u/2381216?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ibukanov](https://github.com/ibukanov)**
_Thursday Jan 15, 2015 at 08:55 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/1054_

---

PATH for the core user contains /bin and PATH for root contains /bin and /sbin. As /bin and /sbin are symlinks to /usr/bin and /usr/sbin, these are redundant and should be removed.

**Comment by dm0-** [comment]
This is implemented in coreos/coreos-overlay#2348, which affects production images (not the SDK).
