### ISSUE TITLE
Could a machine be accessible from other in the cluster without ssh access?

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#607]
<a href="https://github.com/phuongnd08"><img src="https://avatars.githubusercontent.com/u/184037?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [phuongnd08](https://github.com/phuongnd08)**
_Tuesday Jan 27, 2015 at 04:03 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/1067_

----

I lost access ssh to a machine (not sure why) but it still report a part in the cluster on `fleet list-machines` running on other machine in the cluster (DO machines btw). Could I possibly regain access to that machine?

**Comment by crawford** [comment]
<a href="https://github.com/mischief"><img src="https://avatars.githubusercontent.com/u/1487996?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mischief](https://github.com/mischief)**
_Monday Mar 30, 2015 at 22:50 GMT_

----

@phuongnd08 are you still having this issue?

**Comment by phuongnd08** [comment]
I encountered a fatal production error with digital ocean large machine during that time so I switched away from that. These days just use Heroku.
