### ISSUE TITLE
Please update open-vm-tools to 10.0.0

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#630]
<a href="https://github.com/oliverkurth"><img src="https://avatars.githubusercontent.com/u/6658518?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oliverkurth](https://github.com/oliverkurth)**
_Tuesday Jun 23, 2015 at 18:11 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/1304_

---

We have released version 9.10.2 of open-vm-tools. Please upgrade in CoreOS. Changes are mostly bug fixes.

It's in github here: https://github.com/vmware/open-vm-tools/tree/stable-9.10.x

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Tuesday Jun 23, 2015 at 20:10 GMT_

----

I don't see a GitHub release or git tag for 9.10.2.

**Comment by crawford** [comment]
<a href="https://github.com/oliverkurth"><img src="https://avatars.githubusercontent.com/u/6658518?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oliverkurth](https://github.com/oliverkurth)**
_Tuesday Jun 30, 2015 at 00:08 GMT_

----

Oh sorry, almost forgot - we have a release tag now:
https://github.com/vmware/open-vm-tools/releases/tag/stable-9.10.2

**Comment by crawford** [comment]
<a href="https://github.com/oliverkurth"><img src="https://avatars.githubusercontent.com/u/6658518?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oliverkurth](https://github.com/oliverkurth)**
_Friday Sep 04, 2015 at 21:26 GMT_

----

We have a new release now: 10.0.0. The release tag is here: https://github.com/vmware/open-vm-tools/releases/tag/open-vm-tools-10.0.0-3000743

Release notes are here: https://github.com/vmware/open-vm-tools/blob/stable-10.0.x/ReleaseNotes.md

Just noticed that this issue is still open for 9.10.2, so  thought I reuse it for 10.0.0.

**Comment by oliverkurth** [comment]
We have released version 10.1.0 of open-vm-tols, see https://github.com/vmware/open-vm-tools/tree/stable-10.1.0

**Comment by oliverkurth** [comment]
We are now at version 10.1.5, see https://github.com/vmware/open-vm-tools/tree/stable-10.1.5 .

Noteworthy is also that we a now have a more detailed commit history in github.

**Comment by bgilbert** [comment]
Fixed in https://github.com/coreos/coreos-overlay/pull/2493.
