### ISSUE TITLE
please add vgauth to open-vm-tools

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#631]
<a href="https://github.com/oliverkurth"><img src="https://avatars.githubusercontent.com/u/6658518?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oliverkurth](https://github.com/oliverkurth)**
_Tuesday Jun 30, 2015 at 00:19 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/1323_

---

Can you please add vgauth to open-vm-tools?

https://github.com/coreos/coreos-overlay/blob/master/app-emulation/open-vm-tools/open-vm-tools-9.10.0-r1.ebuild#L97

vgauth is used to support SAML based authentication for guest operations. Let me know if you need more information, or help.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
