### ISSUE TITLE
coreos should ship an iscsi initiator by default

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#634]
<a href="https://github.com/SKRobb"><img src="https://avatars.githubusercontent.com/u/6586444?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SKRobb](https://github.com/SKRobb)**
_Thursday Jul 16, 2015 at 23:10 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/1376_

----

CoreOS should support iscsi out of the box. Does CoreOS support iscsi or any plans to in the future.

**Comment by crawford** [comment]
<a href="https://github.com/danielschonfeld"><img src="https://avatars.githubusercontent.com/u/522598?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [danielschonfeld](https://github.com/danielschonfeld)**
_Saturday Sep 12, 2015 at 15:40 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/darrensessions"><img src="https://avatars.githubusercontent.com/u/818842?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [darrensessions](https://github.com/darrensessions)**
_Wednesday Sep 16, 2015 at 18:29 GMT_

----

+1

We'd love to use CoreOS in applications other than web-tech, but not having iSCSI support in the core and having to do it in containers is both a pain and super inconvenient (never mind the performance hit).

Plus, wouldn't it be cool to move containers from server to server in an outage without actually moving anything? Or maybe have shared volumes (via GFS2)?

#totalawesomeness #openssomanydoors

**Comment by crawford** [comment]
<a href="https://github.com/Marquis42"><img src="https://avatars.githubusercontent.com/u/911263?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Marquis42](https://github.com/Marquis42)**
_Wednesday Sep 16, 2015 at 18:31 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/jbenavidescr"><img src="https://avatars.githubusercontent.com/u/14318286?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jbenavidescr](https://github.com/jbenavidescr)**
_Wednesday Sep 16, 2015 at 18:34 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/IT-Juggler"><img src="https://avatars.githubusercontent.com/u/9489012?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [IT-Juggler](https://github.com/IT-Juggler)**
_Wednesday Sep 16, 2015 at 18:34 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/leifmadsen"><img src="https://avatars.githubusercontent.com/u/768751?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [leifmadsen](https://github.com/leifmadsen)**
_Wednesday Sep 16, 2015 at 18:35 GMT_

----

+1 like woah

**Comment by crawford** [comment]
<a href="https://github.com/zerohalo"><img src="https://avatars.githubusercontent.com/u/351115?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zerohalo](https://github.com/zerohalo)**
_Wednesday Sep 16, 2015 at 18:52 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/CrissSoto"><img src="https://avatars.githubusercontent.com/u/14318973?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CrissSoto](https://github.com/CrissSoto)**
_Wednesday Sep 16, 2015 at 19:25 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/mischief"><img src="https://avatars.githubusercontent.com/u/1487996?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mischief](https://github.com/mischief)**
_Thursday Sep 17, 2015 at 19:29 GMT_

----

fyi everyone, there's a active WIP PR to merge open-iscsi at #1546.

**Comment by crawford** [comment]
<a href="https://github.com/hjfreyer"><img src="https://avatars.githubusercontent.com/u/271308?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hjfreyer](https://github.com/hjfreyer)**
_Friday Sep 18, 2015 at 20:19 GMT_

----

Not sure where this would fit in, but specifically making the iscsi storage backend (as an initiator, not a target) for Kubernetes work would be fantastic.

**Comment by crawford** [comment]
<a href="https://github.com/mischief"><img src="https://avatars.githubusercontent.com/u/1487996?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mischief](https://github.com/mischief)**
_Friday Sep 18, 2015 at 20:20 GMT_

----

@hjfreyer can you give me some more information? right now i'm just trying to merge open-iscsi.

**Comment by crawford** [comment]
<a href="https://github.com/hjfreyer"><img src="https://avatars.githubusercontent.com/u/271308?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hjfreyer](https://github.com/hjfreyer)**
_Friday Sep 18, 2015 at 20:27 GMT_

----

It looks like that only depends on iscsiadm being installed on the machine, which I imagine your work would pull in: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/iscsi/iscsi.go#L63

If it turns out that's not sufficient I can file a new bug here or there as appropriate :) Thanks!

**Comment by crawford** [comment]
<a href="https://github.com/darrensessions"><img src="https://avatars.githubusercontent.com/u/818842?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [darrensessions](https://github.com/darrensessions)**
_Monday Sep 21, 2015 at 01:03 GMT_

----

@mischief @hjfreyer 

My sincere apologies to anyone already familiar with the ins and outs of iSCSI.

A very quick overview of the two iSCSI modes of operation can be found at https://wiki.gentoo.org/wiki/ISCSI

The iSCSI "initiator" mode of operation is, by far, the most utilized mode of operation with iSCSI, whereby the initiator (client) connects to a target (storage machine) over the network.

Additionally, a tool used very, very heavily with iSCSI implementations is multipathd (more here at https://wiki.gentoo.org/wiki/Multipath). Multipathing facilitates a single storage device to be transparently accessed across one or more paths and provides for fault tolerance, load balancing, etc.

**Comment by hjfreyer** [comment]
Hey, what's the story here? The PR (https://github.com/coreos/coreos-overlay/pull/1546) went in a while ago, and I think release 845 includes it, but the iscsi tools don't seem to be on the machine. Is there anything else I need to do?

**Comment by mischief** [comment]
hi @hjfreyer, i delayed on this because i didn't know what to do about the upstream systemd units, so i didn't pull it into the CoreOS production images.

it seems reasonable to merge the binaries for now, and get systemd units later.

**Comment by mischief** [comment]
@hjfreyer coreos/coreos-overlay#1613 will bring in the open-iscsi binaries.

**Comment by mischief** [comment]
@hjfreyer with that pr merged, open-iscsi binaries will be in the next alpha. if you find any issues with it please file a new bug.

**Comment by mischief** [comment]
reverted the binaries in the image, until we have done some tested and figured out systemd units. sorry.

i'll update this ticket again when the situation changes.

**Comment by hjfreyer** [comment]
Hah, that didn't last long :P. Okay, I'll stay tuned.

**Comment by kobelb** [comment]
Any word on this? Is someone still working on this?

**Comment by crawford** [comment]
This is on the back-burner for now. We will revisit it in the coming months.

**Comment by awesensepaul** [comment]
Any progress on this since the last update?

**Comment by crawford** [comment]
No, sorry. :disappointed:

There are a couple items ahead in line, but we are getting closer.

**Comment by marineam** [comment]
Fixed by https://github.com/coreos/coreos-overlay/pull/1546 https://github.com/coreos/portage-stable/pull/265 https://github.com/coreos/coreos-overlay/pull/1888 https://github.com/coreos/coreos-overlay/pull/1890 https://github.com/coreos/coreos-overlay/pull/1892 and included in https://github.com/coreos/manifest/releases/tag/v1029.0.0

Testing has been limited but appears to work. :)

**Comment by andrewrothstein** [comment]
+1
