### ISSUE TITLE
add mount.fuse

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#641]
<a href="https://github.com/ederuiter"><img src="https://avatars.githubusercontent.com/u/6728434?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ederuiter](https://github.com/ederuiter)**
_Monday Sep 07, 2015 at 15:05 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/1518_

---

Currently coreos ships with the fuse file-system enabled, but it doesn't have the mount.fuse helper. This makes it hard to mount fuse based file-systems.
An alternative would be to build mount with --enable-fs-paths-extra=/opt/bin so that mount helpers could be installed in /opt/bin (currently only /sbin/, /sbin/fs.d/, /sbin/fs, /usr/sbin/, /bin/ and /usr/bin are searched for helpers and all those locations are mounted readonly)

**Comment by crawford** [comment]
<a href="https://github.com/mischief"><img src="https://avatars.githubusercontent.com/u/1487996?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mischief](https://github.com/mischief)**
_Monday Sep 07, 2015 at 15:15 GMT_

----

see coreos/bugs#358. have you tried running mount.fuse in a container?

**Comment by crawford** [comment]
<a href="https://github.com/ederuiter"><img src="https://avatars.githubusercontent.com/u/6728434?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ederuiter](https://github.com/ederuiter)**
_Monday Sep 07, 2015 at 15:20 GMT_

----

Yes I did,  but that is not an option as fuse based file-systems cannot be exported from a container to the host. And I need to access this filesystem in several containers (and running it in all containers is not an option as our filesystem replicates all data to local storage)

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.
