### ISSUE TITLE
missing /etc/environment file

### ISSUE THREAD

**Issue by xh3b4sd** [coreos/bugs#65]
Hey there,

sorry for the lack of knowledge, but I don't know where to place this issue elsewhere. Back to topic. I just started a coreos cluster using the ec2 alpha channel image `ami-11c51066` with coreos version `367.0.0`. I wondered why some units failed, the reason was the missing `etc/environment` file. 

`coreos-setup-environment.service` does exist

``` bash
core@ip-xxx-xx-xx-xxx ~ $ cat /usr/lib64/systemd/system/coreos-setup-environment.service
[Unit]
Description=Modifies /etc/environment for CoreOS
RequiresMountsFor=/usr/share/oem
ConditionPathExists=/usr/share/oem/bin/coreos-setup-environment

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/share/oem/bin/coreos-setup-environment /etc/environment

[Install]
WantedBy=multi-user.target
```

`/usr/share/oem/bin/coreos-setup-environment` does not exist

``` bash
core@ip-xxx-xx-xx-xxx ~ $ cat /usr/share/oem/bin/coreos-setup-environment
cat: /usr/share/oem/bin/coreos-setup-environment: No such file or directory
```

`/etc/environment` does not exist

``` bash
core@ip-xxx-xx-xx-xxx ~ $ ls /etc/environment
ls: cannot access /etc/environment: No such file or directory
```

unfortunately there was no error for the service

``` bash
core@ip-xxx-xx-xx-xxx ~ $ systemctl status coreos-setup-environment.service
● coreos-setup-environment.service - Modifies /etc/environment for CoreOS
   Loaded: loaded (/usr/lib64/systemd/system/coreos-setup-environment.service; disabled)
   Active: inactive (dead)
           start condition failed at Tue 2014-07-08 09:25:28 UTC; 1h 18min ago

Jul 08 09:25:28 localhost systemd[1]: Started Modifies /etc/environment for CoreOS.
```

I did not find any documentation that this is intended behaviour. Any ideas? Thanks guys. <3

**Comment by antgeo** [comment]
557.2.0 is missing `/usr/share/oem/bin/coreos-setup-environment` and `/etc/environment`

**Comment by xueshanf** [comment]
@antgeo I think it depends on the platforms. Vagrant still has /usr/share/oem/bin/coreos-setup-environment (CoreOS beta (584.0.0)) and /etc/environment is created. On AWS EC2 (557.2 and 584 for me), /usr/share/oem/bin/coreos-setup-environment doesn't exist, but /etc/environment does - it was created with the instance's public and private IP as part of the cloud-init. I used to have units that depend on coreos-setup-environment.service, now I use ConditionPathExists=/etc/environment/etc/environment on AWS EC2 instances.

**Comment by anapsix** [comment]
both `/usr/share/oem/bin/coreos-setup-environment` and `/etc/environment` are missing in `633.1.0 (beta)`
adding a `write_files` to cloud-config helps, though..
```
write_files:
  - name: /etc/environment
    content: |
        COREOS_PUBLIC_IPV4=74.125.228.232
        COREOS_PRIVATE_IPV4=10.100.0.1
```

**Comment by philips** [comment]
@anapsix What platform are you on?

**Comment by anapsix** [comment]
@philips, running CoreOS 633.1.0 on bare metal

**Comment by philips** [comment]
@anapsix On bare metal we have no metadata service to query so we haven't created /etc/environment on those environments for quite some time. Are you seeing a regression on this from a previous version you were using?

**Comment by anapsix** [comment]
I see your point @philips. However `/usr/share/oem/bin/coreos-setup-environment` does not exist..
Besides, one may choose to implement such metadata services..
I could see using `private_data_url` to override defaults or ensure compatibility (e.g. for hybrid setup of bare-metal/aws/rackspace/your-favorite-cloud-that-does-not-support-private-data) instead of relying on proprietary AWS/Vargant private_data / user_data delivery mechanism.

Consider this:

    coreos:
      private_data_url: http://provisioning.internal.company.net
      private_data_optional_token: cukyagNobrIa

During processing of `cloud_config`, `coreos-setup-environment` _GET[s]_ `private_data_url` with it's hostname in the params and retrieves the ENV.
Obliviously, this functionality could be easily implemented via custom _unit_ in `cloud_config`.. Imho, it makes sense for convenience / consistency sake to have it built in.

**Comment by dj-wasabi** [comment]
Hi,

I am at `CoreOS stable (723.3.0)` with the VMWare image and also `/etc/environments` and `/usr/share/oem/bin/coreos-setup-environment` are missing on my systems.

**Comment by ntquyen** [comment]
I have the same problem with CoreOS stable 723.3.0. `$private_ipv4` is not loaded in cloud-init, `/etc/environments` and `/usr/share/oem/bin/coreos-setup-environment ` are missing. Can we re-open this issue?

**Comment by mischief** [comment]
@ntquyen $private_ipv4 is not supported on all platforms. see the note at https://coreos.com/os/docs/latest/cloud-config.html#coreos.

please file a new issue if the problem exists on a platform where it is documented to work.
