### ISSUE TITLE
blkdev does not work with lvm

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#655]
<a href="https://github.com/lordfolken"><img src="https://avatars.githubusercontent.com/u/407371?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lordfolken](https://github.com/lordfolken)**
_Tuesday Jun 17, 2014 at 23:33 GMT_
_Originally opened as https://github.com/coreos/init/issues/113_

----

blockdev --rereadpt "${DEVICE}"

fails with 
BLKRRPART: Invalid argument
on debian wheezy 7.5

**Comment by crawford** [comment]
<a href="https://github.com/lordfolken"><img src="https://avatars.githubusercontent.com/u/407371?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lordfolken](https://github.com/lordfolken)**
_Tuesday Jun 17, 2014 at 23:34 GMT_

----

This is when using an lv device for the $DEVICE.

**Comment by crawford** [comment]
<a href="https://github.com/C-Duv"><img src="https://avatars.githubusercontent.com/u/1466273?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [C-Duv](https://github.com/C-Duv)**
_Sunday Jun 22, 2014 at 11:51 GMT_

----

Same here when trying to install CoreOS v324.5.0 on a disk file:
```Shell
dd if=/dev/zero of=coreos-disk count=5000 bs=1M
sudo losetup /dev/loop0 coreos-disk
sudo ./coreos-install -d /dev/loop0 -C beta -c cloud-config.yaml
```

I get:
> Downloading and verifying coreos_production_image.bin.bz2...
...
Writing coreos_production_image.bin.bz2 to /dev/loop0...
  /tmp/coreos-install.1VymhkSZdP/coreos_production_image.bin.bz2: done
BLKRRPART: Invalid argument

**Comment by crawford** [comment]
<a href="https://github.com/c4milo"><img src="https://avatars.githubusercontent.com/u/41681?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [c4milo](https://github.com/c4milo)**
_Sunday Jun 22, 2014 at 19:08 GMT_

----

hmm, based on what it is actually documented here: https://coreos.com/docs/running-coreos/bare-metal/installing-to-disk:

![](https://i.cloudup.com/6rwLIPB7OJ.png)

It seems there is an issue either, in the documentation or the installation script. cc @marineam 

@C-Duv @lordfolken despite that, if you boot using the [CoreOS ISO image](https://coreos.com/docs/running-coreos/platforms/iso/), you should be able to run the installation script just fine.

**Comment by crawford** [comment]
<a href="https://github.com/minad"><img src="https://avatars.githubusercontent.com/u/50754?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [minad](https://github.com/minad)**
_Wednesday Jul 30, 2014 at 15:59 GMT_

----

I think you have to do it differently as described here: http://qpfiffer.com/posts/2013-11-06-2013_kvm_coreos

qemu-img convert coreos_production_qemu_image.img -O raw /dev/vg/lv

**Comment by crawford** [comment]
<a href="https://github.com/wmark"><img src="https://avatars.githubusercontent.com/u/191736?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wmark](https://github.com/wmark)**
_Wednesday Jan 21, 2015 at 21:39 GMT_

----

I cannot reproduce this using loop devices.

**Comment by shredder12** [comment]
Hi. I am facing the same issue deploying core-os 766.5.0 on lvm created on a software raid device.
![screen shot 2015-11-20 at 11 46 22 am](https://cloud.githubusercontent.com/assets/490551/11310108/8e822e00-8f7c-11e5-907e-a94e0ee97753.png)

**Comment by Nurza** [comment]
Same problem here with losetup, this bug still not fixed...

```
./coreos-install -C beta -d /dev/loop0                
Current version of CoreOS beta is 1010.3.0
Downloading the signature for https://beta.release.core-os.net/amd64-usr/1010.3.0/coreos_production_image.bin.bz2...
2016-05-12 08:48:30 URL:https://beta.release.core-os.net/amd64-usr/1010.3.0/coreos_production_image.bin.bz2.sig [543/543] -> "/tmp/coreos-install.hcodEmlvo9/coreos_production_image.bin.bz2.sig" [1]
Downloading, writing and verifying coreos_production_image.bin.bz2...
2016-05-12 08:49:40 URL:https://beta.release.core-os.net/amd64-usr/1010.3.0/coreos_production_image.bin.bz2 [258020413/258020413] -> "-" [1]
gpg: Signature made Thu 05 May 2016 09:47:21 AM CEST using RSA key ID 1CB5FA26
gpg: key 93D2DCB4 marked as ultimately trusted
gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>"
blockdev: ioctl error on BLKRRPART: Invalid argument
```
