### ISSUE TITLE
coreos-install fails installing cloud-config

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#664]
<a href="https://github.com/wkornewald"><img src="https://avatars.githubusercontent.com/u/134387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wkornewald](https://github.com/wkornewald)**
_Friday Oct 24, 2014 at 22:06 GMT_
_Originally opened as https://github.com/coreos/init/issues/138_

---

When I install CoreOS from within the soyoustart.com (OVH) rescue system, the -c option doesn't work during the first install attempt because it fails in this line with an exit code of 2:

``` bash
ROOT_DEV=$(blkid -t "LABEL=ROOT" -o device "${DEVICE}"*)
```

Calling coreos-install again with -c seems to work reliably, though.

Note, I already had Ubuntu installed on /dev/sda and simply overwrote /dev/sda.

**Comment by crawford** [comment]
<a href="https://github.com/bryanlarsen"><img src="https://avatars.githubusercontent.com/u/32073?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bryanlarsen](https://github.com/bryanlarsen)**
_Wednesday Dec 17, 2014 at 16:11 GMT_

----

I got a different error when installing on soyoustart/OVH:

BLKRRPART: Device or resource busy

rebooting and then trying the install again fixed the problem.

AFAICT, the problem is that the default OVH install uses software RAID, and that somehow makes /dev/sda busy even if you don't have /dev/md1 mounted.   The first installation blows away the partition table on /dev/sda, the reboot then ensures that /dev/sda isn't busy and the second try works.

**Comment by crawford** [comment]
<a href="https://github.com/osterman"><img src="https://avatars.githubusercontent.com/u/52489?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [osterman](https://github.com/osterman)**
_Saturday Apr 25, 2015 at 19:32 GMT_

----

I have been having the same issues and discovered the same workaround as @wkornewald mentions. Not sure why the device glob works differently between two subsequent runs. 

Here's a transcript of the first run that always fails:
https://www.evernote.com/l/AFjlgo7syAFBdpSIzMfraIdyatsK0roJH4Q

Here's a transscript of the second run that usually succeeds: 
https://www.evernote.com/l/AFiY7bI7poxIjIa3LfgOF0l1r1Nd6tP4yyg

I am also using OVH/Kimsufi.

-Erik

**Comment by crawford** [comment]
<a href="https://github.com/ghmlee"><img src="https://avatars.githubusercontent.com/u/2618612?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ghmlee](https://github.com/ghmlee)**
_Monday May 18, 2015 at 08:59 GMT_

----

I have been having the same issues too.

**Comment by frank-dspeed** [comment]
same problem here but no problem at all works after secund retry

**Comment by crawford** [comment]
These issues have been resolved in the `coreos-install` utility.
