### ISSUE TITLE
update-ssh-keys doesn't handle key files that don't end in a newline

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#676]
<a href="https://github.com/pquerna"><img src="https://avatars.githubusercontent.com/u/110123?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pquerna](https://github.com/pquerna)**
_Friday Sep 04, 2015 at 18:56 GMT_
_Originally opened as https://github.com/coreos/init/issues/175_

----

If you drop an authorized key into `/home/core/.ssh/authorized_keys.d/`, and the file doesn't contain  / end in a new line, the outputted authorized_keys file is malformed.  

CC @robert-chiniquy

**Comment by crawford** [comment]
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Friday Sep 04, 2015 at 19:28 GMT_

----

Amusingly we just found the exact same bug in the new Go re-implementation of update-ssh-keys: https://github.com/coreos/update-ssh-keys/pull/10

**Comment by lrvick** [comment]
This has bit my team multiple times attempting to use ```curl https://github.com/lrvick.keys | update-ssh-keys -a lrvick```.

The result is 2 users keys get concatenated, and both users are locked out.

For now we have resorted to: ```cat <(curl https://github.com/lrvick.keys; echo "") | update-ssh-keys -a lrvick```

**Comment by crawford** [comment]
Closed via https://github.com/coreos/init/pull/184.
