### ISSUE TITLE
Allow for encrypted AMI volumes

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#686]
<a href="https://github.com/KnownSubset"><img src="https://avatars.githubusercontent.com/u/948512?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KnownSubset](https://github.com/KnownSubset)**
_Friday May 01, 2015 at 22:33 GMT_
_Originally opened as https://github.com/coreos/scripts/issues/406_

----

There is no easy way to have an EC2 instance with an encrypted volume when booting up from the CoreOS provided AMIs.  I suggest that we modify the [build script](https://github.com/coreos/scripts/blob/master/oem/ami/build_ebs_on_ec2.sh) for AMIs so that an additional AMI is built per virtualization type with an encrypted volume.  

There is a reduced list of instances available that can run the additional AMIs with encryption enabled, as not all instances support EBS encryption.

**Comment by crawford** [comment]
<a href="https://github.com/KnownSubset"><img src="https://avatars.githubusercontent.com/u/948512?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KnownSubset](https://github.com/KnownSubset)**
_Monday May 04, 2015 at 20:12 GMT_

----

Since PR #400 was merged in a couple weeks back.  It seems that your current build process ([import.sh](../tree/master/oem/ami/import.sh)) still does support encrypted root devices for your AMI images.  It is still possible to create an encrypted volume/snapshot, but it would entail copying the data over from the imported volume to the encrypted volume and registering additional AMIs. 

I could create a PR for creating the AMIs with encrypted root devices, but I don't know what other pieces would need to be touched to have the AMIs show up, or hide them, on the [CoreOS EC2 page](https://coreos.com/docs/running-coreos/cloud-providers/ec2/).

**Comment by crawford** [comment]
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Thursday May 07, 2015 at 04:40 GMT_

----

According to the Amazon documentation it is simply not possible for us to publish public AMIs with encrypted volumes:

> Public or shared snapshots of encrypted volumes are not supported, because other accounts would not be able to decrypt your data.

and

> Encrypted boot volumes are not supported at this time.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html

I presume the warning about boot volumes is simply because no public AMIs can provide encrypted volumes. If that's a white lie and your recommendation works great, but due to the way EBS encryption keys are managed you are stuck with creating the AMIs yourself.

**Comment by meonkeys** [comment]
It's possible as of today: https://twitter.com/awscloud/status/687771685118840832

**Comment by timrsmith** [comment]
I'm curious how you were able to get this to work. I've launched an image, created another from it, then copied. However, when launching that new copied image either via a CloudFormation design template or via the manual method outlined here (https://coreos.com/os/docs/latest/booting-on-ec2.html#manual-setup), I cannot get etcd to start properly. Running `fleetctl list-machines` just spits back `Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd`

Don't have this issue at all when starting fresh with an AMI from the stable channel.

**Comment by meonkeys** [comment]
I don't know much about Fleet or etcd, sorry. In case this helps:

```
core@coreos-stable$ fleetctl list-machines
Error retrieving list of active machines: Get http://domain-sock/fleet/v1/machines?alt=json: dial unix /var/run/fleet.sock: no such file or directory
```

**Comment by timrsmith** [comment]
Ah yeah I've received similar. I'm guessing there's some clean-up needed before coping the freshly launched instances.

**Comment by jeremyd** [comment]
+1 would love to encrypt boot volumes, currently experiencing verity errors.

**Comment by crawford** [comment]
We are working on it in Ignition (https://github.com/coreos/ignition/pull/322). We are shooting to have something available in the next few months.

**Comment by marineam** [comment]
@crawford EBS encryption is unrelated to Ignition's LUKS support, EBS encryption was already fixed in another bug: https://github.com/coreos/bugs/issues/1090

@jeremyd you can encrypt boot volumes, as noted in the above bug. Verity errors would be unrelated to any form of encryption and would be caused by disk or io corruption of some kind. If you are consistently seeing errors across different instances there could be a kernel bug, please open a new bug if that's the case.

**Comment by jeremyd** [comment]
Thanks for the explanation @michael.  I used the amazon ami copy workflow
that AWS suggested to apply encryption. Afterward verity said it was
corrupted filesystem.. I can try a few more copies next week to see if it's
repeatable.
