### ISSUE TITLE
No need to log time and level; journald is taking care of that

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#694]
<a href="https://github.com/afcowie"><img src="https://avatars.githubusercontent.com/u/1088511?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [afcowie](https://github.com/afcowie)**
_Sunday Aug 24, 2014 at 09:42 GMT_
_Originally opened as https://github.com/coreos/update_engine/issues/43_

---

Logging:

> [0824/093710:INFO:update_check_scheduler.cc(84)] Next update check in 10m53s

Is a bit redundant, seeing as how journald takes care of it:

```
Aug 24 09:37:10 cygnus update_engine[473]: [0824/093710:INFO:update_check_scheduler.cc(84)] Next update check in 10m53s
```

How about just logging:

> Next update check in 10m53s

at INFO level, or if you're really desperate for the line number:

> [update_check_scheduler.cc(84)] Next update check in 10m53s

Just a thought.

AfC

**Comment by euank** [comment]
Closing as largely irrelevant.

As a concrete thing which might help , `journalctl -o cat` is a way to omit journald's timestamps, which is one way to make it look less messy.
