### ISSUE TITLE
Support gzip compression

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#741]
<a href="https://github.com/yawn"><img src="https://avatars.githubusercontent.com/u/18242?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yawn](https://github.com/yawn)**
_Friday Jun 06, 2014 at 11:22 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/143_

----

Consider supporting base64 + gzip encoding of cloudinit scripts

**Comment by crawford** [comment]
<a href="https://github.com/yawn"><img src="https://avatars.githubusercontent.com/u/18242?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yawn](https://github.com/yawn)**
_Monday Jun 09, 2014 at 15:25 GMT_

----

Something like this maybe:

```
package initialize

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io/ioutil"
	"strings"
)

func Preprocess(contents string) (string, error) {

	if isDecoded(contents) {
		return contents, nil
	} else if base64, err := tryBase64(contents); err != nil {
		return "", err
	} else if isDecoded(base64) {
		return base64, nil
	} else if zipped, err := tryGzip(base64); err != nil {
		return "", err
	} else if isDecoded(zipped) {
		return zipped, nil
	} else {
		return "", fmt.Errorf("Unable to reconstruct valid configuration via postprocessing from %v", contents)
	}

}

func isDecoded(contents string) bool {
	return strings.Contains(contents, "coreos")
}

func tryBase64(contents string) (string, error) {

	base64, err := base64.StdEncoding.DecodeString(contents)

	if err != nil {
		return "", err
	}

	return string(base64), nil

}

func tryGzip(base64 string) (string, error) {

	var zipped []byte

	zr, err := gzip.NewReader(bytes.NewReader([]byte(base64)))
	zipped, err = ioutil.ReadAll(zr)

	if err != nil {
		return "", err
	}

	if err = zr.Close(); err != nil {
		return "", err
	}

	return string(zipped), nil

}
```

If you agree in principle I'd open a pull request + test. Integration should probably happen [here](https://github.com/coreos/coreos-cloudinit/blob/master/initialize/config.go#L119)

**Comment by crawford** [comment]
<a href="https://github.com/jonboulle"><img src="https://avatars.githubusercontent.com/u/2601015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonboulle](https://github.com/jonboulle)**
_Wednesday Jun 18, 2014 at 19:52 GMT_

----

c.f. http://cloudinit.readthedocs.org/en/latest/topics/format.html#gzip-compressed-content

**Comment by crawford** [comment]
<a href="https://github.com/ianneub"><img src="https://avatars.githubusercontent.com/u/17455?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ianneub](https://github.com/ianneub)**
_Wednesday Dec 10, 2014 at 17:13 GMT_

----

:+1: Any plans to support this? I just hit this limitation.

**Comment by crawford** [comment]
<a href="https://github.com/brotbert"><img src="https://avatars.githubusercontent.com/u/112577?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [brotbert](https://github.com/brotbert)**
_Wednesday Dec 10, 2014 at 17:18 GMT_

----

+1

**Comment by crawford** [comment]
<a href="https://github.com/jonboulle"><img src="https://avatars.githubusercontent.com/u/2601015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonboulle](https://github.com/jonboulle)**
_Wednesday Dec 10, 2014 at 17:45 GMT_

----

@ianneub we don't really have this on the roadmap but I think we'd definitely accept a PR if someone is willing to put in the work - @crawford ?

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Wednesday Dec 10, 2014 at 18:21 GMT_

----

Absolutely. A PR would be great. I'm curious, in what situtions this is needed? Is it a single large file that is being written or many small files/units?

**Comment by crawford** [comment]
<a href="https://github.com/ianneub"><img src="https://avatars.githubusercontent.com/u/17455?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ianneub](https://github.com/ianneub)**
_Wednesday Dec 10, 2014 at 18:44 GMT_

----

For me it is a single large file that I'm trying to write. It looks like #279 might actually fix this issue for me.

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Tuesday Jan 20, 2015 at 22:16 GMT_

----

Is there still a need for this feature? gzip is supported for individual files, just not the entire config.

**Comment by crawford** [comment]
<a href="https://github.com/ianneub"><img src="https://avatars.githubusercontent.com/u/17455?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ianneub](https://github.com/ianneub)**
_Tuesday Jan 20, 2015 at 22:34 GMT_

----

I think with #279 merged, I would not need this anymore. Thanks!

**Comment by crawford** [comment]
<a href="https://github.com/arkadijs"><img src="https://avatars.githubusercontent.com/u/1263169?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arkadijs](https://github.com/arkadijs)**
_Wednesday Mar 04, 2015 at 10:05 GMT_

----

In my case: setting up a number of systemd units via cloud-config, it is essential to have this feature. Splitting into compressed chunks requires additional pre-processing step and compression doesn't help much as individual unit files are small.

**Comment by crawford** [comment]
<a href="https://github.com/KnownSubset"><img src="https://avatars.githubusercontent.com/u/948512?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KnownSubset](https://github.com/KnownSubset)**
_Monday Apr 06, 2015 at 22:12 GMT_

----

Is this ever going to supported?  AWS only supports up to 16KB of user-data.

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Monday Apr 06, 2015 at 22:29 GMT_

----

I would like to support this feature but I do not have the resources right now. If anyone has the time, I will gladly review pull requests. Otherwise, this will have to wait a little longer.

**Comment by h0tbird** [comment]
+1 My user-data is 22k and amazon rejects anything bigger than 16k. They also require `base64` encoding. I wish I could use this:
```
# cat user-data | gzip | base64 > user-data.bz.b64
# ls -la user-data*
-rw-r--r-- 1 marc marc  22K Mar 14 18:17 user-data
-rw-r--r-- 1 marc marc 8.6K Mar 14 19:23 user-data.bz.b64
```

**Comment by crawford** [comment]
This was fixed in https://github.com/coreos/coreos-cloudinit/pull/400.

**Comment by h0tbird** [comment]
coreos/coreos-cloudinit#400 added gzip auto-detection but what about `base64`?
Who should be decoding my `base64` encoded gzip file?

**Comment by crawford** [comment]
Amazon decodes it before it's given to the instance.

**Comment by h0tbird** [comment]
Thank you, that is why it won't work in my Vagrant setup :-)
