### ISSUE TITLE
Disable kexec on UEFI systems.

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#75]
When mixing kexec + UEFI + Intel graphics it is possible to wedge the system during early boot. Considering I plan on moving away from kexec for supporting gracefull fallback anyway I'm not concerned about fixing it for these systems, we already disable kexec/fallback for all Xen systems too.

Requires updates in two places:
- https://github.com/coreos/scripts/blob/master/build_library/configure_bootloaders.sh
- https://github.com/coreos/update_engine/blob/master/coreos-postinst

**Comment by remoe** [comment]
i have this "gradient rectangle" issue again with my current alpha CoreOS 575.0.0
