### ISSUE TITLE
With Vagrant, user-data update does not take effect until 2nd reboot

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#751]
<a href="https://github.com/hapnermw"><img src="https://avatars.githubusercontent.com/u/823943?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hapnermw](https://github.com/hapnermw)**
_Thursday Jul 10, 2014 at 22:41 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/177_

----

The sequence is as follows
1) vagrant halt core-01
2) Update the user-data file in the coreos-vagrant repo
3) vagrant up core-01 --provision
At this point, /var/lib/coreos-vagrant/vagrantfile-user-data contains the updated user-data; however, coreos-cloudinit processed the old version 
4) vagrant halt core-01
5) vagrant up core-01
At this point, coreos-cloudinit processes the correct version of user-data

It appears that when a machine is first provisioned, the /run/systemd/system/coreos-cloudinit-vagrant-user.path waits for user-data to be provisioned before starting its unit. When user-data exists, it runs its unit before Vagrant provisions the updated user-data.

Cloud-config generates runtime changes to the etcd.service and fleet.service; however, the default runtime value for units is false so unit changes are permanent. This is alone confusing. When combined with the fact that, at least in the Vagrant case, user-data is permanently stored and cloud-init always repopulates its changes. Some sorting-out of this is needed.

One way to do this would be to change etcd, fleet and update changes to be permanent and change coreos-cloudinit-vagrant-user.path to use PathChanged instead of PathExists so that user-data is only processed by cloud-init when it changes.

This semantic would fix the current broken semantics for runtime=true units since these units, at least in the case of Vagrant, are recreated on every boot and thus are permanent even if systemd thinks they are runtime.

Also, the doc on the default value of etcd name is incorrect. Cloud-init defaults ETCD_NAME to what appears to be a UUID value; not the, as documented, hostname.

**Comment by crawford** [comment]
<a href="https://github.com/robszumski"><img src="https://avatars.githubusercontent.com/u/755540?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [robszumski](https://github.com/robszumski)**
_Friday Jul 11, 2014 at 18:31 GMT_

----

> Also, the doc on the default value of etcd name is incorrect. Cloud-init defaults ETCD_NAME to what appears to be a UUID value; not the, as documented, hostname.

Address this in https://github.com/coreos/etcd/pull/889

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Thursday Sep 11, 2014 at 23:17 GMT_

----

@hapnermw are you still seeing this behavior?

**Comment by crawford** [comment]
<a href="https://github.com/hapnermw"><img src="https://avatars.githubusercontent.com/u/823943?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hapnermw](https://github.com/hapnermw)**
_Monday Sep 15, 2014 at 18:04 GMT_

----

I haven't been using the cluster lately so I can't say. Off on another
project ...

**Comment by crawford** [comment]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [crawford](https://github.com/crawford)**
_Monday Sep 15, 2014 at 18:08 GMT_

----

@hapnermw OK, please reopen this if you run into the issue again.

**Comment by hapnermw** [comment]
Hi Alex,

I haven't been using vagrant lately so I don't know if its still an issue.

-- Mark
