### ISSUE TITLE
Tune etcd election timeouts

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#76]
Due to poor EC2 performance etcd's election timeout was changed from 200ms to 1200ms. That value has since been copied to generic OpenStack (simply by sharing the OEM with EC2) and Rackspace (needed to be bumped and no one took the time to figure out a better value). OpenStack should just use the 200ms default since the that platform is too varied to pick something else and we should do more testing on Rackspace to see if it can use a lower timeout.

**Comment by yichengq** [comment]
@marineam How is this going? I think this is no longer an issue for etcd2. Is that true?

**Comment by marineam** [comment]
@yichengq  Yeah, closing.
