### ISSUE TITLE
how to bring back and orphaned instance (and why should it orphan out in the first place?)

### ISSUE THREAD

**Issue by developerinlondon** [coreos/bugs#77]
I am trying to figure out why one of my instances got orphaned out. I just stopped a few of the Deis services that doesnt meddle with CoreOS (as far as I know) then boom, the instance is no longer in the fleet.

Whats the best way to figure out whats going on and get it to rejoin the cluster?

I tried running `systemctl cat etcd` and saw the etcd variables are still set:
```
core@ip-172-31-36-213 ~ $ systemctl cat etcd
# /usr/lib64/systemd/system/etcd.service
[Unit]
Description=etcd

[Service]
User=etcd
PermissionsStartOnly=true
Environment=ETCD_DATA_DIR=/var/lib/etcd ETCD_NAME=default
ExecStart=/usr/bin/etcd 
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target

# /run/systemd/system/etcd.service.d/10-oem.conf
[Service]
Environment=ETCD_PEER_ELECTION_TIMEOUT=1200

# /run/systemd/system/etcd.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/3f2dcdd84c7d89498f00e5163c28ea63"
Environment="ETCD_ADDR=172.31.36.213:4001"
Environment="ETCD_PEER_ADDR=172.31.36.213:7001"
Environment="ETCD_NAME=87cb1e499dd949958e08ceae20b2922f"

```

**Comment by yichengq** [comment]
Close it due to low activity.

We strongly recommend to use etcd 2.x, which is more stable. A testing 2.x cluster is running on GCE under heavy load for more than half a year.
