### ISSUE TITLE
SSH into CoreOS machine is extremely slow

### ISSUE THREAD

**Issue by makeamark1** [coreos/bugs#79]
When trying to evaluate CoreOS using Vagrant and VirtualBox on Mac OS X, the created machine is nearly unusable because entering into it with "vagrant ssh" takes everything from 30-80 seconds. Additionally any other SSH sessions seem to be frozen for the duration of the login attempt. I have tried destroying and recreating the machine, using alpha and beta releases of CoreOS and other ways of working around the issue, but it keeps reproducing.

It seems that the same issue has been encountered by others too, as [reported](http://comments.gmane.org/gmane.linux.coreos.devel/1125) on the CoreOS mailing list. This issue is a blocker to evaluating CoreOS for me, as such slowness makes the machine unpractical to use.

Below is a transcript that shows the issue. Notice how the times seem to align on 61 and 31 seconds respectively, perhaps hinting that there is some operation timing out that is causing the slowness.

```
$ vagrant --version
Vagrant 1.6.3
$ VBoxManage --version
4.3.14r95030
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.4
BuildVersion:   13E28
$ git clone https://github.com/coreos/coreos-vagrant.git
[...]
$ cd coreos-vagrant
$ time vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Importing base box 'coreos-alpha'...
==> core-01: Matching MAC address for NAT networking...
==> core-01: Checking if box 'coreos-alpha' is up to date...
==> core-01: Setting the name of the VM: coreos-vagrant_core-01_1405625850500_22596
==> core-01: Clearing any previously set network interfaces...
==> core-01: Preparing network interfaces based on configuration...
    core-01: Adapter 1: nat
    core-01: Adapter 2: hostonly
==> core-01: Forwarding ports...
    core-01: 22 => 2222 (adapter 1)
==> core-01: Running 'pre-boot' VM customizations...
==> core-01: Booting VM...
==> core-01: Waiting for machine to boot. This may take a few minutes...
    core-01: SSH address: 127.0.0.1:2222
    core-01: SSH username: core
    core-01: SSH auth method: private key
    core-01: Warning: Connection timeout. Retrying...
    core-01: Warning: Connection timeout. Retrying...
==> core-01: Machine booted and ready!
==> core-01: Setting hostname...
==> core-01: Configuring and enabling network interfaces...
113.618 secs
$ vagrant ssh -c 'cat /etc/os-release' | grep VERSION
VERSION=379.3.0
VERSION_ID=379.3.0
$ time vagrant ssh -c :
Connection to 127.0.0.1 closed.
61.810 secs
$ time vagrant ssh -c :
Connection to 127.0.0.1 closed.
31.716 secs
$ time vagrant ssh -c :
Connection to 127.0.0.1 closed.
61.825 secs
$ time vagrant ssh -c :
Connection to 127.0.0.1 closed.
31.758 secs
$ vagrant ssh -c journalctl | tail
[...]
Jul 17 22:50:17 core-01 systemd[1]: Starting OpenSSH per-connection server daemon (10.0.2.2:54092)...
Jul 17 22:50:17 core-01 systemd[1]: Started OpenSSH per-connection server daemon (10.0.2.2:54092).
Jul 17 22:50:17 core-01 sshd[2551]: SSH: Server;Ltype: Version;Remote: 10.0.2.2-54092;Protocol: 2.0;Client: OpenSSH_6.2
Jul 17 22:50:17 core-01 sshd[2551]: SSH: Server;Ltype: Kex;Remote: 10.0.2.2-54092;Enc: aes128-ctr;MAC: hmac-md5-etm@openssh.com;Comp: zlib@openssh.com [preauth]
Jul 17 22:50:17 core-01 sshd[2551]: SSH: Server;Ltype: Authname;Remote: 10.0.2.2-54092;Name: core [preauth]
Jul 17 22:50:48 core-01 sshd[2551]: Accepted publickey for core from 10.0.2.2 port 54092 ssh2: RSA dd:3b:b8:2e:85:04:06:e9:ab:ff:a8:0a:c0:04:6e:d6
Jul 17 22:50:48 core-01 sshd[2551]: SSH: Server;Ltype: Kex;Remote: 10.0.2.2-54092;Enc: aes128-ctr;MAC: hmac-md5-etm@openssh.com;Comp: zlib@openssh.com
Jul 17 22:50:48 core-01 sshd[2551]: Received disconnect from 10.0.2.2: 11: disconnected by user
```

**Comment by msumme** [comment]
Hm - I'm running into this on 557.2.0.  It seems to be on both local vagrant and AWS.  Is there a workaround or something I can do to mitigate this problem?  It's making development painfully slow.

**Comment by crawford** [comment]
@msumme I have one idea for your vagrant case (I found one more case where we attempt a DNS lookup for the issue text). I have no idea about AWS though. Are you sure it's not just AWS provisioning the machine?

**Comment by msumme** [comment]
Well - the development machine is where 90% of the pain is, so... I'd love to hear that.

It's definitely the exact same issue.  It seems to be because all the different units are checking for a non-existent domain.  Once a particular unit file is up and running, it broadcasts the IP for the docker container and the hostname resolves.

If there was a way to get it to stop hanging when DNS queries fail, that would be... great.

**Comment by crawford** [comment]
@msumme your AWS issue sounds like a different underlying problem. Can you open up a new bug for that specifically?

**Comment by msumme** [comment]
Well - it's an issue on Virtualbox too.  So it's not AWS specifically.

**Comment by marineam** [comment]
@crawford issue shouldn't impact SSH, it is only used by the getty.
