### ISSUE TITLE
Allow adding custom certificate CAs

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#810]
<a href="https://github.com/radeksimko"><img src="https://avatars.githubusercontent.com/u/287584?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [radeksimko](https://github.com/radeksimko)**
_Thursday Apr 30, 2015 at 12:52 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/339_

---

It's quite easy to do this manually:
https://coreos.com/docs/cluster-management/setup/adding-certificate-authorities/

but I believe this should be just part of cloud init, so it can be automated.

**Comment by h0tbird** [comment]
Please, also make sure it works on the very first boot and before the services that are going to use the user-provided CA (such as docker). My current solution only woks after the second boot onwards. For me the first boot its enough, I don't need re-hashing on every boot (it takes time).

This is what I do now:
```
- name: "update-ca-certificates.service"
  drop-ins:
   - name: 50-rehash-certs.conf
     content: |
      [Unit]
      ConditionPathIsSymbolicLink=

      [Service]
      ExecStart=
      ExecStart=/usr/sbin/update-ca-certificates
```

**Comment by crawford** [comment]
Ignition solves this. Please use that tool instead of coreos-cloudinit.

**Comment by h0tbird** [comment]
Is there a way to translate from coreos-cloudinit to ignition?

**Comment by crawford** [comment]
@h0tbird there is no automated way (the semantics between the two tools is different enough that this would be a very difficult program to write). We have the [config transpiler](https://github.com/coreos/container-linux-config-transpiler), which allows you to maintain your Ignition configs in a human-friendly form. I'd be more than happy to help you translate your configs if you run into trouble.

**Comment by h0tbird** [comment]
I have collections of *Go* template fragments which I dynamically assemble together based on tags and filters. Once the template is composed I render the *coreos-cloudinit*. It is not clear to me how the *config transpiler* can be integrated into the flow. Where can I find a sample YAML definition and usage instructions?

**Comment by crawford** [comment]
> After looking into Ignition I think it makes more sense for me to stick to the native JSON format

Exactly! Since you are programmatically generating that config, it's fine if you generate the Ignition config directly. As you are doing the migration, make sure you take advantage of https://coreos.com/validate/. If you're anything like me, it'll save you a ton of time.

**Comment by h0tbird** [comment]
Yes, I do validate [programmatically](https://github.com/katosys/kato/blob/0ef94d9faa9dfc63872150eef5816c6b489c02d4/udata/udata.go#L401-L415) it is a must for me too :)
