### ISSUE TITLE
Trash godep

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#824]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [crawford](https://github.com/crawford)**
_Tuesday Jul 14, 2015 at 18:51 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/361_

----

Once golang 1.5 arrives, we can get rid of godep. :')

**Comment by xrl** [comment]
Looks `vendor/` support will be an experiment in 1.5 and then in 1.6 it will work transparently: https://github.com/golang/go/commit/183cc0cd41f06f83cb7a2490a499e3f9101befff
