### ISSUE TITLE
Add locksmith reboot window parameters

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#832]
<a href="https://github.com/crawford"><img src="https://avatars.githubusercontent.com/u/368848?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [crawford](https://github.com/crawford)**
_Monday Sep 21, 2015 at 17:32 GMT_
_Originally opened as https://github.com/coreos/coreos-cloudinit/issues/392_

----

**Comment by vcaputo** [comment]
@mischief didn't you implement this?
