### ISSUE TITLE
LOCKSMITHD_ENDPOINT - does it work?

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#853]
<a href="https://github.com/xueshanf"><img src="https://avatars.githubusercontent.com/u/4178225?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [xueshanf](https://github.com/xueshanf)**
_Friday Feb 06, 2015 at 04:37 GMT_
_Originally opened as https://github.com/coreos/locksmith/issues/66_

----

I have worker machines that do not run etcd, but locksmithd is enabled:

     $systemctl is-active locksmithd etcd
     active
     inactive

/etc/cores/update.conf:

    GROUP=stable
    LOCKSMITHD_ENDPOINT=etcd-endpoint.example.local:4001
    REBOOT_STRATEGY=off

And locksmith unit - the default one except the last section for run time service drop-in:

    $systemctl cat locksmithd

    # /usr/lib64/systemd/system/locksmithd.service
    [Unit]
    Description=Cluster reboot manager
    Requires=update-engine.service
    After=update-engine.service
    ConditionVirtualization=!container
    ConditionPathExists=!/usr/.noupdate

    [Service]
    CPUShares=16
    MemoryLimit=32M
    PrivateDevices=true
    EnvironmentFile=-/usr/share/coreos/update.conf
    EnvironmentFile=-/etc/coreos/update.conf
    ExecStart=/usr/lib/locksmith/locksmithd
    Restart=always
    RestartSec=10s

    [Install]
    WantedBy=multi-user.target

    # /run/systemd/system/locksmithd.service.d/20-cloudinit.conf
    [Service]
    Environment="LOCKSMITHD_ENDPOINT=etcd-endpoint.example.local:4001"

With that, I thought locksmithd should use the "LOCKSMITHD_ENDPOINT" env, but it doesn't

    $ systemctl status locksmithd
    locksmithd.service - Cluster reboot manager
    Loaded: loaded (/usr/lib64/systemd/system/locksmithd.service; disabled)
    Drop-In: /run/systemd/system/locksmithd.service.d
           └─20-cloudinit.conf
    Active: active (running) since Fri 2015-02-06 03:50:45 UTC; 37min ago
    Main PID: 12843 (locksmithd)
    CGroup: /system.slice/locksmithd.service
           └─12843 /usr/lib/locksmith/locksmithd

    Feb 06 03:51:20 ip-10-42-5-50.us-west-2.compute.internal locksmithd[12843]: Unlocking old locks failed: etcd.service is inactive. Retrying in 40s.
    Feb 06 03:52:00 ip-10-42-5-50.us-west-2.compute.internal locksmithd[12843]: Unlocking old locks failed: etcd.service is inactive. Retrying in 1m20s.
    Feb 06 03:53:20 ip-10-42-5-50.us-west-2.compute.internal locksmithd[12843]: Unlocking old locks failed: etcd.service is inactive. Retrying in 2m40s.
    Feb 06 03:56:00 ip-10-42-5-50.us-west-2.compute.internal locksmithd[12843]: Unlocking old locks failed: etcd.service is inactive. Retrying in 5m0s.
    Feb 06 04:01:00 ip-10-42-5-50.us-west-2.compute.internal locksmithd[12843]: Unlocking old locks failed: etcd.service is inactive. Retrying in 5m0s.

The locksmithctl client does work with --endpoint:

    $ printenv |grep LOCK
    LOCKSMITHCTL_ENDPOINT=http://etcd-endpoint.example.local:4001
    $ locksmithctl status
    Available: 1
    Max: 1

The problem is that if I use locksmithctl reboot, the reboot lock doesn't get released, I think because locksmithd isnt working with LOCKSMITHD_ENDPOINT setting.

Any ideas what I might have missed?

**Comment by crawford** [comment]
<a href="https://github.com/jonboulle"><img src="https://avatars.githubusercontent.com/u/2601015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonboulle](https://github.com/jonboulle)**
_Friday Feb 06, 2015 at 16:31 GMT_

----

What version of locksmith is this? The endpoint flag was only added very
recently so it's quite possible it's not available in yours yet.
locksmithctl --version

**Comment by crawford** [comment]
<a href="https://github.com/xueshanf"><img src="https://avatars.githubusercontent.com/u/4178225?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [xueshanf](https://github.com/xueshanf)**
_Friday Feb 06, 2015 at 17:33 GMT_

----

locksmithctl version 0.2.2.

**Comment by crawford** [comment]
<a href="https://github.com/jonboulle"><img src="https://avatars.githubusercontent.com/u/2601015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonboulle](https://github.com/jonboulle)**
_Friday Feb 06, 2015 at 21:07 GMT_

----

Hmm, it looks like this hasn't actually made it into a release yet :-/

/cc @crawford

**Comment by crawford** [comment]
<a href="https://github.com/benkershner"><img src="https://avatars.githubusercontent.com/u/1414024?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [benkershner](https://github.com/benkershner)**
_Tuesday Feb 17, 2015 at 21:31 GMT_

----

Same issue. Building a cluster with the Central Services/Worker architecture, and I disabled etcd on the Worker boxes. Turns out locksmith was getting the semaphore from its *local* etcd and not the one specified by the command line. I'm running an Nginx reverse proxy from the localhost to the Central Services cluster as a workaround.

**Comment by crawford** [comment]
<a href="https://github.com/jonboulle"><img src="https://avatars.githubusercontent.com/u/2601015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonboulle](https://github.com/jonboulle)**
_Tuesday Feb 17, 2015 at 21:58 GMT_

----

This will be available in locksmith >=0.2.3 - #67

**Comment by crawford** [comment]
<a href="https://github.com/jonboulle"><img src="https://avatars.githubusercontent.com/u/2601015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonboulle](https://github.com/jonboulle)**
_Wednesday Feb 18, 2015 at 18:42 GMT_

----

(which should make it into the alpha channel of CoreOS in the next few days)

**Comment by crawford** [comment]
<a href="https://github.com/popsikle"><img src="https://avatars.githubusercontent.com/u/3680316?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [popsikle](https://github.com/popsikle)**
_Monday Mar 09, 2015 at 19:17 GMT_

----

lcoksmith 0.2.3 has made its way into beta channel, and this doesn't quite seem to work yet.


```
locksmithctl --debug=true status
Error initializing etcd client: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

cloudinit settings:
```
cat 20-cloudinit.conf
[Service]
Environment="LOCKSMITHD_ENDPOINT=http://172.21.10.241:2379,http://172.21.10.242:2379,http://172.21.10.243:2379,http://172.21.10.244:2379,http://172.21.10.245:2379"
```

ectd cluster is reachable:
```
etcdctl -debug ls
Cluster-Peers: http://172.21.10.241:2379 http://172.21.10.241:2379 http://172.21.10.242:2379 http://172.21.10.242:2379 http://172.21.10.243:2379 http://172.21.10.243:2379 http://172.21.10.244:2379 http://172.21.10.244:2379 http://172.21.10.245:2379 http://172.21.10.245:2379
Curl-Example: curl -X GET http://172.21.10.241:2379/v2/keys/?consistent=true&recursive=false&sorted=false
/dev
```

**Comment by crawford** [comment]
<a href="https://github.com/popsikle"><img src="https://avatars.githubusercontent.com/u/3680316?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [popsikle](https://github.com/popsikle)**
_Monday Mar 09, 2015 at 19:20 GMT_

----

on a side note, there seems to be some logic missing for off-host etcd clusters using etcd-lock strat:
https://github.com/coreos/locksmith/blob/master/locksmithctl/daemon.go#L248-L251 will always fail if etcd is masked on the current host because etcd is running on service hosts, not workers.

**Comment by crawford** [comment]
<a href="https://github.com/jonboulle"><img src="https://avatars.githubusercontent.com/u/2601015?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonboulle](https://github.com/jonboulle)**
_Friday Mar 13, 2015 at 03:36 GMT_

----

You're right :-(, filed #69

**Comment by crawford** [comment]
<a href="https://github.com/a86c6f7964"><img src="https://avatars.githubusercontent.com/u/165381?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [a86c6f7964](https://github.com/a86c6f7964)**
_Thursday Apr 16, 2015 at 01:47 GMT_

----

I should expect this still to not work?
```
core@ip-172-31-29-199 ~ $ locksmithctl -version
locksmithctl version 0.2.3
core@ip-172-31-29-199 ~ $ locksmithctl --endpoint "http://172.31.35.95:4001,http://172.31.11.96:4001,http://172.31.18.233:4001" --debug=true status
Available: 0
Max: 1

MACHINE ID
07f3062062244251b3b75109d7db948e
core@ip-172-31-29-199 ~ $ LOCKSMITHD_ENDPOINT="http://172.31.35.95:4001,http://172.31.11.96:4001,http://172.31.18.233:4001" locksmithctl --debug=true status
Error initializing etcd client: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
core@ip-172-31-29-199 ~ $ LOCKSMITHD_ENDPOINTS="http://172.31.35.95:4001,http://172.31.11.96:4001,http://172.31.18.233:4001" locksmithctl --debug=true status
Error initializing etcd client: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```
Should the documentation for https://coreos.com/docs/cluster-management/setup/cluster-architectures/ get updated? I just followed the
```
coreos:
  fleet:
    metadata: "role=worker"
    etcd_servers: "http://10.0.0.101:4001,http://10.0.0.102:4001,http://10.0.0.103:4001,http://10.0.0.104:4001,http://10.0.0.105:4001"
  locksmith:
    endpoint: "http://10.0.0.101:4001,http://10.0.0.102:4001,http://10.0.0.103:4001,http://10.0.0.104:4001,http://10.0.0.105:4001"
```
and that does not seem to work

**Comment by crawford** [comment]
<a href="https://github.com/a86c6f7964"><img src="https://avatars.githubusercontent.com/u/165381?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [a86c6f7964](https://github.com/a86c6f7964)**
_Thursday Apr 16, 2015 at 01:53 GMT_

----

Ah this works though
```
LOCKSMITHCTL_ENDPOINT="http://172.31.35.95:4001,http://172.31.11.96:4001,http://172.31.18.233:4001" locksmithctl --debug=true status
```
just trying to figure out what a good work around for this would be.

**Comment by crawford** [comment]
<a href="https://github.com/serbaut"><img src="https://avatars.githubusercontent.com/u/68637?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [serbaut](https://github.com/serbaut)**
_Thursday Apr 30, 2015 at 12:52 GMT_

----

A workaround is to run etcd in -proxy mode on each host.

**Comment by genti-t** [comment]
I'm using locksmith 0.3.0. on stable channel coreos
my cloud-config part :
```
  locksmith:
      endpoint: "https://192.168.91.211:2379,https://192.168.91.212:2379,https://192.168.91.213:2379"
      etcd_cafile: "/etc/certs/ca.pem"
      etcd_certfile: "/etc/certs/etcdclient.pem"
      etcd_keyfile: "/etc/certs/etcdclient-key.pem"
  update:
    reboot-strategy: "etcd-lock"
```

generate correctly .service file:
```
# /usr/lib64/systemd/system/locksmithd.service
[Unit]
Description=Cluster reboot manager
ConditionVirtualization=!container
ConditionPathExists=!/usr/.noupdate

[Service]
CPUShares=16
MemoryLimit=32M
PrivateDevices=true
Environment=GOMAXPROCS=1
EnvironmentFile=-/usr/share/coreos/update.conf
EnvironmentFile=-/etc/coreos/update.conf
ExecStart=/usr/lib/locksmith/locksmithd
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target

# /run/systemd/system/locksmithd.service.d/20-cloudinit.conf
[Service]
Environment="LOCKSMITHD_ENDPOINT=https://192.168.91.211:2379,https://192.168.91.212:2379,https://192.168.91.213:2379"
Environment="LOCKSMITHD_ETCD_CAFILE=/etc/certs/ca.pem"
Environment="LOCKSMITHD_ETCD_CERTFILE=/etc/certs/etcdclient.pem"
Environment="LOCKSMITHD_ETCD_KEYFILE=/etc/certs/etcdclient-key.pem"

```

On the logs is steel tryng on local etcd...
```
Unlocking old locks failed: [etcd.service etcd2.service] are inactive. Retrying in ...
```

But after a while it is able to lock on etcd:
```
# etcdctl-lz -o extended get /coreos.com/updateengine/rebootlock/semaphore
Key: /coreos.com/updateengine/rebootlock/semaphore
Created-Index: 2342
Modified-Index: 2343
TTL: 0
Index: 3580

{"semaphore":0,"max":1,"holders":["af640fcfaa714dd79e5949ff04cd333c"]}
```

and never get the Unlocking.

Did I missed something here, or just ver version is not the right one ?

**Comment by crawford** [comment]
@genti-t this issue was fixed in [0.3.1](https://github.com/coreos/locksmith/blob/master/CHANGELOG.md#v031). It should end up in Stable in a couple days.

**Comment by wmark** [comment]
I've run into this with CoreOS 983.0.0 and locksmithctl version 0.3.4

I suspect that environment variables are not read at all.

**Comment by bnordbo** [comment]
I get this behaviour too, in locksmithd 0.3.4, if running in `best-effort` mode. When using `etcd-lock` it works fine. I think it is due to locksmith literally [checking if etcd is running](https://github.com/coreos/locksmith/blob/master/locksmithctl/daemon.go#L226), as the documentation states. In my humble opinion, the `best-effort` mode is somewhat dangerous as it can give a false feeling of security: All of a sudden, you could see your instances rebooting for no good reason, e.g. because the local etcd proxy was stopped for whatever reason.

**Comment by crawford** [comment]
@bnordbo you are exactly correct - `best-effort` is dangerous. It has since been deprecated and we are beginning the process of killing it completely.

**Comment by danieldkim** [comment]
I was having this issue with 0.3.4.  Couldn't get locksmithctl working with commandline options or environment variables.  After switching to the beta channel on one of the machines in my cluster, which bumped locksmithctl to 0.4.1, I got a different error message which helped me realize the underlying issue:

    Error initializing etcd client: 110: The request requires user authentication (Insufficient credentials) [0]

I have authentication turned on in etcd but did not allow access to the path that locksmith needs to write its semaphore.  Granting readwrite access to the guest role to /coreos.com/* resolved the issue for me.
