### ISSUE TITLE
can't create disk image with coreos-install on ubuntu 12.04LTS

### ISSUE THREAD

**Issue by timfpark** [coreos/bugs#86]
I'm trying to create a image using coreos-install but I'm getting the following error when it tries to create the disk image - any ideas?

$ sudo ./coreos-install -d /dev/sdc -C alpha -c ~/cloud-config.yaml
Downloading and verifying coreos_production_image.bin.bz2...
--2014-07-21 21:11:33--  http://alpha.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2
Resolving alpha.release.core-os.net (alpha.release.core-os.net)... 74.125.29.128, 2607:f8b0:400d:c04::80
Connecting to alpha.release.core-os.net (alpha.release.core-os.net)|74.125.29.128|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 174961980 (167M) [application/octet-stream]
Saving to: `/tmp/coreos-install.dxyacsYigX/coreos_production_image.bin.bz2'

100%[===============================================================================================================================================>] 174,961,980 55.8M/s   in 3.0s    

2014-07-21 21:11:37 (55.8 MB/s) - `/tmp/coreos-install.dxyacsYigX/coreos_production_image.bin.bz2' saved [174961980/174961980]

2014-07-21 21:11:37 URL:http://alpha.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2.sig [543/543] -> "/tmp/coreos-install.dxyacsYigX/coreos_production_image.bin.bz2.sig" [1]
gpg: Signature made Wed 16 Jul 2014 02:58:03 AM UTC using RSA key ID 74E7E361
gpg: key 93D2DCB4 marked as ultimately trusted
gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Good signature from "CoreOS Buildbot (Offical Builds) buildbot@coreos.com"
Writing coreos_production_image.bin.bz2 to /dev/sdc...
  /tmp/coreos-install.dxyacsYigX/coreos_production_image.bin.bz2: done
Installing cloud-config...
mount: wrong fs type, bad option, bad superblock on /dev/sdc9,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

$ dmesg | tail
[  391.480829] GPT:9179135 != 62914559
[  391.480831] GPT:Alternate GPT header not at the end of the disk.
[  391.480833] GPT:9179135 != 62914559
[  391.480834] GPT: Use GNU Parted to correct GPT errors.
[  391.480865]  sdc: sdc1 sdc2 sdc3 sdc4 sdc6 sdc7 sdc9
[  394.094131] Btrfs loaded
[  394.103415] device label ROOT devid 1 transid 18 /dev/sdc9
[  394.107915] btrfs: disk space caching is enabled
[  394.107919] BTRFS: couldn't mount because of unsupported optional features (60).
[  394.118303] btrfs: open_ctree failed

**Comment by crawford** [comment]
We no longer use btrfs by default, so this shouldn't be an issue anymore.
