### ISSUE TITLE
Prefix REBOOT_WINDOW_START and REBOOT_WINDOW_LENGTH with LOCKSMITHD_

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#862]
<a href="https://github.com/philips"><img src="https://avatars.githubusercontent.com/u/33544?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philips](https://github.com/philips)**
_Thursday Sep 24, 2015 at 06:00 GMT_
_Originally opened as https://github.com/coreos/locksmith/issues/90_

----

These two env variables are missing the prefix for some reason. We should add the prefix in so it is consistent with our other applications.

**Comment by vcaputo** [comment]
@mischief did you see this?

**Comment by mischief** [comment]
fixed by coreos/locksmith#96 coreos/locksmith#98
