### ISSUE TITLE
machinectl shell broken with systemd 225 (coreos 815) (fixed in 226)

### ISSUE THREAD

**Issue by f0** [coreos/bugs#863]
Hi,

with systemd 225 the machinectl shell commad is broken
when you run an nspawn container and try to log in via machinectl shell <name>, you go logget out of coreos.

this should be fixed in 226, so please update

mailing list discussion
https://mail.google.com/mail/#search/systemd+ma/14f9de1b981ee246

regards f0

cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=815.0.0
VERSION_ID=815.0.0
BUILD_ID=
PRETTY_NAME="CoreOS 815.0.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

**Comment by jonboulle** [comment]
For posterity could we get a link to the upstream bug/change?

**Comment by f0** [comment]
Commit: https://github.com/systemd/systemd/commit/5f430ff76e8e5f7ca5b7ef67dd3b205487a0f41b
Upstream Bug: https://github.com/systemd/systemd/issues/1139
