### ISSUE TITLE
IPv6 is specifically not enabled

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#866]
<a href="https://github.com/philk"><img src="https://avatars.githubusercontent.com/u/29562?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philk](https://github.com/philk)**
_Tuesday Aug 19, 2014 at 23:33 GMT_
_Originally opened as https://github.com/coreos/nova-agent-watcher/issues/9_

---

Currently the [gentoo-networkd script](https://github.com/coreos/nova-agent-watcher/blob/master/scripts/gentoo-to-networkd#L46) skips over IPv6 info and never sets it up. In my limited testing (commenting out that if/continue) IPv6 actually works fine on Rackspace Cloud. I don't currently have a private Openstack cluster to test on and the [commit that created the skip](https://github.com/coreos/nova-agent-watcher/commit/c2a1eb257949d99b289629b56e9686473f905c71#diff-d41d8cd98f00b204e9800998ecf8427e) doesn't have any info.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
