### ISSUE TITLE
OEM build for Interoute has disk/partition corruption

### ISSUE THREAD

**Issue by xied75** [coreos/bugs#868]
Dear Team,

Starting from 801, 808 then 815, the ova we downloaded from release website doesn't work properly. We checked the hash value of the downloads and they all match.

The main problem is during boot sgdisk will complain that partition table does not match backup and suggest use C to fix. Then disk-uuid.service fail, which can be seen by first login. If we run a docker pull triggering writing to sda9, in dmesg there will be ext4 error and remounting sda9 as readonly.

I tried to compare this with a Prod build from a local CoreOS SDK build, that one works correct. It seems ova downloaded from release site is a bit smaller than the SDK build, although the disk layout is exactly same.

Given the SDK produced ova can work properly I assume this should be some error within the build pipeline for release?

(Already reported this to @marineam on irc, need @crawford 's attention too.)

Thanks for helping!

Best regards,

Dong

**Comment by crawford** [comment]
@xied75 are you still seeing this issue?

**Comment by xied75** [comment]
@crawford yes at least 10 days ago still the same.

Although even more strange thing happened. After lots of deployments behaved like above, suddenly I got a zone (as in cloudstack) that worked. The sgdisk finishes without any error msg and disk-uuid.service also success.

So then I checked the cloudstack mysql database, all 13 zones' templates are showing the same hash value, (as long as this is not a cloudstack bug, then we should believe all zones have the SAME template). I then deleted the template from a non-working zone and copied the working one over, funny enough, it still does NOT work.

The only difference I can tell from journalctl having working non-working displayed side-by-side, is that the non working one will fail at sgdisk, manually running that shows the primary partition table checksum messed up, yet the backup one is correct.

I just can't figure out how come the same template booting up in different zones would affect the partition table in anyway. I used to think this is some kind of race condition at early bootup, now I feel there is a wormhole ...

**Comment by crawford** [comment]
I'm not very familiar with Interoute, so I don't _fully_ understand what you've described. Does Interoute do any processing of the image after it is downloaded from our storage site? It looks like there is some corruption happening, though I am not sure where. I've seen these failures on other systems when we used incompatible image formats, but a number of our image flavors use vmdk-stream (the disk format that Interoute uses) so I would expect to see more failures.

**Comment by xied75** [comment]
@crawford Interoute use plain vanilla cloudstack 4.3, the template importing was done either by ansible or terraform, which eventually calls cloudstack api, with the coreos release URL as parameter. Simply put, there is NO intermediate steps in between the coreos release site and cloudstack (secondary storage). Besides, cloudstack would do hash on the image file.

Your mentioning of vmdk-stream is interesting, I'll dig a bit more. Thanks for helping.

**Comment by benjvi** [comment]
Hi @crawford @xied75 any idea what the problem might be here? I'm still seeing this issue in testing with the 835 beta build..

**Comment by crawford** [comment]
@xied75 is this still an ongoing issue? We are going to need your help resolving the issue since this platform is not a high priority for us.

**Comment by xied75** [comment]
@crawford Thanks for asking. Need @benjvi to answer this now.

**Comment by benjvi** [comment]
I don't know if anyone's still working on this either, suggest to close

**Comment by crawford** [comment]
@benjvi is this resolved or should we stop publishing the images?

**Comment by benjvi** [comment]
The issue remained the last time I looked at it. Given that, in all likelihood it should be fine to stop publishing the images but I really can't say for sure

cc @gaelcolas

**Comment by gaelcolas** [comment]
I am not aware of anyone working on/using this, @benjvi is probably right then.

**Comment by crawford** [comment]
We've disabled the Interoute images from our publishing pipeline. I'm going to close this out.
