### ISSUE TITLE
Google Compute Engine: Local SSD breaks rule 79-net-google-compat

### ISSUE THREAD

**Issue by gdcbyers** [coreos/bugs#869]
This appears to be the same issue as #245. When creating a new instance that uses the local SSD, the network interface PCI "address" changes, resulting in no interface named "ens4v1" breaking the google-compute-daemon/address_manager.py script. I can not patch the rule "79-net-google-compat.rules" because /usr is mounted as read-only. What can I do in the short term to fix this?

Output of udevadm info --query=all --path=/sys/class/net/eth0

```
P: /devices/pci0000:00/0000:00:05.0/virtio2/net/eth0
E: DEVPATH=/devices/pci0000:00/0000:00:05.0/virtio2/net/eth0
E: ID_BUS=pci
E: ID_MODEL_FROM_DATABASE=Virtio network device
E: ID_MODEL_ID=0x1000
E: ID_NET_DRIVER=virtio_net
E: ID_NET_LINK_FILE=/usr/lib64/systemd/network/99-default.link
E: ID_NET_NAME_MAC=enx42010a010004
E: ID_PATH=pci-0000:00:05.0
E: ID_PATH_TAG=pci-0000_00_05_0
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Red Hat, Inc
E: ID_VENDOR_ID=0x1af4
E: IFINDEX=2
E: INTERFACE=eth0
E: SUBSYSTEM=net
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/eth0
E: TAGS=:systemd:
E: USEC_INITIALIZED=6806835
```

**Comment by crawford** [comment]
udev will read it's rules from multiple locations. You can copy "79-net-google-compat.rules" into /etc and edit that copy.

**Comment by marineam** [comment]
This is a bug in the noted udev rules, it shouldn't have been closed. Sorry about that.

**Comment by crawford** [comment]
The GCE images don't use the persistent naming anymore, so this should no longer be an issue.

**Comment by bsphere** [comment]
@crawford what should be done to fix this? internal load balancers doesn't work (failing health checks) because of google-address-manager not running..
