### ISSUE TITLE
option to have docker socket and /usr/bin/docker available in the toolbox container

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#877]
<a href="https://github.com/ibukanov"><img src="https://avatars.githubusercontent.com/u/2381216?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ibukanov](https://github.com/ibukanov)**
_Wednesday Nov 05, 2014 at 19:58 GMT_
_Originally opened as https://github.com/coreos/toolbox/issues/8_

---

The current toolbox provides neither an access to the docker socket nor the docker binary preventing to use the toolbox as a universal management tool. It would be nice if toolbox exposed those into the container either by default or with an option.

Currently as a workaround I have a custom copy of the toolbox script with `--bind=/run/docker.sock --bind-ro=/usr/bin/docker` added to the systemd-nspawn arguments, but that works by an accident. `docker` executable is not fully statically linked and there is no guarantee that the fedora image provides the shared libraries the executable depends on.

I suppose a better option would be to turn in the toolbox container /usr/bin/docker into a script that runs the executable from /media/root/usr with the LD_LIBRARY_PATH set to /media/root/usr/lib64/

**Comment by jonboulle** [comment]
<a href="https://github.com/bjaglin"><img src="https://avatars.githubusercontent.com/u/349077?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bjaglin](https://github.com/bjaglin)**
_Friday Nov 28, 2014 at 07:30 GMT_

----

I ran into a similar problem when bind-mounting the `docker` CLI into a container. As far as I know, the official client is statically linked, but the one embedded in CoreOS doesn't appear to be so. I am guessing creating a custom image, mounting the libs inside the container or downloading a statically linked client are the only way to go?

**Comment by jonboulle** [comment]
<a href="https://github.com/ibukanov"><img src="https://avatars.githubusercontent.com/u/2381216?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ibukanov](https://github.com/ibukanov)**
_Friday Nov 28, 2014 at 07:43 GMT_

----

docker client is not fully statically linked. As long as one links against glibc, dynamic linking is unavoidable as glibc itself uses dlopen to load libraries at runtime. So golang compiler by default dynamically links against glibc and few other low-level system libraries while statically linking against the rest.

**Comment by crawford** [comment]
It doesn't make much sense to run the Docker client from within toolbox when it's available outside of that container. We aren't going to modify toolbox to do this.

**Comment by pdecat** [comment]
> It doesn't make much sense to run the Docker client from within toolbox when it's available outside of that container.

Hi @crawford, agreed that makes sense for the main docker client.
However, exposing the docker socket into the toolbox would allow to use third party tools such as [ctop](https://github.com/bcicen/ctop) from within toolbox.
