### ISSUE TITLE
README is inaccurate

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#898]
<a href="https://github.com/rbucker"><img src="https://avatars.githubusercontent.com/u/882595?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rbucker](https://github.com/rbucker)**
_Monday Mar 23, 2015 at 00:33 GMT_
_Originally opened as https://github.com/coreos/toolbox/issues/15_

---

I'm not sure what this is... since this project was created the toolbox has been deployed in the CoreOS image, however, the README suggests that the user should expect a particular user prompt PS1. In fact the default PS1, for me, is: `-bash-4.3#`.

One thing I noticed is hat the welcome message is pretty old.

Another is that the README is missing some critical explanation as to which container mounted which host volume. The fact that the example created a user `bob` seemed to overly confuse. While I could reverse engineer the code and create doc it's my frosted/lazy-side that hopes you'd document it for me since this is a cool piece of code.

**Comment by crawford** [comment]
This was fixed a while ago.
