### ISSUE TITLE
systemd-nspawn: invalid option -- 'c'

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#899]
<a href="https://github.com/rbucker"><img src="https://avatars.githubusercontent.com/u/882595?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rbucker](https://github.com/rbucker)**
_Saturday May 16, 2015 at 13:48 GMT_
_Originally opened as https://github.com/coreos/toolbox/issues/17_

---

I'm not a fan of 'mosh', however, mosh might fill a gap. cutting to the quick: The connection between my desktop(chromebook) and my development server (CoreOS running on GCE) is not reliable. Regardless of whether it's my network or because I'm moving between job sites. (have you ever seen those people who walk around with their laptops open as they go from one meeting to another?

I've logged into my CoreOS as a toolbox user. (a) only one toolbox connection at a time... probably need to launch an ssh server too (b) when I lose my connection I also lose the toolbox session. I strongly disagree with the security claims that the mosh team makes and while it's not worse than ssh it might help with the connection stuff. (unless toolbox was meant to be extremely transient)

When I launched my mosh session from my chromebook I got this:

Trying authentication type Password
Password: 
Bad response when running mosh-server: 'systemd-nspawn: invalid option -- 'c'

**Comment by brycechesternewman** [comment]
Howdy,
Was there a solution to this?
Steps to reproduce..
1. I setup a toolbox on coreos 835.10.0 via instructions in https://coreos.com/os/docs/latest/install-debugging-tools.html
2. yum install wireshark in toolbox session.
3. setup a user called bob via instructions https://coreos.com/os/docs/latest/install-debugging-tools.html
4. run locally ssh bob@10.21.145.208 "tshark -s0 -w - 'port 8080'" | wireshark -k -i -
bob@10.211.145.208's password: 
systemd-nspawn: invalid option -- 'c'

**Comment by paralin** [comment]
Any fix?

**Comment by dm0-** [comment]
I've submitted a fix at coreos/toolbox#39.
