### ISSUE TITLE
No access to /dev/tty on alpine or busybox toolbox images

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#900]
<a href="https://github.com/sporkmonger"><img src="https://avatars.githubusercontent.com/u/1778?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sporkmonger](https://github.com/sporkmonger)**
_Monday Jun 01, 2015 at 16:58 GMT_
_Originally opened as https://github.com/coreos/toolbox/issues/19_

---

There doesn't seem to be a writeable TTY device inside toolbox (using an Alpine image)?

Expected behavior:

```
$ echo 'test' > /dev/tty
test
```

Actual behavior:

```
$ echo 'test' > /dev/tty
-bash: /dev/tty: No such device or address
```

Works fine on fedora, but I can't think of a reason why it wouldn't work on a custom image?

**Comment by jonboulle** [comment]
<a href="https://github.com/sporkmonger"><img src="https://avatars.githubusercontent.com/u/1778?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sporkmonger](https://github.com/sporkmonger)**
_Monday Jun 01, 2015 at 17:05 GMT_

----

Worth noting that I can boot into the same exact image without the tty problem on the same box by just entering the docker command manually.

**Comment by jonboulle** [comment]
<a href="https://github.com/sporkmonger"><img src="https://avatars.githubusercontent.com/u/1778?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sporkmonger](https://github.com/sporkmonger)**
_Monday Jun 01, 2015 at 17:07 GMT_

----

Tried it with ubuntu too and that works, so may be alpine/busybox specific. Given that image size matters though, having it work with alpine still seems important.

**Comment by jonboulle** [comment]
<a href="https://github.com/sporkmonger"><img src="https://avatars.githubusercontent.com/u/1778?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sporkmonger](https://github.com/sporkmonger)**
_Monday Jun 01, 2015 at 17:10 GMT_

----

Confirming the problem also happens w/ busybox.

**Comment by jonboulle** [comment]
<a href="https://github.com/alexanderkiel"><img src="https://avatars.githubusercontent.com/u/822457?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alexanderkiel](https://github.com/alexanderkiel)**
_Wednesday Aug 26, 2015 at 16:40 GMT_

----

Same for me with alpine 3.2 in CoreOS 723.3.0

**Comment by crawford** [comment]
This is up to the distro to implement. We aren't going to be able to override what they've decided.
