### ISSUE TITLE
Use dashes instead of underscores when creating the machine name

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#902]
<a href="https://github.com/ianbytchek"><img src="https://avatars.githubusercontent.com/u/1086845?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ianbytchek](https://github.com/ianbytchek)**
_Thursday Oct 01, 2015 at 04:21 GMT_
_Originally opened as https://github.com/coreos/toolbox/issues/23_

----

For consistency sake, please use `-` not `_` https://github.com/coreos/toolbox/blob/bc6a8c4754c14e66c26fa21a48134a90a0592e9d/toolbox#L17

**Comment by ianbytchek** [comment]
I was wondering for a second what happened with issues over there :smile:

**Comment by crawford** [comment]
The original idea was that `_` are used to designate invalid characters and the `-` separates fields. Now that this is shipped, we can't change this without forcing everyone to redownload their toolboxes (because of the name change). I don't think this particular change is worth the trouble.
