### ISSUE TITLE
Azure: COREOS_PUBLIC_IPV4 is the IP of the load balancer, not an instance's interface

### ISSUE THREAD

**Issue by carmstrong** [coreos/bugs#904]
```console
core@deisNode0 ~ $ fleetctl list-units
UNIT                            MACHINE                         ACTIVE  SUB
deis-builder.service            f32ad131.../40.78.25.225        active  running
deis-controller.service         74abdfd6.../40.78.25.225        active  running
deis-database.service           dc1e9b98.../40.78.25.225        active  running
deis-logger.service             dc1e9b98.../40.78.25.225        active  running
deis-logspout.service           74abdfd6.../40.78.25.225        active  running
deis-logspout.service           dc1e9b98.../40.78.25.225        active  running
deis-logspout.service           f32ad131.../40.78.25.225        active  running
deis-publisher.service          74abdfd6.../40.78.25.225        active  running
deis-publisher.service          dc1e9b98.../40.78.25.225        active  running
deis-publisher.service          f32ad131.../40.78.25.225        active  running
deis-registry@1.service         f32ad131.../40.78.25.225        active  running
deis-router@1.service           74abdfd6.../40.78.25.225        active  running
deis-router@2.service           f32ad131.../40.78.25.225        active  running
deis-router@3.service           dc1e9b98.../40.78.25.225        active  running
deis-store-daemon.service       74abdfd6.../40.78.25.225        active  running
deis-store-daemon.service       dc1e9b98.../40.78.25.225        active  running
deis-store-daemon.service       f32ad131.../40.78.25.225        active  running
deis-store-gateway@1.service    74abdfd6.../40.78.25.225        active  running
deis-store-metadata.service     74abdfd6.../40.78.25.225        active  running
deis-store-metadata.service     dc1e9b98.../40.78.25.225        active  running
deis-store-metadata.service     f32ad131.../40.78.25.225        active  running
deis-store-monitor.service      74abdfd6.../40.78.25.225        active  running
deis-store-monitor.service      dc1e9b98.../40.78.25.225        active  running
deis-store-monitor.service      f32ad131.../40.78.25.225        active  running
deis-store-volume.service       74abdfd6.../40.78.25.225        active  running
deis-store-volume.service       dc1e9b98.../40.78.25.225        active  running
deis-store-volume.service       f32ad131.../40.78.25.225        active  running
```

```console
core@deisNode0 ~ $ cat /etc/environment
COREOS_PRIVATE_IPV4=10.0.0.5
COREOS_PUBLIC_IPV4=40.78.25.225
```

The public IP of all of these instances is different, of course, and is an actual IP. I can see this in the Azure console:

```console
$ azure vm show deisNode0 --resource-group charms|grep "Public IP address"
data:            Public IP address       :40.118.240.165
```

Unfortunately, it looks like whatever facility populates `/etc/environment` for Azure hosts is incorrectly inferring its public interface address.

**Comment by crawford** [comment]
Are these ASM or ARM machines?

**Comment by carmstrong** [comment]
> Are these ASM or ARM machines?

ARM. Our Azure contacts suggested that ASM is soon-to-be-deprecated, so we moved over.

**Comment by crawford** [comment]
OK, that makes sense. coreos-cloudinit was set up assuming machines would use ASM (the only option at the time). I'll have to poke around a bit more and figure out the best approach.

**Comment by carmstrong** [comment]
Thanks @crawford!

/cc @brunoterkaly @jimzim

**Comment by crawford** [comment]
We can't fix this in coreos-cloudinit but we will fix it in coreos-metadata.

**Comment by crawford** [comment]
Just for background, the three existing address types are VIP, DIP, and PIP (http://blogs.msdn.com/b/cloud_solution_architect/archive/2014/11/08/vips-dips-and-pips-in-microsoft-azure.aspx). coreos-cloudinit exposes the DIP as $private_ipv4 and VIP as $public_ipv4. Unfortunately, I don't have a good workaround for you. If there was an XML equivalent to jq, I could give you a one-liner.

Your other option is to let fleet determine its own public IP address. It will end up choosing the DIP, so you won't be able to access the machine from outside the virtual network.

**Comment by crawford** [comment]
After digging into this, I don't see a good way for an instance to figure out its PIP address. Hopefully, I'm missing something obvious. I've reached out to some of the folks on Azure for assistance.

**Comment by crawford** [comment]
Azure confirmed my findings :(  There is no way for us to access this information from within the VM.

@carmstrong your best bet is going to be to let fleet go ahead and figure out its address (which would be the same as specifying `$private_ipv4`). It should end up with the DIP address for the machine.

**Comment by carmstrong** [comment]
> your best bet is going to be to let fleet go ahead and figure out its address

Thanks for the investigation, @crawford!
