### ISSUE TITLE
grep -P doesn't work, pcregrep does

### ISSUE THREAD

**Issue by ianbytchek** [coreos/bugs#906]
Big admirer of perl regular expressions. Enjoy them most with grep. Couldn't help to notice, that `grep -P` on CoreOS fails with `grep: support for the -P option is not compiled into this --disable-perl-regexp binary`, yet `pcregrep` works just fine. If I recall correctly, they use the same library, why not enable this in grep too? Or am I confusing something?

**Comment by mischief** [comment]
it looks like pcre USE flag is turned off in https://github.com/coreos/coreos-overlay/blob/master/profiles/coreos/base/make.defaults#L19, but it's not clear why that is the case. perhaps @marineam knows?

**Comment by marineam** [comment]
@mischief inherited from ChromeOS to avoid unneeded libraries, but I'll bet something we ship has a non-optional dep on pcre and we are shipping it anyway. Need to check that though.

**Comment by marineam** [comment]
selinux and nmap (we only ship ncat though) pull in libpcre, so disabling it for grep doesn't gain anything.

**Comment by mischief** [comment]
@ianbytchek this feature will appear in coreos alpha soon, probably next week.

**Comment by ianbytchek** [comment]
Thanks guys!
