### ISSUE TITLE
systemd-networkd does not change mtu

### ISSUE THREAD

**Issue by lleszczu** [coreos/bugs#913]
According to https://coreos.com/blog/intro-to-systemd-networkd/ I need a .link file to change interface MTU, it does not work though. I did try to go through logs with journalctl but without any luck ( no entries related to .link files ).
That's the entry from my cloud config
```
  - name: eno1.link
    runtime: true
    content: |
      [Match]
      MACAddress=ec:f4:bb:d9:1e:68
      [Link]
      MTUBytes=8950

```

There is workaround: add custom udev rule and place it in /etc/udev/rules.d/10-net.rules
```
ACTION=="add", SUBSYSTEM=="net", KERNEL=="eno1", ATTR{mtu}="8950"

```
After that restart udev:
```
systemctl restart systemd-udev-trigger.service
```

**Comment by marineam** [comment]
You must prefix link files with a number, such as `50-eno1.link`. Otherwise the config doesn't match and the default 99-default.link is used.

**Comment by marineam** [comment]
This isn't a issue for .network files because our default is named zz-default.network, but 99-default.link is from upstream systemd not us so we didn't get to pick the name.

**Comment by marineam** [comment]
That doc goes to great lengths to never specify a file name for the example config, we should change that so users have a more explicit pattern to follow.

/cc @robszumski

**Comment by robszumski** [comment]
@marineam should this example https://coreos.com/os/docs/latest/network-config-with-networkd.html#static-networking not be called static.network?

**Comment by mischief** [comment]
@lleszczu has renaming your .link file with a numeric prefix solved the issue?

**Comment by lleszczu** [comment]
yes, it fixed the issue.

**Comment by webknjaz** [comment]
Hi,
I've got similar issue with `link` file, but the reason was, that `MACAddress` match doesn't work in `systemd` for some reason. So my workaround is to use `Path=` matching instead.

**Comment by shibumi** [comment]
@lleszczu does this setup still work for you? I tried your workaround and it doesn't work for me and seems like systemd-networkd is still unable to set the MTU without reboot
