### ISSUE TITLE
better story for ignition from rootfs

### ISSUE THREAD

**Issue by philips** [coreos/bugs#915]
David Anderson came up with a nice hack to make running igntion from bare metal with a mchine image:

> Ignition (currently) doesn't have a way to provide the ignition config on bare metal installs other than on the kernel commandline. This is fine when you're PXE-booting, but if you're installing to local disk, then it gets a bit icky.
> 
> Fortunately, OEM configs to the rescue! The OEM partition can provide a grub.cfg containing configuration snippets. Just drop a 'set linux_append="coreos.config.url=oem://ignition.json"' into that grub.cfg, and Ignition will load ignition.json from the OEM partition. Lovely!﻿

However, ideally ignition reads from some well-known disk partition on an image similar to the config-drive so that people using image based systems (vmware, openstack, etc) can utilize ignition without a smart PXE server.

https://plus.google.com/u/2/+DavidAndersonJC/posts/dwDGSjVVhov?cfem=1

**Comment by crawford** [comment]
That's is the intended use of the `oem` scheme.

I don't like the idea of Ignition _implicitly_ reading its config from a magic location. As for VMware and OpenStack, they are not yet supported by Ignition. Obviously, you can make it work by tweaking the image as David described, but it will be easier in the future.
