### ISSUE TITLE
Docker pull image stalls with coreos 829.0.0

### ISSUE THREAD

**Issue by stelund** [coreos/bugs#916]
In the end of pulling an image from local registry (v2) with the docker client the daemon stalls and does not continue. Pulling an image from global docker registry works fine, perhaps it is due to the image is not verified?

core@coreos-in-dev-01 ~ $ docker pull internal.com/redis   
Using default tag: latest
latest: Pulling from redis
3fdce1a9dbd6: Pull complete 
535df7603e66: Pull complete 
ab1ce38dad15: Pull complete 
698c67fb770e: Download complete 
698c67fb770e: Pulling fs layer 
d3a1f33e8a5a: Already exists 
c22013c84729: Already exists 
d74508fb6632: Already exists 
91e54dfb1179: Already exists 
7fef2d55af54: Already exists 
3d6a669c5685: Already exists 
88cd63f0930e: Already exists 
090a27e4ad76: Already exists 
2ce1c650afbd: Already exists 
5b429046987f: Already exists 
a44b54bd7d43: Already exists 
e2dafa828f3e: Already exists 

Then it stalls..

Aborting and retrying will say that it's already in progress. Other api calls seems ok. Tried to change storage-driver between btrfs and overlay and started from empty /var/lib/docker without success.

Journal is empty disregarding the pull-image requests.

Backing to beta channel was fine, so was 815.0.0. Maybe this is due to docker being built with go 1.5 or something else. In the changelog docker was not upgraded, so I'll file the bug here.

**Comment by MartinPodval** [comment]
+1. 

We have started to face same problems during last Friday - when we restarted our cluster so it gets  CoreOS (829). It's almost impossible to pull any "local" image, it almost always indefinitely hangs when working on last layer.

**Comment by stelund** [comment]
This is no longer an issue with CoreOS alpha (835.1.0).

**Comment by stelund** [comment]
Please close it @crawford

**Comment by stelund** [comment]
Back again in 835.2.0.

Maybe this is relevant
https://github.com/docker/docker/issues/16689#issuecomment-148589400

**Comment by crawford** [comment]
@stelund Are you sure that the issue went away with 835.1.0? The differences between that and 835.2.0 are pretty unrelated. The only one that seems related is https://github.com/coreos/coreos-overlay/pull/1593.

**Comment by crawford** [comment]
It would also be worth trying to repro with GOMAXPROCS set to 1.

**Comment by stelund** [comment]
@crawford I'm sad to say it's probably due to that I can't deterministic reproduce the error. We ran coreos alpha in our development cluster and saw the issue first with 829. We stepped down to beta and got the cluster healthy again, but one machine was left in alpha without working properly. When it got 835.1 (or perhaps even 835.0) it was OK again. Then when beta got 835.2 we had multiple failures again. Our workaround yesterday was to use docker 1.8.3 built by the docker team.

The GOMAXPROCS sounds plausible, but isn't that set to 1 already in docker 1.8.3? 

The comment I referred to mentions an earlier fix to build to go1.5 in docker 1.9.0-dev. But I am not able to find what pull request it could be. @hosh Can you perhaps try to recall?

**Comment by crawford** [comment]
@stelund we figured it must be a non-deterministic failure. You are correct about the GOMAXPROCS issue. It looks like [they are setting it to 1](https://github.com/docker/docker/blob/729c9a97822ebee2c978a322d37060454af6bc66/daemon/execdriver/native/init.go#L29).

It looks like we either need to find the upstream fix for go1.5 or revert back to go1.4.

**Comment by stelund** [comment]
There was one (https://github.com/docker/docker/pull/15703#issuecomment-150440664) for url+port parsing of ipv6 addresses, our dns should resolve ipv4 addresses so I don't fins that likely. We also use static ipv4 adresses on our coreos machines.

**Comment by hosh** [comment]
@crawford check this thread out: https://github.com/docker/docker/issues/16689#issuecomment-148589400

There is a fix for the Go 1.5 bug in 1.9.0 the last time I checked. Let me see if I can find the exact pull request.

**Comment by hosh** [comment]
@crawford @stelund found the PR:  https://github.com/docker/docker/pull/15545

**Comment by crawford** [comment]
@hosh thanks for digging that up. "it's magically fixed hanging on go1.5" doesn't install much confidence. I think we are going to roll back to go1.4 for the time being.

**Comment by hosh** [comment]
@crawford works for me.

Between this and the overlayfs over allocation patch in, I feel a lot better about putting my cluster into production.

**Comment by stelund** [comment]
@hosh thank you for finding it! Sorry for my late reply.

**Comment by stelund** [comment]
@crawford we haven't seen this issue since the 835.4.0 update last week. Great work, thank you!

**Comment by picardrulez** [comment]
I'm still having this issue with 835.4.0

**Comment by mischief** [comment]
@picardrulez can you provide more information?

**Comment by picardrulez** [comment]
@mischief this might be somewhat unrelated actually.  I've been having an issue with docker pull hanging once it pulls one of the last layers but it appears to only happen when I'm running it through fleet.

**Comment by picardrulez** [comment]
@mischief switching to the alpha release channel appears to have fixed the issue.
