### ISSUE TITLE
systemd: make systemd-journal-upload and systemd-journal-remote work

### ISSUE THREAD

**Issue by kayrus** [coreos/bugs#919]
/cc @crawford @marineam @brianredbeard 

At the moment it is not easy to configure this chain (journal-upload -> journal-remote). There are several issues I've already faced:

* default systemd-journal-upload.service runs under User=systemd-journal-upload and it fails because of non-existing directory `Cannot create parent directory of state file /var/lib/systemd/journal-upload/state: Permission denied`

* systemd-journal-remote doesn't have build-int systemd service file - had to create it
* systemd-journal-remote can listen raw tcp socket, but systemd-journal-upload can not work with raw sockets
* systemd-journal-remote can not listen http/https socket, but systemd-journal-upload requires http socket. systemd-journal-remote returns following messages:

```
Oct 13 15:52:37 coreos1 systemd-journal-remote[2520]: Full config: SplitMode=host Key=n/a Cert=n/a Trust=n/a
Oct 13 15:52:37 coreos1 systemd-journal-remote[2520]: Received 1 descriptors
Oct 13 15:52:37 coreos1 systemd-journal-remote[2520]: Received a listening socket (fd:3)
Oct 13 15:52:37 coreos1 systemd-journal-remote[2520]: Failed to start µhttp daemon
Oct 13 15:52:37 coreos1 systemd-journal-remote[2520]: Failed to register socket (fd:3): Invalid argument
```

Here are custom systemd units:

```
cat /etc/systemd/system/systemd-journal-upload.service.d/10-debug.conf 
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
Group=systemd-journal
ExecStart=
ExecStart=/usr/lib/systemd/systemd-journal-upload --save-state --url=192.168.122.164:19532
```

```
cat systemd-journal-remote.service
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Journal Remote Sink Service
Requires=systemd-journal-remote.socket

[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
ExecStart=/usr/lib/systemd/systemd-journal-remote --listen-http=-3 --output=/var/log/journal/remote/
WatchdogSec=3min

[Install]
Also=systemd-journal-remote.socket
```

```
cat systemd-journal-remote.socket 
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Journal Remote Sink Socket

[Socket]
ListenStream=19532

[Install]
WantedBy=sockets.target
```

I still working on getting them to work.

**Comment by mischief** [comment]
a test in kola for exporting journald logs might be useful.

**Comment by kayrus** [comment]
Spent almost whole day today with this issue.

Had to compile my own `libmicrohttpd.so.10.29.0` with additional debug messages. With my library everything works fine. So it seems the problem is with our built-in `libmicrohttpd`.

Tried to figure out what is wrong and probably it is this bug https://bugs.gentoo.org/show_bug.cgi?id=550718

But I've tried to compile lib with ebuild flags:

```
./configure CFLAGS='-Os' --enable-bauth --enable-dauth --disable-spdy --enable-curl --enable-messages --enable-messages --enable-postprocessor
```

It worked even with them... So I have no idea what is wrong with built-in lib. Probably custom CFLAGS, etc.

**Comment by mischief** [comment]
@kayrus ok, let's bump net-libs/libmicrohttpd.

**Comment by kayrus** [comment]
@mischief can you compile it, upload somewhere and I'll test it.

**Comment by kayrus** [comment]
@mischief our problem is --disable-epoll. `journal-remote.c` uses `MHD_USE_EPOLL_LINUX_ONLY` flag. https://github.com/systemd/systemd/blob/master/src/journal-remote/journal-remote.c#L651

I was confused by working `systemd-journal-gatewayd`, but now I understand why. It doesn't have that flag, only `MHD_USE_POLL`: https://github.com/systemd/systemd/blob/master/src/journal-remote/journal-gatewayd.c#L1027

Fixed here https://github.com/coreos/coreos-overlay/pull/1587

**Comment by kayrus** [comment]
In addition, HTTPS doesn't work because ssl use-flag was disabled.

**Comment by marineam** [comment]
Sounds like systemd is missing a use flag dep. We should file a bug
upstream in gentoo if it hasn't already been fixed there.

**Comment by kayrus** [comment]
I've opened another bug: https://github.com/coreos/bugs/issues/927

**Comment by mischief** [comment]
the unit files systemd-journal-remote.{socket,service} and /var/log/journal/remote/ are missing because we do not have gnutls.

see https://github.com/systemd/systemd/blob/master/Makefile.am#L3827

**Comment by mischief** [comment]
i don't think this is entirely resolved yet.

**Comment by kayrus** [comment]
linking https://github.com/coreos/systemd/pull/22
