### ISSUE TITLE
No way to override cloudinit's OEM discovery on first boot

### ISSUE THREAD

**Issue by xrl** [coreos/bugs#920]
My coreos host is intended to run on an OpenStack installation I do not control. Our OpenStack does not fill in the metadata value for private_ipv4 so when first booting the nodes will register a null IP with the discovery service. I can get the proper private_ipv4 by using:

```
coreos:
  units:
    - name: oem-cloudinit.service
      runtime: yes
      content: |
        [Unit]
        Description=Cloudinit from EC2-style metadata

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/coreos-cloudinit --from-ec2-metadata=http://169.254.169.254/
```

but no combination of "command: start", "command: restart", etc will have it take hold on first boot. And by then the etcd2 daemon has tried registered the node and used the null private_ipv4. So it's a real mess.

  * Can we disable sending null discovery URLs to the discovery service?
  * How can we provide a `coreos-cloudinit --from-ec2-metadata=http://169.254.169.254/` on the first boot?

**Comment by crawford** [comment]
Unfortunately, you will need to ignore the IP addresses coreos-cloudinit gives you and determine them yourself. You can use an approach similar to [this](https://gist.github.com/crawford/3cd24677521f940f842a). You _might_ also be able to use the EC2 image on OpenStack, though, your mileage may vary (I haven't tested it directly).

**Comment by xrl** [comment]
Could we change the `#cloudinit` at the top of the yaml file to be more like a shebang, could be a good spot to provide runtime args?

```
#cloud-config --from-ec2-metadata=http://169.254.169.254/
[[ SNIP ]]
```

**Comment by crawford** [comment]
The userdata can begin with a shebang and coreos-cloudinit will run it.

**Comment by xrl** [comment]
I don't want to evaluate a script, I would like to stick with the yaml file. But can I provide arguments to the `core-cloudinit` invoked?

**Comment by crawford** [comment]
No. coreos-cloudinit fetches the config, so by the time it fetches the config, its arguments have already been provided.

**Comment by xrl** [comment]
Good point. This is an unfortunate situation.

**Comment by xrl** [comment]
OK, I hacked on this until it worked. Your example was only for etcd, I've got it working for etcd2: https://gist.github.com/xrl/d1d7ba9dd85dd965cd58 . This could be useful to detail in the wiki or something.

**Comment by crawford** [comment]
This class of problem falls away if you use Ignition. We are going to start migrating everyone over to Ignition once it is supported on more platforms.
