### ISSUE TITLE
etcd2 options are out of sync

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#922]
Glancing through the etcd 2.2.0 release, I noticed that WAL_DIR was added to etcd but was not added to coreos-cloudinit. There may be other options that are out of sync; I stopped looking after I found the first one.

**Comment by xiang90** [comment]
@crawford Sorry about that. I now looked into cloudinit, and found out it is versioned itself.

When we release a new version of etcd, we cannot simply update cloudinit. So can you please notify etcd-team when you want to update etcd/cloudinit in any CoreOS channels? Then we can look if that pair of etcd/cloudinit matches?

**Comment by xiang90** [comment]
@crawford Also looking more into the actual functionality, I do not think I fully understand why do we copy etcd flags into cloudinit at the first place.

**Comment by crawford** [comment]
@xiang90 I think it would make more sense if you submitted a PR against coreos-cloudinit either when you add the flag to etcd or when you release a new version. Then we can pull in that change and bump coreos-cloudinit when we bump etcd. Does that sound reasonable?

We have the flags in coreos-cloudinit so that we can validate the configs (http://coreos.com/validate). We need to know all of the possible flags so that we can warn against invalid values or unrecognized keys.

**Comment by jonboulle** [comment]
I suggest making a coreos-cloudinit check part of the etcd release process.

**Comment by xiang90** [comment]
@jonboulle @crawford After talking this offline, we will put do the following:

1. cut a release of etcd
2. send a pull request to cloudinit. 

The OS team will review the changes and merge it when appropriate. (For example, when put etcd into a version of CoreOS itself).

**Comment by crawford** [comment]
That sounds great!

**Comment by crawford** [comment]
https://github.com/coreos/coreos-cloudinit/pull/402

**Comment by crawford** [comment]
What about `strict-reconfig-check`?

**Comment by xiang90** [comment]
@crawford That is on master branch, it is not a released version of etcd. etcd has a branch for each releases. [https://github.com/coreos/etcd/blob/release-2.2/Documentation/configuration.md]

We will follow this procedure as I mentioned above.
```
cut a release of etcd
send a pull request to cloudinit.
```

**Comment by crawford** [comment]
Woops, you're right.
