### ISSUE TITLE
Update btrfs progs to latest release

### ISSUE THREAD

**Issue by f0** [coreos/bugs#923]
please update btrfs progs to the latest release, there are some nice fixes e.g capabilities not lost when using send/receive

**Comment by mischief** [comment]
fixed by coreos/portage-stable#272

**Comment by mischief** [comment]
sorry, not fixed yet. we will have 4.0.1 in the next alpha release, but have not moved to 4.1+ yet.

**Comment by mischief** [comment]
hey @f0, btrfs-progs 4.2.2 will appear in the next alpha (898.0.0). thanks for being patient :-)

**Comment by f0** [comment]
@mischief   thx
