### ISSUE TITLE
cloud-config-validator should be versioned

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#924]
The validator @ https://coreos.com/validate/ needs to be versioned against the coreos-cloudinit that it reflects. 

(It would be amazing if we could have three versions of it reflecting the versions of coreos-cloudinit in alpha/beta/stable, but maybe I'm dreamin')

Also, perhaps the project could be renamed to "coreos-cloud-config-validator" to be consistent with the coreos.com documentation and the repository README (I note that it was only just renamed from [coreos-cloudinit-validate](https://github.com/coreos/coreos-userdata-validator/commit/2c8d44c14d53787eadbeb9be7390450eb075aba7), but also that the repo redirects from github.com/coreos/coreos-cloudinit-validat**or** - why have one name when you can have four)

**Comment by robszumski** [comment]
Submitting the provided cloud-config to a different endpoint would be fairly easy on the frontend, but I'd worry about the ops overhead of running those additional services.

**Comment by crawford** [comment]
coreos-cloudinit has been deprecated in favor of Ignition which already versions it's configs.
