### ISSUE TITLE
Update ixgbe driver to the latest release

### ISSUE THREAD

**Issue by aemr3** [coreos/bugs#925]
Current version of ixgbe driver on alpha release is 4.0.1-k. I have a server on OVH which has Supermicro motherboard. Network card is Intel X552/X557-AT 10GBASE-T. This network card is never recognized on stable release. In alpha release it is recognized but ip link is always down. I couldn't make it work. So I have compiled latest driver for kernel 4.2.2 and used driver via insmod. And voila! It works as expected. So please update ixgbe driver to the latest relase 4.1.5 on next alpha release. Thank you.

**Comment by mathieu-lacage** [comment]
I tried to do the same and compiled the latest (4.1.5) driver from http://sourceforge.net/projects/e1000/files/ixgbe%20stable/4.1.5/ but it is unclear to me how coreos expects me to add this driver to my installation: any advice on where I should drop the resulting file ?

**Comment by aemr3** [comment]
/usr is read only partition. You cannot write there. I have copied it to my home folder. And using this service to load it from there:

```
[Unit]
Description=Fix network module
Before=systemd-networkd.service
[Service]
Type=oneshot
ExecStartPre=-/usr/sbin/modprobe vxlan
ExecStartPre=-/usr/sbin/rmmod ixgbe
ExecStart=/usr/sbin/insmod /home/core/ixgbe.ko
[Install]
WantedBy=multi-user.target
```

**Comment by andrewvy** [comment]
:+1:. I'm running into this same issue, it would be awesome to have this be upgraded.

**Comment by aemr3** [comment]
@andrewvy @mathieu-lacage hi, current CoreOS alpha channel fixes this problem.

**Comment by felixkrohn** [comment]
Awesome - can you already predict a date when it will be available in the stable tree?
We have a lot of customers who would like to run (stable) CoreOS on high-end servers with this network interface.

**Comment by robszumski** [comment]
@felixkrohn about 4 to 6 weeks is a rough guess

**Comment by shenhequnying** [comment]
@aemr3 hello dude, how you compile the driver with coreos kernel ?
i can not find the kernel-headers in coreos version:835.9.0
thank you !

**Comment by aemr3** [comment]
@shenhequnying Hi, you can switch to CoreOS Beta release. Beta release fixes this problem. Don't need to compile driver. Right know I am using beta release with no custom drivers.

**Comment by shenhequnying** [comment]
@aemr3  not this problem, i just want to compile a driver module in coreos.

**Comment by shenhequnying** [comment]
@aemr3  can i sent mail to you ?
