### ISSUE TITLE
Etcd crashed unexpectedly: panic: assertion failed: leader.elected.at.same.term

### ISSUE THREAD

**Issue by litch** [coreos/bugs#93]
My (4-node Rackspace cloud) cluster went down overnight - at 10:44 on Jul 25.  One of the machines (infra4-1) seems to have had an etcd crash (there's like a 600 line stack trace there).  
 
```
Jul 25 10:44:46 infra4-1 etcd[731]: [etcd] Jul 25 10:44:46.915 INFO      | Rejoin with http://127.0.0.1:7001 instead of http://10.208.224.192:7001 from 51749d6d0e8645c7adf7b0fcc552e345
Jul 25 10:44:46 infra4-1 etcd[731]: panic: assertion failed: leader.elected.at.same.term.3
```
 
I also found this messaging odd: `Rejoin with http://127.0.0.1:7001 instead of http://10.208.224.192:7001 from 51749d6d0e8645c7a`.  The .244.192 ip address corresponds to infra4-2.
 
Attached are the etcd logs for the machines:  https://gist.github.com/litch/8906a5e404f0abf121c7
 
I've tried restarting all of the machines, as well as restarting etcd, to no avail.

**Comment by yichengq** [comment]
The panic has been explained and solved in goraft/raft#240.

PS, etcd 2.x rewrites the internal raft implementation and is more stable, feel free to give it a try.
