### ISSUE TITLE
Remove hard dependency on /dev/disk/by-label/OEM

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#933]
PXE-booted images won't have this device and will fail to boot. This could be made a soft dependency or, better yet, have a generator determine if it is needed.

**Comment by crawford** [comment]
I think it would be sufficient to add a condition checking for the existence of `/usr/share/oem/oem-release` before it attempts to mount `/usr/share/oem` and then add `/usr/share/oem/oem-release` to the PXE images.

**Comment by marineam** [comment]
This is sort of worked around in the main system by providing a stub .device file that adds a condition to skip the device. In the initrd we can go with my earlier suggestion of adding coreos.oem=foo too the cmdline, thus dropping the need to mount the OEM in the initrd unless it is explicitly requested via the oem url scheme.

**Comment by crawford** [comment]
Right. I forgot about that. I think we can just switch to that scheme and drop the oem-release file entirely.

**Comment by marineam** [comment]
And thank god ignition only runs on first boot so we can make the switch without worrying about compatibility in upgrades! ;-)

**Comment by crawford** [comment]
It's almost like we thought it through this time!

**Comment by dmeiser** [comment]
Hey guys, I am still getting this on 845.0.0, which claims that it closes this bug.  It boots if I do nothing, but if I force a first run, I get the same dependency error.

**Comment by crawford** [comment]
@dmeiser you are attempting to PXE-boot 845.0.0, right? Can you provide a snippet of the log?

**Comment by dmeiser** [comment]
I was getting the same issue, now I'm seeing a new issue.  I'm using an
iDRAC, I'll go to the DC and check it in-person tomorrow.

**Comment by dmeiser** [comment]
So, I went over to the datacenter, hooked up a crash cart and...  no USB keyboard.  I'll file a bug against that.

**Comment by dmeiser** [comment]
Also, this is very interesting: I have root specified (though I don't want to specify root, it's just one of the iterations I'm test) and rebooted the machine, and walked away (forgetting root was specified).  When booting into the existing environment, I have keyboard.  If I remove the root option, I still have no keyboard.  I've tried this several times.
