### ISSUE TITLE
Cluster starting unhealthy on CoreOS alpha (835.1.0)

### ISSUE THREAD

**Issue by Zapadlo** [coreos/bugs#936]
Tried spinning up a cluster 5 - 6 times with various conf for initial number of members, timeouts for etcd2, most of etcd2 logs look like this:

```
-- Logs begin at Tue 2015-10-20 15:28:07 UTC, end at Tue 2015-10-20 15:37:43 UTC. --
Oct 20 15:28:46 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: Starting etcd2...
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://172.24.67.222:2379,http://172.24.67.222:4001
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/27ec448294cfd99ecb2efa7fa236d130
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=3000
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: recognized and used environment variable ETCD_HEARTBEAT_INTERVAL=300
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.24.67.222:2380
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://172.24.67.222:2380,http://172.24.67.222:7001
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: recognized and used environment variable ETCD_NAME=5d2095e3c4af4ab0a1b319197527799b
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: etcd Version: 2.2.0
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: Git SHA: e4561dd
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: Go Version: go1.5.1
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: Go OS/Arch: linux/amd64
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: listening for peers on http://172.24.67.222:2380
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: listening for peers on http://172.24.67.222:7001
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: listening for client requests on http://0.0.0.0:2379
Oct 20 15:28:49 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: listening for client requests on http://0.0.0.0:4001
Oct 20 15:28:51 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: found self e8e8214d7021c972 in the cluster
Oct 20 15:28:51 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: found 1 peer(s), waiting for 2 more
Oct 20 15:29:16 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: found peer bfb257261d8106b9 in the cluster
Oct 20 15:29:16 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: found 2 peer(s), waiting for 1 more
Oct 20 15:30:16 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: error #0: client: etcd member https://discovery.etcd.io returns server error [Gateway Timeout]
Oct 20 15:30:16 ip-172-24-67-222.eu-west-1.compute.internal etcd2[833]: waiting for other nodes: error connecting to https://discovery.etcd.io, retrying in 2s
Oct 20 15:30:17 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: etcd2.service: Start operation timed out. Terminating.
Oct 20 15:30:17 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: etcd2.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 20 15:30:17 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: Failed to start etcd2.
Oct 20 15:30:17 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: etcd2.service: Unit entered failed state.
Oct 20 15:30:17 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: etcd2.service: Failed with result 'exit-code'.
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: Stopped etcd2.
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: Starting etcd2...
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://172.24.67.222:2379,http://172.24.67.222:4001
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/27ec448294cfd99ecb2efa7fa236d130
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=3000
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: recognized and used environment variable ETCD_HEARTBEAT_INTERVAL=300
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.24.67.222:2380
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://172.24.67.222:2380,http://172.24.67.222:7001
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: recognized and used environment variable ETCD_NAME=5d2095e3c4af4ab0a1b319197527799b
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: etcd Version: 2.2.0
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: Git SHA: e4561dd
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: Go Version: go1.5.1
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: Go OS/Arch: linux/amd64
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: the server is already initialized as member before, starting as etcd member...
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: listening for peers on http://172.24.67.222:2380
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: listening for peers on http://172.24.67.222:7001
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: listening for client requests on http://0.0.0.0:2379
Oct 20 15:30:27 ip-172-24-67-222.eu-west-1.compute.internal etcd2[938]: listening for client requests on http://0.0.0.0:4001
Oct 20 15:30:28 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Oct 20 15:30:28 ip-172-24-67-222.eu-west-1.compute.internal systemd[1]: Failed to start etcd2.
```
and keep repeating.

Another host:
```
Oct 20 15:38:20 ip-172-24-58-39.eu-west-1.compute.internal etcd2[835]: 5b34a53a8df3c62a is starting a new election at term 109
Oct 20 15:38:20 ip-172-24-58-39.eu-west-1.compute.internal etcd2[835]: 5b34a53a8df3c62a became candidate at term 110
Oct 20 15:38:20 ip-172-24-58-39.eu-west-1.compute.internal etcd2[835]: 5b34a53a8df3c62a received vote from 5b34a53a8df3c62a at term 110
Oct 20 15:38:20 ip-172-24-58-39.eu-west-1.compute.internal etcd2[835]: 5b34a53a8df3c62a [logterm: 1, index: 3] sent vote request to bfb257261d8106b9 at term 110
Oct 20 15:38:20 ip-172-24-58-39.eu-west-1.compute.internal etcd2[835]: 5b34a53a8df3c62a [logterm: 1, index: 3] sent vote request to e8e8214d7021c972 at term 110
Oct 20 15:38:22 ip-172-24-58-39.eu-west-1.compute.internal etcd2[835]: failed to dial bfb257261d8106b9 on stream MsgApp v2 (net/http: transport closed before response was received)
Oct 20 15:38:22 ip-172-24-58-39.eu-west-1.compute.internal etcd2[835]: failed to dial bfb257261d8106b9 on stream Message (read tcp 172.24.58.39:47403->172.24.155.123:2380: read: connection reset by peer)
Oct 20 15:38:22 ip-172-24-58-39.eu-west-1.compute.internal etcd2[835]: failed to dial bfb257261d8106b9 on stream Message (dial tcp 172.24.155.123:2380: getsockopt: connection refused)
Oct 20 15:38:22 ip-172-24-58-39.eu-west-1.compute.internal etcd2[835]: failed to dial bfb257261d8106b9 on stream MsgApp v2 (dial tcp 172.24.155.123:2380: getsockopt: connection refused)
```

~~I'm spinning up the cluster with ansible, where hosts come up one by one sequentially, does that matter?~~
It doesn't, I switched back to stable (766.4) with the same settings and cluster came up healthy.

**Comment by mischief** [comment]
@Zapadlo can you collect logs using `journalctl -t etcd2` instead of `-u etcd2`? the journal sometimes misses logs if you specify just a unit, but using the syslog label will help.

**Comment by Zapadlo** [comment]
@mischief Actually most of the clusters I set up today started up successfully, had my first failure, but `journalctl -t etcd2` gives me:
```
core@ip-172-24-144-171 ~ $ sudo journalctl -t etcd2
-- No entries --
```
Ta!

**Comment by mischief** [comment]
@Zapadlo, sorry, it looks like a recent change in the etcd2 logging code has caused it to stop tagging log messsages with a syslog identifier. can you gather logs with `journalctl _EXE=/usr/bin/etcd2`?

**Comment by Zapadlo** [comment]
Here are logs for 5/5 machines, using default discovery url, so only 3 should be members:

https://pastee.org/9h48n
https://pastee.org/v8y3p
https://pastee.org/b2775
https://pastee.org/ppm4b
https://pastee.org/sqsja

Thanks!

**Comment by egbertp** [comment]
I experienced exactly the same problem as @Zapadlo . 
I've started 4 CoreOS 835.2.0 machines on the DigitalOcean cloud.  I've used a discovery token with the size of 4, so all machines should be members of the cluster. I'll past my journalctl logs in a minute

**Comment by egbertp** [comment]
https://discovery.etcd.io/9c24eea1ead48b1c7bc629f1e0f8f1c5

https://pastee.org/z49jg
https://pastee.org/uphww
https://pastee.org/v48vc
https://pastee.org/fzekj

**Comment by ofekes01** [comment]
I got the same issue on 835.8.0
I try to form a cluster of 5 node but only the last 3 node join the cluster. If I change the node number to 3 all works ok,

The logs from node 1.

journalctl -u etcd2.service
-- Logs begin at Thu 2015-12-03 09:23:26 UTC, end at Thu 2015-12-03 10:46:06 UTC. --
Dec 03 09:24:00 core-01 systemd[1]: Starting etcd2...
Dec 03 09:24:00 core-01 etcd2[1307]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://192.168.55.101:2379
Dec 03 09:24:00 core-01 etcd2[1307]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Dec 03 09:24:00 core-01 etcd2[1307]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/9c5659ac5eaaa0ba4ebfc8f345e86ff0
Dec 03 09:24:00 core-01 etcd2[1307]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.55.101:2380
Dec 03 09:24:00 core-01 etcd2[1307]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Dec 03 09:24:00 core-01 etcd2[1307]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://192.168.55.101:2380,http://192.168.55.101:7001
Dec 03 09:24:00 core-01 etcd2[1307]: recognized and used environment variable ETCD_NAME=07595d39e56b4130bf305450b8e3eebf
Dec 03 09:24:00 core-01 etcd2[1307]: etcd Version: 2.2.0
Dec 03 09:24:00 core-01 etcd2[1307]: Git SHA: e4561dd
Dec 03 09:24:00 core-01 etcd2[1307]: Go Version: go1.4.2
Dec 03 09:24:00 core-01 etcd2[1307]: Go OS/Arch: linux/amd64
Dec 03 09:24:00 core-01 etcd2[1307]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Dec 03 09:24:00 core-01 etcd2[1307]: listening for peers on http://192.168.55.101:2380
Dec 03 09:24:00 core-01 etcd2[1307]: listening for peers on http://192.168.55.101:7001
Dec 03 09:24:00 core-01 etcd2[1307]: listening for client requests on http://0.0.0.0:2379
Dec 03 09:24:00 core-01 etcd2[1307]: listening for client requests on http://0.0.0.0:4001
Dec 03 09:24:02 core-01 etcd2[1307]: found self 130edd7eae6fc420 in the cluster
Dec 03 09:24:02 core-01 etcd2[1307]: found 1 peer(s), waiting for 4 more
Dec 03 09:24:41 core-01 etcd2[1307]: found peer d564fcd3338bbcb9 in the cluster
Dec 03 09:24:41 core-01 etcd2[1307]: found 2 peer(s), waiting for 3 more
Dec 03 09:25:22 core-01 etcd2[1307]: found peer b576321308d11105 in the cluster
Dec 03 09:25:22 core-01 etcd2[1307]: found 3 peer(s), waiting for 2 more
Dec 03 09:25:30 core-01 systemd[1]: etcd2.service: Start operation timed out. Terminating.
Dec 03 09:25:30 core-01 systemd[1]: etcd2.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 03 09:25:30 core-01 systemd[1]: Failed to start etcd2.
Dec 03 09:25:30 core-01 systemd[1]: etcd2.service: Unit entered failed state.
Dec 03 09:25:30 core-01 systemd[1]: etcd2.service: Failed with result 'exit-code'.
Dec 03 09:25:40 core-01 systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.


The log from node 5

 journalctl -lu etcd2.service
-- Logs begin at Thu 2015-12-03 09:26:23 UTC, end at Thu 2015-12-03 10:48:17 UTC. --
Dec 03 09:26:39 core-05 systemd[1]: Starting etcd2...
Dec 03 09:26:39 core-05 etcd2[1120]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://192.168.55.105:2379
Dec 03 09:26:39 core-05 etcd2[1120]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Dec 03 09:26:39 core-05 etcd2[1120]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/9c5659ac5eaaa0ba4ebfc8f345e86ff0
Dec 03 09:26:39 core-05 etcd2[1120]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.55.105:2380
Dec 03 09:26:39 core-05 etcd2[1120]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Dec 03 09:26:39 core-05 etcd2[1120]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://192.168.55.105:2380,http://192.168.55.105:7001
Dec 03 09:26:39 core-05 etcd2[1120]: recognized and used environment variable ETCD_NAME=a89283615c2348b0859da60e7a1ace5d
Dec 03 09:26:39 core-05 etcd2[1120]: etcd Version: 2.2.0
Dec 03 09:26:39 core-05 etcd2[1120]: Git SHA: e4561dd
Dec 03 09:26:39 core-05 etcd2[1120]: Go Version: go1.4.2
Dec 03 09:26:39 core-05 etcd2[1120]: Go OS/Arch: linux/amd64
Dec 03 09:26:39 core-05 etcd2[1120]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Dec 03 09:26:39 core-05 etcd2[1120]: listening for peers on http://192.168.55.105:2380
Dec 03 09:26:39 core-05 etcd2[1120]: listening for peers on http://192.168.55.105:7001
Dec 03 09:26:39 core-05 etcd2[1120]: listening for client requests on http://0.0.0.0:2379
Dec 03 09:26:39 core-05 etcd2[1120]: listening for client requests on http://0.0.0.0:4001
Dec 03 09:26:42 core-05 etcd2[1120]: found peer 130edd7eae6fc420 in the cluster
Dec 03 09:26:42 core-05 etcd2[1120]: found peer d564fcd3338bbcb9 in the cluster
Dec 03 09:26:42 core-05 etcd2[1120]: found peer b576321308d11105 in the cluster
Dec 03 09:26:42 core-05 etcd2[1120]: found peer c0f59ecc34579a21 in the cluster
Dec 03 09:26:42 core-05 etcd2[1120]: found self 2ee4f9dde1ea58ee in the cluster
Dec 03 09:26:42 core-05 etcd2[1120]: found 5 needed peer(s)
Dec 03 09:26:42 core-05 etcd2[1120]: name = a89283615c2348b0859da60e7a1ace5d
Dec 03 09:26:42 core-05 etcd2[1120]: data dir = /var/lib/etcd2
Dec 03 09:26:42 core-05 etcd2[1120]: member dir = /var/lib/etcd2/member
Dec 03 09:26:42 core-05 etcd2[1120]: heartbeat = 100ms
Dec 03 09:26:42 core-05 etcd2[1120]: election = 1000ms
Dec 03 09:26:42 core-05 etcd2[1120]: snapshot count = 10000
Dec 03 09:26:42 core-05 etcd2[1120]: discovery URL= https://discovery.etcd.io/9c5659ac5eaaa0ba4ebfc8f345e86ff0
Dec 03 09:26:42 core-05 etcd2[1120]: advertise client URLs = http://192.168.55.105:2379
Dec 03 09:26:42 core-05 etcd2[1120]: initial advertise peer URLs = http://192.168.55.105:2380
Dec 03 09:26:42 core-05 etcd2[1120]: initial cluster = a89283615c2348b0859da60e7a1ace5d=http://192.168.55.105:2380
Dec 03 09:26:42 core-05 etcd2[1120]: starting member 2ee4f9dde1ea58ee in cluster 9b7717754c3d413a
Dec 03 09:26:42 core-05 etcd2[1120]: 2ee4f9dde1ea58ee became follower at term 0
Dec 03 09:26:42 core-05 etcd2[1120]: newRaft 2ee4f9dde1ea58ee [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Dec 03 09:26:42 core-05 etcd2[1120]: 2ee4f9dde1ea58ee became follower at term 1
Dec 03 09:26:42 core-05 etcd2[1120]: starting server... [version: 2.2.0, cluster version: to_be_decided]
Dec 03 09:26:42 core-05 etcd2[1120]: failed to dial 130edd7eae6fc420 on stream Message (dial tcp 192.168.55.101:2380: connection refused)
Dec 03 09:26:42 core-05 etcd2[1120]: failed to dial 130edd7eae6fc420 on stream MsgApp v2 (dial tcp 192.168.55.101:2380: connection refused)
Dec 03 09:26:42 core-05 etcd2[1120]: added member 130edd7eae6fc420 [http://192.168.55.101:2380] to cluster 9b7717754c3d413a
Dec 03 09:26:42 core-05 etcd2[1120]: added local member 2ee4f9dde1ea58ee [http://192.168.55.105:2380] to cluster 9b7717754c3d413a
Dec 03 09:26:42 core-05 systemd[1]: Started etcd2.
Dec 03 09:26:42 core-05 etcd2[1120]: added member b576321308d11105 [http://192.168.55.103:2380] to cluster 9b7717754c3d413a
Dec 03 09:26:42 core-05 etcd2[1120]: added member c0f59ecc34579a21 [http://192.168.55.104:2380] to cluster 9b7717754c3d413a
Dec 03 09:26:42 core-05 etcd2[1120]: 2ee4f9dde1ea58ee [term: 1] received a MsgVote message with higher term from b576321308d11105 [term: 2]
Dec 03 09:26:42 core-05 etcd2[1120]: 2ee4f9dde1ea58ee became follower at term 2
Dec 03 09:26:42 core-05 etcd2[1120]: 2ee4f9dde1ea58ee [logterm: 1, index: 5, vote: 0] voted for b576321308d11105 [logterm: 1, index: 5] at term 2
Dec 03 09:26:42 core-05 etcd2[1120]: 2ee4f9dde1ea58ee [logterm: 1, index: 5, vote: b576321308d11105] rejected vote from c0f59ecc34579a21 [logterm: 1, index: 5] at te
Dec 03 09:26:42 core-05 etcd2[1120]: failed to dial d564fcd3338bbcb9 on stream Message (dial tcp 192.168.55.102:2380: connection refused)
Dec 03 09:26:42 core-05 etcd2[1120]: failed to dial d564fcd3338bbcb9 on stream MsgApp v2 (dial tcp 192.168.55.102:2380: connection refused)
Dec 03 09:26:42 core-05 etcd2[1120]: the connection with c0f59ecc34579a21 became active
Dec 03 09:26:42 core-05 etcd2[1120]: added member d564fcd3338bbcb9 [http://192.168.55.102:2380] to cluster 9b7717754c3d413a
Dec 03 09:26:42 core-05 etcd2[1120]: the connection with b576321308d11105 became active
Dec 03 09:26:43 core-05 etcd2[1120]: 2ee4f9dde1ea58ee [term: 2] received a MsgVote message with higher term from b576321308d11105 [term: 3]
Dec 03 09:26:43 core-05 etcd2[1120]: 2ee4f9dde1ea58ee became follower at term 3
Dec 03 09:26:43 core-05 etcd2[1120]: 2ee4f9dde1ea58ee [logterm: 1, index: 5, vote: 0] voted for b576321308d11105 [logterm: 1, index: 5] at term 3
Dec 03 09:26:43 core-05 etcd2[1120]: raft.node: 2ee4f9dde1ea58ee elected leader b576321308d11105 at term 3
Dec 03 09:26:43 core-05 etcd2[1120]: published {Name:a89283615c2348b0859da60e7a1ace5d ClientURLs:[http://192.168.55.105:2379]} to cluster 9b7717754c3d413a
Dec 03 09:26:44 core-05 etcd2[1120]: failed to dial d564fcd3338bbcb9 on stream Message (read tcp 192.168.55.102:2380: connection reset by peer)
Dec 03 09:26:44 core-05 etcd2[1120]: failed to dial d564fcd3338bbcb9 on stream MsgApp v2 (read tcp 192.168.55.102:2380: connection reset by peer)
Dec 03 09:26:44 core-05 etcd2[1120]: set the initial cluster version to 2.1
Dec 03 09:26:44 core-05 etcd2[1120]: failed to dial d564fcd3338bbcb9 on stream Message (dial tcp 192.168.55.102:2380: connection refused)
Dec 03 09:26:44 core-05 etcd2[1120]: failed to dial d564fcd3338bbcb9 on stream MsgApp v2 (dial tcp 192.168.55.102:2380: connection refused)
Dec 03 09:26:50 core-05 etcd2[1120]: failed to dial 130edd7eae6fc420 on stream Message (read tcp 192.168.55.101:2380: connection reset by peer)
Dec 03 09:26:50 core-05 etcd2[1120]: failed to dial 130edd7eae6fc420 on stream MsgApp v2 (read tcp 192.168.55.101:2380: connection reset by peer)
Dec 03 09:26:50 core-05 etcd2[1120]: failed to dial 130edd7eae6fc420 on stream MsgApp v2 (dial tcp 192.168.55.101:2380: connection refused)
Dec 03 09:26:50 core-05 etcd2[1120]: failed to dial 130edd7eae6fc420 on stream Message (dial tcp 192.168.55.101:2380: connection refused)
Dec 03 09:26:56 core-05 etcd2[1120]: failed to dial d564fcd3338bbcb9 on stream Message (read tcp 192.168.55.102:2380: connection reset by peer)

**Comment by mischief** [comment]
ouch. it looks like this might be due to switching the etcd2 systemd service to Type=notify, and etcd2 isn't sending the notify signal until the whole cluster (5/5 instances for example) has come up. this not good, since it means 5 seperate instances all need to come up within the systemd timeout. we could stop use of Type=notify for now, but really etcd2 should gracefully handle termination during bootstrap, since systemd will restart it when it 'times out'.

**Comment by ofekes01** [comment]
I had also see the same problem in the version  877.1 Alpha

**Comment by crawford** [comment]
You can use a drop-in to work around the slow startup. This will up the timeout from 90 seconds to 10 minutes:

```yaml
#cloud-config

coreos:
  units:
    - name: "etcd2.service"
      drop-ins:
        - name: "timeout.conf"
          content: |
            [Service]
            TimeoutStartSec=10m
```

**Comment by mischief** [comment]
i think the core issue here is that etcd will not allow you to run a given instance of it twice with the same discovery URL. in the code, if etcd tries to create an entry in the discovery service and finds that the ID already exists, it is treated as a fatal error. it's not clear if this is optimal behavior, but it certainly can cause frustration when the window for cluster convergence is as small as 90 seconds, and you can't restart any etcd member during that time or you will need to intervene and fix it by hand.
