### ISSUE TITLE
flannel documentation doesn't start etcd

### ISSUE THREAD

**Issue by marineam** [coreos/bugs#938]
Users need complete enough examples that they can build from but https://coreos.com/flannel/docs/latest/flannel-config.html makes no mention of etcd which is required by flannel. Cloud config examples _must_ include either a etcd2 start or configure flannel to hit a remote etcd cluster. Ideally examples cover both.

**Comment by marineam** [comment]
Originally reported in https://github.com/coreos/coreos-overlay/pull/1591

**Comment by crawford** [comment]
It's been almost a year since this was opened. I haven't seen users running into trouble so I'm inclined to close this. Feel free to re-open it if you have a plan for fixing.
