### ISSUE TITLE
systemd-hostnamed fails to set static hostname on boot

### ISSUE THREAD

**Issue by roboll** [coreos/bugs#941]
I have a custom baked AMI built atop coreos via packer. The build process starts the machine, adds a custom ca, runs a few commands to pre-pull some stuff for quick startup, then shuts down and snapshots.

When I start boxes with the resulting AMI, `systemd-hostnamed` errs with this message:
```
systemd-hostnamed[576]: Failed to write static host name: Permission denied
```

This results in `oem-cloudinit` grinding to a halt and nothing else starting up.

`/etc/hostname` still contains the build-time hostname, `hostnamectl` reports the static hostname as the build-time hostname, and reports the correct runtime hostname as transient hostname.

It boils down to code here: https://github.com/systemd/systemd/blob/master/src/hostname/hostnamed.c#L294

Any ideas how to avoid this issue? I'm not setting a hostname in cloud config, just relying on amazon's dhcp assigned hostname.

Running CoreOS 766.4.0

**Comment by roboll** [comment]
`/etc/hostname` permissions look like this:
```
-rw-r--r-- 1 root root 30 Oct 21 20:58 /etc/hostname
```

**Comment by roboll** [comment]
...and to add to my confusion, consistently, manually restarting `oem-cloudinit` service, it _always_ works on the third try. (via the following command)
```
sudo systemctl start oem-cloudinit
```

**Comment by mischief** [comment]
hi @roboll, can you reproduce this on beta (CoreOS 835.1.0)?

**Comment by roboll** [comment]
@mischief yes. see the below output, which demonstrates that `systemd-resolved` is able to change the transient hostname, but `systemd-hostnamed` fails to change the static hostname and fails `oem-cloudinit`. (you can observe the hostname change in the log entries)
```
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Checking availability of "cloud-drive"
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Checking availability of "ec2-metadata-service"
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Fetching user-data from datasource of type "ec2-metadata-service"
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Fetching data from http://169.254.169.254/2009-04-04/user-data. Attempt #1
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Fetching meta-data from datasource of type "ec2-metadata-service"
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Fetching data from http://169.254.169.254/2009-04-04/meta-data/public-keys. Attempt #1
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Fetching data from http://169.254.169.254/2009-04-04/meta-data/public-keys/0/openssh-key. Attempt #1
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Found SSH key for "test-key"
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Fetching data from http://169.254.169.254/2009-04-04/meta-data/hostname. Attempt #1
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Fetching data from http://169.254.169.254/2009-04-04/meta-data/local-ipv4. Attempt #1
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Fetching data from http://169.254.169.254/2009-04-04/meta-data/public-ipv4. Attempt #1
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Parsing user-data as cloud-config
Oct 22 00:26:44 ip-172-31-60-225.ec2.internal coreos-cloudinit[668]: 2015/10/22 00:26:44 Merging cloud-config from meta-data and user-data
Oct 22 00:26:44 ip-10-0-1-87.ec2.internal systemd-resolved[645]: System hostname changed to 'ip-10-0-1-87'.
Oct 22 00:26:44 ip-10-0-1-87.ec2.internal systemd-hostnamed[650]: Failed to write static host name: Permission denied
Oct 22 00:26:44 ip-10-0-1-87.ec2.internal systemd[1]: oem-cloudinit.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by roboll** [comment]
fwiw, i'm running the same code on debian, with systemd v215, and _not_ seeing this issue.

**Comment by roboll** [comment]
@mischief any idea if/when anyone will get a chance to take a look at this? I've been messing around looking for a fix and it consistently works _on the third run, every time_. smells like a bug, but I'm not even really sure where to look for it.

**Comment by roboll** [comment]
done a bunch more debugging trying to find this issue, no luck.

setting permissions to 0777 on /etc/hostname yields no change.
setting hostname via cloudinit yields no change.

**Comment by roboll** [comment]
i'm about ready to give up on this, what a frustrating issue.

can't mask systemd-hostnamed, else oem-cloudinit fails.
overriding the unit under /etc/systemd/system/ with a dash (indicating acceptable failure) yields nothing.

no idea where to step next, except maybe to a different distribution.

**Comment by mischief** [comment]
@roboll i can investigate today.

**Comment by roboll** [comment]
@mischief appreciate that.

my investigations lead me to look at polkit as the likely culprit, though when I put some debug logging in a polkit policy, it generated output when running `hostnamectl set-hostname xxx` from a shell, but _not_ when it was triggered from `oem-cloudinit`.

I hacked my way though disabling the dbus, and isolated the failure to the call `coreos-cloudinit` makes to `hostnamectl set-hostname`.
https://github.com/coreos/coreos-cloudinit/blob/3c2b5e6636da75c163ec980fd4edb0992081a6bc/system/systemd.go#L189

I haven't been able to isolate _why_ polkit acts this way. I suspect it has something to do with communication between a `hostnamectl` child process and polkit dbus. I'm out of my element here hacking my way through, so take all this with a grain of salt.

https://github.com/systemd/systemd/blob/master/src/hostname/hostnamectl.c#L55

**Comment by mischief** [comment]
@roboll can you share what version of coreos you're using and what you are doing to it with packer?

**Comment by roboll** [comment]
@mischief yep.

I've been able to reproduce this on 766.4.0, 835.1.0, and 681.1.0 (all on aws).

All I'm doing with packer is uploading a few tar files and extracting them - their contents all end up under `/opt`, with the exception of a ca certificate, which ends up in `/etc/ssl/certs`. I also run `update-ca-certificates`.

On the packer run the cloud config file is empty, though I've also tried using a file with `hostname: ""` and a few variations of trying to disable / overwrite the service.

On the initial boot via packer, there are no errors - it sets the hostname successfully.

**Comment by mischief** [comment]
@roboll my initial thought is that maybe you run into YungSang/coreos-packer#1 - can you try resetting /etc/machine-id as @YungSang does in YungSang/coreos-packer@5a3e7cd8cf12ebd793aef3a635874a82ef1f7228?

**Comment by roboll** [comment]
@mischief unfortunately no dice there. the machine id gets regenerated, and is different, but setting the static hostname still fails.

**Comment by roboll** [comment]
@mischief this is not just a coreos issue, as I originally thought. 

On a debian system running systemd 215, everything is fine. 

It manifests on:

fedora running systemd 219 

coreos running systemd 219(681)

coreos running systemd 225(766)

**Comment by mischief** [comment]
@roboll is this all under packer or can you reproduce without packer on coreos?

**Comment by roboll** [comment]
@mischief 

trying to reproduce from the amazon web ui, and it looks like it's working properly. interestingly, it looks like the hostname on boot is reset to localhost - do you have any idea why the hostname would under certain circumstances be reset to localhost, and not in others?

anyway, it looks like this may be an issue with the way packer is creating the snapshots, but I'd still like to understand what can throw systemd for such a loop where it can't update the hostname, that doesn't seem right regardless.

**Comment by roboll** [comment]
i have a feeling the root of this issue is this:

https://github.com/systemd/systemd/blob/0a41d91f3022ae5107151ebd1af9b65a55030c7e/NEWS#L1736

**Comment by roboll** [comment]
lots of debugging later, this was some combination of wrong file permissions on systemd units and /etc/hostname, and has nothing to do with the systemd-firstboot or systemd in general - oops.

sorry for the noise.

**Comment by mischief** [comment]
@roboll glad it's fixed :-)

**Comment by max-lobur** [comment]
for those who digging here: when you bootstrap coreos 1st time via packer it changes hostname and changes owner of the /etc/hostname and /etc to core:core.
Solution:
```
sudo chown root:root /etc/hostname
sudo chown root:root /etc/
```
in packer cleanup
