### ISSUE TITLE
journalctl returns `Error was encountered while opening journal files: Invalid argument`

### ISSUE THREAD

**Issue by yichengq** [coreos/bugs#943]
CoreOS version 789.0.0
Update Strategy: No Reboots
GCE, n1-highcpu-2

First, I observed that one machine used 100% CPU, and cannot ssh.
Then, I restarted the machine.
Then, I want to check the log through `sudo journalctl -b -k`, and it returns this error to me.

I googled possible related thread: https://bbs.archlinux.org/viewtopic.php?id=199031, and remove all journal log files, then journalctl works again.

**Comment by vcaputo** [comment]
Closing as probable duplicate of https://github.com/coreos/bugs/issues/959
