### ISSUE TITLE
Enabling LLDP on a CoreOS node

### ISSUE THREAD

**Issue by mazad01** [coreos/bugs#946]
Hi, I'm trying to enable LLDP on a Solarflare NIC interface on a CoreOS host. 
My network file is as follows:

```
core@host ~ $ cat /etc/systemd/network/ens1f0.network                       
 [Match]
Name= ens1f0

[Network]
Address=*
LLDP=yes

[Route]
Gateway=*
Destination=*
```

I also checked to see the LLDP interfaces with `networkctl lldp` with no avail. Any idea?

cc: @greenpau

**Comment by crawford** [comment]
The default network config (99-default.link) is taking precedence over your config (they are evaluated in lexicographic order). You'll need to prefix the file name with a number (e.g. 10-ens1f0.network). You can use `networkctl status ens1f0` to verify that the interface is using the correct config.

**Comment by crawford** [comment]
@mazad01 have you had a chance to try my suggestion?

**Comment by mazad01** [comment]
Hey, thanks for the follow up, haven't completely tested yet, but when I do, I'll update this thread
