### ISSUE TITLE
etcd configuration isn't applied after machine reboot

### ISSUE THREAD

**Issue by sasa1977** [coreos/bugs#947]
This is a "reboot" of the coreos/etcd#3739 issue. It was suggested to me to move the report to this repo. 

The gist of the issue is that etcd settings (e.g. non-default ports) are not applied after I reboot the machine. If I manually restart the service, then it all works as expected. As hinted by @jonboulle, I compared the time when etcd is started against the timestamp of `/run/systemd/system/etcd2.service.d/20-cloudinit.conf` and it looks like configuration file is created after the etcd is started, so that's possibly the reason?

For the sake of completeness, below is the copy-paste of my original report. Any help is much appreciated :-)

I have the following situation. I use CoreOS (833.0.0) powered by Vagrant, and I set a non-default etcd client port through cloud-config. 

This works well on initial boot. However, after I reboot the machine, etcd listens on the default port (4001), thus bypassing my settings. What's really strange is that after I manually restart `etcd2` service, settings are applied correctly.

Here's the interesting part from my cloud-config:

```
coreos:
  etcd2:
        name: "$public_ipv4"
        advertise-client-urls: http://$public_ipv4:20120
        initial-advertise-peer-urls: http://$public_ipv4:20121
        listen-client-urls: http://0.0.0.0:20120
        listen-peer-urls: http://$public_ipv4:20121
        initial-cluster: 192.168.55.101=http://192.168.55.101:20121
...

  - name: etcd2.service
    command: start
```

This looks good on the target machine:

```
$ systemctl status etcd2
● etcd2.service - etcd2
   Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; disabled; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd2.service.d
           └─20-cloudinit.conf

$ cat /run/systemd/system/etcd2.service.d/20-cloudinit.conf

[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://192.168.55.101:20120"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.55.101:20121"
Environment="ETCD_INITIAL_CLUSTER=192.168.55.101=http://192.168.55.101:20121"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:20120"
Environment="ETCD_LISTEN_PEER_URLS=http://192.168.55.101:20121"
Environment="ETCD_NAME=192.168.55.101"
```

However, after I reboot the machine, I see:

```
$ journalctl -u etcd2 --no-pager

...
Oct 23 09:10:13 air-01 etcd2[526]: listening for peers on http://localhost:2380
Oct 23 09:10:13 air-01 etcd2[526]: listening for peers on http://localhost:7001
Oct 23 09:10:13 air-01 etcd2[526]: listening for client requests on http://localhost:2379
Oct 23 09:10:13 air-01 etcd2[526]: listening for client requests on http://localhost:4001
```

Here's the full dump:

```
$ journalctl -u etcd2 --no-pager

...

-- Reboot --
Oct 23 09:10:13 air-01 systemd[1]: Starting etcd2...
Oct 23 09:10:13 air-01 etcd2[526]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 23 09:10:13 air-01 etcd2[526]: recognized and used environment variable ETCD_NAME=6a602f561aa14662b8b0710960bb0c26
Oct 23 09:10:13 air-01 etcd2[526]: etcd Version: 2.2.0
Oct 23 09:10:13 air-01 etcd2[526]: Git SHA: e4561dd
Oct 23 09:10:13 air-01 etcd2[526]: Go Version: go1.5.1
Oct 23 09:10:13 air-01 etcd2[526]: Go OS/Arch: linux/amd64
Oct 23 09:10:13 air-01 etcd2[526]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Oct 23 09:10:13 air-01 etcd2[526]: the server is already initialized as member before, starting as etcd member...
Oct 23 09:10:13 air-01 etcd2[526]: listening for peers on http://localhost:2380
Oct 23 09:10:13 air-01 etcd2[526]: listening for peers on http://localhost:7001
Oct 23 09:10:13 air-01 etcd2[526]: listening for client requests on http://localhost:2379
Oct 23 09:10:13 air-01 etcd2[526]: listening for client requests on http://localhost:4001
Oct 23 09:10:13 air-01 etcd2[526]: name = 6a602f561aa14662b8b0710960bb0c26
Oct 23 09:10:13 air-01 etcd2[526]: data dir = /var/lib/etcd2
Oct 23 09:10:13 air-01 etcd2[526]: member dir = /var/lib/etcd2/member
Oct 23 09:10:13 air-01 etcd2[526]: heartbeat = 100ms
Oct 23 09:10:13 air-01 etcd2[526]: election = 1000ms
Oct 23 09:10:13 air-01 etcd2[526]: snapshot count = 10000
Oct 23 09:10:13 air-01 etcd2[526]: advertise client URLs = http://localhost:2379,http://localhost:4001
Oct 23 09:10:13 air-01 etcd2[526]: restarting member d754d81d0576951e in cluster 3416969fe74d1e1f at commit index 1092
Oct 23 09:10:13 air-01 etcd2[526]: d754d81d0576951e became follower at term 2
Oct 23 09:10:13 air-01 etcd2[526]: newRaft d754d81d0576951e [peers: [], term: 2, commit: 1092, applied: 0, lastindex: 1092, lastterm: 2]
Oct 23 09:10:13 air-01 etcd2[526]: starting server... [version: 2.2.0, cluster version: to_be_decided]
Oct 23 09:10:13 air-01 systemd[1]: Started etcd2.
Oct 23 09:10:13 air-01 etcd2[526]: added local member d754d81d0576951e [http://192.168.55.101:20121] to cluster 3416969fe74d1e1f
Oct 23 09:10:13 air-01 etcd2[526]: set the initial cluster version to 2.2
Oct 23 09:10:14 air-01 systemd[1]: Started etcd2.
```

It looks to me like etcd is completely ignoring env settings.

If I restart the service manually, and check logs, the correct settings are applied:

```
$ sudo systemctl restart etcd2

Oct 23 09:31:40 air-01 systemd[1]: Stopping etcd2...
Oct 23 09:31:40 air-01 etcd2[526]: received terminated signal, shutting down...
Oct 23 09:31:40 air-01 systemd[1]: Stopped etcd2.
Oct 23 09:31:40 air-01 systemd[1]: Starting etcd2...
Oct 23 09:31:40 air-01 etcd2[7217]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://192.168.55.101:20120
Oct 23 09:31:40 air-01 etcd2[7217]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 23 09:31:40 air-01 etcd2[7217]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.55.101:20121
Oct 23 09:31:40 air-01 etcd2[7217]: recognized and used environment variable ETCD_INITIAL_CLUSTER=192.168.55.101=http://192.168.55.101:20121
Oct 23 09:31:40 air-01 etcd2[7217]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:20120
Oct 23 09:31:40 air-01 etcd2[7217]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://192.168.55.101:20121
Oct 23 09:31:40 air-01 etcd2[7217]: recognized and used environment variable ETCD_NAME=192.168.55.101
Oct 23 09:31:40 air-01 etcd2[7217]: etcd Version: 2.2.0
Oct 23 09:31:40 air-01 etcd2[7217]: Git SHA: e4561dd
Oct 23 09:31:40 air-01 etcd2[7217]: Go Version: go1.5.1
Oct 23 09:31:40 air-01 etcd2[7217]: Go OS/Arch: linux/amd64
Oct 23 09:31:40 air-01 etcd2[7217]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Oct 23 09:31:40 air-01 etcd2[7217]: the server is already initialized as member before, starting as etcd member...
Oct 23 09:31:40 air-01 etcd2[7217]: listening for peers on http://192.168.55.101:20121
Oct 23 09:31:40 air-01 etcd2[7217]: listening for client requests on http://0.0.0.0:20120
```

So the question is: what happens? Why are env settings originally ignored? Am I doing something wrong here?

**Comment by crawford** [comment]
It looks like etcd2 is enabled or is a dependency of something that is enabled because it is starting before coreos-cloudinit (which writes out the etcd2 settings). You can check this with `systemctl is-enabled etcd2.service` and `systemctl list-dependencies --reverse etcd2.service`.

**Comment by sasa1977** [comment]
Thank you for your help. Looks like that was it. I have a couple of my own units where I specified:

```
Requires=etcd2.service
BindsTo=etcd2.service
```

Once I removed that, reboot works as expected.

This begs following questions:

1. Is this my fault, i.e. should I avoid specifying such requirements  on etcd2?
2. If yes, how can I ensure that my units are running only if etcd is running? Looking at systemd docs, it seems to me that `After` doesn't cut it, because it only ensures the startup order, but doesn't touch my units if etcd2 somehow crashes. I guess the biggest concern for me is how to stop my units if the machine finds itself in the minority?
3. Is the boot workflow documented anywhere?

Thanks again for your help :-)

**Comment by crawford** [comment]
> Is this my fault, i.e. should I avoid specifying such requirements on etcd2?

Yes and no. You should specify a service's dependency to take full advantage of systemd's async nature. If you are using coreos-cloudinit, you need to go all in and use that tool to start all services. In your case, you have a service which is enabled and then depends on etcd. systemd will start etcd, while fulfilling the dependency for that enabled service, long before coreos-cloudinit has written etcd's configuration.

> Is the boot workflow documented anywhere?

It is not. It is fairly complex and ever-changing. You can generate it using `systemd-analyze dot`.

**Comment by sasa1977** [comment]
Thank you very much for your help! After specifying my services in cloud config, everything works as expected, even if I have hard requirement on etcd2. 

So I guess the issue happened because of my misuse of the whole thing, and the point is that I should manage all my services from cloud config?

**Comment by crawford** [comment]
Yes, you should either go all in on coreos-cloudinit or avoid it entirely. systemd and coreos-cloudinit should be treated as, effectively, two different init systems (for better or worse).

**Comment by Beanow** [comment]
I struggled with this exact same misconception about cloudinit usage recently.
A heads up about this would have been nice in each of:
https://coreos.com/kubernetes/docs/latest/kubernetes-on-generic-platforms.html
https://coreos.com/kubernetes/docs/latest/getting-started.html
https://coreos.com/os/docs/latest/cloud-config.html

**Comment by robszumski** [comment]
cc @joshix
