### ISSUE TITLE
Rackspace RackConnect doesn't work

### ISSUE THREAD

**Issue by philips** [coreos/bugs#95]

**Comment by nnnnathann** [comment]
Anyone know anything about the status of this?  Otherwise I'm planning on following up with our account manager at Rackspace and see what's going on

**Comment by kevin1024** [comment]
Sorry, I haven't heard anything.  Still haven't been able to use CoreOS for work, sadly.

**Comment by nnnnathann** [comment]
Same here, I'll let you know what I hear from RS

Cheers

nathan

**Comment by aetaric** [comment]
Hey everyone! Racker here!

I've got a verified workaround that we tested on a RackConnectV3 account. This is considered unsupported on the RackConnect side but it seems to be working well.

# supernova env image-show fc299ac5-433d-4b80-98ae-e097464a7758
Shows the image and the metadata showing that RackConnect isn't visible. Which means if you try to boot it directly it will fail with a 403 error.

# supernova env volume-create --image-id fc299ac5-433d-4b80-98ae-e097464a7758 --display-name coreos-vol --volume-type sata 75
This will create a bootable volume from the CoreOS image.

From here you can create a "Boot from Volume" server via the control panel selecting the RCv3 Neutron network to make the machine a part of.

Upgrades from RCv2 to RCv3 are currently only possible through manual migration. You can however create another cloud account and connect it to your network device but currently RCv2 and RCv3 don't like to coexist. If you have questions about getting migrated to RCv3 give us a call and talk to your NetSec team about migrating to RCv3.

**Comment by damsonn** [comment]
Hey guys,
I got a problem with CoreOS and RCv2... issue still open so was wondering if you have anything new on the topic ? ( or should I just move to RCv3 ).

Cheers

**Comment by crawford** [comment]
Sounds like the answer is to use RCv3.
