### ISSUE TITLE
find out version of x in particular CoreOS release

### ISSUE THREAD

**Issue by jonboulle** [coreos/bugs#950]
Let's say I want to find the version of systemd in the latest alpha image. Here's the process I currently go through (based on suggestions I've had previously from the OS team):
- go to https://coreos.com/releases
- see latest Alpha is 845.0.0, with version information for kernel/docker/etcd/fleet but not systemd
- follow the link to view this release on GitHub, https://github.com/coreos/manifest/releases/tag/v845.0.0
- click to the commit it represents, https://github.com/coreos/manifest/commit/1161c63ef815a0fed37f6c8a819e7bbb169dbbe2
- view the whole build file at this version, https://github.com/coreos/manifest/blob/1161c63ef815a0fed37f6c8a819e7bbb169dbbe2/build-845.xml
- see coreos/systemd in this file and navigate to the respect commit, https://github.com/coreos/systemd/commit/e859aa9e993453be321450148d45d08fcc55c3f5
- ??? now what. If this was the upstream systemd/systemd repository, I could (partially) rely on the tag information that GitHub helpfully inserts just under the commit message (to give me at least a minimum version), but in this particular case it's just "master". But since our master is several tags behind upstream master that's not so helpful.

There are a lot of leaps here which I've sort of pieced together as what I think is the right path, but none of them are intuitive and I still didn't end up with what I needed. 

Please help.

**Comment by crawford** [comment]
You can also take a look at http://alpha.release.core-os.net/amd64-usr/current/coreos_production_image_packages.txt.

**Comment by jonboulle** [comment]
Thanks for the tip, that probably answers my question 99% of the time. But how can we make it more obvious? Could we link to it from the releases somehow?

**Comment by iaguis** [comment]
:+1:

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
