### ISSUE TITLE
no network device beyond lo

### ISSUE THREAD

**Issue by mathieu-lacage** [coreos/bugs#951]
I have tried to boot both stable and beta coreos releases on a dedicated ovh server but both fail to boot without network connectivity. I have extracted the journalctl logs and I can confirm that:

1. "ip links" shows no network device beyond "lo" after systemd-networkd completes enumeration
2. lspci shows that my ethernet devices are here, indeed.
3. lsmod shows that no network driver is loaded.

Now, I am not familiar with how the kernel boots in general but I can see the following suspicious-looking errors: http://paste.ubuntu.com/12969870/

The full boot logs: http://paste.ubuntu.com/12973943/

**Comment by mischief** [comment]
@mathieu-lacage afaict, we do have the appropriate driver `ixgbe`. have you tried the suggestion in the kernel log?

```
Oct 26 12:03:46 localhost kernel: pci_bus 0000:ff: Some PCI device resources are unassigned, try booting with pci=realloc
```

**Comment by mathieu-lacage** [comment]
ok, I missed that one.

However, I have no physical access to that server and the ipmi mode appears to be too slow to allow me to catch the boot grub2 prompt and insert the pci=realloc argument. I can boot its rescue linux os which is some kind of old stripped-down thing. From there, I can mount /dev/sda1 but I see that you appear to be using grub2 so I am worried editing /boot/grub/menu.lst directly might not be a great idea. Do you have suggestions on what would be the best way to change that ? Do I need to rebuild an entire coreos image myself ?

**Comment by mathieu-lacage** [comment]
FYI, that machine appears to be able to successfully boot a kernel based on this configuration: ftp://ftp.ovh.net/made-in-ovh/bzImage/3.14.32-4/config-3.14.32-xxxx-std-ipv6-64-rescue

**Comment by aemr3** [comment]
Hey this is related with my issue https://github.com/coreos/bugs/issues/925. I have the same problem. Current ixgbe drivers in kernel 4.2.2 doesn't work with ovh servers. I am using ixgbe version 4.1.5. It works.

**Comment by mathieu-lacage** [comment]
I confirm that using a new driver ixgbe allows this box to boot. i.e., this issue is related to issue #925. Is there something I could do to help this land in alpha soon ?

**Comment by mischief** [comment]
@mathieu-lacage we do not ship modules that are not in the upstream kernel.. @marineam any other words on this?

**Comment by aemr3** [comment]
@mischief It is already included in the upstream kernel. But it is not the latest version.

**Comment by philips** [comment]
@aemr3 Is it in the latest version now? We ship Kernel v4.4.1.

**Comment by aemr3** [comment]
@philips yes, I can confirm that kernel v4.4.1 fixes this issue. I have tested CoreOS Alpha channel v970.1.0 and had no problem. So you can close issue #925 also.
