### ISSUE TITLE
network problem with 845.0.0 and my container

### ISSUE THREAD

**Issue by rbucker** [coreos/bugs#952]
after 845.0.0 was installed my containers could not longer contact the public internet. I can keep the machine alive if there are any commands I need to run. I believe that it's somewhere between docker and CoreOS. hello-world works fine. It's been 6 hours but if I recall a straight ubuntu worked but jessie did not. I tried a fresh 845.0.0 but that also failed when I installed my environment.

**Comment by mischief** [comment]
how did you determine the container could not contact the internet? can the host still contact the internet?

**Comment by rbucker** [comment]
my container is my IDE so I run everything from a bash shell. One of the tools is a report generator that connects to an outside SQL Server DB on a remote machine. (a) I failed to connect to the remote DB. As I debugged the system I tried to ping the server (b) ping failed to resolve the hostname. I tried to ping the IP address (c) failed to ping the server via IP address. (d) I tried pinging different hostnames and IPs (google.com, dell.com) and nothing worked. I exited the shell and tried the commands from the CoreOS host and they worked. I tried to rebuild my container with a Dockerfile I had used a hundred time before and it aborted after failing to run apt-get update reporting that apt-get could not connect to any of the server(s).  I took the exact same tests and tried against a clean 845.0.0 and FAIL. I tried the same tests against 835.1.0(current beta) and I was able to rebuild my container.

**Comment by crawford** [comment]
@rbucker are you using DigitalOcean by chance?

**Comment by rbucker** [comment]
yes, this was at DO.

**Comment by mathbruyen** [comment]
I got the same issue since on DigitalOcean after the automatic update of CoreOS (this happened right after a small peak of CPU and network 100% usage). Trying to access services from the outside fails (waiting until browser timeouts) and some services trying to resolve external hostnames (nginx proxypass) fail. I can:

* ssh to the machine
* start and stop containers
* access services running on containers using cURL from the machine (so they are correctly linked as nginx is able to access the application server, itself reading from the DB)
* ping and resolve hostnames from outside containers, even the ones nginx fails to resolve

**Comment by rbucker** [comment]
I suppose there could be some original config problem, however, a fresh 845.0.0 installation at DO created the same problem. According to the support team at DO they make configuration as immutable as possible. In a recent problem I needed to change my cloud-config which they said I could not.

**Comment by bkleef** [comment]
Same here with DO by autoupdate.

**Comment by rbucker** [comment]
autoupdate is not the root of the problem.  I tried a fresh install with the same results.

**Comment by rbucker** [comment]
my intuition is suggesting that it's DHCP or routing table related. when I did 'ip routes' on the host there were multiple routes per network port. This is not bad or evil as it worked that way previously, however, the default route may be wrong or out of order. There was a bug that looked like this several years ago (misplaced the ticket number).  My second choice might be the OEM metadata changes as indicated in the release notes, however, I do no know what those changes might impact.

**Comment by rbucker** [comment]
this is a reply I got from DO:

Hey Richard,

Thanks for reporting this issue. I'm going to spend some time working with our engineers to try to reproduce this issue, but I think it might be because 845.0 introduces some changes to properly work with Floating IPs on our network. There might be a bug in there that's causing this behavior (it is alpha, after all).

I'll update you once I know more. Please let me know if you need anything else or have additional information.

+++++

I hope someone on the team can reach out and help them.

**Comment by rbucker** [comment]
more DO feedback:


Hey Richard,

Thanks for waiting. After some further investigation, it's clear that this only occurs with no floating IPs attached. We will continue work on a resolution, but if you want a quick "fix" you can attach a floating IP to your droplet and it should work fine.

I'll update you again when we have more information for you. Please let us know if you need anything else.

**Comment by mdlayher** [comment]
Hi all, I'm the engineer at DigitalOcean who contributed floating IP support for CoreOS.

I've found what appears to be the solution for this issue, and have submitted a pull request: https://github.com/coreos/coreos-cloudinit/pull/403.

**Comment by rbucker** [comment]
I think we can close this one and keep it around for documentation. Would the owner like to comment?
