### ISSUE TITLE
PXE boot failing on 835.2.0

### ISSUE THREAD

**Issue by dmeiser** [coreos/bugs#955]
PXE Boot is failing with the error:

localhost systemd[1]: Requested transaction contradicts existing jobs: Transaction is destructive.
localhost systemctl[642]: Failed to start initrd-switch-root.target: Transaction is destructive.
localhost systemd[1]: initrd-cleanup.service: Main proces exited, code=exited, status=4/NOPERMISSION
localhost systemd[1]: Failed to start Cleaning Up and Shutting Dow Daemons
localhost systemd[1]: initrd-cleanup.service: Unit entered failed state.
localhost systemd[1]: initrd-cleanup.service: Triggering OnFailure=dependencies
localhost systemd[1]: initrd-cleanup.service: Failed with result 'exit-code'.

**Comment by crawford** [comment]
Can you provide the full logs? These errors are secondary to the actual failure.

**Comment by dmeiser** [comment]
Alex, see this gist:  https://gist.github.com/dmeiser/7c385da12d66ac7235b7#file-rdsosreport-txt

**Comment by crawford** [comment]
Got it:

```
[   92.630708] localhost systemd[1]: dev-disk-by\x2ddiskuuid-00000000\x2d0000\x2d0000\x2d0000\x2d000000000001.device: Job dev-disk-by\x2ddiskuuid-00000000\x2d0000\x2d0000\x2d0000\x2d000000000001.device/start timed out.
```

You are forcing a first boot, but your disk doesn't have the correct signature. This is a bug.

**Comment by vcaputo** [comment]
@crawford issues like this one are making me think we should decouple the "generate random disk uuid on successful boot" from "this is a first boot", and make grub set both when appropriate, and the user set just "this is a first boot" when appropriate.

**Comment by dmeiser** [comment]
@vcaputo I don't know if anyone else is using PXE like we are intending to, but I'm trying to avoid installing anything to disk (reserving disk as a cache).  So, strictly speaking, every boot will be a first boot and there never will be a uuid on disk.

**Comment by tsuna** [comment]
I'm running on CoreOS 835.11.0 and I have this issue too.  I had a failing disk on this machine and re-image OS by PXE booting it, which re-installs the base image, and now I can't get this machine to boot anymore.  I always land in Emergency Mode and can't past it.

I don't understand the fix, so I'm not sure what to do/try.

**Comment by tsuna** [comment]
FWIW, I just upgraded to CoreOS 1000.0.0 and the problem persists.

**Comment by tsuna** [comment]
I believe my issue is a bit different, I filed #1198 instead.
