### ISSUE TITLE
Docker SELinux MCS policy

### ISSUE THREAD

**Issue by oszi** [coreos/bugs#961]
SELinux policies for Docker seem to be missing, should there be any.
I'm using CoreOS 835.1.0 and the docker daemon is of course running with --selinux-enabled.
For instance, this should result in denials but nothing happens in enforcing mode:
```
docker run -dv /tmp/secret:/tmp/secret:Z busybox sleep 60
docker run -v /tmp/secret:/tmp/secret busybox ls /tmp/secret
```
If SELinux is only integrated with rkt then this is a feature request.

**Comment by mjg59** [comment]
https://github.com/coreos/coreos-overlay/pull/1632

**Comment by mjg59** [comment]
https://github.com/coreos/coreos-overlay/pull/1632
