### ISSUE TITLE
systemd: make systemd-journal-upload and systemd-journal-remote work (part 2)

### ISSUE THREAD

**Issue by kayrus** [coreos/bugs#962]
continue #919 

For now we have to fix:
- systemd-remote.conf:

```
d /var/log/journal/remote 2755 systemd-journal-remote systemd-journal - -
d /run/log/journal/remote 2755 systemd-journal-remote systemd-journal - -
```
- systemd-upload.conf:

```
d /var/lib/systemd/journal-upload 0755 systemd-journal-upload systemd-journal-upload - -
```
- add systemd-journal-upload user into systemd-journal group
- fix https->http inside systemd-journal-remote.service (as we don't use https)
- for test purposes (same as tmpfiles.d) create sysusers.d directory https://github.com/coreos/coreos-overlay/pull/1617

**Comment by kayrus** [comment]
Fixed here: https://github.com/systemd/systemd/pull/1766 waiting for reply.

**Comment by kayrus** [comment]
My fix was ignored. Systemd guys implemented their own fixes here:
* https://github.com/systemd/systemd/pull/2331
* https://github.com/systemd/systemd/pull/2213

@mischief can we backport these fixes?

**Comment by Eeemil** [comment]
Whats the status on this issue? I still get `Failed to start µhttp daemon`-errors when trying with HTTPS. I guess it has to do with the lack of GnuTLS but I don't know if there is any workaround for that yet.

Also, what do you mean by this?
> fix https->http inside systemd-journal-remote.service (as we don't use http)

Is that a typo for "as we don't use https"? Https is crucial for my intended use case...

**Comment by kayrus** [comment]
@Eeemil CoreOS doesn't ship gnutls which is used by libmicrohttpd, which is used by systemd-journal-remote. Workaround at the moment is to compile your own gnutls lib, put it into `/opt/lib` and run `systemd-journal-remote` with the `LD_LIBRARY_PATH=/opt/lib`

**Comment by Eeemil** [comment]
Thanks for the quick reply, @kayrus ! Are there any plans for a long-term solution to enable HTTPS? @marineam speaks of reviewing the state of things at https://github.com/coreos/coreos-overlay/pull/1587#issuecomment-148422613 .

**Comment by kayrus** [comment]
@Eeemil there are lot of openssl dependencies. it is not easy just replace openssl with gnutls. also shipping gnutls as a second library can decrease os security. we've already tried to port libmicrohttpd lib to use openssl - it is not possible, here are details of this discussion: http://lists.gnu.org/archive/html/libmicrohttpd/2015-11/msg00015.html

**Comment by Eeemil** [comment]
@kayrus as I read that discussion, there are some unanswered questions about licensing, but besides from that, supporting openssl seems possible - have I missed something?

I get that it's not easy to just replace openssl with gnutls- but are there any efforts to make that transition? Or any other solution to this problem? I just want to know the status of things, if CoreOS is moving towards supporting HTTPS for `systemd-journal-remote` or if this is a wont-fix-issue?

**Comment by kayrus** [comment]
@Eeemil there are both licensing and implementing issues. As soon as I know it is not high priority issue for CoreOS.

**Comment by Eeemil** [comment]
@kayrus I can't find the issues you are speaking of. I find some questions about licensing, but no definite answers. As to implementation issues, I find only non-issues. However, I could have missed something.

> As soon as I know it is not high priority issue for CoreOS.

That doesn't really answer my question. I want to know if there are any plans to solve any of these problems within the CoreOS community. Or do you mean that CoreOS-devs in fact _are_ working on a solution (but slowly, as it isn't high priority?). It's a big difference between a low-prioritized issue, and a wont-fix issue.

*By the way*, I would strongly suggest that we do not "fix" this issue by reverting from https to http in `systemd-journal-remote.service`. At least if we are not certain that nobody will fix the libmicrohttpd+gnuTLS-issue.

Quietly downgrading security is a kludgy path towards doom. If downgrading is the only option, I would suggest we add some kind of highly-visible warning that the traffic will be unencrypted.

**Comment by kayrus** [comment]
@Eeemil I don't work on CoreOS and I can only assume what they think. Also I've provided you with the workaround: compile your own gnutls lib and use it to run systemd-journal-remote in https mode.

**Comment by Eeemil** [comment]
@kayrus with all due respect, I would appreciate if you made it clear on when you're uncertain of the answer. You seem to have more insight than me in this issue and CoreOS development in general, so I have to rely on what you're saying.

@marineam I get the impression that you are the right person to ask: are there any plans to transition to gnuTLS or finding some other solution to getting `systemd-journal-remote` to work with https?

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
