### ISSUE TITLE
systemd malfunctioning breaks ssh access due to socket activation

### ISSUE THREAD

**Issue by vcaputo** [coreos/bugs#966]
When systemd gets into a broken state, socket activation doesn't work, which can make a system inaccessible if ssh is your only option.

I believe we should strongly consider not making sshd socket activated by default.  It doesn't require much in the way of resources or boot time, and makes our system more robust and debuggable in the face of systemd bugs, which aren't exactly uncommon/unlikely considering the complexity and maturity of systemd code.

**Comment by chr0n1x** [comment]
BUMP

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
