### ISSUE TITLE
Missing security defaults for kernel

### ISSUE THREAD

**Issue by kees** [coreos/bugs#969]
I would recommend enabling the following for an improved security stance on the kernel:

CONFIG_DEBUG_RODATA=y (needs CONFIG_DEBUG_KERNEL=y)
CONFIG_CC_STACKPROTECTOR_STRONG=y (not _REGULAR)
CONFIG_SYN_COOKIES=y
CONFIG_DEBUG_CREDENTIALS=y

**Comment by marineam** [comment]
Thanks, forgot to switch stackprotector when we upgraded to gcc 4.9. the others we simply missed :(

@mjg59 any others you can think of?

**Comment by marineam** [comment]
@kees DEBUG_RODATA is enabled by default and SYN_COOKIES is slected by IP_NF_TARGET_SYNPROXY which is enabled. Will post a PR for the others shortly.

**Comment by marineam** [comment]
all of those were missing from arm64 though

**Comment by kees** [comment]
Glad to hear DEBUG_RODATA was already there. (I didn't see DEBUG_KERNEL which is required for RODATA=y.)

forgot to mention for x86:

RANDOMIZE_BASE=y (and removed HIBERNATE if you haven't already)

for arm64:

DEBUG_ALIGN_RODATA=y (along with DEBUG_RODATA)

for both (may already be set):

DEBUG_SET_MODULE_RONX=y

**Comment by marineam** [comment]
Yeah, using a minimal defconfig makes it less obvious what is actually enabled in the final config. Will check on those new options.

**Comment by marineam** [comment]
We tried `RANDOMIZE_BASE` when it was first introduced but it made Xen explode. Hopefully this time around it works better :)

**Comment by marineam** [comment]
And we do have `HIBERNATE` enabled, should be OK to remove as it seems unlikely anyone has managed to configure CoreOS to use it. What is the concern with that feature?

**Comment by marineam** [comment]
Ah, I enabled `HIBERNATE` back when we were debugging/fighting with kexec, it is required for `KEXEC_JUMP`.

**Comment by marineam** [comment]
Ok, all the kernel config suggestions are merged now.
