### ISSUE TITLE
Upgrade to kubectl v1.1.1

### ISSUE THREAD

**Issue by hosh** [coreos/bugs#971]
Kubernetes 1.1 has been officially released now: https://github.com/kubernetes/kubernetes/releases/tag/v1.1.1

There are some good features in here. It would be great to see this in the alpha channel.

**Comment by mischief** [comment]
we do not ship k8s in coreos. we do however ship kubelet. is that what you wish to be upgraded?

**Comment by hosh** [comment]
@mischief yep
