### ISSUE TITLE
Missed HIDDEV interface from kernel on bare metal servers

### ISSUE THREAD

**Issue by mmelnyk** [coreos/bugs#975]
Feature request: Our bare metal servers have integrated power meters via usb bus (support hid interface), but monitoring software required hiddev devices, disabled by default (# CONFIG_USB_HIDDEV is not set) in the kernel. It would be great to have this hiddev interface enabled. Also some usb ups requires hiddev too.

**Comment by mischief** [comment]
@mmelnyk is that the only kernel config option required?

**Comment by mmelnyk** [comment]
Yes - just kernel part, user-mode parts for different devices cab be in containers.

**Comment by mischief** [comment]
@mmelnyk this change will be present in the next alpha.

**Comment by mmelnyk** [comment]
I will test when alpha is available
