### ISSUE TITLE
/etc/issue only has md5 fingerprints

### ISSUE THREAD

**Issue by pwaller** [coreos/bugs#976]
Modern SSH now uses sha256 rather than MD5.

We use the fingerprints from the console to confirm we're talking to the right machine. Would it be possible to put both in [`sshd_keygen`](https://github.com/coreos/init/blob/0ab24b10bb1b6a4bcb0dc8d8981e2a5294864ad1/scripts/sshd_keygen)?

See for example this:

http://superuser.com/questions/929566/sha256-ssh-fingerprint-given-by-the-client-but-only-md5-fingerprint-known-for-se

However it seems that MD5 is known to be very weak, so I would rather have a way to obtain the stronger hash than downgrade my client to use the weaker hash.

**Comment by crawford** [comment]
Do you see MD5 fingerprints when running `ssh-keygen -l -f`? What version of CoreOS?

On my system (845.0.0), I get SHA256 fingerprints.

**Comment by pwaller** [comment]
I guess I'm not running the latest release. That's fine then, I'll happily wait till it hits stable. Thanks for the hint :)

**Comment by marineam** [comment]
Yeah, the system is just following the default behavior of ssh-keygen so we magically switched to sha256 during a recent openssh update. :)
