### ISSUE TITLE
Cannot configure the network settings used in the initramfs

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#981]
Following up from https://github.com/coreos/bugs/issues/212, operators need to be able to configure the network used in the initramfs. In this particular case, having DHCP enabled on all interfaces is causing a problem.

**Comment by FirefighterBlu3** [comment]
any further followup on being able to control network in initramfs? i'm pxe booting and i want my initial dhcp to have a vendor class identifier so i can control what IPs these clients get prior to fetching cloud config.

**Comment by crawford** [comment]
Nothing yet, but this is good feedback.

**Comment by FirefighterBlu3** [comment]
if ignition can notice that ip=<foo...> and bootif=<foo...> has been set on the kernel command line and use that to for our initial network setting as a dhcp renew function, that'd be just perfect.

**Comment by urzds** [comment]
cloud-config supports `*.network` systemd units (which it places under `.../systemd/network`, apparently). Would that also solve this issue?

**Comment by crawford** [comment]
@urzds no. Ignition supports the exact same feature, but this applies to the post-pivoted system, not the initramfs. And since the network is potentially required to fetch the config in the first place, we inherently cannot supply this information via the Ignition config. It will need to come from the kernel command line parameters.
