### ISSUE TITLE
etcd2.service doesn't depend on networking

### ISSUE THREAD

**Issue by polarina** [coreos/bugs#984]
The `etcd2.service` definition doesn't depend on networking.

Other services that may be manually installed by the user that depend on that service may cause etcd2 to start up before the interfaces have been configured.

**Comment by crawford** [comment]
@mischief that's possible, but I think the etcd service should declare that dependency itself since it depends on the network.

**Comment by marineam** [comment]
The network is dynamic, there isn't a "depend on the network". `network.target` means networkd has started but doesn't mean links are up. `network-online.target` means at least one link up and configured but may not mean it is the one that etcd may be configured to listen on.

Is etcd failing on `bind(2)` because it is listening on specific addresses rather than global? Maybe etcd should optionally use `IP_FREEBIND` to tolerate out-of-order startup.

**Comment by crawford** [comment]
Right, depending on `network.target` doesn't ensure the network is up (though, `network-online.target` doesn't really do that either), but it does ensure that the network is queued to be configured. I'm sure this isn't what @polarina had in mind (we'll need to use socket opts to fix the issues with etcd), but as a matter of correctness, I think etcd should depend on the network. The only case where that isn't true is when it is just being run locally.

**Comment by marineam** [comment]
Ok, yeah. Adding a `Wants=network.target` is good for explicitness and may be important if trying to use etcd2.service in a minimal systemd based container. It just doesn't fix anything in a normal system which will always start networking :)

**Comment by xiang90** [comment]
What is the status of this? We have updated the example service file in etcd repo: https://github.com/coreos/etcd/blob/master/contrib/systemd/etcd.service#L4

**Comment by crawford** [comment]
I think everyone forgot about it. The change shouldn't have much of an effect (if any), so no one noticed. Pull requests are welcome.

**Comment by crawford** [comment]
@xiang90 your example etcd service unit doesn't activate the network target, so the After clause isn't guaranteed to have any effect. Additionally, running after the network target has been realized doesn't buy you much. The network isn't necessarily up.
