### ISSUE TITLE
Can't get ignition to work using OEM drive with PXE

### ISSUE THREAD

**Issue by medlefsen** [coreos/bugs#986]
I'm using 835.4.0 with pxeboot and don't want to depend on HTTP for ignition.json but I can't get the oem:// scheme to work.
Looking at the ignition code it appears to support two ways of handling the oem:// scheme:

Looking at /sysroot/usr/share/oem and mounting /dev/disk/by-label/OEM

but neither appear to work. Even if my root disk has a /usr/share/oem, because the squashfs image is mounted on /sysroot/usr, ignition can't find the config.

The mount option fails because ignition attempts to mount the device to /mnt/oem, but that directory does not exist and ignition does not seem to try and create it first, so the mount always fails.

The mount issue seems like an easy fix (add a mkdir or just mount to a different existing directory)

**Comment by crawford** [comment]
Can you share your `coreos.config.url` option and the Ignition logs (`journalctl -t ignition --no-pager`)?

**Comment by crawford** [comment]
This was broken by https://github.com/coreos/coreos-overlay/pull/1592. There used to be a mount unit which created /mnt/oem. Now that it's gone, the mount fails.

**Comment by medlefsen** [comment]
Makes sense. If you still need it:

coreos.config.url=oem:///ignition.json

[ignition.log.txt](https://github.com/coreos/bugs/files/36148/ignition.log.txt)

**Comment by crawford** [comment]
Do you have the details around the failed attempt to use the config in the SquashFS?

**Comment by medlefsen** [comment]
I think I misunderstood how the oem directory is used for PXE. I read the documentation [here](https://coreos.com/ignition/docs/0.2.2/supported-platforms.html) as suggesting that the config can be placed in /usr/share/oem on the root drive for PXE, but looking at the PXE docs I see that you're supposed to edit squashfs image in the initramfs for the oem drive.

**Comment by vcaputo** [comment]
@medlefsen In handling oem:// schemes, Ignition will first attempt the path under the root drive, if that fails it will then attempt to mount the oem partition and look in there:
https://github.com/coreos/ignition/blob/master/src/providers/cmdline/cmdline.go#L178

**Comment by medlefsen** [comment]
@vcaputo it checks /sysroot/usr/share/oem which is not the root drive. In the initramfs shell /sysroot/usr is a loopback squashfs device backed by /usr.squashfs.

I think there may be a bug here but I'm not certain. The [pxe docs](https://coreos.com/os/docs/latest/booting-with-pxe.html) say I should be able to add oem config to the initramfs by editing the cpio, but based on those instructions I would think that would show up in the initramfs as /usr/share/oem, not /sysroot/usr/share/oem, which is where ignition checks for it's config.

**Comment by medlefsen** [comment]
I should say, I directly tested putting ignition.json in /usr/share/oem on the root disk (as specified by the root= kernel flag) and it did not find it. Within the initramfs shell I could see that /sysroot was mounted correctly, but /sysroot/usr/share/oem was empty, due to the issue I described.

**Comment by vcaputo** [comment]
You're correct, we'll have to fix this.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/ignition/pull/150 and https://github.com/coreos/ignition/pull/151.
