### ISSUE TITLE
overlayfs issues?

### ISSUE THREAD

**Issue by minurc** [coreos/bugs#989]
Hi all,

I don't know whether this is overlayfs issue or not, but i did not experience this until now. Previous CoreOS installation had and still has btrfs rootfs and as docker backend.

Both issues I encountered so far are inside container:
1) tail -f does not work properly, meaning if watched file is updated there is no output on tail
2) deletion of file has strange behaviour. Namely:

```
root@monitornig:/opt/supervisor# ls -al
ls: cannot access mysql_supervisor: No such file or directory
total 16
drwxr-xr-x 2 root root 4096 Nov 19 12:35 .
drwxr-xr-x 1 root root 4096 Nov 19 12:34 ..
-rw-r--r-- 1 root root  384 Sep 16 14:45 apache2_supervisor
-rw-r--r-- 1 root root  382 Sep 16 14:45 icinga2_supervisor
c????????? ? ?    ?       ?            ? mysql_supervisor
```

 This actually leads to bigger problem, that container complains when trying to remove one using _docker rm_ and STATUS of container is _Dead_

I really hoped to go into production with this :(
### Host info

```
core@mon ~ $ uname -a
Linux mon 4.1.7-coreos-r1 #2 SMP Thu Nov 5 02:10:23 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5620 @ 2.40GHz GenuineIntel GNU/Linux

core@mon ~ $ cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=766.5.0
VERSION_ID=766.5.0
BUILD_ID=
PRETTY_NAME="CoreOS 766.5.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

core@mon ~ $ docker info
Containers: 2
Images: 86
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-coreos-r1
Operating System: CoreOS 766.5.0
CPUs: 1
Total Memory: 997.5 MiB
Name: mon
ID: Q2VN:DCJN:XVCP:JN5U:XP7B:BIKR:RING:EM6M:IK2L:63XV:KKUG:6C5O
```

**Comment by mischief** [comment]
@minurc both of these are overlayfs issues.

overlayfs does not support inotify - that's why tail doesn't work.
  - https://github.com/docker/docker/issues/11705

and for supervisord, there's a strange hardlink/unix socket issue.
  - https://github.com/docker/docker/issues/12080

there's some other known issues with overlayfs, some info has been gathered at https://docs.google.com/document/d/1-OHPHmH9S1fx1vb1Loq7RGlkRlpc7Pt-FJo_O02Y2ts/edit?usp=sharing

**Comment by crawford** [comment]
@minurc depending on your provider, you can use Ignition to [reformat the root fs](https://coreos.com/ignition/docs/latest/examples.html#reformat-the-root-filesystem) or use a [btrfs volume file](https://coreos.com/os/docs/latest/mounting-storage.html#creating-and-mounting-a-btrfs-volume-file).

**Comment by minurc** [comment]
@mischief i knew about a few issues which i found before asking for confirmation (inotify, fanotify, sockets), but not that much :) deletion was cup which made me think to abandon the road with CoreOS, but i like idea behind this concept very much so i try to survive until problem resolves

@crawford hmm... that's interesting, i'll try that. maybe there is a way to do it during installation. thanks.

Actually I don't use CoreOS as it is intended to be used (meaning clustered environment, which i don't need at the moment and don't have resources). Instead I do all in-house and trying to replace old-school servers with CoreOS instances. We'll see how that goes ;)

Managing it is a bit pain, since all orchestration/mgmt solutions require resources which usually are equivalent of all servers together. Haven't been using fleet so far, but if it can manage host instances separately, not as a cluster, that would be great.

thank you both.

**Comment by mischief** [comment]
@minurc if you use ignition you could use docker with btrfs instead of overlay - or take @crawford's suggestion of a loopback mounted btrfs file - but btrfs has its own problems. if you run into another issue which is not known, please file another bug.

**Comment by philips** [comment]
We need to figure out how to get the patch upstream or at least raise the issue upstream. There is an existing patch that someone put into the Docker issue. @mjg59 could you take a look at https://launchpadlibrarian.net/149319334/overlayfs_inotify.patch and poke upstream?

**Comment by mjg59** [comment]
I'm in contact with the patch author, I'll figure out what the long-term plan is here.

**Comment by crawford** [comment]
Bump

**Comment by mjg59** [comment]
Looks like this should be working as of 4.9 - it appears to be in local testing.

**Comment by crawford** [comment]
I'm going to go ahead and close this. We can reopen it if there is still an issue.
