### ISSUE TITLE
After a while, etcd consumes most memory and CPU due to constant re-elections

### ISSUE THREAD

**Issue by TJC** [coreos/bugs#99]
Seen on "CoreOS 367.1.0", running inside KVM-based virtual machines under Linux.

After running for "some time", etcd appears to get into some kind of tight loop, consuming 100% of a CPU all the time, and gradually increasing in memory usage. Eventually it will consume enough to start breaking other services on the machine.

Looking at the logs for etcd, it seems to be constantly electing new leaders due to heartbeat timeouts -- but I suspect this is a symptom of the memory exhaustion rather than the original cause.

**Comment by Rev1408** [comment]
I still see the issue in latest kubernetes

**Comment by euank** [comment]
@Rev1408 Please file a new issue with the details of the issue you're encountering (etcd version, memory usage, preferably heap snapshot after turning on `--enable-pprof` and dumping it).
