### ISSUE TITLE
Excessive logging causes process to block

### ISSUE THREAD

**Issue by spiffxp** [coreos/bugs#990]
We're using CoreOS as the host OS for our kubernetes cluster.  We're running into edge cases where the kubernetes scheduler process starts to log excessively, and then begins to periodically block. See kubernetes/kubernetes#14216.

While we're trying to make the process log less data, it doesn't seem like the volume of logging should cause it to block.

There is suspicion that `systemd-journald` is somehow causing the process to block while it flushes the journal to disk.  There is also suspicion that flushing to disk may be I/O limited since `/var/log/journal` is by default on the root volume of the AMI, which is not nearly as performant as ephemeral or EBS volumes.

I set `/etc/systemd/journald.conf` to the following by way of `cloud-init`
```
[Journal]
Storage=none
RateLimitBurst=0
RateLimitInterval=0s
SystemMaxUse=50M
RuntimeMaxUse=50M
```

When I ssh'ed in, `journalctl -f` still showed output, so I issued a `systemctl restart systemd-journald`.  No more output followed in `journalctl -f`.

The process was still getting blocked.

I edited the offending process' unit to include the following, then issued `systemctl daemon-reload; systemctl restart foo`
```
[Service]
StandardOutput=null
StandardError=null
```

The process was no longer getting blocked.

**Comment by spiffxp** [comment]
I left out that this is happening in AWS, using the CoreOS-alpha-845.0.0-hvm AMI, which comes with systemd 225

**Comment by spiffxp** [comment]
We're working around this by bypassing journald entirely, and logging directly to files instead

**Comment by crawford** [comment]
Does the scheduler log directly into journald or is it using stdout/stderr?

**Comment by spiffxp** [comment]
stderr, via the default setting of `StandardError=journal`

**Comment by vcaputo** [comment]
There are some issues with the current journald implementation, bypassing journald by either pointing the output to /dev/null or to syslog are the best options for log configuration in the unit file with chatty services.

**Comment by countspongebob** [comment]
@vcaputo "There are some issues with the current journald implementation"... could you elaborate?

**Comment by vcaputo** [comment]
systemd-journald is currently implemented as a simple single-process event loop, performing the journal writes via mmap().  By using mmap an quasi-asynchronous write cache is attained with a minimum of implementation complexity.  A problem with this approach, however, is that the journald process will block spuriously if the the mapped file accesses start blocking on page IO, becoming effectively a synchronous implementation with blocking IO.  While these delays are happening in the kernel, journald's unable to service its event loop, handle new log messages, respond to the watchdog, etc.

**Comment by crawford** [comment]
@spiffxp can you give me more specific numbers around the logging rate and machine? (e.g. log lines per minute, disk IOPS)

**Comment by spiffxp** [comment]
@crawford Unfortunately I can't give you hard numbers on log lines per minute, we're looking to instrument kubernetes' logging to better understand that behavior.  In the meantime I would suggest maybe writing a dummy program that spews data to stderr?  I couldn't make it happen within a bash loop, so something less interpreted may be necessary.

As far as disk IOPS goes, we saw this on AWS instances ranging from m3.xlarge to m4.4xlarge, using gp2 EBS volumes for root partition.  `/var/log/journal` lived on either the root partition, an additional gp2 EBS volume, or the instance's ephemeral drive:
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html

**Comment by vcaputo** [comment]
Just to update, I've been going down this rabbit hole and have found some potentially low-hanging fruit which we'll hopefully be able to pick in the near future.

After instrumenting sd-event to capture the distribution of latencies in running the journald event loop (https://github.com/vcaputo/systemd/commit/bef3983c0dd7e9cc8a7e0c77679793ad9089b5b4) I started taking some measurements and experimenting with some of the ideas I mentioned above.

Here's some of the data resulting from those experiments:
https://gist.github.com/vcaputo/0da93eb0ad364e83b214

The meaning of the numbers is self-evident if you look at the commit linked above, but here's a brief description:

The columns contain counts of latencies of increasing orders of magnitude.  At the far left, you have no delay between sd_event_run() calls, as you move right the delay is doubling per column, in units of microseconds.  So the 19th column is ~512k, a range of ~.5-1 second.  An "ideal" capture with fsync() disabled is included as an ideal goal/reference (for now, there are other sources of delays we need to address, but fsync() is by far the worst right now).  You can see clearly the high-order delays the synchronous fsyncs are causing.  The counts are printed and reset every 5 seconds, they are not cumulative.

The last experiment in the gist linked above shows promise, and I'm working with upstream to get that into a correct/mergable form.

**Comment by vcaputo** [comment]
Switching gears to a more CPU-bound/system-calls-per-message oriented assault has led to more substantial improvements we're working on getting upstream:
https://github.com/systemd/systemd/pull/2280

**Comment by vcaputo** [comment]
https://github.com/systemd/systemd/pull/2318 as well

**Comment by vcaputo** [comment]
and https://github.com/systemd/systemd/pull/2125

**Comment by mischief** [comment]
i believe this is fixed by coreos/coreos-overlay#1835. this change will be available in alpha soon. can you confirm @vcaputo?

**Comment by vcaputo** [comment]
@mischief this is certainly helped by those changes, but journald still uses more cpu per log line than it should.

**Comment by mischief** [comment]
@spiffxp can you try coreos alpha 991.0.0 and see if it alleviates the problem?

**Comment by spiffxp** [comment]
I'll see if I can give this a shot next week.  One slight hiccup is that docker 1.10.x still hasn't been fully validated for use with kubernetes.  Is there some way to backport docker 1.9.x onto that alpha if necessary?

**Comment by mischief** [comment]
feel free to download and use docker binaries if you need to, but the version of docker is not going to change in 991.0.0.

**Comment by binarybana** [comment]
@spiffxp FWIW We've been using CoreOS 983 with Kubernetes 1.2.0 and haven't had any problems yet with Docker 1.10.

**Comment by spiffxp** [comment]
@mischief fyi still actively working on this, lost some time to kubernetes 1.1.8 vs. kubernetes 1.2.0 flakes, I hope to be able to report back by end of week

**Comment by spiffxp** [comment]
@binarybana what size are your nodes, and does density-30 successfully schedule all pods?

**Comment by binarybana** [comment]
For master we generally are running m4.large for small clusters (1-5 nodes) and up to m4.2xlarge for larger clusters (~100). We have run into problems pushing 20-30k `Job`s onto the scheduler, but haven't narrowed down where the problems are coming from there.

How can I run density-30? I couldn't find it after a bit of googling, but if you point me in the right direction I can see what happens on this end.

**Comment by sukrit007** [comment]
Just ran into this with 
CoreOS: 835.12.0
channel: stable
Provider: EC2
Instance Size:  r3.large
Message Rate:  25000-26000 lines / 5 minutes

The behavior was:
- ssh stopped working
- fleet daemon stopped responding on the node to start / stop / destroy commands

**Comment by mischief** [comment]
@sukrit007 update your system to the latest stable and try again.

**Comment by spiffxp** [comment]
@binarybana I'm currently running density test as follows.  The
```
gsutil -m cp gs://kubernetes-release/release/v1.2.0/kubernetes{,-test}.tar.gz .
tar xzf kubernetes.tar.gz
tar xzf kubernetes-test.tar.gz
cd kubernetes
# Set `KUBERNETES_CONFORMANCE_TEST=y` to avoid setting up a cloud provider
KUBECONFIG=path/to/kubeconfig KUBERNETES_CONFORMANCE_TEST="y" go run hack/e2e.go --v --test --test_args="--ginkgo.focus=Density.*30 --ginkgo.v=true" --check_version_skew=false
```

- kubernetes cluster stood up using https://github.com/samsung-ag/kraken
- m4.xlarge apiserver, master, etcd
- 100 m3.medium nodes
- cluster running kubernetes v1.1.8
- density test from kubernetes v1.2.0, run from my laptop
- all components logging to stderr with `--v=1` except scheduler, logging at the verbose `--v=4` level

coreos 991.0.0 on the left, coreos 1010.1.0 on the right
<img width="1440" alt="k8s-v118-vs-v120-density-30-coreos-991 0 0-vs-1010 1 0" src="https://cloud.githubusercontent.com/assets/49258/14435594/837741aa-ffcd-11e5-8ebe-b0629162ce7f.png">

@mischief I'll see if I can bisect further, but in short: systemd-journald performance seems better in this case, but not at the specific version of coreos you asked us to check

**Comment by spiffxp** [comment]
@mischief confirming 1000.0.0 behaves the same as 991.0.0... thus whatever is improving our performance seems to have first landed in 1010.1.0

**Comment by crawford** [comment]
It might be the resolution of https://github.com/coreos/bugs/issues/1162. You can test this by adding `systemd.journald.forward_to_console=yes` to your kernel command line to see if it slows down.

**Comment by spiffxp** [comment]
@crawford thanks, that looks promising

**Comment by sukrit007** [comment]
Thanks @crawford @mischief  
Looks like https://github.com/coreos/bugs/issues/1162#issuecomment-194223382 seems to have resolved the issue for blocked services and high cpu utilizations.

In addition, we also updated to 899.15.0 which helped a bit , but workaround posted in #1162 totally resolved our issue.  

Also thanks @kayrus for your quick workaround.

**Comment by spiffxp** [comment]
@crawford @mischief confirming that the workaround posted by @kayrus in https://github.com/coreos/bugs/issues/1162#issuecomment-194223382 + CoreOS 991.0.0 has eliminated the behavior in our case

**Comment by crawford** [comment]
@spiffxp glad to hear it. Can we close this out?

**Comment by spiffxp** [comment]
@crawford yes, ok to close this out

**Comment by rachid-nadir-red** [comment]
Limiting the MAX file size to 10MB solved my issue (SystemMaxFileSize).
By default the size is not set (I was getting 150MB+ files size), so other processes were blocked when the journald was sync-ing those big files (every 5 minutes, by default for journald).
Hope it will help ;-)

**Comment by mailinglists35** [comment]
I've recently hit this issue on a RHEL-based distribution (oracle linux 7.5 as a vm inside KVM) with an in-house app that has some spikes in logging. Because the app does not log with timestamps, I found it easy to capture it's stdout with a systemd service so I can also have nice timestamps.

But the systemd unit was configured to also log on console (StandardOutput=syslog+console), and the console was the default QXL video card emulated by qemu. I *think* the qxl driver cannot handle such bursts and this led to journald blocking then getting killed by systemd, and the app getting blocked

````
Jun  6 13:46:36 as1 kernel: INFO: task systemd-journal:553 blocked for more than 120 seconds.
Jun  6 13:46:36 as1 kernel:      Not tainted 4.1.12-112.16.7.el7uek.x86_64 #2
Jun  6 13:46:36 as1 kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jun  6 13:46:36 as1 kernel: systemd-journal D ffff88023e698140     0   553      1 0x00000004
Jun  6 13:46:36 as1 kernel: ffff8800bb21b768 0000000000000086 ffff8800bb21b7a8 ffff8802320ec600
Jun  6 13:46:36 as1 kernel: ffffc90000f5d00c ffff8800bb21c000 ffffc90000f5d00c ffff88023122fea0
Jun  6 13:46:36 as1 kernel: ffff8800bb21b820 0000000000000246 ffff8800bb21b788 ffffffff8174ab47
Jun  6 13:46:36 as1 kernel: Call Trace:
Jun  6 13:46:36 as1 kernel: [<ffffffff8174ab47>] schedule+0x37/0x90
Jun  6 13:46:36 as1 kernel: [<ffffffffa0332375>] qxl_ring_push+0x225/0x270 [qxl]
Jun  6 13:46:36 as1 kernel: [<ffffffff810d0280>] ? prepare_to_wait_event+0xf0/0xf0
Jun  6 13:46:36 as1 kernel: [<ffffffffa033242d>] qxl_push_command_ring_release+0x6d/0x90 [qxl]
Jun  6 13:46:36 as1 kernel: [<ffffffffa0334338>] qxl_draw_copyarea+0x108/0x120 [qxl]
Jun  6 13:46:36 as1 kernel: [<ffffffffa033018b>] qxl_fb_copyarea+0x8b/0x150 [qxl]
Jun  6 13:46:36 as1 kernel: [<ffffffff813bb5ec>] bit_bmove+0x6c/0x90
Jun  6 13:46:36 as1 kernel: [<ffffffff813b65bc>] fbcon_redraw_blit.isra.23+0x13c/0x1c0
Jun  6 13:46:36 as1 kernel: [<ffffffff813b9099>] fbcon_scroll+0x9e9/0xd70
Jun  6 13:46:36 as1 kernel: [<ffffffff81451b02>] scrup+0x172/0x180
Jun  6 13:46:36 as1 kernel: [<ffffffff81451bb0>] lf+0xa0/0xb0
Jun  6 13:46:36 as1 kernel: [<ffffffff81454da5>] do_con_trol+0xd5/0x16d0
Jun  6 13:46:36 as1 kernel: [<ffffffff814565cd>] do_con_write.part.23+0x22d/0xab0
Jun  6 13:46:36 as1 kernel: [<ffffffff810ab70a>] ? atomic_notifier_call_chain+0x1a/0x20
Jun  6 13:46:36 as1 kernel: [<ffffffff81456ef5>] con_write+0x65/0x70
Jun  6 13:46:36 as1 kernel: [<ffffffff8143dffa>] do_output_char+0x1aa/0x230
Jun  6 13:46:36 as1 kernel: [<ffffffff8143ecba>] n_tty_write+0x22a/0x4f0
Jun  6 13:46:36 as1 kernel: [<ffffffff810d00e0>] ? abort_exclusive_wait+0xb0/0xb0
Jun  6 13:46:36 as1 kernel: [<ffffffff8143aa6b>] tty_write+0x14b/0x2a0
Jun  6 13:46:36 as1 kernel: [<ffffffff8143ea90>] ? process_echoes+0x80/0x80
Jun  6 13:46:36 as1 kernel: [<ffffffff8143ac5d>] redirected_tty_write+0x9d/0xb0
Jun  6 13:46:36 as1 kernel: [<ffffffff8143abc0>] ? tty_write+0x2a0/0x2a0
Jun  6 13:46:36 as1 kernel: [<ffffffff81217e47>] do_loop_readv_writev+0x77/0xa0
Jun  6 13:46:36 as1 kernel: [<ffffffff81218e5a>] do_readv_writev+0x2ea/0x320
Jun  6 13:46:36 as1 kernel: [<ffffffff8122d033>] ? do_vfs_ioctl+0x323/0x530
Jun  6 13:46:36 as1 kernel: [<ffffffff81218f19>] vfs_writev+0x39/0x50
Jun  6 13:46:36 as1 kernel: [<ffffffff81219da9>] SyS_writev+0x59/0xf0
Jun  6 13:46:36 as1 kernel: [<ffffffff8174fe9f>] ? system_call_after_swapgs+0xe9/0x18c
Jun  6 13:46:36 as1 kernel: [<ffffffff8174fe98>] ? system_call_after_swapgs+0xe2/0x18c
Jun  6 13:46:36 as1 kernel: [<ffffffff8174ff5a>] system_call_fastpath+0x18/0xd4
````

writing this for few others who might run into a similar issue, as well as to easy find it again myself if I forget what I did, changing StandardOutput=syslog+console to StandardOutput=syslog (instead of changing default logging as suggested in https://github.com/coreos/bugs/issues/1162#issuecomment-194223382)
