### ISSUE TITLE
Ignition v0.2.3 fails waiting for OEM device

### ISSUE THREAD

**Issue by medlefsen** [coreos/bugs#991]
This commit:
https://github.com/coreos/ignition/commit/8142ce9f9795e37b2ffb422dfd1d365f1cab1109

causes ignition to fail waiting for the OEM device. The issue is that the unit name it produces starts with a dash (because it just replaces all slashes with dashes), but systemd device units shouldn't begin with a dash. So '/dev/disk/by-label/OEM'  is translated to '-dev-disk-by\x2dlabel-OEM.device', which doesn't work. It should be 'dev-disk-by\x2dlabel-OEM.device'

systemd then times out waiting for the device (because it doesn't exist).

Thanks

**Comment by crawford** [comment]
Closed by https://github.com/coreos/ignition/pull/153. This will make its way into 835.6.0.
