### ISSUE TITLE
Should coreos-metadata use provider-specific names?

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#993]
coreos-metadata is the small utility that can read metadata from various providers and dump that information into `/run/metadata/coreos`. This data is then sourced into services (via EnvironmentFile) and the variables are used in the various Exec statements.

On Amazon EC2, there is a local and public IP address (exposed by coreos-metadata as `COREOS_IPV4_LOCAL` and `COREOS_IPV4_PUBLIC`). On Microsoft Azure, there is a dynamic IP (assigned to the local interface), a virtual IP (the load balancer), and potentially a public IP. The question is: should these addresses be exposed using the same variables mentioned above or do we use very specific variable names (e.g. `COREOS_IPV4_DYNAMIC`, `COREOS_IPV4_VIRTUAL`, and `COREOS_IPV4_PUBLIC`)? The trade off here, of course, is explicitness for ease of use. When the names are the same, users can use the same configs between providers. The downside to using the same names is that it's not immediately obvious if `COREOS_IPV4_PUBLIC` corresponds to the virtual or public IP address on Azure. The even bigger downside to this particular example is that `COREOS_IPV4_PUBLIC` would almost certainly have to be the load balancer address because the public address is optional.

**Comment by robszumski** [comment]
The message of consistency is one that we keep coming back to. IMO it's important for at least the basic variables to work across providers. But I could see an additional set that are provider specific.

**Comment by crawford** [comment]
@robszumski so you are in favor of something like this:

```
COREOS_IPV4_LOCAL=1.1.1.1
COREOS_IPV4_PUBLIC=2.2.2.2
COREOS_AZURE_IPV4_DYNAMIC=1.1.1.1
COREOS_AZURE_IPV4_VIRTUAL=2.2.2.2
```

Where `COREOS_IPV4_LOCAL` and `COREOS_IPV4_PUBLIC` are always mapped to provider-specific names.

**Comment by brianredbeard** [comment]
One thought is to "choose your level of indirection".  Obviously we will know the options provided by the cloud service.  I think it becomes a "no brainer" to provide the provider specific options under some type of prefix (e.g. if you're on Azure you get `AZURE_IPV4_DYNAMIC`, on Amazon you get `AWS_IPV4_PUBLIC`, etc).  Those strike me as being easy to do and allow the users who want to go "all in" on a single cloud provider to go as deep as they want integration wise.

I think the bigger question becomes _how_ do we provide the level of consistency?  Do we allow the user to specify `COREOS_IPV4_PUBLIC=${AWS_IPV4_PUBLIC}` or `COREOS_IPV4_PUBLIC=${AZURE_IPV4_VIRTUAL}`?  Do we make assumptions on the users behalf?  I can see arguments for both on the side of how we map into the `COREOS_...` ones but I think doing the former is also important.

**Comment by robszumski** [comment]
@crawford Yes, exactly.

@brianredbeard thats not a bad idea either. If that was optional, it would only increase the complexity for the people that need it, and we can keep the existing functionality for the base use-case.

**Comment by crawford** [comment]
So, at the very least we need provider-specific names. Since it's always easier to add stuff rather than remove stuff, let's just go with the provider-specific names for now:

```
COREOS_AZURE_IPV4_DYNAMIC
COREOS_AZURE_IPV4_VIRTUAL
COREOS_AZURE_IPV4_PUBLIC
COREOS_EC2_IPV4_LOCAL
COREOS_EC2_IPV4_PUBLIC
```

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/coreos-metadata/pull/11.
