### ISSUE TITLE
coreos-setup-environment infinite loop when booting in Rackspace without ServiceNet

### ISSUE THREAD

**Issue by utahcon** [coreos/bugs#995]
Cloud Vendor: Rackspace Public Cloud

`/usr/share/oem/bin/coreos-setup-environment` (https://github.com/coreos/coreos-overlay/blob/master/coreos-base/oem-rackspace/files/coreos-setup-environment) creates an infinite loop when booting a Rackspace Public Cloud instance with ServiceNet disabled. 

```
#!/bin/bash -e

ENV=$1

if [ -z "$ENV" ]; then
        echo usage: $0 /etc/environment
        exit 1
fi
# test for rw
touch $ENV
if [ $? -ne 0 ]; then
        echo exiting, unable to modify: $ENV
        exit 1
fi

sed -i -e '/^COREOS_PUBLIC_IPV4=/d' \
    -e '/^COREOS_PRIVATE_IPV4=/d' \
    "${ENV}"

# We spin loop until the nova-agent sets up the ip addresses
function get_ip () {
        IF=$1
        IP=
        while [ 1 ]; do
                IP=$(ifconfig $IF | awk '/inet /{print $2}')
                if [ "$IP" != "" ]; then
                        break
                fi
                sleep .1
        done
        echo $IP
}

echo COREOS_PUBLIC_IPV4=$(get_ip eth0) >> $ENV
echo COREOS_PRIVATE_IPV4=$(get_ip eth1) >> $ENV
```

The loop is created when attempting to get the IP for eth1, but there is only a single interface (eth0) attached to the instance. This causes the setup to loop infinitely and not complete cloud config.

I am unsure how best to solve this (or I would have submitted a PR already), as I am not entirely sure of the process between nova-agent and coreos-setup-environment.

**Comment by marineam** [comment]
This script also fails to deal with instances with extra interfaces. Really it needs to go away and be replaced by a tool (or go library that cloudinit can use) that can read and parse rackspace's network configuration that is provided in xenstore.

**Comment by ChrisMcKenzie** [comment]
Has there been any progress on this??

**Comment by crawford** [comment]
No, sorry. We've been focused on other, higher priority tasks.

**Comment by ChrisMcKenzie** [comment]
bummer this makes deploying on rackspace not very fun. :(

**Comment by utahcon** [comment]
@ChrisMcKenzie I have this workaround in our code base -- hope it helps

https://gist.github.com/utahcon/4422cfe0daf4b136ca33
```
fabric_env.host_string = "root@{}".format(self.get_server_ip(server))

sudo("systemctl stop coreos-setup-environment && sed -i '/echo COREOS_PRIVATE_IPV4=$(get_ip eth1) >> $ENV/d' /usr/share/oem/bin/coreos-setup-environment && systemctl daemon-reload && systemctl start coreos-setup-environment")
```

**Comment by ChrisMcKenzie** [comment]
Thank that is essentially what i have been doing but it is less than ideal i think.

**Comment by crawford** [comment]
Rackspace is no longer an officially-supported platform. Any help on this is welcomed.

**Comment by bgilbert** [comment]
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

We're now working on [Fedora CoreOS](https://coreos.fedoraproject.org/), the successor to Container Linux, and we expect most major development to occur there instead. Meanwhile, Container Linux will be fully maintained into 2020 but won't see many new features. We appreciate your taking the time to report this issue and we're sorry that we won't be able to address it.
