### ISSUE TITLE
add some stuff

### ISSUE THREAD

**Issue by vtolstov** [coreos/bugs#996]
I'm use coreos-cloudinit in my own cloud and write some stuff like:
* resize root partition and fs (linux/freebsd)
* runcmd
* set hostname not only via hostnamectl
* lock/unlock user
* create user on freebsd/openbsd

Do you interesting in this features (i can create pr) or i need to maintain own fork for this stuff?

**Comment by mischief** [comment]
i'd be interested to see how you intend to make this work on OpenBSD, given that coreos-cloudinit is fairly linux-specific.

**Comment by crawford** [comment]
Are you using coreos-cloudinit outside of CoreOS Linux? Supporting other distros is outside of the scope of coreos-cloudinit, so we'd only be interested in features directly applicable to CoreOS.

> * resize root partition and fs (linux/freebsd)

CoreOS already does this.

> * runcmd

This might be interesting.

> * set hostname not only via hostnamectl

CoreOS uses systemd, so any other method is not needed.

> * lock/unlock user

If it works, neat.

> * create user on freebsd/openbsd

No thanks.

**Comment by vtolstov** [comment]
lock/unlock i'm create pr https://github.com/coreos/coreos-cloudinit/pull/407

**Comment by vtolstov** [comment]
in case of runcmd - i'm run this stuff via cloudinit binary. Does it sutable for mainline or you prefer to run via creating systemd services ?

**Comment by crawford** [comment]
It's preferable to create a transient service unit for each command.

**Comment by vtolstov** [comment]
@crawford ok, i think about it.
Another question - why coreos-cloudinit not create lockfile by itself? For example for runcmd commands needs to be run on each invocation of cloudinit, but not only once.

**Comment by crawford** [comment]
I don't follow. coreos-cloudinit runs on every boot on CoreOS and reevaluates the config every time. If we had support for `runcmd`, the commands would run every boot.

**Comment by vtolstov** [comment]
2015-11-26 3:13 GMT+03:00 Alex Crawford <notifications@github.com>:

> I don't follow. coreos-cloudinit runs on every boot on CoreOS and
> reevaluates the config every time. If we had support for runcmd, the
> commands would run every boot.
>

But if user change their password on server - does coreos-cloudinit reset
it?


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by crawford** [comment]
No, it has some special cases and only applies certain changes once. After thinking this over more, I'd rather not introduce any more complexity to coreos-cloudinit. We are migrating to Ignition in the future and will eventually (fingers crossed) kill off coreos-cloudinit. Thanks anyway.

**Comment by vtolstov** [comment]
2015-11-30 22:26 GMT+03:00 Alex Crawford <notifications@github.com>:

> No, it has some special cases and only applies certain changes once. After
> thinking this over more, I'd rather not introduce any more complexity to
> coreos-cloudinit. We are migrating to Ignition in the future and will
> eventually (fingers crossed) kill off coreos-cloudinit. Thanks anyway.


Ok.


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru
