### ISSUE TITLE
CoreOS vs NIC Drivers (Mellanox Solarflare etc.)

### ISSUE THREAD

**Issue by vanthome** [coreos/bugs#998]
Hi, 
I would like to give CoreOS a try but we  have a Mellanox infrastructure including the NICs. Now I read that it's kind of a deal to get this working as I need to compile stuff. I'm a Gentoo user myself so I don't have a problem with this but think it should be more easy for common setups.
Shouldn't common modules be just enabled in your Kernel?
If this is not the strategy, then I don't understand why you enabled the module for Solarflare NICs [1].

[1] https://github.com/coreos/bugs/issues/400

**Comment by crawford** [comment]
What drivers do you need enabled? (`lspci -nn`)

**Comment by vanthome** [comment]
From the mellanox MLX4 drivers [1] these tow: mlx4_core, mlx4_en.

[1] http://www.mellanox.com/related-docs/prod_software/MLNX_EN_Linux_README.txt

**Comment by mischief** [comment]
@vanthome both are enabled as modules in the CoreOS kernel.

**Comment by vanthome** [comment]
Wow, ok, cool, then I will give it a try again. I tried some moth ago and back then it wasn't.

**Comment by crawford** [comment]
@vanthome I'm going to close this issue. If you still have trouble, go ahead and re-open it.
