### ISSUE TITLE
ETCD2 is not using the $private_ipv4 and $public_ipv4 variables on vagrant setup

### ISSUE THREAD

**Issue by ArKam** [coreos/bugs#999]
Hi community, thanks to the amazing CoreOS IRC Channel, this is my second contribution on weird bug tracking!

I want to test some features of CoreOS using my own vagrant box, for future corporate demo, to do so, I use vagrant (obviously) but also packer and atlas.

Everything seems to be running smoothly, my builds are working, the vagrant box is starting correctly, I do obtain DHCP IPs and can log using vagrant ssh default insecure keys.

my problem come on the units that require to be aware of the private and public ips provided on the user_data cloud-config file and especially the ETCD2 unit.

It fail at launch due to the fact that Vagrant or Cloud-Config don't correctly populate the drop-in at start and then do wrote a file without any IPs. (20-cloud-init.conf) file:

https://gist.github.com/ArKam/8b6298a9ccd24635ec8c

Nothing seems to be broken according to my logs:
https://gist.github.com/ArKam/b71517f1a8ea80deac8d

However, I do have to set fixed IPs to have an etcd2 unit working fine.

If you need the Vagrantfile you can find it here:
https://gist.github.com/ArKam/fd0e507cea4d5f228929

the user_data file is here as well:
https://gist.github.com/ArKam/bac5d8fdb6c321889e4b

Let me know if you need something else :D

**Comment by crawford** [comment]
Can you provide the contents of `/etc/environment`? This is the file that coreos-cloudinit populates with the metadata it fetches.

**Comment by ArKam** [comment]
Unfortunatly I don't have any environment file created on /etc/ :-/

**Comment by crawford** [comment]
Hmmm, on Vagrant, the "vagrant::guest::coreos::configure_networks" module should populate that file. If it doesn't exist, something very fundamental is going wrong.

What version of Vagrant are you using? Which version of coreos-vagrant have you cloned?

**Comment by ArKam** [comment]
@crawford I use Vagrant 1.7.4 my CoreOS-Vagrant image is not cloned but build by myself using the generic CoreOS Stable iso as you can find out on the metadata.json file, I build my own vagrant box for complete platform tests.

**Comment by crawford** [comment]
Can you try this against our coreos-vagrant repo?

**Comment by ArKam** [comment]
Ok, so, using the coreos-vagrant repo is producing quite the same result as ETCD2 is running exclusively on 127.0.0.1 and not at all using the private_ip or even the public_ip.

For reproducible purposes: just add my linked user_data instead of the sample provided, ask for 1 instance, and change the virtualbox network config from the static ip to this:

config.vm.network :private_network, type: "dhcp"

And voila :D if you need further tests/informations, do not hesitate.

**Comment by crawford** [comment]
As we determined over IRC, setting the network to "dhcp" was the culprit. coreos-cloudinit depends on Vagrant providing these addresses which it cannot do if DHCP is used.

**Comment by ArKam** [comment]
Ok, no problems, I found out that a Vagrant plugin "seems" to provide provisionning on CoreOS but indeed, this plugin is 2 yrs old and do not take in charge ETCD2 and try to launch ETCD1 so I drop it out at the same time that the DHCP idea ;-) thanks a lot for your time anyway.
